### ISSUE TITLE
HostingEngine.Start returns IDisposable. Usage patterns around IDisposable return values should be documented.

### ISSUE THREAD

**Issue by muratg** [aspnet/Docs#1]

**Comment by Rick-Anderson** [comment]
@Erikre can you find the right owner for HostingEngine.Start returns IDisposable.

**Comment by danroth27** [comment]
@muratg Is this doc issue still relevant? It sounds like this is a request for generic documentation on handling of IDisposable, but that's already covered in various places in the [.NET docs](https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx).
