### ISSUE TITLE
.net core 1.1 upgrade to .net core 2.2

### ISSUE THREAD

**Issue by serenitysky** [aspnet/Docs#10009]
**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
- Tell us what docs you found that didn't address your concern.

**Describe the new topic**

- Explain why this topic is needed.
- Suggest a location in the Table of Contents.
- Write an abstract. In one **short** paragraph, describe what this topic will cover.
- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.
My project is used .net core 1.1 now.
If i want to upgrade the project to .net core 2.2. it means that i should first upgrade to 2.0,and then to 2.1 and then to 2.2?
Because i only find the doc about 1.X to 2.0.
Please help.

**Comment by guardrex** [comment]
Hello @serenitysky ... Yes, that's correct when following the migration topics. We don't have a topic that goes from 1.1 directly to 2.2. We incrementally produce these migration topics as each minor release comes out.

I'm going to close this as answered, but we can re-open it if you wish to discuss further. Thanks for commenting.
