### ISSUE TITLE
There doesn't appear to be an IISServerOptions class

### ISSUE THREAD

**Issue by mrbelk** [aspnet/Docs#10013]
but there _is_ an "IISOptions" class in the microsoft.aspnetcore.builder namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrbelk ... I take it you're referring to the API Browser? If so, they're working on an issue with that right now. I don't have an ETA on when it will be available via that site; however, you can see the reference source here ...

https://github.com/aspnet/AspNetCore/blob/2.2.0/src/IISIntegration/src/Microsoft.AspNetCore.Server.IIS/IISServerOptions.cs

I'm going to close as answered, but we can re-open if we need to discuss further. Thanks for commenting.
