### ISSUE TITLE
First MVC App - Adding View - footer title change not in instructions

### ISSUE THREAD

**Issue by SQLEmil** [aspnet/Docs#10018]
The instructions for changing the layout code to change the application title only includes altering the metadata and the header tag, not the footer. However, the samples shown (both code and screenshot) show the title in the footer having also been altered. This should either be added to the instructions or removed from the samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The footer 2019 will change to 2019 in a couple weeks. I made the change now so I wouldn't forget.

**Comment by SQLEmil** [comment]
Hi Rick - the year change is good but didn't address the substance of the issue. The PR I just submitted (linked above) makes the change. Thanks!
