### ISSUE TITLE
What is the way to log-out after ws-federation login?

### ISSUE THREAD

**Issue by oleksandr-bilyk** [aspnet/Docs#10012]
Please, provide sample how to log out after WS-Federation login. ASP.NET Core API was changed  after last samples were on .NET Framework ASP.NET

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@chlowell can you answer this?

**Comment by chlowell** [comment]
The WS-Fed middleware is an authentication handler like any other, so nothing special is required. If you're using Identity, you can sign users out with `SignInManager<TUser>.SignOutAsync()`. If you're not using Identity, you can sign users out with the `HttpContext.SignOutAsync()` extension, as used in the  [sample app](https://github.com/aspnet/AspNetCore/blob/master/src/Security/Authentication/WsFederation/samples/WsFedSample/Startup.cs#L61).

**Comment by oleksandr-bilyk** [comment]
Thanks.
