### ISSUE TITLE
The Box Examine the context registered with dependency injection is emtpy for Visual Studio Code and Visual Studio Mac

### ISSUE THREAD

**Issue by mmattes** [aspnet/Docs#10019]
Got confused as i received errors but that was because the box Examine the context registered with dependency injection is only having content on the Visual Studio Tab and not the Visual Studio Code and Visual Studio Mac Tab. This part can in my opinion just be copied across to the other tabs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's because in VS it's generated and I want you to examine it. In VSC and VSmac, I had you create it earlier.

**Comment by Rick-Anderson** [comment]
And the context is different
`        options.UseSqlite(Configuration.GetConnectionString("MovieContext")));`

VS SQl Server
