### ISSUE TITLE
400 "The input was not valid." on POST request

### ISSUE THREAD

**Issue by royshouvik** [aspnet/Docs#10025]
Payload
```
{
  "name":"walk dog",
  "isComplete":true
}
```
TodoController.cs

```
...

        [HttpPost]
        public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; Store(TodoItem todoItem)
        {
            _context.TodoItems.Add(todoItem);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetTodoItem", new { id = todoItem.Id }, todoItem);
        }
...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you debug to find out what you did wrong?

**Comment by Rick-Anderson** [comment]
If you get a 405 Method Not Allowed error, it's probably the result of not compiling the project after adding the after adding the PostTodoItem method.

**Comment by royshouvik** [comment]
Found the issue. It's important to have `Content-Type` header set to `application/json` in Postman.
