### ISSUE TITLE
API controller failed to call another controller via ASP.NET Core API

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#10022]
I have a problem getting an API controller to call another API controller within the same project. 

Specifically, the integration project is able to call a controller in the production project, and the controller will make another call to a dummy controller within the same project, but the first controller failed with internal server error. 

However, the first controller can call google.com.

Please note that it works when the production project is hosted via either console or windows services. It only happens when tests in integration project run.

The production project is an ASP.NET CORE Web API project v2.1, and the integration test project, v2.1 via xUnit by following below

https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2

Integration project with xUnit below:

    public class RetryPolicyTests: IClassFixture&lt;WebApplicationFactory&lt;Startup&gt;&gt;
        {
            private readonly WebApplicationFactory&lt;Startup&gt; _factory;
    
            public RetryPolicyTests(WebApplicationFactory&lt;Startup&gt; factory)
            {
                _factory = factory;
            }
    
            [Theory]
            [InlineData("http://localhost:1234/api/v1/Book/")]        
            public async Task Test(string url)
            {
                // Arrange
                var client = _factory.CreateClient();
    
                // Act           
    
                var body = "{}";
                using (var content = new StringContent(body, Encoding.UTF8, "application/json"))
                {
    			
                    var response = await client.PostAsync(url, content);
    
                    // Assert
                    response.EnsureSuccessStatusCode(); //Failed here with internal server error
                    Assert.Equal(StatusCodes.Status200OK,
                        (int) (response.StatusCode));
                }
            }
        }

	

BookController		

      [ApiVersion("1")]
        [Route("api/v{version:apiVersion}/[controller]")]
        [ApiController]
        public class BookController : ControllerBase
        {
            private readonly ILog _logger;
            private readonly IConfiguration _configuration;
            private IHttpClientFactory _httpClientFactory;
    
            public BookController(ILog logger , IConfiguration configuration, IHttpClientFactory httpClientFactory)
            {
                _logger = logger;            
                _configuration = configuration;
                _httpClientFactory = httpClientFactory;
            }
    
    
            [HttpPost]
            public async Task&lt;ActionResult&gt; Post()
            {           
                using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
                {
                    string body = reader.ReadToEnd();
    
                    var url = "http://localhost:1234/api/v1/Author/"
                    using (var content = new StringContent(body, Encoding.UTF8, "application/json"))
                    {                    
                        var _httpClient = _httpClientFactory.CreateClient();
                        var s = _httpClient.GetAsync("http://google.com").Result;  //works here
    					
                        var response = await _httpClient.PostAsync(url, content);   //internal server error
                         var statusCode = response.StatusCode;
                        return StatusCode((int)statusCode);
                    }
                
                }      
            }
    
        }

AuthorController 

	
	 [ApiVersion("1")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]        
    public class AuthorController : ControllerBase
    {
        ILog _logger;

        public AuthorController(ILog logger)
        {
            _logger = logger;
        }

        [HttpPost]
        public void Post()
        {
            using (StreamReader reader = new StreamReader(Request.Body, Encoding.UTF8))
            {
                var body = reader.ReadToEnd();

            }

    }
	
It works if integration test hits directly at Author controller.

Error:

    Result StackTrace:	
    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
       at IntegrationTests.xUnit.RetryPolicy.RetryPolicyTests.Test(String url) in C:\IntegrationTests.xUnit\RetryPolicy\RetryPolicyTests.cs:line 46
    --- End of stack trace from previous location where exception was thrown ---
    Result Message:	System.Net.Http.HttpRequestException : Response status code does not indicate success: 500 (Internal Server Error).

Please note that after integration test hits the first controller and before hits the second controller, I tried to send the same data to the first controller via external tools, like Postman, or fiddler. But all controllers are not available to external tool, unlike if it is hosted on console or Windows service (In this case, all controllors can process requests).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @PingPongSet ... That's a great question. Open an issue at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues). We can't help with that here given that we only work on documentation content issues on this repo. The engineers over there should be able to assist. Note that the main engineer who works on testing might be away for the holidays, so you might not get help until the new year.

Let's leave this issue open. When you open an issue over there, cross-reference to this issue at the bottom ...

```
Cross-reference: https://github.com/aspnet/Docs/issues/10022
```

I'll keep an :eye: on this until you get an answer. If we need to make doc updates based on this, we'll take care of it after you find out what's going on with the app/tests.

**Comment by PingPongSet** [comment]
Thanks. I will open an issue like what you said.

**Comment by PingPongSet** [comment]
Cross-reference: https://github.com/aspnet/AspNetCore/issues/5132
