### ISSUE TITLE
Publish to Azure doesn't work for this version.

### ISSUE THREAD

**Issue by Ligren** [aspnet/Docs#10026]
Got this message:
"The page cannot be displayed because an internal server error has occurred."

when added
"&lt;httpErrors errorMode="Detailed"&gt;&lt;/httpErrors&gt;" 
in web.config into "&lt;system.webServer&gt;" tag got this:
"Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list"

For more details and solution, see this:
https://github.com/dotnet/core/issues/2125

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Correct, thanks
see https://github.com/dotnet/core/issues/2120#issuecomment-446693531
