### ISSUE TITLE
I found the entire process difficult to understand

### ISSUE THREAD

**Issue by erangross** [aspnet/Docs#10020]
I am reading the process of creating a website from the start.
I find the documentation challenging, I still cannot connect all the dots meaning all the moving parts of this project.
From my end, it seems quite difficult to understand it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by erangross** [comment]
I wanted to add additional remarks.
What I would like to see.
I would like to see a document that explains from the ground up how to create ASP core up project, starting from scratch, there are so many moving parts when you create the project from the template it is very hard for beginners to connect all the dots and by that I mean to truly understand every method in every source file and every tag in every cshtml file.
I mean I can follow the instructions to the letter and the project will work, but I want to be able to create such project from scratch and really understand where to put each method where to put each tag etc..
I hope I explained my self the right way.
Thanks
Eran

**Comment by Rick-Anderson** [comment]
@erangross 	I agree that's a good idea, create a project without the templates (AKA, from scratch). It might be good to compare with the template generated project.

cc @tdykstra 	- more evidence we need at least links to explain all the magic.

**Comment by pmossel** [comment]
I found it useful to click often on the hyperlinks in the Razor Pages and MVC tutorials to read about, for instance, DataAnnotations, tag helpers and lambda expressions.  When coding in "classic" ASP .NET, I frequently referenced the two-volume classic Esposito book. Compared to ASP .NET, ASP .Net Core with Razor is more logical, much simpler and requires less typing. Yes, it will take a bit of re-reading and digging deeper to get familiar with MVC, Razor, and ASP .NET Core, but it is a journey well worth the effort. The excellent video tutorials on this topic are still on MVA, but they refer to an older version of ASP .NET Core and VS, and MVA will gradually be phased out.

**Comment by cbeamond** [comment]
I too have found this difficult to understand. Thankfully, following the advice here has been a big help. Do the "next tutorial" as it goes into far more depth about how all of this works and is also very, very helpful.

Next tutorial: https://docs.microsoft.com/en-au/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
We can't explain everything in this doc. The best advice is to work through this tutorial, then start drilling down on the details you need.
