### ISSUE TITLE
Custom ChangeTokens and Expand delayed/duplicate token handling approach

### ISSUE THREAD

**Issue by philip-reed** [aspnet/Docs#10032]
Hi, 

Each of the examples here talk about hooking into existing ChangeTokens to watch for changes.
What if I want to trigger my own change? Lets say I am using SqlNotifications to and want to trigger a config reload from the OnChange event of the SqlDependency?  What do I need to do to implement IChangeToken?  What is the difference between ChangeTokens and simple Events + Handlers?

Trying to reverse engineer the FileConfigurationProvider and the ChangeToken is the only part I don't understand:
https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs

Thanks,
Phil

@Rick-Anderson 	edit: PV 1.2 K
See also  #9785 and make sure that is addressed in the next doc sweep.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9310e951-5185-4c31-064d-3a151acc17cf
* Version Independent ID: 42bc4b7b-2a1c-0248-2740-0decdda6000c
* Content: [Detect changes with change tokens in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/change-tokens.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/change-tokens.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @philip-reed ... Thanks for commenting.

pinging @Tratcher and @HaoK for remarks and/or permission to schedule this.

**Comment by Tratcher** [comment]
Sure, wouldn't hurt. The biggest difference between a toke and an event is that change tokens are single use, every time it fires you have to ask for a new one to continue being notified.

**Comment by philip-reed** [comment]
@Tratcher Thanks for the info, I didn't know that, and I don't think it is mentioned in the documentation either.

@guardrex You may not remember it, but this is progress from: [https://github.com/aspnet/Docs/issues/9681](url) 


I have created a Gist of the code I have so far:
[https://gist.github.com/philip-reed/502ea5a24d668bdf4d62c57fc191ddf1](url)
(sorry, couldnt figure out how to embed it)

In the BaseDbConfigurationProvider.cs
( [https://gist.github.com/philip-reed/502ea5a24d668bdf4d62c57fc191ddf1#file-basedbconfigurationprovider-cs](url) )

I use:
`ChangeToken.OnChange(
                    () => Source.DbProvider.Watch(),
                    () => {
                        Thread.Sleep(Source.ReloadDelay);
                        Load(reload: true);
                    });`

And in SqlDbConfigurationProvider.cs
( [https://gist.github.com/philip-reed/502ea5a24d668bdf4d62c57fc191ddf1#file-sqldbconfigurationprovider-cs](url) ) I create a new ChangeToken ( DbConfigurationReloadToken.cs ) in the handler for the SqlNotification

Just not sure how these two things are supposed to hang together.
So I had a got at using an event instead which seems to work but feels like cheating.

Also, 
Do I need to worry about this memory leak issue?
[https://github.com/aspnet/AspNetCore/issues/3110](url)

**Comment by guardrex** [comment]
> ask for a new one to continue being notified

I'll patch the topic with a line to cover it today.

btw - To embed links, link text in brackets, and URL in parentheses ... like this :point_down:

```
[My Gist](https://gist.github.com/philip-reed/502ea5a24d668bdf4d62c57fc191ddf1)
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
