### ISSUE TITLE
Browser Link Daskboard in VS alwalys links to ASP.NET Framework version.

### ISSUE THREAD

**Issue by PixelEditor** [aspnet/Docs#10034]
The Browser Link Daskboard "Learn more about browser link" always takes you to the ASP.NET Framework version of the documentation so it's not clear on first viewing that it can also be used in ASP.NET Core projects.

Suggestions: 

1. Quick win; add a link to the current ASP.NET Framework Browser Link page to the ASP.NET Core Browser Link page. Helps users coming via VS to find the right docs for their project/.NET version. 

2. Update the Browser Link Dashboard in VS to the offer links per ASP.NET version to the user. This also implies is can be used in the both Core and Framework project types.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1fa9-004b-0be3-6148-e8c075e5b2bc
* Version Independent ID: 78a1947e-dea7-65b4-2376-05c7795e4bf9
* Content: [Browser Link in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/client-side/using-browserlink?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/client-side/using-browserlink.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-browserlink.md)
* Product: **aspnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
Thanks for pointing this out, @PixelEditor. I've started a discussion with the team to determine how to address this problem.

**Comment by scottaddie** [comment]
The decision was made to adopt the "Quick win" approach identified in the issue description. This change is live now. Thank you for reporting it!
