### ISSUE TITLE
Explanation recommendation

### ISSUE THREAD

**Issue by ferronsw** [aspnet/Docs#10030]
"For production use, a Redis backplane is recommended only for on-premises infrastructure. To minimize latency, the Redis server should be in the same data center as the SignalR app. If your SignalR app is running in the Azure cloud, we recommend Azure SignalR Service instead of a Redis backplane. You can use the Azure Redis Cache Service for development and test environments."

What is the argumentation for this statement? For example if I run my app with SignalR on AKS and use self deployed Redis Cache pods for distributed cache and SignalR. Why would this not be recommended according to this statement? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@bradygaster 	please respond.

**Comment by ferronsw** [comment]
Thank you for the response. If both my WebApp and Redis resources are placed in West Europe for example, latency wouldn't be a problem? I'm in no need for resources to be placed over multiple data-centers, so only Redis would be sufficient for me.

**Comment by tdykstra** [comment]
On the advantages that Azure SignalR Service provides compared to Redis, see the list in [ASP.NET Core SignalR hosting and scaling - Azure SignalR Service](https://docs.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-2.1#azure-signalr-service).  A Redis backplane is feasible in your scenario but it will be harder to make sure that the web servers don't run out of connection resources.

@bradygaster - please comment if there are any other considerations I'm missing.

**Comment by bradygaster** [comment]
If you are running in Azure, our *strong* recommendation is that you use the Azure SignalR Service for scaling out your SignalR connections. It's the best option for Azure-hosted apps.
