### ISSUE TITLE
Next button shows the same page content

### ISSUE THREAD

**Issue by elmawardy** [aspnet/Docs#10052]
Next/Previous button shows the same page content I believe it's a bug , thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [ASP.NET Core MVC with EF Core - Migrations - 4 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Read the page and check the URL. That version is not supported.

**Comment by elmawardy** [comment]
Thanks
