### ISSUE TITLE
windows server 2012R2安装.net core 2.2发生aspnetcorev2.dll 未能加载。返回的数据为错误信息

### ISSUE THREAD

**Issue by tightnessxgy** [aspnet/Docs#10071]
一部分windows server2012R2安装aspnetcoreV2模块iis启动是可以加载的，但是有一小部分是加载失败的，返回错误信息。但是aspnetcore的dll iis加载dll是成功的

**Comment by guardrex** [comment]
Hello @tightnessxgy ...

> Some windows server2012R2 install aspnetcoreV2 module iis startup can be loaded, but a small part is loaded failure, return error message. But aspnetcore dll iis load dll is successful

What error message?
