### ISSUE TITLE
aspnet-WebApp1 database doesn't exist on my local database.  

### ISSUE THREAD

**Issue by BrettPrime** [aspnet/Docs#10076]
Should we have built aspnet-WebApp1 database with earlier code?  Are there instructions for setting this up?  Your instructions jump right into it assuming its already there.
Right now my appsetting.json has

  "ConnectionStrings": {
    "DefaultConnection": "DataSource=app.db"
  },

and app.db is a generated file on the root

**Comment by guardrex** [comment]
Hello @BrettPrime ... Would you mind re-opening this issue from the **Content feedback** button at the bottom of the topic that you're referring to? It will tag your issue with info from the topic that helps us track the issue.

**Comment by BrettPrime** [comment]
Hi Luke

I can’t find that option except to reply to one of the already existing issues

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio

[cid:image002.jpg@01D49874.BBE9D880]

**Comment by guardrex** [comment]
Ok ... that's cool. It **_should have been_** at the bottom of the topic. :smile: There might be some platform/browser-specific requirement for that button and form to show up.

**Comment by Rick-Anderson** [comment]
When you create a Web app with authentication, the templates create all the code to create the DB.

**Comment by BrettPrime** [comment]
I got it to work by creating it in .Net core 2.0.  2.1 did not work.
