### ISSUE TITLE
Impact of Google+ API deprecation on this flow?

### ISSUE THREAD

**Issue by darrenmart** [aspnet/Docs#10079]
With the Google+ APIs set to shut down on March 7, 2019, I'm unclear on what changes are needed for this .NET Core flow to continue authenticating Google users. There are several Google dev docs/samples but I'm hoping to avoid a separate flow for Google versus Facebook and Microsoft Account. Any guidance on where to start?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@haok please respond.

**Comment by HaoK** [comment]
@Tratcher any ideas if we are going to be impacted by g+ going away?  I imagine maybe the setting might get renamed only?

**Comment by pnishman** [comment]
Yes, I too am concerned about this as I have multiple active users using google sign in on Azure app service and in MVC applications. this is the notice I received. Need to migrate to Google sign in from Google plus. The server communication is a black box to me. Need to have microsoft update dll i think it is Microsoft.Owin.Security.Google

 If you see calls to people.get, these can be the result of using the Google+ Sign-In feature in your application, which is now fully deprecated and is being shut down. Developers should migrate from the Google+ Sign-In feature to the more comprehensive Google Sign-in authentication system.

Project	Google+ API Name	Version	Method
Wearable Coach (wearable-coach)	plus	v1	plus.people.get

**Comment by Tratcher** [comment]
See https://github.com/aspnet/AspNetKatana/issues/251#issuecomment-449587635 for Microsoft.Owin.

**Comment by Tratcher** [comment]
@Rick-Anderson doc updates needed for aspnetcore/security/authentication/social/google-logins.md:
- This affects all versions of the doc & framework.
- Link to the breaking change announcement: https://github.com/aspnet/AspNetCore/issues/6486
- Remove the three mentions and screen shots showing Google+ setup. No replacement is needed until it gets to "Add credentials to your project". The replacement screen shots would show Credentials, Create credentials, OAuth client ID, Web application

This is time sensitive, can you get it updated by Jan 28th?
