### ISSUE TITLE
Microsoft.AspNetCore.Razor.Design - Overide

### ISSUE THREAD

**Issue by twcarnahan** [aspnet/Docs#10086]
So, with this library, the AzureAD is the Area and it has a controller with Signin and SignOut; how do we get to use post_logout_redirect_URI to work - we have to Overide the RCL? Ultimately, we need to redirect after the Signout finishes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What do you mean by Area?

**Comment by twcarnahan** [comment]
`namespace Microsoft.AspNetCore.Authentication.AzureAD.UI.AzureAD.Controllers.Internal
{
    [AllowAnonymous]
    [Area("AzureAD")]
    [NonController]
    [Route("[area]/[controller]/[action]")]
    internal class AccountController : Controller`

**Comment by twcarnahan** [comment]
'services.AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options =>
                {
                    Configuration.Bind("AzureAd", options);
                    
                });'
From Startup.cs

**Comment by twcarnahan** [comment]
The below code solved my problem. 
`services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
    options.Authority = options.Authority + "/v2.0/";

    options.TokenValidationParameters.ValidateIssuer = false;

    options.Events.OnSignedOutCallbackRedirect = (context) =>
    {

        context.Response.Redirect("/Home/About");
        context.HandleResponse();

        return Task.CompletedTask;
    };
});`

**Comment by Rick-Anderson** [comment]
@twcarnahan 	thanks for posting your fix. It will probably help someone else.

I edited your code above (added ```) Triple tick code formatting. Can you confirm it's correct?

**Comment by twcarnahan** [comment]
@Rick-Anderson - Yes, it's correct.

**Comment by Rick-Anderson** [comment]
@pranavkm is this something we should document?

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by pranavkm** [comment]
There's a way to Scaffold the UI libraries that ASP.NET Core ships. @javiercn could you confirm it works for the AzureAD UI package too?

**Comment by javiercn** [comment]
Not sure what the question is about. If you don't want to use /Accounts/SignedOut (I think that was the page) you can set the url on the oidc options to whatever you prefer.

**Comment by javiercn** [comment]
> services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options => { options.Authority = options.Authority + "/v2.0/"; options.TokenValidationParameters.ValidateIssuer = false; options.Events.OnSignedOutCallbackRedirect = (context) => { context.Response.Redirect("/Home/About"); context.HandleResponse(); return Task.CompletedTask; }; });

This is the best way to achieve it. As an alternative, the entire controller can be taken out from the list of controllers and your own can be provided.

**Comment by pranavkm** [comment]
Closing since this question was answered.
