### ISSUE TITLE
Using Asynchronous Methods in ASP.NET 4.5

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10088]
File: */aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45.md*

See #10075

@Tratcher 	responds:

Yeah, this is not the right doc for that guidance. Singleton usage is unrelated to async code.

I see why he did it though, that code sample is doing the wrong thing:
```
    using (HttpClient httpClient = new HttpClient())
    {
        var response = await httpClient.GetAsync(uri);
        return (await response.Content.ReadAsAsync<List<Gizmo>>());
    }
```

Also: “The asynchronous HttpClient class is used instead of the asynchronous WebClient class.” That’s odd guidance given WebClient has Async APIs as well.

@Tratcher can you give me the async `WebClient` code so I can fix this?

**Comment by Tratcher** [comment]
The async Task replacement for WebClient.DownloadString is [DownloadStringTaskAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadstringtaskasync?view=netframework-4.7.1) (creative, right?).

So that code becomes:
```
public async Task<List<Gizmo>> GetGizmosAsync()
{
    var uri = Util.getServiceUri("Gizmos");
    using (WebClient webClient = new WebClient())
    {
        return JsonConvert.DeserializeObject<List<Gizmo>>(
            await webClient.DownloadStringTaskAsync(uri)
        );
    }
}
```
