### ISSUE TITLE
Expand route to include both / and ~/

### ISSUE THREAD

**Issue by sadqiang** [aspnet/Docs#10089]
This article says: If the `[HttpGet]` attribute has a route template (for example, `[HttpGet("/products")]`, append that to the path.

But it is wrong because of "/".  In order to make it correct, remove the "/".
As far as I know, the  prefix "/" in attribute router applied to action methods will make the route independent on controller's attribute route

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#register-the-database-context)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sadqiang 	it should say, append `"/products"`

**Comment by Rick-Anderson** [comment]
@scottaddie 	please review.

**Comment by sadqiang** [comment]
Sorry. It will NOT be appended. 

References: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2

> Route templates applied to an action that begin with a / don't get combined with route templates applied to the controller. This example matches a set of URL paths similar to the default route.

**Comment by Rick-Anderson** [comment]
@scottaddie please review.

**Comment by Rick-Anderson** [comment]
@rynowak please review.

**Comment by rynowak** [comment]
The statement is correct, I would expand it to include both `/` and `~/`
