### ISSUE TITLE
What is the purpose of IApplicationBuilder.UseResponseCaching?

### ISSUE THREAD

**Issue by stamminator** [aspnet/Docs#10095]
Does invoking this method enable use of `ResponseCacheAttribute`? Does failing to invoke it render the attribute useless? And is it possible to not use caching in a standard development workflow, like this:

### Startup.Configure(IApplicationBuilder app)
```csharp
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseResponseCaching();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @stamminator ...

* *Purpose: Add the Response Caching Middleware to the request processing pipeline.*
* *No* (for example, see the sample app ... the middleware isn't used)
* Mostly *No* -- `VaryByQueryKeys` wouldn't work. The rest of the attribute scenarios will work without the middleware.
* *Yes* -- **_IF_** you mean the server-side caching aspects and `VaryByQueryKeys`.

The attribute participates in setting cache control headers on responses, while the middleware is capable of caching responses on the server. They overlap when it comes to `VaryByQueryKeys` ... it's used in the attribute but requires the middleware to work.

If you don't add the middleware to the request processing pipeline, the server-side caching scenarios aren't functional, as described in the other topic: https://docs.microsoft.com/aspnet/core/performance/caching/middleware

> The web server can cache responses when you add [Response Caching Middleware](https://docs.microsoft.com/aspnet/core/performance/caching/middleware).

Seems like to me that the intro could use a slight rewording or perhaps another sentence or two that would make it crystal clear ... *sort of like what I just said.* :smile:

Leave this open for Rick to see ... he'll decide what to do. Rick, you can assign me if ur busy. It should only take a few minutes to touch up.

**Comment by guardrex** [comment]
I'm just sitt'in here with nothing (small) to do. I'll shoot in a quick suggestion PR, which can be closed if it isn't good.
