### ISSUE TITLE
No Data returned on the Test the PostTodoItem method

### ISSUE THREAD

**Issue by KevinMull** [aspnet/Docs#10096]
On the 'Test the PostTodoItem method' section I am posting the following JSON...

{
  "name":"walk dog",
  "isComplete":true
}

But the response I get back is...

{
    "id": 2,
    "name": null,
    "isComplete": false
}
Status: '201 Created'

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Start debugging.

**Comment by KevinMull** [comment]
I have debugged it and right at the start of method 'PostTodoItem(TodoItem todoItem)' NO data is being posted.  So could it be something wrong in the Postman set up?

I am posting...


{
"Name":"walk dog",
"IsComplete":true
}

But after breaking  on the above method it shows...


{
"id": 2,
"name": null,
"isComplete": false
}

Note, no matching camel case in the response
