### ISSUE TITLE
Bundling and Minification in ASP.NET 5

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#101]
ASP.NET 5 -> Client-Side Development -> Bundling and Minification in ASP.NET 5

**Comment by styfle** [comment]
I am interested in how ASP.NET 5 will handle bundling and minification.
Do you plan on sticking with the [MVC](http://www.asp.net/mvc/overview/performance/bundling-and-minification) solution of storing the bundle in memory during release builds or adopting the new [Web Essentials](http://vswebessentials.com/features/bundling) solution of `.bundle` files that minify upon saving?

Forgive me if this is not the correct  place to ask such a question :panda_face:

**Comment by awestroke** [comment]
Why is this closed?

Also, a question that is so far unanswered is, how do you get the current Solution Configuration (Release|Debug) in their gulp/grunt config? It's vital to switch on minification etc

**Comment by ryanheath** [comment]
Is it an idea to do something like this? https://github.com/ryanheath/MVC-Bundling-And-Minification-For-VisualStudio-With-Gulp
Or are you guys planning to take a whole other direction with bundling & minification?
I'm will to create something alike for asp.net if still needed.

**Comment by awestroke** [comment]
I solved this by always building two versions of the javascript with gulp, and switching which one is used with the environment tags in the new ASP.NET vNext. It's not ideal, as the production js build can take up to 30 seconds, but it works. I use hot building for development anyways

**Comment by danroth27** [comment]
Clarify that the environment tag uses tag helpers and link to http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/intro.html

**Comment by danroth27** [comment]
See also https://github.com/aspnet/Docs/issues/308.

**Comment by fotijr** [comment]
It's not clear to me what the proposed replacement is now the the `.bundle` files are going away in ASP.NET 5. Is TagHelpers the solution? I would be fine using something like [wiredep](https://github.com/taptapship/wiredep) with gulp, but it'll be a lot more useful if we can reference the solution configuration (as mentioned by @awestroke).

I'm surprised we're this far in the development of ASP.NET 5 with no clear recommendation on replacing the current MS bundling system.

**Comment by Erikre** [comment]
Updating based on the following outline:
Bundling and Minification
- Overview
- Bundling
- Minification
- Impact of Bundling and Minification
- Controlling Bundling and Minification
- Using the “*” Wildcard Character to Select Files
- Bundle Considerations
- Gulp
- See Also
