### ISSUE TITLE
what is with encrypting data protection keys at rest

### ISSUE THREAD

**Issue by hoksource** [aspnet/Docs#10100]
From my understanding setting the key persistence location turns off default key encryption at rest.
what does "rest" mean?
why should we do it? Is it because the persisted key is not encrypted form? what are the vulnerabilities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share cookies among apps with ASP.NET and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello and *Happy Holidays!* ⛄️ @hoksource ...

> setting the key persistence location turns off default key encryption at rest.

Yes ... the info in the **Warning** messages at the tops of [Key encryption at rest in ASP.NET Core](https://docs.microsoft.com/aspnet/core/security/data-protection/implementation/key-encryption-at-rest) and [Key storage providers in ASP.NET Core](https://docs.microsoft.com/aspnet/core/security/data-protection/implementation/key-storage-providers) are valid according to engineering. The default they reference is the in-memory provider. Actually, that provider isn't actually listed (perhaps, it should be).

You are correct about "at rest" ... it means that the keys aren't encrypted where they're stored.

The vulnerability for not encrypting at rest is that anyone with access to the key storage location can get the keys and then decrypt anything encrypted by Data Protection.

The current advice is *always to encrypt at rest when possible*. In addition to those **Warning** messages ...

> Keys should be protected at rest when possible. The system should figure out an appropriate default protection mechanism and apply it automatically.

From: https://docs.microsoft.com/aspnet/core/security/data-protection/introduction#design-philosophy

@hoksource Leave this open. I'd like to talk to the team about this after the holidays (after Jan. 2).

**Comment by guardrex** [comment]
Looking over the topics, I think it's ok as we have it.

I'm going to close as answered, but we can re-open to discuss further if needed.

**Comment by hoksource** [comment]
Thank for the response. It was very informative. :)
