### ISSUE TITLE
AddAuthentication() is missing

### ISSUE THREAD

**Issue by ikemtz** [aspnet/Docs#10107]
I've looked around for any breaking changes related to the Microsoft.AspNetCore.Authentication package and haven't found any.  If there is a breaking change where this is no longer included in the Microsoft.AspNetCore.App package, I would expect to find that documentation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @ikemtz ... It's in the metapackage. See the **Dependencies** listed at :point_right: https://www.nuget.org/packages/Microsoft.AspNetCore.App/

The last (major) set of changes for auth were for the release of 2.1 :point_right: https://docs.microsoft.com/aspnet/core/migration/20_21#changes-to-authentication-code

I'm sure that there were bug fixes and improvements for 2.2, but nothing significant for migration that the engineers informed us about.

**Comment by ikemtz** [comment]
Thanks for the response.  I tried going through the steps listed in the doc and I was getting a few errors related to Authorization namespace and extension methods missing.  I tried again today and for some reason, it worked.

Thanks again!
