### ISSUE TITLE
Unclear flow of message

### ISSUE THREAD

**Issue by sadqiang** [aspnet/Docs#10105]
"The SendMessage method can be called by any connected client. It sends the received message to all clients. SignalR code is asynchronous to provide maximum scalability."

These sentences are not clear enough to describe the flow of message from a invoking client to the server passing to other clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@sadqiang Thanks for the comment -- The call from the client is added later in the tutorial, so I'll add a sentence here explaining that you see later how the client calls the server method.
