### ISSUE TITLE
Visual Studio 2019 Preview does not have Controller in Add submenu.

### ISSUE THREAD

**Issue by mbalcerzyk** [aspnet/Docs#10109]
Preview is a preview, but Visual Studio 2019 Preview does not have Controller in Add submenu (at least in my installation). Can the docs be updated for this preview also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mbalcerzyk ... No, sorry, we won't be able to do that. Previews of the tooling and the framework change quite a bit from preview-to-preview, and we don't have the staffing to keep up with all of the documentation changes that would be required.

I'll close as answered, but we can re-open this issue if you would like to discuss it further.

**Comment by Mackbuster** [comment]
You can create the folder named controllers under the MVCMovies project and then add a controller. 

You have to add the code app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=Index}/{id?}");
});
in the startup.cs otherwise you wont be able to see that in the browser
