### ISSUE TITLE
Invalid Json format on multiple set

### ISSUE THREAD

**Issue by RemiBou** [aspnet/Docs#10116]
Repro step on mac os :
-  create an json file with values on your project folder
- open a terminal the project folder
- type "cat file.json | dotnet user-secrets set"
- output "
System.FormatException: Could not parse the JSON file. Error on line number '0': '﻿{}'. ---&gt; Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ﻿. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.SecretManager.Tools.Internal.SetCommand.FromStdInStrategy.Execute(CommandContext context) in /_/src/dotnet-user-secrets/Internal/SetCommand.cs:line 73
   at Microsoft.Extensions.SecretManager.Tools.Program.RunInternal(String[] args) in /_/src/dotnet-user-secrets/Program.cs:line 88
   at Microsoft.Extensions.SecretManager.Tools.Program.TryRun(String[] args, Int32& returnCode) in /_/src/dotnet-user-secrets/Program.cs:line 36
Command failed : Could not parse the JSON file. Error on line number '0': '﻿{}'.
"
Expected output : the user secrets has to be set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=macos#set-multiple-secrets)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by RemiBou** [comment]
You can find it here https://github.com/RemiBou/Toss.Blazor/blob/master/Toss.Server/empty-secrets.json

**Comment by scottaddie** [comment]
@RemiBou Which version of the .NET Core SDK are you using for this project?

**Comment by RemiBou** [comment]
Here is my dotnet --version output "2.2.101" and here is my global.json

`{
  "sdk": {
    "version": "2.2.100"
  }
}`

**Comment by scottaddie** [comment]
@RemiBou Thank you for the info! I'm unable to reproduce on macOS using that *global.json* file and SDK version. Can you please make available a project on GitHub that reproduces the problem?

**Comment by RemiBou** [comment]
@scottaddie sorry for the lack of feedback, I'll send a repro soon

**Comment by rasputin243** [comment]
I am seeing the same issue when running the following command (as recommended in the [User Secrets guide](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=windows)) from a powershell script

``` type .\dev.json | dotnet user-secrets init```

When I execute this in an interactive shell, it works correctly. It fails when executed in a PowerShell script.

> OS: Windows 10 Pro
> dotnet --version 3.1.201
> PowerShell version: 7.1.0-preview.2

####  Additional Diagnostics: 
```
$config = Get-Content ".\dev.env"
$config | ConvertFrom-Json | ConvertTo-Json 
$config | dotnet user-secrets set
```
and 
```
cat ".\dev.env" | dotnet user-secrets set
```
did not work within the powershell script, but do work in an interactive shell.
