### ISSUE TITLE
Introduction to Identity - inconsistent logout

### ISSUE THREAD

**Issue by amafernandes** [aspnet/Docs#10119]
# Issue description
 
Log out scaffolding states: 
> [SignOutAsync](/dotnet/api/microsoft.aspnetcore.identity.signinmanager-1.signoutasync#Microsoft_AspNetCore_Identity_SignInManager_1_SignOutAsync) clears the user's claims stored in a cookie. Don't redirect after calling `SignOutAsync` or the user will **not** be signed out.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

# Details

Log out scaffolding recommendation on  [Identity docs](https://github.com/aspnet/Docs/blame/100970349db83ade6615702a7828880dd42ad7d4/aspnetcore/security/authentication/identity.md#L187) contradicts current [Identity code](https://github.com/aspnet/AspNetCore/blob/5a64688d8e192cacffda9440e8725c1ed41a30cf/src/Identity/src/UI/Areas/Identity/Pages/V4/Account/Logout.cshtml.cs#L47-L61) bellow:

``` csharp
        public override async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                // This needs to be a redirect so that the browser performs a new
                // request and the identity for the user gets updated.
                return RedirectToPage();
            }
        }
```

After scaffolding the Logout page, if `returnUrl` is `null`, the result of using `Page()` instead of `RedirectToPage()` is that username and Logout button are still visible after logout is made.

![](https://raw.githubusercontent.com/amafernandes/assets/master/logout.PNG)

**Comment by Rick-Anderson** [comment]
Would you mind opening this issues with the "content feedback" button at the bottom of the problem page? It helps us keep track of issues related to docs and gets the attention of the doc owners.

**Comment by Rick-Anderson** [comment]
MOved to #10169
