### ISSUE TITLE
Visual Studio Community 2017 for Mac Version 7.7.2 (build 21) - Does not have Controller folder

### ISSUE THREAD

**Issue by rasfal** [aspnet/Docs#10112]
Visual Studio Community 2017 for Mac
Version 7.7.2 (build 21)

It does not have controller folder as said in the tutorial. 
I am unable to proceed further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.2&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Then you didn't create a MVC app in the first part.
