### ISSUE TITLE
Custom watch projects instructions are vague

### ISSUE THREAD

**Issue by jamietwells** [aspnet/Docs#10117]
It simply says: 

> If the goal is to watch both projects, create a custom project file configured to watch both projects

What is a *custom project file*? How do I create one? `dotnet new custom-project`? Where should I put this file? In the same folder as the `.sln` file? In the `tests` folder? What should I use as the file name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e3163f-1903-f2c7-8909-d34f917944bf
* Version Independent ID: 55aae418-9d32-5b2b-1df7-5e4e76313ec4
* Content: [Develop ASP.NET Core apps using a file watcher](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/dotnet-watch.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/dotnet-watch.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
