### ISSUE TITLE
LibMan GUI displays unreadably light colored font in VS dark theme

### ISSUE THREAD

**Issue by bdelaney** [aspnet/Docs#10118]
In the Add Client-Side Library search box, the drop down list at &lt;Type to search&gt; is a very light gray, almost unreadable. Reproducible in VS 2017 15.9.4 with Dark theme applied. In other themes, list is visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d69ef46-689c-33d0-c86b-078c8172c480
* Version Independent ID: 519af8ab-78e5-88c9-f268-431f417eca73
* Content: [Use LibMan with ASP.NET Core in Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-2.2)
* Content Source: [aspnetcore/client-side/libman/libman-vs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/libman/libman-vs.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by bdelaney** [comment]
I see this is already raised as an issue: https://github.com/aspnet/LibraryManager/issues/376

**Comment by guardrex** [comment]
Hello @bdelaney ... Yes, the engineering issue will cover this. We just handle the documentation over here. I'll close here, but we can re-open to discuss further if the topic requires attention.
