### ISSUE TITLE
Namespaces matter

### ISSUE THREAD

**Issue by Xerillio** [aspnet/Docs#10124]
I think it's important to point out that the namespaces for the classes used by the localizer matters a lot in locating the resources. Specifically in the sample repo. the SharedResources class is located at:
        ./sample/Localization/Resources/SharedResource.cs
Its namespace is just `namespace Localization`, however this is not the default namespace when you create the file on that path in Visual studio where you get `namespace Localization.Resources`. I had a hard time getting this to work until I stumbled upon [this comment](https://github.com/aspnet/Docs/issues/6830#issuecomment-395635041) and decided to look into why that in-fact solved the problem.
      

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Xerillio 	thanks for pointing that out. You are correct. I thought I mentioned that. I hope to review this soon.

**Comment by dunlapm** [comment]
It should also be noted that if your assembly name is not the same as your default namespace, the resources will also fail to load.

**Comment by Rick-Anderson** [comment]
@hishamco 	please review.

**Comment by hishamco** [comment]
`RootNamespaceAttribute` came for the rescue, FYI this will be mentioned in the troubleshoot article

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg 	please make a PR with the initial draft addressing this. I can clean up and merge.

**Comment by ryanbrandenburg** [comment]
Yeah, this is already [covered here](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md#resource-file-naming). Closing.
