### ISSUE TITLE
LinkGenerator API has changed

### ISSUE THREAD

**Issue by felipepessoto** [aspnet/Docs#10129]
It seems LinkGenerator changed in ASP.NET Core 2.2 Preview 3, but the docs references the old API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @felipepessoto ... The updates for 2.2 (`LinkGenerator`) were performed on https://github.com/aspnet/Docs/pull/9527. We may have missed something given how large the update was.

The API Browser is still down for 2.2, so it's painful for me to check API. Are you referring specifically to the *URL generation reference* section at the end of the topic? If not, can you point out what API you're referring to?

**Comment by felipepessoto** [comment]
In the Middleware example:

var url = _linkGenerator.GenerateLink(new { controller = "Store",
                                                    action = "ListProducts" });


It also be nice to add what Nuget Package we need to add if we want to use LinkGenerator in a class library

**Comment by guardrex** [comment]
Thanks for flagging this. I'll add a bit for the NuGet package while fixing it.
