### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Afam6** [aspnet/Docs#10127]
There's a typo in the "Next steps" section of this article "Ran the app"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Afam6 ... It's ok ... it's past tense.

> ... you ... Created ... Ran ... Examined
