### ISSUE TITLE
Address empty PUT returns 500 Error

### ISSUE THREAD

**Issue by RobertBernstein** [aspnet/Docs#10123]
If I add the PutTodoItem method as it appears in the walkthrough, I get an HTTP 500:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: The instance of entity type 'TodoItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key 4c3e value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap&lt;TKey&gt;.ThrowIdentityConflict(InternalEntityEntry entry)
```

However, if I comment out the line that sets the Entry.State to EntityState.Modified, then I get the expected HTTP 204 response.  Am I doing something wrong?

Also, it seems like adding the following line above the SaveChangesAsync() is needed to actually modify the contents of item # 1: 

```
_context.TodoItems.Update(todoItem);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RobertBernstein 	not exactly sure what you're doing wrong but the error message provides a pretty good clue.

**Comment by RealityMasque** [comment]
Hi, I copied & pasted up from this tutorial up to that same point as RobertBernstein, & got the same error.  Is the tutorial wrong?

**Comment by NickeManarin** [comment]
I have the same problem, looks like every time that I run the project, the database restarts. Since it's empty, I have to call GET to run the constructor of the Context.cs class in order to create the first ToDo item. After that, the PUT works fine.

So what I think that is happening is that since the PUT method is the first thing that you are trying to run, and the database is empty, you have two parts of the code dealing with the ToDo item of ID 1.

**Comment by Rick-Anderson** [comment]
> I have the same problem, looks like every time that I run the project, the database restarts. Since it's empty, I have to call GET to run the constructor of the Context.cs class in order to create the first ToDo item. After that, the PUT works fine.

Per the article:

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TodoApi.Models;

namespace TodoApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TodoController : ControllerBase
    {
        private readonly TodoContext _context;

        public TodoController(TodoContext context)
        {
            _context = context;

            if (_context.TodoItems.Count() == 0)
            {
                // Create a new TodoItem if collection is empty,
                // which means you can't delete all TodoItems.
                _context.TodoItems.Add(new TodoItem { Name = "Item1" });
                _context.SaveChanges();
            }
        }
    }
}
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TodoApi.Models;

namespace TodoApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TodoController : ControllerBase
    {
        private readonly TodoContext _context;

        public TodoController(TodoContext context)
        {
            _context = context;

            if (_context.TodoItems.Count() == 0)
            {
                // Create a new TodoItem if collection is empty,
                // which means you can't delete all TodoItems.
                _context.TodoItems.Add(new TodoItem { Name = "Item1" });
                _context.SaveChanges();
            }
        }
    }
}using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TodoApi.Models;

namespace TodoApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TodoController : ControllerBase
    {
        private readonly TodoContext _context;

        public TodoController(TodoContext context)
        {
            _context = context;

            if (_context.TodoItems.Count() == 0)
            {
                // Create a new TodoItem if collection is empty,
                // which means you can't delete all TodoItems.
                _context.TodoItems.Add(new TodoItem { Name = "Item1" });
                _context.SaveChanges();
            }
        }
    }
}
```

 This code is in the constructor, so it runs every time there's a new HTTP request. If you delete all items, the constructor creates Item1 again the next time an API method is called. So it may look like the deletion didn't work when it actually did work.

**Comment by Rick-Anderson** [comment]
I'll have to think of a cleaver way to make sure the DB is not empty. Maybe seed it on startup.

**Comment by Rick-Anderson** [comment]
I don't see what the problem is here - other than maybe explain you need to do a PUT on an exiting item.  Maybe I should add something like

Call GET on the item you want to update with PUT to verify the item is in the DB.
