### ISSUE TITLE
Question on inconsistent factory class

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#10126]
@jabbera states on https://github.com/aspnet/Docs/pull/10120#issuecomment-450272729 ...

> I missed the where TStartup: class restriction. The class is not consistent. You should either have the CustomWebApplicationFactory not be generic and replace TStartup here:  
https://github.com/jabbera/Docs/blob/2f5cda31d239a364db29c7cf3616ea9fd455b6d7/aspnetcore/test/integration-tests/samples/2.x/IntegrationTestsSample/tests/RazorPagesProject.Tests/CustomWebApplicationFactory.cs#L42
>
> With the concrete type, or make my change (that compiles of course.) 

The proposed change on the PR was from ... 

```csharp
    public class CustomWebApplicationFactory<TStartup> 
        : WebApplicationFactory<RazorPagesProject.Startup>
```

... to ...

```csharp
    public class CustomWebApplicationFactory<TStartup> 
        : WebApplicationFactory<TStartup>
```

Thanks @jabbera for commenting. The sample app approach for the custom factory was approved by engineering when the topic was published, so let's take this up with @javiercn, the engineer who built and advises on the integration testing bits, when he gets back from the holiday break. I suspect he'll be back next week (or perhaps the week after).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@javiercn is this worth investing in?

**Comment by javiercn** [comment]
Using the concrete Startup class sounds fine to me, but not worth investing.

**Comment by guardrex** [comment]
> investing

This is quick to change tho.

I like the generic approach that allows the factory to be used with different projects in the solution (by typing the factory with different `Startup` classes).

However, I'm stuck on one aspect of the original PR.

```csharp
public class CustomWebApplicationFactory<TStartup> 
        : WebApplicationFactory<TStartup>
```

... throws ...

> The type 'TStartup' must be a reference type in order to use it as parameter 'TEntryPoint' in the generic type or method 'WebApplicationFactory\<TEntryPoint>'

@jabbera said it compiles, but it doesn't compile here.

**Comment by jabbera** [comment]
@guardrex I made a subsequent change which you have not tested which compiles for me. Notice the addition of the where clause.

https://github.com/jabbera/Docs/commit/9edf513548cc339fd87ffc88819396bfd766fc21

```
    public class CustomWebApplicationFactory<TStartup> 
        : WebApplicationFactory<TStartup> where TStartup: class
```

**Comment by guardrex** [comment]
Ah ... Yes ... I do recall that now.

I like the proposed change if approved, so @javiercn let me know if I should proceed or close.

This may require minor textual changes if it goes forward. I'll look when I get back. I'm at the gym :muscle: for a bit.
