### ISSUE TITLE
Pressing button [Previous] or [Next], it also send me to same content.

### ISSUE THREAD

**Issue by donhuvy** [aspnet/Docs#10131]
When I press button [Previous] or [Next], it also send me to same content. It is a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6081e36d-a501-324b-3d5a-e0554658d301
* Version Independent ID: 232ef04e-563a-86b4-e397-1359bb5579ca
* Content: [ASP.NET Core MVC with EF Core - Concurrency - 8 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/concurrency?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-mvc/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
It's not. Read it.
