### ISSUE TITLE
CDN for MicrosoftAjax localization dead links

### ISSUE THREAD

**Issue by footed** [aspnet/Docs#10133]
I use .net framework to build a webform website with ScriptManager and I set EnableCdn to true.
I find ScriptManager set the MicrosoftAjax.js to https://ajax.aspnetcdn.com/ajax/4.6/1/MicrosoftAjax.zh-Hant.js and the response code is 404 so the system come back to my website to get the MicrosoftAjax.zh-Hant.js and MicrosoftAjaxWebForms.zh-Hant.js
I also try to link MicrosoftAjax.js and MicrosoftAjaxWebForms.zh-Hant.js use another language like fr-Fr the response code is 404 same with zh-Hant.

**Comment by guardrex** [comment]
Pertains to: https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#using-aspnet-ajax-from-the-cdn

@ChrisSfanos

**Comment by guardrex** [comment]
Looks like this should be opened over on: https://github.com/aspnet/Docs/issues/5832

I'll move it over there.
