### ISSUE TITLE
Scafold Department

### ISSUE THREAD

**Issue by rcroeder** [aspnet/Docs#10143]
Just note, if you follow the instructions in order, rowversion is already inserted into the index.cshtml before instructor. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`rowversion` is inserted by the SQL Server in the DB.

@tdykstra 	when you update this series take a quick scan a closed issues and review this.

**Comment by tdykstra** [comment]
@Rick-Anderson Will do.
