### ISSUE TITLE
You can set an absolute expiration time with ExpiresUtc

### ISSUE THREAD

**Issue by udiNaveh** [aspnet/Docs#10145]
According to the docs: 
"You can set an absolute expiration time with `ExpiresUtc`. You must also set `IsPersistent`; otherwise, `ExpiresUtc` is ignored and a single-session cookie is created." 
However, I am running the sample app code (on .Net Core 2.1), and when I set ExpiresUtc=DateTimeOffset.UtcNow.AddSeconds(10)  and IsPersistent=false,
 the user is logged out after 10 seconds of inactivity. So ExpiresUtc is not ignored despite the fact that IsPersistent is not set.  This actually makes sense, because I would like to have control on the length of the session of the user when the cookie is not persistent, but it seems to contradict the docs. Can I count on this behavior in production code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.md#absolute-cookie-expiration)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Absolute cookie expiration](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.2#absolute-cookie-expiration)

@HaoK 	please review

**Comment by Rick-Anderson** [comment]
@serpent5 and @HaoK 	please review.

**Comment by serpent5** [comment]
The `ExpiresUtc` value is used in combination with setting `IsPersistent` as described, in that the *cookie* will be either session-based (`IsPersistent = false`) or persistent with an expiration of `ExpiresUtc` (`IsPersistent = true`).

However, the cookie is mainly just responsible for storing an `AuthenticationTicket`, which itself uses the value of `ExpiresUtc` (if set). This means that a session-based cookie could be holding an expired `AuthenticationTicket`, which will be rejected accordingly.

When this is the case (the cookie exists but the `AuthenticationTicket` it holds has expired), the user will fail authentication and the logs will show a "Ticket expired" message indicating this.

Where the docs states that `ExpiresUtc` is ignored, it is referring to it being ignored when configuring the *cookie*, but it is still respected for the `AuthenticationTicket` expiration.

**Comment by Rick-Anderson** [comment]
@HaoK 	the above sounds like it should be added to this doc. Do you concur?

**Comment by HaoK** [comment]
Yeah seems fine, @Tratcher sound good?

**Comment by Rick-Anderson** [comment]
@serpent5 can you create a PR with this info?
