### ISSUE TITLE
Add this information to the documentation the ApiControllerAttribute class

### ISSUE THREAD

**Issue by spivonious** [aspnet/Docs#10154]
PLEASE add this information to the documentation the ApiControllerAttribute class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-2.1#annotation-with-apicontroller-attribute)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
What information would you like added? If you would like it added to the API docs, you need to open an issue with code.
