### ISSUE TITLE
Document Domain Routing Policies (DomainMatcherPolicy)

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#10151]
@JamesNK Do you concur that we need to document this? If so, I'd like to do this in a section at the bottom of the *Routing* topic with perhaps some cross-linking from *Host and deploy* node topics.

I recommend we link your sample in the *aspnet/samples* repo as opposed to hosting a sample app for it. **Bonus:** It will give me a chance to test out the cross-repo snippet linking functionality that we presumably have. It will either work :smile: or all end in tears :cry:, but I'd like to give that a try. This is a good test case for that doc scenario.

Cross-ref: https://github.com/aspnet/samples/tree/master/samples/aspnetcore/mvc/domain

**Comment by JamesNK** [comment]
I think it is a Useful Thing that people should know about. I’ll trust your judgement on how much documentation it should have.

Btw we’re planning to make this a more official part of routing in 3.0 and ship it with asp.net core

**Comment by guardrex** [comment]
Let's try it as a short-ish section in *Routing*, which won't take long to generate. As a short section, it's easy to replace/modify for 3.0, too. I'll ping ya on the PR.

> I’ll trust your judgement

... I'm sure Rick, Scott, and Tom will *appreciate the humor in that remark.* 😀

**Comment by Rick-Anderson** [comment]
Closing. We can doc this in 3.0
