### ISSUE TITLE
Object inherited from base class shows Object reference not set in .cshtml

### ISSUE THREAD

**Issue by tonypitwood** [aspnet/Docs#10153]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1#create-a-base-class-to-share-common-code)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tonypitwood** [comment]
My problem is that the object inherited from the base class
compiles OK but click on CreateNew throws an Error Object reference not set - asp-items="@Model.DepartmentNameSL"> in Courses/Create.cshtml
Holding my mouse over @Model.DepartmentNameSL shows
Select DepartmentNameModel.DepartmentNameSL { get; set; } so why would it be saying Object reference not set?
I have copied/pasted the three files, Create.cshtml and cshtml.cs and DepartmentNamePageModel.cs from Github, but still hit the error
Please help! Pitters

**Comment by tonypitwood** [comment]
I am following page 7 of 8 Razor Contoso Universty tutorial

**Comment by tonypitwood** [comment]
Thanks for a quick response, Rick, very encouraging.
I copied and pasted SchoolContext.cs and corrected Student to Students ! and Enrollment to Enrollments . . 
but when I compile (OK) and click n Courses it now tells me that Department in Index.cshtml.cs doesn't exist :(
            Course = await _context.Courses
                .Include(c => c.Department)
                .AsNoTracking()
                .ToListAsync();
yet when I hover over c.Department, it shows "Department Models.Course.Department { get; set; } "
My Models are the same as the tutorial solution

Oh, and a very Happy New Year to you all, too!!

**Comment by tonypitwood** [comment]
Further to above, I changed the field name Department, and selected CourseAssignments 
(in Pages\Courses\Index.cshtml.cs.
Compiled and ran - clicked on Courses and it opened the Courses screen but the Department field was blank.
Clicked on Edit link and got the original error Object reference not set 
????

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
