### ISSUE TITLE
JSON Serialization options

### ISSUE THREAD

**Issue by JNickVA1** [aspnet/Docs#10152]
The doc states "As an example, to configure the serializer to use "PascalCase" property names, instead of the default "camelCase" names, use the following code:", with the code being:
services.AddSignalR()
    .AddJsonProtocol(options =&gt; {
        options.PayloadSerializerSettings.ContractResolver = 
        new DefaultContractResolver();
    });
The way I read the JSON.NET documentation, the default case IS PascalCase and you would need to use a CamelCasePropertyNamesContractResolver in order to use "camelCase" names. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
> The way I read the JSON.NET documentation, the default case IS PascalCase and you would need to use a CamelCasePropertyNamesContractResolver in order to use "camelCase" names.

Sure, but SignalR sets the default to camelCase so the doc comment is accurate.
