### ISSUE TITLE
Update Documentation 

### ISSUE THREAD

**Issue by kucxgithub** [aspnet/Docs#10155]
Hi, please update your documentation.

For Visual Studio 2017 (Windows) with ASP.NET Core 2.2+, there could be missing steps between [Create a web app and scaffold identity] and [Test new user registration]. The project database will not automatically show up.

Alternative Steps:
A. SQL Server Object Explorer in Visual Studio 2017

1. Under View menu, select SQL Server Object Explorer.
2. Right-click on SQL Server Object Explorer. Select 'Add SQL Server'.
3. Under Browse menu, toggle 'Local'. 
4. Select 'MSSQLLocalDB'. The project database should now be visible. 

B. SQL Server Management Studio Via Visual Studio Local DB (MS SQL) Server

1. Under Registered Servers, right-click on Database Engine.
2. In Server Name field, type '(LocalDb)\MSSQLLocalDB
3. Select 'Connect'.

C. SQL Server Management Studio via Your Own SQL Server 

1. Generate SQL scripts. In Package Manager Console (Tools &gt; NuGet Package Manager &gt; Package Manager Console), run the following commands:

(Powershell) Script-Migration
(Console) dotnet ef migrations script

2. Copy the generated script.
3. Open SQL Server Management Studio application. 
4. Go to View &gt; Object Explorer. Right-click on your project's database.
5. Select 'New query'.
6. Paste the query.
7. Execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio#test-new-user-registration)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
SQL Server for Local generally shows up automatically. I've seen cases where it doesn't, and you need to follow your instructions.
