### ISSUE TITLE
WebSocketOptions snippet not working

### ISSUE THREAD

**Issue by Sherbanm** [aspnet/Docs#10163]
AllowedOrigins.Add didn't work for me on .net core 2.2. Is the sample wrong or the property deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @Sherbanm ... It should be there ...

https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Middleware/WebSockets/src/WebSocketOptions.cs

You might need the Options namespace: `using Microsoft.Extensions.Options;`

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
