### ISSUE TITLE
Temp File Limit per Server

### ISSUE THREAD

**Issue by ericbrunner** [aspnet/Docs#10161]
I don't understand that sentence:

The 65535 files limit is per server, so another app on the server can use up all 65535 files.

As far as I understand is the file limit 65535 per server. So all apps running on one server have to share that limitation ?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ericbrunner ... The API seems to imply that the limit would be specifically for temporary files ...

https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=netframework-4.7.2#System_IO_Path_GetTempFileName

... so it perhaps really means **temp files per server**.

IIRC some disk storage formats (e.g., FAT), do have a limit like that for total files on disk.

We probably won't be able to resolve the question completely here at this time without someone from the community researching it. The docs team can take a look when this topic is addressed on https://github.com/aspnet/Docs/issues/5331. Let's leave this open, and I'll add it to the list there for a look when it comes time to work on that one.

**Comment by Rick-Anderson** [comment]
> So all apps running on one server have to share that limitation ?

That's correct.
