### ISSUE TITLE
What is considered as a large file?

### ISSUE THREAD

**Issue by baruchiro** [aspnet/Docs#10171]
The file moved from RAM to Disk if it is exceeding 64KB.
So until I have space in my disk, the file considered as a small file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.2#uploading-large-files-with-streaming)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Large depends on your system resources.

**Comment by baruchiro** [comment]
This is my question- Which system resource? Disk?

**Comment by Rick-Anderson** [comment]
Memory
