### ISSUE TITLE
Document what sections of web.config are no longer used in ASP.NET Core

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1017]

**Comment by GuardRex** [comment]
@tdykstra Would you like me to add something to *Publishing to IIS* that mirrors the guidance from the IISIntegration sample? Something along the lines of ...

> Unlike .NET Framework applications that are configured with the `<system.web>` element in *web.config*, ASP.NET Core apps are configured with an `appsettings.json` file. Many IIS native modules work with ASP.NET Core apps and are configured with the `<system.webServer>` element. For more information, see *Configuration* (LINK: fundamentals/configuration) and *Using IIS Modules with ASP.NET Core* (LINK: hosting/iis-modules).

☝️ The *Using IIS Modules with ASP.NET Core* doc is WIP and will show up as a PR soon.

**Comment by tdykstra** [comment]
@GuardRex That sounds good, but you might want to revise "Core apps are configured with appSettings.json" because it isn't always true -- any of a variety of config sources can be used.

**Comment by GuardRex** [comment]
Yes, I agree. I stole that language from a `web.config` that was trying to tell devs where to put file-based configuration. I'll craft it better for the PR, which will land here in a few minutes.
