### ISSUE TITLE
Wrong ASP.NET Core

### ISSUE THREAD

**Issue by ChefSQL** [aspnet/Docs#10175]
I've installed my Visual Studio after the date on this document (12‎/‎04‎/‎2018), yet my newest ASP.NET Core is version 2.1
The 3rd instruction is:
"Select ASP.NET Core 2.2 in the dropdown, and then select Web Application." There should be instructions on how to update to version 2.2
I am now forced to continue with my 2.1
This does not build confidence and I am now shadowed with the idea that I may just be wasting my time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Tutorial: Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio#prerequisites

**Comment by ChefSQL** [comment]
That's great, but I'm just trying to work to a tutorial that supports the software I just installed.
