### ISSUE TITLE
The Privacy page doesn't exist

### ISSUE THREAD

**Issue by ChefSQL** [aspnet/Docs#10174]
Yup, the 'Privacy' page does not exist!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It does in 2.1 +
