### ISSUE TITLE
Does not Work

### ISSUE THREAD

**Issue by ChefSQL** [aspnet/Docs#10173]
Find does not work. There is some missing instructions or rather there are some specifics missing making this hard to understand. App Runs but the search doesn't work. Then the Genre update doesn't build.
Error:
'An expression tree may not contain a dynamic operation'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We have lots of customers confirming it works. See if you can debug and find your error.
