### ISSUE TITLE
Dispatcher object not defined in my sample.

### ISSUE THREAD

**Issue by sulu99** [aspnet/Docs#10190]
my Visual Studio client SignalRSample doesn't seem to understand where the Dispatcher comes from. What's the proper namespace for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
>The code sample in this article is a WPF app that uses the ASP.NET Core SignalR .NET client.

`this.Dispatcher` is specific to WPF apps, if you have a regular console application then you can just remove the `Dispatcher` usages and keep the code that it was invoking.

**Comment by sulu99** [comment]
Thanks Brennan, That explains it!

**Comment by mutiadavid** [comment]
ASP.NET Core 2.2 doesn't seem to have HubConnectionBuilder. What's the alternative way to create a hub connection?

**Comment by BrennanConroy** [comment]
ASP.NET Core 2.2 does have `HubConnectionBuilder`, did you install the client package? https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2#install-the-signalr-net-client-package
