### ISSUE TITLE
Response from "Add a DeleteTodoItem method"

### ISSUE THREAD

**Issue by yaz65** [aspnet/Docs#10195]
Thanks a lot for this good tutorial, clear and complete! 
I just found a small mistake in the "Add a DeleteTodoItem method" section:

It is written:" The DeleteTodoItem response is 204 (No Content)." whereas this action returns the deleted item (return todoItem;). 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. We'll get it fixed in the next update.
