### ISSUE TITLE
Tag Helpers for CDNs

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#102]
MVC -> Views -> Working with CDNs
- Tag helpers: link, script, img

[Edit Rick-Anderson] #2785 
[Edit Tom Dykstra] [commit with deleted article stub](https://github.com/aspnet/Docs/commit/e4940fb39e40b4af7973e0709c004c6a6cc62f21)

**Comment by bmgarelick1** [comment]
I have created an Azure Web App using MVC and EF. The main objective is to serve video media. I am currently using Google CDN but have not found a clear sample of code that shows how to manage and deliver the media from the MVC web app interacting with the Google CDN. Or, for that matter, the Microsoft Azure services.

**Comment by GuardRex** [comment]
@bmgarelick1 For `link` and `script`, you'll probably want to take a look at the `<environment>` Tag Helper ... https://github.com/aspnet/MusicStore/blob/dev/samples/MusicStore/Views/Shared/_Layout.cshtml#L57-L70 ... which allows you to swap local assets for CDN-based assets based on the environment (Development, Staging, Production, etc.).

I personally use image sources directly from the CDN, even in development. If they don't already offer a Tag Helper for images, you could build your own. https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring

**Comment by bmgarelick1** [comment]
Thanks, I'll take a look.

Sent from my iPhone 7 Plus

On Jan 11, 2017, at 7:39 PM, Luke Latham <notifications@github.com<mailto:notifications@github.com>> wrote:


@bmgarelick1<https://github.com/bmgarelick1> For link and script, you'll probably want to take a look at the <environment> Tag Helper ... https://github.com/aspnet/MusicStore/blob/dev/samples/MusicStore/Views/Shared/_Layout.cshtml#L57-L70 ... which allows you to swap local assets for CDN-based assets based on the environment (Development, Staging, Production, etc.).

I personally use image sources directly from the CDN, even in development. If they don't already offer a Tag Helper for images, you could build your own. https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring

-

**Comment by spboyer** [comment]
Should be covered by #2698

**Comment by Rick-Anderson** [comment]
Fixed by by #2698
