### ISSUE TITLE
Update and use RP

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10217]
433 PV 100% CSAT

Moved from #6807

* The instructions are a bit incomplete.
* The sample isn't a Razor Pages app.
* The sample requires both Redis and SQL Server config to work, and that's a bad bet for an effective sample. Devs probably won't be using both simultaneously. Having to configure both when the dev just wants to see the sample use the one they plan to implement is a major drag on learning from the sample. I'd like to solve this either with two samples or one sample that makes it easy to switch between the two technologies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 937e7280-ac1c-936c-6650-20557da31a8c
* Version Independent ID: d81e3546-e3db-2851-2f61-71f01404057f
* Content: [Distributed Cache Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/distributed-cache-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Opened from wrong topic. Moved to #11236.
