### ISSUE TITLE
Rename Web API node of ToC

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#10212]
The treejack tests revealed some confusion about whether "Web API" referred to:

* How to develop ASP.NET Web API projects

or

* ASP.NET Core API reference 

Can we come up with a name that would be less ambiguous while still short enough to use in the ToC?

**Comment by Rick-Anderson** [comment]
How about **Web API projects** or **Web API apps**

cc @scottaddie

**Comment by tdykstra** [comment]
@Rick-Anderson Web API apps seems perfect as it parallels Web apps and Real-time apps.
