### ISSUE TITLE
Is there any convention for naming or architecture of a custom middleware?

### ISSUE THREAD

**Issue by nicholasyin** [aspnet/Docs#10221]
Why isn't designed using IMiddleware or an abstract class? If the class can be written in any way, is there any convention to follow, e.g. name the method to Invoke or InvokeAsync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
There's more information (e.g., `IMiddleware`) in the factory-based middleware topic, where conventional middleware is compared to factory-based middleware ...

https://docs.microsoft.com/aspnet/core/fundamentals/middleware/extensibility

**Comment by nicholasyin** [comment]
I read the document, got the idea of middleware factory concept. However, could you provide more definitive documentation about the convention details using the 'conventional' way?
