### ISSUE TITLE
Code link doesn't work, Scaffolding gives error

### ISSUE THREAD

**Issue by cataquil** [aspnet/Docs#10229]
what version of Microsoft.VisualStudio.Web.CodeGeneration.Design

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ZQY104** [comment]
I got the same issue. my solution is change the folder name from"2.2.0" to "2.2.0-rtm-35687"  for C:\Users\Administrator\.dotnet\tools\.store\dotnet-aspnet-codegenerator\2.2.0-rtm-35687\dotnet-aspnet-codegenerator\2.2.0-rtm-35687

**Comment by guardrex** [comment]
Cross-ref:

* https://github.com/dotnet/cli/issues/10459
* https://github.com/aspnet/Docs/issues/10016#issuecomment-447657124

I'm going to close as answered, and they have a patch coming for the next minor release.

**Comment by cataquil** [comment]
2 issues: 1 the link to the code.

Issue 2 was scaffolding, it turned out I fixed this by adding the URL to nuget.org/v3/index.json to Nuget Package Manager->Package sources
