### ISSUE TITLE
migration generated code fragment missing one LOC

### ISSUE THREAD

**Issue by costarec** [aspnet/Docs#10224]
In the optional section "Apply the migration to the existing database" the following code fragment is shown from the ComplexDataModel timestamped migration file:

migrationBuilder.AddColumn&lt;int&gt;(
    name: "DepartmentID",
    table: "Course",
    type: "int",
    nullable: false,
    defaultValue: 0);

However, when I generate the migration, my cs file has the code fragment minus the LOC: type: "int", as shown following:

migrationBuilder.AddColumn&lt;int&gt;(
    name: "DepartmentID",
    table: "Course",
    nullable: false,
    defaultValue: 0);

I haven't yet observed any incorrect behavior on the part of the app, but I thought I would ask if this will be important later on and what might I be missing that caused this not to be generated, or maybe a decision that a different/newer version of EF is responsible for?

And thanks for a great tutorial!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio#apply-the-migration-to-the-existing-database)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
SHouldn't matter. Glad you like it.
