### ISSUE TITLE
Environment Tag Helper code snippet is out-of-context

### ISSUE THREAD

**Issue by serpent5** [aspnet/Docs#10228]
The code snippet underneath the line that reads:

> "The Environment Tag Helper uses the value of IHostingEnvironment.EnvironmentName to include or exclude markup in the element:"

doesn't demonstrate the tag helper - it demonstrates using `IHostingEnvironment.EnvironmentName` in a view, but not the tag helper itself.

I can't fully decide whether or not this is intentional, but I was expecting the code snippet to show the tag helper given the context of the line I've quoted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @serpent5 ... It looks like the code snippet simply doesn't capture enough of the file to show it in the topic ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments/sample/EnvironmentsSample/Pages/About.cshtml

It also doesn't link over to the Environment Tag Helper topic.

This is a quick patch fix, so I'll knock it out. Thanks for opening this issue.

**Comment by guardrex** [comment]
Ah ... I see what happened. The snapshot used there doesn't show the code from the *About.cshtml* file. Simplest fix is just to update the snapshot to show the code for the snippet.
