### ISSUE TITLE
Template Configure method is out of date.

### ISSUE THREAD

**Issue by serpent5** [aspnet/Docs#10237]
> The ASP.NET Core templates configure the pipeline with support for a developer exception page, BrowserLink, error pages, static files, and ASP.NET Core MVC:

This statement and the code snippet that follows it are a little out of date:

* BrowserLink (`UseBrowserLink`) is no longer included.
* `UseHsts`, `UseHttpsRedirection` and `UseCookiePolicy` are included as of 2.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2#the-configure-method)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks for flagging this @serpent5.

The topic is referencing a 2.0-era sample (thus code snippets). @tdykstra do you want to take this one, or shall I update it? IMO, we should set up 2.1 and 2.2 samples with versioning in the topic.

**Comment by tdykstra** [comment]
@guardrex If you'd like to take care of it, it's all yours. 😄

**Comment by guardrex** [comment]
@serpent5 I should be on the case with this one in a week or so. I'll give the topic a full pass/update.
