### ISSUE TITLE
Overview of Startup suggests it must contain a ConfigureServices method.

### ISSUE THREAD

**Issue by serpent5** [aspnet/Docs#10236]
> The `Startup` class must be public and contain the following methods:

This reads (to me) that `Startup` must contain both `ConfigureServices` and `Configure` (shown in the code snippet), but only `Configure` is *required* (see [App Startup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2#the-configureservices-method)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.2&tabs=linux)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for catching that @serpent5 ... I'll patch it up real quick. 🏃
