### ISSUE TITLE
Should we care about the DbContext or SqlConnection when  work with WebSockets (longtime connection) ?

### ISSUE THREAD

**Issue by John0King** [aspnet/Docs#10247]
I worry about the number of `DbContext` or `SqlConnection` that not be release when work with websockets.
I use websocket in MVC, and constructor inject , so the the scope will not be release until the websocket close.
should I create my own scope and dispose it when access to the DbContext ?
```C#
using(var scope = HttpContext.RequestServices.CreateScope())
{
    var provider = scope.ServiceProvider;
    var db = provider.GetRequiredService<MyDbContext>();
    //something else
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@anurse 	is this a problem?

**Comment by davidfowl** [comment]
Yes it is a problem and it’s why SignalR makes a scope per Hub innovation instead of per connection. When do you want to create an dispose the scope? Per what exactly?

**Comment by anurse** [comment]
Also adding @BrennanConroy and @mikaelm12 for discussions since I'm on leave at the moment.

**Comment by John0King** [comment]
@davidfowl I'm using websocket directly without `SignalR`,  so the default dependency inject is per connection.

> Yes it is a problem ...

Is the problem caused by pool (Sql connection pool, dbcontext pool) ?   Is it safe to use websokcet with MVC controller (Is there something pooled)?

**Comment by davidfowl** [comment]
You’ll exhaust the pool very quickly since you’re tying the lifetime of a sql connection to a websocket connection.

**Comment by John0King** [comment]
@davidfowl Can u answer my second question  `Is it safe to use websokcet with MVC controller (Is there something pooled)`
I will not use any default dependency inject (neither controller inject or action method inject) and create my own scope every time I access to db

**Comment by davidfowl** [comment]
Sure the controller lives for as long as the websocket connection so keeping that entire object graph alive might be wasteful if you don’t need it but it is “safe”.
