### ISSUE TITLE
Am I missing some new Roslyn goodness or is this code example bogus?

### ISSUE THREAD

**Issue by WillSullivan** [aspnet/Docs#10250]
AFAICT, this given example won't compile

``` c#
app.UseWebSockets(new WebSocketOptions()
{
    AllowedOrigins.Add("https://client.com");
    AllowedOrigins.Add("https://www.client.com");
});
```
Unless there's some new language sugar coming down the pipe, you can't add items to a collection in an object initializer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@tdykstra 	can we move this to a snippet?

**Comment by Rick-Anderson** [comment]
@WillSullivan 	thanks for bringing this to our attention.
