### ISSUE TITLE
Not passing the id as query string does not work for me

### ISSUE THREAD

**Issue by jabejaranoq** [aspnet/Docs#10258]
I made carefully this changes:
"Update the Edit, Details, and Delete Razor Pages to use the "{id:int}" route template. Change the page directive for each of these pages from @page to @page "{id:int}"."
And that did not produced the expected result.  I wonder if a modification in index.cshtml is also needed appart of the ones applied to details, delete and edit pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Nope.
