### ISSUE TITLE
Show examples of receiving an object from the client other than just a string

### ISSUE THREAD

**Issue by kevinclarkneudesic** [aspnet/Docs#10277]
Strings are easy to understand, but how do I take an object I create from a TypeScript interface and call a Hub method?  I am getting an error from a simple interface with one property.  On the Hub method I have the parameter be an interface that I created.  Just get this: Uncaught (in promise) Error: Failed to invoke 'CreateEvent' due to an error on the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by kevinclarkneudesic** [comment]
So I changed my C# model from an interface to a class and it worked.  Perhaps C# is not like TypeScript in that you can say the interface just models the JSON you are expecting.  Everything needs to be a class it seems.  I have been programming so much in TS lately I thought the concepts would transfer to .NET.

**Comment by tdykstra** [comment]
It sounds like your question is answered, so we'll close the issue now. Feel free to reopen if you want to follow up with more questions or comments.
