### ISSUE TITLE
Working with Forms

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1027]
MVC -> Views -> Working with Forms
- Tag helpers: form, input**, text area, select+option, label, validation summary+message
- Cover HTML helper alternatives
- Grow up story to use editor templates (link to separate doc)
- Link to Model Validation

**Comment by Rick-Anderson** [comment]
see notes in #365

**Comment by Rick-Anderson** [comment]
replaced by #365

**Comment by danroth27** [comment]
#365 has the details on how we are covering the built-in tag helpers. This issues specifically covers the Working with Forms article.

**Comment by Rick-Anderson** [comment]
fixes #529

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/124
