### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by Bjego** [aspnet/Docs#10286]
Hey guys,
our trainee follows your tutorial to get started with asp.net core. She is following the visual studio code steps and had an issue with the scaffolding section.
We got an issue that the package "Microsoft.EntityFrameworkCore.Design" wasn't found.
Please add the package installation command for at least visual studio code:
`
dotnet add package Microsoft.EntityFrameworkCore.Design
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Bjego 	at what step did you get that error? I can't repo it doing the following:

`dotnet new mvc -o MvcMovie`
Then jump to this page and follow the instructions.

**Comment by RobCyrus** [comment]
I (different user) am having the same problem at this below step:.. using visual studio code.

dotnet aspnet-codegenerator controller -name MoviesController -m Movie -dc MvcMovieContext --relativeFolderPath Controllers --useDefaultLayout --referenceScriptLibraries

The error message is:
Building project ...
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=2.2.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:12.57

**Comment by RobCyrus** [comment]
2.2.100

**Comment by RobCyrus** [comment]
Maybe I am wrong, but I expected a little more help than one phrase for the whole issue.

“I can’t repo the problem”

**Comment by Rick-Anderson** [comment]
@RobCyrus 	I'm sorry, we're a small doc team. We don't have the resources to provide support. I can tell you we have more than half a million folks reporting this works. Most were not working with Angular.

**Comment by Rick-Anderson** [comment]
@RobCyrus 	it's an excellent error. Try adding `Microsoft.EntityFrameworkCore.Design`

**Comment by RobCyrus** [comment]
Thanks for the reply, I already took Visual Studio code out… 

Take care.

**Comment by Rick-Anderson** [comment]
The top of the issue has an answer
`dotnet add package Microsoft.EntityFrameworkCore.Design`

**Comment by RobCyrus** [comment]
I had already done all that… Not sure what caused it, and it’s too late now. I removed it.
