### ISSUE TITLE
Tutorial: Create a web API with ASP.NET Core MVC - Update Item issue

### ISSUE THREAD

**Issue by drweb86-work** [aspnet/Docs#10289]
# Before you open an issue

If the issue is:
- A problem completing a tutorial, compare your code with the completed sample.

# Issue description

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio

This code is invalid:
// PUT: api/Todo/5
[HttpPut("{id}")]
public async Task<IActionResult> PutTodoItem(long id, TodoItem todoItem)
{
    if (id != todoItem.Id)
    {
        return BadRequest();
    }

    _context.Entry(todoItem).State = EntityState.Modified;
    await _context.SaveChangesAsync();

    return NoContent();
}

Correct code is:
[HttpPut("{id}")]
        public async Task<IActionResult> PutTodoItem(long id, TodoItem todoItem)
        {
            if (id != todoItem.Id)
            {
                return BadRequest();
            }

            var item = await _context.TodoItems.SingleAsync(z => z.Id == id);
            item.IsComplete = todoItem.IsComplete;
            item.Name = todoItem.Name;
            _context.Entry(item).State = EntityState.Modified;
            await _context.SaveChangesAsync();

            return NoContent();
        }
&lt;include description here&gt;

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Rick-Anderson** [comment]
@drweb86-work 	here's the code the scaffolder generates:

```
// PUT: api/TodoItems/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutTodoItem(long id, TodoItem todoItem)
        {
            if (id != todoItem.Id)
            {
                return BadRequest();
            }

            _context.Entry(todoItem).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TodoItemExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }
```

**Comment by drweb86-work** [comment]
The problem is that this code _context.Entry(todoItem).State would fail if to call it sequentially. IOC in a sample is created once on app start. .Net Core **caches** entities that were fetched without AsNoTracking. On second attempt to modify item - it will complain that it already have object with this key in its cache and you're attempting to attach another one.

**Comment by Rick-Anderson** [comment]
@drweb86-work 	feel free to open an issue with the scaffolding team.

**Comment by Rick-Anderson** [comment]
You might want to post to SO first.
