### ISSUE TITLE
SQLite error adding new field

### ISSUE THREAD

**Issue by JDeanThomas** [aspnet/Docs#10299]
Received error

"SQLite does not support this migration operation ('AlterColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262."

Even after deleting DB.

Tried removing DB and Migrations (through VS) and running

dotnet ef migrations add InitialCreate

as well as

dotnet ef migrations add InitialCreate
and
dotnet ef database update

Ultimately the issue was fixed by deleting the DB in VS and then running

dotnet ef migrations remove
and
dotnet ef migrations add InitialCreate

Otherwise error was always:

RazorPagesMovie.Pages.Movies.IndexModel.OnGetAsync() in Index.cshtml.cs

            Genres = new SelectList(await genreQuery.Distinct().ToListAsync());

**Comment by Rick-Anderson** [comment]
> Ultimately the issue was fixed by deleting the DB in VS and then running

Correct. You need to delete the DB.

> Even after deleting DB.

You didn't delete the DB.

**Comment by JDeanThomas** [comment]
I deleted the DB 3 times, and then tried several combinations that including the DB.

If deleting the migrations is part of deleting the DB, then it might be better to explicitly say that. As someone new to using .Net for creating web pages, it was not clear.
