### ISSUE TITLE
Example on how to verify hashed password when using the given example

### ISSUE THREAD

**Issue by maillouxc** [aspnet/Docs#10298]
It's not clear how to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1052d7-e93f-fcb8-6d87-d86cededad23
* Version Independent ID: 61e65ca8-4008-ed27-7254-93385a9ed6d7
* Content: [Hash passwords in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/password-hashing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/consumer-apis/password-hashing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by michael-freidgeim-webjet** [comment]
It will be useful to include in the article body something like ValidatePassword(string password, string correctHash) from https://cmatskas.com/-net-password-hashing-using-pbkdf2/

**Comment by maillouxc** [comment]
I ended up using the `PasswordHasher` class from identity instead, the one that was linked on this page.

At first I was reluctant to use it because I am using authentication without identity and the mentioned class requires a user type as generic parameter, but it turns out it's not actually used anywhere in the class.

This should be documented somewhere, there is really no need to write code such as this for 99% of use cases it seems.

I'm still not sure why the password has her class requires a user parameter when the user is never used anywhere in the class.

**Comment by Rick-Anderson** [comment]
@blowdart 	please review:

* > It will be useful to include in the article body something like ValidatePassword(string password, string correctHash) from https://cmatskas.com/-net-password-hashing-using-pbkdf2/
* > why the `PasswordHasher` class requires a user parameter

**Comment by blowdart** [comment]
So for passwordhasher the parameter is there in case someone wants it for derived classes.

For the comparison I'd just use in the code in Identity, and cut and paste that.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by Ogieeeeee** [comment]
Can we have an example on how to verify a (string) password with a hashed password?

**Comment by mammadkoma** [comment]
This article wrote on 07 May 2014 :
https://cmatskas.com/-net-password-hashing-using-pbkdf2/
Can we use these codes in .net 6 in 2023?
