### ISSUE TITLE
Is WebHost.CreateDefaultBuilder is deprecated?

### ISSUE THREAD

**Issue by baruchiro** [aspnet/Docs#10305]
I can't access him with Microsoft.AspNetCore.Hosting 2.2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [App startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by baruchiro** [comment]
The `WebHost` class does not exist. Only `IWebHost`.

**Comment by serpent5** [comment]
It's in the [Microsoft.AspNetCore package](https://www.nuget.org/packages/Microsoft.AspNetCore/).
