### ISSUE TITLE
Instruction "Create a wwwroot folder in the project directory" not needed

### ISSUE THREAD

**Issue by Toby9876** [aspnet/Docs#10302]
In the "Call the API with jQuery", there is an instruction "Create a wwwroot folder in the project directory." that seems to not be needed since the project template already has created this folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
The *wwwroot* folder does need to be created, as that folder was removed from the 2.2 API project template. 2.1 and earlier versions already include the folder in their project template.
