### ISSUE TITLE
Statement about Microsoft.AspNetCore.App including all packages Supported by the ASP.NET Core team seems incorrect

### ISSUE THREAD

**Issue by Structed** [aspnet/Docs#10314]
The page says at the top:
> Includes all supported packages by the ASP.NET Core team except those that contain third-party dependencies (other than those previously mentioned).

This seems to not be true, because (at least) [Microsoft.AspNetCore.Mvc.Versioning](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning) is not included, but seems to be maintained & supported by the ASP.NET Core team and it does not have any dependencies other than packages already included in the metapackage. And there are probably more packages which are not covered by this statement.

# Suggested change:
> Includes the most commonly used packages which do not have any other dependencies except those included in the metapackage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabe9331-b438-fabe-18ca-15f752ec6778
* Version Independent ID: 3294609f-b881-1fec-de04-2021b48de489
* Content: [Microsoft.AspNetCore.App metapackage for ASP.NET Core 2.1 and later](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/metapackage-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/metapackage-app.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Structed That package is owned by MS, but not by the ASP.NET team.

**Comment by Structed** [comment]
Alrighthanks for the clarification. The package name format is then perhaps  a bit mislwading. If I may ask: how can I check who owns a package?

**Comment by Rick-Anderson** [comment]
YOu can check on NuGet. In this case it says Microsoft, but it's not the ASP.NET team.
