### ISSUE TITLE
Bug in Update method

### ISSUE THREAD

**Issue by Toby9876** [aspnet/Docs#10311]
When trying to update a book with an HTTP PUT using e.g. URL http://localhost:54978/api/books/5c377ee3abdf6607f491228c 
and JSON body 
 {
        "id": "5c377ee3abdf6607f491228c",
        "bookName": "Design Patterns UPDATED",
        "price": 111.93,
        "category": "Computers",
        "author": "Ralph Johnson"
    }

you'll get a conversion error on the Id in the book parameter since it cannot automatically be converted to an ObjectId. However, omitting the id row in the JSON body still does not work since the ID is never set in Book object in the BookService Update method before the ReplaceOne method is run in the database. You'll get a MongoWriteException because the ObjectId is 0. Just setting the Id on the Book object solves the problem.

The other way to solve it would be be able to keep the Book Id as a string in the JSON body and for the Id string to be converted to an ObjectId type somehow by the framework. Is that possible to achieve plugging in a transformer or something in the MVC request pipeline? Otherwise I guess you always would have to get rid of the ObjectId on the Book objects before sending it to the server in various update scenarios (in a more advanced scenario). Kind of a bummer...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Build web APIs with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@prkhandelwal please review

**Comment by prkhandelwal** [comment]
Hello @Toby9876 ,
Thanks for bringing up the issue. This issue can be solved by "Keeping the id as string". You can decorate the id with "BsonRepresentation".

`

        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

`
After doing this, some changes in 'BookServices.cs' will be required.

@Rick-Anderson I'll try to update the code in sample and docs over the weekend.

**Comment by BharatBhushan1610** [comment]
![doc error](https://user-images.githubusercontent.com/46257901/51425868-f870c680-1c07-11e9-9918-1d552d5a908d.PNG)
I had to add these changes along with some string to ObjectId conversion to make the PUT method work fine

**Comment by prkhandelwal** [comment]
@BharatBhushan1610 Although that would would work, the issue was to eliminate the need to explicitly assign the id value.
