### ISSUE TITLE
Need to add some documentation around how to configure the underlying OIDC options for AzureB2C

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#10324]
For doc https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.2

we should add some guidance that they can still configure the OIDC options directly if they specify the scheme name, see: 

https://github.com/aspnet/AspNetCore/issues/6157
https://github.com/aspnet/AspNetCore/issues/6447

**Comment by Rick-Anderson** [comment]
Moved to #10389
