### ISSUE TITLE
Correcting something that we already corrected

### ISSUE THREAD

**Issue by salomonsk8r2003** [aspnet/Docs#10339]
This lesson starts off saying "We don't want to see the time (12:00:00 AM in the image below)".

This was already addressed in the earlier parts of the tutorial. Even the image referenced doesn't show time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@salomonsk8r2003 	fixed. Thanks for pointing this out.
