### ISSUE TITLE
Documentation "Azure Active Directory B2C: OAuth 2.0 authorization code flow" not in sync with "Use Postman to get a token and test the API"

### ISSUE THREAD

**Issue by becke-ch-s0-v1** [aspnet/Docs#10335]
The documentation "Azure Active Directory B2C: OAuth 2.0 authorization code flow": https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code is not in sync with the
documentation "Use Postman to get a token and test the API": https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.2#use-postman-to-get-a-token-and-test-the-api
a) The "MS B2C Postman" doc suggest to use "grant_type=implicit" whereas the "MS B2C OAuth" suggests to use "grant_type=authorization_code"
b) The "MS B2C Postman" doc suggest to use "scope=https://{tenant}.onmicrosoft.com/{api-id-uri}/{scope name}" (e.g. "https://beckechdir1v1.onmicrosoft.com/becke-ch--b2c--s0-v1--webapi-ad/Hello.Read openid offline_access") whereas the "MS B2C OAuth" suggests to use "scope=&lt;client-id&gt; Hello.Read  openid offline_access" (e.g. scope=999f3c14-5e3b-41ea-af33-baa969b... Hello.Read  openid offline_access)
Applied to the quick-start/tutorial (https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-quickstarts-web-app) and its code (https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi/archive/master.zip)
The "MS B2C Postman" doc is working and the "MS B2C OAuth" is not working.
Can you pls fix.
Thank you Raoul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.2#use-postman-to-get-a-token-and-test-the-api)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Rick-Anderson** [comment]
Dup of #10336
