### ISSUE TITLE
Great Tutorial

### ISSUE THREAD

**Issue by CodyPellom** [aspnet/Docs#10362]
Love these tutorials. They really break down .NET for beginners. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the compliment.

@scottaddie 	@tdykstra  bring back the kudos label?

**Comment by tdykstra** [comment]
>bring back the kudos label?

I like our current minimalist approach to labels.  I don't think we get enough of these issues to warrant a label, and kudos come from many sources so I think we'd do better to store them somewhere in a OneNote page.

**Comment by scottaddie** [comment]
There's already a Teams channel for these. I posted this one in that channel.
