### ISSUE TITLE
"ASP.NET Core 2.1 version of this topic" link

### ISSUE THREAD

**Issue by serpent5** [aspnet/Docs#10365]
The "ASP.NET Core 2.1 version of this topic" link points to the current page (2.2 version).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @serpent5 ... The link is correct in markdown, so DoxFX is mess'in with us ...

> [ASP.NET Core 2.1 version of this topic](xref:fundamentals/routing?view=aspnetcore-2.1)

I'll try relative.

**Comment by guardrex** [comment]
I think the problem here is that the query string isn't preserved with xref-style links. DocFX slaps on the latest version when it rendered the link.
