### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by jesslilly** [aspnet/Docs#10372]
Hi!  I think you should hit us quickly with probably the most common use case.  In the "HTTP-based caching respects request Cache-Control directives" section, why not have a really quick code example of how to disable caching on a single controller action?  I bet that is why most people come to this page.  Otherwise, it takes a very long time to read the whole article and figure out what exactly to do.

Also the hierarchy of this page is confusing.  Why not move "Other caching technology in ASP.NET Core" to the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6728e59-93ec-891e-0416-94819296ad72
* Version Independent ID: 5d581acc-c651-2112-844a-6b85dc5a99a6
* Content: [Response caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/response.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/response.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jesslilly 	 just use `[ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]`
