### ISSUE TITLE
Highlight is missing in a code example

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10374]
This is a topic content issue. 
Under the section "Change the title, footer, and menu link in the layout file", the footer of the code example is not highlighted although the footer was changed and the paragraph preceding the code says: "The following markup shows the highlighted changes". Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This will be fixed in the next version.
