### ISSUE TITLE
Can't get EF Power Tools Community Edition to work on this project

### ISSUE THREAD

**Issue by Toby9876** [aspnet/Docs#10376]
In this tutorial there is a reference to EF Power Tools for creating the diagrams without a links to the tools. I search, found, and installed this: https://marketplace.visualstudio.com/items?itemName=ErikEJ.EntityFramework6PowerToolsCommunityEdition

When right clicking on the SchoolContext file, I try to run the Entity Framework -&gt; View Entity Data Model (Read Only) in the contect meny. Nothing happens. At the bottom of Visual Studio I get the following error message: "A constructible type deriving from DbContext could not be found in the selected file". All the other EF Power tool links give the same message. I completed the full tutorial on this page, the project compiles, and I am able to see the newly populated data in the browser. I also tried adding an empty constructor to SchoolContext without success.

The EF Power Tools Community Edition is version 0.9.65.0.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per doc 

> for EF 6.x

**Comment by Toby9876** [comment]
I'm sorry, but do you think you can elaborate a bit more? I don't understand what you mean.

**Comment by Toby9876** [comment]
Got ya. Thanks. Found this reading on the topic: https://www.marathonus.com/about/blog/moving-from-entity-framework-6-to-entity-framework-core-2-0/
