### ISSUE TITLE
Violation of DRY principle in solving an example

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10375]
Under the section of "Change the title, footer, and menu link in the layout file", the user is asked to change the application name in 3 different places: inside the title tag; inside the navbar-brand; and in the footer. 
The solution was a literal hard-code change in the 3 different places.
I suggest to teach the users the [DRY (Don't Repeat Yourself) Principle](https://deviq.com/don-t-repeat-yourself/) this is in order to fight [copy/paste programming](https://deviq.com/copy-paste-programming/) by using the following suggested solution:

```
@{
string AppName = "Movie App";
}
```

and then use `@AppName` in the 3 places. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The app uses the templates and we wouldn't want to change the templates. Many folks will use different strings.
