### ISSUE TITLE
UseIIS with CreateDefaultBuilder 

### ISSUE THREAD

**Issue by brubakerjeff** [aspnet/Docs#10382]
In regards to the following, does this mean CreateDefaultBuilder  calls UseIIS encapsulated within, or that we need to ensure UseIIS is called after CreateDefaultBuilder ?

"CreateDefaultBuilder calls the UseIIS method to boot the CoreCLR and host the app inside of the IIS worker process (w3wp.exe or iisexpress.exe). Performance tests indicate that hosting a .NET Core app in-process delivers significantly higher request throughput compared to hosting the app out-of-process and proxying requests to Kestrel server."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @brubakerjeff ... Yes, `CreateDefaultBuilder` calls `ConfigureWebDefaults` here ...

https://github.com/aspnet/AspNetCore/blob/master/src/DefaultBuilder/src/WebHost.cs#L196

... and then that calls `UseIIS` here ...

https://github.com/aspnet/AspNetCore/blob/master/src/DefaultBuilder/src/WebHost.cs#L228

You're good. Check that source ... the bit in the first link shows all of the guts of `CreateDefaultBuilder` ... all of the good stuff it does for you under-the-covers.

I'll close as answered, but we can re-open if necessary.
