### ISSUE TITLE
Add doc section:Enable using a Cookie Session Store from DI

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10392]
From https://github.com/aspnet/Security/pull/1719

`@HaoK` wrote:
We should have an explicit section recommending this pattern of how to configure options instances with things from DI in this doc.
```
public class UseSomethingFromDI : IConfigureNamedOptions/IConfigureOptions<YourOptions> {
       public CookieConfig(ISomethingFromDI thing) => _thing = thing;
       public void Configure([string name,] YourOptions o) { o.Thing = thing; }
   }
   services.AddTransient<IConfigureOptions<YourOptions>, UseSomethingFromDI>();
```

We can also demonstrate a new in 2.1 API ConfigureOptions here as well maybe:

`services.ConfigureOptions<UseSomethingFromDI>` instead of `services.AddTransient<IConfigureOptions<YourOptions>, UseSomethingFromDI>();`, this uses reflection to basically do the same thing and also lets UseSomethingFromDI configure multiple option types if desired.

Moved from #5922

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Fixed by #11128
