### ISSUE TITLE
Publish to an Azure Web App With Continuous Deployment

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#104]
ASP>NET 5 -> Publishing and Deployment -> Publish to an Azure Web App With Continuous Integration

**Comment by tugberkugurlu** [comment]
I have recently spent some time on this (on dnx v1.0.0-beta4-11532) and I can definitely give this a go and write it up.

> Loving this repo :heart:

**Comment by danroth27** [comment]
Sure! The intent was that this topic would cover using Kudu with ASP.NET 5. We still need to make some updates to Kudu to support our beta4 bits, which should simplify the steps needed. I will let you know once that is in place. 

Please be sure to review our [contribution guidelines](https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md) and [style guide](http://docs.asp.net/en/latest/contribute/style-guide/style-guide.html) and make sure you have a CLA in place. Thanks!

**Comment by danroth27** [comment]
Might be able to use some stuff from http://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/, but need to add ASP.NET 5 app specifics.

**Comment by prateek08** [comment]
Hi @danroth27,
I am using the [partsunlimited ASP.NET 5 project] (https://github.com/microsoft/partsunlimited) in Github. I am able to build and deploy to an Azure Web app from Visual Studio.
Now, I want to integrate the same flow in my CI system (Jenkins). The issue I am facing is - How do i compile/build the ASP.NET 5 project through the command-line so that a web package is generated?

**Comment by danroth27** [comment]
You can use the `dnu publish` command. This will create a folder structure with all the artifacts need to run the app.

**Comment by Erikre** [comment]
I'm updating this topic based on the following outline:

Overview
This tutorial shows you how to create an ASP.NET 5 web app using Visual Studio and deploy it from Visual Studio to Azure App Service using continuous deployment.
Prerequisites
     Install Visual Studio Community
     Install Microsoft ASP.NET 5
     Install Git
Create the web app
Run the web app locally
Create a web app in the Azure Portal
Enable Git publishing from Visual Studio 
Publish the web app to Azure App Service
     Verify the Active Deployment
Run the app in Azure
Update the web app and republish
View the updated web app in Azure
Troubleshooting
Additional Resources

**Comment by AlexChesser** [comment]
I'm trying to make CI work right now from VSO to AZURE.
The error message in trying to build a DNX project to a webapp in VSO is 
```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets (119, 0)
The Dnx Runtime package needs to be installed. See output window for more details.
Exception Message: MSBuild error 1 has ended this build. You can find more specific information about the cause of this error in above messages. (type BuildProcessTerminateException)
Exception Stack Trace: at System.Activities.Statements.Throw.Execute(CodeActivityContext context)
at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)
```

Unless azure gets upgraded to support DNX out of the box, there will need to be some documentation surrounding the azure prebuild scripts needed, what folder to put them in for CI, what to name the files, or whatever is needed to make it work.

I'm struggling to find any of that at the moment.
