### ISSUE TITLE
Suggestion: To use BadRequest() instead of NotFound()

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10406]
I think it would be better to return `BadRequest()` when checking a null id in the following action:

```
public async Task<IActionResult> Edit(int? id)
{
    if (id == null)
    {
        return BadRequest(); //The suggestion
    }
...

}
```

By the way, this is how this is treated in the analogous API scaffold, which I think makes more sense than `NotFound()` for this line specifically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Feel free to open an issue with the scaffolding team. The scaffolder here generates

```
if (id == null)
{
    return NotFound();
}
```
