### ISSUE TITLE
MVC core is behaving illogically in two places.

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10408]
Two things are illogical in how MVC core works:

1- Why `model.Movies[0].Title` does not generate a null reference error when there is no results for the Movies list? isn't this an out of index (famous) error. 
Try to write `var firstItem=Model.Movies[0];` at the top of the view and it throws a null reference error when the Movies list is empty and accessing the first element in an empty array is not allowed. Thus, logically, MVC core should throw errors in evaluating a child of `model.Movies[0]` when displaying the fields names because the element of index [0] does not exist. However, when I used `var firstItem = Model.Movies.FirstOrDefault()` at the top of the view no problems occurred and things make sense in displaying the name of the `firstItem.Title`. MVC should treat  `model => Model.Movies[0].Title` the same way it treated `var firstItem=Model.Movies[0];` at the top of the view by throwing an out of index error. 

2- The other illogical thing about MVC Core is the tag helper. It seems it's not respecting the MVC concept. It behaves illogically as follows: How did the tag helper know and save the states of MovieGenre and SearchString in the index view after doing a search although the returned view model has null values for both view model properties. It seems like the tag manager is making a hidden direct communication between the view model and the view without the knowledge of the controller. Try to trace the controller and you will notice that the returned model has null values for MovieGenre and SearchString, then how the tag-manager knew their values and saved them in the HTML,This violates the MVC pattern concept because the controller is the layer which is entitled of coordinating the data between the models and the views. Is the tag-manager an MVVM thing? because it works beyond the knowledge of the controller by the above evident.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> 1- Why model.Movies[0].Title does not generate a null reference error when there is no results for the Movies list? isn't this an out of index (famous) error.

See this document:

Examine the lambda expression used in the following HTML Helper:

@Html.DisplayNameFor(model => model.Movies[0].Title)

In the preceding code, the DisplayNameFor HTML Helper inspects the Title property referenced in the lambda expression to determine the display name. Since the lambda expression is inspected rather than evaluated, you don't receive an access violation when model, model.Movies, or model.Movies[0] are null or empty. When the lambda expression is evaluated (for example, @Html.DisplayFor(modelItem => item.Title)), the model's property values are evaluated.

> 2- The other illogical thing

Feel free to open an issue with the product team.

**Comment by serpent5** [comment]
I was just typing something up to try and help with this. You beat me to it. :)
