### ISSUE TITLE
services.AddAuthentication in .Net Framework

### ISSUE THREAD

**Issue by JamesFenton** [aspnet/Docs#10403]
The "Work with Windows Authentication" section requires the line `services.AddAuthentication(IISDefaults.AuthenticationScheme);` but when targeting .Net Framework, the AddAuthentication method is not found. 
After much searching, I found I had to install the Microsoft.AspNetCore.Authentication nuget package. Please include this in the docs to help other people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=visual-studio#work-with-windows-authentication)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good idea. We often provide the package name but perhaps it slipped thru because that package is inside the `Microsoft.AspNetCore.App` package and template-based apps use the metapackage.

I'll add our usual language here for this.
