### ISSUE TITLE
What does renameLocals do?

### ISSUE THREAD

**Issue by spacecat** [aspnet/Docs#10404]
What does renameLocals do?

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/sv-se/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @spacecat ... that just renames local vars during minification. The minifier settings are online. Let me see if I can cross-link that.

**Comment by guardrex** [comment]
No ... we're good ... it's there under the link for "JavaScript Minifier" :point_right: https://github.com/madskristensen/BundlerMinifier/wiki/JavaScript-Minifier-settings
