### ISSUE TITLE
Any chance to include a completed code sample for Policy, Role and Claims based authorization?

### ISSUE THREAD

**Issue by sonichanxiao** [aspnet/Docs#10410]
A bit hard to get a overall idea for people who are new to .net core authorization.

The article "Create an ASP.NET Core app with user data protected by authorization" needs quite a bit guessing on how each part works and set up the environment is a bit pain.

**Comment by Rick-Anderson** [comment]
[Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.2) is our recommended authorization sample. authorization is difficult. A Policy, Role and Claims sample wouldn't be simpler.

Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
