### ISSUE TITLE
For row selection use class "table-success"

### ISSUE THREAD

**Issue by khortsch** [aspnet/Docs#10416]
The bootstrap css class for tr selected is "table-success" not "success".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.2&tabs=netcore-cli)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
The tutorial (and sample application) is built with Bootstrap 3, which uses the [`success`](https://getbootstrap.com/docs/3.3/css/#tables-contextual-classes) CSS class. It's Bootstrap 4 that uses the [`table-success`](https://getbootstrap.com/docs/4.2/content/tables/#contextual-classes) CSS class.

**Comment by Rick-Anderson** [comment]
@serpent5 	thanks!
