### ISSUE TITLE
Mac and VSC require dotnet add package Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10411]
Moved from #10284 by @JDeanThomas 

I had to run the following:
`dotnet add package Microsoft.EntityFrameworkCore.Design`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-mac)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JDeanThomas** [comment]
To be clear, I was using VS, not VSC.

**Comment by Rick-Anderson** [comment]
For VS, we have several hundred thousands customers reporting the instructions work. There must have been an anomaly on your machine or the way the project was created.
