### ISSUE TITLE
No About page in 2.2

### ISSUE THREAD

**Issue by JamesUKDEV** [aspnet/Docs#10428]
Creating a new project against 2.2 doesn't create the About page.
Using 2.1 it does.
Can you provide some more info on this please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.2)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The 2.2 templates don't create an about page. You can create that yourself.

**Comment by Rick-Anderson** [comment]
@tdykstra should you fix this before you do the 2.2/3.0 preview 3 update?

**Comment by tdykstra** [comment]
Yes, I think this is likely to cause confusion. It looks like the series wasn't updated for/validated with 2.2 -- maybe make this a general 2.2 update and set it to P1?
