### ISSUE TITLE
Arrow functions not supported in Internet Explorer

### ISSUE THREAD

**Issue by jdarundell** [aspnet/Docs#10421]
This is all brilliant

BUT

MS' own product Internet Explorer does not support javascript "async" and cracks up at the '=&gt;' of     connection.onclose(e =&gt; {

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#call-hub-methods-from-client)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for reporting that, we'll add a note about IE.
