### ISSUE TITLE
How can I connect to Google Cloud Storage?

### ISSUE THREAD

**Issue by CrestApps** [aspnet/Docs#10420]
I wonder if there is a way to use UseStaticFiles() to configure external storage like Google Cloud Storage where we can use virtual drive to external storage space.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @CrestApps ... You'll need to consult the Google docs (and blog posts, chat, support forums) for something like that. We don't document anything regarding Google Cloud Storage here.
