### ISSUE TITLE
Wrong place for this article and other articles in the tree view of Microsoft Docs

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10431]
Hi, I've noticed that there are 5 articles including this one belong to Razor pages however they are put in the left-side tree view of Microsoft Docs under the MVC tree. 
Can you please organize the tree view by moving those 5 topics to the Razor Pages node?

The 5 topics that need to be moved to the Razor Pages node are:
- Filters
- Razor Class Libraries
- Route and app conventions
- Upload files
- Razor SDK

![wrong tree view structure](https://user-images.githubusercontent.com/12829248/51260134-42fb0480-19b6-11e9-925e-8fe2b52cda44.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.2)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your suggestion. I added it to our TOC update issue #10210
