### ISSUE TITLE
Migration names are rendered as class names

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10455]
I suggest to add a note after using `add-migration Initial` that the migration name will be rendered as a class name. Thus naming conventions of classes should apply here. For example, it should start with a letter, preferably capital and should not contain special characters or spaces. What do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That could be added to https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations but doesn't fit into this intro tutorial.

cc @tdykstra 	in case he'd like to add it to the RP/EF tutorial.

**Comment by Rick-Anderson** [comment]
@tdykstra  this is a good tip. We might want to add that at some point. Should I reopen and assign to you?

**Comment by tdykstra** [comment]
Sure
