### ISSUE TITLE
Missing <strong> element

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10457]
**The first correction:** 
This line:
`Func<dynamic, object> petTemplate = @<p>You have a pet named @item.Name.</p>;`
should become:
`Func<dynamic, object> petTemplate = @<p>You have a pet named <strong>@item.Name</strong>.</p>;`

this is in order to match the output which contains the `<strong>` tags.

**The second correction:**
This line:
 `@petTemplate2(pet)`

should become:
` @petTemplate(pet)`

because  `petTemplate2( )` function does not exist in the context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	thanks for the report. Would you be able to create a PR to fix these issues?

**Comment by serpent5** [comment]
I can take this one if @shadinamrouti doesn't want to do so.

**Comment by shadinamrouti** [comment]
Hi @Rick-Anderson , sure, I will do it. Thanks.
