### ISSUE TITLE
searchString parameter not changed in code block

### ISSUE THREAD

**Issue by tetryon** [aspnet/Docs#10466]
In the section that discusses changing the search string parameter to use ID, the following should be highlighted as it changed

if (!String.IsNullOrEmpty(id))   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks. We'll fix this in the next sweep.

**Comment by dogafincan** [comment]
I’ve fixed this here: https://github.com/aspnet/Docs/pull/11004

Wasn’t aware of this issue.

**Comment by Rick-Anderson** [comment]
@dogafincan thanks for letting me know.
