### ISSUE TITLE
Update EF MVC for 3.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#10487]
Update the tutorial for ASP.NET Core 3.0 and content model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d4c57d-4eb1-71fe-6587-b9967ad1b445
* Version Independent ID: 8f0488f1-adc0-b42c-9549-b4028d4317d6
* Content: [ASP.NET Core MVC with EF Core - tutorial series](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@tdykstra 	we don't have the resources to update this. We'll just go with the EF/RP series.
