### ISSUE TITLE
Doc suggestion/question for RC1-final to RC2-final conversions

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1050]
The typical advice for betaX-to-betaY or beta8-to-RC1-final is to hit up the Announcements repo and rundown the breaking changes.

That's easy advice ... that's the low hanging fruit, but not particularly efficient. There are a set of obvious changes that a dev will make going from RC1-final to RC2-final when RC2-final releases.

Would there be merit or would it even be possible in having a doc that encapsulates the major changes one would make converting an RC1-final app into an RC2-final app when RC2 releases?

**Comment by danroth27** [comment]
Yup, we plan to write a migration doc for moving from RC1 to RC2, which is tracked by https://github.com/aspnet/Docs/issues/910.
