### ISSUE TITLE
Unable to Publish to Azure for ASP.NET MVC Database First Site 

### ISSUE THREAD

**Issue by yoorw** [aspnet/Docs#10517]
I was following this tutorial: https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/database-first-development/publish-to-azure and am not able to access the database data on the web app using Azure. 
I am able to run the app locally and access the the database data.  

The web app published successfully.
Clicking on "List of students" results in 

> Error.
An error occurred while processing your request.

I followed the Publish database to SQL Azure section.
I am able to access the database in the Azure Portal and can see the tables populated for Course, Enrollment, and Student. 

I also configured the database server firewall settings for the correct IP.

Are there other things I should be checking to see why I am not able to access the data on Azure?

Thank you.

**Comment by guardrex** [comment]
Examine the Application Event Log ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot#application-event-log

and/or enable stdout logging (same topic) ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot#aspnet-core-module-stdout-log

**Comment by yoorw** [comment]
@Rick-Anderson Thank you for sending the tutorial. Trying to follow those steps for my app fails when publishing with the error: "The 'server' keyword is not supported." I'm assuming it is because my app is a DB First approach and the app you send is a Code First approach? 

@guardrex Thank you for sending the Diagnostic steps. The detailed events I get are: 
`        <System>
            <Provider Name="HttpPlatformHandler"/>
            <EventID>2000</EventID>
            <Level>4</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2019-01-21T07:29:42Z"/>
            <EventRecordID>-1394444875</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD2818788D0379</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>APPLICATION_MANAGER::~APPLICATION_MANAGER | this=00F9D770 [TID 17824] [PID 10916]</Data>
        </EventData>
`

But the app starts and runs fine on Azure. The issue is when my app tries to access the Azure SQL database. 
I can access the database without any issues in the Azure Portal (I can see table data).
I can also access the Azure SQL database in Visual Studio (I can see table data).
However my app has a link to access and display 1 of the Azure SQL database tables.
Clicking on this link when the app is published to Azure results in 
`Error.
An error occurred while processing your request.`

Here is a link to the site: [https://contososite120190121010057.azurewebsites.net/](url)
The error occurs when clicking on "List of students" or "List of enrollments" 


Thank you for your help.

**Comment by guardrex** [comment]
> HttpPlatformHandler

Not used in all of the recent releases. Confirm that you're using the latest SDK. https://dotnet.microsoft.com/download

**Comment by yoorw** [comment]
@guardrex Thank you for your support with this.
I recreated the app project using the latest .NET Framework (4.6.1) and now the db entries display on the web app using Azure.
Thank you.

**Comment by thahurasultana** [comment]
@yoorw  I am at a point where I have published the web app to azure and database as well and even my application uses a database first approach however, my application is not connecting to the database none whatsoever. I have checked the version of SDK which is  6.0.301 and even tried changing the connection string manually but this did not help me. Could you please help me in understanding what did you actually do with regard to the database like the steps you followed?
