### ISSUE TITLE
"options" in version object of a dependency, what are the choices and what do they mean?

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Docs#1052]
As I see more and more types of options dev,build,private etc. I'm really looking for some docs on them.

Are there any?

**Comment by shirhatti** [comment]
Docs on `project.json` will live on the [.NET Core Docs](http://dotnet.github.io/docs/index.html).
Doesn't look like they have published them yet, but they do have an issue tracking it [dotnet/core-docs/#256](http://dotnet.github.io/docs/index.html) and there is an open PR for it. Hope that helps!
