### ISSUE TITLE
display-4 class unavailable

### ISSUE THREAD

**Issue by Gammerz26** [aspnet/Docs#10523]
In the instructions to amend "Pages/Index.cshtml", the Bootstrap class "display-4" is specified. On my copy of VS 2017 Community V15.9.5, this class doesn't appear in the Bootstrap code-completion list, and has no effect on the display if it's omitted or changed to another class (e.g. "display-1").

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/getting-started/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See the Prerequisites

**Comment by Gammerz26** [comment]
Can community edition user upgrade to core .Net to 2.2 by simply downloading the link here https://dotnet.microsoft.com/download/dotnet-core/2.2, in order to run through this tutorial, or are there other changes that need to be performed?

**Comment by Rick-Anderson** [comment]
Yes, install the 2.2 SDK.
