### ISSUE TITLE
What is "4 of 10" in title?

### ISSUE THREAD

**Issue by baruchiro** [aspnet/Docs#10524]
What is `4 of 10` in the title?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [ASP.NET Core MVC with EF Core - Migrations - 4 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Part 4 of the 10 part series.
