### ISSUE TITLE
Use Async/await in WriteResponseBodyAsync

### ISSUE THREAD

**Issue by sugarjig** [aspnet/Docs#10539]
My understanding of async/await is that you should use it through the entire call stack in order to benefit from it. Shouldn't the `WriteResponseBodyAsync` method look more like this?

```
public override async Task WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
{
    ...
    await response.WriteAsync(buffer.ToString());
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@halter73 please review.

@sugarjig 	I think you're right. And `WriteResponseBodyAsync` shouldn't be named async if it's not async.

cc @scottaddie
