### ISSUE TITLE
scaffolder details on Model and DbContext from referenced projects

### ISSUE THREAD

**Issue by vmandic** [aspnet/Docs#10549]
I am having an issue in finding any suitable information on is it possible to specify in generator's options for model and dc if a model and / or dc can be used from other referenced project(s)? And if so, how to?

e.g. if located in web project directory could I run aspnet-generator List -m Proj2.MyModel -dc Proj2.MyDbContext -outDir Pages/MyModelList ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@vmandic 	can you open that issue at https://github.com/dotnet/cli/issues/new
