### ISSUE TITLE
Describe Composite Formatting of ValidationAttribute ErrorMessages 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10546]
Moved from #4505 by @Rabadash8820 

It recently came to my attention that `ValidationAttribute` error messages support [composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting).  I discovered this while reading about [localization of DataAnnotations](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#dataannotations-localization).  That section references a sample code snippet from this repo with the follow property declaration:

https://github.com/aspnet/Docs/blob/4dad08a6662a5cf2eac03c46b4dbb2cd009a43ef/aspnetcore/fundamentals/localization/sample/Localization/ViewModels/Account/RegisterViewModel.cs#L16-L20

The `[StringLength]` attribute is what caught my eye; I'd never seen anything like that!  A composite format string in an attribute constructor??

Unfortunately, I could not find the parameters for these composite format strings anywhere in the Docs, and had to resort to digging through the .NET Core source code to find how these strings were actually used (usually in `string.Format()` calls inside overriden `FormatErrorMessage()` calls).  It really seems like this information should be documented somewhere other than XML comments in the source code.

## Possible TOC locations:

- [Introduction to model validation](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
- [Introduction to using tag helpers in forms](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
- [Adding validation](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
- [Part 6: Using Data Annotations for Model Validation](https://github.com/aspnet/Docs/blob/master/aspnet/mvc/overview/older-versions/mvc-music-store/mvc-music-store-part-6.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@Rabadash8820 

> had to resort to digging through the .NET Core source code to find how these strings were actually used (usually in string.Format() calls inside overriden FormatErrorMessage() calls). 

Do you still have the link to the place in the .NET Core source code that has the string.Format() calls?

**Comment by DanVicarel** [comment]
@tdykstra  Sorry for the late reply.  Here is the `string.Format` call for [`StringLengthAttribute`](https://github.com/dotnet/corefx/blob/3eacad602f7505f9f199dcd1992429506dd98330/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/StringLengthAttribute.cs#L79).  Most of the other classes in that folder of the repo also contain `string.Format` calls.

**Comment by tdykstra** [comment]
@DanVicarel Thanks.  I'm adding a note about this to the doc in #11282

**Comment by tdykstra** [comment]
@dougbu Would you consider the use of Format.String and placeholders in validation attribute error messages an implementation detail that application code shouldn't rely on?  There are lots of ways to get field name and parameters like max length into a default error message, and if we don’t document how we're doing it, it occurs to me that it could be in part because we're holding our options open for doing it differently in the future.

I did add a section explaining how to take advantage of this to my Validation doc PR, but it occurred to me I should double-check to make sure this is good advice..

**Comment by dougbu** [comment]
No, `string.Format` and the placeholders are not implementation details. The developer reading this documentation is writing the format strings and needs to know what parameters the framework will pass (matching those placeholders).
