### ISSUE TITLE
AD LDS

### ISSUE THREAD

**Issue by Sotr461** [aspnet/Docs#10545]
Does .NET Core support AD LDS (Active Directory - Light Directory Service)?

One of the reason we cannot migrate to .NET Core from .NET because all of our web-apps are using AD LDS for authentication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.2#iis-configuration)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@blowdart 

btw- We don't document it if we do, and there's darn little on the Net generally, too.

**Comment by guardrex** [comment]
Thanks @blowdart.

@Sotr461 ... Thanks for asking. This is a *very rare* question ... here anyway ... you're the first to ask on the docs repo AFAIK. I'm going to close for now, but let's see if anyone else asks. If we get another question or two about this, then we'll schedule an update to surface some content on it. Thanks again for mentioning it.
