### ISSUE TITLE
Web server controls

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10542]
As you know, web server controls topic [is no longer supported in other parts of Microsoft Docs](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/7698y1f0(v=vs.85)), therefore, I suggest removing the paragraph titled "Tag Helpers compared to Web Servers Controls" or at least keep the Tag Helpers advantages alone as absolute features of this new technology. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
People still like to compare them.
