### ISSUE TITLE
Identity already exists, need to update _LoginPartial @Inject 

### ISSUE THREAD

**Issue by kokaruk** [aspnet/Docs#10541]
If IdentityMVC already exists, need to update _LoginPartial @inject statements with new identity class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kokaruk 	what is `IdentityMVC` ?

**Comment by kokaruk** [comment]
@Rick-Anderson oops, it was 4 am here. I meant, if we're scaffolding Identity in an MVC project with existing identity for the purpose of extending user data class, injecting that said new class is a crucial step.

**Comment by Rick-Anderson** [comment]
We'll look at this on the next doc sweep.
