### ISSUE TITLE
Unable to build app created with dotnet new react command

### ISSUE THREAD

**Issue by NotMyself** [aspnet/Docs#10554]
I am attempting to build a SPA application created with `dotnet new react` command using docker. Using the following Dockerfile, I get an *npm not found* error.

```Dockerfile
FROM microsoft/dotnet:2.2-sdk-alpine AS build
WORKDIR /app

COPY . .
RUN dotnet restore
RUN dotnet build
RUN dotnet publish -c Release -o /app/deploy

FROM microsoft/dotnet:2.2-aspnetcore-runtime-alpine AS runtime
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
WORKDIR /app
EXPOSE 80
COPY --from=build /app/deploy ./
ENTRYPOINT ["dotnet", "api.dll"]
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Please see the following workaround: https://github.com/aspnet/aspnet-docker/issues/347#issuecomment-354316642. Also, you can join the discussion here: https://github.com/aspnet/Docs/issues/5450.
