### ISSUE TITLE
Add default timeout and how to change

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10560]
Question:As per the documentation below, the health checks are executed periodically if we add publisher. What’s the default interval for auto execution of tests and is there any override?

Per `@pranavkm` 	

It defaults to 30 seconds and you can configure it using HealthCheckPublisherOptions.Period:

`services.Configure<HealthCheckPublisherOptions>(options => options.Period = ...);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-in/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#health-check-publisher)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex 	if you can knock this out quickly do it anytime and ask for review from me and `@pranavkm`

**Comment by guardrex** [comment]
Yes, it's a quick one (btw - didn't seem to make the cut for 3.0 as it only appears in the archived repo).

Cross-ref: https://github.com/aspnet/Diagnostics/blob/082d505977d72c75b68935c93c21feded6928e5f/src/Microsoft.Extensions.Diagnostics.HealthChecks/HealthCheckPublisherOptions.cs

**Comment by guardrex** [comment]
Cross-ref (let's work these two together): https://github.com/aspnet/Docs/issues/10664
