### ISSUE TITLE
Suggestion: for vs code users suggest dotnet watch run instead of ctrl+f5

### ISSUE THREAD

**Issue by Languafe** [aspnet/Docs#10579]
The latter will by default open your browser to https://localhost:5001 unless you manually edit the generated launch.json, for no good reason. If using dotnet watch run from a terminal the tutorial shouldn't have to specifically call out when you need to rebuild.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie 	should we have an include for `dotnet watch` for all the tutorials?

**Comment by Rick-Anderson** [comment]
Thanks for the suggestion. Moved to #9488
