### ISSUE TITLE
Use  etc/hosts file as an option for testing with a domain name

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10587]
Created by @user135711 in #6889

Before your domain is registered, and to save the trouble of setting up Bind9 as a DNS, I think there should be a line at the beginning of both linux tutorials reminding the reader that for testing purposes you can use etc/hosts file to temporarily test your domain name in the tutorials. 

* https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx
* https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-apache

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shirhatti quick/easy review.
cc @guardrex

**Comment by guardrex** [comment]
That argument can be made *in many places* tho throughout the hosting topics (i.e., we don't do this for Windows *hosts* file). Some concepts are just too far afield for ASP.NET Core. Too many remarks like this muddy the core topic concepts.
