### ISSUE TITLE
ExecStart issues when running on RHEL

### ISSUE THREAD

**Issue by juandelcid** [aspnet/Docs#10594]
On RHEL, this does not work:

```
ExecStart=/usr/bin/dotnet /var/www/helloapp/helloapp.dll
```

You need to create a shell script:

```
#!/bin/bash
/usr/bin/scl enable rh-dotnet22 -- dotnet helloapp.dll --server.urls http://0.0.0.0:8080
```

and run that script from the service file:

```
ExecStart=/bin/bash /var/www/helloapp/start.sh
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by shirhatti** [comment]
I haven't tried it myself, but I'm skeptical of it. @juandelcid What's the reason `ExecStart` doesn't work as specified?

**Comment by juandelcid** [comment]
I'm sorry... it was a matter of just using `dotnet`... you're correct, this works:

```
ExecStart=/usr/bin/scl enable rh-dotnet22 -- dotnet /var/www/helloapp/helloapp.dll --server.urls http://0.0.0.0:8080
```
