### ISSUE TITLE
No Example for AspNetCore

### ISSUE THREAD

**Issue by ganjeii** [aspnet/Docs#10598]
Hi! Currently, the documentation only shows an example for configuring the .net client for a forms application. But, say for an AspNetCore web app, it would be nice to see a best practice for configuring the client on app startup. For example: Where would be best to execute a method to configure the client on startup?  The "Configure" method in the startup class would be my first guess, maybe by defining custom middleware to execute the configuration for the client? But that raises the question, does it actually make sense to put it in the "Configure" method in startup.cs since the though behind this method is to configure the http pipeline, and the custom middleware wouldn't be using httpcontext in any way aside from invoking "next".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
>only shows an example for configuring the .net client for a forms app

That's not correct. The sample code is all from an ASP.NET Core app.

Per the doc:

> The following `Startup.Configure` method adds middleware components for common app scenarios:
