### ISSUE TITLE
UseCookiePolicy together with Facebook, Google login

### ISSUE THREAD

**Issue by vovikdrg** [aspnet/Docs#10591]
Please provide more information how to use cookie policy with external logins.

Currently if I apply cookie policy I am getting correlation error. It looks like that user must accept cookie and only after that they will be able to login with external login

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
* Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
* Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/gdpr.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@vovikdrg 	I think that's correct. @HaoK 	is that correct? Should we document you must accept cookie policy before you can use an external login?

**Comment by HaoK** [comment]
Yes if you don't accept cookie policy, all bets are off and lots of things won't work, and aren't expected to work
