### ISSUE TITLE
Initial example, are there errors?

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [aspnet/Docs#10600]
I see that the method CreateAsync is calling CreatedAtAction, but with the name of GetByIdAsync.  Shouldn't it be nameof(CreateAsync)?

And isn't the ModelState.IsValid check obsolete as explained a few paragraphs later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
> I see that the method CreateAsync is calling CreatedAtAction, but with the name of GetByIdAsync. Shouldn't it be nameof(CreateAsync)?

Think of `nameof(GetByIdAsync)` as a pointer to the HTTP GET action which is capable of retrieving the newly created pet in this HTTP POST action. It's used by ASP.NET Core to generate a `Location` header in the HTTP response.

> And isn't the ModelState.IsValid check obsolete as explained a few paragraphs later?

That `ModelState.IsValid` check is unnecessary ONLY when using the `[ApiController]` attribute.

**Comment by ZombiesWithCoffee** [comment]
Thanks for the explanation.  At this point int he Web API documentation, CreatedAtAction wasn't yet defined and looked strange there.  :)

**Comment by scottaddie** [comment]
We talk about this in our web API tutorial; however, I see the explanation there is incorrect. Working on a fix for that right now.

**Comment by Rick-Anderson** [comment]
> That `ModelState.IsValid` check is unnecessary **ONLY** when using the `[ApiController]` attribute.

The sample is using `[ApiController]` 

- remove the unnecessary code and rewrite the **Automatic HTTP 400 responses** paragraph. 
- Explain how to disable auto validation.
- Add a link to **Automatic HTTP 400 responses** in  #8951 and close both issues.
