### ISSUE TITLE
CORS instructions don't work

### ISSUE THREAD

**Issue by tala9999** [aspnet/Docs#10623]
I think the author didn't test their code. Per the author, we need to do at least 2 things:
1. Register CORS services:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors();
}

```
2. Enable CORS, for example with middle ware:
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseCors(builder =>
       builder.WithOrigins("http://example.com"));
}

```
However, the above instruction and code never works for me.

This works for me:
1. AddCors
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("ScormStorageCors",
                    builder => builder.AllowAnyOrigin()
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials());
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }
```

2. Use Cors in Configure
```

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseCors("ScormStorageCors"); // This will apply cors to all controllers or methods
    // if you want apply cors to some controllers or methods, there are two ways:
    // 1. remove this app.UseCors and declare cors as step #3 below
    // 2. keep app.UseCors, but apply [DisableCors] to controllers or methods

}
```

3. Add policy to controller or method
```

    [Route("api/[controller]")]
    [ApiController]
    [EnableCors("ScormStorageCors")]
    public class ValuesController : ControllerBase
    {
     //..... code here
    }
```

Also, if you are using Postman tool to test, make sure you add "Origin" header to the request, the value can be the URL of the the current API (e.g. http://localhost:15349) or "*". Without this, the response will not return "Access-Control-Allow-Origin" header.

Hope this helps.

@Rick-Anderson 	edit: 24.4 K PV, 69% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@spboyer 	please review.

**Comment by Rick-Anderson** [comment]
@tala9999 per the doc:

Specifying `AllowAnyOrigin` and `AllowCredentials` is an insecure configuration and can result in cross-site request forgery.

**Comment by Rick-Anderson** [comment]
1. Register CORS services:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors();
}

```

The author is not saying that's all you need to do.

I'll change it to:
```
public void ConfigureServices(IServiceCollection services)
{

    services.AddCors(options =>
     {
         options.AddPolicy("AllowSpecificOrigins",
         builder =>
         {
             builder.WithOrigins("http://example.com",
                                 "http://www.contoso.com");
         });
     });

    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
```

**Comment by tala9999** [comment]
> The author is not saying that's all you need to do.

`
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors();
}
`

This is the only thing mentioned in "Register CORS services" section. So even the author is not literally saying that, a lot of people think that's all they need to do. It should be changed. Check in stackoverflow to see how many people are not able to make Cors work based on this instruction.
