### ISSUE TITLE
Titles are not the same

### ISSUE THREAD

**Issue by dojademake** [aspnet/Docs#10622]
The statement "Pages/Index.cshtml and Pages/Movies/Index.cshtml currently have the same title, ..." is not true since by default the Pages/Index.cshtml title is set to "Home page" in Core 2.2:

ViewData["Title"] = "Home page";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by dojademake** [comment]
Also the "decimal commas in the Price field" purple section just below this seems a little out of place with the flow of the document.

**Comment by Rick-Anderson** [comment]
Fixed, thanks for pointing this out.
