### ISSUE TITLE
For Linux and Mac, rename folder "Todo" to "ToDo"

### ISSUE THREAD

**Issue by JulioJu** [aspnet/Docs#10636]
Contrary to Razor page, "View discovery relies on finding view files by file name. If the underlying file system is case sensitive, view names are probably case sensitive." https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.2 

Therefore, following folders should be renamed `ToDo` (with an uppercase `D`). 
1. https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/views/view-components/sample/StarterViewComp/Views/Todo 
2. https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/views/view-components/sample/ViewCompFinal/Views/Todo
3. Corresponding quote of this folder should be changed at https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md

Otherwise on Linux, (and probably on Mac) we have errors

```
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/ToDo/Index.cshtml
/Views/Shared/Index.cshtml
```

If you want I could make a PR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> If you want I could make a PR

That would be fantastic.
