### ISSUE TITLE
Suggestion to add two notes

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10645]
I suggest adding the following note boxes or similar. You may ignore this if you think the notes are not important. Thanks:

  > [!NOTE]
  > If the image path has one or more parameters, a ```v``` parameter will be appended to them. The image tag helper will manage adding the & character appropriately after the existing parameters. However, avoid using a v parameter because you will end up having multiple v parameters in the image path.
 
  > [!NOTE]
  > The image file needs only to be accessible on the server. It's not necessary to be detectable by the tilde character in the editor. You can use a string to represent the image and the version parameter will be appended if the image path exists on the server at run time. For example: ```<img src="@("/images/asplogo.png")" asp-append-version="true" />``` is valid provided that the image exists on the server. This is useful when the image path is stored in a database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f09866f1-f286-b98c-1073-e402a10f35d3
* Version Independent ID: 18653de6-49b6-3f75-0392-b5eba55145ad
* Content: [Image Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/image-tag-helper?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/image-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	 I don't think we need the `v` param note.

@shadinamrouti 	wrote:

You can use a string to represent the image and the version parameter will be appended if the image path exists on the server at run time. For example: ```<img src="@("/images/asplogo.png")" asp-append-version="true" />``` is valid provided that the image exists on the server. This is useful when the image path is stored in a database.

@pkellner @NTaylorMullen 	should we include a note like that?

**Comment by NTaylorMullen** [comment]
> should we include a note like that?

Eh, it's a bit too technical if you ask me. Even though the notes are true, most users wont need to care about that level of information.

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	thanks for the suggestions. This information is discoverable from the closed issues link on that page.

**Comment by shadinamrouti** [comment]
@Rick-Anderson & @NTaylorMullen 
I agree with both of you. Thanks for the valuable feedback.
