### ISSUE TITLE
Documentation uses ProducesResponseType with numeric codes

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [aspnet/Docs#10642]
I'm noticing that a lot of your documentation, uses magic numbers for the ProducesResponseType attribute.   Your Analyzer uses the StatusCodes enumeration, which I would assume, should be preferred.

[ProducesResponseType(404)]
[ProducesResponseType(StatusCodes.Status404NotFound)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by bartlannoeye** [comment]
Was surprised to see integers instead of status codes (linking sample for my colleague), took the liberty of sending a PR.
