### ISSUE TITLE
[N00b problem] Movies folder "page not found"

### ISSUE THREAD

**Issue by ferdinandtrommsdorff** [aspnet/Docs#10643]
Hello all,
I have performed this tutorial from the start on (creating all sources by myself). It compiles and site is available. After creating the initial db and the scaffolded items, I want to test the "Movies" page. I tryto navigate to "localhost:xxx/Movies" or "localhost:xxx/movies". I get the error "page not found".
I am a beginner with asp.net. Do I miss some site routing? The folder is there in my sources, containing "index.cshtml", "edit", and so on.
Thanks for your help,
Ferdinand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#pmc)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Start debugging and check your steps.

**Comment by bhuvanesh-dev** [comment]
After following the steps we didn't get any controllers from scaffolding, where do we start the debugging?

**Comment by Rick-Anderson** [comment]
You don't get controllers in Razor Pages.

**Comment by bhuvanesh-dev** [comment]
Thanks for the info, Any idea where to start debugging?

**Comment by spletnipopotnik** [comment]
Did yo create the "Movie" folder in the "Pages" folder?
