### ISSUE TITLE
A suggestion to delete a sentence 

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10646]
I suggest to delete the last sentence in the following paragraph because the ```model``` attribute was not mentioned before which makes a misunderstanding and because the same sentence is already there in the paragraph titled **model**.

> 
> **for**
> ... default inference behavior is overridden by using the @ symbol to define an inline expression. ~The for attribute can't be used with the model attribute.~
> 
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4c23ba-19f6-d847-fefa-a61e283d5fde
* Version Independent ID: e7df465a-5f3b-1522-b2d9-5e3afbf74257
* Content: [Partial Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	can you make that PR?

**Comment by shadinamrouti** [comment]
@Rick-Anderson , it's done. You can thankfully proceed with the merge.
