### ISSUE TITLE
Great documentation - is there anything more in-depth for a wider range search?

### ISSUE THREAD

**Issue by Webbarrr** [aspnet/Docs#10652]
Do you have any online guides / tutorials for setting something up that's more robust in being able to search in a model for multiple search parameters?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No, that's it. But if you keep learning you'll be able to figure that out.
