### ISSUE TITLE
Include Mocking HTTP Requests using either HttpContext or HttpClient

### ISSUE THREAD

**Issue by CoderKooke** [aspnet/Docs#10655]
Thank you for the documentation above but could you also include how you would mock the POST and GET calls that these methods would expect.  Ideally using Moq with either HttpRequest or HttpClient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.2#test-actionresultt)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @CoderKooke ... I've added this to the Integration Testing project, where the engineers will look and determine how to handle your request.

In the meantime while the engineers take a look, search around the Net ... there are blog posts and GH issues that discuss working with `IHttpClientFactory` and `HttpMessageHandler` in tests.

**Comment by danroth27** [comment]
Let's handle this one as part of #7847
