### ISSUE TITLE
Upgrade view-components samples to 2.2 instead of 2.0

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10657]
@Rick-Anderson 	edit: 11 KPV, 88% CSAT.

1. I suggest to upgrade the [samples of view components](https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/views/view-components/sample) to 2.2 instead of 2.0.

2. I suggest to use the following 2.1 clean way to seed data instead of using a separate SeedData.cs file which also requires additional advanced code to be added to Program.cs:

  ```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
      for (int i = 0; i < 9; i++)
            {
                modelBuilder.Entity<TodoItem>().HasData(
                   new TodoItem
                   {
                       IsDone = i % 3 == 0,
                       Name = "Task " + (i + 1),
                       Priority = i % 5 + 1
                   });   
            }
 }
```

**Note**
Using the above method of seeding does not need lots of work as the DB is in-memory and the seeding process was not referenced in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sample upgrades are tracked by https://github.com/aspnet/Docs/issues/5495. In case you want to work on this, we typically mirror all of the changes in the template when a sample is upgraded, but they'll advise further on that point.

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	would you be able to PR this?
