### ISSUE TITLE
Error in default trusted proxies

### ISSUE THREAD

**Issue by Zenexer** [aspnet/Docs#10651]
> Only proxies running on localhost (127.0.0.1, [::1]) are trusted by default

This is incorrect.  There is one entry in KnownProxies by default: [::1].  There is one entry in KnownNetworks by default: 127.0.0.1/8.  This means that all loopback addresses (127.0.0.0/8 and [::1]) are allowed by default, not just the two addresses listed in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti

**Comment by Zenexer** [comment]
@guardrex I can make a PR to fix this. Will that speed things up, or is it not worth the trouble? There are a bunch of other minor Nginx confit issues I can fix as well (in a separate PR).

**Comment by guardrex** [comment]
I recommend listing the updates here first for @shirhatti to inspect. It will save time if he declines any of the changes

**Comment by guardrex** [comment]
@shirhatti Do you want to go forward with a change on this one?

**Comment by shirhatti** [comment]
@Tratcher ?

**Comment by Tratcher** [comment]
Technically accurate, but I've never seen any 127.0.0.0/8 address used except 127.0.0.1. Did you find a scenario where this distinction is meaningful?

**Comment by guardrex** [comment]
In case we don't get an answer, how about ...

> Proxies running on loopback addresses (127.0.0.0/8, [::1]), which includes the standard localhost address (127.0.0.1/32), are trusted by default.

**Comment by Tratcher** [comment]
Seems fine if you drop the `/32`, most people don't know what that means.

**Comment by Zenexer** [comment]
@Tratcher 

> Technically accurate, but I've never seen any 127.0.0.0/8 address used except 127.0.0.1. Did you find a scenario where this distinction is meaningful?

Yes, use of other 127.0.0.0/8 addresses is very common on Linux.  Debian-based distros use 127.0.1.1 quite a bit out-of-the-box.  If you initialize an Ubuntu installation with default settings and a hostname of `ubuntu`, `/etc/hosts` will contain something like this:

```
127.0.0.1 localhost
127.0.1.1 ubuntu
```
