### ISSUE TITLE
Didn't mention to Import Entity Framework in the dependencies

### ISSUE THREAD

**Issue by minaShaker** [aspnet/Docs#10653]
This tutorial is for new to .Net Core, but some people (like me) are new to the .Net as general

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2

**Includes all supported packages by the Entity Framework Core team except those that contain third-party dependencies (other than those previously mentioned)**.

What version of the .NET SDK are you using. What error did you get?

**Comment by PSCRIMS** [comment]
I am new to ASPNetCore and I do like the tutorial, I'm trying to learn by myself, and after buying a couple of books and not being able to recreate the environment which was used to demonstrate the features of NetCore, I come to appreciate something that works when I follow in Visual Studio. That said I have a question about the placement of the following  code, is it a standalone C# or is it to be added to another code?


using Microsoft.EntityFrameworkCore;

namespace RazorPagesMovie.Models
{
    public class RazorPagesMovieContext : DbContext
    {
        public RazorPagesMovieContext (DbContextOptions<RazorPagesMovieContext> options)
            : base(options)
        {
        }

        public DbSet<RazorPagesMovie.Models.Movie> Movie { get; set; }
    }
}

**Comment by PSCRIMS** [comment]
Never mind you did mention RasorPagesMovieContext.cs
