### ISSUE TITLE
There are external links from non-authoritative sources

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10668]
The article has links from a non-authoritative source. See the first two links in the first paragraph, namely, (Separation of Concern), and (Single Responsibility Principle) and others.
I suggest to redirect them to relevant Wikipedia articles.

cc/ @Rick-Anderson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b26c2a-d481-043c-e37b-cbe3ad427d41
* Version Independent ID: d7d85488-c055-7aea-0664-2e97bc937a04
* Content: [Overview of ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/overview.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I've been replacing these with relevant section links from Steve's other work (on the Docs) ...

https://docs.microsoft.com/dotnet/standard/modern-web-apps-azure-architecture/architectural-principles

@shadinamrouti Just a bit of history here: Steve Smith (@ardalis) wrote and worked on many topics here. Those links actually are *authoritative*, but it's a relative term in regards to MS's own topics. Of course, MS doc links are best, and that's what we try to do. It so happens that he wrote on (or completely wrote) all three: the overview, the DevIQ site, and the architectural principles topic.

**Comment by Rick-Anderson** [comment]
We'll look at removing these in the next doc sweep. We do look at closed issues on a doc sweep.

**Comment by Rick-Anderson** [comment]
We have very few non-authoritative. The non-authoritative links we use have been reviewed and deemed reliable and helpful to the content.
