### ISSUE TITLE
DB를 업데이트 하는 부분의 예시가 부족합니다.

### ISSUE THREAD

**Issue by LisandroSu** [aspnet/Docs#10662]
@kimkyeseung commented on [Mon Jan 28 2019](https://github.com/aspnet/Docs.ko-kr/issues/124)

```_books.ReplaceOne(book =&gt; book.Id == id, bookIn);```
이 부분이 DB를 업데이트 하는 예제의 전부입니다.

사용자가 응용을 하게되면 collection의 Boolean값을 반대로 바꾸거나 Array인 데이터에 새 값을 push 하는 경우가 생기는데, ReplaceOne 말고도 다양한 방법으로 DB를 Update하는 방법을 설명해주셨으면 좋겠습니다.
감사합니다.

```_books.ReplaceOne(book =&gt; book.Id == id, bookIn);```
This is all of the examples that update the DB. When the user applies, User may change the boolian value of the collection in reverse or push a new value to the Array data. I would like you to explain how to update the DB in various ways besides ```ReplaceOne```. 
Thank you.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [ASP.NET Core 및 MongoDB를 사용하여 웹 API 빌드](https://docs.microsoft.com/ko-kr/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/docs.ko-kr/blob/live/aspnetcore/tutorials/first-mongo-app.md)
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Duplicate of #10663
