### ISSUE TITLE
You cannot apply assembly-level attributes to a class

### ISSUE THREAD

**Issue by Carl-Hugo** [aspnet/Docs#10665]
The doc states: **As a recommendation, apply assembly-level attributes to the `Startup` class.**
Based on my understanding, you cannot apply assembly-level attributes to a class.
I think that should instead read: **As a recommendation, apply assembly-level attributes in the `Startup.cs` file.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by pranavkm** [comment]
Feel free to edit the doc, if that reads better. The intent was to suggest doing this:

```C#
[assembly: ApiConventionType(typeof(DefaultApiConventions))]
namespace ApiConventions
{
    public class Startup
    {
```
