### ISSUE TITLE
Add an external link for a definition

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10661]
I suggest to add [this external link](https://deviq.com/magic-strings/) to the term "magic string" to explain it.

**Note** 
The above domain seems reputable in other Microsoft Docs articles, see how **Separation of Concern** is linked in the top of **MVC overview** [article](https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2#avoiding-magic-strings)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We generally don't allow external links from non-authoritative sources. We also don't like to use jargon like "magic string". It's easily googleable, but a link would be nice.

cc @tdykstra 	@scottaddie 	
Given we haven't had any complaints, I'm inclined to leave it without a link.

**Comment by tdykstra** [comment]
We could change "avoiding magic strings" to something like "compile-time name validation"
