### ISSUE TITLE
Select another culture

### ISSUE THREAD

**Issue by andrestalavera** [aspnet/Docs#10670]
I've tried to use _SelectLanguagePartial.cshtml, but is dosn't work: only the current culture was displayed in the select list.
I've wrote this code:

````CSharp
/* startup class */
ConfigureService(IServiceCollection services)
{
    services.AddLocalization(o =&gt; o.ResourcesPath = "Resources");
    services.AddMvc(o =&gt; o.Conventions.Add(new RouteTokenTransformerConvention(new SlugifyParameterTransformer(services.BuildServiceProvider()));
    .AddDataAnnotationsLocalization(o =&gt; o.DataAnnotationLocalizerProvider(type, factory) =&gt; factory.Create(typeof(SharedResources))
    .AddViewLocalization()
    .AddMvcLocalization()
    .AddCompatibilityVersion(CompatibilityVersion.Version_2_2);
}
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You need to set the `RequestLocalizationOptions` per the doc.

```
private const string enUSCulture = "en-US";

services.Configure<RequestLocalizationOptions>(options =>
{
    var supportedCultures = new[]
    {
        new CultureInfo(enUSCulture),
        new CultureInfo("fr")
    };

    options.DefaultRequestCulture = new RequestCulture(culture: enUSCulture, uiCulture: enUSCulture);
    options.SupportedCultures = supportedCultures;
    options.SupportedUICultures = supportedCultures;

    options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(async context =>
    {
        // My custom request culture logic
        return new ProviderCultureResult("en");
    }));
});
```
