### ISSUE TITLE
Model Validation: Top-level node validation

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#10675]
@smarts says on [aspnet/Docs \#10264](https://github.com/aspnet/Docs/issues/10264#issuecomment-458395892) ...

&gt; Thanks for adding this @Rick-Anderson , but the docs now incorrectly state that `MvcOptions.AllowValidatingTopLevelNodes` is `true` by default and can be disabled, but that's only true if the compatibility version is set to `CompatibilityVersion.Version_2_1`, which does not match the example. If the compatibility version is `CompatibilityVersion.Version_2_2` (as in the example), then the property must be explicitly set to `true`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2#top-level-node-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It was based on the API and testing locally. I was going by this ...

> The default value is \<see langword="true"/> if the version is \<see cref="CompatibilityVersion.Version_2_1"/> or later; \<see langword="false"/> otherwise.

... and then for 2.0 it states ...

> If the application's compatibility version is set to \<see cref="CompatibilityVersion.Version_2_0"/> then this setting will have the value \<see langword="false"/> unless explicitly configured.

... and then a 2nd remark on '2.1 or later' ...

> If the application's compatibility version is set to \<see cref="CompatibilityVersion.Version_2_1"/> or higher then this setting will have the value \<see langword="true"/> unless explicitly configured.

It's the "or later" and "or higher" parts in those two statements that I picked up on. Besides, it worked in testing. It was **_15 years ago in .NET Core time_** lol (i.e., 2 weeks :smile:); but IIRC, it worked without explicitly setting the value.

Do we need to ping engineering? Let's **_NOT_** unless we can't help it ... they're crazy busy. 🏃 

Cross-ref: https://github.com/aspnet/Mvc/blob/65af12f1f575fdaee893e0232416df29bb83d7fa/src/Microsoft.AspNetCore.Mvc.Core/MvcOptions.cs#L194-L221

**Comment by smarts** [comment]
It's possible that I misunderstood compatibility defaults. I assumed that the compatibility version defaults [if unset] to whichever version of ASP.NET Core MVC you're targeting (i.e., the package version), which for my case was 2.2.*. If that's not the case then the documentation is probably right.

**Comment by guardrex** [comment]
I didn't chat with engineers about this. I was going off the API and sample app. When you run into a problem and the guidance seems wrong, you're right to ask. Truly ... 👽 *Strange Things*:tm: 👽 can happen when I work on a topic without direct engineering guidance! :smile: lol
