### ISSUE TITLE
There was an error running the selected code generator: ' value cannot be null parameter: type'

### ISSUE THREAD

**Issue by minaShaker** [aspnet/Docs#10681]
after clicking new -&gt; Scaffolded item
and finishing the steps, and clicking add on the Razor dialog.
an error pop up saying:
 There was an error running the selected code generator: ' value cannot be null parameter: type'

please note that this error don't show if I remove the navigation property "ICollection&lt;Enrollment&gt; Enrollments "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Can you file an issue on the Microsoft Developer Community instead of here? This can be accomplished from Visual Studio by clicking on Help > Send Feedback, and choosing the appropriate action.

Include the output of `dotnet --version`
