### ISSUE TITLE
Instructions followed exactly still lead to errors (even if Google+ API is enabled)

### ISSUE THREAD

**Issue by samboustani** [aspnet/Docs#10684]
**You must enable Google+ API and then create credentials for that API before it will work.  Otherwise, you will get the error below.**

An unhandled exception occurred while processing the request.
HttpRequestException: An error occurred when retrieving Google user information (Forbidden). Please check if the authentication information is correct and the corresponding Google+ API is enabled.
Microsoft.AspNetCore.Authentication.Google.GoogleHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler&lt;TOptions&gt;.HandleRequestAsync()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I'll also add this to the tracking issue for a look :eyes:. https://github.com/aspnet/Docs/issues/1470

... something else came to mind. There was some talk of Google+ auth changing ... depreciated? We should track down that engineering issue and see what's what.

**Comment by GBPhilip** [comment]
With google+ I have the code in c#. Is there a c# version for the new google authentication

**Comment by guardrex** [comment]
There was some talk about that approach on that issue. I think the issue was in aspnet/AspNetCore repo issues, but I'm not 100% sure about that. It might be elsewhere in the engineering repos. The issue discusses the depreciation of Google+ and some alternative ways to deal with Google auth.

I'm 🏃 at the moment and can't look, but I'll come back later and see if I can find that issue and post the link here.

**Comment by guardrex** [comment]
@GBPhilip **Found it!** (actually, it wasn't that hard to track down ... it was in the aspnet/AspNetCore repo issues). See ......

https://github.com/aspnet/AspNetCore/issues/6486

**Comment by GBPhilip** [comment]
Thanks, now I need to work out how to make sure I google + api so when I test it I know it is going to the right place.

**Comment by Rick-Anderson** [comment]
It's in the first paragraph.

For more information and temporary mitigations for ASP.NET Core, see this GitHub issue. This tutorial has been updated with the new setup process.
