### ISSUE TITLE
CORS issue when running CRA server independently.

### ISSUE THREAD

**Issue by prkhandelwal** [aspnet/Docs#10695]
When running the CRA server independently, there are issues in fetching the api dur to CORS policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.2&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by SteveSandersonMS** [comment]
This issue is mistaken. I think you must be pointing your browser to the external dev server. You shouldn't do that - instead, point it to the ASP.NET Core application which proxies to the dev server on your behalf. Then it's all one site and CORS doesn't come into it.
