### ISSUE TITLE
Transports missing

### ISSUE THREAD

**Issue by KingHippoSE** [aspnet/Docs#10705]
HubOptions&lt;T&gt; seems to be missing .Transports
Has to be set on HttpConnectionDispatcherOptions like 
app.UseSignalR(configure =&gt;
{
    configure.MapHub&lt;Hub&gt;("/MyHub", options =&gt; 
    {
           options.Transports = HttpTransportType.ServerSentEvents | HttpTransportType.LongPolling;
    });
})

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
@KingHippoSE - I read through this and reproduced code that I think replicated the issue being reported. This code, below, shows how `HubOptions` fails to offer a `Transport` property in both scenarios.

```csharp
public class NormalHub : Hub { }
public class StronglyTypedHub : Hub<IHubInterface> { }
public interface IHubInterface { }
public class Startup
{
     public void ConfigureServices(IServiceCollection services)
     {
         services.AddSignalR()
                 .AddHubOptions<NormalHub>(options => 
                 {
                     // options.Transports doesn't exist here
                 });

         services.AddSignalR()
                 .AddHubOptions<StronglyTypedHub>(options => 
                 {
                     // or here
                 });
      }
}
```

As you pointed out, the `HttpConnectionDispatcherOptions` is where one would configure the desired Transports. So I extended the code to include this: 

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseSignalR((configure) => 
    {
        var desiredTransports = 
            HttpTransportType.WebSockets |
            HttpTransportType.LongPolling;

        configure.MapHub<NormalHub>("/normalhub", (options) => 
        {
            options.Transports = desiredTransports;
        });

        configure.MapHub<StronglyTypedHub>("/stronglytypedhub", (options) => 
        {
            options.Transports = desiredTransports;
        });
    });
}
```

So, like with `services.AddSignalR...`, this part is also consistent. In a sense, "a hub is a hub." 

However, I totally see the issue - the discussion of `HttpConnectionDispatcherOptions` is directly after the discussion of `AddHubOptions`. So, it seems like the best course of action would be to show the code for my example `Configure` method in between the `AddHubOptions` and the `HttpConnectionDispatcherOptions` table. 

![image](https://user-images.githubusercontent.com/41929050/52400654-97a11500-2a74-11e9-8061-f6db4dd9ff0f.png)

Is my assumption correct? Also, would this be a good method of resolving this and providing more information on this facet of configuration?

**Comment by KingHippoSE** [comment]
Oh now I see what line I missed in the documentation. I think the new version with the code explains it well! Thanks!

**Comment by bradygaster** [comment]
@KingHippoSE no problem! i could totally see why the confusion arose. The doc switched from the context of `ConfigureServices` to `Configure` without warning. :)
