### ISSUE TITLE
IIS Express / Windows Authentication

### ISSUE THREAD

**Issue by brubakerjeff** [aspnet/Docs#10710]
Under "Enable Windows Authentication with IIS"

"Provide a local web.config file that activates Windows Authentication on the server when the app is deployed."

Is it possible to be more specific for where to place web.config? Additionally, is there any affect when using IISExpress?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @brubakerjeff ... That remark isn't linked down in the topic to the section where it's described, but fast-forward to the section that pertains to that remark ... https://docs.microsoft.com/aspnet/core/security/authentication/windowsauth#development-side-configuration-with-a-local-webconfig-file

WRT IIS Express ... The `iisSettings` in *launchSettings.json* are honored (`"windowsAuthentication": true,`) ...

```json
{
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:17349",
      "sslPort": 44391
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
...
```

I'll see if I can do a touch of work here to improve it. Thanks for asking.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
