### ISSUE TITLE
Do these contradict?

### ISSUE THREAD

**Issue by dumbledad** [aspnet/Docs#10720]
> CreateDefaultBuilder calls AddUserSecrets when the EnvironmentName is Development. 

> When CreateDefaultBuilder isn't called during host construction, add the user secrets configuration source with a call to AddUserSecrets in the Startup constructor  

    if (env.IsDevelopment())
    {
        builder.AddUserSecrets&lt;Startup&gt;();
    }

From the text it sounds like we need to add that line of code when the environment **is not** development, but the code snippet adds it when the environment **is** development. Which is correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @dumbledad ... The reader shouldn't retain a condition regarding the environment from the first paragraph into the second paragraph and assume the inverse applies. Since the second paragraph doesn't remark on the environment, I can see how that would happen. I'll clarify it. Thanks for asking.
