### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by kleinepannekoek** [aspnet/Docs#10721]
Hi! I'm trying to create a Scaffolding Item in a solution that already has multiple Scaffolding Items in it (so it should be possible, you'd think). After clicking "add", I get the following error

could not load file or assembly microsoft.entityframeworkcore,version2.0.3.0, culture=neutral, publickeytoken=adb9793829ddae60
the located assemblys manifest definition does not match the assembly reference.
exception from hresult 0x80131040

Does this mean the git-project I cloned was written in another version of VS? What can I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You can add multiple scaffolded projects. The error doesn't have anything to do with scaffolding. Can you build the project? 2.0 is an old version. Do you have the 2.0 SDK installed?

**Comment by kleinepannekoek** [comment]
I had 2.2 installed first, but later I installed the later version 3.0. Both give the same message.

**Comment by Rick-Anderson** [comment]
Yes, it's looking for the 2.0 version. 
Can you build the project?

**Comment by Rick-Anderson** [comment]
Or update to 2.2

**Comment by kleinepannekoek** [comment]
Yes I can build the project that I cloned, I just can't add a scaffolded item (and possibly oher items) and other versions of .NET CORE don't seem to solve the problem - it does seem to have something to do with Entity Framework but I dont know how to solve it. Here is some additional information that I get

Attempting to figure out the EntityFramework metadata for the model and DbContext: 'AP_Monitoring'
Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design, Version=2.0.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

**Comment by Rick-Anderson** [comment]
Installing other versions won't help. You need to either install the correct 2.0 SDK or upgrade the project references in the .csproj file.
