### ISSUE TITLE
Fix broken builds

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10735]
Broken build with error:

Git repo encounters case-sensitivity conflicts because the repo contains files with name only differing in casing. Please fix the casing conflicts and try building again. Note that if you are working on a Pull Request, please fix the target branch first if the target branch contains casing conflicts. Detected casing conflicts are with following files: aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml

**Comment by Rick-Anderson** [comment]
Fix was to remove the following red dot
![image](https://user-images.githubusercontent.com/3605364/52099331-da478680-2576-11e9-87d4-c4b7d14ce7b9.png)

**Comment by Rick-Anderson** [comment]
@JulioJu  see this fix I needed to make.

@guardrex 	what's that red character?

**Comment by guardrex** [comment]
It's ye olde Byte Order Mark. It should be harmless.

**Comment by JulioJu** [comment]
@Rick-Anderson @guardrex 

Just for info:

> Microsoft compilers[9] and interpreters, and many pieces of software on Microsoft Windows such as Notepad treat the BOM as a required magic number rather than use heuristics. These tools add a BOM when saving text as UTF-8, and cannot interpret UTF-8 unless the BOM is present or the file contains only ASCII. Google Docs also adds a BOM when converting a document to a plain text file for download. 

https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

With the GNU tool `file`, I've tested, the file aspnetcore/mvc/views/razor/sample/Views/Home/Contact.cshtml contains only ASCII characters, therefore no problems for character encoding when a Windows user will open this file.
