### ISSUE TITLE
Single policy with multiple requirements

### ISSUE THREAD

**Issue by christiansk** [aspnet/Docs#10736]
It's not clear how a single policy with multiple requirements will work. Do all requirements have to pass, or is a single one enough? In other words, does it work like an "AND" or an "OR" between the requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See What should a handler return?
at https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2#what-should-a-handler-return

**Comment by Rick-Anderson** [comment]
If one handler returns `context.Succeed` and no handler returns `context.Fail`, it succeeds.

If any handler returns `context.Fail`, it fails.

Return `Task.CompletedTask` when requirements aren't met. `Task.CompletedTask` is neither success or failure—it allows other authorization handlers to run.

I suppose I could add that to the doc.

@blowdart 	are you OK with me adding that to the doc?

**Comment by christiansk** [comment]
O don't think you need to add that to the docs, it's already well explained. But it all refers to a *single requirement with multiple handlers*.

My question is about a *single policy with multiple requirements*, a completely different matter.

**Comment by blowdart** [comment]
Ah, for a policy with multiple requirements *all* _requirements_ must pass for the policy to pass.

**Comment by Rick-Anderson** [comment]
@christiansk 	would you be able to create a PR to add that information? Use [this link](https://github.com/aspnet/Docs/edit/master/aspnetcore/security/authorization/policies.md) to edit in the browser.

**Comment by christiansk** [comment]
Yes, glad to help. I just submitted the PR.

**Comment by Rick-Anderson** [comment]
Fixed in #10754
