### ISSUE TITLE
Static files and IIS considerations

### ISSUE THREAD

**Issue by leonardlabat** [aspnet/Docs#1074]
Hello

The IIS considerations section in the static files page is referring to an obsolete method (**RunIISPipeline**). I think that this whole section should be updated to reflect the beta8 hosting model update.

Link to section I'm talking about :
https://docs.asp.net/en/latest/fundamentals/static-files.html#iis-considerations

If nobody has started working on this specific point, I can write the update and send a PR.

Thanks

**Comment by danroth27** [comment]
@leonardlabat Thanks for bringing this to our attention! A PR for this would be great.

**Comment by danroth27** [comment]
@Tratcher
