### ISSUE TITLE
Resolved: Chrome ERR_INVALID_HTTP_RESPONSE and ERR_HTTP_1_1_REQUIRED

### ISSUE THREAD

**Issue by TJSoftware** [aspnet/Docs#10753]
I normally use Chrome for debugging and I initially received an 'ERR_INVALID_HTTP_RESPONSE' only with Chrome. Upgrading to the latest version (71.0.3578.98) resolved that issue. Then I saw the ERR_HTTP_1_1_REQUIRED. I found the solution on https://github.com/aspnet/AspNetCore/issues/4398. Add the following code to your startup.cs class.

app.Use(async (ctx, next) =&gt;
{
  await next();
  if (ctx.Response.StatusCode == 204)
  {
    ctx.Response.ContentLength = 0;
  }
});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Tribalnecktie** [comment]
Great tutorial. Helped me get set up to learn some new things.

**Comment by Rick-Anderson** [comment]
Per `@jkotalik` 	**[Here](https://github.com/aspnet/AspNetCore/issues/4398#issuecomment-452548971)**  *This should now be fixed in the latest release of 2.2.*
