### ISSUE TITLE
Remove NuGet article stub

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1075]
We should just point to http://docs.nuget.org.

**Comment by danroth27** [comment]
https://docs.asp.net/en/latest/conceptual-overview/nuget.html

**Comment by daneb** [comment]
Would you consider if I wrote a short tutorial that covers the basics (CRUD),  that is 1) install 2) delete 3) update and 4) restore and then for further information reference http://docs.nuget.org?

**Comment by danroth27** [comment]
The NuGet related docs are moving to the [.NET Core docs](https://dotnet.github.io) and the existing [NuGet docs](http://docs.nuget.org). Closing this as we already removed the NuGet doc stub in our dev build (see https://docs.asp.net/en/dev/conceptual-overview/index.html).
