### ISSUE TITLE
Section 7. Run the App

### ISSUE THREAD

**Issue by Kaelum** [aspnet/Docs#10755]
This section states that it should be possible to use HTTP.sys w/o an Administrator account if you use localhost and any port above 1024.  However, I have not been able to get it to work at all, unless running under an Administrator account.  Is this section wrong?  If not, why doesn't it work as described?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e347c54-6a6a-d685-4af7-39b023bf7f15
* Version Independent ID: 41aa77f5-9466-6580-5ec6-b1bf97bd0f01
* Content: [HTTP.sys web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/servers/httpsys.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/httpsys.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@Tratcher

**Comment by Tratcher** [comment]
@Kaelum what address do you pass in at startup? Try `http://localhost:5000/`.

**Comment by Kaelum** [comment]
@Tratcher that is the url I was using, but no matter what I tried, it wouldn’t work.  I rebooted my system a few times, and no change, so I went home for the day.  The next morning, it just worked w/o any changes.  I havdn’t tried making any changes to the urls since, as I don’t want to break it, and I don’t have any extra time right now.

**Comment by Tratcher** [comment]
Glad it's working for you. Closing this until anyone can provided more information.
