### ISSUE TITLE
IHostingStartup Overrides User Code Instead of Other Way Around

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#10785]
From @aodl ...

Relates to https://github.com/aspnet/Docs/issues/6951

Does this statement from MSDN documentation still hold true, since configuration building has been moved out of the Startup class (since core 2.0)?

> IHostingStartup.Configure in the hosting startup assembly is called by the runtime before Startup.Configure in user code, which allows user code to overwrite any configuration provided by the hosting startup assembly.

From this^ I was of the impression that `IHostingStartup` code would be overridable by user code in terms of web host configuration.

The problem I'm having is that although `IHostingStartup.Congifure` gets called early on as suggested, the actual lambda's that I'm passing into things like `.AddConfigureAppConfiguration` don't get called until after the ones defined in the actual app (so the `IHostingStartup` in the external assembly actually overrides the app's configuration instead of the other way around). Is this expected to be the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613ad64e-bc62-edf7-2e86-42210de718f4
* Version Independent ID: aabbbc32-3237-5ef9-c422-892dc6884a22
* Content: [Use hosting startup assemblies in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.2#class-library)
* Content Source: [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/platform-specific-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher

**Comment by Tratcher** [comment]
You're right, callbacks registered by IHostingStartup run after user code. How about calling UseConfiguration rather than AddConfigureAppConfiguration in your IHostingStartup, that will make sure it is applied before AddConfigureAppConfiguration.

**Comment by guardrex** [comment]
@Tratcher I need clarification on a few points ...

1. `AddConfigureAppConfiguration` ... where is that? The API Browser update for 2.2 isn't live yet, and I don't see it in the repos.
1. Should it call out `ConfigureLogging` and `ConfigureServices`, too? If it's the case that delegates registered by all of these go after user code, then it seems like the text should move away from the (misleading) remark:

   > `IHostingStartup.Configure` in the hosting startup assembly is called by the runtime before `Startup.Configure` in user code, which allows user code to overwrite configuration provided by the hosting startup assembly.

   It should say that although the runtime calls the `IHostingStartup.Configure` first, the registered delegates run after those provided by the user, thus the user **can't** overwrite configuration unless the `UseConfiguration` approach is adopted. :point_left: Is that a good synopsis?
1. The sample app is taking this approach. For example ...

   ```csharp
   public class ServiceKeyInjection : IHostingStartup
   {
       public void Configure(IWebHostBuilder builder)
       {
           builder.ConfigureAppConfiguration(config =>
           {
               var dict = new Dictionary<string, string>
               {
                   {"DevAccount_FromLibrary", "DEV_1111111-1111"},
                   {"ProdAccount_FromLibrary", "PROD_2222222-2222"}
               };

               config.AddInMemoryCollection(dict);
           });
       }
   }
   ```
   Should it be using `UseConfiguration` for such a demonstration? ... or should I call it out that such config is going run after user code where these examples appear in the topic?

**Comment by Tratcher** [comment]
1. Typo `AddConfigureAppConfiguration` -> `ConfigureAppConfiguration`
1. The complaint above was that IHostingStartup.ConfigureAppConfiguratrion **was** overriding app config. `UseConfiguration` is applied immediately so it takes effect before the ConfigureAppConfiguratrion callbacks and **can** be overriden by the app.
1. That sample looks fine. Mentioning the ordering would be enough.

**Comment by guardrex** [comment]
`AddConfigureAppConfiguration` :smile: Thought so. Good. 

> The complaint above

Yes, I understand. However, I'm piecing together the reverse of the complaint (and broading to ask about *all delegates* set up by the hosting startup) for what the topic should say about this. Right now, I was leaning toward something like ...

> `IHostingStartup.Configure` in the hosting startup assembly is called by the runtime before `Startup.Configure` in user code. However, delegates registered by `IHostingStartup` (for example, when calling `ConfigureAppConfiguration`) run after user code. To ensure that configuration code that relies on callbacks is executed before user code, call `UseConfiguration` to apply the configuration to the app.
