### ISSUE TITLE
New documentation page contains a link for the wrong Github issue

### ISSUE THREAD

**Issue by tidusjar** [aspnet/Docs#1078]
The following page : http://docs.asp.net/en/latest/mvc/views/dynamic-vs-static.html
contains a link that links to #134 when it should be about Dynamic vs Strongly typed views

**Comment by shirhatti** [comment]
Fixed in 9b30420c1aef5e4970e95bbea1131392760546e1.
Thanks for pointing it out

**Comment by tidusjar** [comment]
Is this blog post I wrote a while ago relevant? 
https://www.jamietech.com/2015/10/14/mvc-view-models-or-viewdata/
