### ISSUE TITLE
IHostingStartup Overrides User Code Instead of Other Way Around

### ISSUE THREAD

**Issue by aodl** [aspnet/Docs#10784]
Relates to https://github.com/aspnet/Docs/issues/6951

Does this statement from MSDN documentation still hold true, since configuration building has been moved out of the Startup class (since core 2.0)?

> IHostingStartup.Configure in the hosting startup assembly is called by the runtime before Startup.Configure in user code, which allows user code to overwrite any configuration provided by the hosting startup assembly.

From this^ I was of the impression that `IHostingStartup` code would be overridable by user code in terms of web host configuration.

The problem I'm having is that although `IHostingStartup.Congifure` gets called early on as suggested, the actual lambda's that I'm passing into things like `.AddConfigureAppConfiguration` don't get called until after the ones defined in the actual app (so the `IHostingStartup` in the external assembly actually overrides the app's configuration instead of the other way around). Is this expected to be the case?

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/Docs/issues/10785.
