### ISSUE TITLE
This article seems to be incorrectly parented in the ToC

### ISSUE THREAD

**Issue by drub0y** [aspnet/Docs#10807]
It's parented under "Use a file watcher" which seems completely unrelated.

![image](https://user-images.githubusercontent.com/284152/52311570-40a81c80-295c-11e9-8ce2-a8c29fbd4864.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f5eb44-55e5-d4a5-0ab1-5122c29a1db5
* Version Independent ID: 0b8da6a7-8333-5d8f-23a5-05bf0ca661f9
* Content: [Factory-based middleware activation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/middleware/extensibility.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/extensibility.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, you're correct @drub0y ... thanks for reporting. We'll get it squared away ASAP.

**Comment by guardrex** [comment]
It's a simple fix ... I'll knock it out @tdykstra and ping u on the PR.
