### ISSUE TITLE
This article seems to be incorrectly parented in the ToC 

### ISSUE THREAD

**Issue by drub0y** [aspnet/Docs#10808]
It's parented under "Use a file watcher" which seems completely unrelated.

![image](https://user-images.githubusercontent.com/284152/52311586-50bffc00-295c-11e9-8a64-c1bc5d646560.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2deb6b4-41be-256b-9569-819f7af5b2fa
* Version Independent ID: ea1db4c0-e8cc-98e8-a235-8c80e9a8f395
* Content: [Middleware activation with a third-party container in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility-third-party-container?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/middleware/extensibility-third-party-container.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/extensibility-third-party-container.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Dup of #10807

**Comment by drub0y** [comment]
Sorry, it's not _exactly_ a dupe, 'cause it's two different articles both with the same problem and I just wanted to make sure to report it for both in case it wasn't obvious. Hope that was clear!
