### ISSUE TITLE
Add example for PUT & DELETE

### ISSUE THREAD

**Issue by YvonneArnoldus** [aspnet/Docs#10821]
I have used the provided template in Visual Studio to create a Web API but the PUT and DELETE method there give an 405 error, when you run those. So it would be nice if this example will show you how to use this.

I'm using asp.net core 2.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
PUT requires you run a GET first. Most people do that. Delete works fine. The tutorial will be updated today.

**Comment by Rick-Anderson** [comment]
@YvonneArnoldus 	see https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio
