### ISSUE TITLE
migrations add Rating doesn't produce incremental change

### ISSUE THREAD

**Issue by phi1ipp** [aspnet/Docs#10823]
the command produced 'create table' output, so `update` threw an exception

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Hi @phi1ipp 
I'm not sure what you did wrong, but the instructions do work.

**Comment by phi1ipp** [comment]
Hi @Rick-Anderson

I finished with installing SQL Server in a docker container and set up connection to it in JSON config, so #10820 is not affecting me any more. Do you need any details about this issue?

**Comment by Rick-Anderson** [comment]
No, can I close this issue now?

**Comment by phi1ipp** [comment]
Well, if you say I should've followed SQLite path instead, then I guess, it might be closed. Still interesting why it didn't produce a diff change for DB for native SQL Server.

**Comment by Rick-Anderson** [comment]
It might be a docker issue, which this tutorial doesn't include. Let me know if you figure it out.
