### ISSUE TITLE
Add Blazor topics

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#10825]
React to: https://github.com/aspnet/Docs/pull/10800#discussion_r255284040

- [x] **Title:** *Introduction to Blazor* &ndash; **Location:** aspnetcore/client-side/spa/blazor/index.md
- [x] **Title:** *Get started with Blazor* &ndash; **Location:** aspnetcore/client-side/spa/blazor/get-started.md
- [x] Refactor *Build your first Razor Components app* to include Blazor. Provide a separate downloadable sample app for Blazor.

**Comment by danroth27** [comment]
I think we need to do a few things here:
- We need Get started content for Blazor somewhere that includes the steps for installing the Blazor VSIX, installing the Blazor CLI templates and creating your first Blazor app
- We need a version of the Build your first app tutorial for Blazor. It should be virtually identical to the Razor components tutorial
- We need a aspnet/core/client-side/spa/blazor.md topic

**Comment by guardrex** [comment]
> We need Get started content for Blazor somewhere

> a version of the Build your first app tutorial for Blazor

I recommend that we resolve those first. I'll work those on a new issue after I hear back from you either here or offline.

* Will it be one topic each to cover both hosting models, or will it be two topics each to cover both?
* If it will be two topics each, describe TOC and file locations separately, especially for the *Get started* topic pair. Both *Build your first* topics would go into the *aspnetcore/tutorials* folder, so that one is obvious wrt to physical file location. *Get started* is a little thornier to deal with.
