### ISSUE TITLE
RunConsoleAsync does not exit in .net core 3.0

### ISSUE THREAD

**Issue by OnurGumus** [aspnet/Docs#10822]
Title says all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.0)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @OnurGumus ... Thanks for commenting. Engineering will call out all of the hosting changes for 3.0 shortly, and this one will be included in that change set.

**Comment by guardrex** [comment]
btw --- @OnurGumus ... before I close ... where did you hear that. It's on master ...

https://github.com/aspnet/Extensions/blob/master/src/Hosting/Hosting/src/HostingHostBuilderExtensions.cs#L157

**Comment by OnurGumus** [comment]
My bad RunConsoleAsync is part of IHostBuilder, I was looking at IHost. A bit confusing though.
