### ISSUE TITLE
Initial Migration Section

### ISSUE THREAD

**Issue by vmsvarun** [aspnet/Docs#10830]
is the location of MvcMovieContext.cs supposed to be in Models (In the Models/MvcMovieContext.cs file) or Data (In the Data/MvcMovieContext.cs file)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Models for now, that's what the scaffolder does. I have a bug open on scaffolding to move it to data.

It's your choice.

**Comment by mathewgries** [comment]
It moves to Data now. However, it would be nice when showing a file's contents to also include the file's location. I should not have to search the comments to find out where this file was
