### ISSUE TITLE
Please update middleware order to specify where UseCors should be placed.  Would also help to include all other middleware as well.

### ISSUE THREAD

**Issue by CarlosOnline** [aspnet/Docs#10839]
UseCors is missing from the order information link below. 

Please add UseCors order information.

Reference
------------- 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.2#order

The following Startup.Configure method adds middleware components for common app scenarios:

Exception/error handling
HTTP Strict Transport Security Protocol
HTTPS redirection
Static file server
Cookie policy enforcement
Authentication
Session
MVC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We didn't intend this section to show every service/scenario. Ordering info for CORS is covered in the table at https://docs.microsoft.com/aspnet/core/fundamentals/middleware/index#built-in-middleware ... "Before components that use CORS."

**Comment by CarlosOnline** [comment]
Can you provide a link that specifies which components uses Core?

The table needs to list the specific components that are described.

Before components that use CORS.

**Comment by Rick-Anderson** [comment]
@CarlosOnline 	PR #10709 fixes this
