### ISSUE TITLE
Windows Service topic enhancements

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#10836]
Thanks @pherbel for remarking on how `sc create` **_does NOT_** set the local security policy for the user to log on as a service. I'll update for that and a few other items here.

* Call out executing `net user` commands from an admin command shell.
* Call out default password expiry of six weeks.
* Possibly call out (or just link) `wmic UserAccount where Name='username' set PasswordExpires=False` to set the password expiry to `never`.
* Use Local Security Policy console to grant the user the `Log on as a service` privilege. Turns out that `sc create` doesn't do it, and I'm not sure how my test account gained the privilege earlier.
* Cross-links:
  * Net user: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/cc771865(v=ws.11)
  * Log on as a service: https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/log-on-as-a-service
  * User Rights Assignment: https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/user-rights-assignment
  * Configure security policy settings: https://docs.microsoft.com/windows/security/threat-protection/security-policy-settings/how-to-configure-security-policy-settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@blowdart TL;DR ...

* Possibly call out (or just link) `wmic UserAccount where Name='username' set PasswordExpires=False` to set the password expiry to `never`.

For a Windows Service user account, do you want to call out how to set the account's password to never expire, or do you just want to say that the default expiry is six weeks and leave it at that?

```console
wmic UserAccount where Name='username' set PasswordExpires=False
```

**Comment by blowdart** [comment]
I'd leave it as "at six weeks", and maybe point to managed service accounts in the windows admin docs?
