### ISSUE TITLE
Unneccesary files in deployment

### ISSUE THREAD

**Issue by shapeh** [aspnet/Docs#10831]
We are currently publishing to IIS via Web Deploy.

By default it seems like several files &gt;not&lt; needed for production (FDD) is included in the publish folder. e.g. 

```
appsettings.Development.json
appsettings.json
bundleconfig.json
Microsoft.VisualStudio.Web.CodeGeneration.Design.*.dll
NuGet.Frameworks.dll
```
Perhaps there are more irrelevant files and perhaps these files could automatically be removed? 

It seems like a security issue with files like `appsettings.json` is included in the publish folder, as that particular file often contains passwords and connection strings in clear-text.

Others on SO seem to have similar issues:

1. https://stackoverflow.com/questions/46237725/asp-net-core-2-0-has-microsoft-visualstudio-web-codegeneration-files-in-output-f
2. https://stackoverflow.com/questions/42712055/asp-net-core-exclude-or-include-files-on-publish

For our case, we manually marked files not to be included in the content / build, so .csproj looks something like below:

```
  <ItemGroup>
    <Content Remove="appsettings.Development.json" />
    <Content Remove="appsettings.json" />
    <Content Remove="bundleconfig.json" />
  </ItemGroup>

<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.1" PrivateAssets="all" />

  <ItemGroup>
    <None Include="appsettings.Development.json" />
    <None Include="appsettings.json" />
    <None Include="bundleconfig.json" />
  </ItemGroup>
```

The `NuGet.Frameworks.dll` we found no way to exclude from csproj, so we just manually deleted the file in the deployed folder.

Full csproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Development.json" />
    <Content Remove="appsettings.json" />
    <Content Remove="bundleconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="2.8.391" />
    <PackageReference Include="Dapper" Version="1.50.5" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.1" PrivateAssets="all" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.2" />
    <PackageReference Include="Rotativa.AspNetCore" Version="1.1.1" />
    <PackageReference Include="SimpleMvcSitemap" Version="3.1.0" />
    <PackageReference Include="WebMarkupMin.AspNetCore2" Version="2.5.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Rotativa\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Development.json" />
    <None Include="appsettings.json" />
    <None Include="bundleconfig.json" />
  </ItemGroup>


  <ItemGroup>
    <None Update="Rotativa\wkhtmltoimage.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Rotativa\wkhtmltopdf.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Rotativa\wkhtmltox.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CreateLogsFolder" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
    <WriteLinesToFile File="$(PublishDir)Logs\.log" Lines="Generated file" Overwrite="True" Condition="!Exists('$(PublishDir)Logs\.log')" />
  </Target>

</Project>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566f8ed0-217e-5125-b0f7-6d93c3a145c1
* Version Independent ID: 9fa94395-eff8-3b12-c2d5-c1c6d4142378
* Content: [ASP.NET Core directory structure](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/directory-structure.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/directory-structure.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @shapeh ... Thanks for commenting. We only handle documentation issues that pertain directly to ASP.NET Core (i.e., not MSBuild, but I believe the .NET Core docs team is working on an MSBuild topic that will either explain or link to instructions on controlling published output). With regard to what's published, direct feedback on the product to the [aspnet/AspNetCore repo issues](https://github.com/aspnet/AspNetCore/issues). Also note that if you're concerned about secrets and connection strings in settings files, we recommend using the [Secret Manager tool (aka User Secrets)](https://docs.microsoft.com/aspnet/core/security/app-secrets) locally and either env vars or the [Azure Key Vault configuration provider](https://docs.microsoft.com/aspnet/core/security/key-vault-configuration) on the production host.
