### ISSUE TITLE
Convert Windows Services topic to use Powershell

### ISSUE THREAD

**Issue by pherbel** [aspnet/Docs#10833]
Add Powershell options for script or command line setup.

There is a New-Service ps command: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-6

There is a Set-Acl ps command: https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Security/Set-Acl?view=powershell-6

Here is a sample:
$cred = Get-Credential

$currentDirectory = (Get-Item -Path ".\").FullName

$binPath = $currentDirectory + '\YourService.exe --environment Production --server.urls "http://*:80"'

$acl = Get-Acl $currentDirectory

$aclRuleArgs = $cred.UserName, "Read,Write,ReadAndExecute", "ContainerInherit, ObjectInherit", "None", "Allow"

$AccessRule = New-Object System.Security.AccessControl.FileSystemAccessRule $aclRuleArgs

$acl.SetAccessRule($AccessRule)

$acl | Set-Acl $currentDirectory

New-Service -Name {SERVICE NAME} -BinaryPathName "$binPath" -Credential $cred -DisplayName {SERVICE DISPLAYNAME} -StartupType Automatic -Description {SERVICE DESCRIPTION}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by pherbel** [comment]
With this extension you can grant log on as service rights
https://gallery.technet.microsoft.com/scriptcenter/Grant-Revoke-Query-user-26e259b0

Import-Module .\UserRights.psm1

$cred = Get-Credential
Grant-UserRight -Account $cred.UserName -Right SeServiceLogonRight

**Comment by guardrex** [comment]
Thanks @pherbel ... I'm more interested in following up with engineering on your former remark: The `ServiceUser` account you saw in that screenshot that had been granted *Log on as a service* permissions could only have landed there via the `sc create` command. I'll follow-up with engineering on it shortly. The process provided worked here. However, I don't think the topic remarks on running the commands as admin. There might be some additional factors to address, and we should explore those avenues before introducing an entirely different approach (i.e., PS). I'll ping them later today. I'm 🏃 😅 at the moment.

**Comment by guardrex** [comment]
@pherbel ... I'm moving the work over to https://github.com/aspnet/Docs/issues/10836, where I list some additional work items.

WRT PS, we're not going to go that way at this time. Engineering will let us know if in the future they would like to cover the approach. If so, your post here will be very helpful. Thanks for remarking on the procedure here.

**Comment by guardrex** [comment]
We're going try to take the topic in this direction. It could be a little while tho ... a few months. I have a rather large amount of 3.0 work to do in the coming weeks.

**Comment by pherbel** [comment]
@guardrex  Thanks for your effort.
