### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by udaymandava** [aspnet/Docs#10844]
Link for build your first blozor app is broken, it takes to 404 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8227c67e-83bb-dee3-e31c-73097df59614
* Version Independent ID: e7b564a3-b078-c390-15ba-b5044bd4edec
* Content: [Get started with Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/razor-components/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @udaymandava ... I fixed it earlier on https://github.com/aspnet/Docs/pull/10842, and it will go live soon.

When the fix goes live, it will point to the tutorial at https://docs.microsoft.com/aspnet/core/tutorials/build-your-first-razor-components-app
