### ISSUE TITLE
Not consistence between keys in appsettings.json and c# code above

### ISSUE THREAD

**Issue by olesjo** [aspnet/Docs#10845]
The following lines

                config.AddAzureKeyVault(
                    $"https://{builtConfig["Vault"]}.vault.azure.net/",
                    builtConfig["ClientId"],
                    builtConfig["ClientSecret"],
                    new PrefixKeyVaultSecretManager(versionPrefix));

should be replaced by

                config.AddAzureKeyVault(
                    $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
                    builtConfig["AzureADApplicationId"],
                    builtConfig["AzureADPassword"],
                    new PrefixKeyVaultSecretManager(versionPrefix));

to reflect values in appconfig.json 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault Configuration Provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by olesjo** [comment]
Or the appsettings.json should be updated to reflect the c# code.

**Comment by guardrex** [comment]
Thanks @olesjo ... I'll patch that up.
