### ISSUE TITLE
Error in "Edit.cshtml.cs"

### ISSUE THREAD

**Issue by Dolu-** [aspnet/Docs#10848]
Around line 57 in "Pages\Contacts\Edit.cshtml.cs":

```
var contact = await Context
                .FirstOrDefaultAsync(m => m.ContactId == id);

```
Should be replaced by :
```
var contact = await Context.Contact
                .FirstOrDefaultAsync(m => m.ContactId == id);
```

Have to add "**.Contact**" to work properly.

**Comment by daveabrock** [comment]
Hey @Dolu! Can you say which file is this for? FYI, next time if you do it straight from the bottom of the article an issue will be created with all this information.

**Comment by Dolu-** [comment]
Ok, sorry about that, it's my first report for an issue, here's the absolute path to the file :
https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization/secure-data/samples/final2/Pages/Contacts
