### ISSUE TITLE
Changes to Main are shown twice

### ISSUE THREAD

**Issue by MNF** [aspnet/Docs#10857]
The article shows Changes to Main in 2.1 twice- once as an image, second time as code. Image is redundant, as you can highlight particular lines/words in HTML text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> you can highlight particular lines/words in HTML text.

Right, but the image is the standard diff image optimized to shows a difference.

Thanks for your comment.

**Comment by MNF** [comment]
Consider to use better diff tools :) that generate HTML difference instead of image.GitHub and TeamCity do it well for git changes. May be http://www.mergely.com/ will be useful
