### ISSUE TITLE
Can you use Razor Components and Razor Pages in the same app?

### ISSUE THREAD

**Issue by mrlife** [aspnet/Docs#10851]
As of now, you can use Razor Pages with MVC. For those of us only using Razor Pages, will we be able to incorporate Razor Components into an existing app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b13daaae-9363-66b4-4104-d74952dee4d9
* Version Independent ID: c4563f5a-c4ef-1a21-8887-136b205b797f
* Content: [Frequently asked questions (FAQ) about Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/faq?view=aspnetcore-3.0)
* Content Source: [aspnetcore/razor-components/faq.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/faq.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mrlife ... the answer is *yes* ... it should work ... **_for ASP.NET Core 3.0 Preview_**. If you run into trouble, open an issue on the aspnet/AspNetCore issues at https://github.com/aspnet/AspNetCore/issues for engineering assistance.

**Comment by mrlife** [comment]
@guardrex Will adding a Razor Component to a Razor Pages app be described in the docs somewhere?

**Comment by guardrex** [comment]
@mrlife Eventually, yes. I'm taking my cues on *what to add when* from engineering. They haven't remarks on that scenario *yet*.

**Comment by jjorian** [comment]
yes you can, you must edit some file in blazer website project
1-add _Layout.cshtml and write base page html,head,import css,js ,.... and @RenderBody()
2-import _Layout on _Host.cshtml and set a route on top of  this file ex @page "/dddd" and keep  only <app>....</app>
3-now you can add index.cshtml or another razor pages name with routing ex @page "/"  this page is access with http:/localhost:port/
4-now you can add contact.component or another razor componenet  with routing ex @page "/contact" this page is access from browser in http:/localhost:port/contact without "dddd"!!!

**Comment by guardrex** [comment]
It's on a PR for review now. We're mostly still off for the holidays right now, so we'll get it reviewed and merged in the new year.

https://github.com/aspnet/AspNetCore.Docs/pull/16098
