### ISSUE TITLE
PersistKeysToFileSystem: documentation needs note about setting up %LOCALAPPDATA% path for app pools

### ISSUE THREAD

**Issue by jclas** [aspnet/Docs#10864]
(I'm using IIS 10.0 on a windows 10 machine.)
Issue:
By default, my app pool's %LOCALAPPDATA% path was blank. It was causing my application(s) to not be able to get to the correct path to store keys in its keyring (when using the  services.AddDataProtection "PersistKeysToFileSystem" option).

This was remedied by the following:
In addition to setting the apppool's "Load the user profile" (Advanced settings) to true, I had to set "setProfileEnvironment" to true inside the file: %windir%\system32\inetsrv\config\applicationHost.config 
(By default it is false)

I think this note should be added to the documentation. This would save a lot of users several hours/days of pain.
Secondly, maybe the IIS team should consider adding this property setting to the app pool's advanced settings UI.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jclas ...

> By default, my app pool's %LOCALAPPDATA% path was blank. It was causing my application(s) to not be able to get to the correct path to store keys in its keyring (when using the services.AddDataProtection "PersistKeysToFileSystem" option).

**to get to the correct path** ... **when using ... PersistKeysToFileSystem**

I'm a bit confused by that: The path is passed to `PersistKeysToFileSystem`. AFAIK, one either sets `Load user profile` and allows DP to use %LOCALAPPDATA% as the key store location **_OR_** one doesn't set `Load user profile` and uses `PersistKeysToFileSystem` with a custom path to wherever the keys should be stored (and of course, the app pool needs read/write permission to that location).

We document it that way in the [IIS topic](https://docs.microsoft.com/aspnet/core/host-and-deploy/iis#data-protection), where we say ...

> ... use **one** of the following approaches ...

One approach ends up using %LOCALAPPDATA% and the other is a custom location.

I'm not sure if doing both creates this :boom: scenario that you describe. It sounds like you're saying that you need to load the user profile for other reasons ... *and* ... you need to use a custom location for the key ring (i.e., not use %LOCALAPPDATA%). Is that right? If not, explain a bit more what your scenario is.

> adding this property setting to the app pool's advanced settings UI.

That feedback would need to go to the IIS team. We just handle ASP.NET Core docs here. Try :point_right: https://forums.iis.net/1080.aspx

**Comment by jclas** [comment]
To reiterate:
I was trying to write my dataprotection keys to: %LOCALAPPDATA%\ASP.NET\DataProtection-Keys
which translates to "C:\Users\Owner\AppData\Local\ASP.NET\DataProtection-Keys" on my computer when running the app on localhost. Everything worked fine on localhost.

When I ran my app on my IIS server, %LOCALAPPDATA% was an empty string. This caused the app to try to write to an unintended folder "C:\ASP.NET\DataProtection-Keys".
My remedy (in addition to setting Load User Profile = true) was to ALSO setProfileEnvironment=true inside %windir%\system32\inetsrv\config\applicationHost.config. By default it is false.
By setting setProfileEnvironment=true, the environment variable were then set for the app pool user that my app was using.
To restate more simply, if setProfileEnvironment=false then the environment variable LOCALAPPDATA is empty.
I hope this clarifies.

**Comment by guardrex** [comment]
Yes, I understand, but are you using `PersistKeysToFileSystem` in addition to those settings?

**Comment by guardrex** [comment]
What happens on IIS if you only set `Load user profile` to `True` on IIS? ..... **Don't use** `PersistKeysToFileSystem`. Does it behave correctly and store keys in the user profile directory?

**Comment by guardrex** [comment]
I did some research on this, and you're correct, but there's a caveat.

The probable reason that this hasn't come up before is that `setProfileEnvironment` is **supposed to default to `True`**. *Famous last words, right?* :smile: On my local machine, it was explicitly disabled. On a fresh Azure WS2016 machine, it does default to `True`. 

https://docs.microsoft.com/iis/configuration/system.applicationhost/applicationpools/add/processmodel

This is worthy of pointing out. It only takes a sentence or two to surface it. As you say, it can save someone hours of pain.

@blowdart TL;DR The problem here is that we say that for DP to store keys in a custom user profile that the dev should confirm that `Load user profile` is `True`. That's correct. However, `setProfileEnvironment` must also be `True`. It should be the default, but it might not be in some cases. For example on my Win10 machine, it was set to `False` in the `<applicationPoolDefaults>`. The result was ...

> Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

When I went into *applicationHost.config* and set it ...

```xml
<applicationPools>
    <add name="testselfcontained" ...>
        <processModel identityType="SpecificUser" userName="ServiceUser2" password="..." setProfileEnvironment="true" />
    </add>
    <applicationPoolDefaults managedRuntimeVersion="v4.0">
        <processModel identityType="ApplicationPoolIdentity" loadUserProfile="true" setProfileEnvironment="false" />
    </applicationPoolDefaults>
</applicationPools>
```

>User profile is available. Using 'C:\Users\ServiceUser2\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.

... and keys go there ...

<img width="463" alt="capture1" src="https://user-images.githubusercontent.com/1622880/52542586-d8e04000-2d66-11e9-8e1c-7892b25a1fed.PNG">

So, I'm going to add a sentence to two to clarify the situation with `setProfileEnvironment`.

**Comment by jclas** [comment]
You found exactly what I found. setProfileEnvironment was by default set to false.
I glad you have come to the same conclusion. I trust you will supplement the documentation accordingly. I'm sure it will help many people. Thanks for you efforts.

**Comment by guardrex** [comment]
Yes, thanks for opening this. I guess when engineering first worked the issue that they were only considering the server environment, where it should default `True`. The updates are on #10875, so we'll get that merged soon. Thanks again for your help. I'm sure you will save devs a lot of :cry: *tears*.
