### ISSUE TITLE
documentation needs note about setting up %LOCALAPPDATA% path for app pools

### ISSUE THREAD

**Issue by jclas** [aspnet/Docs#10865]
(I'm using IIS 10.0 on a windows 10 machine.)
Issue:
By default, my app pool's %LOCALAPPDATA% path was blank. It was causing my application(s) to not be able to get to the correct path to store keys in its keyring (when using the  services.AddDataProtection "PersistKeysToFileSystem" option).

This was remedied by the following:
In addition to setting the apppool's "Load the user profile" (Advanced settings) to true, I had to set "setProfileEnvironment" to true inside the file: %windir%\system32\inetsrv\config\applicationHost.config 
(By default it is false)

I think this note should be added to the documentation. This would save a lot of users several hours/days of pain.
Secondly, maybe the IIS team should consider adding this property setting to the app pool's advanced settings UI.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945c28b7-6cc7-d4ed-3b96-a401eef42f59
* Version Independent ID: eb45fbf9-29fb-c67b-2f50-454380a502dd
* Content: [Data Protection key management and lifetime in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings?view=aspnetcore-2.2#key-management)
* Content Source: [aspnetcore/security/data-protection/configuration/default-settings.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/configuration/default-settings.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Let's track this on the other topic. I'll put the reference here, and that will cross-link these two.

https://github.com/aspnet/Docs/issues/10864
