### ISSUE TITLE
When i run, error

### ISSUE THREAD

**Issue by peterremote1980** [aspnet/Docs#10862]
It said:
Startup.cs(35,50): error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseInMemoryDatabase' and no accessible extension method 'UseInMemoryDatabase' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assemblyreference?) [C:\Users\Peter\Desktop\aspnetcoreapp\aspnetcoreapp.csproj]

The build failed. Please fix the build errors and run again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Great error message. You might want to compare with the download.
