### ISSUE TITLE
I would like to test with postman.

### ISSUE THREAD

**Issue by frankmehlhop** [aspnet/Docs#10871]
Hi,
thanks for the tutorial!
So far I'm testing my WebApi with postman and it works fine.
Is it possible to keep on testing with postman the requests and response like before but also doing the health check via postman? 
I guess I have to set a different port for that? And than how does the request looks like?
Please could you explain that to me? I'm new in this surrounding of WebApi's and that stuff. 
Thank you very much! 
Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#filter-by-port)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @frankmehlhop ... You should be able to just make a request on the health check endpoint from Postman, and the probe should respond normally.

> but also doing the health check via postman

Health check endpoints are separate endpoints from web API endpoints, so any request to a health check probe endpoint is a separate request.

The alternative to manually making requests to health check probes is to use the **Health Check Publisher**. However, the [topic section](https://docs.microsoft.com/aspnet/core/host-and-deploy/health-checks#health-check-publisher) doesn't have the best explanation of that right now. Updates are on a PR, so you would need to read the PR diff to see the latest content, which we hope to merge into the live documentation fairly soon. See: https://github.com/aspnet/Docs/pull/10728

I think the opening paragraph of the topic covers the concept ...

> Health checks are exposed by an app as HTTP endpoints.

... so I don't think there's anything to work at this point; however, if you feel we need to make improvements (perhaps add more content) to the topic, we can re-open to discuss further.

**Comment by frankmehlhop** [comment]
Thanks. Was easy.
http://localhost:_myPort_/health
--> Healthy / 200
