### ISSUE TITLE
Singleton vs Transient for email

### ISSUE THREAD

**Issue by Ponant** [aspnet/Docs#10881]
Hi,
We used to use a transient service for the email interface. Is there a reason why a singleton is preferred now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See [Service lifetimes](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#service-lifetimes)

Singleton lifetime services are created the first time they're requested and Every subsequent request uses the same instance.

**Comment by Ponant** [comment]
Thanks @Rick-Anderson , I know that and this is why to me a transient service was more appropriate for an email service.
Cheers

**Comment by Ponant** [comment]
@Rick-Anderson , I think you should change it to transient, see here
https://github.com/aspnet/AspNetCore/blob/bfec2c14be1e65f7dd361a43950d4c848ad0cd35/src/Identity/UI/src/IdentityBuilderUIExtensions.cs 
It makes more sense to me .
Cheers

**Comment by Rick-Anderson** [comment]
@Ponant 	thanks for bringing this up and being persistent.
