### ISSUE TITLE
Swashbuckle has not been updated for a long time

### ISSUE THREAD

**Issue by adamdallis** [aspnet/Docs#10880]
# Issue description
Swashbuckle is out of date and has not had a release for over 2 years I do not think Microsoft Docs should be even recommending it. Also, the current version of Swashbuckle uses an old version of swagger that uses an old version of Jquery which contains a vulnerability. I think this page should be completely removed because it will cause websites to contain vulnerabilities.

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Rick-Anderson** [comment]
This is covered in #8194
