### ISSUE TITLE
Documentation for ASP.NET Core targeting .NET Framework

### ISSUE THREAD

**Issue by GoFightNguyen** [aspnet/Docs#10899]
I would love better documentation about an ASP.NET Core app targeting .NET Framework.
When/Why would I want to do this?
Would the development experience be the same as if I was writing a true ASP.NET Core app?
What middleware is excluded?
What are the gotchas and pain points?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2#aspnet-core-targeting-net-framework)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> When/Why would I want to do this?

When you have an ASP.NET Framework app that you can't migrate to Core.

**Comment by Rick-Anderson** [comment]
ASP.NET Core 3.0 doesn't support targeting the .NET Framework.

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?view=aspnetcore-2.2

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server?view=aspnetcore-2.2

**Comment by GoFightNguyen** [comment]
What if I have a greenfield application, but my organization will not allow .NET Core? I like the csproj structure, the development experience, the configuration of middleware, the standard libraries, etc. so much better than in ASP.NET Framework.

Is there any documentation on using all the Microsoft.AspNetCore standard libraries in an ASP.NET Framework project?
