### ISSUE TITLE
Shouldn't StartupHostedServiceHealthCheck.StartupTaskCompleted be volatile?

### ISSUE THREAD

**Issue by joaoportela** [aspnet/Docs#10895]
In StartupHostedServiceHealthCheck I think that the StartupTaskCompleted property should be `volatile`.

It can potentially be modified by multiple threads that are executing at the same time. Which is literally [what `volatile` is for](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@rynowak 

Cross-ref: https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/health-checks/samples/2.x/HealthChecksSample/StartupHostedServiceHealthCheck.cs
