### ISSUE TITLE
Multiple JWT authentication schemes do not work

### ISSUE THREAD

**Issue by mrtoby** [aspnet/Docs#10896]
I have tried to do exactly as the example and set breakpoints in both snippets where the options are configured. Only one of the breakpoints is reached, and only the corresponding authentication scheme works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
which example?

**Comment by mrtoby** [comment]
The one under "Use multiple authentication schemes" on the page
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x
.

What I want to achieve is to use two different trust framework policies,
one for normal sign-in/sign-on and one for a resource owner policy (which
can be used from automated tests).
I can only get one policy to work at a time and that is not enough...
Also, different clients might need different framework policies.

Best regards,
/Tobias

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
