### ISSUE TITLE
External links that affects your website ranking in search engines

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10894]
If I were @satyanadella, I would prevent this:

This article and others (see: https://github.com/dotnet/docs/issues/10200 and
https://github.com/aspnet/Docs/issues/10668) has links to a private website.

In SEO, an external link is considered a vote to the other website (see: https://support.google.com/webmasters/answer/2648487?hl=en). It affects the ranking of both websites. At least you should use "rel=nofollow" for external links. Please read about nofollow here: https://en.wikipedia.org/wiki/Nofollow

External links in this article: Search for "Explicit Dependencies Principle" and "Don't Repeat Yourself (DRY) principle".

Suggestion is to clean up Microsoft Docs from such external links that badly affects Microsoft websites and provide traffic to the external website or at least use rel=nofollow for external links if you need to mention. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6704d196-b171-db13-9798-da6d383a8833
* Version Independent ID: b988e9ea-5086-8af7-a469-9575a7c57607
* Content: [Handle requests with controllers in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/actions.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/actions.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
So you think there should only be links to *public* web sites? Or that the docs system and/or Microsoft should literally cover every topic that might be of even tangential interest to those reading documentation of their products? Linking to other sites is literally what HTML and the "world wide web" was invented to support.

**Comment by guardrex** [comment]
I agree with @ardalis, and there's no major issue to address **_on this repo_** in these regards. We are continually striving to link MS-generated content where feasible, but I can guarantee you that 100% of external links will not be removed from the repo. There will always be a small number of external links to quality content, such as @ardalis's content, that we need for subjects that we don't have the capacity to cover and maintain.

I can't speak to this issue ("badly affects Microsoft websites") across the company. Please open a feedback issue where the docs managers will see it at https://github.com/MicrosoftDocs/feedback ... that's a better spot than here to discuss this broadly across MS docs.
