### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#109]
ASP.NET 5 -> Fundamentals -> Middleware
- What is middleware?
    - ASP.NET 5 apps are made up of a middleware pipeline
    - Abstractly middleware takes the next request delegate and provides a request delegate (`Func<RequestDelegate, RequestDelegate>`)
    - Request delegates
- Creating a middleware pipeline with `IApplicationBuilder`
    - You "Use" middleware
    - Forking the pipeline using `Map` or `MapWhen`
    - Terminating middleware (ex `app.Run(RequestDelegate)`)
    - Default 404 middleware at the end of the pipeline
- Built-in middleware
    - Static Files #60, Routing #61, Diagnostics #62, Authentication, CORS #94, etc, etc.
    - Link to corresponding topics
- Writing middleware
    - In-line lambda pattern (`Use(Func<RequestDelegate, RequestDelegate>)`)
    - Class pattern (`UseMiddleware<T>(params)`)
        -  ctr(RequestDelegate next, optional DI parameters, params from UseMiddleware)
        - `Task Invoke(HttpContext)` with optional DI parameters
        - VS item template
        - By convention provide a `IApplicationBuilder` extension method: `app.UseMyMiddleware(...)`
        - By convention provide an `IServiceCollection` extension method to add any required services" `services.AddMyMiddleware(...)`
    - Middleware configuration (#64) using Options

**Comment by DjVG** [comment]
Hi Daniel, 
Do you need help o write middleware/OWIN articles? Please let me know if I cam help.

**Comment by danroth27** [comment]
Absolutely! This particular topic is intended to be an overview of what middleware is in ASP.NET 5 and how to author middleware. We have a separate issue tracking documenting our OWIN support (#71) and other issues track documenting specific middleware implementations (ex static files, session, authentication, etc.). Before you write anything please propose an outline in the issue so that we can make sure we are on the same page. Thanks!

**Comment by ardalis** [comment]
What about Session? https://github.com/aspnet/Session We don't have an issue to cover it, either.
