### ISSUE TITLE
Development-time IIS support without Visual Studio

### ISSUE THREAD

**Issue by fihnatowicz** [aspnet/Docs#10904]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.2

Is there way to configure Development-time IIS support without installing Visual Studio IDE? Some peoples, like FE Developers/HTML-Coders doesn't have VS. It's a little uncomfortable installing Visual Studio just to run it once. Thx.

**Comment by guardrex** [comment]
@fihnatowicz 

> just to run it once

I'm a little confused by your question. What setup are you trying to achieve?
