### ISSUE TITLE
Server-Side tip.

### ISSUE THREAD

**Issue by RFDominguez** [aspnet/Docs#10908]
Since you'll get little or no error feedback at all when running a Server-Side and getting an exception (under VS 2019 preview 1) when using IIS Express as the host, change this option to use the [AppName].Server. This will show the exceptions being thrown in case of any.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba6222c-95d0-eb55-4d5c-7342a9dc916c
* Version Independent ID: 851e452f-1c89-ffe2-e403-5dce6e482541
* Content: [Debug Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/debugging?view=aspnetcore-3.0)
* Content Source: [aspnetcore/razor-components/debugging.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/debugging.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27

**Comment by danroth27** [comment]
This is a temporary issue with VS. When using IIS Express you should be able to see the ASP.NET Core logs using the ASP.NET Core Web Server output tab, but this was broken when we moved to in-proc hosting. This issue will be fixed in a future VS update.
