### ISSUE TITLE
ItemGroup csproj file updated automatically on release

### ISSUE THREAD

**Issue by Urgen-Dorjee** [aspnet/Docs#10917]
Pretty curious to know why ASP.NET core csproj file being updated with unwanted settings automatically. When I pushed my code to CI/CD pipelines and expected to see the output as it was tested, however to my surprise it did not display as expected and when I see the csproj file it has added with following line of xml settings unknowingly, well I can remove these lines but why these lines are added in the csproj file:-

&lt;ItemGroup&gt;
        &lt;Content Remove="Views\Post\DeleteAsync.cshtml" /&gt;
 &lt;/ItemGroup&gt;
&lt;ItemGroup&gt;
    &lt;UpToDateCheckInput Remove="Views\Post\DeleteAsync.cshtml" /&gt;
 &lt;/ItemGroup&gt; 
 &lt;ItemGroup&gt;
       &lt;_ContentIncludedByDefault Remove="Views\Post\DeleteAsync.cshtml" /&gt;
 &lt;/ItemGroup&gt;
 &lt;ItemGroup&gt;
        &lt;None Include="Views\Post\DeleteAsync.cshtml" /&gt;
 &lt;/ItemGroup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b26c2a-d481-043c-e37b-cbe3ad427d41
* Version Independent ID: d7d85488-c055-7aea-0664-2e97bc937a04
* Content: [Overview of ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/overview.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What tool is doing that?
To report Visual Studio problems
**Help > Send Feedback > Report a Problem**

![image](https://user-images.githubusercontent.com/3605364/52737321-27145f80-2f70-11e9-8eb0-828478541672.png)

**Comment by Urgen-Dorjee** [comment]
Appreciated your help. I missed to add this last time around regarding the product. I have been using VS2019 Preview since it is released. However surprisingly even send feedback acting very weird as it is something  new to this planet. Copy & Paste does not work, backspace does not work either. I have reported this problem to Developer community signing through web portal since it is not working from VS2019 "Report a Problem" option.  

Thanks!
