### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by theVietCoder** [aspnet/Docs#10915]
When i try dotnet run, i got this error:
Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d &lt;toolname&gt;": C:\Program Files\dotnet\sdk\3.0.100-preview-010184\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by ericbyrd** [comment]
Hey - 
Check the known issues here: https://blogs.msdn.microsoft.com/webdev/2019/02/05/blazor-0-8-0-experimental-release-now-available/

My workaround was to run `dotnet new console -n test` (in a directory other than the Blazor proj).  I then went back to the Blazor project and ran `dotnet run` and Bob's your uncle.

**Comment by guardrex** [comment]
Thanks @ericbyrd ... yes, it's listed there as ...

> "Unable to generate deps.json, it may have been already generated.": You may see this error when running a standalone Blazor app and you haven't yet restored packages for any .NET Core apps. To workaround this issue create any .NET Core app (ex dotnet new console) and then rerun the Blazor app.

**Comment by theVietCoder** [comment]
Thank you @ericbyrd .It's amazing that Google couldn't find that article.

**Comment by guardrex** [comment]
Let's ask about both of those ...

@danroth27 Would you like to cover these two temporary known issues?

> Known issues
> 
> There are a couple of known issues with this release that you may run into:
> 
> **"It was not possible to find any compatible framework version. The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found."**: You may see this error when building a Blazor app because the IL linker currently requires .NET Core 2.x to run. To work around this issue, either install .NET Core 2.2 or disable IL linking by setting the <BlazorLinkOnBuild>false</BlazorLinkOnBuild> property in your project file.
> 
> **"Unable to generate deps.json, it may have been already generated."**: You may see this error when running a standalone Blazor app and you haven't yet restored packages for any .NET Core apps. To workaround this issue create any .NET Core app (ex dotnet new console) and then rerun the Blazor app.

**Comment by danroth27** [comment]
@guardrex Not in the docs. We have them covered in the [announcement blog post](https://blogs.msdn.microsoft.com/webdev/2019/02/05/blazor-0-8-0-experimental-release-now-available/) and now also in the [release notes](https://github.com/aspnet/Blazor/releases/tag/0.8.0)
