### ISSUE TITLE
how to fix this error when we add controller..

### ISSUE THREAD

**Issue by erbarunKamal** [aspnet/Docs#10920]
![capture1](https://user-images.githubusercontent.com/45435598/52730523-98d8c180-2fe1-11e9-9fae-f6d99435e353.PNG)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
To report Visual Studio problems
**Help > Send Feedback > Report a Problem**

![image](https://user-images.githubusercontent.com/3605364/52737321-27145f80-2f70-11e9-8eb0-828478541672.png)
