### ISSUE TITLE
Link on #client-side-development isn't working.

### ISSUE THREAD

**Issue by octy40** [aspnet/Docs#10921]
On the Client-Side development section, the link to client-side development in that paragraph goes to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2#client-side-development)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @octy40 ... I'll patch that up. We have the client-side index page directed to Blazor now. It was a change that just went in yesterday. While I'm at it, I'll search for any others.
