### ISSUE TITLE
IValidatableObject mention not completed

### ISSUE THREAD

**Issue by bsimser** [aspnet/Docs#10923]
There's a couple of mentions using the IValidatableObject interface but it doesn't give any examples. It even says "a better option is to use IValidatableObject as shown in the following paragraph" but that paragraph never happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's in the sample at https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation/sample/MovieIValidatable.cs#L7

I'll show the entire sample to make this clear. 
Thanks for bringing this up.

**Comment by bsimser** [comment]
Looks great, thanks!
