### ISSUE TITLE
Upgrade policy sample from 1.1 to 2.2

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#10932]
Upgrade policy sample from 1.1 to 2.2

Changed `GetExternalAuthenticationSchemes` to `GetExternalAuthenticationSchemesAsync`
but `Where` needs work.

```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context,
                                               BuildingEntryRequirement requirement)
{
    if (context.User.HasClaim(c => c.Type == ClaimTypes.BadgeId &&
                                   c.Issuer == "http://microsoftsecurity"))
    {
        context.Succeed(requirement);
    }

    //TODO: Use the following if targeting a version of
    //.NET Framework older than 4.6:
    //      return Task.FromResult(0);
    return Task.CompletedTask;
}
```
 
`ClaimTypes` does not contain a definition for `TemporaryBadgeId`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@haok would you be able to upgrade [PoliciesAuthApp1](https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1) to 2.2?

I got stuck on the `Where` and `ClaimTypes`

**Comment by serpent5** [comment]
You can use the following (taken from the [RCL source](https://github.com/aspnet/AspNetCore/blob/release/2.2/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/Manage/ExternalLogins.cshtml.cs#L97)) for the `where` change:

    var otherLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync())
        .Where(auth => userLogins.All(ul => auth.Name != ul.LoginProvider))
        .ToList();

This also requires a change from `AuthenticationDescription` to `AuthenticationScheme` in [`ManageLoginsViewModel`](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies/samples/PoliciesAuthApp1/Models/ManageViewModels/ManageLoginsViewModel.cs#L14).

**Comment by Rick-Anderson** [comment]
@blowdart can you help get this code working?

**Comment by HaoK** [comment]
I have to get through my preview3 bugs before I can take a look at this, but I would suggest it might be easier to create a new 2.2 app and move the authz controllers + policy handlers over, that might be easier than trying to convert things, since the stuff the samples is demonstrating isn't really related to any of the changes between 1.1 and 2.2

**Comment by HaoK** [comment]
Authentication changed a lot in 2.x, but Authorization policies should be more or less untouched for the purposes of this sample

**Comment by Rick-Anderson** [comment]
@serpent5 would you be able to create the new 2.2 app?

**Comment by serpent5** [comment]
@Rick-Anderson Sure. I should be able to put something together within the next couple of days.
@HaoK Rather than moving the authz controllers over, would it be OK to use the default UI in the new project?

**Comment by HaoK** [comment]
That should be fine

**Comment by serpent5** [comment]
@Rick-Anderson Shall I stick to controllers/views in the new version or would you prefer if I switch over to RP as part of this?

**Comment by Rick-Anderson** [comment]
Your call. I have a slight preference for RP, but either is fine.

**Comment by dkamins314** [comment]
Ron Petrusha directed me to contact you regarding implementing a Hebrew calendar in asp net core c# the ms sample programs are console - and I tried setting it up in a model - but since it is extending an abstract class it requires implementation of each of the members - I am just starting programing - and I do not understand how to implement it or create a proper view for it. I appreciate any help and guidance that you can offer . Thank you
