### ISSUE TITLE
Using multiple trust framework policies

### ISSUE THREAD

**Issue by mrtoby** [aspnet/Docs#10939]
I have been looking at the example under "Use multiple authentication schemes" since I want to do something similar.

What I want to achieve is to use two different trust framework policies, one for normal sign-in/sign-on and one for a resource owner policy (which can be used from automated tests).
I can only get one policy to work at a time and that is not enough...
Also, different clients might need different framework policies.

The best for me would be if the client could use "Bearer" at all times and the server figure out which trust framework policy that applies to which JWT - this should be simple since the JWT contains the claim "tfp" which is the name of the policy.

I have tried to do exactly as the example (with "Bearer1" and "Bearer2") and set breakpoints in both snippets where the options are configured. Only one of the breakpoints is reached, and only the corresponding authentication scheme works.

Is the documentation wrong or is it the library that is wrong? - and even so, I think the implementation should support multiple tfp's at the same time.

I am using version 2.2.0 of Microsoft.AspNetCore.Authentication and Microsoft.AspNetCore.Authentication.JwtBearer.

Best regards,
/Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by blowdart** [comment]
This is a usage question. Please ask either on StackOverflow, or if you feel it's a bug, in the [aspnet core repo](https://github.com/aspnet/AspNetCore/issues).
