### ISSUE TITLE
502.19  After uninstalling ASP.NET IIS Module 2.2 and Installing 2.1

### ISSUE THREAD

**Issue by qcc-na** [aspnet/Docs#10935]
I believe this should be covered in these docs.

See this issue:  https://github.com/aspnet/AspNetCore/issues/6664

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f16c68-708b-003e-8c63-1df60c6344d0
* Version Independent ID: 25fa0508-4450-9051-cdd7-0d3260c60b4f
* Content: [Troubleshoot ASP.NET Core on IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/Docs/issues/10940
