### ISSUE TITLE
In-process hosting model graphic is not consistent with description

### ISSUE THREAD

**Issue by TaDe90** [aspnet/Docs#10938]
The graphic suggests that the IISHttpServer sits in the middle between the ASP.NET Core Module and the application code. But in the description below it says that the request is handled first by the IISHttpServer, which passes it on to the ASP.NET Core Module and then to the application code as an HttpContext.

It also says that the application code passes the response directly to IIS. Is there no involvement of IISHttpServer or ASP.NET Core Module?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @TaDe90 ...

It says that after the IIS HTTP Server processes the request, the request is pushed into the **ASP.NET Core middleware pipeline**, not to ANCM.

> It also says that the application code passes the response directly to IIS.

It doesn't say "directly." I'd like to add "back through IIS HTTP Server" to make it clear. I'll put that change in now. Thanks for suggesting it.
