### ISSUE TITLE
VirtualFile Class is not available in .Net Core

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#10942]
Let's remove `VirtualFile` from the below paragraph as it's not available in .Net Core (kindly see: [VirtualFile Class](https://docs.microsoft.com/en-us/dotnet/api/system.web.hosting.virtualfile?view=netframework-4.7.2&viewFallbackFrom=netcore-2.2))
> Other common methods of this type include File, PhysicalFile, and VirtualFile

In fact, `PhysicalFile` returns a `PhysicalFileResult` and `File` returns a `VirtualFileResult`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6704d196-b171-db13-9798-da6d383a8833
* Version Independent ID: b988e9ea-5086-8af7-a469-9575a7c57607
* Content: [Handle requests with controllers in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/actions?view=aspnetcore-2.2#defining-actions)
* Content Source: [aspnetcore/mvc/controllers/actions.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/actions.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shadinamrouti 	did you want to create a PR to fix this?
