### ISSUE TITLE
API Convention for any object?

### ISSUE THREAD

**Issue by VictorioBerra** [aspnet/Docs#10954]
```csharp
        [ProducesResponseType(201)]
        [ProducesResponseType(typeof(ValidationProblemDetails), 400)]
        public static void Post(
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any)
        {
        }
```

note the `(object any)`. Is there a better way to do this?

Follow up: Is there a way to match if my method name is `Post` regardless if the param `int Id` is there or not? I have some overloads that return the same thing and I do not want to copy and paste them essentially.

```csharp
        [ProducesResponseType(200)]
        [ProducesResponseType(typeof(ProblemDetails), 400)]
        public static void GetDataTable(
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any,
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any1)
        {
        }

        [ProducesResponseType(200)]
        [ProducesResponseType(typeof(ProblemDetails), 400)]
        public static void GetDataTable(
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any,
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any1,
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any2)
        {
        }

        [ProducesResponseType(200)]
        [ProducesResponseType(typeof(ProblemDetails), 400)]
        public static void GetDataTable(
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any,
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any1,
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any2,
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Any)]
            object any3)
        {
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d14d206-7998-2031-d1d7-f8c8dbecf54a
* Version Independent ID: 3071c40e-f08b-555e-4fe7-dc3828f5828e
* Content: [Use web API conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-2.2)
* Content Source: [aspnetcore/web-api/advanced/conventions.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/conventions.md)
* Product: **aspnet-core**
* GitHub Login: @pranavkm
* Microsoft Alias: **scaddie**

**Comment by pranavkm** [comment]
From the docs: 

> A `params[]` argument indicates remaining parameters that don't need to be explicitly matched.

**Comment by VictorioBerra** [comment]
@pranavkm Thank you for your reply. does "remaining parameters" also include no parameters? Or would I still need an overload that takes nothing?

**Comment by pranavkm** [comment]
> also include no parameters

It should. That said, some of these scenarios aren't super well tested, so if you do see an issue, feel free to file an issue in https://github.com/aspnet/AspNetCore

**Comment by VictorioBerra** [comment]
Last question, are they case sensitive?

```csharp
        [ProducesResponseType(200)]
        [ProducesResponseType(404)]
        public static void Get(
            [ApiConventionNameMatch(ApiConventionNameMatchBehavior.Suffix)]
            int id)
        {
        }
```

will that match `Get(int myId)`?

**Comment by pranavkm** [comment]
Yup - with the suffix behavior `id` will match `id` or `myId` but not `ID` or `myID`. Here's the ode that does the suffix matching in case you'd like to have a look at the implementation - https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Core/src/ApiExplorer/ApiConventionMatcher.cs#L125-L158

**Comment by VictorioBerra** [comment]
Very useful. I propose we slip that into the docs.
