### ISSUE TITLE
Document that startup exceptions are captured by default and show how to opt-out of this behavior

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1095]
Ex. A startup exception could prevent SSL from being enabled (see https://github.com/aspnet/KestrelHttpServer/issues/369).

Opt-out using UseCaptureStartupErrors

**Comment by isaac2004** [comment]
@danroth27 are you looking for a doc or a sample or both?

**Comment by danroth27** [comment]
I think we just need to add a note to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting in the section on UseCaptureStartupErrors.

**Comment by davidfowl** [comment]
This is only on by default when running behind IIS

**Comment by tdykstra** [comment]
@isaac2004 I have active PR #3875 with changes to hosting.md.  If you want to take this you're welcome to do so, or I can add the note today to my PR.

**Comment by isaac2004** [comment]
@tdykstra if you are already there just do it, I won't look at it for a day or so probably

**Comment by tdykstra** [comment]
@Tratcher does this issue apply only to Kestrel 1.x?  Your description in https://github.com/aspnet/KestrelHttpServer/issues/369 refers to calling UseKestrelHttps in Configure method:

> SSL is enabled for kestrel via connection filters in Startup.Configure. app.UseKestrelHttps(...); If an exception happens before this line in Startup then hosting will catch it, start the server, and display an http error page on that port. If an exception happens after that line then the error page will be served over https instead.

The hosting.md doc says `CaptureStartupErrors` defaults to false, so it should also add that the default is true when running behind IIS.

**Comment by Tratcher** [comment]
This issue applies to UseIISIntegration for all versions. Dan was just giving an example of why startup may fail and some of it's consequences.

That said Dan, your example is misleading. Kesterel HTTPS is never enabled with UseIISIntegration. CaptureStartupErrors is off by default for self-host scenarios like Kestrel HTTPS.

**Comment by tdykstra** [comment]
Fixed by #3875
