### ISSUE TITLE
How to deal with typed clients injected into singleton services

### ISSUE THREAD

**Issue by natenho** [aspnet/Docs#10963]
"Keeping a single HttpClient instance alive for a long duration is a common pattern used before the inception of IHttpClientFactory. This pattern becomes unnecessary after migrating to IHttpClientFactory."

I could not understand the implications of keeping the common pattern with long duration instances using HttpClientFactory, for instance, is it ok to have a singleton with a single injected HttpClient and use it to serve several requests? In other words, taking the typed client example in this documentation, what if I inject GitHubService into a singleton service, would it leverage all HttpClientFactory advantages? Or should I need to create a factory like this one described in https://www.stevejgordon.co.uk/ihttpclientfactory-patterns-using-typed-clients-from-singleton-services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Initiate HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1#typed-clients)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by stevejgordon** [comment]
Hi @natenho - The problem with having a singleton HttpClient whether manually doing so (as before HttpClientFactory) or by capturing an instance from HttpClientFactory inside a singleton is that the connection will never refresh. As a result, you are losing the benefit HttpClientFactory offers which is managing the connection (handler) lifetimes for you.

When possible I review if I can simply change my dependant service registration to also be transient if it depends on a typed client. If not, then the factory approach has worked for me too. Perhaps @rynowak has advice or a view on better options/patterns.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by weitzhandler** [comment]
So based on my understanding of the above, in case I need to use a `HttpClient` in my singleton I should do the following:

```c#
public class MySingletonService : IMySingletonService
{
  readonly IHttpClientFactory _HttpClientFactory;
  public MySingletonService(IHttpClientFactory httpClientFactory)
  {
    _HttpClientFactory = httpClientFactory;
  }  
  
  public async Task DoAction()
  {
    var client = _HttpClientFactory.CreateClient();
    var myWebValue = await client.GetAsync("route/action");
  }
}
```

Is that correct?
