### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by gaborbalazs** [aspnet/Docs#10961]
"Welcome to IdentityServer4 (Documentation)." -&gt; https://identityserver4.readthedocs.io/en/release/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a218cc00-a5c0-717e-5b42-5efd6caf8abb
* Version Independent ID: 69bded75-ba42-d3ff-f27b-f7e715f6d2f8
* Content: [Community OSS authentication options for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/community?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/community.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/community.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @gaborbalazs ... I'll replace that.
