### ISSUE TITLE
ApplicationUser is used without explanation

### ISSUE THREAD

**Issue by 42degrees** [aspnet/Docs#10974]
This sample code uses an assumed customer-provided class called ApplicationUser, but this use is not explained anywhere in this document.  I assumed it was a class that I had just not linked in and it took me finding https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-2.2 to learn that this is a "naming convention" for an application-specific user class.

This documentation should either use IdentityUser in the services.AddIdentity call, or it should explain or provide a class example for ApplicationUser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@42degrees 	thanks for pointing this out. The 1.1 templates generated a class for `ApplicationUser`. I'm fixing it in #10975
