### ISSUE TITLE
    app.UseStaticFiles(); before  app.UseResponseCaching(); - is it right?

### ISSUE THREAD

**Issue by shapeh** [aspnet/Docs#10987]
Under Conditions section it says:
"Terminal middleware, such as Static File Middleware, must not process the response prior to the Response Caching Middleware."

In the Configuration you do this:

   ...
   app.UseHttpsRedirection();
    app.UseStaticFiles();   // static comes before caching?
    app.UseCookiePolicy();

    app.UseResponseCaching(); // caching. 

Shouldn't UseResponseCaching come before UseStaticFiles - or am I misreading the Conditions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The "conditions" are just saying what has to be true in order for the Response Caching Middleware to work. It's not saying that any particular middleware should or shouldn't be allowed to cache, including the Static File Middleware. I think the best thing to do is just remove that example. I'll just make it say what is obviously true ...

> Terminal middleware must not process the response prior to the Response Caching Middleware.

... and leave it at that. Thanks for commenting on this.

**Comment by shapeh** [comment]
Okay, I am not sure I get your response correctly - I am unsure if the order matter?

Is this order correct?
```
app.UseStaticFiles();
app.UseResponseCaching();
```

Or this one? - or it does not matter?
```
app.UseResponseCaching();
app.UseStaticFiles();
```

**Comment by guardrex** [comment]
When a *terminal middleware* (for example, Static File Middleware) processes a request, it terminates the middleware processing pipeline and no middleware that comes after it will execute.

In order for Response Caching Middleware to work, it must process the request.

There's no "correct" order, per se. It just depends on whether or not you want responses from terminal middleware to be cachable.

### Response Caching Middleware *after* Static File Middleware

If Response Caching Middleware comes after Static File Middleware and Static File Middleware handles a request, Response Caching Middleware won't run (it won't be reached ... the response will have already been sent), and the response can't be cached.

```csharp
app.UseStaticFiles();
app.UseResponseCaching();
```

### Response Caching Middleware *before* Static File Middleware

If Response Caching Middleware comes before Static File Middleware and Static File Middleware handles a request, Response Caching Middleware will have already run, and the response can be cached (if all of the other caching conditions are met).

```csharp
app.UseResponseCaching();
app.UseStaticFiles();
```

For more info on middleware processing order, see the [Middleware topic](https://docs.microsoft.com/aspnet/core/fundamentals/middleware).

**Comment by shapeh** [comment]
Thanks for clarifying this @guardrex.  This is very helpful and perhaps this info added to the docs would be beneficial for others too.

On a side note, I love what Microsoft teams are doing these days - the docs.microsoft.com are so much better than the old msdn, and ASP.NET Core just rocks due to its simplicity and speed!

Keep up the good work and thanks again for delivering great products :)

**Comment by guardrex** [comment]
Thanks for those kind words.

I'm not too concerned about the ordering remark itself ...

> Terminal middleware must not process the response prior to the Response Caching Middleware.

What I am concerned about is that "terminal middleware" is used in the middleware topic but not defined where "short-circuiting" is explained. It should be. Then, this line can link over to that topic to explain what a "terminal middleware" is.

I don't want this to get very specific to Static File Middleware. There are other terminal middlewares, including ones that the developer might create, so the remark should stay generic ... it applies to *any* terminal (short-circuiting) middleware.

I'll add an update for this on a new PR to improve it further.

**Comment by shapeh** [comment]
That makes very good sense to elaborate more on 'terminal middleware' 👍 
Thanks again for responding quickly.
