### ISSUE TITLE
Warning about Razor Pages applicability seems incomplete

### ISSUE THREAD

**Issue by joaofbantunes** [aspnet/Docs#10996]
The warning at the top of the doc, indicating this doesn't apply to Razor Pages seems incomplete, because it makes it look as if role-based authorization doesn't apply at all to Razor Pages, but it does, only one should be aware of differences while using it, at least from my understanding.

Regarding the Authorize attribute, if we use it in the class directly, not the methods, it seems to work as expected, example:
```
[Authorize(Roles = "admin")]
public class IndexModel : PageModel
```

Another way to achieve this seems to be by using Razor Pages conventions, configured in the Startup class:
```
services
	.AddMvc()
	.AddRazorPagesOptions(options =>
	{
		options.Conventions.AuthorizePage("/Admin/Index", "APolicyThatRequiresARole");
	})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Related to (and probably should be worked with) :point_right: https://github.com/aspnet/Docs/issues/6301

**Comment by blowdart** [comment]
@ryanbrandenburg because Razor Pages are his and this is an MVC issue

**Comment by blowdart** [comment]
Wrong ryan :) @rynowak
