### ISSUE TITLE
Are @section <name> { ... } working in ViewComponents ?

### ISSUE THREAD

**Issue by LucaGabi** [aspnet/Docs#10999]
Are @section &lt;name&gt; { ... } working in ViewComponents ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LucaGabi ... See the last line of the `@section` coverage in the *Layout* topic ...

https://docs.microsoft.com/aspnet/core/mvc/views/layout?view=aspnetcore-2.2#sections
