### ISSUE TITLE
Require Email confirmation should redirect to ConfirmEmail page 

### ISSUE THREAD

**Issue by Ponant** [aspnet/Docs#10991]
The page ConfirmEmail.cshtml.cs exists in the template and could be used as a redirection endpoint after the user registers in the scenario where email confirmation is required. So far the docs do a local redirect to the returnurl (typically home page in testing).

**Comment by Rick-Anderson** [comment]
@Ponant we use the template generated code. If you think the templates are not correct, open an issue at https://github.com/aspnet/AspNetCore/issues

There are several related issues open, please review them before creating a new issue.
