### ISSUE TITLE
I don't see how this works

### ISSUE THREAD

**Issue by Itsey** [aspnet/Docs#11005]
I don't get how / if this works.  I have configured the profile but at no point have I configured IIS to point at the project directory in visual studio, therefore there is no content.  How do you configure IIS to point against the project directory such that when you run the site up using the profile the site is actually present?
I could see it if we "published" but that introduces an additional step, that seems to be worse than the IISExpress experience.

Is there a bit missing from the document or have I done something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* GitHub Login: @shirhatti
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It should work exactly as described by the topic.

@shirhatti will let us know for sure if there were any regressions recently, but I haven't heard of any.

@Itsey Can you provide your versions:

* VS: **Help** > **About Microsoft Visual Studio**
* .NET Core: VS **Package Manager Console** > `dotnet --version`
* IIS: From a command prompt > `%SystemRoot%\system32\inetsrv\InetMgr.exe`, then **Help** > **About Information Services**.

**Comment by Itsey** [comment]
Hi 
Help>About VS> 4.7.03062
Dotnet --version > 2.2.104
IIS > 10.0.14393.0

I'll retry again and make sure I have followed all the steps and let you know.

**Comment by Itsey** [comment]
Hi both I'm really sorry but I think I must have messed up the naming, I've now rerun it from top to bottom and I think that they key part is that the name needed to match - so please disregard this it was just my inability to follow your instructions!

**Comment by guardrex** [comment]
No worries. I'm glad it had a happy ending. :tada:
