### ISSUE TITLE
sc commands give errors

### ISSUE THREAD

**Issue by gzinger** [aspnet/Docs#11007]
sc commands, as presented, don't work in powershell because the alias to Set-Content
use sc.exe instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
By-design at this point&mdash;it's console-only at this time. Note tho that we're going to moving the entire process to PS on an upcoming doc update. Therefore, I'll close this as a dup of https://github.com/aspnet/Docs/issues/10833.

@gzinger Please feel free to add any thoughts you would like considered to that issue. That's the one that I'll use to track the work. It's going to have to wait a bit tho. We're about to dig into 3.0 doc updates, and that's going to take top priority. I'll get to https://github.com/aspnet/Docs/issues/10833 as soon as I can.
