### ISSUE TITLE
Why do I need to publish?

### ISSUE THREAD

**Issue by gzinger** [aspnet/Docs#11008]
Why do I need the "publish" step? Isn't content produced by build is not the same?
Can't I just copy the the "bin\Release\netcoreapp2.2\win7-x64" folder to the target server and register the service executable there? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
I don't recall if the exe comes out if the Release config is passed to `dotnet build` ... I'll take your word for it. There's a very important reason tho **_NOT_** to deploy from `dotnet build` that supersedes anything else: **_It's just not supported by engineering._**

I quote ...

> It's [referring to `dotnet publish`] the only officially supported way to prepare the application for deployment.

Therefore, beware deploying from `dotnet build` even in Release config ...

🐉 *There probably be dragons there!* 🐉
