### ISSUE TITLE
Tutorials missing steps

### ISSUE THREAD

**Issue by eliassal** [aspnet/Docs#1101]
Hi, I read the  fundamentals / servers.rst, opened the sample but really don't know what to do with the sample, is there any guidance or tutorial to play with the sample "ServersDemo". The page servers.rst gives an overview but it does not guide us on using the sample.
By the way, I went through a couple of tutorials, the todo list api and Contosobooks, the tutorials are missing the code that needs to be added when reading the tutorials, I copied the lines of codes from the downloaded files
Thanks for your help

**Comment by shirhatti** [comment]
The code samples provided in the fundamentals are not structured as tutorials. We will look at updating the fundamentals articles to remove code sample links.

> By the way, I went through a couple of tutorials, the todo list api and Contosobooks, the tutorials are missing the code that needs to be added when reading the tutorials, I copied the lines of codes from the downloaded files.

Can you elaborate on which instructions were missing from the tutorials?

**Comment by shirhatti** [comment]
Moved the first part to https://github.com/aspnet/Docs/issues/1102

**Comment by eliassal** [comment]
If you go to https://github.com/aspnet/Docs/blob/master/aspnet/tutorials/first-web-api.rst, you will find several statements like this "Replace the generated code with" but nothing behind it

**Comment by Rick-Anderson** [comment]
No, it brings in the source file:
```
Replace the generated code with:

.. literalinclude:: first-web-api/sample/src/TodoApi/Models/TodoItem.cs
    :language: c#
```
GitHub is to store the doc, not to read the doc.

**Comment by eliassal** [comment]
Rick, I am a little bit confused, what is "it brings..." who brings, sorry I am not expert in Git

**Comment by Rick-Anderson** [comment]
just read  Read the doc at https://docs.asp.net/en/latest/tutorials/first-web-api.html,, don't try to read the docs on gitHub. Our build system brings in the source file mentioned. See https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md
