### ISSUE TITLE
Not working link

### ISSUE THREAD

**Issue by EvaldasPovilaitis** [aspnet/Docs#11021]
IL Linker: Syntax of xml descriptor: https://github.com/mono/linker/blob/master/linker/README.md#syntax-of-xml-descriptor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5c95675-3daf-be91-3080-25b3e73ff523
* Version Independent ID: b9277aa2-e8e2-7d65-7fc7-28c941eb0c90
* Content: [Configure the Linker for Blazor](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components/configure-linker?view=aspnetcore-3.0)
* Content Source: [aspnetcore/host-and-deploy/razor-components/configure-linker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/razor-components/configure-linker.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... I'll get that fixed up.
