### ISSUE TITLE
Windows Auth Scheme

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#11027]
If I want to [select the scheme w/ the `Authorize` attribute](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x#selecting-the-scheme-with-the-authorize-attribute) for windows auth, I apparently use `"Windows"`.  I stumbled across this [SO Post](https://stackoverflow.com/questions/51053459/asp-net-core-2-0-mixed-authentication-of-jwt-and-windows-authentication-doesnt) that happened to be using it.

```csharp
[Route("api/[controller]")]
[Authorize(AuthenticationSchemes = "Windows")]
public class TestController : Controller { ... }
```

I can't seem to find this documented though.  Is it?

And probably more of a product issue than a doc issue but is there a member I can reference like `JwtBearerDefaults.AuthenticationScheme` or `CookieAuthenticationDefaults.AuthenticationScheme`?  Feels "wrong" to use a string like that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee71441f-471a-89cd-0ef4-9b32b5dd85cf
* Version Independent ID: 0096c365-2f4e-5d21-89a0-c4f10fcb0ed9
* Content: [Authorize with a specific scheme in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/limitingidentitybyscheme?view=aspnetcore-2.2&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authorization/limitingidentitybyscheme.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/limitingidentitybyscheme.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by blowdart** [comment]
It's not documented because it's won't work as you expect. Windows auth is pretty much all or nothing.

**Comment by Tratcher** [comment]
It actually does work. There are three constants (all with the same value) depending on which server you're using.
- IIS out of process: Microsoft.AspNetCore.Server.IISIntegration.IISDefaults.AuthenticationScheme 
- IIS in process: Microsoft.AspNetCore.Server.IIS.IISServerDefaults.AuthenticationScheme 
- HttpSys: Microsoft.AspNetCore.Server.HttpSys.HttpSysDefaults.AuthenticationScheme

**Comment by spottedmahn** [comment]
FYI, I previously tried:

```csharp
using Microsoft.AspNetCore.Server.IISIntegration;
//...
[Authorize(AuthenticationSchemes = IISDefaults.AuthenticationScheme)]
```
but that yields:

>Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0182	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type	Windows and Cookie Auth Expirement	C:\Users\mdepouw\source\repos\GitHub\spottedmahn\Experiments\Windows Auth Expirement\Windows and Cookie Auth Expirement\Controllers\HomeController.cs	81	Active

I see it is defined as `static readonly` not a `const`:

```csharp
namespace Microsoft.AspNetCore.Server.IISIntegration
{
    public class IISDefaults
    {
        //...
        public static readonly string AuthenticationScheme;
        //...
    }
}
```

I got the idea from here: [Configure Windows Authentication in ASP.NET Core -> Work with Windows Authentication -> IIS](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#iis)

---

`Microsoft.AspNetCore.Server.IIS.IISServerDefaults.AuthenticationScheme` works as it is a constant 👍

**Comment by Tratcher** [comment]
Those `static readonly` have been changed to `const` in later versions for this reason.

**Comment by Tratcher** [comment]
These are documented under windows auth:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#iis

**Comment by spottedmahn** [comment]
I see, thanks @Tratcher 👍
