### ISSUE TITLE
Identify exact files where changes are needed

### ISSUE THREAD

**Issue by joeshepherdmba** [aspnet/Docs#11023]
Can you please identify the exact files that need changes? In the first few sections I assume that you are talking about the csproj file but that is never called out specifically. 

Also I assume these steps need to happen for every project in the solution? Overall a little more step by step clarity could make this documentation go a long way. For example above you say "If targeting .NET Core, remove the Version attribute for the metapackage reference. Inclusion of a Version attribute results in the following warning:". 

It's not readily clear what was meant so i had to search elsewhere. I finally found this article and was able to piece it together. https://github.com/dotnet/corefx/issues/32340  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.1&tabs=visual-studio-mac)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
> Can you please identify the exact files that need changes?

Thank you for pointing this out. I've addressed it in the linked PR. The project (*.csproj) file is what you'll need to change in those first steps.

> Also I assume these steps need to happen for every project in the solution?

You are correct. Repeat these steps for each ASP.NET Core project in your solution.
