### ISSUE TITLE
Regarding AzureAppServicesDiagnosticsSettings

### ISSUE THREAD

**Issue by KeiroKamioka0000** [aspnet/Docs#11029]
According the URL of [AzureAppServicesDiagnosticsSettings]
https://docs.microsoft.com/ja-jp/dotnet/api/microsoft.extensions.logging.azureappservices.azureappservicesdiagnosticssettings?view=aspnetcore-2.2

It says "This API is now obsolete." Is current URL is most recent one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#azure-app-service-provider)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@KeiroKamioka0000 Thanks for reporting that.  We're investigating.
