### ISSUE TITLE
This localhost page can’t be found

### ISSUE THREAD

**Issue by kayakingcoder** [aspnet/Docs#11033]
Hi,
I'm in the same position as Itsey who said "I don't see how this works" in the closed issues.

At no point does the article tell us to create a virtual directory / application in IIS that points to the .Net Core application, so I don't understand how they should be linked? I don't mind, but it doesn't work.
I've confirmed that "Development time IIS support" is ticked in VS Installer
In IIS I have added an https binding with hostname "localhost" to "Default Web Site" and selected the IIS Express certificate.
In my .Net core project, I've added a launch profile with launchURL "https://localhost/TradeTribes" similar to how you have "https://localhost/WebApplication1" in the article.

    "IIS": {
      "commandName": "IIS",
      "launchBrowser": true,
      "launchUrl": "https://localhost/TradeTribes",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }

Debug configuration is selected and IIS profile is selected before I click the run/debug button...

But when I debug through VS 2017, I get a 404 on "https://localhost/TradeTribes"

Versions:
VS: 15.9.7
.Net Core: 2.2.104
IIS: 1803 (OS Build 17134.1)

Any idea what I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.2#configure-the-project)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* GitHub Login: @shirhatti
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> At no point does the article tell us to create a virtual directory / application in IIS that points to the .Net Core application

Correct ... you don't.

AFAIK, the procedure described by the topic works. I would've suggested re-walking the steps carefully, but it seems like you've done that already.

@shirhatti Do you know if it requires an IIS restart or a VS restart? Have you heard of anything that commonly trips this up?

**Comment by kayakingcoder** [comment]
You know, I was going to ask yesterday whether .Net Core 2.2 could be my problem as only 2.1 and older are listed in VS Installer, but somehow it slipped my mind.

Turns out I had to install the IIS Hosting Bundle for .net core 2.2 and all is well with the world
https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#install-the-net-core-hosting-bundle

**Comment by guardrex** [comment]
@shirhatti, you didn't list the hosting bundle as required. I had it installed locally when I ran the steps of the topic, so idk the behavior without it.

**Comment by shirhatti** [comment]
😕 That's odd. Installing the hosting bundle shouldn't be required. We install ANCM as part of VS if you select that optional component.

**Comment by shirhatti** [comment]
Also, you don't have to create a vdir as Visual Studio does that for you.

**Comment by guardrex** [comment]
@kayakingcoder We'll probably need a reliable repro in order for engineering to dig into this further. I'll keep an :eye: out for more reports on this topic's guidance failing. Thanks for reporting it.

**Comment by shirhatti** [comment]
Just FYI @jkotalik. In case you think something is amiss

**Comment by kayakingcoder** [comment]
Thanks y'all. I don't have the resources or skill to uninstall everything and try to recreate this scenario. All I know is that my VS Installer doesn't mention 2.2 anywhere (it only has entries like ".Net Core 2.1 development tools"), so I'm not sure why you'd expect it to install the 2.2 hosting bundle.

Anyway, thanks for your help.

**Comment by guardrex** [comment]
... I looked :eyes: and the components listed aren't clear wrt ANCM. Here's what's shown for the two workloads ...

<img width="255" alt="capture" src="https://user-images.githubusercontent.com/1622880/53197698-52d2bd80-35e0-11e9-9e72-0f0d6d89f4a6.PNG">

Not critical, but it might have been good to list for the .NET Core x-plat bits under "Included" a checkmark entry for "ASP.NET Core Module."

Wouldn't matter wrt this issue tho.

I still wonder if a restart of VS and/or IIS is required ... and we don't say to do that currently in this topic if it is required. VS may restart tho with a workload change automatically ... not sure ... don't recall.

**Comment by guardrex** [comment]
I'm going to close due to inactivity and no further engineering notes. We'll keep an :eye: on this topic tho for any further reports.

**Comment by aftabthesun** [comment]
I have allready hosted api on IIS but My image and media not showing on browser
