### ISSUE TITLE
Provide Guidance on when to turn on EnableForHttps for Response Compression

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Docs#11036]
The current docs state:

&gt; Compressed responses over secure connections can be controlled with the EnableForHttps option, which is disabled by default. Using compression with dynamically generated pages can lead to security problems such as the CRIME and BREACH attacks.

I think there are occasions when it is permissable to turn this flag on i.e. when the content of any requests or responses contain no secrets. An example might be a public API about star wars characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response compression in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.2)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@blowdart

**Comment by guardrex** [comment]
The text doesn't say not to use it ... just warns about the risk of doing so.

**Comment by blowdart** [comment]
The text is accurate, and fine as is and we're not about to hedge our bets around security statements.

**Comment by APIWT** [comment]
I have to agree with @RehanSaeed and I suggest re-opening this issue. Adding more guidance would help people make an informed decision about when Microsoft recommends using response compression with HTTPS.
