### ISSUE TITLE
Update DataProtection docs

### ISSUE THREAD

**Issue by javiercn** [aspnet/Docs#1105]
Docs need to acommodate changes for http://github.com/aspnet/dataprotection/issues/120, http://github.com/aspnet/dataprotection/issues/121 and http://github.com/aspnet/dataprotection/issues/122

**Comment by BrennanConroy** [comment]
Some sections are from beta8 and don't even work in RC1 such as https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html

**Comment by javiercn** [comment]
@ajaybhargavb Is doing a refactoring on this area, so it might be worth waiting. @Eilon ?

**Comment by Eilon** [comment]
I think @danroth27 and @blowdart will have to decide on that. They should consult with @ajaybhargavb and @rynowak to get an idea of what the changes are and perhaps use that to gauge which RC2 docs are more important to update, and perhaps which can wait.

**Comment by danroth27** [comment]
@blowdart Can you make these updates? Otherwise, please work with @Rick-Anderson on the changes.

**Comment by blowdart** [comment]
Hah, @javiercn promised to do it when he made the initial changes.

**Comment by blowdart** [comment]
Also we still haven't made that darned sample "officially" ours, that work was waiting for post RC2 @HaoK

**Comment by javiercn** [comment]
@ajaybhargavb Is doing a bunch of changes on the area, so I think he is the best person to do it or help someone do it.

**Comment by BrennanConroy** [comment]
I think this can be closed?
