### ISSUE TITLE
/Health Authenticated

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/Docs#11058]
Document how to authenticate the /health endpoint.

For example:

```cs
    public class AuthenticationForHealthCheckMiddleware
    {
        private readonly RequestDelegate _next;
        public AuthenticationForHealthCheckMiddleware(RequestDelegate next)
        {
            _next = next;
        }
        public async Task Invoke(HttpContext context)
        {

            var route = context.Request.Path;
            if (route.HasValue && route.Value.Contains("/health", StringComparison.OrdinalIgnoreCase)
                && !context.User.Identity.IsAuthenticated)
            {
                context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                await context.Response.WriteAsync("Should be authenticated...");
                return;
            }
            await _next.Invoke(context);
        }
    }
```
Startup.cs
```cs
            app.UseMiddleware<AuthenticationForHealthCheckMiddleware>();
            app.UseHealthChecks("/health");
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cbb094-29e9-740a-9fd6-db372641d753
* Version Independent ID: 52d8efc9-a336-71d9-6d90-98173cbf6bf4
* Content: [Health checks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-2.2#filter-health-checks)
* Content Source: [aspnetcore/host-and-deploy/health-checks.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/health-checks.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vertonghenb ... see :point_right: https://github.com/aspnet/AspNetCore/issues/4544
