### ISSUE TITLE
Certificate error when running the example

### ISSUE THREAD

**Issue by salgiza** [aspnet/Docs#11051]
As soon as you press Ctrl+F5 to launch the app, it runs as an https service (the screenshots are correct, but the explanation in the "Launch the app" still say http.

This has the problem that, at least in macOS, both Safari and Chrome block you from accessing the webpage (because the project seems to generate a self-signed certificate).

It would be nice if the doc fixed all references to http, warned about this problem, and explained where the self-signed certificate is coming from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@salgiza Thanks for reporting this.

 I fixed `http` to use the correct `https`. I'm updating the doc and adding a link to [Trust the ASP.NET Core HTTPS development certificate on Windows and macOS](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.2&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos)

When you launched the app for the first time, did you get prompted to install the certificate with the following?

![image](https://user-images.githubusercontent.com/3605364/53274789-a0146500-369c-11e9-9ec4-b5a4b59f615c.png)

![image](https://user-images.githubusercontent.com/3605364/53274807-ba4e4300-369c-11e9-9a7e-fb92cead4d80.png)
