### ISSUE TITLE
Resource files: Build Action

### ISSUE THREAD

**Issue by QuickScoP3s** [aspnet/Docs#11053]
If you use resource files for localization, it's very important that they have the appropriate build action:
They should be "Embedded Resource" and my VS doesn't set this automatically, resulting in the localizer not being able to find the resources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#provide-localized-resources-for-the-languages-and-cultures-you-support)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please comment.

**Comment by hishamco** [comment]
resx files are embedded resources, but I'd like to know why the VS that are using is not  set the build action, can you send your issue from within feedback inside VS

**Comment by WautW** [comment]
Well, it just didn't do it automatically, but I can change it manually of course ;)

I just wanted to suggest, that you add like a "NOTE" box to the docs, saying the build action should be "Embedded Resource"
This way, should VS not set it automatically, devs still know (cuz I searched for it, about 2h...)

**Comment by QuickScoP3s** [comment]
Well, it just didn't do it automatically, but I can change it manually of course ;)

I just wanted to suggest, that you add like a "NOTE" box to the docs, saying the build action should be "Embedded Resource"
This way, should VS not set it automatically, devs still know (cuz I searched for it, about 2h...)

(Sorry, the other comment was with my other account)

**Comment by Rick-Anderson** [comment]
@QuickScoP3s 	can you make sure VS is up to date? ( **Help > Check for updates**)

Can you try reproduce this? If you can repo it, we should probably add a note. Would you be able to PR and update? You can edit in browser to make the update/PR.

**Comment by QuickScoP3s** [comment]
VS is up to date:
15.9.7

What should I reproduce? The resource file generation, without build action being set?

**Comment by QuickScoP3s** [comment]
VS is up to date:
15.9.7

What should I reproduce? The resource file generation, without build action being set?

**Comment by QuickScoP3s** [comment]
Damn, wrong button...

I wanted to ask: What does PR mean

**Comment by hishamco** [comment]
@Rick-Anderson we can add this to troubleshooting article or point to it in the main article

@QuickScoP3s But again send a feedback from within VS

**Comment by QuickScoP3s** [comment]
Okay, will do 👍

**Comment by hishamco** [comment]
I added that to the troubleshooting docs, @QuickScoP3s if your issue has been fixed, please close this

**Comment by WautW** [comment]
Thank you very much!

**Comment by QuickScoP3s** [comment]
Thank you very much
