### ISSUE TITLE
What is a scoped service?

### ISSUE THREAD

**Issue by nabokov-ef** [aspnet/Docs#11064]
&gt;&gt;Hosted service that activates a scoped service.
I am curious what a scoped service is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It means scoped to the request. I'll crosslink to the Dependency Injection topic. https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2

**Comment by guardrex** [comment]
Leave open ... It will automatically close when the PR merges.
