### ISSUE TITLE
Type or NameSpace REMOTE could not be found

### ISSUE THREAD

**Issue by wgutierrezr** [aspnet/Docs#11061]
I'm trying to add remote validation to my class but I got an error:
        [Remote(controller: "Vendors", action: "ValidateCode", ErrorMessage = "Code already exists!")]
        public string Code { get; set; }

Error:CS0246	The type or namespace name 'Remote' could not be found (are you missing a using directive or an assembly reference?)

Help please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
[`RemoteAttribute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.remoteattribute?view=aspnetcore-2.2) is in the `Microsoft.AspNetCore.Mvc` namespace, so you will need a `using` directive for this:

    using Microsoft.AspNetCore.Mvc;

If you're not using the `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All` metapackages in your project, you might also need a reference to the [`Microsoft.AspNetCore.Mvc.ViewFeatures`](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.ViewFeatures) nuget package.

**Comment by wgutierrezr** [comment]
Hi
Thank you for your answer. I was using Microsoft.AspNetCore.App and the RemoteAttribute library is not there, I had to install Microsoft.AspNetCore.All and everything is ok now.

Regards

**Comment by winsonet** [comment]
I have same issue, and after I reference to the  Microsoft.AspNetCore.Mvc.ViewFeatures nuget package, the issue has been solved, thanks!
