### ISSUE TITLE
Content difference for Core 3.0 vs 2.2

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#11079]
I selected Core 3.0 Preview 2, and downloaded pdf, but the pdf content seems the same as that for 2.2. Am I correct?

How do I know the last update date of the pdf?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd495160-090c-065e-5b98-53b112db0cea
* Version Independent ID: 46699e55-2685-95f8-4b54-dcb66d630000
* Content: [What's new in ASP.NET Core 2.2](https://docs.microsoft.com/en-gb/aspnet/core/release-notes/aspnetcore-2.2?view=aspnetcore-3.0)
* Content Source: [aspnetcore/release-notes/aspnetcore-2.2.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/release-notes/aspnetcore-2.2.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @PingPongSet ... This topic only pertains to 2.2. There's no 'What's new' topic content *yet* for 3.0. We'll be producing that content shortly ... around the time that the 3.0 release candidate is released by engineering. Today, there's only a migration topic, and that topic will be receiving additional updates as we get closer to the 3.0 release. https://docs.microsoft.com/aspnet/core/migration/22-to-30
