### ISSUE TITLE
What is the purpose of adding .AddRoles<IdentityRole>()?

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#11070]
What is the purpose of adding .AddRoles&lt;IdentityRole&gt;()?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Adds the role service.

**Comment by ryanbrandenburg** [comment]
@Rick-Anderson it doesn't seem that there's a work item here since the line now reads `Append AddRoles to add Role services`. Should we close this out?
