### ISSUE TITLE
"Deployment Options" changed to "Deployment Center" in Azure Portal

### ISSUE THREAD

**Issue by bassambst** [aspnet/Docs#11074]
Under section "Disconnect local Git deployment" and step #2 Click "Deployment options". 
The naming is changed. It is called "Deployment Center" now in Azure Portal. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec897b11-5ad4-a660-598c-daa98d81c536
* Version Independent ID: d4f12beb-b256-ab36-80f1-50c8207b0b1e
* Content: [Continuous integration and deployment - DevOps with ASP.NET Core and Azure](https://docs.microsoft.com/en-us/aspnet/core/azure/devops/cicd?view=aspnetcore-2.2)
* Content Source: [aspnetcore/azure/devops/cicd.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/azure/devops/cicd.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Any chance you could PR this? At the top right of the article, select the pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.
