### ISSUE TITLE
Decorating "Price" with [Column(TypeName = "decimal(18, 2)")] causes migration to fail later

### ISSUE THREAD

**Issue by fmachadopiriz** [aspnet/Docs#11078]
In the "Add a new field" step, when adding the "Rating" field, migration fails with message "SQLite does not support this migration operation ('AlterColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.". This is caused by the "Price" field modification, not by the "Rating" field addition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Skip that when using SQLite.
Were tracking this in #9991
@tdykstra 	might include SQLite instructions in the next refresh.
