### ISSUE TITLE
aspnet/Docs/blob/master/aspnetcore/razor-components/get-started.md

### ISSUE THREAD

**Issue by ruant** [aspnet/Docs#11086]
# Issue description
On aspnet/Docs/blob/master/aspnetcore/razor-components/get-started.md the Project Templates image should be updated since to match the new design that's in VS2019.

Would have done a PR, but the image is hosted elsewhere so can't update.

**Comment by ruant** [comment]
![image](https://user-images.githubusercontent.com/1150473/53346740-ed503b00-3917-11e9-8bca-0d76911b8ec4.png)

**Comment by Rick-Anderson** [comment]
We'll be updating all these in the next doc sweep.

**Comment by Rick-Anderson** [comment]
We prefer issues be created from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)

**Comment by Rick-Anderson** [comment]
cc @guardrex 	if possible, avoid images.

**Comment by guardrex** [comment]
I do ... it was engineering ... *you know who.* :smile:
