### ISSUE TITLE
Development environment by design?!

### ISSUE THREAD

**Issue by voroninp** [aspnet/Docs#11083]
WTF?! Nowhere this insane default is documented. 

```CSharp
protected virtual IWebHostBuilder CreateWebHostBuilder()
{
    var builder = WebHostBuilderFactory.CreateFromTypesAssemblyEntryPoint&lt;TEntryPoint&gt;(Array.Empty&lt;string&gt;());
     if (builder == null)
     {
         throw new InvalidOperationException(Resources.FormatMissingCreateWebHostBuilderMethod(
                    nameof(IWebHostBuilder),
                    typeof(TEntryPoint).Assembly.EntryPoint.DeclaringType.FullName,
                    typeof(WebApplicationFactory&lt;TEntryPoint&gt;).Name,
                    nameof(CreateWebHostBuilder)));
      }
      else
      {
          return builder.UseEnvironment("Development");
      }
}
```
It looks like sometimes decisions are made intentionally to make developers suffer. By default regular aspnet core application runs under `Production` environment, unless other value is set explicitly.

This is what YOUR [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2) state:

>If ASPNETCORE_ENVIRONMENT isn't set, it defaults to Production.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#basic-tests-with-the-default-webapplicationfactory)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@voroninp I was heading in this direction with https://github.com/aspnet/Docs/pull/9060 based on convo of https://github.com/aspnet/Docs/issues/8917, but it wasn't embraced by engineering. However, I'm sure that a note on this is entirely reasonable and will be welcome. I'll get it in there by the end of the day.
