### ISSUE TITLE
Not all private message sending examples are provided

### ISSUE THREAD

**Issue by Dafeg** [aspnet/Docs#11087]
This section has not implementation example of private message sending in client side. 
It seems that it is not clear from where "userIdentifier"(id of private message receiver)  could be got in the client side before sending to the server side. 
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by bradygaster** [comment]
We moved some of the user-specific content over to the [auth article](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2). Please take a look there. Closing this issue as that's the close of what we expected to do with this segment of the docs.

**Comment by Dafeg** [comment]
Thanks a lot!)
