### ISSUE TITLE
Google Authentication Guides for  ASP.NET Core 1.x

### ISSUE THREAD

**Issue by newbienewbie** [aspnet/Docs#11105]
Hi, 

Several days ago, I was interested in [a google authentication related question on SO](https://stackoverflow.com/questions/54802763/adding-a-net-authentication-abstraction-for-google-sign-in-to-a-net-core-1-x-s) because I notice that [Tratcher](/Tratcher) shows us a great solution for Google Authtication(https://github.com/aspnet/AspNetCore/issues/6486) but I have never had a change to deal with ASP.NET Core 1.x in practice.

As I'm not familiar with ASP.NET Core 1.x , I search on the [docs.microsoft.com](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-1.1# ) . However all the contents  are about ASP.NET Core v2+ even I select the `ASP.NET Core 1.1` version . For example, I tried the [following code](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-1.1#multiple-authentication-providers):
```csharp
services.AddAuthentication()
    .AddMicrosoftAccount(microsoftOptions => { ... })
    .AddGoogle(googleOptions => { ... })
    .AddTwitter(twitterOptions => { ... })
    .AddFacebook(facebookOptions => { ... });
```
But it doesn't work. Because the [`AddGoogle()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.googleextensions.addgoogle?view=aspnetcore-2.0#applies-to)  is added as of 2.0 . I realize that these APIs are [not available with ASP.NET Core 1.x](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.2#authentication-middleware-and-services)

1. I know ASP.NET Core v1.x will reach its EOF on June 27, 2019. But there're still 4 months left.  How can I view the docs for v1.x without  checkouting the commit of [some particular version](https://github.com/aspnet/Docs/commits/master/aspnetcore/security/authentication/social/google-logins.md) ?
2. Thanks to @Tratcher , [he told us](https://github.com/aspnet/AspNetCore/issues/6486) the mitigation for Microsoft.Owin can also be adapted for ASP.NET Core 1.x.  So, if the first question is possible, I would appreciate if you guys kindly add the [solution](https://github.com/aspnet/AspNetKatana/issues/251#issuecomment-449587635) to the docs.

Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-1.1#)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
1. I don't know if there's a cached copy of the 1.x docs beyond the source control, but at this point most resources are focused on creating new docs for the upcoming 3.x so do not expect any new content for the remainder of 1.x. In fact, the docs from Microsoft.Owin where these auth components were originally taken from will get you most of the way there: https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on. 
2. The different patterns for AddGoogle vs UseGoogleAuthentication do not substantially affect the mitigation for the G+ issue. What's missing in 1.x is the ability to dynamically change how claims are mapped from user data. If you're having trouble adapting the Microsoft.Owin mitigation to 1.x let me know and we can work through it. The result would be best shared on that announcement.

**Comment by newbienewbie** [comment]
@Tratcher  Thanks for your detailed explanation.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
