### ISSUE TITLE
RedisCache links should go to the newer Caching.StackExchangeRedis package

### ISSUE THREAD

**Issue by marekr** [aspnet/Docs#11118]
The page still links to the older RedisCache package that is effectively deprecated.
There's the newer Microsoft.Extensions.Caching.StackExchangeRedis package that uses the 2.x versions of stack exchange redis and is also built for 2.2 (and I'm guessing later 3.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Distributed caching in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2#distributed-redis-cache)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the heads-up @marekr ... I'll take a look this afternoon.
