### ISSUE TITLE
Are comments permitted in appsettings.json?

### ISSUE THREAD

**Issue by ryanwebjackson** [aspnet/Docs#11114]
I'm aware that comments are not part of a valid JSON file, but am wondering if the FileConfigurationProvider checks for them, either accepting or rejecting the configuration file -- it's not clear to me from this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
[`JsonConfigurationProvider`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.configuration.json.jsonconfigurationprovider), which inherits from [`FileConfigurationProvider`](https://docs.microsoft.com/dotnet/api/microsoft.extensions.configuration.fileconfigurationprovider), uses Newtonsoft.Json to parse .json files. It supports both both single- and multi-line comments, which means you *can* include comments in `appsettings.json` and the parser will just ignore them without issue.

**Comment by guardrex** [comment]
Follow-up with the engineers on the announcement ...

https://github.com/dotnet/corefx/issues/33115#issuecomment-434113532

... seems like it will be an opt-in opportunity.
