### ISSUE TITLE
DbSet has not "Count" method

### ISSUE THREAD

**Issue by m1u1n2kh2** [aspnet/Docs#11119]
In the controller code, call a Count method of  TodoItems DbSet. But, DbSet hasn't Count method.

if (_context.TodoItems.Count() == 0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-code#add-a-controller)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by georgiqg** [comment]
The Count() method is provided by the System.Linq namespace. Make sure you have the corresponding using statement.
