### ISSUE TITLE
Update usage around processesPerApplication

### ISSUE THREAD

**Issue by DAllanCarr** [aspnet/Docs#11122]
There is a github issue open https://github.com/aspnet/AspNetCore/issues/3798. Needs clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2&WT.mc_id=-blog-scottha#in-process-hosting-model)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @DAllanCarr

@shirhatti It looks like no action has been taken, but do you want to triage this one way or the other: I need guidance on what to change/add, or we close for now (i.e., we can open an issue later for it when there's something actionable to do).

**Comment by shirhatti** [comment]
Can you update the docs to indicate that `processesPerApplication` is discouraged and will be dropped in a future version?
