### ISSUE TITLE
Azure Apps ANCM debug log location

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#11137]
Current guidance places the log in the root of the app. Let's have devs shoot the log into the *LogFiles* folder, which is the same location we use for the stdout logging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 587ea934-c90e-54a3-c708-83d36cf621b4
* Version Independent ID: c2f26258-1119-e6c2-3f2d-d0f0cddbdb7f
* Content: [Troubleshoot ASP.NET Core on Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/troubleshoot?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by jkotalik** [comment]
Sounds good.

**Comment by guardrex** [comment]
Using the same path for stdout logging **fails** to generate the log file ...

```xml
<handlerSetting name="debugFile" value="\\?\%home%\LogFiles\aspnetcore-debug.log" />
```

Therefore, the topic should indicate that it will generated in the app's content root and should be examined using the Kudu console.

**Comment by guardrex** [comment]
It's already covered for the content root, so no changes are required for the current guidance. 

Since I couldn't get `\\?\%home%\LogFiles\` to work with a test app, let's stick with the current guidance.
