### ISSUE TITLE
DNX - Using Commands - SqlConfig section contains commands from SecretManager

### ISSUE THREAD

**Issue by aleksandradz** [aspnet/Docs#1114]
[https://docs.asp.net/en/latest/dnx/commands.html#global-commands-details](https://docs.asp.net/en/latest/dnx/commands.html#global-commands-details)
Section **SqlConfig** contains table with commands and note the same as section above, SecretManager (looks like copy-paste)
![image](https://cloud.githubusercontent.com/assets/17968828/13907050/a301f64e-eee5-11e5-9dae-d34dd8117338.jpeg)

**Comment by danroth27** [comment]
Nice catch :-). This article is going away in RC2 since we are moving off of DNX and onto the new [.NET CLI](https://github.com/dotnet/cli), but this update should be pretty quick.

**Comment by danroth27** [comment]
No longer relevant now that we've moved to .NET Core.
