### ISSUE TITLE
Add instructions for .NET Framework

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/Docs#11164]
Re:
> The test project must:
> - Reference the following packages:
>     - Microsoft.AspNetCore.App
>     - Microsoft.AspNetCore.Mvc.Testing

The Microsoft.AspNetCore.App package does not target .NET Standard so it cannot be installed in a project that targets .NET Framework. Please add instructions for testing ASP.NET Core on .NET Framework 4.7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#test-app-prerequisites)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @StevenLiekens ... I wasn't given guidance for that scenario, and I think it will be a *no-go* ... e.g., ASP.NET Core 3.0 will only run on .NET Core, and we'll be divorcing all .NET Framework content from this docs repo as we go forward in time.

@javiercn

**Comment by javiercn** [comment]
Sounds right to me. I believe the package is NETStandard but that moving forward it will be netcoreapp3.0 only as it depends on the shared framework.

**Comment by guardrex** [comment]
@StevenLiekens ... I'll leave it with some remarks from [ASP.NET Core 3.0 will only run on .NET Core](https://github.com/aspnet/Announcements/issues/324) ...

* "Support and servicing for 2.1 will continue until at least August 21, 2021"
* "For more information about porting from .NET Framework to .NET Core, ..."

... and let you be the judge of where things are heading. **_'No comment' from me on this._**

What I can tell you is that we're a *very* small team of doc authors, and we're 🏃🏃🏃🏃😅 with doc updates in advance of the 3.0 Release Candidate. If you or a member of the community would like to pitch language a new topic in the upcoming ASP.NET docs (we're splitting .NET Framework and ASP.NET Core topics into two repos), then management would at least consider the offer.

**Comment by StevenLiekens** [comment]
Thanks for the information. If you'd like, I can submit a PR to clarify that this topic only applies to .NETCoreApp 2.x.

**Comment by StevenLiekens** [comment]
See #11201
