### ISSUE TITLE
Update hosting environment variable name to ASPNETCORE_ENVIRONMENT

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1117]

**Comment by shirhatti** [comment]
https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting.Abstractions/WebHostDefaults.cs

**Comment by danroth27** [comment]
We should do a general scrub to rename ASPNET_ENVIRONMENT and Hosting:Environment to ASPNETCORE_ENVIRONMENT.

**Comment by spboyer** [comment]
There are currently no references to ASPNET_ENVIRONMENT in the repo or samples. Can we close this? @rachelappel @danroth27
