### ISSUE TITLE
Add link to RP areas

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#11195]
Add link to [RP areas](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.2#areas-with-razor-pages)

`<xref:mvc/controllers/areas#areas-with-razor-pages>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66c32c8-ec27-1771-bb62-71d6aa55b1d6
* Version Independent ID: 99dc76fb-8762-20a6-d7b1-df3ce6e6fc4d
* Content: [Razor Pages route and app conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/razor-pages-conventions?view=aspnetcore-2.2&branch=pr-en-us-11194)
* Content Source: [aspnetcore/razor-pages/razor-pages-conventions.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/razor-pages-conventions.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guardrex 	can you add `#areas-with-razor-pages>` to `<xref:mvc/controllers/areas#areas-with-razor-pages>`

**Comment by guardrex** [comment]
"add **_to_**" 😕 ... `<xref:mvc/controllers/areas>` doesn't exist in this topic. Add it to *Additional resources*?

**Comment by Rick-Anderson** [comment]
Sure and anywhere you talk about URL generation.

**Comment by guardrex** [comment]
There's no discussion of URL generation in the topic AFAIK. I'll confirm when I add the link.
