### ISSUE TITLE
Adopt the IIS in-process hosting model - custom web.config

### ISSUE THREAD

**Issue by edwiles** [aspnet/Docs#11217]
An additional upgrade step when adopting the IIS in-process hosting model: If you have a custom web.config that currently contains modules="AspNetCoreModule", this needs to be changed to "AspNetCoreModuleV2".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Great idea @edwiles, and I'll include `hostingModel="InProcess"`, too.

**Comment by guardrex** [comment]
May as well do the 3.0 changes for the 2.2 to 3.0 migration doc while I'm at it.

**Comment by edwiles** [comment]
Actually that's a question - if <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel> is present in the web csproj, do we need hostingModel="inProcess" in the custom web.config?

**Comment by guardrex** [comment]
Here's the logic ...

https://github.com/aspnet/websdk/blob/06b8237d0c3d7cd712c3f9619afef541ad5502cd/src/ProjectSystem/Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.targets#L24

As you can see, it's **_only used there_**, so the answer is *not really*. If you have a custom *web.config*, then you can *only set the* `hosting model` *attribute on the element* and you don't need the project file entry. However, I would go ahead and set it myself ... just in case later the custom *web.config* is removed from the project. I would want the opt-in in-process behavior if the project ever went *back* to a non-custom *web.config* setup.

In the 2.1 to 2.2 migration topic, I think it best to:

* Leave the project file property info for hosting model in its current section.
* Have the custom *web.config* remarks in another section.
* Not describe it further.

We're recommending to devs to go with in-process. Therefore, it's best to have both sections go that way.

WRT 3.0 ... In-process is by-default, so we can let devs remove the project file prop if they want to. WRT a custom *web.config* there, I assume that they already have a good 2.2 starting app configured however they want with or without the *web.config*. No changes are required.
