### ISSUE TITLE
Document process for collecting crash dumps

### ISSUE THREAD

**Issue by pakrym** [aspnet/Docs#11210]
For AppServices we might want to use https://blogs.msdn.microsoft.com/asiatech/2015/12/28/use-crash-diagnoser-site-extension-to-capture-dump-for-intermittent-exception-issues-or-performance-issues-on-azure-web-app/ as a basis

For on-prem scenarios there is https://docs.microsoft.com/en-us/windows/desktop/wer/collecting-user-mode-dumps but we might want to turn it into exact set of steps with correct values or even a powershell script (https://github.com/aspnet/AspNetCore/blob/cb21edc5009b254388fc6da93d212f679087c326/.azure/pipelines/tools/SetupTestEnvironment.ps1#L71-L73).

cc @guardrex @shirhatti

**Comment by guardrex** [comment]
> AppServices

Let me know if you have notes that I should drop into the text. This will likely be a short section in the [App Services Troubleshooting topic](https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot).

> on-prem scenarios

I recommend specific steps or the PS approach. Can engineering provide the steps and/or the script? If so, what would the ETA look like ... should I push this issue back to April (or later)?

**Comment by pakrym** [comment]
I'll write a script today

**Comment by pakrym** [comment]
### EnableDumps.ps1

``` powershell
param(
    [Parameter(Position=0,mandatory=$true)]
    $application,
    [Parameter(Position=1,mandatory=$true)]
    $location
    )

$werHive = "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting";
$ldHive = "$werHive\LocalDumps";
$applicationHive = "$ldHive\$application";

if (!(Test-Path $ldHive))
{
    New-Item -Path $werHive -Name "LocalDumps";
}

if (!(Test-Path $applicationHive))
{
    New-Item -Path $ldHive -Name $application;
}

New-ItemProperty $applicationHive -Name "DumpFolder" -Value $location -PropertyType "ExpandString" -Force;
# Allow maxinum 5 dumps
New-ItemProperty $applicationHive -Name "DumpCount" -Value 5 -PropertyType "DWORD" -Force;
# 2 - Full Dump
New-ItemProperty $applicationHive -Name "DumpType" -Value 2 -PropertyType "DWORD" -Force;
```

### DisableDumps.ps1

``` powershell
param(
    [Parameter(Position=0,mandatory=$true)]
    $application
    )

$werHive = "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting";
$ldHive = "$werHive\LocalDumps";
$applicationHive = "$ldHive\$application";

if (Test-Path $applicationHive)
{
    Remove-Item $applicationHive -Force;
}
```

### Usage

``` powershell
# OutOfProcess
.\EnableDumps dotnet.exe c:\dumps
# InProcess
.\EnableDumps w3wp.exe c:\dumps

.\DisableDumps dotnet.exe
.\DisableDumps w3wp.exe
```
