### ISSUE TITLE
A bit stuck

### ISSUE THREAD

**Issue by dirkesquire** [aspnet/Docs#11225]
Trying to follow the instructions and did all the pre-requisuites except that Visual Studio 2019 Preview for Mac doesn't seem to want to install the Blazor .vsix extension. In fact it doesn't seem to recognise .vsix as a valid extension file. How do we install the Blazor extension for VS 2019 Preview for Mac? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-gb/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27

**Comment by danroth27** [comment]
@dirkesquire Thanks for trying out Blazor!

The Blazor Visual Studio extension is only for Visual Studio on Windows. Visual Studio for Mac uses a different extensibility model. Unfortunately, we don't have support for Blazor/Razor Components tooling and templates on Visual Studio for Mac just yet, but it's something we do plan to get to: https://github.com/aspnet/AspNetCore/issues/5490. You can however use the .NET Core SDK to create, build, and run Blazor/Razor Component projects and then use a simple text editor (like Visual Studio Code) to edit your component files.

@sayedihashimi

**Comment by dirkesquire** [comment]
Great thanks for confirming. I just wish this was clear in the article as it does not really say that this is for Windows developers only?
I did get the command line Blazor template to run nicely.
However my usecase is ultimately this is something that needs to be cross compatible with our team of windows and mac developers.

**Comment by sayedihashimi** [comment]
Yes, we don’t have support for Blazor in Vidal Studio for Mac yet but it is on our roadmap. We have some more fundamental features that we are focused on at this time.
