### ISSUE TITLE
Loading appsettings.<>.json file when hosted via Windows Service.

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#11224]
Please provide details on how to Load appsettings.&lt;&gt;.json file when hosted via Windows Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The configuration providers described in the Configuration topic work for Windows Services app.

See :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/configuration/#json-configuration-provider

`CreateDefaultBuilder` is called by the sample app in the Windows Service topic, so the configuration in the *appsettings.{ENVIRONMENT}.json* is consumed by the app.

See :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service

**Comment by nicksav** [comment]
Guys, why not provide at least ONE simple example???

**Comment by guardrex** [comment]
@nicksav Please don't comment on closed issues/PRs. Open a new issue using the **This Page** feedback button+form at the bottom of any topic to open an issue for that topic, which will ping the author automatically and add metadata to the opening comment to help us work the issue.
