### ISSUE TITLE
Menu links in page header not updated when logging out after scaffolding Login/Logout/Register pages

### ISSUE THREAD

**Issue by kschenkeveld** [aspnet/Docs#11231]
After I added several of the standard identity pages to my project (Add--&gt;New Scaffolded Item, Identity, then selected the Login, Logout, and Register items) the behaviour of Logout has changed. Before including the standard pages the menu links in the header would be refreshed when logging out, replacing the name of the logged in user and Logout with Login. After including the pages the menu in the page header still shows the logged in user and Logout. Note that the contents of the page itself are correct (shows the Logout page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/965
