### ISSUE TITLE
Is app.UseMvc() or app.UseMvcWithDefaultRoute() required for Web API?

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#11241]
Is app.UseMvc() or app.UseMvcWithDefaultRoute() required for Web API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.2#additional-resources)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes

**Comment by greenemichael** [comment]
> Yes

thanks but.. which one.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.mvcapplicationbuilderextensions.usemvcwithdefaultroute?view=aspnetcore-2.2

**Comment by Rick-Anderson** [comment]
`UseMvcWithDefaultRoute` is for controllers  with views, not  Web API

**Comment by greenemichael** [comment]
of course... thanks!
