### ISSUE TITLE
More details or example on this

### ISSUE THREAD

**Issue by PingPongSet** [aspnet/Docs#11244]
More details or example on below:
"
IWebHostBuilder configuration is added to the app's configuration, but the converse isn't true—ConfigureAppConfiguration doesn't affect the IWebHostBuilder configuration.
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#override-configuration)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That's correct @PingPongSet ... the host is already built by the time the app is running, so there can't be additional host configuration at that point.
