### ISSUE TITLE
Secure data sample build error

### ISSUE THREAD

**Issue by chanmmn** [aspnet/Docs#11257]
I have this message during build 
"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ApplicationDbContext' does not contain a definition for 'FirstOrDefaultAsync' and no accessible extension method 'FirstOrDefaultAsync' accepting a first argument of type 'ApplicationDbContext' could be found (are you missing a using directive or an assembly reference?)	ContactManager	C:\Users\chan.mn\Downloads\ASPNET\final2\Pages\Contacts\Edit.cshtml.cs	58	Active".

I downloaded the source from here https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization/secure-data/samples/final2

**Comment by guardrex** [comment]
Hello @chanmmn ... 2.0 is no longer supported. Can you try the 2.1 sample at :point_right: https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization/secure-data/samples/final2.1
