### ISSUE TITLE
Source files not found

### ISSUE THREAD

**Issue by chanmmn** [aspnet/Docs#11256]
Can the code be downloaded anywhere? I do not see any download link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @chanmmn ... Yes, the code used by this topic can be found here :point_right: https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/startup/sample_snapshot
