### ISSUE TITLE
Update usage of IMemoryCache.CreateLinkingScope

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Docs#1125]
It is being removed in rc2.

**Comment by danroth27** [comment]
https://docs.asp.net/en/latest/performance/caching/memory.html?highlight=createlinkingscope

**Comment by danroth27** [comment]
@sebastienros @muratg @Eilon Was there an announcement for what changed here that we can reference? If not, can someone summarize what replaced this functionality?

**Comment by Eilon** [comment]
This is the PR that removed it: https://github.com/aspnet/Caching/pull/168

@Tratcher, you signed off on the change, and @sebastienros is OOF, can you provide the info that @danroth27 requested?

**Comment by Tratcher** [comment]
Scopes are now built into the lowest level memory cache API CreateEntry. CreateEntry creates the scope, then you configure the entry, then you dispose the creator to close the scope and add the key/value to the cache. Gets or Sets/Creates within the scope will copy their ChangeTokens to the new entry.

Here's a sample:
https://github.com/aspnet/Caching/blob/f15fb804cdc2e14f9a64896817f3c6c343110820/samples/MemoryCacheSample/Program.cs#L95-L107

**Comment by dealdiane** [comment]
@Tratcher  which means that calling `AddEntryLink` has become redundant hence it was also removed? Is that right?

**Comment by Tratcher** [comment]
Yes and Yes. I don't think there is an opt-out.

**Comment by Rick-Anderson** [comment]
Closing as `CreateLinkingScope` seems to be removed.
