### ISSUE TITLE
UseUrls

### ISSUE THREAD

**Issue by gaziqbal** [aspnet/Docs#11263]
UseUrls is introduced in the "Endpoint Configuration" without any context. It would be helpful to provide the list of URL configuration options with examples first. We have to wait until the "Specify URLs using the:" section to find out that it's an extension method of some sort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#endpoint-configuration)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks for this feedback @gaziqbal ... I agree.
