### ISSUE TITLE
UseCookiePolicy & Sessions

### ISSUE THREAD

**Issue by PKGeorgiev** [aspnet/Docs#11269]
It should be noted in Docs that sessions won't work until the user accepts the GDPR rules presented in the website (i.e. the user accepts use of cookies). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and app state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's covered by the following remark in the [Session state](https://docs.microsoft.com/aspnet/core/fundamentals/app-state?view=aspnetcore-2.2#session-state) section ...

> There's no default mechanism to inform app code that a client browser has been closed or when the session cookie is deleted or expired on the client. The ASP.NET Core MVC and Razor pages templates include support for General Data Protection Regulation (GDPR) support. Session state cookies aren't essential, session state isn't functional when tracking is disabled.

I think the wording could be a hair clearer ... along the lines of ...

> Session state cookies aren't marked essential by default, so session state isn't functional unless tracking is permitted by the site visitor. For more information, see \<xref:security/gdpr>.

... and the topic explains how to make the cookie essential.

Let's do that ... I'll put it in and see how we like it.
