### ISSUE TITLE
Config retrieval examples

### ISSUE THREAD

**Issue by gaziqbal** [aspnet/Docs#11265]
From the GetValue section and onward, the examples use a "config" object. However, there is no guidance or examples on how to actually get a config object. It would be helpful to show a complete example.

It is not clear if configs are available in the ConfigureServices() context when is called after CreateDefaultBuilder(). 
Or if it is necessary to wait for Startup to access the IConfiguration object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#configureappconfiguration)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, the pattern in the Options topic is better: https://docs.microsoft.com/aspnet/core/fundamentals/configuration/options#general-options-configuration

The Configuration topic relies on the slightly cryptic remark ...

> IConfiguration is available in the app's Dependency Injection (DI) container.

... in the *Conventions* section. An example right there would clarify the injection of the `IConfiguration` for later sections.

WRT "no guidance" ... in the text, perhaps, but it's challenging to get 100% framework scenario coverage in the text. The sample apps for most of our topics help. In this case ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index/samples/2.x/ConfigurationSample/Pages/Index.cshtml.cs

However, I do want to enhance the *Conventions* section. It could say 'see the sample app,' but **_Nah!_** I think an in-text example is best, so I'll try that first.

> It is not clear if configs are available in the ConfigureServices() context when is called after CreateDefaultBuilder(). Or if it is necessary to wait for Startup to access the IConfiguration object.

Yes, it should ✨ *Just Work!*:tm: ✨ I'll add a remark about it in the section that pertains to `ConfigureAppConfiguration` ...

https://docs.microsoft.com/aspnet/core/fundamentals/configuration/#configureappconfiguration

**Comment by gaziqbal** [comment]
Thank you! I missed the DI container bit. I think it would be helpful if the GetValue section was prefaced with a skeleton example which used CreatedDefaultBuilder and loaded values from an IConfiguration.

**Comment by guardrex** [comment]
Let's see how it looks by placing it into *Conventions* first. That's very early. It's fairly simple code conceptually.

I'll have it submitted in a minute.
