### ISSUE TITLE
SQLite does not support this migration operation ('AlterColumnOperation').

### ISSUE THREAD

**Issue by cheebz** [aspnet/Docs#11268]
Hi I am getting the above error when trying to run the "dotnet ef database update" cli command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by super2broom** [comment]
So what was the resolution here? I've run into the same problem. Been trying everything. I tried:
1) Deleting the MvcMovie.db file
2) dotnet ef database drop
3) dotnet ef migrations remove (in case there were any migrations pending)\

Still reaching the same error. Maybe something's missing from the doc.

**Comment by Rick-Anderson** [comment]
Any of those should work.

**Comment by Rick-Anderson** [comment]
`dotnet ef migrations remove` is the preferred approach..

**Comment by cheebz** [comment]
> `dotnet ef migrations remove` is the preferred approach..

This was how I ended up resolving the issue

**Comment by MDorhamy** [comment]
1: remove current database
2: run 'dotnet ef migrations remove' to remove all migrations
3: run 'dotnet ef migrations add initialCommit'
4: run 'dotnet ef database update'

**Comment by hungnvo** [comment]
would this work with all operations (edit, delete..) or just for adding a new field?

**Comment by Sameelfm** [comment]
Sqllite has some limitations, My trick was removing the last migration and edit the previous or the table you need to alter created migration with new column name or what ever you need and do the database update

**Step 1**
dotnet ef migrations remove

**Step 2**
Then alter the previous migration that you need to alter the table column or remove column

**Step 3**
dotnet ef database update

**Comment by usmanchaudary** [comment]
as per this link: 
https://docs.microsoft.com/en-us/ef/core/providers/sqlite/limitations
if you can upgrade your .net version to .net5 then all the operations are supported.
