### ISSUE TITLE
When deploying new code to an ASP.NET Core Windows Service, is there a mechanism to seamlessly transition from the old to the new code without aborting requests?

### ISSUE THREAD

**Issue by madelson** [aspnet/Docs#11279]
When we want to deploy new code to an active app in legacy ASP.NET on IIS, IIS seamlessly handles this by drain-stopping the existing app domain while simultaneously spinning up the new one.

How does this work with ASP.NET Core for Windows Services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Currently (based on the Web Host), the requests should drain up to the Kestrel shutdown timeout: https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#shutdown-timeout

WRT the Generic Host (but we haven't documented Windows Services with the Generic Host yet; that's coming up asap after 3.0 RTM, which is scheduled for later this year), should go along the lines of 🤞🍀 ...

```csharp
services.Configure<HostOptions>(option =>
{
    option.ShutdownTimeout = System.TimeSpan.FromSeconds(20);
});
```

https://docs.microsoft.com/dotnet/api/microsoft.extensions.hosting.hostoptions.shutdowntimeout?view=aspnetcore-2.2#Microsoft_Extensions_Hosting_HostOptions_ShutdownTimeout

I'd ask engineering, but this isn't the best time. They're all 🏃🏃🏃🏃😅 at the moment. There was a prototype. Idk if it's still good ... if it will run on 3.0 preview bits ... but you can look it over and perhaps give it a go: https://github.com/aspnet/Hosting/pull/1492#issuecomment-405298223.

If you set up an app and don't get requests to drain up to the shutdown timeout, then open an issue at [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues), but I doubt that you'll have trouble with it. AFAIK, the shutdown should be graceful inside of the limit (that you can set using either host) and it all should ✨ *Just Work!*:tm: ✨
