### ISSUE TITLE
Please provide more information on the performance implications of in-process vs. out-of-process hosting

### ISSUE THREAD

**Issue by madelson** [aspnet/Docs#11278]
Currently the docs say:

&gt; Performance tests indicate that hosting a .NET Core app in-process delivers significantly higher request throughput compared to hosting the app out-of-process and proxying requests to Kestrel server.

Since my app currently has to target .NET Framework and thus in-process hosting isn't available, this is a cause for alarm. Unfortunately, there isn't sufficient detail to help me make a decision on how to proceed. In particular, I'd want to know:

* How does out-of-process ASP.NET Core compare to legacy in-process ASP.NET? Since I'm converting from legacy ASP.NET, I'm ok with anything that won't degrade performance.
* More detail about what performance benchmarks have shown. Is the difference in throughput 10x? 2x? 1.1x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> there isn't sufficient detail to help me make a decision

That would be impossible to provide given that environments and apps vary widely. Even using 3rd party code could influence the result.

> anything that won't degrade performance

You'll have to test. Load test your NetFX app and create an ASP.NET Core version of it and load test that under the same environmental conditions (SxS if possible ... same server, etc.). That's the only way for your app and environment to see what kind of hit you'll take.

In general, the engineers have identified a perhaps&dagger; 400% increase in perf.&Dagger;

&dagger;Under ideal conditions with plain text benchmarking IIRC.
&Dagger;Reference: https://devblogs.microsoft.com/aspnet/asp-net-core-2-2-available-today/. You might be able to get more info in the [aspnet/Benchmarks](https://github.com/aspnet/Benchmarks) repo. Not sure tho ... search their issues (open and closed) with something like "in-process" to see what's been discussed. If there are no issue, you can ask them there about benchmarking these scenarios. IIRC, it has been discussed/proposed *somewhere*. Search the [aspnet/AspNetCore issues (open and closed)](https://github.com/aspnet/AspNetCore/issues) for info, too.
