### ISSUE TITLE
Please mention the dotnet core sdk version this feature available

### ISSUE THREAD

**Issue by MishalValiyakath** [aspnet/Docs#11284]
Please mention the dotnet core sdk version this feature available. Currently, I am getting invalid switch -au Individual while running the dotnet new command for angular or react with this new switch with dotnet 3.0 preview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21cb7455-3305-9316-5440-bdc22947a82d
* Version Independent ID: 137d4b94-7b26-3911-b22d-42c754a95fc1
* Content: [Introduction to authentication for Single Page Applications on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authentication/identity-api-authorization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-api-authorization.md)
* Product: **aspnet-core**
* GitHub Login: @javiercn

**Comment by EricDAllen** [comment]
The -au switch doesn't work for me on 2.2.
Maddening.  This article _looks_ like exactly what I want.

**Comment by javiercn** [comment]
This is a 3.0 feature that is part of our preview3 release that will be available soon.

**Comment by EricDAllen** [comment]
Roger.  Having gotten to it by looking at the 2.2 docs, though, I thought that might be worth mentioning....

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-2.2

For the record, _is_ there a proposed solution available for this in 2.2?

**Comment by MishalValiyakath** [comment]
@javiercn As I mentioned I was trying it out .net core sdk 3.0 preview release and still not working, it will be released in later minor version of 3.0 preview release?

**Comment by javiercn** [comment]
ASP.NET Core 3.0 preview3. It will be released soon.

**Comment by guardrex** [comment]
@javiercn Would you like me to add the moniker to the topic metadata to make it for >=3.0?

**Comment by javiercn** [comment]
Yes please

**Comment by MishalValiyakath** [comment]
Installed .net Core 3 preview 3, successfully used the command to generate both react and angular apps with Individual option. But, the react template with auth has basic syntax errors in ApiAuthorizationConstants and reference issue in ApiAuthorizationRoutes (wrong relative path) and finally once you fix those the routes to authorization are broken and the corresponding components won't load. For the angular application, the client side seems to be working fine. But server-side requests like register or login on identity controller fails with below error. 
`MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'.
IdentityServer4.EntityFramework.Extensions.ModelBuilderExtensions+<>c__DisplayClass2_0.<ConfigurePersistedGrantContext>b__0(EntityTypeBuilder<PersistedGrant> grant)`

**Comment by javiercn** [comment]
The server side exception is a known issue. Here is how to work around it.

https://github.com/dotnet/core/blob/master/release-notes/3.0/preview/3.0.0-preview-known-issues.md

**Comment by Svetomechc** [comment]
Ported this over to .NET Core 2.2 / Angular 8
https://gitlab.com/Svetomechc/angularidentityserver
