### ISSUE TITLE
dotnet.exe x64/x86 order in PATH

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#11285]
Cross-ref: https://github.com/aspnet/AspNetCore/issues/3624

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f16c68-708b-003e-8c63-1df60c6344d0
* Version Independent ID: 25fa0508-4450-9051-cdd7-0d3260c60b4f
* Content: [Troubleshoot ASP.NET Core on IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti Head-check my understanding of the scenario:

If the dev installs the x64 SDK immediately prior to the hosting bundle (without the x86 SDK ever being installed), the hosting bundle establishes an order of `\dotnet` folders between `Program Files` and `Program Files (x86)` on the PATH such that x86 is first, thus *dotnet.exe* is (unexpectedly) the x86 version.

x86 SDK ... hosting bundle - OK (x86 will be used)
x64 SDK ... hosting bundle - :cry: (x86 will be used)
x64 SDK ... x86 SDK ... hosting bundle - OK (x86 will be used)
x86 SDK ... x64 SDK ... hosting bundle - OK (x64 will be used)

**Comment by guardrex** [comment]
@shirhatti :point_up: Am I working from a valid understanding?

**Comment by shirhatti** [comment]
Well there are more issues that what you listed.

For example, if you install a 64-bit 2.1.x SDK and a 32-bit 2.2.x SDK then whichever one wins on your PATH will be the only runtime available.

In short, the guidance is
- Always install the same bitness SDKs and runtimes.
- If you install the hosting bundle and SDKs/runtimes you may need to modify your PATH manually
