### ISSUE TITLE
Paging & sorting & filtering to razor page scaffolding automatic

### ISSUE THREAD

**Issue by mammadkoma** [aspnet/Docs#11296]
Can we scaffold an entity for making razor pages with paging & sorting & filtering features automatically without writing code for these features both back end and front end codes like third party's controls (grid) in asp.net webform or asp.net mvc?

**Comment by Rick-Anderson** [comment]
Sorry, No.

**Comment by mammadkoma** [comment]
Is there any package for that in razor page or in blazor?

**Comment by Rick-Anderson** [comment]
no

**Comment by mammadkoma** [comment]
So asp.net core is very weak.
