### ISSUE TITLE
Downloading 5mb sample solution requires downlaod of 750mb complete examples?!

### ISSUE THREAD

**Issue by niico100** [aspnet/Docs#11297]
[Enter feedback here]
I'm not sure if this is the right place to comment but it's ridiculous that downloading a sample application from MS documentation, eg here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2

Requires the user to download a complete 750mb download of every sample project available. This is insane and often not practical depending on the connection. 

Users should only have to download what they need. If this isn't the right venue for this where is? This is the only feedback option at the bottom of the Docs page.

thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @niico100 ... It's a known issue. They're working on a solution.

Cross-ref: https://github.com/aspnet/Docs/issues/8379
