### ISSUE TITLE
javascript libraries, anyone?

### ISSUE THREAD

**Issue by beefydog** [aspnet/Docs#11298]
Where is the signalr.js javascript? Is there another package to get this? If so, where can I find it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
If you follow the instructions, you first install the npm package https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#install-the-signalr-client-package
And then use the signalr.js file from the package https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#use-the-signalr-javascript-client

**Comment by beefydog** [comment]
I found them in the "node_modules\@aspnet\signalr\dist\browser" folder of the solution.  The instructions don't indicate this and the npm installer won't move it for you, so hope this helps someone else looking for it under the wwwroot/lib/

**Comment by BrennanConroy** [comment]
I think you must have missed the section that says exactly that.
>npm installs the package contents in the `node_modules\@aspnet\signalr\dist\browser folder`. Create a new folder named signalr under the `wwwroot\lib` folder. Copy the signalr.js file to the `wwwroot\lib\signalr` folder.
