### ISSUE TITLE
Edit code

### ISSUE THREAD

**Issue by wstaelens** [aspnet/Docs#11294]
It would be useful to add documentation on how to write an Update/Edit action method when using viewmodels.

Now there is: "Recommended HttpPost Edit code: Read and update" and "Alternative HttpPost Edit code: Create and attach".
But the "Recommended HttpPost Edit code: Read and update" cannot work when using ViewModels.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [Tutorial: Implement CRUD Functionality - ASP.NET MVC with EF Core](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-2.2#get-the-code)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Se the [Razor Pages/EF](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.2#view-model) version.

**Comment by wstaelens** [comment]
@Rick-Anderson so you assume that people using MVC, look at EF Core with MVC will have to know that the information about viewmodels is on the razor pages section? 😞
