### ISSUE TITLE
ASP.NET MVC Conceptual Overview

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#113]
ASP.NET MVC -> Getting Started -> ASP.NET MVC Conceptual Overview
- What is ASP.NET MVC?
- What is the MVC Pattern?
- Using MVC for Web UI and Web APIs

**Comment by abhishek31kr** [comment]
What is ASP.NET MVC?
ans- Asp.Net Mvc is a Architectural pattern that uses design pattern.

**Comment by abhishek31kr** [comment]
Models: Business Logic(.cs) + Data Access Logic
Views: .cshtml page...
Controllers: Business Logic (.cs )

**Comment by JanePamela** [comment]
am interested in reviewing the content

**Comment by orney21d** [comment]
i'm interested in reviewing the draft content ...  you can send me info about this at orney21d@gmail.com 

Best regards.

**Comment by jadubreuil** [comment]
am interested in reviewing the draft content.  thanks..

**Comment by ardalis** [comment]
@Rick-Anderson for the last section on 'Using MVC for Web Apps and Web APIs` are we thinking this should be a 'hello world' walkthrough of setting up an MVC app? If not, what should be included in this section (we have walkthroughs elsewhere)?

**Comment by ardalis** [comment]
See PR https://github.com/aspnet/Docs/pull/1774

**Comment by Rick-Anderson** [comment]
I don't think we should just point to https://docs.asp.net/en/latest/tutorials/first-web-api.html for the Web API portion.   For MVC https://docs.asp.net/en/latest/tutorials/first-mvc-app/index.html is long. @danroth27  what do you recommend? I don't think we want to include a MVC sample in this article. cc / @spboyer

**Comment by ardalis** [comment]
Fixed by #1774
