### ISSUE TITLE
Update docs blazor version for .net core preview 3

### ISSUE THREAD

**Issue by raz-canva** [aspnet/Docs#11308]
The guide mentions to run this command:
```
dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04
```
However, with the release of preview 3 today, that fails to build.

Update the docs to use the newest version of blazor templates

`0.9.0-preview3-19154-02`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-gb/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by oliversturm** [comment]
Running `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.9.0-preview3-19154-02` allows me to create a working project using the CLI. The resulting project shows a number of warnings like this:

```
warning NU1603: Microsoft.AspNetCore.Blazor.Server 0.9.0-preview3-19121-06 depends on Microsoft.NETCore.Platforms (>= 3.0.0-preview.19109.6) but Microsoft.NETCore.Platforms 3.0.0-preview.19109.6 was not found. An approximate best match of Microsoft.NETCore.Platforms 3.0.0-preview3.19128.7 was resolved.
```

It seems to work correctly in some short tests.

Side note: the [ASP.NET Core Blazor Language Services](https://marketplace.visualstudio.com/items?itemName=aspnet.blazor) doesn't support preview 3 yet.

Second side note: using the working CLI project in VS doesn't work either. It fails with this error:

```
Error	NU1202	Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19121-06 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19121-06 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)	
```

**Comment by guardrex** [comment]
I think @danroth27 will patch the versions shortly.

**Comment by danroth27** [comment]
The Blazor VSIX should now be updated to Blazor 0.9.0.

I submitted one additional PR to update the version in the Blazor get started doc: https://github.com/aspnet/Docs/pull/11325

**Comment by guardrex** [comment]
Fixed by https://github.com/aspnet/Docs/pull/11325.

**Comment by ThinhVu** [comment]
Getting a warning when install preview-19154-02.

"warning NU1603: restore depends on Microsoft.AspNetCore.Blazor.Templates (>= 0.9.0-preview-19154-02) but Microsoft.AspNetCore.Blazor.Templates 0.9.0-preview-19154-02 was not found. An approximate best match of Microsoft.AspNetCore.Blazor.Templates 0.9.0-preview3-19121-06 was resolved."

**Comment by guardrex** [comment]
Please open a new issue using the topic's Content Feedback button.

**Comment by danroth27** [comment]
> Getting a warning when install preview-19154-02.

The correct version of the templates package for 0.9.0 is 0.9.0-preview3-19154-02.

**Comment by gekas** [comment]
@oliversturm You have installed major version of .NET Core SDK 2.2 while Blazor Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19121-06 requires >= 3.0. There are preview versions for 3.0 available: https://dotnet.microsoft.com/download/dotnet-core/3.0
