### ISSUE TITLE
Replace references to HttpPlatformHandler with AspNetCoreModule

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#1130]
Announcement: https://github.com/aspnet/IISIntegration/issues/105

Here are the required template changes for reference: https://github.com/aspnet/Templates/issues/450

Search:
https://github.com/aspnet/Docs/search?p=3&q=HttpPlatformHandler+&utf8=%E2%9C%93
- Lots of Web.Config samples
- Severs: https://github.com/aspnet/Docs/blob/29c3d17ddefb669ce2a1b3253fb6e30255bfa706/aspnet/fundamentals/servers.rst#L149
- Nano: https://github.com/aspnet/Docs/blob/0c3d55a0753f0c30e91ac698b4c52154bd39764b/aspnet/tutorials/nano-server.rst#L56
- https://github.com/aspnet/Docs/issues/577
- https://github.com/aspnet/Docs/issues/786

@danroth27

**Comment by shirhatti** [comment]
And this entire article as well https://github.com/aspnet/Docs/blob/master/aspnet/hosting/http-platformhandler.rst

**Comment by danroth27** [comment]
Opened #1348 to track the Servers doc updates

**Comment by rachelappel** [comment]
Nano doc modified for ASP.NET Core module (https://github.com/aspnet/Docs/blob/0c3d55a0753f0c30e91ac698b4c52154bd39764b/aspnet/tutorials/nano-server.rst#L56)
