### ISSUE TITLE
Need ef-rp update for core 3.0  

### ISSUE THREAD

**Issue by MugiwaraJAK** [aspnet/Docs#11302]
Changing the ASP.NET Core version to "3.0 ... " doesn't change the document.  There are a few items in this tutorial that do not work the same from 2.2 to 3.0 

Also, the completed project sample on github seems to be from 2017. Can we get a completed version of this as we are in the 3rd month of 2019. 
/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/cu3x ??? :)

In the past I have been able to walk through these documents with relative ease. I know this is still a preview version.  Thank you for all you have given us. I am very excited about this upcoming release. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MugiwaraJAK ...

> I know this is still a preview version

Given that 3.0 isn't close to release, we can't document it yet. The API is still changing. Once we reach the release candidate stage, things will be stable enough to update docs.

We've started a 3.0 migration doc, and devs should check that for the breaking changes (although note that Preview3 released *TODAY* :tada:, so it hasn't been updated for Preview3 yet).

https://docs.microsoft.com/aspnet/core/migration/22-to-30
