### ISSUE TITLE
TS errors and wrong tutorial information

### ISSUE THREAD

**Issue by GuitarHero1969** [aspnet/Docs#11319]
Scenario: following this link:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio#feedback

"Test the app"

How do you change the directory using cd in the PMC ?
I get the following errors when trying to run:

TS2688, TS2580, TS2688, TS2580, TS2688, TS2580
There is NO start without debugging option in VS 2017 in the Debug menu.

The tutorial says type npm run release in the console, yet it mentions the PMC - which is it ?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)

**Comment by GuitarHero1969** [comment]
I'm not sure why but it seems to be working ok now.
I typed "npm run release" in a command window, then clicked the green run button in VS2017
with "SignalRWebPack" selected (instead of IIS Express)   which of these is the correct one to select anyway ?
