### ISSUE TITLE
AccessTokenProvider in Android

### ISSUE THREAD

**Issue by BrianChesbrough** [aspnet/Docs#11320]
SignalR now has a first party Java client for android.

You gave examples of how to use AccessTokenProvider to pass the token in javascript and .Net. Is there something similar available with the Java Client? If not what is the proper way to do this on that client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by BrianChesbrough** [comment]
Nevermind found the solution here: https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2

Might want to add this additional info to this article or link to the other.

HubConnection hubConnection = HubConnectionBuilder.create("YOUR HUB URL HERE")
    .withAccessTokenProvider(Single.defer(() -> {
        // Your logic here.
        return Single.just("An Access Token");
    })).build();

**Comment by bradygaster** [comment]
Closing issue since submitter found resolution.
