### ISSUE TITLE
Provide a list of providers

### ISSUE THREAD

**Issue by fekberg** [aspnet/Docs#11328]
I'd suggest that the page includes a list of all the available storage options for keys (EF, Redis etc) it's currently confusing as to what is suggested, versus what is available when reading the configuration overview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63ab082-ad30-b00d-ecd1-ca88eee1659e
* Version Independent ID: 69818122-e47a-3fed-ea37-8009f66e2a5c
* Content: [Configure ASP.NET Core Data Protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/data-protection/configuration/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/configuration/overview.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They're in the implementation section. I'll cross-link them here.
