### ISSUE TITLE
EnsureCreated isn't called from DbInitializer but from Main

### ISSUE THREAD

**Issue by fmachadopiriz** [aspnet/Docs#11332]
In the step **Remove EnsureCreated and test the app** the tutorial ask to remove the call to EnsureCreated from DbInitializer, but the call to EnsureCreated was added in a previous tutorial to Main. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145343de-9267-9171-b6c9-718703b7544d
* Version Independent ID: 2c2f791f-d41c-f995-a941-2461151a7db4
* Content: [Razor Pages with EF Core in ASP.NET Core - Migrations - 4 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/migrations.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fmachadopiriz thanks. We'll address this in the next doc sweep.
