### ISSUE TITLE
Migration picks up column type change for price, fails with sqlite

### ISSUE THREAD

**Issue by brandhilton** [aspnet/Docs#11335]
Early in the tutorial, we change the column type for Price from decimal to decimal(18,2). When we run the migration in this portion of the tutorial, it picks up that change, so the migration includes the addition of the Rating column, but also the type change on the Price column. The problem is, Sqlite doesn't permit column data type changes, so the migration fails. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Tracked in #9991
