### ISSUE TITLE
See this  stackoverflow

### ISSUE THREAD

**Issue by wstaelens** [aspnet/Docs#11334]
I had to follow https://stackoverflow.com/questions/45282853/the-language-does-not-change-in-the-asp-net-core-web-application in order to get the example working. Give this documentation to a student and they will be stuck. all of them...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#implement-a-strategy-to-select-the-languageculture-for-each-request)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
@Rick-Anderson this is seems a localization configuration + javascript issue, we already have done this in [Localization.StarterWeb](https://github.com/aspnet/Entropy/blob/master/samples/Localization.StarterWeb/)
