### ISSUE TITLE
DI, Configuration, and Logging in a not-hosted-service console application

### ISSUE THREAD

**Issue by sadqiang** [aspnet/Docs#11340]
For learning purposes, is there any example of using all the cutting-edge features DI, Configuration and Logging in a not-hosted-service console application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> cutting-edge

If you mean for 3.0, not yet. Although some 3.0 issues are being worked right now, we won't work on the 3.0 doc updates in earnest until the release candidate is available.

> not-hosted-service console application

Concepts in those areas (DI, config, and logging) are just about identical between console apps and web apps. I think these topics should be fine as a baseline for console app development.

**Comment by sadqiang** [comment]
@guardrex : I meant an example of using DI, Configuration, Logging with IHost but **not** for a background processing console application.

**Comment by guardrex** [comment]
That's not available yet in the doc set. There are various engineering examples around to show how things will compose. For example ...

* https://github.com/aspnet/AspNetCore/tree/master/src/Hosting/samples/GenericWebHost
* https://github.com/aspnet/Extensions/tree/master/src/Hosting/samples/GenericHostSample
* https://github.com/aspnet/AspNetCore/tree/master/src/Mvc/test/WebSites/GenericHostWebSite

A good way to go right now is to have a 3.0-preview3 template generate a RP/MVC app, then work in DI, config, and logging along the lines of how the engineering samples handle them.

We'll be updating the topics and samples for the 3.0 Generic Web Host when the release candidate arrives. Generally, there's too much engineering churn for us to document the next release before that point. Sometimes an engineer (or community members) will author a blog post and/or there will be an Announcement on what's new. I haven't looked, so I'm not sure what's out there.

**Comment by sadqiang** [comment]
@guardrex : Thank you very much. It is really helpful. 👍
