### ISSUE TITLE
Reflecting CheckBox contents on the database 

### ISSUE THREAD

**Issue by PSCRIMS** [aspnet/Docs#11348]
I am following the Get Started with EF Core in ASP.NET MVC web app, my environment for the project (netcore and sdk) is 2.2.0 (VS is 15.9.7)

Everything worked as described until Update Related Data - ASp.Net Core MVC with EF Core (dated 2/4/2019)
After I added the checkboxes under the Edit Form (the Views/Instructors/Edit.cshtml reflect with no problems the tutorial) the set of checkboxes is named "selectedCourses". 

What is happening is when I click on a course to add a class, all the previous classes get cleared)

I placed a breakpoint  in " public async Task<IActionResult> Edit(int? id, string[] selectedCourses)" and noticed that "        UpdateInstructorCourses(selectedCourses, instructorToUpdate);" selectedCourses has no contents and all the existing or new courses get cleared by the logic.

I am new to NetCore and I am sure I probably forgot to add something(being a newbie I am not sure of the stack trace of a ASPNet web app, so I don't know where I should add a breakpoint to check what happens after the Save button is clicked.

I looked at the source of the Save button and I can tell (I was editing the first instructor)
view-source:https://localhost:44378/Instructors/Edit/1
I need to add a breakpoint in the click action. 

Please help

**Comment by PSCRIMS** [comment]
First off I apologize for (re) opening the issue here, I am not sure the other issue that I opened is in the right forum.
===
I am following the Get Started with EF Core in ASP.NET MVC web app, my environment for the project (netcore and sdk) is 2.2.0 (VS is 15.9.7)

Everything worked as described until "Update Related Data - ASp.Net Core MVC with EF Core" (dated 2/4/2019)
After I added the checkboxes under the Edit Form (the Views/Instructors/Edit.cshtml reflect with no problems the tutorial) the set of checkboxes is named "selectedCourses".

What is happening is when I click on a course to add a class, all the existing courses get wiped out.

I placed a breakpoint in " public async Task Edit(int? id, string[] selectedCourses)" and noticed that " UpdateInstructorCourses(selectedCourses, instructorToUpdate);" selectedCourses has no contents and all the existing or new courses get cleared by the logic.

I am new to NetCore and I am sure I probably forgot to add something(being a newbie I am not sure of the stack trace of a ASPNet web app, so I don't know where I should add a breakpoint to check what happens after the Save button is clicked, unlike under Windows Forms I can't add a click event, which is taken care by EF.

When edit instructor is called with a specific instructor a call to PopulateAssignedCourseData is executed:
===
private void PopulateAssignedCourseData(Instructor instructor)
        {
            var allCourses = _context.Courses;
            var instructorCourses = new HashSet<int>(instructor.CourseAssignments.Select(c => c.CourseID));
            var viewModel = new List<AssignedCourseData>();
            foreach (var course in allCourses)
            {
                viewModel.Add(new AssignedCourseData
                {
                    CourseID = course.CourseID,
                    Title = course.Title,
                    Assigned = instructorCourses.Contains(course.CourseID)
                });
            }
            ViewData["Courses"] = viewModel;
        }
===
That guarantees that the existing courses are reflected on the View

On the trip back from Edit the variables for the Instructor are called specifically for update
=======
public async Task<IActionResult> Edit(int? id, string[] selectedCourses)
        {
            if (id == null)
            {
                return NotFound();
            }

            var instructorToUpdate = await _context.Instructors
                .Include(i => i.OfficeAssignment)
                .Include(i => i.CourseAssignments)
                    .ThenInclude(i => i.Course)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (await TryUpdateModelAsync<Instructor>(
                instructorToUpdate,
                "",
                i => i.FirstMidName, i => i.LastName, i => i.HireDate, i => i.OfficeAssignment))

====
The instructor gets correctly updated, then a call is made to update the "selected courses" with 
the string []  selectedcourses having no value therefore wiping out the previous existing courses.

Being new to this environment I don't know if I should have to looped through  i.CourseAssignments to populate selectedcourses[] or this is something EF should have taken care of.

I may have overlooked something but at this point I am lost 

Please help

**Comment by PSCRIMS** [comment]
I apologize for the bold area of my comment.

**Comment by Rick-Anderson** [comment]
I'm not sure what you missed but the code works. We'll review this on the next doc sweep.
