### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Gluups** [aspnet/Docs#11341]
Hello,
Is it a normal approach to have to grope more than one hour for compatible versions of the dependencies, and then still have no in memory database, and discover tens of warnings in the errors window, signalling other compatibility problems ?
Does a ready-to-use package exist, with all the necessary in it ?
A Web-API project could do it, Angular with it would be fine.
Or, at least, a complete list of packages to install, in the correct order. I imagine this would be easier to maintain than a project model, although it would take a little more time to install.
I imagine Visual Studio 2017 Community and Windows 10 64 bits 1809 is a decent environment ?

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)

Also, what is the problem you found with the doc? If it's in-memory DB is not persistent, that's known. In memory is used for the tutorial, not a production app.
