### ISSUE TITLE
Error. Registration form keeps popping for a registered user after token has expired

### ISSUE THREAD

**Issue by jgathairu** [aspnet/Docs#11349]
I have implemented the WSFederation successfully on Asp.net core. When the idle time of 20 mins lapses, the application re-authenticates by calling the ADFS page. However, the application takes the registered user back to the registration page. I will then either recycle the application pool or restart the website to make it work again. How do I resolve the issue ? The console is showing error 401

![Capture](https://user-images.githubusercontent.com/29246216/54067229-be5a9300-424e-11e9-8906-71ca1368ee2c.JPG)

**Comment by guardrex** [comment]
Hello @jgathairu ... We only handle documentation issues here. Open an issue for engineering in the [aspnet/AspNetCore issues](https://github.com/aspnet/AspNetCore/issues).

If you ultimately learn that there is a problem with the documentation, open a new issue using the **Content feedback** button at the bottom of the ADFS topic at: https://docs.microsoft.com/aspnet/core/security/authentication/ws-federation
