### ISSUE TITLE
InvalidOperationException on SelectList

### ISSUE THREAD

**Issue by jwalleser** [aspnet/Docs#11345]
The example code, as written with the exception of a namespace difference yields the following error:

InvalidOperationException: Could not create an instance of type 'Microsoft.AspNetCore.Mvc.Rendering.SelectList'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Alternatively, set the 'Genres' property to a non-null value in the 'vsWebApp.Pages.Movies.IndexModel' constructor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The code works. You might want to test the download.

**Comment by jwalleser** [comment]
I mistakenly left a [BindProperty] annotation on the Genres property of SelectList type. Problem solved.
