### ISSUE TITLE
Authorizing Area Pages

### ISSUE THREAD

**Issue by mkoma808** [aspnet/Docs#11351]
It should be noted, that at the current time, when you scaffold Identity into an ASP.Net Core app, many of the scaffolded pages will have [AllowAnonymous] at the top of the *.cs file, meaning that if you want to use something like: options.Conventions.AuthorizeAreaPage("Identity", "/Register");

You must comment out or delete the [AllowAnonymous] at the top of the Register.cshtml.cs file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a49eaa-a2ee-baac-e614-5e2f7c74072a
* Version Independent ID: 09513dc8-546a-ea10-9f0b-cde361127647
* Content: [Razor Pages authorization conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/authorization/razor-pages-authorization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/razor-pages-authorization.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@mkoma808 I agree. That's a good add to this section with a cross-link over to the [scaffold Identity topic](https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity).

Do you know if the same behavior exists if you **_don't scaffold_** but just add the `AuthorizeAreaPage` to an app that uses the library? I would expect this result either way. If you don't know, I'll run a test just to make sure the behavior is the same.

**Comment by guardrex** [comment]
Thanks for the note @mkoma808, but we're going to wait and see if this is a widespread problem before making changes.
