### ISSUE TITLE
code improvement

### ISSUE THREAD

**Issue by CeciAc** [aspnet/Docs#11357]
@rlmendes commented on [Sun Mar 10 2019](https://github.com/aspnet/Docs.pt-br/issues/108)

I suggest this improvement for this part of code:

Genre: &lt;select asp-for="MovieGenre" asp-items="Model.Genres"&gt;
            &lt;option value=""&gt;All&lt;/option&gt;
        &lt;/select&gt;
Just for better appearance for users.

Thanks

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Adicionar a pesquisa às Páginas Razor do ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/docs.pt-br/blob/live/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the contributor is making a suggestion on the example code

best

**Comment by Rick-Anderson** [comment]
@rlmendes  good suggestion. We'll do this in the next doc sweep.
