### ISSUE TITLE
Label tag helper doesn't converts camel-cased properties to a sentence

### ISSUE THREAD

**Issue by rkaralkin** [aspnet/Docs#11355]
This page has statement that label tag helper converts camel-cased properties to a sentence composed of the property name with a space where each new upper-case letter occurs. But it doesn't works for me on ASP.NET Core 2.2, the label content is exactly the same as a model property name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by auspex** [comment]
Very true. And disappointing. I've actually been looking for something that would do exactly what the Label TagHelper is apparently supposed to do automatically!

**Comment by scottaddie** [comment]
I've confirmed that this statement in the doc is inaccurate. Submitted a PR to address it.
