### ISSUE TITLE
JSRuntime.Current.InvokeAsync is still being used in the sample

### ISSUE THREAD

**Issue by dodyg** [aspnet/Docs#11369]
JsInteropClasses/ExampleJsInterop.cs:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f4eeb7-4bf9-2631-3814-52bd4608445b
* Version Independent ID: fcde7f10-d897-1276-a3b7-4c5d19d14e4c
* Content: [Razor Components JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/razor-components/javascript-interop?view=aspnetcore-3.0)
* Content Source: [aspnetcore/razor-components/javascript-interop.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/javascript-interop.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The updates are coming on https://github.com/aspnet/Docs/pull/11314.
