### ISSUE TITLE
How to get decrypted cyphertext with Data Protection API's?

### ISSUE THREAD

**Issue by jcoddaire** [aspnet/Docs#11373]
In the example, the following code generates a new XML file with the encrypted text in it:

>  _protector.Protect(input);

The decrypted text is retrieved by using the resulting `protectedPayload` object. However, what if that object is not available?

I want to create a method that, given the `ApplicationID`, `purpose`, and `directory`, will fetch the correct XML file and decrypt the `protectedPayload`. However, it is not clear how to decrypt a secret without already knowing what payload to use.

Here's an example from .NET Framework 4.7.2:

```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Security;
using System.IO;

/// <summary>
/// Decrypts the encrypted text from the stored file.
/// </summary>
/// <param name="textFileLocation">The text file location.</param>
/// <param name="purpose">The purpose / password.</param>
/// <returns></returns>
public static string DecryptFromFile(string textFileLocation, string purpose)
{
	string encryptedTextFromFile = File.ReadAllText(textFileLocation);
	byte[] encryptedData = Encoding.Default.GetBytes(encryptedTextFromFile);

	byte[] decryptedValue = null;
	decryptedValue = MachineKey.Unprotect(encryptedData, purpose);

	return Encoding.Default.GetString(decryptedValue);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532d66a6-fa01-54d3-1dfa-20d1889668bb
* Version Independent ID: 6489c522-2148-e39a-92cc-6f631c065422
* Content: [Get started with the Data Protection APIs in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/data-protection/using-data-protection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/using-data-protection.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by blowdart** [comment]
Samples are meant to be simple. You are asking a usage question, and not a documentation question. I'm afraid those belong on stackoverflow.

Having said that, to save you the trip, it doesn't matter. Look at the code. ProtectedPayload is a *string*, It's not special. It doesn't matter. It contains nothing special. Just create a suitable protector and be done with it.
