### ISSUE TITLE
How do you call alert or console.log

### ISSUE THREAD

**Issue by dodyg** [aspnet/Docs#11379]
I tried but it never returns. Any of this call will work once then it just stops working.

protected override async Task OnInitAsync()
    {
        await JS.InvokeAsync&lt;object&gt;("alert", "Hello World");
        await JS.InvokeAsync&lt;object&gt;("console.log", "hello world console");
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f4eeb7-4bf9-2631-3814-52bd4608445b
* Version Independent ID: fcde7f10-d897-1276-a3b7-4c5d19d14e4c
* Content: [Razor Components JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/razor-components/javascript-interop?view=aspnetcore-3.0#capture-references-to-elements)
* Content Source: [aspnetcore/razor-components/javascript-interop.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/javascript-interop.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by dodyg** [comment]
So anything synchronous at OnInitAsync would kill the JS Interop. This should be documented.

```
@page "/"
@inject IJSRuntime JS 

<button onclick="@ConfirmAsync">Confirm</button>

@functions  
{
    protected override async Task OnInitAsync()
    {
        await JS.InvokeAsync<object>("console.log", "hello world console");
    }

    async Task ConfirmAsync(){
        var result = await JS.InvokeAsync<bool>("confirm", "Do you confirm?");
        await JS.InvokeAsync<short>("alert", $"Result {result}");
    }
}
```
When I remove the console.log from OnInitAsync, everything will work just fine.

**Comment by guardrex** [comment]
Hello @dodyg ... This topic will be updated on https://github.com/aspnet/Docs/pull/11314. We'll either look at this for that PR or the next PR (Preview3) right after it.

**Comment by danroth27** [comment]
This is a bug tracked by https://github.com/aspnet/AspNetCore/issues/8274
