### ISSUE TITLE
Initialize method  does not work as it is

### ISSUE THREAD

**Issue by PeterLuZC** [aspnet/Docs#11385]
Initialize method  does not work as it is, as ID column in Course table is an identity column, it does not accept values when record is added. correct code block is attached here:
 var courses = new Course[]
            {
            new Course{Title="Chemistry",Credits=3},
            new Course{Title="Microeconomics",Credits=3},
            new Course{Title="Macroeconomics",Credits=3},
            new Course{Title="Calculus",Credits=4},
            new Course{Title="Trigonometry",Credits=4},
            new Course{Title="Composition",Credits=3},
            new Course{Title="Literature",Credits=4}
            };

...

 var enrollments = new Enrollment[]
            {
            new Enrollment{StudentId=students[0].ID,CourseId=courses[0].ID,Grade=Grade.A},
            new Enrollment{StudentId=students[0].ID,CourseId=courses[1].ID,Grade=Grade.C},
            new Enrollment{StudentId=students[0].ID,CourseId=courses[3].ID,Grade=Grade.B},
            new Enrollment{StudentId=students[1].ID,CourseId=courses[2].ID,Grade=Grade.B},
            new Enrollment{StudentId=students[1].ID,CourseId=courses[3].ID,Grade=Grade.F},
            new Enrollment{StudentId=students[1].ID,CourseId=courses[4].ID,Grade=Grade.F},
            new Enrollment{StudentId=students[2].ID,CourseId=courses[1].ID},
            new Enrollment{StudentId=students[3].ID,CourseId=courses[4].ID},
            new Enrollment{StudentId=students[3].ID,CourseId=courses[3].ID,Grade=Grade.F},
            new Enrollment{StudentId=students[4].ID,CourseId=courses[3].ID,Grade=Grade.C},
            new Enrollment{StudentId=students[5].ID,CourseId=courses[4].ID},
            new Enrollment{StudentId=students[6].ID,CourseId=courses[6].ID,Grade=Grade.A},
            };

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@PeterLuZC  did you miss this?

```
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
```

```
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int Credits { get; set; }

        public ICollection<Enrollment> Enrollments { get; set; }
    }
}
```
