### ISSUE TITLE
Must use forward slash "/" for paths on macOS

### ISSUE THREAD

**Issue by mrlife** [aspnet/Docs#11383]
In the section "Scaffold the student model", in the ".NET Core CLI" tab, the last command uses `Pages\Students`. On macOS, this creates the files in a "PagesStudents" folder in the root of the project. Instead, `Pages/Students` must be used. May be the same on Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.2&tabs=netcore-cli#scaffold-the-student-model)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mrlife thanks for bringing this to our attention. Fixed in #11387

**Comment by mrlife** [comment]
Thank you! The same exists on other pages that have .NET Core CLI commands like this, e.g. https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.0&tabs=netcore-cli#create-a-course-page-that-displays-department-name
