### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by SH1N081** [aspnet/Docs#11380]
This introduction is not up to date with the VS19 preview.
Images are from a different version, and the template file structure suggested in this tutorial is not the same (separate projects for .App and .Server, for example).
Also, the suggested changes in this tutorial do not work in my Razor Component project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8227c67e-83bb-dee3-e31c-73097df59614
* Version Independent ID: e7b564a3-b078-c390-15ba-b5044bd4edec
* Content: [Get started with Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-components/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @SH1N081 

Correct ... the topic was updated for Preview2, but we haven't reached it yet for Preview3. We're tracking the work on https://github.com/aspnet/Docs/issues/10717.
