### ISSUE TITLE
Why is Bower recommended for installing FontAwesome? 

### ISSUE THREAD

**Issue by ciaran036** [aspnet/Docs#11392]
I am confused by this. After installing FontAwesome following this advice I installed SweetAlert2 via Bower only to find it didn't work properly because the developer dropped support for Bower because it is supposedly a dead project. The Bower project itself seems to recommend moving to Yarn or WebPack but in other places NPM seems to by the recommended way to go. At this stage, I had expected a consistent message from Microsoft in managing client-side packages for ASP.NET Core. This is all too confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01743cdd-23a9-2846-1e6e-7fbccab03d7e
* Version Independent ID: c60c655f-92dd-5f4a-799f-d55b0e6700e8
* Content: [Less, Sass, and Font Awesome in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/less-sass-fa?view=aspnetcore-2.2#font-awesome)
* Content Source: [aspnetcore/client-side/less-sass-fa.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/less-sass-fa.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
This doc is really outdated, and the decision has been made to retire it. npm is a great solution I've personally had luck with. Microsoft does, however, offer a tool called LibMan that could solve your problem too. Read more about it: https://docs.microsoft.com/aspnet/core/client-side/libman/
