### ISSUE TITLE
Documentation refers to dnu cli instead to the dotnet cli

### ISSUE THREAD

**Issue by maveonair** [aspnet/Docs#1141]
I have installed dotnet and asp.net core today and went through the tutorial "Building your first MVC 6 application", which is awesome by the way. Nevertheless, in the data Migration part the documentation is refers to the dnu cli instead of the dotnet cli: https://docs.asp.net/en/latest/tutorials/first-mvc-app/adding-model.html#use-data-migrations-to-create-the-database. 

Is there any reason why the documentation is still refering to the dnu cli instead of the dotnet cli? I can offer to help you to update the documentation.

**Comment by BrennanConroy** [comment]
The documentation is about the current release, which is RC1 i.e. dnu. When we ship RC2 all the documentation will be updated to dotnet cli

**Comment by maveonair** [comment]
Thanks!
