### ISSUE TITLE
Razor templates in @functions block

### ISSUE THREAD

**Issue by oliversturm** [aspnet/Docs#11410]
As described, I can create Razor templates like this:

```
@{
  RenderFragment foo = @<p>this is text</p>;
  RenderFragment<string> titleFragment = (title) => @<h4>@title</h4>;
}
```

However this syntax doesn't seem to be supported at all in an `@functions` block -- both of the above assignments render a series of compiler errors.

I expected to be able to do this:

```
  [Parameter]
  RenderFragment<string> TitleTemplate { get; set; } =
    (title) => @<h4 class="card-title">@title</h4>;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11a64802-62dc-40e0-034f-fcee55f31d4e
* Version Independent ID: 038d7f90-aa71-a35c-cee9-c8543403cfd7
* Content: [Create and use Razor Components](https://docs.microsoft.com/en-us/aspnet/core/razor-components/components?view=aspnetcore-3.0#razor-templates)
* Content Source: [aspnetcore/razor-components/components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/components.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by danroth27** [comment]
Thank you for this feedback! We are planning on support a variant of Razor templates in functions blocks in the next preview update to .NET Core 3.0. You can see details about it here: https://github.com/aspnet/AspNetCore/issues/5577
