### ISSUE TITLE
Changing SUT environment

### ISSUE THREAD

**Issue by piccaso** [aspnet/Docs#11417]
I did not find an obvious way to change the `ASPNETCORE_ENVIRONMENT`.  
After digging around in the [source ](https://github.com/aspnet/Mvc/blob/a6199bbfbab05583f987bae322fb04566841aaea/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs#L278-L293) a bit I realized that `CreateWebHostBuilder` was `virtual` and came up with:
```cs
public class WebAppFactory<TEntryPoint> : WebApplicationFactory<TEntryPoint> where TEntryPoint : class {
        private readonly string _environment;
        public WebAppFactory(string environment) {
            _environment = environment;
        }
        protected override IWebHostBuilder CreateWebHostBuilder() {
            return base.CreateWebHostBuilder().UseEnvironment(_environment); 
        }
    }
```
Is there a better way?  
And, is it documented somewhere?  
(apologies if it is, i really tried to find it...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @piccaso ... See :point_right: https://github.com/aspnet/Docs/issues/8917

I attempted to cover it on https://github.com/aspnet/Docs/pull/9060, but engineering didn't like the direction it was going, so it isn't covered at this time.
