### ISSUE TITLE
"Additional Resources" Missing from "In this article" Section

### ISSUE THREAD

**Issue by mrlife** [aspnet/Docs#11416]
Looks like it needs to be changed from &lt;h3&gt; to &lt;h2&gt;

I believe the same issue is present on this page of the tutorial:

https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.2&tabs=visual-studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145343de-9267-9171-b6c9-718703b7544d
* Version Independent ID: 2c2f791f-d41c-f995-a941-2461151a7db4
* Content: [Razor Pages with EF Core in ASP.NET Core - Migrations - 4 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/migrations.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We'll fix this in the next doc sweep.

**Comment by Rick-Anderson** [comment]
@mrlife I think it's better as an H3

**Comment by mrlife** [comment]
Since most of the pages in the tutorial included "Additional Resources" in the navigation on the right side, I assumed the 2 pages missing that were the error. I actually like being able to jump to that section using the navigation.

**Comment by mrlife** [comment]
I'm assuming things with H2 get auto included in the navigation.

**Comment by Rick-Anderson** [comment]
Correct on H2
