### ISSUE TITLE
Why do we need a null check to get the Error from IExceptionHandlerPathFeature

### ISSUE THREAD

**Issue by ilya-git** [aspnet/Docs#11411]
Here is an example from the documentation:

```
if (exceptionHandlerPathFeature?.Error is FileNotFoundException)
{
    await context.Response.WriteAsync("File error thrown!");
}
```

I can't quite figure out why do we need a null check here. I have read the code and it does not seem possible to have null, nor does it seem logical that it can be either. Maybe we can skip it and have a guarantee that it will never be null instead?

I have opened a similar question on SO: https://stackoverflow.com/questions/55166679/when-can-an-error-be-null-with-exceptionhandlermiddleware-in-asp-net-core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
If a secondary exception is thrown by the middleware itself prior to the `IExceptionHandlerPathFeature` being set, it would :boom:.

This code example was reviewed by engineering when the PR updates were made, and they would've likely flagged it if they didn't like it.

They'll look at it again on the next doc sweep, which might be for 3.0 RC.

**Comment by ilya-git** [comment]
Then it would not reach our code I suppose? Because it's being called right after it's being set, though it of course can change in the future

**Comment by guardrex** [comment]
It logs and ultimately rethrows ...

https://github.com/aspnet/AspNetCore/blob/28157e62597bf0e043bc7e937e44c5ec81946b83/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L101
