### ISSUE TITLE
Check .NET Core - Use Previews Setting

### ISSUE THREAD

**Issue by bytemon** [aspnet/Docs#11422]
Installed everything as outlined above, but project wouldn't run - received error regarding .NET Core version.  In Visual Studio tools, had to set: "Projects & Solutions / .NET Core / Use previews of the .Net Core SDK" to TRUE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdcc295-2262-311c-99d4-7ece67c5f6ed
* Version Independent ID: 20152398-0971-0302-21f8-b17308f02183
* Content: [Get started with Blazor](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/blazor/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/blazor/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We used to have this topic+sample set up for 0.X.0 (non-preview). Therefore, it was fine to have that setting unchecked. Now that it calls for Preview 3, I agree that this requires an update.

**Comment by guardrex** [comment]
@bytemon It shouldn't be necessary ...

> For preview releases of Visual Studio, the tools will continue to consume the latest preview version of the SDK that is installed on your machine by default. You cannot change the option to turn this off for preview releases of Visual Studio because they usually require a corresponding preview SDK to work correctly.

... from https://devblogs.microsoft.com/dotnet/net-core-tooling-update-for-visual-studio-2017-version-15-9/

The preview VS should use the preview SDK without that setting.
