### ISSUE TITLE
Adding Search, intro to MVC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1143]
From DISQUS
David Hoffman 
Fantastic tutorial! Some minor corrections (I think) needed on this page:
1. "following code... retrieves all the genres from the database" is missing 3rd line ("select") in the snippet
2. "using System;" required for use of "String"
3. "using System.Collections.Generic;" required for use of "GenreList = new List<string>();"

**Comment by danroth27** [comment]
Should be fixed now
