### ISSUE TITLE
Filtering example

### ISSUE THREAD

**Issue by JonVinson** [aspnet/Docs#11438]
Filtering example didn't seem to work until I change name of input box from SearchString to searchString (to match parameter name).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JonVinson  were you using MacOS or Linix?

**Comment by JonVinson** [comment]
I was using Windows, actually.

**Comment by Rick-Anderson** [comment]
Try the download code.  It's not case sensitive. You must have had another error.
