### ISSUE TITLE
Need target for appsettings link

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Docs#1147]
In rc2 we are adding an FWLink into the templates (see PR https://github.com/aspnet/Templates/pull/493) letting users know that app settings go into `appsettings.json` instead of `web.config`. I looked around but didn't find a good landing page for this. I found https://docs.asp.net/en/latest/security/data-protection/configuration/index.html but that's not specific enough. We may need a new doc here.

**Comment by rustd** [comment]
https://docs.asp.net/en/latest/fundamentals/configuration.html would be a good landing page for RC2

**Comment by sayedihashimi** [comment]
FYI fwlink has been updated.
