### ISSUE TITLE
Wrong code snippet

### ISSUE THREAD

**Issue by mysteryx93** [aspnet/Docs#11490]
This snippet in the code is wrong; that's not the same as in the source code nor as to what's displayed below.

    Assert.Equal(
        expectedMessages.OrderBy(x =&gt; x.Id), 
        actualMessages.OrderBy(x =&gt; x.Id), 
        new Utilities.MessageComparer());

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor Pages unit tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/razor-pages-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @mysteryx93  ... It's pulling the code directly from the sample ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/test/razor-pages-tests/samples/2.x/tests/RazorPagesTestSample.Tests/UnitTests/IndexPageTests.cs#L41-L47

The next bit of content refers to a different test.

Leave this issue open. The content might organize better with some strategic subheadings. I'm OOF this week, so I'll take a closer look when I'm back next week. Thanks for commenting.

**Comment by mysteryx93** [comment]
You're pulling the code snippet directly, but just a little bit further up on the page, the same code section is different. There should be no Utilities.MessageComparer.

**Comment by guardrex** [comment]
Ah, yes ... I see what u mean. We modded it here ...

https://github.com/aspnet/Docs/pull/4832#discussion_r153292937

... but the sample snapshot wasn't updated with the same change that we made for the sample app. 

I'll take care of it ... Thanks for reporting it.
