### ISSUE TITLE
Typo in View Components

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#1149]
> View Components are intended anywhere you have reusable rendering logic that is too complex for a partial view, such as:

**Change to:**

> View Components should be used anywhere you have reusable rendering logic that is too complex for a partial view, such as:

**Comment by danroth27** [comment]
@Rick-Anderson Please fix as part of the RC2 updates.

**Comment by Rick-Anderson** [comment]
@ardalis @davidMuir the old MS style guide prohibits should - and this case points it out. You don't need to use VC's anywhere you have reusable rendering logic that is too complex for a partial view,
