### ISSUE TITLE
.NET Core application doesn't launch in Ubuntu 18.04

### ISSUE THREAD

**Issue by shunjid** [aspnet/Docs#11492]
Pressing Ctrl + F5 after creating a new webapp/mvc actually doesn't run the app in Ubuntu 18.04. Because of the two ports in **Properties** > **launchSettings.json** kestrel doesn't listen to Port 5001. 

![Screenshot from 2019-03-17 20-03-37](https://user-images.githubusercontent.com/29749035/54492353-fc5f5300-48ef-11e9-8750-54af5f38ce92.png)

All you need to do is to update the lauchSettings.json file as follows: 

**Initial Code**

```
"MvcBooks": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
```

**Updated Code**

```
"MvcBooks": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
```

Now pressing Ctrl + F5 works to run the application. My request to the official @aspnet is to update this in docs tutorial.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
