### ISSUE TITLE
Using MVC 6 with Entity Framework 7

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#115]
ASP.NET MVC -> Tutorials -> Using MVC 6 with Entity Framework 7
- http://www.asp.net/mvc/overview/getting-started/getting-started-with-ef-using-mvc/creating-an-entity-framework-data-model-for-an-asp-net-mvc-application

**Comment by tdykstra** [comment]
Given how much work this big tutorial series is to update, I thought we had planned on waiting until the EF and MVC bits are relatively stable (RTM) to update it.  Is the work for this issue going to create a small subset of the tutorial series?  A smaller intro tutorial might be a better fit for the prerelease time frame.

**Comment by MikeWasson** [comment]
I'm writing a smaller tutorial - code is at https://github.com/aspnet/Docs/pull/247

There's plenty of other stuff to cover for MVC6 + EF7, I'm really just writing a basic "getting started".

**Comment by tdykstra** [comment]
Perfect, just wanted to make sure since the intro to the issue had a link to the big series.
