### ISSUE TITLE
performance/caching/distributed  "Working with a Distributed Cache"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1150]
Less than 5K PV.

[Working with a distributed cache in ASP.NET Core
](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed)

- [ ] Needs total rewrite - it doesn't contain any code that shows how to use it with Razor Pages or MVC.
- [ ] "A distributed cache is shared by multiple app servers" Need to mention the local in-memory cache is not distributed but inherits from `IDistributedCache`
- [ ] #1124  (Add tag helper)
- [ ] DISQUS - check  redis cache only works if you target .net 4.6
- [ ] disambiguate  you should avoid using the in-memory implementation (MemoryCache) in multi-server environments.  Make it clear Reddis is multi-server friendly.
- [ ]  in-memory is fine with sticky bits
- [ ]  UE scrub
- [ ]  remove pick the approach you're comfortable with

Maybe something like this:

Redis Cache is a caching solution which gives you high throughput and low latency as compared to SQL Cache.

**Comment by Rick-Anderson** [comment]
@ardalis can you work on some of these check boxes? #3683 address TH so you can skip that.

**Comment by Rick-Anderson** [comment]
@guardrex if any of these apply can you open a new issue attached to the doc?

**Comment by guardrex** [comment]
@Rick-Anderson :+1: Will do. I'll look on Friday and see if anything is still relevant.
