### ISSUE TITLE
Uninstall instructions for OS X

### ISSUE THREAD

**Issue by ryanadkins** [aspnet/Docs#1151]
How do you uninstall the DNVM from OS X? I followed the install instructions per the documentation using the cURL script.

**Comment by danroth27** [comment]
@glennc Can you help out with this one?

**Comment by danroth27** [comment]
I don't think we will add anything to do the docs for this one since dnvm is going away.

**Comment by ryanadkins** [comment]
I am not asking to add anything to the docs. I just want to know how to uninstall the dnvm from my computer. In another issue someone replied with the windows install path. what is the OS X install path? But I am sure I am not the only one who may need this question answered due to the dnvm Bing deprecated in RC2.

**Comment by n777ty** [comment]
There's a subfolder called "dnvm" inside the .dnx folder off your user home directory... That's where dnvm.sh lives (default location).  You can remove that subfolder to "uninstall" it :)

**Comment by ryanadkins** [comment]
Thank you, that worked for me.

**Comment by jasontooke** [comment]
You may also want to remove the loader from .bash_profile. It looks like this;

`[ -s "/Users/username/.dnx/dnvm/dnvm.sh" ] && . "/Users/username/.dnx/dnvm/dnvm.sh" # Load dmvm`
