### ISSUE TITLE
The linked example for WebApiSample.Api._22 does not work

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [aspnet/Docs#11536]
Please if you are providing examples as a guide, one would expect that the examples have been  vetted and actually work.

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'WebApiSample.DataAccess.Repositories.ProductsRepository' while attempting to activate 'WebApiSample.Api._22.Controllers.ProductsController'.
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
```

Not good.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
This problem has been resolved in https://github.com/aspnet/Docs/pull/11425. The fix will go live within the next 24 hours.
