### ISSUE TITLE
The configuration system is set up to read keys from environment variables.

### ISSUE THREAD

**Issue by chaim1221** [aspnet/Docs#11538]
You don't say! Except `Authentication:Facebook:AppId=1234567890` isn't valid Bash! So if you're not trying to host with Azure, what do you do here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by chaim1221** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.2#environment-variables-configuration-provider

```
When working with hierarchical keys in environment variables, a colon separator (:) may not work on all platforms. A double underscore (__) is supported by all platforms and is replaced by a colon.
```

A link to this in the OIDC docs would be helpful.

**Comment by Rick-Anderson** [comment]
@chaim1221 can you help me word that? How about
When working with hierarchical keys in environment variables **(for example with Bash)**, a colon separator (:) may not work on all platforms. A double underscore (__) is supported by all platforms and is replaced by a colon.

**Comment by chaim1221** [comment]
Yep that text is fine, or a link to the text, either way. Just some way to call out in this document that the "environment variables" can be "colon-ized" (if you will) that way.
