### ISSUE TITLE
Modify a statement

### ISSUE THREAD

**Issue by shadinamrouti** [aspnet/Docs#11543]
Regarding this warning: https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot?view=aspnetcore-2.2#the-net-core-sdk-is-installed-in-multiple-locations

Not only the x86 SDK should be removed, but also the x86 runtime. 

Thanks for your continuous support for .net core. I see your generous efforts everywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 967496ea-59b6-1f17-4f39-1e4c232126c6
* Version Independent ID: 09bb2010-fe5c-1061-23ec-a0dcc92bdd3f
* Content: [Troubleshoot ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/test/troubleshoot?view=aspnetcore-2.2#the-net-core-sdk-is-installed-in-multiple-locations)
* Content Source: [aspnetcore/test/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shadinamrouti  thanks for pointing that out. Can you PR this?
