### ISSUE TITLE
Model Validation updates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1154]
- [x] Update for RC2
- [x] RegularExpression Validates that the data matches **the specified**  regular expression
- [x]  GetClientValidationRules() I don't think you meant to show that
- [x]  as shown in the following paragraph.  Looks like something is missing
- [x] implementing IValidatableObject - don't you want to say implementing ``Validate`` on the ``IValidatableObject`` interface?
- [x] The first step is to control what data- attributes are added by implementing the IClientModelValidator interface as shown here:   Wrong lines?
- [x] https://github.com/aspnet/Announcements/issues/179

**Comment by danroth27** [comment]
@rachelappel Can you take a look at these?

**Comment by danroth27** [comment]
Need to also update for RC2

**Comment by dougbu** [comment]
350b3fc
