### ISSUE TITLE
IIS launch profile with in process hosting model

### ISSUE THREAD

**Issue by nguyenhthai** [aspnet/Docs#11550]
Hi.

I have a question related to the in process hosting model within ASP.Net Core 2.2. My setup is below:
VS: 2017 15.9.9, 2019 RC2
.Net Core: SDK v2.2.105, Runtime & Hosting Bundle Installed as well
IIS: 10.0.17763.1
Windows 10 (v. 1809)

In version 2.2, the hosting model is defaulted to be OutOfProcess. In order to use the InProcess model, I add &lt;AspNetCoreHostingModel&gt;InProcess&lt;/AspNetCoreHostingModel&gt; in the web project .csproj file and then change the web.config to use AspNetCoreModuleV2 as well as add the attribute hostingModel="inprocess" in the aspNetCore part. However, every time I build or run the project, Visual Studio automatically transforms the web.config to the old model that use the old AspNetCoreModule and OutOfProcess hosting. Is there a way to allow in-process model to be configured with through Visual Studio?

In addition, I noticed a strange thing when I created a new ASP.Net Core project to see what is the different between my working project and the new project. In the "Web Server Settings" below the "App Url", in the new project, there is the "Hosting Model" dropdown that has 3 values: Default, In-process, and Out of process. My working project does not have that dropdown. I dig into the .csproj files and noticed that because of the reference of Microsoft.AspNetCore.App. My web project does not reference Microsoft.AspNetCore.App directly in the .csproj file. However, it does reference a .Net Core library that reference Microsoft.AspNetCore.App. If I add that reference directly to the main web project .csproj file, then open the Configuration page will show the dropdown. However, that also broke the reference from other class libraries and the build itself. Without that reference, I cannot choose the hosting model even if I put everything correctly in the web.config and the .csproj file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* GitHub Login: @shirhatti
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nguyenhthai

For your first question, there's a MSBuild propeety that you can set in the project file to stop the automatic web.config transformation. See ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/index#webconfig-file

> a .Net Core library that reference Microsoft.AspNetCore.App.

That's unusual and not recommended for class libs. Can you use the metapackage in the app and have the class lib reference [Microsoft.AspNetCore](https://www.nuget.org/packages/Microsoft.AspNetCore/) and additional packages that it requires? ... Microsoft.AspNetCore provides extension namespaces for things like config and logging.

**Comment by nguyenhthai** [comment]
@guardrex This project is an open source project that I forked and currently working to add additional functionality so that why I have not gone to the extreme to fix all the iffy stuff like that. The compiler warns me about that as well but to fix it, I would have to do additional works that the original source might have some fixes ready by the time I have figured out. So that why I am having trouble with just leaving everything intact and try to add or change things in the web project only.

Back to the config transformation, if I do that way, still IIS debugging support with F5 in VS or would I have to manually attach the debugger to the process? When choosing IIS, the web.config is currently modified to use VSIISExeLauncher. So if I keep the custom web.config, will F5 still work?

Thanks.

**Comment by guardrex** [comment]
Yes ... It should still work. It should use your custom web.config and not transform it. If something doesn't work and we leave this issue open, Sourabh will see this. He's OOF travelling right now, so we may need to wait a while to hear back. If things work as expected for you, then go ahead and close this so he'll know that ur ok.

**Comment by nguyenhthai** [comment]
When starting by using F5, the web.config file is modified by VSIISExeLauncher every time despite I have set the property to not transform it.

Also related to the hidden option that I mentioned early, is it a feature or bug that the option is determined by the reference of Microsoft.AspNetCore.App in the web project? If it is a feature, then why the setting does not show up if the reference is from the class library and that class library is reference within the main web project?

**Comment by guardrex** [comment]
Given that both Sourabh and I are OOF at the moment, lets close this issue and have you open a new issue at:  https://github.com/aspnet/AspNetCore/issues

Give them your scenario and include the VS version and your SDK version. Include a copy of your custom web.config file.

I'd like to repro your scenario, but Im out-of-state until Saturday, and I don't even have my laptop with me.

Best bet is to ask on the aspnet/AsoNetCore issues. Please CC: @guardrex on the new issue, so I can follow the discussion. If we need a doc update, then I'll re-open this issue later to track the work.

**Comment by guardrex** [comment]
Oh ... One more thing. Search those issues (both open and closed) to see if the same or a similar issue exists.
