### ISSUE TITLE
Where is VB.NET version, please?

### ISSUE THREAD

**Issue by SteveHigh** [aspnet/Docs#11581]
I am following the Visual Studio ASP.NET Identity tutorial here about creating Register and Log-in pages:

[https://docs.microsoft.com/en-us/aspnet/identity/overview/getting-started/adding-aspnet-identity-to-an-empty-or-existing-web-forms-project](url)

Problem is that the author's code (and general orientation) is in C#. Is there a version of this code , or these pages, in vb.net, please?

**Comment by guardrex** [comment]
Hello @SteveHigh ... Last I heard ([for example](https://devblogs.microsoft.com/vbteam/visual-basic-in-net-core-3-0/)) VB.NET will be supported for .NET Core 3 later this year. At this time, all of our samples are C#.
