### ISSUE TITLE
Inconsistent RPC title case

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Docs#11623]
https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.0

![image](https://user-images.githubusercontent.com/303201/54769541-9cea9700-4bbe-11e9-8d28-2fd39b5479e1.png)

OCD triggered.

Which is correct?

**Comment by JamesNK** [comment]
Speaking of OCD, the order of "Web apps" and "Web API apps" is different under Tutorials. Fix that up at the same time.

**Comment by scottaddie** [comment]
Thank you for reporting this, @JamesNK! My changes will go live within the next 24 hours.
