### ISSUE TITLE
Blazor docs not consistent with Starter App

### ISSUE THREAD

**Issue by mbowles201** [aspnet/Docs#11624]
The content above hops between Razor and Blazor...with page name refs to the matching Blazor item.   Unfortunately, the content differs between the two.  Example: the Fetchdata in Blazor does not use DI for the WeatherService and the WeatherService itself is different.   Moving on to the ToDo list, you can't add a razor page to the Blazor app, it throws a "There are no scaffolders supported for this item" error message.   Creating a cshtml seems to do the trick.  This looks promising and will allow real devs to get into this "front-end" race.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9063eb3-fb65-45ed-2e3d-a7cf1354d523
* Version Independent ID: 84390f51-2206-8269-221b-5a20726dab76
* Content: [Build your first Razor Components app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/build-your-first-razor-components-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-razor-components-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/build-your-first-razor-components-app.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by wally666** [comment]
...and 

server-side example code is out-of-date: there is no extension method "UseServerSideBlazor" in .Net Core 3 prev. 3

**Comment by guardrex** [comment]
Thanks for commenting. Your timing is perfect: We just had a meeting a couple of hours ago, which included a discussion of this topic. There will be a round of updates early next week (perhaps even this weekend), and I'll fix the problems that you identified.

**Comment by guardrex** [comment]
@wally666 I think you're referring to the hosting models topic (not the tutorial), correct? I haven't reached the hosting models topic yet except for a small patch on the template name. That's where we left off when I had to fly out for the conference. The hosting models and the host+deploy topics are still generally of the Preview2 era but will be updated shortly. https://github.com/aspnet/Docs/issues/10717
