### ISSUE TITLE
Custom Storage Providers for ASP.NET Core Identity

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1162]
Port http://www.asp.net/identity/overview/extensibility/overview-of-custom-storage-providers-for-aspnet-identity to ASP.NET Core Identity

See https://github.com/aspnet/Identity/issues/1113
>Yeah we shouldn't call it the UOW pattern since its not exactly that, best to just be explicit and say something to the effect of: "Stores should only persist changes in the CreateAsync/UpdateAsync/DeleteAsync methods of base Store interface, any other store method should only manipulate the entity without persisting the changes."

Overall structure same as previous article; Hao and Steve will work together to update it.

Main changes: removed TKey from all interfaces. The key is now always a string to identity - it's up to the provider to convert that string into its type.

**Comment by DeluxZ** [comment]
Any update on this?

**Comment by danroth27** [comment]
@blowdart Not yet - it's still on our backlog

**Comment by jorgeyanesdiez** [comment]
+1 for this, I'm trying to get rid of the EF dependency and this would come handy.

**Comment by CodingSamurai** [comment]
This is essential functionality if people are going to be moving to .NET Core for production apps.

**Comment by stephan19** [comment]
+1, I'm also trying to get rid of the EF dependency

**Comment by AbdoDabbas** [comment]
+1, when do you expect to get it done ?

**Comment by alex521** [comment]
+1

**Comment by danroth27** [comment]
@HaoK @blowdart There's quite a bit of customer interest in getting this content out sooner. Is this something you guys could help out with?

**Comment by HaoK** [comment]
I can take a pass over the old article and see what needs updating

**Comment by jrgunawan** [comment]
+1

**Comment by dntim** [comment]
Folks, any news?

**Comment by danroth27** [comment]
This is actively being worked on and should be published in the next few weeks.

**Comment by Greatsamps** [comment]
are we getting close yet?

**Comment by rushfive** [comment]
+1 any updates on the progress?

**Comment by krunalrspl** [comment]
Any update on this?

**Comment by RobVargaCH** [comment]
Still no update guys?

**Comment by danroth27** [comment]
I believe @ardalis will have a PR out for this shortly

**Comment by ardalis** [comment]
This week!

**Comment by RobVargaCH** [comment]
Hi Guys, thanks very much for getting this out; all looks good clear.  One small recommendation I have is that in Steve's code the ApplicationUser inherits from ClaimsIdentity: this may confuse some users and maybe a quick one-liner about implementing IIdentity as an alternative may be helpful.

Thanks again.

Cheers,
Rob

**Comment by ardalis** [comment]
@RobVargaCH Thanks, I updated the sample in the PR to use IIdentity instead of ClaimsIdentity, along with a couple of other minor tweaks.
