### ISSUE TITLE
.NET Core application doesn't launch in Ubuntu 18.04

### ISSUE THREAD

**Issue by shunjid** [aspnet/Docs#11638]
Pressing Ctrl + F5 after creating a new webapp/mvc actually doesn't run the app in Ubuntu 18.04. Because of the two ports in Properties &gt; launchSettings.json kestrel doesn't listen to Port 5001.

All you need to do is to update the lauchSettings.json file as follows:

Initial Code

"MvcBooks": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5001;http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
Updated Code

"MvcBooks": {
      "commandName": "Project",
      "launchBrowser": true,
      "applicationUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
Now pressing Ctrl + F5 works to run the application. My request to the official @aspnet is to update this in docs tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie @guardrex  sounds like a template bug.

**Comment by guardrex** [comment]
If `RequiresHttps` is true (via VS check box or in the default template case or with an authentication option passed when creating the app), it will provide the secure endpoint. For example (they all have this) ...

https://github.com/aspnet/AspNetCore/blob/master/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/Properties/launchSettings.json

I'm still out-of-town at a conference. I'll look later this weekend and see what we can do to clarify it in the Nginx topics. The topics and examples there do go with an insecure app experience, so we should have the readers produce an app for the experience without the secure endooint. Thanks @shunjid

**Comment by shunjid** [comment]
@guardrex : Was there any change regarding this issue in documentation/sdk?

**Comment by shunjid** [comment]
@guardrex : 
Is this the [part updated](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#publish-and-copy-over-the-app) in document to remove `https://localhost:5001` right after the issue was closed?
![Screenshot from 2019-04-01 23-06-26](https://user-images.githubusercontent.com/29749035/55345878-d5e60e00-54d2-11e9-9235-156475710712.png)

**Comment by guardrex** [comment]
@shunjid Yes, but I'm not sure what you mean by "right after the issue was closed." When the PR merges, the issue automatically closes.

**Comment by shunjid** [comment]
@guardrex Got it. Thanks anyway  +1:
