### ISSUE TITLE
Courses are not properly spaced.

### ISSUE THREAD

**Issue by LouBH** [aspnet/Docs#11645]
After adding Courses to the Instructor page, the courses are not spaced out as they are in your example.  There is a substantial margin on the left, which I can get rid of by changing "&lt;div class="col-md-offset-2 col-md-10"&gt;" t o "&lt;div class="col-md-12"&gt;",   but the columns are also too narrow, resulting in course names moving down to the next line.  This is the second time I have worked through the tutorial and I have encountered the same problem both times.  Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Hi @LouBH 
The article doesn't focus on CSS so you're on your own. The pic's are old from previous CSS I'm guessing.
