### ISSUE TITLE
What to do when step 3 gives you a dialog with the last 3 options disabled

### ISSUE THREAD

**Issue by ibruynin** [aspnet/Docs#11641]
In Visual Studio:
1.    Create a new ASP.NET Core Web Application.
2.    Select Web Application from the list of templates.
3.    Select the Change Authentication button and select Windows Authentication.

I tried both VS2017 and VS2019
In 2019 The option "Add connected service" also does not show the "Azure AD authentication" option...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I can't reproduce this. Can you supply screen shots and tell me what you expect?

**Comment by ibruynin** [comment]
This is the dialog I see 
<img width="537" alt="azureAD" src="https://user-images.githubusercontent.com/15861800/54902685-58bb0780-4eda-11e9-8fbf-ce91a1186ab1.png">

and I expect to see the option for Azure AD as documented here: https://docs.microsoft.com/en-us/azure/active-directory/develop/vs-active-directory-add-connected-service

**Comment by ibruynin** [comment]
and this is what I see when creating a new dotnet core web application: 
![image](https://user-images.githubusercontent.com/15861800/54902929-ea2a7980-4eda-11e9-81af-249758402344.png)

**Comment by Rick-Anderson** [comment]
ASP.NET Core 3 is a pre-release. You'll need to use 2.2 for this.
