### ISSUE TITLE
Correction proposal to linux-nginx article

### ISSUE THREAD

**Issue by sergei66666** [aspnet/Docs#11655]
Hello!
I am talking about this article -
https://docs.microsoft.com/ru-ru/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2#configure-nginx

Article say use it: "proxy_set_header   Host $host;". 
And it work if we use IP or domain name. But if we use IP:Port - redirect doesn't work correctly (it redirect to IP without port).

If replace it with "proxy_set_header   Host $http_host;" all works fine.

p.s. "If the issue is with an ASP.NET Core document, open the issue with the **Content feedback** button at the bottom of that document page." - I tried to do it and got error.

Thank you.

**Comment by guardrex** [comment]
> open the issue with the Content feedback button at the bottom of that document page." - I tried to do it and got error.

Thanks for reporting that. I'll take a look in the morning and see if the form is broken here, too.

> If replace it with "proxy_set_header Host $http_host;" all works fine.

It creates a security vulnerability. See the references on the PR: https://github.com/aspnet/Docs/issues/5707 ... especially this one :point_right: https://github.com/yandex/gixy/blob/master/docs/en/plugins/hostspoofing.md
