### ISSUE TITLE
PUT throws server-side InvalidOperationException if executed before GET or POST

### ISSUE THREAD

**Issue by aannenko** [aspnet/Docs#11661]
Steps:
1. Build and run TodoApi
2. Perform PUT request as described in the Add a PutTodoItem method section
Result:
The line `_context.Entry(item).State = EntityState.Modified;` throws the following exception:
`InvalidOperationException: The instance of entity type "TodoItem" cannot be tracked because another instance with the same key value for {"Id"} is already being tracked...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Create a web API with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio-code#add-a-deletetodoitem-method)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the article
his sample uses an in-memory database that must be initialed each time the app is started. There must be an item in the database before you make a PUT call. Call GET to insure there is an item in the database before making a PUT call.
