### ISSUE TITLE
Starter App

### ISSUE THREAD

**Issue by johnmackerras** [aspnet/Docs#11662]
1. Move the Section "Create the starter app" to the top of the page, maybe directly after the section "The starter and completed app". Those users who prefer to build an example from scratch, such as myself, would prefer that this option is not left until the last of the exercises is complete.
2. The link to the Starter App refers to Starter2, which is a .Net Core 2.0 application, it would be better if it refers to Starter2.1, which is a .Net Core 2.2 application. 
3. Github does not offer a "Clone or download" option at the level where the sample project is. I had to download the entire repository from "https://github.com/aspnet/Docs", and then navigate back through the directories in the downloaded zip file (750Mb) to where the sample is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
1. Most users prefer to not create the starter. For those who don't, it should be no problem to click the link to the starter. The starter app doesn't have much to do with the tutorial.
3. Per the download link, that's how gitHub works.
