### ISSUE TITLE
Scaffolding Requirements missing

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/Docs#1166]
Hi,

I think in the article **Your First ASP.NET 5 Web App Using Visual Studio** https://github.com/aspnet/Docs/blob/master/aspnet/tutorials/your-first-aspnet-application.rst#add-scaffolding, could be mentioned that **project.json** needs to have `Microsoft.Extensions.CodeGenerators.Mvc` to see the option **New Scaffoled Item...** not sure if the additional packages are also not required according this https://github.com/aspnet/Tooling/issues/290#issuecomment-164725559.

Also here in this article **Adding a model**  https://github.com/aspnet/Docs/blob/master/aspnet/tutorials/first-mvc-app/adding-model.rst#scaffolding-a-controller

Thanks :)

**Comment by Tratcher** [comment]
The first tutorial was removed: https://github.com/aspnet/Docs/commit/9b6065a4d2ed9965af1f417e95e7cec2ba5b3c1c

**Comment by Tratcher** [comment]
Add dependencies:
```
			    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			      "version": "1.0.0-preview2-21343",
			      "type": "build"
			    },
			    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc":  {
			      "version": "1.0.0-preview2-21343",
			      "type": "build"
			    }
			    "Microsoft.EntityFrameworkCore.Design": {
			      "version": "1.0.0-preview2-21343",
			      "type": "build"
			    },
```
Add tools entries:
```
			    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
			      "version": "1.0.0-preview2-21343",
			      "imports": [
			        "portable-net45+win8+dnxcore50",
			        "portable-net45+win8"
			      ]
			    }
			    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-21343",
```

Add UseDatabaseErrorPage
`"Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc3-21343",`

Add `/Views/Shared/_ValidationScriptsPartial.cshtml`

**Comment by Rick-Anderson** [comment]
We explain this now in https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model
