### ISSUE TITLE
aspnet-codegenerator razorpage step does not work on Fedora 28 - fails with "Scaffolding failed. No such file or directory"

### ISSUE THREAD

**Issue by vphadnav** [aspnet/Docs#11666]
Following this tutorial step by step on Fedora 28, this step does not work: (in fact, -h does not work either)

[~/Projects/RazorPagesMovie] $ dotnet tool install --global dotnet-aspnet-codegenerator
Tool 'dotnet-aspnet-codegenerator' is already installed.
[~/Projects/RazorPagesMovie] $ codegen_trace=1 dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries
[Trace]: Command Line: razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries
Scaffolding failed.
No such file or directory
[Trace]:    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Extensions.Internal.Command.Execute() in /_/src/Shared/Cli.Utils/Command.cs:line 74
   at Microsoft.Extensions.ProjectModel.MsBuildProjectContextBuilder.Build() in /_/src/Ext.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs:line 42
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.BuildAndDispatchDependencyCommand(String[] args, String projectPath, String buildBasePath, String configuration, Boolean noBuild, ILogger logger) in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 176
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.&lt;&gt;c__DisplayClass19_0.&lt;Execute&gt;b__0() in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 109
RunTime 00:00:00.07
[~/Projects/RazorPagesMovie] $ codegen_trace=1 dotnet aspnet-codegenerator razorpage -h
[Trace]: Command Line: razorpage -h
Scaffolding failed.
No such file or directory

Usage: aspnet-codegenerator [arguments] [options]

Arguments:
  generator  Name of the generator. Check available generators below.

Options:
  -p|--project             Path to .csproj file in the project.
  -n|--nuget-package-dir   
  -c|--configuration       Configuration for the project (Possible values: Debug/ Release)
  -tfm|--target-framework  Target Framework to use. (Short folder name of the tfm. eg. net46)
  -b|--build-base-path     
  --no-build               

[Trace]:    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Extensions.Internal.Command.Execute() in /_/src/Shared/Cli.Utils/Command.cs:line 74
   at Microsoft.Extensions.ProjectModel.MsBuildProjectContextBuilder.Build() in /_/src/Ext.ProjectModel.MsBuild.Sources/MsBuildProjectContextBuilder.cs:line 42
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.&lt;&gt;c__DisplayClass19_0.&lt;Execute&gt;b__0() in /_/src/dotnet-aspnet-codegenerator/Program.cs:line 126
RunTime 00:00:00.08

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by vphadnav** [comment]
looked at https://github.com/aspnet/Scaffolding/issues/838, and verified that csproj file has the Web.CodeGeneration.Design package reference. does this work for vscode as well?

    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />

**Comment by vphadnav** [comment]
looking at https://github.com/aspnet/scaffolding/issues/444, adding the following line to the csproj manually, and then invoking dotnet restore, dotnet build and then followed by the dotnet aspnet-codegenerator makes everything work.

<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />

Output:
[~/Projects/RazorPagesMovie] $ dotnet restore
  Restoring packages for /home/vphadnav/Projects/RazorPagesMovie/RazorPagesMovie.csproj...
  Restore completed in 25.22 ms for /home/vphadnav/Projects/RazorPagesMovie/RazorPagesMovie.csproj.
  Installing Microsoft.NETCore.DotNetAppHost 2.0.0.
  Installing System.Runtime.CompilerServices.Unsafe 4.4.0.
  Installing Microsoft.NETCore.DotNetHostResolver 2.0.0.
  Installing Microsoft.Extensions.Primitives 2.0.0.
  Installing Microsoft.NETCore.DotNetHostPolicy 2.0.0.
  Installing NETStandard.Library 2.0.0.
  Installing Microsoft.Build 15.3.409.
  Installing Microsoft.Build.Tasks.Core 15.3.409.
  Installing Microsoft.Build.Utilities.Core 15.3.409.
  Installing Microsoft.Build.Framework 15.3.409.
  Installing Microsoft.Extensions.FileProviders.Abstractions 2.0.0.
  Installing Microsoft.Extensions.FileSystemGlobbing 2.0.0.
  Installing Microsoft.NETCore.App 2.0.0.
  Installing Microsoft.Build.Runtime 15.3.409.
  Installing Microsoft.Extensions.FileProviders.Physical 2.0.0.
  Installing NuGet.Frameworks 4.0.0.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.0.
  Installing Microsoft.VisualStudio.Web.CodeGeneration.Contracts 2.0.0.
  Restore completed in 6.23 sec for /home/vphadnav/Projects/RazorPagesMovie/RazorPagesMovie.csproj.
[~/Projects/RazorPagesMovie] $ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 66.66 ms for /home/vphadnav/Projects/RazorPagesMovie/RazorPagesMovie.csproj.
  Restore completed in 60.24 ms for /home/vphadnav/Projects/RazorPagesMovie/RazorPagesMovie.csproj.
  RazorPagesMovie -> /home/vphadnav/Projects/RazorPagesMovie/bin/Debug/netcoreapp2.2/RazorPagesMovie.dll
  RazorPagesMovie -> /home/vphadnav/Projects/RazorPagesMovie/bin/Debug/netcoreapp2.2/RazorPagesMovie.Views.dll

Build succeeded.                                                                                                   
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.42
[~/Projects/RazorPagesMovie] $ dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries                
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.2.3-servicing-35854 initialized 'RazorPagesMovieContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
Added Razor Page : /Pages/Movies/Create.cshtml
Added PageModel : /Pages/Movies/Create.cshtml.cs
Added Razor Page : /Pages/Movies/Edit.cshtml
Added PageModel : /Pages/Movies/Edit.cshtml.cs
Added Razor Page : /Pages/Movies/Details.cshtml
Added PageModel : /Pages/Movies/Details.cshtml.cs
Added Razor Page : /Pages/Movies/Delete.cshtml
Added PageModel : /Pages/Movies/Delete.cshtml.cs
Added Razor Page : /Pages/Movies/Index.cshtml
Added PageModel : /Pages/Movies/Index.cshtml.cs
RunTime 00:00:11.76
[~/Projects/RazorPagesMovie] $ dotnet aspnet-codegenerator -h


Usage: aspnet-codegenerator [arguments] [options]

Arguments:
  generator  Name of the generator. Check available generators below.

Options:
  -p|--project             Path to .csproj file in the project.
  -n|--nuget-package-dir   
  -c|--configuration       Configuration for the project (Possible values: Debug/ Release)
  -tfm|--target-framework  Target Framework to use. (Short folder name of the tfm. eg. net46)
  -b|--build-base-path     
  --no-build               

Available generators:
  area      : Generates an MVC Area.
  view      : Generates a view.
  razorpage : Generates RazorPage(s).
  identity  : Generates an MVC Area with controllers and 
  controller: Generates a controller.


RunTime 00:00:02.25
[~/Projects/RazorPagesMovie] $

**Comment by Rick-Anderson** [comment]
looks like you sovled it.
