### ISSUE TITLE
eRPC - Impressive recent research from CMU and Intel

### ISSUE THREAD

**Issue by rboissy** [aspnet/Docs#11665]
Datacenter RPCs can be General and Fast
http://www.cs.cmu.edu/~akalia/doc/nsdi19/erpc_nsdi19.pdf
https://github.com/erpc-io/eRPC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Rick-Anderson** [comment]
@JamesNK  should **Alternative Framework Scenarios** list these?

**Comment by JamesNK** [comment]
I don't think so. It looks like an implementation of RPC that is focused on performance, but doesn't yet have a community of users.

I'm not sure what the action is from this issue. It could probably be closed.
