### ISSUE TITLE
MyBaseController clarity

### ISSUE THREAD

**Issue by benmccallum** [aspnet/Docs#11673]
In the example of creating a base api controller, should it inherit from ControllerBase? It's currently not clear. Should it be updated to?

```
    [ApiController]
    public abstract class ApiControllerBase : ControllerBase { /* ... */ }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/index?view=aspnetcore-3.0#annotate-class-with-apicontrollerattribute)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by benmccallum** [comment]
(sorry in my example I used "ApiController" base as that's what I'm going for in my app, but in the doc it corresponds with "MyBaseController" which could probably also be renamed to "MyBaseApiController" for clarity anyway.

Makes me wonder, why wouldn't this be included in the framework by default?

**Comment by Rick-Anderson** [comment]
Before ASP.NET Core, MVC and API had different controllers. That's no longer the case.

**Comment by benmccallum** [comment]
Hi @Rick-Anderson , yep I'm aware of that. Still doesn't make the docs any clearer on how to do your own base API controller. 

I just want to know, do I do this (my thinking);
```
[ApiController]
public abstract class ApiControllerBase : ControllerBase 
{ }
```

Or this, as in doc:
```
[ApiController]
public class MyBaseController 
{ }
```

**Comment by Rick-Anderson** [comment]
@benmccallum I think you're right - fixing in #11706

**Comment by benmccallum** [comment]
Awesome, thx guys!
