### ISSUE TITLE
Incorrect ExecStart Location for Ubuntu

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/Docs#11676]
In the guide above it says the starting location should be `/usr/local/bin/dotnet`:
`ExecStart=/usr/local/bin/dotnet /var/www/helloapp/helloapp.dll`

But it seems the correct location for Ubuntu should actually be:
`/usr/bin/dotnet` (without the "/local")

I realise the guide is designed for Cent Os but should it be adapted to include Ubuntu as everything is the same aside from that path and Ubuntu is the more popular release for devs I think (but could be wrong)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **spboyer**

**Comment by guardrex** [comment]
Covered by this topic's sister topic :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx
