### ISSUE TITLE
Missing startup step

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/Docs#11670]
This intro appears to be missing a step in order to run it.  As this is an intro users reading it may not be familiar with the steps needed to start up this project.

![image](https://user-images.githubusercontent.com/6592543/54906427-85bfe800-4ee3-11e9-9fd0-28b35b8341f7.png)

Doesn't mention that you need to apply the migrations.

![image](https://user-images.githubusercontent.com/6592543/54906515-b273ff80-4ee3-11e9-886e-0a8bb50f9f11.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Although it's intro to Identity it's a more advanced doc where we don't include these steps.

**Comment by LindaLawton** [comment]
I am confused that you merged the pull request yet rejected the issue?
