### ISSUE TITLE
Two years..

### ISSUE THREAD

**Issue by spacecat** [aspnet/Docs#11680]
..is a long time in tech.

you sure there hasnt been any updates in the localization /globalization field during this period? :)

I just started a new multi-regional and multilingual, doing some research, thats why im asking.

also, resource files are kinda obsolete 2019? People still use it in midern apps?

another thing i noticed is SEO is not mentioned. at least some basics and common best practices should exist.

will take a look at the sample app provided, hopefully it provides some good things i can usd as a starting point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
