### ISSUE TITLE
Incorrect information about minimum required references

### ISSUE THREAD

**Issue by Leon99** [aspnet/Docs#11698]
After adding Microsoft.AspNetCore.Razor.Design and Microsoft.AspNetCore.Mvc.Razor.Extensions, build generates RazorAssemblyInfo.cs file that contains reference to Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute, which is located in Microsoft.AspNetCore.Mvc.Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e930c44-70f6-8820-1451-d1f781ded7a0
* Version Independent ID: 6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e
* Content: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2)
* Content Source: [aspnetcore/razor-pages/sdk.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/sdk.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Leon99** [comment]
Plus, there are quite a few dependencies that are missing and prevent cshtml from compiling even after adding Microsoft.AspNetCore.Mvc.Core. I suggest to either include a list of all the required dependencies or specify that Microsoft.AspNetCore.Mvc is required. Former is better but the latter is easier.

**Comment by Rick-Anderson** [comment]
Per the article:

Typically, a package reference to `Microsoft.AspNetCore.Mvc` is required to receive additional dependencies

**Comment by Leon99** [comment]
Per the article:
> At a minimum, your project should add package references to:
> - Microsoft.AspNetCore.Razor.Design
> - Microsoft.AspNetCore.Mvc.Razor.Extensions

This is incorrect.

**Comment by Rick-Anderson** [comment]
What's the min?

**Comment by Rick-Anderson** [comment]
@vijayrkn please review

**Comment by vijayrkn** [comment]
For minimum required razor dependencies, I would ask @rynowak /  @NTaylorMullen

**Comment by NTaylorMullen** [comment]
> Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute, which is located in Microsoft.AspNetCore.Mvc.Core.

By default when you have Razor.Design and Mvc.Razor.Extensions in a project the generated C# files assume MVC runtime bits are available. Meaning, it is still able to parse and generate C# but it is unable to compile those bits unless MVC is available. So from a parsing perspective `Razor.Design` and `Mvc.Razor.Extensions` are the bare minimum to generate .cs files. 

That being said it's not common to generate those files and then not expect them to be able to compile into an assembly immediately. To do that the minimum is to include `Microsoft.AspNetCore.Mvc.Razor` in your 2.X project (along side of the design and extensions package).
