### ISSUE TITLE
Possible issue : Keyword 'page' is used internally by MVC's routing system

### ISSUE THREAD

**Issue by CeciAc** [aspnet/Docs#11693]
@hybernatus commented on [Mon Mar 25 2019](https://github.com/aspnet/Docs.fr-fr/issues/205)

Thank you for your great explanations on this topic.

Just a remark. I have had to change 'page' keyword into 'pageNumber' in order to make the code work. Otherwise the route is not determined properly.

You can rename 'page' to 'pageNumber' in the body of the method and in the ASP tag

(The keyword 'page' seems to be not only a reserved word in MVC'routing system but also in the context of a Razor view)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [Tutoriel : Ajouter le tri, le filtrage et la pagination - ASP.NET MVC avec EF Core](https://docs.microsoft.com/fr-fr/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/Docs.fr-fr/blob/live/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

---

@hybernatus commented on [Mon Mar 25 2019](https://github.com/aspnet/Docs.fr-fr/issues/205#issuecomment-476223376)

The term 'pageIndex' suits better to reality, these are not page numbers but indexes of group of pages. This is the term already used in PaginatedList CreateAsync definition

---

@CeciAc commented on [Mon Mar 25 2019](https://github.com/aspnet/Docs.fr-fr/issues/205#issuecomment-476223883)

Hello, @hybernatus 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
please check this issue, is referring to the code
best

**Comment by Rick-Anderson** [comment]
I agree, this should be changed.

**Comment by Rick-Anderson** [comment]
@tdykstra change this in the next doc sweep.
