### ISSUE TITLE
Documentation for integration with modular bundlers such as Webpack

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/Docs#1169]
Since a lot of development is switching more towards Webpack modular bundlers as opposed to the slightly older way of bundling files yourself (Gulp / Grunt for example). It'd be nice to have some thorough documentation on dealing with things like Webpack's *webpack-dev-server* (light Node server) while spinning up Kestrel for example at the same time.

I've been running into a lot of issue with these, I'm sure there will be plenty of others who will feel this pain.  I could look into adding some Documentation for this as well.

**Comment by danroth27** [comment]
@madskristensen Thoughts on this?

**Comment by danroth27** [comment]
@MarkPieszak Since we don't have any immediate plans around Webpack modular bundler we plan to add any doc content in this area. It would probably make a nice blog post though if you want to write something up for the community.

**Comment by MarkPieszak** [comment]
Definitely, I'll get something going over the next week if I can. Thanks Dan
