### ISSUE TITLE
Routing to Controller Actions

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#117]
ASP.NET MVC -> Controllers -> Routing to Controller Actions
- Relationship to middleware (#61)
- Startup code and relationship to MVC route handler
- Attribute routing
    - `[Route]`, `[Http*]`
    - Routes on controller vs actions
    - Inheritance
    - Token replacement in route templates (`[controller]`, `[action]`, `[area]`)
    - Custom route attributes using `IRouteTemplateProvider`
    - Pointer to using Application Model to customize attribute routes
- Conventional routing
    - Mapping of action/area/controller maps to a controller action (action selection)
- Action constraints
    - HTTP method constraints
    - Custom constraints

**Comment by pranavkm** [comment]
cc @ssargent

**Comment by atrauzzi** [comment]
Is there going to be any way to create route configuration files that point directly to controllers?  There still seems to be quite a heavy focus on attribute routing.  [This ticket](https://github.com/aspnet/Mvc/issues/2486) explains some of the things I'd hope to see made available.

**Comment by danroth27** [comment]
Some existing content we might leverage:  http://www.asp.net/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2

**Comment by atrauzzi** [comment]
@danroth27 - I meant, *not* using attribute routing.  _"route configuration files that point directly to controllers"_.

Attribute and in-code routes are a somewhat dated practice compared to what other mature frameworks out there are doing.

**Comment by davidfowl** [comment]
This is about documenting the existing features. Use that ticket to further ask for things but this issue isn't  about adding new features.

**Comment by njasm** [comment]
o_O

**Comment by danroth27** [comment]
Initial content in PR: https://github.com/aspnet/Docs/pull/602

**Comment by ar27111994** [comment]
Any way to map routes in a separate file / class? @danroth27 @atrauzzi

**Comment by NinoFloris** [comment]
I have searched everywhere for some content on how to handle custom inline route constraints in MVC 6. Are they still in?

**Comment by ardalis** [comment]
When you say custom, you mean beyond the ones that are available here?\
https://github.com/aspnet/Routing/blob/1.0.0-rc1/src/Microsoft.AspNet.Routing/RouteOptions.cs

**Comment by PeterBocan** [comment]
Any updates on this issue? I would appreciate some documentation on this topic :) ... would older documentation work until then?

**Comment by danroth27** [comment]
It's in progress

**Comment by glangdonvt** [comment]
I'd be happy to be a test-subject for your documentation when you feel it's ready.  I'm about 200 hours into working with MVC/webapi after about 25 years of software engineering experience.  george@rcxrules.com.

**Comment by Rick-Anderson** [comment]
fixed by https://docs.asp.net/en/latest/mvc/controllers/routing.html
