### ISSUE TITLE
Service Lifetimes definitions are ambiguous

### ISSUE THREAD

**Issue by ScottHutchinson** [aspnet/Docs#11707]
In the section https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#service-lifetimes , it says "Transient lifetime services are created each time they're requested." and "Scoped lifetime services are created once per request."

The two definitions sound equivalent to me. How is the lifetime of a Transient different from a Scoped service?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Good idea @ScottHutchinson ... I agree ... "request" is overloaded here. I'll fix it up. Thanks for commenting.

**Comment by guardrex** [comment]
@ScottHutchinson Do you agree that if it remarked for transient along the lines "(service is) requested from the container" that that would clear it up? I think adding "from the container" should do the trick in those spots. Whereas, most devs will process (for scoped) "the request" as an ordinary app request.

**Comment by ScottHutchinson** [comment]
I think that's a lot clearer. Thanks for the prompt fix!



------ Original Message ------
   Received: 11:45 AM PDT, 03/27/2019
