### ISSUE TITLE
CreatedAtRoute method

### ISSUE THREAD

**Issue by RobinTTY** [aspnet/Docs#11717]
While this tutorial is a great introduction to ASP.NET, I have one suggestion:
In the section "Add a controller" the attribute [HttpGet("{id:length(24)}", Name = "GetBook")] and CreatedAtRoute() method are used to add new items. The concept behind CreatedAtRoute isn't really touched upon in this or the other tutorial. It would be nice to maybe have a short explanation of what is happening here since the Docs aren't too expansive on this topic either.

I found a good explanation here: https://forums.asp.net/t/2027150.aspx?Created+vs+CreatedAtRoute+IHttpActionResults

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Build web APIs with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by prkhandelwal** [comment]
@Rick-Anderson It is actually a good suggestion. Current docs don't really explain `CreatedAtRoute()` that well. But is it a good idea to include it in this  tutorial?

**Comment by Rick-Anderson** [comment]
Might be better to change that to `CreatedAtAction`
