### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by JustTheDr** [aspnet/Docs#11724]
When I followed through the tutorial, and navigate to my localhost:port/movies I get a blank page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.

**Comment by duydangnguyendkt** [comment]
I have same issues but i know what is going on, 
some how it generate codes (Create,Delete,Details,....) on Models, you need create Movies folder in Pages and move these file into it. Worked for me .

Rick Anderson is great and the tutorial is fine.
