### ISSUE TITLE
Layouts add more complexity than they help

### ISSUE THREAD

**Issue by jakobrames** [aspnet/Docs#11735]
It appears to me that any problem solved by using layouts can also be solved by using regular Blazor components. 
Layouts might be a subjectively cleaner way to do it, but adding an extra learning topic, which adds so little functionality, for new developers getting into Blazor seems counter-intuitive to me.
Having a clean way to implement this in normal components (like there already is), instead of using layouts, seems like it will keep the learning curve less steep for beginners and ensure people will always implement child content of components in the same way across a codebases.
I'm brand new to Blazor, and maybe I've missed something and layouts can do something you cannot do with normal components. If that's the case, I could understand there might be a use for them.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: cce76032-e7b4-d168-6e24-c2cb88ae7e44
* Version Independent ID: f3ecd255-c3ce-9162-ddf1-67b35aeffc11
* Content: [Razor Components layouts](https://docs.microsoft.com/da-dk/aspnet/core/razor-components/layouts?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/razor-components/layouts.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-components/layouts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-razorcomponents**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jakobrames ... Normal components used in parent-child relationships require the parent to explicitly include the child component by name. Layouts allow you to set an `@Body` property in the layout component where *any child referencing the layout in an `@layout` directive* will have its content rendered at the `@Body` location. This is better for the scenario that it serves. The ability to have *one directive* (just one line of Razor code) in each component that consumes the layout isn't just subjectively cleaner ... it's actually a lot cleaner.
