### ISSUE TITLE
Some Authentication is still performed even without calling app.UseAuthentication()

### ISSUE THREAD

**Issue by DrEsteban** [aspnet/Docs#11741]
This is probably an strange quirk of Identity system vs MVC.  

This document says that Authentication is inserted into the middleware pipeline by calling `app.UseAuthentication()` at the appropriate place in your `Startup.Configure()` method.  Well, in our app we want the ability to disable authentication with an environment variable for testing purposes.  We thought we could do this by simply surrounding the call as follows:

```C#
public void Configure(IApplicationBuilder app)
{
    if (authEnabled())
    {
        app.UseAuthentication();
    }
}
```

And of course, all our controllers are tagged with the `[Authorize]` attribute.  Well, it turns out that MVC adds a default `AuthorizeFilter` with a `DenyAnonymousAuthorizationRequirement` even if you intentionally leave out `app.UseAuthentication()`.  This means some level of auth is still required even though we were expecting it not to be...

Might be worth calling this out in the docs?  Or working with the MVC team to change this behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you use `[Authorize]`, you get the behavior you mention. You need to remove that too. You can do that with `#if`
