### ISSUE TITLE
Switching between cultures in dropdown redirects to default culture

### ISSUE THREAD

**Issue by FaridGN** [aspnet/Docs#11742]
I followed the steps given by you, but face with the problem given in the title: 
Switching between cultures in dropdown redirects to default culture.
I wrote to many forums but none of their advice could help me solve it. Here is the link where you can get detailed info and used codes, browser results, etc.
https://forums.asp.net/t/2154249.aspx?Switching+between+cultures+in+dropdown+redirects+to+default+culture

Please, review attentively, you must know what might cause this problem. 
Thanks in advance

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
Please refer to the [Localization.StarterWeb](https://github.com/aspnet/Entropy/tree/master/samples/Localization.StarterWeb) or to my [LanguageSwitcherTagHelper](https://github.com/hishamco/languageswitchertaghelper)

**Comment by Rick-Anderson** [comment]
@hishamco  شكرا جزيلا.

**Comment by hishamco** [comment]
You're welcome any time Rick :)

**Comment by rschindhelm** [comment]
I stumbled upon this too. There is a correlation between the [GDPR cookie consent feature](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr) middleware, which will prohibit setting the cookie when the user has not yet given his consensus.

Thanks @hishamco for providing the tag helper.

**Comment by hishamco** [comment]
@rschindhelm I did that before GDPR support, you can file the issue in my repo, hopefully to work on what you asked for

thanks

**Comment by davidbuckleyni** [comment]
https://github.com/aspnet/AspNetCore.Docs/issues/16563 I am having the same issue here totally re producible I shouldn't have to use another third-party component as this is Microsoft documentation the above solution is not correct.

**Comment by davidbuckleyni** [comment]
@FaridGN  DID You solve your issue I am having the act same problem

**Comment by hishamco** [comment]
While the issue is closed, please file a new one and link it to this

Ping me whenever you create it
