### ISSUE TITLE
Clarify on how MemoryCache works when size limit is reached

### ISSUE THREAD

**Issue by datvm** [aspnet/Docs#11740]
I see nowhere that states how items are going to be evicted once the size limit is reached. May worth mention it in one short sentence I think. First added, Least access, Nearest to Expiration or Earliest access?

According to [the code here](https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs), it seems the entry simply is not cached at all if the limit is reached? It seem counter intuitive to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#use-setsize-size-and-sizelimit-to-limit-cache-size)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #11216

**Comment by datvm** [comment]
Sorry I did check that issue before. In #11216 what I can see most relevant to my issue is your last comment

> I'll add that to the docs.
> Should I write, when memory is exhausted, behavior is indeterminate.

I see it's not in the doc yet (but in Todo list). I hope it's more specific than just `indeterminate`. May I suggest just describe what it is doing now (ignore)?

**Comment by Rick-Anderson** [comment]
It doesn't do anything. It's the same as if you allocate more memory than is available.
