### ISSUE TITLE
docs.asp.net is blocked by my company's firewall

### ISSUE THREAD

**Issue by caitchison** [aspnet/Docs#1175]
docs.asp.net resolves to 198.232.125.32 which is a shared IP address which also hosts some "malicious" sites according to quite a few online security providers. As an example see https://www.threatcrowd.org/ip.php?ip=198.232.125.32

This means that people that try to access the site from behind certain company firewalls are unable to. Is there any possibility of having it use a different IP address that is not shared with malicious sites?

**Comment by danroth27** [comment]
@blowdart

**Comment by danroth27** [comment]
@agjohnson @ericholscher

**Comment by blowdart** [comment]
The IP address in question is a CDN proxy, which is used by more than just the docs site. There's not a lot we can do about this, as it's not a problem with the actual site hosting the docs. But we'll make them aware of it anyway, just in case they can do something.
