### ISSUE TITLE
Installing Core tools for IIS breaks aspnet core projects

### ISSUE THREAD

**Issue by gimzani** [aspnet/Docs#11764]
Please tell your team that creates installers about this one!!!

Scenario:
I spent some time developing several dotnet core projects as microservices.  
Next, I wanted to serve them using IIS - so I published to a folder and hooked up IIS on my local machine.
It didn't work initially and gave me an error 500 - which basically said that IIS could not use the current module - it was a version behind.  So I installed 2.2.3
The IIS sites worked, but when I went back into Visual Studio - NONE of my core projects would load.
What happened is that the IIS installer overwrote the "PATH" variable and put the dotnet items out of order.

Please fix this - it could REALLY anger developers that are trying really hard to like dotnet core.

ref:
https://poshtools.com/2018/04/27/fixing-did-you-mean-to-run-dotnet-sdk-commands-error-when-running-dotnet-version/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f16c68-708b-003e-8c63-1df60c6344d0
* Version Independent ID: 25fa0508-4450-9051-cdd7-0d3260c60b4f
* Content: [Troubleshoot ASP.NET Core on IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/troubleshoot.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-hostdeploy**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gimzani ... It's a known issue for the installer. We addressed it in the docs on https://github.com/aspnet/Docs/pull/11386. The coverage was provided at: https://docs.microsoft.com/aspnet/core/test/troubleshoot#missing-sdk-after-installing-the-net-core-hosting-bundle

I'll cross-reference that coverage from the IIS Troubleshoot topic.

We plan to address the scattered troubleshooting content/topics on https://github.com/aspnet/Docs/issues/10150 (asap 🏃🏃🏃🏃😅).

Leave this issue open. It will auto-close when my PR merges.

**Comment by guardrex** [comment]
Actually, the cross-link is already there.

The IIS Troubleshooting topic's sole purpose is to describe **_how to troubleshoot_** IIS, not to list and describe the *great number of error scenarios*. The *Troubleshoot* topic in the *Test, Debug, and Troubleshoot* area and the *Common Errors for IIS/Azure* topics maintain that content.

I'll take a broad look at how we're maintaining this coverage when I get to #10150. It's likely that the IIS *Troubleshoot* topic (and the Azure Apps *Troubleshoot* topic) will be moved into the *Test, Debug, and Troubleshoot* area, which will make it easier to find/consume all of the help content.
