### ISSUE TITLE
Why prefer putting untrusted JS data in an HTML element over JS encoding this data?

### ISSUE THREAD

**Issue by gaazkam** [aspnet/Docs#11775]
&gt; Before putting untrusted data into JavaScript place the data in an HTML element whose contents you retrieve at runtime. If this isn't possible, then ensure the data is JavaScript encoded.

Why is the former preferred over the latter?

Shouldn't the latter work just as well, while being more conveniet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's not the recommendation. You might ask this question on SO for the details.
