### ISSUE TITLE
HttpPost Tutorial didn't work for me

### ISSUE THREAD

**Issue by Jaygem** [aspnet/Docs#11787]
# Issue
In [this page](https://docs.microsoft.com/fr-fr/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio) at the HttpPost section there's a missing attribute : 
original : 
```csharp
// POST: api/Todo
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem(TodoItem item)
{
    _context.TodoItems.Add(item);
    await _context.SaveChangesAsync();

    return CreatedAtAction(nameof(GetTodoItem), new { id = item.Id }, item);
}
```

Working solution for me : 

```csharp
// POST: api/Todo
[HttpPost]
public async Task<ActionResult<TodoItem>> PostTodoItem([FromBody] TodoItem item)
{
    _context.TodoItems.Add(item);
    await _context.SaveChangesAsync();

    return CreatedAtAction(nameof(GetTodoItem), new { id = item.Id }, item);
}
```

**Comment by guardrex** [comment]
Moving to https://github.com/aspnet/Docs/issues/11790.

@Jaygem Please use the feedback button at the bottom of the topic to open an issue. It adds metadata that helps us track the issue.
