### ISSUE TITLE
Actions and Action Results

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#118]
ASP.NET MVC -> Controllers -> Actions and Action Results

- What is a controller?
  - Defines and groups a set of actions
  - An action is method on your controller that handles requests 
  - A public instantiable class that ends in "Controller" or inherits from a class that ends with "Controller"
- Defining your actions
  - Public method on a controller type
  - Parameters on your action get bound to request data and validated using model binding (link)
    - Note: your controller code SHOULD check `ModelState.IsValid`
  - Your action methods contain application logic that map requests to a business concern.
    - Business concerns are typically represented as services that you controller uses (link to Controller DI)
    - Actions map the result of the business action to an application state
  - Actions can return
    - An `IActionResult` that produces a response
      - You can return an action result directly or call one of the many helper methods on `Controller`
      - Examples:
        - Views that use a Model to render HTML (ex `View(product)`)
        - Specific HTTP status codes (ex Redirect, OK, etc)
        - Response formatting (ex `Json()`)
    - An object that you want formatted in the response (link to Response Formatting)
  - Cross cutting concerns
    - Handled by Filters (link)
    - Examples:
      - Authorization (link)
      - Response caching (link)

Note: Cover custom action results in a separate topic

**Comment by Rick-Anderson** [comment]
Routing to Controller Actions#117 https://huboard.com/aspnet/docs#/

**Comment by danroth27** [comment]
I think this one should stay open - the Routing to Controller Actions article is more about how a request makes it to your action. It doesn't really cover the response path and how action results work.

**Comment by ardalis** [comment]
@danroth27 this is my last outstanding article this batch - do we need to set up a meeting to discuss the outline?
