### ISSUE TITLE
Problem Abou Publish to a Linux Production Environment

### ISSUE THREAD

**Issue by lonely-boy** [aspnet/Docs#1181]
this is article‘s link[https://docs.asp.net/en/latest/publishing/linuxproduction.html](url)

Hello, i have some question about this article. After I configured supervisor, it doesn't work. And the log file print `/var/www/output/approot/kestrel: line 11: exec: dnx: not found`
this is  my config file info
```
[program:test1]
command=bash /var/www/output/approot/kestrel
director=/var/www/output/approot
autostart=true
autorestart=true
stderr_logfile=/var/log/test1.err.log
stdout_logfile=/var/log/test1.out.log
environment=Hosting__Environment=Production
user=root
stopsignal=INT
```
What should i do about this problem？

**Comment by danroth27** [comment]
Did you follow the setup steps to install DNX in your linux environment?: https://docs.asp.net/en/latest/getting-started/installing-on-linux.html

**Comment by lonely-boy** [comment]
Yes,I was already Install DNX and the commad of the config file is worked in Terminal.But it doesn't worked use supervisor.

**Comment by danroth27** [comment]
@shirhatti Thoughts on what might be going on here?

**Comment by lonely-boy** [comment]
this is my Kestrel file Info:
```
#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

exec "dnx" --project "$DIR/src/test1" --configuration Debug kestrel "$@"
```
when command run `exec "bash dnx" --project "$DIR/src/test1" --configuration Debug kestrel "$@"`
it write a log`/var/www/output/approot/kestrel: line 11: exec: dnx: not found`
so what should i do??

**Comment by lonely-boy** [comment]
@danroth27  thanks for you help！I have solution this question.
just like the log file sya `dnx: not found`
so, I add the path of dnx in the Kestrel file :
`exec "/usr/local/bin/dnx" --project "$DIR/src/test1" --configuration Debug kestrel "$@"`
and then restart supervisor.
ok, my application is working.
