### ISSUE TITLE
Error in tag helper prefix code listing in Tag Helpers intro

### ISSUE THREAD

**Issue by anpete** [aspnet/Docs#1185]
The tag helper prefix example in https://github.com/aspnet/Docs/blob/master/aspnet/mvc/views/tag-helpers/intro/_static/thp.png should not have quotes around the prefix. I.e: It should be:
```html
@tagHelperPrefix th:
```

**Comment by Rick-Anderson** [comment]
@anpete Yes, this is a RC2 change. You also don't need the ":" so it should be
``@tagHelperPrefix th``

**Comment by Rick-Anderson** [comment]
fixed
