### ISSUE TITLE
Errors in authoring tag helpers page

### ISSUE THREAD

**Issue by anpete** [aspnet/Docs#1186]
1) Usages of @addTagHelper use double-quotes around the arguments.
2) Examples show using an _address_ tag helper rather than _email_

**Comment by Rick-Anderson** [comment]
@anpete https://github.com/aspnet/Docs/pull/1188

**Comment by Rick-Anderson** [comment]
@anpete I see lots of EmailTagHelper but no AddressTagHelper

**Comment by anpete** [comment]
@Rick-Anderson I was looking at http://docs.asp.net/en/latest/mvc/views/tag-helpers/authoring.html. If this is already fixed then feel free to ignore.

**Comment by Rick-Anderson** [comment]
Thanks, I was looking at intro. I'm fixing intro now "th:" - I'll fix both of them in the author doc. Thanks for the quick feedback and the good RC2 change catch.

**Comment by Rick-Anderson** [comment]
fixed
