### ISSUE TITLE
Social Logins doc needs to be updated for RC2

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#1187]
* Still refers to DNVM and Beta8
* `dnu commands install` used to install secret manager
* In the [Enable Facebook Middleware](https://docs.asp.net/en/latest/security/authentication/sociallogins.html#enable-facebook-middleware) step, where do I put it? Middleware order is important. And, it has to go **below** `UseIdentity` or things blow up
* In the [Enable Facebook Middleware](https://docs.asp.net/en/latest/security/authentication/sociallogins.html#enable-facebook-middleware) step, needs to use `new FacebookOptions() { ... }` instead of `options => { ... }`
* We need simple reference docs for configuring each provider including the URLs that need to be registered (for example `[myapp]/signin-microsoft`, etc.)
* Some providers, such as Microsoft Account, do not allow the use of `localhost`. The docs should provide some assistance with configuring something like [localtest.me](http://readme.localtest.me/).
* More coming as I continue testing...

/cc @Tratcher @HaoK

**Comment by rustd** [comment]
This doc should get updated for RC2 to match the API version/ tool changes.

**Comment by Rick-Anderson** [comment]
fixed.
