### ISSUE TITLE
ASP.NET Core Module Configuration Reference

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#1189]
Document how to configure the ASP.NET Core Module using web.config. It will read similar to the [HttpPlatformHandler Configuration Reference](http://www.iis.net/learn/extensions/httpplatformhandler/httpplatformhandler-configuration-reference).

It should also explicitly call out the `app_offline` behavior.

This article will live under the Publishing and Deployment node in the top level TOC.

**Comment by shirhatti** [comment]
@danroth27 Thoughts?

**Comment by danroth27** [comment]
Sounds good to me.

**Comment by shirhatti** [comment]
Spoke to @Rick-Anderson offline. He will be working on this

**Comment by Rick-Anderson** [comment]
>It should also explicitly call out the `app_offline` behavior.

@shirhatti can you send me the text for that?

**Comment by shirhatti** [comment]
If you place a file with the name `app_offline.htm` in the root of a web application directory, ANCM will shut-down the application and stop processing any new incoming requests for that application.  ANCM will also then respond to all requests for dynamic pages in the application by sending back the content of the `app_offline.htm` file (for example: you might want to have a “site under construction” or “down for maintenance” message).
 
Once you remove the app_offline.htm file, the next request into the application will cause ANCM to load the application again, and life will continue along as normal.
