### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#119]
ASP.NET MVC -> Controllers -> Filters
- Which filter do I need?
- How do filters work? Async or not; Cancellation/short-circuiting
- Configuring Filters - How, Where, Ordering, Scope
Filters are not directly returned from DI
You can write an attribute that has the filter interface on it
or you can implement an attribute that implements IFilterFactory
or you can use TypeFilter attribute or ServiceFilter attribute
TypeFilter: news it up and passes params to its constructor from DI
ServiceFilter: gets your filter from ServiceCollection (thus must be registered with DI)
If you're using IFilterFactory, you can specify lifetime of the filter
When your filter is the instance, your filter instance is cached, so don't do anything stateful.
GlobalFilters are registered through MvcOptions

Scope - Filter can be applied per-action method (via attribute) or via controller (via attribute), or in global filters collection. Scope also generally determines ordering. The filter closest to the action runs first; generally you get overriding behavior without having to explicitly set ordering.

- Action filters (see Ryan's doc)
- Result filters (see Ryan's doc)
- Exception filters
Handle unhandled exception
Good for localized error handling (around this action/controller, not Localization)
Only called when an exception happens
Guidance - Prefer using error handling middleware for general case; use filters only for exceptional exceptions :) cases
All filters have a before/after stage, except Exception Filters (and Auth only have Before)
Filters run from outer scope to inner before, then inner to outer after. Russian doll nesting.
These let you handle errors that occur during controller creation or during model binding.

- Authorization filters
Only have a before stage
Throwing an exception in an auth filter is "considered an error" - nothing will handle this exception (exception filters won't handle them). Instead, issue a challenge or find another way.
Recommendation: Only write an auth filter if you are writing a custom auth framework
The [Authorize] attribute should be flexible as-is; we don't recommend extending it
Resource filters replace some scenarios devs used to use [Authorize] for
Link to the Authorize article stub

- Resource filters
Run after Authorization. It's the first thing after Authzn that is your code.
Lets you determine if resource should continue executing or not - happens before controller creation, model binding, etc. so you can very cheaply short circuit the request at this point. Example: caching could happen here, well before a lot of other request processing has taken place.
Ignore whether these can modify the inputs to model binding - this feature may go away.

Avoid filter examples that mimic diagnostics and logging capabilities already in the framework (include note to this effect)

In general, filters are meant to handle cross-cutting business and application concerns.

Difference between Middleware vs. Filters

(A planned feature in vNext is, create a middleware pipeline and put it into a filter.)

Filters are very similar to Middleware in capability, but let you scope that behavior and insert it into a location in your app where it makes sense (e.g. before a view, or after model binding). Ex: If I have a validation error, always return a 400 error and put error in the body (for an API). This can't be done in middleware since it can't access the MVC context.

**Comment by danroth27** [comment]
A useful starting point here: https://github.com/aspnet/Docs/tree/rynowak-wip

**Comment by ardalis** [comment]
https://github.com/aspnet/Docs/blob/551ac274b4c23c583262bd165619370495006dec/mvc/controllers/filters.rst

**Comment by ardalis** [comment]
Resource filters in MVC examples: ConsumesAttribute  SaveTempDataFilter

SkipStatusCodePagesAttribute

FormatFilter

**Comment by ardalis** [comment]
@rynowak is there anything I need to document about ordering filters (within the same stage)?

**Comment by ardalis** [comment]
@rynowak let me clarify - I understand scope-related ordering. My question is, given the same stage and the same scope, do we have a means of ordering filters? e.g. on a method if I say:
[Filter1]
[Filter2]
public void Method()

Can I expect these to run in a particular sequence? Can I do anything to enforce a desired sequence?

**Comment by rynowak** [comment]
Yes, filters can implement `IOrderedFilter` to manually provide an ordering. See the docs here https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Filters/IOrderedFilter.cs for a precise, yet verbose description.

All of the built-in filters generally implement `IOrderedFilter`.

Let me also showcase that `Order` is a stronger qualifier than scope. Filters are sorted first by order, and then scope is used to break ties.
