### ISSUE TITLE
Enhance ClaimsPrincipal/Identity content in CookieAuth w/o Identity topic

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#1190]
In https://docs.asp.net/en/latest/security/authentication/cookie.html#creating-an-identity-cookie, nothing describes how to create the necessary ClaimsPrincipal. There are a few tricks to deal with there and some docs would help. For example:
- Must set `AuthenticationType` on the ClaimsIdentity
- What claims should I add? Why?

/cc @blowdart @Tratcher

**Comment by danroth27** [comment]
@blowdart if you could send us a short text proposal we can get it merged in.

**Comment by blowdart** [comment]
You must set an authenticationtype on the claims identity because that is how the identity knows it's authenticated. If you forget the identity will be unauthenticated and will be ignored by authorization.

As for what claims, honestly that's up to the user scenario. I don't think I can give any generic guidance.

**Comment by anurse** [comment]
Yeah, I figured out why I needed AuthenticationType, but it wasn't obvious right from the start.

I think that calling out the Name and Role claims would be useful, since they are what most users will want to configure.

**Comment by guardrex** [comment]
We made a decent start on this with the work on https://github.com/aspnet/Docs/pull/5307.

https://docs.microsoft.com/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x#creating-an-authentication-cookie

I see an opportunity to enhance it a bit and fix this issue.

Confirm cross-links to:
* [Claims-Based Authorization](https://docs.microsoft.com/aspnet/core/security/authorization/claims)
* [Policy-based role checks](https://docs.microsoft.com/aspnet/core/security/authorization/roles#policy-based-role-checks)
