### ISSUE TITLE
No docs on Identity "Lockout" feature

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Docs#1195]
The docs at http://docs.asp.net/en/latest/security/authentication/index.html cover most aspects of Identity, but they don't mention the account lockout feature.

It's not easy to discover how to enable this. Even if you discover the `Lockout` property on the `AddIdentity` callback in `Startup.cs`, that's not enough - you also have to modify `AccountController`'s `Login` method to pass `lockoutOnFailure: true`.

**Comment by danroth27** [comment]
@blowdart @HaoK

**Comment by Rick-Anderson** [comment]
@blowdart @HaoK can you provide guidance on account lockout?

**Comment by guardrex** [comment]
This issue has been addressed to some extent with the content in:
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?tabs=aspnetcore2x#lockout
* https://docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa#account-lockout-for-protecting-against-brute-force-attacks

Looks like the first link to *Lockout* could use at least a one or two line description under the section heading.

@HaoK What else do we need to surface?
