### ISSUE TITLE
Account Confirmation and Password Recovery (security/authentication/accconfirm.md)

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Docs#1196]
The docs at http://docs.asp.net/en/latest/security/authentication/accconfirm.html say:
- It’s a best practice to confirm the email of a new user registration to verify they are not impersonating someone else (that is, they haven’t registered with someone else’s email).
- You generally want to prevent new users from posting any data to your web site before they have been confirmed by email, an SMS text message, or another mechanism.

These two statements don't really work together. If you're going to allow confirmation via SMS or "another mechanism", then you haven't actually confirmed ownership of the email address. You only confirm they have access to whatever communication channel they get the token through.

[Edit - adding more work]
- [ ]  Address steves comment.
- [x]  Update for RTM 
- [x]  Sendgrid API has changed 
- [x]  #2167  add ` options.SignIn.RequireConfirmedEmail = true; `

**Comment by Rick-Anderson** [comment]
removed SMS and now it reads

You generally want to prevent new users from posting any data to your web site before they have a confirmed email. In the sections below, we will enable email confirmation and modify the code to prevent newly registered users from logging in until their email has been confirmed.
