### ISSUE TITLE
"Safe Storage of App Secrets" 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1197]
- [ ] rename to "Keeping app secrets out of code during Development with the Secret Manager tool"
- [ ] update for RC2

Customers don't like the current title because secret manger doesn't encrypt secrets - the article is really about using the tool to keep secrets out of code.

@blowdart  is the title change better/preferred/OK?

**Comment by blowdart** [comment]
I'd add "In Development" because that is what this is aimed at.

**Comment by Rick-Anderson** [comment]
Keeping app secrets out of code in Development with the Secret Manager tool
sounds like out of dev they can be in code.
@blowdart  is that where you wanted "in Dev"

**Comment by blowdart** [comment]
Ah I see, how about during Development then. Does that flow better?

**Comment by Rick-Anderson** [comment]
New title:
Keeping app secrets out of code during Development with the Secret Manager tool

perfect

**Comment by blowdart** [comment]
Thanks
