### ISSUE TITLE
Create VS code  versions of tutorials/first-web-api

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1215]

**Comment by dlebedynskyi** [comment]
would really love sample with configuration of ssl and custom run port retrieved from configuration. Similar to what you can do in VS with launchSetting.json setting `sslPort:44312`

**Comment by spboyer** [comment]
For non-vs examples, do we want to use `yo aspnet` or `dotnet new`? or show both?

@DamianEdwards @danroth27
