### ISSUE TITLE
RC1 -> RC2 Migration followup

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Docs#1227]
Followup to https://github.com/aspnet/Docs/pull/1161.

Issues that still need to be addressed:

- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L74-L87. I have sent an email explaining what changed here. The content should be updated and maybe even an accompanying explanation.
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L184. nit: append `.Build()` at the end.
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L174. nit: there are lots of inconsistent formatting between project.json and `project.json`. Same with web.config vs `web.config`. Let's choose one and go with it. Good idea to search the entire document and make sure each occurrence is formatted correctly.
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L270. What is meant by the `web` command? There isn't a `dotnet-web`. Missing `Microsoft.AspNetCore.Server.IISIntegration.Tools` and `Microsoft.AspNetCore.Razor.Tools`? Also, this section doesn't mean much at the moment and it might be better to explain this section a bit more, i.e. how to add tools to a project and how to run them. For RC2, we currently do not have dotnet CLI capability for global tools so each of these tools are project specific and need to be added under the `tools` section in the `project.json` along with its required `imports` subsection. To run them, you need to be in the project directory and run `dotnet <tool name>` Maybe this explanation belongs in the dnx->dotnet migration doc though.
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L340-L341. Formatting looks wrong, the two lines should be merged into a single row.
- [x] I brought this up before. Delete `RC1StarterWeb - Web Deploy-publish.ps1`, see image below. This is a script generated by VS for web deploy. There is a version for RC1 projects (dnx based) and a different script for RC2 projects (dotnet based) which are incompatible with each other. As such, when migrating to RC2, you need to delete the old script and let VS generate a new one to ensure web deploy works for the converted RC2 project.
![image](https://cloud.githubusercontent.com/assets/2030323/15305788/37ebb78e-1b7a-11e6-9c7e-6b41013b46d0.png)
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L40. nit: formatting. Function names should be formatted to `SomethingLikeThis()` and also format project.json, wwwroot, etc.
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L60-L69. Headings?
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L108, https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L118. nit: missing semicolon
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L276. nit: inconsistent formatting. `IConfigurationSource` is formatted IConfigurationProvider is not.
- [x] https://github.com/aspnet/Docs/blame/dev/aspnet/migration/rc1-to-rc2.rst#L289. nit: Trace is not formatted
- [x] should also mention removing or updating sdk version in `global.json`
- [x] if applicationhost.config was created with RC1 or early RC2 it will point to a wrong application folder and the user won't be able to start the appliation with IIS. (https://github.com/aspnet/Tooling-Internal/issues/577)
We should also get another pair of eyes on this since I'm not familiar with some of the changes (like the ones related to MVC).
cc @rachelappel @danroth27

**Comment by JunTaoLuo** [comment]
@DamianEdwards, we should figure out how to restructure the document here and what to add/update in the dotnet migration docs.

**Comment by moozzyk** [comment]
Added one more line to the issue where it may not be possible to start the application from VS if it was created with RC1 or early RC2. The applicationhost.config file will read wwwroot as the application folder and this is where IISExpress will look for web.config file. Since web.config now lives in approot the application won't start and it is very hard to figure out why (https://github.com/aspnet/Tooling-Internal/issues/577).
