### ISSUE TITLE
Testing Controller Logic

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#123]
ASP.NET MVC -> Controllers -> Testing Controller Logic

**Comment by cmatskas** [comment]
Hi @ardalis and @danroth27. Has there been any progress with this? Can we/I help in anyway to get the documentation outthere somehow? thanks

**Comment by tomtomcarter** [comment]
Hi, 
I would be pleased if I could get a copy of the draft version of this article to come. 
Many thanks. 
Thomas

**Comment by ardalis** [comment]
I expect to start on this article this week.

**Comment by tomtomcarter** [comment]
Great thanks
