### ISSUE TITLE
Correct way to enable Server GC in RC2?

### ISSUE THREAD

**Issue by jeremymeng** [aspnet/Docs#1237]
The migration guide suggests something like the following, which seems from https://github.com/aspnet/Announcements/issues/175
```
{
  "runtimeOptions": {
    "gcServer": true,
    "gcConcurrent": true
  }
}
```
However, when I tried on RC2, it doesn't work for me.  I had to use the code below
```
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  }
```

**Comment by GuardRex** [comment]
Covered by the Annoucement: https://github.com/aspnet/Announcements/issues/175

**Comment by danroth27** [comment]
@ajaybhargavb @piotrpMSFT

Here is what I see in our RC2 templates: 

```json
  "runtimeOptions": {
    "gcServer": true
  }
```

When you say that the above doesn't work for you can you clarify what exactly you are seeing? How are you detecting whether server GC is being used?

**Comment by jeremymeng** [comment]
I have this code:
```csharp
            if (GCSettings.IsServerGC)
            {
                Console.WriteLine("Server GC");
            }
            else
            {
                Console.WriteLine("Workstation GC");
            }
```
It prints out "Workstation GC" when I use `gcServer": true`

**Comment by jeremymeng** [comment]
A related issue: https://github.com/dotnet/cli/issues/2121
A related commit: https://github.com/aspnet/benchmarks/commit/b7632666c7aa9a90f1893f5c677239d1795001b8

**Comment by ajaybhargavb** [comment]
@danroth27, I think the structure of `runtimeOptions` has changed since the announcement. https://github.com/aspnet/Home/issues/1418#issuecomment-219815694

**Comment by danroth27** [comment]
@sayedihashimi @phenning @ajaybhargavb @piotrpMSFT @rachelappel  So what we have in the templates for RC2 is incorrect? The JSON schema also appears to be incorrect:

![image](https://cloud.githubusercontent.com/assets/1874516/15383376/641ba494-1d47-11e6-8b45-ead899ba31d1.png)

**Comment by sayedihashimi** [comment]
The runtime team owns the schema, and I think it can be updated on the fly.

**Comment by danroth27** [comment]
@sayedihashimi @barrytang This is more than just a schema issue. It looks like what we have in our template project.json files is wrong.

**Comment by bragma** [comment]
I'm a bit lost. Is this valid also for webjobs (console apps) targeting net461?

**Comment by danroth27** [comment]
No, for console apps target the full .NET Framework you would need to enable server GC in app.config.
