### ISSUE TITLE
404 Not found for "Getting Started With ASP.NET Core and Entity Framework Core"

### ISSUE THREAD

**Issue by lzonjic** [aspnet/Docs#1239]
On page [Working with Data](https://docs.asp.net/en/latest/data/index.html) there is a broken link to [Getting Started With ASP.NET Core and Entity Framework Core](http://docs.efproject.net/en/latest/platforms/aspnetcore/getting-started.html)

**Comment by danroth27** [comment]
@Rick-Anderson Please close once #1240 is merged.
