### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#124]
ASP.NET  -> Fundamentals -> Error handling
- Exception handling page (move from Diagnostics)
- When and how to use exception filters
- Status Code page (in Diagnostics package - fits best here)
- Limitations of error handling in client/server interactions (see #67)
- Reference IIS/Kestrel/Server error handling (links)
- Startup error handling (https://github.com/aspnet/Docs/issues/1095)

**Comment by Rick-Anderson** [comment]
captured in MVC Error handling#124 https://huboard.com/aspnet/docs#/

**Comment by ardalis** [comment]
I'm working on this next, @danroth27

**Comment by danroth27** [comment]
@ardalis Sounds fine.

**Comment by ardalis** [comment]
Can you provide me with some reference/links or point-of-contact for IIS/Kestrel/Server error handling? @danroth27
