### ISSUE TITLE
bower.json and package.json not visible in VS solution explorer

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1244]
See https://docs.asp.net/en/latest/client-side/bower.html#comment-2682384620
in https://docs.asp.net/en/latest/migration/mvc.html we have them edit both files.
Need to document how to work with these files and why they are hidden.

**Comment by danroth27** [comment]
I believe a lot of this stuff is also getting removed from the templates, so we will need to do a major update to the doc.

**Comment by scottaddie** [comment]
@Rick-Anderson I'm working on updating the client-side Bower doc, and I expect to have a PR ready in the next week or so.

**Comment by spboyer** [comment]
@scottaddie - are you still working on this

**Comment by scottaddie** [comment]
@spboyer I've hit a brick wall with this. There's a known issue in the Manage Bower Packages dialog which is causing me trouble. Either the fotorama example has to be replaced with something else, or this issue needs to be fixed. According to Joe Davis' comment [here](https://github.com/aspnet/Tooling/issues/506), only the top 1,000 packages are displayed in the Manage Bower Packages UI. I suspect fotorama didn't make the cut. Any recommendations on how to proceed?

**Comment by spboyer** [comment]
@scottaddie - need to wait until there is a fix perhaps for the package manager

**Comment by danroth27** [comment]
@madskristensen
