### ISSUE TITLE
Introduction to Tag Helpers

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#125]
ASP.NET MVC -> Views -> Tag Helpers -> Introduction to Tag Helpers

What they are
- Lift from https://channel9.msdn.com/Series/ConnectOn-Demand/232
- Allow server-side code to participate in the rendering of HTML
- Differences from Web Form controls
  - No lifecycle, no DOM
  - Multiple can run on an element
  - Tag helpers are attached to an HTML element vs you _use_ a Web Forms control
  - No type converters, not ComponentModel based.

Why they exist
- Edit in HTML with all the power of the editing tools + C# editing tools

Comparison to HTML Helpers
- Ex. Comparison of login.cshtml for MVC 5 and MVC 6

**Comment by pnewhook** [comment]
I'd like to write about this. Does it make sense to break out each bullet into it's own issue? I think [Damian Edwards' video](https://channel9.msdn.com/Series/ConnectOn-Demand/232) gives a good starting point, at least for 'What are Tag Helpers'?

**Comment by danroth27** [comment]
@pnewhook Thanks for offering to contribute! Because Tag Helpers are a new feature in MVC 6 we plan to have someone from the product team handle the Tag Helper docs directly. There are still plenty of other articles that need to be written though, so please do look through the issues and see if there is something else you would like to work on.

**Comment by Rick-Anderson** [comment]
@danroth27  Do you mind if I add links to the series at http://www.davepaquette.com/archive/2015/05/11/cleaner-forms-using-tag-helpers-in-mvc6.aspx on http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/index.html ?
Customers will have something useful on tag helpers.

**Comment by danroth27** [comment]
I'd rather not. Our official docs need to be authoritative, updated and persistent, while blog content is more point in time.

**Comment by Rick-Anderson** [comment]
Our authoritative doc's have a section on other resources. We can't do everything. This is reminding me a lot of wikipedia. Maybe we can get discoverability by featuring the docs on the asp.net site (featured blogs).

**Comment by gusennan** [comment]
This would be great.  Until there is documentation on this, is there a way you could recommend that early adopters can find out which tag helpers are available on which elements?  Looking through source could be acceptable at this time...

**Comment by danroth27** [comment]
The in the box taghelpers can be found here: https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNet.Mvc.TagHelpers

**Comment by GuardRex** [comment]
@danroth27 :-1:

Not being an employee of Microsoft or among the elite outsiders and producing "authoritative, updated and persistent" documentation should not be mutually exclusive concepts, and just because documentation is "authoritative, updated and persistent" doesn't mean that it explains concepts clearly or describes good process.

I wish you would let @pnewhook write his draft and compare it to the draft from the MS team member and see who can do a better job with the topic? Let *quality* be the basis for what becomes the official documentation ... not a *wild guess* that god's chosen few will do the better job. Hail Ming! :smile:

**Comment by danroth27** [comment]
@GuardRex I think you misunderstand me! The whole reason we made our docs open source was to allow for contributions from anyone in the community. _Anyone_ is welcome to contribute. If @pnewhook wants to contribute this topic then he is more than welcome to do so! My comment was more about not wanting to lean on blog posts for our official docs. Community blog posts are great and we are happy to reference them from our [community feeds](http://www.asp.net/community/spotlight), but we don't want our docs to be a bunch of links to blog posts. Blog posts tend to be point-in-time posts. They are generally not updated. For out docs we want to have content that is stable and authoritative. Our docs should be something that you can reference and trust. So this is really more about expressing a stronger commitment to maintain and update our docs.

**Comment by GuardRex** [comment]
@danroth27 I did misunderstand you ... I thought that "authoritative, updated and persistent" could be equally applied to the reason for denying @pnewhook the opportunity to primary author the Tag Helpers documentation. I have the impression that we (people in the community) shouldn't confuse "contribute" with "primary authorship." It's just an impression; that's all it is.

**Comment by danroth27** [comment]
In general anyone can be the primary author for a proposed topic. We can certainly use the help! But we also want to respect everyone's time and avoid duplicate effort. This was really my bad for not assigning this issue to @DamianEdwards earlier.

**Comment by Rick-Anderson** [comment]
@pnewhook @gusennan @GuardRex Can you guys email me Rick.Anderson@microsoft.com and I'll send you an early draft of my "Intro to TH" doc. I'm looking for feedback.
