### ISSUE TITLE
/publishing/linuxproduction.html "Publish to a Linux Production Environment"

### ISSUE THREAD

**Issue by PedanCN** [aspnet/Docs#1251]
nginx kestrel.sock 502???

**Comment by danroth27** [comment]
The "Publish to a Linux Production Environment" still needs to be updated for RC2.

**Comment by danroth27** [comment]
@PedanCN Could you please clarify exactly what you tried, what you expected and what issue you saw?

**Comment by Rick-Anderson** [comment]
Add #1277

**Comment by spboyer** [comment]
Closing after review, all items addressed and closed.
