### ISSUE TITLE
RC2 updates for Publishing to IIS with Web Deploy using Visual Studio

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1255]
@sayedihashimi can you outline the changes that need to be made for RC2 on [Publishing to IIS with Web Deploy using Visual Studio](https://docs.asp.net/en/latest/publishing/iis-with-msdeploy.html)

**Comment by Rick-Anderson** [comment]
ping @sayedihashimi

**Comment by moozzyk** [comment]
The sections about setting up IIS and configuring data protection should refer to the content in the Publish IIS topic. As it is now the information is duplicated, incomplete and out of date. Keeping both in sync will be probably hard.

**Comment by moozzyk** [comment]
The rest of the document shows what to do "If your hosting provider has support for creating a publish profile" but does not show what to do in the case where my provider does not have support for creating a publish profile.

Also, it's weird that the first 2/3 of the article tells how to setup IIS and then the last section suddenly talks about "a provider that may or may not support creating publish profiles"

**Comment by moozzyk** [comment]
The "Preparing your web server for ASP.NET Core" section says that it is required to install web deploy 3.6 but it is not explained how or where it is used during deployment. In fact it is not mentioned later in the article at all so hard to tell why this step is required and what it gives.
