### ISSUE TITLE
Your First ASP.NET Core Web App Using Visual Studio

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1256]
Phase 1 (to quickly get something published)
-Create new MVC Core app with **OUT** individual user accounts.
- Deploy to Azure
- point to other articles that do more

Phase 2 (RTM bits)
- Create new MVC Core app (again without individual user accounts)
- Scaffold the movie model
- Push to Azure -

**Comment by danroth27** [comment]
It should live here where the old one used to: https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html

**Comment by Rick-Anderson** [comment]
@danroth27 @tdykstra @sayedihashimi  For a simple deploy to azure tutorial, what's the preferred way to deploy? From project creation should I select "Host in the cloud"?
That doesn't seem to let you create a new resource group.

Publishing after also doesn't let me create a new RG.

**Comment by Rick-Anderson** [comment]
@danroth27 @tdykstra @sayedihashimi 
Looks like my Azure SDK is outdated, that's why I can't create a new RG. I'll following https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-get-started/ but deploy a ASP.NET MVC Core app

@danroth27 see my updated outline at the top

**Comment by danroth27** [comment]
My preference is to use the default template with no additional configuration. Why disable authentication? Are there issues with the publishing experience when identity and EF are involved?

**Comment by Rick-Anderson** [comment]
@danroth27 Adding the EF/SQL greatly complicated publishing for what I feel is very little value. It takes far longer to provision and publish with a high probability of a publish error. 

I'm fine with publishing with authen/db.

**Comment by sayedihashimi** [comment]
To publish just create a publish profile, no need to go through Host in the Cloud.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Docs/pull/1266
