### ISSUE TITLE
looking for informations

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Docs#1259]
Hi, after a few test with rc 2 I'm looking on more infos about a few things:

1. I have problems to understand is the **Tools** section of the project.json.
what do they add to the project? commands to the dotnet command?
how can I find informations about them? when I had a new package tool this section is added to the  project.json?
the imports. How can I discover the imports I have to add?
2. Since now a web application is a console app I found a few problems creating a **library with an ef data model**. I opened this issue https://github.com/aspnet/EntityFramework/issues/5425 and I solved, but since it's quite unusual with asp.net to have problems moving code and references from an app to a library, I would like to have more infos if this happens with other libraries.
3. how can I switch an application from .net framework and core back and forth? especially at the beginning, for compatibility reasons with libraries, could happen that I start a project running core and I have to switch to .net framework.
4. how can i compile a library both for core and .net framework? To solve some compatibility issues I can try to move code che use libraries incompatible with .net core in another .fx web app, but if I cannot add to this project a library with, for example, the ef mode I have a big problem. If I try this now to add a library to a .net fc project I receive the message are not compatible.
5. what's happened to the update mechanins of the runtime and stable and unstable feed?

**Comment by danroth27** [comment]
@blackdwarf 

For (1) .NET Core tools are explained here: http://dotnet.github.io/docs/core-concepts/core-sdk/cli/overview.html. We should probably link to this doc when we talk about the tools we ship with ASP.NET Core.

For (2) we are aware of the library limitation with EF Core and we are working to get it fixed.

For (3 through 5) you should refer to the [.NET Core docs](http://dotnet.github.io/docs/porting/index.html). If you don't find the content you need you can file issues on https://github.com/dotnet/core-docs.
