### ISSUE TITLE
System.Net.Primitives.dll Cannot find the file

### ISSUE THREAD

**Issue by DandY30** [aspnet/Docs#1260]
In ApsNetCore RC2 web application i'am having a problem injecting IHttpContextAccessor

I have a class **HttpContextService** which implements **IHttpContextAccessor** and in stratup.cs I added it like this `services.AddTransient<IHttpContextAccessor, HttpContextService>();`

And when I run the project it stoppes without showing errors, so I looked into log and found this: 
**'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc2-3002702\System.Net.Primitives.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.ni.dll
Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.ni.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.dll**

Does someone has same problem or solution to fix it?

**Comment by Rick-Anderson** [comment]
@DandY30 The doc repo is not a support forum. Can you post that question on SO? THanks.
