### ISSUE TITLE
Large parts of documentation are not updated for RC2

### ISSUE THREAD

**Issue by svick** [aspnet/Docs#1261]
It seems a lot of the documentation is stuck in RC1 times and needs to be updated for RC2.

The issues I noticed on a cursory walk through the documentation:

* Lots of references to the old `Microsoft.AspNet` packages and namespaces instead of `Microsoft.AspNetCore`
* Uses of `project.json` features that don't work anymore (e.g. `"commands"` in [Servers](https://docs.asp.net/en/latest/fundamentals/servers.html#project-json-truncated))
* Uses of APIs that were changed (e.g. `WebHostBuilder(IConfiguration)` constructor in [Servers](https://docs.asp.net/en/latest/fundamentals/servers.html#program-cs))
* Incorrect update to `dotnet`: [Unit Testing](https://docs.asp.net/en/latest/testing/unit-testing.html?highlight=dotnet%20watch#dotnet-watch) references the `dotnet watch` command, which doesn't exist

**Comment by Rick-Anderson** [comment]
@svick  actually a lot of it is still beta. We are aware of this and would welcome PR's to help get it updated.

**Comment by danroth27** [comment]
There are two many topics that need to be updated to track it all with one issue. We should open issues for individual topics.
