### ISSUE TITLE
mvc/controllers/filters.html "Filters"

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1267]
- [x] See https://github.com/aspnet/Home/issues/1470. 
- [x] UE edit
- [x] AuthorizationFilterAttribute was removed, and this doc should be updated accordingly, check this issue for more info https://github.com/aspnet/Mvc/issues/4233
- [x]  https://github.com/aspnet/Home/issues/1613

**Comment by Bartmax** [comment]
wanted to ping to this issue: https://github.com/aspnet/Home/issues/1613#issuecomment-229858925

I think it has potentially interesting info.

**Comment by tdykstra** [comment]
Fixed by #2398
