### ISSUE TITLE
View Components

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#127]
ASP.NET MVC -> Views -> View Components

**Comment by tugberkugurlu** [comment]
What is the story on already written blog posts on the topics by the community? Are there any plans to link them relevantly or move the ones that make sense?

For example, I have a post on [View Components](http://www.tugberkugurlu.com/archive/exciting-things-about-asp-net-vnext-series-mvc-view-components). Of course, the community blog posts may not meet the quality bar of the official docs.

**Comment by danroth27** [comment]
We love our community blog posts, but we want this site to have official documentation that we maintain over time. @Rick-Anderson and @MikeWasson have some initial View Component documentation [here](http://www.asp.net/vnext/overview/aspnet-vnext/vc#intro) that I had expected to port over and update. Let us know though if you want take on this topic.
