### ISSUE TITLE
Publish to Azure Web App with VSTS Build CI

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/Docs#1271]
An article to outline Continuous Integration using Visual Studio Team Services with Build and/or Release features. I would see the doc outlining steps potentially being:

1. Get and install `dotnet` on build servers with script from https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1
2. `dotnet restore`
3. `dotnet publish -c Release -o $(build.stagingDirectory)/MyProject`
4. Use powershell to zip contents of published folder
4. Azure web app deployment using "Azure Web App Deployment" VSTS task with 'web deploy pacakge' as path of zipped folder from 3.

This doc could also outline an alternative between steps 3 and 4 to use "Publish Artifacts" and then use VSTS Release to do the release step

**Comment by danroth27** [comment]
Yup, this is something we definitely want to have. Are you offering to write it? :wink:

**Comment by damienpontifex** [comment]
Yes @danroth27 am offering and will get started 😊

Was also checking no one had started work on such content. Plus happy for any feedback on the steps outlined above for writing said content myself.

**Comment by danroth27** [comment]
@sayedihashimi @DarqueWarrior Can you guys take a look at the doc proposal above? Is there existing content already published for ASP.NET Core and VSTS that we can reference?

**Comment by DarqueWarrior** [comment]
I am working on a post. Should be out on DonovanBrown.com this weekend.

**Comment by damienpontifex** [comment]
I have started on a docs article here https://github.com/damienpontifex/Docs/blob/vsts-ci/aspnet/publishing/vsts-continuous-deployment.rst 

Be aware, I have only outlined steps and am looking to refine the article and contents. Looking forward to seeing your article @DarqueWarrior for tips and improvements to my current workflow.

**Comment by DarqueWarrior** [comment]
[DevOps for ASP.NET Core RC2](http://www.donovanbrown.com/post/2016/05/30/DevOps-for-ASPNET-Core-RC2)

**Comment by danroth27** [comment]
@damienpontifex How goes the doc writing? Is this still an article you would like to contribute?

**Comment by damienpontifex** [comment]
@danroth27 yes. Updating now and including the fact that dotnet cli is now included on hosted build servers. Will try and get an initial PR soon
