### ISSUE TITLE
Question: supervisor configuration: where is the bash script located?

### ISSUE THREAD

**Issue by stevo-knievo** [aspnet/Docs#1275]
I followed the [Publish to a Linux Production Environment](https://docs.asp.net/en/latest/publishing/linuxproduction.html) instruction. But I’m struggling with the [supervisor configuration](https://docs.asp.net/en/latest/publishing/linuxproduction.html#configuring-supervisor). I have no idea where the bash file is located. 

`command=bash /var/aspnet/HelloMVC/approot/web`

I use the [ASP cli-samples (HelloMvc)](https://github.com/aspnet/cli-samples/tree/master/HelloMvc) but there is no “/approot/web” included.

Thanks tons!

**Comment by danroth27** [comment]
@shirhatti Can you help out here?

**Comment by shirhatti** [comment]
@stevo-knievo That article is out of date. I'm working on updating it `/var/aspnet/HelloMVC/approot/web` was the shell script generated with the `dnu publish` gesture in RC1.

In RC2, replace that with `command=dotnet ./foo.dll` (where `foo` is the name of your app.

**Comment by branciat** [comment]
@shirhatti 
it would be good to put documentation, which is not the case today. :wink:
