### ISSUE TITLE
Question: Kerstrel on Linux isn't creating unix socket

### ISSUE THREAD

**Issue by stevo-knievo** [aspnet/Docs#1277]
I followed the [Linux Production Environment instruction](https://docs.asp.net/en/latest/publishing/linuxproduction.html#configure-nginx) instruction but the Kerstrel server isn't creating unix socket.

I put the command in the project.json file.

```
"commands": {
    "web": "Microsoft.AspNet.Server.Kestrel --server.urls http://unix:/var/aspnet/HelloMVC/kestrel.sock",
},
```
After I run the following commands the socket file isn't created.

```
dotnet restore
dotnet run

```
Thanks a lot!!

**Comment by stevo-knievo** [comment]
So I figured out how to create the socket...
```

public class Program
{
	public static void Main(string[] args)
	{
		var host = new WebHostBuilder()
			.UseUrls("http://unix:/app/kestrel_test.sock")
			.UseContentRoot(Directory.GetCurrentDirectory())
			.UseIISIntegration()
			.UseStartup<Startup>()
			.Build();

		host.Run();
	}
}
```

Now I would like to know how I could set this via config file maybe like this:

`dontnet ./foo.dll –-lunch.prod.settings.json`


Thanks!!!

**Comment by danroth27** [comment]
@shirhatti
