### ISSUE TITLE
mvc/controllers/areas.rst Areas

### ISSUE THREAD

**Issue by VanKichline** [aspnet/Docs#1284]
Docs / aspnet / mvc / controllers / areas.rst  uses the @Html.ActionLink syntax (old) instead of TagHelpers, which would be more consistent.

**Comment by Rick-Anderson** [comment]
- [ ] Dev review/outline
- [ ] Use TagHelpers, remove @Html.ActionLink
- [ ] Update to RTM

**Comment by Rick-Anderson** [comment]
@kichalla  I updated this in bumped up priority.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas shows both HtmlHelper  and TagHelper syntax
