### ISSUE TITLE
app-secrets tool section and userSecretsId - Secret Manager tool

### ISSUE THREAD

**Issue by christiannagel** [aspnet/Docs#1287]
In https://github.com/aspnet/Docs/blob/master/aspnet/security/app-secrets.rst it would be helpful to add information how the tools section should look like, like:

```
"Microsoft.Extensions.SecretManager.Tools": {
  "version": "1.0.0-preview1-final",
  "imports": "portable-net45+win8+dnxcore50"
},
```

Also, after "Add a userSecretsId for your project in its project.json file:", the code block is missing.

Christian

**Comment by Rick-Anderson** [comment]
@christiannagel  good idea on explaining/showing the tools section. We'd like to do that in a version independent way.

>after "Add a userSecretsId for your project in its project.json file:", the code block is missing.
It's showing up in https://docs.asp.net/en/latest/security/app-secrets.html

![image](https://cloud.githubusercontent.com/assets/3605364/15549856/54cd8892-224a-11e6-9b6d-99edf266bafa.png)

**Comment by christiannagel** [comment]
@Rick-Anderson  defining the tools section in a version independent way, a docu update wouldn't be necessary in the next version :-)
I think the version "1.0.0-preview1-final" could be rewritten with "1.0.0-*", this should work in the next version as well.

**Comment by danroth27** [comment]
Please note that the imports statement will go away in RTM. That was a temporary thing for RC2.

Also, I believe the version wildcard `1.0.0-*` may only work with prerelease versions.

**Comment by Rick-Anderson** [comment]
dup of #1404
