### ISSUE TITLE
Using typescript with aspnet core

### ISSUE THREAD

**Issue by tmds** [aspnet/Docs#1288]
This article is empty: https://docs.asp.net/en/latest/client-side/typescript.html
And the related issue is closed: https://github.com/aspnet/Docs/issues/31

**Comment by danroth27** [comment]
We should just point to https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/ASP.NET%20Core.md.

**Comment by tmds** [comment]
@danroth27 What's strange about that document is that it nowhere has the typescript compiler in the build scripts. Could it be that it relies on VS to compile the typescript to javascript? It is preferable the documentation tackles the topic xplat.

**Comment by danroth27** [comment]
@DanielRosenwasser do you guys have any plans to produce xplat instructions (ex with VSCode instead of VS) for using TypeScript with ASP.NET Core?

**Comment by DanielRosenwasser** [comment]
Our initial motivation for the current documentation was that we saw a lot of demand from users on how to set up TypeScript & ASP.NET with Visual Studio.

My thinking is that the cross platform story is probably simpler to integrate `tsc` into, so we'd probably leverage the existing documentation on your end (i.e. pointing users to it) and then build on that.

Tracking at https://github.com/Microsoft/TypeScript-Handbook/issues/290.

**Comment by Rick-Anderson** [comment]
We have https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.2&tabs=visual-studio
