### ISSUE TITLE
VS Publish doesn't work on RC2 on some configuration

### ISSUE THREAD

**Issue by DeLeneMirouze** [aspnet/Docs#1297]
My default temp publish path has diacritic characters (accents).

This wasn't an issue until RC1, but RC2 throw a publish error and stop

It is possible to solve this issue by adding an explicit PublishOutputPathNoTrailingSlash in the pubxml file
But maybe this shouldn't be an issue as previously!

**Comment by danroth27** [comment]
@sayedihashimi @barrytang @piotrpMSFT Can you guys take a look? Is this potentially a CLI issue?

**Comment by barrytang** [comment]
Adding @vijayrkn and @mlorbetske.

**Comment by vijayrkn** [comment]
This is not a cli issue. This is an issue in the tooling manifest file. Fix is in the publish powershell script.

**Comment by Rick-Anderson** [comment]
@vijayrkn can you post the PS workaround?

**Comment by vijayrkn** [comment]
This is the fix: https://github.com/aspnet/vsweb-publish/pull/62

To get the fix, Copy the latest publish-module.psm1 from https://github.com/aspnet/vsweb-publish/blob/master/publish-module.psm1 to here - C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Publish\Scripts\1.1.0.
