### ISSUE TITLE
Example using AuthorizeAsync is incorrect

### ISSUE THREAD

**Issue by vkichline** [aspnet/Docs#1299]
On Docs / aspnet / security / authorization / views.rst the example code:
`@if` (await AuthorizationService.AuthorizeAsync(User, "PolicyName"))
...is incorrect.  AuthorizeAsync takes three parameters.  The middle one is object resource.  It would be helpful to explain exactly what to supply as the resource.

**Comment by danroth27** [comment]
@blowdart can you help out with some prose for describing what the "resource" is?

**Comment by blowdart** [comment]
The docs are a bit wrong, but this isn't accurate either. The code has moved to an extension class. I have some edits waiting in the office.

**Comment by blowdart** [comment]
This looks like a tooling bug. I can get the extensions to appear just fine with intellisense. Closing as not a doc bug.
