### ISSUE TITLE
mvc/models/validation "Model Validation" 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1304]
- [ ] Show how to disable validation.  
- [ ] #1928 The .NET and MVC semantics for the `[Required]` attribute seem to confuse everyone. See the long thread at aspnet/Mvc#5115 for example.
- [ ] provide code for MergeAttribute 
- [ ] provide sample code
- [ ] DISQUS article very confusing and chaotic! I only managed to get custom validation working by visiting other resources...
- [ ] PM review required, what do we need to add
- [ ] remove  Creating your own custom validation attributes in MVC is easy. 
- [ ] remove all instances of market speak "great feature"
- [ ] remove Just inherit from the ValidationAttribute, and override the IsValid method. The IsValid method accepts two parameters, the first is an object named value and the second is a ValidationContext object named validationContext. Value refers to the actual value from the field that your custom validator is validating.  After the code sample you can explain  the details here.

When using a custom validator - how do you disable validation? See [this DIQUS question ](https://docs.asp.net/en/latest/tutorials/first-mvc-app/validation.html)
How can I disable model validation in ALL the application? I'm using a custom validation framework for this task (Fluent Validator), also the validator is buggy when using [Nodatime](https://github.com/nodatime/nodatime/issues/249)

Add instructions to https://docs.asp.net/en/latest/mvc/models/validation.html

**Comment by AxelMarquez** [comment]
Thanks @Rick-Anderson for creating the issue, I'm the person who asked that DIQUS question.

**Comment by danroth27** [comment]
@dougbu @rynowak @Eilon What's our guidance on this?

**Comment by dougbu** [comment]
Haven't tried it but I suggest placing a `NullObjectModelValidator` in DI, replacing the default `IObjectModelValidator` implementation. Might be something like:
``` c#
public class NullObjectModelValidator : IObjectModelValidator
{
    public void Validate(
        ActionContext actionContext,
        ValidationStateDictionary validationState,
        string prefix,
        object model)
    {
    }
}
```

Alternatively, walk the model tree and mark everything as valid.

**Comment by Rick-Anderson** [comment]
Replaced by #9315
