### ISSUE TITLE
directories for ASP.NET Core module

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1305]
update https://docs.asp.net/en/latest/hosting/directory-structure.html for ANCM
@shirhatti  can you work with @GuardRex  who will be doing the PR? Is this correct

- replace platform handler with ANCM
- remove approot from table - that's an RC1 artifact
- mention you need to create the *logs* directory

Do we need any other changes?

**Comment by GuardRex** [comment]
@shirhatti From my message to @Rick-Anderson ...

I don't have the impression that any particular name has been given to the `approot` folder of DNX/RC1-days other than `content root path` or `application base path`. You certainly don't see it referred to recently as `approot`, except sometimes in terms of Azure Apps. The flat output of publishing is ...

#### Self-contained
```
--- publish
   --- logs (if included in publishOptions)
   --- refs
   --- Views (if included in publishOptions)
   --- wwwroot (if included in publishOptions)
   --- DLL's
   --- myapp.deps.json
   --- myapp.exe
   --- myapp.pdb
   --- myapp.runtimeconfig.json
   --- web.config (if included in publishOptions)
```
#### Portable
```
--- publish
   --- logs (if included in publishOptions)
   --- refs
   --- runtimes
   --- Views (if included in publishOptions)
   --- wwwroot (if included in publishOptions)
   --- DLL's
   --- myapp.deps.json
   --- myapp.dll
   --- myapp.pdb
   --- myapp.runtimeconfig.json
   --- web.config (if included in publishOptions)
```
Azure Apps is a little different in that the published output goes to `%home%\site`, while logs go to `\\?\%home%\LogFiles`. [That's from looking at how @moozzyk has the `publish-iis` tool setup.] I've seen a few devs deploy to `%home%\site\approot` in Azure Apps, but I think they were carrying over DNX/RC1-era naming.

**Comment by shirhatti** [comment]
👍 Looks good to me

**Comment by GuardRex** [comment]
@shirhatti Do you want me to do the PR on it? If so, how do you want the authorship handled? I can take this one over, split with you as 2nd, or take 2nd myself ... whatever works best ... or that's not an issue if you're doing the PR, of course.

**Comment by shirhatti** [comment]
By all means, go for it. You can take this one over 😄

**Comment by GuardRex** [comment]
@shirhatti Ok, great. I'll get on this this afternoon.

**Comment by GuardRex** [comment]
@Rick-Anderson Submit the PR to the `dev` branch then? I thought you might want this one for `master` given that the current doc is very DNX/RC1-ish.

**Comment by GuardRex** [comment]
@shirhatti This one is so short and sweet we can prob knock it out right here for a quick and easy PR. What do you think of this:

In ASP.NET Core, the application directory, *publish*, is comprised of app files, config files, static assets, packages, and the runtime (for self-contained apps). This is unlike previous versions of ASP.NET, where the entire application lived inside the web root directory.
```
+----------------+------------------------------------------------+
| App Type       | Directory Structure                            |
+================+================================================+
| Portable       | - publish*                                     |
|                |   - logs* (if included in publishOptions)      |
|                |   - refs*                                      |
|                |   - runtimes*                                  |
|                |   - Views* (if included in publishOptions)     |
|                |   - wwwroot* (if included in publishOptions)   |
|                |   - .dll files                                 |
|                |   - myapp.deps.json                            |
|                |   - myapp.dll                                  |
|                |   - myapp.pdb                                  |
|                |   - myapp.runtimeconfig.json                   |
|                |   - web.config (if included in publishOptions) |
+----------------+------------------------------------------------+
| Self-contained | - publish*                                     |
|                |   - logs* (if included in publishOptions)      |
|                |   - refs*                                      |
|                |   - Views* (if included in publishOptions)     |
|                |   - wwwroot* (if included in publishOptions)   |
|                |   - .dll files                                 |
|                |   - myapp.deps.json                            |
|                |   - myapp.exe                                  |
|                |   - myapp.pdb                                  |
|                |   - myapp.runtimeconfig.json                   |
|                |   - web.config (if included in publishOptions) |
+----------------+------------------------------------------------+
```
\* Indicates a directory

The contents of the *publish* directory represent the *content root path*, also called the *app base path*, of the deployment. Whatever name is given to the *publish* directory in the deployment, its location serves as the physical path of the hosted assets to the server. The *wwwroot* directory, if present, only contains static assets. The *logs* directory may be included in the deployment by creating it in the project and adding it to **publishOptions** of *project.json* or by physically creating the directory on the server.

**Comment by danroth27** [comment]
@GuardRex This should go into master

**Comment by GuardRex** [comment]
Gotcha. I'll just wait to see what @shirhatti and @Rick-Anderson have to say about that ^^ and have the PR in asap. I know this confuses some devs right now coming into .NET Core, so I'll knock it out asap.

**Comment by danroth27** [comment]
@blowdart @shirhatti The original doc covered the recommended permissions for the various folders in the published output of an ASP.NET Core. We need to update those recommendations based on the new structure of the published output. Can you guys help out with this?

**Comment by blowdart** [comment]
@shirhatti can. I can't.

**Comment by GuardRex** [comment]
I refactored something generally related to permissions: This doc is in "hosting," so I pulled out explicit references to IIS, except for `web.config`, because I felt it was important to leave there. 

The reason I say it's related to permissions is that if this is about a generic directory display for published output that can go to any platform, I felt I didn't know enough about permissions on other platforms to leave anything on permissions in the doc.

My wild guess is: The deployment needs Read/Execute, except for the `logs` folder, which needs Read/Write.

**Comment by shirhatti** [comment]
> My wild guess is: The deployment needs Read/Execute, except for the logs folder, which needs Read/Write

:+1:

**Comment by GuardRex** [comment]
I'll add the following as a new paragraph at the end ...

> The deployment directory requires Read/Execute permissions, while the logs directory requires Read/Write permissions. Additional directories where assets will be written require Read/Write permissions.

**Comment by huangshubin** [comment]
can move all the nuget dlls (the third-part dlls) to one folder named like "vendor" or "packages" and the mvc project can load these dlls from the folder. currently, the nuget pacakges and the prjoject dlls are together and i think it's not well organization.

**Comment by GuardRex** [comment]
@huangshubin This issue addresses the documentation (not the design) of published output directory structure. You should open an issue in https://github.com/dotnet/cli/issues to make your suggestion regarding the directory structure.

**Comment by Rick-Anderson** [comment]
@GuardRex  can I close this now or are there more issues?

**Comment by GuardRex** [comment]
This one is cool :+1:. I'm working on https://github.com/aspnet/Docs/issues/1359 right now, so yeah, this one is good to close.

**Comment by GuardRex** [comment]
Fixed by https://github.com/aspnet/Docs/pull/1328
