### ISSUE TITLE
Remove MinimumLevel from Logging docs

### ISSUE THREAD

**Issue by ciwchris** [aspnet/Docs#1308]
The "Configuring Logging in your Application" section in the [Logging](https://github.com/aspnet/Docs/blob/master/aspnet/fundamentals/logging.rst#configuring-logging-in-your-application) doc states:

> In addition to adding loggers, you can also control the verbosity of the application's logging by setting the MinimumLevel property on the logger factory.

But this property was removed in the issue [Remove ILoggerFactory.MinimumLevel](https://github.com/aspnet/Logging/issues/298) and therefore should be removed.

**Comment by danroth27** [comment]
@ardalis  In PR: https://github.com/aspnet/Docs/pull/1280

**Comment by danroth27** [comment]
Duplicate of https://github.com/aspnet/Docs/issues/908
