### ISSUE TITLE
Example of MemoryConfigurationProvider usage is incorrect

### ISSUE THREAD

**Issue by vkichline** [aspnet/Docs#1309]
Topic Docs > Fundamentals > Configuration contains:
`builder.Add(new MemoryConfigurationProvider());`
 ...which does not compile.
MemoryConfigurationProvider requires a MemoryConfigurationSource parameter (no idea what that would be.)
Perhaps the example should use: builder..AddInMemoryCollection();

**Comment by danroth27** [comment]
In PR: https://github.com/aspnet/Docs/pull/1306
