### ISSUE TITLE
Show "Last updated on <date>" on each doc

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1318]
From @joelbennett on [Slack](https://aspnetcore.slack.com/archives/docs/p1464636947000050) ...

How difficult would it be to display the last updated date for a particular documentation page (on the page itself)?

Reason I ask is that it'd be nice to know if a certain document is up to date.  I had something pop up in Twitter saying that the Application Startup documentation had been updated, but looking at the documentation, I though the startup class had been renamed to just "Program".  Showing a "last updated on ___" date on a page would be kind of a nice thing.  Definitely lower priority than correcting errors in documentation, but something to eventually think about.

**Comment by joelmartinez** [comment]
Unfortunately, the literally last updated date might not be quite as useful ... for example, if an older document got a quick copyedit to fix a misspelling, it would erroneously indicate that the information was more recent than it actually was. 

As much as it sucks, IMO, the last updated date should be an editorially chosen value ... which is to say, when a human author decides that they've made significant edits to a document, they would update the "last updated date" to the current date.

**Comment by joelmartinez** [comment]
![image](https://cloud.githubusercontent.com/assets/90380/15725341/6a80607c-2819-11e6-90d8-f069186b2b92.png)
small disclaimer, though I'm a part of the aspnet org, I don't actively work on this project ... was just sharing my opinion on the topic (I work doc tools for Xamarin :) )

**Comment by JoelBennett** [comment]
That does make sense.  The trick is remembering to update it when updating the documentation.  

From personal experience, it's generally easier to have something automatically updated (even if it is slightly less accurate) rather than relying on having people remember rules that are easily forgotten.  It's the classic computer science saying of "quick or correct, choose one" . :P

If this does end up being one of those things that is a total pain in the butt, feel free to kill it off.

**Comment by innerlee** [comment]
How about have both of them?
* Last updated: by editor, maybe below the title.
* Last edit: automatically, maybe in the footer.

**Comment by JoelBennett** [comment]
That could work.

**Comment by Rick-Anderson** [comment]
We added a warning for doc's that are not current:
![capture](https://cloud.githubusercontent.com/assets/3605364/16403373/512e347e-3ca9-11e6-8d01-8c10c612d350.PNG)

**Comment by JoelBennett** [comment]
Awesome!  That totally works.
