### ISSUE TITLE
Views overview

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1325]
MVC -> Views -> Overview

Targeting RTM

- What are Views
  - Razor files
  - You can think of a View as a template block of HTML with some embedded code that will generate HTML to send to the client
  - Add a note about how view turns into code that renders (without going into the weeds with razor)
  - Razor deeply understands HTML, allowing it to do its thing without much ceremony
- Creating a View
  - Create the file
  - Put it in /Views/ControllerName/ActionName.cshtml
- How do Controllers (Actions) Specify Views?
  - ViewResult
  - View helpers
  - View Discovery (partial view, ViewComponents also have a discovery mechanism, _ViewStart/_ViewImports - these can refer here)
    - Talk about Shared views
    - Call out to Layout, _ViewStart, etc. docs from here
    - View Name Options
       - No name - use action name convention
       - View name, no extension
       - Path to View filename with extension (relative or from app root)
       - Maybe add a note about ViewLocationExpander to customize convention for view location
- How to Pass Data into a View (Replace #132 with this content)
  - Start with passing in model and all the goodness this entails.  
  - ViewData
    Mention ViewData as another, weakly typed option.
  - ViewBag is a dynamic view over the ViewData
  - Maybe a note that if you don't declare @model you can dynamically access properties.

Notes on dynamic view
  - return View(new Person (){ FirstName="Steve" }); // pass in strongly typed model
  - in the view, @Model.FirstName will work, provided FirstName as provided // use dynamic in view; no @model declaration. No compilation error, no intellisense, only runtime failure if property doesn't exist

- Benefits of using Views
  - List features and link off to other docs

**Comment by ardalis** [comment]
I'm going to let #132 cover the intricacies of dynamic views.
