### ISSUE TITLE
AddDataProtection configuration

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#1329]
Missing parts on custom crypto 

From @joeaudette: Need to document alternatives for certificates and custom crypto. Some of the crypto stuff is available as methods but maybe need different params

@blowdart

**Comment by joeaudette** [comment]
the parts  where you see services.ConfigureDataProtection(...) are the things that are not correct

**Comment by timdows** [comment]
So in the new RC2 and RTM version most can be done under services.AddDataProtection().
But I miss the ProtectKeysWithCertificate option.

Is there a solution to use X509Certificate2 with AddDataProtection?

**Comment by timdows** [comment]
Note: Have to admit that I am using NETCoreApp, Version=v1.0
The docs mention that this is not yet available
https://docs.asp.net/en/latest/security/data-protection/implementation/key-encryption-at-rest.html

But if there is a workaround, I would love to use it for the time being

**Comment by Rick-Anderson** [comment]
@joeaudette  Is there a doc this bug should be attached to?

![image](https://user-images.githubusercontent.com/3605364/50663623-5df95d80-0f4e-11e9-8918-10b10c5198ae.png)

>the parts where you see `services.ConfigureDataProtection(...)` are the things that are not correct

Which doc is that in?

What's the ask here? Can this be closed?

**Comment by Rick-Anderson** [comment]
@joeaudette 	Thanks!
