### ISSUE TITLE
Request for documentation on concurrency/threading

### ISSUE THREAD

**Issue by timmydo** [aspnet/Docs#1336]
I was browsing the documentation at https://docs.asp.net/en/latest/ and was wondering if there were plans to add anything on concurrency/thread safety. For example, if I add a service to the DI container with AddSingleton vs AddScoped, when do I need to design a class with thread safety in mind (i.e. worry about multiple threads trying to use the same object at the same time)?

At a high level,

> In general requests are handled by separate threads, so if you have a singleton service it will need to be thread safe. Scoped and Transient services will generally be handled within the context of the request thread, but if you start sharing them across threads yourself then obviously they will need to be thread safe as well.

**Comment by Rick-Anderson** [comment]
from @danroth27 
In general requests are handled by separate threads, so if you have a singleton service it will need to be thread safe. Scoped and Transient services will generally be handled within the context of the request thread, but if you start sharing them across threads yourself then obviously they will need to be thread safe as well.

@halter73 can you outline the guidance here?

**Comment by Rick-Anderson** [comment]
@halter73  wrote:
I agree that whether a scoped or transient service needs to be thread safe depends on your application. It might be worth noting that if a Singleton service has a dependency on a “transient” service, it’s very possible that the transient service will also need to be thread safe depending how it’s used by the singleton.

Unfortunately there aren’t really many hard and fast rules with regard to the thread safety of services. I would go with singletons must be thread safe and it depends for everything else.

**Comment by Rick-Anderson** [comment]
Make it clear what the threading model is for ASP.NET Core.
