### ISSUE TITLE
Confusing formatting of generic types in API reference

### ISSUE THREAD

**Issue by svick** [aspnet/Docs#1337]
In API reference, generic types are formatted in a confusing way. For example, the return type of [`ConfigurationProvider.Data`](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/Extensions/Configuration/ConfigurationProvider/index.html#prop-Microsoft.Extensions.Configuration.ConfigurationProvider.Data) shows as:

> System.Collections.Generic.IDictionary\<System.Collections.Generic.IDictionary`2>{System.String\<System.String>, System.String\<System.String>}

Instead, this should show just like in the code just below:

> IDictionary\<string, string>

Or maybe with namespaces included:

> System.Collections.Generic.IDictionary\<string, string>

**Comment by danroth27** [comment]
I fixed up this specific case manually in the .rst. We will follow up on getting the rst generation logic fixed.

**Comment by danroth27** [comment]
Let us know if you see more instances of this.
