### ISSUE TITLE
request: Git based deployment articles

### ISSUE THREAD

**Issue by villanus** [aspnet/Docs#1343]
Please article git hook based deployment for Linux and Windows virtual machines

**Comment by danroth27** [comment]
Not sure what this is really asking for. We do have some content that shows how to do CI with Kudu on Azure: https://docs.microsoft.com/en-us/aspnet/core/publishing/azure-continuous-deployment

Closing for now, but we can take another look if you can provide more details.

**Comment by villanus** [comment]
Is there a way to do this without azure?

**Comment by danroth27** [comment]
Sure, there are a variety of ways to setup CI for ASP.NET Core. Here's another example of how to do it with VSTS where VSTS pulls your repo, builds and deploys to Azure or wherever you'd like: https://www.visualstudio.com/en-us/docs/build/apps/aspnet/aspnetcore-to-azure.
