### ISSUE TITLE
Need section on unit testing client-side development

### ISSUE THREAD

**Issue by gregveres** [aspnet/Docs#1344]
I found the treatment of unit testing and integration testing as first class citizens in this overall document a welcome refreshing change. However, why isn't there any discussion about unit testing in the Client-side Development section? It is just as important and valid to do unit testing on the client side code (either javascript or typescript) as it is on the server side. Can you please add a sub-section on unit testing? What frameworks (jasmine perhaps) does the .Net team recommend and more importantly, how to setup the VS environment to incorporate the framework and unit testing into the overall process. So far this is a great overall document but this is a glaring hole.

**Comment by ardalis** [comment]
I could see this being included here: https://docs.asp.net/en/latest/client-side/index.html

But otherwise, the reason it's not in the docs is because ASP.NET is a server-side technology and as such doesn't have much to do with how you might implement your client-side functionality (or even what kind of client you might be using - think web APIs and native mobile/desktop clients).

**Comment by gregveres** [comment]
By that logic, then why have a Client-Side development section at all? Why discuss Angular or Knockout or bootstrap? 
I would argue that it is because ASP.Net is a full stack development chain. It creates HTML views using razor, which carry javascript and other client side elements. New full stack web developers could use some assistance in being guided to the best practices of setting up client side unit testing in an ASP.Net Core project, just like was provided for server side unit testing. 

And yes  https://docs.asp.net/en/latest/client-side/index.html is exactly where it should go. I would expect a section under that index page that would talk about setting up unit testing for javascript / typescript.

**Comment by Rick-Anderson** [comment]
This would be great to have but given our limited resources we won't be able to do this. There are a variety of resources on the web on this topic.
