### ISSUE TITLE
fundamentals/app-state.rst "Managing Application State"

### ISSUE THREAD

**Issue by Neurothustra** [aspnet/Docs#1345]
supplying "services.AddCaching()" in Startup.cs requires the use of "using Microsoft.Framework.DependencyInjection;" which causes an ambiguity conflict with "using Microsoft.Extensions.DependencyInjection;"

[https://docs.asp.net/en/latest/fundamentals/app-state.html](url)

**Comment by Rick-Anderson** [comment]
Microsoft.Framework.DependencyInjection was renamed Microsoft.Extensions.DependencyInjection;"
This doc needs to be updated for RC2
see https://docs.asp.net/en/latest/migration/rc1-to-rc2.html

**Comment by Rick-Anderson** [comment]
@blowdart [App State](https://docs.asp.net/en/latest/fundamentals/app-state.html)
states:

Session storage relies on a cookie-based identifier to access data related to a given browser session (a series of requests from a particular browser and machine). You can’t necessarily assume that a session is restricted to a single user, so be careful what kind of information you store in Session. It is a good place to store application state that is specific to a particular session but which doesn’t need to be persisted permanently (or which can be reproduced as needed from a persistent store). 

>You can’t necessarily assume that a session is restricted to a single user,

Should that be:
Session storage is not secure. Do not store secrets in session storage.

**Comment by blowdart** [comment]
Not sure about "is not", "may not" would be more accurate. Storing secrets, well, that depends what you do with them *grin* How about this?

Session storage relies on a cookie-based identifier to access data related to a given browser session (a series of requests from a particular browser and machine). You can’t necessarily assume that a session is restricted to a single user, so be careful what kind of information you store in Session _- you cannot assume it is secure_. It is a good place to store application state that is specific to a particular session but which doesn’t need to be persisted permanently (or which can be reproduced as needed from a persistent store).

**Comment by Rick-Anderson** [comment]
Session storage relies on a cookie-based identifier to access data related to a given browser session (a series of requests from a particular browser and machine). You can’t necessarily assume that a session is restricted to a single user, that is,  you cannot assume it is secure. It is a good place to store application state that is specific to a particular session but which doesn’t need to be persisted permanently (or which can be reproduced as needed from a persistent store).

**Comment by Rick-Anderson** [comment]
moved to #858
