### ISSUE TITLE
Update unit testing to point to https://docs.microsoft.com/en-us/dotnet/articles/core/testing/unit-testing-with-dotnet-test

### ISSUE THREAD

**Issue by JakeRyu** [aspnet/Docs#1346]
I was following the unit test scenario. In  "Configuring the Test project.json" section, the same code appeared twice but the second should be something to do with test runner as described. The second code used to be the command section in RC1 so it should be referred to as test runner accordingly.

In addition, dotnet watch doesn't work. Tooling might be missing. The screen shot should be replaced  with RC2 dotnet, not dnx.

**Comment by ardalis** [comment]
This article hasn't been updated for RC2 yet - it's still RC1. Leaving this issue open to track the need to update the article.

**Comment by JakeRyu** [comment]
The article seemed to be updated on *Update ASP.NET UnitTest section for RC2 changes #1289*. There seemed to be a merging issue though, e.g, the second code in "Configuring the Test project.json" section should be one line code according to the changes on #1289.

That is one thing, screen shots and dotnet watch are still issues.

**Comment by Rick-Anderson** [comment]
Update to point to http://dotnet.github.io/docs/core-concepts/testing/unit-testing-with-dotnet-test.html

**Comment by Rick-Anderson** [comment]
@rachelappel  can you fix this today?

**Comment by Rick-Anderson** [comment]
fixed
