### ISSUE TITLE
Correct headings in Publish to IIS

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1347]
RE: https://docs.asp.net/en/latest/publishing/iis.html

I'm ready to submit a PR to adjust the casing of headings in the doc. Before I do the PR, let's look at them here and see if the proposed replacements look right. Language is not changed ... only the casing.

Current Heading | Proposed Heading
--- | ---
Supported Operating Systems | Supported operating systems
IIS Configuration | IIS configuration
Windows Desktop Operating Systems | Windows desktop operating systems
Windows Server Operating Systems | Windows Server operating systems
Install the .NET Core Windows Server Hosting Bundle | Install the .NET Core Windows Server Hosting bundle
Deploy the Application | Deploy the application
Configure the Website in IIS | Configure the website in IIS
Create a Data Protection Registry Hive | Create a Data Protection Registry Hive
Common Errors | Common errors
Installer Unable to Obtain VC++ Redistributable | Installer unable to obtain VC++ Redistributable
.UseUrls(...) Mispositioned | .UseUrls(...) mispositioned
platform Conflicts with RID | platform conflicts with RID
URI Endpoint Wrong or Stopped Website | URI endpoint wrong or stopped website
CoreWebEngine or W3SVC Server Features Disabled | CoreWebEngine or W3SVC server features disabled
Incorrect Website Physical Path or Application Missing | Incorrect website physical path or application missing
Incorrect Server Role, Module not Installed, or Incorrect Permissions | Incorrect server role, module not installed, or incorrect permissions
Incorrect proecessPath, Bundle not Installed, or Server not Restarted | Incorrect proecessPath, bundle not installed, or server not restarted
Incorrect arguments of <aspNetCore> Element | Incorrect arguments of <aspNetCore> element
Stopped Application Pool | Stopped Application Pool
Additional Resources | Additional resources

**Comment by Rick-Anderson** [comment]
Looks good.

**Comment by GuardRex** [comment]
@Rick-Anderson Ok, cool. I'll get that in later today.
