### ISSUE TITLE
Fundamentals/servers/overview.html "Servers"

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1348]
Replace mention of HTTP Platform Handler with ASP.NET Core Module.
General cleanup.

**Comment by Rick-Anderson** [comment]
- [ ] Update
- [ ] UE edit

**Comment by Rick-Anderson** [comment]
@Bartmax  added that to the asked for list (doesn't mean we will get it without help)

**Comment by rachelappel** [comment]
Moving "sample/instructions for configuring Apache as a proxy server" to new issue. Should go in one of these https://docs.asp.net/en/latest/publishing/index.html
