### ISSUE TITLE
Should we cover MIA .NET Framework version in Publishing to IIS?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1354]
From Brian Mitchard on Disqus comments to [Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html) ...

"In the event viewer, I get the following:
```
Failed to start process with commandline '[My app path here] ', Error Code = '0x80004005'.
```
I turned on logging and here is the error:
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Diagnostics.DiagnosticSourceEventSource' threw an exception. ---> System.MissingMethodException: Method not found: 'Void System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings)'
at EmptyTest.Program.Main(String[] args) in ..\Program.cs:line 21
```
Line 21 in my static void Main for this app is the host.Run() line.
...
When I try an ASP.NET Core (.NET Core) empty web app project, I still get a 502.3 in the browser, and the same error in the event viewer, but here is the error in the log:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(IHostingEnvironment hostingEnvironment, String applicationName, String contentRootPath, WebHostOptions options)
at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildHostingServices()
at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
at EmptyTestCore.Program.Main(String[] args)
```

He reported later ...

**The solution for both the full framework app as well as the core app was that .NET 4.6 was not installed on the target server. Once I installed 4.6, both apps worked.**

Do we need a Common Errors section entry for missing a .NET Framework?

#### Missing .NET Framework version

- **Browser**: 502.3 Bad Gateway: There was a connection error while trying to route the request.
- **Application Log**: Failed to start process with commandline '[IIS_WEBSITE_PHYSICAL_PATH] ', Error Code = '0x80004005'.
- **ASP.NET Core Module Log**: Missing method, file, or assembly exception. The method, file, or assembly specified in the exception is a .NET Framework method, file, or assembly.

Troubleshooting:

Install the .NET Framework version missing from the server.

**Comment by Rick-Anderson** [comment]
covered in #1359
