### ISSUE TITLE
Incorporate content from IIS publishing blog post

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1358]
- [ ] New article focused on Azure websites. Get info from [RUNNING ASP.NET CORE APPLICATIONS WITH IIS AND ANTARES (AZURE WEBSITES)](https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/)

or incorporate into https://docs.asp.net/en/latest/tutorials/publish-to-azure-webapp-using-vs.html

**Comment by Tratcher** [comment]
https://docs.asp.net/en/latest/publishing/iis.html could also include some of these details.

**Comment by GuardRex** [comment]
@Tratcher There are a few nice troubleshooting adds for sure. I'll open an issue and make a list, including talking about the `publish-iis` tooling, which still isn't in that doc. Given that people assume it actually publishes apps to IIS, yeah, it probably should get a few words.

**Comment by guardrex** [comment]
This info is already covered (e.g., the ANCM topic under the Servers node) or info that pertains to the previous release (e.g., *project.json*-era/1.0-era info).

oy @moozzyk (Happy New Year! btw) Would u like me to ping you to TAL at work on https://github.com/aspnet/Docs/issues/5100 as it goes in?

**Comment by moozzyk** [comment]
@guardrex - probably not. I moved on and am not doing ASP.NET on daily basis at the moment.

**Comment by guardrex** [comment]
@moozzyk ok, cool. You will be missed around here!

@Rick-Anderson @scottaddie I think we can close this, since I don't see content changing based on the content of @moozzyk's post given the time that's passed.
