### ISSUE TITLE
Update publishing/iis.html 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1359]
- [ ] Get info from [RUNNING ASP.NET CORE APPLICATIONS WITH IIS AND ANTARES (AZURE WEBSITES)](https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/)

See #1358

**Comment by GuardRex** [comment]
I'll make a list and add a note here about `publish-iis` tooling for review.

**Comment by GuardRex** [comment]
This isn't meant to be an exhaustive list, but here's a list of ideas ...

- Short description of the `web.config` file but that primarily relies upon a link to [ASP.NET Core Module Configuration Reference](https://docs.asp.net/en/latest/hosting/aspnet-core-module.html) to explain the details of configuration.
- Short description of the `publish-iis` tool and `project.json` setup for it.
- Brief description of how to use `app_offline.htm`.
- Remark that Azure Apps have their own doc and link to it early in this doc.
- Add IIS options settings and what they do: `services.Configure<IISOptions>(options => { ... });`
- Additional troubleshooting tips at the top of the Common errors section:
  - Running the app directly to narrow down IIS-module problem versus app problem.
- Additional Common errors to test and list along with the rest
  - dotnet.exe is not on the PATH
  - Confirm that having %LAUNCHER_PATH%/%LAUNCHER_ARGS% placeholders match the currently listed behaviors for bad processPath/arguments, respectfully.
  - and [MIA .NET Framework on the server (Docs/#1354)](https://github.com/aspnet/Docs/issues/1354)

@moozzyk wrt ...

> I read about other failures (https://docs.asp.net/en/latest/publishing/iis.html) but so far have not seen any of them.

Strange remark. If you actually do anything listed, those would be the failure scenarios and actual browser and logging behaviors based on my testing. Besides, you make that statement, then proceed in your list to not state explicitly the causes or the exact errors/behaviors outside of listing (a) no module, (b) no bundle (cli tooling), and (c) bad processPath/arguments ... all of which are covered by the Common errors outlined in the doc.

I guess we have two disagreements: The value of that section and "poor man's logging." :smile:

**Comment by Rick-Anderson** [comment]
> `app_offline.htm`.'

That's described in another doc, we should point to that. Any thing described in another doc (I think a few of them are or should be), we'd want to link. Other than that, looks good.

**Comment by GuardRex** [comment]
I'll go down the list here (in this issue) first and provide a little more detail on which ones should probably get a blurb and where and which ones should be links, like `app_offline.htm`, and where the links might be placed (perhaps `Additional resources` for most/all of them). Once we firm up plans a bit, then I can get a draft PR put together.

**Comment by GuardRex** [comment]
@Rick-Anderson @moozzyk @shirhatti @danroth27 I'm putting the PR together for this today.

There is one add to the list above: A user became confused by one of the screenshots and was trying to find `Basic Settings ...` for the AppPool in the contextual menu of the website (i.e., he was right-clicking on the website trying to set `No Managed Code`. The problem should be solved by an image change. I'd like to go with this one ...

![apppoolsbasicsettingscontextmenu](https://cloud.githubusercontent.com/assets/1622880/16277859/456f795a-387a-11e6-8eb2-198625f3f638.png)

My philosophy will be not to get wordy with anything. The doc is plenty long, so I'll try to get these updates in with short comments and external links to relevant bits.

Given the list I posted earlier, do you see any other changes that should be made or have any comments, tips, etc. before I go to work on it?

**Comment by rsheptolut** [comment]
There is a link to iis-with-msdeploy.rst in this doc, and it's very outdated. I have a problem right now with publishing any new ASP.NET Core app to an existing remote IIS server from Visual Studio and I'm not able to resolve it.

**Comment by GuardRex** [comment]
@rsheptolut I've only read about people using MSDeploy. I use my own PowerShell approach to publishing shown at https://github.com/GuardRex/aspnetcore-iis-ps-publish.

> I have a problem right now with publishing any new ASP.NET Core app to an existing remote IIS server from Visual Studio

You might be able to find help or open an issue in https://github.com/aspnet/vsweb-publish/issues.

@Rick-Anderson It looks like the `iis-with-msdeploy.html` one didn't get the ":version: 1.0.0-rc2" note. If you want me to add it, I can pop it on there.

**Comment by Rick-Anderson** [comment]
@GuardRex  can I close this?

**Comment by GuardRex** [comment]
@Rick-Anderson Yes, I think so.
