### ISSUE TITLE
Fundamentals and "Introduction to ASP.NET Core" cleanup

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1367]
- [ ] Explain ""Built on .NET Core, which supports true side-by-side app versioning".

The hosting doc will go into detail on content root and web root. Point to them for details.

per @danroth27 
By default the content root will be the location where your app dll is loaded from, which ~~during development~~ [edit insert] { in test/production}  is the bin directory. The content directory is used to determine the location of things like your views and your web root ( _wwwroot_  folder). However, during development your views and web root are not in the bin folder. They are a couple of directories up where your project is located. To fix that we setup the project to use the current directory where you are running “dotnet myapp.dll” from, which is during development is typically the root directory of your project.

Can you reword "To fix that setup"? Should it be something like "To set the content root for development"? 

Seems like it's much simpler to define content root as the parent of web root ( _wwwroot_ )

~~It is based on a set of granular and well factored NuGet packages.This allows you to optimize your app to include just the NuGet packages you need.~~ replace with something like

It is based on a set of well factored NuGet packages, you include only the packages you need.

The following is fixed
The content root is the base path to any content used by the app, such as its views and web content. By default the content root is the same as application base path for the executable hosting the app; an alternative location can be specified with WebHostBuilder.

What does web content mean?  @danroth27  asks fowler " how to describe the content root for an ASP.NET Core app?" Fowler responds:
- Any non code files that need to be read from the project. Config files, data files (like a database file), etc. it's also the base path for the webroot folder 

-- end of fixed

**Comment by Rick-Anderson** [comment]
@Tratcher  how do you change _web root_ ? I've done the following in a template generated web app.

added ``UseWebRoot("./MyWebRoot")``

```
public static void Main(string[] args)
{
    var host = new WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseIISIntegration()
        .UseStartup<Startup>()
        .UseWebRoot("./MyWebRoot")
        .Build();

    host.Run();
}
```
Update _gulpfile.js_  
```
var webroot = "./MyWebRoot/";
```

But visual studio won't let me change the magic directory _wwwroot_

**Comment by Tratcher** [comment]
@BillHiebert ?

**Comment by TravisBoatman** [comment]
@Rick-Anderson Create a 'hosting.json' file in the root directory and add - 

`{
  "webroot": "MyWebRoot"
}`

**Comment by Tratcher** [comment]
@TravisBoatman There is no longer a default hosting config file (though you may add a custom one in Main).

**Comment by Rick-Anderson** [comment]
MOved to #10559
