### ISSUE TITLE
Method overloads don't have ids and thus can't be linked to

### ISSUE THREAD

**Issue by svick** [aspnet/Docs#1372]
When a method has multiple overloads, only the first one gets an id, the following ones don't. This means that it's impossible to link to a specific overload, unless it's the first one.

An example of this is [`HttpRequestMessageExtensions.CreateErrorResponse()`](https://docs.asp.net/projects/api/en/latest/autoapi/System/Net/Http/HttpRequestMessageExtensions/index.html#meth-System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse).

The HTML for the first overload (`CreateErrorResponse(HttpRequestMessage, InvalidByteRangeException`) starts like this:

```html
<dl class="method">
<dt id="meth-System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse">
<code class="descname">CreateErrorResponse</code><span class="sig-paren">(</span><em>System.Net.Http.HttpRequestMessage</em>, <em>System.Net.Http.InvalidByteRangeException</em><span class="sig-paren">)</span><a class="headerlink" href="#meth-System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse" title="Permalink to this definition">¶</a></dt>
```

This means that I can link to it as https://docs.asp.net/projects/api/en/latest/autoapi/System/Net/Http/HttpRequestMessageExtensions/index.html#meth-System.Net.Http.HttpRequestMessageExtensions.CreateErrorResponse (and there's even a helpful link icon for this).

But for the second overload (`CreateErrorResponse(HttpRequestMessage, HttpStatusCode, ModelStateDictionary)`) the HTML is:

```html
<dl class="method">
<dt>
<code class="descname">CreateErrorResponse</code><span class="sig-paren">(</span><em>System.Net.Http.HttpRequestMessage</em>, <em>System.Net.HttpStatusCode</em>, <em>Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary</em><span class="sig-paren">)</span></dt>
```

Notice that there is no `id` on the `<dt>` element, so it's not possible to link to it.

If the issue is generating unique ids, a solution might be adopt the approach of .Net Core docs, where method parameters are always included in the id. For example, the link to `Convert.ToBoolean(Boolean)` is https://dotnet.github.io/api/System.Convert.html#System_Convert_ToBoolean_System_Boolean_, while the link to `Convert.ToBoolean(Byte)` is https://dotnet.github.io/api/System.Convert.html#System_Convert_ToBoolean_System_Byte_.

**Comment by danroth27** [comment]
This will be fixed when we move to docfx.
