### ISSUE TITLE
Some tags in XML documentation generate raw HTML tags in API reference

### ISSUE THREAD

**Issue by svick** [aspnet/Docs#1373]
It seems that when XML documentation contains some specific tags, the generated HTML contains visible HTML tags. For example, this happens on [`HttpRequestMessageExtensions.CreateResponse`](https://docs.asp.net/projects/api/en/latest/autoapi/System/Net/Http/HttpRequestMessageExtensions/index.html#meth-System.Net.Http.HttpRequestMessageExtensions.CreateResponse%3CT%3E):

[The XML documentation](https://github.com/aspnet/Mvc/blob/b5a6303/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/HttpRequestMessage/HttpRequestMessageExtensions.cs#L251-L254) contains `<c>` and `<paramref>`:

```c#
/// <param name="value">The value to wrap. Can be <c>null</c>.</param>
/// <returns>
/// A response wrapping <paramref name="value"/> with <see cref="System.Net.HttpStatusCode.OK"/> status code.
/// </returns>
```

It generates this RST, with `<code>` and `<em>`

```rst
:param value: The value to wrap. Can be <code>null</code>.
        
:type value: T
:rtype: System.Net.Http.HttpResponseMessage
:return: A response wrapping <em>value</em> with <em>statusCode</em>.
```

Which generates this HTML, with `&lt;code&gt;` and `&lt;em&gt;`:

```html
<li><strong>value</strong> (<em><span>T</span></em>) &#8211; The value to wrap. Can be &lt;code&gt;null&lt;/code&gt;.</li>
[snip]
<tr class="field-odd field"><th class="field-name">Returns:</th><td class="field-body"><p class="first last">A response wrapping &lt;em&gt;value&lt;/em&gt; with &lt;em&gt;statusCode&lt;/em&gt;.</p>
```

Which renders as:

![](http://i.imgur.com/Tst3M6o.png)

It's possible this issue applies to other XML tags, not just `<paramref>` and `<c>`.

**Comment by danroth27** [comment]
This will be fixed when we move to docfx.
