### ISSUE TITLE
The "dotnet run" is not working as expected.

### ISSUE THREAD

**Issue by PeterBocan** [aspnet/Docs#1375]
Command ```dotnet run``` does not launch the webserver.
https://docs.asp.net/en/latest/getting-started.html

**Comment by davidfowl** [comment]
No it does not launch the webserver, it launches your `Program.Main`. This is by design.

**Comment by PeterBocan** [comment]
I got it. Somehow it did not started the website, because ```UseStartup<T>()``` could not resolve the class so it looked like it silently ended.
