### ISSUE TITLE
Add minimal xplat getting started with MVC tutorial 

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1378]
We need to have a minimal getting started with MVC tutorial that covers without tooling:
- Adding the Microsoft.AspNetCore.Mvc package
- Calling services.AddMvc() and app.UseMvc()
- Create a HomeController that returns a simple view with a model

**Comment by Rick-Anderson** [comment]
@danroth27 should that be targeted to non- Visual Studio environments? Do you want to assume an environment?

**Comment by danroth27** [comment]
Yup, non-VS. This should be like https://docs.asp.net/en/latest/getting-started.html but for MVC.

**Comment by Rick-Anderson** [comment]
@danroth27 https://docs.asp.net/en/latest/getting-started.html  doesn't provide any help for OSX users. Don't we want a version like https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html ?

**Comment by danroth27** [comment]
My point was https://docs.asp.net/en/latest/getting-started.html is completely independent of your OS. Those same steps work for Windows/Mac/Linux.

For this simple MVC tutorial I'm fine showing VS Code like we do in https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html, if that's what you mean. VS Code is xplat.

**Comment by Rick-Anderson** [comment]
Looks like @spboyer put in a bunch of very helpful OSX specific instructions - which might confuse those on other platforms. For example

> can be removed automatically by using ``⌘ .`` when the lightbulb icon appears. Classes and methods also display how many references there are in the project to them. If you're coming from Visual Studio, Code includes many of the same keyboard shortcuts, such as ``⌘KC`` to comment a block of code, and ``⌘KU`` to uncomment.

I'll use that as a template. Should I include OSX help? Should I set up a Linux  VM and include Linux  help? Or can I do the first pass with an OSX bias then add in Linux? Maybe I could take Linux  and @tdykstra  could do Linux?

**Comment by danroth27** [comment]
I think we want to keep this as generic as possible. These steps for this simple tutorial should be virtually identical regardless of platform. Let's not write different versions for Windows, Mac and Linux.

**Comment by spboyer** [comment]
That contradicts some of the issues currently on the list for OSX, Linux/Ubuntu specific walkthroughs.  There needs to be a clean way to present platform specific keystrokes, files (*.sh) etc. instead of having to write multiple articles for each platform. Becomes repetitive. MSDN had tabs for language choice or versions, azure.com has something similar.

**Comment by Rick-Anderson** [comment]
>Let's not write different versions for Windows, Mac and Linux.

You mean Let's not write different versions for ~~Windows,~~ Mac and Linux.

We will always have Windows/VS specific versions.

I'll write it platform agnostic and we can see what questions we get.

**Comment by tdykstra** [comment]
@BillWagner how are we handling the need for different platform versions of the same tutorial in the .NET Core docs?

**Comment by danroth27** [comment]
@spboyer I was referring to just this tutorial. We are of course ok to have platform specific tutorials. But this tutorial I wanted to be generic.

**Comment by BillWagner** [comment]
The default answer we've taken for samples in core is to have each topic concentrate on a platform. The feedback is that readers want to read about their environment, not all environments.

Sadly, this does mean some duplication of effort, as the platform doesn't support reuse for that yet. (It has been requested).

@danroth27 what is the benefit for readers to have a single generic tutorial? Do you want to show how a team might work if some developers are on different platforms?

**Comment by danroth27** [comment]
@BillWagner The idea was that this tutorial would be so simple and the steps so generic that you really don't need platform specific versions. Pretty much all of the steps are the same regardless of what platform you are on. I.e. add the MVC package, add the MVC services, add the MVC middleware and some routes, create a controller, add a view and maybe a layout page, done. Just the minimal steps needed to get started with MVC regardless of the platform or editor that you are using.

**Comment by danroth27** [comment]
`dotnet new mvc` is your friend

**Comment by danroth27** [comment]
And we already show using `dotnet new mvc` in the https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet doc.
