### ISSUE TITLE
Working with the Application Model

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#138]
ASP.NET MVC -> Controllers-> Working with the Application Model

Application Model lives here:
https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.Core/ApplicationModels

Conventions can be applied as attributes.
Example: https://github.com/aspnet/Mvc/tree/dev/test/WebSites/ApplicationModelWebSite/Controllers

Attributes applied to a base type will allow child types to inherit these attribute-applied conventions.

Application Model Sample:
https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention 

Example: WebAPICompatShim modifies assumptions made in MVC Core to match Web API 2 conventions, for instance.
https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim

**Comment by rynowak** [comment]
A good idea for a sample https://github.com/aspnet/Home/issues/1613

**Comment by danroth27** [comment]
Application model is a representation of your MVC app that you can read and manipulate
- Controller names, action names, action parameters, attribute routes, filters
Modify the application model with custom conventions
- Ex Web API compat shim
Explore your app
- Ex. Swagger
