### ISSUE TITLE
tutorials/first-web-api "Building Your First Web API"

### ISSUE THREAD

**Issue by h82258652** [aspnet/Docs#1380]
- [x] Decorate public IEnumerable<TodoItem> GetAll()   with    [HttpGet] so it works with Swagger 
- [ ] Use token generated named route - Token replacement also applies to route names defined by attribute routes. [Route("[controller]/[action]", Name="[controller]_[action]")] will generate a unique route name for each action.
- [x] link to MVC routing doc
- [x]  Use in-memory provider and int ID's. That makes it much easier to hack the URLs for testing.
- [ ]  Add [JSON Patch](https://tools.ietf.org/html/rfc6902)
- [ ]   Jsonp (Json with Padding): mention JSONP is a workaround for sending simple cross origin requests. We don’t have support for JSONP built-in – we recommend CORS instead.

**Comment by Rick-Anderson** [comment]
@MikeWasson  please review

**Comment by Rick-Anderson** [comment]
- [ ] replace TryGetValue
- [ ]  #1461

**Comment by Rick-Anderson** [comment]
Closing to work on higher priority items.
