### ISSUE TITLE
Configuration: Document format supported for command line arguments provider

### ISSUE THREAD

**Issue by divega** [aspnet/Docs#1382]
Originally mentioned in https://github.com/aspnet/Configuration/issues/120:

> ... it is not obvious, without looking at the code, how are they supposed to be used.
> 
> For example, is I have:
> 
> ``` C#
> Configuration config = new Configuration();
> config.AddCommandLine(args);
> ```
> 
> What is the format accepted by the strings in "args" to be valid? There are many possible options: `/key value`, `--key value`, `--key:value`, `key=value`, etc.

For some initial context, by default the command line arguments provider supports converting arguments of the format `key1=value1 key2=value2 key3=value3` Additional syntax with `-key1 value1`, `--key2 value2` and `/key3 value3` are supported when providing switch mappings.

**Comment by steveoh** [comment]
can we get a list of the ones supported by the platform. Should I be able to change the port kestrel runs on with a command line arg?

**Comment by spboyer** [comment]
The implementation of the CommandLine arguments are for settings similar to the Configuration providers that exist for INI,JSON, and XML files.  The difference here is the setting are passed in at start of the application conversely the files are used in the Startup.cs class.

### Using a file
```
public Startup(IHostingEnvironment env)
{
	var builder = new ConfigurationBuilder()
		.SetBasePath(env.ContentRootPath)
		.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
		.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
		.AddEnvironmentVariables();
	Configuration = builder.Build();
}
```

### Using command line provider

```
dotnet run --Key2=Value2 /Key3=Value3 -Key1=Value1

# in Startup.cs
public Startup(IHostingEnvironment env)
{
	var builder = new ConfigurationBuilder()
		.SetBasePath(env.ContentRootPath)
		.AddCommandLine(args);
	Configuration = builder.Build();
}
```

The port(s) that kestrel runs on are now configured using the `.UseUrls(string[])` method of WebHostBuilder

```
public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseUrls(["http://*:5001","http://*:5002"])
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

**Comment by spboyer** [comment]
@Rick-Anderson @danroth27 ^^

**Comment by danroth27** [comment]
@Rick-Anderson The ask here is to cover what syntaxes are supported by the command-line provider. We kinda cover this here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration#commandline-configuration-provider. However, the behavior isn't clearly specified. Instead you have to figure it out from the example. When I read this section I still felt like I needed to go read the code for the provider to understand exactly what it does. In general I think we should adopt a documentation pattern of declaratively specifying the behavior and *then* provide an example.
