### ISSUE TITLE
Writing Custom Formatters

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#139]
ASP.NET MVC -> Models -> Writing Custom Formatters

**Comment by LRPalacios** [comment]
any updates on draft for this? i am currently trying to write a text/javascript formatter some docs will be helpful

**Comment by danroth27** [comment]
Not yet - still on the backlog.

**Comment by Rick-Anderson** [comment]
@danroth27  can we get an outline of what you want? I'm looking for a community contribution for this. What are the top use cases? I'm guessing  text/javascript formatter would be a good example.

**Comment by Rick-Anderson** [comment]
@danroth27  we really need some guidance ASAP
from @fiyazbinhasan
I managed to write some custom formatters. It was tough cause already all of them are pretty much written by other community members :P. Anyways I wrote a YAML formatter (Input/Output Formatters), Pdf formatter (Output), Xls Formatter (Output). Here is [the link to the git repo](https://github.com/fiyazbinhasan/NET-Core-Custom-Formatters) where you can find them,

I'll write a blog soon. Will keep you notifying. Meanwhile please do check the repo and let me know if I missed anything.

@fiyazbinhasan : Can you write a ReadMe.MD explaining how to build/use the formatters?

@tdykstra  has first dibs as co-author, I'm 2nd in line. cc/ @spboyer

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson readme.md file added :)

**Comment by tdykstra** [comment]
Proposed outline for the doc

* When to use:
  * There is a particular content type you want to enable that 
    a. isn't supported OOB (i.e., not JSON, XML, or plain text) and 
    b. You want to enable it in a way that integrates with content negotiation
  * Example use cases
    * Google Protobuf is a binary format that is more efficient than text types.
    * vCard is a text format commonly used for exchanging contact data.  The sample app will implement a simple vCard formatter.

* How to create a custom formatter class
  * For text media types (e.g., vcard, json, xml), derive from TextInputFormatter or TextOutputFormatter base class
    * Otherwise, derive from InputFormatter or OutputFormatter base class
  * Note that you can't do constructor DI in a formatter; to access services you need to use the context object that gets passed in to your methods.
  * In the constructor specify valid media types and encodings  
    * Add to SupportedMediaTypes collection (e.g., application/vCard)
    * Add to SupportedEncodings collection 
  * Override CanReadType/CanWriteType to specify the type you can deserialize into/serialize from (e.g., Contact type for vCard)
    * Note about output formatters:  use CanWriteType for design time type, use CanWriteResult for runtime type
  * Override ReadRequestBodyAsync/WriteResponseBodyAsync to do the actual work of deserializing/serializing

* How to configure MVC to use a custom formatter 
  * Add the formatter to MvcOptions InputFormatters and/or OutputFormatters collections

**Comment by danroth27** [comment]
@kichalla Please take a look at the proposed outline. Does the flow seem reasonable? Anything missing?

**Comment by kichalla** [comment]
Looks good to me.

**Comment by tdykstra** [comment]
Fixed by #2743
