### ISSUE TITLE
Update URLs in sample code to reference latest docs

### ISSUE THREAD

**Issue by dougbu** [aspnet/Docs#1390]
A few samples contain `fwlink` links to very old documentation. Not sure whether we need `fwlink` at all. But definitely don't want to plunge user into the old docs if they follow a link from the latest sample.

Example:
1. https://docs.asp.net/en/latest/fundamentals/configuration.html#using-the-built-in-sources
2. Scroll down to code comment that starts w/ "For more details"
3. Select the `fwlink` URL (http://go.microsoft.com/fwlink/?LinkID=532709)
4. Paste into the browser

Expected: Get to https://docs.asp.net/en/latest/security/app-secrets.html right quick
Actual: Sent to https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration -- an old DNX-related page that (fortunately) contains a link to https://docs.asp.net/en/latest/security/app-secrets.html

**Comment by Rick-Anderson** [comment]
Maybe a stale fwlink? I fixed this a month ago I think. It's working now.
