### ISSUE TITLE
fundamentals/error-handling.html "Error Handling"

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#1397]
Looking at https://docs.asp.net/en/latest/fundamentals/error-handling.html

If you click on one of the HEADINGS - they all have fragment names like `#id1` instead of `#configuring-an-exception-handling-page`. The TOC for the page has good names, but the headings of the sections do not.

**Comment by Rick-Anderson** [comment]
- [ ] DISQUS questions (see one below)
- [ ] Headings
- [ ] Best practices
- [ ] Dev review
- [ ] UE review

I have bunch of controller that initiates Async calls, that performs background task. What are my options if I want to have a global exception handler which will catch the failures happening in these task.
Any advise how this can be done.

if the i workflow with the **client** is async:
1.	Don’t use `async void`.
2.	More generally, `await` all `async` calls.
3.	Write the `IExceptionFilter` / `IAsyncExceptionFilter` implementation however you like.

If the client waiting for a response while the processing takes place. - we don’t have a recipe for this just yet.

**Comment by Rick-Anderson** [comment]
If the background task is expected to live longer than the request that initiated it I would suggest having a singleton service that schedules/tracks jobs and provide with each new Job a polling URL that the client can query to check on the status of the task and send back to the client any error that happened during the execution. I strongly discourage using exception filters for this. I would build an abstraction that captures any exception on the job and converts it into an error data structure that can be sent back to the client in the next polling request.

In general building infrastructure to execute tasks in the background is way more complicated than what I explained here, but this + what Ryan/Doug said is spot on. Other things to consider are:
1)	Orphaned jobs (client sends request but never polls for the result)
2)	Rate limiting (how  many concurrent jobs can be running at the same time without taking down the system, how many jobs a given user can run in a given amount of time, etc.).

**Comment by Rick-Anderson** [comment]
Pranav K
It might be worthwhile determining how much of something like WebBackgrounder (https://github.com/NuGet/WebBackgrounder) is portable to Asp.NetCore. It’s pretty useful to do house cleaning work which isn’t required to be entirely reliable, but it does setup and teardown of jobs and synchronization across a farm. I imagine it’s a lot saner
