### ISSUE TITLE
Discussion of ModelState in error handling doc is out of place

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#1398]
This section: https://docs.asp.net/en/latest/fundamentals/error-handling.html#handling-model-state-errors doesn't have much in common with the topics discussed elsewhere in the document. 

I wouldn't come to this doc to try and find information about validation - which is a topic that all MVC actions taking user-input need to deal with.

**Comment by ardalis** [comment]
It's also covered in detail here: https://docs.asp.net/en/latest/mvc/models/validation.html. It's worth a mention, IMO, in Error Handling, but can pretty much link to the validation article for details.

**Comment by Rick-Anderson** [comment]
@rachelappel  can you make sure this gets fixed for RTM as part of your model binding work?

**Comment by rachelappel** [comment]
38bf6953d7510e83f39ea46973cb2cb34bc5b696
