### ISSUE TITLE
Author section is unnecessary 

### ISSUE THREAD

**Issue by blowdart** [aspnet/Docs#140]
Given the open source nature of the docs system if everyone who contributes to an article ends up in the author section it's going to be bigger than some actual articles. It also becomes out of date extremely quickly.

It ought to just go away.

**Comment by tugberkugurlu** [comment]
Would be cool to automaticay list contributers, who contributed to that page, at the bottom of the article.

**Comment by blowdart** [comment]
That's fine. Photos and/or bios would just get too big.

**Comment by MikeWasson** [comment]
I think the author section is for the primary author(s), not every contributor who submits a PR (which will be in the history). Listing authors has been important on the asp.net site, for building author reputations and giving credit to MVPs or others who contribute to the docs.

**Comment by ardalis** [comment]
Ditto @MikeWasson. They just need to be kept under control (like they are now and on the asp.net site).

**Comment by MatthewBonner** [comment]
Says the person advertising his company...
