### ISSUE TITLE
Remove unnecessary `imports` from `project.json` samples and snippets

### ISSUE THREAD

**Issue by dougbu** [aspnet/Docs#1403]
The current documentation contains `imports` for the RC2 / Preview 1 tools. Most can be removed for 1.0.0 / Preview 2.

For example https://docs.asp.net/en/latest/security/app-secrets.html#installing-the-secret-manager-tool implies "Microsoft.AspNetCore.Razor.Tools" and "Microsoft.Extensions.SecretManager.Tools" require `imports` properties. Neither does anymore.

See also aspnet/Templates#613

{EDIT}

- [ ] Remove `imports` properties from security/app-secrets.rst
- [ ] Remove from other documents (unidentified at this point) - don't close this issue until we identify/fix all docs.

**Comment by rachelappel** [comment]
d1fe67b7f92ca8471971da79eac81c0c49515323
