### ISSUE TITLE
 aspnet/security/app-secrets.rst "Safe storage of app secrets during development"

### ISSUE THREAD

**Issue by dougbu** [aspnet/Docs#1404]
- [ ] Add link to secrets on production.
- [ ]  #1287 doc tools

The [Safe storage of app secrets with the Secret Manager tool](https://docs.asp.net/en/latest/security/app-secrets.html) page is about storing secrets while developing a site. However it contains no recommendations or links to recommendations for what to do in production.

**Comment by Rick-Anderson** [comment]
We changed the title to **Sate storage of secrets during development**.

**Comment by dougbu** [comment]
@Rick-Anderson why does that lead to closing this issue? Where is the information about safely storing secrets in production?

**Comment by Rick-Anderson** [comment]
@dougbu  I agree. @danroth27  asked me to close it. I'll keep it open until we provide a link to guidance. I can't stop @danroth27  from closing it.

**Comment by danroth27** [comment]
This can stay open. We will look at providing more concrete guidance on handling of secrets in production post 1.0.0.

**Comment by Rick-Anderson** [comment]
>We will look at providing more concrete guidance on handling of secrets in production post 1.0.0.
@danroth27  Who's the contact for this?

**Comment by danroth27** [comment]
We now have an Azure Key Vault config provider. @glennc is probably the right contact for that.
