### ISSUE TITLE
Improvements and updates to Identity docs

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/Docs#1405]
**Things that are out of date**

- [x]  Doc at https://docs.asp.net/en/latest/security/authentication/accconfirm.html contains out-of-date code snippet (e.g., `RedirectToAction` should be `RedirectToLocal`, and the `EnsureDatabaseCreated()` should be removed). Generally, all the code blocks in this page should be updated to match the final templates.
- [x] The screenshot of VS under "Enable SSL in Visual Studio" on https://docs.asp.net/en/latest/security/authentication/accconfirm.html is out of date - doesn't match current tooling and refers to version 1.0.0-beta7 and the ASPNET_ENV variable.
- [x] Doc at https://docs.asp.net/en/latest/security/authentication/2fa.html contains code blocks that don't match latest template (e.g., it has a link to the `RemovePhoneNumber` action, whereas the shipping template uses a `<form>` that does a POST)

- [ ] **Improvement to "account lockout" docs**
Regarding https://docs.asp.net/en/latest/security/authentication/2fa.html, we should mention that, to enable it, you also need to modify your `Login` action to pass `lockoutOnFailure: true`. Currently there's no mention of that, and it's not easy to discover.

- [ ] **Improvement to "account confirmation" docs**
We need to address the point about enabling account confirmation for existing sites that already have users. That (clearly important) scenario isn't mentioned at all, and there's a major gotcha: by enabling account confirmation, you are locking out all your existing users, because their accounts are not confirmed. To work around this, you either need to edit your DB to mark all existing users as being confirmed, or you need to confirm them somehow (batch-send emails with confirmation links, or similar).

**Comment by Rick-Anderson** [comment]
>user-secret set SendGridUser RickAndMSFT
that's now ``dotnet user-secrets set``
