### ISSUE TITLE
Show How To Format JSON Responses using Pascal Case in Formatting doc

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#1406]
This section was removed since camel casing is now the default JSON formatting.

Configuring the JSON Formatter
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

A common request when formatting responses using JSON is to use JavaScript-style "camel" casing (the first character of each property is lowercase, then uppercase is used to begin each additional word making up the name). Support for camel casing can be added by using the ``AddJsonOptions`` extension method when configuring MVC:

.. code-block:: c#

  services.AddMvc()
    .AddJsonOptions(o =>
      o.SerializerSettings.ContractResolver = 
        new CamelCasePropertyNamesContractResolver());

Replace the default ``SerializerSettings.ContractResolver`` with a new instance of ``CamelCasePropertyNamesContractResolver``. Before this change, an object with a property of "FirstName" and a value of "Steve" would be serialized to JSON as ``{"FirstName":"Steve"}``; after the change to use camel case, it would serialize as ``{"firstName":"Steve"}``.

Consider updating the article for RTM to show how to format the JSON as PascalCase rather than camelCase.

**Comment by lucamorelli** [comment]
cold be added a specific doc listing ths kind of breaking changes between aspnet and core? could be of use migrating existing asp.net apps

**Comment by kashave** [comment]
Hi
use the following code

var jsonFormatter = config.Formatters.OfType<JsonMediaTypeFormatter>().First();
            //jsonFormatter.SerializerSettings.ContractResolver = new //CamelCasePropertyNamesContractResolver();
