### ISSUE TITLE
Document sql-cache tool

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1412]
Add to https://docs.asp.net/en/latest/performance/caching/distributed.html#using-a-sql-server-distributed-cache

**Comment by cesarbs** [comment]
This can be closed, right?

**Comment by Rick-Anderson** [comment]
Yes, altho the csproj version is [here](https://review.docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?branch=csproj)
