### ISSUE TITLE
Remove Diagnostics article

### ISSUE THREAD

**Issue by shanselman** [aspnet/Docs#1419]
https://docs.asp.net/en/latest/fundamentals/diagnostics.html#the-developer-error-page 

- [ ] Consider retiring this doc or making it into a content map. I'd be unhappy if I came here looking for diagnostics.
- [ ]  Remove glimpse link
- [ ]  The welcome page is not a diagnostic
- [ ]  Delete logging into and just list the link

**Comment by Rick-Anderson** [comment]
@danroth27  can we just delete this page? It doesn't have anything useful on it.

**Comment by danroth27** [comment]
Yeah, let's remove it.

**Comment by danroth27** [comment]
Yeah, let's remove it

**Comment by Rick-Anderson** [comment]
fixed by removing
