### ISSUE TITLE
Add info about case sensitivity of view look up

### ISSUE THREAD

**Issue by kichalla** [aspnet/Docs#1423]
I think it would be good to have a small section explaining the case-sensitivity of view search (mainly for non-windows platforms)

The current behavior is this:

User types in the URL and case could be anything => we try to do a case-Insensitive mapping from the input names (ex: controller and action names) to C# type and method names and use these C# type and method names to do a case-sensitive search of views.

So names of types, method names and area names must be case-sensitive equal with the files/folders on the machine. 

@pranavkm

**Comment by danroth27** [comment]
@ardalis This should get covered in the view discovery section of the views overview doc (#1325)
