### ISSUE TITLE
update migration/mvc.rst to RTM

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1424]
[Migrating From ASP.NET MVC to ASP.NET Core MVC](https://docs.asp.net/en/latest/migration/mvc.html) shouldn't need much work. On rewrite:

- [x] Just tell them what needs to be added to *project.json*, don't include the literal with version numbers. That way the doc won't be obsolete on the next release.

- [x]  on the remaining .json files, add a note:these version numbers might not be current, use the current version numbers. Or something like that.

- [x] Put a header label on **Solving HTTP 500 errors** so we can link to that from other docs. See http://www.sphinx-doc.org/en/stable/markup/inline.html#ref-role Cross-referencing arbitrary locations

**Comment by rachelappel** [comment]
300995a239ffafe2903232e9c72269cbe92a75e6
