### ISSUE TITLE
Document dotnet new -t Web / -lib / -xunittest

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#1425]
https://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-new.html

Should be updated to include the new flags
`dotnet new -t Lib`
`dotnet new -t Web`
`dotnet new -t xunittest`

**Comment by danroth27** [comment]
@HaoK @richlander This needs to get tracked in the https://github.com/dotnet/core-docs repo. 

We do however need to update our ASP.NET Core Getting Started page with the dotnet new stuff. We can use this issue to track that.

**Comment by danroth27** [comment]
Looks like `dotnet new -t web` includes everything and the kitchen sync so we will keep the ASP.NET Core getting started topic as it is for now.
