### ISSUE TITLE
Broken links to external docs

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#1429]
On: https://docs.asp.net/en/latest/security/authentication/azure-active-directory/index.html

All three links go to pages on azure.microsoft.com that appear to have been moved and now 404. For example: https://azure.microsoft.com/en-us/documentation/samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnet5/

**Comment by danroth27** [comment]
87510068d548b4cbe720f7166aeb0c40999f4566
