### ISSUE TITLE
mvc/controllers/actions "Controllers, Actions, and Action Results"

### ISSUE THREAD

**Issue by dougbu** [aspnet/Docs#1435]
> ##### Content negotiated response
> 
> Instead of returning an object directly, an action can return a content negotiated response (using `Ok`, `Created`, `CreatedAtRoute` or `CreatedAtAction`). Examples: `return Ok();` or `return CreatedAtRoute("routename",values,newobject");`

**Comment by dougbu** [comment]
Hit `<enter>` too soon...

See https://docs.asp.net/en/latest/mvc/controllers/actions.html#controller-helper-methods

The "Content negotiated response" description in this section implies returning an object directly does _not_ do content negotiation and returning `Ok()` does. Neither is true.

Content negotiation applies whenever an action returns an `ObjectResult` or something other than an `IActionResult` implementation. `BadRequestObjectResult`, `CreatedAtActionResult`, `CreatedAtRouteResult`, `CreatedResult`, `NotFoundObjectResult`, and `OkObjectResult` (all of which have corresponding `Controller` helper methods) are `ObjectResult` subclasses. the Web API compatibility shim adds a few more.

**Comment by dougbu** [comment]
Might go further and re-categorize the controller helper methods:

1. Methods / results returning an empty response body. The existing "Redirect" category differs from the other "HTTP Status Code" primarily in the addition of a `Location` header. No content, no need for a `Content-Type` header in the response.
2. Methods / results returning a non-empty response body with a predefined content type. The existing "View" category has an additional subsystem behind it but isn't that different from other "Formatted Response" methods / results. Most of these results have `ContentType` properties allowing e.g. `application/json` instead of `text/json`.
3. Methods / results returning a non-empty response body formatted in a content type negotiated with the client. This is the existing "Content negotiated response" category.

The special cases within 1. and 2. _are_ worth calling out. But it's confusing to treat them as entirely separate.

**Comment by Rick-Anderson** [comment]
- [ ] Fix doug's complaints above
- [ ] UE Edit needed

**Comment by Rick-Anderson** [comment]
@scottaddie  can  you take this one?

**Comment by Rick-Anderson** [comment]
Title should be 
Handling requests with controllers in ASP.NET Core MVC

**Comment by scottaddie** [comment]
@Rick-Anderson Updated the doc title. Will look at the rest of this issue today.

**Comment by Rick-Anderson** [comment]
@scottaddie  I'm assigning this to @ardalis

**Comment by ardalis** [comment]
@Rick-Anderson I started looking at this today, but @scottaddie has an open PR he's actively working on. Should I wait for him to merge it?

**Comment by scottaddie** [comment]
@Rick-Anderson @ardalis I'll reassign myself, as I'm actively working with Doug to wrap this one up.
