### ISSUE TITLE
fundamentals/logging

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1441]
- [x]  Add a paragraph for each of the 4 loggers. `EventLogger` for example can't be configured with a filter. There are several other discrepancies like that.
- [x] Add EventSource provider #1979 
- [x] Add Azure App Service provider #1673
- [x] Need MVC specific section or add a new MVC logging topic
- [x] http://www.maherjendoubi.io/asp-net-core-1-0-built-in-logging-framework-2/ might have value
- [x] Needs UE Review

> .. note:: You can specify the minimum logging level each logger provider will use when you configure it. For example, the `AddConsole` extension method supports an optional parameter for setting its minimum `LogLevel`. You can also specify a function to filter the log levels you wish to include (for example `l => l >= LogLevel.Warning`) or a function to filter based on both log levels and category strings (for example, `(category, loglevel) => category.Contains("MyController") && loglevel >= LogLevel.Trace`). The `ConsoleLogger` allows you to specify whether or not to include scope information in the output by setting`includeScopes`to`true``.

You can specify the minimum logging level {for} each logger provider ~~will use when you configure it~~.

Probably needs to be rewritten - maybe not as a note - something like:

You can filter based on log level and category. For example:
[show example using `AddConsole`] 
show the other examples.

You can ~~also~~ specify a function 
run on sentence needs to be split up

**Comment by cesarbs** [comment]
There's also another issue: not all logger types support the same overloads. `EventLogger` for example can't be configured with a filter. There are several other discrepancies like that.

How about writing one paragraph per logger that we ship? There are only four of them.
