### ISSUE TITLE
How to parse Razor files

### ISSUE THREAD

**Issue by dazinator** [aspnet/Docs#1442]
Hello,

I'd like to figure out how to parse Razor files, and modify them. I have done a similar thing with C# files using Roslyn. This is for an RC1 to RC2 upgrade tool. 

Any ideas where I can find some example code or docs for parsing and editing?

I put together the following, which was a guess based on examining the available classes in teh Razor namespace, to see how far I could get:

```csharp
      
    var razorEngineHost = new RazorEngineHost(new CSharpRazorCodeLanguage());
    var testFilePath = System.IO.Path.Combine(assemblyDir, "testRazorFiles\\_ViewImports.cshtml");
       
    var editorParser = new Microsoft.AspNetCore.Razor.RazorEditorParser(razorEngineHost, testFilePath);

    var parseTree = editorParser.CurrentParseTree;

    // parseTree appears to be null, not sure how to populate it.

    // hoping I can visit the synax tree and modify some nodes.
    var testVisitor = new RazorParserVisitor();
    parseTree.Accept(testVisitor);

```

Where `RazorParserVisitor` is

```csharp
 public class RazorParserVisitor : ParserVisitor
        {
            public override void VisitBlock(Block block)
            {
                switch (block.Type)
                {
                    case BlockType.Directive:
                        break;
                    case BlockType.Markup:
                        break;
                    case BlockType.Section:
                        break;
                    case BlockType.Statement:
                        break;
                }
                base.VisitBlock(block);
            }
        }

```

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  any comment?

**Comment by NTaylorMullen** [comment]
@dazinator what type of editing are you trying to do?

- Are you using MVC and trying to edit the final output? Aka do you want to change the final output via Roslyn?
- Are you using only Razor and want to change the generated Razor file?

**Comment by dazinator** [comment]
I'm writing a console application / command line untility. It runs against an RC1 solution directory. It performs actions on files in the file system - loads them into memory, and modifies them in order to upgrade them to RC2 format. For example there are changes to project.json files, .xproj files, global.json, launchsettings.json etc. However there are also namespace changes that need to be made. I was able to use roslyn to parse c# files and rewrite using statements. However im not sure how to do the same for .cshtml files. As a simple example i'd like to correct usages of the old `AspNet` taghelpers as they changed namespaces to `AspNetCore`.

**Comment by NTaylorMullen** [comment]
Ah, so Razor doesn't provide a mechanism to parse a Razor file, modify the syntaxtree and then reverse the process and spit out the cshtml file responsible for it. Your best bet will be well crafted regex's on cshtml files.

**Comment by dazinator** [comment]
I was scared you were going to say that ><

**Comment by NTaylorMullen** [comment]
Hah, sorry there isn't a better solution!
