### ISSUE TITLE
Consider adding new section showing RequireAssertion in policies.rst

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#1456]
We added a new short hand sugar that we should show which simplifies (aka hides the requirement/handler stuff which we should demonstrate at the end).

This would be a compact alternative to doing the handler/requirement stuff.  Basically it inlines a single handler function which must evaluate to true for the policy to pass.  Its great for simple auth where you can easily express the check in a few lines of code.

@Rick-Anderson @blowdart 

```
services.AddAuthorization(options =>
    {
        options.AddPolicy("BadgeEntry",
                          policy => policy.RequireAssertion(context => 
                                  context.User.HasClaim(c => 
                                     (c.Type == ClaimTypes.BadgeId || c.Type == ClaimTypes.TemporaryBadgeId)
                                      && c.Issuer == "http://microsoftsecurity"));
                          }));
    }   
```

**Comment by blowdart** [comment]
Yea should pop a new section in the policy doc. @Rick-Anderson can you do, or should I?

**Comment by Rick-Anderson** [comment]
>new section in the policy doc.

I can do that.

**Comment by blowdart** [comment]
Beat you to it :)
