### ISSUE TITLE
Use of Fiddler to make API requests is heavy-handed

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Docs#1461]
The use of Fiddler to make API calls as [here](https://github.com/aspnet/Docs/blob/master/aspnet/tutorials/first-web-api.rst#use-fiddler-to-call-the-api) seems like an awfully big hammer to use when something like curl, Invoke-RestMethod (in powershell) or [Postman](https://www.getpostman.com/) could accomplish the same thing without making people learn the UI and workings of a tool meant primarily to inspect all of a machines network traffic.

**Comment by ardalis** [comment]
Just a matter of taste, IMO. They're all free tools. Showing more than one approach would probably be the way to go, as opposed to replacing any one with another.

**Comment by Rick-Anderson** [comment]
We should mention alternative tools. Everyone should have the fiddler hammer in their toolbox.

**Comment by Rick-Anderson** [comment]
@MikeWasson what tools should we mention? I don't think we need to show how to use the other tools, just mention them.

**Comment by danroth27** [comment]
Ideally we would show something that is simpler and cross-platform. I don't think we need to list every tool that let's you make an HTTP request though.

**Comment by MikeWasson** [comment]
That particular doc is VS specific, tho'. 

curl is cross-platform but I don't know if posting JSON in curl is really simpler than using Fiddler? 

Postman might be a good option, it's x-plat. Complexity-wise it seems about the same as Fiddler, for doing basic GET and POST calls.

**Comment by Rick-Anderson** [comment]
I don't think we should drop fiddler as it's universally used and easy to use in this case. We can show another approach and mention there are other tools. 

>That particular doc is VS specific, tho'.

#1215  will address that

**Comment by Rick-Anderson** [comment]
See http://stackoverflow.com/a/11845427/502537

**Comment by davidfowl** [comment]
I'd favor POSTman over fiddler for sending API requests as well. It's much more user friendly, works on all platforms and was really made specifically for these kinds of scenarios.

**Comment by Rick-Anderson** [comment]
Moved to #1380

**Comment by Rick-Anderson** [comment]
After updating this with Postman I was shocked at how much better it is for testing Web-API than fiddler.
