### ISSUE TITLE
Introduction to identity screen shots need to be updated

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#1462]
https://docs.asp.net/en/dev/security/authentication/identity.html

Need an updated png from the latest tooling templates (Step 1, File New dialog has changed).

**Comment by HaoK** [comment]
The Identity Components screenshot could also be updated to show the latest 1.0.0 references instead of rc1 versions

**Comment by HaoK** [comment]
Same template png issue with https://docs.asp.net/en/dev/security/authentication/accconfirm.html

**Comment by HaoK** [comment]
Same screen shot in https://docs.asp.net/en/dev/security/authentication/2fa.html

**Comment by danroth27** [comment]
Duplicate of #1472
