### ISSUE TITLE
"Introduction to Identity" security/authentication/identity

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1472]
- [ ] Update for RTM 
- [ ] #1465
- [ ] #1462
- [ ] #1405

**Comment by Rick-Anderson** [comment]
@scottaddie can you do this?

**Comment by Rick-Anderson** [comment]
@scottaddie assigning to @ardalis 
Looks like most of this is done.

**Comment by ardalis** [comment]
@scottaddie you don't have some WIP on this one somewhere do you?

**Comment by scottaddie** [comment]
@ardalis Nope. You're good to go.
