### ISSUE TITLE
How Web Publishing In Visual Studio Works contains images referring to dnu publish

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Docs#1486]
https://docs.asp.net/en/latest/publishing/web-publishing-vs.html has links to images that refer to dnu publish - e.g.: 
![image](https://cloud.githubusercontent.com/assets/1438884/16323668/70dc2858-3961-11e6-8ddc-01bb90b09b38.png)

**Comment by GuardRex** [comment]
@sayedihashimi @moozzyk @Rick-Anderson If it's just a matter of making those two images say "dotnet publish" (with a change of font to match the font used in the other boxes), would you like me to knock that out real quick? I'm certainly the least busy of four of us. :smile:

**Comment by moozzyk** [comment]
@GuardRex - thanks for fixing this!

**Comment by GuardRex** [comment]
@moozzyk np ... If I can help with the RTM docs push, let me know. :+1:
