### ISSUE TITLE
Gaps in the RC1->RC2 migration guide

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#1492]
https://docs.asp.net/en/latest/migration/rc1-to-rc2.html

Missing steps:
- [x] TFMs: dnx451 -> net451, dnxcore50 -> netcoreapp1.0, Microsoft.NETCore.App dependency
- [x] buildOptions emitEntryPoint
- [ ] Migrating xunit test projects

References:
https://github.com/aspnet/Docs/commit/090db3acb8e5ef92901f9c740876f6011f55a0b5
https://github.com/aspnet/Docs/commit/c9fcad4fdba0e18f680ea8140aa2264b5dfae826

**Comment by davidfowl** [comment]
What about dotnet-publish-iis

**Comment by cesarbs** [comment]
I've identified a bunch of other stuff last night too, I'll update it today.

**Comment by cesarbs** [comment]
- [ ] Add section on "exclude" (now "buildOptions -> compile -> exclude")
- [ ] Add section on "publishExclude" -> "publishOptions"
- [ ] Removal of runtime information stuff
- [ ] ILoggerFactory.MinimumLevel removed?
- [ ] Call .SetBasePath(env.ContentRootPath) on WebHostBuilder
- [ ] sql cache tool
- [ ] user secrets tool
- [ ] dnx-watch -> dotnet-watch

**Comment by cesarbs** [comment]
cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
@Tratcher note that there is also the dotnet migration doc (there's a link to it from the aspnet migration doc). For example, the TFM updates are noted there.

**Comment by JunTaoLuo** [comment]
In fact some of the gaps listed here should be addressed in the dotnet migration docs if they are missing since it is not specific to aspnet https://dotnet.github.io/docs/core-concepts/dnx-migration.html. Or, we can duplicate the information in both places if it's very important (like the global.json changes).

**Comment by cesarbs** [comment]
cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
Let's just point to dotnet and not duplicate.

**Comment by Rick-Anderson** [comment]
fixed via #1485
