### ISSUE TITLE
Fix header styling for long article titles

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#150]
The breadcrumb pushes down the Edit on Github link when the article section + title gets too long.

**Comment by ardalis** [comment]
For example: https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html in a narrow browser window. Edit on GitHub wraps below the title. I would expect the title to wrap and Edit on GitHub to stay in place.

**Comment by Rick-Anderson** [comment]
@ardalis  closing this. I don't think this applies to MD format.
