### ISSUE TITLE
Move Intro to ASP.NET Core to top level TOC

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1512]
- [x] Move Intro to ASP.NET Core to the top of the TOC above Getting Started and rename the file to intro.html
- [x] Move Choosing the Right .NET on the Server to Fundamentals
- [ ] Setup redirects on Read the Docs pointing to the new locations (email)
  - /conceptual-overview/aspnet.html -> /intro.html
  - /conceptual-overview/choosing-the-right-dotnet.html -> /fundamentals/choosing-the-right-dotnet.html
  - /conceptual-overview/index.html -> /intro.html
- [x] Move API down in the TOC between Migration and Contribute

**Comment by Rick-Anderson** [comment]
fixed by #1535
