### ISSUE TITLE
RC1 Data Protection example in need of update

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1520]
@blowdart @Rick-Anderson

In https://docs.asp.net/en/latest/security/data-protection/using-data-protection.html, the code sample contains ...
```c#
using System;
using Microsoft.AspNet.DataProtection;
using Microsoft.Framework.DependencyInjection;
```
... which should be ...
```c#
using System;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.DependencyInjection;
```
If you're busy, I can update it for you.

**Comment by BrennanConroy** [comment]
Checkout https://github.com/aspnet/Docs/blob/dev/aspnet/security/data-protection/using-data-protection/samples/protectunprotect.cs :P
