### ISSUE TITLE
Add information about assembly information

### ISSUE THREAD

**Issue by LukaszDev** [aspnet/Docs#1525]
Hi Guys,

Following this issue: [Wrong assembly information / exe file details (dotnet/cli  #3620)](https://github.com/dotnet/cli/issues/3620)...

Can you consider to add note in docs about from assembly information are taken, please ?

I mean relation between `project.json` and `AssemblyInfo.cs` files.

Currently `AssemblyInfo.cs` file is not included in new project created from default template in VS2015... It's mean that assembly information are taken form `project.json` - that's fine, but `AssemblyInfo.cs` it's still 'higher priority' file, and it's used if exist anywhere in the project...

It's mean that we have mess if we don't have our own `AssemblyInfo.cs` file (by default), but any of 3rd-party library (included by bower) contains that file (from any reason) - in that case this 3rd-party file will be taken as source of assembly information.

There is solution for that - we can exclude `lib` folder from compilation in `project.json` file - for example:
```
"buildOptions": {
  "compile": {
    "exclude": [ "lib" ]
  }
}
```
but still it confuse if you don't know about this, so my suggestion is mention about this in new docs.

Thanks in advance.

**Comment by GuardRex** [comment]
@LukaszDev Since `project.json` is going away in favor of `csproj`, it's likely that this won't be an issue shortly. There is no ETA on it, but the move to `csproj` is a WIP with a lot of activity right now.

**Comment by LukaszDev** [comment]
Thanks for info, i wasn't aware that.

But still it can be issue, depends from assembly information will be taken...

If meta data from project.json just will be moved to csproj file then we have still similar relation between metadata from project and AssemblyInfo.cs file, so still we can have the same issue.

In other word issue in not with project.json - issue is with AssemblyInfo.cs file and as far as this file have higher priority over project metadata and 3rd party component can unintentionally change our assembly information (including this file) we still have the issue.

It's won't be an issue if assembly information will be taken only from one source in our project and this will be well documented.

My suggestion is more general - about add to docs description from assembly are taken, just short note...

**Comment by Rick-Anderson** [comment]
Can you open this  in https://github.com/dotnet/core-docs/issues
Thanks
