### ISSUE TITLE
Add information on testing ASP.NET Core projects on VS Code

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Docs#1528]
This is now supported so it would be nice to add some documentation and screenshots for it on the unit testing page.

**Comment by Rick-Anderson** [comment]
dup of #1346

**Comment by JunTaoLuo** [comment]
I don't see any VS Code test related information in the doc that's mentioned in the other issue. Is that pending?

**Comment by JunTaoLuo** [comment]
@Rick-Anderson What I meant was adding a section indicating that you can directly run/debug tests from VS Code like so: 
![image](https://cloud.githubusercontent.com/assets/2030323/16392889/073523be-3c63-11e6-843c-11483c652e8d.png)

**Comment by Rick-Anderson** [comment]
we are deleting https://docs.asp.net/en/latest/testing/unit-testing.html and ponting to https://docs.microsoft.com/en-us/dotnet/articles/core/testing/unit-testing-with-dotnet-test 
so any issues would need to be opend at https://docs.microsoft.com/en-us/dotnet/articles/core/testing/unit-testing-with-dotnet-test

**Comment by JunTaoLuo** [comment]
Ah I see.
