### ISSUE TITLE
Link to  .NET Core Windows Server Hosting bundle points to RC2

### ISSUE THREAD

**Issue by kirkktx** [aspnet/Docs#1543]
The link here https://github.com/aspnet/Docs/blob/master/aspnet/publishing/iis.rst#install-the-net-core-windows-server-hosting-bundle  points to RC2.  Is the RTM out yet?  If so, I need to know how to download it. Thanks!

**Comment by Rick-Anderson** [comment]
@kirkktx  is https://go.microsoft.com/fwlink/?LinkId=817246 wrong?

**Comment by Rick-Anderson** [comment]
@GuardRex  please review

**Comment by kirkktx** [comment]
Looks good.  I just installed on top of the RC2 that I had previously installed.  It installed ok and simple web app from template built with VS2015 Update3 works.
