### ISSUE TITLE
tutorials/first-web-api.rst: Action void return type returns 200 instead of 204

### ISSUE THREAD

**Issue by whyleee** [aspnet/Docs#1559]
In ["Delete" subsection](https://docs.asp.net/en/latest/tutorials/first-web-api.html#delete) of "Implement the other CRUD operations" section of the article it is stated that action void return type returns 204 response, but I get 200 in this case. I'm using latest ASP.NET Core 1.0.

**Comment by Rick-Anderson** [comment]
@rachelappel  please verify when you update this tutorial.

**Comment by Rick-Anderson** [comment]
dup of #1380

**Comment by ryanhall27** [comment]
I'm a little bit confused on this.  Is this a bug in the code or the documentation?  Seems to me like it is a bug in the code.  A void method should return 204 by default correct?  

I just need to know either way so I can plan accordingly, thanks.

**Comment by Rick-Anderson** [comment]
@danroth27  please respond

**Comment by danroth27** [comment]
Returning void isn't sufficient to tell if the response body is empty. You can always add content to the response using the HttpContext directly. 

If you want to return a 204 when returning void then you can add the HttpNoContentOutputFormatter to the output formatters.

**Comment by ryanhall27** [comment]
That makes perfect sense, thank you for the explanation.
