### ISSUE TITLE
fundamentals/environments.rst "Working with Multiple Environments"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1561]
- [ ] [1550 comment](https://github.com/aspnet/Docs/pull/1550/files/b10fdabf8a06f01323e68337e6f12626d17b638a#r68808110) Note that `WebHostBuilder.UseStartup<TStartup>()` overrides detection of environment specific startup types. Environment specific methods still work. See https://github.com/aspnet/Home/issues/1595
- [ ] thank tratcher when you fix this

**Comment by spboyer** [comment]
There isn't any update needed for the doc, there is a related comment in the chain related to starting your application with a specific ENV - https://github.com/aspnet/Home/issues/1595#issuecomment-231829737

I believe that this can be closed.

cc:/ @Tratcher

**Comment by spboyer** [comment]
@danroth27 - See comment above

**Comment by danroth27** [comment]
I think this is a simple one line fix to add a note to the [Startup Conventions](https://docs.asp.net/en/latest/fundamentals/environments.html#startup-conventions) section of this topic that says calling `WebHostBuilder.UseStartup<TStartup>()` will override the environment specific startup sections. This should be really quick to fix. @spboyer Can you make the quick edit?

**Comment by spboyer** [comment]
done.
