### ISSUE TITLE
Links in tutorials goes to wrong url with .md extension which returns an error.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Docs#1568]
On the docs pages / tutorials like this one:
https://www.microsoft.com/net/tutorials/csharp/getting-started/strings

there are links that points to `.md` files.
For example: https://www.microsoft.com/net/tutorials/csharp/getting-started/methods.md

That link doesn't work and returns an error. The correct path is https://www.microsoft.com/net/tutorials/csharp/getting-started/methods

Looks like all links have the same issue.

/cc @ardalis

**Comment by ardalis** [comment]
Those docs aren't part of this repository, but I'll follow up and get it fixed. Thanks!

**Comment by Bartmax** [comment]
Thanks, I didn't know where to file an issue. asked on slack and followed to this repo.
