### ISSUE TITLE
VSCode on Mac OSX /Linux version of  Web-API and  tutorials/first-mvc-app/index.md "Getting started with ASP.NET Core MVC and Visual Studio"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1576]
From #1378 
We need to have a minimal getting started with MVC tutorial that covers without tooling:
- Adding the Microsoft.AspNetCore.Mvc package
- Calling services.AddMvc() and app.UseMvc()
- Create a HomeController that returns a simple view with a model

Related issues:
- #1842
- #1378
- #1799

**Comment by spboyer** [comment]
Is this just the `yo aspnet` walk through for a web app?

**Comment by Rick-Anderson** [comment]
we need that too ( a non Visual Studio version of https://docs.asp.net/en/latest/tutorials/first-web-api.html)

This issue is for a non VS version of https://docs.asp.net/en/latest/tutorials/first-mvc-app/index.html

**Comment by Rick-Anderson** [comment]
#1215 is the Web-API issue @spboyer

**Comment by Rick-Anderson** [comment]
@spboyer @danroth27  changing this to P0 from cust feedback.

**Comment by danroth27** [comment]
We already cover a minimal getting started experience with MVC in https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet. 
https://github.com/aspnet/Docs/issues/1215 tracks adding a minimal getting started tutorial for Web APIs.
