### ISSUE TITLE
How can I connect with MySQL ?

### ISSUE THREAD

**Issue by songwutk** [aspnet/Docs#1579]
MySQL is php favorite database.

**Comment by Rick-Anderson** [comment]
see https://docs.efproject.net/en/latest/providers/mysql/index.html
@rowanmiller  what's the latest?

**Comment by rowanmiller** [comment]
That doc you linked to has the latest status, unfortunately there is no other information I can share.

**Comment by rowanmiller** [comment]
BTW I did just want to add that we do consider MySQL a top priority, so please don't take my lack of comment to mean we don't care about the scenario. When working with provider writers it is up to them how and when they publically share information about timelines etc.

**Comment by songwutk** [comment]
https://github.com/bgrainger/MySqlConnector

My Search.
