### ISSUE TITLE
Folder names conventions for static assets

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#1592]
Some articles are in violation of the convention specified in the [contributing guide](https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md#example-structure).
- [x] `aspnet/publishing/pubIIS` should be renamed to `aspnet/publishing/iis` (assets directory should match name article)
- [x] `aspnet/mvc/views/forms/` should be renamed to `aspnet/mvc/views/working-with-forms`
- [x] `aspnet/hosting/aspnet-core-module/ANCM-502_5.png` should move to `aspnet/hosting/aspnet-core-module/_static/ANCM-502_5.png`
- [ ] `aspnet/security/data-protection/consumer-apis/purposes-multi-tenancy/` should be renamed to `aspnet/security/data-protection/consumer-apis/purpose-strings-multitenancy/`
- [ ] `aspnet/performance/caching/response-caching/` should be renamed to `aspnet/performance/caching/response/`

**Comment by shirhatti** [comment]
@danroth27

**Comment by shirhatti** [comment]
This is part of the OPS work

**Comment by danroth27** [comment]
@Shirhatti Are you planning to PR this? If not, then how urgent is it?

**Comment by shirhatti** [comment]
Not urgent. The script expects these conventions. Now, it just succeeds with some failures.
You can choose to fix it now, or in the manual pass later.

**Comment by Rick-Anderson** [comment]
@shirhatti  please test scripts and close this if fixed

**Comment by shirhatti** [comment]
@Rick-Anderson Those 3 changes were good. I found 2 more inconsistencies. I have edited the issue

**Comment by shirhatti** [comment]
- [ ] `aspnet/security/data-protection/consumer-apis/purposes-multi-tenancy/` should be renamed to `aspnet/security/data-protection/consumer-apis/purpose-strings-multitenancy/`
- [ ] `aspnet/performance/caching/response-caching/` should be renamed to `aspnet/performance/caching/response/`

**Comment by Rick-Anderson** [comment]
@shirhatti  I know how to look at the task list, no need to copy -:) I fixed those with #1600
So can we close this issue now?

**Comment by shirhatti** [comment]
Sorry. I misunderstood what you said.
I haven't had a chance to review. I'll re-run the script later today and let you know :)

**Comment by shirhatti** [comment]
I should have closed this issue on Jul 21, 2016 😄
