### ISSUE TITLE
`index.rst` pages should not have content

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#1596]
We need some content refactoring so as to ensure `index.rst` pages contain only a TOC and no other text. There are a few pages in violation of this.

- [ ] https://docs.asp.net/en/latest/security/authorization/index.html
- [ ] https://docs.asp.net/en/latest/security/data-protection/index.html
- [ ] https://docs.asp.net/en/latest/hosting/index.html
- ~~https://docs.asp.net/en/latest/index.html~~ (Don't touch)

**Comment by shirhatti** [comment]
@danroth27 Part of the OPS work

**Comment by Rick-Anderson** [comment]
@shirhatti  I think we can safely remove the intro on the first two. How do you want to handle hosting? Do you want an intro doc?

**Comment by Rick-Anderson** [comment]
@rachelappel  I did #1592, this one is yours :-)

**Comment by shirhatti** [comment]
I think it's safe to remove the intro for hosting as well. I don't see it as much of a value add. Especially since we renamed Hosting -> Guidance for Hosting Providers

**Comment by Rick-Anderson** [comment]
@rachelappel  can you do this next so @shirhatti  can test his scripts. It will save you and me manual work.

**Comment by shirhatti** [comment]
The home page is also in violation of this.
- [ ] https://docs.asp.net/en/latest/index.html

I would recommend removing the text accompanying the Contribute section.
The attention and note at the top of the page needs to go as well.

**Comment by danroth27** [comment]
Please don't touch the home page as part of this clean up. The home page is "special" and should be handled as a one off change.

**Comment by Rick-Anderson** [comment]
@shirhatti  I think I've covered everything, can you run your scripts again?

**Comment by Rick-Anderson** [comment]
@shirhatti I think I've covered everything, can you run your scripts again?  And update this issue?

**Comment by shirhatti** [comment]
👍 Looks good to me
