### ISSUE TITLE
OWIN suport for .NETCoreApp

### ISSUE THREAD

**Issue by GDBSD** [aspnet/Docs#1598]
Trying to add the Owin package to a new project. In project.json (dependencies segment) red squigly under Microsoft.AspNet.WebApi.Owin": "5.2.3". Mouseover displays four errors all relating to support for .NETCoreApp

![owindotnetcoreerror](https://cloud.githubusercontent.com/assets/7552225/16533109/1b0ed25e-3f9c-11e6-8c03-3ac7d98380a1.png)

**Comment by Rick-Anderson** [comment]
It's now AspNetCore, see our update guide.
