### ISSUE TITLE
Requirement of package needed for configuration is "hidden" in code.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Docs#1604]
In this doc: 
http://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects

the requirement of a particular package to make configuration work with binding is in the code snipped instead of being part of the document itself. I think a note box will be more appropiate. just my 2c.

```
// Configure MyOptions using config by installing Microsoft.Extensions.Options.ConfigurationExtensions
    services.Configure<MyOptions>(Configuration);
```

**Comment by Rick-Anderson** [comment]
Thanks moved this to #829
