### ISSUE TITLE
Docs search isn't working

### ISSUE THREAD

**Issue by CIPop** [aspnet/Docs#1608]
Searching for "IIS" doesn't give any results: 
https://docs.asp.net/en/latest/search.html?q=iis&check_keywords=yes&area=default

The first result of this search points to the right article on the docs.asp.net site:
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=host%20asp.net%20core%20in%20iis

**Comment by GuardRex** [comment]
Fixed with DocFX?

![capture](https://cloud.githubusercontent.com/assets/1622880/22238483/38eed1c4-e1d7-11e6-8ea4-dbac349eedd9.PNG)

**Comment by Rick-Anderson** [comment]
It's working now. Thanks

**Comment by CIPop** [comment]
Thanks!
