### ISSUE TITLE
fundamentals/localization "Globalization and localization"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1610]
- [x] https://github.com/aspnet/Localization/issues/277 Pri 0 
- [ ] aspnet/Mvc#5282 Document how to localize custom validation attributes (was #1878)
- [x] Survey to find out if one file/view or one single file per app is more popular - and the ratio. Several customers assert one file/view is never used and should not be introduced at the beginning of the topic.
  **results of twitter poll were mixed**
- [ ] Once  https://github.com/aspnet/Localization/pull/266 is resolved add section on cross-project loc. 
- [x] #1798 
- [x] #2025 perf
- [ ] #2026 validation

**Comment by Rick-Anderson** [comment]
@damienbod @bartmax please review https://twitter.com/RickAndMSFT/status/750772253852176384

**Comment by Rick-Anderson** [comment]
Once the survey is good I'll have damien edwards re-tweet so we can get lots of feedback.

**Comment by hishamco** [comment]
@Rick-Anderson seems all unchecked items has been resolved
