### ISSUE TITLE
API ref docs encoding <p> for <para>

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#1620]
Compare:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Routing/IRouteValueProvider.cs#L22
https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Mvc/Routing/IRouteValueProvider/index.html#Microsoft.AspNetCore.Mvc.Routing.IRouteValueProvider

The `<para>` tags in the XML are getting turned into `<p>` tags and then getting encoded so they don't affect the HTML.

**Comment by Rick-Anderson** [comment]
@rynowak  we're moving to docFX which will have all new issues for you to file.
