### ISSUE TITLE
/fundamentals/routing "Routing"

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#1625]
This doc [aspnet/fundamentals/routing.md](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing) could use a lot more exposition about the technical process of link generation.

**Comment by Rick-Anderson** [comment]
- [ ] more exposition about the technical process of link generation.
- [ ] Map[Verb] extensions will need their own section.
- [ ] rewrite startup section/code
- [ ] 
- [ ]

**Comment by Rick-Anderson** [comment]
@rynowak if you have time to do this in word/MD or any other format I can update the doc.

**Comment by Rick-Anderson** [comment]
dup of #1077
