### ISSUE TITLE
Update Publishing to IIS Common Errors for ANCM changes

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1626]
RE: [Common Errors of Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html#common-errors)

RTM ANCM changes yield new browser and ANCM log entries. For example: ANCM behavior for missing `.UseIISIntegration()` on `WebHostBuilder()` ...

Previous ANCM Behavior
**Browser:** No response
**ANCM Log:** Process '4568' failed to start. Port = 32205, Error Code = '-2147023436'.

New ANCM Behavior
**Browser:** HTTP Error 502.5 - Process Failure
**ANCM Log:** Process was created with commandline '"PATH\testselfcontained.exe" ' but either crashed or did not reponse within given time or did not listen on the given port '3976', ErrorCode = '0x800705b4'

Therefore, I'll rework the common errors list and update the Troubleshooting section. Look :eyes: for a PR within 48 hours.

**Comment by Rick-Anderson** [comment]
@GuardRex  are you going to update the doc?

**Comment by GuardRex** [comment]
Yes I'll have the PR in tonight.
On Jul 6, 2016 2:04 PM, "Rick Anderson" <notifications@github.com> wrote:

@GuardRex <https://github.com/GuardRex> are you going to update the doc?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/Docs/issues/1626#issuecomment-230872589>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABjDYNApgZBfSfnGTMngXQ8PtdBLdm_Dks5qS_xPgaJpZM4JFvf_>
.

**Comment by GuardRex** [comment]
@Rick-Anderson @danroth27

Slight prob with one of them. The RTM ANCM is throwing *identical and indistinguishable messages/exceptions* for two common error scenarios: the `.UseUrls()` after `.UseIISIntegration()` and the one that @CIPop is adding for a missing `.UseIISIntegration()`.

### Prior ANCM
#### `.UseUrls()` after `.UseIISIntegration()`
Browser: No response
Application Log: Process ‘PROC_ID’ failed to start. Port = PORT, Error Code = ‘-2147023829’.
ASP.NET Core Module Log: Unhandled Exception: System.AggregateException: One or more errors occurred. (Error -4092 EACCES permission denied)

#### Missing `.UseIISIntegration()`
Browser: No response
Application Log: Process '10588' failed to start. Port = 31095, Error Code = '-2147023436'.
ASP.NET Core Module Log: Application started. Press Ctrl+C to shut down.

### RTM ANCM
#### `.UseUrls()` after `.UseIISIntegration()` or Missing `.UseIISIntegration()`
**Browser:** HTTP Error 502.5 - Process Failure
**Application Log (Portable app):** Process was created with commandline '"dotnet" ...' but either crashed or did not reponse within given time or did not listen on the given port 'PORT', ErrorCode = '0x800705b4'
**Application Log (Self-contained app)**: Process was created with commandline '"PATH\my_application.exe" ' but either crashed or did not reponse within given time or did not listen on the given port 'PORT', ErrorCode = '0x800705b4'
**ASP.NET Core Module Log:**  Application started. Press Ctrl+C to shut down.

No huge deal ... It just means that I need to combine these two. I'll continue with the testing, update, and submit this PR tonight. After @CIPop's PR is merged, I'll submit an update PR to update the "Missing `.UseIISIntegration()`" common error.

**Comment by wildsylvan** [comment]
@GuardRex I know this is not the best place but could I have your contact? I'm getting 502.5 with an empty log created and I run out of things to try...

**Comment by GuardRex** [comment]
@wildsylvan I'm on Slack right now ... http://tattoocoder.com/aspnet-slack-sign-up/ ... meet me in the #iis channel
