### ISSUE TITLE
 Sample/instructions for configuring Apache as a proxy server - under publishing/index.rst

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#1630]
Should go somewhere under https://docs.asp.net/en/latest/publishing/index.html
Originally requested at https://github.com/aspnet/Docs/issues/1348

**Comment by Rick-Anderson** [comment]
@glennc FYI

**Comment by Rick-Anderson** [comment]
@glennc if you can provide these instruction in word/html/notepad I'll get them added. Please suggest where they should go.
