### ISSUE TITLE
getting-started.rst "Getting Started" 

### ISSUE THREAD

**Issue by CIPop** [aspnet/Docs#1632]
Ref #1609:

> > Going through the tutorial/getting started I can't see the UseContentRoot part: https://docs.asp.net/en/latest/getting-started.html
> > Should the getting started get updated as well or leave this as is?
> 
> It's up to @Rick-Anderson and @danroth27, but I hope for consistency across all of them with https://github.com/aspnet/cli-samples

**Comment by CIPop** [comment]
@danroth27 @Rick-Anderson PTAL

**Comment by Rick-Anderson** [comment]
- [ ] Missing UseContentRoot in the Getting Started section

**Comment by danroth27** [comment]
This was deliberately left out because the getting started sample didn't need it. However, we are getting feedback that we should extend the getting started flow to include 1. enabling static files, 2. enabling an MVC view, and 3. returning some JSON, in which case we will need to add this.

**Comment by CIPop** [comment]
@danroth27 I personally like the simplest possible "Hello world" sample. While it's fine to add static files, MVC, etc, to getting started, I think it's always great to keep the simple "Hello world" as well.
