### ISSUE TITLE
Incorrect supervisord config in Linux Publishing guide

### ISSUE THREAD

**Issue by WayneKoorts** [aspnet/Docs#1645]
The configuration has some critical problems which mean the process won't run under supervisord:

- The dotnet command should not be run through bash, since it's not a bash script.
- The "directory" supervisord option should be specified (working directory). I'm not 100% sure whether this was only required because I was temporarily running my app using a SQLite DB, but it seems a safe option to set regardless and I imagine many people will do what I did to try a test setup.

**Comment by WayneKoorts** [comment]
Pull request with fix: #1646

**Comment by Rick-Anderson** [comment]
migrated to #1251
