### ISSUE TITLE
epub version contains errors

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Docs#1648]
I exported the v1.0.0 docs to an epub file through docs.asp.net and nearly each section starts with a smilar error to below one:

![image](https://cloud.githubusercontent.com/assets/328122/16709905/cda15a84-4615-11e6-9a9d-e642da76c0a6.png)

**Comment by tugberkugurlu** [comment]
iBooks on iPhone.

**Comment by danroth27** [comment]
@agjohnson Have you guys seen these errors with the generated ePub files on iBooks? Is there something we are doing in the .rst that is causing this?

**Comment by agjohnson** [comment]
@danroth27 reproduced this on OSX reader as well, looks like it may be an issue with our Sphinx template and unclosed tags again. I'll open an issue there.

refs rtfd/readthedocs.org#409
refs rtfd/readthedocs.org#744

**Comment by agjohnson** [comment]
Looked into this, looks like the helpfulness plugin drops an unclosed tag in the output (`input` tag on line 4):

```html
<div class="helpfulness-form-no" style="display:none;">
  <h2>Is this page helpful?</h2>
  Sorry this wasn't helpful.
  <input type="text" id="txt-helpfulness" placeholder="Please let us know why this wasn't helpful">
  <span id="helpfulness-characters-left">characters remaining</span>
  <a id="helpfulness-btn-submit" href="javascript:;" class="common-btn">Submit</a>
  <a id="helpfulness-btn-skip" href="javascript:;" class="common-btn secondary">Skip this</a>
</div>
```

cc @danroth27

**Comment by danroth27** [comment]
@agjohnson Sure, but this is valid HTML right? Input tags are void tags. Are there constraints that we need to be aware of when putting HTML in our templates?

**Comment by danroth27** [comment]
I built a new [epub](https://www.dropbox.com/s/9zipfmcqhp2v1hg/aspnet-aspnet-danroth27-epub.epub?dl=0) with a fix. @tugberkugurlu can you try it out?

**Comment by agjohnson** [comment]
@danroth27 correct, it was valid HTML but not XHTML. EPUB seems to require valid-ish XHTML.
