### ISSUE TITLE
Docs sample changes default namespace.

### ISSUE THREAD

**Issue by ColinDabritz** [aspnet/Docs#1652]
I followed the default docs getting started guide on a mac today, and got this error:

```
Compiling aspnetcoreapp for .NETCoreApp,Version=v1.0
/usr/local/share/dotnet/dotnet compile-csc @/Users/colin/Projects/dotnet/aspnetcoreapp/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
/Users/colin/Projects/dotnet/aspnetcoreapp/Program.cs(12,29): error CS0246: The type or namespace name 'Startup' could not be found (are you missing a using directive or an assembly reference?)
```

A quick inspection revealed that the namespace declarations are not the same.

With my setup (latest dotnet core setup as of today) running a `dotnet new` gave me a `Program.cs` namespace of `namespace ConsoleApplication`, rather than the project/folder name as shown in the guide of `namespace aspnetcoreapp`. Clearly, because the namespaces don't match and there is no full qualification of Startup, it can't find the class leading to the above error.

Unless I'm misunderstanding the intended behavior, this is just a missing highlight on step 6 showing the namespace change (or alternately fully qualifying including the namespace).

I will submit a pull request with a fix shortly.

**Comment by Rick-Anderson** [comment]
fixed buy https://github.com/aspnet/Docs/pull/1653
