### ISSUE TITLE
client-side/using-gulp.rst "Using Gulp": Deprecated Gulp plugin recommendation

### ISSUE THREAD

**Issue by ArgTang** [aspnet/Docs#1668]
Hello.

In the gulp [section ](https://github.com/aspnet/Docs/blob/master/aspnet/client-side/using-gulp.rst) it is recomended to use [gulp-css-min](https://github.com/chilijung/gulp-cssmin).

gulp-css min on npm is a duplicate of [gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css), witch is deprecated and recomended to upgrade to [gulp-clean-css](https://github.com/scniro/gulp-clean-css)

**Comment by danroth27** [comment]
We've also moved away from using gulp in our default templates for bundling and minification.

**Comment by danroth27** [comment]
Closing since we are moving away from gulp for bundling and minification.
