### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by tverboon** [aspnet/Docs#1677]
We want to internationalize our Asp.Net Core web application and we are figuring out how to do this. The new workflow described in the documentation sounds great:

> You can leave the default language literal strings in the app and wrap them in the localizer, so that you can focus on developing the app. You develop your app with your default language and prepare it for the localization step without first creating a default resource file. Alternatively, you can use the traditional approach and provide a key to retrieve the default language string. For many developers the new workflow of not having a default language .resx file and simply wrapping the string literals can reduce the overhead of localizing an app.

But I am afraid this will only kick the can down the road? What if we want to add another language? Do we need to go through all our sources and scan for localization keys and build the resx then? Or is there a smarter way to do it?

**Comment by Rick-Anderson** [comment]
This is not a Q/A forum. One easy approach is to have only one file and one resx. Then you simply produce the 2nd resx.

**Comment by tverboon** [comment]
Thank you for your answer. I am aware that this is not a Q/A forum and maybe my introduction made it look that way. The approach you give is the 'traditional' work flow as it is described in the documentation and is well known. I still don't understand how this 'new' workflow is going to reduce the overhead if it means you still have to through all the sources and create your resx file based on _localizer["some string"]. If that's the case, why bother at all with wrapping around the string literals?

I guess I was reading too much into this and was hoping for some roslyn analyzer that could generate  the first resx file afterwards. Sorry for the inconvenience.
