### ISSUE TITLE
Document what kind of formats are supported in model binding

### ISSUE THREAD

**Issue by kichalla** [aspnet/Docs#1680]
It would be nice to table out the list of formats that we support in model binding. For example, for `Dictionary<string, string>` following formats work which is kind of difficult for an end user to figure out:

*Model*: `Dictionary<string, string> states`
   1. states[wa]=washington&states[va]=virginia&states[mi]=michigan
   2. states[0].Key=wa&states[0].Value=washington&states[1].Key=va&states[1].Value=virginia

@dougbu

**Comment by dougbu** [comment]
Relates to aspnet/Mvc#1001 which is about a similar doc comment gap. @danroth27 which would you prioritize?

**Comment by danroth27** [comment]
We have some text in the [model binding](https://docs.asp.net/en/latest/mvc/models/model-binding.html) doc covering this, but it's hard to find and it looks wrong:

>Model binding treats Dictionary types similarly, asking for parameter_name[key] or just [key], as long as the keys are simple types.

**Comment by dougbu** [comment]
@danroth27 the bit you quoted is correct but covers one of four possible formats for dictionary elements. The other formats are `parameter_name[0].Key=key&parameter_name[0].Value=value`, `parameter_name[].Key=key&parameter_name[].Value=value`, and `parameter_name.index=32&parameter_name[32].Key=key&parameter_name[32].Value=value`. As with the illustrated format, `parameter_name` can be left out for a top-level dictionary.

Separately, which issue is this a duplicate of?

**Comment by danroth27** [comment]
Dup of https://github.com/aspnet/Docs/issues/1080
