### ISSUE TITLE
Customizing model binding

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1681]
mvc/models/custom-model-binding

Outline
- Overview (what is model binding, refer to main doc, describe where a custom model binder will fit in)
- The Problem
  - Example: Base64 encode/decode. This is already implemented in the box. Reference as an example.
  - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ByteArrayModelBinder.cs
  - Database-based binding. Scenario: user submits a key and model binding automatically fetches the record associated with that key and passes it into the action method.
- Implementing a Custom Model Binder
  - Need to know exactly what it is you're binding. Is it a specific class, group of classes, strings, or something based on an attribute?
  - The simplest approach is to use the `ModelBinderAttribute`, and specify the binder there.
  - 2nd easiest is to write your own `ModelBinderProvider`. That's what the framework does. You would do this mainly if you are shipping a 3rd party framework, or you want dynamic logic to decide whether to use your binder, or if your binder needs to consume other binders (e.g. for composite or complex binder that references other binders).
  - Consider what kinds of errors may occur, and how you would surface them to the user? To the model binding system? Example with database binder. If entry isn't there, you probably should return a 400 error. This would be implemented as a ModelState error (example: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ByteArrayModelBinder.cs#L47). For something like a database not being available, you can just throw and return a 500.
  - DI
    - If you register your model binder via the model binder attribute, then DI works via constructor
  - Steps to Create a Custom Model Binder
    - Determine where you're reading the input from
    - Read the input (value provider, route provider, database, body, headers)
    - Convert data to format it needs to be in. Typically you set BindingContext.Result (see: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ByteArrayModelBinder.cs#L47)
- Recommendations and Best Practices
  - You shouldn't need to write your own provider except in rare cases.
  - Devs usually want to use a model binder because they want something to show up in the action as a parameter that isn't normally a parameter.
  - If all you want to do is convert a string to your custom type, you should write a `TypeConverter` instead. Refer to the .NET docs on this.

See info in #2717

Also reference: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/BinderTypeModelBinder.cs

**Comment by Rick-Anderson** [comment]
@danroth27  please recommend the use case to use in the article.

**Comment by rynowak** [comment]
Dan says you should look at the info in #2717

**Comment by Rick-Anderson** [comment]
@ardalis  can you do this? Let me know when to set up a meeting wit [@]rynowak

**Comment by ardalis** [comment]
Sure. I sent you availability for next week. See if you can schedule something in with Ryan then, too.

**Comment by ardalis** [comment]
@rynowak quick question:
Trying to use ModelState to determine a 404 should be returned is not very elegant. Do you know of a better way than this?
```
        public IActionResult GetById(Author author)
        {
            if (!ModelState.IsValid)
            {
                if (ModelState
                    .Any(s => s.Key == "id" &&
                         s.Value.Errors
                            .Any(e => e.ErrorMessage.Contains("not found"))
                        ))
                {
                    return NotFound();
                }
                return BadRequest(ModelState);
            }
            return Ok(author);
        }
```
Full code: https://github.com/aspnet/Docs/tree/ardalis/custom-model-binding/aspnetcore/mvc/advanced/custom-model-binding/sample/CustomModelBindingSample

**Comment by ardalis** [comment]
I was thinking it might be simpler to not add the modelstate error and have `author` be null when it's not found, and in the controller check for that state and return `NotFound`. Also, is there any easy way to get back the id that was passed in, in this case? If I request /author/2 which doesn't exist, in the action method I'm no longer going to have access to the 2 value (or if I do, from where?), so I can't say `return NotFound(2);` which is a common pattern.

**Comment by ardalis** [comment]
Related: http://stackoverflow.com/questions/11211546/should-a-modelbinder-throw-a-404-exception

**Comment by ardalis** [comment]
@rynowak in case you missed these questions above, too.

**Comment by rynowak** [comment]
> I was thinking it might be simpler to not add the modelstate error and have author be null when it's not found, and in the controller check for that state and return NotFound. 

I think this is fine

> Also, is there any easy way to get back the id that was passed in, in this case? If I request /author/2 which doesn't exist, in the action method I'm no longer going to have access to the 2 value (or if I do, from where?),

No you can make it a separate parameter if you want, but I don't see why this is important.

>  so I can't say return NotFound(2); which is a common pattern.

I have never heard of this before. `NotFound(2)` would attempt to serialize the `2` as JSON which is almost certainly not what you want.

**Comment by ardalis** [comment]
Right, returning the id just makes it easy for the client code to say something like "No record found for id {id}" where {id} is the thing in the body of the 404 response. It's not critical so I just won't show that in the sample at all.
