### ISSUE TITLE
Will there be Documentation and/or Guide for Microsoft.Extensions

### ISSUE THREAD

**Issue by Abdullah2993** [aspnet/Docs#1690]
As of right now only API reference is available in docs. 
Will there be proper Documentation and Guides for using `Microsoft.Extension.*` so that they can be use separately for `AspNetCore`

Especially for `Microsoft.Extensions.DependencyInjection`,  `Microsoft.Extensions.Configuration`, `Microsoft.Extensions.Logging` and `Microsoft.Extensions.Options`

**Comment by GuardRex** [comment]
> proper Documentation and Guides

Those are covered at https://docs.asp.net/en/latest/ ... were you looking for something beyond the ASP.NET Core docs?

**Comment by danroth27** [comment]
Microsoft.Extensions.* are covered in various parts of the ASP.NET Core docs (ex Configuration, Logging, DI, etc.). While these components can technically be used independently of ASP.NET Core we consider them part of the ASP.NET Core family of components.
