### ISSUE TITLE
Yeoman article

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#17]
Noel's booked until later in April when he expects to write this article.

**Comment by ardalis** [comment]
Noel submitted it yesterday; pending review now.

**Comment by peterblazejewicz** [comment]
Hi guys, just wondering: which specific tool is that content covering? [generator-aspnet](https://github.com/OmniSharp/generator-aspnet) (best choice)?
Thanks!

/cc @sayedihashimi  @spboyer
This applies to following docs section I assume:
https://github.com/aspnet/Docs/blob/master/docs/tutorials/your-first-mac-aspnet.rst#scaffolding-applications-using-yeoman

**Comment by sayedihashimi** [comment]
It should be using yo aspnet, if not we will need a rewrite :)
