### ISSUE TITLE
When downloading the html docs loading is slow and search doesn't work

### ISSUE THREAD

**Issue by eByte23** [aspnet/Docs#1704]
I would like to be able to download the docs for offline use.

Currently I can download in html format which shows a search box but it doesn't work.
I would like to be able to use this.

Also it takes and extremely long time time "finish" loading. It displays the page but its very gittery until the version box in the bottom left shows

**Comment by Rick-Anderson** [comment]
-  I've confirmed that search does not work but that's expected for HTML. The ePub and PDF readers should offer search.
- loading for me was fast with chrome and slow with Edge and IE. We'll investigate.
