### ISSUE TITLE
Add project.lock.json to .gitignore

### ISSUE THREAD

**Issue by muratg** [aspnet/Docs#171]
Not sure why we are checking in these files.  If the goal is to hardcode beta4, then files should be actually locked.  Otherwise it should be in .gitignore.

**Comment by carlosmunozrodriguez** [comment]
`lock.project.json` is already in VisualStudio.gitignore from this commit in github/gitignore: https://github.com/github/gitignore/commit/467e257fdb71b6b920dde08ef16337e80ef91bb6

**Comment by muratg** [comment]
This bug was filed for the samples in this repo.  One example: https://github.com/aspnet/Docs/blob/f988eba02dd1e418e1f09a027ec566ecf6dc6ce2/docs/mvc/migration/migratingfromwebapi2/sample/ProductsDnx/project.lock.json

**Comment by Rick-Anderson** [comment]
@TomArcher  can you add that? This is fairly hi-pri (fix in the next two weeks please).

**Comment by TomArcher** [comment]
@Rick-Anderson This appears to be done already

**Comment by Rick-Anderson** [comment]
Great - thanks for checking. This was an ancient open issue and now it's closed.
