### ISSUE TITLE
Forwarded action for UseExceptionHandler() is not documented in Error Handling

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1721]
@ardalis @Rick-Anderson @kichalla

Referring to https://github.com/aspnet/Diagnostics/issues/320, I wanted to run an idea by you to add something to the Error Handling doc at ...

https://docs.asp.net/en/latest/fundamentals/error-handling.html?highlight=useexceptionhandler#configuring-an-exception-handling-page

The HTTP verb of the request is going to be forwarded to the path provided to `app.UseExceptionHandler("/Error");`. I feel it's probably noteworthy to mention that fact where this is shown in the doc.

Here is some brainstormed language that would have saved me a few minutes tacked on after ...

> When not in development, it’s a good idea to configure an exception handler path using the `UseExceptionHandler` middleware:
```
app.UseExceptionHandler("/Error");
```

The middleware will forward the HTTP verb to the path provided. For example, if a PUT request were to fail, the handler will invoke the **/Error** path with PUT. The same will be true for other HTTP verbs.

If your application receives request verbs other than GET and you intend to serve an MVC View, such as an error page, either don't specify the HTTP verb constraint on the `IActionResult`:
```c#
[Route("/Error")]
public IActionResult Index()
{
    return View();
}
```
or specify all of the verbs that you intend to cover. For example:
```c#
[HttpGet, HttpPut, HttpPost, HttpDelete, HttpPatch]
[Route("/Error")]
public IActionResult Index()
{
    return View();
}
```

**Comment by Rick-Anderson** [comment]
@kichalla can you review this?

**Comment by GuardRex** [comment]
... and my OP doesn't make complete sense (i.e., returning a View for non-GET verbs, like PUT or DELETE). It might be better to show something more like ...

If your application receives request verbs other than GET and you intend to handle them collectively, don't specify the action attribute on the `IActionResult`:
```c#
[Route("/Error")]
public IActionResult Index()
{
    // Handle error here
}
```
or specify all of the verbs explicitly that you intend to cover. For example:
```c#
[HttpGet]
[Route("/Error")]
public IActionResult Index()
{
    return View();
}

[HttpPut, HttpPost]
[Route("/Error")]
public IActionResult HandlePutOrPostError()
{
    // Handle PUT or POST error here
}

[HttpDelete]
[Route("/Error")]
public IActionResult HandleDeleteError()
{
    // Handle DELETE error here
}
```

**Comment by Rick-Anderson** [comment]
@kichalla is this worth adding?

**Comment by kichalla** [comment]
Sorry for the delay in reviewing this. Yes, I think its worth adding. Probably we should just add the following section to keep it less verbose and mentioning to not explicitly decorate with http method attributes as the whole app is going to use this single action and having explicit verbs could prevent reaching this action for some requests.

```
[Route("/Error")]
public IActionResult Index()
{
    // Handle error here
}
```

**Comment by Rick-Anderson** [comment]
@GuardRex  did you want to add this?

**Comment by GuardRex** [comment]
Sure ... I'll get it in today.
