### ISSUE TITLE
Sample for creating cache profile doesn't actually contain a sample.

### ISSUE THREAD

**Issue by ctolkien** [aspnet/Docs#1723]
https://docs.asp.net/en/latest/performance/caching/response.html

Defines a route for Mvc, does not actual cover any code that configures a cache profile.

![image](https://cloud.githubusercontent.com/assets/515955/17122140/50fb99f4-531c-11e6-98b6-089638c7a0f6.png)

**Comment by Rick-Anderson** [comment]
@ctolkien  thanks for letting us know. Can you check my fix? You might need to ^F5 so you don't get a cached copy.
