### ISSUE TITLE
How to open first-web-api project?

### ISSUE THREAD

**Issue by zhouhao27** [aspnet/Docs#1739]
I didn't find any VS project file. Also my VS doesn't have an option to create a web-core-api template. What should I do? Thanks.

**Comment by Rick-Anderson** [comment]
Open project.json
Sounds like you don't have tooling installed if you don't get the Web API and Web App.
Follow the install instructions at https://docs.asp.net/en/latest/tutorials/first-mvc-app/start-mvc.html
