### ISSUE TITLE
deploy EF/MVC core  Azure

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1744]
- [ ]  migrations
- [ ]  links to logging

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie Looks like this one is covered by the [Publish an ASP.NET Core web app to Azure App Service using Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs) topic.

Logging will be covered in the upcoming Antares topics.
