### ISSUE TITLE
Installation guidelines for DNVM standalone on windows point to KVM

### ISSUE THREAD

**Issue by ctolkien** [aspnet/Docs#175]
http://docs.asp.net/en/latest/getting-started/installing-on-windows.html#install-asp-net-standalone

@powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.ps1'))"

**Comment by glennc** [comment]
Fixed
