### ISSUE TITLE
Change Default Port in ASP.NET MVC Core Kestrel

### ISSUE THREAD

**Issue by KiarashS** [aspnet/Docs#1750]
Dear,

I want change default port in ASP.NET MVC Core Kestrel from 5000 to 80 in Ubuntu, How i can do this work?

Thanks

**Comment by spboyer** [comment]
@KiarashS 
```
new WebHostBuilder()
    .UseUrls("http://*:5000;http://localhost:5001;https://hostname:5002")
```

There is a pending document for all the hosting options should be published very soon.
@ardalis

**Comment by Rick-Anderson** [comment]
It's documented in https://github.com/aspnet/Docs/pull/1702 which will be published soon in fundamentals/hosting.
