### ISSUE TITLE
client-side/using-gulp.rst "Using Gulp" 

### ISSUE THREAD

**Issue by bennedik** [aspnet/Docs#1751]
On the page https://docs.asp.net/en/latest/client-side/using-gulp.html
you write:

> The ASP.NET Core Web Application project template is used to help you get started designing and coding a new Web application in Visual Studio. It contains default functionality to demonstrate many aspects of ASP.NET. The template also includes Node Package Manager (npm) and Gulp, making it easier to add bundling and minification to a project.

The project template does no longer include Gulp nor npm. The documentation is out of date.

**Comment by Rick-Anderson** [comment]
@danroth27 should we update the doc or just delete it?

**Comment by bennedik** [comment]
It should still be useful to have documentation about how to use Gulp.

Looking at the current project template for an MVC Core application, any package added with Bower is written directly into the wwwroot/lib folder, and deployed to the server.
For many packages this will include samples and other things, that should definitely not be deployed.

Therefore I almost find the project template unusable in a production environment. Using Gulp seems to be the only solution, or maybe I am missing something here?

In any case, instructions for using Gulp should still be relevant and not be deleted.

**Comment by scottaddie** [comment]
@Rick-Anderson My opinion is that there's still value in having Gulp documentation; and, the [Bundler & Minifier extension](https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40) provides an option to revert back to Gulp. When your development workflow needs become more complex, Bundler & Minifier falls short.
