### ISSUE TITLE
Handling System.Web to Core [best practices]

### ISSUE THREAD

**Issue by muratg** [aspnet/Docs#1752]
_From @narenkv on July 20, 2016 5:11_

Hello all,

Is there any best practices or steps or senarios which would help people to migrate from .NET 4.x.y versions. 

Responding this will help many people in the world :-)  

/Naren

_Copied from original issue: dotnet/corefx#10166_

**Comment by muratg** [comment]
_From @lextm on July 20, 2016 13:23_

Have you gone through these?

https://docs.asp.net/en/latest/migration/index.html

If not, you should. Issues or questions on those materials can be submitted to

https://github.com/aspnet/Docs/issues

**Comment by muratg** [comment]
_From @narenkv on July 20, 2016 23:4_

Hello Lextm

Yes, But it helps to one extent. however the alternatives and not clearly articulated. Example System.Web references how to handle is not given. May be a sample conversion project with bare minimal code is shared will be of great help

Also heading mentions the documentation is limited to .0.0-rc2 versions and updates are yet to come.

/Naren

**Comment by muratg** [comment]
_From @joshfree on August 2, 2016 19:45_

@muratg can you help route this to an asp.net repo?

**Comment by muratg** [comment]
@narenkv not sure what you mean with "example System.Web references how to handle". System.Web is not used anymore, if that's what you're asking.

**Comment by narenkv** [comment]
Hello muratg,

Yes, We are looking for a example implementation. 

/Naren

**Comment by davidfowl** [comment]
This needs to be a thing that gets built up based on specific scenarios. ASP.NET Core is a different framework so it would be good to explain exactly what you're trying to convert.

**Comment by Rick-Anderson** [comment]
Closing for other higher priority issues.
