### ISSUE TITLE
Expanded coverage for .ConfigureServices()and .Configure() on WebHostBuilder?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1756]
@ardalis @Rick-Anderson @danroth27

@bluemmc points out in https://github.com/aspnet/Hosting/issues/820#issuecomment-237154466 that the ability to setup `.ConfigureServices()` and `.Configure()` on `WebHostBuilder` is lightly mentioned in the docs. I've been enjoying the pattern for a long time, and I agree that more devs might like it if they just knew a little more about it (e.g., see https://gist.github.com/GuardRex/f40f1b1414e175a6514f). Devs at Jabbr :skull: :cry: and Slack have implemented elements of this pattern from time to time.

The only place I could find it is in the last Note at https://docs.asp.net/en/latest/fundamentals/hosting.html?highlight=configureservices#setting-up-a-host. The Note could be broken out into the text with a short example if you wanted to expand the coverage a bit. Something that shows them both in use ...

> When setting up a host, you can provide `Configure` and `ConfigureServices` methods, instead of or in addition to specifying a `Startup` class (which must also define these methods if present - see `Application Startup`). Multiple calls to `ConfigureServices` will append to one another. Calls to `Configure` or `UseStartup` will replace previous settings.

```c#
// Set localEnvironment based on env vars, command line args,
// or other configuration sources
var localEnvironment = "Development";
var host = new WebHostBuilder()
    .ConfigureLogging(options => {
        options.AddConsole(LogLevel.Warning);
    })
    .UseKestrel()
    .UseContentRoot(Directory.GetCurrentDirectory())
    .UseEnvironment(localEnvironment)
    .UseIISIntegration()
    .ConfigureServices(services =>
    {
        services.AddMvc();
    })
    .Configure((app) =>
    {
        if (localEnvironment == "Production")
        {
            app.UseExceptionHandler("/Error");
        }
        else
        {
            app.UseDeveloperExceptionPage();
        }
        app.UseStaticFiles();
        app.UseMvcWithDefaultRoute();
    })
    .Build();
host.Run();
```

**Comment by Rick-Anderson** [comment]
@davidfowl  can you comment?

**Comment by ardalis** [comment]
I had this covered in an earlier draft of the Hosting doc. Maybe it could be a separate, more advanced topic on configuring that we could link to from the fundamentals topic?

**Comment by GuardRex** [comment]
Another possibility (which is prob a bad idea, but let's consider it for a sec) would be to mention this where the `Startup` class is covered at https://docs.asp.net/en/latest/fundamentals/startup.html. It could be a section at the end of that document.

The current note states ...

> When setting up a host, you can provide Configure and ConfigureServices methods, instead of or in addition to specifying a Startup class (which must also define these methods - see Application Startup).

If they go to the `Startup` doc at that point, the reader will just get `Startup` class info (no example of the alternate pattern) and even be confronted with this line ...

> In ASP.NET Core, the Startup class provides the entry point for an application, and is required for all applications.

... which isn't true (the "required" part), so it contradicts what they just read in the Hosting doc.

It might be a bad idea though to put a section dealing with `WebHostBuilder` `ConfigureServices` and `Configure` in the `Startup` doc. It's rather out-of-context to show that outside of the hosting doc.

**Comment by Rick-Anderson** [comment]
@davidfowl is there a use case for this?

**Comment by danroth27** [comment]
I agree that we should cover the .Configure and .ConfigureServices on WebHostBuilder. I don't think these should go into a more advanced topic - these methods are actually for simple use cases, not advanced ones. I think it would make sense to cover these in Startup article.

**Comment by ardalis** [comment]
Some scenarios I see:

- Add services in WHB.ConfigureServices which are then available to Startup ctor and Configure methods
- Call WHB.ConfigureLogging so that logging is available to all Startup methods (via DI)
- Use WHB Configure and ConfigureServices to easily set up hosts for integration tests (this is already covered somewhat in Testing Controllers but is buried in the sample code: https://github.com/aspnet/Docs/blob/master/aspnet/mvc/controllers/testing/sample/TestingControllersSample/tests/TestingControllersSample.Tests/IntegrationTests/TestFixture.cs#L34).

**Comment by danroth27** [comment]
I spoke with @davidfowl and we think what we have already in the [Hosting](https://docs.asp.net/en/latest/fundamentals/hosting.html) doc on these methods is sufficient. Most people should use a Startup class.

**Comment by ardalis** [comment]
More coverage of configuration with WHB is here, too: http://ardalis.com/configuring-aspnet-core-apps-with-webhostbuilder
