### ISSUE TITLE
Can't access the https://doc.asp.net site

### ISSUE THREAD

**Issue by wjzhou** [aspnet/Docs#1759]
When opening the doc site https://docs.asp.net. The following page is shown:

   \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|

Is that just me or do I access the wrong url?

**Comment by leosbrf** [comment]
Same here. What has happened?

**Comment by scotmeiste** [comment]
it appears to be back up now.

**Comment by pablotdv** [comment]
It seems that back

**Comment by wjzhou** [comment]
It works for me too.
