### ISSUE TITLE
Can we get documentation on sub-application support in .net core?

### ISSUE THREAD

**Issue by muratg** [aspnet/Docs#1764]
_From @wpostma on August 5, 2016 17:5_

It seems that deploying  sub-applications in IIS, with .net core 1.0 are not documented.

Sub-apps are referenced elsewhere in other issues:
https://github.com/aspnet/IISIntegration/issues/190

There's no full working example and no IIS configuration and example code or docs for it yet.  Or if there is, my google-fu is failing me.

_Copied from original issue: aspnet/IISIntegration#248_

**Comment by muratg** [comment]
_From @wpostma on August 5, 2016 17:7_

Here's where I think that docs might have existed:
https://docs.asp.net/en/latest/publishing/iis.html

**Comment by muratg** [comment]
_From @GuardRex on August 5, 2016 17:14_

Good idea for the sample, and I'll put this on my list for the next Publishing to IIS doc update, which is coming soon.

**Comment by Rick-Anderson** [comment]
@GuardRex  would you be able to do this? You could add it to https://docs.asp.net/en/latest/publishing/iis.html
We could consider making this a separate topic.

**Comment by GuardRex** [comment]
Yes. I think I can cover it concisely in there similar to the way I have it in the IIS Hotline doc on Slack. 

I'll also add one troubleshooting entry to cover when a dev has repeated the <handlers> section in the sub-app.

I have two other minor updates, too. I'll put up an issue first to cover/discuss the updates later today. I think the two minor ones are just language updates, so they might go into one PR, while the sub-app one is it's own PR.

**Comment by muratg** [comment]
Thanks @GuardRex!
