### ISSUE TITLE
mvc/controllers/filters.html#filter-scopes - incorrect method for adding global filter

### ISSUE THREAD

**Issue by aggieben** [aspnet/Docs#1770]
The documentation here: https://docs.asp.net/en/latest/mvc/controllers/filters.html#filter-scopes describes the way of adding global filters like this:

```
services.AddMvc(options =>
{
    options.Filters.Add(typeof(SampleActionFilter)); // by type
    options.Filters.Add(new SampleGlobalActionFilter()); // an instance - not really supported
});
```

The second method whereby a user would add an _instance_ of a filter to the filter collection is not supported in the current released version (1.0.0).

**Comment by ardalis** [comment]
What does "not really supported" mean, exactly? I just re-tested and it works as expected in 1.0.0.

**Comment by aggieben** [comment]
Well, that's a good question.  I also tried unsuccessfully to figure out what I meant, and it even turns out that I'm adding a filter to `MvcOptions` with an instance in my own code.  I suspect I just misunderstood the requirements of the constructor for the filter I was trying to use at the time, but I'm not sure.  I'll close this.
