### ISSUE TITLE
Update Bundling and Minification

### ISSUE THREAD

**Issue by spboyer** [aspnet/Docs#1786]
- [ ] Update Gulp & Grunt portions
- [ ]  Add Bundler Minifier : https://visualstudiogallery.msdn.microsoft.com/9ec27da7-e24b-4d56-8064-fd7e88ac1c40 and https://github.com/madskristensen/BundlerMinifier
- [ ] Update to match current templates
- [ ] Break in to Intro, 3 sub parts Bundler Minifier, Gulp, Grunt
- [ ] Covers #1751 

cc @danroth27

**Comment by spboyer** [comment]
@madskristensen - any additions?

**Comment by spboyer** [comment]
covers #1751

**Comment by spboyer** [comment]
@madskristensen what is the status on the templates moving forward? Seems that there is nothing in the newer templates using bundleconfig.json and BundlerMinifier.Core is no longer included.

**Comment by madskristensen** [comment]
The bundleconfig.json should still be in the template but we're not including the dotnet cli tool for it anymore. @phenning you didn't remove bundleconfig.json, right?

**Comment by phenning** [comment]
@madskristensen I just confirmed, bundleconfig.json is still in the StarterWeb base template.

**Comment by spboyer** [comment]
@phenning @madskristensen - is the expectation to have the devs add the nuget package then and/or use gulp or grunt or "roll your own"

**Comment by danroth27** [comment]
@madskristensen and if the story is to use the tool then why are we no longer including it? Why are we including a bundleconfig.json file in the template if nothing uses it?

**Comment by madskristensen** [comment]
bundleconfig.json is there for the VS extension to consume. When a user opens bundleconfig.json they are prompted to install the extensions. We're leaving out the CLI tools because of migration scenarios and the muddy upgrade story between 1.0.x and 1.1 for tooling packages. The goal is to completely replace bundleconfig.json with runtime bundling/minification which we'll be able to do around the .NET Core 2.0 time frame

**Comment by spboyer** [comment]
Is there an extension for VS Code? What if any is the xplat story here.

**Comment by madskristensen** [comment]
The xplat story is to install the CLI nuget package manually. It's explained here https://github.com/madskristensen/bundlerMinifier/wiki#visual-studio-code

**Comment by spboyer** [comment]
ok great. Thanks. we'll get the docs here updated.

**Comment by spboyer** [comment]
blocking issue: https://github.com/madskristensen/BundlerMinifier/issues/230

@madskristensen @danroth27

**Comment by madskristensen** [comment]
For .NET Core 1.0 you should use version 2.2.301

**Comment by danroth27** [comment]
@DamianEdwards
