### ISSUE TITLE
Get error "The name '_config' does not exist in the current context" when add Server-side behavior

### ISSUE THREAD

**Issue by wanzicaidi** [aspnet/Docs#179]
Following code does not pass build, that the build error says "The name '_config' does not exist in the current context"

    public IActionResult About()
    {
        string appName = _config.Get("ApplicationName");
        ....
    }

Did I miss any point, or anything wrong?

**Comment by danroth27** [comment]
We should remove the _config code.

**Comment by ardalis** [comment]
And update the code samples for this article to use literal include of real code files. Will do.
