### ISSUE TITLE
fundamentals/routing - clarify use of attributes

### ISSUE THREAD

**Issue by vaindil** [aspnet/Docs#1795]
As discussed in [this SO question](https://stackoverflow.com/questions/39008789), routing in MVC only functions if one of these three conditions is met. All routes otherwise return a 404.
- BOTH the class AND action have a `[Route]` attribute.
- NEITHER the class NOR the action has a `[Route]` attribute.
- The `[action]` parameter is set inside the class route: `[Route("[controller]/[action]")]`.

I think this should be clarified in the docs, as it took me and others a little while to figure it out.

The examples below assume a request to `/values/getfirst` for simplicity. The app was registered using `app.UseMvcWithDefaultRoute()`.

This works because no route attributes are set:

``` csharp
public class ValuesController
{
    [HttpGet]
    public IActionResult GetFirst()
    {
        return Ok();
    }
}
```

This also works because both have route attributes:

``` csharp
[Route("[controller]")]
public class ValuesController
{
    [Route("getfirst")]
    [HttpGet]
    public IActionResult GetFirst()
    {
        return Ok();
    }
}
```

This does not work because only the class has the attribute:

``` csharp
[Route("[controller]")]
public class ValuesController
{
    [HttpGet]
    public IActionResult GetFirst()
    {
        return Ok();
    }
}
```

This does work because the class route attribute specifies `[action]`:

``` csharp
[Route("[controller]/[action]")]
public class ValuesController
{
    [HttpGet]
    public IActionResult GetFirst()
    {
        return Ok();
    }
}
```

**Comment by ardalis** [comment]
@Rick-Anderson I can make a PR with this update if you like. I think it's good to add. Assign me if you want me to take care of it.

**Comment by Rick-Anderson** [comment]
@ardalis I"ll take care of it, I'm working on routing now.

> routing in MVC only functions if one of these three conditions is met. All routes otherwise return a 404.

 * BOTH the class AND action have a `[Route]` attribute.

The following works fine with no decoration on the class.

```
public class MyDemoController : Controller
{
    [Route("")]
    [Route("Home")]
    [Route("Home/Index")]
    public IActionResult MyIndex()
    {
        return View("Index");
    }
}
```

@rynowak  looks like we do need to clarify, Should we update the fundamentals routing or the MVC routing and with what?

**Comment by vaindil** [comment]
Sorry, I should have worded it as "routing in MVC only appears to function if..."; I hardly know what I'm talking about. Thank you for the quick response, I greatly appreciate it!

**Comment by Rick-Anderson** [comment]
So it looks like the rule is:
 If you add the  [Route] attribute to a  controller, you indicate that you want to start building a new route; any routes set in startup don't apply. Therefore each action requires a route attribute.

**Comment by rynowak** [comment]
@Rick-Anderson - this is an MVC feature not related to routing fundamentals.

Actions in MVC are either conventionally routed **or** attribute routed. Placing a route on the controller **or** the action makes it attribute routed.

**Comment by ardalis** [comment]
@Rick-Anderson Also note that if you have a Route on a controller, you don't *have* to have it on the action, if the class attribute includes action in it.

**Comment by rynowak** [comment]
> Also note that if you have a Route on a controller, you don't have to have it on the action, if the class attribute includes action in it.

This is not true. **any** route attribute on the controller makes **all** actions in the controller attribute routed, regardless of what constructs are used in the route.

**Comment by ardalis** [comment]
@rynowak Right, I was specifically addressing this from Rick's comment: "each action requires a route attribute". That's not necessarily true, right? If the controller route includes the action in it, the individual action methods do not each require a [Route] attribute (but are still going to use the route in the controller).

**Comment by rynowak** [comment]
>  If the controller route includes the action in it

This is not true. any route attribute on the controller makes all actions in the controller attribute routed, regardless of what constructs are used in the route.

**Comment by ardalis** [comment]
@rynowak Are you saying that any route attribute on the controller means all actions in that controller must have a [Route] attribute? I'm not questioning whether they're routed, only whether they require that attribute on them in the code.

**Comment by rynowak** [comment]
I am saying exactly what I mean. ANY route attribute on the controller makes all actions in the controller attribute routed.

```
[Route("foo")]
public class MyController : Controller
{
    public IActionResult Index() { ... }

    public IActionResult About() { ... }
}
```

Both `MyController.Index()` and `MyController.About()` are attribute routed actions that will match the URL `foo`.

**Comment by ardalis** [comment]
That's true but not useful, since that would yield this:
AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

However, this would work fine:
[Route("foo/[action]")]

and so would this:
[Route("foo")]
public class MyController : Controller
{
  [Route("Index")]
  public IActionResult Index() {...}

  [Route("About")]
  public IActionResult About() {...}
}
Right?

I'm just looking for good examples for Rick to offer in his article.

**Comment by rynowak** [comment]
Yes, absolutely - and both of your examples are fine. I just want to make sure we're crisp on what it actually means.

**Comment by guardrex** [comment]
@scottaddie #1882 fixes this but it didn't auto-close the issue ... maybe because the "fixes" was lowercase over there ... or perhaps because it wasn't in the initial comment.

https://github.com/aspnet/Docs/pull/1882#issuecomment-247465480

Either way 🎂 :tada: 🎈 I think this can close 🎈 :tada: 🎂 .
