### ISSUE TITLE
Debugging MVC 6

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#180]
•         If you don’t’ have a web.config, deploy generates one for you.
•         If you have a web.config, deploy inserts the markup into its web.config.
•         You must put web.config in the www folder.
•         You can quickly examine the web.config via KUDU

**Comment by danroth27** [comment]
@Rick-Anderson This doesn't seem like it merits a completely new topic, but maybe we can add these details to an existing/planned topic under [Publishing and Deployment](http://docs.asp.net/en/latest/publishing/index.html).

**Comment by Rick-Anderson** [comment]
@danroth27  Customers that get a 500 error (which contains no information) will want to know how to add web.config. How about I put the information in Publishing and Deployment and add a link in the diagnostics "See deploying web.config to get detailed error messages".

**Comment by Rick-Anderson** [comment]
This info was added to diagnostics
