### ISSUE TITLE
Make make html be as picky as Travis

### ISSUE THREAD

**Issue by blowdart** [aspnet/Docs#1805]
Currently make html run locally does not treat warnings as errors.

The Travis build does treat warnings as errors.

So a successful local built can fail on the CI.

The local build should match the behaviour of the CI build.

**Comment by spboyer** [comment]
@blowdart - can you give me an example? One for sure is case specific issues.

**Comment by blowdart** [comment]
https://github.com/aspnet/Docs/pull/1804 - the first checkin

This compiled just fine on my local clone, with warnings about not being able to syntax highlight 3 HTML sections. On checkin Travis rejected it because the warnings became blocking errrors.
