### ISSUE TITLE
Your First ASP.NET Core Application on a Mac Using Visual Studio Code, does not deploy to azure

### ISSUE THREAD

**Issue by jmarolf** [aspnet/Docs#1806]
Looking at this tutorial: [Your First ASP.NET Core Application on a Mac Using Visual Studio Code
](https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html) [[source](https://github.com/aspnet/Docs/blob/master/aspnet/tutorials/your-first-mac-aspnet.rst)]

under [Initialize Azure Website
](https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html#initialize-azure-website)

- Create a new Web App (https://tryappservice.azure.com/) takes me to a page which looks different from the documentation
- link  continuous deployment using Git (https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/) returns 404
- Most unfortunately, pushing to the newly created azure site does not appear to deploy anything after running:

<details>
   <summary>Click to expand</summary>

```
C:\Users\jmarolf\OneDrive\Code\aspnetcoreapp (master)
λ git push azure master
Counting objects: 28, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (24/24), done.
Writing objects: 100% (28/28), 40.72 KiB | 0 bytes/s, done.
Total 28 (delta 2), reused 0 (delta 0)
remote: Updating branch 'master'.
remote: Updating submodules.
remote: Preparing deployment for commit id 'b91a1f6722'.
remote: Generating deployment script.
remote: Generating deployment script for Web Site
remote: Generated deployment script files
remote: Running deployment command...
remote: Handling Basic Web Site deployment.
remote: KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
remote: Copying file: '.gitignore'
remote: Copying file: 'Program.cs'
remote: Copying file: 'project.json'
remote: Copying file: 'project.lock.json'
remote: Copying file: 'Startup.cs'
remote: Copying file: '.vscode\launch.json'
remote: Copying file: '.vscode\tasks.json'
remote: Copying file: 'bin\Debug\netcoreapp1.0\aspnetcoreapp.deps.json'
remote: Copying file: 'bin\Debug\netcoreapp1.0\aspnetcoreapp.dll'
remote: Copying file: 'bin\Debug\netcoreapp1.0\aspnetcoreapp.pdb'
remote: Copying file: 'bin\Debug\netcoreapp1.0\aspnetcoreapp.runtimeconfig.dev.json'
remote: Copying file: 'bin\Debug\netcoreapp1.0\aspnetcoreapp.runtimeconfig.json'
remote: Copying file: 'obj\Debug\netcoreapp1.0\.IncrementalCache'
remote: Copying file: 'obj\Debug\netcoreapp1.0\.SDKVersion'
remote: Copying file: 'obj\Debug\netcoreapp1.0\dotnet-compile-csc.rsp'
remote: Copying file: 'obj\Debug\netcoreapp1.0\dotnet-compile.assemblyinfo.cs'
remote: Copying file: 'obj\Debug\netcoreapp1.0\dotnet-compile.rsp'
remote: Finished successfully.
remote: Running post deployment command(s)...
remote: Deployment successful.
To https://$14242c06-0ee0-4-231-b9ee:sJovw9CRtu0rF3qp1zMMhBMH6mQs7XYnNvwEEJERbvCE5jFvcgsjhpeKtufu@14242c06-0ee0-4-231-b9ee.scm.azurewebsites.net/14242c06-0ee0-4-231-b9ee.git
 * [new branch]      master -> master
```

</details>

I see this: 
![image](https://cloud.githubusercontent.com/assets/9797472/17874848/1a7c6422-6883-11e6-9fae-81241832eb10.png)

Not this: 
![image](https://cloud.githubusercontent.com/assets/9797472/17874863/2c06307e-6883-11e6-86e3-995cf6ab6388.png)

Which I see if I debug locally.

**Comment by spboyer** [comment]
@jmarolf 
Thanks for reporting the broken link on the Azure instructions for deployment.  Here is a corrected one: https://azure.microsoft.com/en-us/documentation/articles/app-service-continous-deployment/

The (https://tryappservice.azure.com/) link is for Azure new customers, if you have an account already you can ignore that link and just create a new App Service for a Website and link your newly created GitHub repo for deployment as explained in the link I provided.

To address seeing something different from what you are generating and what the "tryappservice" is generating; that is because each is using a different template.

**Comment by jmarolf** [comment]
@spboyer what does deploying my code do then? If I can't see my changes after a `git push` how am I supposed to use azure?  How can I override the template with my own code?  Seeing my actual code runing on azure would seem to be the entire point of this.

**Comment by spboyer** [comment]
If you follow the tutorial : [Your First ASP.NET Core Application on a Mac Using Visual Studio Code](https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html) 

* create the git repository
* git push your code to the new repo
* create a new Website on Azure (https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-get-started/)
* Setup the Continuous Deployment (https://azure.microsoft.com/en-us/documentation/articles/app-service-continous-deployment/) 

Every time you push your code to the repo, the web site will update with the new changes, provided that there are no errors.

**Comment by jmarolf** [comment]
@spboyer right, and I am reporting that this is not working.  If you follow those directions you will not get your changes deployed

**Comment by jmarolf** [comment]
@spboyer also, "Deploy an ASP.NET web app to Azure App Service, using Visual Studio" isn't what I want.  Is this impossible to do with Visual Studio Code on a Mac? Why have this article if it is not possible.
