### ISSUE TITLE
Separate Grunt and Gulp (or lead with Gulp)

### ISSUE THREAD

**Issue by calvinward** [aspnet/Docs#181]
Out of the box, ASP.NET 5 is implemented with Gulp. 

However when reading the docs, they start with Grunt, which by itself isn't bad, but if the developer skips to Gulp because their project begins that way, and then reviews documentation that has comments like, "The code below assigns the same tasks used in the Grunt example...", it puts the developer in the position of having to go back each time to ensure nothing is missed in the explanation.

Options:
* Write each topic independent of each other and list Gulp first. 
* Start with Gulp and have Grunt reference it, instead of the other way around

**Comment by danroth27** [comment]
Yup, this is a known issue. We started writing the Grunt content before we made the switch to use Gulp by default. We plan to update the docs to give Gulp a fuller treatment.
