### ISSUE TITLE
Add a link to a working sample to the cookie sharing doc

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1812]
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing

I think we might be able to link to https://github.com/aspnet/Identity/tree/master/samples/Interop4.5

**Comment by danroth27** [comment]
Looks like there the sample needs a few updates: https://github.com/aspnet/Identity/issues/682

**Comment by Rick-Anderson** [comment]
@HaoK  where is the sample for Interop with 4.5 (doc/sample story) #682 and is it OK to link to it?

**Comment by HaoK** [comment]
@blowdart I believe you had this working in one of your personal repos?

**Comment by HaoK** [comment]
For cookie sharing specifically its here: https://github.com/blowdart/idunno.CookieSharing
