### ISSUE TITLE
Help users pick between .NET Core and .NET Fx when getting started

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1813]
Examples of customer confusion:
- http://stackoverflow.com/questions/37627234/visual-studio-2015-web-application-net-core-vs-net-framework
- http://forums.asp.net/t/2101151.aspx?ASP+NET+MVC+Multiple+Deployments+Frameworks+Same+Codebase

We have https://docs.asp.net/en/latest/fundamentals/choosing-the-right-dotnet.html but users really need to understand this decision when they are getting started (i.e. which VS template to fix?).

**Comment by Rick-Anderson** [comment]
- [ ] Getting started tutorials point to https://docs.asp.net/en/latest/fundamentals/choosing-the-right-dotnet.html
- [ ] add to https://docs.asp.net/en/latest/intro.html

**Comment by Rick-Anderson** [comment]
@danroth27  see https://microsoft.sharepoint.com/teams/DotNetStrategyTeam/_layouts/15/WopiFrame.aspx?sourcedoc=%7B763DACCD-8008-489E-B83C-1E7BE17BD361%7D&file=When%20to%20use%20dotNET%20Core%20or%20dotNET%20Framework.docx&action=default

I have a few cycles so let me know if this is something I should work on.

**Comment by danroth27** [comment]
Looks like the official doc on choosing between .NET Core and .NET is located here: https://docs.microsoft.com/en-us/dotnet/articles/standard/choosing-core-framework-server. We should remove our doc and link to the official one.

**Comment by Rick-Anderson** [comment]
@tdykstra  an easy one for you.
