### ISSUE TITLE
readthedocs vs docs.microsoft.com

### ISSUE THREAD

**Issue by totht91** [aspnet/Docs#1814]
Why are the asp.net core docs powered by the read-the-docs engine, when there is a new docs engine the [docs.microsoft.com]()? There is a misslead in the [docs.microsoft.com]() site that the asp.net core docs is powered by the new engine. Is there any plan to migrate this to the new one?

**Comment by Rick-Anderson** [comment]
We do plan to eventually move to docs.ms.com. At the time we started  ASP.NET Core, Read The Docs was the best platform.

**Comment by totht91** [comment]
Thank you! I got answers on twitter too. :)

**Comment by GuardRex** [comment]
@Rick-Anderson One other quick ?: docs.microsoft.com doesn't seem to be searchable. I mean I don't see a search box anywhere on the pages for .NET Core docs, and that's been a pain point (for me anyway) finding things over there. Is the preferred method to use search operators? ... e.g. for Bing or Google ...
```
<search term | "search phrase"> site:docs.microsoft.com
```

**Comment by Rick-Anderson** [comment]
@GuardRex  They're working on it.
