### ISSUE TITLE
Tutorial uses old framework naming

### ISSUE THREAD

**Issue by eduaglz** [aspnet/Docs#182]
At the tutorial: `Your First ASP.NET 5 Application Using Visual Studio` ( [link](http://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html#create-a-new-asp-net-5-project) ) below the section `Adding Server-Side Behavior` it says the following: 
> Now we can build the solution. Since the default web template targets both the full .NET and .NET Core, we expect the build to fail when it tries to access the Environment.MachineName and Environment.OSVersion variables in HomeController. This behavior won’t work in .NET Core, so we can comment it out. Open project.json and modify the “frameworks” key as shown:
```
"frameworks": {
    "aspnet50": { }/*,
    "aspnetcore50": { }*/
},
```

Shouldn't it be changed to the new framework names:
````
"frameworks": {
    "dnx451": { }/*,
    "dnxcore50": { }*/
},
```

**Comment by davidfowl** [comment]
Yes it should be. Care to send a pull request fixing it?

**Comment by eduaglz** [comment]
Sure, I'll do it
