### ISSUE TITLE
How I can change a MVC4 project to .netCore

### ISSUE THREAD

**Issue by shcemApp** [aspnet/Docs#1820]
Hi All:

I want to change a MVC4 project to .netCore, what can I do？

**Comment by GuardRex** [comment]
I would like to say "See https://docs.asp.net/en/latest/migration/mvc.html" ... but it hasn't been updated yet for RTM. Doc updates are on-going.

Your best bet is to start right at the top at https://docs.asp.net/en/latest/intro.html and work right down the docs taking it all in and studying the examples. Any doc that hasn't been made ready for RTM (only a handful at this point) will have a large banner to that effect. You'll probably also want to take in the .NET Core docs at https://docs.microsoft.com/en-us/dotnet/articles/core/index.

If you get stuck on something and need help, hit up the devs on Slack. Popular channels are announcements, aspnet-core, dotnet-core, general, identity, iis, kestrel, mvc, logging, razor, and xunit. Many devs hang out in the general channel and are happy to help with general refactoring issues. You can get in at http://tattoocoder.com/aspnet-slack-sign-up/

**Comment by Rick-Anderson** [comment]
@spboyer @danroth27  I'm closing this. The migration doc will have to do.
