### ISSUE TITLE
Provide appropriate headers so that browsers/RSSreaders can find the ASP.NET Core docs RSS feed

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1822]
We do have am RSS feed (http://docs.asp.net/en/latest/rss.xml), but it isn't discoverable.

**Comment by blowdart** [comment]
Put the following in every page's head section

  <link rel="alternate" type="application/rss+xml" href="https://docs.asp.net/en/latest/rss.xml" title="RSS feed for documentation additions and updates">

**Comment by RehanSaeed** [comment]
What happened to the feed. Doesn't seem to work anymore. Can we have it back?
