### ISSUE TITLE
What is project.fragment.lock.json for and should it also be ignored?

### ISSUE THREAD

**Issue by OsirisTerje** [aspnet/Docs#1825]
I see this file being generated, and I see that the project.lock.json is being ignored, but what is this fragment lock file?

Ref https://github.com/NuGet/Home/issues/3121
and
https://github.com/aspnet/Docs/issues/171

And, if so, could it be an idea to just add *.lock.json in the gitignore - is there any reason not to exclude also all possible variations of this?

**Comment by spboyer** [comment]
@rrelyea can you address?

**Comment by spboyer** [comment]
@OsirisTerje yes you can add `*.lock.json` to your gitignore. there is no reason to commit this to your repo.

**Comment by OsirisTerje** [comment]
Thanks! 
Will you update the standard gitignore on github https://github.com/github/gitignore   with this too?

**Comment by spboyer** [comment]
@OsirisTerje it is already there https://github.com/github/gitignore/blob/master/VisualStudio.gitignore#L45

**Comment by OsirisTerje** [comment]
yep,  project.fragment.lock.json is there, but not *.lock.json :-)

**Comment by spboyer** [comment]
currently, project.lock.json and project.fragment.lock.json are the only files that are produced that match that pattern. There are no expected additions.

**Comment by aszalavitz** [comment]
What generates project.fragment.lock.json?  Whatever it is has a bug or a configuration issue, and I don't know where to submit it.  I've asked on StackOverflow because I'm hoping I can configure to fix the issue, so here's the link http://stackoverflow.com/q/40309163/967448.  I can re-iterate that here, if it helps, so let me know.
