### ISSUE TITLE
Convert issue markdown to html

### ISSUE THREAD

**Issue by kkamegawa** [aspnet/Docs#1828]
[Use VSTS to Build and Publish to an Azure Web App with Continuous Deployment
](https://docs.asp.net/en/latest/publishing/vsts-continuous-deployment.html) 's issue.
Step3 in "Setup VSTS Build"

Wrong:
> Arguments: publish src/WebApplication –configuration $(BuildConfiguration) –output $(PublishOutput)

Correct:
> Arguments: publish src/WebApplication --configuration $(BuildConfiguration) --output $(PublishOutput)

Markdown is right, but html convertor wrong.
![2016-08-30](https://cloud.githubusercontent.com/assets/1450745/18069256/dd7f5b84-6e80-11e6-8742-faa778984dba.png)

**Comment by spboyer** [comment]
Fixed in #1821
