### ISSUE TITLE
Inherited Controllers

### ISSUE THREAD

**Issue by Slacquer** [aspnet/Docs#1834]
Is there any effort to having Swashbuckle read inherited comments?  I am new to Swashbuckle, but I found myself creating OperationFilters for the metadata below, I have controllers as such:

        /// <summary>
        ///     Posts a resource.
        /// </summary>
        /// <param name="resource">The resource.</param>
        /// <returns>IActionResult.</returns>
        /// <response code="400">The supplied [TResource] resource data is invalid</response>
        /// <response code="409">The specified [TResource] resource already exists</response>
        /// <response code="201">Successfully created a new [TResource] resource</response>
        [HttpPost]
        public async Task<IActionResult> PostResource([FromBody] TResource resource)
        {
        }

**Comment by spboyer** [comment]
Ask this on the swashbuckle repository https://github.com/domaindrivendev/Ahoy/issues
cc:/ @domaindrivendev
