### ISSUE TITLE
Add Rewrite middleware documentation

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Docs#1839]
This should be in by 1.1. This was my intern project!
See: 
https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.Rewrite

**Comment by spboyer** [comment]
@ZestyBread this was a great piece of work. Can you add a README to the repo? and possibly add here what should be covered in a doc. 

For a presentation of the stuff Justin is referencing here see: https://www.youtube.com/watch?v=gDEpkzlx3WU&list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&index=0

**Comment by spboyer** [comment]
@danroth27

**Comment by glennc** [comment]
@natemcmaster did some perf charts in an issue here: https://github.com/aspnet/BasicMiddleware/issues/73

It would be good to show those when we talk about not having lots of rules. Updated if the implementation has changed enough to make them different.

**Comment by danroth27** [comment]
@glennc Can we instead digest the perf data into concrete guidance? I'd prefer to not have to maintain these perf charts in the docs long term. They will almost certainly go stale.

**Comment by GuardRex** [comment]
This was covered by https://github.com/aspnet/Docs/pull/2446

**Comment by spboyer** [comment]
Fixed by #2446
