### ISSUE TITLE
Document how to load Session asynchronously in the Application State document

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Docs#1840]
https://docs.asp.net/en/latest/fundamentals/app-state.html

The default session provider in ASP.NET Core will only load the session record from the underlying `IDistributedCache` store asynchronously if the `ISession.LoadAsync` method is explicitly called **before** calling the `TryGetValue`, `Set` or `Remove` methods. Failure to call `LoadAsync` first will result in the underlying session record being loaded synchronously, which could potentially impact the ability of an application to scale.

If applications wish to enforce this pattern, they could wrap the `DistributedSessionStore` and `DistributedSession` implementations with versions that throw if the `LoadAsync` method has not been called before calling `TryGetValue`, `Set` or `Remove`, and register the wrapped versions in the services container.

**Comment by Rick-Anderson** [comment]
fixed in #2489

**Comment by laultman** [comment]
I have read the discussion about the LoadAsyn() call. It is distressing to know that this must be done to scale the app and I cannot find an implementation example anywhere. MS docs have nothing other than the normal boilerplate. Is there an actual example. Can't seem to find one. I need to ensure that we can scale an application for a large health care agency with an Azure solution.

**Comment by Rick-Anderson** [comment]
@DamianEdwards can you assign someone to respond to this and possibly create a sample app?

@laultman  contact me if we don't get a response in the next week.

**Comment by laultman** [comment]
Thanks, we are working on an Azure app for Florida Department of Health and the CDC for Miami/Dade.  We have a requirement to be able to scale for the general population to access CDC and Health data and to use the site for pre-screening data collection.

Thanks, Larry

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Rick-Anderson** [comment]
@Tratcher 	please review.
when you close #4837 can you provide a sample?

**Comment by Tratcher** [comment]
Was that the right issue link?

Not much to show, it's just calling `HttpContext.Session.LoadAsync()` before you start using session. The only code reference I see is the unit tests for the error cases:
https://github.com/aspnet/AspNetCore/blob/cd0eab88eaa230fa276c27ab5dc71ea267efe14f/src/Middleware/Session/test/SessionTests.cs#L654-L656

**Comment by Rick-Anderson** [comment]
>Was that the right issue link?

Oops https://github.com/aspnet/AspNetCore/issues/4837

**Comment by sharadshahihw** [comment]
Does anyone have code sample to load session asynchronously to make it work with ISession.Set, TryGetValue, Remove?
