### ISSUE TITLE
Documentation suggests using outdated version of Angular (1.x) and outdated package manager (Bower)

### ISSUE THREAD

**Issue by dsaf** [aspnet/Docs#1844]
https://docs.asp.net/en/latest/client-side/angular.html

I want to use cutting edge tech - ASP.NET Core and Angular 2. However I just learned that Bower/NuGet is useless for Angular 2. I don't yet know how npm-friendly is VS 2015.3. It would be great to update the documentation, since Angular 2 is quite stable starting from rc5-6. Thanks.

Update: just learned that Bower is dying and front-end community is switching to NPM.

**Comment by spboyer** [comment]
@dsaf - Angular 1.x is not outdated, it is still being maintained and updated on a regular basis by the Angular team. Angular 2 assets are only being distributed via npm which is completely supported by Visual Studio 2015 out of the box.
