### ISSUE TITLE
Last [Fact] for https://github.com/aspnet/Docs/blob/master/aspnet/mvc/controllers/testing.rst is incomple

### ISSUE THREAD

**Issue by gerryLowry** [aspnet/Docs#1847]
https://docs.asp.net/en/latest/mvc/controllers/testing.html

`[Fact]
        public async Task ForSessionReturnsIdeasForValidSessionId()
        {
            // Arrange
            var testSession = Startup.GetTestSession();

```
        // Act
        var response = await _client.GetAsync("/api/ideas/forsession/1");

        // Assert
        response.EnsureSuccessStatusCode();
        var ideaList = JsonConvert.DeserializeObject<List<IdeaDTO>>(
            await response.Content.ReadAsStringAsync());
        var firstIdea = ideaList.First();`
```

......................... above is incomplete

https://github.com/aspnet/Docs/blob/master/aspnet/mvc/controllers/testing.rst

**Comment by spboyer** [comment]
@gerryLowry could you be more specific as to what is incomplete? Are you looking for the entire file to be represented there? The full sample code is available on github - https://github.com/aspnet/Docs/tree/master/aspnet/mvc/controllers/testing/sample

**Comment by danroth27** [comment]
Those methods in the code block should be dedented as well.

**Comment by ardalis** [comment]
This appears to be resolved.
