### ISSUE TITLE
Grunt-gulp, indicate to create JavaScript file instead of TypeScript file

### ISSUE THREAD

**Issue by Kelderro** [aspnet/Docs#185]
The grunt-gulp.rst file (https://github.com/aspnet/Docs/blob/master/docs/client-side/grunt-gulp.rst) contains a typing mistake on row 54.
Row 54 indicates that the user should create a file named food.js. The content of the file is TypeScript. The correct extension of the file should be ts and not js.

**Comment by ardalis** [comment]
Fixed, thanks!
