### ISSUE TITLE
Document MapAreaRoute in the Areas doc

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1852]
Looks like we have a nice extension method for adding routes for a specific area:

https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Builder/MvcAreaRouteBuilderExtensions/index.html?highlight=maparearoute#Microsoft.AspNetCore.Builder.MvcAreaRouteBuilderExtensions.MapAreaRoute

We should include this in the [Areas](https://docs.asp.net/en/latest/mvc/controllers/areas.html) doc.

**Comment by guardrex** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.mvcarearoutebuilderextensions?view=aspnetcore-2.0

**Comment by guardrex** [comment]
@danroth27 It's (somewhat*) documented over here :point_right: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#areas

somewhat* = Lacking API links and overloads info.

Seems a bit scatter-brained 😵 to have Areas documented in two places. Should most of the Routing-Areas content be integrated into the Areas topic, and then the Routing topic can briefly address Areas routing and link over to the Areas topic for details?

**Comment by Rick-Anderson** [comment]
moved to #10503
