### ISSUE TITLE
call an API in c# code in ASP.NET Core

### ISSUE THREAD

**Issue by 60662** [aspnet/Docs#1857]
call an API in c# code in ASP.NET Core

I'm looking for a call service to send SMS in the c# code. He composed it a URI like https://smsapi.free-mobile.fr/sendmsg? user = 10606753 & pass = cle_identification & msg = Hello % 20World % 20!
How to make

Thank you for avence JP

**Comment by spboyer** [comment]
See [this question on Stackoverflow](http://stackoverflow.com/questions/30304365/using-httpclient-in-asp-net-5-app)
