### ISSUE TITLE
make html error

### ISSUE THREAD

**Issue by ifairy** [aspnet/Docs#1863]
# Warning, treated as error:
D:\Software\download\Docs-master\aspnet\fundamentals\app-state.rst:148: WARNING: dn:iface reference target not found: ~Microsoft.AspNetCore.Http.ISession

**Comment by spboyer** [comment]
Warnings are now treated as errors: see #1805

**Comment by ncarandini** [comment]
Ok, I understand that warnings must be treated as errors, but how can I solve the warning?
I'm on the master branch, and I see that the file
`C:\Git\aspnet-docs\api\autoapi\Microsoft\AspNetCore\Http\ISession\Index.rst`
do exist and in fact it works on the live documentation (https://docs.asp.net/en/latest/fundamentals/app-state.html).
So why I get the Warning?

**Comment by spboyer** [comment]
what is the full error you are getting? Can you include the few lines above and below?

**Comment by ncarandini** [comment]
The make html command produce this output:
```
Running Sphinx v1.4.6
loading pickled environment... not yet created
loading intersphinx inventory from ../common/api.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 186 source files that are out of date
updating environment: 186 added, 0 changed, 0 removed
reading sources... [100%] tutorials/your-first-mac-aspnet                      ioniderston-details
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] tutorials/your-first-mac-aspnet                       oniderston-details

Warning, treated as error:
c:\Git\aspnet-docs\aspnet\fundamentals\app-state.rst:148: WARNING: dn:iface reference target not found: ~Microsoft.AspNetCore.Http.ISession
```

**Comment by ncarandini** [comment]
Maybe a problem with intersphinx_mapping?
I'm just starting to learn Sphinx, but I can see that the unresolved reference is in another project (the api one) and this is the mappimg that I've found in the conf.py file:
```
# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'api': ('http://docs.asp.net/projects/api/en/latest', '../common/api.inv')
}
```

**Comment by ncarandini** [comment]
Maybe this can be interesting. Trying to execute intersphinx as a pyton command:
`c:\Git\aspnet-docs\common>python -m sphinx.ext.intersphinx http://docs.asp.net/projects/api/en/latest`
give me this error:
`intersphinx inventory 'http://docs.asp.net/projects/api/en/latest' not readable due to AttributeError: 'MockApp' object has no attribute 'info'`

So maybe my mapping fails silently and I don't have an updated "common/api.inv" file?
