### ISSUE TITLE
Missing HttpMethodAttribute error in swagger tutorial

### ISSUE THREAD

**Issue by chrstnbrn** [aspnet/Docs#1865]
If I follow the instructions of the swagger tutorial (https://docs.asp.net/en/latest/tutorials/web-api-help-pages-using-swagger.html) I'm getting an internal server error when trying to get the swagger.json. Swashbuckle suggests this is because of a missing HttpMethodAttribute. After adding [HttpGet] to GetAll in the TodoController everything works fine. Maybe you could include this in the docs (either in the swagger tutorial or the web api tutorial).

**Comment by spboyer** [comment]
@chrstnbrn - yes, need to add this to the code used as the starter. Thanks for the note. I'll get that in asap.
