### ISSUE TITLE
migration/mvc.rst: Update doc from RC2 to RTM

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#1866]
The code samples need to be updated to RTM. The Gulp & NPM sections should be replaced with the BundlerMinifier.Core information.

@spboyer Is anyone already working on updating this doc? If not, I'll take it.

**Comment by spboyer** [comment]
I am working on the Gulp, Grunt, BundlerMinifier story

**Comment by spboyer** [comment]
@scottaddie THIS doc, go ahead and take it.  I am working on #1786

**Comment by Rick-Anderson** [comment]
does PR #1901 address this?
