### ISSUE TITLE
Kestrel step-by-step missing in "Publish to a Linux Production Environment"

### ISSUE THREAD

**Issue by v1n1akabozo** [aspnet/Docs#1868]
Running 'dotnet publish' will give me only dll's and the cshtml files, and or i am missing something, or the dotnet run command will only work if you have the source code in the folder it is targetting because it always asks for the project.json file, so both commands don't work along opposing what the text leads.

The only way to actually run the self contained directory is through the 'supervisor' ? I managed to get nginx working but the bit of code that is supposed to handle supervisor configuration should be commented. Am i supposed to place my newly created app in that folder ('/var/....')? 

Edit: This line in particular might be missleading:

"Try and run the app and navigate to http://<serveraddress>:<port> in your browser to see if the application runs fine on Linux".

If i've just published the app i won't be able to run it using 'dotnet run'. This is okay if i'm developing in the Linux environment and the production one runs Linux too, but it's not always the case so it sounds as if i should deploy source code to production in order to test it.

**Comment by Rick-Anderson** [comment]
@glennc  @spboyer  please review

**Comment by Rick-Anderson** [comment]
see also #1251

**Comment by glennc** [comment]
`dotnet run` is for development. Running a published app is done with `dotnet app.dll` or `app` if you are self contained and have an executable binary. Anything that implied you should use `dotnet run` on your server is definitely wrong.

**Comment by v1n1akabozo** [comment]
@glennc i'm aware, i just think the text is a lil bit missleading, i could get it working on centOS though. Someone that can't associate supervisor to IIS's behavior on creating and managing application pools will probably have a hard time figuring out how the kestrel server will ever be activated.

**Comment by glennc** [comment]
What doc are we talking about here? https://github.com/aspnet/Docs/blob/master/aspnet/publishing/linuxproduction.rst tells you how to setup a supervisor. Is that the doc that is confusing?

**Comment by brandonmartinez** [comment]
The confusion for me was that I didn't have the dotnet cli installed on my server, as it wasn't listed under prerequisites. Should this be added there?

**Comment by ckelner** [comment]
@glennc I believe those are the docs in question.  

I think the specific part that could use some work is: https://github.com/aspnet/Docs/blame/master/aspnet/publishing/linuxproduction.rst#L26-L29 -- providing examples of what to run would be helpful, e.g. providing `donet /<path>/HelloMVC.dll`

**Comment by spboyer** [comment]
supervisor is no longer a recommendation for montitoring Kestrel, the document has been updated to prescribe using `systemd`.
