### ISSUE TITLE
fundamentals/hosting HOSTING

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1870]
- [ ] See https://github.com/aspnet/Mvc/issues/5155#issuecomment-246593871
- [ ] Clarify in the Hosting doc that ApplicationName must be the name of the application assembly 
- [ ] UE edit
- [ ]  link to IHostingEnvironment and how to consume it at runtime per @yishaigalatzer

**Comment by guardrex** [comment]
@Rick-Anderson @tdykstra Since the first two on the list are squared away, I'll see about knocking out the other two items soon.

**Comment by Rick-Anderson** [comment]
@guardrex  sounds great. BTW, [@]tdykstra moved to another team :(

**Comment by guardrex** [comment]
@Rick-Anderson @danroth27 @ardalis @davidfowl I'm almost done with the PR, but I have a few questions:

The current outline is ...

* Hosting in ASP.NET Core
  * What's a host?
    * What's the difference between a host and a server?
  * Setting up a host
  * Configuring a host
    * Host configuration values
    * Overriding configuration
    * Ordering importance
  * IHostingEnvironment interface
  * IApplicationLifetime interface
  * Additional resources

**Question 1**: I'd like to refactor the introductory content into a straight *introduction* without questions ...

* Hosting in ASP.NET Core
  * Introductory paragraph includes the "What's a host?" and "What's the difference between a host and a server?" content removing the questions (in those headers).
  * Setting up a host
  * Configuring a host
    * Host configuration values
    * Overriding configuration
    * Ordering importance
  * IHostingEnvironment interface
  * IApplicationLifetime interface
  * Additional resources

**Question 2**: Does the topic need to surface any or all of these other config keys that aren't currently described in the topic?

* HostingStartupAssembliesKey: *hostingStartupAssemblies*
* PreferHostingUrlsKey: *preferHostingUrls*
* PreventHostingStartupKey: *preventHostingStartup*
* ShutdownTimeoutKey: *shutdownTimeoutSeconds*

**Question 3**: The current topic doesn't get into `IWebHost` startup and config. It goes on `WebHostBuilder` everywhere. There's nothing over in [Application Startup in ASP.NET Core](https://docs.microsoft.com/aspnet/core/fundamentals/startup). I presume you want `IWebHost` coverage here. If yes, then I presume you want the current `WebHostBuilder` content to appear in 1.x tabs with the new `IWebHost` bits in 2.x tabs? ... or do you want all of the `WebHostBuilder` stuff *converted into* `IWebHost` examples?

**Comment by danroth27** [comment]
> I'd like to refactor the introductory content into a straight introduction without questions 

Sounds fine

> Does the topic need to surface any or all of these other config keys that aren't currently described in the topic?

Yes, I think so. @Tratcher any concerns?

> The current topic doesn't get into IWebHost startup and config . . . I presume you want IWebHost coverage here.

Yes, `IWebHost` should be covered in this topic. What content specifically do you want to add?

> I presume you want the current WebHostBuilder content to appear in 1.x tabs with the new IWebHost bits in 2.x tabs?

`IWebHost` isn't new in 2.0. Are you maybe referring to the new static helper methods on the `WebHost` class?

**Comment by guardrex** [comment]
@danroth27 Yes, my bad ... nevermind on **Question 3**. It's been several days since I worked on the PR and didn't realize it was handled here. We're good on that point.

**Comment by Tratcher** [comment]
Go ahead.

**Comment by scottaddie** [comment]
@guardrex Do you plan to update [Application Startup in ASP.NET Core](https://docs.microsoft.com/aspnet/core/fundamentals/startup) too? The `Configure` and `ConfigureServices` code snippets currently reflect 1.x. I'm thinking we should add a 2.x tab too. Specifically, the `UseIdentity` and `AddIdentity` method calls are 1.x. only.

**Comment by guardrex** [comment]
@scottaddie I'm only addressing the hosting topic on this issue to try and close this one out.

**Comment by scottaddie** [comment]
@guardrex Thanks for the clarification. I'll create an issue, if one doesn't already exist, to address what I called out above.
