### ISSUE TITLE
fundamentals/owin "Open Web Interface for .NET (OWIN)"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1871]
- [ ] DISQUS questions
- [ ] I agree with the comments below. The whole OWIN integration into ASP.NET core is lacking clarity and a very simplified tutorial by experienced publishers. As far as I can tell from the past few weeks of research the real time event and streaming development community is slowing transitioning to node and the reason is that .net core has been slow to provide a simplified solution to these integration issues. Hopefully someone at Microsoft realizes that there is a huge market for industrial event and monitoring that is easily implemented at a lower cost than packaged software. Just a few cents worth.
- [ ] The definitions given here are extremely ambiguous. But certainly we need to know whether asp-net core can work independently of owin and vice versa. And why we would mix them. And I'm very uncertain about the meaning of owin enabling http disconnected from hosting. Is this just about how the functionality got dropped into various libraries? Or are these two frameworks able to do something if either operates standalone/

**Comment by Rick-Anderson** [comment]
@Tratcher can you comment on the feedback and I'll update the doc. cc @danroth27

**Comment by Tratcher** [comment]
OWIN provides a decoupling layer that allows two frameworks with disparate object models to be used together. The Microsoft.AspNetCore.Owin package provides two adapter implementations, ASP.NET Core -> OWIN and OWIN -> ASP.NET Core. This allows ASP.NET Core to be hosted on top of an OWIN compatible server / host, or for other OWIN compatible components to be run on top of ASP.NET Core.  

Note using these adapters comes with a performance cost. Applications using only ASP.NET Core components should not use the Owin package or adapters.

**Comment by isaac2004** [comment]
@Rick-Anderson does this issue even need to be addressed? I think there is some good documentation about OWIN and how it compares to ASP.NET Core in [Migration](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/). If I am missing something here please advise

**Comment by Rick-Anderson** [comment]
@isaac2004  agreed. I just wanted to verify `@Tratcher`'s comment made it to the article.
