### ISSUE TITLE
Rework TOC a little bit

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Docs#189]
Going through a docs, I think we should restructure it a bit:

Brain dump:

- DNX (This section is fine but we can add more things)
  - What's in it?
    - dnu, dnx, design time host
 - Project System
   - global.json, project.json and project.lock.json (schema function etc)
    - Types of references
    - Project references
    - Package references
    - Assembly references
    - msbuild style (csproj, vbproj) project references
 - NuGet and DNU (workflows etc) (some of this)
   - Package sources with NuGet.Config
 - Features
    - Servicing
    - Services offered by the DNX
    - Compilation
    - Loaders

- Workflows and Troubleshooting
  - Working with DNX and the .NET 4.x (things you need to know when working with DNX on desktop)
    - AppDomain.AppBase is different 
    - How to reference a GAC assembly
  - NuGet package version
  - Working with snapshot versions
  - Diagnosing Dependency failures  (http://davidfowl.com/diagnosing-dependency-issues-with-asp-net-5/)

- Fundamentals (cross cutting concerns)
 - Caching
 - Configuration
 - FileSystem
 - DataProtection (can point to that section)
 - DependencyInjection
 - Options 

- Testing
   - Unit testing
   - The Test Host
   - The Test command
    - Plugging into the unit test infrastructure 

- Http Stack
 - HttpAbstractions (why and how are they supposed to be used)
 - Middleware 
 - Hosting Model
  - Feature Model/Feature Interfaces
  - Server feature interfaces (would be good to describe them all, overlap with API docs)
 - OWIN
  - Plugging in OWIN middleware
  - Plugging in OWIN servers
 - Security (probably goes to another section)
   - ASP.NET AuthN and AuthZ abstractions
    - `IAuthorizationHandler`, `IAuthorizationRequirement`, `AuthorizationPolicy`
    - Authorization Policies
    - Generic `[Authorize]` attribute

- Standard Middleware
 - StaticFiles
 - CORS
 - WebSockets
 - Diagnostics
 - Security Middleware (big enough to have its own section?)
   - Concepts (base class etc)
    - Facebook, Twitter, OpenIdConnect, Generic
 - Session
 - Routing 
 - Caching (TDB)

- Frameworks
 - MVC
 - SignalR

- Web Servers (why pick one over the other, pros and cons)
 - IIS/ IIS Express
 - WebListener
 - Kestrel
 - Implementing servers

- Working with Data
 - EntityFramework (pointer to another repository)

**Comment by danroth27** [comment]
Reviewed and separate issues filed.
