### ISSUE TITLE
Clearly list all interfaces for identity

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Docs#1895]
If I'm looking to implement identity storage myself, it would be nice to have a clear list of the interfaces necessary, along with any tips that might be useful.

**Comment by Rick-Anderson** [comment]
Take a look at https://github.com/IdentityServer

**Comment by Rick-Anderson** [comment]
@blowdart  for those who want to implement identity storage do you recommend they start at  https://github.com/IdentityServer ?

**Comment by blowdart** [comment]
Wait, what's identity "storage"? As in use your own database for ASP.NET identity, or something else?

**Comment by atrauzzi** [comment]
Yeah, databases.

**Comment by blowdart** [comment]
Sorry, I entire missed the reply. So your own database schema. When you say identity then, are you wanting to use ASP.NET identity with your own schema, or that you just want to implement your own login system, not using ASP.NET identity.

**Comment by atrauzzi** [comment]
Yes, use ASP.NET identity with my own or a pre-existing schema.  The path for enabling integration between my data and anything that interfaces with identity isn't quite clear.

**Comment by blowdart** [comment]
That's because it depends how far you want to go. @HaoK do you have any guidance on what the bare minimum is?

**Comment by Rick-Anderson** [comment]
@HaoK do you have any guidance on what the bare minimum is?

**Comment by HaoK** [comment]
I think we used to have old documents talking about this (pre core docs).

The barest minimum for password logins is implementing a schema that is able to store everything in 
`IUserPasswordStore`

https://github.com/aspnet/Identity/blob/master/src/Core/IUserPasswordStore.cs
