### ISSUE TITLE
The dotnet-watch sample does not compiles.

### ISSUE THREAD

**Issue by mjza** [aspnet/Docs#1902]
Hi. I followed the documentation and I want to test the dotnet watch but when I add the Watcher to tool like the following:

```
"tools": {
        "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
},
```

Then I get the following error in the time of restoring:

C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample>dotnet restore
log  : Restoring packages for C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebAppTests\project.json...
log  : Restoring packages for C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebApp\project.json...
error: Unable to load the service index for source https://dotnet.myget.org/F/aspnet1/api/v3/index.json.
error:   Response status code does not indicate success: 404 (Feed does not exist.).

**Comment by spboyer** [comment]
Can you try going to the command line and doing a `dotnet restore` from there? 

@Rick-Anderson and I were able to replicate your issue but after having the local cache built from the CLI, everything worked as it should even on a new project.  

@danroth27

**Comment by Rick-Anderson** [comment]
Thanks for reporting this. From https://github.com/aspnet/dotnet-watch/tree/1.0.0-preview2

Add Microsoft.DotNet.Watcher.Tools to the tools section of your project.json file:

{
...
  "tools": {
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net451+win8"
    }
  }

From the command line
dotnet restore

**Comment by danroth27** [comment]
> Unable to load the service index for source https://dotnet.myget.org/F/aspnet1/api/v3/index.json

Why is this feed being used? I get a 404 when I try to access it.

**Comment by mjza** [comment]
@Rick-Anderson Thanks for the answer but I got the 404 error again:

My tools is like this:

"tools": {
    //"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net451+win8"
      }
    },

Even without commenting the second line the 404 error exists.

And the error is:

error: Unable to load the service index for source https://dotnet.myget.org/F/aspnet1/api/v3/index.json.
error:   Response status code does not indicate success: 404 (Feed does not exist.).

**Comment by mjza** [comment]
@spboyer I tried from the command line. When I wanted to run 'dotnet restore' command I received the above error. Before adding the dotnet watch I could compile and run the project from the command line. I followed the PDF line by line.

**Comment by Rick-Anderson** [comment]
> Unable to load the service index for source https://dotnet.myget.org/F/aspnet1/api/v3/index.json

Why is this feed being used? I get a 404 when I try to access it.

**Comment by spboyer** [comment]
@mjza - Check your NuGet package sources in Visual Studio. On the **Tools** menu, choose **Options**.... In the left nav expand **NuGet Package Manager** and choose **Package Sources**.

![tools-options-nuget](https://cloud.githubusercontent.com/assets/7681382/18678974/c793e5ea-7f2b-11e6-800e-df655c70970a.png)

The feed that you are referencing should not be in your sources.

**Comment by mjza** [comment]
@spboyer Did you read the example? It is a command line example and not an example within Visual Studio. Shall I convert it to some example inside of VS?

Is it possible to do this modification inside of the text files?

I want to run it via CMD as it is.

**Comment by spboyer** [comment]
Sorry, there was not a link to the sample you are following provided.  Can you post the link?

>C:\Users\mansari\Documents\Visual Studio 2015\Projects

Lead me to believe that you were using Visual Studio.

**Comment by mjza** [comment]
@spboyer Yes. Here is the link to the tutorial and sample code:

https://github.com/aspnet/Docs/tree/master/aspnet/tutorials/dotnet-watch/sample

https://docs.asp.net/en/latest/tutorials/dotnet-watch.html

**Comment by spboyer** [comment]
@mjza trying to figure out why you have https://dotnet.myget.org/F/aspnet1/api/v3/index.json as a package url.  [dotnet-restore](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-restore) will look for NuGet.json files within the project folder or below to add sources.  Do you have a NuGet.json within your working directory that has the above url? There is not one in example code repo.

**Comment by mjza** [comment]
@spboyer I didn't write that tutorial. It is there and I just followed the the tutorial that provided its link. I just reported the problem. Actually 50% of the sample can be compiled and run but the remained not. I think the author or authors of this sample can answer the problem which you mentioned better.

**Comment by spboyer** [comment]
@mjza understand. There is some updates needed to the sample and article.

**Comment by danroth27** [comment]
You can see which feeds and NuGet.config files are in effect by running:

```
dotnet restore -v Information
```

**Comment by spboyer** [comment]
@mjza can you run the command above and provide the output?

**Comment by mjza** [comment]
@spboyer Sorry for late answer.

Here is the output of the command.

Please note that I didn't made it with VS. I just downloaded the whole dotnet from Github and just placed in VS2015 folder to not messy up my disk. I used cmd for this project.


C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebApp>dotnet restore -v Information
log  : Restoring packages for C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebApp\project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in C:\Users\mansari\Documents\Visual Studio 2015\Projects\Docs-master\aspnet\tutorials\dotnet-watch\sample\WebApp\project.json...
error: Unable to load the service index for source https://dotnet.myget.org/F/aspnet1/api/v3/index.json.
error:   Response status code does not indicate success: 404 (Feed does not exist.).
