### ISSUE TITLE
Wrong instructions on how to set SSL in a ASP.NET Web Application

### ISSUE THREAD

**Issue by ncarandini** [aspnet/Docs#1908]
## Context
In the [Enabling authentication using Facebook, Google and other external providers
](https://docs.asp.net/en/latest/security/authentication/sociallogins.html) article, one of the steps describe how to set SSL, with an image that shows the selected SSL option and the field of the App URL **_with the same https URL that is shown to the right of the SSL option_**. And this is bad (like crossing the streams in the famous Ghostbusters dialogue) because after this step debugging the app won't work anymore, with VS showing this error: "An error occurred attempting to determine the process id of dotnet.exe which is hosting your application. One or more errors occurred.":

<img width="350" alt="ssl_setup" src="https://cloud.githubusercontent.com/assets/139274/18688390/81944b4e-7f84-11e6-8684-0a4ac305ae5c.png">

## Solution
Change the article to reflect this:
  1.  The App URL need to remain unchanged.
  2.  Open the launchSettings.json file and manually add the Launch URL and set it to the URL shown to the right of the SSL option.

## Example
Create a new project, open the project preferences and set the SLL option:

<img width="512" alt="ssl_setup" src="https://cloud.githubusercontent.com/assets/139274/18688563/3c4a571c-7f85-11e6-9ff1-ff10be9733f7.png">

Save the project preferences, then open the launchSettings.json:
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:5681/",
      "sslPort": 44377
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "WebApplication4": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
As you can see no "launchUrl" property is present in the "IIS Express" profile, so if we launch the app we don't land to the proper https page (it will default to the http App URL).

To solve, add the ***"launchUrl":  "https://localhost:44377"*** row to the "IIS Express" profile:
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:5681/",
      "sslPort": 44377
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "https://localhost:44377",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "WebApplication4": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```
Now press F5 to start debugging, it should work.
_Many thanks to Richard Marskell that helped me solving this issue on Gitter._

**Comment by Rick-Anderson** [comment]
If you don't set ``launchUrl``, it defaults to the ``applicationUrl`` setting. You can set ``applicationUrl``  from the Visual Studio IDE on the same page
![capture](https://cloud.githubusercontent.com/assets/3605364/18761063/572b1f06-80b8-11e6-9bf8-f7c22069b8ba.PNG)

**Comment by Rick-Anderson** [comment]
@ncarandini - we have reproduced the problem on one machine. A much simpler solution is to copy the SSL URL to the Launch URL box as shown above. However you should also use the same SSL URL in the App URL.

**Comment by ncarandini** [comment]
@Rick-Anderson - you're right, setting the Launch URL from the Visual Studio IDE is much easier, and with the Launch URL set, the App URL can be set to the same https URL without any problem.

So the only thing to add to the article is to **_copy the https URL also in the Launch URL from the Visual Studio IDE same page_**.

Thanks!

**Comment by Rick-Anderson** [comment]
@ncarandini  Thanks for reporting this. I updated #1470

**Comment by rmarskell** [comment]
I think this must have been fixed in the recent update. I used to not be able to set the app URL to the HTTPS version without getting the error above, but it seems to be working for me now, even without the launch URL.

**Comment by ncarandini** [comment]
Wow, just tried and I can confirm that now it works, as @rmarskell reported.

**Comment by ncarandini** [comment]
Because the docs page content now correspond to the VS behavior, I think we can close this issue.
