### ISSUE TITLE
MVC Application Parts

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1910]
MVC -> Extensibility -> Application Parts

An application part is a resource where MVC features might be found, like an assembly.
A feature provider populates features from the application parts (e.g. controllers, viewcomponents, Tag Helpers, Razor compilation references). Helps you discover these things. Precompiled Views are available in 1.1. (View discovery doesn't currently use this, but may in the future)

App parts are the raw materials that mvc will look at to discover "stuff". Normally just an assembly, like the AssemblyPart. Motivation is for customers who want to discover controllers or views from another assembly. For instance, MVC default discovery will search dependency tree and find controllers. But to load an arbitrary assembly (e.g. a plugin), you can use an application part. To do this without this feature would require rewriting controllerfactory and discovery logic - this simplifies that process.

Conversely if you want to *avoid* looking for controllers in a particular assembly or location, you can use app parts to do that as well.

ApplicationPartManager has a collection of ApplicationParts that you can mutate. Order is not important for application parts.

Order is important - you must have configured your application parts before you can use them for features. In ConfigureServices, add MVC, configure app part manager, *then* use anything that needs services added to DI from these things.

Application Feature Providers
Look at application parts and provide features for those parts.
IApplicationFeatureProvider<T> where T is the type of feature (controllerfeature, viewcomponentfeature, . taghelper, metadatareference, views). You can add additional feature providers for any of these features, which does additional things.
Order matters based on the order of the list of feature providers.

References:
https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.GenericControllers 

Normally generic controllers are ignored by MVC. You can add your own. FeatureProviders are ordered and you can see what has been added previously, and you can remove/add from there.

MvcBuilder Helpers:
 .ConfigureApplicationPartManager
 .AddAssemblyPart

Examples:
Show how to populate a feature. How to get the list of controllers. In user code, if you wanted to know all of the controllers in the system, you would get the ApplicationPartManager via DI, and you would populate whichever features you cared about. For Views, it's only partially implemented. Views that aren't precompiled go through a different discovery process currently.

Call out how feature providers and application parts interact. Parts implement very specific interfaces that the parts look for (2 of them - look at AssemblyPart class to see them - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/AssemblyPart.cs). The base applicationpart abstraction is just a name - to get types out of it you have to use the interfaces. IApplicationPartTypeProvider and ICompilationReferencesProvider. Application parts may or may not implement them.

Think of application parts as raw materials. Building chair? Part is a tree, says it has wood. Feature provider says "i need wood, i can make a chair".

The type of the application part is an implementation detail.

This sample also refers to Application model concepts that will be covered in #138.

Reference: http://stackoverflow.com/a/40732215

**Comment by ardalis** [comment]
Is there a cleaner way to remove one application part from ApplicationPartManager than this?

                .ConfigureApplicationPartManager(p =>
                {
                    var parts = p.ApplicationParts.ToList();
                    p.ApplicationParts.Clear();
                    p.ApplicationParts.AddRange(parts.Where(part => part.Name != "DependentLibrary"));
                })

This works but I'd rather something like .RemoveWhere(p => p.Name == "whatever")

**Comment by ardalis** [comment]
For reference: https://github.com/aspnet/Docs/pull/1945

**Comment by ardalis** [comment]
Get the instance and then remove it directly: https://github.com/danroth27/AspNetCoreModules/blob/master/src/Microsoft.AspNetCore.Modules.Mvc/MvcBuilderModulesExtensions.cs#L18
