### ISSUE TITLE
Move cookie sharing topic to Security

### ISSUE THREAD

**Issue by blowdart** [aspnet/Docs#1913]
It also needs promoting out of hiding under data protection, and to be a first class topic under security.

**Comment by guardrex** [comment]
@blowdart Do the recent updates (and others since this was opened) cover this issue? One thing we didn't do was make the topic 1st class under *Security*. It's still under: *data-protection/compatibility/*.

**Comment by guardrex** [comment]
We have an updated topic, so let's move it up to *Security*: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing?tabs=aspnetcore2x
