### ISSUE TITLE
Unable to contribute to this project

### ISSUE THREAD

**Issue by ncarandini** [aspnet/Docs#1915]
I've installed Sphinx and cloned this project.
On the master branch, when trying to `make html` from the `aspnet` directory the build exit with the (warning treated as an) error:
```
c:\Git\aspnet-docs\aspnet\fundamentals\app-state.rst:148: WARNING: dn:iface reference target not found: ~Microsoft.AspNetCore.Http.ISession
```
But the `index.rst` file do exist in my `C:\Git\aspnet-docs\api\autoapi\Microsoft\AspNetCore\Http\ISession\` folder, and the corresponding [web page](https://aspnet-aspnet.readthedocs-hosted.com/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Http/ISession/index.html) exist in the cross referenced [mapped site](http://docs.asp.net/projects/api/en/latest).

The cross reference mapping is:
```
intersphinx_mapping = {
    'api': ('http://docs.asp.net/projects/api/en/latest', '../common/api.inv')
}
```
and should be ok.

I've also managed to read the `api.inv` file with the `sphobjinv` package, that I've installed with `pip install sphobjinv`.

I've converted the `api.inv` file to `api.tx`t file with the line command (executed from the `common` folder):
```
sphobjinv decode api.inv
```
and I did found this reference:
```
Microsoft.AspNetCore.Http.ISession dn:interface 1 autoapi/Microsoft/AspNetCore/Http/ISession/index.html#$ -
```
in the text-converted file.
So I really can't understand why I get the warning error.

**Comment by ncarandini** [comment]
## Solved!

### Cause
All `*.rst` files use a *wrong syntax* to cross reference. As an example see the line that produce the error:
```
[...] which exposes a property called ``Session`` of type :dn:interface:`~Microsoft.AspNetCore.Http.ISession`. [...]
```
note the reverse accent (aka backtick or grave accent) before the tilde character, placed there to mark the beginning of the hyperlink reference (as dictated by the reStructuredText inline markdown syntax).

***But in that position the reverse accent breaks the cross reference syntax!***

### Solution
The right place is **before** the start of the cross reference, as shown here:
```
[...] which exposes a property called ``Session`` of type `:dn:interface:~Microsoft.AspNetCore.Http.ISession`. [...]
```
After changing this in all the `*.rst` files, all the warning errors disappear.

**Comment by ardalis** [comment]
Hi Nicolò,

I can't reproduce this issue on my machine, probably because I already have the required bits installed. Here is what I just did to reproduce.

1. Go to my 'scratch' folder in cmd prompt
1. git clone <url> docs
1. cd docs
1. cd aspnet
1. make html

End result:
![image](https://cloud.githubusercontent.com/assets/782127/18840744/9d4f52cc-83dd-11e6-8604-9cb567ddc753.png)

Are you certain you have followed the instructions here, from the correct directories and with the necessary permissions?
https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md

**Comment by ncarandini** [comment]
Hi Steve,
I'm double checking and also try to install everything again to another device (my Surface Pro 1, still good for this). I'll update ASAP

**Comment by Rick-Anderson** [comment]
@ncarandini  Just ignore that warning for now.

**Comment by ncarandini** [comment]
Thanks Rick and Steve, I successfully installed everything on my other device. So I'm good to go.
By the way, I'm still trying to understand what got wrong on my first device, but now is irrelevant, just my curiosity.

**Comment by ncarandini** [comment]
I've also solved on my first device uninstalling python and deleting all related folders in `%LocalAppData%\Programs\` and following the steps on the https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md (as I did before, but only after some other steps, like installing the latest version of Sphinx by myself).

To reproduce the issue, I tried to replay the same steps I did the first time in a Windows 10 clean VM, without success.

So I've decided that enough is enough, and this has been a long story with an happy ending.

**Comment by ncarandini** [comment]
Hi Steve,

thanks for your help.

My apologies for wasting your time, restarting from scratch solved the issue, and I can’t tell what went wrong in the first try.

 

I hope to meet you in person at the MVP Summit, I owe you a beer! :)

 

Nicolò.

 

Da: Steve Smith [mailto:notifications@github.com] 
Inviato: lunedì 26 settembre 2016 17:39
A: aspnet/Docs <Docs@noreply.github.com>
Cc: Nicolò Carandini <n.carandini@outlook.com>; State change <state_change@noreply.github.com>
Oggetto: Re: [aspnet/Docs] Unable to contribute to this project (#1915)

 

Hi Nicolò,

I can't reproduce this issue on my machine, probably because I already have the required bits installed. Here is what I just did to reproduce.

1.	Go to my 'scratch' folder in cmd prompt
2.	git clone docs
3.	cd docs
4.	cd aspnet
5.	make html

End result:
 <https://cloud.githubusercontent.com/assets/782127/18840744/9d4f52cc-83dd-11e6-8604-9cb567ddc753.png> 

Are you certain you have followed the instructions here, from the correct directories and with the necessary permissions?
https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md
