### ISSUE TITLE
Please document way to redirect user using Window Authentication without cookies

### ISSUE THREAD

**Issue by jllblk** [aspnet/Docs#1922]
I am using IIS 10 and using Asp.Net Core 1.0.0.0 with .NET Framework 4.5.2. I am using the windows authentication type of .NET Core web application. Window Authentication works. What isn't documented is a way to setup the middleware so that the user will be redirected to a certain route in the application. There is cookie specific documentation which I tried, but doesn't work without cookies.

**Comment by Rick-Anderson** [comment]
@blowdart

**Comment by blowdart** [comment]
Windows Auth happens at the IIS level, before your application even sees the request. It's not something middleware configures. What the middleware does is react to the Windows Identity IIS sends the app.

I don't know what you mean by "so that the user will be redirected to a certain route in the application"

**Comment by jllblk** [comment]
Thanks for answering my question. Allow me to clarify: ChallengeResult() is what I meant by "so that the user will be redirected to a certain route in the application."
I'm using Windows Authentication and Policy Authorization in a ASP.NET Core 1.0.0.0 app alongside .NET 4.6. I understand that Windows Authentication is handled by IIS only.
In my application, I am using the Windows Authentication Identity to lookup application specific user data and I am using that user data in the Policies. What I meant to ask was when a user is not authorized due to no policies succeeding, what middleware can raise a ChallengeResult() to a custom page without using cookies? (I'm using Windows Authentication, and I don't want to deal with cookies if I don't have to).

Thanks,

Joel Black
________________________________
