### ISSUE TITLE
npm packages are not automatically restored

### ISSUE THREAD

**Issue by yechongbo** [aspnet/Docs#1923]
Hi Guys,

In my solution, gulpfile.js and package.json are together located in a solution folder, same level as sln file, and they are under the source control as well. the problem right now is, whenever i get latest version of these files, and let say they have been updated by a team member. the npm packages are not automatically updated until i save the package.json manually. is it expected?

**Comment by spboyer** [comment]
@yechongbo the restore will not happen until the .json file is in fact changed.

**Comment by yechongbo** [comment]
@spboyer, thanks for the clarification. but it seems it works when they are at project level.

**Comment by spboyer** [comment]
interesting, sorry missed the "location" portion.  Create a new issue in  Tooling repo -> https://github.com/aspnet/tooling/issues
