### ISSUE TITLE
ef-mvc/crud.rst#test-the-edit-page incorrect comment

### ISSUE THREAD

**Issue by rvmaccount** [aspnet/Docs#1925]
in the section Test the Edit page it says

The HTML and Razor code in Views/Students/Edit.cshtml is similar to what you saw in Create.cshtml, and **no changes are required.**

this is not correct, in order to show the date validation message, similar to the create page an explicit end tag for the span tag is needed.

**Comment by Rick-Anderson** [comment]
@tdykstra
