### ISSUE TITLE
ASP.NET 5 on Azure Service Fabric

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#193]
Tutorials -> ASP.NET 5 on Azure Service Fabric

**Comment by danroth27** [comment]
http://azure.microsoft.com/blog/2015/04/20/announcing-azure-service-fabric-reducing-complexity-in-a-hyper-scale-world/

**Comment by luisrudge** [comment]
any news on that? :)

**Comment by danroth27** [comment]
@glennc

**Comment by reifnir** [comment]
Still very much looking forward to hosting full ASP.NET components in Service Fabric. Is there an estimated date or quarter that we can expect this support? I'm not really sure how useful Actor Events are without a client that can communicate all the way back to a user.

**Comment by seanmck** [comment]
ASP.NET 5 support will be available in our public preview next month.

**Comment by JakobBlomberg** [comment]
Very interesting with the whole ServiceFabric concept and looking forward to being able to use ASP.NET 5 with ServiceFabric. Are there already now any tutorials or guides on how to setup such a project? Have completed the tutorial on how to setup a WebAPI using OWIN Self-hosted but all my projects have been converted to MVC6 so I'd really like to use them with ServiceFabric.

**Comment by seanmck** [comment]
Not yet. They will be available when we release our public preview (very soon).

Sent from Outlook<http://aka.ms/Ox5hz3>




On Mon, Nov 9, 2015 at 12:07 PM -0800, "JakobBlomberg" <notifications@github.com<mailto:notifications@github.com>> wrote:


Very interesting with the whole ServiceFabric concept and looking forward to being able to use ASP.NET 5 with ServiceFabric. Are there already now any tutorials or guides on how to setup such a project? Have completed the tutorial on how to setup a WebAPI using OWIN Self-hosted but all my projects have been converted to MVC6 so I'd really like to use them with ServiceFabric.

-

**Comment by JakobBlomberg** [comment]
@seanmck Which would you say is the best notification service to signup to in order to be notified when the new public preview is available? I have a bunch of different subscriptions today but it seems like different MS technologies travel faster on different channels such as MSDN, Azure, etc.

**Comment by seanmck** [comment]
Look for an announcement on our team blog when we have new bits available: http://blogs.msdn.com/b/azureservicefabric/

**Comment by danroth27** [comment]
https://azure.microsoft.com/en-us/documentation/articles/service-fabric-add-a-web-frontend/

**Comment by grahamehorner** [comment]
update required for aspnetcore rc2

**Comment by danroth27** [comment]
@seanmck when can we get the ServiceFabric + ASP.NET Core doc updated for the ASP.NET Core RC2 release?

**Comment by seanmck** [comment]
We'll have a release out in the next couple of weeks that provides an RC2-based template. I'll update the docs then.
