### ISSUE TITLE
Worthwhile to add module/schema/config info to ANCM doc?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1931]
I caught a great post by @jhkimnew at https://github.com/aspnet/Home/issues/1583#issuecomment-249754022 describing details on module/schema/config locations for ANCM.

I think this would be nice to add to the bottom of the ANCM doc at https://docs.asp.net/en/latest/hosting/aspnet-core-module.html. It's good reference material for finding these locations quickly for those who need it. What do you think?

Reorganized from https://github.com/aspnet/Home/issues/1583#issuecomment-249754022:

#### Module

IIS (x86/amd64):
%windir%\system32\inetsrv\aspnetcore.dll
%windir%\syswow64\inetsrv\aspnetcore.dll

IISExpress (x86/amd64):
%ProgramFiles%\IIS Express\aspnetcore.dll
%ProgramFiles(x86)%\IIS Express\aspnetcore.dll

#### Schema

IIS: %windir%\system32\inetsrv\config\schema\aspnetcore_schema.xml

IISExpress: %ProgramFiles%\IIS Express\config\schema\aspnetcore_schema.xml

#### Configuration

IIS: %windir%\system32\inetsrv\config\applicationhost.config

IISExpress: .vs\config\applicationhost.config

You can search file for `aspnetcore.dll`. For IISExpress, the `applicationhost.config` file won't exist by default. The file is created when you start any existing web application project of the VS solution.

cc/ @Rick-Anderson @shirhatti

**Comment by Rick-Anderson** [comment]
OK

**Comment by GuardRex** [comment]
:+1: I'll get a PR in within 48 hours.
