### ISSUE TITLE
Add a common error scenario to Publishing to IIS?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#1932]
From https://github.com/aspnet/IISIntegration/issues/270, we don't cover this failure scenario. How about I add something like the following to our Common Errors section?

**Browser:** HTTP Error 502.5 - Process Failure
**Application Log:** Failed to start process with commandline ‘“dotnet” .\my_application.dll’ (portable app) or ‘”.\my_application.exe”’ (self-contained app), ErrorCode = ‘0x800705b4’
**ASP.NET Core Module Log:** Log file created but empty

Troubleshooting

* This general exception indicates that the process failed to start, most likely due to an application configuration problem. Confirm that your published output (link "published output" to the Directory Structure doc) is correct and that your application's configuration files are present and contain correct settings for your app and environment.

cc/ @pan-wang @Tratcher @Rick-Anderson @spboyer @shirhatti @moozzyk

**Comment by Rick-Anderson** [comment]
OK by me and @spboyer

**Comment by GuardRex** [comment]
:+1: Cool ... I'll get a PR in within 48 hours.
