### ISSUE TITLE
Is the copyright notice at the end of docs pages required / usefull ?

### ISSUE THREAD

**Issue by ncarandini** [aspnet/Docs#1934]
At the end of each page we find:
>© Copyright 2016, Microsoft. Revision 868c661c. 

While I can understand that this is automatically produced by Sphinx based on the content of the `config.py` file:
```
# General information about the project.
project = 'ASP.NET'
copyright = str(datetime.date.today().year) + ', Microsoft'
author = 'Microsoft'
```
I'm wondering if it's a good thing to do, because I can't find any copyright notice on the [.NET Core documentation](https://docs.microsoft.com/en-us/dotnet/articles/welcome).

If not needed, I do think it would be better to remove it (#openness).

**Comment by Rick-Anderson** [comment]
Good question. This will change when we're hosted with the [.NET Core documentation](https://docs.microsoft.com/en-us/dotnet/articles/welcome).
