### ISSUE TITLE
performance/caching/memory.md "In Memory Caching"

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Docs#1938]
- [ ]  Show dependencies
- [ ] DISQUS
- [ ] UE Scrub
- [ ] Show how to use with controllers

The [caching page](https://docs.asp.net/en/latest/performance/caching/memory.html#cache-dependencies-and-callbacks) says: 

> You can configure cache entries to depend on other cache entries, the file system, or programmatic tokens

However, it doesn't explain **how** to use other cache entries or the file system as dependencies.

**Comment by dodyg** [comment]
https://github.com/aspnet/Caching/tree/dev/samples/MemoryCacheFileWatchSample

**Comment by Daniel15** [comment]
@dodyg - That explains how to add a dependency on a file, but doesn't explain how to add a dependency on another cache entry.
