### ISSUE TITLE
Add response caching middleware content to the response caching doc

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#1947]
We will have response caching middleware in 1.1.

**Comment by moozzyk** [comment]
Here are the topics that needs to be described (from my verification):
- cacheable vs. non-cacheable responses based on:
   method - only GET/HEAD responses are cachable
   headers - Authorization, Cache-Control: no-cache, Pragma: no-cache make responses non-cacheable
- which Cache-Control header options and headers affect caching and how:
   - request: min-fresh, max-age, max-stale
   - response: shared-max-age, must-revalidate, Expires (header) 
- CacheOptions
   - max response size, 
   - case sensitive paths
- ETags and 304 (Content not modified) responses
- 504 responses
- VaryBy
   - headers
   - keys

/cc @JunTaoLuo

**Comment by GuardRex** [comment]
This was covered by https://github.com/aspnet/Docs/pull/2505
