### ISSUE TITLE
Add documentation on the DNX design time host

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#195]

**Comment by JoshVarty** [comment]
:+1: 

I would love even just like a couple sentences about the design time host.

I am working on an application that must load/compile/emit ASP .Net 5 projects. Could someone help me understand how the design time host fits into this and works with project.json files?

Also is the design time host open source? I see aspnet/tooling/issues/9 mentions the design time host, but there's no source in that repository.

**Comment by danroth27** [comment]
@davidfowl 

Sounds like you want to do something similar to what the [OmniSharp](http://www.omnisharp.net/) folks are doing. OmniSharp is used by [Visual Studio Code](https://code.visualstudio.com/), so it's definitely worth a look.

**Comment by danroth27** [comment]
No longer relevant now that we are moving from DNX to the new [.NET CLI](https://github.com/dotnet/cli)

**Comment by JoshVarty** [comment]
Is the DNX stuff going away? Is anyone other than Omnisharp using the Design Time Host?

I see DNX still falls under the /aspnet organization, so where will this stuff be documented?

**Comment by danroth27** [comment]
DNX is getting replaced by the new .NET CLI. Much of the application model will be unchanged (i.e. project.json, NuGet packages, etc), but the underlying infrastructure is getting an upgrade. The .NET docs for the .NET Core effort are currently at http://dotnet.github.io.
