### ISSUE TITLE
Document when to choose WebListener

### ISSUE THREAD

**Issue by breyed** [aspnet/Docs#1959]
The section [Choosing a server](https://docs.asp.net/en/latest/fundamentals/servers.html#choosing-a-server) describes different ways of hosting Kestrel, but doesn't even mention WebListener, much less offer guidance about when to choose it.

Related StackOverflow question: [WebListener vs Kestler: Why choose one over another?](http://stackoverflow.com/q/39248345/145173)

**Comment by danroth27** [comment]
Yup, we need to document WebListener for the upcoming 1.1 release.

**Comment by tdykstra** [comment]
Added to #1348, see also new WebListener doc #1827
