### ISSUE TITLE
aspnetcore/client-side/angular.md Using Angular for Single Page Applications (SPAs)

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1962]
- [ ] remove almost everything that is angular, just leave what's relevant to ASP.NET Core.

@scottaddie  or @spboyer should be able to do this.

**Comment by spboyer** [comment]
@Rick-Anderson ? Essentially that means removing all content below https://docs.asp.net/en/latest/client-side/angular.html#key-components

@danroth27

**Comment by danroth27** [comment]
We decided to leave the content until it actually becomes an issue.
