### ISSUE TITLE
ASP.NET Core Module schema reference bug

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#1965]
https://github.com/aspnet/Docs/blame/master/aspnet/hosting/aspnet-core-module.rst#L52

There is **NO** attribute called startupRetryCount

**Comment by shirhatti** [comment]
There is also **NO** configurable attribute called recyleOnFileChange

All references to it should be removed from the docs

**Comment by GuardRex** [comment]
@Rick-Anderson Do you want me to put in a fix for these two (i.e., remove them)?

@shirhatti Curious: What's up with `recycleOnFileChange` in the schema? Is it nop?
```
<element name="recycleOnFileChange">
  <collection addElement="file" clearElement="clear">
    <attribute name="path" type="string" required="true" validationType="nonEmptyString" expanded="true"/>
  </collection>
</element>
```

**Comment by Rick-Anderson** [comment]
@GuardRex , yes that would be great if you could remove them. But do it at https://github.com/Microsoft/Docs-1, not here

**Comment by GuardRex** [comment]
Ok ... will do.

**Comment by GuardRex** [comment]
@shirhatti As before, does the module attempt to restart the process after the `startupTimeLimit` has passed? If so, do you want me to add a note on indefinite restart attempts?

From the current text ...
> If this time limit is exceeded, the handler will kill the process and attempt to launch it again **startupRetryCount** times.

To ...
> If this time limit is exceeded, the handler will kill the process and attempt to launch it again.

Or better if the restart attempts are indefinite ...
> If this time limit is exceeded, the handler will kill the process and attempt to launch it again. The module will attempt to restart the process indefinitely until either the website or the application pool is stopped.

One other thing ... There are four spots where the ANCM is referred to as a "handler," but shouldn't that be "module?" If so, I'll knock that out at the same time. 👊

**Comment by shirhatti** [comment]
If this time limit is exceeded, the handler will kill the process. ANCM will attempt launch it again when it receives a new request. It will continue to attempt to restart the process on subsequent incoming requests unless the application failed to start `rapidFailsPerMinute` number of times in the last rolling minute.

And yes, it should be referred to as a module. I'm guessing that's an artifact of HttpPlatformHandler days.

**Comment by GuardRex** [comment]
Thx @shirhatti ... I'll use that language or very similar language in the  PR, which I'll get in within a few hours.

**Comment by shirhatti** [comment]
Given @muratg's comment in #1990, I think it's best we keep `recyleOnFileChange` in the configuration reference, but explicitly called it has been deprecated and currently only no-ops. This way it will be less confusing for folks who discover this attribute in their schema file.

**Comment by GuardRex** [comment]
Ok ... I'll get the commit in there to restore that bit with the note on depreciation/no-op in a couple of hours when I get back from the gym 💪 .

**Comment by Rick-Anderson** [comment]
> but explicitly called it has been c and currently only no-ops

Don't use deprecated, deprecated means it works now but may not in the future. Just say it does nothing (no-op). Don't use no-op alone (that is, say it does nothing (no-op)).

**Comment by GuardRex** [comment]
How about this for the description?

> This setting does nothing (no-op) and is included in the schema for backwards compatibility. Formerly, this element defined a collection of files, which when changed, would prompt a recycle of the worker process.

**Comment by GuardRex** [comment]
This still seems a little awkward to me ...

> This setting does nothing (no-op) and ...

maybe ...

> This element is not honored (no-op) and ...

or ...

> This element is not used by the module (no-op) and ...

**Comment by Rick-Anderson** [comment]
You could probably go with

`This element is not used by the module.`

And that's all you need.

**Comment by GuardRex** [comment]
mmm ... kind'a begs the question why its there.

How about ...

> This element is not used by the module and is included in the schema for backwards compatibility.

**Comment by Rick-Anderson** [comment]
That's fine. You could even tack on 
Formerly, this element defined a collection of files, which when changed, would prompt a recycle of the worker process.

**Comment by GuardRex** [comment]
ok, cool. It's done.
