### ISSUE TITLE
ASP.NET Core 1.0.1 on IIS fails with HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by b0bi79** [aspnet/Docs#1967]
Hello.
I get HTTP Error 502.5 - Process Failure. After added disableStartUpErrorPage="true" stdoutLogEnabled="true" in the web.config, I get HTTP Error 502.3 - Bad Gateway. 
Windows event log: Process was created with commandline '"C:\inetpub\wwwroot\VernoPortal\Verno.Reports.Web.exe" ' but either crashed or did not reponse within given time or did not listen on the given port '13417', ErrorCode = '0x800705b4'
ASP.NET Core Module Log creates an empty log file.
Verno.Reports.Web.exe started from console work fine.

Site deployed on Windows Server 2008 R2 with Web Deploy using Visual Studio. 
On the server are installed:
- DotNetCore.1.0.1-WindowsHosting
- httpPlatformHandler_amd64
- .NET 4.6.2

Web.Config
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\Verno.Reports.Web.exe" arguments="" disableStartUpErrorPage="true" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false" />
  </system.webServer>
</configuration>
`
Help me please.

**Comment by danroth27** [comment]
This really isn't a doc issue. Are you able to run Verno.Reports.Web.exe directly without error?

If you need further assistance with this issue I recommend posting a question on StackOverflow.

**Comment by b0bi79** [comment]
I solved this issue by removing DotNetCore, httpPlatformHandler_amd64, .NET 4.6.2 and reinstalled this. But instead .NET 4.6.2 I installed .NET 4.6.1
