### ISSUE TITLE
Update ResponseCaching docs

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Docs#1969]
The documentation for the response caching attribute should be updated.

It should reflect the addition of the VaryByQueryKey property that was added in https://github.com/aspnet/Mvc/pull/5383 and the addition of the response caching middleware on the server.
[edit] #1679 master issue on response caching

**Comment by JunTaoLuo** [comment]
@danroth27 any progress on this issue?

**Comment by danroth27** [comment]
@Rick-Anderson ?

**Comment by Rick-Anderson** [comment]
@JunTaoLuo  can you PR https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/response.md with the basic changes and I'll clean up the writing?

**Comment by Rick-Anderson** [comment]
@JunTaoLuo when will VaryByQueryKeys be in the API docs for [responsecacheattribute] (https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.responsecacheattribute)?

**Comment by JunTaoLuo** [comment]
How is that built? If it is being built against 1.1.0 release (FTS) then it should be.

**Comment by Rick-Anderson** [comment]
fixed by  #2210
