### ISSUE TITLE
mvc/models/formatting "Formatting Response Data"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#1971]
- [ ] UE Edit - simply is a banned word
- [ ] Disqus
- [ ]  #1406  Consider updating the article for RTM to show how to format the JSON as PascalCase rather than camelCase.
- [ ] #2005  - The following two links are incorrect
  System.Xml.Serialization.XmlSerializer. If you prefer, you can use the System.Runtime.Serialization.DataContractSerializer
- [ ]  provide guidance on System.Xml.Serialization.XmlSerializer. vs System.Runtime.Serialization.DataContractSerializer
- [ ]  explain _developers have many helper methods corresponding to many of the choices_. 
- [ ] delete 
- [ ] To return data in a specific format from a controller that inherits from the Controller base class, use the built-in helper method Json to return JSON and Content for plain text.  That's already said
- [ ] Sample response from this action - pic is too small to read
- [ ]   _Also note the list of options presented by the browser_     explain that. Are those options? Mention how to launch tools and provide a link.
- [ ] Change to: The following images shows a response from this action.
- [ ] Combine Tip with Note - both talking about return.  We really need to explain why you return `IActionResult` in fundamental tutorials.
- [ ] _In the sample, a request for a valid author alias will receive a 200 OK response with the author’s data. A request for an invalid alias will receive a 204 No Content response. Screenshots showing the response in XML and JSON formats are shown below_.  It's not clear how two diff returns are possible, make that explicit like the previous example - or if it's the case returning null returns a 204, add that to the code comment and point it out.
- [ ] break up ro sentences.
- [ ] Content Negotiation Process - consider using a list
- [ ] remove note dialog on _If the Accept header contains_

**Comment by sksbrg** [comment]
Hi,
I was stuck with following error when expecting the out-of-the-box JSON content formatting of ASP.NET Core MVC to be applied when serializing a list to the response:
`warn: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]No output formatter was found for content type ‘’ to write the response.`

Thanks to the articles of [Fabian Gosebrink](https://offering.solutions/blog/articles/2017/02/07/difference-between-addmvc-addmvcore/) and [Ben Foster]( http://benfoster.io/blog/bare-metal-apis-with-aspnet-core-mvc) I learned about the difference between using "AddMvc()" and "AddMvcCore()" methods. When using "AddMvcCore()" it is needed to explicitly specify the usage of the JSON formatter ("AddJsonFormatters()") and I would suggest to reflect this in the documentation. Maybe this could be done as part of the planned rework.

**Comment by Rick-Anderson** [comment]
moved to #10189
