### ISSUE TITLE
Is there any interest in contribs for updating samples for RTM?

### ISSUE THREAD

**Issue by LeeDumond** [aspnet/Docs#1974]
Just wondering if the team would welcome contributions on updating some of the sample solutions that break on the RTM version of ASP.NET Core. Many of them only work with the preview versions which many folks probably don't have on their machines.

**Comment by Rick-Anderson** [comment]
@LeeDumond We would greatly appreciate the help, however can you hold off for now? We're going to freeze this repository while we make some changes. cc @danroth27

**Comment by LeeDumond** [comment]
OK, no problem, I will keep an eye out...

**Comment by guardrex** [comment]
@Rick-Anderson Since there's an on-going effort for sample updates to 2.0 now, is this still relevant?
