### ISSUE TITLE
[1.1 New Feature] Add docs for EventSource Logger Provider

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#1979]
Working on testing this right now and I noticed there's no doc. I'll try to add notes here as I go. If I have some cycles after sign-off I'll try to get the doc written up myself, otherwise there should be enough notes here for someone else to take it
- How to install (package ID, version, etc.): `Microsoft.Extensions.Logging.EventSource` `1.1.0-...`
- How to enable: `loggerFactory.AddEventSourceLogger`
- How to read the events using PerfView:
  - Add the string `*Microsoft-Extensions-Logging` to the "Additional Providers" list when collecting.
- <del>How to read the events using Windows Performance Analyzer?</del> (very difficult)
- <del>How to read the events using Microsoft Message Analyzer?</del> (very difficult; crashes)

**Comment by anurse** [comment]
# Screenshots from PerfView

### Collecting events

![image](https://cloud.githubusercontent.com/assets/7574/19492875/5ec04744-952d-11e6-9ab4-486e0b258fb0.png)

**Comment by anurse** [comment]
# Capturing from Nano Server

**Prerequsite:** The app is up and running on Nano, with the `EventSource` logger configured.

1. Connect PowerShell remoting to the Nano Server (`Enter-PSSession [name]`)
2. Create an ETW session: `New-EtwTraceSession -Name "MyAppTrace" -LocalFilePath C:\trace.etl`
3. Add ETW providers
  1. [CLR Provider](https://msdn.microsoft.com/en-us/library/ff357718(v=vs.110).aspx): `Add-EtwTraceProvider -Guid "{e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}" -SessionName MyAppTrace`
  2. ASP.NET Logging Provider (the GUID for this is not currently documented, but you can determine it by calling `EventSource.GetGuid` on the [LoggingEventSource](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging.EventSource/LoggingEventSource.cs) type: `Add-EtwTraceProvider -Guid "{3ac73b97-af73-50e9-0822-5da4367920d0}" -SessionName MyAppTrace`
  3. Other ETW Providers as desired
4. Run the site, performing any actions you want to perform
5. **IMPORTANT** when finished, run `Remove-EtwTraceSession MyAppTrace`

Trace sessions are **global** and must be cleaned up **manually**. Don't forget the last step!

The `C:\trace.etl` file can be analyzed with PerfView just as before.

**Comment by Rick-Anderson** [comment]
Looks like this was added to [Intro to logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x)

**Comment by alexiordan** [comment]
Reactivating an old thread.
Is this also available for UWP app?

For an Windos 10 IoT UWP app, how can one see the generated ETW in device portal once has added
`.AddEventSourceLogger()`

In Windos 10 IoT device portal Custom providers can only be added by GUID.
