### ISSUE TITLE
[1.1 Upgrade Docs] When upgrading from 1.0 to 1.1, publish profiles need to be updated.

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#1985]
Changing the Target Framework Moniker (TFM) in the _project.json_ does not update the Publish Profile settings, which also need to be updated (specifically `[Project Name]/Properties/PublishProfiles/[Profile Name].pubxml` which has a `PublishFramework` setting).

We should make sure to document this in upgrade docs.

/cc @danroth27 @muratg

**Comment by anurse** [comment]
This manifests as a publish failure if you update project.json to use the new TFM, and re-publish without editing the Publish Profile:

```
C:\Program Files (x86)\dotnet\dotnet.exe publish "C:\Users\anurse\Code\anurse\netcore11-preview1-signoff\src\SignOffApp" --framework netcoreapp1.0 --output "C:\Users\anurse\AppData\Local\Temp\PublishTemp\SignOffApp86" --configuration Release --no-build
'C:\Users\anurse\Code\anurse\netcore11-preview1-signoff\src\SignOffApp' cannot be published for 'netcoreapp1.0' '<no runtime provided>'
```

Note that you can edit the profile by pressing "Back" in the dialog, and in fact you don't have to do anything since the TFM drop down automatically resets to the the TFM in your project, so just moving back and then forward again in the Publish Wizard actually solves the issue.

**Comment by Rick-Anderson** [comment]
@tdykstra  where would this go?

**Comment by tdykstra** [comment]
@Rick-Anderson a new doc under Migrations in the TOC, or just a new section in the [1.1 what's new](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-1.1).

**Comment by Rick-Anderson** [comment]
@anurse now that we're on _csproj_ do we still need to document this?

**Comment by anurse** [comment]
I don't think it's needed any more.
