### ISSUE TITLE
missing favicon

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#1986]
Missing Microsoft Logo for all the links/pages under  " https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/intro "
when viewed in IE11.

**Comment by Rick-Anderson** [comment]
@Prasanna-Rani  can you attach a screen shot?

**Comment by Prasanna-Rani** [comment]
![1986](https://cloud.githubusercontent.com/assets/22809209/19569888/0df21cb8-9715-11e6-97ce-775c9d99b8f3.PNG)

Here is the screenshot Rick

**Comment by Rick-Anderson** [comment]
@danroth27 @bradygaster will we get the favicon automatically?

**Comment by Rick-Anderson** [comment]
It will be there when we publish. Doesn't show in IE/Edge now but does show in Chrome/FF
