### ISSUE TITLE
DocFX - aspnet/aspnetcore/tutorials/your-first-mac-aspnet , Your First ASP.NET Core Application on a Mac Using Visual Studio Code

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#1987]
Step1:Navigate to https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/tutorials/your-first-mac-aspnet page.
Step2: View the code block under "Running Locally Using Kestrel"
Actual Result : "Microsoft.AspNetCore.Server.Kestrel": is only being displayed( i.e only the yellow colored code)
Expected Result : In Live Environment 
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0", 

is being displayed

**Comment by Rick-Anderson** [comment]
In this case, I removed everything but the package, and removed the version number because version numbers changes. Thanks.
