### ISSUE TITLE
ASP.NET Core Tutorials 

### ISSUE THREAD

**Issue by venkatapidikiti** [aspnet/Docs#1989]
Hi,
I am unable to find ASP.NET Core tutorials using "Visual Studio Code" whilst "Visual Studio".
Here is ref link:https://docs.asp.net/en/latest/tutorials/
Thanks
Venkatta

**Comment by Rick-Anderson** [comment]
see (Your First ASP.NET Core Application on a Mac Using Visual Studio Code)[https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html]
