### ISSUE TITLE
DNX Compilation

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#199]
DNX -> Compilation
- Compilation options
- Compile Modules

**Comment by danroth27** [comment]
Covered by #50

**Comment by diddledan** [comment]
is this really done? checking https://docs.asp.net/en/latest/dnx/compilation.html points here saying the document isn't written, so I'm guessing the label `3 - done` is incorrect...

**Comment by diddledan** [comment]
alternatively the linked #50 is incorrectly marked as complete. Either way one of these issues is wrong?

**Comment by danroth27** [comment]
The intent here was to close this bug as a duplicate of #50, but it looks like we never removed the corresponding compilation topic from the TOC. 

Pretty soon we will be moving off of DNX and onto the new [.NET CLI](https://github.com/dotnet/cli), so these docs will all get removed and instead we will point to http://dotnet.github.io/docs.

**Comment by diddledan** [comment]
thanks for the update. That makes sense :-)
