### ISSUE TITLE
Doc about web.config recycleOnFileChange being no-op in ASP.NET Core

### ISSUE THREAD

**Issue by muratg** [aspnet/Docs#1990]
Source https://github.com/aspnet/IISIntegration/issues/291

- `recycleOnFileChange` in web.config currently no-ops for ASP.NET Core apps. We can't remove it from the schema, so this should be documented.
- `AddJsonFile("appsettings.json", reloadOnChange: true)` is the ASP.NET Core way of achieving this

Current doc seems a little sparse on this detail: https://github.com/Microsoft/Docs-1/blob/master/aspnet/aspnetcore/fundamentals/configuration.md#using-the-built-in-sources

**Comment by GuardRex** [comment]
@shirhatti and I removed the `recycleOnFileChange` from the ANCM doc in https://github.com/Microsoft/Docs-1/pull/52 ... I think the thinking was that it isn't configurable, so we could just cut it from the doc (as opposed to listing it and stating it isn't configurable).

**Comment by danroth27** [comment]
We'll handle this as part of #1965.

**Comment by spboyer** [comment]
Closed with #1965
