### ISSUE TITLE
Docfx- /aspnet/aspnetcore/fundamentals/localization ,Globalization and localization

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#1991]
There is a table under the topic "Resource file naming"
Table is not Correctly displayed. I mean its an Open Table.
Below is the screenshot of the same.

![table](https://cloud.githubusercontent.com/assets/22809209/19570020/b50ec4e2-9715-11e6-8685-03345122314f.PNG)

**Comment by Prasanna-Rani** [comment]
similar issue is found with the table in https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/fundamentals/logging     page.

**Comment by Prasanna-Rani** [comment]
similar issue in  https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/fundamentals/owin page . here it looks more clumsy with continuous tables.

![table1](https://cloud.githubusercontent.com/assets/22809209/19570342/28e9f08e-9717-11e6-9e38-8f754ff4893a.PNG)

**Comment by Rick-Anderson** [comment]
See https://help.github.com/articles/organizing-information-with-tables/
GFM tables are very limited - I don't think there is anything we can do to improve them.
