### ISSUE TITLE
suggestion you write full namespace in your code thank you.

### ISSUE THREAD

**Issue by 50774283** [aspnet/Docs#2000]
such as:
services.ConfigureSwaggerGen(options =>
{
    options.SingleApiVersion(new Info
    {});
});

some developer don't use Visual Studio,so we're unable to know the namespace of the class Info.
i had take too much  time for resolve this issue and very disappointed.
thank you.

**Comment by spboyer** [comment]
[Omnisharp](https://www.omnisharp.net/#integrations) - offers intellisense cross platform within Vim, Emacs, Visual Studio Code, Brackets and other text based editors.  Have you tries this add-in?
