### ISSUE TITLE
DocFX - aspnet/aspnetcore/mvc/models/model-binding , Introduction to model binding

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2004]
Some links are pointing to staging environment and some links are pointing to Production Environment.
like ...
routing (https://docs.asp.net/en/latest/mvc/controllers/)
validation  (https://docs.asp.net/en/latest/mvc/models/)

**Comment by Rick-Anderson** [comment]
@Prasanna-Rani can you give me the URL or page where these links occur?

**Comment by Prasanna-Rani** [comment]
Hi Rick , I mentioned the link in the title of the bug itself .
Url of the page : https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/models/model-binding

In this page we can find the links under the Topic "**How model binding works**"
routing --- this leads to (https://docs.asp.net/en/latest/mvc/controllers/)
 validation---- this leads to  (https://docs.asp.net/en/latest/mvc/models/)

**Comment by Rick-Anderson** [comment]
fixed
