### ISSUE TITLE
DocFX - /aspnet/aspnetcore/mvc/models/formatting, Formatting Response Data

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2005]
Links "System.Xml.Serialization.XmlSerializer" and " System.Runtime.Serialization.DataContractSerializer" are leading to Page not found. below is the screen shot

![bug2](https://cloud.githubusercontent.com/assets/22809209/19696285/13ab8e94-9b04-11e6-9146-b4da0f31899b.PNG)

**Comment by Rick-Anderson** [comment]
@Prasanna-Rani  where are you finding these links?

**Comment by Prasanna-Rani** [comment]
In this page " https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/models/formatting" 
Under the topic " Configuring Formatters " 
Here is the screenshot 

![2005](https://cloud.githubusercontent.com/assets/22809209/19715942/647f764c-9b76-11e6-9c96-a1c2ae1d2f3a.PNG)

**Comment by Rick-Anderson** [comment]
removed links
