### ISSUE TITLE
VSTS continuous deployment improvement suggestions

### ISSUE THREAD

**Issue by xdaDaveShaw** [aspnet/Docs#2007]
The [VSTS continuous deployment](https://docs.asp.net/en/latest/publishing/vsts-continuous-deployment.html) has a few issues that could be improved on:
1. It recommends the installation of a 3rd party marketplace extension to zip files when there is a built in one.
2. The Copy and Publish step doesn't work as well as the Publish Build Artifacts.

I've create fork with my suggested improvements [here](https://github.com/xdaDaveShaw/Docs/commit/7655e89846f64a48863a57bbc7175f4e2bcebc1f), happy to create a PR, if you want these.

**Comment by Rick-Anderson** [comment]
@sayedihashimi  are you the right reviewer?
@xdaDaveShaw  you caught us in the middle of converting from .RST to GFM (.MD).

**Comment by sayedihashimi** [comment]
@rick-Anderson, I think Chris Patterson would be a better suited reviewer but I'm willing to help as needed.

**Comment by Rick-Anderson** [comment]
@sayedihashimi  do you mean @chrisrpatterson ?

**Comment by sayedihashimi** [comment]
Yes

**Comment by chrisrpatterson** [comment]
@Rick-Anderson  I left some comments on your PR.

**Comment by xdaDaveShaw** [comment]
@Rick-Anderson - I didn't see the memo on the README - that will teach me to read the docs on the docs :). I'll wait until the conversion is over before I create a PR.

**Comment by Rick-Anderson** [comment]
@xdaDaveShaw  I probably put the note in after your PR :-(

**Comment by xdaDaveShaw** [comment]
I've restarted my work on a new branch following the markdown changes. First commit is [here](https://github.com/xdaDaveShaw/Docs/commit/a495edea63630d3d3697a2decbbae41fdc969bd7) - will be adding Azure RM as suggested by @chrisrpatterson before raising a PR.

**Comment by xdaDaveShaw** [comment]
Given the new build UI and the improved dotnet cli support and Azure RM changing. My changes are out of date again.
If someone else wants to pick this up, they can. If not I'll get around to it when I can.
