### ISSUE TITLE
Issue with environment variable case sensitivity

### ISSUE THREAD

**Issue by grbinho** [aspnet/Docs#2012]
In the documentation about [environments ](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md)

This section is not valid for Linux.

> The specified environment name is case insensitive. Whether you set the variable to Development or development or DEVELOPMENT the results will be the same.

I ran into this issue couple of days ago. Case matters.

For example , if you are reading a configuration file depending on the environment, file is called
`appsetings.production.json` and variable is set to "Production". Code that might be using `env.EnvironmentName` will not read the file on Linux. It will try to read `appsettings.Production.json`.

**Comment by Rick-Anderson** [comment]
@grbinho  I think it might be the case that "The specified environment name is case insensitive." is true for environment variables but not for file names.

We could make it clear that the file names are case sensitive.

**Comment by Rick-Anderson** [comment]
master issue #2028

**Comment by spboyer** [comment]
Closing. #2424 addressed issue.
