### ISSUE TITLE
DocFX-/aspnet/aspnetcore/mvc/views/overview,Views Overview

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2013]
Url of the page -https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/overview

Following  2 Links are redirecting to Production Environment
![capture1](https://cloud.githubusercontent.com/assets/22809209/19778058/b0b53b1e-9c98-11e6-94e3-6528d19a9034.PNG)

**Comment by Prasanna-Rani** [comment]
Hi Rick,
Following are some more pages where links are redirecting to Production Environment.
Url: https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/razor
screenshot
![capture1234](https://cloud.githubusercontent.com/assets/22809209/19778572/034ea03e-9c9b-11e6-986e-ea14cfd158ce.PNG)

Same page
![capture125](https://cloud.githubusercontent.com/assets/22809209/19778847/2b0c93dc-9c9c-11e6-84b7-f12b69a24261.PNG)

**Comment by Prasanna-Rani** [comment]
url: https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/working-with-forms

**Comment by Prasanna-Rani** [comment]
url: url: https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/working-with-forms

Under the Heading "HTML Helper alternatives to Input Tag Helper"

![capture128](https://cloud.githubusercontent.com/assets/22809209/19779510/0cdcc564-9c9f-11e6-8dd9-13f53b453de4.PNG)

**Comment by Rick-Anderson** [comment]
these will be fixed with #2079
