### ISSUE TITLE
DocFX- /aspnet/aspnetcore/mvc/views/razor,Razor Syntax Reference

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2014]
Url of the  page: https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/razor

Under the Heading "Razor syntax" a Link with the name "Razor reserved keywords" is missing

Below is the Screenshot
![capture2](https://cloud.githubusercontent.com/assets/22809209/19778375/078eff78-9c9a-11e6-9924-c86f8ce68214.PNG)

**Comment by Prasanna-Rani** [comment]
Same url : https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/razor

Under the Heading "Directives"  a link with name "Viewing the Razor C# class generated for a view  " link is missing.
Screenshot
![capture126](https://cloud.githubusercontent.com/assets/22809209/19779058/15f54d58-9c9d-11e6-95e3-e31a8fe2cba9.PNG)

**Comment by Rick-Anderson** [comment]
fixed by https://github.com/aspnet/Docs/pull/2102
