### ISSUE TITLE
Suggestion: Consider adding information regarding running a published application in Docker

### ISSUE THREAD

**Issue by ckelner** [aspnet/Docs#2016]
I had been having some difficulty getting a published dotnet app running happily inside a docker container and couldn't find any decent examples anywhere.  I put together an example [here](https://github.com/ckelner/aspnetcorespa-example#aspnet-core-spa-example) both to help myself (bare minimum boilerplate to remove any self introduced issues) and to serve as an example of what I'd like to see from the aspnet contributors.

I can see where it is both beneficial to include a Dockerfile for local development and testing, and where it is beneficial to have one that would be used for production.  I'm pretty new to Docker, so I'm not sure how to maintain two Dockerfiles for different scenarios in the same project (I've yet to research) so I am uncertain if you could provide both through a yeoman generator or not.  Perhaps simply documentation that expands on this article: https://docs.asp.net/en/latest/publishing/linuxproduction.html ?

Thanks for all the hard work.  I haven't touched dotnet in years but this tooling and documentation is pretty great compared to what I had used in the past (love that I can use it under osx as well, big plus on the cross platform stuff).

**Comment by danroth27** [comment]
@spboyer Can you provide a link to our current guidance?

**Comment by spboyer** [comment]
@ckelner - Here are a few articles on using our tools for running apps in containers.
https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images
https://docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker
https://blogs.msdn.microsoft.com/stevelasker/2016/09/29/building-optimized-docker-images-with-asp-net-core/
