### ISSUE TITLE
DocFx-/aspnet/aspnetcore/mvc/views/tag-helpers/intro,Introduction to Tag Helpers

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2018]
url of the page :https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/tag-helpers/intro 

Unlike other Documents, the Section topics are mentioned twice ...one under "In this Article(Right side of the page) another in the document itself

Screenshot

![capture130](https://cloud.githubusercontent.com/assets/22809209/19815908/a3bcae7c-9d62-11e6-8336-55efaea82092.PNG)

**Comment by Rick-Anderson** [comment]
@Prasanna-Rani  nice catch. Fixed by https://github.com/aspnet/Docs/pull/2043
