### ISSUE TITLE
DocFX- /aspnet/aspnetcore/mvc/views/tag-helpers/intro,Introduction to Tag Helpers

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2019]
Url of the page: https://review.docs.microsoft.com/en-us/aspnet/aspnetcore/mvc/views/tag-helpers/intro

Links are redirecting Production Environment
![capture131](https://cloud.githubusercontent.com/assets/22809209/19816021/2bfa99ca-9d63-11e6-8343-0eb2dee812c0.PNG)

![capture132](https://cloud.githubusercontent.com/assets/22809209/19816060/56bdd8d4-9d63-11e6-8367-a03b18c4bd6f.PNG)

![capture133](https://cloud.githubusercontent.com/assets/22809209/19816190/f433e3ce-9d63-11e6-839c-e3c9a4270943.PNG)

**Comment by Rick-Anderson** [comment]
@Prasanna-Rani  great catch, fixed via https://github.com/aspnet/Docs/pull/2043
