### ISSUE TITLE
HTTP Abstractions

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#202]
Fundamentals -> HTTP Abstractions

Cover the new HttpContext and how to use it.

**Comment by craigsmitham** [comment]
Looking forward to this - main question I have is how does the `Microsoft.AspNet.Http` namespace relate to `System.Net.Http`? Will there be an HTTP client that uses `Microsoft.AspNet.Http`?

**Comment by davidfowl** [comment]
> Looking forward to this - main question I have is how does the Microsoft.AspNet.Http namespace relate to System.Net.Http

There's no relation between the 2 namespaces. You can get at strongly typed headers in System.Net.Http using an extension method http://odetocode.com/blogs/scott/archive/2015/11/30/working-with-typed-headers-in-asp-net.aspx.

> Will there be an HTTP client that uses Microsoft.AspNet.Http

Nope. `Microsoft.AspNet.Http` was designed specifically for the server.

**Comment by dumbledad** [comment]
[The docs](https://docs.asp.net/en/latest/fundamentals/http-abstractions.html) mention that if we "would like to review early drafts and outlines of this topic, please leave a note with your contact information" here. Yes please, my Microsoft alias is timregan

**Comment by danroth27** [comment]
We think this topic is sufficiently covered by the following articles:
- https://docs.asp.net/en/latest/fundamentals/middleware.html
- https://docs.asp.net/en/latest/fundamentals/request-features.html
- https://docs.asp.net/en/latest/fundamentals/servers.html
