### ISSUE TITLE
How to show date/time in client time zone, not server

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2024]
> There is no word on how to get client's local date/time to the server. Its not clear if Asp.Net Core helps with that in any way like it helps with client's culture capturing. At least you should have noted that model bindings use server's time zone when parsing date/time values with no offset specified. The same is regarding formatting date/time values for response: while client's culture is automatically used, the time zone offset is taken from the server system.

Image I want the [F1 schedule](http://www.espn.com/racing/schedule/_/series/f1) but displayed in clients time zone.  
- Save client time zone (TZ) in users profile and add to session
- Apply TZ offset in time responses

customer asked this question in[ Globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) but that's probably not the best place to provide guidance.

cc @danroth27

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS please comment.

**Comment by SteveSandersonMS** [comment]
Browsers aren't required to automatically send the user's timezone to the server with each request. The HTTP spec doesn't require that.

So if you need that information on the server, you'll need to run some client-side code to grab the timezone offset and put it somewhere that will get sent back to the server, such as a hidden form field. Example here: http://stackoverflow.com/questions/40510963/how-to-get-user-timezone-offset-and-send-it-to-the-server-in-asp-net-application/40511542

Alternatively, if you're building your UI with JavaScript (e.g., in an Angular/React/etc application) just send the dates from the server to the client in UTC, and then have client-side logic for displaying it in the local date format and offset.

**Comment by andriysavin** [comment]
As a question author, I meanwhile found a "workaround": I render all date/times in a UTC or in a "with offset" format, and use client-side JS to convert these to local time. Similar is for input: I make any entered date/time to carry the offset with it (or, alternatively, can convert to UTC). But I'd say its pretty inconvenient to implement that in every app. Especially this concerns date/time input, where support for time zone offset is either absent (HTML5) or inconsistent. This is why I call this a workaround. Its sad that with server html rendering framework you have to cooperate with client side script for such a basic task...

**Comment by Rick-Anderson** [comment]
This is a client side issue, not server so closing.
