### ISSUE TITLE
fundamentals/localization "Globalization and localization" perf

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2025]
Suppose I support limited number of translations, but I want to handle every possible culture in terms of formatting. E.g. I have only English version of the web app, but want users to see date-time and number formatting which correspond to their system setting. Is it ok to do this like:

```
services.Configure<requestlocalizationoptions>(options =>
{
options.SupportedCultures = CultureInfo.GetCultures(CultureTypes.AllCultures);
options.SupportedUICultures = new[] { new CultureInfo("en-US") };
});
```

My concern here is about specifying an array of ALL (832) cultures which will be checked at every request - can that have noticeable performance impact? Is there more correct way to achieve what I need?

My intuitive thinking was that the runtime should just try to instantiate a CultureInfo with client's culture if, say, supported cultures are not specified, but in this case I guess it will fallback to default culture.

This question from fundamentals/localization topic.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please comment

**Comment by ryanbrandenburg** [comment]
I ran a quick test on the LocalizationWebsite to see if it was noticably slow in this scenario and it didn't seem to be. Also, `CultureInfo.GetCulture` and `CultureTypes` are both removed from .NET Core so for people using that this patern isn't even an option. Further, I think it's unlikely to be useful for a number to be formated for a persons language if the page isn't in their language.

Overall I don't think we really need to address this scenario in the docs as it's an edge case.

**Comment by Rick-Anderson** [comment]
I agree, great work.

**Comment by andriysavin** [comment]
>  I think it's unlikely to be useful for a number to be formated for a persons language if the page isn't in their language.
The page can be not in their language not because they set different language on their system, but because the web site doesn't have translation to their language. But at least such site could give the user what doesn't require translation effort: the formatting. 

For example, suppose you're working on a flight or hotel booking app, you support not every language, but want users to see dates, numbers and currency formatting as they're used to see them. For example, en-US culture formats dates so month goes first, then day (MM/dd). But in many other cultures day goes first, then month (dd/MM). If the user sees 05/04/2016, how can he be sure which exact date this means?

**Comment by ardalis** [comment]
@andriysavin For date formats at least, using something like dd MMM yyyy as the format tends to be clear worldwide, even if the language used for the months isn't translated (as you already noted). That's why it's my preferred online format.
(written 4 Nov 2016)

**Comment by andriysavin** [comment]
@ardalis I agree if you display dates as  "4 Nov 2016" it removes any confusion. But its not always acceptable. Sometimes (and often) you want a numeric format.

**Comment by ryanbrandenburg** [comment]
To be clear, I'm not saying there's anything WRONG with doing it the `CultureTypes.AllCultures` way or that we don't support it, I'm just saying that it's an edge case for the reasons listed above and therefore not something we need to address in our high level documentation.

**Comment by andriysavin** [comment]
@ryanbrandenburg Ok, at least this approach works, and works without performance issues. But how can this case be addressed on the .NET Core, where, as you said, these APIs are removed? I understand this is not docs-related, but since we already started...

**Comment by ryanbrandenburg** [comment]
I know of no alternative to `CultureInfo.GetCultures`. You can check out [this](https://github.com/dotnet/corefx/issues/1669) issue for a little background on the how and why on the lack of `CultureInfo.GetCultures`. My best suggestion would be to select the list of cultures you feel are most important to your apps user base.

**Comment by andriysavin** [comment]
@ryanbrandenburg Thanks!
