### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#203]
Fundamentals-> Unit Testing
- Unit testing
  - Create a unit testing project
  - Add the test runner package (xunit.runner.dnx)
    - Don't refer to xunit.runner.aspnet!!!
  - Add a test command named test, point to the runner
  - Write your tests
  - VS should "just work", or run `dnx test` at the command-line
     - Gotchas: have the test window open and not minimized, do a build in VS

**Comment by ardalis** [comment]
I'm going to get started on this article this week. Let's meet if we need to nail down some more specifics, @danroth27

**Comment by ardalis** [comment]
* How to Create Test Projects
* How to Run Test
