### ISSUE TITLE
Travis fails with Could not find .travis.yml

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2036]
see https://github.com/aspnet/Docs/pull/2034 for an example
cc @danroth27

**Comment by danroth27** [comment]
@Eilon Did you disable travis for the docs repo?

**Comment by Eilon** [comment]
Not yet, got distracted. But haven't forgotten.

**Comment by Eilon** [comment]
Travis should now be disabled. Thanks!
