### ISSUE TITLE
Export DISQUS comments

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2038]
There is a way to export the comments:
https://help.disqus.com/customer/portal/articles/472149-comments-export

However, the same “Export” doesn’t follow their own import guidelines:

Note: exports are designed for backup purposes only and do not follow the same format as our custom XML import format. Exports cannot be re-imported to other Disqus forums.

We are aware that the comments will be lost, and recommend for everyone who needs their comments for future reference to export them directly through the article above.

cc @danroth27

**Comment by spboyer** [comment]
This should be closed? Decided not to export correct? @danroth27 @Rick-Anderson
