### ISSUE TITLE
fix broken download links  

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2039]
For example in _Docs\aspnetcore\data\ef-mvc\intro.md_
`You can [download the completed application](https://github.com/aspnet/Docs/tree/master/aspnet/data/ef-mvc/intro/samples/cu-final)`

I think you just need to search for `(https://github.com/aspnet/Docs/tree/master/aspnet` and replace with
`(https://github.com/aspnet/Docs/tree/master/aspnetcore`

This string below shows the broken/fixed segments of the link:

```
(https://github.com/aspnet/Docs/tree/master/aspnet
(https://github.com/aspnet/Docs/tree/master/aspnetcore
```

The correct link for the data/ef-mvc tutorial is:

You can [download the completed application](https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-mvc/intro/samples/cu-final)

@v-anpasi is this something you could fix?
@tdykstra  please review

**Comment by tdykstra** [comment]
@Rick-Anderson Yes that's correct
