### ISSUE TITLE
Introduction to NuGet

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#205]
Conceptual Overview -> Introduction to NuGet
- Package sources
- Installing packages
- Restoring packages
- Creating packages
- Target frameworks

**Comment by danroth27** [comment]
Lots of references to http://docs.nuget.org.

**Comment by AndybSe** [comment]
need a contributor for this one?

**Comment by danroth27** [comment]
I think actually I'm going to close this one. We should just be linking to http://docs.nuget.org and the .NET docs.
