### ISSUE TITLE
remove U+FEFF hex char from metadata 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2051]
See 
- https://github.com/aspnet/Docs/pull/2050
- https://github.com/aspnet/Docs/commit/968ef5ecbff30ff82001de9f8640235f9c217b8b
- https://github.com/aspnet/Docs/edit/master/aspnetcore/fundamentals/error-handling.md

I've fixed several of these. They are invisible in notepad++ but they cause notepad++ not to work correctly and they break XID links. The hex char shows up like a ? in Visual Studio Code but is invisible in notepad/notepad++/visual Studio.

@v-anpasi we need to remove these.
@spboyer  do you know what the character is?

**Comment by spboyer** [comment]
Are all of the ones you have fixed located in front of the `uid` ?

I cannot identify what the character is, just happen to notice it in VSCode.

**Comment by Rick-Anderson** [comment]
YOu can see it in https://github.com/aspnet/Docs/edit/master/aspnetcore/publishing/linuxproduction.md

**Comment by Rick-Anderson** [comment]
@tdykstra  found http://stackoverflow.com/questions/17912307/u-ufeff-in-python-string

**Comment by v-anpasi** [comment]
Fixed in https://github.com/aspnet/Docs/pull/2073
