### ISSUE TITLE
Verify all static links

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2059]
Verify all the static links in [ASP.NET Core docs](https://review.docs.microsoft.com/en-us/aspnet/core/?branch=saldanatest)

I've used http://validator.w3.org/checklink
Even with recursive it doesn't seem to be checking everything in the TOC. You might need to check https://docs.asp.net/en/latest/ and then check https://docs.microsoft.com/en-us/aspnet/core/ once the URL is  public

@tdykstra  can you do this? @danroth27  can you recommend an approach?

**Comment by tdykstra** [comment]
@Rick-Anderson Can you clarify what you're asking for -- what do you mean by static links, are you talking about TOC links, do you mean every link in every doc in the site, what issues have you seen / do you expect?

**Comment by Rick-Anderson** [comment]
Internal links are validated by OPS. We just need all external links validated. In our case we need the tool to recuse the TOC links to hit every document.

**Comment by Rick-Anderson** [comment]
![capture](https://cloud.githubusercontent.com/assets/3605364/19939168/ed3dabca-a0cb-11e6-993a-41fa5f5d0a89.PNG)

All the links on the RTD site are being tested. We might need to wait until the OPS site is public.

**Comment by neusamir** [comment]
We have a broken link checker that can do the crawling. Reply back when the OPS site is public and I can run it.

**Comment by tdykstra** [comment]
@neusamir The site is public at https://docs.microsoft.com/en-us/aspnet/core/ - please go ahead and run your link checker.

**Comment by tdykstra** [comment]
@neusamir -- do you have an ETA on when we can get the link checker run on https://docs.microsoft.com/en-us/aspnet/core/ ?

cc: @Rick-Anderson
