### ISSUE TITLE
File Providers

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#206]
Fundamentals -> File Providers
- File Providers as an abstraction over file systems
  - IFileProvider, IFileInfo, IDirectoryContents
  - Wraps System.IO.File (but also is scoped to a directory, and all paths are from that directory going forward)
  - Get a file, get folder contents, watch for changes
- Concrete implementations
  - Physical
  - Embedded (assembly resources)
  - Composite (aggregates over multiple file providers)
- Globbing Patterns (used e.g. by Watch's filter parameter)
  - * behavior
  - ** behavior
  - Examples: a file, a folder, all files of a certain type in a folder

Behavior of DOTNET_USE_POLLINGFILEWATCHER:
- Set to 1 or true, for docker containers and network shares where we don't reliably get notifications of changes
- Polls every 4s looking for file system changes
- Otherwise just wraps BCL FileSystemWatcher with IChangeToken abstraction

Where are file providers used in ASP.NET Core?
- Static files middleware
- Configuration
- IHostingEnvironment
  - scoped to physical folder where web app lives
  - IFileProvider ContentRootFileProvider, WebRootFileProvider in IHostingEnvironment
- Razor uses IFileProvider
- Publish in dotnet

https://github.com/aspnet/filesystem

**Comment by HornerGrahame** [comment]
would be nice to have an example of how to create and register a custom IFileProvider. This would allow the community to develop FileSystem providers for cloud/nosql and other type of storage for content management.

**Comment by Montagne1984** [comment]
How can I read a file in the web application? Is this topic about this?

**Comment by avishekhbharati** [comment]
How can I write the logs to the text file ?

**Comment by danroth27** [comment]
You can plug existing third-party logging frameworks into the [Logging](https://docs.asp.net/en/latest/fundamentals/logging.html) framework. Ex [Serilog](https://www.nuget.org/packages/Serilog.Sinks.File) is a good option.
