### ISSUE TITLE
Post conversion: Update Intro page

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2065]
Consider updating the Intro page to look something like the [.NET intro page](https://docs.microsoft.com/en-us/dotnet/articles/welcome).

**Comment by Rick-Anderson** [comment]
Consider updating the Intro page to look something like the [.NET intro page](https://docs.microsoft.com/en-us/dotnet/articles/welcome).

**Comment by danroth27** [comment]
I think we agreed to go with the Intro to ASP.NET content for this page.
