### ISSUE TITLE
Enable Travis and AppVeyor for external PR's

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2067]
OPS probably doesn't validate external PR's from customer forks. OPS validates our PR's that are branch based.

**Comment by spboyer** [comment]
@Rick-Anderson @danroth27 - According to @bradygaster Travis wont give us anything more than the OPS Builds.

**Comment by Rick-Anderson** [comment]
@spboyer @bradygaster can you confirm OPS runs on a fork from an external PR? How does it do that? OPS is fine when internal folks submit a branch.

**Comment by spboyer** [comment]
Closing this, OPS is building all PRs
