### ISSUE TITLE
Update link on docs.microsoft.com to aspnet

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2069]
[docs.microsoft.com](docs.microsoft.com) has a link to [ASP.NET Core](docs.asp.net) which currently points to [docs.asp.net](docs.asp.net)

Make sure this fwlink points to something reasonable, probably not the  [ASP.NET hub ](https://review.docs.microsoft.com/en-us/aspnet/ ) page.

See what the .Net folks are doing.

**Comment by Rick-Anderson** [comment]
@bradygaster  can you own this

**Comment by Rick-Anderson** [comment]
From: Adam Kinney 

That’s a good point. 

Kim, you will need to update the .NET Hub Page links excel file that you sent Jason. Is that available on a share so the content can be updated?

From: Brady Gaster 

Subject: RE: [aspnet/Docs] Update fwlink on docs.microsoft.com (#2069)

I agree with Adam. We want to edit both the .NET and Docs.ms.com home page HTML as late as possible but still get it pushed out in time for Connect so that we link to docs.ms.com/aspnet instead of RTD.

**Comment by bradygaster** [comment]
@Rick-Anderson paraphrasing earlier comment and email - i'm working with dev and design to make sure the link is changed on the docs home page at the appropriate time.
