### ISSUE TITLE
DocFX-/aspnet/core/mvc/controllers/routing, Routing to Controller Actions

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2074]
Url of the page  : https://review.docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing

Links are redirecting to Production Environment

screenshot
![capture134](https://cloud.githubusercontent.com/assets/22809209/19939989/2b584dea-a151-11e6-9bed-44ba8d456268.PNG)

same page another area

![capture135](https://cloud.githubusercontent.com/assets/22809209/19940169/bff5fa60-a151-11e6-8347-74dd94a471a5.PNG)

another area in same page

![capture136](https://cloud.githubusercontent.com/assets/22809209/19940317/42eb483a-a152-11e6-8fae-2296e28443f4.PNG)

NOTE:
Rick !Please Don't mind me saying like this.... This Complete Article has links redirecting to Production Environment. Please check

I will retest this Article, once you close this bug.

**Comment by Rick-Anderson** [comment]
move to  #2079
