### ISSUE TITLE
Docfx-/aspnet/core/mvc/controllers/testing#unit-testing,Testing Controller Logic

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2075]
url of the page : https://review.docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing

The document"Testing Controller Logic"  is listed twice in the left pane.

![capture137](https://cloud.githubusercontent.com/assets/22809209/19941967/1efea63c-a158-11e6-96f8-66e90c406339.PNG)

**Comment by ardalis** [comment]
This is by design for discoverability.

**Comment by Rick-Anderson** [comment]
Thanks  @ardalis
