### ISSUE TITLE
DocFx- /aspnet/core/data/ef-mvc/intro, Unit Testing, Working with Data

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2076]
View the documents on sub links/topics 
Testing > Unit Testing    and
Working with Data>Getting started with ASP​.NET Core and Entity Framework Core using Visual Studio>ASP.NET Core Tutorials on the Entity Framework Core docs site
 
These 2 documents are pointing to Production Environment. 

Screenshot

![capture138](https://cloud.githubusercontent.com/assets/22809209/19942843/1f941912-a15b-11e6-83de-6f87f6e09ca8.PNG)

**Comment by Rick-Anderson** [comment]
Nice catches. The first link is correct, that goes outside our repo to the .Net repro. The second was very important to catch and I fixed it with #2100
