### ISSUE TITLE
Replace API links with type name

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2079]
1. Find all links of the form `http://docs.asp.net/projects/api/en/latest/autoapi`
2. remove the link so you just have the type name (for example `UseMvc`)

Many of these are to APIs, for example in _Docs\aspnetcore\mvc\controllers\routing.md_
```
[UseMvc](http://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Builder/MvcApplicationBuilderExtensions/index.html#Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc)

[MapRoute](http://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/AspNetCore/Builder/MapRouteRouteBuilderExtensions/index.html#Microsoft.AspNetCore.Builder.MapRouteRouteBuilderExtensions.MapRoute)
```

 @bradygaster has confirmed there are no redirects on API links.
@v-anpasi is this something you can do?

**Comment by bradygaster** [comment]
@Rick-Anderson do you mean basically to write a GREP script to do this intelligently?

**Comment by Rick-Anderson** [comment]
Yes, but this should be assigned to @v-anpasi  - sorry about that.

**Comment by Rick-Anderson** [comment]
@v-anpasi can you get this done by the end of the week?

**Comment by Rick-Anderson** [comment]
>I think these links will work after we go live. @bradygaster can you confirm?

I assigned to @bradygaster  only to answer this question. If redirects work, this is not an urgent issue.

**Comment by Rick-Anderson** [comment]
redirects to API won't work, so this is a P0.

**Comment by v-anpasi** [comment]
https://github.com/aspnet/Docs/pull/2115
