### ISSUE TITLE
typescript and asp.net 5

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Docs#208]
Hi, I started to write a few sample project using typescript 1.5 beta and vs 2015 rc with angular 1, angular 2, aurelia, react, polymer and with a lot of problems they're starting to work.
May be interesting to create a few articles showing how to create typescript apps with these frameworks?

**Comment by danroth27** [comment]
We actually already have some typescript content in the works for https://github.com/aspnet/Docs/issues/31. The content is actually already written. It just needs to be converted to reST and published.

**Comment by jchadwick** [comment]
Where is it?
