### ISSUE TITLE
Fix download links

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2093]
•	Task [703484](https://mseng.visualstudio.com/TechnicalContent/_workitems?id=703479&fullScreen=true&_a=edit) 

We changed the path to our repro, therefore we need to change the path to the download links. Here is a sample of the old/new

https://github.com/aspnetcore/Docs/tree/master/aspnet/data/ef-mvc/intro/samples/cu-final
https://github.com/aspnetcore/Docs/tree/master/aspnetcore/data/ef-mvc/intro/samples/cu-final

Need a global change of 
https://github.com/aspnetcore/Docs/tree/master/aspnet/
to
https://github.com/aspnetcore/Docs/tree/master/aspnetcore/

@v-anpasi  can you do this today?

**Comment by v-anpasi** [comment]
https://github.com/aspnet/Docs/pull/2116
