### ISSUE TITLE
Update style guide

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2094]
Point to good .Net versions and add our specific info (code snippets)

**Comment by Rick-Anderson** [comment]
@tdykstra  can you get this done today?

**Comment by tdykstra** [comment]
@Rick-Anderson yes

**Comment by Rick-Anderson** [comment]
Use the snippets from my https://github.com/aspnet/Docs/pull/2046
Tomorrow is fine

**Comment by tdykstra** [comment]
Made PR, still have to proofread after I’ve let it sit for a while.

Didn’t make changes to .NET Core docs, instead I linked to them and explained how we do things differently.  Removed contributing folder and put everything in Contributing.md in repo root.  Used your snippet examples but condensed by only showing syntax examples, not rendered snippets, which for the purposes of this doc and keeping it short seems to make sense.  Addressed Wade’s points.

**Comment by Rick-Anderson** [comment]
see https://github.com/aspnet/Docs/pull/2090
we can list banned words in style guide or edit them out every PR. That's the best written customer PR I've ever seen

**Comment by tdykstra** [comment]
That list would apply to all docs.ms.com, not just ASP.NET.  Monica is working on making a style guide with that kind of info available to community contributors.

**Comment by Rick-Anderson** [comment]
They won't add that list, but I see them in most non-trivial PRs.
