### ISSUE TITLE
Add some documentation for claims transformation (Auth)

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#2097]
As part of the initial doc, we should include a caveat about: https://github.com/aspnet/Security/issues/284

~~Also once the fix https://github.com/aspnet/Security/issues/863 makes it in,~~ we should add an example of claims transformation using a request scoped DbContext which has been a common ask.

**Comment by Rick-Anderson** [comment]
@scottaddie  please review

**Comment by scottaddie** [comment]
@HaoK Would the following sample app be a good fit for this doc?
https://github.com/aspnet/AuthSamples/tree/dev/samples/ClaimsTransformation

**Comment by HaoK** [comment]
Sure, do you have some cycles to work on this?  Feel free to update the sample, don't worry about adding functional tests etc for that (unless you really want to), I will do that later when I do a pass through all the samples fleshing out all the functional tests

**Comment by Rick-Anderson** [comment]
Moved to #4055
