### ISSUE TITLE
Additional Web API 2 to MVC 6 Migration content

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#21]
- [x] [Migrating HttpConfiguration logic to the MvcOptions pattern](https://docs.microsoft.com/en-us/aspnet/core/migration/configuration)
- [x] [Migrating message handlers to middleware](https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules)
- [x] Migrating formatters to the new formatter model
- [ ] Using the Microsoft.AspNet.Mvc.WebApiCompatShim package if you are porting a lot of Web API 2 code and you want to use the Web API 2 patterns (method overloading, HTTP verb convention based on method name, HttpRequestMessage/HttpResponseMessage programming model, etc.). #1811

**Comment by tdykstra** [comment]
@danroth27 If the new custom formatters doc addresses "migrating formatters", we can close this old issue.

**Comment by Rick-Anderson** [comment]
#1811 tracked.
