### ISSUE TITLE
Verify DocFX works on Mac

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2104]
@spboyer  can you verify DocFX builds work on Mac. Currently DocFX is not creating the TOC but is creating all the HTML files.

**Comment by spboyer** [comment]
Getting is setup using Mono now.

**Comment by spboyer** [comment]
- Install mono via Homebrew - `brew install mono`
- Download Latest version of DocFX - https://github.com/dotnet/docfx/releases/tag/v2.7.2
- Extract to `\bin\docfx`
- created alias for **docfx**

```
function docfx {
  mono $HOME/bin/docfx/docfx.exe
}

function docfx-serve {
  mono $HOME/bin/docfx/docfx.exe serve _site
}
```

run **docfx** in the `Docs\aspnetcore` directory to build the site, and **docfx-serve** to view the site at http://localhost:8080

**Comment by spboyer** [comment]
@Rick-Anderson - do you want to add this information to the README?

**Comment by Rick-Anderson** [comment]
@tdykstra  can you add these instructions to the appropriate guide?

**Comment by tdykstra** [comment]
Will do

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
