### ISSUE TITLE
aspnet/core/client-side/knockout "Knockout.js MVVM Framework"

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2105]
Url : https://review.docs.microsoft.com/en-us/aspnet/core/client-side/knockout

In this Document certain lines of code which is supposed to be highlighted in Yellow is not highlighted .

Screenshot
![capture139](https://cloud.githubusercontent.com/assets/22809209/20015396/535d05b0-a2e1-11e6-8bc3-e75126102d75.PNG)

![capture140](https://cloud.githubusercontent.com/assets/22809209/20015478/a5008af4-a2e1-11e6-9fe9-ed46b65edcb0.PNG)

![capture141](https://cloud.githubusercontent.com/assets/22809209/20015557/ed19f064-a2e1-11e6-8af4-dce04296f31f.PNG)

6 more code blocks are present in the same page which don't have the necessary code highlighted. please fix there too.

**Comment by Prasanna-Rani** [comment]
same issue( missing yellow color highlighting ) is found in code blocks in  https://review.docs.microsoft.com/en-us/aspnet/core/client-side/less-sass-fa  page also

**Comment by Rick-Anderson** [comment]
@danroth27  can we delete this article?
