### ISSUE TITLE
Gulp prefers existing node packages

### ISSUE THREAD

**Issue by nickvdyck** [aspnet/Docs#211]
Gulp's philosophy is quite different from grunt's, as it is not required to create a plugin or wrapper for each node package. Instead it is preferred to use existing node packages.

For example in the gulp docs there is a dependency on gulp-clean, which has been deprecated for quite some time and for which del is preferred ([blacklist](https://github.com/gulpjs/plugins/blob/master/src/blackList.json)).

Also maybe in the intro mention the different philosophy between grunt and gulp.

I can submit a PR if you want to.
https://github.com/aspnet/Docs/blob/master/docs/client-side/grunt-gulp.rst#using-gulp

**Comment by danroth27** [comment]
@ardalis @DamianEdwards @madskristensen 

Adding some folks to make sure this message is aligned with what we are doing in the tooling.

**Comment by Rick-Anderson** [comment]
@danroth27  @ardalis @DamianEdwards @madskristensen  please review.

**Comment by ardalis** [comment]
@nickvdyck Is this still an issue with the revised version of the Gulp content, found here: https://docs.asp.net/en/latest/client-side/using-gulp.html ? If so, can you please open a new issue? I'm going to close this one as the article it was referencing has since been replaced. Thanks!
