### ISSUE TITLE
views/partial.md "Partial Views"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2118]
- [x] Update to RTM
- [x] UE review
- [x] DISQUS 
- [ ] Show how to [Pass Additional ViewData to a Strongly-Typed Partial View](http://stackoverflow.com/questions/1169170) fixed in #2984

**Comment by MaherJendoubi** [comment]
Hi @Rick-Anderson,

The partial.md content and the associated code sample are already updated to RTM. UE is reviewed. It remains to answer comments (disqus) and how to pass additional ViewData to a strongly-typed partial view. I still working on them.

Regards

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  any chance you could add how to [Pass Additional ViewData to a Strongly-Typed Partial View](http://stackoverflow.com/questions/1169170)

**Comment by MaherJendoubi** [comment]
@Rick-Anderson https://github.com/aspnet/Docs/pull/2984

**Comment by MaherJendoubi** [comment]
@Rick-Anderson I updated the sample using VS2017 RTM. I wrote : 

@using Microsoft.AspNetCore.Mvc.ViewFeatures
@using PartialViewsSample.ViewModels
@model Article

<h2>@Model.Title</h2>
@Html.Partial("AuthorPartial", Model.AuthorName)
@Model.PublicationDate

@foreach (var section in Model.Sections)
{
    @Html.Partial("ArticleSection", section, new ViewDataDictionary (ViewData){ { "Article", Model } })
}

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  outstanding. Do I need to update the MD file to mention the code shows how to pass additional ViewData?

**Comment by MaherJendoubi** [comment]
@Rick-Anderson Yes please, it is very important. Thank you.

**Comment by Rick-Anderson** [comment]
@MaherJendoubi  I see you're passing in `new ViewDataDictionary (ViewData){
                                                { "Article", Model } })`

but you don't use that in the ArticleSection partial. Can we update the ArticleSection partial to use something from that model?

**Comment by guardrex** [comment]
@Rick-Anderson This was fixed by https://github.com/aspnet/Docs/pull/3024.
