### ISSUE TITLE
tutorials/publish-to-azure-webapp-using-vs "Deploy an ASP.NET Core web app to Azure using Visual Studio"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2119]
- [x] #4391 Modify https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs so the "Setup" and Next Steps sections are better worded. 
- [x] Azure portal has changed, update.
- [x] Add logging and log streaming #2146

**Comment by rachelappel** [comment]
Logging has its own article including streaming, and has been updated but I see where some enhancements can be made around streaming. I'll close this and open an issue just for the log streaming part. 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x
