### ISSUE TITLE
Docfx-/aspnet/core/security/authentication/identity,Introduction to Identity

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2130]
url : https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/identity
The link " Entity Framework Core" is redirecting to https://docs.efproject.net
screenshot
![capture124](https://cloud.githubusercontent.com/assets/22809209/20146562/6b24df78-a6ca-11e6-9cfd-ff3b1cb0a392.PNG)

**Comment by spboyer** [comment]
The link eventually routes to: https://docs.microsoft.com/en-us/ef/ which is correct.
