### ISSUE TITLE
Docfx- aspnet/core/security/authentication/sociallogins,Enabling authentication using Facebook, Google and other external providers

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2131]
https://review.docs.microsoft.com/en-us/aspnet/core/security/authentication/sociallogins

Screenshot
![capture125](https://cloud.githubusercontent.com/assets/22809209/20147754/68ed3282-a6cf-11e6-829b-1bd7169a7beb.PNG)

the url  (https://localhost:44320/)is displayed as link .It is  supposed to be displayed just as url  not as link(as in production)

**Comment by Rick-Anderson** [comment]
Nice catch. Fixed by #2138
