### ISSUE TITLE
Docfx- https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro,Getting started with ASP.NET Core MVC and Entity Framework Core using Visual Studio

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2139]
Url : https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro
( This url is just a sample page. this is applicable to entire documents)

In responsive mode the section "In This article " is being displayed under the author pic .

 please see the screenshot. If this is intentional... please ignore this bug.

![capture126](https://cloud.githubusercontent.com/assets/22809209/20174419/b81c2d4c-a763-11e6-9789-c093be8663c9.PNG)

**Comment by Rick-Anderson** [comment]
@tdykstra  can you fix this? cc @rick-anderson

**Comment by tdykstra** [comment]
@Rick-Anderson As noted, this applies across the board to all of docs.ms.com, not just to ef mvc tutorial.
