### ISSUE TITLE
Docfx- https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction,

### ISSUE THREAD

**Issue by Prasanna-Rani** [aspnet/Docs#2143]
Url : https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction
 few more pages where same issue is being observed : https://docs.microsoft.com/en-us/aspnet/core/security/authorization/dependencyinjection

The space between the last sentence in the document and the comments section is too long. It gives an impression to the reader as some text/image/code block is missing

![capture127](https://cloud.githubusercontent.com/assets/22809209/20187823/e5b5b056-a79b-11e6-86d5-00b6768a0951.PNG)

**Comment by spboyer** [comment]
@Prasanna-Rani  @Rick-Anderson - this is because the TOC determines the length of the page. If you close the TOC on the left the space is reduced.
