### ISSUE TITLE
Show how to use Azure Web App Log Streaming with ASP.NET Core.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#2146]
_From @olegburov on November 11, 2016 1:33_

Hi Guys,

I'm straggling to make the Azure Web App Log Streaming works with ASP.NET Core application. I tried it based on both .NET Framework and .NET Core, with ASP.NET Core 1.0 and 1.1 Preview-1, using `System.Diagnostics.Trace` and `ILogger/ILoggerFactory`. It just doesn't work for me.

At the same time, it works perfectly with old-fashioned ASP.NET 4 using the example @shanselman showed in the Azure Fridays video: https://channel9.msdn.com/Shows/Azure-Friday/Azure-Web-App-Log-Streaming-with-Scott-Hanselman

Could you please show what needs to be done with a clean ASP.NET Core Web Application (.NET Framework / .NET Core) to make it work?

_Copied from original issue: aspnet/IISIntegration#300_

**Comment by Rick-Anderson** [comment]
@tdykstra can you triage and add to the master logging issue?

**Comment by Tratcher** [comment]
Or to the azure deployment doc?

**Comment by tdykstra** [comment]
How do you immediately catch all the new issues and PRs as they come in without getting buried in an avalanche of GitHub emails?

**Comment by Rick-Anderson** [comment]
fixed by https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#azure-log-streaming  cc / @rachelappel
