### ISSUE TITLE
Specify alt text in all images

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2147]
- [x] Add requirement to style guide that all images need alt text `![alt-text](configuration/_static/imagename.png)`
- [ ] Open https://msdnhelp  asking help desk to add alt text

**Comment by GuardRex** [comment]
@Rick-Anderson I realize this wasn't quite "up for grabs" given your OP, but it looked like fun, so I thought I would float this PR to you. If you prefer the help desk to do it, no worries.

I noticed an image that needs a PS touch-up as I was doing this, and I'll open a new PR to update that image shortly.

**Comment by Rick-Anderson** [comment]
@tdykstra  are all the images fixed?

**Comment by GuardRex** [comment]
Looks like a couple slipped by me (but I'm not sure how ... SneakyLinks:tm:) ...

aspnetcore/security/authentication/identity.md 
aspnetcore/tutorials/first-mvc-app/new-field.md 

I'll get a PR in to fix these in a few minutes.
