### ISSUE TITLE
EF Core 1.0 with ASP.NET Core 1.0 MVC WebApi on IIS Server 7.0 Error 404

### ISSUE THREAD

**Issue by charreal** [aspnet/Docs#2163]
Hello,
I have a small application that uses EF Core 1.0 with ASP.NET Core 1.0 MVC WebApi, is working perfectly in kestrel self-hosting scenarios (IIS Express) .When i publish on IIS 7.0, i get 404 error when i call method use EF Core, but when i call method that does not use EF Core it work perfectly. What is the configuration for using EF Core 1.0 with ASP.NET Core 1.0 MVC WebApi on IIS Server. Thanks for your help. You would find at this url an application answering the same criterion that will give a 404 error after being pulse on IIS 7.0
https://github.com/FabianGosebrink/ASPNET-Core-Entity-Framework-Core

**Comment by Rick-Anderson** [comment]
Can you try posting this to SO? This is not a support forum.

**Comment by Rick-Anderson** [comment]
take a look at https://docs.microsoft.com/en-us/aspnet/core/publishing/iis

**Comment by charreal** [comment]
Excuse me, but I do not know where ask my question. Before asking my question I look at the doc aspnet-core; Publishing / IIS, fundamentals / server and EF Core. In addition all the examples that I found in microsoft or the web in general have the same problem when I deploy them on IIS.
The problem is on EF Core AspNet Core webapi on IIS, if don't have EF Core all is ok.
Another time Excuse me.
