### ISSUE TITLE
Account Confirmation and Password Recovery missing step

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2167]
Sebastien Ros `:`

>While doing my 1.1.0 release verification, I found that the current tutorial is missing an important option:

>https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm#require-email-confirmation

>If you follow the tutorial, you can still login even if the confirmation has not been processed. It’s missing this:

>`options.SignIn.RequireConfirmedEmail = true;`

**Comment by zetway** [comment]
I have the same issue
