### ISSUE TITLE
API docs: incorrect description

### ISSUE THREAD

**Issue by 50774283** [aspnet/Docs#2197]
The url below have a incorrect description in section Microsoft.AspNetCore.StaticFiles.
https://docs.microsoft.com/zh-cn/aspnet/core/api/
Thank you.

**Comment by Rick-Anderson** [comment]
Can you be more specific. What is wrong?

**Comment by 50774283** [comment]
Sorry,Rick-Anderson.the English is not my first language and i'm hard work to learn English.
the text "Support for session state" incorrect marked on namespace Microsoft.AspNetCore.StaticFiles.

**Comment by Rick-Anderson** [comment]
I don't see that. Can you send the URL to the page and screen shot. Here is what I see
![capture](https://cloud.githubusercontent.com/assets/3605364/20443821/a001e61a-ad72-11e6-93eb-b7ee7b08f78b.PNG)

**Comment by 50774283** [comment]
![description-wrong](https://cloud.githubusercontent.com/assets/16589080/20453533/82e6e61a-ae63-11e6-9ec1-6d2919ef4133.PNG)
![description-wrong-url](https://cloud.githubusercontent.com/assets/16589080/20453540/d7cdc964-ae63-11e6-9264-e69ffda1a492.PNG)

**Comment by Rick-Anderson** [comment]
Excellent, Thanks!

**Comment by Rick-Anderson** [comment]
@bradygaster  see https://docs.microsoft.com/en-us/aspnet/core/api/
Session is above. Also, why so many without descriptions?
![capture](https://cloud.githubusercontent.com/assets/3605364/20459708/43a3d3a8-ae6f-11e6-8eca-4e54f9e7b35c.PNG)

**Comment by Rick-Anderson** [comment]
@bradygaster  @danroth27  please review. 
I've had to close two PR's over this. See https://github.com/aspnet/ApiDocs/pull/14/files and https://github.com/aspnet/ApiDocs/pull/15/files

**Comment by danroth27** [comment]
Yeah, we should fix this. Shouldn't we just take one of those two PRs?

**Comment by bradygaster** [comment]
@danroth27 seems like the right thing to do
