### ISSUE TITLE
Migrate JS Web articles

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#22]
- Grunt and Gulp Task Runners
- Bower Package Manager
- Bootstrap Responsive Web Framework
- LESS, SASS, Font Awesome,
- TypeScript
- Knockout.js
- Backbone.js
- Angular.js
- React.js

**Comment by ardalis** [comment]
Moved all but the grunt/gulp article to separate issues; this issue now only applies to the Grunt/Gulp article
