### ISSUE TITLE
Review & update for Directory Structure

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2205]
@Rick-Anderson @spboyer @Tratcher @pranavkm @shirhatti @moozzyk @danroth27

I'd like to review and update [Directory Structure](https://docs.microsoft.com/en-us/aspnet/core/hosting/directory-structure) if that's ok with you.

- [x] Spelling, grammar, structure, and content review
- [x] Review directory structures shown and update as needed

I understand from https://github.com/aspnet/Docs/pull/2179#issuecomment-261017193 that we leave references to `publishOptions` and `project.json` in place until sometime next year when MSBuild/`csproj` becomes first-class.

**Comment by Rick-Anderson** [comment]
>I understand from https://github.com/aspnet/Docs/pull/2179#issuecomment-261017193 that we leave references to `publishOptions` and `project.json` in place until sometime next year when MSBuild/`csproj` becomes first-class.

correct 

Looks good, proceed.
