### ISSUE TITLE
API not picking up inherited members summary

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2207]
For example, see Order in https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.responsecacheattribute#Microsoft_AspNetCore_Mvc_ResponseCacheAttribute_Order

The order property is shown. Order defined in the parent class.

**Comment by Rick-Anderson** [comment]
@danroth27  please comment

**Comment by danroth27** [comment]
@bradygaster Is this a problem with the triple slash comments or with the API ref infrastructure?

**Comment by Rick-Anderson** [comment]
@danroth27  it has to be with the API Ref infrastructure. There are no /// comments typically on inherited members.
