### ISSUE TITLE
Can't find config variable

### ISSUE THREAD

**Issue by gabsferreira** [aspnet/Docs#221]
Sorry if I shouldn't open this here, but I'm having a problem following the docs. In the section "Your First ASP.NET 5 Application Using Visual Studio", in this code snippet:

```C#
public IActionResult About()
{
        string appName = _config.Get("ApplicationName");
        ViewBag.Message = "Your application name: " + appName;

        var serverInfo = new ServerInfo();
        serverInfo.Name = Environment.MachineName;
        serverInfo.Software = Environment.OSVersion.ToString();
        return View(serverInfo);
}
```

 this "_config" variable is not found, should it be inherited from the Controller class?

I'm using the latest version of VS 2015 14.0.22823.1.

**Comment by bigodera** [comment]
Maybe the declaration of the variable _config is lacking? Maybe something like:
var _config = new Configuration();

If it's just that, I could do it.

**Comment by ardalis** [comment]
This is fixed in a pending Pull Request (https://github.com/aspnet/Docs/pull/217). Sorry for the confusion. Part of the issue was that that article didn't use an associated sample, but this is corrected in the PR as well.

**Comment by bigodera** [comment]
@ardalis oh, ok then. Thank you.
