### ISSUE TITLE
Doc needed for Controller with app settings

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Docs#2211]
It's not easy adding a controller to a core app which consumes config. I know that we have an existing config page, but that is too broad for typical VS users. We should have a targetted article of how to create a contoller that consumes config.

cc @Andrew-MSFT

**Comment by ardalis** [comment]
You want something in mvc/controllers that indicates how to access config (probably IOptions<T>) values? I agree that would probably be helpful. @danroth27

**Comment by sayedihashimi** [comment]
Yes that's what  looking for.

**Comment by Rick-Anderson** [comment]
I'm updating config and pretty good coverage of controller consuming config see https://github.com/aspnet/Docs/pull/2120/

**Comment by ardalis** [comment]
Right but that's not necessarily as discoverable if you're doing MVC and drill down into the docs via MVC.

**Comment by sayedihashimi** [comment]
Consuming a config value in a controller is very common. We also changed how that's accomplished, and it's more difficult than it previously was. 
Most users require guidance. Having a specific article for this would be ideal.

**Comment by Rick-Anderson** [comment]
@sayedihashimi  see https://review.docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?branch=ra%2Fconfig and comment on my PR  #2120
