### ISSUE TITLE
"command line" over "command-line"

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2248]
This one falls under the heading of "Black Friday Silliness!" :smile:

I'm working on Pub IIS and fixing little things like "command line" (with a space) along the way. I became curious and did a quick search ... "command line" with a space is correctly used 16 times. However, "command-line" (with a dash) is used 9 times.

@Rick-Anderson When I'm done with Pub IIS, would you like me to submit a PR on getting the "command-line" (dashed) ones changed over?

command-line :-1: |
--- |
aspnetcore/data/entity-framework-6.md | 
aspnetcore/hosting/apppool.md | 
aspnetcore/publishing/linuxproduction.md | 
aspnetcore/fundamentals/servers/kestrel.md |
aspnetcore/client-side/bundling-and-minification.md |
aspnetcore/data/ef-mvc/intro.md |
aspnetcore/client-side/yeoman.md |
aspnetcore/fundamentals/servers/weblistener.md |
aspnetcore/fundamentals/configuration.md |

command line :+1: |
--- |
aspnetcore/fundamentals/servers/kestrel/sample/Program.cs
aspnetcore/fundamentals/servers/weblistener/sample/Program.cs
.gitattributes
aspnetcore/fundamentals/servers/aspnet-core-module/sample/Program.cs 
aspnetcore/client-side/yeoman.md
aspnetcore/data/ef-mvc/migrations.md 
aspnetcore/publishing/vsts-continuous-deployment.md 
CONTRIBUTING.md 
aspnetcore/fundamentals/hosting.md 
aspnetcore/fundamentals/configuration.md 
aspnetcore/fundamentals/servers/weblistener.md 
aspnetcore/publishing/web-publishing-vs.md 
aspnetcore/publishing/apache-proxy.md 
aspnetcore/tutorials/publish-to-azure-webapp-using-vs.md 
aspnetcore/mobile/native-mobile-backend.md 
aspnetcore/fundamentals/configuration/sample/src/ConfigConsole/Program.cs

**Comment by tdykstra** [comment]
The usage should be two words as a noun, hyphenate as an adjective. Examples from the style guide:

> command-line parameter 
> command-line tool
> Developers enter commands at a command prompt, not on a command line.

The style guide also advises use of "command prompt" where we often use "command line".

> Describe entering commands at a command prompt, not on a command line.
> Example 
> At the command prompt, type certutil -setreg ca.

**Comment by GuardRex** [comment]
@tdykstra Thanks. I may have missed or lost "style guide" along the way. Is that public? Do you have a link?

**Comment by GuardRex** [comment]
Let me propose then that when I'm done with Pub IIS PR that I take a closer look at use in the docs that I list above. I can review and report if all is well or not.

**Comment by tdykstra** [comment]
Your proposal to review and fix sounds great.  Unfortunately the style guide that has all the detailed terminology and grammatical guidance is not public yet, though I've been told they're working on making it public or creating a public version.

**Comment by GuardRex** [comment]
:smile: I thought so. :smile: Well .... my "boss" @Rick-Anderson can hardly hold that one against me. :smile:

Yeah ... I'm greatly looking forward to seeing what the grammar police think at MS.

WRT to this issue: Yeah, let me at least take a peek along the lines of what you gave me. If I find anything, I can float the changes (if any) in the issue. If that looks PR-worthy, then I'll shoot one in. I'm about 90% there on Pub IIS, so I'll get back soon.

**Comment by GuardRex** [comment]
aspnetcore/hosting/apppool.md ...

>You can also do this via the command-line by using ICACLS tool.

:point_up: **noun**

aspnetcore/client-side/bundling-and-minification.md ...

> To run bundling and minification tasks from the command-line using gulp ...

:point_up: **noun** (and prob should be "... from a command prompt ...")

aspnetcore/client-side/yeoman.md ...

> The Yeoman command line tool yo works ...

:point_up: **adjective**

@tdykstra I just checked the first few, and yes, there are probs here. Would you like to see a PR?

**Comment by tdykstra** [comment]
@GuardRex Yes that would be great, thanks!
