### ISSUE TITLE
Add a doc page that lists all core tag helpers

### ISSUE THREAD

**Issue by simonech** [aspnet/Docs#2256]
ASP.NET Core MVC comes with a dozen of tag helpers.
Form related ones are already explained in the tag helpers page, but all the other ones, cache, script, environment and so on are not.

Would it be of interest? I can write that doc.

**Comment by Rick-Anderson** [comment]
See Tag helper built in examples proposal  #2238 
We have one in PR, feel free to review

**Comment by Rick-Anderson** [comment]
Please review #2238

**Comment by skyflyer** [comment]
I second the need for better tag helper documentation. For developers coming from MVC 5 (and thus transitioning from `HtmlHelper`s), it would be really nice if tag helpers were [documented properly](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro).

The form ones are documented in a way that is usable, but the others are not. For instance, anchor tag helper (`<a>`) is not (well) documented. The `asp-route-*` attribute is documented only in [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/crud.md#route-data) (and there is another hint in [sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md#add-paging-links-to-the-student-index-view)

**Comment by Rick-Anderson** [comment]
PR #2785 addresses this - but it needs some editing work.

**Comment by guardrex** [comment]
@scottaddie #2785 is merged. Is this still needed?

**Comment by scottaddie** [comment]
@guardrex Yes. We need a complete list of built-in Tag Helpers. I frequently hear devs asking for this at events I attend. They get tired of hearing "look at the code on GitHub".

@pkellner Are you already working on documenting the remaining built-in Tag Helpers?

**Comment by badersur** [comment]
I wish if there's a table showing all tag helpers with their equivalent HTML helpers (not sure about the name, I mean the one used in MVC 5!) and the normal HTML tags...

I would like to convert all HTML Helpers created by the `aspnet-codegenerator` to the tag heplers but I don't know what to look for (espically when it comes to the `<select>` tag). Last year I was working on Ubuntu with no Visual Studio and didn't know how to use the scaffolder, so I had to look at the source code of the scaffolder to mimic its behaviour :/ I learned a bit -and forgot it after few months- and it was tedious and enjoyable! And I don't understand why the scaffolder is creating the older HTML helpers these days. Also, it's difficult to look at MVC 5 samples and try to convert the old helpers to the newer tags!

**Comment by scottaddie** [comment]
@prafullbhosale or @mlorbetske See the comment from @badersur above. Do you plan to migrate from HTML Helpers to Tag Helpers, where possible, with issue https://github.com/aspnet/Scaffolding/issues/399?

**Comment by guardrex** [comment]
The following THs are listed/covered at https://docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/built-in/:
* AnchorTagHelper
* CacheTagHelper
* DistributedCacheTagHelper
* EnvironmentTagHelper
* FormTagHelper
* ImageTagHelper
* InputTagHelper
* LabelTagHelper
* SelectTagHelper
* TextAreaTagHelper
* ValidationMessageTagHelper
* ValidationSummaryTagHelper

Unlisted:
* FormActionTagHelper
* LinkTagHelper
* OptionTagHelper
* PartialTagHelper
* RenderAtEndOfFormTagHelper
* ScriptTagHelper

**Comment by Rick-Anderson** [comment]
@guardrex 	what's the difference between `FormTagHelper` and `FormActionTagHelper`
`FormActionTagHelper` is used [here](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.2&tabs=visual-studio#multiple-handlers-per-page)

**Comment by Rick-Anderson** [comment]
Moved to #10593 to make it more discoverable.
