### ISSUE TITLE
Transfering Secrets to Azure

### ISSUE THREAD

**Issue by vkichline** [aspnet/Docs#227]
Pranav's article http://docs.asp.net/en/latest/security/sociallogins.html described how to use Secret Store to store my Facebook login secrets, which was a great example.  Now I'm encouraged to try it out, but before doing so I **have to know** how to keep my app running once I publish it to Azure.
The article links to https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration, which doesn't explain this, either.
Being uncertain about this blocks me from trying out this cool new feature.  Why write a website I can't publish?
Please add a topic about this, and be sure to link Pranav's article to it, or add the information to https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration.

**Comment by timmydo** [comment]
You could call config.AddEnvironmentVariables() and store the secrets in the azure web app settings

**Comment by timmydo** [comment]
@rustd

**Comment by Rick-Anderson** [comment]
@danroth27 I could add this to my secrets article but then we'd be violating the separation of ASP.NET and Azure.

**Comment by danroth27** [comment]
I'd love to see some content on how to ASP.NET 5 with the [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/), although currently I think that would require writing a custom config provider.

**Comment by GuardRex** [comment]
@danroth27 Love that, too, but unfortunately, not Core-friendly yet: https://www.nuget.org/packages/Microsoft.Azure.KeyVault/1.0.0 ... soometimes "core" just doesn't mean "core" ... https://github.com/Azure/azure-sdk-for-net/tree/master/src/KeyVault/Microsoft.Azure.KeyVault.Core

**Comment by danroth27** [comment]
https://docs.asp.net/en/latest/security/app-secrets.html covers using both the user secrets tool and env vars for dealing with secrets.
