### ISSUE TITLE
Publishing and Deployment & Guidance for Hosting Providers clean up

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2277]
- Make content in Guidance for Hosting Providers available to those who are not hosting providers - ex ANCM ref should be in a more generic place, it's relevant to anyone who wants to host in IIS
 - "Guidance for Hosting Providers" should be renamed as it applies to more than hosting providers.
- Currently 3 docs on publishing to IIS - when would I use each approach? Who is that targeted to?
- Figure out audiences and what that want to do.
- Provide guidance for linux base hosting providers
- Clear location where OPS people should go on hosting ASP.NET Core apps on both windows/linux - content is spread out and should be consolidate. Not clear which topic to read.

details in pub-hosting-reorg.mp4

**Comment by tdykstra** [comment]
Fixed by #3176
