### ISSUE TITLE
How to Customize Publishing

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#228]
ASP.NET 5 -> Publishing and Deployment -> How to Customize Publishing

**Comment by andresmoschini** [comment]
Hi @danroth27, is there any update on it? 

Following http://docs.asp.net/en/latest/fundamentals/environments.html I understand that it is possible and simple to determine environment at runtime.  

But, I would like to deploy only the right configuration for each environment, is it possible? 

cc: @abriscioli

**Comment by danroth27** [comment]
@sayedihashimi Do we have any notion of environment specific deployment at this point?

**Comment by jda808** [comment]
just checking in on this. i was linked via pdf render of read the docs aspnet.pdf

**Comment by jda808** [comment]
And I finally stumbled upon via website now. I've went full circle 🎱

**Comment by danroth27** [comment]
Published as of https://docs.asp.net/en/latest/publishing/web-publishing-vs.html.

**Comment by ygoe** [comment]
Strange, the docs page says you're working on it, and this page says you won't do it. Which one is outdated?

**Comment by danroth27** [comment]
Opened #1643 to track removing the article stub.

**Comment by sayedihashimi** [comment]
Here is the page that include the content https://docs.asp.net/en/latest/publishing/web-publishing-vs.html
