### ISSUE TITLE
update to RTM Client-side/Bundling and Minification

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2291]
#2259

**Comment by Rick-Anderson** [comment]
From the bundling and min doc
![image](https://cloud.githubusercontent.com/assets/3605364/20821420/67ccf266-b7e6-11e6-93d4-0d62b7a90745.png)

Something has changed, as the default template project now has no npm node and no package.json.  
@spboyer Do you know where there are current directions for this?

**Comment by spboyer** [comment]
@Rick-Anderson - yes it is a new topic: https://github.com/aspnet/Docs/issues/1786

This is the next item I am working on.

**Comment by tdykstra** [comment]
@spboyer #1786 is for update of client-side/bundling-and-minification which is what this issue was created for, so looks like this is a dup - what's the new topic? Can we close this one and add #1786 to the RTM updates issue #2259 ?

**Comment by spboyer** [comment]
@tdykstra  the new topic is to document the **Bundling and Minification** functions that are in the new templates in lieu of gulp. Everything that needs to be done is in #1786
