### ISSUE TITLE
Update to RTM Security/Authentication/Two-factor authentication with SMS 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2293]
@Swiss-Devs  plans to do this.
master issue #2259
project.json to csproj/msbuild issue #2744

**Comment by Rick-Anderson** [comment]
@danroth27 @spboyer 
@joeaudette  has a [REST library for Twilio ](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Messaging.Sms/TwilioSmsSender.cs) 

Can I use Joe's code until Twilio supports core? 

In issue https://github.com/twilio/twilio-csharp/issues/163 twilio engineer @mplacona states:

>@mplacona commented on Mar 18, 2016
We're working on a brand new version of the library that will support the
latest version of the .Net Core 1.0. I know it's taking a long time, but
we'll have it on GA soon!

We could use Joe's version for now and switch to Twilio when they have something stable.

**Comment by Rick-Anderson** [comment]
Looks like aspsms.com plans to do this in a few weeks.

**Comment by mplacona** [comment]
Hey @Rick-Anderson thanks for tagging me on this, and sorry it took me so long to pitch in.

You are correct, and we are working on a new version of the library that will support .NEt Standard, which should make sure there's no more fragmentation. For the time being though, I think it's worth mentioning here that the library is no more than a wrapper for our API, so while the library is not stable at this time, the API is.

All the library does it dd some syntactic sugar to it and manage the URLs. But that is it.

I wrote some code a couple of weeks ago to list calls from my Twilio account using .NET core without the library. And while the code is slightly bigger than it would have been with the library, it really is not much bigger.

You can see it [here](https://github.com/mplacona/TwilioCallLogCore/blob/master/TwilioCallLogsConsole/Program.cs)

Other people have also done similar things, and are using this on production. See [here](https://www.example-code.com/dotnet-core/twilio_sms.asp).

Hope this helps you out, and I'll be happy to give you any support you may need with this.

**Comment by ArashMotamedi** [comment]
Hello @Rick-Anderson, @mplacona!

Thanks for the pointers and looking forward to the updated library from Twilio. In the meantime, as a stop-gap measure for folks looking for a drop-in solution for their projects, I just reconstructed the Twilio.Api project as a .Net Core Library project, replaced RestSharp with RestSharp.NetCore, added a couple lines of code to synchronously call RestSharp.NetCore's `ExecuteAsync` method... and voila! It's working.

Feel free to take the package for a spin: https://www.nuget.org/packages/Twilio.NetCore 
And take a look at the repo: https://github.com/ArashMotamedi/twilio.netcore

Cheers,
Arash

**Comment by Rick-Anderson** [comment]
@Swiss-Devs  let me know if I can help. We'd like to get this updated for [msbuild ](http://www.natemcmaster.com/blog/2017/01/19/project-json-to-csproj/) by the end March 1st, 2017. See #2744
