### ISSUE TITLE
Consistent stdout log naming needed

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2303]
There are inconsistent `stdout` log names in the docs. I've spotted a few here and there, and [I see it again in the Response Caching sample](https://github.com/aspnet/ResponseCaching/blob/dev/samples/ResponseCachingSample/web.config#L7) ...
```
stdoutLogFile=".\logs\stdout"
```
It should be ...
```
stdoutLogFile=".\logs\aspnetcore-stdout"
```
I propose to submit a PR that will make these consistent and correct across the docs. Sound good?

**Comment by Rick-Anderson** [comment]
@spboyer @tdykstra  please review proposal

**Comment by spboyer** [comment]
Why do you think it "should be" `aspnetcore-stdout`?  When writing stdout in node, it is not `nodejs-stdout`.

**Comment by tdykstra** [comment]
I'd prefer to use what the VS project templates create, which is what you see in the Response Caching sample, i.e., I would go in the opposite direction from what you're proposing.

**Comment by GuardRex** [comment]
It's not the default tho AFAIK for ANCM.

**Comment by GuardRex** [comment]
https://github.com/aspnet/AspNetCoreModule/blob/93ace1b84bd79382233cb39b858611d2db05552e/src/AspNetCore/aspnetcore_schema.xml#L24

**Comment by tdykstra** [comment]
Maybe it's more a product than a docs issue and we look at changing the VS project templates to create ".\logs\aspnetcore-stdout"?  Docs would then follow that lead.

**Comment by Rick-Anderson** [comment]
> changing the VS project templates to create ".\logs\aspnetcore-stdout"
If others concur I'll open a template issue.

**Comment by Rick-Anderson** [comment]
@GuardRex  we've decided to not change the names at this time.
