### ISSUE TITLE
1.1 feature: Redis and Azure Storage Data Protection Key Repositories

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2309]
From the list in #2260 
[1.1 blog](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/)

**Comment by Rick-Anderson** [comment]
@danroth27  @pakrym should I add **Redis and Azure Storage Data Protection Key Repositories** to [security/data-protection/configuration/overview - "Configuring Data Protection"](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview)?

I'll then add links to Azure articles and [Working with a Distributed Cache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed)

Is @pakrym the right dev contact for this? cc @tdykstra
