### ISSUE TITLE
Advanced Tag Helpers

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#231]
MVC -> Views -> Tag Helpers -> Advanced Tag Helpers

Doing more advanced stuff like ModelExpressions, multiple tag helpers per element, coordination between Tag Helpers, packaging them up in NuGet packages, etc.

**Comment by xiaolu6t** [comment]
Some suggestion:
I want something like this:
```
<if condition="true">
true
<else/>
false
</if>
```
```
<ul>
	<foreach name="user" enumerator="ViewBag.users">
		<li>user.id</li>
		<li>user.name</li>
		<li>user.age</li>
	</foreach>
</ul>
```
Add a new  PreParser method to TagHelper,
And add context.RazorContext to TagHelper.
System.Web.Razor.Parser.RazorParser parser = new System.Web.Razor.Parser.RazorParser(
                new System.Web.Razor.Parser.CSharpCodeParser()
                , new System.Web.Razor.Parser.HtmlMarkupParser());
            parser.DesignTimeMode = false;
            var results = parser.Parse(new StringReader(template));
before parser.Parse() to find all the custom taghelper tags.
then run the PreParser method before compile.
[HtmlTargetElement("foreach")]
public class TagNameTagHelper : TagHelper
{
	[HtmlAttributeName("name")]
	public string name="";
	[HtmlAttributeName("enumerator")]
	public object enumerator="";
	//compile Code,
	public override void PreParser(TagHelperContext context, TagHelperOutput output)
	{
		//context of razorContent is like this:
		//<li>@user.id</li>
		//<li>@user.name</li>
		//<li>@user.age</li>
               //context.items["key"] return Attribute string not object;
		string razorContent=$@"@foreach(var {context.items["name"]} in {context.items["enumerator"]})
		{
			{context.RazorContent};
		};
		output.SetRazorContent(razorContent);
	}
}
before PreParser
<ul>
	<foreach name="user" enumerator="ViewBag.users">
		<li>@user.id</li>
		<li>@user.name</li>
		<li>@user.age</li>
	</foreach>
</ul>
after PreParser
<ul>
	@foreach(var user in ViewBag.users)
	{
		<li>@user.id</li>
		<li>@user.name</li>
		<li>@user.age</li>
	}
</ul>
add so on...All the possible you can image.

**Comment by Kahbazi** [comment]
Is there any way to use tag helper inside of another tag helper (in the Process method)?

I like to create a FormTagHelper and user InputTagHelper in its Process method

**Comment by NTaylorMullen** [comment]
@Kahbazi If you're looking to programmatically use one in the process method you can always do:

```C#
var inputTagHelper = new InputTagHelper(...)
{
  // Set properties you want
};
// Create a new TagHelper output, context etc. if you want
inputTagHelper.Process(output, context)
```

**Comment by xiaolu6t** [comment]
context object can't contain razor template mark.

**Comment by NTaylorMullen** [comment]
@xiaolu6t It sounds like you want partial view-like logic. The http://live.asp.net site has a partial `TagHelper` to execute another view inside the Process method of a TagHelper. See the [Partial View TagHelper](https://github.com/aspnet/live.asp.net/blob/93edc93c0cb26f3f6933b071b9f78b3614dcc58d/src/live.asp.net/TagHelpers/PartialTagHelper.cs).

**Comment by Kahbazi** [comment]
@NTaylorMullen Can you please show me how to create new \TagHelper output and context?

**Comment by NTaylorMullen** [comment]
@Kahbazi can you be more specific? Is using their constructors not sufficient?

**Comment by Kahbazi** [comment]
@NTaylorMullen their constructors is clear for me, I don't know how to provide the inputs.
what I want to do is create  CreateForm Tag Helper which gets a model class as its attribute and create all the elements which is needed for Creating that class.

I want to write this in my View :
 
@model Person
<CreateForm asp-Entity="@Model"/>

and I want CreateForm tag helper to generate this : 

<Form>
<label> First Name </label>
<input type="text">
<label> Last Name </label>
<input type="text">
<input type="Submit"
</Form>

**Comment by NTaylorMullen** [comment]
You could do: `public object AspEntity { get; set; }` in your `CreateForm` TagHelper and then reflect over that object to generate the types. You could also utilize ModelExpression to work with a piece or the entire model and do: `public ModelExpression AspEntity { get; set; }` and look at the metadata

**Comment by Kahbazi** [comment]
I've already done that, I get my `AspEntity` and use `Reflection` to get to the properties and create a `ModelExplorer` object for each property, but my problem is when I create a new `InputTagHelper` in my  `Process` method  of `CreateFormTagHelper` and call its `Process` method, nothing is added to output.


    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
         foreach (PropertyInfo PI in Model.GetProperties())
         {
             var metadataProvider = new EmptyModelMetadataProvider();
             var containerExplorer = metadataProvider.GetModelExplorerForType(Model, Object);
             var propertyMetadata = metadataProvider.GetMetadataForProperty(Model, PI.Name);
             var modelExplorer = containerExplorer.GetExplorerForExpression(propertyMetadata, Object);

              var labelTagHelper = new LabelTagHelper(Generator)
              {
                    For = new ModelExpression(PI.Name, modelExplorer),
                    ViewContext = ViewContext
              };
              labelTagHelper.Process(context, output);   //nothing will be added after this method to output

              var inputTagHelper = new InputTagHelper(Generator)
              {
                    For = new ModelExpression(PI.Name, modelExplorer),
                    ViewContext = ViewContext
               };
               inputTagHelper.Process(context, output);  //nothing will be added after this method to output

        }

**Comment by NTaylorMullen** [comment]
So when the `InputTagHelper`s `Process` method is called it expects that the `output` passed in represents an input tag. It then modifies the output in-place to represent a new input tag. It doesn't add itself to the output.

You could however create a separate `TagHelperOutput` for the input tag and then append its output to your `CreateForm`s `TagHelperOutput`.

Ex:
```C#
var inputOutput = new TagHelperOutput(....);
var inputContext = new TagHelperContext(...);
var inputTagHelper = new InputTagHelper(Generator)
{
    For = ...,
    ViewContext = ...
};
inputTagHelper.Process(inputOutput, inputContext);

output.Content.AppendHtml(inputOutput);
```

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  maybe you could write some code with advanced features and we could write a doc around it.

**Comment by Rick-Anderson** [comment]
@NTaylorMullen if you write some code with advanced features we could write a doc around it.

Otherwise I'll close this issue.

**Comment by NTaylorMullen** [comment]
Sadly I don't have the bandwidth 😢
