### ISSUE TITLE
testing/integration-testing "Integration testing"

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2321]
- [ ] The article gives directions for making changes that presume you're working with a "starter" project but never gives you the starter project. If we retain the process of creating a middleware component we should provide the starter project.
- [ ] As part of the middleware component creation the article mentions creation of "extension methods" but doesn't show them and only shows a call to one extension method.  If we retain the process of creating a middleware component, we should explain better the part about extension methods.
- [ ] respond to feedback

**Comment by Rick-Anderson** [comment]
@tdykstra 	move this issue to integrated issue if you want it to remain open.
