### ISSUE TITLE
create TOC for Configuring Facebook, google, etc authentication

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2332]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/sociallogins

put them in https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social
folder

**Comment by Rick-Anderson** [comment]
@tdykstra  can you get this done this week?

**Comment by tdykstra** [comment]
@Rick-Anderson Yes
