### ISSUE TITLE
security/authentication/social/google-logins.md "Configuring Google authentication"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2345]
When it says: “Add the Google middleware in the `Configure` method in Startup.cs:”

It should be specified that the code needs to go AFTER the call to `UseIDentity` or there will be an exception.

@tdykstra  can you fix this in our December milestone and notify @sebastienros when it's fixed?

**Comment by tdykstra** [comment]
@sebastienros See #2354 -- this warning was also in the overview page but the note formatting code was incorrect so it didn't show up as a note.
