### ISSUE TITLE
Project: Develop and Enhance Content for ASP.NET Core on macOS / Linux

### ISSUE THREAD

**Issue by spboyer** [aspnet/Docs#2351]
This is a discussion issue for the [Develop and Enhance Content for ASP.NET Core on macOS / Linux project](https://github.com/aspnet/Docs/projects/4)

If there are topics or specific areas of interest related to this area, comment in this issue.

- #1842 Your First ASP.NET Core app on a Mac Using VS Code - Update/enhance
- #1799 Add Ubuntu versions of tutorials
- #1576 VSCode on Mac OSX /Linux version of Web-API and  "Getting started with ASP.NET Core MVC"
- #1378 Add minimal xplat  getting started with MVC tutorial

**Comment by jchannon** [comment]
Are 3rd party web fwks welcome?

**Comment by spboyer** [comment]
@jchannon - How is developing a fw different on macOS vs Linux vs Windows? Is there enough of a difference to warrant content for each platform?

**Comment by jchannon** [comment]
I meant as this was filed under ASP.Net docs for content, I assume meaning How-Tos was this restricted to ASP.Net MVC or things like Nancy on dotnetcore?

**Comment by spboyer** [comment]
@jchannon this issue is specific to macOS and Linux development. I would open an [new issue](/aspnet/docs/issues/new) related to that question.

@danroth27

**Comment by Rick-Anderson** [comment]
@spboyer  dup of #1576

**Comment by spboyer** [comment]
@Rick-Anderson not a duplication, this is a project discussion related issue for ALL macOS and Linux content.  #1576 should be added to the project.

**Comment by Rick-Anderson** [comment]
Closing as this is tracked in projects.

**Comment by Rick-Anderson** [comment]
[Introduction to ASP.NET Core MVC on Mac or Linux](https://docs.microsoft.com/en-us/aspnet/core/tutorials/) is completed
