### ISSUE TITLE
remove UseWebRoot in [Working With Static Files]

### ISSUE THREAD

**Issue by duynguyen0511** [aspnet/Docs#2355]
Please remove note or add clarification about UseWebRoot in [Working with Static Files](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/static-files.md) because there is no mentions of UseWebRoot in [Introduction to ASP.NET Core](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)

Does UseWebRoot work ? There is an open ticket for it #1367 

![usewebroot](https://cloud.githubusercontent.com/assets/436950/21025498/ebe80900-bd45-11e6-86e7-3c69cfa90f35.png)

**Comment by danroth27** [comment]
Yeah, we should remove the pointer to the Intro to ASP.NET Core doc from that note.

Yes, `UseWebRoot()` does work, although I don't think VS will be able to reflect this correctly in the solution explorer. I believe VS just always assumes that `wwwroot` is your web root, but everything should still work correctly at runtime. The icon will just be wrong.

**Comment by Rick-Anderson** [comment]
fixed in #2375
