### ISSUE TITLE
Add new middleware to list in Middleware doc

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2358]
@ardalis 

For the `Built-in middleware table` in the `Middleware` doc at: 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware#built-in-middleware
https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware.md#built-in-middleware

Does it need (alphabetically added) ...

Heading | Text
--- | ---
Response Caching | Provides support for caching responses.
Response Compression | Provides support for compressing responses.
URL Rewriting | Provides support for rewriting URLs and redirecting requests.

If you'd like me to knock this out, let me know.

[EDIT] ... and browsing blogs this morning, I stumbled into a [K. Scott Allen *Ode to Code* blog post](http://odetocode.com/blogs/scott/archive/2016/11/22/asp-net-core-and-the-enterprise-part-3-middleware.aspx), where he states ...

> ... when developers use middleware they often struggle finding the right middleware to use. Microsoft distributes ASP.NET Core middleware in granular NuGet packages, meaning you have to know the middleware exists, then find and install the package, and then find the extension method to install the middleware. As ASP.NET Core has moved from release candidate to the current 1.1 release, there has been churn in the package names themselves, which has led to frustration in finding the right package name.

I've felt that way myself. The OOB middleware packages aren't so easy to discover, except for the list you have here, and the dedicated docs for each are a bit scattered in the docs. A couple of idears:
* Slightly more 🍖 meat on the bone 🍖 than just a short sentence about each (even if at the very end of this doc in a separate section).
* Showing the full package name (even if at the very end of this doc in a separate section).
* Linking the middlewares in this list (or in a section at the end of this doc) to their respective dedicated documents.

**Comment by danroth27** [comment]
Yup, sounds good. @GuardRex if you'd like to take this on that would be great.

**Comment by GuardRex** [comment]
@danroth27 Sure thing. I'll get a PR in soon.
