### ISSUE TITLE
requesting Built-in Services table

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/Docs#236]
Fundamentals -> Dependency Injection -> Built-in Services.

A Table which includes all ASP.NET 5 Built-in Services (e.g. IHttpContextAccessor), together with their type (Scoped, Transient, or Singleton) and major function. This topic may especially useful while either creating custom services or writing application code.

**Comment by danroth27** [comment]
Agreed - having a table of all built in services would be great. Some of the built-in services are covered in https://docs.asp.net/en/latest/fundamentals/startup.html#services-available-in-startup, but it loosk like IHttpContextAccessor isn't covered anywhere.

**Comment by Rick-Anderson** [comment]
Moved to #9238
