### ISSUE TITLE
New Topic: Using IIS Modules with ASP.NET Core

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2367]
This question has reoccurred to me due to Response Compression, Response Caching, and URL Rewriting middlewares hitting the scene.

Some IIS modules can process requests/responses with the reverse-proxy setup and others don't work. For example, IIS Dynamic Compression (`DynamicCompressionModule`) works, while IIS Static Compression (`StaticCompressionModule`) doesn't work.

Should we provide a pair of lists in the Publish to IIS doc (or the ANCM Configuration Reference doc) that shows which IIS modules work and which ones don't work?

Reference List: https://www.iis.net/learn/get-started/introduction-to-iis/iis-modules-overview

**Comment by danroth27** [comment]
Sounds like good content to have. I'm not sure the Publish to IIS doc is really the right place though. I definitely wouldn't put it in the ANCM Config Reference. Maybe a separate topic? We really need to rework the TOC for hosting and publishing.

**Comment by Rick-Anderson** [comment]
Call it IIS modules that work with ASP.NET Core.

**Comment by danroth27** [comment]
Or maybe "Using IIS Modules with ASP.NET Core"?

**Comment by GuardRex** [comment]
Here's the full list for reference:

### Utility Modules
AnonymousAuthenticationModule
BasicAuthenticationModule
CertificateMappingAuthenticationModule
CgiModule
ConfigurationValidationModule
CustomErrorModule
CustomLoggingModule
DefaultDocumentModule
DigestAuthenticationModule
DirectoryListingModule
DynamicCompressionModule
FailedRequestsTracingModule
FileCacheModule
HttpCacheModule
HttpLoggingModule
HttpRedirectionModule
IISCertificateMappingAuthenticationModule
IpRestrictionModule
IsapiFilterModule
IsapiModule
ManagedEngine
ProtocolSupportModule
RequestFilteringModule
RequestMonitorModule
ServerSideIncludeModule
StaticCompressionModule
StaticFileModule
TokenCacheModule
TracingModule
UriCacheModule
UrlAuthorizationModule
WindowsAuthenticationModule

### Managed Modules
AnonymousIdentification
DefaultAuthentication
FormsAuthentication
OutputCache
Profile
RoleManager
Session
UrlAuthorization
UrlMappingsModule
WindowsAuthentication

**Comment by GuardRex** [comment]
@danroth27 @Rick-Anderson I'll work through collecting data for this. I'll take relevant notes as I go in case there is more to say than "Yes" for any given module.

**Comment by GuardRex** [comment]
@Tratcher @pan-wang @shirhatti

I filled in the table with some local testing results (marked `*`). I could use some feedback to help ...
1. Correct errors
2. Add information
3. Shape the direction of the doc

As it stands, my crude outline is ...
* Introductory paragraph
  * Some modules work, some don't
  * Notes (shown under the table ... and I need help understanding the last one on the ordering of modules)
  * Middleware offers some direct replacement options (referring to the 3rd table column)
* Add the common English names and the DLL of the modules e.g. **Request Monitor** `RequestMonitorModule` **iisreqs.dll**
* Link the modules to their respective IIS docs (module + **web.config** element)
* The table is an effective way to present this information, so I'll try a draft with tables similar to what you see above.
* Additional Resources

**Comment by Tratcher** [comment]
FormsAuthentication is replaced by the CookieAuthentication middleware

**Comment by Tratcher** [comment]
Some pieces of RewriteModule do not work with Core, (e.g. IsFile or IsDirectory), due to changes in the file structure layout.

**Comment by guardrex** [comment]
Hello @carathorys ... This issue is closed. Could you open a new issue for that on this repo?
