### ISSUE TITLE
Docs for UseForwardedHeaders, working with reverse proxies and load balancers

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#2384]
https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction
https://github.com/aspnet/Security/issues/1070
https://github.com/aspnet/Security/issues/929
https://github.com/aspnet/Security/issues/757
https://github.com/aspnet/Security/issues/853
https://github.com/aspnet/IISIntegration/issues/140
https://github.com/aspnet/Security/issues/1620
https://github.com/aspnet/Security/issues/1702
Enabled by default by UseIISIntegration, but with limited settings (ANCM reverse proxy on loopback)

**Comment by Tratcher** [comment]
https://github.com/aspnet/BasicMiddleware/issues/190

**Comment by Rick-Anderson** [comment]
@Tratcher Please clarify the ask and outline the solution.

**Comment by Tratcher** [comment]
Most sites are hosted behind a reverse proxy, especially our recommended configurations using IIS/ANCM or NGinx. When the request is being proxied some information may be lost like the original scheme (http/https), the client IP address, etc.. You may need these values to properly generate links, evaluate polices, geolocate clients, etc.. There is a convention for the proxies to forward these values as HTTP headers (x-forwarded-*). The UseForwardedHeaders middleware reads these headers and fills in the associated fields on HttpContext.

UseForwardedHeaders has pretty complicated settings due to trust concerns with these forwarded headers (e.g. spoofing). Explain how the middleware works overall and each of the settings.

UseForwardedHeaders is enabled by default by UseIISIntegration, but with a very restricted configuration specific to ANCM.

**Comment by spboyer** [comment]
@Tratcher if UseIISIntegration is not enabled and/or IIS is not used (i.e. nginx, apache, etc) it is important to not only have the reverse proxy setup properly for forwarding the requests and headers, but to also add the UseForwardedHeaders middleware.

Is that what you are asking here to document?

and is more that the following needed:

```
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

```

**Comment by Tratcher** [comment]
@spboyer yes that's part of it. There are several other settings related to identifying/trusting the proxies. You also need to make sure your reverse proxy is adding the headers.

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction captures the nginx specific scenario.

**Comment by spboyer** [comment]
@Tratcher so are you looking for a specific document targeted at just the setting for UseForwardedHeaders?

>UseForwardedHeaders has pretty complicated settings due to trust concerns with these forwarded headers (e.g. spoofing). Explain how the middleware works overall and each of the settings.

**Comment by Tratcher** [comment]
Not quite. We need to explain the end-to-end scenarios and how the various UseForwardedHeaders settings apply (e.g. IIS+ANCM, Nginx, multiple proxies, etc.).

**Comment by mitja-p** [comment]
We had some problems with forwarding and lost 2 days due to this. It would be nice to mention in the documentation that only headers for KnownProxies / KnownNetworks are taken into account and that the default is only IPAddress.IPv6Loopback / IPAddress.IPLoopback. So changing forwarding limit has basically no effect without modifying KnownProxies / KnownNetworks. And the right way to setup forwarding when there is Proxy -> IIS -> ASPNET situation is to increase forwarding limit, depending on the type of proxy set RequireHeaderSymmetry = false and add the proxy IP to KnownProxies / KnownNetworks.

**Comment by pksorensen** [comment]
I wanted to pitch in here as I failed to find documentation for what I am doing.

I write my nginx configuration in service fabric dynamic from the following code:
```
                sb.AppendLine($"{tabs}proxy_set_header Host                          $host;");
                sb.AppendLine($"{tabs}proxy_set_header X-Real-IP                   $remote_addr;");
                sb.AppendLine($"{tabs}proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;");
                sb.AppendLine($"{tabs}proxy_set_header X-Forwarded-Host    $host;");
                sb.AppendLine($"{tabs}proxy_set_header X-Forwarded-Server  $host;");
                sb.AppendLine($"{tabs}proxy_set_header X-Forwarded-Proto   $scheme;");
                sb.AppendLine($"{tabs}proxy_set_header X-Forwarded-Path     $request_uri;");
```
and have a few senaries that the UseForwardedHeaders dont cover or I am missing documentation on how to make it work.

```
 app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                 ForwardedHeaders = ForwardedHeaders.All
            });
```

basically I have to run the following also to make it work

```
        private const string XForwardedPathBase = "X-Forwarded-PathBase";
        private const string XForwardedProto = "X-Forwarded-Proto";
 
        app.Use((context, next) =>
            {
                if (context.Request.Headers.TryGetValue(XForwardedPathBase, out StringValues pathBase))
                {
                    context.Request.PathBase = new PathString(pathBase);
                    
                }

                if (context.Request.Headers.TryGetValue(XForwardedProto, out StringValues proto))
                {
                    context.Request.Protocol = proto;
                }

                return next();
            });
```

To update the protocol in those cases where nginx do the ssl offloading and the backend app just uses http. And to set the PathBase, for those cases when nginx has removed part of the path when passing the request forward.

If UseForwardedHeaders can do this already, how do i do it?

**Comment by Tratcher** [comment]
X-forwarded-proto support is built in, but it maps to scheme, not protocol (http/1.1).

With PathBase make sure you're creating your PathString with the unescaped value.

**Comment by pksorensen** [comment]
thanks for the added info. i will try a few thing then to find out why my identity server generates wrong urls. https://www.earthml.com/identity/.well-known/openid-configuration (the urls it generate should also be https )

**Comment by pksorensen** [comment]
`context.Request.Protocol = proto;` was a typo

Here is my working solution, so somehow the forward middleware do not work: 
![image](https://cloud.githubusercontent.com/assets/2718591/23865057/a951d322-0814-11e7-8aeb-8dbb2505843b.png)

Next step is properly to check some case sensitive stuff, i properly made a mistake there

**Comment by Tratcher** [comment]
Can you log your headers as received by the app? The middleware is pretty strict.

**Comment by pksorensen** [comment]
Ye, i am off for a few hours- then i will try to log out some requests to see what actually happens. Thanks for helping

**Comment by pksorensen** [comment]
Here are the headers.
Will start investigate the code to see where it can go wrong.
```
["X-Forwarded-Server"]=["www.earthml.com"],
["X-Forwarded-Proto"]=["https"]
["X-Forwarded-Path"]=["/identity/connect/authorize/consent?client_id=EarthML.Mapify&redirect_uri=https%3A%2F%2Flocalhost%3A44377%2F&response_type=id_token%20token&scope=openid%20profile&state=621bc11cd0674059994828b401561a8c&nonce=7f2766fd2c3f4393abebf1d3c0630e93"]
["X-Forwarded-PathBase"]=["/identity/"]
```

**Comment by Tratcher** [comment]
You have it set to ForwardedHeaders.All, but you don't have an x-Forwarded-For header, so it freaks out and won't process Proto either. Scope it down to just the header you need.

**Comment by pksorensen** [comment]
@Rick-Anderson Sure, not sure what exactly that means and what I should do :) The problem was resolved based on @Tratcher comment, about changing `ForwardedHeaders.All` to the headers actually used by my setup.

@Tratcher Is it ideal that it is this strict? Since the config lays within the application, meaning that if the guy responsible for the nginx setup changes the config, the the app breaks. Worth considering to use thoes headers present when set to all?

**Comment by Tratcher** [comment]
We have an open bug for relaxing some of the defaults to make it easier to use (https://github.com/aspnet/BasicMiddleware/issues/190).

However, we still need a writeup explaining the usage scenarios. See https://github.com/aspnet/Docs/issues/2384#issuecomment-270195458

**Comment by Rick-Anderson** [comment]
@Tratcher  any chance you could do a rough draft of this doc? Any format is fine.

**Comment by Tratcher** [comment]
Not sure when I can get to it. Would a conference call content-dump be helpful?

**Comment by Rick-Anderson** [comment]
@Tratcher  I'll check back in a few weeks and set up a call.

**Comment by Rick-Anderson** [comment]
End of "C:\Dropbox\wrk\Outline of all components that need s. . . - Thursday, April 27, 2017 10.32.36 AM.mp4" covers this.

**Comment by nrandell** [comment]
I've just had a few hours of head scratching around this as well. My scenario is a service fabric application running behind an application gateway in azure. 

I've found that in order to make it work so I can pick up the remote ip address correctly is the following.

```
var options = new ForwardedHeadersOptions
{
   ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
};
options.KnownNetworks.Clear();
options.KnownProxies.Clear();
app.UseForwardedHeaders(options);
```
First off the application gateway only provides x-forwded-for, x-forwarded-port and x-forwarded-proto (see https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq), so setting ForwardedHeaders.All didn't work.

Then as the application gateway is a separate host, the original remote ip and port values were 10.0.1.X as the service fabric machines were on the 10.0.1.X network. This caused the error message, only visible at debug level, or
`Unknown proxy: 10.0.1.4:53690`

So clearing the network and proxies, skipped the check for known IPs and it then started working.
Hopefully this is useful information and can be added to the docs.

**Comment by qmfrederik** [comment]
It looks that when you deploy an ASP.NET Core application as a Docker Container to Azure App Services for Linux, the `X-Forwarded-Proto` header is not present.

These headers are present:
```
Connection close
Accept text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding gzip, deflate, sdch, br
Accept-Language en-US,en;q=0.8
Cookie ARRAffinity=341b768fc49455e18091f5063d13391e034e3b8570558d994fba7687534feb33
Host [host].azurewebsites.net
Max-Forwards 9
User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Upgrade-Insecure-Requests 1
X-LiveUpgrade 1
X-WAWS-Unencoded-URL /home/debug
X-Original-URL /home/debug
X-ARR-LOG-ID f53feb81-d121-4f96-994b-3f37fbbe909d
DISGUISED-HOST [host].azurewebsites.net
X-SITE-DEPLOYMENT-ID [host]
WAS-DEFAULT-HOSTNAME [host].azurewebsites.net
X-Forwarded-For 109.128.4.143:55380, 10.0.128.18
X-ARR-SSL 2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT SSL SHA2|CN=*.azurewebsites.net
X-Client-IP 109.128.4.143
X-Forwarded-Host [host].azurewebsites.net
X-Forwarded-Server SmallDedicatedLinuxWebWorkerRoleIN252.corp.microsoft.com
```

The `X-ARR-SSL` header seems like a good candidate to detect the client using https, and I'm using the following code in my application startup:

```
app.Use((context, next) =>
{
    if (context.Request.Headers.TryGetValue("X-ARR-SSL", out StringValues pathBase))
    {
        context.Request.Scheme = "https";
    }

    return next();
});
```

Leaving this here for anyone else who may be hitting this, took me some time to figure it out :)

**Comment by erwinwildenburg** [comment]
@qmfrederik I was just looking into the exact same thing :)
Thanks!

**Comment by BennieCopeland** [comment]
Can we also get docs on using IIS as a reverse proxy without ANCM, or alternatively/in addition to, allow configuring ANCM without having it control the kestrel process. My use case is that in my web application, I have a background thread to handle some tasks, and the recommended way to do that safely is hosting as a windows service. We're attempting to deploy now, but running into issues generating absolute URLs using `UrlHelper`.

**Comment by BennieCopeland** [comment]
Using IIS URL Rewrite to map from the FQDN to localhost:5000.

We've been working on the problem all day, checking the different ASP.Net core repos figuring out how ANCM works. We got it working with `x-original-for` set to host:port, `x-original-proto`, and `x-forwarded-host` and my coworker is testing to see what the bare minimum host headers are to keep it working.

The second issue we ran into was the base path. We are hanging this off an existing IIS site as a sub application, and it seems that ANCM uses an environment variable to set that value. We've solved that by having the `hosting.json` urls setting have the same base path instead of hard coding it `app.Use` as demonstrated in a comment above. I.e. `{ "urls": "http://mydomain.com/subapp"}`.

Our next issue we are tackling is getting https to work, and after that the need to support client certificates for authentication.

**Comment by Tratcher** [comment]
@shirhatti can you comment on @BennieCopeland's UrlRewrite/ARR scenario?

**Comment by shirhatti** [comment]
@BennieCopeland Did you run into any difficulties with that scenario?
I haven't tried it myself, but I expect ARR proxying locally to your Windows service to just work.

I can post back here when I've had a chance to try it out myself. 
cc @pan-wang

**Comment by pan-wang** [comment]
ARR just replaces the host fragment in the request url with the host defined in the configuration. If you configured everything correctly, the local scenario (targeting a windows service) should work.

**Comment by buvinghausen** [comment]
@nrandell you are a gentleman and a scholar

**Comment by Tratcher** [comment]
And another: https://github.com/aspnet/Home/issues/2219

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/1508

**Comment by brandoncole** [comment]
Thanks @nrandell - we were missing the 
````
options.KnownNetworks.Clear();
options.KnownProxies.Clear();
```
but adding that resolved our problem when hosted in Elastic Beanstalk via ELB / EC2 on AWS.   I followed the conversations over at https://github.com/aspnet/Mvc/issues/6360 and @singlewind as well.

**Comment by Tratcher** [comment]
And https://github.com/aspnet/Security/issues/1521

**Comment by mjnorman** [comment]
@pksorensen 's fix above worked for me.  Thanks team!

**Comment by Tratcher** [comment]
And https://github.com/aspnet/Security/issues/1529.

@danroth27 can we move this up the priority list? We're getting consistent hits on it.

**Comment by Rick-Anderson** [comment]
@Tratcher  we can do this for [Sprint 127 (11/11/17 - 12/01/17)](https://github.com/aspnet/Docs/milestone/22)
@scottaddie  can you take this on?

**Comment by scottaddie** [comment]
@Rick-Anderson Yes. I'll get to it next sprint, as you already mentioned.

**Comment by ygoe** [comment]
What's the default for `ForwardedHeaders` when calling just `app.UseForwardedHeaders()` without options? I can't find it in the source code:

https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersExtensions.cs

The documentation of this topic is useless, it doesn't explain anything:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.forwardedheadersextensions.useforwardedheaders

**Comment by Tratcher** [comment]
@ygoe ForwardedHeaders is None by default.
https://github.com/aspnet/BasicMiddleware/blob/dd038387285bf9fa8dc52910ef762b9843ff22e4/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersOptions.cs#L51-L74
https://github.com/aspnet/BasicMiddleware/blob/dd038387285bf9fa8dc52910ef762b9843ff22e4/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeaders.cs#L11

**Comment by ygoe** [comment]
@Tratcher Ah, so `app.UseForwardedHeaders()` does exactly the opposite – it does *not* use any forwarded headers. Good to know.

**Comment by Tratcher** [comment]
*poke* We're getting almost daily questions about this topic.

**Comment by Rick-Anderson** [comment]
@Tratcher  -- @scottaddie  will work on this tomorrow. Are you asking that we doc ** ForwardedHeaders is None by default.** or asking for the  request in the title:

**Docs for UseForwardedHeaders, working with reverse proxies and load balancers**

**Comment by Tratcher** [comment]
Overall docs for working with reverse proxies please.

**Comment by guardrex** [comment]
![wallace](https://user-images.githubusercontent.com/1622880/37852078-3ccd7586-2eaf-11e8-829e-fd150b31d343.jpg)

**_You ain't got no problem, @Tratcher. I'm on the topic. Go back in there and chill them devs out and wait for The Rex, who should be coming directly._** - Marsellus Wallace ([Ving Rhames](https://www.facebook.com/Ving-Rhames-201254109906831/))

[Pulp Fiction](https://www.miramax.com/movie/pulp-fiction/) Copyright 1995 [Miramax Film Corp.](https://www.miramax.com/)

**Comment by buvinghausen** [comment]
Not sure if this is the right place to put this remark but I'm hoping this might save someone else looking some time.  We are running on AWS in Docker on Linux with Nginx as the proxy back to kestrel.

When we upgraded from .NET Core Preview 1 to Preview 2 the forwarded headers middleware stopped working because the KnownNetworks was no longer trusting the IPNetwork from our NGinx proxy.  It turns out previously that address was regular IPV4 but after Preview 2 (and still true in RC1) the address from Nginx was now an IPv4MappedToIPv6 address so we just had to put the ::ffff: prefix on the IP during the call to IPAddress.Parse and the rest fell in place.

I'm guessing since this is still true after the RC1 bits have dropped it will make it into .NET Core 2.1 RTM so we may want to flag this in the Linux production conversion guide or something.

**Comment by Tratcher** [comment]
@buvinghausen what configuration did you provide for kestrel? Something like `"urls": "http://*:8080"`?

**Comment by bihe** [comment]
@buvinghausen how did you actually solve this? I have the same issue. Nginx+letsencrypt in front of a docker image where I use dotnet core with OpenIdConnect@Google. 
Issue is, that https is not used for redirection urls - so I end up with https://accounts.google.com/o/oauth2/v2/auth?client_id=<client_id>&redirect_uri=HTTP%3A%2F%2F<my_url>%2Fsignin-oidc&response_type=....
expected: redirect_uri should use HTTPS

**Comment by nikator** [comment]
@buvinghausen thank you for comments. I was using UseForwardedHeaders with known proxy set to "192.168.x.x". After upgrade to 2.1 it stopped resolving remote IP addresses and throwing message "Unknown proxy: [::ffff:192.168.x.x]:...".
Adding IP address as "::ffff:192.168.x.x" to known proxies have helped.

**Comment by MartinDawson** [comment]
I'm getting infinite redirects with asp.net core's new HTTPS system for this. The same as this: https://stackoverflow.com/questions/48479608/infinite-redirect-loop-in-asp-net-core-while-enforcing-ssl

What's the actual solution for this?

**Comment by Tratcher** [comment]
@MartinDawson https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot

Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

**Comment by OsmondJiang** [comment]
I believe a lot of people are looking for a "server workable forward headers configuration example" in this thread but somehow the github hide it. Here is the link https://github.com/aspnet/docs/issues/2384#issuecomment-297980490, hope this can resolve your problems.

**Comment by V1ct0rV** [comment]
@MartinDawson I had same problem, The solution for me was this: https://stackoverflow.com/a/51635196/193361

Make sure to put at the beginning of `Startup.Configure` method:

```
app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.All
});

app.Use((context, next) =>
{
    if (context.Request.Headers.TryGetValue("X-Forwarded-Proto", out StringValues proto))
    {
        context.Request.Scheme = proto;
    }

    return next();
});
```

**Comment by Tratcher** [comment]
@V1ct0rV while that may work for your scenario I don't recommend it as a general solution. It's better to get ForwardedHeadersOptions configured correctly than to blindly apply X-Forwarded-Proto.

**Comment by Tratcher** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot for relevant fields to log.

**Comment by V1ct0rV** [comment]
Hi @Tratcher, this is the output, I masked IP addresses and domains:

```
Request Method: GET
Request Scheme: https
Request Path: /headers
Request Headers:
Cache-Control: max-age=0
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es;q=0.8
Cookie: __cfduid=dfb239a4ce70a0a5bc821ada409fcb1761535638746; gsScrollPos-1878=; .AspNetCore.Antiforgery.9TtSrW0ssss=CfDJ8LPdmgbQkBpGkdbE_rXr0sqZk2-fRfbOvBKWpVqKiUlJr2hST7d7n_fPY-737AeNqCNl4vYf0FWn4TKFKxHgjFi26J2gKAuWvM54Rhm2VIwmi9bI
Host: xxx.something.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
X-Request-ID: 69679e55cc863857c677f4d806d460e7
X-Real-IP: xx.xx.xx.xx
X-Forwarded-For: xx.xx.xx.xx
X-Forwarded-Host: xxx.something.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Original-URI: /headers
X-Scheme: https
upgrade-insecure-requests: 1
dnt: 1

Request RemoteIp: ::ffff:456.675.0.5
```

**Comment by Tratcher** [comment]
That RemoteIp is your problem, see ForwardedHeadersOptions.KnownNetworks or KnownProxies.

**Comment by OsmondJiang** [comment]
@V1ct0rV ,check my last comment, open the hidden comments in this thread and you will find your answers.

**Comment by V1ct0rV** [comment]
@OsmondJiang Thanks! I applied @nrandell Solution:

```
var options = new ForwardedHeadersOptions
	        {
		        ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
	        };
	        options.KnownNetworks.Clear();
	        options.KnownProxies.Clear();
	        app.UseForwardedHeaders(options);
```

I spent one day trying to solve this issue, the documentation should be more clear or at least do not add default values to `KnownNetworks` and `KnownProxies`

Thanks!!!

**Comment by guardrex** [comment]
@Tratcher Can you specify what, if anything, from https://github.com/aspnet/Docs/issues/2384#issuecomment-297980490 that you'd like me to address in the topic? I'm a bit worried about clearing networks/proxies given the guidance on header spoofing.

**Comment by Tratcher** [comment]
Yeah, clearing isn't an acceptable answer either. You need to actually supply a new value.

**Comment by nrandell** [comment]
I think what would be really useful for people is to explain how to do this in various scenarios. So for my example where the debug message said `Unknown proxy: 10.0.1.4:53690`, I know I could probably get data from anything on 10.0.1.x, or possibly even 10.0.x.x.

Making it obvious how some of these scenarios work would make things a lot easier.  I'm sure there are some standard scenarios, such as Azure app service running docker containers on Linux that would benefit from some of these examples. I'm pretty sure I've copied and pasted the clearing of `KnownNetworks` and `KnownProxies` a number of times for various projects I've worked on.


Is header spoofing really possible if you are sitting on an azure app service (I'm sure I will regret writing this comment …)

**Comment by ygoe** [comment]
Isn't there a design issue in "examples" for "standard scenarios"? Do you want to change your application code and rebuild when you switch the hosting environment? Say from Azure to a local server, or whatever. Do you even have the code for all web apps you run? I feel these things should be covered by the hosting environment in a way that doesn't require code changes.

**Comment by Tratcher** [comment]
They should certainly be extracted to config to facilitate environment portability.

**Comment by V1ct0rV** [comment]
Hi @Tratcher 

My nginx reverse proxy Ipaddress is: `100.116.0.5` and the local network CIDR is `100.64.0.0/10` I tried with `options.KnownProxies.Add(IPAddress.Parse("100.116.0.5"));` with no luck, then tried with `options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("100.64.0.0"), 10));` and did not work.

I really want to have configured it in a proper way, what I'm doing wrong?

**Comment by Tratcher** [comment]
Your debug output said the reverse proxy address was `::ffff:456.675.0.5`. Note that's an IPv4 address nested in an IPv6 address. Your KnownProxies or KnownNetworks would need to be represented as IPv6 addresses as well.

**Comment by V1ct0rV** [comment]
Hi All,

I finally get working my app, the configuration at the end is:

```
services.Configure<ForwardedHeadersOptions>(options =>
	        {
		        options.ForwardedHeaders =
			        ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
		        options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("::ffff:100.64.0.0"), 106));
			});
```

I think this should be documented on the official documentation, not always we deploy the reverse proxy in the same server, about the ipv6 this should be documented too.

Thanks for you help.

**Comment by Tratcher** [comment]
@guardrex you got this?

**Comment by guardrex** [comment]
Yes, I'll open an issue.

> Note that's an IPv4 address nested in an IPv6 address. Your KnownProxies or KnownNetworks would need to be represented as IPv6 addresses as well.

We're going for that :point_up: coverage.

Anything else?

**Comment by Tratcher** [comment]
And general discussion around setting KnownNetworks/Proxies. https://github.com/aspnet/Docs/issues/2384#issuecomment-418785152

**Comment by guardrex** [comment]
We already have it, *generally speaking*.

I need more specific guidance in terms of what's missing from what we currently have on `KnownProxies` and `KnownNetworks`.

Let's move this over to the issue for further discussion on what else the topic needs. #8417

**Comment by mattnewell** [comment]
With due respect, this API is the pit of failure.

If you call `UseForwardedHeaders` with no arguments, it does nothing and throws no exception. See https://github.com/aspnet/BasicMiddleware/issues/296

If you call `UseForwardedHeaders(new ForwardedHeadersOptions { ForwardedHeaders = ForwardedHeaders.All })` it does nothing and throws no exception.  See https://github.com/aspnet/Docs/issues/2384#issuecomment-286997661

I would suggest this needs improvement at the API level. If this isn't the appropriate repository, I'm happy to do the legwork of logging additional issues in the correct location.

**Comment by ygoe** [comment]
Stupid question, because I see this comment a lot: What does that mean “not tracked”? Somebody does get notifications.

**Comment by jondmcelroy** [comment]
To sum up the 90+ comments here:
```C#
// In the Configure function in Startup.cs

// Add the ForwardedHeadersOptions that you want.
// By default the options are empty, so you MUST specify what you want.
var options = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
};

// Clear the forward headers networks so any ip can forward headers
// Probably only want to do this while testing or in a dev env
options.KnownNetworks.Clear();
options.KnownProxies.Clear();

// OR

// For security you should limit the networks that can forward headers (MUST BE IN IPv6)
// Adding a network with a mask
options.KnownNetworks.Add(new IPNetwork(IPAddress.Parse("::ffff:111.12.0.0"), 16));
// OR Adding specific ips
options.KnownProxies.Add(IPAddress.Parse("::ffff:10.0.1.2"));
options.KnownProxies.Add(IPAddress.Parse("::ffff:10.0.1.3"));

app.UseForwardedHeaders(options);
```

**Comment by Tratcher** [comment]
@jondmcelroy the IPv6 restriction no longer applies in 2.2.

Clearing the networks and proxies is strongly discouraged.

**Comment by buvinghausen** [comment]
@Tratcher strongly discouraged may not be sufficient.

You should *never ever ever ever* consider doing it ;-)

**Comment by andycmaj** [comment]
key point here that f'ed me over: https://github.com/aspnet/Docs/issues/2384#issuecomment-286271048

> You have it set to ForwardedHeaders.All, but you don't have an x-Forwarded-For header, so it freaks out and won't process Proto either. Scope it down to just the header you need.

**Do NOT use `ALL`. Use only the headers your proxy ACTUALLY forwards.**

**Comment by guardrex** [comment]
@andycmaj Please open a new issue using the **Content feedback** button at the bottom of the [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/aspnet/core/host-and-deploy/proxy-load-balancer) topic.
