### ISSUE TITLE
security/cors Add content to CORS topic on using wildcards or custom logic for allowing origins

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2386]
- [ ] See https://github.com/aspnet/CORS/pull/94 for details on wildcards/custom logic.
- [ ] Consider adding back the client and service test project creation sections from the [ASP.NET classic original version of this article](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api).
- [x] ~Respond to LiveFyre comments~

**Comment by pranavkm** [comment]
@Rick-Anderson do you know what questions this issue references:

> Respond to LiveFyre comments

**Comment by Rick-Anderson** [comment]
@pranavkm 	we lost LiveFyre comments a couple years ago.
