### ISSUE TITLE
Security: Extend ContosoUniversity with Authentication

### ISSUE THREAD

**Issue by mekinney** [aspnet/Docs#2391]
Extend ContosoUniversity tutorial in Working with Data / Getting started with ASP.NET Core to include  Authentication.  This would be a more real world example.  This example would demonstrate how to give existing students the ability to login and see their classes.  Demonstrates how to link authentication classes (ex: ApplicationUser) to application classes (ex: Student).

**Comment by Rick-Anderson** [comment]
@mekinney  PR https://github.com/aspnet/Docs/pull/1780 does this. I need to fix one security issue and hope to get to it soon.
cc @tdykstra  @spboyer
