### ISSUE TITLE
Improvements to site navigation

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2406]
- [x] Make expandable TOC nodes go to index.md page for the group rather than just expand/collapse the TOC, similar to how the docs.ms.com/dotnet/articles site works.
  - [x] Fundamentals and Fundamentals/Server - make overview topic for Fundamentals #2364
  - [x] Security/Authentication/Social #2341 #2361
  - [x] Tutorials - index.md should organize the list of tutorials and facilitate navigation to tutorials in other parts of the TOC
- [x] Revise structure of MVC section of TOC. 
- [x] Revise structure of Deployment section of TOC. 
- [x] Review and revise TOC node titles to make them work better with the TOC filter box. E.g., on the .NET site entering "tutorials" gets you to all of the TOC sections that have tutorials, but doing that on the ASP.NET Core site misses many of them.

**Comment by wadepickett** [comment]
@tdykstra @Rick-Anderson ,
Update on this?  Pr1 label but in the backlog still.

**Comment by Rick-Anderson** [comment]
@wadepickett  no ETA and not scheduled in the next quarter.

**Comment by tdykstra** [comment]
@wadepickett This won't take a big effort to finish up, I can take some time next week to take care of it.
