### ISSUE TITLE
Address MVP summit feedback on Configuration

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2408]
Most of the issues were address independently in  #2346. Use the bullets below to address the remainder.

- [ ] Add intro that states why you'd want to use config and that it works for ASP.NET MVC Core apps.       **addresses** console app	Assumed that the post wasn’t about ASP.NET
- [ ] The beginning of the doc is a bullet pointed list of the configuration providers that are supported which is very eye catching.  I think this should be moved later in the doc, and it should started by helping people get started with the new paradigm in .NET Core rather than explaining that it’s going to work with Environment variables, Command line args, etc.
- [ ] there is no section heading that uses the title “ASP.NET” or “MVC”, 
- [ ] Use a single method for passing configuration when building the complete code sample walk through before showing alternate methods.  Current doc consecutively shows three ways (passing whole Configuration object, binding to a subsection, using a lambda expression to set values) before getting to the complete Startup.cs which then includes all three in the complete code sample

---------- Email below ----------------
**From**: Andrew Hall Sent: Friday, November 18, 2016 10:52 AM
**Subject**: Web Tools MVP Summit UX Study

**Using Configuration in .NET Core**
Takeaways
•	No one can add config settings without Googling, and docs.asp.net is confusing to follow
o	Bing doesn't even have docs.asp.net as a top result
o	One big problem, is the first code snippet is a console app, many people saw this and assumed the doc didn't apply to ASP.NET apps
o	Another problem is there are three different ways of doing it all mixed together
o	The code snippets provided, are not in full context (e.g. people wanted a complete example Startup.cs)
•	Current config is extremely verbose compared to the old way, even with examples it took people over 15 minutes to be successful accessing a value stored in appsettings.json
•	Presence of the Web.config means many people went straight to that as a starting point
o	No one saw the comment in Web.config saying to use appsettings.json

--------------------------------------------------------------------------------------------------

study I think there are a few simple things we could do to the existing .NET Core configuration doc that would help people be successful with it much more quickly.

The overall pattern that we saw, was:
•	people Googled for “.NET Core configuration”
•	the doc is the #1 result (great!)
•	they clicked it
•	They scrolled down as far as the first code sample, which is a console app
•	Assumed that the post wasn’t about ASP.NET
•	Clicked the back button to go to their search results
•	Didn’t have much success in other places
•	Eventually ended up back in our doc
•	Finally ventured further down beyond the Console sample to the part that applies to ASP.NET
•	Got confused by:
o	The code samples that concat to a complete Startup.cs were spread across multiple code blocks with explaining text not in a single sample block
o	The sample code block for “ConfigureServices()” contains three different ways of doing it only distinguished by comments 

A few practical suggestions to make it easier for people:
•	The beginning of the doc is a bullet pointed list of the configuration providers that are supported which is very eye catching.  I think this should be moved later in the doc, and it should started by helping people get started with the new paradigm in .NET Core rather than explaining that it’s going to work with Environment variables, Command line args, etc.
•	I understand we started with a Console app because we wanted a grow up story like Node, but as soon as people saw the console sample, they thought they were in the wrong doc.  I think it’s a good sample, but there should be some structure and introduction that tells the user up front there are both ASP.NET and Console sample snippets
o	Related, there is no section heading that uses the title “ASP.NET” or “MVC”, if we added one of those for the sample part that shows how to this, it would help catch people’s eye as they are scrolling through looking for that
•	Prescribe a single best practice method of doing it
•	Provide a complete Startup.cs that shows this, and only this way
•	Cover the other potential ways of doing it in a following section if we think it’s important. Although personally I’d vote for keeping the docs as simple as possible, prescribing a single way of doing it, and then expounding on other methods in a blog post.

**Comment by ardalis** [comment]
Want me to work on this one? If yes, assign me.

**Comment by Rick-Anderson** [comment]
@ardalis  I totally rewrote [config ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration) just before  the MVP summit - but it wasn't published yet. I think my rewrite fixed 95% of the problems they identified. I might move MVC sample up higher or do something to address that.

**Comment by Rick-Anderson** [comment]
rewrite addressed most of this.
