### ISSUE TITLE
Organize and expand  Web API

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2410]
Customer likes [Building Your First Web API with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) but would like to see a followup tutorial.  

- [ ] #2461 Angular 2
- [ ]  #949 Patch
- [ ]  Versioning
- [ ]  Security - CORS, XSRF, JWT
- [ ]  Update [Building Your First Web API with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) to use  EF in-memory DB. This will make it easy to write test and show how to use EF
- [ ] aggregate Web API content

**Comment by smatthews1999** [comment]
I would like to see adding Entity Framework incorporated (Code First) and actual save operations to a DB.  Where would these saves most likely happen from... TodosRepository?  Is there any way to avoid having to write models twice (TodoItem and the DB equivalent)?

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/Docs/projects/5

**Comment by vijayande** [comment]
Rick, how do I connect to Azure SQL DB and get some records from the DB using web-api, could you please share any article on the same.

**Comment by Rick-Anderson** [comment]
@vijayande this is not a support forum. I recommend you post your question to SO.
