### ISSUE TITLE
How to contribute to https://github.com/aspnet/

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#242]
generic to any open source package where you want to clone the code for the package, replace the package with the code, make your change, submit your change to the project and then replace the code with the update package. This feature is really about encouraging the .NET open source community. This probably should live under the DNX docs as it really isn’t specific to ASP.NET 5.

**Comment by Rick-Anderson** [comment]
Originally I planned on writing an article on debugging MVC 6 source but @danroth27 wants this generic. I think the debugging MVC 6 has value.

**Comment by Eilon** [comment]
How to debug MVC is very different from how to contribute - I want to make sure those concepts are not conflated. The best way to contribute to MVC or any OSS project is to start a discussion, not to send a pull request.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Docs/issues/505 opened for debugging ASP.NET 5.
How to contribute to ASP.NET 5
1. Open an issue. (simple way to contribute)
2. Start a discussion (best way to contribute).
3. Create a PR.
4. Other

**Comment by Eilon** [comment]
I also want to make sure we don't duplicate content from https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md.

**Comment by danroth27** [comment]
We should just add a link under the Contribute node that points to https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md as the official content on how to contribute to the ASP.NET project. We will need to distinguish this article from the existing article on how to contribute to the docs. Proposed TOC:

Contribute
 - [ASP.NET Contributing Guide](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md)
 - [ASP.NET Docs Contributing Guide](https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md)
 - [ASP.NET Docs Style Guide](https://docs.asp.net/en/latest/contribute/style-guide.html)
 - [ASP.NET Docs Survey](https://docs.asp.net/en/latest/contribute/docs-survey.html)
