### ISSUE TITLE
Clean up file names to use lower case

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#244]
We still have a bunch of files that have mixed casing. To avoid casing issues on Linux we should just lower-case everything.

**Comment by Rick-Anderson** [comment]
@TomArcher can you add this to the contrib doc? It helps that we now have CI/CD

**Comment by danroth27** [comment]
I think we still have a bunch of cases where we aren't using lower case files.

**Comment by Rick-Anderson** [comment]
I don't think we should change articles that are working correctly (ie mixed case but the case is consistent in the .rst file). This should be the rule for new articles.

**Comment by Rick-Anderson** [comment]
Closing, too risky to change now. The templates generate mixed case files. Adding to style guide, "MD and images use only lower case".
