### ISSUE TITLE
Comment system/notifications on docs seems broken

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2444]
I wasn't getting notifications on doc comments after I made a comment on a few docs, so I tried to get into my profile to set notifications. After clicking the `Edit profile` link, it seems to get stuck and the profile is never loaded ... thus I'm unable to set notifications.

![capture1](https://cloud.githubusercontent.com/assets/1622880/21474178/5174b8e2-cae1-11e6-8cf9-4aa93918d0ec.PNG)

![capture](https://cloud.githubusercontent.com/assets/1622880/21474181/534cbdfe-cae1-11e6-84d6-762783f04f72.PNG)

**Comment by Rick-Anderson** [comment]
@tdykstra  please respond

**Comment by tdykstra** [comment]
@GuardRex The problem with editing your profile is a LiveFyre issue.  I get the same result when I click Edit Profile, but I'm getting notifications.  Did you click "Follow" under the comment text entry box on the articles you want to follow?

**Comment by GuardRex** [comment]
I'll try that. Thanks.

Is the broken profile situation tracked elsewhere ... can I close this issue?

**Comment by tdykstra** [comment]
Yes -- you can close this issue.

**Comment by tdykstra** [comment]
No, but I can't repro that.  Maybe someone else clicked Follow the same time you did, or you're such an important contributor that you count as two people.

**Comment by GuardRex** [comment]
Something funky going on here. I went over to the *Working with Static Files* doc. I just kept clicking "Follow" and "Unfollow" over and over. I was able to get the user count to jump up five users ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/21668108/52c2639e-d2c4-11e6-8670-8f6d58cdd443.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1622880/21668109/56a16b4a-d2c4-11e6-9b37-f85dab5634f7.PNG)

... then opened the doc page in Edge to show 26 ...

![capture3](https://cloud.githubusercontent.com/assets/1622880/21668136/9802e5fa-d2c4-11e6-93a6-2ac6b73adb97.PNG)

... went back to Chrome, closed the tab, opened a new tab, and navigated back to the page to find .....

![capture4](https://cloud.githubusercontent.com/assets/1622880/21668182/ffe85452-d2c4-11e6-9009-761d7049c660.PNG)

... next ... I opened a new Google window to the page to find .... *25*!!! ... with "Unfollow" showing on the page.

![capture5](https://cloud.githubusercontent.com/assets/1622880/21668247/987b0958-d2c5-11e6-8562-b72c1df3db1f.PNG)

### Yikes! .... the *LiveFyre Completely Random Counter*:tm: :smile:

**Comment by tdykstra** [comment]
OK, I passed that on to our LiveFyre contact also.

**Comment by tdykstra** [comment]
@GuardRex Regarding getting stuck at "loading profile", LF responded

>have you tried clearing your browser's cache/cookies, logging out and logging back in again?

When I do that it works for me.
