### ISSUE TITLE
"Adding a model" tutorial suggestion

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#2451]
In the [Adding a model](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model) tutorial, the following property in the `Movie` class should be decorated with a `Display` attribute to insert a space between the words "Release" and "Date":

```c#
public DateTime ReleaseDate { get; set; }
```

It's a common requirement to display text other than the default property name, so I think many would benefit from seeing how this is accomplished. Let me know if there's interest in this idea, and I can submit a PR. I'm proposing defining the property as follows:

```c#
[Display(Name = "Release Date")]
public DateTime ReleaseDate { get; set; }
```

**Comment by Rick-Anderson** [comment]
Yes, thanks.
