### ISSUE TITLE
Upgrading Testing Controller Logic sample code to 1.1

### ISSUE THREAD

**Issue by bcnzer** [aspnet/Docs#2453]
In the article [Testing Controller Logic](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing) the sample code references 1.0 of the .NET Core SDK. Specifically: 
- `1.0.0-preview2-003121` in global.json 
-  `netcoreapp1.0` in the project.json files

I'd like to change that to reference the v1.1 of the SDK. It's a small change: 
1. in global.json change the version to `1.0.0-preview2-1-003177` and 
2. In both projects, change the project.json files change it to `netcoreapp1.1`  

That being said, not sure if you want code samples to be using 1.1 at this point. I've noticed the download links for .NET Core default to the LTS version and I'm assuming that, in a clean install of VS 2015, you'd get 1.0 not 1.1

**Comment by Rick-Anderson** [comment]
@spottersys  Yes, thanks.
