### ISSUE TITLE
Document using ASP.NET Core with Angular 2

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2461]
We should see what docs we should add to the official ASP.NET Core docs for using Angular 2 with ASP.NET Core given the great work @SteveSandersonMS and the community have been doing in this area:

http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

see Suggestion for new page in client side development #2926

**Comment by spboyer** [comment]
Document Outline

- Using SpaServices for Angular and ASP.NET Core 
- What is SpaServices
     - Pre-rendering
     - TagHelpers
     - webpack / build and bundling
- Middleware
     - MapSpaFallbackRoute
     - UseWebpackDevMiddleware
- Prerequisites
- Creating a new project
     - Using the yeoman generator
          - What does it produce
          - Web API
          - Angular
- Debugging your application
     - VS Code
     - Visual Studio
 - Deploying your application
     - Azure
     - Docker

Please review and comment : @danroth27 @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
Good plan @spboyer! Suggested tweaks:

* Using SpaServices for Angular and ASP.NET Core / Overview of features
    * Pre-rendering
    * webpack / build and bundling
    * Ability to invoke Node.js code/packages from .NET code
    * Associated project templates
* Creating a new project
  * Prerequisites
  * Using the yeoman generator (+ when implemented, using dotnet new to create the same projects)
  * What does it produce
    * Web API
    * Angular
    * Build configuration
    * Tests and test runner
* Using SpaServices features
  * UseWebpackDevMiddleware
  * MapSpaFallbackRoute
  * asp-prerender-module tag helper
* Debugging your application
  * In browser dev tools (e.g., in Chrome)
  * VS Code
  * Visual Studio
* Deploying your application
  * Azure
  * Docker

If this doesn't make sense, let me know. Of course you should change it in any other way you think best :)

**Comment by damienbod** [comment]
Should also add a section about AoT, treeshaking, HMR, angular lazy loading and using npm, yarn

**Comment by FabianGosebrink** [comment]
Hey, how about this:

- Using SpaServices for Angular and ASP.NET Core
- What is SpaServices
    - Pre-rendering
    - TagHelpers
- Middleware
    - MapSpaFallbackRoute
    - UseWebpackDevMiddleware
- Prerequisites
- Creating a new project
    - Using the dotnet cli
    - using npm/yarn
    - What does it produce
    - Web API
    - Angular
    - Using Webpack (dev/prod)
    - Using Lazy Loading
- Debugging your application
    - VS Code
    - Visual Studio
- Distribution
    - Ahead of Time Compilation
    - TreeShaking
- Deploying your application
    - Azure
    - Docker

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS  can you split up an outline into a couple docs? Your outline (and @FabianGosebrink )  look like they could be spit up.  Please consider @FabianGosebrink  outline.
 @spboyer  won't be doing the work so it would be great if you can come up with the outline.

@fiyazbinhasan  are you interested in this?

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson interested! should i start with @FabianGosebrink outline?

**Comment by SteveSandersonMS** [comment]
@FabianGosebrink's outline looks great! Only points I'd add:

 * Would be good to describe testing with Karma (i.e., just that you can run `npm test` and what happens - once people realise there's a working Karma setup out of the box, they will go forwards with that)
 * The AOT/treeshaking stuff is a work-in-progress right now, so you might just have to leave a placeholder until that's streamlined.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  Yes, with Steve's points. cc @tdykstra

**Comment by fiyazbinhasan** [comment]
@SteveSandersonMS @Rick-Anderson got it! will be on it ASAP

**Comment by FabianGosebrink** [comment]
@fiyazbinhasan would love to help

**Comment by fiyazbinhasan** [comment]
@FabianGosebrink awesome!!! it would be great if you can refer me to some online resources :D

**Comment by FabianGosebrink** [comment]
@fiyazbinhasan add me on Skype with my email here in github. Let's continue there...are you okay with that?

**Comment by fiyazbinhasan** [comment]
@SteveSandersonMS can you refer me some Api docs where the SpaServices taghelpers are briefly described. TIA :)

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson @FabianGosebrink starting here, [angular2-doc](https://github.com/fiyazbinhasan/Docs/tree/angular2-doc)

**Comment by damienbod** [comment]
Hi @fiyazbinhasan 

I think you should rename the doc to just angular-doc 
angular == version 2, 4 and 5 later this year
1 == angularJS

Then also remove all the 2s from the doc.

Is this the right place for feedback or should I add it directly on your branch?

Greetings Damien

**Comment by fiyazbinhasan** [comment]
@damienbod you can add it to the branch :)

**Comment by damienbod** [comment]
@fiyazbinhasan pull-request or issue?

**Comment by fiyazbinhasan** [comment]
PR :)
