### ISSUE TITLE
Outdated content in Publishing to IIS with Web Deploy using Visual Studio doc publishing/iis-with-msdeploy

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2478]
The [Publishing to IIS with Web Deploy using Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis-with-msdeploy) doc still refers to the HTTP platform handler. It also duplicates content about how to setup data protection. I think this doc should only cover the Publish gesture in VS and link to the [Publishing to IIS](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis) doc for all the other IIS setup details.

**Comment by Rick-Anderson** [comment]
1. Move how to publish to IIS from VS to https://docs.microsoft.com/en-us/aspnet/core/publishing/iis
2. remove this doc.

Just document the gesture from VS to IIS.

@GuardRex  can you do this?

**Comment by GuardRex** [comment]
@Rick-Anderson Sure thing. I'll take care of it.
