### ISSUE TITLE
Update Publishing to Docker to Azure

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2479]
Currently we point to https://docs.microsoft.com/en-us/azure/vs-azure-tools-docker-hosting-web-apps-in-docker, but I think this content is outdated. @spboyer what should we be pointing to?

**Comment by spboyer** [comment]
This is the correct link, but needs to be updated.

**Comment by spboyer** [comment]
There is not a way to create and issue in the azure-docs repo? Need to get the referenced article updated, the powershell script in the tools is no longer there and is invalid.

This is also for VS 2015, should have one for VS 2017 as well.

@squillace

**Comment by spboyer** [comment]
Under review with @danroth27 and @stevelasker

**Comment by spboyer** [comment]
@danroth27 - @mlearned said he would update the article (owner) 

cc:/ @erickson-doug

**Comment by Rick-Anderson** [comment]
> @mlearned said he would update the article (owner) 

cc:/ @erickson-doug

@mlearned  can we get an ETA on this update? Can you mention me in the PR? Can you create an issue I can point to?

cc @spboyer

**Comment by mlearned** [comment]
just replied via email.  I'm full until week of Dec 4th if I need to update it.  (focused on Azure DevOps project and other commitments) ..I could carve some time that week to roll something out if needed.

**Comment by Rick-Anderson** [comment]
> @mlearned said he would update the article (owner) 

cc:/ @erickson-doug

@mlearned  can we get an ETA on this update? Can you mention me in the PR? Can you create an issue I can point to?

cc @spboyer

**Comment by Rick-Anderson** [comment]
> @mlearned said he would update the article (owner) 

cc:/ @erickson-doug

@mlearned  can we get an ETA on this update? Can you mention me in the PR? Can you create an issue I can point to?

**Comment by mlearned** [comment]
@Rick-Anderson  sorry I had a couple articles confused and this one slipped through cracks. I'm not sure on original owner or how it got to me, but I'm updating via this work item here to knock it out https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1303910

**Comment by mlearned** [comment]
@Rick-Anderson  can you elaborate on the updates needed for this one?  it was updated back in may for VS 2017 … are there more updates needed?  https://docs.microsoft.com/en-us/azure/vs-azure-tools-docker-hosting-web-apps-in-docker       … sorry for back/forth, there are a lot of articles in play and want to make sure we are on the same page here.

**Comment by Rick-Anderson** [comment]
@mlearned  closing now, I didn't know it was updated in May.
