### ISSUE TITLE
Guidelines for security administration

### ISSUE THREAD

**Issue by PeteX** [aspnet/Docs#2486]
When we deploy an application, we also set up a maintenance process for it, because forgotten applications can easily turn into a security risk.  The main thing we're looking at is the application's third party dependencies.  These need to be updated if they have released security patches since our application was written.

The .NET Core documentation is very good on the programming-related aspects of security, for example how to use ASP.NET Core Identity, but it doesn't give any information relating to this kind of maintenance.  Ideally there would be a list of component versions which should no longer be used, because of known security weaknesses that have since been fixed.

I see there has been a security bulletin (aspnet/Announcements/issues/203) and it has been tagged Security.  Is that now a fixed policy, so searching for uses of that tag will turn up all known security issues?  Also presumably aspnet/Announcements is only for the web-related aspects of .NET Core.  Is there something similar for other components?

I imagine this is going to be an issue for lots of companies who are making the change from older versions of .NET.  As I understand it (my background is Linux more than Windows) with older versions, there was a single package rather than multiple components, and fixes would generally be installed automatically by Windows Update.

**Comment by Rick-Anderson** [comment]
This issue was moved to dotnet/docs#1397
