### ISSUE TITLE
update/port "View components and Inject in MVC 6"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#25]

**Comment by danroth27** [comment]
We should separate these two topics. It doesn't really make sense to cover View Components and Inject in the same topic.

**Comment by Rick-Anderson** [comment]
It's just the title that needs to change - the article is about VC's. My DI article goes into inject in more detail. The VCs in the article use Inject, so that needs some presentation.

**Comment by danroth27** [comment]
Dup #127.
