### ISSUE TITLE
[Localization] Missing the case when default namespace is different from assembly name

### ISSUE THREAD

**Issue by tanaka-takayoshi** [aspnet/Docs#2502]
[The document](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md#resource-file-naming) says:
> the default namespace (which is also the name of the assembly)

In some cases, the default namespace is different from the assembly name. However, the document is missing for this case. The document should describe the available workaround for it. Or should clearly say "this is the limitation" if there's no workaround.

**Comment by Rick-Anderson** [comment]
It goes on to say
>Resources are named for the type of their class minus the default namespace (which is also the name of the assembly). For example, a French resource in the LocalizationWebsite.Web project for the class LocalizationWebsite.Web.Startup would be named Startup.fr.resx. The class LocalizationWebsite.Web.Controllers.HomeController would be Controllers.HomeController.fr.resx. **If for some reason your targeted class is in the same project but not in the base namespace you will need the full type name.** For example, in the sample project a type ExtraNamespace.Tools would be ExtraNamespace.Tools.fr.resx.

That should be rewritten to:

If your targeted class does not use the same namespace you will need the full type name.** 

@ryanbrandenburg  is this correct?

**Comment by ryanbrandenburg** [comment]
@Rick-Anderson I don't think that's what @tanaka-takayoshi is saying. I think he's saying that although by default most people will have the default namespace be the same as their assembly name that's not always the case, the two can different. The determining factor is the [HostingEnvironement.ApplicationName](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs#L49) which I believe should be the AssemblyName.

We should remove the references to default namespace in that section.

@dougbu does that all sound accurate to you?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you tap [Edit ](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md) link and make a first pass? 

Can you include using resource files from another class ( a common question) - which I think is the same - using _FQN.fr.resx_

**Comment by tanaka-takayoshi** [comment]
I debugged something with reading [ResourceManagerStringLocalizerFactory] (https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizerFactory.cs) and @Rick-Anderson 's comment appears good.
At first, ApplicationName should be the AssemblyName. I think this is the current dotnet core specification and I confirmed when I specify the "name" in project.json, this become the application name and assembly name.

Then I tried two cases.
## Case1)
If the class name of resource, which is the T of ``IStringLocalizer<T>`` or ``IHtmlLocalizer<T>``, starts with the assembly name, we **must** abbreviate assembly name from class name. It means we **can't** specify the full class name.
e.g.:
assembly name: AspNetCore.StarterWeb
class name: AspNetCore.StarterWeb.Controllers.HomeController (used by ``IStringLocalizer<HomeController>`` )
resource file: Controllers.HomeController.ja.resx (in the case of Japanese resouce)
``AspNetCore.StarterWeb.Controllers.HomeController.ja.resx`` is not working.

## Case2) 
If the class name of resource doesn't start with the assembly name, we **must** specify the full class name in resource file name.
e.g.:
assembly name: AspNetCore.StarterWeb
class name: WebApplication.Controllers.HomeController (used by ``IStringLocalizer<HomeController>`` )
resource file: WebApplication.Controllers.HomeController.ja.resx (in the case of Japanese resouce)

**Comment by Rick-Anderson** [comment]
@tanaka-takayoshi  Excellent!

**Comment by dougbu** [comment]
@ryanbrandenburg your comments on assembly names are correct though @tanaka-takayoshi's cases make things more clear.

For one thing, there's no requirement that a C# namespace have _any_ relationship to the assembly name. So mentioning the default namespace is somewhat off-topic except for the narrow case where users create classes in or below the default namespace and that default happens to be different from the assembly name e.g. because the assembly name contains special characters.

**Comment by ryanbrandenburg** [comment]
I've made #2513 as a first run at clearing up that doc.

**Comment by ryanbrandenburg** [comment]
That's all merged in now, so closing this out.
