### ISSUE TITLE
Automatic Startup class detection.

### ISSUE THREAD

**Issue by tapanrami** [aspnet/Docs#2511]
As mention in the article that it will automatically choose the Startup class from alphabetically first namespace if it is not found in the root namespace. when i tried it i explicitly need to specify the namespace because it give me ambiguous error.

**Comment by tapanrami** [comment]
I tried using AssemblyName but its still not working.

**Comment by Rick-Anderson** [comment]
@tapanrami  thanks, created https://github.com/aspnet/Docs/pull/2538
