### ISSUE TITLE
Add Middleware ordering section to Middleware doc

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2516]
Per @JunTaoLuo in https://github.com/aspnet/Docs/pull/2505#discussion_r96088295

The Middleware doc should address middleware ordering that can circumvent middleware from running if it's placed after a terminal middleware.

Proposal: Add a section after the *Built-in middleware* section with content something like this ...

## Middleware ordering
Terminal middleware, which processes a request and returns a response, placed before another middleware will prevent the downstream middleware from executing. For example, if you place the Static File Middleware before the Response Compression Middleware, your static files cannot be compressed. The Static File Middleware will fully handle requests for static files, returning them to clients before the Response Compression Middleware can execute.

```c#
public void Configure(IApplicationBuilder app)
{
    app.UseStaticFiles();
    app.UseResponseCompression();
    app.UseMvcWithDefaultRoute();
}
```

If you intend to use the Response Compression Middleware to compress your static files, position the Response Compression Middleware earlier in the request processing pipeline. The following example demonstrates the middleware arrangement that would result in compression of your static files.

```c#
public void Configure(IApplicationBuilder app)
{
    app.UseResponseCompression();
    app.UseStaticFiles();
    app.UseMvcWithDefaultRoute();
}
```

**Comment by Rick-Anderson** [comment]
@GuardRex  looks good to me. Can you PR and ask [@]JunTaoLuo to review?
