### ISSUE TITLE
Codeblock Blues

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2524]
@Rick-Anderson @tdykstra

I was looking at some doc info and stopped for a sec to put in a few PR's to fix some codeblock issues. I became concerned about other docs. I imagine this happened with the move to DocFX: I count 90 docs with bad codeblocks.

After I have the draft ready for *Azure Key Vault Configuration Provider*, do you have any objection to my setting up one of my **ReximusMaximus:tm:** consistency PR's to get the codeblocks in order?

**Comment by tdykstra** [comment]
@GuardRex What are you seeing wrong in the code blocks?

Another cleanup task if you're interested is fixing headings in docs and the TOCs to be sentence case.

**Comment by GuardRex** [comment]
I see a lot of ...
* Indentation/spacing/blank line problems (e.g., inconsistent or incorrect 2-space or 4-space indents ... sometimes the inconsistency is even within the *same doc*, added or missing spaces on lines, blank line at the start of the end of a block, etc.)
* Wrong or inconsistent code language (e.g., JSON marked as JavaScript, "none" where it should state "console" or be blank, variable casing ... "c#" vs "C#", which would be cleaned up by using "csharp" everywhere, etc.)
* Highlighting (e.g., a highlight misses a brace, highlight includes a blank leading or trailing line, highlighting of braces is inconsistent, etc.)

I looked at every doc and totaled 90 of them that need a touch here and there. It's especially bad when the content is JSON, the text says "in the `xxx.json` file," and the codeblock is tagged `JavaScript`. :cry:

I enjoy a good 'ole fashioned consistency PR, so this one is right up my alley. I'd suggest that I list the codeblock consistency goals with examples on this issue. Once you let me know/confirm how the rules should be applied, I can sweep thru in a mega PR and fix everything in one shot.

> Another cleanup task if you're interested is fixing headings in docs and the TOCs to be sentence case.

Sure thing ... will keep me out of trouble here! :grin:

... and at some point down the line we still have the point-of-view problem and getting some phrases out of 3rd person.

**Comment by GuardRex** [comment]
Is this correct?

### Specifications
Content | DocFX Language | Indentation (spaces)
:---: | :---: | :---:
C# | csharp | 4
HTML | html | 4
CSS | css | 4
JavaScript | javascript | 2
XML | xml | 2
JSON | json | 2
Console | console | 2
Text | - | 2

**Comment by tdykstra** [comment]
That looks correct, but my suggestion is to correct indentation spacing only where doing so improves readability (for example by decreasing the necessity of horizontal scrolling) or makes the intent of the code clearer.

**Comment by GuardRex** [comment]
When you use the copy button or cut-and-paste you get whatever spacing is part of the code. If you're a bit fussy like me (hopefully not borderline OCD :smile:), you must stop and fix blown spacing after you paste into your IDE.

I'll check on treatment options for my OCD :cry:; but in the meantime, let me submit one for the ~12 MVC docs. If you cats don't like it, we'll just kill it and move on to something else. If that goes well and looks good, I'll batch up another PR for tutorials.

I have time: I'll be submitting the PR for the *Azure Key Vault Configuration Provider* doc Tuesday morning. I'm only lightly working on the *Using IIS Modules with ASP.NET Core* otherwise.

**Comment by GuardRex** [comment]
Tracking for updates:

- [X] client-side https://github.com/aspnet/Docs/pull/2529
- [ ] mvc
- [ ] fundamentals & data
- [ ] tutorials
- [ ] publishing & hosting
- [ ] security
- [ ] performance, mobile, testing, migration

**Comment by GuardRex** [comment]
@tdykstra 

MVC docs use "*ASP.NET Core MVC*" ... I thought it was supposed to be "*ASP.NET MVC Core*."

Are they correct?

**Comment by GuardRex** [comment]
Revised checks and updates
* Add description & keywords
* Codeblock updates
* Bold or plain text filenames converted to italics
* Title and header casing updated to sentence case (with TOC/index update)
* Table formatting
* Convert internal links to `xref:` format
* Get `en-us` out of links

**Comment by GuardRex** [comment]
@tdykstra There's too much churn on the repo for me to batch up changes to so many docs in each PR. The checks and updates I listed are rather time-consuming to make. If I were to batch-up many doc updates into large PR's, I'll likely end up with rebasing conflicts on my branch due to on-going updates with docs, which will slow me down even more.

Questions ...
1. If these checks & updates :point_up: are desirable, is it ok if I batch them into just 1-6 docs at a time, such that whatever I can do in one sitting here can go in as one PR?
2. Would you and @Rick-Anderson rather have me work on something else? Do you have higher priority item(s) where I could be of greater assistance?
3. Do you guys (now or later) want the Foundation `License.txt` agreement placed in each sample repo? If so, do you also want the copyright and license lines at the top of every C# file in the samples?

**Comment by Rick-Anderson** [comment]
@GuardRex  ya, we have lots of other higher pri stuff to work on. We'll find you something.
