### ISSUE TITLE
Livefyre comments still broken

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2567]
@tdykstra Livefyre made some changes such that profiles load correctly now :+1:; however, I'm still not getting messages from the forum on the Publish to IIS doc.

You can see in the screenshot that I'm "following" the comments. My E-mail address in their system is correct, which is an outlook.com address. I didn't get the last one that was posted eight days ago.

![capture](https://cloud.githubusercontent.com/assets/1622880/22169076/173cd0e6-df37-11e6-9169-00825d57f58f.PNG)

**Feature request:** Comments should be editable. I had to completely delete one just to make a change to it.

**Comment by tdykstra** [comment]
@GuardRex Is this still a problem, and if so do you have a recent example?

**Comment by GuardRex** [comment]
Yes ... I just checked and there are new messages that I didn't receive while configured to "Follow" the chat ...

![capture](https://cloud.githubusercontent.com/assets/1622880/22911345/d4373ec0-f224-11e6-8501-aa898491fe63.PNG)

I confirmed my E-mail address was correct when I filed this issue, but I just attempted to access my profile, and I received the spinning-forever-no-loading-profile (as we went through before) ...

![capture1](https://cloud.githubusercontent.com/assets/1622880/22911360/ec1871d0-f224-11e6-8731-cf2fa089b93a.PNG)

So ... I sign out and try to sign in again with my MS account and it fails. I request a password reset and no message has arrived (ten minutes later anyway) to reset the password.

You guys sure this whole *Deadfyre* :trollface: thing was a good idea? :grin:

**Comment by GuardRex** [comment]
I can't get signed back into the system now. The reset feature is not sending a reset or temporary password to my Outlook mail account.

**Comment by GuardRex** [comment]
Livefyre Support is handling the issue.

**Comment by GuardRex** [comment]
This isn't going to get resolved easily or quickly, so I'll reopen and post updates as it goes forward.

* Livefyre uses Zendesk for mail services.
* Livefyre Support claims that Zendesk's portal shows the messages are going out.
* At least some Zendesk servers are blacklisted by SORBS.
* MS and Proofpoint, the owners of SORBS, are doing security business.

Therefore, a possible cause for Livefyre messages not reaching Outlook is blocking on the Outlook side due to blacklisted servers. It's just a guess, but it would explain the behavior here.

**Comment by GuardRex** [comment]
Today's update ...

* They have no idea why their password reset system doesn't work. They had me forward the password reset link E-mail and the followup "Your password has been changed" E-mail.
* They didn't check if my outlook.com address is linked to the comments for *Publishing to IIS*, as I asked them to confirm.
* They have no answer on the Zendesk mail servers being blacklisted by SORBS. They remarked that I can whitelist the mail servers myself by adding their Zendesk address to my outlook.com Safe Senders list. [I'll let you guess what I think about the efficacy of that suggestion. :grin:]
* They didn't delete an account I setup inadvertently under "GuardRex_Corporation1" when trying to get their system to work, as I asked them to do.
