### ISSUE TITLE
dependent "templates.docs.msft" missing 

### ISSUE THREAD

**Issue by jhaker** [aspnet/Docs#2574]
Missing repository listed in ".openpublishing.publish.config.json".

"dependent_repositories": [
    {
      "path_to_root": "_themes",
      "url": "https://github.com/Microsoft/templates.docs.msft",
      "branch": "master"
    },
    {
      "path_to_root": "_themes.pdf",
      "url": "https://github.com/Microsoft/templates.docs.msft.pdf",
      "branch": "master"
    }
  ]

Error: 
Clone https://github.com/Microsoft/templates.docs.msft to folder C:\Users\jon\Documents\_ops\Docs\_themes failed. Error:
 Cloning into 'C:\Users\jon\Documents\_ops\Docs\_themes'... remote: Repository not found. fatal: repository 
 'https://github.com/Microsoft/templates.docs.msft/' not found
! RunExeProcess common.ps1: line 349

**Comment by Rick-Anderson** [comment]
@jhaker  that's a private repo used by OPS to build our docs. Why do you want to clone it?

**Comment by jhaker** [comment]
What repo is this regarding? I don't recall sending a clone request
directly to a git repo.

**Comment by jhaker** [comment]
Didn't realize local build instructions were being checked in. Thought it was a bug. My bad:) Please ignore. Closing out.

**Comment by jhaker** [comment]
Please ignore. Closing out.
