### ISSUE TITLE
Clarify in docs for 1.1 features that the app must consistently target 1.1

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2579]
We've seen issues where customers are trying to use 1.1 features in a project that targets netcoreapp1.0. Customers create a new project in VS, which target 1.0, and then add a 1.1 package and then don't understand why it doesn't work. This happened recently, for example, with someone following https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging#appservice and running into issues because they used the Microsoft.Extensions.Logging.AzureAppServices package in a 1.0 project.

We should clarify everywhere we discuss 1.1 features that your entire project should target Current bits.

**Comment by GuardRex** [comment]
This will apply to ...
* URL Rewriting Middleware `fundamentals/url-rewriting`
* Response Compression Middleware `performance/response-compression`
* Response Caching Middleware `performance/caching/middleware`
* Key Vault Configuration Provider `security/key-vault-configuration`
* Key Storage Providers `security/data-protection/implementation/key-storage-providers`
* Razor Syntax Reference: View compilation `mvc/views/razor`

I already have a *Package* section in the first four. The other two have sections where a line can be added.

> This feature is available for apps that target ASP.NET Core 1.1.0 and higher.

@tdykstra @Rick-Anderson Do you want me to take this one?

Notes on this already appear in ...
* Session and application state: TempData `fundamentals/app-state`
* Filters: Using middleware in the filter pipeline `mvc/controllers/filters`
* Configuration `fundamentals/configuration`

Backlog ...
* EventSource Logger Provider https://github.com/aspnet/Docs/issues/1979

**Comment by tdykstra** [comment]
> Do you want me to take this one?

Yes, please.

**Comment by GuardRex** [comment]
Not sure whaz what with View Components as Tag Helpers tho. https://github.com/aspnet/Docs/issues/1757
