### ISSUE TITLE
https://docs.microsoft.com/en-us/aspnet/webhooks/sending/ remove

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2580]
https://docs.microsoft.com/en-us/aspnet/webhooks/sending/ is just a link to https://docs.microsoft.com/en-us/aspnet/webhooks/sending/senders

@tdykstra  please fix

**Comment by tdykstra** [comment]
Fixed in aspnetmigration branch, will be going to master soon.
