### ISSUE TITLE
.gitignore cleared

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2607]
see https://github.com/aspnet/Docs/commits/aspnetmigration/.gitignore

@neusamir Is this clearing temporary?  When will it be restored? We rely on it to keep the repository clean.
cc @tdykstra  @danroth27

**Comment by neusamir** [comment]
Good question. I will look into ignoring everything under /aspnet instead of the whole tree. It was removing files that we needed to include.

**Comment by Rick-Anderson** [comment]
Can you add a _./aspnet/gitignore_ to that folder and restore this file?

**Comment by tdykstra** [comment]
And is it possible to determine which files were getting excluded and remove only those from the .gitignore rather than clearing out the whole file?  Maybe we can still have just one repo-level file.

**Comment by Rick-Anderson** [comment]
You can nest .gitignore, so just add an empty _./aspnet/gitignore_

**Comment by neusamir** [comment]
Ok this is done.
