### ISSUE TITLE
Document OnPrepareResponse in the Static Files doc

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2625]
[Working with static files in ASP.NET Core (fundamentals/static-files)](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files) doesn't document `OnPrepareResponse`; consequently, devs can't see how to add a header. For example, https://github.com/aspnet/ResponseCaching/issues/97.

Might be able to roll it into the last code example of *Serving static files*. Could go something like the following with some text added to call it out ...
```c#
public void Configure(IApplicationBuilder app)
{
    app.UseStaticFiles();

    app.UseStaticFiles(new StaticFileOptions()
    {
        FileProvider = new PhysicalFileProvider(
            Path.Combine(Directory.GetCurrentDirectory(), @"MyStaticFiles")),
        RequestPath = new PathString("/StaticFiles"),
        OnPrepareResponse = ctx =>
        {
            ctx.Context.Response.Headers.Append("Cache-Control", "max-age=3600");
        }
    });
}
```
Let me know if you want me to take a stab at it.

[Side Note 1: I think I found a bug tho in the Static File Middleware. I'll open an issue to ask.]

[Side Note 2: `IHostingEnvironment` and `ILoggerFactory` are injected into `Configure()` methods but not used. Seems like they should be removed.]

**Comment by Rick-Anderson** [comment]
@Tratcher  please approve or reject this idea.

**Comment by Tratcher** [comment]
👍

**Comment by GuardRex** [comment]
I'll put up a PR this evening for u to consider.
