### ISSUE TITLE
ASP.NET Migration TOC issue

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2667]
- [ ] Remove MVC 3 Music Store or maybe move under Older version 1, 2 and 3 and don’t surface any of the tutorials

**Comment by tdykstra** [comment]
@Rick-Anderson There are only two Music store tutorials in the TOC and one is clearly marked MVC 3 and the other is clearly marked MVC 2 -- why do these need to be removed?

**Comment by Rick-Anderson** [comment]
They don't need t be remove but they are so old they are of little value.  Probably close this issue now.
