### ISSUE TITLE
Document NPM/Bower installation and settings

### ISSUE THREAD

**Issue by vkichline** [aspnet/Docs#267]
The VS tooling private installation of npm and bower is intentional and beneficial, but hard to understand if not presented right. Document how and why these are installed as they are, and how to alter the settings for different scenarios.

**Comment by Rick-Anderson** [comment]
@vkichline  can you outline this and I'll make sure someone publishes the doc.

**Comment by Rick-Anderson** [comment]
@vkichline  - is it OK if we add that to https://docs.asp.net/en/latest/client-side/bower.html ? Also, can you outline  how and why these are installed as they are, and how to alter the settings for different scenarios.and I'll get this updated.

**Comment by danroth27** [comment]
@madskristensen Anything to document here?

**Comment by spboyer** [comment]
for **bower**, the *.bowerrc* file must be edited on a per project basis.
```
{
    "proxy":"http://<host>:<port>",
    "https-proxy":"http://<host>:<port>"
}
```
If working behind an authenticated proxy, user and password should be included like this:
```
{
    "proxy":"http://<user>:<password>@<host>:<port>",
    "https-proxy":"http://<user>:<password>@<host>:<port>"
}
```

This is documented on the [bower.io] site at https://bower.io/docs/config/ 

for **npm** node.js must be installed globally and then the registry is set with the command:
```
npm config set registry=<registry url>
```

documented at https://docs.npmjs.com/cli/config

is this something that we just want to link to in the doc(s) when referencing node.js or bower?

@danroth27  @vkichline  @Rick-Anderson

**Comment by danroth27** [comment]
Let's not duplicate the bower/npm docs. If there are VS specific things to document here then let's do it. Otherwise I think we should close this issue.
