### ISSUE TITLE
Migrate article from https://docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#2679]
I think it make more sense for [this article](https://github.com/dotnet/docs/blob/master/docs/framework/docker/aspnetmvc.md
) to live in this docset as opposed to the .NET docset.

**Comment by Rick-Anderson** [comment]
@spboyer  @tdykstra  can you recommend where this should go in the TOC? I'll do the migration.

**Comment by tdykstra** [comment]
@Rick-Anderson We can put it in the new hosting and deployment TOC section -- it would be best to wait until @danroth27 reviews the plan for that section, then I can tell you where it fits.

**Comment by shirhatti** [comment]
My $0.02, have it linked to from [here](https://docs.microsoft.com/en-us/aspnet/index#pivot=aspnet&panel=aspnet_tutorials)

**Comment by tdykstra** [comment]
Oh, I missed that this is ASP.NET classic.  Sourabh's suggestion is good, but we should also put it in the ASP.NET classic TOC.  

Right now we have a deployment TOC node only here:  
https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/ 

Ideally we would add this link not only there but also create new nodes at /aspnet/mvc/deployment and /aspnet/web-api/deployment, then add this and other deployment links as appropriate in those new nodes.
