### ISSUE TITLE
Update Publish to IIS doc to react to VS2017 updates and IIS publishing tool changes

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2682]
The publishing experience for ASP.NET Core apps in VS2017 has changed quite a bit. You can now publish directly to IIS using web deploy.

The IIS publishing tool has also gone away and web.config generation is now handled as part of the web sdk.

**Comment by GuardRex** [comment]
I was waiting on *the word* to start working on those sections.

Some info is there for Web Deploy, but I'm not very happy with it. It was something we temporarily dropped in there from another doc, and I merely moved the content over (e.g., the only screenshot shows importing a pub profile :cry:).

@tdykstra When do you want me to do the updates on the doc?

**Comment by tdykstra** [comment]
@danroth27 correct me if I'm wrong, but I would say go ahead and start now, working in the csproj branch so the changes will go to master along with the project.json-->csproj changes.

**Comment by GuardRex** [comment]
:+1: ... and as for the PJ-based samples that we did for the new middleware docs, I'll open PR's to update those on the csproj branch as well if that's ok.

**Comment by tdykstra** [comment]
That sounds good except I'd stick with 1.1 rather than 2.0 for now.

**Comment by GuardRex** [comment]
![marcellus](https://cloud.githubusercontent.com/assets/1622880/22715327/04a16f6e-ed56-11e6-84f7-97b00e9e9d05.jpg)
*You ain't got no problem, @tdykstra. I'm on the mother.* - Marsellus Wallace (Ving Rhames), *Pulp Fiction*, 1994

**Comment by GuardRex** [comment]
This is partially addressed by https://github.com/aspnet/Docs/pull/2708.

I'll constrain my updates to the *Publishing to IIS* doc parts dealing with Web Deploy. I'm working on this first thing in the morning along with middleware samples that need MSBuild/`csproj` :heart: (Response Caching Middleware, URL Rewriting Middleware, and Response Compression Middleware). I'll PR into the `csproj` branch. I'll also confirm the bits in the Key Vault Config Provider sample are working (that PR is still open).

**Comment by GuardRex** [comment]
@tdykstra @Rick-Anderson Everything is done except for the Web Deploy upgrade for the *Publishing to IIS* doc.

I'm a bit concerned about working with such an old version of the doc on the `csproj` branch. We have basic guidance in the current doc for Web Deploy. We merged the content over recently from the dedicated VS with Web Deploy doc which went away. It's just not as good as I'd like it to be.

If you think we could wait until after the dust settles for `csproj` going into `master`, I suggest allowing me to work on upgrading the Web Deploy bits after the merge. If that's ok, you can leave this issue open, and I'll tag it on the PR when the time comes to get that done.

**Comment by tdykstra** [comment]
The version of the doc in csproj should be current soon, as we're going to be rebasing csproj on master weekly. But it's OK to wait until csproj merges to take on the Web Deploy changes.

**Comment by GuardRex** [comment]
Perfect. I'll jump right on it as soon as it merges.
