### ISSUE TITLE
Cannot resolve symbol 'Address.AddressLine1` error in Visual Studio from sample code for Working with forms section

### ISSUE THREAD

**Issue by kimbaudi** [aspnet/Docs#2687]
In the sample code for **Working with forms** section <https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/views/working-with-forms/sample/final>, there is `RegisterAddressViewModel` which has a `AddressViewModel` property:

```csharp
    public class RegisterAddressViewModel
    {
        public string Email { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }

        public AddressViewModel Address { get; set; }
    }

    public class AddressViewModel
    {
        public string AddressLine1 { get; set; }
    }
```

On Visual Studio, the corresponding view `RegisterAddress.cshtml` indicates an error that it `Cannot resolve symbol 'Address.AddressLine1'`

![Cannot resolve symbol error](https://cloud.githubusercontent.com/assets/1864092/22716080/e4647a46-ed48-11e6-8165-3265b4bcb1b8.png)

When debugging, `AddressViewModel.Address1` binds correctly so it is working. But Visual Studio shows it as an error.

**Comment by cpear** [comment]
Its probably resharper. Try disabling it.

**Comment by kimbaudi** [comment]
Yup, you're right!
