### ISSUE TITLE
aspnetcore/mvc/views/dependency-injection/sample/src/ViewInjectSample/Project_Readme.html

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2689]

**Comment by Rick-Anderson** [comment]
@tdykstra  what's the issue here?

**Comment by tdykstra** [comment]
See the file at 

https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/dependency-injection/sample/src/ViewInjectSample/Project_Readme.html

It's out of date in places and in particular mentions project.json.

**Comment by Rick-Anderson** [comment]
So why not delete that file? It never should **not** have been checked in. I added it the *.gitignore* so it won't be checked in again. It's boilerplate template code.

**Comment by Rick-Anderson** [comment]
Our primary concern is the published documents.
