### ISSUE TITLE
Updating the Docker instructions when installing ASP.NET on Linux

### ISSUE THREAD

**Issue by mattcan** [aspnet/Docs#269]
The docs I am speaking of: http://docs.asp.net/en/latest/getting-started/installing-on-linux.html#using-docker

The documentation for installing on Linux is great but the link to a blog post for getting a Docker environment setup is now outdated as it refers to **k** and **kvm**. It might make sense to transition most of the information into the ASP.NET documentation instead of having the blog updated.

I'm not sure if issue #108 will solve this but if not, I am happy to write up the updates as I just went through the process.

**Comment by Rick-Anderson** [comment]
@mattcan if you could help that would be great. You can either submit a PR or contact me with the updates.

**Comment by danroth27** [comment]
I think #108 is a separate topic, so a PR for this issue would be great. Totally agree that the blog post is way out of date. @glennc  May also have thoughts on how we should document this.

**Comment by glennc** [comment]
I've always wanted something better than just the blog post to document how to get going with Docker and ASP.NET 5. If you get started on this I will help out, even if just with reviewing and such.

**Comment by mattcan** [comment]
Alright, I will definitely dig into it again. I should have something up by the 18th. Thanks!
