### ISSUE TITLE
Eliminate separate .gitignore in the aspnet folder

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2694]
An empty .gitignore file was placed in the aspnet folder to deal with problems that were caused by the main .gitignore file.  It would be better to determine the cause of the problem and  
update the main .gitignore accordingly.

@neusamir Do you recall the specific errors that prompted creating an empty .gitignore file?

**Comment by neusamir** [comment]
I don't recall the specifics but we can remove that file and see what happens.

**Comment by tdykstra** [comment]
@Rick-Anderson If you agree with Samir's proposal, I'll go ahead and remove the aspnet/.gitignore.

**Comment by Rick-Anderson** [comment]
@tdykstra  remove
