### ISSUE TITLE
Document how to setup windows authentication in ASP.NET Core

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2711]
I had someone point out to me today that we don't currently cover setting up Windows authentication anywhere in our docs.

[Edit Rick] [@]Tratcher  is contact when ready to start to review outline.

**Comment by danroth27** [comment]
Proposed outline:
- Brief overview of what Integrated Windows Authentication is
  - Clarify that it only works on Windows
- Enabling Windows Authentication via IIS
  - Show creating a new ASP.NET Core app that uses Windows Authentication from Visual Studio using the built-in auth config tooling for new projects
  - Reference [Publish to IIS]() doc for setting up ASP.NET Core to run behind IIS
  - Reference https://www.iis.net/configreference/system.webserver/security/authentication/windowsauthentication for more detailed documentation for setting up Windows Authentication with IIS
- Enabling Windows Authentication via WebListener
  - Note that Kestrel does not support Windows Authentication directly. For self-hosted scenarios you can use WebListener instead.
  - Set the authentication scheme to Windows in the WebListener options (note that AllowAnonymous is true by default):

    ```c#
    var host = new WebHostBuilder()
        ...
        .UseWebListener(options =>
        {
            options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.Negotiate | AuthenticationSchemes.Ntlm;
            options.ListenerSettings.Authentication.AllowAnonymous = false; 
        })
        .Build();
    ```

**Comment by GuardRex** [comment]
New versions of the ANCM will [default (aspnet/AspNetCoreModule #53)](https://github.com/aspnet/AspNetCoreModule/issues/53) `forwardWindowsAuthToken = true` ... Why do I have a sneaky feeling tho that if it isn't called out that devs will run amok? An old `web.config` lying around in the app that has it set to `false` is a ticking :bomb:.

**Comment by Rick-Anderson** [comment]
@Tratcher  please review/revise and approve outline.
@ardalis  can you take this one?

**Comment by ardalis** [comment]
@Rick-Anderson yes

**Comment by Tratcher** [comment]
Yes, that's a good start.

Be careful to take any WebListener code samples from the right branch / released bits. The auth settings themselves haven't changed in dev, but the settings object has.
