### ISSUE TITLE
We need to document writing a custom model binder

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#2717]
This is a common ask, and we don't have it

**Comment by Rick-Anderson** [comment]
@rynowak  any chance you could write it? Our model bind docs are in bad shape.

**Comment by ardalis** [comment]
If not, I can take a stab at it, with @rynowak 's help. That's more in my comfort zone than some of the security stuff I'm working on these days.

**Comment by rynowak** [comment]
The more tricky part is coming up with an example that we actually like 😆 Maybe using model binding to fetch a model from the database?

**Comment by ardalis** [comment]
That seems ugly - maybe the model binder can accept something base64 encoded and decode it?

**Comment by rynowak** [comment]
That's a good idea... so good that we already have it https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/ByteArrayModelBinder.cs

The database one is something we'd have customer requests for and we can't put it in the box due to layering issues.

**Comment by ardalis** [comment]
Doh! Ok, I can certainly do one that hooks into the database, but I'm not a fan of that (architecturally)...

**Comment by Rick-Anderson** [comment]
What about the EF in-memory DB and using a view model?

**Comment by Rick-Anderson** [comment]
dup of #1681
