### ISSUE TITLE
convert aspnetcore/fundamentals/localization/ from project.json to csproj

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2722]
sample/Resources/Views/Book/Index.resx 
Also other language .resx files
sample/Views/

**Comment by Rick-Anderson** [comment]
@hishamco would you be able to convert the code from _project.json_ to _.csproj_ ? We're working out of the _new-csproj_ branch. It might be easier to start after we rebase with master (so we have the changes you made today).

**Comment by Rick-Anderson** [comment]
@hishamco actually it's just a matter of remove _project.json_  from the resource files - so that would should be done in master. I'll do it and if I have any problems I'll ping you.

**Comment by Rick-Anderson** [comment]
PR #2723 fixes this

**Comment by hishamco** [comment]
Sorry I was working on something else when you ping me
