### ISSUE TITLE
csproj conversion aspnetcore/tutorials/your-first-mac-aspnet.md

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2726]
[Your First ASP.NET Core Application on a Mac Using Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet)
This upgrade requires a total rewrite.

-  Replace Yeoman with dotnet
- make it work with Linux

**Comment by Rick-Anderson** [comment]
@spboyer  can we trade a couple .Net Core conversion issues for this one?

**Comment by spboyer** [comment]
I will be taking care of the xplat items. If there are some .NET Conversion items you want to look at, please assign them to me.

**Comment by Rick-Anderson** [comment]
@spboyer  this is for csproj conversion.
