### ISSUE TITLE
Entity Framework Core - ASP.NET -Working WITH DBA's

### ISSUE THREAD

**Issue by robertparis** [aspnet/Docs#2737]
Tom,
How to use migrations in the work environment where the DBA's control the database and we have to adapt our code to the changes they produce?

Previewing Microsoft/Docs/ASP​.NET/ASP​.NET Core which demonstrates how to create ASP.NET Core 1.0 MVC web applications using Entity Framework Core 1.0 and Visual Studio.

The Docs make a lot about using migrations and specifically 

> When you develop a new application, your data model changes frequently, and each time the model changes, it gets out of sync with the database. You started these tutorials by configuring the Entity Framework to create the database if it doesn't exist.

Which is good IF you are developing by yourself. Rapid prototyping, the examples work.

In the work environment, you have DBA's, a normalized relational database and coworkers. Examples that show how to use the Entity Framework in that environment are more worthwhile would be appreciated. 

**Robert_Paris1  That's a good point.  The migrations feature includes commands that create SQL scripts that you can give to a DBA, but we don't have docs for that yet.  You can request new documentation by creating an issue in the documentation repository -- https://github.com/aspnet/Docs/issues/new**

**Comment by Rick-Anderson** [comment]
@robertparis  this would go in https://github.com/aspnet/EntityFramework.Docs, not here.
