### ISSUE TITLE
aspnetcore/publishing/web-publishing-vs.md

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2741]
[How web publishing in Visual Studio works](https://docs.microsoft.com/en-us/aspnet/core/publishing/web-publishing-vs)

**Comment by Rick-Anderson** [comment]
@sayedihashimi would you be able to update this for msbuild/.csproj?

**Comment by Rick-Anderson** [comment]
@sayedihashimi  listed below are all the *project.json* - can you let us know how these should be changed for *.csproj*/msbuild?

>In ASP.NET Core the publish process has been simplified, we no longer store a reference to files that the project contains. All files are included in the project by default (files can be excluded from the project or from publish by updating **project.json**). 

>The dotnet publish command will inspect **project.json** and the project folder to determine the files which need to be published. 

As stated previously `dotnet publish` is a command-line utility that can be used to help publish your ASP.NET Core application. This is a cross platform command-line
    utility (that is, you can use it on Windows, Mac or Linux) and does not require Visual Studio. If you are working on a team in which some developers are not using
    Visual Studio, then you may want to script building and publishing. When dotnet publish is executed it can be configured to execute custom commands before or after
    execution. The commands will be listed in project.json in the scripts section. The supported scripts for publish are prepublish and postpublish. The ASP.NET Core Web Application template uses the prepublish step by default. The relevant snippet
    from *project.json* is shown below.
    
    ```javascript
    "scripts": {
      "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ]
    }  ```
    
    
    `Here multiple comma separated calls are declared.`
    
    When Visual Studio is used the prepublish and postpublish steps are executed as a part of the call to `dotnet publish`. The postpublish script from *project.json* is
    executed before the files are published to the remote destination because that takes place immediately after `dotnet publish` completes.  In the next step we cover
    customizing the PowerShell script to control what happens to the files after they reach the target destination.

**Comment by sayedihashimi** [comment]
@Rick-Anderson basically the entire doc needs to be rewritten. How should we proceed? I can probably draft a new write up, but that may take me a few days. If you have bandwidth we can meet and I can go over the changes with you and then go from there.

**Comment by Rick-Anderson** [comment]
@sayedihashimi  can you draft up a new article (word is fine), I'll review it ping you if I have any questions.
