### ISSUE TITLE
aspnetcore/client-side/yeoman.md msbuild conversion

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2747]
[Building projects with Yeoman](https://docs.microsoft.com/en-us/aspnet/core/client-side/yeoman)

**Comment by Rick-Anderson** [comment]
@danroth27  can we delete this in the csproj branch? cc @spboyer

**Comment by Rick-Anderson** [comment]
@scottaddie @danroth27  should this be deleted  or migrated to msbuild? cc @spboyer

**Comment by spboyer** [comment]
The generators are currently in the process of being updated to support the RC4 templates, once that is complete the article can be updated. At this point that's a blocker. We should not delete it.

There are plans to change the yeoman generator to use the same template system as dotnet new, giving those developers who like yo the choice to still use it. 

cc:/ @sayedihashimi

**Comment by spboyer** [comment]
Updates are complete for csproj. Article can be updated

**Comment by spboyer** [comment]
@Rick-Anderson - There are no code assets to this article.  However, there is an edit that needs to be done for screen shots and content that I will do.
