### ISSUE TITLE
2.0 Document PasswordOptions.RequiredUniqueChars

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Docs#2748]
New feature that lets a user require a minimum number of unique chars in a password. See issue linked for context.
 
https://github.com/aspnet/Identity/pull/1100

**Comment by Rick-Anderson** [comment]
@sebastienros  is that a 1.1 feature?

**Comment by Rick-Anderson** [comment]
[Account confirmation and password recovery](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm)  2.0 feature, nice to have for summer when 2.0 RTWs.
