### ISSUE TITLE
aspnetcore/client-side/using-gulp.md to msbuild

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2749]
[Using Gulp in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp)

**Comment by Rick-Anderson** [comment]
@scottaddie @danroth27 should this be deleted or migrated to msbuild? cc @spboyer

**Comment by scottaddie** [comment]
@Rick-Anderson I vote for migrating to MSBuild, since Gulp is still very relevant in ASP.NET Core projects.

**Comment by Rick-Anderson** [comment]
@scottaddie  thanks, I'll start migrating. I'll ping you *when* I get stuck.
