### ISSUE TITLE
Upgrade "View components" doc samples to csproj/MSBuild with VS 2017

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#2756]
The [View components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components) doc uses `project.json` and `*.xproj` for VS 2015. The sample code should be updated to reflect using VS 2017.

@Rick-Anderson Is anyone working on this? If not, I'll take care of it.

**Comment by Rick-Anderson** [comment]
@scottaddie  that would be great, thanks.
