### ISSUE TITLE
How to use DNVM DNX with VS15 never explained

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#276]
http://docs.asp.net/en/latest/mvc/views/view-components.html#run-ef-migrations shows how to use dnx - but this belongs in http://docs.asp.net/en/latest/getting-started/installing-on-windows.html  - installing on windows shouldn't assume you install VS15 and that's it - even with VS15 installed, you sometimes need dnx as my VC tutorial points out.

**Comment by ardalis** [comment]
Looks like this has been fixed (perhaps by Rick)
