### ISSUE TITLE
DNVM, DNX, and DNU - Understanding the ASP.NET 5 Runtime Options

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#278]
port over  http://typecastexception.com/post/2015/05/17/DNVM-DNX-and-DNU-Understanding-the-ASPNET-5-Runtime-Options.aspx - I'll work with John Atten. 
@danroth27 let me know where you want this information then assign to me.

**Comment by danroth27** [comment]
Since we are moving away from DNX onto the .NET CLI this documentation will no longer be needed.
