### ISSUE TITLE
New doc: What's new in ASP.NET Core 1.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2786]
Create new topic "What's new in ASP.NET Core 1.1" List new features and link to doc on the 1.1 feature. 

- [.NET Core Support Lifecycle](https://www.microsoft.com/net/core/support) and it's relationship to ASP.NET Core (they're the same - right).
- [URL Rewriting Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting)
- [Response Caching Middleware](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware)
- [WebListener Server for Windows](https://docs.microsoft.com/aspnet/core/fundamentals/servers/weblistener)
- View Components as Tag Helpers #1757
- Middleware as MVC filters link to [Using middleware in the filter pipeline](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters)
- [Cookie-based TempData provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state)
- [Azure App Service logging provider](https://docs.microsoft.com/aspnet/core/fundamentals/logging#appservice)
- [Azure Key Vault configuration provider](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration)
- [Redis and Azure Storage Data Protection Key Repositories](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers)
- WebSockets #2789 #204 

Should this go in the Migrations folder? If not, where?

[Internal bug](https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=377630)  - cross ref #2260

**Comment by Rick-Anderson** [comment]
@tdykstra @GuardRex  please review, looks like we missed "WebListener Server for Windows",  "Azure App Service logging provider" and WebSockets

**Comment by tdykstra** [comment]
@Rick-Anderson We didn't miss WebListener (new doc in Fundamentals/Servers) or App Service logging provider (new section in Fundamentals/Logging), only WebSockets.

**Comment by GuardRex** [comment]
Cross-ref: https://github.com/aspnet/Docs/issues/2260

Note that your https://github.com/aspnet/Docs/issues/2787 is a dup of https://github.com/aspnet/Docs/issues/1757

**Comment by Andrew-MSFT** [comment]
I would recommend there be a "help me choose between 1.0 and 1.1" sentence or two, probably tied to the "Support lifecycle" section

**Comment by Rick-Anderson** [comment]
fixed by #2799
