### ISSUE TITLE
doc WebSockets for 1.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2789]
see https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/

- [x ] Short term, add to What's new in ASP.NET Core 1.1 #2786
- [ ] Long term, create an independent doc

**Comment by Rick-Anderson** [comment]
@tdykstra  this got missed. Can you do this one?

**Comment by tdykstra** [comment]
@Rick-Anderson What's the priority compared to csproj work?

**Comment by Rick-Anderson** [comment]
@tdykstra  this is higher. We just need a copy of the announcement for now.

**Comment by tdykstra** [comment]
Duplicate of #204
