### ISSUE TITLE
Publishing to Azure App Service

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#2800]
[Azure Integration](https://github.com/aspnet/AzureIntegration) seems lightly covered. It's only covered in a Note in the Fundamentals/Logging doc.

The existing docs cover quite a bit of ground on CI, Git, VS, EF, and SQL Database. They don't touch on [Azure Integration](https://github.com/aspnet/AzureIntegration) or mention the Azure App Service logging provider. The landing page for Azure Apps could provide brief overview and helpful links.

### Outline
* Introduction
  * Describe the Azure App Service
  * Suggest reading the *Publishing to IIS* doc
  * Link the *How App Service works* doc - https://docs.microsoft.com/azure/app-service/app-service-how-works-readme
* Create/deploy to Azure Apps: Link to our existing tutorials. TAL at [Deploy your app to Azure App Service](https://docs.microsoft.com/azure/app-service-web/web-sites-deploy), too.
* Application configuration
  * `Microsoft.AspNetCore.AzureAppServicesIntegration` package. See [Implement azure app services lightup package](https://github.com/aspnet/AzureIntegration/issues/9).
  * `.UseAzureAppServices()` covers `AddAzureWebAppDiagnostics()`, which provides the logging providers for light up logging features in Azure Apps.
* Merely list the monitoring and logging options. Link to the troubleshooting topic and the common errors topic.
* Note that the DP key ring doesn't follow the app when deployment slots are swapped - https://github.com/aspnet/Docs/pull/2340
* Additional resources

**Comment by Rick-Anderson** [comment]
@GuardRex great outline. This probably belongs in the Azure doc set.  We can look at this after VS17 RTMs.

Most of this info is scattered around.

**Comment by GuardRex** [comment]
> belongs in the Azure doc set

If that turns out to be the best spot and the other two docs remain here, then I would suggest a cross link to it at the tops of those docs. What I'm outlining here is a more introductory-level "how to get on Azure Apps with an ASP.NET Core app" than the two that exist today, which might be complicated for a newbie to Azure Apps ... they certainly have a lot more in them than you need to know.
