### ISSUE TITLE
Make a doc for the LoggerMessage.DefineScope pattern

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Docs#2810]
We should document the low allocation logging pattern that uses `LoggerMessage.DefineScope` and `LoggerMessage.Define` as seen here https://github.com/aspnet/KestrelHttpServer/blob/b41c4078bdbbf2b2413fe13922a64552ed1177b6/src/Microsoft.AspNetCore.Server.Kestrel/Internal/Infrastructure/KestrelTrace.cs and https://github.com/aspnet/Mvc/blob/624909763bf762c4448955d00eef1649737df8d6/src/Microsoft.AspNetCore.Mvc.Razor/Internal/MvcRazorLoggerExtensions.cs

**Comment by glennc** [comment]
I think some guidance around the implications of mixing something like string interpolation and formatters will be useful to add as well.

**Comment by guardrex** [comment]
@Rick-Anderson 
* Would you like this as a sub-topic to *fundamentals/logging.md* in the TOC?
* Title? :racing_car: *High-performance logging with LoggerMessage in ASP.NET Core* :racing_car:

**Comment by Rick-Anderson** [comment]
@guardrex  sounds good. cc @scottaddie

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie Proposal for this topic ...

Title: *High-performance logging with LoggerMessage in ASP.NET Core*
TOC: sub-topic to *fundamentals/logging.md*

#### Outline

* Introduction
   * `LoggerMessage` feature description (1-2 sentences)
   * Sample link
* Describe `LoggerMessage.Define` and `LoggerMessage.DefineScope`
* Illustrate `LoggerMessage.Define` using the sample
* Illustrate `LoggerMessage.DefineScope` using the sample

**Comment by Rick-Anderson** [comment]
@BrennanConroy  @glennc  can you review the outline? LGTM.

**Comment by BrennanConroy** [comment]
👍

**Comment by guardrex** [comment]
@glennc @BrennanConroy Need a head-check on scopes config behavior:

1. I setup scopes, which I hadn't used before, so I didn't know what to expect for configuration.
2. I have `IncludeScopes` set to `true` in *appsettings* files.
3. I see that the logging config is handled by `WebHost`'s `CreateDefaultBuilder`: https://github.com/aspnet/MetaPackages/blob/dev/src/Microsoft.AspNetCore/WebHost.cs#L178
   ```csharp
   logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
   ```
   ... but I do note on the next line that the `AddConsole` option *is not set*:
   ```csharp
   logging.AddConsole();
   ```

Scopes aren't active unless I explicitly set ...

```csharp
.ConfigureLogging((hostingContext, logging) =>
{
    logging.AddConsole(options => options.IncludeScopes = true);
})
```

Is the *appsettings* value only honored when the `IncludeScopes` option is enabled in `ConfigureLogging` `AddConsole`?

If so, the Logging topic only implies that this is the case ...

> The following code enables scopes for the console provider

... so I think we'll need to make that explicit in the Logging topic: *You must set the option for the bits to work.* cc/ @Rick-Anderson @scottaddie

**Comment by BrennanConroy** [comment]
I believe `IncludeScopes` isn't working from configuration files in 2.0.0, but has been fixed in latest dev. Although it now lives under the specific logger, so your last example should work in 2.1.0-*

**Comment by guardrex** [comment]
@BrennanConroy Thanks. I'll make a small modification to the Logging topic to compensate for the time being. The current language doesn't call it out clearly.

@scottaddie @Rick-Anderson I'll add the update for the Logging topic to the `LoggerMessage` PR, which should be up soon. The sample is almost finished, and the topic is a one-day write-up. Should have it Tuesday ... Wednesday at the latest.
