### ISSUE TITLE
project.json to .csproj -- aspnetcore/client-side/less-sass-fa.md

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2827]

**Comment by tdykstra** [comment]
@spboyer @scottaddie This doc uses a ref to project.json to get the webroot folder path:

![less-sass-fa](https://cloud.githubusercontent.com/assets/1569635/23283636/ece9dfd6-f9db-11e6-9b09-1a650e18f109.png)

Same thing in the 2fa sample project.

In other sample app gulpfiles I see the path hardcoded:

var webroot = "./wwwroot/";

Any reason not to replace project.webroot with hardcoded webroot here as is done elsewhere?

**Comment by scottaddie** [comment]
I cannot think of a reason why you wouldn't just hardcode this value, especially since it's not a value that gets used over and over in this example.

**Comment by spboyer** [comment]
See the bundleconfig.json file. We are using the hard path there. 

```javascript
{
    "outputFileName": "wwwroot/css/site.min.css",
    // An array of relative input file paths. Globbing patterns supported
    "inputFiles": [
      "wwwroot/css/site.css"
    ]
  },
```

**Comment by spboyer** [comment]
Closing #2835 fixed.
