### ISSUE TITLE
[New document concept] ASP.NET OSS Developer Projects

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#2828]
On the [2/21 Standup (23:14)](https://www.youtube.com/watch?v=rIYP-9RWLiA#t=23m14s), [@]jongalloway shows two lists of OSS .NET tools, frameworks, libraries, and software:
* [Awesome .NET (quozd/awesome-dotnet)](https://github.com/quozd/awesome-dotnet)
* [.NET Open Source Developer Projects (dotnet/dotnet-developer-projects.md)](https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md)

Jon called these lists a **"treasure trove of neat open source .NET stuff."** It would be great if something like this (or a subset of the links specifically relevant to ASP.NET Core) was incorporated as a reference doc into the ASP.NET Core docs to help devs discover and navigate all of the wonderful ancillary technologies for .NET.

There's also:
* [.NET Open Source Consumer Projects (dotnet/dotnet-consumer-projects.md)](https://github.com/Microsoft/dotnet/blob/master/dotnet-consumer-projects.md)
* [Free Services & Tools for Open Source .NET Projects (dotnet/dotnet-free-oss-services.md)](https://github.com/Microsoft/dotnet/blob/master/dotnet-free-oss-services.md)

If you like the concept (at least the concept of having portions of these lists dealing with ASP.NET-related OSS content in a doc), I hope it isn't too presumptuous of me to suggest asking Vitali Fokin ([@]quozd) if he would like to author such a doc.

If you prefer I move the entire issue over to `dotnet/docs`, I'll move it over there. As usual if this falls under the *GooberRex*:tm: series of goofy ideas, feel free to close. :grin:

**Comment by spboyer** [comment]
Maybe a better place for this is off the http://dot.net under the [community page](https://www.microsoft.com/net/community)?

cc: / @shanselman @jongalloway

**Comment by GuardRex** [comment]
I'm just concerned about its discoverability. The doc(s) could put anywhere and get a mention and link in a blurb at the end of the [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/) doc, or there could be a doc at the very bottom of the TOC ... just above *API Reference*.

This stuff is so hot, I think all devs should know it exists.

**Comment by Rick-Anderson** [comment]
@dend please review

**Comment by dend** [comment]
@Rick-Anderson @GuardRex @spboyer I am all for making these part of the documentation, but not sure if it deserves a super-special treatment.

**Comment by guardrex** [comment]
@tdykstra @Rick-Anderson @jongalloway 

[Awesome .NET!](https://github.com/quozd/awesome-dotnet) and [.NET Open Source Developer Projects](https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md) are well maintained. How about just linking these as the last two links in the *Next steps* section of https://docs.microsoft.com/en-us/aspnet/core/? Let me know, and I'll 🤜 knock it out 🤛.

**Comment by guardrex** [comment]
@Rick-Anderson There's no movement here ... shouldn't we just close this?
