### ISSUE TITLE
aspnetcore module fails to launch dotnet exe

### ISSUE THREAD

**Issue by fasigpt** [aspnet/Docs#2830]
In this article https://docs.microsoft.com/en-us/aspnet/core/tutorials/nano-server
 we are trying to install .net core to $InstallRoot = "$env:LocalAppData\Microsoft\dotnet" which will lead to 502.5 Process Start Failures. Unfortunately, in this scenario both stdout and event logs are having empty messages

Get-WinEvent -FilterHashTable @{LogName='Application'; Level=2; St
artTime=$StartTime} |format-table -autosize
   ProviderName: IIS AspNetCore ModuleTimeCreated             Id LevelDisplayName Message
-----------             -- ---------------- -------
2/24/2017 11:37:50 AM 1000
2/24/2017 11:37:50 AM 1000

So, its very hard to debug why this is failing. The article https://docs.microsoft.com/en-us/aspnet/core/publishing/iis talks about one scenario where we need to make sure appPool account has access to dotnet core install folder. In my case though the appPool was under Local System Account and it for some reason failed to access $env:LocalAppData\Microsoft\dotnet

I think, we should install the runtime to c:\program files\microsoft\dotnet

The script should be changed accordingly.

**Comment by Rick-Anderson** [comment]
@fasigpt  this doesn't seem to be a documentation issue.  You might try posting this to [SO](http://stackoverflow.com/).
