### ISSUE TITLE
Docs say Ubuntu 14.04 uses systemd

### ISSUE THREAD

**Issue by zanedo** [aspnet/Docs#2839]
The docs here: https://github.com/aspnet/Docs/blob/master/aspnetcore/publishing/linuxproduction.md

Say to set the service up in systemd but Ubuntu 14.04 doesn't use systemd, it uses init.d.

Is there an example using init script?

**Comment by spboyer** [comment]
That is correct, The document should be updated to reflect 16.04. `systemd` is available as of Ubuntu 15.10.  For Ubuntu 14.04, you should use supervisord, the version of the document [here](https://github.com/aspnet/Docs/blob/e9c1419175c4dd7e152df3746ba1df5935aaafd5/aspnetcore/publishing/linuxproduction.md) has that information on that practice.
