### ISSUE TITLE
Update "Razor syntax" doc to CSPROJ

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#2843]
The ["View compilation"](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor#view-compilation) section of the MVC **Razor syntax** doc still references `project.json`. Is anyone working on updating this? If not, I'll take care of it.
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
I updated it in the CSPROJ branch:

## View compilation

Razor views are compiled at runtime when the view is invoked. ASP.NET Core 1.1.0 and higher can optionally compile Razor views and deploy them with the app. To do this set `MvcRazorCompileOnPublish` to true and include a package reference to `Microsoft.AspNetCore.Mvc.Razor.ViewCompilation`. The following *.csproj* sample highlights these settings:

[!code-html[Main](razor\sample\MvcRazorCompileOnPublish.csproj?highlight=4,15)]
