### ISSUE TITLE
Describe language fallback behavior

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Docs#2846]
The [localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) docs don't mention how we do language fallback for resources, we might want to include a short blurb about that behavior.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you send me a paragraph on that and I'll get it added.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg can you send me a paragraph on that and I'll get it added.
