### ISSUE TITLE
Search for Instuctor Controller

### ISSUE THREAD

**Issue by kirspas23** [aspnet/Docs#2851]
Hi, I tried to create an account to comment on the Microsoft Docs page but it wouldn't work even with my Microsoft Account. I attached what I wanted to say:

Really fantastic tutorial! I started to play around with the content and lessons to better understand. 

How would you implement search functionality with the Instructor model and controller? Searching for an Instructor name in a large list. Since the Instructor is using a ViewModel, it is not an IQueryable<T> like Students is. It also means you cannot use the PaginationList class.

I just made an if/else statement with 2 different eager loads with one having a where clause of the searchString. This seems like a bad practice as it can become complex and repeats itself.

**Comment by Rick-Anderson** [comment]
@kirspas23  this is for issues with documents. I suggest you post this question to SO or leave the question on LiveFyre.
