### ISSUE TITLE
Show how to get it working with VueJS

### ISSUE THREAD

**Issue by murbanowicz** [aspnet/Docs#2856]
VueJS is already one of big players so it should be definitely included in docs how to set it up with ASP.NET core

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/JavaScriptServices/issues/524

**Comment by MarkPieszak** [comment]
@Rick-Anderson Demo of it here: https://github.com/MarkPieszak/aspnetcore-Vue-starter
