### ISSUE TITLE
Call out local testing on 502.5 exceptions in IIS troubleshooting

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#2858]
Talking to @conkman on Slack ...

We speak to running an app locally in the lead-in to the *Common Errors* section; however, that can get lost in the mix when trying to tease out why a 502.5 is occurring on the server.

I'd like to add a bullet point to the 502.5 errors in the list that explicitly calls attention to checking the app locally (it should be the first bullet in each list imo). When it crashes locally, the dev should look within the app (at least initially) for their process crashing problem. It's when it runs locally but 502.5's on the server that they can consider the other errors we show as the possible culprit.

@Rick-Anderson @tdykstra Ok to put that PR this afternoon??? lol ... They told me not to do a damn thing until Monday. lol

Thanks to @conkman for flagging this problem.

**Comment by Rick-Anderson** [comment]
@GuardRex  I think it's OK if this is not part of your assigned work. If for some reason it is your assigned work you can can comp time.

**Comment by GuardRex** [comment]
Cool ... I gotta get something in ... I see the PR's buzzing by and feel so left out of the fun. :cry:
