### ISSUE TITLE
Accessing appsettings.json of class library project from Asp.NetCore project

### ISSUE THREAD

**Issue by bilalarshad** [aspnet/Docs#2865]
There are two projects Asp.NetCore and .NetCore class library. I want to access appsettings.json from class library project inside Asp.NetCore project. 

What I tried 
- Add it to build options and set copyToOutputDirectory, But it place appsettings.json inside [debug/release]\[ProjectName]\appsettings.json but I want it to be on path [debug/release]\appsettings.json.

Kindly suggest me a workaround or a better solution to achieve this requirement using .NetCore.
Thanks

**Comment by GuardRex** [comment]
@bilalarshad Hello - This repo is just for docs. Close here and open your issue over in https://github.com/dotnet/sdk/issues. However, keep in mind that they're working actively with MSBuild/`csproj` over there, so they might be inclined to answer you with an MSBuild/`csproj` approach. :wink:

**Comment by bilalarshad** [comment]
Fixed it 👍
