### ISSUE TITLE
Feedback on environments.rst

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#290]
@ardalis How/Why would you use a web profile? (or provide a link). 
What's the purpose of launchSettings.json? Is that how IIS Express reads env variables?
IHostingEnvironment  on first occurrence should be a link.
When the application is run with ASPNET_ENV set to Staging, this Startup class is used
Should be
When the application is run with ASPNET_ENV set to Staging, the StartupStaging class is used
Also note that if no environment is set
Should be
Also note that if ASPNET_ENV  is not set

public class StartupStaging
{
   public async void Configure(IApplicationBuilder app)
   {
This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-

blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

Please remove () from method names. That is The Configure() and ConfigureServices() methods  should be 
The Configure and ConfigureServices methods.

We never use e.g. - please use "for example"

**Comment by Rick-Anderson** [comment]
@ardalis  Can you close this once these are addressed?

**Comment by ardalis** [comment]
Added link to Servers to learn more about debug profiles.
Clarified launchSettings.
Clarified StartupStaging class is used.
Disagree re: if no environment is set, especially given there are currently multiple ways to set the environment (ASPNET_ENV, Hosting:Environment).
Removed async from StartupStaging Configure method to fix warning.
Removed () from method names.
Replaced e.g. with for example.
Updated samples to RC1.
