### ISSUE TITLE
Not readable diagrams on "Lifecycle of an ASP.NET MVC 5 Application" page

### ISSUE THREAD

**Issue by maroonedsia** [aspnet/Docs#2905]
Hi,

The diagrams on "Lifecycle of an ASP.NET MVC 5 Application" page, https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/lifecycle-of-an-aspnet-mvc-5-application , are not readable at all. I thought they should be thumbnails, but they are not links to bigger readable images either. 

I think these 2 diagrams are the most important pieces of the page and they should be swapped with bigger readable images.

**Comment by maroonedsia** [comment]
I just saw the link to the PDF file on top of the page that contains the diagram. So, there is no missing diagram there, but still I think if there are small diagrams on the page, there should be explicit hints on how to see the full size diagrams. Thank you.

**Comment by Rick-Anderson** [comment]
@maroonedsia  great suggestion, thanks. I created #2915 to solve this.
