### ISSUE TITLE
Update content on view compilation

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#2909]
We should document how to precompile your views.
make doc a child of Rendering HTML with views

**Comment by danroth27** [comment]
Don't use wildcard package version - use the stable package:

```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0-*" />
```

Also fix highlighting of the property to the correct line.

**Comment by danroth27** [comment]
We should also probably make this content its own doc with guidance on when to use the feature.

**Comment by Rick-Anderson** [comment]
Mention when you don't want to use pre-compilation
