### ISSUE TITLE
Incorrect last edit date in doc

### ISSUE THREAD

**Issue by YouenZeng** [aspnet/Docs#2918]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state

On my local system,  the head of this document displays as `3/14/2017 10 min to read Contributo...`. But today is `The current date is: ?? 2017/03/08` , 6 days before 2017/03/14.

**Comment by Rick-Anderson** [comment]
That's just a meta data artifact.

**Comment by Rick-Anderson** [comment]
@YouenZeng  thanks, I fixed it.
