### ISSUE TITLE
Create custom 404 page

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#2920]
Create a 404.md file in the root folder of the docset, with links to home page, overview pages, etc.

**Comment by ardalis** [comment]
...and make sure it looks cool. Maybe include the DotNet bot on it: https://github.com/dotnet/swag/blob/master/dotnet-bot/dotnet-bot-pot.png

**Comment by dend** [comment]
At this time, let's not create any custom 404 pages - we are working on a consistent docs experience, and would prefer at this time to not introduce any custom error pages. 

We have it on our radar to improve the 404 experience.
