### ISSUE TITLE
Suggestion for new page in client side development

### ISSUE THREAD

**Issue by damienbod** [aspnet/Docs#2926]
Introduction to using Webpack in ASP.NET Core

I think this would be useful like the gulp, grunt pages.

**Comment by Rick-Anderson** [comment]
@danroth27  do we want this?
@damienbod  would you be interested in writing this? 
[@]SteveSandersonMS  will review outline.

**Comment by damienbod** [comment]
yes, should I start?

**Comment by Rick-Anderson** [comment]
@damienbod  Yes, Post the outline first.

**Comment by damienbod** [comment]
Document Outline:

1 Introducing Webpack
2 Preparing the application
..1. Using Webpack with npm
..2. Using Webpack with yarn
3 Configuring Webpack
..1. Production, Development builds, wwwroot
..2. Modules Typescript
..3. Modules SASS, LESS, CSS, HTML
..4. Chunking
..5. Hot Module Replacement 
..6. Plugins UglifyJsPlugin, CleanWebpackPlugin, HtmlWebpackPlugin, CopyWebpackPlugin
4 Debugging with Webpack

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS @danroth27  please review

**Comment by SteveSandersonMS** [comment]
Regarding this list of topics, do you think they could be phrased in terms of things that are unique to ASP.NET? As it stands, it sounds like general-purpose Webpack docs that could apply to any web application platform.

**Comment by damienbod** [comment]
@SteveSandersonMS 
I did this, because this is how the gulp and grunt docs are written, which I think are done well. I decided to follow the same style. The contents will be ASP.NET Core or Visual Studio specific like the grunt/gulp docs. 

Greetings Damien

**Comment by FabianGosebrink** [comment]
Hey, @damienbod and me just talked about that. 

Maybe the document could fulfill the unique ASP.NET  case in having the app in one folder inside Visual Studio (Code), building it into wwwroot, triggering it with a binding on starting or building the project and starting the production and development build out of Visual Studio.

Would that be worth a document?

Would love to help btw.

Fabian

**Comment by Rick-Anderson** [comment]
>I did this, because this is how the gulp and grunt docs are written, which I think are done well.

Can't we just point to their well written docs? We should just be documenting what's unique to ASP.NET Core.

**Comment by damienbod** [comment]
@Rick-Anderson yes/no, I only want the documentate what you need to do inside Visual Studio to get Webpack working, or specific webpack configurations when working with an ASP.NET Core project, or publishing inside VS with ASP.NET Core or just using Webpack inside VS. 

I was refering to the titles, which are as @SteveSandersonMS pointed out general. The titles are just subtitles. My suggestion for the title is "Introduction to using Webpack in ASP.NET Core" and the subtitles are the document outline. 

Also I was thinking of documentating everything for Visual Studio, didn't think about Visual Studio Code.

?

**Comment by Rick-Anderson** [comment]
@damienbod It would be great to include VS Code.

**Comment by danroth27** [comment]
We do want to start moving the content around [JavaScriptServices](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/), which includes a bunch of webpack related functionality, but we should avoid trying to redocument webpack itself.

**Comment by danroth27** [comment]
We had some proposed outlines in https://github.com/aspnet/Docs/issues/2461 that we should take into account.

**Comment by damienbod** [comment]
@Rick-Anderson @SteveSandersonMS @FabianGosebrink @danroth27 @shanselman 

I would like to start with this, if you want it. I suggest we continue with the document outline, and I will only add Visual Studio, Visual Studio Code, ASP.NET Core content. I will add links to the webpack docs as required. I would create an angular 4 template as a demo (not using JavaScriptServices) and demonstrate how to configure and use within Visual Studio/Visual Studio Code. 

I have be maintaining an angular template for Visual Studio for a while (with @FabianGosebrink and @robisim74 ) and a lot of users seem to have problems setting up and using webpack, npm, yarn, typescript together with Visual Studio, Visual Studio code. I think it would be good that the typical problems be documented here. 

https://github.com/damienbod/AngularWebpackVisualStudio

Greetings Damien

**Comment by Rick-Anderson** [comment]
@damienbod  @FabianGosebrink  @fiyazbinhasan - we need to reconcile this with  **Document using ASP.NET Core with Angular 2**  #2461

**Comment by fiyazbinhasan** [comment]
agree on two separate docs; one which will only focus on using angular 2/4 with aspnet core and another, only focusing on using webpack. @damienbod can start on the webpack doc and in the using angular 2/4 with aspnet core @FabianGosebrink and me can refer to that doc whenever something related to webpack pops up. we wont go explaining stuff related to webpack in that using angular doc. We need a new modified outline for **Document using ASP.NET Core with Angular 2** [#2461](https://github.com/aspnet/Docs/issues/2461)

whats your suggestion @Rick-Anderson ?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
