### ISSUE TITLE
Testing Sample Processor Architecture Warning

### ISSUE THREAD

**Issue by michal-ciechan** [aspnet/Docs#2928]
I have checked out the latest sample from 

`aspnet/Docs/tree/master/aspnetcore/testing/integration-testing/sample` - [Link](https://github.com/aspnet/Docs/tree/master/aspnetcore/testing/integration-testing/sample) 

Upgraded using VS2017, built and get the following warning:

Field | Value
--- | ---
Severity | Warning
Code | MSB3270
Description|There was a mismatch between the processor architecture of the project being built "`MSIL`" and the processor architecture of the reference "`\sample\src\DataTester\bin\Debug\net451\PrimeWeb.exe`", "`x86`".  This mismatch may cause runtime failure.  Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
Project|PrimeWeb.UnitTests
File|C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
Line|1964

![image](https://cloud.githubusercontent.com/assets/5235315/23726160/27d93fa0-044b-11e7-8e29-6a63c35877f5.png)

![image](https://cloud.githubusercontent.com/assets/5235315/23726175/3d52fbaa-044b-11e7-8055-128e1661ea06.png)

![image](https://cloud.githubusercontent.com/assets/5235315/23726186/484e333a-044b-11e7-92a7-823b1ee1a990.png)

Considering everything is `AnyCPU` I don't understand where the `x86` reference is coming from?

Any insight/guide/resources to help investigate this would be useful!

**Comment by Rick-Anderson** [comment]
[Doc link](https://github.com/aspnet/Docs/blob/master/aspnetcore/testing/integration-testing.md)

**Comment by Rick-Anderson** [comment]
@michal-ciechan  thanks for pointing this out.
