### ISSUE TITLE
Request Features

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#293]
ASP.NET 5->Fundamentals->Request Features
- Feature collection and relationship to HttpContext
- Feature collection mutability: added, removed, wrapped and replaced
- Created by servers **and** middleware
    - Servers own creating the collection
    - Middleware adds to the collection using `HttpContext.SetFeature<T>(feature)`
- Consumed by middleware and app code (see `HttpContext.GetFeature<T>()`)
- Built-in features (https://github.com/aspnet/HttpAbstractions/tree/dev/src/Microsoft.AspNet.Http.Features)
    - Note: feature specifics should be covered in API ref docs (coming soon)

**Comment by ardalis** [comment]
Making progress on this - any examples you can offer for Middleware usage of Feautures/FeatureCollection?
