### ISSUE TITLE
Migrating Message Handlers to Middleware

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#294]

**Comment by Rick-Anderson** [comment]
@danroth27  can you be more specific?  We do have https://docs.asp.net/en/latest/fundamentals/middleware.html#additional-resources which point to https://docs.asp.net/en/latest/migration/http-modules.html
do we need something like that for message handlers? Should this info go in https://docs.asp.net/en/latest/fundamentals/middleware.html>

**Comment by danroth27** [comment]
I think this would be a new topic under the migration node. It probably should be part of a broader set of content that general covers migrating from ASP.NET Web API to ASP.NET Core. So maybe: `/migration/web-api/message-handlers.html`.

**Comment by danroth27** [comment]
I think this was supposed to be titled migrating HTTP handlers to middleware, which is already covered here: https://docs.microsoft.com/en-us/aspnet/core/migration/http-modules?view=aspnetcore-2.2#migrating-handler-code-to-middleware
