### ISSUE TITLE
Localization sample doesn't work if an application is deployed in IIS as Virtual App

### ISSUE THREAD

**Issue by PeterJakubik** [aspnet/Docs#2943]
In https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#resource-file-naming the sample in "Setting the culture programmatically" doesn't work if the ASP MVC app is deployed in IIS in Virtual Application

When the App is IIS Virtual Application the returnUrl in form parameter is wrong.

I think that sample should prepend the "~" like:
```
@{
var requestCulture = Context.Features.Get<IRequestCultureFeature>();
  var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
   var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : "~" + Context.Request.Path.Value;
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name" style="text-align:center; padding:5px">
    <form id="selectLanguage" asp-controller="Localizer"
          asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
          method="post" class="form-horizontal" role="form">
        
        <label style="color:white">@Localizer["Language:"]</label>      
        <select name="culture" onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
    </form>
</div>
```

With this fix the Controller works with `LocalRedirect(returnUrl)`

Kind regards
Peter

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please review

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg please review

**Comment by guardrex** [comment]
@PeterJakubik @ryanbrandenburg @scottaddie If there's no objection, I'd like to work this sample forward to 2.0 and see about this issue in the process. One quick clarification: "Virtual apps" aren't supported, so we're talking about running this as a "sub app." In IIS, I'll run it both as a site and as a sub app to see if I can repo the behavior. Note that changes have been made to the partial since this issue was opened and that those changes may have fixed the issue here as a bonus. I'll report back shortly.

**Comment by guardrex** [comment]
I have the 2.0 sample done. It seems to run well on its own. 

However, hosted as a sub app ... :boom: :man_facepalming:

![capture10](https://user-images.githubusercontent.com/1622880/30101549-68e3ed9c-92b2-11e7-8889-d78504018755.PNG)

Although the code of the partial changed, it doesn't take into account the path change you made above, so it probably just needs a little fix along those lines to get it running. I'll fix it tomorrow ... er ... later today (it's 3:30am)! :smile:
