### ISSUE TITLE
clean up tutorials/your-first-mac-aspnet

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#2961]
- [ ] re-shoot the first 3 screenshots and crop so they are readable
- [x]  On my mac I had to open the project folder to get prompted to restore. Verify instructions.
- [x] After `Tap "Yes" to add the build and debug assets.` I'm left with the 2nd  message with a restore button. Do I need to tap restore on that?
- [ ] 
- [ ]

**Comment by spboyer** [comment]
@Rick-Anderson - what is wrong with the images? Is there a standard size you want these at?

**Comment by spboyer** [comment]
@Rick-Anderson in the article it does state 

> Open the project folder in Visual Studio Code (VS Code).

**Comment by spboyer** [comment]
@Rick-Anderson states two instructions, one for each prompt.

> Tap Yes to add the build and debug assets and then tap Restore to restore the project dependencies.

**Comment by Rick-Anderson** [comment]
Images are too small. That's OK, I'll reshoot them.

**Comment by Rick-Anderson** [comment]
>@Rick-Anderson in the article it does state

> >Open the project folder in Visual Studio Code (VS Code).

LOL, I know, I added that :--)

**Comment by spboyer** [comment]
^^ Oh, lol ok, didn't realize you made that add. Thanks.

**Comment by computeronix** [comment]
FYI on https://docs.microsoft.com/en-us/aspnet/#pivot=core&panel=core_tutorials
The tutorial (this issue references) - Build a website on a mac --- links to https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet which is an invalid URL

I wasn't sure where the page went otherwise would have provided PR to fix this

The file to edit is https://github.com/aspnet/Docs/blob/master/aspnet/index.md

**Comment by Rick-Anderson** [comment]
>FYI on https://docs.microsoft.com/en-us/aspnet/#pivot=core&panel=core_tutorials
The tutorial (this issue references) - Build a website on a mac --- links to https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet which is an invalid URL

@tdykstra  how do we fix that page we don't own?
@computeronix  thanks for reporting this.

**Comment by tdykstra** [comment]
We do own that page -- fix is in #3757

**Comment by Rick-Anderson** [comment]
this tutorial was dropped
