### ISSUE TITLE
Update DataProtection docs

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Docs#2975]
The docs for Data Protection need to be updated as per the changes in https://github.com/aspnet/DataProtection/issues/134

**Comment by Rick-Anderson** [comment]
@ajaybhargavb  who do you recommend to update the docs? [@]blowdart  ?

**Comment by ajaybhargavb** [comment]
I think I can do it myself and have @blowdart review it.

**Comment by ajaybhargavb** [comment]
108ae806a574395dd45f5e8f8faba764cabeca39
