### ISSUE TITLE
Add how to build in README.md

### ISSUE THREAD

**Issue by borgdylan** [aspnet/Docs#3]
To let people not familiar with sphinx build these docs, add that python 2, pip, sphinx and the "sphinx_rtd_theme" module must be installed to the README. The theme is installed like so:
```
sudo pip install sphinx_rtd_theme
```

**Comment by ardalis** [comment]
Updated README with instructions. Please open a new issue if there are still problems. Thanks!

**Comment by borgdylan** [comment]
Thanks for mentioning autobuild. I did not know it existed.
