### ISSUE TITLE
configuration.rst need security warning call AddEnvironmentVariables last

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#303]
@ardalis @danroth27 
"Essentially, the last configuration source specified “wins” if a setting exists in more than one location."

Remove essentially, it's not essentially, it's actually. Then add a security note that AddEnvironmentVariables should always be called last because you want env variable to win.
@Eilon @blowdart  we need security approval of this assertion.

**Comment by Eilon** [comment]
That's not a security concern as far as I can tell. It's just a common practice. It's perfectly reasonable to have any config sources in any order. You might have the last one be an INI source for a file called `super_important_dont_override.ini` to ensure that even env vars won't override certain values.

**Comment by Rick-Anderson** [comment]
AddEnvironmentVariables should always be called last because you want env variable to win.
@Eilon @blowdart we need security approval of this assertion.
@blowdart  can you approve this message?

**Comment by blowdart** [comment]
Yea, I would much rather see must because it makes it clearer ordering wins, and if you want the local config to win you MUST do it. You could clarify it a little to make it clear this is why it's a must?

**Comment by Rick-Anderson** [comment]
@ardalis can you make this change. Also point to my secrets doc.

**Comment by Rick-Anderson** [comment]
@Eilon @blowdart  Why don't we just fix the code. Throw if you config any source after environment - then we don't need to add the caveat - evn var wins **** assuming you've configured env last *****

**Comment by Eilon** [comment]
That is very poor guidance in my view. There is *absolutely nothing special* about env vars. It's just another config provider. Why is it so important that env vars always win? Under what scenario is this important?

**Comment by Rick-Anderson** [comment]
I was thinking config files are inherently insecure. I have a strong bias from the doc point of view - too many doc's assert that env vars win - and I can't monitor all the docs (to make sure they explain "env vars win when they are the last configured").
 I'll leave this to you and @blowdart

**Comment by Eilon** [comment]
My comments are unrelated to security. You are correct that secure content shouldn't be stored in config files (for many reasons, including that they get checked into source control). But that's orthogonal to the config system and env vars.

**Comment by ardalis** [comment]
@Rick-Anderson if the PR #771looks good, close this.
