### ISSUE TITLE
HttpContext.Items keys are objects rather than strings

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Docs#3040]
At https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md#working-with-httpcontextitems:

> Note: Keys into Items are simple strings. If you are developing middleware that must work across many applications, consider giving your keys a prefix with a unique identifier to avoid key collisions (for example, "MyComponent.isVerified" instead of "isVerified").

This is incorrect.  As stated just above this comment in the doc, `HttpContext.Items` has type `IDictionary<object, object>`, so keys are objects.  The best practice is to use a unique `object` as a key, where the key is private or public as needed.  For example:

```C#
public class Foo {
    private static readonly object _isVerifiedKey = new object();

    app.Use(async (context, next) =>
    {
        // perform some verification
        context.Items[_isVerifiedKey] = true;
        await next.Invoke();
    });
}
```

**Comment by Rick-Anderson** [comment]
@ardalis  can you also fix:

- [ ] remove extra` }` in last sample
- [ ] remove a couple characters so ` await context.Response.WriteAsync("Verified request? " + context.Items["isVerified"]);
});` doesn't scroll.

ping me for review.

**Comment by ardalis** [comment]
@Rick-Anderson you have a patch branch with this - I assume I should just commit to that?

**Comment by Rick-Anderson** [comment]
@ardalis  no, just work off master.

**Comment by Rick-Anderson** [comment]
@mikeharder  quick review please.

**Comment by mikeharder** [comment]
Approved
