### ISSUE TITLE
Update "Use VSTS to Build and Publish to an Azure Web App with Continuous Deployment

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3043]
TLDR;
Remove this and redirect to https://www.visualstudio.com/docs/build/aspnet/core/quick-to-azure

1. We have an out of the box .NET Core task
2. Hosted Build pool supports _project.json_ and there is a new VS2017 hosted pool image which supports csproj
3. We have also added a new .NET Core Build template

![image](https://cloud.githubusercontent.com/assets/3605364/24226793/b66b0fb6-0f0c-11e7-9f41-a0542eecfdcb.png)

@damienpontifex would you be able to update? cc @azooinmyluggage

**Comment by damienpontifex** [comment]
@Rick-Anderson yes I can update. Please assign to me.

I had thought before, but was waiting for the hosted build servers to be updated to 1.0.0 of the cli. Seeing as there are now VS2017 hosted servers, I think this will be alright to go.

**Comment by Rick-Anderson** [comment]
@damienpontifex  OK, it's yours. I can't assign you in the UI since you're not a member of the repository.

**Comment by damienpontifex** [comment]
@Rick-Anderson reading around and wondering whether this article should redirect to the Team Services article here https://www.visualstudio.com/en-us/docs/build/apps/aspnet/aspnetcore-to-azure

That article also needs updating to display the out of the box tasks. But would be better to have one version of the content?

Let me know thoughts and if we should go ahead with this article or pursue updating it on the Team Services doc site?

**Comment by Rick-Anderson** [comment]
@damienpontifex  I agree.  @danroth27  @tdykstra  should we update [Build and deploy your ASP.NET Core app to Azure](https://www.visualstudio.com/en-us/docs/build/apps/aspnet/aspnetcore-to-azure)

**Comment by damienpontifex** [comment]
I tried searching to see whether those docs were also accepting contributions, but didn't find anything.

**Comment by Rick-Anderson** [comment]
@damienpontifex  arg - the old MS. I'll find the owner.

**Comment by tdykstra** [comment]
>  should we update Build and deploy your ASP.NET Core app to Azure

Yes, and when that's done retire our version, redirect the URL of our version to the VSTS article, and change our TOC to link to the VSTS article.

**Comment by Rick-Anderson** [comment]
@tdykstra  @danroth27  [Build and deploy your ASP.NET Core app to Azure](https://www.visualstudio.com/en-us/docs/build/apps/aspnet/aspnetcore-to-azure) is in a private repo only MSFT FTE's can contribute. I'm asking them to retire their version and we should migrate it to our open repo.

**Comment by Rick-Anderson** [comment]
@tdykstra  can you Remove this and redirect to https://www.visualstudio.com/docs/build/aspnet/core/quick-to-azure
