### ISSUE TITLE
Create a page with links to alternative ways to configure authentication using .NET OSS projects

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#3046]
We'd like to have a place in our docs that we can link to that points people to alternative .NET OSS projects for configuring authentication. We already link directly to the IdentityServer4 docs from https://docs.microsoft.com/en-us/aspnet/core/security/authentication/. The new page would highlight IdentityServer4 along with any other project that the community thinks is worth mentioning (ASOS? OpenIDDict? Anything else?).

@brockallen @leastprivilege @pinpointtownes @blowdart @sayedihashimi

**Comment by leastprivilege** [comment]
Has anything happened yet? Wasn't the plan to add this link to VS with the next update? Update 1 was released today - is this info included now?

**Comment by danroth27** [comment]
@sayedihashimi @Andrew-MSFT 

The updated to VS to surface this content is targeted for the [ASP.NET Core 2.0 release in Q3](https://github.com/aspnet/home/wiki/roadmap).

**Comment by danroth27** [comment]
@leastprivilege @brockallen @pinpointtownes The link is now in our internal VS builds and will show up *very soon* in an upcoming VS preview, so we'd like to get this topic published by early next week. 

@sayedihashimi @tdykstra @Rick-Anderson Can you guys help out with working out a basic structure for this page and getting this page in place?

**Comment by danroth27** [comment]
@jongalloway

**Comment by Rick-Anderson** [comment]
@danroth27  if someone can PR the list of links @tdykstra  or @Rick-Anderson will edit/format.

**Comment by PinpointTownes** [comment]
@danroth27 is there anything we can/should do to help?

**Comment by danroth27** [comment]
To start out, how about we have a short project description and a link for each option? Can you guys provide the text and link that you'd like us to use?

**Comment by sayedihashimi** [comment]
Draft at https://github.com/aspnet/Docs/pull/3314. For the OSS Packages I need the following info:

- Name
- Description
- Link

**Comment by tdykstra** [comment]
Fixed by #3314
