### ISSUE TITLE
rename "What's new" to release notes

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3052]
We also need a way to surface the pdf in https://github.com/aspnet/Docs/tree/master/aspnetcore/common/_static

**Comment by tdykstra** [comment]
> We also need a way to surface the pdf in https://github.com/aspnet/Docs/tree/master/aspnetcore/common/_static

Could put it in TOC:

* 1.1 Release notes
  * Earlier release notes
  * Project.json documentation (PDF)
