### ISSUE TITLE
The View Compilation article needs an example of IDesignTimeMvcBuilderConfiguration

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Docs#3057]
Posting this after having :bug:'d @pranavkm over at the aspnet/MvcPrecompilation repo.

**Comment by Rick-Anderson** [comment]
@tuespetre  Do you have a sample we could use?

**Comment by Rick-Anderson** [comment]
Compare with rich diff
![image](https://user-images.githubusercontent.com/3605364/27348578-6b6d94f0-55a9-11e7-81a3-420816b46b30.png)

**Comment by Rick-Anderson** [comment]
Closing for higher priority items.
