### ISSUE TITLE
"Publish to a Linux Production Environment" should suggest using UNIX sockets

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Docs#3068]
Currently the [Publish to a Linux Production Environment](https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction) page configures Nginx to proxy `localhost:5000`. In a production scenario, it's more likely that you'll use a UNIX socket instead. This has lower overheads compared to TCP connections, and is generally how services on Linux listen for local connections.

Here's an example of how I configure my site/blog:
https://github.com/Daniel15/Website/blob/8d1485d5e6e5136bd1753b7031f067aeae596fa3/Daniel15.Web/nginx.conf#L73
https://github.com/Daniel15/Website/blob/8d1485d5e6e5136bd1753b7031f067aeae596fa3/Daniel15.Web/supervisord.conf#L2

**Comment by Rick-Anderson** [comment]
@Daniel15  great info. Any chance you could submit a PR for this article?

 `localhost:5000` is for development on local machine - right?

**Comment by RehanSaeed** [comment]
> A UNIX socket is an inter-process communication mechanism that allows bidirectional data exchange between processes running on the same machine.
[Source](https://serverfault.com/questions/124517/whats-the-difference-between-unix-socket-and-tcp-ip-socket)

So this would only work if you had NGINX and an ASP.NET Core app running on the same machine right? In a Docker based scenario, that cannot be guaranteed.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
