### ISSUE TITLE
Web API tutorial cleanup WebAPI

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3076]
- [x]   refactor the 3 versions with includes. 
- [x] Here is an example HTTP response for the - shows GUID
- [x]  wrong pic on ##Add a controller windows version
- [x]  Replace Key in model with ID and remove [Key]. Make it an int, not long.
- [ ] EF 1.1 has Find command, could use that in Find and Remove methods.
- [x] remove repository to simplify and provide a link at the end to repository pattern.
- [x] #3800 `UseInMemoryDatabase`

**Comment by Rick-Anderson** [comment]
@tdykstra  since you own EF do you want to take this one? Would be nice to get agreement of mwasson before removing repository. Anything that makes the tutorial simpler is an improvement.

**Comment by ardalis** [comment]
Not sure we want to promote direct coupling of UI and data layers in the API controllers in our docs. Adding an interface adds a trivial amount of code but enables better testability.

**Comment by tdykstra** [comment]
@Rick-Anderson Sure

@ardalis The thought there is that we added EF to this tutorial, and EF essentially functions as repository and UoW.  See https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced#repository-and-unit-of-work-patterns

**Comment by Rick-Anderson** [comment]
@ardalis  the EF PU approved [This](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced#repository-and-unit-of-work-patterns)

**Comment by Rick-Anderson** [comment]
@MikeWasson We're going to remove repository from your tutorial. Do you agree? Read [This](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced#repository-and-unit-of-work-patterns)

**Comment by ardalis** [comment]
It's not just about testing - having proper abstractions in place is better for a variety of reasons. There's no reason why the UI project should know anything about how persistence is achieved. If it does, that tight coupling just becomes technical debt. Let's say we want to implement data-level caching, for some operations. We don't want that code to live in our UI layer. We don't want it to live in the DbContext. With an abstraction around persistence, it's trivial to use a Decorator(or Proxy if you prefer - same pattern different intent) to wrap caching logic around the persistence logic. See [CachedRepository](http://ardalis.com/building-a-cachedrepository-via-strategy-pattern) for example.

Then there's the Interface Segregation Principle argument. It states that client code shouldn't depend on methods that it doesn't use. If a controller only needs to, say, list Orders, and maybe fetch an Order, it needs two methods. An interface can suffice for this. Passing a DbContext, which for  a real application will likely have tens of DbSets on it, is way more than it needs. Any time the DbContext is modified, all of the code that depends on it is potentially impacted. With an abstraction in place, only when the abstraction change (or its 2-method implementation) does this need to occur.

I get that the EF team would prefer everybody use their code everywhere directly, but there may be some (implicit) bias there. I love EF and I think EF Core is amazing. But it doesn't change the fact that software that follows separation of concerns and doesn't tightly couple UI concerns to persistence concerns is going to have less long-term technical debt. If you're just looking at CRUD or sample projects, fine. There's no need to do any separation of concerns or have multiple projects, as long as you're sure to inform readers that this is the reason for the lack of a more robust architecture. But for anything that's going to have substantial complexity or shelf-life, following SOLID principles and Separation of Concerns is going to be pretty tough to argue credibly against, IMO.

**Comment by Rick-Anderson** [comment]
@divega please comment. We need to weigh best practice vs. keeping this super intro tutorial simple.

**Comment by tdykstra** [comment]
@MikeWasson We're considering removing repository from your tutorial since we've added EF. What do you think? We removed repository from the EF MVC tutorials - see [this discussion in EF MVC](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/advanced#repository-and-unit-of-work-patterns)

**Comment by Rick-Anderson** [comment]
@danroth27  please weigh in - should we remove repository from this tutorial?  This will keep the tutorial more focused on Web API.

**Comment by danroth27** [comment]
These tutorials are simple enough that I think implementing a repository is overkill. I'm in favor of removing it. Feel free to link to content that guides people to the more robust patterns though.
