### ISSUE TITLE
Document how to use gulp-rev to handle static file versioning and caching

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#308]
https://github.com/aspnet/Mvc/issues/2666#issuecomment-112454805

**Comment by benmccallum** [comment]
Thanks guys :) Happy to contrib a start if I get time.

**Comment by danroth27** [comment]
Cool - we would welcome the contribution!

**Comment by Rick-Anderson** [comment]
@benmccallum  any chance you could give us a PR on this?

**Comment by benmccallum** [comment]
Sure @Rick-Anderson! I'll start something up now.

**Comment by benmccallum** [comment]
@Rick-Anderson, I'm going to start working on /aspnet/client-side/bundling-and-minification as I think it's a good place to talk about (1) Using gulp, (2) Using grunt, (3) Cache-busting techniques.

Firstly, are you aware of anyone working on this article?

Secondly, I notice there's an article at /aspnet/client-side/using-grunt which would overlap quite a bit with my part on using grunt. Just wondering how to proceed before I get stuck in:
1. Make "Using grunt" article content more generic (like "Using gulp" is) by moving out the bundling/minification tasks into my article, or
2. Reference "Using grunt" article from mine, or
3. Copy-paste and have duplication (i.e. if every article should be self-contained)

I'm leaning towards option 1, but I'll have to let the author (Noel Rice) know. What's your preference?

**Comment by Rick-Anderson** [comment]
@Erikre  is working on some grunt articles but I'm sure he could use your help - can you coordinate with him?
@noelatfalafel @danroth27  can you review @benmccallum proposal?

**Comment by noelatfalafel** [comment]
@benmccallum, I lean towards option #2 just to keep the internal progression of the article in one piece. Option #1 is OK, but I won't be able to participate in a rewrite just now. #3 seems like a non-starter.

**Comment by danroth27** [comment]
I think @Erikre is already looking at writing up client-side bundling and minification (see https://github.com/aspnet/Docs/issues/101).

**Comment by Erikre** [comment]
@benmccallum - When I have this topic farther along I could review it with you.

**Comment by benmccallum** [comment]
Thanks everyone! @Erikre, perhaps if you leave off the concept of cache-busting, I'll write a separate page that addresses cache-busting/versioning (gulp-rev, and other techniques) with examples of implementations in grunt/gulp as it's cross-cutting really.

**Comment by Erikre** [comment]
The Using Gulp topic (https://docs.asp.net/en/latest/client-side/using-gulp.html) has been updated and the Bundling and Minification topic (https://docs.asp.net/en/latest/client-side/index.html) is currently being reviewed.

**Comment by danroth27** [comment]
We decided this is really outside the scope of the ASP.NET Core docs.
