### ISSUE TITLE
Need a reference page for dnvm

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Docs#309]
dnvm shows just a short description for each command. For some commands (setup, upgrade) it does not seem be enough. For instance I am missing information on scenarios when to use `dnvm setup` or  what is the difference between `dnvm install` and `dnvm upgrade` (seems like `dnvm upgrade` is kind of redundant - it just saves typing)

**Comment by moozzyk** [comment]
Need a detailed explanation of the `<VersionNuPkgOrAlias>` parameter of the `dnvm install` command and the scenarios when it is useful.

**Comment by danroth27** [comment]
All of DNX and it's current acquisition story will soon be replaced by the new [.NET CLI](https://github.com/dotnet/cli), which will be documented as part of the .NET docs. Closing.
