### ISSUE TITLE
New article explaining files created in new ASP.NET web app 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3091]
Create an article explaining the files create with VS new web app template or `dotnet new mvc`

Several tutorials could link to it. For example my two "intro to MVC" and  [Scaffold](https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet#scaffolding-applications-using-dotnet-new) which does a half  explanation. 

@tdykstra  please review

**Comment by tdykstra** [comment]
Are we getting requests for that?  I don't see the need for that unless we have really obscure files you couldn't guess the usage of by looking at them.  One possible use for such a doc would be an explanation for each file as to whether it can be omitted and what happens if you delete it, but again I don't know what the demand would be for that, so this is hard to prioritize.

**Comment by Rick-Anderson** [comment]
It's more of a refactor question.  I want to make the following one article rather than copy/paste it in 3 to 5 places (from  [Scaffold](https://docs.microsoft.com/en-us/aspnet/core/tutorials/your-first-mac-aspnet#scaffolding-applications-using-dotnet-new)  )

Startup.cs : Startup Class - class configures the request pipeline that handles all requests made to the application.
Program.cs : Program Class that contains the Main entry point of the application.
firstapp.csproj : Project file MSBuild Project file format for ASP.NET Core applications. Contains Project to Project references, NuGet References and other project related items.
appsettings.json / appsettings.Development.json : Environment base app settings configuration file. See Configuration.
bower.json : Bower package dependencies for the project.
.bowerrc : Bower configuration file which defines where to install the components when Bower downloads the assets.
bundleconfig.json : configuration files for bundling and minifying front-end JavaScript and CSS assets.
Views : Contains the Razor views. Views are the components that display the app's user interface (UI). Generally, this UI displays the model data.
Controllers : Contains MVC Controllers, initially HomeController.cs. Controllers are classes that handle browser requests.
wwwroot : Web application root folder.

**Comment by tdykstra** [comment]
Why not use an include?
