### ISSUE TITLE
Update Fundamentals/Routing doc sample code to CSPROJ

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#3104]
The sample code for the [Routing](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing) doc is still based on `project.json`. Is anyone already working on upgrading it to CSPROJ? If not, I'll take care of it.

/cc: @Rick-Anderson

**Comment by Rick-Anderson** [comment]
That would be great - Thanks.
