### ISSUE TITLE
React to UseUrls breaking change for 2.0

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#3109]
https://github.com/aspnet/Announcements/issues/230

https://github.com/aspnet/Docs/search?utf8=%E2%9C%93&q=UseUrls&type=

Looks like three spots/samples that require a touch of work when 2.0 lands.

**Comment by guardrex** [comment]
@scottaddie Good news on this one. I checked all instances of `UseUrls`, and the topics have it covered. They've either already been addressed (e.g., URL Rewriting Middleware sample) or are about to be addressed [e.g., the [upcoming updates to *fundamentals/hosting* (Docs/4137)](https://github.com/aspnet/Docs/pull/4137)]. We can close here. :+1:

**Comment by scottaddie** [comment]
@guardrex Thanks for following up on this!
