### ISSUE TITLE
Error: "Arithmetic operation resulted in an overflow." on executing a command "dotnet ef database update"

### ISSUE THREAD

**Issue by OksanaMych** [aspnet/Docs#3111]

**Comment by Rick-Anderson** [comment]
@OksanaMych  Looks like it's a problem with your anti-malware software:

http://stackoverflow.com/questions/32609088/arithmetic-overflow-exception-when-opening-sql-connection 

Apparently the same software can cause DivideByZeroException:

https://kb.eway-crm.com/faq-1/database/connection-with-local-database-is-not-working  

You also need to update to .NET Core 1.1
