### ISSUE TITLE
Intro to MVC cleanup - adding a model

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3112]
- [x] Explain why we need [initial migration](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model#dotnet-ef-commands). Pointer to more migration info
- [x] explain Add the database context to the Startup.cs file: in xplat adding a model
- [x] add tdykstra as co-author
- [x] look for comment `<!-- Move the next two sections to an include -->` and do that.
- [x]  [Strongly typed models and the @model keyword](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model#strongly-typed-models-and-the-model-keyword) Explain: 

*  `(int? id)`
* `m => m.ID == id)` and provide links

**Comment by Rick-Anderson** [comment]
@tdykstra  can you clean up/expand the EF info in these two?

**Comment by tdykstra** [comment]
Yes. By "these two" do you mean the VS version and the new xplat version?

**Comment by tdykstra** [comment]
@Rick-Anderson Is this ready for me or are you still working on it?

**Comment by Rick-Anderson** [comment]
@tdykstra  ready for you to take over - and yes review both versions.
