### ISSUE TITLE
Tag Helpers section "intellisense-support-for-tag-helpers" is not work

### ISSUE THREAD

**Issue by kkbruce** [aspnet/Docs#3113]
Hi Sir

This section 
https://docs.microsoft.com/zh-tw/aspnet/core/mvc/views/tag-helpers/intro#intellisense-support-for-tag-helpers (from https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/intro.md) incorrect and is not work now. 

Replace this https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md content, is work and correct now.

**Comment by Rick-Anderson** [comment]
@kkbruce  what exactly is wrong and what is the correction?

**Comment by kkbruce** [comment]
Hi

In VS 2017 RTM, 
1. Create a new ASP.NET Core Web Application(.NET Core)
2. open a .cshtml view page
3. input **asp-** in html tag 
No tag helpers Intellisense, This's normal status.

I reference "#intellisense-support-for-tag-helpers" section, after installed "Microsoft.AspNetCore.Razor.Tools", no any tag helpers Intellisense.

I find another doc (https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#aspnet-core-known-issues),  he say "Install the Razor Language Service extension". This workaround is work for me.
