### ISSUE TITLE
Little mistake on 'your-first-aspnet-application.rst'

### ISSUE THREAD

**Issue by Dantrech** [aspnet/Docs#313]
In 'Adding Server-Side Behavior', the example code show:

```c#
public IActionResult About()
{
	string appName = "Your First ASP.NET 5 App";
	ViewBag.Message = "Your Appliation Name: " + appName;

	...
}
```

Follow the next image (http://docs.asp.net/en/latest/_images/server-behavior.png) it should be:

```c#
public IActionResult About()
{
	string appName = "Fundamental Concepts";
	ViewBag.Message = "Your application name: " + appName;

	...
}
```

Or just update the image (because it's show the string 'Use this area to provide additional information.').

**Comment by Rick-Anderson** [comment]
@ardalis please fix and close.

**Comment by ardalis** [comment]
This whole article was replaced, so this issue is no longer relevant.
