### ISSUE TITLE
Update 2FA article to use Twilio

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3134]
When I create a .NET Core 1.1 console app and run `Install-Package Twilio` I get a ton of errors.
@joeaudette can you help me get this working?

cc @GuardRex

**Comment by Rick-Anderson** [comment]
@joeaudette @GuardRex  got it working. I had a name collision caused by my console app project having the same name as the Twilio package. I

**Comment by GuardRex** [comment]
With the project named "Twilio", installing the Twilio package the errors are ...

> error: Failed to resolve conflicts for .NETCoreApp,Version=v1.1.

A gazillion of errors like ...

> error: Unable to satisfy conflicting requests for 'Twilio': project/Twilio (>= 1.0.0) (via project/Twilio 1.0.0), Twilio  (via project/Twilio 1.0.0)

Ending with ...
> error: Sequence contains more than one matching element

Does it feel like one of those *the error message could be improved*-types of scenarios/issues?

Do docs need to go as far as saying at `dotnet new`'s `--name` option that when you name your project, you should confirm at NuGet.org that the name isn't already in use as a package name? If so, should tutorials and samples also say something about this in project naming instruction steps?
