### ISSUE TITLE
 ICompileModule missing reference on 'DNX Overview' (overview.rst)

### ISSUE THREAD

**Issue by Dantrech** [aspnet/Docs#314]
In 'Compile Modules' sections, 'ICompileModule' has a hyperlink to
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Framework.Runtime.Roslyn.Interfaces/ICompileModule.cs

Url don't exists.

**Comment by danroth27** [comment]
Merged in fix: c292ca0e015efe8d6a9bbdfd664fa313867097a6
