### ISSUE TITLE
10th item in list appears as 0

### ISSUE THREAD

**Issue by mihemihe** [aspnet/Docs#3140]
**General**

The **10th** item in the list in document [https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/) appears as **0** . It is also happening in other lists in the documentation, like here [https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/)

![Image of List](https://i.imgur.com/wSfXam3.png)

Resizing the browser appears to bring the missing 1, but not quite right:

![Image of resized browser](https://i.imgur.com/dIikWxb.png)

PDF generated file shows 10 properly:

![Image of pdf](https://i.imgur.com/5Wyf0Mb.png)

**Tested in:** 

1. Chrome 56
2. IE11
3. Others via online browser testing tools

**Solution**

I tried to create a PR and edit the document, but the markup seems correct, so it might be some kind of bug with the markup itself, or the way the browsers render the content, or the div margins:

![Image of markup](https://i.imgur.com/c0o95ES.png)

![Image of Chrome html](https://i.imgur.com/wzLxu6x.png)

**Comment by Rick-Anderson** [comment]
@mihemihe  I can't repo with Chrome/FF/IE/Edge on windows or Chrome/FF/Safari on macOS (all current versions) 
@tdykstra  can you repro?

**Comment by mihemihe** [comment]
@Rick-Anderson It works correctly now, in all my browsers, in different PCs and in online browser compatibility tools ¯\_(ツ)_/¯
