### ISSUE TITLE
English to Japanese Translation

### ISSUE THREAD

**Issue by beachside-project** [aspnet/Docs#3169]
I (and my friends) want to translate Japanese docs at [aspnet/Docs.ja-jp](https://github.com/aspnet/Docs.ja-jp) . 
we translated some. 
could you create the ja-jp docs like issue [#3168](https://github.com/aspnet/Docs/pull/3168) ?

**Comment by Rick-Anderson** [comment]
We will be creating a .ja-jp repro soon with machine translated docs. Once we have that repo you can submit PR's. We hope to have that done in a couple months.

 subscribe to #3188 to get notified.
