### ISSUE TITLE
XCopy over Web Deploy (MSDeploy) for publishing to IIS?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#317]
I'm surprised you went the direction you did with [Publishing to IIS](http://docs.asp.net/en/latest/publishing/iis.html#xcopy-to-iis-server). Isn't XCopy going to be crazy slow because it's going to copy all of the files to the server every publish? Is that correct? That's what I read about it.

**Comment by Rick-Anderson** [comment]
I use robocopy and my assumption was so would most folks. Historically MS has written XCopy as brute force approach and most folks seem to know to use robocopy.
