### ISSUE TITLE
RESTful, claims-based authentication without using external providers

### ISSUE THREAD

**Issue by shaunluttin** [aspnet/Docs#318]
# The proposed article

The proposed article is particularly relevant to single-page applications and related RESTful clients (e.g. those that use AngularJS.) These apps often require access tokens for authorized access to multiple resource servers. Instead of relying totally on external providers, this article will explain how to create and consume access tokens using the apps own OpenID Connect identity provider, as an complement to using external providers.

A few articles at docs.asp.net explain how to do authorization/authentication using external providers. E.g. [Enabling authentication using external providers](http://docs.asp.net/en/latest/security/sociallogins.html) does this. A complementary use case that is not yet complete, is being able to provide our own RESTful authentication/authorization without relying on external providers. This gives end users the choice to sign in via the current domain rather than an external provider.

I propose an article that explains how to use Open ID Connect in ASP.NET 5. The article will cover how to be the relying party, resource server, and identity provider and will illustrate this with an extremely simple sample solution, [which is in progress here](https://github.com/bigfont/AspNet.Security.OpenIdConnect.Server/tree/bigfont/samples/ResourceOwnerPasswordFlow). 

The article will touch on topics that are in proposed articles: 
- [Roles-based authorization](http://docs.asp.net/en/latest/security/authorization/roles.html)
- [Claims-based authorization](http://docs.asp.net/en/latest/security/authorization/claims.html)
- [Supporting third party clients using OAuth 2.0](http://docs.asp.net/en/latest/security/authorization/oauth2.html)

The article will assume that readers have their own way of storing user credentials (e.g. via ASP.NET Identity.) As a result, we will not be covering the topics that are described in [Account confirmation and password recovery with ASP.NET Identity](http://docs.asp.net/en/latest/security/accconfirm.html).
# Title brainstorming
- RESTful authentication with OAuth 2.0 and OpenID Connect
- Username Password Flow with OAuth 2.0 and OpenID Connect
- RESTful, claims-based authentication without using external providers

**Comment by danroth27** [comment]
@shaunluttin Thank you for proposing this article!

@blowdart Could you please review this article proposal? Any questions or concerns?

**Comment by blowdart** [comment]
I'd drop roles based, we're trying to steer people away from that. I'd be concerned about the usual oauth stuff, replays, nonces, everything in the oauth spec around security. Simple samples end up being insecure. We didn't want to write a server for very good reason; which is why we've been recommending Identity Server.

**Comment by danroth27** [comment]
Yeah, I don't think we want sample code for token issuance. We should instead by directing folks to use trusted token sources.

**Comment by shaunluttin** [comment]
That's all good stuff to know. Thank you for the feedback.

**Comment by shaunluttin** [comment]
@danroth27 Let me see if I am understanding the feedback from @blowdart. I think he is saying that this article is not appropriate for the docs, because you would rather be referring people to use trusted token sources, such as Twitter, Facebook, Google, etc. Is that right?

**Comment by blowdart** [comment]
My concern is more around writing your own identity provider. It is hard to make those secure, and we've avoiding doing it very deliberately. It's even harder to make them secure when you're writing it as a simple sample that people understand.

We've been steering people towards identity server for that sort of thing.

**Comment by shaunluttin** [comment]
@PinpointTownes I am wondering whether the above feedback means about my fork of https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server.

**Comment by shaunluttin** [comment]
@blowdart What if instead I leveraged this contribution to implement the resource owner password flow.  https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server

**Comment by blowdart** [comment]
I've not looked at that so I don't know. As we officially steer people to identity server is far rather see that as the server used in any documentation.

**Comment by shaunluttin** [comment]
@blowdart Hmm. I might be over my head. I am not sure what you mean by steering people toward Identity Server.

**Comment by blowdart** [comment]
Identity server is a 3rd party component that issues tokens. It's the only token issuer we recommend and thus for any official documentation or samples around issuance we would require that as an issuer.

**Comment by shaunluttin** [comment]
@blowdart Is this it? https://github.com/IdentityServer/IdentityServer3 or are you referring to another implementation?

**Comment by blowdart** [comment]
That's the one.

**Comment by shaunluttin** [comment]
@blowdart Great. In the next few days, I will update my write-up of the proposed article based on your feedback and then message you.

**Comment by PinpointTownes** [comment]
> @PinpointTownes I am wondering whether the above feedback means about my fork of https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server. Is the sample that I was creating still relevant?

Sure, it is. ROPC is a very popular grant.

> I've not looked at that so I don't know. As we officially steer people to identity server is far rather see that as the server used in any documentation.

Funny you've never heard about ASOS... it helped fix many bugs in the OIDC client middleware your team develops :smile:

**Comment by shaunluttin** [comment]
@PinpointTownes I think what I will do then, is to finish off the example that I started on with with ASOS. Once that is done, I will consider porting it to Identity Server.

**Comment by PinpointTownes** [comment]
Great, thanks :smile: 

FWIW, using [OpenIddict](https://github.com/openiddict/core) is now the approach I recommend when integrating ASOS with Identity 3. It implements a few things for you: client authentication, resource owner credentials validation (with lockout support) and automatic refresh token revocation when the security stamp changes.

**Comment by danroth27** [comment]
For using external identity providers like OpenIDDict or IdentityServer4 we prefer just to point folks to the docs for those components. We are also looking at building our own identity service component, but nothing to document yet. Closing.
