### ISSUE TITLE
Improve explanation of ConfigureServices vs. Configure method in fundamentals/startup.md

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3205]
LiveFyre sidenote comments on ConfigureServices section:
* You need to add more here. Why do some services need to be defined here but other not . What is going on in the application initialization at this phase?
* Here you need to add more. what differentiate configure from configureservices? what run-time you referring here. We know about CLR from previous versions with it's in-out but here the run-time is too abstract

**Comment by ardalis** [comment]
@tdykstra to review PR.
