### ISSUE TITLE
Improve session and application state in ASP.NET Core article by adding more details

### ISSUE THREAD

**Issue by amdnaji** [aspnet/Docs#3216]
I think it will be great if we add more information to **session and application state in ASP.NET Core** article
Like 

- What is sticky session

- What is coherent session

- Why sticky sessions affect scalability and complicate web app updates.
Br,

.

**Comment by guardrex** [comment]
https://docs.microsoft.com/aspnet/core/fundamentals/app-state
*aspnetcore/fundamentals/app-state.md*

**Comment by Rick-Anderson** [comment]
closing to work on high pri items.
