### ISSUE TITLE
Explain TFMs

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Docs#323]
Target framework monikers are not documented yet. We should explain the subtleties in `dnx451` vs `net451`, `netcore50` vs `dotnet` etc. Currently, this is information is only available by parsing [blog posts](http://oren.codes/2015/06/09/pcls-net-core-dnx-and-uwp/).

**Comment by Eilon** [comment]
I'm pretty sure this is planned to be covered in the .NET docs. @danroth27 @richlander @davidfowl

**Comment by csharpfritz** [comment]
We're writing this document now.. more details coming before release



Jeff

**Comment by natemcmaster** [comment]
Looking forward to it.

It would still be useful for the ASP.NET docs to link to the article (when complete)

**Comment by Eilon** [comment]
For sure!

**Comment by MisterJames** [comment]
@Eilon @csharpfritz Any progress here? I'm not having much luck getting dnx46 to work, which I expected in the release of Beta6 (details here: https://github.com/aspnet/dnx/issues/2365)

**Comment by Eilon** [comment]
@MisterJames we have a guy looking at the DNX issue you mention.

Regarding the basic concept of these TFMs, `dnxXY` are DNX targets for .NET Framework X.Y, and `dnxcoreXY` are DNX targets for .NET Core (CoreCLR), which currently there's only a `50` version.

ASP.NET 5 requires DNX targets.

**Comment by MisterJames** [comment]
Thanks @Eilon, I'm still digging. I closed 2365 in favor of an easier repro at https://github.com/aspnet/dnx/issues/2367

Let me know if there's anything you need from my end.

**Comment by danroth27** [comment]
TFMs will be covered in some combination of the NuGet and .NET docs. Nothing to document here for ASP.NET. Closing.

**Comment by csharpfritz** [comment]
Information about target frameworks can be found in the NuGet docs at:
http://docs.nuget.org/create/targetframeworks
