### ISSUE TITLE
Create a Security Landing Page / Home Page

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#3254]
There's no top-level content node in our TOC for Security. When you expand it in the navigation, the first element is Authentication, and the first element after that is ASP.NET Core Identity: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity

However, this isn't a good overview of web or ASP.NET Core security, and already assumes that users understand, for instance, the difference between authentication and authorization (which many do not). I think we need a general overview of web security concerns, common terms, common attacks and vulnerabilities. This would link to several of the already-present security articles, but would serve as a landing page for anyone seeking to learn more about ASP.NET Core Security (currently you can hack the URL to go [here](https://docs.microsoft.com/en-us/aspnet/core/security/), but you can't actually get to that URL by clicking links in the navigation of the site).

Suggested reviewers: @blowdart @danroth27

**Comment by Rick-Anderson** [comment]
cc @tdykstra
