### ISSUE TITLE
Outline of all components that need specific web-farm configuration

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#3255]
It's standard practice to deploy web apps on multiple instances with shared resources. It would be helpful to have a consolidated list of components and configuration that need special attention in this scenario:

Needs configuration:
- DataProtection (IDataProtectionProvider)
- Caching (IDistributedCache)
- Databases (EF/SQL)

Dependent Components:
- Authentication - Depends on DataProtection for Cookies, temp state, etc.
- Session - Depends on DataProtection and Caching for the cookie and the data store - https://github.com/aspnet/Session/issues/159
- Identity - Depends on DataProtection, Databases (@haok?)
- TempData provider - Various implementations, some depend on DataProtection, and others depend on Session (@kichalla?)
- Anti-forgery - Depends on DataProtection

Cross link from https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot

`@rick-anderson` edit:
For a web-farm, you need to do these things.
We have all this information, we need to put it together in one doc (web-farm/multi-machine config) with:

* Links to each article
* Notes on what breaks when you don't. That might help SEO

**Comment by Rick-Anderson** [comment]
@Tratcher   can you draft this article and we'll take it from there? We don't have the expertise to write this. cc @danroth27  @tdykstra

**Comment by Tratcher** [comment]
@danroth27 do you want to schedule a meeting for this? Include Hao.

**Comment by Rick-Anderson** [comment]
@Tratcher  meeting sent.

**Comment by Vinhaman** [comment]
I've spent over half a day trying to make my Session Management using the Redis Cache on our .Net Core 1.1 Application. I'm still not doing it on the web farm because it still fails on my Dev Machine with the following:
 ...
            var connectCS = Configuration["ConnectionsString:CS_RedisCache"];
            var redis = ConnectionMultiplexer.Connect(connectCS);
            services.AddDataProtection().PersistKeysToRedis(redis, "Master_DataProtectionKeys");
            services.AddOptions();
            services.AddDistributedRedisCache(option =>
            {
                option.Configuration = connectCS;
                option.InstanceName = "Master_";
            });            

            services.AddSession(options =>
            {
                options.IdleTimeout = TimeSpan.FromMinutes(appSetting.SessionMinutesIdleTimeout);
                options.CookieName = appSetting.SessionCookieName;
            });
....

This seems to to half the trick since on my login controller i have access to a brand new session and set information nicely. When my middleware triggers (when the login is over) the  "context.Session" doesn't exists with the Redis implementation (using services.AddDistributedMemoryCache(); works great)

...
            app.Use(async (context, next) =>
            {
                    //session is not available probably because of the Data Protection...
                    var logged = context.Session.GetBool("Login");
            }
...

I see you guys probably did some beta documentation already that i would be deeply thankfull to try.

**Comment by Tratcher** [comment]
Bump, hit this again today.

**Comment by Tratcher** [comment]
Bump: https://github.com/aspnet/Security/issues/1805

**Comment by guardrex** [comment]
@Tratcher I would have liked to be here by now, but `@DamianEdwards` would like 2.1 issues resolved asap, and we still have a mess of [2.1 samples to update](https://github.com/aspnet/Docs/issues/5495) ... some still *project.json*-based 🤦‍♂️. In addition, a few new 2.1 issues have surfaced since 2.1 RTM.

"a mess" ... I've definitely been hanging around in the Florida panhandle too long! :smile:

I'm going as fast as I can 🏃😅. I guesstimate that it will take a few more weeks to get the samples and the new 2.1 issues squared away.

**Comment by guardrex** [comment]
@Tratcher We're moving this up to **_Next_** :tada:.

**Comment by guardrex** [comment]
@Tratcher 

**Title**: *Host ASP.NET Core in a web farm*
**Description**: Learn how to host multiple instances of an ASP.NET Core app with shared resources in a web farm environment.
**TOC**: aspnetcore\host-and-deploy\web-farm
**UID**: `host-and-deploy/web-farm`

### Outline

* Introduction
* General configuration
   - Process manager/reverse proxy (external links)
   - Hosting bundle/runtime (external links)
   - Mention Azure App Service (external link)
* Host, scheme, IP, and port forwarding (proxy/LB config topic, cross-link both ways)
* Data Protection (IDataProtectionProvider)
* Cookies - Encrypted depends on DP
* Database (EF/SQL) and storage (Azure Blob/Table/Queue Storage)
* Caching (IDistributedCache) - Depends on Redis or database
* Authentication - Depends on DP
* Identity - Depends on DP and database
* Session - Depends on encrypted cookies and caching
* TempData - Depends on Session or encrypted cookies
* Anti-forgery - Depends on DP

Questions, queries, posers ...

* *Database (EF/SQL) and storage (Azure Blob/Table/Queue Storage)* &mdash; Not sure we have more to say than 'set your connection string properly.' What else did you envision for content (or links) here?
* Outline missing anything?
* In addition to getting the sections defined, how does the order look?
* Link as much existing content from other topics as possible, correct?

**Comment by Tratcher** [comment]
Cookies in this context is CookieAuth, it's redundant with your Authentication entry.

**Comment by guardrex** [comment]
Outline modified. I'm set to work on it tomorrow. I anticipate having it Friday morning; but if it lands on Saturday or Sunday, I suppose that would be ok.

**Comment by Tratcher** [comment]
See my outline above. There are things that need configuration (DP, caching), and then there are things that depend on them but don't need any additional config (Auth, Session). The doc should keep these separate so users can focus on changes they need to make.

Database doesn't seem to fit here, it's already a resource external to your application. If anything you may need to introduce a database to exchange data that you were previously storing in memory like caching, app state, etc..

**Comment by Tratcher** [comment]
We may also want a troubleshooting section (or troubleshooting notes in each topic) about what symptoms you'd see if that component wasn't properly configured for multiple agents. E.g. for Auth you would randomly be asked to sign in again depending on which instance you accessed.

**Comment by guardrex** [comment]
Can try *Troubleshoot* as a section. I think devs would find that handy ... go to one spot ... find the symptom and get directed to the cure.

I updated the outline. :point_up:

**Comment by guardrex** [comment]
Roll ...

* Host, scheme, IP, and port forwarding (proxy/LB config topic, cross-link both ways)

... in to one of the sub-categories?

**Comment by Tratcher** [comment]
forwarding isn't directly related to multi agent, it's a general reverse proxy concern. Move it up into the General configuration?

**Comment by guardrex** [comment]
Yes, this is coming along well. I think there will be a PR on Friday afternoon.

... and I'll squeeze an important update in there soon. https://github.com/aspnet/Docs/issues/7589
