### ISSUE TITLE
Remove gulp content from the grunt and gulp article and instead link to the new gulp article

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#326]
We are working on splitting out the gulp content here: https://github.com/aspnet/Docs/pull/307. We will also need to pull out the gulp content from http://docs.asp.net/en/latest/client-side/grunt-gulp.html and instead link to the new article.

**Comment by danroth27** [comment]
@ardalis Can you take care of this as part of merging #307?

**Comment by ardalis** [comment]
@danroth27 will do

**Comment by ardalis** [comment]
@danroth27 I'm going to merge #307 first, then branch from master with that article and update the original.

**Comment by danroth27** [comment]
Sounds fine.

**Comment by ardalis** [comment]
Done. The Grunt content may need a refresh to adjust to beta 5 and/or the release version of VS2015, but with this PR it's organized properly.
