### ISSUE TITLE
Little question about MySqlInitializer 

### ISSUE THREAD

**Issue by Kyoraku** [aspnet/Docs#3260]
Hi, 

I'm trying to use identity within my application and i had a little problem in the MySqlInitializer  
there is a "insert your user here"
`var migrationHistoryTableExists = ((IObjectContextAdapter)context).ObjectContext.ExecuteStoreQuery<int>(
        string.Format(
          "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '{0}' AND table_name = '__MigrationHistory'",
          "[Insert your database schema here - such as 'users']"));`

it's a simplification tip but i'm lost in there what should i put in there plz ? =) 

Thanks a lot, and sorry for my english anyway

**Comment by Rick-Anderson** [comment]
@Kyoraku  I agree it's not clear. Can you create an issue with code you show above and ask that they provide a better hint?  cc @tdykstra
