### ISSUE TITLE
Update Key Management Documentation

### ISSUE THREAD

**Issue by joshbartley** [aspnet/Docs#3273]
The Key Management documentation at ( https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/default-settings#data-protection-default-settings)  does not account for all scenarios.  The four scenarios listed do not account for applications that are load balanced outside of the Azure Web Sites offering. 

I think the documentation should be updated with the following information.

5. For load balanced scenarios, not on Azure Web Sites, a Key Management repository that will store keys out of process is required. The http://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/ package provides Key Management repositories using AzureBlob, Azure Key Management, and Redis.

Also update the paragraph below the four listed options as " The first three options above should good defaults " is a typo I believe.

Below this, the documentation should provide code samples for configuration for the Startup.cs. The current samples are inside the DataProtection samples folder which is not linked and makes it tougher to find. 

I think I can try to write this up and PR this if everyone agrees this is an issue.

**Comment by Rick-Anderson** [comment]
@blowdart  please review this proposed work.

**Comment by blowdart** [comment]
Looks fine to me.

**Comment by guardrex** [comment]
@blowdart @Rick-Anderson I looked at this for #4549.

> The four scenarios listed do not account for applications that are load balanced outside of the Azure Web Sites offering.

The list pertains to this line from the topic ...

> The app attempts to detect its operational environment and handle key configuration on its own.

i.e., "detect[ion] ... [and] ... configuration [without dev attention]."

These statements are written from the app's/DP's perspective ... what the app can and can't do on its own for key management ... not from the developer's perspective. It isn't currently written as a list of all of the ways that key management can be handled; it's more like these first three are handled for you and the fourth isn't. The fourth covers cases where the app will lose its keys. The line immediately under the list refers directly to the overview, where `PersistKeysToFileSystem` is covered.

It could be re-written to address out-of-process providers, but my current understanding is that topics that describe KV and Redis won't be initiated until 2.1. We'd also need to bring in a sixth entry for custom key extensibility approaches (@blowdart, you may recall my *RexHacks*:tm: to do key management with Azure Table Storage in ancient times! lol). We'd need a seventh entry for `PersistKeysToFileSystem`.

> Below this, the documentation should provide code samples for configuration for the Startup.cs.

I kind'a doubt that would work well here. There will be a topic for each provider in the future, so I think the full topics would be better to address each configuration. Those could be linked here as *See also* topics.

To address what I can now, I'm adding a *See also* section to #4549 with a link to the key extensibility topic. I already added a line about Docker, and I'm adding another line that external providers are useful in web farm scenarios that also surfaces `PersistKeysToFileSystem`.

**Comment by joshbartley** [comment]
Thanks @guardrex Expanding on the documentation will be good. I just know a few people on the enterprise side look at these docs for on-premise enterprise deployments and that causes some friction in adoption on those environments. I know it caused me some trouble trying to get something going when I didn't have a local Redis server available. Thanks!
