### ISSUE TITLE
Add technology names to doc titles and h1's to improve discoverability in search

### ISSUE THREAD

**Issue by wadepickett** [aspnet/Docs#3278]
Task: 
Improve search
Add ASP.NET technology names to doc titles and H1's where feasible across the entire doc set. Both ASP.NET Core and ASP.NET.

Background:
This seems trivial but it makes a difference. Where we have corrected this so far we see around a 40% increase in clicks from search with indications that the community is getting to where they need to be rather than having to visit pages and read details to determine if the topic is applicable to their need.

Here is an example: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing
Page title (metadata): You can do the following either across a content set via a file in the repo, or for each article individually as it appears was done so far.
`Change: title: Routing to Controller Actions`
`To:         title: Routing to Controller Actions - ASP.NET Core MVC`
  [Note hyphen in place of text: You don’t need to add a complete phrase.]
H1:
`Change: # Routing to Controller Actions in ASP.NET Core MVC`
`To:         # Routing Controller Actions in ASP.NET Core MVC`

Verify the rich snippet results in search engines on a few as you go to make sure we are getting the results.

**Comment by Rick-Anderson** [comment]
@rachelappel @scottaddie  let;s try to do this when reviewing articles.

**Comment by scottaddie** [comment]
> Add ASP.NET technology names to doc titles and H1's where feasible across the entire doc set. Both ASP.NET Core and ASP.NET.

For the sake of clarity, is @wadepickett referring to the "title" metadata value when he says "doc titles"?

**Comment by Rick-Anderson** [comment]
>For the sake of clarity, is @wadepickett referring to the "title" metadata value when he says "doc titles"?

I think so. We also need to honor the character limit of title meta-data and H1's. @tdykstra  knows what those limit are.

**Comment by tdykstra** [comment]
59 and 100 -- https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-seo-basics?branch=master#page-title-description-and-friendly-filename

**Comment by Rick-Anderson** [comment]
@guardrex  how hard would this be to complete?

**Comment by rachelappel** [comment]
"doc titles and H1's " so that should be both metadata and the # line

**Comment by guardrex** [comment]
I was working this issue over on :point_right: https://github.com/aspnet/Docs/issues/5280

**Comment by guardrex** [comment]
@rachelappel Yes, I'm doing that over on #5280 ... I just got temporarily slammed with other issues. I can get back to that soon ... maybe even this evening.

**Comment by guardrex** [comment]
The actual comment on that issue that shows what the script is setup to check is this one :point_right: https://github.com/aspnet/Docs/issues/5280#issuecomment-369466835
