### ISSUE TITLE
SecretManager rename

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Docs#328]
SecretManager package has been renamed to Microsoft.Framework.SecretManager. So the new way to install it is ```dnu commands install Microsoft.Framework.SecretManager```

**Comment by Eilon** [comment]
@BrennanConroy can you send a PR to fix that? I think it's mentioned in only a couple of docs.

**Comment by Rick-Anderson** [comment]
@BrennanConroy @Eilon  I'll do a PR on http://docs.asp.net/en/beta5/security/app-secrets.html - That's the critical doc.

**Comment by BrennanConroy** [comment]
If we're updating every milestone then this is for beta6

**Comment by danroth27** [comment]
We should be using the correct package ID for the Secret Manager tool (Microsoft.Extensions.SecretManager) everywhere at this point.
