### ISSUE TITLE
This is the printed version of the documentation

### ISSUE THREAD

**Issue by SetTrend** [aspnet/Docs#3284]
### I printed the documentation and had it bound. This is the result:
<br/>

![p1000080](https://cloud.githubusercontent.com/assets/9283914/25536031/7ee6c52c-2c39-11e7-8d2a-80976e60b567.png)

![p1000082-1](https://cloud.githubusercontent.com/assets/9283914/25536147/f1dc92a0-2c39-11e7-8ebc-7a581bb21ab4.png)

![p1000084-1](https://cloud.githubusercontent.com/assets/9283914/25536150/f4db0b6c-2c39-11e7-95da-1974b19afffd.png)

## First of all: My compliments to all the authors in creating such valuable piece of information.

<br/>

However, given this large chunk of information: wouldn't it be valuable to seek for ways to drain a bit of complexity out of ASP.NET Core?

I mean, there are literally hundreds of documentations around: NodeJS, grunt, gulp, bower, Webpack, React, TypeScript, ECMAScript, AngularJS, jQuery, Visual Studio, Team Foundation Server, SQL Server, Entity Framework (Core), ODATA, OAuth2, Docker, IIS, Hyper-V, Azure, PowerShell, HTML5, CSS3, LESS, SASS .......

Trying to learn all these and stay updated with them all becomes a war that's not to win ... Shouldn't we strive to keep things more compact?

Just a thought ...

**Comment by Rick-Anderson** [comment]
@SetTrend  thanks for the thought. CC @tdykstra
