### ISSUE TITLE
Document that deployment requires stopping the app

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#3301]
@danroth27  what doc should that go in besides https://docs.microsoft.com/en-us/aspnet/core/publishing/iis

**Comment by Rick-Anderson** [comment]
@vijayrkn   what doc should that go in besides https://docs.microsoft.com/en-us/aspnet/core/publishing/iis ? It wouldn't apply to https://docs.microsoft.com/en-us/aspnet/core/publishing/web-publishing-vs
