### ISSUE TITLE
WebListener doc does not align with github repo

### ISSUE THREAD

**Issue by ferrx** [aspnet/Docs#3333]
The github repo for aspnet/WebListener now sits at aspnet/HttpSysServer (name change for core 2?)

Several links and documented code in this guide https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/weblistener.md are out of date and very confusing.

I'm trying to keep my cool, but learning aspnet/dotnet core is becoming difficult because of the constantly moving parts like this. I need documentation that is robust and accurate. Where is the equivalent of this type of MSFT documentation for core -- https://msdn.microsoft.com/en-us/library/system.math(v=vs.110).aspx I mean, if I want to know for example, what the default value is for AuthenticationManager.AllowAnonymous in WebListener's options, how would I figure that out?

I do see that there is an API ref [here](https://docs.microsoft.com/en-us/aspnet/core/api/), but no sign of WebListener. Is there something about WebListener that causes it to be excluded? Has it not met a certain release phase? Is it in beta?

**Comment by davidfowl** [comment]
WebListener was recently renamed in 2.0 to avoid confusion with the existence of HttpListener in .NET Core 2.0.

**Comment by ferrx** [comment]
@davidfowl Is there a reason it's not found in the api docs? https://docs.microsoft.com/en-us/aspnet/core/api/

Looks like the original issue I raised was corrected by @tdykstra so I may need to create a new issue to discuss that.

**Comment by davidfowl** [comment]
My guess is because it's 2.0.0-preview1. I'd assume it'll all be there when it ships RTM
