### ISSUE TITLE
Should I use WebListener or Kestrel with IIS integration to self host Web Api on Windows?

### ISSUE THREAD

**Issue by nehmebilal** [aspnet/Docs#3365]
I've been doing some research to figure out the best option to self host ASP.NET Web Api on Windows. Some articles recommend using WebListener for client facing services and other state that Kestrel is faster and can be used behind an IIS proxy.

What is the better option? 

I understand that Kestrel has the benefit of being cross-platform but I am only deploying on Windows and mainly concerned about performance.

Thanks,
Nehme

**Comment by Rick-Anderson** [comment]
@danroth27  please respond.
@nehmebilal  can you wait for ASP.NET Core 2.0? If so, I think Kestrel might be a good option.

**Comment by danroth27** [comment]
We generally recommend using Kestrel behind IIS on Windows. However, Kestrel is not supported as an edge server in 1.1 (it will be in 2.0), so if you don't want to use IIS then use WebListener. Kestrel by itself is generally faster than WebListener, but if you put Kestrel behind IIS it will be slower than plain WebListener as things currently stand.

**Comment by nehmebilal** [comment]
Thanks @danroth27!
