### ISSUE TITLE
Issues with KeyVaultConfigProviderSample

### ISSUE THREAD

**Issue by olavt** [aspnet/Docs#3369]
I have tried to follow the instructions and running this sample:

https://github.com/aspnet/Docs/tree/master/aspnetcore/security/key-vault-configuration/sample

But, there seems to be issues with it:

1) The sample crashes with an exception:

"Operation \"list\" is not allowed by vault policy"

Nowhere is it mentioned that "list" access should be granted to the application.

2) There seems to be some confusion related to the naming of a key:

Instructions says:

Create key vault secrets 
MySecret: secret_value_1
Section--MySecret: secret_value_2

This is used in the code:

Configuration["Section:MySecret"]

What is the link between: "Section--MySecret" and "["Section:MySecret"]"?

**Comment by GuardRex** [comment]
@Rick-Anderson @tdykstra I'm working on the updates now for 2.0. Let's piggyback the 2.0 update on this issue, and I'll knock them both out.

@olavt The part of the topic that pertains to permissions is this bit ...

> Authorize the app to access the key vault. When you use the `Set-AzureRmKeyVaultAccessPolicy` PowerShell cmdlet to authorize the app to access the key vault, provide `List` and `Get` access to secrets with `-PermissionsToKeys list,get`.

However, I didn't add that level of detail to the sample itself (in its *README.md* file at https://github.com/aspnet/Docs/tree/master/aspnetcore/security/key-vault-configuration/sample), where it merely states ...

> Authorize the application to use the secrets

I'll fix that on this pass.

On your point 2: I agree with you: It should have more text here to explain. The current language assumes that the reader will understand the replacement of `--` with the colon that's normally used when accessing configuration values. The topic overly relies on the reader having seen/remembered in the [Configuration topic: Simple configuration section](https://docs.microsoft.com/aspnet/core/fundamentals/configuration#simple-configuration) ...

>Configuration consists of a hierarchical list of name-value pairs in which the nodes are separated by a colon. To retrieve a value, access the Configuration indexer with the corresponding item’s key: [followed by an example of where the colon is used to obtain a `subsection:suboption1`]

I'll work on this problem, too, on this next update to the topic.

Sorry for the confusion. The current version was the first version of the topic, and it takes a little bit of time and an update or two to make a topic really shine. Thanks for reporting the issues you found with the topic. I'll ping you on the PR when I submit it, and then you can review the changes if you like.

**Comment by Rick-Anderson** [comment]
@GuardRex  sounds great.
