### ISSUE TITLE
Handling secrets on Azure

### ISSUE THREAD

**Issue by weinong** [aspnet/Docs#337]
it would be nice to explain the best practice to handle secrets on Azure.
One way to do that I think is through environment variable which can be defined in the app settings on Azure portal.

**Comment by Rick-Anderson** [comment]
@weinong I agree, however we need to be careful and not show an Azure bias on ASP.NET 5. If @danroth27 approves, I can add an Azure section.

**Comment by danroth27** [comment]
http://docs.asp.net/en/latest/security/app-secrets.html
