### ISSUE TITLE
Create an RSS Feed for New/Updated Docs

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Docs#3379]
There used to be an RSS feed at http://docs.asp.net/en/latest/rss.xml created in https://github.com/aspnet/Docs/issues/1822 but it seems to have stopped working. Please bring it back, it used to be a great resource to stay up to date with ASP.NET Core and EF.

**Comment by Rick-Anderson** [comment]
@tdykstra  @danroth27  do you know about the rss feed?

**Comment by tdykstra** [comment]
I don't.  Looks like a relic of readthedocs that we didn't implement in docs.ms.com after migration

**Comment by Rick-Anderson** [comment]
@mairaw  @dend  should we consider adding RSS feed?

**Comment by mairaw** [comment]
You can track this issue on our UserVoice site: https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/16608964-rss-feed
