### ISSUE TITLE
2.0 Release notes

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3384]
- [x] New doc aspnetcore-2.0.md following pattern set in aspnetcore-1.1.md
- [x] Add 2.0 doc to TOC, taking 1.1's place and moving 1.1 down.

  From

  >  * [1.1 Release notes](aspnetcore-1.1.md)
  >    * [Earlier release notes](https://github.com/aspnet/home/releases)
  >    * [VS 2015/project.json docs](https://docs.microsoft.com/dotnet/articles/project-json)

  to:

  >  * [2.0. Release notes](aspnetcore-2.0.md)
  >    * [1.1 Release notes](aspnetcore-1.1.md)
  >    * [Earlier release notes](https://github.com/aspnet/home/releases)
  >    * [VS 2015/project.json docs](https://docs.microsoft.com/dotnet/articles/project-json)

Initial draft created by #3687 will require ongoing updates as documentation for 2.0 is written.

**Comment by Rick-Anderson** [comment]
@tdykstra can this be closed?

**Comment by tdykstra** [comment]
As you finish additional 2.0 docs it would still be best to add links to them in this doc, but we don't need to hold the issue open for that.
