### ISSUE TITLE
Authentication changes in 2.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3386]
Auth Affected docs:

- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/
- https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie
- Everything under Azure AD.  23:45  Per @ danroth27 - update them all for 2.0 if you can't version them.

**Comment by scottaddie** [comment]
Duplicate of https://github.com/aspnet/Docs/issues/3777
