### ISSUE TITLE
2.0 - App Insights integration

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3389]
App Insights integration

[Hosting startup and AI](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0#hosting-startup-and-application-insights)

**Comment by tdykstra** [comment]
Assigned to @bwren

**Comment by hardhub** [comment]
Where to read details about this?

I have found only this info:
Hosting environments can now inject extra package dependencies and execute code during application 
startup, without the application needing to explicitly take a dependency or call any methods. This feature can be used to enable certain environments to "light-up" features unique to that environment without the application needing to know ahead of time.

In ASP.NET Core 2.0, this feature is used to automatically enable Application Insights diagnostics when debugging in Visual Studio and (after opting in) when running in Azure App Services. As a result, the project templates no longer add Application Insights packages and code by default.

**Comment by tdykstra** [comment]
@hardhub [@]bwren will be documenting the Application Insights integration.  No ETA yet.

**Comment by bitbonk** [comment]
Until the docs are done, where can I learn, how this works? Any hint?

**Comment by normj** [comment]
I found this blog post interesting in understanding how the injection works. http://www.hishambinateya.com/istartup-vs-ihostingstartup

**Comment by Rick-Anderson** [comment]
@bwren can we help you get started on this? Do you have an ETA for this.

**Comment by bwren** [comment]
@Rick-Anderson Sorry, there was some confusion on this.  Adding @mrbullwinkle who now owns App Insights.  I'll work with him to get this addressed.

**Comment by scottaddie** [comment]
@mrbullwinkle Are there any updates to provide on this? Anything you need from me?

**Comment by mrbullwinkle** [comment]
@scottaddie it is on my internal VSTS board and I had originally planned to have it done this month. It got bumped by a few other tasks that I had not anticipated. I have two days blocked out next week to start working on this. I will send you an update 11/3 which I am tentatively targeting to have a first draft for your feedback/review.

**Comment by scottaddie** [comment]
@mrbullwinkle Just following up on this and hoping to get a status. Anything I can do to help?

**Comment by Rick-Anderson** [comment]
per @mrbullwinkle:
I have added tasks to the App Insights backlog:

https://mseng.visualstudio.com/TechnicalContent/_workitems?id=1138727

https://mseng.visualstudio.com/TechnicalContent/_workitems?id=1138735

cc @anthonychu

**Comment by Rick-Anderson** [comment]
cc @cecilphillip

**Comment by Rick-Anderson** [comment]
@mrbullwinkle can you give us an ETA on this? @scottaddie  is willing to help.

**Comment by mrbullwinkle** [comment]
@Rick-Anderson we have new App Insights content coming out for .Net Core next week: 1/22-1/26 and 1/29-31. Goal is to have all the content requests from your team complete by month end.

**Comment by scottaddie** [comment]
@mrbullwinkle Any updates to provide?

**Comment by mrbullwinkle** [comment]
@scottaddie Apologies again for the previous delay. I am working on the new App Insights .NET Core content right now,

**Comment by mrbullwinkle** [comment]
This issue is addressed in this doc: [https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-core](https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-core)
