### ISSUE TITLE
ASP.NET Core metapackage in 2.0

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3390]
Affected docs - any doc that tells you how to add packages

When using ASP.NET Core, use the single package. If your using the .NET Framework, you can't use this single package.

- [ ] Perf increase from ASP.NET Core/EF Core included with .NET Core. You don't need to include these packages, they are in the runtime. (see 5:30 into the video) - Publishing is faster. Startup perf is better.

**Comment by Rick-Anderson** [comment]
dup of #3449
