### ISSUE TITLE
migration/http-modules "Migrating HTTP handlers and modules "

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3405]
- [ ] LiveFyre comments 
  - [ ] The suggested substitute for Request.Url and Request.RawUrl is incorrect; according to the documentation here: https://msdn.microsoft.com/en-us/library/system.web.httprequest.rawurl(v=vs.110).aspx "The raw URL is defined as the part of the URL following the domain information." Request.RawUrl returns the URL's path and query, whereas httpContext.Request.GetDisplayUrl() returns the full URL.
  - [ ] I miss the HttpRequest.AppRelativeCurrentExecutionFilePath property in the "Migrating to the new HttpContext" section

**Comment by Rick-Anderson** [comment]
@tdykstra 	move to integrated issue.
