### ISSUE TITLE
Improve presentation of MVC tutorials in TOC

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3407]
Issues with TOC and doc titles:

* The three Web API tutorials are represented differently in the TOC -- one shows up once, one shows up twice, one shows up not at all. 
* The various getting started tutorials have different titles that make it hard to tell what's the difference between them -- "Building your first ...", "Create a...", "Getting started...", "Introduction to ..."
* Some of the TOC titles are out of sync with doc titles
* Some of the doc titles don't follow SEO length limits
* We use gerunds everywhere in TOC (Building ... Getting ... Handling ... Rendering) but current guidance prefers to avoid them.

Suggestions for the MVC tutorials:

* Doc H1 headings:  standardize on "Create a {app type} with {IDE}" or "Get started with {app type plural} and {IDE}
  * Create an ASP.NET Core MVC web app with Visual Studio for Windows
  * Create an ASP.NET Core MVC web app with Visual Studio Code
  * Create an ASP.NET Core MVC web API with Visual Studio for Mac
  * Create an ASP.NET Core MVC web API with Visual Studio for Windows
  * Create an ASP.NET Core MVC web API with Visual Studio Code
  * Get started with ASP.NET Core MVC and Entity Framework
* TOC titles
  * Create an ASP.NET Core MVC web app with VS for Windows
  * Create an ASP.NET Core MVC web app with VS Code
  * Create an ASP.NET Core MVC web API with VS for Mac
  * Create an ASP.NET Core MVC web API with VS for Windows
  * Create an ASP.NET Core MVC web API with VS Code
  * Get started with ASP.NET Core MVC and Entity Framework Core
* Doc metadata titles:
  * Create an ASP.NET Core MVC web app
  * Create an ASP.NET Core MVC web API with VS for Mac
  * Create an ASP.NET Core MVC web API with VS for Windows
  * Create an ASP.NET Core MVC web API with VS Code
  * Get started with ASP.NET Core MVC and Entity Framework Core

The EF series is at present the exception for which we have only a VS for Windows variant, so I'm thinking we just leave off the IDE from the title for now.

**Comment by Rick-Anderson** [comment]
@tdykstra   Shouldn't the doc metadata title be the same as the H1?

**Comment by tdykstra** [comment]
@Rick-Anderson No, the H1 is supposed to expand on the title, provide more information than the title.  Typically that's more than just expanding on an abbreviation, but I thought that might work in this case.

**Comment by Rick-Anderson** [comment]
@tdykstra  I like to put Web API up front - otherwise it's hidden

- Create a Web API with ASP.NET Core MVC and Visual Studio for Mac
- Create a Web API with ASP.NET Core MVC and Visual Studio for Windows
- Create a Web API with ASP.NET Core MVC and Visual Studio Code

**Comment by tdykstra** [comment]
Sure, and do the same with web app for the MVC UI version then.

**Comment by Rick-Anderson** [comment]
@tdykstra  can we drop MVC - the title is pretty long

- Create a Web API with ASP.NET Core ~~MVC~~ and Visual Studio for Mac
- Create a Web API with ASP.NET Core ~~MVC~~ and Visual Studio for Windows
- Create a Web API with ASP.NET Core ~~MVC~~ and Visual Studio Code

**Comment by Rick-Anderson** [comment]
Or maybe just drop MVC from the title

**Comment by tdykstra** [comment]
For the TOC under MVC you can drop ASP.NET Core too.  But I believe one of these docs shows up in another part of the TOC where you might want to keep both.

**Comment by tdykstra** [comment]
For the doc title you might want to keep ASP.NET Core and MVC both but could drop MVC

**Comment by Rick-Anderson** [comment]
see also #3542
