### ISSUE TITLE
Dependencies - not installed

### ISSUE THREAD

**Issue by JerryPierre** [aspnet/Docs#345]
Using Visual Studio 2015 Enterprise TRM on Windows 8.1

on step 12.Save the bower.json file.

I adding "jquery": "2.1.3", "bootstrap": "3.3.2" and saved it but I get "Dependencies - not installed"
![image](https://cloud.githubusercontent.com/assets/1745045/8832781/ce235114-305f-11e5-9f23-5e967a149112.png)

So the bower_components directory was not created but without running Task Manager both Jquery and Bootstrap was deployed automatically to the wwwroot. There are a number of thinks that seem to be inconstant. Is your lab based on the latest release?

Any help would greatly be appreciated,

JP

**Comment by Rick-Anderson** [comment]
@JerryPierre   step 12 of what doc?

**Comment by danroth27** [comment]
http://docs.asp.net/en/latest/client-side/bower.html

**Comment by Rick-Anderson** [comment]
@noelatfalafel  can you fix this?

**Comment by danroth27** [comment]
Shouldn't be an issue anymore - the Bower article has gone through multiple revisions at this point.
