### ISSUE TITLE
PROPOSAL: Update some documentation pages to use Visual Studio 2015 or Visual Studio 2017

### ISSUE THREAD

**Issue by eriawan** [aspnet/Docs#3452]
## General

A proposal to update some doc pages to use VS 2015 or VS 2017 instead of using VS 2013, because VS 2013 is not supported anymore.

## Issues with Existing Topics

Most topics in the documentations are using Visual Studio 2012 or 2013. Both Visual Studio 2012 and Visual Studio 2013 are now end of support, according to these Microsoft's product lifecycle articles:

1. [Visual Studio 2013 lifecycle](https://support.microsoft.com/en-us/lifecycle/search/17351)
2. [Visual Studio 2012 lifecycle](https://support.microsoft.com/en-us/lifecycle/search/16677)

These are samples of pages (and the subtopics below them) that needs to be updated:

1. [Getting Started with ASP.NET Web API](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/)
2. [ASP.NET Web API Testing and Debugging](https://docs.microsoft.com/en-us/aspnet/web-api/overview/testing-and-debugging/)
3. [Host ASP.NET Web API 2 in an Azure Worker Role](https://docs.microsoft.com/en-us/aspnet/web-api/overview/hosting-aspnet-web-api/host-aspnet-web-api-in-an-azure-worker-role)
4. [Web API Routing](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/)

The downside of this update means that those pages will be updated to only include ASP.NET MVC 5 and later, because VS 2015 only supports ASP.NET MVC 5 or later by default. (**Correct me if I'm wrong on this one, guys**)
I'm assuming because of this version I see this ASP.NET MVC's nuget package installed when I create new ASP.NET MVC on VS 2015 Update 3 with .NET 4.6.2 installed:

![image](https://cloud.githubusercontent.com/assets/8773147/26713503/3c1ac832-4797-11e7-9ac6-30ab92cb7f75.png)

## Descriptions of further actions: (if this proposal gets accepted 🙂 )

1. I will create PR linked to this issue with the TODO list model to change/update the above topics to use VS 2015/2017 instead
2. The updated pages within the TODO list will be synched with the MVC used supported by VS 2015 and VS 2017, which is MVC 5.

I welcome suggestions 😄

**Comment by Rick-Anderson** [comment]
@eriawan  We would really appreciate having these updated. Rather than one PR with several articles, can you do a PR per article?

@danroth27 @tdykstra - Should @eriawan  use VS 2015 or VS 2017? I think the only difference is the presentation of available templates. VS 2015 users should be able to follow VS 2017 instructions.

**Comment by tdykstra** [comment]
@Rick-Anderson Agree -- best to use VS 2017.

**Comment by eriawan** [comment]
@Rick-Anderson Ok, I'll do a PR per article.

> @Rick-Anderson Agree -- best to use VS 2017.

Is this finalized/agreed? If this is OK, I'll do these:
1. create a new issue with TODO list, (Because I need to have a separate issue to track those pages I'm going to update)
2. linked the new issue to this issue, then close this issue. 
3. Create multiple PRs for separate pages with updated content for VS 2017 based on TODO list of previous first point/issue

Thanks for the reply, guys! 👍

**Comment by Rick-Anderson** [comment]
@eriawan  Sounds great.

**Comment by eriawan** [comment]
@Rick-Anderson thanks! I have created a separate umbrella task for this. 
I'm closing this proposal.
