### ISSUE TITLE
IAuthorizationService somehow incomplete

### ISSUE THREAD

**Issue by frankabbruzzese** [aspnet/Docs#3453]
I think the actual definition of `IAuthorizationService `is somehow incomplete, since the `AuthorizeAsync `method handles properly just  in-memory resources. More specifially, if the resource has already been loaded in memory from a DB it may give an answer to all needed authorization queries, but what if one would like to load and page from a DB  just all resources the current user has the permission to read? 

An in-memory test would be inadequate, since it would force loading uneusefull resources in memory(also the ones the user can't read), and would interfere with a LinQ skip/take paging.  

Accordingly, the developer would be forced to spread authorization rules all over the DB queries instead of encapsulating them only into `IAuthorizationHandler `implementations! In other word with the actual implementation the user is forced to break `IAuthorizationHandler  `encapsulation, loosing most of modularity-related advantages of the `IAuthorizationService`/`IAuthorizationHandler  `framework.

The problem I sketched shortly might be solved by adding a new method to `IAuthorizationService `, say something like:

`Expression<Func<T, bool>> AuthorizePredicate<T>(ClaimsPrincipal user, IEnumerable<IAuthorizationRequirement> requirements)`

That would return a LinQ predicate the developer may insert in a LinQ `Where` to filter out all not authorized resources. Clearly, also the `IAuthorizationHandler `should be enriched properly to give the devolper the possibility to define all needed predicates. The predicate returned by `AuthorizePredicate `should be the "logical or" of all predicated provided in all relevant `IAuthorizationHandlers`.

**Comment by davidfowl** [comment]
Why did you file this on the docs repository instead of https://github.com/aspnet/Security?

**Comment by frankabbruzzese** [comment]
@davidfowl , My error! Sorry I'll move it.
