### ISSUE TITLE
Model always null when you using PUT request.

### ISSUE THREAD

**Issue by 50774283** [aspnet/Docs#3462]
dotnet version 2.0.0-preview1-005977

namespace TodoApi.Controllers
{
    [Route("api/[controller]")]
    public class TodoController:Controller
    {
        public ITodoRepository TodoItems{get;set;}

        public TodoController(ITodoRepository todoItems)
        {
            this.TodoItems=todoItems;
        }     

        [HttpPut("{id}")]
        public IActionResult Update(string id,[FromBody] TodoItem item)
        {
          // this item always is null when you using PUT request
 //I have double check and make sure the Fiddler 100% sent data to my url  address and request verb is PUT.  asp.net core 1.0 work fine.

            if(item==null || item.Key!=id) return BadRequest();
            TodoItem todo=this.TodoItems.Find(id);
            if(todo==null) 
            {   
                return NotFound();
            }
            this.TodoItems.Update(item);
            return new NoContentResult();
        }
    }
}

**Comment by Rick-Anderson** [comment]
@50774283  not sure what you're doing wrong but Web API PUT is working fine. We're no longer using this sample in the docs.
