### ISSUE TITLE
Add "Calling the Web API with Javascript and jQuery" to "Create a Web API with ASP.NET Core"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3463]
The legacy version of the [Intro to Web API](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api) tutorial has a section [Calling the Web API with Javascript and jQuery](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api#calling-the-web-api-with-javascript-and-jquery). Add the client side access section to the [ASP.NET Core WebAPI](https://docs.microsoft.com/en-us/aspnet/core/tutorials/#building-web-apis) tutorials.

Should the sample use jQuery?

Perhaps we should just point to #3261 
@danroth27  please review.

**Comment by danroth27** [comment]
For a simple getting started tutorial I think using jQuery to make a couple of GET requests is fine. For a full SPA example I would Angular.

**Comment by Rick-Anderson** [comment]
@isaac2004  no, I plan on adding the JavaScript and jQuery calls that exist in the legacy Web API sample.

**Comment by Rick-Anderson** [comment]
@isaac2004 would you be interested in doing this? I think a followup of [Create a Web API](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api) that had [Calling the Web API with Javascript and jQuery](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api#calling-the-web-api-with-javascript-and-jquery)

**Comment by isaac2004** [comment]
@Rick-Anderson I can take a look at this.

**Comment by isaac2004** [comment]
@Rick-Anderson would it make sense to take that jQuery section from that older doc, turn it into an include and put it in all of the web api pages? You could than reuse the same sample code (as JS won't change unless you want to show fetch() or something) in the following places

* [Get Started with ASP.NET Web API 2 (C#)](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api)
* [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc)
* [Create a Web API with ASP.NET Core and Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api-mac)
* [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api)

If that works I will do that and submit a PR shortly.

**Comment by Rick-Anderson** [comment]
@isaac2004  I don't think you can share includes across aspnet and aspnetcore. Why don't you make an include and share it with the last 3. No need to change anything.
