### ISSUE TITLE
Document Options 2.0 changes

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#3469]
We'd like to document the changes we made for Options in 2.0, namely
IOptionsSnapshot
IOptionsCache
IOptionsFactory

Please ping me for more details, I can help with the content

**Comment by Rick-Anderson** [comment]
[IOptionsSnapshot for 1.1](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration#ioptionssnapshot)

**Comment by Tratcher** [comment]
https://github.com/aspnet/Options/issues/217

**Comment by HaoK** [comment]
We should make sure to have a section about how to register named options that use DI

**Comment by HaoK** [comment]
High level overview of Options 2.0 (focus on new stuff/changes from 1.x):

`IOptions<TOptions>` - Mostly unchanged, still focused on singleton static options usage, where the value of an option does not change.  In 2.0 the implementation was switched to use the new `IOptionsFactory` but functionally there shouldn't be any difference.  Also supports the new `IPostConfigureOptions`

`IOptionsMonitor<TOptions>` - This is mostly unchanged similar to `IOptions`, it was updated to support named options, and also uses `IOptionsFactory`, but it remains the way to get the most up to date options, as it provides support for reloadable options, and change notifications.  Also supports the new `IPostConfigureOptions`

`IOptionsSnapshot<TOptions>` - This type was reimplemented in 2.0 with some subtle differences.  In 1.x, this would be a snapshot of `IOptionsMonitor<TOptions>` and would update automatically whenver the montior triggered changes.  In 2.0, this was repurposed to be used for options with the lifetime of the request.  TOptions will be computed once per request, and cached for the lifetime of the request, but each request will get a new instance that will be recomputed the first time its asked for.  Also supports the new `IPostConfigureOptions`

`IConfigureOptions<TOptions>` - This was the only way to configure options in 1.x, it continues to behave similarly, with a few wrinkles from `IConfigureNamedOptions`, it has a single method `void Configure(TOptions options)`

`IConfigureNamedOptions<TOptions>` - This dervies from `IConfigureOptions<TOptions>` and is how we added on named options support.  It has a new method: `Configure(string name, TOptions options)`.  Rather than breaking `IConfigureOptions` we added this new interface and the `IOptionsFactory` does the right thing.  There's new overloads of `Configure` that take a name to target, and also an overload that configures all instances `ConfigureAll`.  Internally, null name means target all instances, while the default name maps to `Options.DefaultName`.

`IPostConfigureOptions<TOptions>` - New in 2.0, we added this as a way to configure options after the normal configuration has occurred.  These are equivalent to `IConfigureNamedOptions` but all PostConfigures run after the Configures.  There's also the corresponding sugar to add these via `services.PostConfigure[All](name, o => { })`

`IOptionsFactory<TOptions>` - New in 2.0, This is what's responsible for creating new options instances.  It has a single `TOptions Create(string name)` method.  The default implementation takes all registered `IConfigureOptions` and `IPostConfigureOptions`, and runs all the configures first, followed by the post configures.  It distinguishes between `IConfigureNamedOptions` and `IConfigureOptions`, and will only call the old `IConfigureOptions` if the name == `Options.DefaultName`.  This is how we preserved backwards compatability, we treat old 1.x nameless `IConfigureOptions` as all targeting `Options.DefaultName`.

`IOptionsMonitorCache<TOptions>` - New in 2.0, this exposes the cache that the `IOptionsMonitor` uses, this is how to invalidate options instances in the monitor so the value will be recomputed (`TryRemove(string name)`) and values can be manually introduced as well via `TryAdd(string name)`.  The `Clear()` method is also there if all named instances should be recreated on demand.

**Comment by HaoK** [comment]
@rachelappel I added an overview of the new changes to options in 2.0. Let me know if you want me to expand any areas, or if you need me to provide any example usages for any of these.

cc @davidfowl @ajcvickers @divega as FYI,

**Comment by guardrex** [comment]
@Rick-Anderson 
* Do you want me to use tabs to distinguish the 1.1 vs. 2.0 features?
* For new 2.0-only features mark them as such? ... for example using language like:
   * In ASP.NET Core 2.0+, ...
   * (new in ASP.NET Core 2.0) or (new in 2.0)
   * Requires ASP.NET Core 2.0 or later. (btw- We're going with "or later" in these cases, correct?)
* I think (guessing) that the new content can fit into the Configuration topic with a bit of reorganization of options-related content: one main 2nd level heading with 3rd level headings for features. The sample requires an update for named options.

**Comment by Rick-Anderson** [comment]
@guardrex 
Yes, use tabs to distinguish

I'd go with "Requires ASP.NET Core 2.0 or later."
Yes, use later, not higher.
