### ISSUE TITLE
ASP.NET Core (.NET Framework) - 4.5.2 - Localization

### ISSUE THREAD

**Issue by onyand** [aspnet/Docs#3483]
I have implemented localization on my project using the cookies option to persist user selection. The home page launches with the selected culture successfully. However, navigation to other pages reverts back to the default language (English). 
An interesting pattern noted is that the scaffolds for "Create" method in all pages when invoked select the correct language specified. I have followed the steps in the link https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization unsuccessfully. 

NOTE: I initially created my ASP.NET Core project with ASP.NET Core (.NET Core) and Localization was working properly. I had to abandon in it and start afresh with ASP.NET Core (.NET Framework) because I ran into a scaffolding error which had no known solution.    @RickAndMSFT, @shanselman kindly assist

**Comment by Rick-Anderson** [comment]
@onyand  please create the simplest possible project that reproduces the problem. Create a new project using the templates and add localization. Don't change the generated code except to add localization. Create an issue in https://github.com/aspnet/localization

**Comment by Rick-Anderson** [comment]
@onyand  provide fiddler traces to show what's going wrong.

**Comment by onyand** [comment]
@Rick-Anderson I have managed to sort out the issue. I changed my framework from 4.5.2 to 4.6 and it worked. Thanks!

**Comment by Rick-Anderson** [comment]
Why aren't you using .NET Core?
