### ISSUE TITLE
New Topic Proposal: Client-Side Development -> Visual Studio Extensibility -> Task Runner Explorer

### ISSUE THREAD

**Issue by raquelsa** [aspnet/Docs#349]
This topic will describe how to get started on writing a Task Runner Explorer extension and will point to code samples from our Grunt and Gulp extensions.

**Comment by danroth27** [comment]
@madskristensen Do you want this to live on docs.asp.net or on your VS site?

**Comment by Rick-Anderson** [comment]
@Erikre please review.

**Comment by danroth27** [comment]
We cover the Task Running Explorer in various places in the client-side docs. Ex. http://docs.asp.net/en/latest/client-side/using-gulp.html#running-default-tasks
