### ISSUE TITLE
How to receive the inner content from "Microsoft.AspNet.Mvc.Razor.HelperResult" namespace

### ISSUE THREAD

**Issue by Shameer-Ali** [aspnet/Docs#3492]
I have created a custom component by using Html Helper in ASP.NET MVC. Also, did the same logic in ASP.NET Core platform.

My component will be working fine, when I have set the properties. Now I am trying to include one additional support like displaying custom contents (like images, html elements and text) with in my component like in dialog component.

In ASP.NET MVC, I have received the inner content from “System.Web.WebPages.HelperResult” this namespace. But ASP.NET Core, I’m unable to get my component inner content which will be mentioned in my view page.

In ASP.NET Core, I’m trying to get the content from “Microsoft.AspNet.Mvc.Razor.HelperResult” namespace. But unfortunately, the expected result was unable to get from this namespace. Even, I don’t know how to get from this namespace (even surfing in internet no ideas about this).
If there is any alternative options to get the result in ASP.NET Core platform or any possible way, please suggest to me!

Please, find the issue in the attached image.

<img width="416" alt="razor" src="https://user-images.githubusercontent.com/29402958/27084323-15281272-5069-11e7-97a8-2aa82353ccb2.png">

**Comment by Rick-Anderson** [comment]
@Shameer-Ali  This is for opening doc issues, it's not a support forum. Can you post your question on SO?
