### ISSUE TITLE
Swagger tutorial doesn't correspond with the new version of sample project at GitHub

### ISSUE THREAD

**Issue by misha-fm** [aspnet/Docs#3493]
The tutorial about using Swagger in ASP.NET Core WebAPI (https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger) has code listings, that include fererences to TodoRepository, that was changed by TodoContext in recent  update (https://github.com/aspnet/Docs/pull/3399).

Tutorial now needs to be updated to correspond with the actual codebase of the sample project.

**Comment by misha-fm** [comment]
There's a sample project with final result for the tutorial here: https://github.com/misha-fm/Docs/tree/master/aspnetcore/tutorials/web-api-help-pages-using-swagger/sample/src/TodoApi). There code in this project corresponds with the article. So it seems that both article and a sample project with final result need to be updated.

**Comment by Rick-Anderson** [comment]
Article needs work - csat 59% with high viewership.

**Comment by Rick-Anderson** [comment]
@ardalis  If you have any hours left.
