### ISSUE TITLE
Sub-generators removed from ASP.NET Core Yeoman generator

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#3499]
Per commit https://github.com/OmniSharp/generator-aspnet/commit/af33b2721e38a4cb31f8ba3c3b4195e85cbdd6b0, the sub-generators have been removed from this Yeoman generator. The associated [doc](https://docs.microsoft.com/en-us/aspnet/core/client-side/yeoman)'s **Adding to your project with sub generators** section specifically references the `class` sub-generator. It appears that customers running v.0.3.0+ of the generator, won't be able to complete this step.

@sayedihashimi @peterblazejewicz Are there plans to reintroduce these sub-generators?

**Comment by peterblazejewicz** [comment]
As far as I know there is no notion of related items or project template in `dotnet/templating`. The latest published version of `generator-aspnet` was redacted to use the same content as in `dotnet new`.  As far as I understand we should promote use of `dotnet new` for creating new content and when a feature is missing (class template, controller template) either add a request/PR to dotnet/templating or go in ones own item template for `dotnet new`.
The docs shows usage of many technologies which could be fully rewritten/refactored to use `dotnet new` completely (if and when applicable OFC)

The `omnisharp-vscode` plugin for VSCode offers some standard items creation snippets, including class:
https://github.com/OmniSharp/omnisharp-vscode/blob/bc232949dbb9d80a96a41aba8118af71280f7c49/snippets/csharp.json

**Comment by scottaddie** [comment]
- [ ] Update sub generators section content
- [ ] UE edit
