### ISSUE TITLE
Replace all screen shots of "Intro to MVC" series with chrome

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3505]
All three versions can share the same Chrome images.

**Comment by tdykstra** [comment]
But browser chrome looks noticeably different on Windows vs. Mac, e.g. close button upper right vs. upper left

**Comment by Rick-Anderson** [comment]
Can I get buy with doing all the shots on Chrome/Mac? or Chrome/Windows? It won't be that big of a distraction and half the screenshots to update next version.

**Comment by tdykstra** [comment]
Yes, you can explain the reasons why you made that choice if someone comments about it.

**Comment by Rick-Anderson** [comment]
we'll do this on the next update
