### ISSUE TITLE
Retire 'Getting Started' TOC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3511]
Retire this node.

![image](https://user-images.githubusercontent.com/3605364/27261978-ef1d81a0-5402-11e7-9ed2-927cea36b833.png)

**Comment by tdykstra** [comment]
You mean just the dotnet watch (the only one crossed out) or the entire Getting started node with everything under it?  What about the basic getting started tutorial that the Getting started node itself points to?

**Comment by Rick-Anderson** [comment]
I think we should get rid of the entire node. The getting started would be surfaced on the tutorials page. Or you could replace 
![image](https://user-images.githubusercontent.com/3605364/27294001-ed23d1c2-54cc-11e7-9083-e163feaf0957.png)

With a link to the tutorials page - but that seems like unnecessary duplication.

**Comment by tdykstra** [comment]
I would leave Getting Started but make it a leaf node (not expanding, just goes to that one doc).  It doesn't really fit well in the same list as the other tutorials.
