### ISSUE TITLE
aspnet/core/client-side/angular "Using AngularJS for Single Page Applications (SPAs) with ASP.NET Core"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3543]
https://docs.microsoft.com/en-us/aspnet/core/client-side/angular
- [ ] Review/update.
- [ ] Remove anything that is documented on the Angular side
- [ ] Borrow or link to[ Sharing Configuration in ASP.NET Core SPA Scenarios](https://blogs.msdn.microsoft.com/webdev/2017/10/27/sharing-configuration-in-asp-net-core-spa-scenarios/)

**Comment by scottaddie** [comment]
Closing, as this doc was removed in https://github.com/aspnet/Docs/pull/4998.
