### ISSUE TITLE
2.0 Migrating from 1.x to 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3548]
Should be ref type document, not cook book as our ASP.NET MVC classic to ASP.NET Core guide is now.
7.0 into video.

Need to update and uncomment the Markdown link & text in `aspnetcore-2.0.md` once this PR is merged.

**Comment by danroth27** [comment]
@scottaddie Can you dump your notes from our meeting here?

**Comment by scottaddie** [comment]
Here are some notes I jotted down during the meeting...

**Doc Goal:** not to identify every change, but to identify main brush strokes

**Steps to consider documenting**
- Update packages
	- Upgrade TFM to `netcoreapp2.0`
	- Update to ASP.NET Core meta-package: `Microsoft.AspNetCore.All` (this is only relevant for .NET Core)
		- No change needed for desktop framework other than updating package versions to 2.0.0 (meta-package isn't applicable here)
		- ASP.NET Core 2.0 requires `net461` TFM or above
		- There's no meta-package for the tools reference, so you just update those to the latest version
	- `AssetTargetFallback` is new in CSPROJ <-- this used to be `PackageTargetFallback`
	- NuGet package downgrade errors could occur
		- either downgrade the error to a warning or fix the package reference'

- The biggest area of breaking changes in 2.0 is authentication
- TODO: Create an ASP.NET Core 1.1 MVC w/ Individual User Authentication as a sample app to demo migration
- Most auth code has moved from `Configure` into `ConfigureServices` method
- Update *global.json* by either deleting it or update to the version of the SDK (2.0.0)

- with regard to DI, the default behavior has changed in `BuildWebHost.CreateDefaultBuilder`
	- scoping is now validated in development mode (e.g., are singletons being referenced longer than they should?)

- until 3rd party loggers like Serilog or NLog upgrade to the new 2.0 pattern, they'd need to continue using the old 1.x pattern with `ILoggerFactory`

- NOTE: If you're currently targeting .NET Framework and want to target .NET Core instead, try again. There are many more APIs added in 2.0 as a result of .NET Standard 2.0.

- Logging system applies global filters from configuration
	- App settings now apply to all loggers by default
	- This is a property of the Logger Factory

- create an App Insights section
	- remove their explicit references?
	- all 1.1 apps created in VS 2017 will have App Insights
	- remove explicit `UseApplicationInsights` method call from *Program.cs* if not explicitly calling into App Insights APIs

- need a prereqs section in the doc
	- VS 2017 latest update, VS Code, VS for Mac
	- .NET Core 2.0
	- need to update hosting bundle if you're running on Windows

- ".NET Core Runtime Store" is something new in 2.0 that changes publishing
	- this trims the bundle of assets to be deployed

- on publish, Razor view precompilation is on by default
	- you can't edit the Razor files when you do this because it's not there
	- your output file will be smaller and startup time will be faster

- host setup <-- change to use new pattern in *Program.cs*
