### ISSUE TITLE
Consider adding docs for Web Api compat shim

### ISSUE THREAD

**Issue by brockallen** [aspnet/Docs#3557]
I had a customer today that wanted to take existing Web API 2 code and move to ASP.NET Core with minimal changes. They were looking for docs on how to use the Web API compat shim, but apparently there are none: https://twitter.com/RickAndMSFT/status/878033598367932416 // @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@danroth27  do we have anything to start with?

**Comment by danroth27** [comment]
No, we need to create a new doc from scratch.

**Comment by danroth27** [comment]
Dup of #1811
