### ISSUE TITLE
Add filter to API search

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3565]
We limit search to ASP.NET Core

![image](https://user-images.githubusercontent.com/3605364/27509842-45490908-58ba-11e7-86d3-7305ecc5408a.png)

We need to do the same for API

See related [broken build](https://mseng.visualstudio.com/VSChina/_workitems?id=1035309) and [search](https://mseng.visualstudio.com/CSI/_workitems?id=1025513)

Several closed PR's to fix this like https://github.com/aspnet/ApiDocs/pull/19

**Comment by Rick-Anderson** [comment]
@danroth27  a PR with this fix was merged into master. Can we merge master into live?

**Comment by Rick-Anderson** [comment]
@dend  Can you make sure this works?  We merged the fix to master, it's just not in live.

**Comment by dend** [comment]
@saurabhchoudhury would have better context on how to set search scopes.

**Comment by Rick-Anderson** [comment]
@dend  Sorry - search has been enabled in master. We just need to merger master into live.

**Comment by Rick-Anderson** [comment]
it's fixed with the 2.0 update
