### ISSUE TITLE
Bootstrap reboot aspnet/core/client-side/bootstrap

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3567]
The bootstrap article has high views and low ratings -  66K views in 3 months and 60% sat

- [ ] Rename article Using bootstrap with ASP.NET Core MVC
- [ ] Remove the how to use bootstrap info that is found elsewhere, and link to a good Bootstrap introduction and/or tutorial. This article should be on how to hook up bootstrap with ASP.NET  Core MVC. 
- [ ] Remove or condense the alternative installations

@tdykstra  @scottaddie  @danroth27  please review

**Comment by tdykstra** [comment]
@Rick-Anderson The stats are out of sync with the LiveFyre comments, which are generally very positive.  Many customers do need an intro to bootstrap itself, so I added to your list a note to link to introductory Bootstrap documentation. Also added MVC to the proposed title.

**Comment by spboyer** [comment]
Removing images from an article on a UI framework seems strange to me. Giving a goog understanding of how bootstrap works with ASP.NET MVC, TagHelpers etc would be best served with images.

**Comment by tdykstra** [comment]
@Rick-Anderson @spboyer I think we could remove the last bullet (remove most images) altogether, as the second bullet (remove Bootstrap content that isn't related to using it with Core) should cover it.
