### ISSUE TITLE
Conceptual Overview: Scripts Section: Consider linking to doc on order of events

### ISSUE THREAD

**Issue by jderus** [aspnet/Docs#357]
It is fairly easy to figure out the full list from VS. But without a bunch of work, I cannot see the order or purpose of the different events available in the scripts section of projects.json. 

My proposal is in the Conceptual Overview section, link to a page on further information.
Specifically a description of each possible event, and a visual timeline on the order in which they happen.

**Comment by danroth27** [comment]
See http://docs.asp.net/en/latest/dnx/projects.html#scripts and let us know if you still have questions.

**Comment by jderus** [comment]
That looks great Dan! Thanks.
