### ISSUE TITLE
Consider replacing GetTempFileName with GetTempPath and GetRandomFileName

### ISSUE THREAD

**Issue by jbagga** [aspnet/Docs#3589]
Consider removing uses of `GetTempFileName` as

> The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files.

The following files use this:
ProfileController
StreamingController
UploadFilesController

See aspnet/Coherence-Signed#510 for more information.

cc @Eilon

**Comment by Rick-Anderson** [comment]
@jbagga  what's the ask for the doc repo?

**Comment by jbagga** [comment]
There are instances that use GetTempFileName, example: https://github.com/aspnet/Docs/blob/43b3de4a508e6d7b5cf495c9b3c5ffd4c6be51e6/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Controllers/ProfileController.cs#L54

The docs should use a different API for random files because of the reason stated above. One option is to use GetTempPath and GetRandomFileName to avoid maxing out at 65,535 files. There could also be clean up code to delete the temp file after use. Please see the original aspnet/Coherence-Signed#510 issue for more details and other suggestions.

**Comment by Rick-Anderson** [comment]
@jbagga  I think we will do this in two phases. First pass, add a note:

The `GetTempFileName` method will raise an `IOException` if it is used to create more than 65535 files without deleting previous temporary files. A real app should either delete temporary files or use `GetTempPath` and `GetRandomFileName` to replace `GetTempFileName`.

2nd pass would be to actually follow our advice.

**Comment by Eilon** [comment]
BTW to be clear about the problem, it doesn't matter how "good" *your* program is. A different misbehaving app could easily exhaust all 65535 files and then your app will never work.

**Comment by Rick-Anderson** [comment]
@jbagga  see my update to the include file that addresses [@]EILON'S  comment.

The 65535 files limit is per server, so another app on the server can use up all 65535 files.
