### ISSUE TITLE
Verify all external links

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3593]
Run a tool to check all external links. fix any bad links.

**Comment by isaac2004** [comment]
@Rick-Anderson is there a preferred tool for this or can I use something like [awesome-bot](https://github.com/dkhamsing/awesome_bot)

**Comment by Rick-Anderson** [comment]
@isaac2004  I used https://validator.w3.org/checklink last time but use anything that works.

**Comment by isaac2004** [comment]
@Rick-Anderson just external links or things like css as well?

**Comment by isaac2004** [comment]
Hey @Rick-Anderson sorry just getting back to this. So do you want just 404s changed, or 300s as well?

**Comment by scottaddie** [comment]
Fixed by #4241
