### ISSUE TITLE
Describe MSBuild props that control web.config transform

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#3607]
Describe ...

* **\<IsTransformWebConfigDisabled>**
* **\<TransformWebConfigEnabled>**

... in *Set up a hosting environment for ASP.NET Core on Windows with IIS, and deploy to it*.

**Comment by vijayrkn** [comment]
Property to set is
```
<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
```
https://github.com/aspnet/websdk/blob/afbcec9b0951d09088f26e98e6aca6114e0d32ee/src/Publish/Microsoft.NET.Sdk.Publish.Targets/netstandard1.0/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets#L47

I don't think this property - TransformWebConfigEnabled is used any where.
