### ISSUE TITLE
Built-in MVC Tag Helpers

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#365]
Instead of writing an article per built-in tag helper we want to cover the tag helpers in scenario focused docs. Here's the plan:

1.	Add a list of the built-in tag helpers list to “Intro to Tag Helpers” doc that link to the corresponding sections of the appropriate scenario focused articles (#1025)

2.	Cover the build-in tag helpers in scenario focused articles as follows:

    MVC -> Views/Controllers -> Link Generation (#1026)
    - UrlHelper
    -	`@Href`
    -	Anchor tag helper

    MVC -> Views -> Working With Forms (#1027)
    -	Tag helpers: form, input**, text area, select+option, label, validation summary+message
    -	Cover HTML helper alternatives
    -	Grow up story to use editor templates (link to separate doc)
    -	Link to Model Validation

    MVC -> Views -> Working with CDNs (#102)
    -	Tag helpers: link, script, img

    ASP.NET -> Fundamentals -> Working with Multiple Environments (#1028)
    -	Tag helpers: environment
    
    MVC -> Performance -> Output Caching (#880)
    -	Tag helpers: cache**

    ** These are the most complex/fancy tag helpers - lots of attributes to cover

**Comment by Rick-Anderson** [comment]
I'll be working with @dpaquette on this.
