### ISSUE TITLE
2.0 SPA templates in VS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3655]
See http://gunnarpeipman.com/2017/07/aspnet-core2-spa/

**Comment by isaac2004** [comment]
@Rick-Anderson what is the expected goal here? A new doc that showcases the SPA Templates? a set of how-to guides on using each template? (I know there are a few other issues that are similar).

Maybe adding a new section for SpaServices documentation?

**Comment by Rick-Anderson** [comment]
@isaac2004  this can be closed. Duplicate of #3771 and #3543
