### ISSUE TITLE
2.0 C# language versions ASP.NET Core projects (project, Razor, scaffolding)

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3656]
As dan roth for more details

**Comment by guardrex** [comment]
@Rick-Anderson Can you say more about what this one entails?

**Comment by Rick-Anderson** [comment]
See #5591

**Comment by guardrex** [comment]
Title: *Language support in ASP.NET Core projects*

Notes:
* Configuring the ASP.NET Core project's language versions in VS isn't intuitive. VS uses the "hidden UI" (referring to project Properties > Build panel > Advanced > Language version DDL).
* Talks about Razor, scaffolding, C#, publishing ... because they all get impacted by the version of Roslyn compiler that you bring in as a dependency versus what gets compiled by VS.
* https://github.com/aspnet/Razor/issues/1046
* **Important!** :point_right: https://github.com/dotnet/roslyn/issues/20614
* https://github.com/dotnet/roslyn/issues/18783

**Comment by guardrex** [comment]
@Rick-Anderson @mairaw @BillWagner 

It looks like this ask on this issue has been (mostly) addressed. See :point_right: https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-7-1#language-version-selection

However, it was written for 7.1. The 7.2 topic didn't receive a similar section.

Perhaps to better surface the content, should that section become its own topic and be written to generically apply to C# versions? ... perhaps under https://docs.microsoft.com/dotnet/csharp/whats-new/

**Comment by BillWagner** [comment]
We have an issue for this: dotnet/docs#3685  Do you want to take it on?

If you search the docs repo for <LangVersion> you'll find the locations that should link to the new topic.

**Comment by guardrex** [comment]
> Do you want to take it on?

It doesn't matter to me, but I've been ordered not to work on other repos while on contract. I need approval.

@Rick-Anderson Do you want to close this as a dup of dotnet/docs#3685? Do you want to approve my working dotnet/docs#3685?

**Comment by Rick-Anderson** [comment]
@guardrex  I think @JRAlexander can handle it.

**Comment by guardrex** [comment]
@BillWagner Just so you know, there is a contract stipulation of some sort at play. When I was working with you, Maira, and Ron, I asked about occasionally doing some stuff with Rick and Tom over here on my own time outside of the contract. I was flatly told, "NO! Don't you dare help Rick and Tom!" :smile: lol ... Seriously tho, I really did have to stay off this repo for that five months. Now the tables are turned, and I can't do much for the .NET Core docs without probably getting into some hot water somewhere ... even if only with the vendor.

**Comment by JRAlexander** [comment]
@Rick-Anderson Handle what?

**Comment by guardrex** [comment]
@JRAlexander He's referring to dotnet/docs#3685. This issue is a dup of that one.

**Comment by JRAlexander** [comment]
Ok, I'll talk with @BillWagner  and @mairaw to see if this should be included in the .NET 2.1 project. Thanks!
