### ISSUE TITLE
2.0 Tag helper components, head and body tag helpers

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3662]
@pkellner would you be interested in this one?

**Comment by rachelappel** [comment]
Rough outline:

- What are Tag Helper Components?
- Benefits of Tag Helper Components
- Built-in Tag Helper Components [head and body]
- Tag Helper Components compared to Tag Helpers
- Authoring Tag Helper Components

**Comment by pkellner** [comment]
@Rick-Anderson Yes, not in the next month or two. I'm pretty over committed right now. I'd love to read what @rachelappel does though.  Even better. :)

**Comment by scottaddie** [comment]
@rachelappel Is this is a duplicate of https://github.com/aspnet/Docs/issues/4033?

**Comment by rachelappel** [comment]
@scottaddie It looks like some of it is. We can merge these.

**Comment by Rick-Anderson** [comment]
duplicate of #4033
