### ISSUE TITLE
2.0 Data protection changes

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3663]
@HaoK  Are you the contact for this? What are the changes? Can you draft the changes?

**Comment by HaoK** [comment]
Nope @blowdart should be able to find you the lucky guy

**Comment by blowdart** [comment]
@natemcmaster & @ajaybhargavb

**Comment by ajaybhargavb** [comment]
This is a duplicate https://github.com/aspnet/Docs/issues/2975
