### ISSUE TITLE
Runtime package store

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3664]
link to [.NET Core docs](#2725) PR https://github.com/dotnet/docs/pull/2496
Dev contact @-JunTaoLuo 

ASP.NET Core publish behavior (6:50) - we imply a target manifest that includes all the packages in the all package.  How do you get the ASP.NET Core store. - make sure that' documented. 
Document versioning: 7:20 If you add ABC-v-x.y to the store and then reference a different version (ABC-v-x.2) from your project - ABC won't be used from the store because it doesn't match.

* If you have the assembly ABC in your bin or publish folder - the ABC from the store will not be used, the output folder is always matched first. That's a big difference from the GAC. With the GAC,  the app always gets the assembly from the GAC. 
* If you publish with a target manifest  - You can only run your published output on a machine that have those assets listed in the target manifest in the runtime store. If you have a version mismatch with the target manifest you published with and the hosts runtime store, your app won't start. You will get an error indicating the missing assembly.  The error also includes the name of the manifest.  Add a section troubleshooting runtime store problems on ASP.NET Core apps - Show the error, show how it can happen.  Run publish and move to a server that doesn't have the runtime store. Show error. 

* https://github.com/dotnet/designs/issues/8
* [andrew lock blog](https://andrewlock.net/the-microsoft-aspnetcore-all-metapackage-is-huge-and-thats-awesome-thanks-to-the-net-core-runtime-store-2/)

Correct name is “Runtime  Store” see https://github.com/dotnet/cli/issues/7301

[Applications](https://github.com/aspnet/Home/wiki/Roadmap) using the new `Microsoft.AspNetCore.All` will automatically take advantage of the new **.NET Core Runtime Store**, which will contain all the runtime assets needed to run ASP.NET Core 2.0 applications by default, removing the requirement to have assets from the referenced ASP.NET Core NuGet packages deployed with the application. These assets are also pre-JIT'ted such that application startup-time is improved.

Questions: 

- target manifest - what's the scenario?  A target manifest is the list of NuGet packages on the publish target host (that is, packages pre-installed on the targeted host)?
- Azure will include the .NET Core 2.0 runtime store when it's released.

**Comment by Rick-Anderson** [comment]
@JunTaoLuo
C:\Program Files\dotnet\store is really the ASP.NET Core 2.0 store - it's not a generic .NET 2.0 store - right? cc @GuardRex

**Comment by JunTaoLuo** [comment]
The store directory is intended to contain all runtime package store files. Currently ASP.NET Core is the only user that installs runtime package stores there. In the future, it is theoretically possible that other third parties also install runtime package store files to that location.

**Comment by Rick-Anderson** [comment]
fixed by https://github.com/dotnet/docs/pull/2496
