### ISSUE TITLE
Windows/Linux hosting with the new runtime store

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3667]
@Tratcher who is the contact for windows/linux hosting?

**Comment by Tratcher** [comment]
Ask @JunTaoLuo about the store

**Comment by Rick-Anderson** [comment]
@JunTaoLuo can you provide a rough draft.

**Comment by JunTaoLuo** [comment]
Is this still needed? We have replaced the runtime store with the shared framework starting in 2.1 and 2.0 which uses the store fell out of support. There are still some components like SiteExtensions that still uses this feature but even those are being redesigned. I think we should just close this issue.
