### ISSUE TITLE
Identity updates - usage outside of ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3668]
@guardrex  it's a P3 so I wouldn't worry about it. I think it had to do with using Identity outside ASP.NET Core. Maybe we should close for now. I think it came from a product announcement list or road map.

**Comment by guardrex** [comment]
@Rick-Anderson Can you elaborate on this one?

**Comment by guardrex** [comment]
In case we reopen this, this pertains to using ASP.NET Core Identity in UWP apps. They made changes to Identity [split into (1) Extensions Identity (provides Identity without the signin manager) and (2) ASP.NET Core Identity] to accommodate the UWP scenario specifically.
