### ISSUE TITLE
2.0 localization  changes

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3669]
@ryanbrandenburg  can you update [Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) for 2.0 - or provide me with a draft?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you provide a draft for the [Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) 2.0 changes?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you provide a draft for the [Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) 2.0 changes?

**Comment by ryanbrandenburg** [comment]
The only Localization breaking change I'm aware of for 2.0.0 is aspnet/Announcements#260 and I don't believe that requires an update in the docs. Is there something more specific you're looking for.

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  breaking changes and new features.

**Comment by ryanbrandenburg** [comment]
According to [this query](https://github.com/aspnet/Localization/issues?q=is%3Aissue+is%3Aclosed+milestone%3A2.0.0) there were no new features for Localization in 2.0.0.
