### ISSUE TITLE
2.0 API ref

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3711]
related to #3710

**Comment by Eilon** [comment]
BTW what exactly is needed from me on this? Not too long ago I sent an email with all the products, package names, and versions for all 3 versions of ASP.NET Core and EF Core (1.0, 1.1, and 2.0).

**Comment by Rick-Anderson** [comment]
@Eilon  we the 2.0 API reference for ASP.NET Core and EF Core

**Comment by Eilon** [comment]
What do you actually need from me? The XML files themselves? Or the NuGet package ids + versions?

**Comment by danroth27** [comment]
The [ASP.NET Core 2.0 API refs](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0) are published. We just need to fix #3926. Closing this issue.
