### ISSUE TITLE
AntiForgery documentation needs to explain that it uses data protection.

### ISSUE THREAD

**Issue by blowdart** [aspnet/Docs#3716]
## General

The anti-forgery topic doesn't mention that it uses data protection, so there are no instructions on how to set it up in a load balanced setting. This needs addressing.

**Comment by Rick-Anderson** [comment]
@blowdart can you outline the instructions to set it up? I'm guessing we haven't seen alot of complaints on this because Azure uses sticky bits by default.

**Comment by blowdart** [comment]
A paragraph acknowledging it uses data protection and then linking to the config doc for it would suffice. Maybe wrapped in a note to highlight it. https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview
