### ISSUE TITLE
Check broken link report and fix

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3728]
[Internal Broken links report](https://msit.powerbi.com/groups/me/dashboards/f3ca3491-4d15-4ed3-a1f8-306d993e9b7f/reports/faa2149a-1493-49ad-9817-f337bdab395a/ReportSection)

![image](https://user-images.githubusercontent.com/3605364/28230092-c6de926a-68a2-11e7-8061-c215e7cc7794.png)

**Comment by IvandroFabiaeFilhos** [comment]
This "Broken links report" link is only to Microsoft employees?

**Comment by Rick-Anderson** [comment]
@IvandroFabiaeFilhos  yes, it's internal

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/3593
