### ISSUE TITLE
Document servicing

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Docs#374]
We need a detailed documentation on how servicing works. This is especially needed when:
- the customer is using the `DNX_SERVICING` variable to take servicing over
- the customer is deploying an application to a machine (e.g. a production server) where they will not install Visual Studio or the MSI that would prepare the machine for servicing)
- when we support servicing on non-windows boxes

Some important things to document:
- folder structure
- format of the servicing manifest (index.txt file)
- recommended ACLs

**Comment by danroth27** [comment]
Duplicate of #196.
