### ISSUE TITLE
Document how to connect from a mobile app to local web app in the same solution

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#3746]
We should update https://docs.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend with more detailed steps on how to connect from the mobile app emulator to the web api when both are in the same solution. Ex. with the Android emulator you use IP address 10.0.2.2 and you need to update your IIS Express site bindings to allow the request through. We should also figure out  what the steps are for iOS or UWP.

**Comment by Rick-Anderson** [comment]
MOved to #9815
