### ISSUE TITLE
2.0 update aspnet/core/security/authentication/social/ for 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3753]
15:55 into 7-17 recording.

- [ ] [Enabling authentication using Facebook, Google and other external providers]( https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/)
- [ ] [Google ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins) Do the next quick update after this.
- [ ] [Combine social and local login accounts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm#combine-social-and-local-login-accounts) (only the last section) 
- [ ] [Facebook ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins)
- [ ] [Twitter ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins)
- [ ] [Microsoft ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins) 
- [ ] #3796

**Comment by Rick-Anderson** [comment]
@01binary let me know if you can help update these for VS 2017/ASP.NET Core 2.x 
I can do all the MD work if you want to provide the updated steps.

**Comment by 01binary** [comment]
I think I will have some time during the next couple of weeks.

**Comment by Rick-Anderson** [comment]
@01binary  put yourself as lead author and me second. Drop Pranav Rastogi

**Comment by 01binary** [comment]
Setting up my environment with Visual Studio 2017 Preview version 15.3 and .NET Core 2.0 Preview 2 unless you specify otherwise.

**Comment by Rick-Anderson** [comment]
I can do the SSL work. For Visual Studio 2017 preview 3 and higher, the individual user accounts tutorial automatically set the URL to HTTPS.

Install latest .NET Core 2.0 SDK from https://github.com/dotnet/cli/tree/release/2.0.0
Note that ASP.NET Core 2.0 is a separate install from VS. You have to separately download and install the .NET Core 2.0 SDK to get the ASP.NET Core 2.0 bits.

**Comment by Rick-Anderson** [comment]
@01binary  also list yourself as lead author and drop the other co-authors.

**Comment by 01binary** [comment]
> This tutorial demonstrates how to build an ASP.NET Core app that enables users to log in using OAuth 2.0/1.0a

Sounds like 1.0a should be removed because 1.0 stack is no longer supported? Reference: https://github.com/aspnet/Security/issues/1310

**Comment by 01binary** [comment]
Updated index and facebook so far

https://github.com/01binary/Docs/blob/master/aspnetcore/security/authentication/social/index.md
https://github.com/01binary/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md

Going to create a PR when all done

**Comment by 01binary** [comment]
In the course of updating the content, I found that complaints about steps no longer applying for Facebook and Google were due to skipped steps while following the tutorials. I will add more screenshots to increase screen space taken by some important steps, making it less likely for someone to skip a single-sentence bullet point.

Many other complaints were about the right place to add social providers, which no longer applies (AddIdentity can be called before or after, doesn't matter, and UseMvc is now in a completely different place so you can't accidentally setup providers after it). I am adding a Troubleshooting section to each social provider topic to take care of the rest.

**Comment by 01binary** [comment]
> Combine social and local login accounts (only the last section)
I don't know what this means but I went through the steps and everything looks accurate in that last section. I updated the screenshot to match the new project template, but differences were minimal.
