### ISSUE TITLE
Update docs URL in README.md

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#3763]
The `README.md` file of this repo references the older docs.asp.net URL. Should this URL be replaced with https://docs.microsoft.com/aspnet, which is currently referenced in the repo description text?

/cc @danroth27

**Comment by danroth27** [comment]
Yeah, docs.asp.net points to the ASP.NET Core docs, but this repo has the docs for both ASP.NET and ASP.NET Core, so we should point to docs.microsoft.com/aspnet instead.
