### ISSUE TITLE
2.0 Create an angular app using the templates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3769]
Tutorial creating an app using VS 2017 preview 2 or later and the following:

![image](https://user-images.githubusercontent.com/3605364/28342206-55a8aaec-6bd4-11e7-9f42-94a65bb73a68.png)

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  can you do this?

**Comment by fiyazbinhasan** [comment]
i can!!! 👍 kindly provide me the outline. note that I wrote a section describing how to create and developing an angular application using the template for a previous issue [Add SpaServices with ASP.NET Core doc](https://github.com/aspnet/Docs/pull/3563#issuecomment-311742160) here:

https://github.com/fiyazbinhasan/Docs/blob/angular2-doc/aspnetcore/client-side/angular2.md#creating-an-angular-application-using-spaservices

let me know whether the demo app will work or will it be a multi-part article  showcasing a full CRUD based application. TIA.

**Comment by Rick-Anderson** [comment]
@scottaddie  can you help me come up with an outline?

**Comment by scottaddie** [comment]
@Rick-Anderson Yep! I've assigned myself to this issue as a reminder to create an outline.

**Comment by Rick-Anderson** [comment]
@scottaddie  can you work on an outline or something to get @fiyazbinhasan  going?

**Comment by YuxuanLin** [comment]
That is awesome.
A question, that where is the 

> .anguar-cli.json

 file now? I still need it to generate component from cli which is a quicker way than VS.

**Comment by scottaddie** [comment]
@YuxuanLin The Angular CLI isn't currently supported in the project template; however, there is a plan to add it. See the following issue for more info: https://github.com/aspnet/JavaScriptServices/issues/1288.

**Comment by YuxuanLin** [comment]
Awesome! Thanks!

**Comment by scottaddie** [comment]
This is being addressed in #4919.
