### ISSUE TITLE
2.0 Create a React.js app

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3770]
![image](https://user-images.githubusercontent.com/3605364/28342235-7e562faa-6bd4-11e7-82c8-4173348e818b.png)

**Comment by Rick-Anderson** [comment]
https://stackoverflow.com/questions/45288226/setting-up-reactjs-on-net-core-2-0-invalidoperationexception 
Rather than https://reactjs.net/getting-started/tutorial.html - perhaps the templates are better.  cc @fiyazbinhasan

**Comment by Rick-Anderson** [comment]
@danroth27  who can write an outline for this article? @fiyazbinhasan  has volunteered to to write it. cc @scottaddie

**Comment by danroth27** [comment]
@SteveSandersonMS Can you help out with this?

**Comment by scottaddie** [comment]
This is being addressed in #4919.
