### ISSUE TITLE
2.0 create a React.js and Redux app

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3771]
![image](https://user-images.githubusercontent.com/3605364/28342263-a00f1828-6bd4-11e7-90a7-45e48ed98ab7.png)

**Comment by Rick-Anderson** [comment]
@danroth27  who can write an outline for this article? @fiyazbinhasan  has volunteered to to write it. cc @scottaddie

**Comment by danroth27** [comment]
@SteveSandersonMS Can you help out with this and the docs for the other SPA templates?

**Comment by SteveSandersonMS** [comment]
Yes, though we are going to change some things for 2.1 so it might be best to wait until that plan settles.

**Comment by scottaddie** [comment]
This is being addressed in #4919.
