### ISSUE TITLE
2.0 Create authentication app that connects to user store in the cloud

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3772]
Create and deploy the app to Azure.

![image](https://user-images.githubusercontent.com/3605364/28342331-f195fd6a-6bd4-11e7-9701-9efc00dac0fe.png)

**Comment by isaac2004** [comment]
@Rick-Anderson should this be a new doc or an added section to an existing one?

**Comment by Rick-Anderson** [comment]
@isaac2004  a new app. cc / @scottaddie

**Comment by isaac2004** [comment]
@Rick-Anderson @scottaddie There is a 1.1 Sample on [Azure GitHub](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapp). It gives you full flow. Thoughts on linking to this documentation and then walkthrough with screens of creating 2.0 app.

**Comment by isaac2004** [comment]
@scottaddie @Rick-Anderson bump

**Comment by Rick-Anderson** [comment]
@isaac2004 it would be great to have a 2.0 sample and tutorial. Are you able to do this?

**Comment by isaac2004** [comment]
If there isn't a defined ETA, sure I can do that.

**Comment by isaac2004** [comment]
@Rick-Anderson can you point me to where you want the doc?

**Comment by Rick-Anderson** [comment]
Under https://docs.microsoft.com/en-us/aspnet/core/security/authentication/

**Comment by isaac2004** [comment]
@rick, I just noticed this PR #5200 that references issue #4835 that is the same. Should we close this issue and the PR I opened?

**Comment by Rick-Anderson** [comment]
@isaac2004  yes - sorry about that.
