### ISSUE TITLE
2.0 Sweep all of aspnet/core/security for auth changes

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3777]
This is the master issue. List each doc here:

- [x] update security/data-protection/compatibility/cookie-sharing #3776
- [x] update & rename 2fa with sms, /security/authentication/2fa
- [x] add new TOTP/Authenticator app doc
- [x] update [core/security/authentication/social/index](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/) for new config
- [x] ~update & rename/retitle [security/authentication/cookie](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie)~ nofix (see below)
- [x] add razor pages authorize doc #4444
- [x] update security/data-protection/configuration/index and sub pages for new config. Add instructions for redis and keyvault.

**Comment by blowdart** [comment]
Also tagging @danroth27 and @HaoK

**Comment by Rick-Anderson** [comment]
@01binary  just checking, I think update [core/security/authentication/social/index](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/) for new config is complete - right?

**Comment by 01binary** [comment]
@Rick-Anderson core/security/authentication/social/index does not have code snippets, changes specific to 2.0 were minimal. Provider-specific topics were updated for RTM 2.0 in August - if there has been an API breaking release since then, they will need to be updated again (i.e. I assume Preview 2 API is older than RTM 2, with the latter being final).

**Comment by guardrex** [comment]
@Rick-Anderson For ...

> rename/retitle security/authentication/cookie

`https://docs.microsoft.com/aspnet/core/security/authentication/cookie`
Title: *Using Cookie Authentication without ASP.NET Core Identity*

1. What title would you like?
2. Based on the prior conversation, do you want the ASP.NET 1.x bits removed in favor of the PDF (here and generally) leaving the entire topic in a for-2.0 state? That seems to be your last order before the conversation moved into other versioning subjects.

**Comment by Rick-Anderson** [comment]
@guardrex  No, change of plans. Keep the 1.x and 2.x tabs.
That title looks good to me. Can you think of a better title?

**Comment by guardrex** [comment]
@Rick-Anderson "Keep the 1.x and 2.x tabs." :+1:

The title seems ok to me. By that point, they'll already have seen the topics pertaining to using cookie auth *with* Identity, so this calls out clearly that it's cookie auth without Identity. *Yikes!* on the lack of an introduction calling that out tho. It just launches right into config. (I'll fix that.)

**Comment by guardrex** [comment]
@Rick-Anderson 

I checked off the entry for the cookie sharing updates. There's just one left here:

> update security/data-protection/configuration/index and sub pages for new config. Add instructions for redis and keyvault.

Should I look into this and see where it stands, or did u want to TAL?

**Comment by Rick-Anderson** [comment]
What's TAL?

**Comment by Rick-Anderson** [comment]
Look into it please.

**Comment by guardrex** [comment]
Will do.

TAL = *Take a look* ... I must have picked that up somewhere around the repos.

**Comment by guardrex** [comment]
@Rick-Anderson Let's ice this ... We're cool here. https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers#azure-and-redis
