### ISSUE TITLE
document unexpected behavior (unfixed issued)

### ISSUE THREAD

**Issue by WernerMairl** [aspnet/Docs#3779]
Issue 
https://github.com/aspnet/Hosting/issues/839 and his duplicate (with a better explanation about the impact) https://github.com/aspnet/Hosting/issues/1056
seems not be solved for 2.0 (breaking changes)

If not fixed, i suggest to document the unexpected behavior (it costs me a full day of dev to find out that there is no bug in my code but a unexpected behavior in the framework)

regards
Werner

**Comment by Rick-Anderson** [comment]
@WernerMairl  can you suggest where this should be documented? Can you suggest the text?

**Comment by WernerMairl** [comment]
> Can you suggest the text?


no sorry, english is my 3° language with a lot of difficults for me!

Issue  https://github.com/aspnet/Hosting/issues/1056 contains a god explanation and can be used as basic idea!

> can you suggest where this should be documented?

- We have a "known issues" area (release notes) ?

- The story behind my usecase (that can help to find the right place for documentation)
i was starting from some of the default samples/docs for using ConfigurationBuilder and appsettings.json.
then i come to the idea of putting multiple json files into one by using sections
=> no samples available for this usage of GetSection
then i run into the error always assuming that something is wrong on my idea - it takes me a full day to find out that it is bug inside the Library.

so my suggestion
a) extend the default documentation with the idea/sample of using multiple sections
b) put warning here about the known issue
c) provide a workaround on the same place

i hope that helps...

regards
Werner

**Comment by Rick-Anderson** [comment]
@GuardRex  would you mind commenting on this? I'll fix it, don't spend more than 5 minutes on it.

**Comment by GuardRex** [comment]
The problem is very well laid out by @kierenj in https://github.com/aspnet/Hosting/issues/839#issue-171836583.

The easy way to go is to splice a `![NOTE]` into https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting#overriding-configuration, possible linking that :point_up: issue and possibly mentioning the workaround of @AndSDev at https://gist.github.com/AndSDev/03b2ed680ded355724bef4f7e02df491.

**Comment by GuardRex** [comment]
If you want a `![NOTE]` passage, let me know. Now that I'm back to being semi-retired, I have *plenty of time* to knock something up. :grinning:

**Comment by Rick-Anderson** [comment]
That would be awesome!

**Comment by GuardRex** [comment]
Sure ... I'm going out for a 🚴 ride (one of my retirement duties! lol), and I'll shoot u back something shortly.
