### ISSUE TITLE
Docs/aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/ tests does not run after upgrade to the latest nuget packages

### ISSUE THREAD

**Issue by hanslai** [aspnet/Docs#3781]
After upgrade to the latest nuget packages for Docs/aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/  none of the test will run.

And the output windows shows nothing.

The tests run fine before package upgrade.
running VS 2017 Version 15.2

**Comment by guardrex** [comment]
This was probably fixed by https://github.com/aspnet/Docs/pull/4157.

@hanslai Have you had a chance to try it after those updates on Aug. 30 :point_up:? I did the updates with VSC, but the tests should run equally well in VS.

**Comment by guardrex** [comment]
@Rick-Anderson No answer here, and this should be fixed by #4157.
