### ISSUE TITLE
Feedback: EF Doc walkthrough: Saving data 

### ISSUE THREAD

**Issue by rynowak** [aspnet/Docs#3787]
This is my collected feedback from https://github.com/aspnet/Release/issues/191 that was part of 2.0.0 signoff activities.

## Sample Code Issues:
I opened https://github.com/aspnet/EntityFramework/issues/9220 and https://github.com/aspnet/EntityFramework/issues/9222 based on the sample code for these docs, but both of these items were resolved as by-design.

The sample code needs to be updated for cases that rely on lazy loading in the 'Related Data' page.  See https://github.com/aspnet/EntityFramework/issues/9222 for an example. The fix is to add an `.Include(b => b.Posts)` where we retrieve the blog if we want to also retrieve its posts.

The sample code should also be updated to call `db.SaveChanges()` where it *almost* provides the code needed to seed the database, see https://github.com/aspnet/EntityFramework/issues/9220 for an example. I found a cases like this in the 'Basics' doc.

The sample at https://github.com/aspnet/EntityFramework.Docs/blob/master/samples/core/Saving/Saving/ExplicitValuesGenerateProperties/EmployeeContext.cs has obsolete code and needs to be updated. `Warning	CS0618	'IMutableProperty.IsReadOnlyAfterSave' is obsolete: 'Use AfterSaveBehavior instead.'`

One minor style issue, I noticed that the sample code alternately uses `context` and `db` for the `DbContext` variables.

## Content Issues
If found the section on 'removing relationships' to be very frustrating, it introduces the concept of a cascading delete at https://docs.microsoft.com/en-us/ef/core/saving/related-data#removing-relationships and then I had to click through many more links to find out what behavior I should expect by default 

https://docs.microsoft.com/en-us/ef/core/saving/related-data#removing-relationships links to
https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete then to
https://docs.microsoft.com/en-us/ef/core/modeling/relationships 

At this point you can find the section labeled 'Cascade Delete' and it will like you to https://docs.microsoft.com/en-us/ef/core/modeling/relationships#Required which appears to be a dead link.

Then if you search for 'Required' and find that section, it links you to https://docs.microsoft.com/en-us/ef/core/modeling/required-optional and at this point you have all of the information at this point.

It seems like it would be better to just duplicate some of this information where it is necessary. The table describing the three types of cascade delete behavior appears in a few different docs I looked at on this journey, but it took a lot of work to find out which of those three behaviors I should expect from this simple sample which just demonstrates the common idiom.

**Comment by ajcvickers** [comment]
Thanks Ryan! 👍 Moved to EF-docs repo.
