### ISSUE TITLE
aspnet/core/tutorials/first-web-api show how to pass multiple params

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3790]
add 2nd param for all items where is IsComplete = false or true, whatever you pass.
Customer asked for this.

**Comment by rachelappel** [comment]
@scottaddie Is this applicable to what you're working on? Web API stuff, correct? Or is that @guardrex?

**Comment by scottaddie** [comment]
@rachelappel @Rick-Anderson Is there any more detail to provide on this? It's not clear to me what needs to be done.
