### ISSUE TITLE
aspnetcore/getting-started.md

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3793]
[Getting Started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started)

- [x] In 2.x, restore is not needed. Perhaps add a note saying so. See comments in https://github.com/aspnet/Docs/pull/3792

- [x] The install instructions link for windows users defaults to the VS2017 installer, not what we want:

1.  Install [.NET Core](https://microsoft.com/net/core)

The problem with that link on Windows is it defaults to install Visual Studio - which is a major diversion from this tutorial.  And we can't hard code the right tab - ie command line - `https://www.microsoft.com/net/core#windowscmd`

![image](https://user-images.githubusercontent.com/3605364/28479569-cf878fec-6e11-11e7-95f6-04ac1c028100.png)
because that would break all the other environments

@danroth27 @scottaddie @tdykstra

**Comment by danroth27** [comment]
I think we should update the default getting started instructions for 2.0, and then have a link to separate getting started instructions for 1.1 (i.e. "Looking to get started with 1.1? Go __here__").

We'll need to follow up separate with folks to get the [Getting Started with ASP.NET Core](https://www.microsoft.com/net/core#windowsvs2017) page updated.

**Comment by tdykstra** [comment]
@danroth27 In a basic, as-simple-as-possible getting-started tutorial, why would we even offer prior-version instructions, i.e., why not just present 2.0 instructions?  We already have one comment that reads "Previous versions required ... if you get an error ... install the latest".  If someone wants to learn 1.1 they must already know something about ASP.NET Core and this wouldn't be the right place for them to go.

**Comment by danroth27** [comment]
The 2.0 instructions are definitely the top priority. We want to direct new users to 2.0

ASP.NET Core 1.1 will still be supported however for a while after 2.0 ships, so the 1.1 specific docs shouldn't just disappear.

**Comment by Rick-Anderson** [comment]
>ASP.NET Core 1.1 will still be supported however for a while after 2.0 ships, so the 1.1 specific docs shouldn't just disappear.

We can save a PDF for 1.1 like we did with VS 2015. We don't want to maintain two versions and we'd like folks to move to 2.0. I don't see much demand for a 1.1 version of this tutorial.

**Comment by tdykstra** [comment]
> I don't see much demand for a 1.1 version of this tutorial.

That's the issue -- elsewhere we are saving 1.1 text by putting it in 1.x vs. 2.x tabs, but for this ultra simple getting started tutorial I can't think of why someone would need a 1.1 version.  I can see keeping a 1.1 version of Intro to MVC.

**Comment by danroth27** [comment]
> We don't want to maintain two versions

That decision can't be made at the documentation level. .NET Core has a published support policy, so until 1.1 goes out of support the 1.1 documentation needs to continue to be available.

What's the concern with maintaining the 1.1 getting started content on a separate page?

**Comment by tdykstra** [comment]
It's the nature of the documentation.  It's a simple install link + a few CLI commands and you're done.  It's not documenting anything that isn't already covered in dozens of other places.  And it's not like we'd be saving the prior version as-is, we'd have to write a new one that explains how to install an old version and how to make sure your CLI commands use it even if a newer version is installed.  It becomes a different sort of document than the "here's how quick you can do a hello world" that the original is.

**Comment by danroth27** [comment]
You might need the 1.1 version, for example, to get the install links for setting up a 1.1 machine for a new member of your team. You might not have moved forward to 2.0 yet for a variety of reasons (you're targeting an older .NET Framework version, your organization adopts things slowly, you're already working on a 1.1 app that's in production and migration isn't a priority right now, etc.)
