### ISSUE TITLE
Documentation outdated for 2.0

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Docs#3796]
[The doc for authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index) is out of date for 2.0 release where authentication was redone. See https://github.com/aspnet/Security/issues/1310 for the scope of changes. 

The doc also reads: "For Visual Studio 2017 RC1" even though VS 2017 shipped months ago.

The instructions for external providers linked from this page are also outdated but workable.

**Comment by scottaddie** [comment]
This issue will be addressed in https://github.com/aspnet/Docs/pull/3874.
