### ISSUE TITLE
It is not clear that application id is actually client id

### ISSUE THREAD

**Issue by moozzyk** [aspnet/Docs#3797]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins

This doc talks about application id and suddenly uses client id without pointing that these two terms are equivalent. Microsoft Developer Portal does not use the term "clientid" so it is confusing for people doing this the first time.

**Comment by Rick-Anderson** [comment]
@01binary

**Comment by guardrex** [comment]
@moozzyk This sentence (the first place `ClientId` is mentioned) doesn't cover it?

> Although the terminology used on Microsoft Developer Portal names these tokens `ApplicationId` and `Password`, they are exposed as `ClientId` and `ClientSecret` to the configuration API.

Idea ... a note could go immediately after the image that shows them both:

![microsoftdev](https://user-images.githubusercontent.com/1622880/30202740-16f2d6da-9445-11e7-9fbd-869f98a00c9c.png)

Something like ...

> `ApplicationId` and `ClientId` are equivalent but used in different places. The Microsoft Developer Portal uses `ApplicationId`, while `ClientId` is used by `MicrosoftAccountOptions` to configure the Microsoft Account Middleware and when using the Configuration API.

**Comment by moozzyk** [comment]
I must have missed the "App ID/ Client Id" on the picture and then when I searched with Ctrl + F the term "ApplicationId" (or Application Id) is nowhere near the picture. I think it would be enough to just change:

`Note the Application Id displayed on the Registration page`

to something like

`Note the Application Id displayed on the Registration page - you will use it as the client-id in the commands below`

**Comment by guardrex** [comment]
Cool. I'll take care if it and ping u on the PR.
