### ISSUE TITLE
tutorials/first-web-api Webapi Web api - UseInMemoryDatabase API has changed.

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Docs#3800]
https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api/sample/TodoApi/Startup.cs#L12

The no param `UseInMemoryDatabase` has been deprecated (see https://github.com/aspnet/EntityFramework/blob/rel/2.0.0/src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs#L83). This code needs to be updated.

**Comment by Rick-Anderson** [comment]
using the latest Microsoft.EntityFrameworkCore 2.0.0 and Microsoft.EntityFrameworkCore.InMemory 2.0.0, the statement:

  services.AddDbContext<TodoContext>(opt => opt.UseInMemoryDatabase());

gets error:

     DbContextOptionsBuilder' does not contain a definition for 'UseInMemoryDatabase'
The solution is to include a name as follows:

   services.AddDbContext<TodoContext>(opt => opt.UseInMemoryDatabase("TodoList"));

**Comment by harshalyeole-tudip** [comment]
@Rick-Anderson 

The solution is to include a name as follows:

services.AddDbContext(opt => opt.UseInMemoryDatabase("TodoList"));

Tried above solution and didn't work.
