### ISSUE TITLE
Misleading data in tutorial doc

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Docs#3801]
The "Update" part of https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?tabs=aspnet20 tutorial has misleading input data for the PUT request.

The request body in this https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api/_static/pmc.png image has `"key": 2` but there is no field in `TodoItem` named `key`. It should be `id` instead.

**Comment by Rick-Anderson** [comment]
@ajaybhargavb  thanks. Dup of #3076
