### ISSUE TITLE
Migrating from ASP.NET proper to ASP.NET Core 2.x

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#3809]
For customers who still haven't moved to ASP.NET Core from ASP.NET proper, it would be useful to have a migration doc. This doc should serve as a reference, not an end-to-end walkthrough.

**Comment by isaac2004** [comment]
@scottaddie, I can take this depending on the timeline. What version of Core should the guide target?

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scottaddie** [comment]
@isaac2004 The goal is to cover migration to ASP.NET Core 2.0. No particular timeline in mind. Take a crack at an outline for the doc and post it here for approval before going too far.

**Comment by isaac2004** [comment]
So basically update this doc and children docs?

https://docs.microsoft.com/en-us/dotnet/core/porting/

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scottaddie** [comment]
@isaac2004 The doc you linked to lives in the **dotnet/core** repo, which focuses on .NET Core. Here, we want to keep the focus on ASP.NET Core &mdash; specifically, migrating an ASP.NET MVC 5 or Web API 2 application to ASP.NET Core 2.x. The thought is that many ASP.NET proper customers haven't used ASP.NET Core yet.

What I'm proposing in this issue is a brand new doc that would live under the [**Migration** node](https://docs.microsoft.com/en-us/aspnet/core/migration/) in the table of contents. This new doc should be more of a reference doc than an end-to-end walkthrough tutorial. It would be written in a similar style as what I'm working on here: https://github.com/aspnet/Docs/pull/3768.

@Rick-Anderson Is there anything in particular that you'd like addressed in this doc?

**Comment by Rick-Anderson** [comment]
>@Rick-Anderson Is there anything in particular that you'd like addressed in this doc?

No.
Looking for reference style doc going from MVC 5/Web API 2 to ASP.NET Core 2.

**Comment by isaac2004** [comment]
@scottaddie @Rick-Anderson 

I took an hour to think through what I would like from a doc to act as a "Reference Guide" when migrating my Web Application from .Net Framework 4.x to ASP.NET Core 2 and here is what I came up with, let me know if there is stuff missing/not needed


- Prerequisites
   - Tooling, links to other docs, etc

- Benefits to Core vs Proper
    - Platform Independence (infographic for instance)
    - Performance Gains from using Core

- Key package changes
  - Common assemblies and core equivalent (table or mapping diagram)
  - Assemblies not supported in Core

- .Net Standard
    - Introduction to .Net Standard and what it looks like

- Project structure differences
  - Changes to .csproj
  - Middleware (App_Start/Global.asax vs Startup.cs)

- Storing Configurations
   - Using appsettings.json vs Web.config sections

- DI first class citizen
   - Code sample of built in DI

- Static file / wwwroot
   - Adding assets and publishing through wwwroot

**Comment by Rick-Anderson** [comment]
Skip benefits - that's another doc. This should focus what you need to know to migrate.
~Benefits to Core vs Proper~

~Platform Independence (infographic for instance)~
~Performance Gains from using Core~

Outline looks like a good start. Maybe look at [Migrating From ASP.NET MVC to ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/migration/mvc) and rewrite that as a ref doc - rather than the current walk-through.  Make sure all the topics in that series are covered.

@scottaddie  any thoughts?

**Comment by isaac2004** [comment]
@scottaddie @Rick-Anderson I'll take a look at that step-by-step doc. Do we still need something like that? Or is the reference good enough?

_Sent from my Samsung SM-G955U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scottaddie** [comment]
@isaac2004 The reference doc is good enough.

**Comment by isaac2004** [comment]
Sounds good, I'll fork and start in a new file. Figure out what to do when it is farther along.

**Comment by scottaddie** [comment]
Addressed with #3897
