### ISSUE TITLE
Update "Get started with ASP.NET" 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3819]
See [ASP.NET Documentation](https://docs.microsoft.com/en-us/aspnet/#pivot=aspnet&panel=aspnet_overview)

![image](https://user-images.githubusercontent.com/3605364/28583676-de02376a-711e-11e7-9a7f-c35207115c79.png)

It sends you to a VS download and has nothing about ASP.NET. Recommend we replace that target with one of the following:

- [ASP.NET overview](https://docs.microsoft.com/en-us/aspnet/overview)
- [ASP.NET tutorials](https://docs.microsoft.com/en-us/aspnet/tutorials)

cc @tdykstra

**Comment by tdykstra** [comment]
We would have to change the text in the card too, since it does say "Download VS ..."
An alternative would be to replace "Get started..." with "Download Visual Studio" and make the text below it read "Visual studio is the free IDE for ASP.NET on Windows."
