### ISSUE TITLE
Dead link in aspnet/core/fundamentals/servers/weblistener

### ISSUE THREAD

**Issue by mjrousos** [aspnet/Docs#3821]
The link to [Windows Authentication](https://docs.microsoft.com/en-us/security/authentication/windowsauth.md) in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener leads to a 404.

**Comment by scottaddie** [comment]
@mjrousos Thank you for reporting this. The fix has been merged.
