### ISSUE TITLE
Integration test against Index action of the HomeController of  ASP.NET Core Web Application (.Net Core) it's return an error page

### ISSUE THREAD

**Issue by erangaapp** [aspnet/Docs#3834]
I trying to test against Index action of the HomeController of  ASP.NET Core Web Application (.Net Core)
and when I debug the test for 

**var response = await _client.GetAsync("/");**

> response was an internal server error with following html part. So what should be the reason for this.
>Where should add reference for those assemblies.

<h1>An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.</h1>
    <div id="stackpage" class="page">
        <div class="titleerror">/Views/_ViewImports.cshtml</div>
        <div class="details">One or more compilation references are missing. Possible causes include a missing &#x27;preserveCompilationContext&#x27; property under &#x27;buildOptions&#x27; in the application&#x27;s project.json.</div>
        <br />
        <ul>
            <li class="frame" id="frame1">
                <h3>The type or namespace name &#x27;Identity&#x27; does not exist in the namespace &#x27;Microsoft.AspNetCore&#x27; (are you missing an assembly reference?)</h3>

                <button class="expandCollapseButton" data-frameId="frame1">+</button>
                <div class="source">
                    <ol start="1" class="collapsible">
                        <li><span>@using web</span></li>
                        <li><span>@using web.Models</span></li>
                        <li><span>@using web.Models.AccountViewModels</span></li>
                        <li><span>@using web.Models.ManageViewModels</span></li>
                    </ol>
                    <ol start="5" class="highlight">
                        <li><span>@using Microsoft.AspNetCore.Identity</span></li>
                    </ol>
                    <ol start='6' class="collapsible">
                        <li><span>@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers</span></li>
                        <li><span></span></li>
                    </ol>
                </div>
            </li>
        </ul>
        <br />
    </div>

**Comment by Rick-Anderson** [comment]
@erangaapp  See https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing
This is not a support forum. If you find a problem with a document, open an issue.
