### ISSUE TITLE
Documentation pages generating browser errors in the console

### ISSUE THREAD

**Issue by WiredUK** [aspnet/Docs#3844]
The docs pages are generating lots of errors in the console. For example:

>Failed to load resource: the server responded with a status of 400 (Invalid instrumentation key)

Seems to be some sort of Javascript that runs on a timer. Happens on any page that has actual docs (i.e. doesn't seem to happen on the homepage.) Screenshot for info:

![image](https://user-images.githubusercontent.com/7810709/28718458-028508c0-739e-11e7-9d64-1773f1c91559.png)

**Comment by scottaddie** [comment]
I've confirmed that this isn't specific to the ASP.NET Core docs and that it occurs in Edge as well:
![error](https://user-images.githubusercontent.com/10702007/28720332-7deb1a26-7372-11e7-9d9f-d35f624ea118.png)

**Comment by Rick-Anderson** [comment]
@dend

**Comment by Rick-Anderson** [comment]
@DuncanmaMSFT  do you have an public issue we can track?

**Comment by WiredUK** [comment]
@Rick-Anderson I assume this means there's something internal going on that you can't share? It's not clear why it was closed otherwise.

**Comment by Rick-Anderson** [comment]
@WiredUK  sorry - yes we have an internal bug on this. It's a microsoft.docs issue, not ASP.NET.
