### ISSUE TITLE
aspnet/core/security/authentication/social/ for 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3862]
@01binary - this from @timheuer

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins 
i'm following this doc and after adding the middleware package, the api AddGoogleAuthentication (and the Microsoft one) are not available
I think it should be app.Use* 

MSA auth would fails
-- end of Tim --

Can we mark off the steps that require ASP.NET Core 2.0? Did we lose the steps for 1.x?

I think Tim has Google working but not MSA. Any trouble shooting tips?

**Comment by 01binary** [comment]
We can add a tabbed container with code snippets for 1.x and 2.x. I dropped 1.x steps because they constitute breaking changes. The 1.x snippets can be recovered from previous version to add them back.

**Comment by 01binary** [comment]
> I think Tim has Google working but not MSA. Any trouble shooting tips? @RickAndMSFT 

I verified MSA for 2.0 at the time of writing that topic. Does @timheuer want to start an email chain or post here to describe his experience? The step where it fails is important. Did he look at Troubleshooting section?
