### ISSUE TITLE
EF Getting Started Doc updates for 2.0.0

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Docs#3866]
Following up with issues found in EF getting started docs during 2.0.0 signoffs at https://docs.microsoft.com/en-us/ef/core/get-started/

- .NET Framework - New Database: `Templates ‣ Visual C# ‣ Windows` is now called `Templates ‣ Visual C# ‣ Windows Classic Desktop`
- .NET Framework - New Database: `Console Application` is now called `Console App (.NET Framework)`
- .NET Framework - Existing Database: We no longer build the package `Microsoft.EntityFrameworkCore.SqlServer.Design` documentation needs to be updated to reflect this.
- ASP.NET Core - New Database: Need to create project with selection `Web Application (Model-View-Controller)` to be able to scaffold with `MVC Controller with views, using Entity Framework` later on in the walkthrough.
- ASP.NET Core - New Database: Need to install `Microsoft.VisualStudio.Web.CodeGeneration.Design` to enable scaffolding in the project.
- ASP.NET Core - Existing Database: Need to create project with selection `Web Application (Model-View-Controller)` to be able to scaffold with `MVC Controller with views, using Entity Framework` later on in the walkthrough.
- ASP.NET Core - Existing Database: Need to install `Microsoft.VisualStudio.Web.CodeGeneration.Design` to enable scaffolding in the project.
- ASP.NET Core - Existing Database: We no longer build the package `Microsoft.EntityFrameworkCore.SqlServer.Design` documentation needs to be updated to reflect this.
- ASP.NET Core - Existing Database: `OnConfiguring` snippet to delete looks different
Currently:
```c#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    #warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
    optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;");
}
```
New:
```c#
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Blogging;Trusted_Connection=True;");
            }
        }
```
- UWP scenario is not currently supported. `Install-Package : Package Microsoft.EntityFrameworkCore.Tools 2.0.0 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x86-aot. Package Microsoft.EntityFrameworkCore.Tools 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)`

**Comment by Rick-Anderson** [comment]
moved to EF docs repo https://github.com/aspnet/EntityFramework.Docs/issues/427
