### ISSUE TITLE
[2.0] Use AssetTargetFallback in sample?

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#3871]
The sample in [Adding a model to an ASP.NET Core MVC app](https://docs.microsoft.com/aspnet/core/tutorials/first-mvc-app-mac/adding-model) (*start-mvc/sample/MvcMovie.csproj*), uses `PackageTargetFallback`. Prompted by a discussion regarding `PackageTargetFallback` [here](https://github.com/dotnet/cli/issues/3439#issuecomment-319702662), this might (probably) require work ... versioned samples?

Cross-ref:
https://github.com/NuGet/docs.microsoft.com-nuget/issues/410
https://github.com/dotnet/docs/issues/2816

**Comment by GuardRex** [comment]
@tdykstra, if you need this and provide guidance on how u want it fixed, I can square it away tonight.

**Comment by tdykstra** [comment]
I'm not working on start-mvc at the moment, but @Rick-Anderson might be interested.

**Comment by Rick-Anderson** [comment]
@guardrex  can you fix this?

**Comment by guardrex** [comment]
The concern here (based on only a quick look) is that the sample should go 2.0 SxS with the existing 1.1 version, and the current 1.1 sample is possibly tied into several topics.

In order to get a SxS 2.0 with new 1.1+2.0 sample folders (i.e., the cheese moves for the 1.1 sample), then a whole bunch of topics will need help with the changes (if this search result is accurate): https://github.com/aspnet/Docs/search?utf8=%E2%9C%93&q=start-mvc%2Fsample&type=

Anywho ... the short answer is *Yes!* I can do it. Next week ok?

**Comment by Rick-Anderson** [comment]
We aren't keeping the 1.x version. I'll update this series this week and ping you when I get stuck. We don't keep older versions.

**Comment by guardrex** [comment]
Ah! Yes ... makes sense. It still may touch several topics, but surly not as much as I initially thought. Sure thing, I'll be around to help where needed.

**Comment by guardrex** [comment]
@scottaddie Good news here, too. :smile: No 2.0 samples call for a \<PackageTargetFallback>. Authors can just pull it as they go when updating 1.x or adding new 2.0 samples. We can close here. :+1:
