### ISSUE TITLE
Add App Insights to Building Real-World Cloud Apps e-book

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3873]
The telemetry chapter of the Building Real-World Cloud Apps e-book was written before App Insights was released.

https://docs.microsoft.com/en-us/aspnet/aspnet/overview/developing-apps-with-windows-azure/building-real-world-cloud-apps-with-windows-azure/monitoring-and-telemetry

**Comment by Rick-Anderson** [comment]
@tdykstra  that series is so obsolete can we get them to retire it and open an issue in the Azure repro? Maybe open an issue in Azure asking them to retire that series too - then close this issue?

**Comment by tdykstra** [comment]
Like a lot of the P&P ebooks, the material is old but much of it is still useful.  If we retired everything that's old in the /aspnet/ folder of the repo there wouldn't be much left.  My suggestion is to leave this open with a low priority, and see if someone eventually volunteers to do the update.

**Comment by isaac2004** [comment]
@Rick-Anderson @tdykstra is the goal to redo that one doc or eventually every one? Maybe we should be rewriting it for Core 2.0 or .Net 4.7

**Comment by tdykstra** [comment]
I'm not working on ASP.NET docs now, so @Rick-Anderson or @scottaddie would know more about current plans for that series.  I believe it would be worth updating if we had enough people interested in working on it.
cc @guardrex

**Comment by isaac2004** [comment]
@Rick-Anderson @scottaddie comments?

**Comment by Rick-Anderson** [comment]
@isaac2004  
I would update the article with a note at the top saying something like

The article was written before App Insights was released. App Insights is the preferred approach for telemetry on Azure. See the following links for more information:

* link 1
* link 2

**Comment by isaac2004** [comment]
@Rick-Anderson PR opened
