### ISSUE TITLE
aspnet/core/publishing/iis#configuration-of-sub-applications clarification and samples

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#3877]
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#configuration-of-sub-applications
https://github.com/aspnet/Hosting/issues/1156#issuecomment-319850581

The current text describes hosing nested ASP.NET Core applications as sub applications under other ASP.NET Core applications. In that case you need to exclude `<add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />` from the sub application.

However, if you want to host a non-ASP.NET Core sub app underneath an ASP.NET Core app you have to explicitly remove the inherited handler in the sub application.
```
<system.webServer>
  <handlers>
    <remove name="aspNetCore"/>
  </handlers>
</system.webServer>
```

**Comment by GuardRex** [comment]
@Tratcher 

> The current text describes hosing nested ASP.NET Core applications as sub applications under other ASP.NET Core applications. In that case you need to exclude `<add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />` from the sub application.

For that use case, excluding the `<handlers>` section does the same thing as not having `<add>`. Do you prefer it to say explicitly something along the lines of (expressing the idea ... not these exact words) ...

> If a **\<handlers>** section is present in a sub-app *web.config*, the ANCM **\<add>** shouldn't be present in the **\<handlers>** section.

RE the non-ASP.NET Core sub app scenario ...

> if you want to host a non-ASP.NET Core sub app underneath an ASP.NET Core app you have to explicitly remove the inherited handler in the sub application.

Easy ... I'll make a PR with this in the commit, including your example.

**Comment by Tratcher** [comment]
The first case should include a sample rather than just describe it:
```
<system.webServer>
  <aspNetCore processPath="dotnet" arguments=".\XXX.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
</system.webServer>
```
