### ISSUE TITLE
Update Your First ASP.NET app article to use EF7 and highlight more tooling features

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#388]
We want to:
- Highlight more of the cool stuff in ASP.NET 5 and the VS tooling (project.json IntelliSense, resolving packages using ctrl-., searching the package graph in the solution explorer, publishing to the cloud, edit-save-F5 (already there), debug profiles, running commands, etc.)
- Include data access in this initial tutorial
- Provide more links to more detailed topics
- Leave the user feeling like the platform is simple, productive and has a lot of great stuff to offer. 

Outline...
<updated - See below>

**Comment by Erikre** [comment]
Here are the updated sections along with new title for the topic:

Title: Your First ASP.NET 5 Web App Using Visual Studio
•	Overview
•	Audience
•	What you’ll learn
      o	How to create a new ASP.NET 5 project.
      o	The file structure of the project.
      o	How to run the project in Visual Studio.
      o	The different features of the default ASP.NET 5 application.
      o	Some basics about how to use the Visual Studio environment.
      o	How to create a data model.
      o	How to initialize and seed the database.
      o	How to update and configure the application to support the database.
      o	How to publish and run the web app in Azure
•	Prerequisites
•	Create a new ASP.NET 5 project
      o	Understanding .NET Core
•	Review the project
•	Run the default web application
•	Review the features of the web project
•	Tour Visual Studio 2015
       (We should fine-tune what we need here:)
      o	IntelliSense
      o	(resolving packages using ctrl-)
      o	(searching the package graph in the solution explorer)
      o	(publishing to the cloud)
      o	(edit-save-F5)
      o	(debug profiles)
      o	(running commands)
•	Create a data model
•	Configure the web application to use the data model
•	Build the web application
•	Run the web application locally
•	Create a web app in the Azure preview portal
•	Enable Git publishing for the new web app
•	Publish the web app to Azure App Service
•	Run the app in Azure
•	Summary
•	Additional resources

**Comment by danroth27** [comment]
Blocked on scaffolding not being available in VS yet.
