### ISSUE TITLE
2.0 update to Create an ASP.NET Core MVC app with VS Code

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3887]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/

**Comment by isaac2004** [comment]
@Rick-Anderson what needs to be fixed here? Just the sample? First glance at the docs themselves look fine

**Comment by Rick-Anderson** [comment]
@isaac2004  it looks like it has been updated for 2.0
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/adding-view

Note: The ASP.NET Core 2.0 version is slightly different. It doesn't contain @inject ApplicationInsights and @Html.Raw(JavaScriptSnippet.FullScript).
