### ISSUE TITLE
Ensure that Razor Pages are presented consistently as part of MVC

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3888]
Make sure we consistently refer to Razor Pages as part of MVC and not a separate thing. 

For content that uses MVC with controllers and views add the phrase “with controllers and views”. Razor Pages should generally be assumed, but it’s ok to say “with Razor Pages” when additional clarity is needed.

**Comment by Rick-Anderson** [comment]
dup of #3551
