### ISSUE TITLE
Update 2.0 install instructions when .NET Core 2.0.0 RTW

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3903]
- [x] aspnet/core/getting-started-1.1
- [x] aspnet/core/getting-started
- [x] https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/
- [x] https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start
- [x] https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc
- [x] https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/start-mvc
- [x] https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/start-mvc
- [ ] https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api-mac
- [x] https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api
- [ ] https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc

**Comment by isaac2004** [comment]
@Rick-Anderson @scottaddie are these currently being worked on? Seems like some are updated.

**Comment by danroth27** [comment]
We should remove all version specific installation instructions from these pages. Just point people to https://dot.net/core and https://visualstudio.com.

**Comment by Rick-Anderson** [comment]
@danroth27  wrote

> We should remove all version specific installation instructions from these pages. Just point people to https://dot.net/core and https://visualstudio.com.

That won't work for 1.x versions of the doc. Once ASP.NET Core 3.0 RTW's, it won't work for the 2.x version.  cc / @rachelappel  @scottaddie

**Comment by Rick-Anderson** [comment]
@isaac2004  They're all updated now. Let me know if you find any missing.
