### ISSUE TITLE
Middleware for clientCache, doDynamicCompression and doStaticCompression

### ISSUE THREAD

**Issue by martinkearn** [aspnet/Docs#391]
Are there any existing (or plans to write) middleware components so that the three concepts in the title can be used in ASP.net 5 via startup.cs?

In 4.5 i could do this:

    <staticContent>
      <clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="365.00:00:00" />
    </staticContent><urlCompression doStaticCompression="true" doDynamicCompression="true" /> 

I appreciate that these are IIS concepts, but other servers must presumably offer the same type of features and even if they don't, I still want to do this stuff on IIS.

**Comment by danroth27** [comment]
Not sure. @Tratcher do you know?

**Comment by Tratcher** [comment]
ClientCache can be implemented via OnPrepareResponse (https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNet.StaticFiles/StaticFileOptions.cs#L54) where you can set any headers deem appropriate.

I would expect the dynamic compression to still work when running in IIS. The static and cache compression probably don't work.
