### ISSUE TITLE
HttpContext thread safety issues

### ISSUE THREAD

**Issue by muratg** [aspnet/Docs#3916]
HttpContext is not thread safe and folks are falling into pitfalls quite often. One recent example is here: https://github.com/aspnet/HttpAbstractions/issues/839 

We should doc the behavior and show examples of correct usage (queue access to HttpContext for example.)

**Comment by Rick-Anderson** [comment]
@danroth27   and @muratg  where should we document this? Can you provide an outline and sample code?

**Comment by danroth27** [comment]
@Rick-Anderson Did you mean to close this?

**Comment by danroth27** [comment]
@Tratcher Do you want to propose a change for this one?

**Comment by Tratcher** [comment]
This is likely best covered by the [guidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/0ba7625050f975f8a7df1df57c80ad08da250541/AspNetCoreGuidance.md#do-not-use-the-httpcontext-after-the-request-is-complete) @davidfowl is putting together. We'll need to figure out where that ends up back in the docs.

**Comment by rynowak** [comment]
https://github.com/aspnet/Docs/pull/11133
