### ISSUE TITLE
Change links to point to 2.0 API ref when available

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#3926]
- [x] update the link on the [ASP.NET Core hub page](https://docs.microsoft.com/en-us/aspnet/#pivot=core&panel=core_overview)
- [x] redirect the old API ref docs for 1.1 and 1.0 to the new pages at https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-1.1 and https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-1.0.

--- original issue ---
The servers docs (Kestrel, HttpSys) link to source code for details about options and other API because 2.0 API Ref isn't available yet.  When it is available, convert those source code links to the equivalent API ref links.

Docs:
[Servers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/)
[Kestrel](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel)
[HttpSys](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys)
[WebListener](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener)

**Comment by danroth27** [comment]
@Rick-Anderson The 2.0 docs are now available at https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0. We need to update the link on the ASP.NET hub page and redirect the old API ref docs for 1.1 and 1.0 to the new pages at https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-1.1 and https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-1.0.

**Comment by Rick-Anderson** [comment]
- [ ] update the link on the [ASP.NET Core hub page](https://docs.microsoft.com/en-us/aspnet/#pivot=core&panel=core_overview)
- [ ] redirect the old API ref docs for 1.1 and 1.0 to the new pages at https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-1.1 and https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-1.0.

**Comment by Rick-Anderson** [comment]
@v-savila  this is the issue tracking update the link on the [ASP.NET Core hub page](https://docs.microsoft.com/en-us/aspnet/#pivot=core&panel=core_overview)
Your PR #4457 was to the wrong file.

**Comment by v-savila** [comment]
@Rick-Anderson I've reverted that page (aspnet\aspnet\index.md) to the original file with the redirect and updated the correct file (aspnet\index.md).

**Comment by Rick-Anderson** [comment]
@v-savila  where is the PR?

**Comment by v-savila** [comment]
@Rick-Anderson https://github.com/aspnet/Docs/pull/4478
