### ISSUE TITLE
Complete Linux docs to install dnvm on CentOS

### ISSUE THREAD

**Issue by SpaceShot** [aspnet/Docs#394]
I want to help update the docs to display these minor changes for CentOS (mostly package management).  I would like to discuss what the expectation is for a baseline install.  

Also, disclosure:  Linux newbie who is learning this because of aspnet.  Comments welcome.

#### CentOS 7 with GNOME desktop

I'm working on a CentOS 7 install now where I installed with the GNOME environment selected.  (Used CentOS-7-x86_64-DVD-1503-01.iso downloaded here: https://www.centos.org/download/)

Then I followed the instructions line by line here and got DNVM running:
https://gist.githubusercontent.com/SpaceShot/82442bd3999067f9cd21/raw/da80db723c30d52696f9544c8e03da04d2a252de/yum_install_prereqs.sh

I have not been able to follow through and run an aspnet app generated with yeoman because dnu restore keeps failing with "HTTP request timed out", but I'm still working on this.

#### CentOS 7 minimal (networking only)

I've also installed CentOS (VirtualBox again) without a desktop and have been working through that.  That install is really minimal, so more was required, including installing yum-utils.  

#### Azure?

Should an Azure VM be the baseline?

**Comment by SpaceShot** [comment]
Update:
I have a script that works for me on CentOS 7 (a VirtualBox guest).  During CentOS install I only select the GNOME desktop environment and turn on networking.  

Once the box comes up, I do kickstart the software updater can go to work (what I've found is that it has some process that is using yum and locks it, so I couldn't start the script right off... not seeing this on Ubuntu desktop).  I also have just started the Software Updater via the GUI and forced it along.  The point was to get locking on yum out of the way.

Then in a terminal window:

```
wget https://gist.githubusercontent.com/SpaceShot/bc9c5c18d63a20bcae56/raw/735bfdb2f8a3417642db6be70c5e25cd784ee978/setup_aspnet5_centos7_minimal.sh --output-document=install_aspnet5.sh && bash install_aspnet5.sh
```

I have some cleanup to do.  I realize now how the dnvm install script is trying to detect where to add to the user profile.  I'm adding to .bashrc.  It works but looks funny to the end user.  The key is that I found you really need the Mono environment variable to make dnu restore reliable and on CentOS you need the library variable or dnx doesn't find libuv.

The rest was just researching where to find packages.  I found a way that works for me to get 0.12.7 node and recent npm.  The base yum packages were 0.10 timeframe and npm was warning that yeoman was expecting later.

Appreciate comments and if we want these steps to be documented in the CentOS portion, I can start on that (I want a full script, but I appreciate the current Ubuntu document shows steps).

**Comment by danroth27** [comment]
@glennc Can you take a look at these proposed steps?

**Comment by SpaceShot** [comment]
I have been working on my script, and here is the current state:
https://gist.github.com/SpaceShot/bc9c5c18d63a20bcae56

I want to clarify a few things.  I am doing more than just getting dnvm going.  After that I proceed to make sure I can generate a project (via yeoman) and that I can run it.  I am not proposing that the docs should do this.  The main exercise in this issue is to put something down where it says "instructions coming soon".

The major difference between Ubuntu 14.04 and CentOS 7 is of course use of package management.  I found a path I liked.  But the major thing I ran into when trying to run dnx was libuv would not load.  I found that adding the LD_LIBRARY_PATH environment variable solved the issue, but I do not pretend to know why.

I've also found I need to add the MONO_THREADS_PER_CPU boost for "dnu restore" to work reliably.  Prior to this I had terrible HTTP timeout issues on Ubuntu and CentOS.

I do not propose to change the docs to go beyond getting DNVM working, but I would like to discuss the need for the environment variable(s) and whether they should be documented.  I think that someone new to Linux and to this process might just say "ehh, doesn't work."

**Comment by glennc** [comment]
Have you looked at https://github.com/aspnet/Docs/pull/413 as well?

I skimmed the latest script and it looks reasonable at the moment. Are you proposing that we give a script like this that people can run once to get everything going or that you break the script into instructions like our existing docs?

**Comment by SpaceShot** [comment]
To be honest, I had little faith in my Linux ability so I didn't create a pull request for the docs.  So I didn't know about #413 but it does look like we're proposing the same thing... to get the docs updated.

That said, I was just proposing we update the docs in the same fashion as the Ubuntu instructions.  I like having the automated script for myself but I wouldn't expect it to be in official docs.

**Comment by glennc** [comment]
Ok cool, do you want to go look at #413 and help get it through then?

**Comment by SpaceShot** [comment]
#413 is going to take care of this
