### ISSUE TITLE
ASP.NET Core 2+ Precompiled By default

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Docs#3954]
On [https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?tabs=aspnet20](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?tabs=aspnet20) to pre-compile views it says to set the MvcRazorCompileOnPublish property should be set to true.

While this will work, technically pre-compiling happens by default now in ASP.NET Core 2 if you don't specify anything at all.  I think this should be mentioned in this article.  I am happy to submit a PR to update, but I wasn't sure exactly how you would like to word this or lay that out.

Thanks,

Scott

**Comment by scottaddie** [comment]
@Rick-Anderson I propose that we remove the XML snippet and mention that the precompilation happens by default. Also, we should mention that for projects targeting .NET Framework, a specific package needs to be installed. This is referenced here: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/#review-your-razor-view-compilation-setting. Thoughts?

**Comment by Rick-Anderson** [comment]
@scottaddie  agreed.

**Comment by scottaddie** [comment]
@scottsauber If you're still willing, please submit a PR with these changes.

**Comment by scottaddie** [comment]
@scottsauber I'll take care of this one, since I'm already in that doc making a related change.

**Comment by scottsauber** [comment]
Sounds good. Sorry about the delayed response. Have had a sick kid at home the last 2 days.

**Comment by scottaddie** [comment]
@scottsauber No worries. Hope the kiddo gets well soon.

**Comment by scottaddie** [comment]
This change was addressed in https://github.com/aspnet/Docs/pull/3996.
