### ISSUE TITLE
Multiple issues on MacOS Issues 

### ISSUE THREAD

**Issue by joaogl** [aspnet/Docs#3965]
## General
I'm created a solution at work using .NET Core under a windows 10 machine using Visual Studio 2017, it's working correctly and I've also deployed it to two servers using Jenkins. Everything works fine! Until I add my mac to mix :| 
On my mac I'm running Jetbrains Rider on the same project and it keeps giving me awkward issues.

## Issues with Existing Topics

One of the issues is on my repository, I got Entity Framework working with code first pattern.

My repository looks something like this:
`        
public virtual bool Update(T item)
        {
            try
            {
                if (EntityUtil<T>.ModifiedBy != null && LoggedUserId > 0)
                {
                    EntityUtil<T>.ModifiedBy.SetValue(item, LoggedUserId);
                }
                if (EntityUtil<T>.ModifiedAt != null)
                {
                    EntityUtil<T>.ModifiedAt.SetValue(item, DateTime.Now);
                }
                using (EFormsContext context = new EFormsContext())
                {
                    context.Entry<T>(item).State = System.Data.Entity.EntityState.Modified;
                    return context.SaveChanges() > 0;
                }
            }
            catch (Exception ex)
            {
                log.Error(ex, ex.Message, null);
                return false;
            }
        }
`

On mac, and only on mac, it crashes every single time on the `EntityUtil<T>.ModifiedAt.SetValue(item, DateTime.Now);`
with a "{System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting date and/or time from character string." error.

Another error that I noticed was with xml...
I got this code:

`                XmlElement element = doc.DocumentElement;
                SignedXml signedXml = new SignedXml(element);
                signedXml.SigningKey = cert.PrivateKey;

                // Tipo de dados "ID" é restrito às strings em NCName:
                //<xs:simpleType name="ID" id="ID">
                //  <xs:annotation>
                //    <xs:documentation source="http://www.w3.org/TR/xmlschema-2/#ID"/>
                //  </xs:annotation>
                //  <xs:restriction base="xs:NCName"/>
                //</xs:simpleType>
                // NCName está definido em http://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName como:
                // NCName	 ::=	(Letter | '_') (NCNameChar)*
                Reference reference = new Reference("#" + element.Attributes["ID"].Value);

                // Vide 5.4.3 "Canonicalization Method" e 5.4.4 "Transforms" em 
                // http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
                reference.AddTransform(new XmlDsigEnvelopedSignatureTransform());
                reference.AddTransform(new XmlDsigExcC14NTransform());

                signedXml.AddReference(reference);
                signedXml.KeyInfo.AddClause(new KeyInfoX509Data(cert));
                signedXml.ComputeSignature();
                XmlElement xmlDigitalSignature = signedXml.GetXml();

                // AuthnRequestType define a ordem dos elementos filhos na schema saml-schema-protocol-2.0.xsd:
                //<complexType name="RequestAbstractType" abstract="true">
                //    <sequence>
                //        <element ref="saml:Issuer" minOccurs="0"/>
                //        <element ref="ds:Signature" minOccurs="0"/>          
                //        <element ref="samlp:Extensions" minOccurs="0"/>
                //    </sequence>
                //    ...
                //</complexType>
                XmlNode refNode = doc.GetElementsByTagName("Issuer", "urn:oasis:names:tc:SAML:2.0:assertion").Item(0);
                element.InsertAfter(xmlDigitalSignature, refNode);`

It crashes on mac and only on mac in the `element.InsertAfter(xmlDigitalSignature, refNode);`
due to a "The node to be inserted is from a different context" error.

Are these kind of issues normal for running Core on mac?
Are they solvable? I've been testing around and by now I'm out of ideas to solve them.

thanks.

**Comment by Rick-Anderson** [comment]
If you can show a bug in the framework open an issue in the appropriate repo. It's not uncommon for code developed in one platform to fail in another. This is usually because of bugs in the code do not cause a failure on the original platform.
