### ISSUE TITLE
Authenticator apps instructions are incomplete

### ISSUE THREAD

**Issue by benaadams** [aspnet/Docs#3969]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes

There is no `AuthenticatorUri` in `TwoFactorAuthenticationModel` as per [the RazorPagesWeb template](https://github.com/dotnet/templating/blob/360e1497e601221b42aa8bb8de17d19dea4a8488/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/Pages/Account/Manage/TwoFactorAuthentication.cshtml.cs)

```csharp
new QRCode(document.getElementById("qrCode"),
{
    text: "@Html.Raw(Model.AuthenticatorUri)",
    width: 150,
    height: 150
});
```
So following the instructions results in a compile error.

Also may want to specify the instructions are just for RazorPages as MVC users might get confused; however its [`TwoFactorAuthenticationViewModel` doesn't have `AuthenticatorUri` either](https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Models/ManageViewModels/TwoFactorAuthenticationViewModel.cs)

**Comment by Rick-Anderson** [comment]
@blowdart can address these problems?

**Comment by blowdart** [comment]
There should have been - @danroth27?

**Comment by blowdart** [comment]
Yup, fixed it last night in my yolo push to master, because aussie internet sucks and I can't sync the repo. 

@benaadams can you confirm the updated instructions work for you?

**Comment by benaadams** [comment]
Yes; and... I might have a sheepish admission...

**Comment by zinczinc** [comment]
Can someone point me to the working example or code snippets where the missing AuthenticatorUri has been fixed?
