### ISSUE TITLE
Clarify what the location of webroot means

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#397]
Originally submitted by @visualstuart in https://github.com/aspnet/Docs/pull/395

In the conceptual overview:

> The Web root of your application is the root location in your project from which HTTP requests are handled 

This section would be improved with some further clarification. What is the meaning of "the root location", especially the term 'location'? Is this referring to a concept in the Solution Explorer in Visual Studio, a folder in the file system during development or when hosted? If this is the 'root' node, what would the children be? What would it mean or achieve to change the "webroot" property in the project.json file? What else would I have to do if I made that change?

**Comment by danroth27** [comment]
Make sure the language is consistent in the static file middleware topic.

**Comment by Rick-Anderson** [comment]
@TomArcher can you fix this?

**Comment by Rick-Anderson** [comment]
Per fowler on content root: Any non code files that need to be read from the project. Config files, data files (like a database file), etc. it's also the base path for the webroot folder

**Comment by GuardRex** [comment]
Current descriptions are found in [Fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/#web-root) and the *Web Root `string`* section of [Hosting](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting).

**Comment by guardrex** [comment]
@Rick-Anderson Is this still a prob? I can't find the OP topic mentioned (i.e., an "overview" with webroot language), and I can't find the string in the OP in any of the topics. The Fundamentals description seems quite respectable, and I'll double-check that the Hosting topic has good content on this in the morning (the PR for the Hosting topic updates is almost ready).

**Comment by Rick-Anderson** [comment]
fixed via:

* https://docs.microsoft.com/en-us/aspnet/core/fundamentals/index?tabs=aspnetcore2x#content-root
* https://docs.microsoft.com/en-us/aspnet/core/fundamentals/index?tabs=aspnetcore2x#web-root
