### ISSUE TITLE
TOCs mismatch/outdated for different languages

### ISSUE THREAD

**Issue by justdmitry** [aspnet/Docs#3990]
That's a general problem. Each one particular issue can be solved by updating (I guess) some .md files, but this issue is about problem "in common".

On screenshot below you can see same section of docs called *Migration*, but for different languages - `en-us` on the left and `ru-ru` on the right. Compare TOCs subtrees - they are different. Data in right ("localized") TOC is different (I guess outdated).

Doc page content itself is correctly shown in English and labeled with "This page is not translated yet, original version is shown", but nobody in ru-ru can navigate this page(s) because they are not linked to from TOC!

In common, no one non-English visitor of https://docs.microsoft.com guaranteed to read (and find, and even guess it exist!) actual and correct doc pages because he/she is automatically redirected to localized version, which contains old/wrong TOC!

If docs engine is unable to handle outdated TOC file(s) - may be it's better to completely disable TOC translation? Every developer is able to understand some basic english words, because we all writing programs with english keywords - nobody here tries to translate `try` / `catch` / `finally` to `Попытка` / `Исключение` / `КонецПопытки` ;)

![tocs-are-different](https://user-images.githubusercontent.com/3540597/29356888-65baf154-827e-11e7-852b-4d50baa14cb8.png)

**Comment by Rick-Anderson** [comment]
@nokura ?

**Comment by scottaddie** [comment]
The team is in the process of localizing the ASP.NET Core content. In about 2 weeks, the localized Table of Contents and the docs will be published. At that time, this issue will be resolved.

**Comment by justdmitry** [comment]
@scottaddie No, this issue is not about particular non-translated file. It's about problem "in common" that when TOC changes then all non-English TOC becomes outdated and does not display new links. New docs exist and can be shown (even without translation) to non-English readers, but this readers can't reach this pages because TOC does have no links to them!

TOC logic should be changed to make all TOC in all languages always show up-to-date links/structure, even not translated yet.

Say, when translating some GUI app - not-yet-translated controls/labels are not hidden, they are shown with non-translated content instead.

**Comment by Rick-Anderson** [comment]
@justdmitry  I think this has been resolved - if localized content is more than 2 weeks out of date let me know.
