### ISSUE TITLE
Obsolete description in documentation for linux production environments

### ISSUE THREAD

**Issue by markusschaber** [aspnet/Docs#3991]
https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction claims we should call app.UseIdentity() in App.Config() - However, this is obsolete in ASP.NET Core 2.0 and gives a compiler warning: aspnet/Security#1310

I cannot write the PR myself, als I'm still an absolute noob in ASP.NET Core (but trying to improve...)

**Comment by scottaddie** [comment]
This will be addressed with PR #4059
