### ISSUE TITLE
DateTime.Now does not belong in ASP.NET

### ISSUE THREAD

**Issue by mj1856** [aspnet/Docs#3992]
## The Problem

According to [this search](https://github.com/aspnet/Docs/search?q=DateTime.Now), there are currently 
 228 instances of `DateTime.Now` in the ASP.NET documentation samples.  This is a problem because it reinforces an anti-pattern.

`DateTime.Now` reflects the local time of the computer where it is executed.  In a web application, that will use the *server's* time zone when deployed, and will use the *developer's* time zone during development.  This disparity can result in bugs that pass unit tests and aren't found until an application is in production.

Sometimes this is counteracted by trying to change the server's time zone, which is also a bad practice.  Server time zones should generally be set to UTC, and applications should generally not depend on the server's time zone setting.

Consider also that local time zones may have transitions, such as those caused periodically by daylight saving time, or by the occasional governmental change of standard time in a region.  This means that local time is non-linear, and potentially ambiguous.  Depending on timing and the specific implementation, using a local time may create a runtime error.

In summary, `DateTime.Now` should never be used in an ASP.NET application.  It should be reserved for UIs in client-side code, such as desktop and mobile applications.  And even then, it should be used with caution.

Additional reading from some old blog posts of mine and StackOverflow:
- http://codeofmatt.com/2013/04/25/the-case-against-datetime-now/
- http://codeofmatt.com/2015/03/06/common-daylight-saving-time-mistakes-for-net-developers/
- https://stackoverflow.com/questions/2532729/daylight-saving-time-and-time-zone-best-practices

## Proposal

Most examples using `DateTime.Now` should use `DateTime.UtcNow` instead.  However, a mass search/replace is a bad idea.  Some examples may not be as straightforward.  It will require a manual review.

I can submit the required changes to existing documentation and samples, but I want to ask here first which is preferred:

- A single large PR with all the changes
- A large number of separate PRs, one for each subject area
- An even larger number of separate PRs, one for each sample snippet
- Something else?

Thanks.

**Comment by scottaddie** [comment]
@mj1856 This is a great suggestion! Thank you for volunteering to submit the required changes. We prefer a large number of separate PRs, one for each subject area.

**Comment by mj1856** [comment]
@rosieks `DateTime` is essential, especially when binding to UI that is just a date and a time.  That article outlines many key use cases for `DateTime`.   I think you are referring to the note that says:

> These uses for `DateTimeOffset` values are much more common than those for `DateTime` values. As a result, `DateTimeOffset` should be considered the default date and time type for application development.

It doesn't say to stop using `DateTime`, it just is speaking to what should be "considered the default". 
 Personally, I think the idea of a "default" type is not useful here.  At least, it's no more useful than asking whether `int` or `double` should be the default choice for numbers.  An evaluation of fitness for the purpose at hand must be made.  There is no good "default".

**Comment by Rick-Anderson** [comment]
@mj1856  When you're ready to work on this create a new issue listing what you will update.

**Comment by mj1856** [comment]
Thanks.  I have been tied up on other things, but will get to this at some point and reference here.  Thanks.

**Comment by Rick-Anderson** [comment]
@mj1856  you can ping me on this issue and I'll reopen it.
