### ISSUE TITLE
Update for new hosting bundle installer link

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#3997]
The downloads page link for the hosting bundle installer is ...

https://download.microsoft.com/download/B/1/D/B1D7D5BF-3920-47AA-94BD-7A6E48822F18/DotNetCore.2.0.0-WindowsHosting.exe

... but we've been using an fwlink in the topics.

@shirhatti Is it out? If not, let me know later, and I'll quickly pop it into the IIS and ANCM topics.

**Comment by guardrex** [comment]
Ping @leecow ... sry forgot u helped with this last time.

**Comment by leecow** [comment]
@guardrex - you can use https://aka.ms/dotnetcore.2.0.0-windowshosting

**Comment by guardrex** [comment]
I guessed ... I went ahead and put the word "bundle" in the link.

**Comment by guardrex** [comment]
@leecow Side Question: Just ran into something unexpected with the `OPT_INSTALL_LTS_REDIST=0 OPT_INSTALL_FTS_REDIST=0` switches. I just ran the installer with them. According to the status messages in the installer window, both the runtime and the runtime store were installed. We state in the topics that if the admin only intends to install the ANCM that these switches will configure the install to  *only* include the module and its config file ... nothing else.

**Comment by shirhatti** [comment]
@joeloff

**Comment by joeloff** [comment]
LTS and FTS only apply to 1.x bundles, We treat 2.0 as LTS for now. So if you do OPT_INSTALL_LTS=0, you should only get the package store and ANCM. We can look at adding a switch to disable the package store as well for 2.0.1 if you'd like

**Comment by leecow** [comment]
@joeloff I don't think you're making a policy statement but want to be clear, 2.0 has not been declared LTS yet and should be considered 'current' from a lifecycle perspective.

**Comment by guardrex** [comment]
> So if you do OPT_INSTALL_LTS=0, you should only get the package store and ANCM.

According to the installer messages, it's adding the runtime. Maybe it isn't, but that's what the status messages say. I'd need to dig into the log to confirm.

The use case for this is pure SCD hosting scenarios, where the admin only wants the ANCM and config file. This isn't currently possible. @Rick-Anderson @tdykstra I'd like to pull that note from the topic. How do u want it handled?

**Comment by joeloff** [comment]
@guardrex yes, you are correct. That flag appears to be disabled when support for the OPT_NO_X86 was added and because the package store is always installed.

**Comment by joeloff** [comment]
I think we should fix this properly in 2.0.1. Given that the bundle is intended to install as much as possible by default and that we don't necessarily carry LTS/FTS bits.

I'd propose that we do the following:
1. No flags installs everything it can install
2. OPT_INSTALL_RUNTIME=0 disables all the runtimes, so if there are LTS/FTS both are disabled
2.1 OPT_INSTALL_LTS and OPT_INSTALL_FTS can be specified, but will only apply if the bundle carries an LTS and FTS runtime.
3. OPT_INSTALL_PACKAGE_STORE=0 disables all the package stores
4. OPT_INSTALL_X86=0 disables installing x86 packages on x64 OS

**Comment by guardrex** [comment]
It might be unusual to either ...
* Install the runtime but not the runtime store
* Install the runtime store but not the runtime

However, the SCD 😍 folks can combine the flags and ultimately end up with only ANCM module and config file, so that sounds very nice.

In the meantime tho, I should pull the note. It's not a current feature of the installer. If you open an issue for tracking those installer flag updates :point_up: is create a doc issue attached to your tracking issue so we can come back at 2.0.1 or 2.1 and put an updated note back in the topics.
