### ISSUE TITLE
getting-started for 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#3998]
the asp.net site getting started will be updated to show these steps, and the one in the aspnet/Docs repo needs to follow suit:

a.	dotnet new razor -o aspnetcoreapp
b.	dotnet run
c.	View in the browser
d.	Edit Index.cshtml to add <p>Hello, world! The time on the server is @DateTime.Now</p>

Notes: Remove the mkdir/cd and use the -0

**Comment by scottaddie** [comment]
Item 1 in the list on that page should probably say "Install .NET Core SDK" instead of "Install .NET Core".

**Comment by tdykstra** [comment]
[@]rowanmiller is taking care of this.

**Comment by Rick-Anderson** [comment]
@rachelappel  looks like we want a copy of https://www.asp.net/get-started for now
@scottaddie  is that your understanding?

**Comment by scottaddie** [comment]
@Rick-Anderson That is my understanding. Dan and Rowan are in talks about how we can avoid the duplication down the road.

**Comment by rachelappel** [comment]
https://github.com/aspnet/Docs/pull/4133
