### ISSUE TITLE
I am ready to translate

### ISSUE THREAD

**Issue by erlimar** [aspnet/Docs#4]
I am ready to translate to `pt_BR`.

Where are the rules for translation?
It would be nice to have it in the project wiki.

**Comment by Eilon** [comment]
@erlimar I'm not sure if the docs are quite ready for translation, but it's great to know you'd like to help! I think for now @danroth27 (who is managing a lot of the docs) is focusing on the initial en-US docs, but I'm sure translation will eventually happen too.

**Comment by Rick-Anderson** [comment]
combining with https://github.com/aspnet/Docs/issues/416
