### ISSUE TITLE
https://aka.ms/dotnet-install-templates has bad redirect + No "Install templates docs"

### ISSUE THREAD

**Issue by shanselman** [aspnet/Docs#4018]
With SDKs backward compatible (without global.json) it possible to create a .NET Core 1.1 application by using the new version, such as
`dotnet new console --framework netcoreapp1.1`
This returns with an error that this is not a valid value for –framework and a link to install additional templates:  https://aka.ms/dotnet-install-templates
It would be ideal if this link showed how to install a template for .NET Core 1.1 with the the .NET Core 2.0 SDK as well as the general "how to install templates" topic. 
However, this aka link redirects to Introduction to ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/

I see a few to-dos here:

- [ ] Create "how to install dotnet new CLI templates" topic
- [ ] How to install .NET 1.1 templates while using the .NET 2.0 CLI
- [ ] Update the https://aka.ms/dotnet-install-templates link

/cc @mlorbetske @RickAndMSFT

**Comment by shanselman** [comment]
From Mike, some starter text:

To install the 1.0 and 1.1 project templates, please run one or more of the following commands

For web templates:
dotnet new -i Microsoft.DotNet.Web.ProjectTemplates.1.x::1.0.0-*

For class library or console apps:
dotnet new -i Microsoft.DotNet.Common.ProjectTemplates.1.x::1.0.0-*

For unit test projects:
dotnet new -i Microsoft.DotNet.Test.ProjectTemplates.1.x::1.0.0-*

**Comment by danroth27** [comment]
@Rick-Anderson @tdykstra

**Comment by rachelappel** [comment]
Move to this repo: https://github.com/dotnet/docs/issues/3178
