### ISSUE TITLE
Missing launchsettings.json migration

### ISSUE THREAD

**Issue by damienbod** [aspnet/Docs#4021]
I have to change the launchSettings.json with each update, otherwise the app will not run from the console. This should be added to the docs:

https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/1x-to-2x/index.md

Greetings Damien

**Comment by scottaddie** [comment]
@damienbod Thank you for reporting this. Can you please specifics on what you had to change in that file?

**Comment by damienbod** [comment]
Hi @scottaddie 

old not working from console (Was working in 1.1)

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:6510/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "api/test",
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      }
    },
    "web": {
      "commandName": "web",
      "environmentVariables": {
        "Hosting:Environment": "Development"
      }
    }
  }
}
```

new working

```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:44123/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "WebApplicationNoAuth": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:44124/"
    }
  }
}

```

Greetings Damien

**Comment by scottaddie** [comment]
@damienbod I've confirmed with the product team that `"commandName": "web"` was a holdover from the commands which could be specified in `project.json` for DNX-based projects. No related properties appear to have been changed with the 2.0 release.

**Comment by tebeco** [comment]
@scottaddie hello
do you know where is the code to generate that launchSettings file if it does not exists ?
i’d like to edit it for custom tools but it is not create using `dotnet new` and creating default file just like studio does seems like a good idea right ?

**Comment by scottaddie** [comment]
@tebeco *launchSettings.json* is a Visual Studio artifact, so I wouldn't expect it to be generated by the .NET Core CLI. See here for the file in the 2.0 project template within the aspnet/templating repo: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Properties/launchSettings.json

**Comment by tebeco** [comment]
i agree, 
CLI should not generate vs related file ;)

In order to setup `ElectronNet` the `init` step add a file to the csproj and it also might be a good idea to enhance the debug configuration so that pressing F5 in Vs2017 would also you either just to run the Aspnet application in `iis express`, `console` or `électron` itself

i do not intend to ask for any modification, i just wanted to see if it was possible to reuse that piece of code as an `OPT-IN` so if the file does not exists it would be properly generated / added

**Comment by tebeco** [comment]
@scottaddie, any idea how `ports` are randomized ? min and max including or excluding bounds ?

**Comment by scottaddie** [comment]
@tebeco Let's ask @mlorbetske & @sayedihashimi. Mike and/or Sayed, any ideas on the port questions above?

**Comment by mlorbetske** [comment]
The code for doing the port generation at the CLI can be found here https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Macros/GeneratePortNumberMacro.cs, web projects can optionally include a launchSettings.json when created via dotnet new by supplying the --use-launch-settings switch

**Comment by tebeco** [comment]
thx a lot
