### ISSUE TITLE
Translate documentation to spanish

### ISSUE THREAD

**Issue by genitalico** [aspnet/Docs#4031]
Hi guys,

I have a question, how to can or (we), translate the documentation to spanish, I only do create a fork and I order merge ?

my friends and me can do this.

Thanks!

**Comment by Rick-Anderson** [comment]
Creo que está programado para ser traducido pronto. Estoy revisando y le informaré. Gracias por su interés.

**Comment by Rick-Anderson** [comment]
Thank you for your interest in providing the translation into Spanish. We are planning to publish machine-translated content around mid-September. At that point, you will be able to submit PRs to improve the quality. We will inform you as soon as the machine-translated pages are published

**Comment by genitalico** [comment]
@Rick-Anderson gracias, estare al pendiente entonces, para ver si podemos colaborar con esto ..

saludos
