### ISSUE TITLE
Document the new ITagHelperComponent in ASP.NET Core 2.0

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#4033]
Work with Jass Bagga to get this new 2.0 scenario documented. See https://github.com/aspnet/Mvc/issues/6282 for more info.

I propose the following outline for a new reference doc called **Creating Custom Tag Helper Components**:
- Overview
- Use Cases
- Adding via Dependency Injection
- Adding via Controllers
- Adding via Views

This new doc will be found within the **MVC** --> **Views** --> **Tag helpers** TOC node, and a sample app similar to https://github.com/jbagga/VSLiveDemo/tree/master/src/TagHelperComponentSample will accompany it.

**Comment by scottaddie** [comment]
@danroth27 @jbagga @NTaylorMullen Looking for your feedback on the doc title and outline provided above.

**Comment by jbagga** [comment]
Title recommendation: Modifying <head> or <body> HTML tags with TagHelperComponents (or something similar)
If there is a subsection, explaining how to modify/target other HTML tags by writing your own TagHelperComponentTagHelper implementation, then that can be titled:
Modifying other HTML tags

cc @NTaylorMullen

**Comment by NTaylorMullen** [comment]
I'd probably have a specific section labeled: `Including JavaScript and CSS in your views using TagHelperComponents.`

This will be the typical use-case from users. Having other pieces that go into detail on the components would also be required.

**Comment by mguinness** [comment]
@NTaylorMullen Are TagHelper components usable from within partial views as well?  If so, that would be a good example to include.  As sections don't work in partial views, this would be a useful alternative that is [often requested](https://stackoverflow.com/a/7556594/310601).

**Comment by NTaylorMullen** [comment]
> @NTaylorMullen Are TagHelper components usable from within partial views as well?

They are 😄 

> As sections don't work in partial views, this would be a useful alternative

It wouldn't be super straight forward to use TagHelperComponent's in partials (since they apply to every view) but it's definitely doable. I'm not sure if it's worth noting in the doc due to its complexity.

**Comment by mguinness** [comment]
Thanks!  I'm sure they'll be used in partial views for things like widgets even if it's a bit of work, but since it's an edge case it makes sense to omit from doc.

**Comment by Rick-Anderson** [comment]
@NTaylorMullen if you can write a sample app for this I'll get the doc scheduled in the next sprint.

**Comment by jbagga** [comment]
Here is the cleaned up sample https://github.com/jbagga/TagHelperComponentSample

Let me know if I can clarify anything or look at the doc.

**Comment by guardrex** [comment]
Cross-ref `@DamianEdwards` presenting: https://youtu.be/Blo--Qio84w?t=56m51s
