### ISSUE TITLE
Intro to Identity Needs Updated to 2.0

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Docs#4043]
This [article](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?tabs=visual-studio) still uses the 1.x API's for configuring Cookies.  These API's are missing in 2.x.

Specifically this:
```csharp
services.Configure<IdentityOptions>(options =>
{
    // Cookie settings
    options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromDays(150);
    options.Cookies.ApplicationCookie.LoginPath = "/Account/LogIn";
    options.Cookies.ApplicationCookie.LogoutPath = "/Account/LogOut";
});
```

Should be this:
``` csharp
services.ConfigureApplicationCookie(
{
    // Cookie settings
    options.Cookie.Expiration= TimeSpan.FromDays(150);
    options.LoginPath = "/Account/Login";
    options.LogoutPath = "/Account/Logout";
});
```

Happy to send a PR (for real this time!), but didn't know if this was already a WIP somewhere that I didn't see already, and if you wanted to have tabs for 1.x vs 2.x behavior like other places on the docs.

Thanks!

**Comment by Rick-Anderson** [comment]
@scottsauber  a PR would be much appreciated. cc @scottaddie

**Comment by scottaddie** [comment]
@scottsauber Are you still interested in submitting a PR for this?

**Comment by scottsauber** [comment]
Yep! Will start tonight. Sorry! I skimmed the issue and saw it was assigned to you and completely missed Rick's comment. 

First go at contributing to MS docs besides a typo in SQL's docs so I may noob it up. :)

**Comment by scottaddie** [comment]
@scottsauber Not a problem. We're here to help if you have any questions. Thanks again for your help!

**Comment by scottsauber** [comment]
@scottaddie I'm having some trouble testing out the Tabs for the diff versions of Core like you see on other pages with like 1.x vs 2.x. 

1. I can't preview the tabs when I build locally, they just look like links.  Is this a style thing that only happens when you pick up the css of docs.asp.net?
2. When I indent code snippets within a tab, I break the code snippets.  The first one will render, but the other ones will not.  Again, not sure if this is just a local problem or not.  Also not sure if I need to indent the code snippets within a tab, but I can't preview it.
3. Somehow with the #'s get reset locally when I use the tabs.  Like the "3. Create a User" gets replaced with "1. Create a User."  Not sure if this is a bug or if I'm doing something wrong.

My commit with my changes is in my fork here if you want to take a look or repro: https://github.com/scottsauber/Docs/commit/c8381d50aab58dd12a7c71f1073fe68b1baf3df9

Hope some of these are just user error.  Once we figure out some of this stuff, I think I can contribute to a few of the other Identity ones that need a 1.x vs 2.x like https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration

Thanks!

**Comment by scottaddie** [comment]
@scottsauber 

> 1. I can't preview the tabs when I build locally, they just look like links and only render the first tab's contents. Is this a style thing that only happens when you pick up the css of docs.asp.net?

That's the expected behavior &mdash; the latest version of DocFx doesn't support previewing of tabs. We'll soon have a versioning strategy in place to differentiate between 1.x and 2.x content. At that point, this use case for tabs is likely to disappear.

> 2. Somehow the #'s get reset when I preview locally when I use the tabs. Like the "3. Create a User" gets replaced with "1. Create a User." Not sure if this is a bug or if I'm doing something wrong. It shows as "3. Create a User" in the markdown.

Try using the following:

```
1.  Create an ASP.NET Core Web Application project with Individual User Accounts.

    # [Visual Studio](#tab/visual-studio)
    In Visual Studio, select **File** -> **New** -> **Project**. Select the **ASP.NET Web Application** from the **New Project** dialog box. Selecting an ASP.NET Core **Web Application** with **Individual User Accounts** as the authentication method.

    Note: You must select **Individual User Accounts**.
 
    ![New Project dialog](identity/_static/01-mvc.png)
    
    # [.NET Core CLI](#tab/netcore-cli)
    If using the .NET Core CLI, create the new project using ``dotnet new mvc --auth Individual``. This will create a new project with the same Identity template code Visual Studio creates.
 
    The created project contains the `Microsoft.AspNetCore.Identity.EntityFrameworkCore` package, which will persist the Identity data and schema to SQL Server using [Entity Framework Core](https://docs.efproject.net).
    
    ---
 
2.  Configure Identity services and add middleware in `Startup`.

    The Identity services are added to the application in the `ConfigureServices` method in the `Startup` class:

    # [ASP.NET Core 2.x](#tab/aspnetcore2x)
    
    [!code-csharp[Main](identity/sample/src/ASPNETv2-IdentityDemo/Startup.cs?name=configureservices&highlight=7-9,11-28,30-39)]
    
    These services are made available to the application through [dependency injection](xref:fundamentals/dependency-injection).
    
    Identity is enabled for the application by calling  `UseAuthentication` in the `Configure` method. `UseAuthentication` adds cookie-based authentication [middleware](xref:fundamentals/middleware) to the request pipeline.
    
    [!code-csharp[Main](identity/sample/src/ASPNETv2-IdentityDemo/Startup.cs?name=configure&highlight=17)]
    
    # [ASP.NET Core 1.x](#tab/aspnetcore1x)
    
    [!code-csharp[Main](identity/sample/src/ASPNET-IdentityDemo/Startup.cs?name=configureservices&highlight=7-9,13-34)]
    
    These services are made available to the application through [dependency injection](xref:fundamentals/dependency-injection).
    
    Identity is enabled for the application by calling  `UseIdentity` in the `Configure` method. `UseIdentity` adds cookie-based authentication [middleware](xref:fundamentals/middleware) to the request pipeline.
        
    [!code-csharp[Main](identity/sample/src/ASPNET-IdentityDemo/Startup.cs?name=configure&highlight=21)]
    
    ---
     
    For more information about the application start up process, see [Application Startup](xref:fundamentals/startup).

3.  Create a user.
```
