### ISSUE TITLE
Defaults ASP.NET Core 2.0 API Template, return a response COOKIE 

### ISSUE THREAD

**Issue by taigosantos** [aspnet/Docs#4051]
Defaults ASP.NET Core 2.0 API Template, return a response COOKIE in all API responses. 
How can i remove this reponse COOKIE?

**Comment by Rick-Anderson** [comment]
@HaoK

**Comment by HaoK** [comment]
@taigosantos can you clarify exactly what you are doing and what you expect?  It sounds like you've created an app using a 2.0 Web API template and you are getting an unexpected cookie response?

**Comment by HaoK** [comment]
Closing due to lack of response, feel free to file a new issue if this is still a problem
