### ISSUE TITLE
RP: Explain post delete method

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4054]
Per customer question
`OnPostDeleteAsync` method in the code below is confusing. What is it for?

**Comment by guardrex** [comment]
I can knock this out quickly, but I don't see it (shown in code samples) in the RP tutorial. Which topic? ... if you want me to take care of it.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/razor-pages/index/sample/RazorPagesContacts/Pages/Index.cshtml.cs

**Comment by guardrex** [comment]
Ah ... I see what you mean ... It isn't shown in the topic and that *is* the problem (along with missing a textual explanation of it). I thought at first that the code was shown but that it wasn't explained. Let me see if I can fix this.
