### ISSUE TITLE
Rename all mention of bundleExclude to publishExclude in project.json

### ISSUE THREAD

**Issue by dimaaan** [aspnet/Docs#407]
There are several places in samples and screenshorts mention 'bundleExclude':
https://github.com/aspnet/Docs/search?utf8=%E2%9C%93&q=bundleExclude
See 
https://github.com/aspnet/Home/issues/610
https://github.com/aspnet/dnx/issues/1474
for details.

**Comment by Rick-Anderson** [comment]
@dimaaan thanks for reporting.
@Erikre  can you fix these and then close this issue?

**Comment by row5is** [comment]
I'll work on this now.

**Comment by row5is** [comment]
submitted pr #613
