### ISSUE TITLE
Try to establish CICD with VSTS and the ContosoUni APP

### ISSUE THREAD

**Issue by mountainbrother** [aspnet/Docs#4074]
I was able to build the App and could publish it via Webdeploy to an Webapp with SQL to Azure.
Now i try to create an Pipline with VSTS. 
I ran always in an release error on SQL.
Do we have a step by step docu how to setup a pipeline for this App.
thanks for help

**Comment by Rick-Anderson** [comment]
Try [this](https://www.google.com/search?q=Pipline+with+VSTS+cicd&oq=Pipline+with+VSTS+cicd+&aqs=chrome..69i57.14040j0j7&sourceid=chrome&ie=UTF-8)
