### ISSUE TITLE
Suggestion: use include statements in the Core MVC tutorials

### ISSUE THREAD

**Issue by badersur** [aspnet/Docs#4078]
The tutorials share a lot of text and fixing issues in all places is time consuming and most likely won't happen (because contributors don't know, don't notice or forget!)

I've submitted [some fixes for Windows tutorial](https://github.com/aspnet/Docs/commits/master?author=badersur) and now I'm seeing the same issues on the macOS and xplat tutorials! and I'm lazy (and don't have time) to resubmit them again :(

I suggest using `include` statements for shared text, or better combine these 3 tutorials into 1 because it's just showing how to build the same app using different tools!

**Comment by Rick-Anderson** [comment]
Most of the Razor and MVC intro's use includes. I'm working on that.

**Comment by badersur** [comment]
Great news :)
