### ISSUE TITLE
Create Snapshot Debugging with ASP.NET Core doc

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#4079]
See https://azure.microsoft.com/en-us/blog/snapshot-debugger-for-azure/ for more detail on the topic. Ideally, this doc would be listed in the TOC under **Testing and debugging**.

**Comment by isaac2004** [comment]
@scottaddie is the scope of this a sample project and step by step instructions on setting up? Looks like there is some Core 2.0 content here 

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-snapshot-debugger

**Comment by danroth27** [comment]
Can we just reference the existing azure doc from our TOC?

**Comment by scottaddie** [comment]
@danroth27 We certainly can. Do you have a link to the doc?

**Comment by isaac2004** [comment]
@scottaddie the link I provided has a pretty straight forward setup for setting this up (I have followed it on apps I have built with no issue)

https://docs.microsoft.com/en-us/azure/application-insights/app-insights-snapshot-debugger

**Comment by scottaddie** [comment]
@isaac2004 I appreciate the link! Thanks for all your help with our docs.
