### ISSUE TITLE
New: Azure App Service Authentication (Easy Auth) 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4095]
[Customer request](https://docs.microsoft.com/en-us/aspnet/core/?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification#lf-content=177014839:728805420)
It would be good to see an example and documentation using Azure App Service Authentication (Easy Auth) with .NET Core 2.x. Including how to get user information once authenticated.

I tried with earlier versions but ended up having to switch to normal .NET. I couldn't figure out the authentication to .auth/me server side to get user information. Could be useful to add Redis Cache in their too.

cc @danroth27  @HaoK @Tratcher  to comment/set priority

**Comment by isaac2004** [comment]
@Rick-Anderson would it make sense to put this new doc here or in Azure docs? The Easy Auth process is done totally in Azure (minus local dev obviously) so maybe it makes sense to writeup the doc in Azure docs, and link to it in Intro or Auth Index... Thoughts?

**Comment by danroth27** [comment]
That would be my preference.

**Comment by Rick-Anderson** [comment]
Yes, do it in Azure docs.

**Comment by isaac2004** [comment]
@danroth27 @Rick-Anderson It looks like there are docs for this, in a hard to find place

https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-overview#documentation-and-additional-resources

Should we link these in aspnetcore docs?

**Comment by isaac2004** [comment]
@Rick-Anderson @danroth27 thoughts?

**Comment by danroth27** [comment]
We should check that these steps actually work for ASP.NET Core apps

**Comment by danroth27** [comment]
But assuming they do, then linking to the [Azure App Service Authentication Overview](https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-overview) article sounds fine to me

**Comment by isaac2004** [comment]
@danroth27 I just tested a new template using dotnet new deployed to Azure and tested all providers. All worked following the steps.

https://test-easy-auth.azurewebsites.net

I think it is safe to link those Azure Docs, but it isn't my decision :)

**Comment by Rick-Anderson** [comment]
I'll get them linked early next week.

**Comment by isaac2004** [comment]
@Rick-Anderson I can put the links in there. How about here

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/

**Comment by Rick-Anderson** [comment]
Great

**Comment by isaac2004** [comment]
done!

**Comment by scottaddie** [comment]
Fixed with https://github.com/aspnet/Docs/pull/4501
