### ISSUE TITLE
Tutorials use hard coded strings instead of using `nameof`

### ISSUE THREAD

**Issue by badersur** [aspnet/Docs#4098]
I believe the recommended approach is to use `nameof`, and `dotnet new` uses it but the tutorials ask us to replace it with hard coded strings!

Example: https://github.com/aspnet/Docs/blob/f6333f838ab33e011c745a5bb75118cc0a003410/aspnetcore/data/ef-mvc/intro/samples/cu/Controllers/StudentsController.cs#L251

**Comment by scottaddie** [comment]
In this particular example, `nameof` is preferred. Feel free to submit a PR to fix this.

**Comment by badersur** [comment]
Almost all the controllers have this issue that's why I opened an issue (otherwise I'd be submitting the fix as usual :D)

I may submit a PR spanning these controllers in few hours or tomorrow! I hope fixing other files will be preferred as well..

**Comment by scottaddie** [comment]
As a general rule of thumb, `nameof` is preferred over magic strings referencing a member of the class.

**Comment by Rick-Anderson** [comment]
@badersur  don't change any of the template generated code such as
Example: https://github.com/aspnet/Docs/blob/f6333f838ab33e011c745a5bb75118cc0a003410/aspnetcore/data/ef-mvc/intro/samples/cu/Controllers/StudentsController.cs#L251

**Comment by badersur** [comment]
Thanks for the rule :)
Now I'm thinking that these magic strings could be discussed in the tutorials and I can't know where it's used and whether it's safe to change them! I think it is safer to just change it where I find it (https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud)

**Comment by badersur** [comment]
@Rick-Anderson I should not change any thing?!

In VS2017, my auto-generated code uses `nameof` and the one you referenced uses the magic strings so I'm not sure about the issue

**Comment by Rick-Anderson** [comment]
If the scaffolder is using nameof, we should change the code to match the scaffolder.

**Comment by badersur** [comment]
Now I get it :)

**Comment by Rick-Anderson** [comment]
If the scaffolder is not using nameof, we should open a bug in https://github.com/aspnet/scaffolding

**Comment by badersur** [comment]
I found that `dotnet new`, VS scaffolder and aspnet-codegenerator are using nameof (not sure if vs uses aspnet-codegenerator behind the hoods!)

**Comment by Rick-Anderson** [comment]
Yes, it uses the same scaffolder.

**Comment by badersur** [comment]
Nice! Thanks for letting me know about this. I've been thinking about it for a while :)

Should I use `fixed #4098` in the PR message to close this issue or keep it open because I see you adding it to Backlog milestone?

**Comment by Rick-Anderson** [comment]
fixed.
