### ISSUE TITLE
Replace HttpSys with HTTP.sys

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4099]
We should match how the IIS docs refers to HTTP.sys: https://docs.microsoft.com/en-us/iis/get-started/introduction-to-iis/introduction-to-iis-architecture

**Comment by scottaddie** [comment]
@glennc Should this text be updated in your recent blog post too? https://blogs.msdn.microsoft.com/webdev/2017/08/25/asp-net-core-2-0-features-1/
