### ISSUE TITLE
Is it fine to say "Run the page"?!

### ISSUE THREAD

**Issue by badersur** [aspnet/Docs#4106]
I'm seeing this 3 times in https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page and it doesn't seem alright to me! Maybe it should be "Run the app" or "Refresh the page"...

I'm wondering how I was able to include an absolute code URL in my last issue! I can't do it again to include an example here :/

**Comment by scottaddie** [comment]
@Rick-Anderson Any preferences on the verbiage? I was thinking something like "Browse to the page".

**Comment by badersur** [comment]
I've found another occurrence in https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model:
> Run the Students Index page again and notice that times are no longer displayed for the enrollment dates.

**Comment by Rick-Anderson** [comment]
Refresh the Students Index page ~again~ and notice that times are no longer displayed for the enrollment dates.

**Comment by badersur** [comment]
I'm not sure about fixing this issue because there're several variations:

In [crud](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/crud.md) there're:
> Run the application, select the Students tab, and click the Details link for a student. (looks fine to me but included to show variations!)

> Run the application and select the Students tab, then click an Edit hyperlink. (seems fine!)

> Run the page by selecting the Students tab and clicking Create New. (change "page" to "application", and use the previous structure (i.e. run ... and select ..., then ..)?)

> Run the page by selecting the Students tab and clicking a Delete hyperlink: (same as above)

In [sort-filter-page](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md):
> Run the page and click the Last Name and Enrollment Date column headings to verify that sorting works. (Refresh the page?)

> Run the page, enter a search string, and click Search to verify that filtering is working. (Refresh the page?)

> Run the page. (Change to "Refresh the page"?)

> Run the app and click the About link. The count of students for each enrollment date is displayed in a table. (looks fine to me!)

In [complex-data-model](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
> Run the Students Index page again and notice that times are no longer displayed for the enrollment dates. The same will be true for any view that uses the Student model. (refresh ... <del>again</del>)

> Run the Create page, and enter either name longer than 50 characters. When you click Create, client side validation shows an error message. (refresh)

Should I use a mixture of run and refresh? Are suggested edits in () fine?

**Comment by scottaddie** [comment]
@tdykstra Do you have any preferences on the verbiage used here?

**Comment by tdykstra** [comment]
In general the suggested edits are OK.  Could simplify in some cases by using "Go to the x page"; "Refresh the page" only works if it's a subsequent time and it's safe to assume they left the browser window open.

**Comment by badersur** [comment]
Any one planning to submit a PR for this? or working on it? I may be able to fix it tonight or tomorrow!

**Comment by badersur** [comment]
Unfortunately I didn't have time for this!

**Comment by scottaddie** [comment]
@badersur Nobody is working on this. If you have time to submit a PR, it would be greatly appreciated.

**Comment by badersur** [comment]
Maybe I'll be able to work on it next week!

**Comment by badersur** [comment]
I'm trying to update these files to use refresh and go to x page but now I realize that we need to re-run the application after changing C# code (as far as I know since we didn't use `dotnet watch`! Does VS re-run ASP.NET Core apps on the background?! I didn't notice this..)
Or we can assume developers will re-run the app if refresh didn't work!

**Comment by badersur** [comment]
It seems I'll just use "run the application" everywhere...

**Comment by tdykstra** [comment]
Or change text like "run page x" to:

"run the app and navigate to page x" 

or shorter

"run the app and go to page x"
