### ISSUE TITLE
Is using a singleton in the Web API tutorial thread-safe?

### ISSUE THREAD

**Issue by geertendoornenbal** [aspnet/Docs#411]
On the Web API tutorial (http://docs.asp.net/projects/mvc/en/latest/getting-started/first-web-api.html) it shows the injection as a singleton. However, the use of the dictionary is not thread-safe.

Am I missing something? Or is this tutorial showing bad practice..Because with multiple requests coming in at the same time, this could give problems..

**Comment by MikeWasson** [comment]
Yeah - it should be a concurrent dictionary. Also I think it should be registered as "Scoped" not "Singleton" and then make the dictionary static, because normally the repository should be created per request. (The dictionary is a stub, it would really be a DB connection or something.)

Thanks!

**Comment by geertendoornenbal** [comment]
Yeah, a concurrent static dictionary is more similar to a database indeed :)

In my implementation following this tutorial I also registered it as "Scoped".
