### ISSUE TITLE
ASP.Net Core API Reference Search - lacks support for searching by Method or Property names

### ISSUE THREAD

**Issue by githubgitgit** [aspnet/Docs#4119]
Background: I'm new to .NET. Only been interested in .NET because of ASP .NET Core. It shows a lot of promise and seems to be great for simple and rapid web application development without a lot of baggage/heavyweight and seems straightforward!

Issue: 
On this page:  https://docs.microsoft.com/en-us/aspnet/core/api/
(Issue also applies to: https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-2.0)
and search for method names like:

AddMvc - no results
AddDbContext - no results (part of EntityFrameworkCore)
BuildWebHost - no results
CreateDefaultBuilder - no results
..etc

Suggestions:
1) The ASP.NET Core API Reference Search box should display (partial) matches from Method names and Properties also (e.g.: AddMvc method if you search for Mvc). This is a basic (essential) requirement.  
Preferably, The results should be grouped by "Methods / Property" matches and Assembly/Package name matches (eg: Microsoft.AspNetCore.Mvc). There could be checkboxes provided whether to display search both (Methods+Properties and Assembly/Package names)  or from either of those results.

2) Up for debate: Entity framework core is a first-class framework from Microsoft and should be treated as such, part of the ASP.NET Core API. So EntityFramework API's search results should be  displayed in the ASP.NET Core API Reference.

3) Tighter integration with IDE's. For example in Visual Studio for Mac, or Windows, you should be able to Select something and click "Go to API Reference" and it should atleast, open the appropriate browser page to the API Reference to the associated assembly/package.

**Comment by Rick-Anderson** [comment]
Dup of #3565
I'm guessing you're searching in the filter box in the left pane - that's great for filtering but is not a search. The search box is in the upper right. I made the same mistake.
2. EF should be searched in the EF docs.
3. We hope to have that someday.
