### ISSUE TITLE
[ubuntu] fixing the 'missing libcurl' error

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Docs#414]
A default installation of Ubuntu 14 does not have libcurl. `dnu restore` throws:

>    System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libcurl': The specified module could not be found.

The docs should specify that Linux users also need `libcurl4-gnutls-dev`

```
sudo apt-get install libcurl4-gnutls-dev
```

**Comment by danroth27** [comment]
Update instructions in PR here: https://github.com/aspnet/Docs/pull/410. Added note with prereqs for running on .NET Core.

**Comment by natemcmaster** [comment]
Closing as a dup.

**Comment by claysmith** [comment]
add it here: http://dotnet.github.io/core/getting-started/

**Comment by danroth27** [comment]
See http://docs.asp.net/en/latest/getting-started/installing-on-linux.html
