### ISSUE TITLE
retire "Building Real-World Cloud Apps with Azure" 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4151]
Retire [Building Real-World Cloud Apps with Azure](https://docs.microsoft.com/en-us/aspnet/aspnet/overview/developing-apps-with-windows-azure/building-real-world-cloud-apps-with-windows-azure/introduction)

The series is 6 years out of date. The scenario is owned by the Azure folks, not the ASP.NET team.

**Comment by Rick-Anderson** [comment]
@tdykstra 	I'm retiring this. What should I redirect to?

cc @MikeWasson

**Comment by tdykstra** [comment]
How about https://docs.microsoft.com/azure/architecture/guide/

**Comment by Rick-Anderson** [comment]
Perfect. Would you mind fixing this?
