### ISSUE TITLE
Update "Code First Migrations and Deployment with the Entity Framework in an ASP.NET MVC Application" to current Azure

### ISSUE THREAD

**Issue by terrimorton** [aspnet/Docs#4177]
https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/migrations-and-deployment-with-the-entity-framework-in-an-asp-net-mvc-application

This article refers to "Windows Azure" in screenshots and alt text. The Azure screenshots are old and no longer apply. There is at least one comment on this article where the user is confused.

**Comment by isaac2004** [comment]
@terrimorton do you think the whole doc could use an upgrade or just the Azure section? I can. Update the Azure section pretty quickly if that is all needed.

**Comment by scottaddie** [comment]
@isaac2004 If you're feeling ambitious, update the whole doc. If not, just the Azure stuff is good enough for now.

**Comment by isaac2004** [comment]
@scottaddie based on the tech, the doc looks pretty good, I will just update the Azure section to show the new process against App Service using the new portal
