### ISSUE TITLE
2.1 Update config for 2.x Azure KV config provider topic samples

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#4211]
Based on the [updates to config for 2.1 adding chained config](https://github.com/aspnet/Configuration/pull/719), we can move the 2.x Azure Key Vault config provider topic samples ([sample 1](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration/samples/basic-sample/2.x/Program.cs), [sample 2](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration/samples/key-name-prefix-sample/2.x/Program.cs)) to a nicer config setup ...

```csharp
WebHost.CreateDefaultBuilder(args)
    .ConfigureAppConfiguration((context, config) =>
    {
        var builtConfig = config.Build();

        var keyVaultConfigBuilder = new ConfigurationBuilder();

        keyVaultConfigBuilder.AddAzureKeyVault(
           $"https://{builtConfig["Vault"]}.vault.azure.net/",
           builtConfig["ClientId"],
           builtConfig["ClientSecret"];

        config.AddConfiguration(keyVaultConfigBuilder);
   })
   .Build()
```
@scottaddie Can you create a label for `2.1` for this? ... or mark it `blocked` right now?

**Comment by scottaddie** [comment]
@guardrex Label created and applied

**Comment by Rick-Anderson** [comment]
Make sure this is updated to the latest version without tabs from previous versions. If you need previous versions, point to https://github.com/aspnet/Docs/blob/master/aspnetcore/common/_static/9-25-17.pdf
