### ISSUE TITLE
Head-check on 2.0 auth migration guidance

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#4216]
@HaoK I noticed a small delta between the [1.x-2.x auth migration topic](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x#replace-getexternalauthenticationschemes), which shows this ...
```html
<button type="submit" class="btn btn-default" name="provider" 
    value="@provider.Name" title="Log in using your @provider.DisplayName 
    account">@provider.Name</button>
```
... and [one your PRs for SignalR](https://github.com/aspnet/SignalR/blob/27e90edc1c72de90e87c3bee614e3a97e336a7c2/samples/ChatSample/Views/Manage/ManageLogins.cshtml#L49), which shows this ...

```html
<button type="submit" class="btn btn-default" name="provider" 
    value="@provider.Name" title="Log in using your @provider.Name 
    account">@provider.Name</button>
```
You have `@provider.Name` in the `title`, while the topic has `@provider.DisplayName`. Which is correct?

**Comment by HaoK** [comment]
DisplayName was added later, and meant to be used for display purposes

**Comment by guardrex** [comment]
@HaoK Thx.

@scottaddie IIRC, there are other spots in topic samples where this will need to be addressed. Fortunately, the old code won't compile without fixing this line. :smile: Therefore, you could close this. I'll leave it up to you.

**Comment by guardrex** [comment]
btw - I'm going to go with ...

```html
<button type="submit" class="btn btn-default" name="provider" value="@provider.Name" 
    title="Log in using your @provider.DisplayName account">@provider.DisplayName</button>
```
