### ISSUE TITLE
New topic: AI new project with VS and Azure

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#4229]
Create new topic that is similar to [Publish an ASP.NET Core web app to Azure App Service using Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs)

This was first requested in [Issue 3373](https://github.com/aspnet/Docs/issues/3373) "AI info and links. Explain how AI is hooked and show how to use it."

@wadepickett @scottaddie @rachelappel all agreed this should be a new topic, as it doesn't make sense to inundate the user with AI information in a level 100 basic how to on using Visual Studio. It's outside the scope of that doc.

**Comment by guardrex** [comment]
There's a related issue from back in February. There's an outline there that may or may not help; but either way, there seems to be some overlap here or there: https://github.com/aspnet/Docs/issues/2800.

Also possibly related: https://github.com/dotnet/docs/issues/2716

**Comment by rachelappel** [comment]
Looks like the Azure side has a doc covering App Insights https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net

@guardrex  I'm not sure where AI is specifically mentioned in issue 2800. Looks like just Azure App Services - not App Insights.

**Comment by guardrex** [comment]
Azure Integration lol ... sorry. My acronym-fu failed me.

**Comment by rachelappel** [comment]
Well "AI" is pretty vague. Let's just blame Rick since he started it. :D :D

**Comment by isaac2004** [comment]
@rachelappel @guardrex  so the goal is to build a doc for Azure AD Integration for a Core App? There are a few code samples for this. https://azure.microsoft.com/en-us/resources/samples/active-directory-b2c-dotnetcore-webapp/ for instance.

**Comment by rachelappel** [comment]
@isaac2004 AI = App Insights https://docs.microsoft.com/en-us/azure/application-insights/app-insights-asp-net

**Comment by isaac2004** [comment]
@rachelappel sorry confused, there is a comment by @guardrex that AI means Azure Integration

**Comment by rachelappel** [comment]
@isaac2004  So many acronyms it is impossible to keep track of what people mean. Anyway looks like I can close this.
