### ISSUE TITLE
New topic: Connect to server explorer and do basic debugging

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#4230]
A new topic on using Visual Studio to connect to Server Explorer as well as some basic debugging is requested. 

First requested in [Issue 3373](https://github.com/aspnet/Docs/issues/3373) stating "info on connecting to Server Explorer and doing basic debugging" however it was decided by @wadepickett @scottaddie @rachelappel that this is better suited as a new topic to keep the scope of docs straightforward and simple.

**Comment by danroth27** [comment]
Sorry, but I don't get what this topic is intended to cover. Is this about remote debugging an ASP.NET Core app in Azure App Services?

**Comment by rachelappel** [comment]
@danroth27 Well, any sort of debugging was out of scope for the doc it was requested for, and I don't know the original context past this sentence "info on connecting to Server Explorer and doing basic debugging" (which even just that is out of scope for the doc on publishing to azure). So after discussing with the team we figured it might be a new topic, so remote debugging could certainly be included there. However, there might be an existing article out there it can be squeezed into.

**Comment by danroth27** [comment]
This looks like it covers the remote debugging with ASP.NET Core scenario: https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-azure

**Comment by rachelappel** [comment]
Ok, close this out then?
