### ISSUE TITLE
Consolidate migration content

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#4237]
We should eventually consolidate our migration content from ASP.NET to ASP.NET Core so it isn't specific to an ASP.NET Core version. We can probably just document how to migrate to the latest available version of ASP.NET Core, so that folks don't mistakenly migrate to an outdated version.

**Comment by isaac2004** [comment]
@scottaddieso everything I. The migration folder needs to be updated/version agnostic

**Comment by isaac2004** [comment]
@scottaddie so everything in The migration folder needs to be updated/version agnostic

**Comment by scottaddie** [comment]
Paging @danroth27. Looking for input on what you'd like to see here.

**Comment by danroth27** [comment]
How about something like this for the [migration](https://docs.microsoft.com/en-us/aspnet/core/migration/) node:

Migrating from ASP.NET to ASP.NET Core
- Migrating from ASP.NET MVC to ASP.NET Core
- Migrating Configuration
- Migrating from ASP.NET Web API to ASP.NET Core
- Migrating HTTP Modules to Middleware

Migrating from ASP.NET Core 1.x to 2.0
- Migrating from ASP.NET Core 1.x to 2.0
- Migrating Authentication and Identity

The content in the "Migrating from ASP.NET to ASP.NET Core" would always be for migrating to the latest supported version.

Daniel Roth

**Comment by isaac2004** [comment]
@danroth27 @scottaddie This idea seems fine, so the goal is to update those 5 docs from 1.x to 2.x?

**Comment by isaac2004** [comment]
@danroth27 Based on #974 I think it makes sense to add another level to Migrating Configuration, something like

Migrating from ASP.NET to ASP.NET Core
- Migrating Configuration
    * Migrating from ASP.NET Membership to ASP.NET Core
        *  Migrating Data
        *  Migrating Application
    * Migrating from ASP.NET Identity to ASP.NET Core
        * Migrating Application
        * Migrating Data 

Some caveats here, there is currently a ASP.NET to ASP.NET Core 1.x Identity doc and a ASP.NET Core 1.x to 2.0 doc, but ASP.NET to ASP.NET Core 2 doc does not exist. 

Thoughts also @blowdart

**Comment by isaac2004** [comment]
@danroth27 @blowdart

**Comment by blowdart** [comment]
That makes sense, I'd number the ASP.Identity ones too, because there are so so many
