### ISSUE TITLE
Introduce NSwag as an alternative to Swashbuckle when using Swagger

### ISSUE THREAD

**Issue by zuckerthoben** [aspnet/Docs#4258]
Article: https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md 

This article covers Swagger and introduces to Swashbuckle.  
I would like to see an alternative to Swashbuckle proposed, namely NSwag (https://github.com/RSuter/NSwag). The big selling point of NSwag is its ability to not only introduce the Swagger UI, but generate complete, robust and efficient API client code for C# and TypeScript. You also have the choice to use it directly in code, with an easy to use GUI or in cmd. It also supports asp.net core. All in all the workflow offers more than Swashbuckle in my opinion. We use it in our dev team with great success in C# and Angular 4 projects. 

I propose mentioning NSwag as an alternative to Swashbuckle at the start of the article or even better, move the Swashbuckle-focussed content into a sub page and create a sub page for NSwag, describing the workflow. Then you could describe what Swagger is, what the advantages are and how to use the UI in the main article, then link to the two sub pages. 

Current TOC:  

- Introduction
[Swashbuckle content]
- Getting started 
- Package install 
- Configure middleware
- swagger.json 
- Swagger UI 
- Customization
- XML doc in VS (for Mac/Code) 
- Data Annotations
- Customizing the UI
(EDIT: - Honorable mention of ReDoc) 

Proposed TOC:  

- Introduction, mentioning Swashbuckle and NSwag
- What is Swagger, swagger.json, Swagger UI
- How to use the Swagger UI 
- Link to sub pages on how to implement(Swashbuckle & NSwag)

Subpage TOC (Swashbuckle, NSwag):

- Getting started
- Package install
- Configure middleware
- First launch
- Customization
- XML doc
- Data Annotations
- Customizing the UI 
- Link to project wiki

**Comment by Rick-Anderson** [comment]
@zuckerthoben  would you be willing to write this article?
@danroth27  @spboyer please review

**Comment by zuckerthoben** [comment]
Yes, I can do that. I can start next week.

**Comment by Rick-Anderson** [comment]
@danroth27 @spboyer please review

**Comment by danroth27** [comment]
I'm concerned this is premature given that NSwag uses reflection instead of the ApiExplorer model. @rynowak thoughts?

**Comment by rynowak** [comment]
I think this is fine. We've already reached out to @rsuter (the author) and we're going to work with him to address any gaps. NSwag in its current form is still a very complete product and we expect it to get better too. I see no reason why we shouldn't start recommending it.

**Comment by danroth27** [comment]
Alright, let's proceed then.

**Comment by zuckerthoben** [comment]
I finished the raw articles. Please review the general content layout. I will then finalize and push the PR.

Main article: 
https://github.com/zuckerthoben/Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md

Sub articles:
Swashbuckle: https://github.com/zuckerthoben/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md
NSwag: https://github.com/zuckerthoben/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md

**Comment by RSuter** [comment]
@danroth27 @rynowak  Changing it to use ApiExplorer should not be that big of an effort itself (the code change) - the problem are all the dependencies (i.e. create new packages), support for legacy Web API, ASP.NET Core 1.0/1.1/2.0 and command line support...

**Comment by Rick-Anderson** [comment]
@scottaddie  can you review the raw articles?

**Comment by RSuter** [comment]
Hi everyone, 

I'm the developer of NSwag and here are my 50 cent. 

Main article: 

- Intro: 
	- "two popular Swagger .NET implementations": What exactly is implemented? I think we should write about the difference between Swagger generation, Swagger UI and code generation (main use cases for Swagger) and that we are talking here mainly about Swagger generation?

- What is Swagger?
	- Maybe we should add a comparision with WSDL, e.g. "Swagger is to RESTful HTTP services what WSDL is for SOAP Web services". This will clarifiy its capabilities for lots of people. 

- Swagger Ui
	- I think we should create a new chapter, e.g. "What is Swagger used for?" with the following subchapters: 
		- Render a web based test UI 
			- e.g. Swagger UI => there are others (e.g. ReDoc)
		- Generate client proxies
			- Like WCF service references
			- Many different generation tools
				- Main problem: Missing features in the generated problem (e.g. no support for discriminators, etc.)
- Getting started: 
	- Comparision between the tools (capabilities), maybe a table like: 
	

|                 | Swagger generation (Web API/MVC) | Serve Web UI          | Code generation (C#)             | Swagger generation integration
| --------------- | -------------------------------- | ----------------------------------------------------------
| Swashbuckle     | x                                | x                     |                                  | Middleware
| NSwag           | x                                | x (Swagger UI, ReDoc) | x (C#/TypeScript)                | Middleware, command line (NPM), msbuild
| AutoRest        |                                  |                       | x (C# and many other languages)  |
| swagger-codegen |                                  |                       | x (C# and many other languages)  |

Because I'm the developer of NSwag this may be a little biased.

**Comment by zuckerthoben** [comment]
* So I would ref to the comparison table in the intro, I guess? 
* I can insert the WDSL comparison. 
* If we get the "What is Swagger used for" chapter and sub chapters lined out properly I can change it to that.

**Comment by scottaddie** [comment]
@zuckerthoben Thank you for your help with this topic! Please submit a PR to this aspnet/Docs repo, and I'll review what you've done ASAP. It will be much easier to collaborate that way.

**Comment by simeyla** [comment]
This is great - except where did the nswag article go? This is a broken link

https://github.com/zuckerthoben/Docs/blob/master/aspnetcore/tutorials/getting-started-with-nswag.md

Trying to decide between continuing with nswag for Angular 5 (which I used months ago) or `ng-swagger-gen` which is yet another implementation but just for Angular https://github.com/cyclosproject/ng-swagger-gen

**Comment by zuckerthoben** [comment]
Sorry, I havent found time to correct the errors yet. 

This is the correct link: https://github.com/zuckerthoben/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md

**Comment by RSuter** [comment]
@zuckerthoben and others. What is that current state of this issue/PR?

**Comment by zuckerthoben** [comment]
Unfortunately nothing changed yet. Its hard for me to find the time to learn the way the docs work (especially embedding the correct code snippets from the repo) in my spare time. I would be glad if somebody has the energy and time to spare to fix the errors in the PR with me.

**Comment by scottaddie** [comment]
@zuckerthoben If you submit a PR with these changes, I'll be happy to review and assist with the code snippets and anything else.

**Comment by RSuter** [comment]
I've created the PR: https://github.com/aspnet/Docs/pull/5622
I will also review the text and update the PR as needed...

**Comment by RSuter** [comment]
@zuckerthoben is this ok for you? otherwise I'll delete the PR and you can create one...

**Comment by zuckerthoben** [comment]
All fine. Create a new one.

**Comment by mikeblakeuk** [comment]
@zuckerthoben @scottaddie Did the comparison table get added to documentation?
