### ISSUE TITLE
Cannot complete Mac walkthrough of DNX because of crucial broken link

### ISSUE THREAD

**Issue by VanKichline** [aspnet/Docs#429]
On http://docs.asp.net/en/1.0.0-beta7/tutorials/your-first-mac-aspnet.html, the link "Download a sample Empty Web Site to use with this article.” just points to https://github.com/aspnet/docs/, which makes it impossible to complete the walk-through. No other source for the basic template is cited.  This blocks evaluating ASP.NET on the Mac using this source, and I don’t trust others to be up-to-date.

**Comment by KevM** [comment]
I ran into the same issue just now. I think I fixed it to point at the correct location. Hope this helped.

**Comment by VanKichline** [comment]
There's no change.  The link still points to https://github.com/aspnet/docs/.

**Comment by KevM** [comment]
@VanKichline the PR has not been merged yet. The link I believe should be changed to : https://github.com/aspnet/Home/tree/dev/samples

**Comment by danroth27** [comment]
We decide to remote this link and point people to Yeoman instead: https://github.com/aspnet/Docs/pull/442
