### ISSUE TITLE
Add content on doing localization with PO files

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4297]
The proposal is to add content on doing localization with PO files using Orchard. Proposed content here:

https://gist.github.com/sebastienros/7980aad2ab33dd3a1c011fcf5a3f350c

The package is on MyGet right now, and will be on Nuget in a few days.

@sebastienros

**Comment by scottaddie** [comment]
@danroth27 We already have a "**Fundamentals/Globalization and localization**" link in the TOC. I propose that we make that an expandable node and put this proposed doc under it. Thoughts?

**Comment by danroth27** [comment]
Yup, that sounds reasonable.
