### ISSUE TITLE
Step 7 Uses AppId/AppSecret incorrectly

### ISSUE THREAD

**Issue by bryanwrightscode** [aspnet/Docs#4348]
Re Topic "Creating a Google app for OAuth 2 and connecting the app to the project"
Step 7 states to copy and paste the AppId and AppSecret into the UseGoogleAuthentication method. As of writing this comment, the method takes ClientId and ClientSecret, whereas ~~Twitter and~~ Facebook method~~s~~ ~~use~~ uses App instead of Client. It might be beneficial to also state where the AppId and AppSecret are coming from in Google Api, especially since the credentials created also use Client instead of App terminology. Lastly it would be helpful to state that this method is found in the Startup.Auth.cs file in the App_Start folder.

**Comment by guardrex** [comment]
@bryanwrightscode ... Step 7 of which topic?

**Comment by bryanwrightscode** [comment]
Topic: "Creating a Google app for OAuth 2 and connecting the app to the project"
Step 7: "Copy and paste the AppId and App Secret ... "
`    app.UseGoogleAuthentication(
         clientId: "000-000.apps.googleusercontent.com",
         clientSecret: "00000000000");`

**Comment by guardrex** [comment]
Ah ... thx ...

https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on#creating-a-google-app-for-oauth-2-and-connecting-the-app-to-the-project

*aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on.md*

**Comment by guardrex** [comment]
@bryanwrightscode Would this text cover it?

> From the Google APIs API Manager, visit the **Credentials** tab to obtain the **Client ID**. Download to save a JSON file with application secrets. Copy and paste the **ClientId** and **ClientSecret** into the `UseGoogleAuthentication` method found in the *Startup.Auth.cs* file in the *App_Start* folder. The **ClientId** and **ClientSecret** values shown below are samples and don't work.

Also, you mentioned, "whereas Twitter and Facebook methods use App instead of Client." This topic (for Facebook anyway) uses "App Id" and "App Secret". Twitter seems to be using "ConsumerKey" and "ConsumerSecret" (according to the [aspnetcore Twitter topic](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?tabs=aspnetcore2x)). Are additional changes needed?

**Comment by bryanwrightscode** [comment]
Yeah your proposed text seems to solve all my concerns. I mistakenly said Twitter uses AppId and AppSecret, sorry about that. Otherwise all of this looks good to me.
