### ISSUE TITLE
Update session

### ISSUE THREAD

**Issue by Eilon** [aspnet/Docs#4349]
## General

We use issues to drive the discussion for changes to
existing topics and the creation of new topics.
This template offers some suggestions to consider
when creating an issue.

## Issues with Existing Topics

If the issue is a simple typo or similar correction, just submit a PR.
Otherwise, let us know what's wrong or what we should improve. Include a
link to the topic.

## Requests for new Topics

1. Write a **short** paragraph describing what the topic will cover.

2. Write an outline of the proposed topic contents.

3. Where would you put the topic in the Table of Contents.

4. If you know who should review the issue, notify them by including @githubID in the issue description.

**Comment by guardrex** [comment]
Might be a duplicate (or just related to):

[2.0 Update fundamentals/app-state (aspnet/Docs 3767)](https://github.com/aspnet/Docs/issues/3767)
[Improve session and application state in ASP.NET Core article by adding more details (aspnet/Docs 3216)](https://github.com/aspnet/Docs/issues/3216)

**Comment by Eilon** [comment]
Oops, I somehow submitted this issue by mistake. Closing.
