### ISSUE TITLE
Markup to show how to inject Options in Configuration document

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#437]
@danroth27 @MiKom @omarpando 

I just ran into a lack of knowledge (https://github.com/aspnet/Home/issues/916) on what to inject into the view for Options. I thought I'd mention that a little markup showing how to do it at ...

http://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects

... might be very helpful. For your example, it might be something like ...

``` html
@inject IOptions<MyOptions> optionsAccessor
<html lang="en-US">
    <head>
        <title>Options Markup</title>
    </head>
    <body>
        <div>...@(optionsAccessor.Options.Option1)...</div>
    </body>
</html>
```

**Comment by Rick-Anderson** [comment]
Good suggestion.

**Comment by Rick-Anderson** [comment]
@GuardRex  can you provide a sample project? No hurry.

**Comment by Rick-Anderson** [comment]
@danroth27  is this something we want to add to the document or sample?  Wouldn't it be better to pass the options in a model from the action method?

**Comment by GuardRex** [comment]
@Rick-Anderson 

Under the section *Using Options and configuration objects* and immediately after the line ...

>The HomeController.Index method returns option1 = value1_from_json, option2 = 2.

Something like this could be mentioned (with a View added to the current **UsingOptions** sample), which ties into the example just provided ...

You can also inject `IOptions<TOptions>` directly into a Razor view:
```html
@using Microsoft.Extensions.Options
@inject IOptions<MyOptions> OptionsAccessor
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Options Injection into a View</title>
</head>
<body>
    <h1>Options Injection into a View</h1>
    <p>
        option1 = @OptionsAccessor.Value.Option1, option2 = @OptionsAccessor.Value.Option2
    </p>
</body>
</html>
```
Could possibly add a browser rendering this, but it probably isn't necessary.

If you want to see that in a PR, let me know.
