### ISSUE TITLE
Information on self certing while working with kestrel is mostly out dated.

### ISSUE THREAD

**Issue by BrianMinister** [aspnet/Docs#4373]
**For page:** https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x
**MD file:** https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md

* Makecert UI is last updated in 2012, and is on codeplex which is shutting down.
* For new-selfsignedcertificate, https://technet.microsoft.com/itpro/powershell/windows/pki/new-selfsignedcertificate is a dead link.

Both of those links should be replaced or removed.

**Comment by guardrex** [comment]
Thanks @BrianMinister!

According to https://msdn.microsoft.com/en-us/library/aa386968.aspx, the tool is depreciated:

> MakeCert is deprecated. To create self-signed certificates, use the Powershell Cmdlet New-SelfSignedCertificate.

I'll remove it and update the topic with a good PS link for `New-SelfSignedCertificate`.
