### ISSUE TITLE
call out that AddIdentity sets the defaults so you shouldn’t AddAuthentication(scheme). 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4381]
related https://github.com/aspnet/Docs/pull/4377

From: Chris Ross (ASP.NET) 
One of the more common issues we have is people calling AddIdentity and AddAuthentication(scheme). Can we at least call out that AddIdentity sets the defaults so you shouldn’t?

**Comment by scottaddie** [comment]
Fixed by https://github.com/aspnet/Docs/pull/4387
