### ISSUE TITLE
TagHelpers ToC Update

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#4386]
Update ToC for TagHelpers

**Comment by guardrex** [comment]
btw- There's some TOC work in https://github.com/aspnet/Docs/pull/4345 that hasn't merged yet.

**Comment by rachelappel** [comment]
@guardrex  Yep those are good. Will also need to add some in for Tag Helpers that haven't been documented yet.

**Comment by guardrex** [comment]
I was just concerned about merge conflicts :boom: :cry:, but #4345 might go in soon.
