### ISSUE TITLE
Update Continuous Deployment to Azure with VS to .NET Core 2.0 and VS 2017

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#4393]
https://docs.microsoft.com/en-us/aspnet/core/publishing/azure-continuous-deployment

**Comment by isaac2004** [comment]
@rachelappel are the only changes needed are changing the VS screenshots and  the link to .NET Core to https://www.microsoft.com/net/download/core

**Comment by rachelappel** [comment]
@isaac2004 Some text will have to be changed to match the updated screen shots. Also updated docs require SEO and MinVC content updates. Mostly it is screen shots but there are also a few adjustments in the steps too. Nothing too serious. I've been OOF for a while so I haven't gotten back to this yet.

**Comment by isaac2004** [comment]
@rachelappel should this be modified to use Azure Continuous Delivery (preview) or the same process using Deployment Options?

**Comment by rachelappel** [comment]
@isaac2004  There is  [this doc](https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-dotnet-continuous-delivery) on it. Generally, the guidelines are to try to keep specific topics to their own page, as customer satisfaction goes up when the docs are smaller and focused to a single topic. 

On a similar note we also have continuous deployment and integration docs and I'm wondering if it would be a good idea to add a new doc that compares continuous deployment vs delivery vs integration, as the similar names seem to be a source of confusion for a few folks.

**Comment by isaac2004** [comment]
@rachelappel yep all makes sense. I will just update some of the VS and Azure screens and text for this doc than.
