### ISSUE TITLE
Update instructions for viewing generated Razor code for 2.0

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4432]
Looks like these instructions for viewing the generated Razor code need to be updated for 2.0:

https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor#viewing-the-razor-c-class-generated-for-a-view

@NTaylorMullen @ajaybhargavb Could you guys please provide the updated instructions?

**Comment by danroth27** [comment]
From @NTaylorMullen:

You can view your generated code by implementing https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.Extensions/MvcRazorTemplateEngine.cs and inspecting the returned code document from CreateCodeDocument.

**Comment by danroth27** [comment]
@NTaylorMullen What do you mean by "implement" `MvcRazorTemplateEngine`? It's already a concrete class, right? Also, how do you inspect the `RazorCodeDocument` to see the actual C#?

**Comment by NTaylorMullen** [comment]
Like this:

Add the service: `services.AddSingleton<RazorTemplateEngine, CustomTemplateEngine>();`

Have the class:
```C#
public class CustomTemplateEngine : MvcRazorTemplateEngine
{
    public CustomTemplateEngine(RazorEngine engine, RazorProject project) : base(engine, project)
    {
    }
        
    public override RazorCSharpDocument GenerateCode(RazorCodeDocument codeDocument)
    {
        var csharpDocument = base.GenerateCode(codeDocument);
        var generatedCode = csharpDocument.GeneratedCode;
            
        // Look at generatedCode
            
        return csharpDocument;
    }
}
```

**Comment by danroth27** [comment]
Perfect, thx!

**Comment by guardrex** [comment]
@Rick-Anderson Want me to get this?

**Comment by Rick-Anderson** [comment]
@guardrex  thanks

**Comment by guardrex** [comment]
Sure .... do you want the sample with no layout page for any view?

**Comment by Rick-Anderson** [comment]
Full, minimal or no layout - doesn't matter. Might be best to keep it simple.

**Comment by guardrex** [comment]
I went simple with it last night. There's a proper *_Layout.cshtml* view in it now. It just has the required tags to create a well-formed page.

I'll have it for u in a few hours. I'm going to hit the 💪 gym first, then wrapping this up is next.
