### ISSUE TITLE
security/authentication/identity-enable-qrcodes - need instructions for MVC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4439]
[Enabling QR Code generation for authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes) states:

**Note: This topic applies to ASP.NET Core 2.x with Razor Pages.** - Need MVC instructions. Customer [writes](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes#lf-content=206166910:739148776)

>Looking at mvc core 2.0 it looks like everything is implemented in mvc template and when enabling qr code everything works fine with authenticator app. But even after confirming email and adding phonenumber I see no way of enabling.2-fact using email or sms and no google searches reveal any info about this.

>Isnt it supposed to work out-of-the-box like athenticator app?

**Comment by blowdart** [comment]
It's the same instructions. Literally.

**Comment by Rick-Anderson** [comment]
@blowdart  I'll update the doc. Can I add this customer comment in a new debugging section?

check if the server time is correct. TOTP auth depends on very precise time, since the generated codes are short-lived. It could also be that your authenticator app is running on a device with the wrong time, but if you use that same app with other services, then the problem must be at your server.

`< I won't add this >`
I had this problem before because the company firewall was preventing Windows from updating the time with the Windows Time Servers. After I fixed the server time the generated codes started to match.

**Comment by blowdart** [comment]
Oh wait, it's a little different. The only diffence is the path to the view, for MVC it's

 Views\Account\Manage\EnableAuthenticator.cshtml 

I'm sure I had both in the original doc :)

So,

In the Pages\Account\Manage\EnableAuthenticator.cshtml (Razor Pages) or Views\Account\Manage\EnableAuthenticator.cshtml (MVC)  file, locate the Scripts section at the end of the file:

As for customer comment

TOTP authentication depends on both the server and authenticator device having an accurate time. Tokens only last for 30 seconds. If your TOP 2FA logins are failing check that your server time is accurate, and preferably synchronized to an accurate NTP service.
