### ISSUE TITLE
add razor pages authorize doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4444]
@danroth27   this is listed in #3777 - please edit this and outline what you want - Did you want to document RP Auth using the templates?

**Comment by Rick-Anderson** [comment]
@danroth27 this is listed in #3777 - please edit this and outline what you want - Did you want to document RP Auth using the templates?

**Comment by danroth27** [comment]
I believe this doc is intended to cover the folder based authorization model used by Razor Pages. Some of this is already being discussed in https://github.com/aspnet/Docs/issues/4281. We should setup some time with @pranavkm and just get a brain dump.

**Comment by Rick-Anderson** [comment]
dupe of #4281
