### ISSUE TITLE
arch & runtime flavor notice on Installing ASP.NET 5 On Windows 

### ISSUE THREAD

**Issue by doggy8088** [aspnet/Docs#445]
In this page [Installing ASP.NET 5 On Windows](http://docs.asp.net/en/1.0.0-beta7/getting-started/installing-on-windows.html), it will be better to add some notcie about `dnvm upgrade` will install `dnx-clr-win-x86.1.0.0-beta7` only.  If you need install all the other 3 runtimes, you'll have to install it manually.  That is

>dnvm install 1.0.0-beta7 -arch x86 -r coreclr
>dnvm install 1.0.0-beta7 -arch x64 -r coreclr
>dnvm install 1.0.0-beta7 -arch x86
>dnvm install 1.0.0-beta7 -arch x64

**Comment by Rick-Anderson** [comment]
@TomArcher can you try to reproduce on a clean VM. I just test 
dnvm list
lists all 4 versions as installed.

**Comment by danroth27** [comment]
If you use the installer you will get all four runtimes. It's only when you use dnvm that you just get the default DNX.
