### ISSUE TITLE
fundamentals/logging | Introduction to Logging in ASP.NET Core | Update for Streaming with Core 2.0

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#4459]
Introduction to Logging in ASP.NET Core 
Add streaming logs for Core 2.0 to the section on Azure logging https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging

Moved from https://github.com/aspnet/Docs/issues/2119

**Comment by rachelappel** [comment]
@guardrex Luke, are the TagHelpers docs all in place where I can update the ToC to reflect what's out there or are there PRs being worked on where I should wait? I'm assuming you were working on those (I was OOF a bit so might not be up to date on what's going on). LMK thanks

**Comment by guardrex** [comment]
They're in place as far as I know with no immediate PRs in the works for THs. There might be some issues, but no active work AFAIK.

I'm about to put up a PR that moves the logging content into an index page so that we can have the new LoggerMessage topic sit next to it in the TOC. 

Cc @scottaddie

**Comment by rachelappel** [comment]
@guardrex Sounds good and oops that comment was supposed to go in issue 4386. I have too many tabs open. :D

**Comment by guardrex** [comment]
ah ... i see. I was wondering. lol ... That's why I mentioned the LoggerMessage PR about to go in. I was looking at the title of this.
