### ISSUE TITLE
Install instructions for Linux (deb) may be wrong

### ISSUE THREAD

**Issue by Senorsen** [aspnet/Docs#4470]
In https://www.microsoft.com/net/core#linuxubuntu , there may be a mistake in step one:

```
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
```
The commands above will fail to add the key; We should use `apt-key add microsoft.gpg` instead.

**Comment by Rick-Anderson** [comment]
@Senorsen  can you open the issue at https://github.com/dotnet/core/issues/new
