### ISSUE TITLE
Update UseIdentity with UseAuthentication

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4472]
- [ ] [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data) #4473 
- [x] [Application Startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup) 
- [x] middleware fixed in #4481

@scottaddie  I did a search and looks like this is all.

**Comment by isaac2004** [comment]
@Rick-Anderson can you check the 2nd item in this list? It was fixed by that PR
