### ISSUE TITLE
Update security/authorization/secure-data to 2.0

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4473]
[Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data)

- [ ] 2.0 version in Razor Pages
- [ ]  app.UseIdentity(); -> app.UseAuthentication
- [ ] Move seed from startup to main
- [ ] Use meta-data package

@joeaudette  anything else I need to do?

**Comment by joeaudette** [comment]
@Rick-Anderson sounds right to me. Also need to change the Startup Constructor to be more like the 2.0 templates, ie:

       public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

and the property in Startup for IConfigurationRoot needs to change to IConfiguration

and in Program.cs the syntax for building the host should be updated when you move the seeding there

**Comment by isaac2004** [comment]
@Rick-Anderson 

Do you want the View in this section *Inject the authorization service into the views* to be converted from MVC to Razor Pages?

**Comment by Rick-Anderson** [comment]
@isaac2004 
The entire app should be Razor Pages - so [Update the code to support authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data#update-the-code-to-support-authorization) would be update the Razor Pages to support authorization, etc.

This tutorial was written for 1.x, where the seed method ran from Startup. Seed method now runs from Main.

**Comment by isaac2004** [comment]
@Rick-Anderson gotcha, in that case I will unlink that PR from this issue as rewriting that app is a little more work.

**Comment by Rick-Anderson** [comment]
@Tratcher  please 1 minute review [Program.cs](https://github.com/Rick-Anderson/RPsecureUserData/blob/master/ContactManager/Program.cs#L31,L38)

If the [password is too weak](https://github.com/Rick-Anderson/RPsecureUserData/blob/master/ContactManager/Data/SeedData.cs#L46-L50), the user is not created.  Many customers had trouble with this - so I don't want the app to start.

**Comment by Tratcher** [comment]
Seems file. The formatting is off on this line: https://github.com/Rick-Anderson/RPsecureUserData/blob/606affb5c31cedb7ed2a044c88d4a2b99b5f5091/ContactManager/Program.cs#L31
