### ISSUE TITLE
Broken Link for Create and run unit tests with Visual Studio

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4477]
The following link: "Create and run unit tests with Visual Studio" on this page, [Testing controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification), is broken.  I tried searching for the new url and I can't find it.  It is currently pointing to https://www.visualstudio.com/docs/code/create-and-run-unit-tests-vs

![image](https://user-images.githubusercontent.com/14079228/31076750-afd6e6cc-a749-11e7-8d51-f1ea89966afd.png)

**Comment by guardrex** [comment]
It prob should be: */visualstudio/test/unit-test-your-code* (relative link; for the topic link)

... that goes to: https://docs.microsoft.com/visualstudio/test/unit-test-your-code
