### ISSUE TITLE
Update 2.0 App Insights migration instructions for .NET Framework

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#4493]
https://docs.microsoft.com/aspnet/core/migration/1x-to-2x/#rely-on-application-insights-light-up-features

If targeting .NET Framework, an explicit App Insights SDK package reference is required. In addition, the `UseApplicationInsights` extension method still needs to be called. Without these 2 things in place, the "light up" feature of VS 2017 doesn't work.

**Comment by davidfowl** [comment]
When was it deprecated?

**Comment by isaac2004** [comment]
@davidfowl Ah I misread a doc I was looking at. `AppBuilder.UseApplicationInsightsExceptionTelemetry()` is deprecated, not `UseApplicationInsights` on `WebHostBuider`.... disregard
