### ISSUE TITLE
Basics of Web Development

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#45]
Getting Started->Conceptual Overview->Basics of Web Development
- HTML
- JavaScript
- CSS

**Comment by MikeWasson** [comment]
If this is not specifically about ASP.NET or our tools, perhaps we can just point to some useful resources on the web -- there's plenty of stuff already out there.

**Comment by dvalishvili1** [comment]
this can be great introduction https://developer.mozilla.org/en-US/docs/Web_Development/Introduction_to_Web_development

**Comment by GuardRex** [comment]
Another candidate link for such a section might be http://www.w3.org/standards/webdesign/

**Comment by thebeebs** [comment]
There is an on going effort at http://webplatform.org for this sort of thing.

**Comment by danroth27** [comment]
We've decided existing content on the Web (ex w3Schools) is sufficient for this level of intro content.

**Comment by thedanfernandez** [comment]
Since this article isn't going to be created, I'd suggest removing from the TOC for clarity
