### ISSUE TITLE
Describe Composite Formatting of ValidationAttribute ErrorMessages

### ISSUE THREAD

**Issue by Rabadash8820** [aspnet/Docs#4505]
It recently came to my attention that `ValidationAttribute` error messages support [composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting).  I discovered this while reading about [localization of DataAnnotations](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#dataannotations-localization).  That section references a sample code snippet from this repo with the follow property declaration:

https://github.com/aspnet/Docs/blob/4dad08a6662a5cf2eac03c46b4dbb2cd009a43ef/aspnetcore/fundamentals/localization/sample/Localization/ViewModels/Account/RegisterViewModel.cs#L16-L20

The `[StringLength]` attribute is what caught my eye; I'd never seen anything like that!  A composite format string in an attribute constructor??

Unfortunately, I could not find the parameters for these composite format strings anywhere in the Docs, and had to resort to digging through the .NET Core source code to find how these strings were actually used (usually in `string.Format()` calls inside overriden `FormatErrorMessage()` calls).  It really seems like this information should be documented somewhere other than XML comments in the source code.

## Possible TOC locations:

- [Introduction to model validation](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
- [Introduction to using tag helpers in forms](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
- [Adding validation](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
- [Part 6: Using Data Annotations for Model Validation](https://github.com/aspnet/Docs/blob/master/aspnet/mvc/overview/older-versions/mvc-music-store/mvc-music-store-part-6.md)

## Suggested reviewers:
- @Rick-Anderson 
- @jerriep
- @rachelappel 
- @damienbod 
- @hishamco

**Comment by Rick-Anderson** [comment]
@Rabadash8820  I think this would make a great addition. Maybe a paragraph describing it and a sample. we could have a list of validation attributes that support this and the list would be a link to the source code.

@danroth27  please comment

**Comment by Rick-Anderson** [comment]
@Rabadash8820 is this covered in one of your PRs?

**Comment by Rabadash8820** [comment]
Unfortunately no.  I've had the reference source sitting in an open tab on my browser since I made this issue; just haven't gotten around to combing through it yet. 😛

**Comment by danroth27** [comment]
@mairaw This should be documented in the data annotations docs. Maybe in the API ref?

**Comment by mairaw** [comment]
Fine with me. I think @Rick-Anderson owns that part of our API docs too since it's ASP.NET related.

**Comment by Rick-Anderson** [comment]
@danroth27  currently all the API docs are generated from /// comments.

@dend  what's the best way to get this documented?

**Comment by mairaw** [comment]
> @danroth27 currently all the API docs are generated from /// comments.
That's not true for the .NET reference such as https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations. You just have to click edit and provide the content you want. I can help you with format if needed.

**Comment by Rick-Anderson** [comment]
Moved to #10546
