### ISSUE TITLE
Documentation error for QR Code generation

### ISSUE THREAD

**Issue by NoralK** [aspnet/Docs#4517]
## Issues with Existing Topic

[Enabling QR Code generation for authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes)

Great article!  I did find two issues.

**First issue**

In the **Adding QR Codes to the 2FA configuration page** section change:

Views\Account\Manage\EnableAuthenticator.cshtml (MVC)

to

Views\Manage\EnableAuthenticator.cshtml (MVC)

**Second issue**

In the **Change the site name in the QR Code** section change:

The site name in the QR Code is taken from the project name you choose when initially creating your project. You can change it by looking for the `GenerateQrCodeUri(string email, string unformattedKey)` method in the EnableAuthenticator.cshtml.cs file.

to

The site name in the QR Code is taken from the project name you choose when initially creating your project. You can change it by looking for the `GenerateQrCodeUri(string email, string unformattedKey)` method in the Pages\Account\Manage\EnableAuthenticator.cshtml.cs (Razor Pages) or Controllers\AccountController.cs (MVC).

Noral

**Comment by scottaddie** [comment]
@NoralK Thank you for reporting this issue! I've created a pull request to address it.
