### ISSUE TITLE
Bower article needs to be updated for changes to bower component installation

### ISSUE THREAD

**Issue by jongalloway** [aspnet/Docs#452]
[Manage Client-Side Packages with Bower](http://docs.asp.net/en/latest/client-side/bower.html) was written for previous script installation / management which put bower_components in root and copied distributable scripts to wwwroot via gulp. That has been changed to installing bower components directly in wwwroot via .bowerrc.

**Comment by scottaddie** [comment]
@jongalloway Is this the new approach as of the Beta 8 release? I'm willing to tackle this article rewrite if the team needs some assistance. Just let me know.

**Comment by danroth27** [comment]
@scottaddie Yup, this should be in beta8 (shipping this week), so if you want to submit a PR for this update that would be great. You can see what the beta8 templates look like in the newly public Templates repo: https://github.com/aspnet/Templates/tree/release/src/BaseTemplates/StarterWeb

**Comment by scottaddie** [comment]
@danroth27 Thank you for the info! Will start on this tonight.

**Comment by scottaddie** [comment]
@danroth27 Submitted a pull request. Let me know if something doesn't look quite right. I'm still learning Git.

**Comment by Rick-Anderson** [comment]
@scottaddie I'm not seeing the PR

**Comment by scottaddie** [comment]
@Rick-Anderson Here you go. It was already merged: https://github.com/aspnet/Docs/pull/550
