### ISSUE TITLE
Fix Getting Started with ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4528]
Snippet doesn't show changes. Also, remove the extra folder, no need for that.
Open Pages/About.cshtml and modify the page to display the message "Hello, world! The time on the server is @DateTime.Now":

see https://github.com/aspnet/Docs/pull/4521

**Comment by rachelappel** [comment]
@Rick-Anderson Which snippet doesn't show which changes?

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/getting-started
