### ISSUE TITLE
Document dependency required in the "Working with Static Files" page

### ISSUE THREAD

**Issue by angellaa** [aspnet/Docs#453]
I'd like to add a section to show how to add the Microsoft.AspNet.StaticFiles dependency that is required in order to configure static files. This change will follow a similar pattern as the "Add the CORS package" section in http://docs.asp.net/en/latest/security/cors.html?highlight=package#add-the-cors-package

**Comment by Rick-Anderson** [comment]
@TomArcher  can you follow-up?

**Comment by danroth27** [comment]
@angellaa We would welcome a PR for this issue. Let us know if you want to take this one.

**Comment by angellaa** [comment]
@danroth27 I would be more then welcome to take this one. Actually I already had a fix when I wrote the issue and I was waiting for an approval. I still have the changes locally but I struggle to build the project. Followed the steps many time completely uninstalling python and I get the following error when I run "make html".

Extension error:
Could not import extension yasfb (exception: No module named 'yasfb')

If I try to install yasfb I get a compilation error.

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Andrea\AppData\Local\Temp\pip-build-2las3t2q\feedformatter

Not sure how to fix this so I am not able to verify my changes locally. Grrr

**Comment by Rick-Anderson** [comment]
See also #716 
This doc is badly out of date.

**Comment by danroth27** [comment]
@angellaa The issue you saw should be fixed now. Pull down the latest and you should be able to build.

**Comment by danroth27** [comment]
Package information is now specified.
