### ISSUE TITLE
mvc/razor-pages fix UseInMemoryDatabase

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4544]
UseInMemoryDatabase API has changed (remove name)

**Comment by isaac2004** [comment]
@Rick-Anderson looks like you still need to pass string into the extension per [master on GitHub](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs)

![image](https://user-images.githubusercontent.com/8878502/32280263-a2337ca0-bef1-11e7-9463-842314656ea9.png)

**Comment by isaac2004** [comment]
@Rick-Anderson @scottaddie  please above is correct

**Comment by guardrex** [comment]
@isaac2004 That's correct. I ran into this with a few sample upgrades to 2.0. I've been using "InMemoryDb" as the name. Do we want to be consistent about that?

**Comment by Rick-Anderson** [comment]
Looks like all the samples in aspnetcore\mvc\razor-pages\index\sample pass a string param - so I'll close this.
