### ISSUE TITLE
important! Spam link on https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/recommended-resources-for-mvc

### ISSUE THREAD

**Issue by richardspence** [aspnet/Docs#4545]
The topic found [here](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/recommended-resources-for-mvc)

Has this link [ASP.NET MVC Quick Guide](http://qkview.com/techbrij/aspnet-mvc-4) but the destination is now a spam link talking about improving pc performance.

Either remove the link or fix the target blog if owned

**Comment by guardrex** [comment]
Thanks @richardspence ... if they want it removed, that'll do the trick.

**Comment by guardrex** [comment]
@richardspence Cool ... so it's just something that can be removed. You probably saw the "Edit" button on these topics. If you need to make a quick (small) change, you don't even need to open an issue ... just shoot in a PR. If you need to chat with devs about the process for working on larger changes, most of us hang out on Slack. Hit us up anytime! Self-signup is at: http://tattoocoder.com/aspnet-slack-sign-up/
