### ISSUE TITLE
NPM dependencies stop working

### ISSUE THREAD

**Issue by BlanketGuy** [aspnet/Docs#4547]
I've been having a lot of trouble with the dependencies when creating a project with the Angular template on VS 2017. 
First I had to install all the npm packages one by one, and some of them stopped working out of the blue. 
Every time I fix something and re-open the project, something else stops working. Anyone else had this problem? How did you solve it?

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/templating/issues/61
