### ISSUE TITLE
Docs Request: Tag Helper Components

### ISSUE THREAD

**Issue by ctolkien** [aspnet/Docs#4552]
## Requests for new Topics

This is a feature which was briefly outlined in [this post](https://blogs.msdn.microsoft.com/webdev/2017/08/25/asp-net-core-2-0-features-1/), however I could find no mention of it in the official docs.

Suggest it goes in under the existing Tag Helper TOC.

cc @guardrex

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/4033 https://github.com/aspnet/Docs/issues/3662

**Comment by ctolkien** [comment]
Well... :poop:
