### ISSUE TITLE
Update Getting Started with ASP.NET MVC 5 to VS 2017

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4557]
The series [Getting Started with ASP.NET MVC 5](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/) needs to be updated to VS 2017

**Comment by isaac2004** [comment]
@Rick-Anderson I can take this one, had a question about the solution though. It looks like the MVC Movie repo at one point lived under your account. Is it somewhere that can be moved to this repo?

**Comment by Rick-Anderson** [comment]
@isaac2004  the sample code should go in the Docs\aspnet\mvc\overview\getting-started\introduction\getting-started\sample folder. You'd have to create the sample folder.

**Comment by isaac2004** [comment]
@Rick-Anderson I am thinking creating the entire sample and putting it at Docs\aspnet\mvc\overview\getting-started\introduction\sample (which does not exist)
This would be the entire solution (no snippets) and all the docs would reference. Than obviously that would be the location the Deploy to Azure button reads from. If this makes sense I will proceed

**Comment by Rick-Anderson** [comment]
@isaac2004  sounds great. I don't think I ever saved the code for this tutorial.

**Comment by isaac2004** [comment]
@Rick-Anderson is good to be closed?

**Comment by Rick-Anderson** [comment]
@isaac2004  Yes, thanks!
