### ISSUE TITLE
Fix bookmarks

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4560]
bookmarks are missing '""', for example

that in file dependency-injection.md contains the content: [Options Model](configuration.md#options-config-objects) whose bookmark is invalid in file configuration.md’s output page.
If you check the content in configuration.md you can find there’s some content like the following shows:
`<a name=options-config-objects></a>`
I guess the purpose is that user want to define his own bookmark. However, the syntax is wrong, it should be
`<a name="options-config-objects"></a>`

**Comment by guardrex** [comment]
... because apparently DocFX isn't really following HTML specs. Unquoted attribute values that have values without spaces have been supported since HTML 2.0, so these should work fine for browsers.
