### ISSUE TITLE
Diagram for Custom Policy-Based Authorization

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4563]
## General
I think it would be handy to have some type of diagram for [custom policy-based authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies).  I think this would help people get up to speed quicker.

## Requests for new Topics

1. A diagram to help convey the architecture.

2. Write an outline of the proposed topic contents.

3. Where would you put the topic in the Table of Contents?  [Top of this page](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies).

4. @scottaddie @HaoK 

![image](https://user-images.githubusercontent.com/14079228/31547726-638600e0-aff6-11e7-9af1-957d80753a6a.png)

**Comment by scottaddie** [comment]
@danroth27 @HaoK Thoughts?

**Comment by danroth27** [comment]
@blowdart Thoughts?

**Comment by blowdart** [comment]
Diagrams work. It'd be interesting to try to diagram that any handler can pass to fulfilled by a requirement, but all requirements must to fulfilled to pass a policy.

**Comment by Rick-Anderson** [comment]
@spottedmahn  are you able to write this document? If so, what can we do to help?

**Comment by Rick-Anderson** [comment]
@spottedmahn  closing for now. We don't have the resources to create this doc. I
