### ISSUE TITLE
Last Build Report URL?

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4566]
I just submitted a PR and I got a [build report,](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r) very cool.  That got me thinking, is there a URL for the last successful build?

This would allow contributors to go in and clean up warnings.  With out the lastest build report though, contributors wouldn't know what needs fixing.

**Comment by Rick-Anderson** [comment]
@spottedmahn  that's a good idea. The build reports are super sporatic on what they report. The goal right now is to fix all the bad links. 

See #4651  #4649 #4648
Feel free to fix a few links and check them off (for example in #4651)
They are easy to fix in the browser edit. A good way to get lots of commits.

Thanks for reporting this, I haven't seen a good build report in awhile.

**Comment by spottedmahn** [comment]
Hi @Rick-Anderson - glad u like the idea!

I've submitted a few PR's now.  I'm wondering how to check them off though?  I can't edit ur post...

**Comment by Rick-Anderson** [comment]
Just reply in the PR with what is fixed and I'll check it.

**Comment by Rick-Anderson** [comment]
We should have clean builds now. I fixed all the errors.
