### ISSUE TITLE
Add HttpsRedirection and Hsts middleware documentation

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Docs#4568]
We just added a new set of middleware (https://github.com/aspnet/BasicMiddleware/pull/264) that will Redirect HTTP to HTTPS and Add the Strict-Transport-Security header to HTTPS responses. We need documentation by 2.1 for this. It should be straightforward. I can write a draft for the documentation.

This would go in the ["Enforcing SSL"]( https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md) section or in parallel to it.

**Comment by scottaddie** [comment]
@jkotalik Please let me know when the draft is ready, and I'll work with you to get it published.

**Comment by scottaddie** [comment]
@jkotalik What's the status of the draft?

**Comment by jkotalik** [comment]
I'll get on this within the next week or so. The design is fairly hardened now so I can properly document it. @danroth27 would you prefer to combine all Https documentation into the same doc or keep this separate?

**Comment by Rick-Anderson** [comment]
@danroth27  can you comment?

**Comment by Rick-Anderson** [comment]
@jkotalik  how is the doc doing? @danroth27  see a question for you.

**Comment by danroth27** [comment]
Same doc seems fine to me.

**Comment by Rick-Anderson** [comment]
@jkotalik let me know when you have a draft of the article or when you'll have time to work on it. I can do the editing and polish it off.

**Comment by jkotalik** [comment]
Thanks @Rick-Anderson ❤️
