### ISSUE TITLE
Describe how to call generic methods in .cshtml Razor files

### ISSUE THREAD

**Issue by Rabadash8820** [aspnet/Docs#4575]
## Background

I came upon this problem while trying to call `Assembly.GetCustomAttribute<T>()` in one of my Razor files.  Since C# generics use brackets (`<>`), the Razor compiler seemed to think that the call was an HTML tag.  Some googling led to posts like [this one](https://stackoverflow.com/questions/4253224/how-to-use-generic-syntax-inside-a-razor-view-file) on SO and [this one](https://forums.asp.net/t/1598699.aspx?Does+the+Razor+View+Engine+Support+Generic+Methods+) on the ASP.NET forums.  They explain how to call generic methods with an explicit Razor expression.  One of the answers on the SO post also mentions the pitfall of having extra `@` characters inside a Razor block.  However, neither I nor any of the contributors on that SO post had been able to find any of this information in the docs, which is no good.

## Solution
I don't think this info would need its own topic, but should be mentioned in the [Razor syntax ](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor) topic, probably in the Razor expression and/or Razor code block sections.

## Suggested Reviewers
- @Rick-Anderson 
- @guardrex 
- @NTaylorMullen

**Comment by Rabadash8820** [comment]
Okay I'm still a little new to PRs.  I accidentally deleted the branch on the PR above too soon; it should not be considered closed yet!

**Comment by Rick-Anderson** [comment]
@Rabadash8820  Are you offering to write that. That would be great and we can get it reviewed.

**Comment by Rabadash8820** [comment]
@Rick-Anderson Yep, see the referencing PR!
