### ISSUE TITLE
Deploy ASP.NET RP app with DB to Azure, dev on Mac & Windows VS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4580]
- [ ] Create an ASP.NET Core Razor Pages app + DB
- [ ]	Use GitHub with VS
- [ ]	Develop with VS Windows and VS Mac
- [ ]	Deploy to Azure using VS
- [x]   appSettings.json to set local DB
- [x]    Demo config settings

**Comment by CamSoper** [comment]
@Rick-Anderson Are these multiple docs?  Or a single scenario?

**Comment by Rick-Anderson** [comment]
>@Rick-Anderson Are these multiple docs? Or a single scenario?

Craig Dunn &  Gordon Hogenson are driving this. The topic(s) may go in the Azure repo.

**Comment by Rick-Anderson** [comment]
@ghogen do you have an issue tracking this? Can I close this issue?

**Comment by Rick-Anderson** [comment]
Closing for now.
