### ISSUE TITLE
Explain return Page() 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4606]
Per customer: 
OnGet of IndexModel does not return Page() but its page is still rendered and populated with a list of Movie (if any). So what does the return Page() mean? I am totally a newbie.

From https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page

Per Ryan

return Page() is the default behavior. This is meant for cases where you don’t do any control flow and just want to set a property or something.

If you are doing control flow, then your handler method will be declared to return IActionResult, so you need `return Page()` so that you have an action result to return. Return null also should work

-- end or ryan

So, for example, some methods have `return RedirectToPage("./Index")`

**Comment by sputier** [comment]
For my first contribution on ASP.NET Docs, I'll grab this one !

**Comment by Rick-Anderson** [comment]
@sputier  Great!

**Comment by rachelappel** [comment]
@sputier Are you still interested in writing this fix?

**Comment by sputier** [comment]
Hi @rachelappel, Sorry, I had a very busy end of year... I'll work on it this weekend.
