### ISSUE TITLE
Docs/aspnetcore/security/authorization/secure-data/samples/final/ not compiling under .net core 2.0

### ISSUE THREAD

**Issue by HappyMiner** [aspnet/Docs#4624]
Hi,

I am currently trying to learn Authorization in .net core 2.0 and I am also new to .net in general.

Today I found: 

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data

https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authorization/secure-data/samples/final

I tried to compile the "final example", but got several issues: 

Not compatible with core 2.0. Got 2 steps further through this: https://github.com/aspnet/Identity/issues/1176 and this
https://stackoverflow.com/a/45569379/7455830

Basically I ended up doing this to my final.csproj:

```
<RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
    <!-- <RuntimeFrameworkVersion>1.0.4</RuntimeFrameworkVersion> -->
    <!-- <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback> -->
    <!-- <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback> -->
```
Only the change to 2.0.0 allowed me to download the NuGet packages and finally resolve the issue that is mentioned here:

https://github.com/aspnet/Identity/issues/1176

Another problem (it might be a very easy one for an experienced developper) is this one:

ContactsController.cs(35,35): Error CS0023: Operator '!' cannot be applied to operand of type 'AuthorizationResult' (CS0023) (final)

I got 8 more errors like this. No idea how to solve this.

I am currently blocked at this level and cannot compile the example in order to continue my studies. Any body able to help?

I am running VS2017 on MAC.

It's pretty frustrating to see that most of the examples I found require one specific (often outdated) version and old code seems to be never compatible with newer versions. Not sure what to make of this.

Many thanks in advance!

**Comment by HappyMiner** [comment]
I have been struggling a couple of hours now trying to get this example to run. Found something that seems to be related to this issue and tried to set `!isAuthorizedRead.Succeeded`, since this at least returns the required bool: https://github.com/aspnet/Security/issues/1343

I have (blindly) changed all offenders to this and at least now the code compiles to a point where I can apparently initialise the related DB ("Exception: Use secrets manager to set SeedUserPW ").

If anybody gets stuck on the same: You can show server error messages through adding the following in Program.cs:

var host = new WebHostBuilder()
                **_.CaptureStartupErrors(true)_**
                .UseKestrel()
Next problems will probably arise once I try to initialise the DB as mentioned in the readme.

**Comment by isaac2004** [comment]
@scottaddie this is related to #4473 and #4082

**Comment by Rick-Anderson** [comment]
dup of  #4473
