### ISSUE TITLE
Update secrets doc - dnu commands install Microsoft.Framework.SecretManager FAILS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#463]
http://geeklearning.io/asp-net-5-0-install-secretmanager/ has all the details.
 @danroth27

**Comment by danroth27** [comment]
The latest doc should already have all that fixed for beta7:

http://docs.asp.net/en/latest/security/app-secrets.html

**Comment by Rick-Anderson** [comment]
Check the link that command doesn't work

**Comment by danroth27** [comment]
The doc already has the right package id and you don't need to explicitly specify the package source unless you've removed the official NuGet feed from your configured package sources.

**Comment by danroth27** [comment]
Checked it. It worked:

C:\Users\danroth27>dnu commands install Microsoft.Framework.SecretManager
Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-15532

  CACHE https://www.nuget.org/api/v2/
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Framework.SecretManager'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.Framework.SecretManager' 525ms
  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\Users\danroth27\.dnx\bin\packages\603a72bc1a184a64a308a497ee8a1fd6\project.json
Writing lock file C:\Users\danroth27\.dnx\bin\packages\603a72bc1a184a64a308a497ee8a1fd6\project.lock.json
Restore complete, 859ms elapsed

NuGet Config files used:
    C:\Users\danroth27\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.nuget.org/api/v2/
    c:\users\danroth27\desktop\feed
  CACHE https://www.nuget.org/api/v2/
Restoring packages for C:\Users\danroth27\.dnx\bin\packages\Microsoft.Framework.SecretManager\1.0.0-beta7\app\project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Linq'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Collections'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Diagnostics.Debug'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.IO'
...
  OK https://www.nuget.org/api/v2/package/System.Private.Uri/4.0.0 3700ms
  OK https://www.nuget.org/api/v2/package/System.Runtime/4.0.0 55867ms
Installing System.Console.4.0.0-beta-23225
Installing System.IO.FileSystem.Primitives.4.0.0
...
Installing System.Runtime.4.0.0
Installing System.Linq.Expressions.4.0.11-beta-23225
Installing System.Threading.4.0.11-beta-23225
Writing lock file C:\Users\daroth\.dnx\bin\packages\Microsoft.Framework.SecretManager\1.0.0-beta7\app\project.lock.json
Restore complete, 70717ms elapsed

NuGet Config files used:
    C:\Users\danroth27\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.nuget.org/api/v2/
    c:\users\danroth27\desktop\feed

Installed:
    52 package(s) to C:\Users\danroth27\.dnx\bin\packages
The following commands were installed: user-secret

C:\Users\danroth27>user-secret -h
 1.0.0-beta7-15516

Usage: user-secret [options] [command]

Options:
  -?|-h|--help  Show help information
  -v|--verbose  Verbose output

Commands:
  set     Sets the user secret to the specified value
  remove  Removes the specified user secret
  list    Lists all the application secrets
  clear   Deletes all the application secrets

Use "user-secret [command] --help" for more information about a command.
