### ISSUE TITLE
Arabic Docs

### ISSUE THREAD

**Issue by hishamco** [aspnet/Docs#4641]
Where's Arabic Docs? From few months ago I tweeted to take the initiative to translate the docs into Arabic, and someone from the team replied to me that he will will email me, from that time I didn't get any respond

Is there possibility to create an Arabic Docs?!! so I can start to translate to

/cc @Rick-Anderson @scottaddie

**Comment by Rick-Anderson** [comment]
@nokura please reply

**Comment by Rick-Anderson** [comment]
@Sara-Nicolini can you respond?

**Comment by Rick-Anderson** [comment]
@hishamco sorry for the delay. I'll try to get a response in the next week.

**Comment by hishamco** [comment]
Ok, thanks

**Comment by Rick-Anderson** [comment]
@hishamco  sorry to let you know, according to @Sara-Nicolini 

>we don’t have Arabic and we are not planning to localize Arabic for any our content.

**Comment by hishamco** [comment]
Why is there any reasons? I saw there are many languages, an Arabic is one of the languages that have a big community especially in Middle East, Asia and Africa
