### ISSUE TITLE
fix links

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4649]
Some [build reports](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r) list these.
Fix the following links:

Illegal link: `[dependency injection](../../fundamentals/dependency-injection.md#fundamentals-dependency-injection)` -- missing bookmark. The file fundamentals/dependency-injection.md doesn't contain a bookmark named fundamentals-dependency-injection. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 19 - 10/13/2017 12:54:43
-- - -- - -- - --
- [ ] aspnetcore/security/authorization/introduction.md - Illegal link: `[role](roles.md#security-authorization-role-based)` -- missing bookmark. The file security/authorization/roles.md doesn't contain a bookmark named security-authorization-role-based. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 25 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/introduction.md - Illegal link: `[rich policy based](policies.md#security-authorization-policies-based)` -- missing bookmark. The file security/authorization/policies.md doesn't contain a bookmark named security-authorization-policies-based. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 25 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/limitingidentitybyscheme.md - Illegal link: `[policy](xref:security/authorization/policies#security-authorization-policies-based)` -- missing bookmark. The file security/authorization/policies.md doesn't contain a bookmark named security-authorization-policies-based. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 120 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/policies.md - Illegal link: `[role authorization](roles.md#security-authorization-role-based)` -- missing bookmark. The file security/authorization/roles.md doesn't contain a bookmark named security-authorization-role-based. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 19 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/policies.md - Illegal link: `[claims authorization](claims.md#security-authorization-claims-based)` -- missing bookmark. The file security/authorization/claims.md doesn't contain a bookmark named security-authorization-claims-based. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 19 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/resourcebased.md - Illegal link: `[dependency injection](../../fundamentals/dependency-injection.md#fundamentals-dependency-injection)` -- missing bookmark. The file fundamentals/dependency-injection.md doesn't contain a bookmark named fundamentals-dependency-injection. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 23 - 10/13/2017 12:54:43
- [x] aspnetcore/security/authorization/resourcebased.md - Illegal link: `[writing a plain requirements handler](policies.md#security-authorization-policies-based-authorization-handler)` -- missing bookmark. The file security/authorization/policies.md doesn't contain a bookmark named security-authorization-policies-based-authorization-handler. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 75 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/views.md - Illegal link: `[dependency injection](../../fundamentals/dependency-injection.md#fundamentals-dependency-injection)` -- missing bookmark. The file fundamentals/dependency-injection.md doesn't contain a bookmark named fundamentals-dependency-injection. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 19 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/views.md - Illegal link: `[resource based authorization](resourcebased.md#security-authorization-resource-based-imperative)` -- missing bookmark. The file security/authorization/resourcebased.md doesn't contain a bookmark named security-authorization-resource-based-imperative. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 21 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/authorization/views.md - Illegal link: `[resource based authorization](resourcebased.md#security-authorization-resource-based-imperative)` -- missing bookmark. The file security/authorization/resourcebased.md doesn't contain a bookmark named security-authorization-resource-based-imperative. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 30 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/cross-site-scripting.md - Illegal link: `[dependency injection](../fundamentals/dependency-injection.md#fundamentals-dependency-injection)` -- missing bookmark. The file fundamentals/dependency-injection.md doesn't contain a bookmark named fundamentals-dependency-injection. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 145 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/compatibility/replacing-machinekey.md - Illegal link: `[default configuration](../configuration/default-settings.md#data-protection-default-settings)` -- missing bookmark. The file security/data-protection/configuration/default-settings.md doesn't contain a bookmark named data-protection-default-settings. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 26 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/default-settings.md - Illegal link: `[key management](../implementation/key-management.md#data-protection-implementation-key-management-expiration)` -- missing bookmark. The file security/data-protection/implementation/key-management.md doesn't contain a bookmark named data-protection-implementation-key-management-expiration. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 38 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/default-settings.md - Illegal link: `[subkey derivation](../implementation/subkeyderivation.md#data-protection-implementation-subkey-derivation-aad)` -- missing bookmark. The file security/data-protection/implementation/subkeyderivation.md doesn't contain a bookmark named data-protection-implementation-subkey-derivation-aad. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 42 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/machine-wide-policy.md - Illegal link: `[Specifying custom Windows CNG algorithms](overview.md#data-protection-changing-algorithms-cng)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named data-protection-changing-algorithms-cng. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 44 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/machine-wide-policy.md - Illegal link: `[Specifying custom Windows CNG algorithms](overview.md#data-protection-changing-algorithms-cng)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named data-protection-changing-algorithms-cng. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 56 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/machine-wide-policy.md - Illegal link: `[Specifying custom managed algorithms](overview.md#data-protection-changing-algorithms-custom-managed)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named data-protection-changing-algorithms-custom-managed. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 64 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/non-di-scenarios.md - Illegal link: `[isolate applications](overview.md#data-protection-configuration-per-app-isolation)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named data-protection-configuration-per-app-isolation. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 28 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/non-di-scenarios.md - Illegal link: `[optional configuration callback](overview.md#data-protection-configuration-callback)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named data-protection-configuration-callback. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 30 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/non-di-scenarios.md - Illegal link: `[ProtectKeysWithCertificate](overview.md#configuring-x509-certificate)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named configuring-x509-certificate. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 30 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/overview.md - Illegal link: `[default settings](default-settings.md#data-protection-default-settings)` -- missing bookmark. The file security/data-protection/configuration/default-settings.md doesn't contain a bookmark named data-protection-default-settings. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 19 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/configuration/overview.md - Illegal link: `[key encryption at rest](../implementation/key-encryption-at-rest.md#data-protection-implementation-key-encryption-at-rest)` -- missing bookmark. The file security/data-protection/implementation/key-encryption-at-rest.md doesn't contain a bookmark named data-protection-implementation-key-encryption-at-rest. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 49 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/consumer-apis/purpose-strings-multitenancy.md - Illegal link: `[Contoso.Messaging.SecureMessage](purpose-strings.md#data-protection-contoso-purpose)` -- missing bookmark. The file security/data-protection/consumer-apis/purpose-strings.md doesn't contain a bookmark named data-protection-contoso-purpose. - Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html.ValidateBookmark - 19 - 10/13/2017 12:54:43
- [ ] aspnetcore/security/data-protection/consumer-apis/purpose-strings-multitenancy.md - Illegal link: `[isolate individual applications](../configuration/overview.md#data-protection-configuration-per-app-isolation)` -- missing bookmark. The file security/data-protection/configuration/overview.md doesn't contain a bookmark named data-protection-configuration-per-app-isolation.

**Comment by spottedmahn** [comment]
`aspnetcore/security/authorization/claims.md` fixed via PR #4660.  FYI, that item is in the build report but not in the list above.

**Comment by spottedmahn** [comment]
`aspnetcore/security/authorization/limitingidentitybyscheme.md` fixed via PR #4661

**Comment by spottedmahn** [comment]
the 2 issues w/ `aspnetcore/security/authorization/introduction.md` are fixed via PR #4662

**Comment by Rick-Anderson** [comment]
@scottaddie  should we close this issue? It seems many of the bad link reports are incorrect. Some are correct and have been fixed by @spottedmahn 

I checked a bunch in #4651 and they are not bad links. DocFX should tell us all the bad links.  cc @rachelappel  for her #4648 issue

**Comment by scottaddie** [comment]
@Rick-Anderson Let's close it. I've been checking all of my changes locally in DocFx before pushing.

**Comment by rachelappel** [comment]
@Rick-Anderson +1 to Close. I think it was something off in the build process, or that with Git. The errors all went away after a few more PRs opened and builds happened. Plus it doesn't show up in DocFX like Scott's.
