### ISSUE TITLE
Using Commands -pre not needed

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#465]
For example, to install the SecretManager package from the Package Manager Console, enter the following:

Install-Package Microsoft.Framework.SecretManager -Pre

**Comment by danroth27** [comment]
The problem is in https://docs.asp.net/en/latest/dnx/commands.html#using-commands-in-your-project.

We also need to update the package name for the Secret Manager tool for beta8.

**Comment by danroth27** [comment]
The DNX docs will be going away with the move to the new .NET CLI.
