### ISSUE TITLE
Mention the opt-in support for binding props OnGet in RP topic?

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#4655]
In the [RP topic](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages), non-binding props on GET requests is mentioned in passing ...

> Razor Pages, by default, bind properties only with non-GET verbs.

It could add the opt-in property requirement for binding on GET requests:

```csharp
[BindProperty(SupportsGet=true)]
```

... and then mention that there are security considerations for doing so.

The default behavior was confusing for a dev who needed prop binding on GET: https://youtu.be/p7iHB9V-KVU?t=54m27s (Standup 9/5)

**Comment by Rick-Anderson** [comment]
@guardrex  closing. We don't want to encourage bad behavior. Dev's who are smart enough to use this feature correctly will figure out how to do it.
