### ISSUE TITLE
ASP.NET Core 2.0 & SignalR Core

### ISSUE THREAD

**Issue by githubshubham90** [aspnet/Docs#4659]
Hi,

I have created a sample application with SignalR and MVC Core. It is working fine. But I am unable to host this on the production. I have created signalr server using below code:
`class Program
    {
        static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseUrls("http://localhost:6000")              
                .Build();
    }`
and startup.cs file is:
`public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("hub",
                    policy => policy.AllowAnyOrigin()
                                    .AllowAnyHeader()
                                    .AllowAnyMethod());
            });

            services.AddSignalR(); // <-- SignalR
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseDeveloperExceptionPage();
            app.UseCors("hub");

            app.UseSignalR(routes =>  // <-- SignalR
            {
                routes.MapHub<NotificationHub>("NotificationHub");
            });
        }
    }`
and for client i use below code:
`let hubUrl = 'http://localhost:5000/NotificationHub';
    let hubUrl = 'http://core.imcredentialed.com/NotificationHub';
    let httpConnection = new signalR.HttpConnection(hubUrl);
    let hubConnection = new signalR.HubConnection(httpConnection);`

This works at my local environment, But for production is not working I have used below code for the production:
`public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseUrls("http://example.com:5001/")            
                .Build();`
onlyURL i have changed for production. 
Is there any other change need to be done, Please suggest. 
If any other process to host signalr server for production please let me know. 
Its very urgent.

Thanks...!!!

**Comment by BrennanConroy** [comment]
SignalR is not recommended for production use. We've only released Alpah2 so far.

As far as it not working in production, are you using Azure Web Apps? Websockets is disabled by default in that environment. Try enabling websockets in the settings.

And this issue does not belong in docs.

**Comment by githubshubham90** [comment]
I am not using Azure Web Apps. 
So if SignalR is not recommended for production use, how can I achieve real time things in MVC Core 2.0. I have also tried to use Web Socket for this, but it's not working.
Please help me to implement real time things in MVC Core 2.0.
