### ISSUE TITLE
Build Report JS Error: File not found: /report/Scripts/ExportReport.js

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4667]
[On this build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C13%5C6a0d29ae-bb37-09f1-c55a-4cfa862c6784%5CPullRequest%5C201710131248087361-4562%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GbG0qgcJNtJMXYbbzHZqcp2BJNdAKtUYmbwoSscw5IY%3D&st=2017-10-13T12%3A50%3A41Z&se=2017-11-13T12%3A55%3A41Z&sp=r), there is a JavaScript error: File not found: /report/Scripts/ExportReport.js

![image](https://user-images.githubusercontent.com/14079228/32179880-de61ea0e-bd66-11e7-9581-cd2e2bcdf317.png)

**Comment by scottaddie** [comment]
Internal bug (# 1115805) filed in VSTS.

**Comment by scottaddie** [comment]
This is fixed.

**Comment by spottedmahn** [comment]
sweet!  thanks @scottaddie
