### ISSUE TITLE
Can't Checkout Repo - Filename too long

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4674]
I've tried cloning the repo using the GitHub desktop app but I'm receiving the following error:

>'aspnet/mvc/overview/older-versions/using-the-html5-and-jquery-ui-datepicker-popup-calendar-with-aspnet-mvc/using-the-html5-and-jquery-ui-datepicker-popup-calendar-with-aspnet-mvc-part-1/_static': Filename too long warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Has anyone else already overcome this issue?

**Comment by isaac2004** [comment]
@spottedmahn Do you have same issue with Git Bash?

**Comment by scottaddie** [comment]
@spottedmahn This sounds like a Windows max path issue. Make sure the path to which you're cloning this repo on your machine is very short. For example, I clone this repo to C:\working_folder\. If that still doesn't fix the problem, then we should shorten the path to that file (e.g., shorten a directory name).

**Comment by spottedmahn** [comment]
Hi @isaac2004 - I'm not as familiar w/ the CLI but I think I did it properly:

>mdepouw@CEI-00662 MINGW64 ~/source/repos/GitHub/spottedmahn/docs (master)
$ git checkout
error: The following untracked working tree files would be overwritten by checkout:
        .gitattributes
        .github/ISSUE_TEMPLATE.md
        .github/PULL_REQUEST_TEMPLATE.md
        .gitignore
        .openpublishing.build.ps1
        .openpublishing.publish.config.json
        .openpublishing.redirection.json
        CONTRIBUTING.md
        LICENSE
        LICENSE-CODE
        README.md
        ThirdPartyNotices
        aspnet/ajax/cdn/cdnajax35.md
        aspnet/ajax/cdn/cdnajax4.md
        aspnet/ajax/cdn/cdnajax451.md
        aspnet/ajax/cdn/cdnajax452.md
        aspnet/ajax/cdn/index.md
        aspnet/ajax/cdn/jquery-cycle/cdnjquerycycle288.md
        aspnet/ajax/cdn/jquery-cycle/cdnjquerycycle294.md
        aspnet/ajax/cdn/jquery-cycle/cdnjquerycycle299.md
        aspnet/ajax/cdn/jquery-cycle/index.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables104.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables105.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables182.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables190.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables191.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables192.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables193.md
        aspnet/ajax/cdn/jquery-datatables/cdnjquerydatatables194.md
        aspnet/ajax/cdn/jquery-datatables/index.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile10.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile101.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile10b3.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile10rc1.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile10rc2.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile110.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile110rc2.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile111.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile112.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile120.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile130.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile131.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile132.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile140.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile141.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile142.md
        aspnet/ajax/cdn/jquery-mobile/cdnjquerymobile145.md
        aspnet/ajax/cdn/jquery-mobile/index.md
        aspnet/ajax/cdn/jquery-templates/cdnjquerytemplatesbeta1.md
        aspnet/ajax/cdn/jquery-templates/index.md
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100.md
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image1.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image10.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image11.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image12.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image13.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image14.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image15.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image16.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image17.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image18.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image19.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image2.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image20.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image21.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image22.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image23.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image24.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image3.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image4.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image5.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image6.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image7.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image8.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1100/_static/image9.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1101.md
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1101/_static/image1.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1101/_static/image10.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1101/_static/image11.png
        aspnet/ajax/cdn/jquery-ui/cdnjqueryui1101/_static/imag
Aborting

**Comment by spottedmahn** [comment]
Hi @scottaddie - agreed.  I though long filenames was (finally) [addressed in Win10](https://lifehacker.com/windows-10-allows-file-names-longer-than-260-characters-1785201032)?  I changed my registry entry and it still fails (I haven't rebooted though).

You're right, a folder on the root of `C` will probably fix it but I was hoping for a more modern solution 😄

**Comment by scottaddie** [comment]
@spottedmahn I'm not familiar with the GitHub desktop app. I use the command line (Cmder with posh-git) and had no issues cloning.

**Comment by spottedmahn** [comment]
I kept looking and I notice I made a mistake.  After cloning it, I see a subdir `Docs`.

>mdepouw@CEI-00662 MINGW64 ~/source/repos/GitHub/spottedmahn/docs-4/Docs (master)
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

>nothing to commit, working tree clean

**Executive Summary**
Cloning from GitBash worked with a deep folder structure but the GitHub desktop client didn't.

**Comment by scottaddie** [comment]
@spottedmahn Glad you figured it out. Thanks for the update.
