### ISSUE TITLE
This overload appears to be missing in .NET Core 2.0, at least in a vanilla console app

### ISSUE THREAD

**Issue by gzak** [aspnet/Docs#4677]
https://github.com/aspnet/Docs/blob/cd0f36ce9f3be0513692415d2ab1eeecfc48c598/aspnetcore/fundamentals/configuration/sample/IOptionsSnapshot2/Startup.cs#L73

I can't bind a poco options class to a subsection, i have to use the lambda syntax with a call to .Bind(), like so:

    serviceCollection.Configure<MyPoco>(opts => config.GetSection("MyPoco").Bind(opts));

But that's obviously more verbose, plus I have to add a dependency on the Binder package. Am I just missing something or is that just the way it is now?

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/Configuration/issues/748.
