### ISSUE TITLE
Update for MVC Beta 7?

### ISSUE THREAD

**Issue by pacific202** [aspnet/Docs#468]
Could we please get this updated for MVC Beta 7?

**Comment by Rick-Anderson** [comment]
What did you wanted updated? We're working on Beta 8 now

**Comment by pacific202** [comment]
Including all of the using statements and explaining how DI maps to the class maps to the json file would be nice.  I think it would also be useful to start with the high-level process.

**Comment by Rick-Anderson** [comment]
"Including all of the using statements" where?
We hope to get the DI article out soon.

**Comment by pacific202** [comment]
Every code example is missing its references to external libraries, except one where there is a comment that references a library that was changed in Beta 7 to Microsoft.Framework.Configuration.

// assumes using Microsoft.Framework.ConfigurationModel is specified

**Comment by Rick-Anderson** [comment]
I think we've been under the assumption that by using Visual Studio 2015 it's trivial to get the using statements, but that might be a bad assumption (if you're not using VS15 for example). The code examples are on GitHub with the document, so you can look at the complete sample - does that solve your problem? Are you developing outside VS?

**Comment by pacific202** [comment]
I am using VS2015, but as part of an educational experience it's good to know where everything is coming from.  That also helps when you're looking up the original API reference, as it removes ambiguitiy.

Many of us are coming over to C#/.Net from Java or other languages thanks to the power of Azure.  Adding something as simple as the libraries to reference is going to greatly help us make the migration quicker.

**Comment by Rick-Anderson** [comment]
My preference is to not use using statements, then you make the API assembly explicit. I've been moving in that direction.

**Comment by pacific202** [comment]
I'm fine with that, so long as the reference isn't ambiguous.
