### ISSUE TITLE
What are these <a name=blah> tags all about?

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#4686]
I'm running the docs locally and I'm seeing:

![image](https://user-images.githubusercontent.com/14079228/32235429-d7e1909c-be35-11e7-8b0f-ccc57e3a1b9d.png)

----

When I look [at the production page](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies) I don't see anything that corresponds to it.  What is the purpose of these tags?  Why do they show up on local builds?

**Comment by spottedmahn** [comment]
nvm, I rebased and they went away.

**Comment by scottaddie** [comment]
For future reference, if the name attribute doesn't use quotes, you'll see this behavior. We recently fixed all of them, which is why you don't see them after rebasing.
