### ISSUE TITLE
RazorPages is ambiguous - rename app MyRazorPages

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4695]
[Customer finds](https://email.livefyre.com/wf/click?upn=oZtfHoAwEgZg8ZniQXSTq5lYbS7d9xuTHMWGktPja-2BHyG4BOnRR2sabmhFhG8bLR1TZB668UkRDbzx4vRPF-2FKYQfPlI9ArodAxEFFWQrbHpAumhKRWLoE6Yfh2dVPMqwfKhMx4mZBUBM2wBUH5duuA-3D-3D_QWzJqCyY-2Fktk78Jhok58QwALCX15NZTQN-2Fr1lFKB1qHepkxd4rxgVxvD1TgihhSkLR-2BCMBMfO2rpeOqw05LMTKHfwLTzn9GhX-2BKvtwHDLwj7dJV8hzRFpZ3G7hH3b-2FdegzYTKGkr9yw6xBytg-2FLITQ3fGGyNCUzPc-2FF5zVcVU0wOzqyDaHwBAeD0BnMEx89qEN5LrEjFizndMflsOSHQng-3D-3D) app name `RazorPages` ambiguous

```
@page
@using RazorPages      @* <-- *@
@model IndexModel2

<h2>Separate page model</h2>
<p>
    @Model.Message
</p>
```

```
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;

namespace RazorPages   // <--
{
    public class IndexModel2 : PageModel
    {
        public string Message { get; private set; } = "PageModel in C#";

        public void OnGet()
        {
            Message += $" Server time is { DateTime.Now }";
        }
    }
}
```

I agree with customer. Should we rename it one of the following?

*  MyRazorPages
*  MyRazorPagesWebApp
* MyRP_WebAPP
* WebApp1

cc @danroth27  @scottaddie

**Comment by guardrex** [comment]
RazorPagesSample?

**Comment by scottaddie** [comment]
I vote for RazorPagesSample.

**Comment by isaac2004** [comment]
@scottaddie @Rick-Anderson can this be closed since it was merged a bit ago?

**Comment by Rick-Anderson** [comment]
@isaac2004  yes, thanks
