### ISSUE TITLE
Need to reset doc.microsoft.com password

### ISSUE THREAD

**Issue by ebattalio** [aspnet/Docs#4714]
I cannot log in to post a comment on docs.microsoft.com. I asked for a password reset but never got an email.

The main problem I have is I follow the instructions at https://docs.microsoft.com/en-us/aspnet/core/publishing/visual-studio-tools-for-docker and am getting a nodejs misisng exception. I am using the 10/21/2017 update to VS2017. I want to post a question to that article.

Thanks,
Eric B

**Comment by Rick-Anderson** [comment]
@ebattalio  LiveFyre controlls that, we don't. You can post the question here.
