### ISSUE TITLE
Document using IPolicyEvaluator in 2.0

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#4748]
Add a section to the [Resource-based authorization](https://docs.microsoft.com/aspnet/core/security/authorization/resourcebased) doc explaining when and how to use `IPolicyEvaluator` in 2.0 apps. The doc currently assumes authentication has run and set the `User` property. `IPolicyEvaluator` should be used instead of `IAuthorizationService` when doing authentication in those samples.

Related issues:
- https://github.com/aspnet/Security/issues/1343
- https://github.com/aspnet/Security/issues/1348
- https://github.com/blowdart/AspNetAuthorizationWorkshop/issues/23

**Comment by Rick-Anderson** [comment]
Moved to #10384
