### ISSUE TITLE
Logo in top-left of docs.asp.net is low-res and thus looks fuzzy on hi-dpi displays

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Docs#475]
Looking at that logo makes me sad on my Surface Pro 3 screen, my MacBook Pro screen, and my shiny new 4K monitor at home. Can we get a nice hi-res version pls? On live.asp.net we use an SVG file for the MS logo. Perhaps we can get an SVG version of the ASP.NET logo created too?

**Comment by shirhatti** [comment]
Fixed in e40983f009b70e32dff9f2e7d99795e40a1c318d
