### ISSUE TITLE
Reference jQuery Validate Documentation

### ISSUE THREAD

**Issue by Rabadash8820** [aspnet/Docs#4750]
The jQuery Validate documentation on the [remote method](https://jqueryvalidation.org/remote-method/) gives very specific details on what values the serverside resource should return.  The ASP.NET Core docs currently should mention those details or at least provide a link to the jQuery Validate documentation.

## Suggested Reviewers:
@rachelappel 
@Rick-Anderson 
@isaac2004 
@guardrex 
@v-anpasi

**Comment by rachelappel** [comment]
@Rabadash8820 Would you post the specific ASP.NET docs you are referencing?
