### ISSUE TITLE
Community provided article on an example of how to use Grid Control in ASP.NET

### ISSUE THREAD

**Issue by terrysheng** [aspnet/Docs#4756]
Hi all, attached please find an article submitted by an Taiwan MVP a while back which was published on a local section of the MSDN library and had higher views that other articles, meaning customers were looking at it. It provides a practical example on using Grid Control and may supplement this content.

It has been reverse-machine-translated to provide you with a readable English version - if you think it has some merit and could find a place in the official documentation, please do let me know and we can work with the author to have it amended as necessary.

This also serves as a test, to see if it's efficient to use this process for such submissions/proposals (that's why I'm using the private repo instead of the public one)
thanks to let me know your thoughts

[ZH-TW Practical Examples in How to Use Grid Control in ASP NET.zip](https://github.com/aspnet/Docs/files/1456648/ZH-TW.Practical.Examples.in.How.to.Use.Grid.Control.in.ASP.NET.zip)

**Comment by Rick-Anderson** [comment]
cc @danroth27 @rachelappel @scottaddie  any thoughts?

**Comment by scottaddie** [comment]
I'm in favor of including the article, perhaps in the following section:
https://docs.microsoft.com/aspnet/web-forms/overview/presenting-and-managing-data/model-binding/

Is there an accompanying sample app?

**Comment by terrysheng** [comment]
@scottaddie thanks so much for your comment. unfortunately, there is no sample app.

**Comment by Rick-Anderson** [comment]
@terrysheng  unfortunately we don't have the resources to add it to our docs.

**Comment by terrysheng** [comment]
[aspnetGridDemo.zip](https://github.com/aspnet/Docs/files/1499747/aspnetGridDemo.zip)

@scottaddie and @Rick-Anderson 
Thanks so much for your update. I have just checked with the Taiwan MVP, and he has actually a sample code for this, and I have attached it here.
However, I notice Rick's comment regarding the resource limit.
Please feel free to let me (I am the Regional PM from APEX International) know if you have resources to support the case or similar cases (community produced content) in the future. And I will do my best to support you!
Have a nice Thanksgiving!
Terry

**Comment by csharpfritz** [comment]
This content would fit in very nicely in the TechNet wiki, which samples like this one would fit in perfectly:  https://social.technet.microsoft.com/wiki/tags/ASP-NET/default.aspx
