### ISSUE TITLE
Update ANCM doc to talk about why we don't proxy to Kestrel via HTTPS

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#4759]
We've had a couple of customers complain about the fact that ANCM doesn't use HTTPS to proxy to backend Kestrel via HTTPS.

We do this a performance optimization since the OS has some optimization on loopback traffic to ensure it doesn't even hit the network interface. We do however guarantee integrity of the requests by passing a token via an environment variable to the backend which it then expects as a header on every request.

https://github.com/aspnet/IISIntegration/blob/cc31406913ae349a6f69acef65be65da91086b39/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L70-L75

There isn't any security concern here and we've adequately done our threat modelling to that regard.

Can we capture this in the documentation to help unblock customers who need this as an official statement from us?

cc @blowdart

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie If approved, I'll drop this in ... it'll only take a couple of minutes.

**Comment by Rick-Anderson** [comment]
@blowdart  can you bless this change so @guardrex can update the doc?

**Comment by blowdart** [comment]
Yes yes :) Although is it actually an environment variable @shirhatti ? I thought it was a command line parameter.

Also I'd say it's NOT "guarantee integrity", it's only proving that the requests came from ANCM, nothing more. Integrity is an overloaded term when it comes to security.

**Comment by guardrex** [comment]
It's a header:

https://github.com/aspnet/AspNetCoreModule/blob/c315b27ad9f384749aab975f5f698f1929dec7fb/src/AspNetCore/Src/forwardinghandler.cxx#L701
https://github.com/aspnet/IISIntegration/blob/cc31406913ae349a6f69acef65be65da91086b39/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L70

> I'd say it's NOT "guarantee integrity", it's only proving that the requests came from ANCM, nothing more.

:+1:

**Comment by shirhatti** [comment]
@blowdart  It comes from an [environment variable](https://github.com/aspnet/IISIntegration/blob/552163ab77c269bc1f6c22bbf2b7560e0677c421/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L75).

**Comment by blowdart** [comment]
Gosh you weirdos :)

**Comment by guardrex** [comment]
I see ... pairing token in header from env var. Tricky!

**Comment by blowdart** [comment]
This is done so an attacker on the local LAN can't port scan, discover Kestrel, then send random stuff, including Windows Identity tokens.
