### ISSUE TITLE
Update getting started on *nix for acquiring libicucore.dylib

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#480]
In `beta8` we require `libicu-dev` on Linux  / `icu4c`on Darwin

We should update the getting started Docs in beta8 to reflect that.

**Comment by Rick-Anderson** [comment]
http://docs.asp.net/en/latest/getting-started/installing-on-linux.html
@danroth27  this looks like a critical update needed

**Comment by danroth27** [comment]
already done on the beta8 branch: http://docs.asp.net/en/1.0.0-beta8/getting-started/installing-on-linux.html

We'll merge this over to master after we ship beta8.
