### ISSUE TITLE
I couldn't download the sample

### ISSUE THREAD

**Issue by samget99** [aspnet/Docs#4816]
## General

We use issues to drive the discussion for changes to
existing topics and the creation of new topics.
This template offers some suggestions to consider
when creating an issue.

## Issues with Existing Topics

If the issue is a simple typo or similar correction, just submit a PR.
Otherwise, let us know what's wrong or what we should improve. Include a
link to the topic.

## Requests for new Topics

1. Write a **short** paragraph describing what the topic will cover.

2. Write an outline of the proposed topic contents.

3. Where would you put the topic in the Table of Contents.

4. If you know who should review the issue, notify them by including @githubID in the issue description.

**Comment by scottaddie** [comment]
@samget99 Please include a link to the doc containing the sample.

**Comment by Rick-Anderson** [comment]
What sample? See https://docs.microsoft.com/en-us/aspnet/core/tutorials/index#how-to-download-a-sample
