### ISSUE TITLE
CSAT Host ASP.NET Core on Windows with IIS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4821]
[URL](https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x)

Plan:
- [ ]  UE pass
- [ ] split off the Troubleshooting into a new standalone topic

**Comment by guardrex** [comment]
Since the topic hasn't changed much but the score has been steadily falling from 70-75 range, have you been able to draw a conclusion as to why the score has fallen so much?

**Comment by Rick-Anderson** [comment]
I agree with your assessment when you wrote:

>The topic hasn't hardly changed. The audience might be changing as a more diverse group of devs and devs with no Core experience are coming in. ... Anyway ... splitting off the Troubleshooting into a new standalone topic might be helpful.

**Comment by guardrex** [comment]
Xref https://github.com/aspnet/Docs/issues/4685 ... if diagnosing startup errors can be addressed (the IIS portion of that issue) at the same time.
