### ISSUE TITLE
first-web-api sample adds another item on every refresh

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#483]
Probably the initialization logic for the collection of items should be moved somewhere else, or the repo should check to see if there are any items before adding new ones. The problem is on line 13 of /Models/TodoRepository.cs. @Rick-Anderson @MikeWasson

**Comment by ardalis** [comment]
Possible fix:
        [HttpGet]
        public IEnumerable<TodoItem> GetAll()
        {
            EnsureItems();
            return TodoItems.GetAll();
        }

        private void EnsureItems()
        {
            if (!TodoItems.GetAll().Any())
            {
                for (int i = 1; i < 11; i++)
                {
                    TodoItems.Add(new TodoItem() { Name="Item " + i});
                }
            }
        }

**Comment by MikeWasson** [comment]
Good catch. It's because I changed the repository lifetime to "scoped". I could just add the item when I initialize `_todos` (or in a static ctor)

This is what I get for wanting to keep EF out of the sample :smile_cat:

**Comment by danroth27** [comment]
Fixed.
