### ISSUE TITLE
Document using Azure AD B2C with an ASP.NET Core Web App

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4835]
We need to add a doc that goes through setting up an ASP.NET Core Web App to use Azure AD B2C for authentication. This doc should be linked to from the Change Authentication dialog in VS.

**Comment by CamSoper** [comment]
@danroth27 Just to verify - This is only to authenticate a web app, right?  We're not passing the token to Web API on the backend, like https://github.com/aspnet/Docs/issues/4836?   Or should this be one topic that does both?

**Comment by danroth27** [comment]
I think these should be separate topics.

**Comment by CamSoper** [comment]
## Proposed Outline

![image](https://user-images.githubusercontent.com/137648/34622680-abc29e72-f213-11e7-9820-9ed59b2f7a24.png)

**Comment by isaac2004** [comment]
request to close this and #3772

**Comment by Rick-Anderson** [comment]
@CamSoper  closer per your azure AD work. Reopen if needed.
