### ISSUE TITLE
Document using Azure AD B2C with an ASP.NET Core Web API

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4836]
We need to add a doc that goes through setting up an ASP.NET Core Web App to use Azure AD B2C for authentication. This doc should be linked to from the Change Authentication dialog in VS and should show how to acquire a token for the Web API using MSAL and then consume the Web API using the token.

**Comment by Rick-Anderson** [comment]
@danroth27  if you can get someone to write a sample app I'll get this scheduled.

**Comment by danroth27** [comment]
The sample should be based on the File->New Project experience, but there is an existing working sample here: https://azure.microsoft.com/en-us/resources/samples/active-directory-b2c-dotnetcore-webapi/

**Comment by Rick-Anderson** [comment]
@CamSoper  can you take this?

**Comment by CamSoper** [comment]
@Rick-Anderson On it.

**Comment by CamSoper** [comment]
@danroth27 For clarification, the document should show an ASP.NET web application consuming a backend Web API using a bearer token, right?  Basically, the same as [this sample app](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi)?

**Comment by danroth27** [comment]
Yup, that sounds good. The focus should be on securing the Web API using B2C, but you need to have some sort of client to complete the scenario, and using a web app is fine. There may be some overlap with https://github.com/aspnet/Docs/issues/4835 then that we should manage

Do we already have content for other types of clients, like native mobile apps and browser apps?

**Comment by CamSoper** [comment]
Not that I'm aware of, but then, I really haven't looked.  I spent all my time today running through the B2C samples.  I'll look for native mobile and browser docs tomorrow.

**Comment by CamSoper** [comment]
Okay, @danroth27 - It appears that the content we have for native clients is limited to samples with walkthroughs.  Start [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oauth-code) and walk down the TOC on the left.  They're all GitHub links, with the exception of an [ASP.NET (Framework, not Core) article](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-api-dotnet) and a [web app to web API article}(https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-api-dotnet).  Basically, the two scenarios we're covering, except ours are for Core, and ours will start with File>New Project (the existing articles rely on samples).

I mean, the "download this sample and follow this walkthrough" approach makes some sense when you consider that there's a lot of code involved.  Shall I move forward with topics that use File>New Project as you originally asked?

**Comment by CamSoper** [comment]
## Proposed outline

![image](https://user-images.githubusercontent.com/137648/34622417-cc0e799a-f212-11e7-907a-dd08b3b98443.png)

**Comment by CamSoper** [comment]
## Proposed Outline

![image](https://user-images.githubusercontent.com/137648/34622555-36e29f4e-f213-11e7-88ec-e3bacc6188ad.png)

**Comment by CamSoper** [comment]
## Proposed Outline

![image](https://user-images.githubusercontent.com/137648/34622604-5b1eb19a-f213-11e7-9a21-1c21c314d5cc.png)

**Comment by CamSoper** [comment]
@danroth27 On further reflection...  Do we need a client?  We can demonstrate it works by using the "Run Now" button on the signup/signin policy in the B2C settings.  That'll redirect to the reply-to URL with the bearer token on the URL.  We could get the reader to copy that token (or make a quick Razor page to display it) and then just use curl or Postman to make the Web API request with the Authorization header.  That would simplify it greatly.

Thoughts?
