### ISSUE TITLE
Configuring Facebook authentication - high PV low CSAT

### ISSUE THREAD

**Issue by wadepickett** [aspnet/Docs#4843]
# Configuring Facebook authentication - high PV low CSAT

This topic: [Configuring Facebook authentication](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?tabs=aspnetcore2x)

Requires some further inspection.  Relatively high traffic but low ratings.   Developers have noted some issues in the topic feedback recently that have gone unanswered.   You have to work through a previous topic before you get to this one so folks may also have a justifiably low tolerance for any perceived issues or complexity by the time they get through this one.

**Comment by Rick-Anderson** [comment]
fixed in  #4980
