### ISSUE TITLE
Host ASP.NET Core on Windows with IIS - high PV low CSAT - Example issues

### ISSUE THREAD

**Issue by wadepickett** [aspnet/Docs#4844]
## Host ASP.NET Core on Windows with IIS - high PV low CSAT - Example issues

This topic: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x

See customer feedback issues.  Steps/examples are not working or it is not clear what steps they are missing.

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/4821
