### ISSUE TITLE
Introduction to ASP.NET Core - high pv and low CSAT

### ISSUE THREAD

**Issue by wadepickett** [aspnet/Docs#4845]
##Introduction to ASP.NET Core - High PV low CSAT
This topic:  [Introduction to ASP.NET Core ](https://docs.microsoft.com/en-us/aspnet/core/)

Requires further inspection:  Very high traffic, low ratings.  Please read through customer complaints under voting data in SkyEye or SkyRay.

**Comment by wadepickett** [comment]
This topic could use some starting steps.  It is the introduction, it does not point you to getting started topics as noted in recent customer feedback.

**Comment by Rick-Anderson** [comment]
@scottaddie  can you update
ASP.NET Core ships entirely as NuGet packages. This allows you to optimize your app to include just the NuGet packages you need. The benefits of a smaller app surface area include tighter security, reduced servicing, and improved performance.

Add a link to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage

I think that's all we can do for now. It's got market-speak in it so it will never get great reviews.
