### ISSUE TITLE
Start MVC intro PDF 8-23-17.pdf content cannot be displayed in PDF readers

### ISSUE THREAD

**Issue by kmav** [aspnet/Docs#4867]
Hello,
Thank you for your great work!

When I download the 8-23-17.pdf (Docs/aspnetcore/tutorials/first-mvc-app-mac/start-mvc/8-23-17.pdf) and I open it I see the table of contents but no content is displayed. 
We get white pages for all content...
I have tried in macos using Preview and iBooks. Same behavior has been experienced using open source readers (e.g. Calibre ebook reader).
Can you check?

**Comment by Rick-Anderson** [comment]
@kmav  you're right. Thanks for opening this issue. Hopefully you can follow the ASP.NET Core 2.0 version. The 2.0 version has a lot more features.

**Comment by kmav** [comment]
Thank you for the good words. I get in that from your article: Getting started with ASP.NET Core MVC and Visual Studio for Mac (https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/start-mvc)...."This tutorial requires the .NET Core 2.0.0 SDK or later. See the **pdf** for the ASP.NET Core 1.1 version.". Can we expect that you are going to fix this pdf, or update your article ?

**Comment by Rick-Anderson** [comment]
@kmav  I'm afraid the PDF is lost and there is no way to restore it.  Can you follow the 2.0 version?

**Comment by kmav** [comment]
@Rick-Anderson Yes, sure :) I just thought that I was in 2.0 version... I am sorry but I am new to dotNET world, I am coming from Unix/Mac and I am "in love" on how Microsoft (and you) are opening your software :)  I had downloaded Visual Studio 2017 and started play on mac ...

**Comment by Rick-Anderson** [comment]
ASP.NET Core 2.0 has alot more features than the 1.1 version.

**Comment by kmav** [comment]
Can you advise for a link for ASP 2.0 to follow ?

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/index
To do the SQLite portion, you'll have to follow https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/start-mvc

**Comment by kmav** [comment]
Thank you very much.

**Comment by Rick-Anderson** [comment]
One you get more experience you'll be able to follow all the articles, not just the Mac tutorials.

**Comment by kmav** [comment]
Following your tutorials and others, I had installed in a few hours, dotnet (and played on command line), Visual Studio 2017, SQL server 2017 on docker and Microsoft opstudio from github!!! 
Next day I had played with a REST api app tutorial.

I did all of this because I had a request to check if I can support an app that is in .NET VB ... that I think is not possible (at least using a Mac).

**Comment by Rick-Anderson** [comment]
It would need to be .NET Core.
