### ISSUE TITLE
API doc: BuildServiceProvider incorrect return type

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4872]
[BuildServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0&term=BuildServiceProvider) incorrectly states:

Returns
ServiceProvider
TheIServiceProvider.

See https://github.com/aspnet/DependencyInjection/issues/614

**Comment by Rick-Anderson** [comment]
@dend @danroth27  see [BuildServiceProvider /// return comments](https://github.com/aspnet/DependencyInjection/blob/dev/src/DI/ServiceCollectionContainerBuilderExtensions.cs#L17)

Why is the API generating 
Returns
ServiceProvider
TheIServiceProvider.

and not The `IServiceProvider`.

**Comment by dend** [comment]
The API documentation reflects the true type that is used in code. The `'///` comment is used as a description, where it was not modified to reflect the changes. The `///` needs to be modified to include the correct type information, then packaged in an updated NuGet.

**Comment by Rick-Anderson** [comment]
>The API documentation reflects the true type that is used in code. 

The 2.0 API is returning `IServiceProvider`, not `ServiceProvider`

@danroth27  Regarding the space, can you confirm that's what's in the XML embedded in the NuGet package used to generate the API docs?

**Comment by Rick-Anderson** [comment]
@dend  should developers be instructed not to add ` /// <returns>` ? see [BuildServiceProvider /// return ](https://github.com/aspnet/DependencyInjection/blob/dev/src/DI/ServiceCollectionContainerBuilderExtensions.cs#L17)

**Comment by dend** [comment]
@Rick-Anderson If you take a look at the API, the docs reflect exactly what's in the source (and I am assuming the binary?):
<img width="255" alt="screen shot 2017-11-27 at 9 51 46 pm" src="https://user-images.githubusercontent.com/1389609/33304368-35157a8e-d3bd-11e7-80f7-8f14deffeaad.png">

The `/// <returns>` is not interpreted as the return type, but rather as a description for the return type, which is correctly displayed on docs.microsoft.com, as far as I can tell.

**Comment by davidfowl** [comment]
Ah our API docs are wrong 😄

**Comment by dend** [comment]
@davidfowl I suspect you have in mind the triple-slash comment and not the presented return type? 😃

**Comment by Rick-Anderson** [comment]
handled by https://github.com/aspnet/DependencyInjection/pull/615
