### ISSUE TITLE
Secret manager tool docs are incomplete and should not be VS Code specific

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#4889]
Currently the content for the secret manager tool is in a VS Code specific tab, which makes it hard to find. This tool is relevant regardless of which VS version you are using. We should move the content for working with the secret manager tool out of the VS Code tab.

The docs also only mention how you can list, remove and clear secrets. You can also pipe a JSON doc into the secret manager tool to set secrets. We should add content that shows how to do these actions.

**Comment by rachelappel** [comment]
This doc? https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio

**Comment by danroth27** [comment]
Yep

**Comment by rachelappel** [comment]
@danroth27 The doc outlines the steps to install SM in both VS and VSCode with a tab containing instructions for each. Not sure what exactly you want done here.  Also who has info on the JSON piping?

**Comment by danroth27** [comment]
>  The doc outlines the steps to install SM in both VS and VSCode with a tab containing instructions for each

That's not what I'm seeing. I only see the cmdline instructions on the VSCode tab.

> Not sure what exactly you want done here

1. Add instructions for installing and using the secret manager tool regardless of which tab is selected
2. Add content that shows how to use each of the actions supported by the secret manager tool (add, remove, list, clear"
3. Document that you can pipe JSON data into the secret manager tool

Basically document what's in the help text for the tool.

Maybe what's needed here is a reference style topic for each of our cmdline tools (user-secrets, watch, sql-cache, aspnet-codegenerator) that we can link to. For comparison here is how the .NET Core SDK folks document their CLI tools: https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x. Or another great example of docs for a cmdline is the [git  reference docs](https://git-scm.com/docs).

But for now, let's get user-secrets more fully documented in the existing safe storage of app secrets doc.

**Comment by Rick-Anderson** [comment]
@rachelappel  the code is way out of date too.

**Comment by Rick-Anderson** [comment]
@rachelappel  can you make this ref style like the  CLI tools: https://docs.microsoft.com/en-us/dotnet/core/tools/ ?
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new is a good example
