### ISSUE TITLE
Building Music Store

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#49]
Getting Started -> Tutorials -> Building Music Store

**Comment by pharmatechnik** [comment]
Hello where is the tutorial :)?

**Comment by baibaomen** [comment]
I would like to contribute/review, baibaomen@gmail.com

**Comment by Rick-Anderson** [comment]
@baibaomen  can you test https://github.com/aspnet/MusicStore/blob/dev/README.md and see if that is enough to build/test/run MusicStore?

**Comment by Rick-Anderson** [comment]
@baibaomen can you test https://github.com/aspnet/MusicStore/blob/dev/README.md and see if that is enough to build/test/run MusicStore?  cc @tdykstra

**Comment by geoffreyaladro** [comment]
@Rick-Anderson I tried running the MusicStore.

The README says to cd \src\MusicStore\
I went to \samples\MusicStore\

With .NET Core 1.1, running "dotnet restore" led to numerous errors.

Installed .NET Core 2.0 Preview 2 and then "dotnet restore" ran with no errors.

"dotnet run" complained that "project targets multiple frameworks"

"dotnet run --framework net461" got the MusicStore running and it appeared fully functional.

After opening the solution file in Visual Studio 2017 and selecting "Start Without Debugging" the browser displayed "HTTP Error 502.5 - Process Failure".

I am just getting started with software development and will be the first to admit I don't really know what I am doing. But I appreciate the opportunity to look through this sample project to see how things can be done in ASP.NET Core. Thank you!

**Comment by Rick-Anderson** [comment]
Try `dotnet run` to run the app. If you want to use VS, you'll need [VS 17 Preview 3](https://www.visualstudio.com/vs/preview/)

**Comment by guardrex** [comment]
@danroth27 @scottaddie I just took a look at this one. The way Music Store is configured these days, the packages aren't versioned. One apparently must run `build.cmd /t:Pin`, which runs the `build.ps1` script to pin the packages and restore the app. However when I tried that ... :boom: :cry: ...

```
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'. At C:\Users\xxxxx\Desktop\MusicStore-dev\MusicStore-dev\build.ps1:98 char:47
+ ...                Expand-Archive -Path $tmpfile -DestinationPath $korebu ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```
... possibly due to a conflict with PSCX according to a forum comment that I found on this exception.

Whatever the case with that, are u sure you want to go forward with this issue? It looks like the dev team isn't so hot about devs playing with it. Note their message in the repo README:

> It is not intended to be a representative sample of how to use ASP.NET Core.

... and I'm a little concerned that Music Store won't be a well-behaved test app for devs.

**Comment by scottaddie** [comment]
@guardrex I'll look to Dan for a decision on this one.

**Comment by guardrex** [comment]
@scottaddie :grinning: I burned out working on the CommandLine config provider issue (almost done; will be submitted tomorrow), so I thought I'd slide over here and play with something else. lol ..... This looked like it was going to be sooooooo easy. *So much for that plan!* lol

**Comment by danroth27** [comment]
The original intent of this issue was to have a tutorial doc that walked you through creating the Music Store app, like we had for previous versions of ASP.NET MVC (see https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions/mvc-music-store/). 

The [MusicStore repo](https://github.com/aspnet/musicstore) was based on the Music Store tutorial, but is now primarily used for testing purposes as part of the ASP.NET Core build infrastructure. This repo is not intended to be consumed as a sample and should not be the basis for any docs. If we decided to recreate the Music Store tutorial for ASP.NET Core it will need to live in a separate repo.

I believe the main value the Music Store app added over our existing [Movie Store tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/) is that it touched on Identity. 

We could try to merge the useful parts from the Music Store repo into the Movie Store tutorial, but I suspect that would add too much complexity. 

So, yes, I think we still want a Music Store tutorial as a more advanced tutorial after you've made it through the basic Movie Store tutorial. We just can't use the MusicStore repo.

**Comment by guardrex** [comment]
I see ... I misunderstood your intent. Since this would be a tutorial that covers significant segments of a rather large app, this is potentially a big job.

**Comment by Rick-Anderson** [comment]
> it touched on Identity.

@danroth27  That's covered better by https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data

closing this issue
