### ISSUE TITLE
Using Commands - SecretManager and SqlConfig should already be installed for you.

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#494]
http://docs.asp.net/en/latest/dnx/commands.html
If you are using Visual Studio, then both SecretManager and SqlConfig should already be installed for you.

**Comment by danroth27** [comment]
Need this to change in the product first.

**Comment by Rick-Anderson** [comment]
@danroth27  http://docs.asp.net/en/latest/dnx/commands.html states (incorrectly right now)
If you are using Visual Studio, then both SecretManager and SqlConfig should already be installed for you.

**Comment by danroth27** [comment]
The DNX commands doc has been removed since we moved to .NET Core.
