### ISSUE TITLE
Installing the Secret Manager tool - instuctions incomplete

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#495]
Install the Secret Manager tool using the .NET Development Utility (DNU). The Secret Manager tool is installed as a DNX command via the Microsoft.Framework.SecretManager package:

dnu commands install Microsoft.Framework.SecretManager

'dnu' is not recognized as an internal or external command, operable program or batch file.

@danroth27 

It also doesn't mention 
Install-Package Microsoft.Framework.SecretManager -pre

Can you add a link for windows folks to http://docs.asp.net/en/latest/getting-started/installing-on-windows.html

**Comment by danroth27** [comment]
> 'dnu' is not recognized as an internal or external command, operable program or batch file.

That just means you don't have DNX installed/available on your command prompt. Open up the *Developer Command Prompt for VS2015* from the Start menu and run the following commands:

```
dnvm setup
dnvm upgrade
```

These steps are documented at http://docs.asp.net/en/latest/getting-started/installing-on-windows.html

> Install-Package Microsoft.Framework.SecretManager -pre

This looks like part of a nuget.exe command which isn't relevant at all for DNX scenarios

> Can you add a link for windows folks to http://docs.asp.net/en/latest/getting-started/installing-on-windows.html

All of our docs assume you have already run through the Getting Started steps for the specific platform you are on. I don't think it makes sense to replicate getting started instructions throughout our docs. If you haven't installed the product then why would you expect to be able to use it?

**Comment by danroth27** [comment]
We updated the Download Center page to include the `dnvm setup` and `dnvm upgrade` steps. By RTM we also plan to install the User Secrets package by default.
