### ISSUE TITLE
API Reference

### ISSUE THREAD

**Issue by distransient** [aspnet/Docs#497]
Beta8 is approaching (wooo!) and .net is missing one big thing... an API reference!

As far as I can tell, Razor, MVC, and Identity have `<summary>` documentation for each class and method at the least. I'm not entirely familiar with the workings of DNX, or what the plans might be to provide documentation for the namespaces of the main API surface of .Net 5 itself. 

I'm willing to help build this part of the documentation, but definitely I'd like to at least confirm there aren't plans or work already put into this that I'm not aware of, as well as hear what the interests of the team are on this.

**Comment by Rick-Anderson** [comment]
@danroth27 is working on this and I'm sure we can find a way for you to help out. We will use some tool to import the API reference from the code.

**Comment by Rick-Anderson** [comment]
@distransient check out https://github.com/aspnet/ApiDocs

**Comment by distransient** [comment]
That repo isn't public yet, or at least I can't see it.

**Comment by Rick-Anderson** [comment]
You're right, it's not public yet, sorry. @danroth27 can you comment on when it will be public and how @distransient can contribute?

**Comment by danroth27** [comment]
That repo isn't actually being used for anything, and there's a good chance it won't be used at all. I'm already working with the Read the Docs folks to setup API docs using the [sphinx-autoapi](https://github.com/rtfd/sphinx-autoapi) extension. Stay tuned!
