### ISSUE TITLE
Explain the difference between IConfigurationRoot and IConfiguration 

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#4985]
The templates are using `IConfiguration` ([example](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L40)), but the [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index) topic examples use `IConfigurationRoot`. This caused a bit of confusion for a reader of the topic. I recommend that we explain the difference in the Configuration topic.

@HaoK said ...

> The only reason you really ever need IConfigurationRoot is if you want to reload config, or want access to the individual providers that make up the config, neither of these two situations are common

**Comment by Rick-Anderson** [comment]
Also address Low CSAT.
