### ISSUE TITLE
Creating a Cross-Platform Console App with DNX 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#499]
http://docs.asp.net/en/latest/dnx/console.html 
see DISQUS 
FYI, your cs file the in the example is missing the Console.WriteLine("Hello from DNX!"); line. Oh and I had to run "dnu restore" first too ;)
@ardalis

**Comment by ardalis** [comment]
Fixed with ec5b3c2eb6030900c3ba10609dd35f63d98034e6 in 1.0.0-beta7 branch.
