### ISSUE TITLE
Link hosting.md to IHostingStartup doc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#4991]
See https://github.com/aspnet/Docs/pull/4973

https://github.com/aspnet/Docs/pull/4967 must be merged first.

**Comment by guardrex** [comment]
@Rick-Anderson I can do this on the same PR. I'll link it now.

**Comment by guardrex** [comment]
Actually safer :bomb: if I *don't* do that. I'll hold off.
