### ISSUE TITLE
Community provided article on Dependency Injection

### ISSUE THREAD

**Issue by andygonusa** [aspnet/Docs#4996]
Hi all, attached please find an article submitted by a Spanish Latam community member, now an FTE in Microsoft. Originally it was published on a local section of the MSDN library and had very good PVs. It provides a good overall description of Dependency Injection

It has been reverse-machine-translated to provide a readable English version - if you think it has some merit and could find a place in the official documentation, please do let me know and we can work with the author to have it amended as necessary.

This also serves as a test, to see if it's efficient to use this process for such submissions/proposal.

thanks to let me know your thoughts
[Inyeccion-de-Dependencias.zip](https://github.com/aspnet/Docs/files/1555551/Inyeccion-de-Dependencias.zip)

**Comment by Rick-Anderson** [comment]
Hi @andygonusa 

We have an article on [DI](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection)
