### ISSUE TITLE
Update Your First ASP.NET 5 Application Using Visual Studio to beta8

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#500]
http://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html
DISQUS reported problem
Removing .NET Core from the list of frameworks from the project.json file isn't enough. I had to right-click in AccountController.cs and choose Organize Usings / Remove Unnecessary Usings. It didn't like the Microsoft.AspNet.Authentication; statement.

@ardalis

**Comment by ardalis** [comment]
I believe this will be fixed if/when the sample is updated to beta8. :watch:
