### ISSUE TITLE
Fix upzip to unzip in installing-on-linux

### ISSUE THREAD

**Issue by anotherkabab** [aspnet/Docs#501]
### Title
Fix upzip to unzip in installing-on-linux

### Functional impact
None.

### Minimal repro steps
Go to the [Install the .NET Version Manager (DNVM)](http://docs.asp.net/en/latest/getting-started/installing-on-linux.html#install-the-net-version-manager-dnvm)

### Expected result
The instruction would read
Install unzip if you don’t already have it:

### Actual result
The instruction reads
Install upzip if you don’t already have it:

### Further technical details
In getting-started, installing-on-linux, in the section "Installing on Debian, Ubuntu and derivatives", subsection "Install the .NET Version Manager (DNVM)". This is a minor typographical error.

**Comment by shirhatti** [comment]
Closing since this has been fixed
