### ISSUE TITLE
How to set Detailed Errors with environment other than shotgun Development

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5011]
Per @glennc in #4685
> I noticed that the [detailedStartupErrors ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#detailed-errors) docs I could find never talked about being able to set it via an environment variable, only showed how to do it in code.

Update doc to show how to set with environment directly. Add any security caveats.

**Comment by Rick-Anderson** [comment]
@danroth27  who's the contact for setting [detailedStartupErrors ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#detailed-errors)  directly by environment variable?

**Comment by danroth27** [comment]
@Tratcher can help out with this.

**Comment by Rick-Anderson** [comment]
@Tratcher how does one set [detailedStartupErrors ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#detailed-errors)  directly by environment variable?

**Comment by Tratcher** [comment]
All Hosting settings can be configured as environment variables by pre-pending them with `ASPNETCORE_`

**Comment by guardrex** [comment]
We currently have this in the *Ordering importance* section of the *Hosting* topic. I'd like to make a quick patch update that will surface it better.

Also, @Tratcher, you say "all," so it's ok to say "all" here instead of "some" ...

> Some of the WebHostBuilder settings are first read from environment variables, if set. These environment variables use the format ASPNETCORE_{configurationKey}.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x#ordering-importance

**Comment by Tratcher** [comment]
Yes, all.

**Comment by Tratcher** [comment]
Put another way, they're all read from the host configuration, which includes env vars by default.

**Comment by guardrex** [comment]
That sentence is confusing because it's unclear on the point of whether or not *all* of them can be set from env vars. It just needs a minor update to clarify the point.
