### ISSUE TITLE
AddAzureWebAppDiagnostics() is required on .NET Framework

### ISSUE THREAD

**Issue by ljani** [aspnet/Docs#5016]
The [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x#the-azure-app-service-provider) for [`Microsoft.Extensions.Logging.AzureAppServices`](https://www.nuget.org/packages/Microsoft.Extensions.Logging.AzureAppServices) provider state that:

> You don't have to install the provider package or call the `AddAzureWebAppDiagnostics` extension method. The provider is automatically available to your app when you deploy the app to Azure App Service.

However, if my ASP.NET Core 2.0 (`<PackageReference Include="Microsoft.AspNetCore" Version="2.0.0" />`) project targets the full .NET Framework (`<TargetFramework>net47</TargetFramework>`), this is no longer true. I need to install the provider package and call `AddAzureWebAppDiagnostics()` explicitly. Can you reword the paragraph to make a distinction between the behavior on .NET Core and .NET Framework please?

This is by design as per https://github.com/aspnet/Logging/issues/716.

**Comment by scottaddie** [comment]
@ljani Thank you for reporting this issue. The fix has been merged and should go live within the next 24 hours.
