### ISSUE TITLE
Hi I am trying to run - calling-a-web-api-from-a-net-client\sample\server\ProductsApp - in visual studio 2017, getting a build error - Severity	Code	Description	Project	File	Line	Suppression State Warning		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.2.1.0\build\Microsoft.Net.Compilers.props.	ProductsApp, I cannot locate this package - any ideas ?

### ISSUE THREAD

**Issue by jasonmoon1969** [aspnet/Docs#5021]

**Comment by Rick-Anderson** [comment]
@jasonmoon1969  follow the instructions at [Getting Started with ASP.NET Web API 2](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/tutorial-your-first-web-api) to create the project. Copy the controller and model contents to the new project. That will give you a working server. I need to figure out how to save the project in GitHub.

**Comment by Rick-Anderson** [comment]
@jasonmoon1969  edit the .csproj file and remove those lines. I'll update the project soon.

**Comment by Rick-Anderson** [comment]
@jasonmoon1969  I fixed the .csproj file. You can see what I did at https://github.com/aspnet/Docs/pull/5037/files

Thanks for reporting this. Tip, next time make a sort title and put the contents in the issue.
Fix will go live in a few hours.

**Comment by Rick-Anderson** [comment]
@jasonmoon1969  fix is now live.
