### ISSUE TITLE
Cannot locate package required for Server project

### ISSUE THREAD

**Issue by jasonmoon1969** [aspnet/Docs#5022]
## General
Hi 
I have downloaded a project to create a local web server. Getting error on build
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.2.1.0\build\Microsoft.Net.Compilers.props.	ProductsApp	- Any ideas where to locate this ?

**Comment by Rick-Anderson** [comment]
dup of #5021

**Comment by Rick-Anderson** [comment]
@jasonmoon1969  ignore my tip in other issue. New TIP. You can edit issues and close issues.
