### ISSUE TITLE
How to debug ASP.NET 5 source

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#505]
This will be a tutorial on how to debug ASP.NET source. ASP.NET MVC 6 will be used as the example, but you should be able to debug any repo source with the instructions.

**Comment by poke** [comment]
[This article on the .NET Web Dev blog](http://blogs.msdn.com/b/webdev/archive/2015/02/06/debugging-asp-net-5-framework-code-using-visual-studio-2015.aspx) might be relevant too. It helped me debug the framework code in the past.

**Comment by danroth27** [comment]
@Eilon @glennc Should this just go on the [Home](https://github.com/aspnet/home) repo?
