### ISSUE TITLE
Create include for New File Project showing .NET Core on .NET FX

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5050]
The changes requested in issue https://github.com/aspnet/Docs/issues/4869 should be made into an include. 
Original PR #https://github.com/aspnet/Docs/pull/5048 with changes

**Comment by scottaddie** [comment]
@rachelappel @Rick-Anderson In the note, I suggest we change the following:

"If you want to use ASP.NET Core on the .NET Framework..."

To this:

"To use ASP.NET Core with .NET Framework..."

Thoughts?
