### ISSUE TITLE
Document reasoning for web.config location

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5055]
Per discussion with @spottedmahn: Document the reason why *web.config* was moved from the webroot to the approot ...

> Moving the web.config file location to the root of the application enables publishing of multiple applications using Web Deploy.

Given the length, complexity, and focus of the hosting in IIS topic, this would probably be best in the [Directory structure](https://docs.microsoft.com/aspnet/core/hosting/directory-structure) topic.

It's probably also a good idea given the security risks of the new layout to either state explicitly what the workaround is for relocating the file back into *wwwroot* or at least link out to the GH issue in the *Additional resources* section. https://github.com/aspnet/IISIntegration/issues/164

@Rick-Anderson @scottaddie I'll knock this out on Jan. 2 if that's ok.

**Comment by Rick-Anderson** [comment]
[The web.config file](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration#the-webconfig-file)
 If you are using Visual Studio and delete web.config, Visual Studio will create a new one.

I don't think that's true with 15.5.x - is it?

**Comment by guardrex** [comment]
I thought VS was just running the targets of Sdk.Web: https://github.com/aspnet/websdk/blob/rel-2.0.0/src/Publish/Microsoft.NET.Sdk.Publish.Targets/netstandard1.0/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets

Regarding it's behavior, yes, at least for 15.5.2, which is what I have here. It does recreate the file if it's deleted from the published output (when performing a folder publish).

**Comment by scottaddie** [comment]
The _web.config_ file is created and dropped to the publish folder upon publish. The following sentence should be updated to clarify:
> If you are using Visual Studio and delete web.config, Visual Studio will create a new one.

@mlorbetske can likely provide additional details.

**Comment by guardrex** [comment]
I have time ... I'll take care of this issue if that's ok.
