### ISSUE TITLE
New kestrel configuration & related APIs

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#5056]
Kestrel now has first class support for loading endpoints via config. See https://github.com/aspnet/KestrelHttpServer/pull/2186

**Comment by Tratcher** [comment]
@shirhatti @danroth27 We'll want to have a blog post for this in preview1. We can use that as the rough draft for the docs.

**Comment by Rick-Anderson** [comment]
@Tratcher give us a change to edit before you publish.

**Comment by danroth27** [comment]
The new scheme is covered in the ASP.NET Core 2.1 roadmap blog post is here: https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/#security

**Comment by scottaddie** [comment]
@guardrex Any interest in taking this one?

**Comment by guardrex** [comment]
Sure ... I ❤️ server stuff.
