### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [aspnet/Docs#5062]
The link [in this file](https://github.com/aspnet/Docs/blob/master/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on.md) that says "one stop guide" is broken.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on

It works for me.
