### ISSUE TITLE
Migrating a tutorial from Angular.js to Angular

### ISSUE THREAD

**Issue by srikarplus** [aspnet/Docs#5069]
@Rick-Anderson 
I see that the tutorial [Hands On Lab: Build a Single Page Application (SPA) with ASP.NET Web API and Angular.js](https://docs.microsoft.com/en-us/aspnet/web-api/overview/getting-started-with-aspnet-web-api/build-a-single-page-application-spa-with-aspnet-web-api-and-angularjs#comments-container) is outdated. I would like to update the tutorial to the latest version of Angular and also introduce tools like VS Code and Angular Cli.
If this sounds good, give me a thumbs up and I will proceed furthur.

**Comment by Rick-Anderson** [comment]
That's the pre Core version - so it would need to stay that way.
@scottaddie  can you respond.

**Comment by scottaddie** [comment]
@srikarplus I'm okay with you updating this tutorial. As mentioned by Rick, keep in mind that this is ASP.NET 4.x, not ASP.NET Core.

Also, avoid explaining Angular fundamentals. Refer readers to the official Angular docs where explanation of a feature is needed/useful. I agree that the Angular CLI should be used throughout the tutorial, since that's the standard for creating Angular apps now.

**Comment by srikarplus** [comment]
Hi @scottaddie , pfa the document and the necessary code files. 
[Creating the SPA Interface.docx](https://github.com/aspnet/Docs/files/1647463/Creating.the.SPA.Interface.docx)
[app.zip](https://github.com/aspnet/Docs/files/1647468/app.zip)
The first part of the tutorial i.e., creating Web api remains unchanged. I have only updated the tutorial for creating Angular frontend.

**Comment by scottaddie** [comment]
@srikarplus Thank you for doing this! Can you please open a pull request and submit this document in Markdown format? I'm happy to help if you have any questions.

**Comment by srikarplus** [comment]
Sure @scottaddie , I will do it.

**Comment by scottaddie** [comment]
Thanks, @srikarplus! Let me know if you have any questions.

**Comment by Rick-Anderson** [comment]
@srikarplus 	we can reopen this when you have time to work on it.
