### ISSUE TITLE
Full text searches?

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#507]
Apparently, the documentation system doesn't do full text searches, correct? I just ran into a case where I opened an issue and sort of wasted a MS dev's time because the documentation system didn't return all mentions of a search term.

**Comment by Rick-Anderson** [comment]
If your on https://docs.asp.net/en/latest/ the search box only searches the aspnet tree. If you're on the MVC side (http://docs.asp.net/projects/mvc/en/latest/index.html) it only searches the MVC tree. Is that what you saw? It would be nice to unify the search.

**Comment by GuardRex** [comment]
I searched "machineKey" because I was trying to get `Antiforgery` working in a web farm scenario, and I wanted to see the deltas for .NET 5 ... was `Antiforgery` using `<machineKey>` to get its tokens set and validated? Turns out the answer is a big fat "NO" ... it's all in the new data protection system now. The search results for "machineKey" yield this:

![capture](https://cloud.githubusercontent.com/assets/1622880/10465757/2bd218bc-71b6-11e5-86c2-39eb8d304415.PNG)

... but I really needed it to show me all of the docs that mention "machineKey," especially the introduction doc at https://docs.asp.net/en/latest/security/data-protection/introduction.html, where you'll see it say early and clearly that ...
```
The ASP.NET 5 data protection stack is designed to serve as the long-term replacement
for the <machineKey> element in ASP.NET 1.x - 4.x.
```
So, I kind'a wasted @blowdart's time answering this question about these bits in https://github.com/aspnet/Antiforgery/issues/19. I mean it was good to hear from him, because he gave me that tip about `IKeyManager`, and I'm more of an "Azure Key Vault philosophy dude" than a "File Share philosophy dude." I'd like to see a sample for `IKeyManager` or `XmlKeyManager` implemented with Azure Key Vault, but it's a bit early right now to hope for something like that to be documented anywhere.

Therefore, it seems like full text search is not working for the documentation system; and if not, it will probably lead to problems like this on a huge scale when the world of .NET shops start adopting .NET 5 at RTM time.

I guess you're hinting that with the search box only searching the tree that it's only searching titles? Is that a limitation that we'll just need to live with? If so, I might as well use Google, e.g., searching Google for "machinekey site:docs.asp.net" has the introduction document come up 3rd in the search results:

![capture2](https://cloud.githubusercontent.com/assets/1622880/10466348/84d4605c-71b9-11e5-8161-5e269c08be14.PNG)

**Comment by Rick-Anderson** [comment]
*Apparently, the documentation system doesn't do full text searches, correct?*
That's incorrect. You seem to have hit an edge case.
search for shortcomings  and you'll see <machineKey>  - maybe the <> prevent machineKey from being in the dictionary. Try other terms and you can see it's does full text searches.

What is a significant limitation is that it searches are only in one tree as I mentioned. (aspnet or mvc)
I created #511 to track that issue.
