### ISSUE TITLE
Copy blog: Exploring the .NET Core Docker files: dotnet vs aspnetcore vs aspnetcore-build

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5096]
[Exploring the .NET Core Docker files: dotnet vs aspnetcore vs aspnetcore-build](https://andrewlock.net/exploring-the-net-core-docker-files-dotnet-vs-aspnetcore-vs-aspnetcore-build/)

@andrewlock can we copy your blog if we list you as lead author?

Per @DamianEdwards [11:30 into Jan 2, 2018 video](https://www.youtube.com/watch?v=_3EpZJxuFJw&feature=youtu.be&t=11m30s) ~~*Our doc team sucks* for not having this.~~ 

@rachelappel  is this something you could do in the next week (If @andrewlock  agrees)?

@danroth27  @scottaddie  please advise on TOC location and priority. 
cc @guardrex

**Comment by Rick-Anderson** [comment]
@rachelappel  review outline with @spboyer

**Comment by DamianEdwards** [comment]
I did not say that 😐

**Comment by guardrex** [comment]
> You know what's great and terrible about this? It's great that this content exists. What's terrible is that we should've written this content. It should be somewhere in our docs site.

> You said it; I didn't.

> I'm being totally honest.

I'm trying to figure out the least painful way to commit _Hara-Kiri_ lol :smile:. I'm sure I overreacted, but your remarks (and @shanselman's retort) made me feel like we're dropping the ball here.

There are currently **518 open docs issues** between the .NET Core and ASP.NET Core docs repos. Geebers McScreebers! :grinning: We have about a dozen new issues opened daily and **only six FT authors** working on the content. In @mairaw's realm, they've surpassed the 300 open issue mark. While the ASP.NET Core docs have dropped from ~230 issues down to 192 (and still falling), the .NET Core docs issue count has steadily risen over the last several months to 326 (!!!) with no end in sight. [If @davidfowl will share his cloning technology, we'll Frankenstein three Mairas, three Ricks, and three Lukes to get the backlog done! lol :smile:]

I think the docs are great and getting better and better as we go. I'm truly honored to be working with these cats. I wouldn't trade this experience and joy for anything. @Rick-Anderson is like a brother to me. @mairaw like a sister. We'll get the content in place. Just shoot us an issue, and we'll get 'er done. :+1:

cc/ @dasMulli @jongalloway

**Comment by DamianEdwards** [comment]
When I say *we* I mean my team. I consider missing docs a failure of my team for not determining or relaying priorities correctly. I've seen feedback on the docker container situation before and didn't log an issue, so that's my failing, not the doc team.

**Comment by guardrex** [comment]
I see. Thanks for clarifying. I simply misunderstood your remarks.

**Comment by andrewlock** [comment]
> @andrewlock can we copy your blog if we list you as lead author?

Sure, or link back to it 🙂

**Comment by Rick-Anderson** [comment]
@DamianEdwards  can you assign someone to point out differences you'd like to see in our copy of Andrew's blog? 

@rachelappel  can you make this your primary task?

**Comment by rachelappel** [comment]
@jralexander Ping

**Comment by JRAlexander** [comment]
I wrote this article: https://docs.microsoft.com/en-us/dotnet/core/docker/intro-net-docker. It's at a higher level than the blog post, but I think it's a good start. What do you think?

**Comment by rachelappel** [comment]
@Rick-Anderson Yeah no prob

**Comment by rachelappel** [comment]
I can create a nice summary and link to details on the blog. The doc can reiterate some of the important highlights on dotnet vs aspnet vs core and docker versions, then present a table with each of the images, its purpose, and what it contains. 

-dotnet vs aspnetcore vs aspnetcore-build 
-docker image versions
-table with each of these docker images listed:
    microsoft/dotnet:2.0.3-runtime-deps - use for deploying self-contained deployment apps
    microsoft/dotnet:2.0.3-runtime - use for deploying .NET Core console apps
    microsoft/aspnetcore:2.0.3 - use for deploying ASP.NET Core apps
    microsoft/dotnet:2.0.3-sdk - use for building .NET Core (or ASP.NET Core apps)
    microsoft/aspnetcore-build:2.0.3 - use for building ASP.NET Core apps, especially apps that need Node, Bower, or Gulp.
    microsoft/aspnetcore-build:1.0-2.0 - use for building ASP.NET Core apps that require multiple .NET Core SDKs, or that need Microsoft.Docker.SDK for building Docker tools projects.

@Rick-Anderson @DamianEdwards  Proceed with this?

**Comment by guardrex** [comment]
@rachelappel Note that the TOC in the Hosting and Deployment area is about to undergo a big update. I just mention it in case this will land in that part of the TOC. I'll have the Stage 1 PR (that deals with TOC updates) wrapped up and ready for review shortly. https://github.com/aspnet/Docs/pull/5127

**Comment by rachelappel** [comment]
Thanks for the heads-up @guardrex!

**Comment by guardrex** [comment]
The Docker topics folder does move on that PR: Everything is going from "publishing" to "host-and-deploy" in the TOC. I'm making the final checks now and putting the final touches on it. I think we'll go quickly with it, since it blocks Stage 2 work (Antares troubleshooting topic), and they need that Antares topic up asap for a link that will go into VS.

**Comment by Rick-Anderson** [comment]
> link to details on the blog
We don't link to blogs. We do copy with permission.

@rachelappel  set up a meeting with Damien to go review the blog and your outline. Damien might defer to another PM.

**Comment by scottaddie** [comment]
@glennc is another great resource for Docker with ASP.NET Core

**Comment by DamianEdwards** [comment]
@glennc is **the** source for Docker with ASP.NET Core from our team

**Comment by guardrex** [comment]
@rachelappel fyi ... just in case you didn't see it ... the *host-and-deploy* TOC is stable now. :rocket:

**Comment by rachelappel** [comment]
Moving to the .NET repo. Team prefers doc be based on different article, does not want copy and paste, wants scenario based solution. New issue: https://github.com/dotnet/docs/issues/4155

**Comment by Rick-Anderson** [comment]
Just for clarification, we would have produced this article by helping Andrew convert his blog to markdown (and make edits). Andrew would then submit the converted doc in a PR.
