### ISSUE TITLE
Creating a Cross-Platform Console App with DNX

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#51]
ASP.NET 5->.NET Execution Environment (DNX)->Creating a Cross-Platform Console App with DNX
- Create a Console Application (Package)
- Building and publishing your cross-platform console app
- Running your cross-platform app

**Comment by ardalis** [comment]
@danroth27 would this make more sense in the getting-started section? It seems like the logical next step after installation is to demonstrate how to run a "hello world" console app, and it is independent of ASP.NET, isn't it?

**Comment by danroth27** [comment]
I'm trying to keep all of the DNX specific content in one place for now so that we can move it if needed. Could we just cross link the topic?

**Comment by ardalis** [comment]
Sounds good; will do.
