### ISSUE TITLE
Search should be for entire site, not just aspnet or mvc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#511]
Searching from the main site only searches the aspnet side, for example
http://docs.asp.net/en/latest/search.html?q=machineKey
the same search on the mvc side
https://docs.asp.net/projects/mvc/en/latest/search.html?q=machineKey

You shouldn't have to search both places.

**Comment by Rick-Anderson** [comment]
@danroth27 In addition to not indexing IIS, it also can't find project.json
search the mvc site for project.json and zero results. Now search for json and you'll see several project.json.

**Comment by danroth27** [comment]
We merged the MVC docs with the ASP.NET Core docs.
