### ISSUE TITLE
Document ASP.NET Core WebHooks

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#5133]
We will preview the ASP.NET Core port of WebHooks early this year and it is slated to ship with 2.1.

**Comment by Rick-Anderson** [comment]
@dougbu can you provide an article draft?

**Comment by dougbu** [comment]
@Rick-Anderson not anytime soon. We're heads down on WebHooks 2.0.0 right now.

On the other hand, the https://github.com/aspnet/WebHooks repo contains many samples. Those samples cover all of the receivers updated to use ASP.NET Core as well as "before" samples using ASP.NET 5.2.2.

**Comment by vankampenp** [comment]
Thanks all, I will eagerly wait for the preview with the aspnetCore nuget package to try it out.

**Comment by scottaddie** [comment]
@danroth27 I have 2 questions for you:
1. Are you hoping for a tutorial, a reference doc, or both?
1. Any particular receiver(s) to focus on in the doc? For example, GitHub, Kudu, etc.

**Comment by vankampenp** [comment]
Mostly a getting started doc for Asp.Net Core webhooks
I am a new user to webhooks. What do I need to do to get a webhook, say Wordpress webhook or any other, working in ASP.NET Core? 
What nuget package works with Asp.Net Core? And which for the receivers?
Maybe it is all there, but today it is a bit too much guess work to get started.
