### ISSUE TITLE
Document the relationship between models, model state and what the HTML helpers render

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#514]
Ex see https://github.com/aspnet/Mvc/issues/3320.

**Comment by danroth27** [comment]
We should check how much this still applies to tag helpers.

**Comment by danroth27** [comment]
@dougbu Can you confirm whether this issue is HTML helper specific or not?

**Comment by dougbu** [comment]
The documentation may need to improve _slightly_ for tag helpers as well. But the story gets more complicated for HTML helpers, especially the `string`-based ones that check `ViewData`.

**Comment by danroth27** [comment]
This should be covered by #131
