### ISSUE TITLE
Don't use json schema in the DNX Projects doc

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#516]
See https://docs.asp.net/en/latest/dnx/projects.html#adding-dependencies. 

Schemas are for machines, not people.

**Comment by danroth27** [comment]
Remove all usages of JSON schema in this article and replace with examples and prose.

**Comment by Rick-Anderson** [comment]
@danroth27  can we close this?

**Comment by danroth27** [comment]
Yup
