### ISSUE TITLE
core/fundamentals/logging

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5161]
- [x] How to create logs - wrong. Need to show how to set up logging first before you use it.
- [x] ~To create logs,~
- [x] ~Then~ call l --- Needs lots of UE work
- [x] UE rewrite - remove "you" and make it reference style.
- [x] Show RP sample, not just MVC. 
- [x] Show how to hook up logging in `Startup` by injecting logger in ctor.
- [x] Show how to hook up logging in `Main`.
- [x] Enhance the `ILogger` interface and implementation remarks. See: https://github.com/aspnet/Docs/issues/8891

Move to a separate issue:
- [x]  Refactor when the non-ASP.NET-specific logging documentation is written per  https://github.com/dotnet/docs/issues/4567

**Comment by Rick-Anderson** [comment]
Logging in `Startup`

```
public class Startup
{
    private readonly ILogger<Startup> _logger;

    public IConfiguration Configuration { get; }

    public Startup(ILogger<Startup> logger, IConfiguration configuration)
    {
        _logger = logger;
        Configuration = configuration;
    }

    public void ConfigureServices(IServiceCollection services)
    {
        _logger.LogInformation("ConfigureServices called");

        // …
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        _logger.LogInformation("Configure called");

        // …
    }
}
```

@guardrex  @scottaddie  can you add a snippet for logging from `Main`?

**Comment by Rick-Anderson** [comment]
[CreateDefaultBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost.createdefaultbuilder?view=aspnetcore-2.0#Microsoft_AspNetCore_WebHost_CreateDefaultBuilder) configures the ILoggerFactory to log to the console and debug output. So we just need sample of using the logger.

**Comment by Rick-Anderson** [comment]
Need to show how to log when seeding the DB:

```
public class Program
{
    public static void Main(string[] args)
    {
        var host = BuildWebHost(args);

        using (var scope = host.Services.CreateScope())
        {
            var services = scope.ServiceProvider;
            var context = services.GetRequiredService<ApplicationDbContext>();
            context.Database.Migrate();

            var config = host.Services.GetRequiredService<IConfiguration>();
            // Set password with the Secret Manager tool.
            // dotnet user-secrets set SeedUserPW <pw>

            var testUserPw = config["SeedUserPW"];

            try { 
            SeedData.Initialize(services, testUserPw).Wait();
            }
            catch (Exception ex)
            {
                var logger = services.GetRequiredService<ILogger<Program>>();
                logger.LogError(ex, "An error occurred while seeding the database.");
                throw ex;
            }
        }

        host.Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>()
            .Build();
}
```

**Comment by guardrex** [comment]
I used service locator approach in the RP testing sample: https://github.com/aspnet/Docs/blob/master/aspnetcore/testing/razor-pages-testing/sample/src/RazorPagesTestingSample/Program.cs#L21

**Comment by tdykstra** [comment]
@guardrex I am going to start on this.  Several logging issues that I could address at the same time are assigned to you -- do you want to keep them or shall I reassign to me the ones that I can do along with this one?

**Comment by guardrex** [comment]
Oh, I think please go ahead and reassign. I have **_plenty_** 😅 to keep me busy. lol

**Comment by guardrex** [comment]
oh ... and btw ... there's a sample tracking issue where logging topics are listed if you want to add your PR number to the ones that are already there (or if you find a logging topic that isn't listed ... I'm finding "hidden" samples on this repo all the time! 🙈). The PRs you currently see next to logging topics might have merely been to update them to 2.1. I don't recall if any UE work was done on those.

https://github.com/aspnet/Docs/issues/5495
