### ISSUE TITLE
PDF file download for ASP.NET Framework docs is broken

### ISSUE THREAD

**Issue by terrimorton** [aspnet/Docs#5173]
The "Download PDF" link (https://docs.microsoft.com/en-us/aspnet/opbuildpdf/toc.pdf?branch=live) at the bottom of the TOC on each page (e.g. https://docs.microsoft.com/en-us/aspnet/overview) seems to be broken. It is generating a large PDF file which cannot be read in either the Chrome browser or a local PDF reader when downloaded.

**Comment by rachelappel** [comment]
@danroth27 @mairaw  Is this anything either of you two can help with?

**Comment by Rick-Anderson** [comment]
@dend  should I open a LSI on this?

**Comment by mairaw** [comment]
I don't have permissions to your repo @Rick-Anderson so cannot check the status of the PDF builds on OPS. I'd open a LSI. We just had one LSI fixed related to PDF builds in our side.

**Comment by Rick-Anderson** [comment]
@Eilon  can you give @mairaw write access to this repo?

**Comment by Rick-Anderson** [comment]
@Eilon  can you also add @guardrex  to this repo.  `@danroth27` approved in our meeting today.

**Comment by Rick-Anderson** [comment]
@terrimorton  it's working for me. Can you check again? (From chrome anyway.)

**Comment by mairaw** [comment]
I get this on Chrome:
![image](https://user-images.githubusercontent.com/12971179/35019720-44e46992-fadd-11e7-8308-71e9e92763a3.png)

**Comment by Rick-Anderson** [comment]
No repo. I opened https://mseng.visualstudio.com/CSI/_workitems?id=1163057 to track this.

**Comment by Eilon** [comment]
Both @mairaw and @guardrex should have push access to the docs repos. Thanks!

**Comment by Rick-Anderson** [comment]
@terrimorton  can you try it now? Looks like it's working.

**Comment by terrimorton** [comment]
It is still repro'ing for me. As Maira indicates, I eventually get a "Failed to load document" in the Chrome browser. And the downloaded .PDF file fails to be opened by Adobe Acrobat Reader DC.

FWIW I am running Windows 10 Enterprise.

**Comment by dend** [comment]
@terrimorton this should be fixed. Can you please validate again?

**Comment by terrimorton** [comment]
Yes, I confirmed with Esther from the Apex SRE team on 1/25 that this was now resolved. I just double-checked and it's still working as expected. Thanks for following up!
