### ISSUE TITLE
Check the Response Caching Middleware sample

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5175]
RE: https://docs.microsoft.com/aspnet/core/performance/caching/middleware

Pull down the sample and see how it's doing. A reader reports it might not be functioning correctly.

@Rick-Anderson @scottaddie I'll find some cycles late next week to TAL.

cc/ @Engin

**Comment by Rick-Anderson** [comment]
Setting priority based on PV.

**Comment by guardrex** [comment]
Actually, I think I'll check this tonight. I don't like me samps gett'in sideways on me. :smile:

**Comment by guardrex** [comment]
:+1: Sample is good.

@engin You probably just need to use a tool like Fiddler to examine the response headers to confirm the response caching behavior and double-check the [caching conditions in the topic](https://docs.microsoft.com/aspnet/core/performance/caching/middleware#conditions-for-caching) to confirm that they're all met in order for the middleware to cache the response. If you need additional help with the middleware, we can chat about it on Slack or you can [open an issue on the Home repo](https://github.com/aspnet/Home/issues). Slack self-signup is here :point_right: http://tattoocoder.com/aspnet-slack-sign-up/
