### ISSUE TITLE
chinese doc Display error

### ISSUE THREAD

**Issue by HeMinzhang** [aspnet/Docs#5177]
![qq 20180113205325](https://user-images.githubusercontent.com/2683269/34906218-d2258ec6-f8a3-11e7-8c2f-a29297e945be.png)
## General

We use issues to drive the discussion for changes to
existing topics and the creation of new topics.
This template offers some suggestions to consider
when creating an issue.

## Issues with Existing Topics

If the issue is a simple typo or similar correction, just submit a PR.
Otherwise, let us know what's wrong or what we should improve. Include a
link to the topic.

## Requests for new Topics

1. Write a **short** paragraph describing what the topic will cover.
https://docs.microsoft.com/zh-cn/ef/core/modeling/generated-properties Display error

2. Write an outline of the proposed topic contents.

3. Where would you put the topic in the Table of Contents.

4. If you know who should review the issue, notify them by including @githubID in the issue description.

**Comment by guardrex** [comment]
@HeMinzhang What browser are you using?

I loaded the page with Chrome and Edge. It looks ok in these browsers.

Chrome 63.0.3239.132:
![capture](https://user-images.githubusercontent.com/1622880/34972330-7040e4d6-fa46-11e7-9e2b-2db43c52170d.PNG)

Edge 41.16299.15.0:
![capture1](https://user-images.githubusercontent.com/1622880/34972333-735b48be-fa46-11e7-8741-03d549f342fc.PNG)

**Comment by HeMinzhang** [comment]
Now my browsers  show there is no error, but did show an error before
