### ISSUE TITLE
ASP.NET Core IIS Hosting Bundle Pre-reqs Deficiency

### ISSUE THREAD

**Issue by mockjv** [aspnet/Docs#5192]
## General

I've been able to reproduce pretty conclusively that the ASP.NET Core Hosting bundle appears to require the MS VC++ 2010 redistributable IF you have not installed "Web Deploy 3.5" and you don't publish the web app with a runtime (e.g. dotnet publish -f netcoreapp2.0), otherwise you receive a 500.19 error message.  I've been able to reproduce this in clean Server 2k8r2 and Server 2016 VMs.  In our specific use case, we're producing an installer/deployment where "Web Deploy" is completely unnecessary since we'll be using Wix to appropriately create the IIS AppPool and application instance.

## Issues with Existing Topics

My thought is there should possibly be a note added to the IIS hosting page regarding this pre-req, in the event that Web Deploy isn't installed.  If this isn't the most appropriate way to approach this, please let me know, but my thought is that all we need is this being clearly indicated.

Issue submitted to AspNetCoreModule:  https://github.com/aspnet/AspNetCoreModule/issues/285

**Comment by guardrex** [comment]
The timing of your feedback is great @mockjv. This section of the TOC has been under revision the last two weeks, and I have another PR going together right now that includes the *Host on IIS* topic.

cc/ @joeloff Thoughts on this?

**Comment by guardrex** [comment]
@joeloff The only thing we have right now is this remark:

> If the system doesn't have an Internet connection, obtain and install the [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/download/details.aspx?id=53840) before installing the .NET Core Windows Server Hosting bundle.

**Comment by mockjv** [comment]
I'm closing this issue because upon further verification, I've found that there must be another factor in my environment or the installer bundle.

**Comment by guardrex** [comment]
@mockjv If you don't mind, I'd like to leave this open just a hair longer. If there's something else that we need to do on the topic for the revisions that pertain to the installer, this is a good spot for me to track the doc work. After all, @joeloff may come in and say 'Yeah, Luke ... your installer doc language is *terrible!*' :smile: lol ... Let's see how it plays out; and if there's no doc action required, then we can close this.

**Comment by guardrex** [comment]
@joeloff Let me know if we need to reopen this to discuss further. I'm closing here, but I'll address the installer language in the IIS hosting topics when I get to Stage 3 hosting updates on https://github.com/aspnet/Docs/issues/5100.

Thanks @mockjv for reporting. 🌴 Let us know if you hit any snags with the docs on this or in other ways.
