### ISSUE TITLE
Create a New NuGet Package with DNX

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#52]
ASP.NET 5->.NET Execution Environment (DNX)->Create a New NuGet Package with DNX
- Create a new DNX project for your package (link to DNX projects article)
  - Various project.json properties map to package metadata: authors, description, version, etc
  - Package id will match the DNX project name (folder name by default, no way to change it yet)
  - Version can have -*. Set DNX_BUILD_VERSION env var on your build server to specify the replacement for the version wildcard.
  - Pointer to DNX commands article for creating command packages
- Targeting multiple frameworks
  - Each framework under frameworks maps to a folder under lib in your package that gets built for you by DNX automatically
  - Target framework specific dependencies are handled for you
  - Specify set of frameworks that you can target (.NET 2.0?, PCLs? Silverlight? etc)
- Building your package
  - `dnu pack` will do a build and create your package and symbol package
  - Dependencies/frameworkAssemblies will automatically get handled
  - Limitations:
    - One assembly per package
    - Can't add additional files yet (see https://github.com/aspnet/dnx/pull/2561#issue-103130995)
- Publishing your package
  - Upload to your favorite package feed (nuget.org, myget.org, internal company feed, etc)
  - Note: Uploading to nuget.org requires you to have a description . . .

**Comment by markrendle** [comment]
Is this actually possible right now (i.e. in beta4)?

**Comment by danroth27** [comment]
@markrendle  Absolutely! You can create the package from the command line using `dnu pack` or you can set the "Produce outputs on build" option in VS on the project's Build tab.

![produce-output-on-build](https://cloud.githubusercontent.com/assets/1874516/7842827/9488f5fc-045a-11e5-9d1c-ef47bd4434a5.png)

**Comment by neil-119** [comment]
When I published a project to Nuget, I got the following error:
*Failed to read the package file. Ensure it is a valid NuGet package with a valid manifest.*

Turned out the problem was that I had a blank description in project.json. It would be helpful if Visual Studio outputted a warning when "Produce outputs on build" is on but the required meta data is not available.

**Comment by Gekctek** [comment]
Is there a plan to have the nuget package id configurable (instead of project name) by the initial release of AspNet 5? at all? or are there easy workarounds without changing the project name?

**Comment by danroth27** [comment]
@Gekctek It's on our backlog (https://github.com/aspnet/dnx/issues/2312), but will probably come after the initial release.

**Comment by danroth27** [comment]
This topic will be covered as part of the .NET docs now that we are moving to the new [.NET CLI](https://github.com/dotnet/cli). Closing.
