### ISSUE TITLE
Explain how to get configuration at startup

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5230]
@nhwilly asks on the [Options topic](https://docs.microsoft.com/aspnet/core/fundamentals/configuration/options) ...

> I need to get at those [Options] values while still in the ConfigureServices method. ... What am I missing?

This would be a great add imo. I just drop back to a built configuration to take them, and I think that will work well in most cases. If they need to use a new configuration builder for a source that isn't OOB, that's fine. We could note that or show it. At the very least, we prob want to provide some basic guidance tho.

[EDIT] I'm thinking this new section should appear at the bottom of the Configuration topic, but then we link a little blurb about it at the bottom of the Options topic over to that Configuration section to surface it in Options.

@HaoK Thoughts?

```csharp
public class Program
{
    public static IConfiguration Configuration { get; set; }

    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((hostingContext, config) =>
            {
                Configuration = config.Build();
            })
            .ConfigureServices(services =>
            {
                services.Configure<MyOptions>(Configuration);

                Console.WriteLine(".......................................");
                Console.WriteLine($"{Configuration["subsection:suboption1"]}");
                Console.WriteLine(".......................................");

                services.AddMvc();
            })
            .Configure(app =>
            {
                ...
            })
            .Build();
}
```

**Comment by nhwilly** [comment]
Wow, thanks for addressing this so quickly.

If it helps, I found the following, which seems weird to me, but I don't know much.

The code below does not work. `_cosmosConfig` is always null.
```
public class Startup
{
    private CosmosConfig _cosmosConfig => new CosmosConfig();
    ...
}
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(_config);
    services.AddOptions();
    _config.GetSection(nameof(CosmosConfig )).Bind(_cosmosConfig);
    ...
}
```

But **this** code does work.
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton(_config);
    services.AddOptions();
    var _cosmosConfig = new CosmosConfig();
    _config.GetSection(nameof(CosmosConfig )).Bind(_cosmosConfig);
    ...
}
```
If I declare it locally with the method, it seems to work fine.

And this always works:
```
    var sp = services.BuildServiceProvider();
    _cosmosConfig = sp.GetService<IOptions<CosmosConfig>>().Value;
```

Since I have a workaround, I'm good, but I thought that behavior was odd.  Clearly others will have similar issues (especially around OpenIdConnect options) so suggesting the proper way to do that in the docs would be a great addition.

**Comment by nhwilly** [comment]
Ok, so my thoughts, fwiw.

At the top of the document, it suggests isolating options to classes specific for use so that their consumers don't get access to items they don't need.  Makes perfect sense to me.  

So I created my own options classes and I want the IOptions<T> dependency injection to take care of the rest.  I'm not a fan of strings in code if I can help it.

So my `appsettings.json` file has a few top level items and then all the POCO's underneath.  Actually, that makes the most sense to me, rather than using `["Parent:Child"]` way of obtaining the value.

Maybe I'm doing it wrong, but I thought I was doing things the recommended way.

**Comment by guardrex** [comment]
@nhwilly On your first question ('this works' but 'this doesn't'), the wisdom of @HaoK will guide us.

RE: `GetService` ... We definitely want to avoid a service locator pattern if we can.

> isolating options to classes specific for use so that their consumers don't get access to items they don't need

... i.e. ... SoC right into startup (`ConfigureServices`). I have some notions, but let's see where the discussion goes. I usually don't sweat SoC quite that far.

**Comment by HaoK** [comment]
Can you include your entire startup.cs @nhwilly ?

**Comment by HaoK** [comment]
But going to your main question, since you are inside the actual method that's part of building the service provider, building your own provider is likely the only good option.

```
  var sp = services.BuildServiceProvider();
    _cosmosConfig = sp.GetService<IOptions<CosmosConfig>>().Value;
```

**Comment by guardrex** [comment]
@HaoK 

1. Should we proceed with covering the approach for obtaining configuration for `CongifureServices` in the Configuration topic (i.e., the example I show in the OP)? I envision it as a new section at the bottom of the topic.
2. Should we cover the service build/locator pattern in the Options topic? I envision it as a new section at the bottom of the topic.
3. If the answer to (1) and (2) are 'yes,' I envision linking a remark in Options over to the section in Configuration. If the dev can just use config, that seems like a viable approach, so they would have a choice.

**Comment by HaoK** [comment]
You shouldn't really be using IOptions in ConfigureServices, but binding an options instance against config in ConfigureServices is fine

**Comment by guardrex** [comment]
Ok, but getting access to config values in `ConfigureServices` is becoming a regular ask, so I'd like to just go with (1). I'll try a short remark at the bottom of Options to surface the new Configurations topic section in case they land in Options or didn't catch the Configuration topic first. If it doesn't look good on review, we can cut or modify it. Sound good (at least to try and see how it looks)?

**Comment by HaoK** [comment]
Using config in configure services is fine, just not IOptions itself since that's the part of what's building up the IOptions services itself.
