### ISSUE TITLE
Enhance cookie sharing topic for common Identity dB

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5238]
~Blocked by: https://github.com/aspnet/AuthSamples/pull/45~

aspnetcore/security/data-protection/compatibility/cookie-sharing.md
https://docs.microsoft.com/aspnet/core/security/data-protection/compatibility/cookie-sharing

The three cookie-sharing projects in the cookie sharing topic sample are under revision in the AuthSamples repo. ~The refactor aims to have all three projects use a common Identity dB. For the cookie sharing topic, the dev will only need to create the user in one project to sign into all three apps. For an alternative topic, the projects will be an example of sharing an Identity dB generally across apps (Core-to-Core and Core-to-NET).~

* ~Drop the current sample from the topic.~
* ~Cross-repo link the AuthSamples sample into the topic (See the *External code snippets* section of *Step 3. Authoring* > *Authoring Content* > *Code snippets* of the OPS docs).~
* ~Update the instructions/content in the topic (and README, if needed) to reflect a single-dB sample.~

We're going to comment in the text (and possibly even update the sample) on sharing a common Identity dB across the apps.

**Comment by Tratcher** [comment]
A consistent issue I see people copying from the current samples is that they're always creating local data protection providers rather than configuring the central service.
https://stackoverflow.com/a/49329480/2588374
This sample would be better:
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x#persistkeystofilesystem

**Comment by guardrex** [comment]
It's documented in the topic and in the sample, but it's a quick one-liner in the topic. I'll add a paragraph to highlight it.

**Comment by guardrex** [comment]
@HaoK I've worked up to this issue now.

We were discussing the possibility of adding a section that describes the use of a common Identity dB across the cookie-sharing apps. What did you have in mind for this section? Alternatively, we could let this issue go because this isn't a developer ask.

**Comment by HaoK** [comment]
Yeah we can just let it go for now if noone has asked about it to date.
