### ISSUE TITLE
Using Browser Link with Firefox

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5251]
RE: Update to the Browser Link topic
aspnetcore/client-side/using-browserlink.md
https://docs.microsoft.com/aspnet/core/client-side/using-browserlink?tabs=aspnetcore2x

@Larswa reports ...

https://stackoverflow.com/questions/39385195/visual-studio-browser-link-not-working-in-firefox

When in FF and browsing a local site using IIS, Browser Link runs SSL on port 44399. And you need to browse to that port to go through the "Add to exception" to accept the localhost certificate most of us are developing against locally. After that Firefox browser link works fine.

**Comment by Larswa** [comment]
Let me know if there is anything more you want. Screenshots or more detailed explanations. Or a pull request against the docs.

**Comment by guardrex** [comment]
Ran into a snag here. Opened an issue to investigate :point_right: https://github.com/aspnet/BrowserLink/issues/65

**Comment by guardrex** [comment]
This isn't being addressed by engineering, so closing until further notice.
