### ISSUE TITLE
Section in Getting Started on Windows about uninstalling

### ISSUE THREAD

**Issue by per-samuelsson** [aspnet/Docs#526]
Want me to do [this](https://github.com/aspnet/dnx/issues/2287#issuecomment-129282374)? 

I've read through the contribution guidelines, and can send you a PR with a suggestion once you clear it. I don't want to set up the environment before that though.

**Comment by danroth27** [comment]
This will become part of the .NET CLI docs.

**Comment by danroth27** [comment]
This will become part of the .NET CLI docs.
