### ISSUE TITLE
Change ANCM requestTimeout property to remove 'requestTimeout must be specified in whole minutes'

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Docs#5264]
The requestTimeout in the aspnetcore_schema will be updated to allow a requestTimeout to be specified in seconds. https://github.com/aspnet/Docs/blob/313486d76f89ceac7af9b8c0769f72d1b224d4ca/aspnetcore/host-and-deploy/aspnet-core-module.md can now remove the note about only allowing whole minutes.
cc/ @shirhatti

**Comment by jkotalik** [comment]
This would be for 2.1.

**Comment by scottaddie** [comment]
@jkotalik Will this schema change apply ONLY to 2.1 and up? I'm wondering if we should state that the current note applies to all versions prior to 2.1. Thoughts?

**Comment by shirhatti** [comment]
Schema is a global singleton. As long as you've installed a newer ANCM (the one that will ship with 2.1) you'll get the fix, regardless of whether you continue to use an older version of ASP.NET Core.

**Comment by guardrex** [comment]
@Rick-Anderson Would u like to put me on this one? It's right up my alley.
