### ISSUE TITLE
Tracking: Metadata, title, description, and H1 updates

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5280]
Tracking:

* [x] Metadata entry sequence (https://github.com/aspnet/Docs/pull/5296)
* [ ]  Too long/short titles/descriptions/H1s, missing descriptions, and technology names in titles/H1s (#3278)

Metadata sequence has become a bit messy over time. I'd like to run one of my 😵 mad scripts 😵 on the repo to get a consistent order on the entries.

Sequence:

1. Title
2. Everything else alphabetized
3. UID

Descriptions should be between 115-145 characters including spaces. I'd like to run another script to check for and repair too long/short descriptions (and provide one when missing).

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie @rachelappel This evening, I'm getting back to this. It would have been done last weekend, but HTTP.sys kept me quite busy. 🏃

I'm addressing the following:
* Long titles (59 chars + technology name; H1 is 100, but we plan to match them)
* Technology names in titles/H1s (#3278)
* H1s that don't match titles (I'm aware of the SEO cheat sheet guidelines, but my current understanding is that we're matching them on this repo. Let me know if otherwise.)
* Missing and too long/short descriptions (Range: 115-145)

There's also https://github.com/aspnet/Docs/issues/5534, which looks like a dup of #3278, so let me know if I need to remove the title/H1 work from the list above :point_up: and just concentrate this on descriptions. In which case, I'll leave both #5534 and #3278 alone here.

**Comment by Rick-Anderson** [comment]
@tdykstra  I thought title could be longer than H1.

**Comment by tdykstra** [comment]
The opposite -- H1 longer than title

**Comment by guardrex** [comment]
@tdykstra :wave: Hope ur well.

Their guidance seems a bit flexible on the exact length when taking the technology into account:

> Title body is about 59 chars or fewer including spaces. Your product brand may require longer page titles. That’s OK. Test how your title truncates. Make the article intent clear and the brand recognizable.

For H1:

> Up to 100 characters including spaces.

They say not to use the title for the H1, but that's not a fast and easy fix here. Even if u want to go that way, perhaps it's best to do that as topics are edited over time.

**Comment by tdykstra** [comment]
The contributor guide SEO guidance for H1 doesn't say not to use the title:  

> Must be unique, with most important or differentiating terms first. You can repeat the page title, but you also have room to elaborate.

**Comment by guardrex** [comment]
It's from the SEO cheat sheet (Carolyn Gronlund, Sr Content Dev Mgr, C+E; Updated 17 Jan 2017):

> Page title: Text with the greatest impact on search rank and clickthrough. NOT the same as the H1 at the top of a page. 

> Heading 1 (H1)
> Heading at the top of article. It isn’t the same as the page title.  Second most important text string for search rank and relevance.
> Up to 100 characters including spaces.
> Avoid duplicating the page title if you can. 

Is this older guidance? See: https://github.com/aspnet/Docs/issues/5534#issuecomment-368061882

**Comment by guardrex** [comment]
Result of analysis:

| Problem | # Files |
| --- | :---: |
| H1 is too long (100 chars) | 0 |
| Title is too long [59 chars + 12 ("ASP.NET Core" allowance)] | 5 |
| Description is too long (145 chars) | 11 |
| Missing "ASP.NET Core" in title | 95 |
| Title is different from H1 | 104 |
| Description is too short (115 chars) | 189 |

Of course, many topics have more than one problem. Grand total, there are **252 topics** out of **390 total topics on the repo** that require some form of attention.

I'm going to break these down and setup one PR for the first three problems, then I'll set up subsequent PRs with about 30 topics per PR to save reviewer vision 👓.

I do have 😵 *mad Rex script automation* 😵 to help me update these, so it will be a piece of :cake:.

**Comment by cjgronlund** [comment]
@guardrex Thanks for this report.
These aren't the  checks we do on content -- there's a crawl report you can request. Please refer to this doc: https://review.docs.microsoft.com/en-us/help/contribute/how-to-seo-hackadoc?branch=master

For ASP.NET, we found many issues by flagging short page titles and H1s - there sometimes wasn't enough information  in the text to signal search rank for Google or relevance to readers.

Also, the H1 can be the same text as the page title -- except the appending of the brand, might look awkward in an H1 ( - ASP.NET Core). 

Please let me know if you have questions. Thanks!

**Comment by guardrex** [comment]
I can't reach that site due to a significant contractual change this time around, and I also wouldn't have access to the crawl report.

WRT the branding in H1, we're angling to incorporate the brand/technology into the title. Some current examples:

* *Work with static files in ASP.NET Core*
* *Response Compression Middleware for ASP.NET Core*
* *ASP.NET Core Middleware*

Therefore, they work ok for H1s imo.

If you have a different set of benchmarks for the updates, let me know.

* The title length guidance suggests that there's some flexibility, so I added 12 characters (the length of "ASP.NET Core") to the 59 character guidance. You might have a different way for me to approach that.
* The description length of 115-145 comes from the cheat sheet.
* The requirement for the technology name (brand) comes from #3278.
* The matching title-H1 comes from team guidelines for this repo. Although, it has been several months since my last chat about it, and that might have been with `@mairaw` early-ish last year.

**Comment by guardrex** [comment]
Added one: *Title matches description*

There are nine cases of that following #5574. They could've been caught by long title or short description filters, but it's good to keep an :eye: on them separately just to make sure.
