### ISSUE TITLE
performance/caching/response "Response caching in ASP.NET Core" improvements

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5283]
[Response caching in ASP.NET Core
](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/response)

Need to show how to set up middleware to use the attributes on this page.

Code snippets are nonsense - there is nothing to cache. 
```
[ResponseCache(VaryByHeader = "User-Agent", Duration = 30)]
public IActionResult About2()
{
```

They need to display time (seconds might be nice) so you can verify caching works.

```
    public IActionResult About()
        {
            ViewData["Message"] = DateTime.Now.Second;

            return View();
        }
```

**Comment by guardrex** [comment]
@Rick-Anderson Kind of a side-question on that: Per our earlier discussion, did you reach a conclusion about using browser dev tools (with caching disabled) or using one of the request-response tools (e.g., Fiddler, Postman) when explaining how to test/troubleshoot?

**Comment by Rick-Anderson** [comment]
@guardrex  that's fine. But we need to have the minimum code to get the sample to work.

**Comment by guardrex** [comment]
Sure thing on the code ... no prob.

I was just wondering if you wanted to go one way or the other on how to explain testing/troubleshooting. My natural inclination is to stick with Fiddler/Postman approaches.

**Comment by Rick-Anderson** [comment]
Hold off on this. First we need to get a working sample. Fiddler/postman/F12 tools should all be mentioned as testing/debugging tools.

**Comment by Rick-Anderson** [comment]
This article is on **Response caching in ASP.NET Core** but the first 80% has nothing to do with ASP.NET Core.

new outline:

**ResponseCache attribute**  should be first, move the preceding sections below.  

Start with the simplest `[ResponseCache(Duration = 6)]` and change the sample to
```
[ResponseCache(Duration = 9)]
public IActionResult About()
{
    ViewData["Message"] = DateTime.Now.Second;
    return View();
}
```

Add complexity from there.

replace note `location` with table

**Comment by guardrex** [comment]
Noting that it will be 2.1 for attribute response caching with RP: https://github.com/aspnet/Mvc/issues/6747
