### ISSUE TITLE
Document usage behavior for Tag Helper ModelExpression properties in a list

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#529]
See https://github.com/aspnet/EntityFramework.Docs/issues/44 
This should go in [Intro to TH](http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/intro.html)
@NTaylorMullen

**Comment by danroth27** [comment]
Document that tag helper properties of type `ModelExpression` or enum properties can use `@` to escape out of the default semantic of specifying a property of the model and instead specify any expression.

**Comment by Rick-Anderson** [comment]
I documented this in  Forms Tag Helpers #1027
