### ISSUE TITLE
Validate common errors in IIS/App Service common errors topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5297]
*Common errors reference for Azure App Service and IIS with ASP.NET Core*
aspnetcore/host-and-deploy/azure-iis-errors-reference.md
https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-iis-errors-reference

**Comment by Rick-Anderson** [comment]
@guardrex  can ASP.NET Core Module in-proc hosting - 6x the throughput on IIS! Better startup error handling (aspnet/AspNetCoreModule#265) be added to this issue or does it need a new issue?

**Comment by guardrex** [comment]
This one is for common errors topic update only, which is its own beast. Every error scenario has to be repro-ed to update this (been there ... done that :smile:). I recommend a new issue. You can assign the new issue to me if you want.

**Comment by guardrex** [comment]
@Rick-Anderson Would you like to add this issue to your 2.1 tracking topic under "issues not in the announcement"? If you do, then I can close out my Antares-IIS tracking topic as soon as Stage 3C is merged (it's probably the last PR in the set except for this common errors topic update).

**Comment by guardrex** [comment]
Note to self: Add an entry for when the app pool doesn't have write access to the location specified for the stdout log.

**Comment by Rick-Anderson** [comment]
>Would you like to add this issue to your 2.1 tracking topic under "issues not in the announcement"? 

Sure, can you do that?

**Comment by guardrex** [comment]
https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-apps/troubleshoot#app-startup-errors
 
From `scottaddie` ... Provide an example. Example: Referencing the 2.1.3 version of the .App metapackage in an app deployed to Azure when 2.1.3 isn’t present. Run `dotnet --info` from the Kudu console to surface it. See: https://github.com/aspnet/IISIntegration/issues/945#issuecomment-398741286

**Comment by guardrex** [comment]
Cross-reference: #8555

**Comment by guardrex** [comment]
Cross-reference: #8344

**Comment by guardrex** [comment]
From @JashanChittesh on https://github.com/aspnet/Docs/issues/8555 ...

The [App startup errors](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#app-startup-errors) troubleshooting guide does have some useful information but given that Visual Studio updates can break compatibility with the ASP.NET Core version installed on your server (giving you _HTTP Error 502.5 - Process Failure_, with no useful information in the Application Event Log (**Application '...' with physical root '...' failed to start process with commandline '...', ErrorCode =  '0x80004005 : 80008096.**), it would be helpful to know where to get the most current version of ASP.NET Core:

I guess after each Visual Studio update, you should probably check this URL and upgrade your server, if a new version is available: [.NET Core 2.1 downloads](https://www.microsoft.com/net/download/dotnet-core/2.1)

Eventually, you'll move to .NET Core 2.2 and that's simply "2.2" at the end of the URL: [https://www.microsoft.com/net/download/dotnet-core/2.2](https://www.microsoft.com/net/download/dotnet-core/2.2)

PS: Ah, even better is this URL:

[.NET download archives](https://www.microsoft.com/net/download/archives) ([https://www.microsoft.com/net/download/archives](https://www.microsoft.com/net/download/archives))

My response ...

Hello @JashanChittesh Thanks for commenting. That particular problem is covered in the *Common Errors* topic: https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-iis-errors-reference#missing-net-framework-version

The *Common Errors* topic is due for an update asap. Let's leave this issue open, and I'll see what kind of cross-linking/new info can be added when that topic is worked.
