### ISSUE TITLE
Disabling 'missing xml' notification

### ISSUE THREAD

**Issue by CoolGoose** [aspnet/Docs#5298]
Hi all.

I was wondering if it makes sense to specify that you can add `<noWarn>1591</noWarn>` in order to ignore the _Missing XML comment for publicly visible type or member._ . 

If so, i think the existing warning should go above the editor choice if you want to have the per specific editor way of disabling this, or just as a generic cross platform option.

Imho I rather tend to think the generic cross platform csproj option would be nicer than telling people how to disable it by a checkbox in the UI (i might be biased using visual studio code), as long as the UI in visual studio does the same thing.

**Comment by CoolGoose** [comment]
Hey @guardrex . I opened it here in the context of the Swagger integration. Should we keep this here and discuss if we'll link from here to the .NET core docs repo ?

**Comment by guardrex** [comment]
Ah! I see what you mean :point_right: https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger#xml-comments

@scottaddie will know what to do.
