### ISSUE TITLE
Project.json Reference

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#53]
ASP.NET 5->.NET Execution Environment->Project.json reference

**Comment by MisterJames** [comment]
@danroth27 I can do a start on this one if you like. Should I fork and start a PR?

**Comment by danroth27** [comment]
Sure, that sounds great! The idea for this topic is to simply be a reference for the entire schema for project.json

**Comment by MisterJames** [comment]
Sure, sounds good. What about the topic of project.lock.json, is this an appropriate place to provide an explanation of that as well?

**Comment by danroth27** [comment]
No, I think we should cover project.lock.json elsewhere (probably #50).

**Comment by jimschubert** [comment]
#50 is closed. Looks like project.lock.json was documented here: https://docs.asp.net/en/latest/dnx/projects.html#project-lock-file

**Comment by danroth27** [comment]
The details of project.json are covered in https://docs.asp.net/en/latest/dnx/projects.html. This content will also be making its way over to the .NET docs. Closing.

**Comment by simonech** [comment]
I guess then then the page http://docs.asp.net/en/latest/dnx/project-json.html should be removed from the tree
