### ISSUE TITLE
Link to EF Getting Started with ASP.NET 5 article

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#530]
Under Working with Data we should just link to http://ef.readthedocs.org/en/latest/getting-started/aspnet5.html.

**Comment by plitwin** [comment]
I'd like to work on this.

**Comment by danroth27** [comment]
@plitwin Sounds good!

**Comment by plitwin** [comment]
@danroth27  Should this simply include a link or should there be some text around it? Are there other articles that do this that you wish for me to emulate?

**Comment by danroth27** [comment]
I think this should just be a TOC entry in index.rst under the Working with Data node.Ideally we would use intersphinx for the link, but for now we can just hard code the URL.
