### ISSUE TITLE
SignalR: Supported Platforms topic update

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5300]
SignalR topic: *Supported Platforms*
https://docs.microsoft.com/aspnet/signalr/overview/getting-started/supported-platforms
aspnet/signalr/overview/getting-started/supported-platforms.md
 
The version language (IIS, Windows OS, WS) throughout requires work.

**Comment by rachelappel** [comment]
Got it over here https://github.com/aspnet/Docs/issues/6015
