### ISSUE TITLE
mvc/views/tag-helpers/built-in/

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5310]
This needs missing tag helpers and some rework

-review all built-in tag helpers docs
-there are missing built-in tag helpers
-ToC update

**Comment by isaac2004** [comment]
Based on the current dev branch, here is a list of all the Built-In Tag Helpers that are missing

- FormActionTagHelper
- LinkTagHelper
- OptionTagHelper
- RenderAtEndOfFormTagHelper 
- ScriptTagHelper

**Comment by Rick-Anderson** [comment]
dup of #2256
