### ISSUE TITLE
Update Tutorials under Docs to Beta 8

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/Docs#535]
I have just noticed that ```your-first-aspnet-application``` under Tutorial of Docs repository is in beta 5.

Is it required to convert to beta 8, which is latest currently?

Path is as below:

https://github.com/aspnet/Docs/tree/master/aspnet/tutorials/your-first-aspnet-application

**Comment by plitwin** [comment]
I will work on this today during the hackathon

**Comment by robbert229** [comment]
By the way I already have a PR for https://github.com/aspnet/Docs/tree/master/mvc/tutorials/mvc-with-entity-framework.rst, just making sure we both don't do the same work.

**Comment by plitwin** [comment]
robbert229 Okay, I will back off this. Thanks for letting me know.

**Comment by plitwin** [comment]
Thanks for letting me know. I am leaving it to you.
Paul Litwin


From:  John Rowley <notifications@github.com>
Reply-To:  aspnet/Docs
<reply+00117bf386f153a4c85d300733f81b7e5f2d7cfe76f5a6e992cf00000001125379b79
2a169ce06a98f95@reply.github.com>
Date:  Thursday, November 5, 2015 at 12:10 PM
To:  aspnet/Docs <Docs@noreply.github.com>
Cc:  Paul Litwin <paul@litwinconsulting.com>
Subject:  Re: [Docs] Update Tutorials under Docs to Beta 8 (#535)


By the way I already have a PR for
https://github.com/aspnet/Docs/tree/master/mvc/tutorials/mvc-with-entity-fra
mework.rst, just making sure we both don't do the same work.


Reply to this email directly or view it on GitHub
<https://github.com/aspnet/Docs/issues/535#issuecomment-154176366> .

**Comment by robbert229** [comment]
This should probably be closed.

**Comment by NeelBhatt** [comment]
nice to see number of people for a task! Thinking when i could get chance to work for Microsoft :P
