### ISSUE TITLE
Document .UseForwardedHeaders on Linux with Apache

### ISSUE THREAD

**Issue by kevinoid** [aspnet/Docs#5358]
It took me a while to figure out that calling `app.UseForwardedHeaders` _with options_ was required to use the `X-Forwarded-*` headers from Apache.  Would it be possible to either copy the ["Why use a reverse proxy server?" section from "Host ASP.NET Core on Linux with Nginx"](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md#why-use-a-reverse-proxy-server) or to move it to a common location which is referenced by both?

Thanks,
Kevin

Related: #2384

**Comment by kevinoid** [comment]
Thanks @guardrex!

**Comment by guardrex** [comment]
@kevinoid :rocket: My pleasure ... thanks for bringing this to our attention.
