### ISSUE TITLE
Use an alternative container for the IMiddlewareFactory topic sample

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5376]
Suggested by @dotnetjunkie on [simpleinjector/SimpleInjector \#510](https://github.com/simpleinjector/SimpleInjector/issues/510#issuecomment-363378953) ...

> I would advise against using Simple Injector as example for demonstrating IMiddlewareFactory in the ASP.NET Core documentation. I think the model described in the Simple Injector documentation is simpler and more practical. I don't see any benefits in implementing a custom IMiddlewareFactory when using Simple Injector. Try to find a different DI Container where this integration point actually makes sense.

cc/ @davidfowl

**Comment by guardrex** [comment]
Looks like we'll be keeping this based on @davidfowl's response. Feel free to reopen if we need to make changes to the sample.

> Today the issue with conventional middleware is that it takes arguments that aren't services. The next `RequestDelegate` pattern being passed to the constructor makes it not very DI friendly. The middleware class is also a singleton today, which means scoped services can't be passed into the constructor, instead we support resolving scoped dependencies from the `InvokeAsync` method.

> In order to fix this, we added `IMiddleware` and `IMiddlewareFactory` which changes the pattern to create the middle per request instead of per app. This means that scoped services can be specified in constructor instead of the `Invoke`/`InvokeAsync` method. The `IMiddlewareFactory` is the composition root for the `IMiddleware` activation. Similar to the `IControllerFactory` in MVC which is responsible for creating and destroying controllers, it's the thing responsible for creating and destroying `IMiddleware`.

**Comment by guardrex** [comment]
Spoke too soon! lol

> If you decide to keep the current use case described, at the very least please refrain from using Simple Injector as example for this particular feature in your documentation, because it pushes Simple Injector users into a direction that is not best for Simple Injector users.

Reopening for work. @Rick-Anderson @scottaddie I'll take this one if that's ok with you.

**Comment by Rick-Anderson** [comment]
@guardrex 
To fix this put a note, something like:
This sample uses `Simple Injector` for documentation simplicity. This is not an endorsement of SI.

@danroth27  - who is a DI backup to ` @davidfowl`?  I don't want to bother DF for every doc question we have.

**Comment by guardrex** [comment]
I'm happy to replace it with a different container if you/they change direction later here. I feel kind of bad about this, since I should've pinged @dotnetjunkie to discuss it in advance.

I'll add the note where the use of SI is first mentioned. I'll have it in this evening.

**Comment by Rick-Anderson** [comment]
[SI](https://simpleinjector.readthedocs.io/en/latest/quickstart.html) has great docs - seems like a good choice with a caveat.
