### ISSUE TITLE
Intro to SignalR

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5390]

**Comment by rachelappel** [comment]
What is SignalR?
Transports and fallbacks
Hubs and Connections 
SignalR for ASP.NET Core Architecture
Related Resources

**Comment by Rick-Anderson** [comment]
@rachelappel  take a look at [staged Introduction to SignalR](https://review.docs.microsoft.com/en-us/aspnet/core/signalr/introduction-to-signalr?branch=pr-en-us-5453) and https://github.com/aspnet/Docs/pull/5453 and see what we can recycle. Original has massive dead wood which I started to remove.
