### ISSUE TITLE
Tutorial: Getting Started with ASP.NET Core SignalR

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5391]

**Comment by rachelappel** [comment]
- Prereqs
- Get Started with SignalR for ASP.NET Core
- Create an ASP.NET Core project that uses SignalR
- Create the SignalR Hub
- Configure the project to use SignalR
- Create the SignalR client code
- Verify code works
- Next Steps

**Comment by Rick-Anderson** [comment]
@anurse  do you want to recycle [Tutorial: Getting Started with SignalR 2 and MVC 5](https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/tutorial-getting-started-with-signalr-and-mvc) ? 

We would use RP (Razor Pages) in lieu of MVC. What other changes? (besides changes to the product)

**Comment by scottaddie** [comment]
Fixed by https://github.com/aspnet/Docs/pull/5540
