### ISSUE TITLE
Allow sample code download without fetching whole repo or zip file

### ISSUE THREAD

**Issue by airmanx86** [aspnet/Docs#5392]
I am trying to download the sample code in this folder.
https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample

As `git` does not have a way to only download a specific folder. I need to clone the whole repo or download it as zip to get it.

Unfortunate for me, I can only `git clone` from github at approx. 400KiB/s, which mean the process takes forever.

It would be very nice if there is release process to allow downloading of each sample code independent of the rest of the repo.

**Comment by scottaddie** [comment]
@dend or @EisenbergEffect, are either of you able to comment on plans to address this?

**Comment by EisenbergEffect** [comment]
Thanks for the feedback @airmanx86 and @scottaddie 

I've always wished that GitHub had the native ability to just download a folder of content. @dend I can put you in touch with our GitHub representatives to discuss this with them directly. Either way, this is a good request to think about as it relates to the future of samples.

**Comment by guardrex** [comment]
This was discussed a few times/places in the past, but things never evolved past just getting links and instructions in place ...

https://github.com/aspnet/Docs/issues/565
https://github.com/dotnet/docs/issues/1644

**Comment by EisenbergEffect** [comment]
@guardrex Thanks for the historical references! @dend Can you confirm that we at least have this as an official backlog item and that this scenario is being considered as part of your samples work?

**Comment by dend** [comment]
We are working on this for our samples - stay tuned for more updates soon.

cc: @EisenbergEffect @guardrex @scottaddie

**Comment by scottaddie** [comment]
Closing this issue. It's much broader than this particular docset, and it's an enhancement that's already in the works.
