### ISSUE TITLE
2.1 Improvements to HTTPS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5393]
See https://github.com/aspnet/Home/issues/2308 
  `javiercn` to review.

- [x] provide URL for .NET Core CLI fwlink  that tells how to trust cert, how to set up HTTPS go here See [2:40 in video](https://www.dropbox.com/s/9olqhldt75vngoz/Review%20ASP.NET%20Core%202.1%20doc%20priorities%20-%20Monday%2C%20April%209%2C%202018%208.09.35%20AM.mp4?dl=0) 
- [x]   [Add HttpsRedirection and Hsts middleware documentation \#4568](https://github.com/aspnet/Docs/issues/4568)
- [x]  Add section on dotnet dev-certs https , more detail below
- [ ] Need  at least a H2 in [Enforcing HTTPS in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl) for **Certificate missing error** . Someone in the PU requested this, they have a fwlink that will point to this. I think this was more aimed at server and not dev.
- [x] We don't recommend using RequireHttpsAttribute and I'm going to suggest deprecating it. Use 2.1 templates approach which uses `app.RedirectToHttps`
See also #5056 and https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/#security

**Comment by guardrex** [comment]
For discussion/consideration:

### Improve 'how to download' for running with HTTPS

https://docs.microsoft.com/aspnet/core/tutorials/index#how-to-download-a-sample

Possibly update section heading: *How to download and run a sample*

Per @scottaddie:

> You should just need to run:
>
> dotnet dev-certs https --trust
>
> See the instructions here:
>
> https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-https-improvements/

May also need the tool installed ...

> dotnet install tool dotnet-dev-certs -g --version 2.1.0

Change "how to download" link text to "how to download and run" across the repo.

Also note that FF has required a manual step to approve the use of untrusted certs in the past.

**Comment by guardrex** [comment]
Since the *Enforce HTTPS* topic is called out for the content's location, this one looks related: [Add HttpsRedirection and Hsts middleware documentation \#4568](https://github.com/aspnet/Docs/issues/4568)
