### ISSUE TITLE
Debug: example shows password

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#540]
http://docs.asp.net/en/latest/fundamentals/logging.html states:

Debug

Used for the most detailed log messages, typically only valuable to a developer debugging an issue. These messages may contain sensitive application data and so should not be enabled in a production environment. Disabled by default. Example: Credentials: {"User":"someuser", "Password":"P@ssword"}

Do we need to even state "may contain sensitive application data" and show an example dumping a password? I'd like to avoid suggesting it's OK to add debug statements with sensitive data.

@blowdart

**Comment by Rick-Anderson** [comment]
@blowdart  should I remove the following from 
http://docs.asp.net/en/latest/fundamentals/logging.html states:

Debug

Used for the most detailed log messages, typically only valuable to a developer debugging an issue. These messages may contain sensitive application data and so should not be enabled in a production environment. Disabled by default. Example: Credentials: {"User":"someuser", "Password":"P@ssword"}

I don't want customers dumping passwords.

see also #548

**Comment by blowdart** [comment]
I'd leave it - it shows the dangers.
