### ISSUE TITLE
Web API conventions - Rich Swagger support without attributes

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5401]
aspnet/Mvc#6870, aspnet/Mvc#6784

Related Resources:
- ASP.NET Community Standup: https://www.youtube.com/watch?v=zr4Btou3H8c&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&index=0
- ASP.NET Core 2.1 Roadmap: MVC - https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/#mvc
- ASP.NET Core 2.1.0-preview1: Improvements for building Web APIs: https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-web-apis/

Docs to update:
- [x] [Create a Web API with ASP.NET Core and VS for Windows](https://docs.microsoft.com/aspnet/core/tutorials/first-web-api)
- [x] [Create a Web API with ASP.NET Core and VS for macOS](https://docs.microsoft.com/aspnet/core/tutorials/first-web-api-mac)
- [x] [Create a Web API with ASP.NET Core MVC and Visual Studio Code on Linux, macOS, and Windows](https://docs.microsoft.com/aspnet/core/tutorials/web-api-vsc)
- [x] [Get started with NSwag](https://docs.microsoft.com/aspnet/core/tutorials/getting-started-with-nswag)
- [x] [Get started with Swashbuckle](https://docs.microsoft.com/aspnet/core/tutorials/getting-started-with-swashbuckle)
  - [x] Update to from Swashbuckle 1.x to 2.x
  - [x] Update to ASP.NET Core 2.1

Docs to create under the new Web API TOC node:
- [x] `ActionResult<T>` reference
- [x] `[ApiController]` attribute reference

**Comment by scottaddie** [comment]
A related ASP.NET Community Standup: https://www.youtube.com/watch?v=zr4Btou3H8c&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&index=0
