### ISSUE TITLE
Compile Razor pages 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5408]
aspnet/Razor#1809

**Comment by scottaddie** [comment]
@Rick-Anderson I've been talking to Dan Roth about this one and have some detailed notes (and a sample app). I'll gladly take this on.

**Comment by guardrex** [comment]
This was noted in #5404 but not obvious here since aspnet/Razor#1809 pertains to compiled Razor in libs.

> Razor compilation is now part of every build. This means that Razor compilation issues are caught at design time instead of when the app is first run. Compiling the Razor views and pages also significantly speeds up startup time. And even though your view and pages are built up front, you can still modify your Razor files at runtime and see them updated without having to restart the app.
