### ISSUE TITLE
Identity UI package and scaffolder

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5410]
- [ ] Update fwlink to this article per `@danroth27`
https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/

aspnet/Home#2311
[Identity Scaffolding: Pages not chooseable by the user need to be generated appropriately](https://github.com/aspnet/Scaffolding/issues/763)

@seancpeters is the contact

**Comment by ckolumbus** [comment]
the blog link is wrong ;-)
https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/

**Comment by Rick-Anderson** [comment]
@ckolumbus  thanks, fixed. They changed it.

**Comment by Rick-Anderson** [comment]
Scaffold identity into a Razor project without auth. Only task

In the PMC, enter the following commands:

``` PMC
Install-Package Microsoft.EntityFrameworkCore.Tools
Add-Migration Initial
Update-Database
```

**Comment by Rick-Anderson** [comment]
Scaffold identity into a Razor project without auth.

Things to fix that are due to bugs, won't need this change in next version:
* fix up layout  file
* fix generated *Areas\Identity\Pages\_ViewStart.cshtml*

Manual changes to make:
