### ISSUE TITLE
Incomplete translation

### ISSUE THREAD

**Issue by anappwilos** [aspnet/Docs#5412]
**Incomplete** **_translation_** of https://docs.microsoft.com/es-es/aspnet/core/tutorials/razor-pages-vsc/model
**for the Spanish language.**

![imagen](https://user-images.githubusercontent.com/29914357/36026525-c93bace2-0d97-11e8-9bf3-88b2bdae2458.png)

*Solution* : Agree translation.

**Comment by scottaddie** [comment]
Paging @nokura and @rachelappel...

**Comment by Rick-Anderson** [comment]
@anappwilos is the problem with the TOC (Table of contents) on the left side? I think the translated TOC sometimes lags the English version. 

I had google translate the es-es version and I couldn't see any problems.  If there is a problem with the translation, [edit the es-es version in the browser](https://github.com/aspnet/docs.es-es/edit/live/aspnetcore/tutorials/razor-pages-vsc/model.md) and create a PR.
