### ISSUE TITLE
Add KeyVault encryption to DataProtection

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5439]
`ProtectKeysWithAzureKeyVault`

https://github.com/aspnet/DataProtection/pull/273

Probably for [Configuring Data Protection in ASP.NET Core](https://docs.microsoft.com/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x)

**Comment by Rick-Anderson** [comment]
Copy from `@blowdart`  dup #5467

KeyVault key wrapping will come in 2.1

Data Protection documentation needs updating to describe this and a simpler, recipe type page should be created to explain to people what they'd use in what circumstances.
