### ISSUE TITLE
Document all the command-line parameter for the ServerHosting bundle

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#5454]
The ANCM document used to reference OPT_INSTALL_LTS and OPT_INSTALL_FTS, but was removed at some point of time. https://github.com/aspnet/Docs/pull/4001

AFAIK we have,
- OPT_NO_X86
- OPT_INSTALL_LTS
- OPT_INSTALL_FTS

@joeloff In case he has added other flags since.

**Comment by guardrex** [comment]
@shirhatti I think there was a window where those `LTS` and `FTS` flags didn't behave as expected ... https://github.com/aspnet/Docs/issues/3997#issuecomment-322927935

@joeloff, can u tell me the current behavior of each of those (and any new ones)? I'll wordsmith your notes into the topic.

**Comment by guardrex** [comment]
@shirhatti I'm going to go ahead and get this in. It seems strange to even have FTS and LTS switches when there are different installers on the .NET Downloads page (Current and LTS).

Whatever the case with that, are the defaults and descriptions below correct?

* OPT_INSTALL_X86 [0 (false)/1 (true); default: 1] Install x86 packages on an x64 OS.
* OPT_INSTALL_LTS [0 (false)/1 (true); default: 0] Install the Long Term Support (LTS) channel runtime.
* OPT_INSTALL_FTS [0 (false)/1 (true); default: 1] Install the Fast Track Support (FTS) channel runtime.

Support info:
* \[Microsoft Support Policy](https://www.microsoft.com/net/Support/Policy)
* \[.NET Support and Versioning](https://blogs.msdn.microsoft.com/dotnet/2016/07/26/net-support-and-versioning/)

**Comment by guardrex** [comment]
@shirhatti I'm piecing together what's going on from the prior discussion. The key concepts are ...

> LTS and FTS only apply to 1.x bundles, We treat 2.0 as LTS for now. So if you do OPT_INSTALL_LTS=0, you should only get the package store and ANCM. We can look at adding a switch to disable the package store as well for 2.0.1 if you'd like

> Also, we have OPT_NO_X86=1. When you specify this, it won't install the x86 bits on x64 OS. In 1.x we only installed the CPU bits matching the OS architecture, but in 2.x we made a change because people on 64-bit OS can host 32-bit and 64-bit applications so we'll install both if we can

From my testing with `OPT_INSTALL_LTS=0`, I found that it was adding the runtime anyway. The reason ...

> That flag appears to be disabled when support for the OPT_NO_X86 was added and because the package store is always installed.

**Therefore AFAICT, only the `OPT_INSTALL_X86` is a working flag for us to document.**
