### ISSUE TITLE
Add BodyTagHelper  to mvc/views/tag-helpers/built-in/

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5475]
See #4033
https://github.com/jbagga/TagHelperComponentSample
@fiyazbinhasan  if you can write the sample code, I'll write the article and list you as author.

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson the repository already contains well enough sample code. Could you please let me know what kind of samples do you need?

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan sorry I meant Document the new ITagHelperComponent in ASP.NET Core 2.0 #4033
Can you links to the repository samples you found?

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson I was talking about the repo link you provided. It has an example for the built-in `head` tag helper component i.e. `GlobalScriptTagHelperComponent`. And a custom `footer` tag helper component, `MyTagHelper`.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  see [this comment](https://github.com/aspnet/Docs/issues/4033#issuecomment-325042283) 
Need a sample that shows how to include JavaScript/CSS in a Razor Page (code should be the same for MVC view).

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson Please check this sample. https://github.com/fiyazbinhasan/TagHelperCompoenentSample

**Comment by NTaylorMullen** [comment]
The primary goal of TagHelperComponents was two fold:
1. Enable TagHelper library authors to add TagHelpers that run on a specific set of tags without requiring a user to `@addTagHelper` their bits. In the default case a library author can add a BodyTagHelper that injects scripts, css, basically any pre-requisites for the library to function properly.
2. Enable dynamic TagHelper on specific tags by adding/removing from the component list (this is covered in the article).

Should add info about 1

**Comment by fiyazbinhasan** [comment]
@NTaylorMullen @Rick-Anderson reorganized the article a little bit. Can you take a look, please? Thanks. 
https://github.com/fiyazbinhasan/TagHelperCompoenentSample

**Comment by Rick-Anderson** [comment]
@NTaylorMullen quick review please so we can get this documented.

**Comment by Rick-Anderson** [comment]
cc @scottaddie

**Comment by Rick-Anderson** [comment]
@jbagga @NTaylorMullen please review this sample for use in Tag Helper component article.

**Comment by NTaylorMullen** [comment]
The sections and flow seems good. 👍

**Comment by scottaddie** [comment]
@fiyazbinhasan Can you please submit a PR with your work? That allows us to review the doc and apply the necessary edits. Thank you very much for your great work so far.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan Let me know if you need any help on the PR or want me to get it started.

**Comment by fiyazbinhasan** [comment]
I can make a PR by the end of this week if that's ok. @Rick-Anderson would be great if you can get it started.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  I'll get it started.

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson @scottaddie please check out the PR https://github.com/aspnet/Docs/pull/7935

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  merged.
