### ISSUE TITLE
Updating logging article to rc1

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#548]

**Comment by Rick-Anderson** [comment]
Additionally, it doesn't show how to log from a controller. Customer  question at https://docs.asp.net/en/latest/fundamentals/logging.html#comment-2379245737

Console couldn't display when running under IIS Express. I go to log folder of IIS Express (/%userprofile%/Documents/IISExpress/logs) of that project but still not see my log.

**Comment by GuardRex** [comment]
@Rick-Anderson Hey ... Happy Thanksgiving to you and @danroth27! Funny you said something about this one ... I was just looking at http://www.tugberkugurlu.com/archive/asp-net-5-and-log-correlation-by-request-id when you posted.
