### ISSUE TITLE
Servers > ANCM UE pass

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5490]
https://docs.microsoft.com/aspnet/core/fundamentals/servers/aspnet-core-module

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie Let's consider reducing the use of the acronym "ANCM" for "ASP.NET Core Module" in this topic. Note that I plan to *reduce* its use ... not eliminate its use.

* It's only rarely used in topics outside of this topic:
   * static-files.md: 2
   * windowsauth.md: 1
   * nano-server.md: 0 (used as part of a script name)
* After the initial reference to the "ASP.NET Core Module" in a section, it's satisfactory to just use "the module" thereafter.
* It's not the name of the module file in IIS (*aspnetcore.dll*) or the name shown in the *Modules* list ("AspNetCoreModule").
* It's not used on the .NET Downloads page or when running the hosting bundle installer.
* Outside of our topics and GH issues, "ancm" doesn't provide relevant results on the first few pages of Google search results.
* Should we be adding yet another acronym to the pantheon of acronyms in .NET 😓 only really useful for IIS insiders? The more acronyms there are, the more cryptic technology becomes.

**Comment by Rick-Anderson** [comment]
AFAIK you need approval - see [this](https://gist.github.com/klaaspieter/12cd68f54bb71a3940eae5cdd4ea1764).

TAWYG!
(Totally Agree With You Guys)

**Comment by guardrex** [comment]
It seems to me that this topic isn't a good spot to halfheartedly duplicate what's in the *Hosting on IIS* topic.

> This section provides an overview of the process for setting up an IIS server and ASP.NET Core app. For detailed instructions, see [Host on Windows with IIS](#).

Why? ... Why not just tell the reader to go access the *Hosting on IIS* topic and the module config reference, where the content is complete (including security coverage)?

I see a few gems in here that should be moved over to the *Hosting on IIS* and module reference topics, but I recommend some of these sections be removed.

This topic should probably just describe the basics of the module (what it is and what it does) and link out to our best coverage for using the module. Other than showing a few lines of code, the sample isn't valuable.
