### ISSUE TITLE
SignalR - Using HubContext to send messages to clients

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#5493]
Filing this for tracking since we've had some customer questions about it, this is in the medium-priority band of SignalR topics (along with scale-out and auth). Anecdotally, most SignalR users are just looking to use it to send notifications to users when an action in their standard MVC/Razor Pages app occurs.

We should have a guide for inject the `HubContext<THub>` type into an MVC controller (or other middleware) and using it to send notifications to clients.

**Scenario**: When one user performs an action, you want to notify all other users of that action

**High-level Outline**

1. Create a Hub class called `Notifications` with no methods (there's no need for any methods in this scenario, the Hub is just a name)
2. Map it to a path in `.UseSignalR`
3. In JS code, connect to the hub and attach a handler for the `Notify` method that updates the UI (maybe just by popping an `alert` dialog) with the notification text
4. Create an MVC controller action to "do the thing" that all users should be notified of.
5. In the controller, inject `IHubContext<Notifications>`
6. In the action method that does the thing, use the `.Clients.All.SendAsync` method on the `IHubContext` to send `Notify` to all clients, with a notification text as the payload.

**Comment by anurse** [comment]
cc @rachelappel @Rick-Anderson for visibility. Just something to keep on the queue for the medium-term (after the high-pri preview 1 getting started docs)

**Comment by anurse** [comment]
Pinging this, we've gotten more customer questions about how to use this. Often these customers are porting ASP.NET SignalR applications and using `GlobalHost` so this is also related to https://github.com/aspnet/Docs/issues/6463

**Comment by scottaddie** [comment]
Fixed by https://github.com/aspnet/Docs/pull/7005
