### ISSUE TITLE
Windows Authentication - Configure AccessDeniedPath

### ISSUE THREAD

**Issue by Trcx528** [aspnet/Docs#5494]
When an authorization policy fails a completely blank page is returned when using windows auth.  With other authentication options, like cookie authentication, one can configure an AccessDeniedPath to redirect a user too in this scenario.  What is the equivalent for windows authentication?   The [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?tabs=aspnetcore2x) seems to gloss over this detail.

**Comment by scottaddie** [comment]
@HaoK Any ideas?

**Comment by HaoK** [comment]
@Tratcher what are people supposed to do when windows auth fails?

**Comment by HaoK** [comment]
I think they probably can just do the equivalent manually...  check for authZ failure, and redirect to the "AccessDeniedPage".  Sound reasonable @blowdart ?

**Comment by blowdart** [comment]
I presume you're getting a 403 status? I'm not sure what Windows auth would do at this point to be honest, but yea a redirect works.

**Comment by Tratcher** [comment]
You could use the StatusCode middleware to provide content. I don't recommend redirecting, you'd loose the protocol 401/403 semantics.

**Comment by blowdart** [comment]
Ah, I didn't mean redirect as in HTTP redirect :) I figured some magical inline redirect

**Comment by Tratcher** [comment]
Ah, yeah, the StatusCodes middleware will do that for you.

**Comment by Trcx528** [comment]
Yes, I am getting 403 status.  I was able to configure the StatusCodePages middleware to add the desired error pages.  I do feel like this needs to be noted in the documentation somewhere, even just a link to the StatusCodePages middleware.  Otherwise the documentation feels incomplete.
