### ISSUE TITLE
Using Commands

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#55]
ASP.NET 5->.NET Execution Environment (DNX)->Using Commands
- What is a command?
- Using commands in your project 
  - Examples: web, kestrel, test, ef?
- Running commands using dnx.exe
  - dnx [command]
  - dnx run
- Global commands
  - Installing
    - Done by package ID
    - Note: only global NuGet.Config is used
    - Option to override (`--overwrite`)
  - Running
    - Always run with the active DNX
  - Uninstalling
    - Done by command name
  - Built-in global commands (user-secrets, sqlservercache)
- Building and publishing global commands
  - Create a new DNX Console app (ref existing article)
  - Define a command in commands section
  - Build as a package (dnu pack or option in VS)
  - Publish to your feed

**Comment by okaram** [comment]
Is anybody writing this ? Do you need help ?

**Comment by danroth27** [comment]
This isn't currently assigned to anyone. If you would like to help out with this article that would be great! 

The idea with this article it show creating a Console App (Package) in VS2015, publishing it to NuGet and then consuming it as a global or project-level command.
