### ISSUE TITLE
Potential problem with OPS build

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5503]
@Rick-Anderson 

For PR: https://github.com/aspnet/Docs/pull/5500

### Built with no warnings ...........................

![capture1](https://user-images.githubusercontent.com/1622880/36338962-9d158b3a-1380-11e8-8742-e5f34e5fa038.PNG)

### The email claims otherwise ...........................

![capture2](https://user-images.githubusercontent.com/1622880/36338923-c79b22c6-137f-11e8-8a38-4fd3137c2993.PNG)

### Clicking to open the report yields ...........................

![capture3](https://user-images.githubusercontent.com/1622880/36338964-a19f4844-1380-11e8-8b1e-012d87143478.PNG)

... but those were removed and merged on https://github.com/aspnet/Docs/pull/5394.

**Comment by Rick-Anderson** [comment]
It's not showing warnings now.

**Comment by guardrex** [comment]
It looked like it built fine in the GH UI as soon as I put it in. I opened here to show the email. I'll close now that you've seen it in case it's worthy of an internal issue.

**Comment by guardrex** [comment]
@Rick-Anderson @scottaddie It just did this again on https://github.com/aspnet/Docs/pull/5531, which was a simple link change in a topic. It sends a warning email message. The build report claims that there are bad links, but those files were removed on #5394 over a week ago.

![capture](https://user-images.githubusercontent.com/1622880/36552029-8d69d82a-17be-11e8-9a96-19845844e993.PNG)

![capture1](https://user-images.githubusercontent.com/1622880/36552037-90b1d348-17be-11e8-91ec-82f50df35789.PNG)

**Comment by Rick-Anderson** [comment]
@guardrex  next time this happens keep the PR open, paste the email in this issue and ping me. I'll open an issue with the tools team.

**Comment by guardrex** [comment]
Ok ... :+1:

**Comment by guardrex** [comment]
I haven't seen this behavior recently. I'll reopen this issue with the details (and leave the PR open) if it happens again.
