### ISSUE TITLE
Describing the hosting bundle installer on the .NET Downloads page

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5505]
Over time, I noticed devs arriving on Slack wondering about the purpose of the "Windows Server Hosting (exe)" installer on the .NET Downloads page: https://www.microsoft.com/net/download/windows

![capture](https://user-images.githubusercontent.com/1622880/36346149-d3e7f444-13fe-11e8-82e1-30985d33c51d.PNG)

Recommendation: Add a tooltip (and possibly a link)

![capture1](https://user-images.githubusercontent.com/1622880/36346210-bcf0dce6-13ff-11e8-82df-52efddc5b885.PNG)

The tooltip text could read something like:

> The .NET Core Windows Server Hosting bundle installs the .NET Core Runtime, .NET Core Library, and the ASP.NET Core Module. The module creates a reverse proxy between IIS and the Kestrel server on Windows platforms.

If the text is linked, it could link to https://docs.microsoft.com/aspnet/core/host-and-deploy/iis#install-the-net-core-windows-server-hosting-bundle

**Comment by guardrex** [comment]
They totally revamped the .NET Downloads page, and there isn't a hosting bundle installer download link at all now. If it stays that way, there's nothing actionable here. I'll re-open if they put the link back later.

**Comment by guardrex** [comment]
Re-opening: This is still an issue.

On `https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.6`.

Naming: They changed the name of it. It has traditionally been called the ".NET Core Windows Server Hosting bundle," and the downloads page used to call it "Windows Server Hosting (.exe)." Now, it's called "Server Hosting Installer." Seems a little scary to me to have the name shift even further away from the doc.

Anyway ... I recommend that the "i" (information) popup and a link to the doc be used with this link on the .NET Downloads page.

![capture](https://user-images.githubusercontent.com/1622880/37475450-bedbacb6-2840-11e8-87b3-0734d3e2f6a5.PNG)

**Comment by guardrex** [comment]
RE: Naming

This installer (and the hosting bundle) aren't really 100% "Windows Server," per se. This install works on Windows desktop. I wonder if the bundle could be renamed it to just "Windows Hosting bundle" that has a "Windows Hosting Installer" on the downloads page (or anything really that removes the word "server" from the name).

cc/ @joeloff

**Comment by guardrex** [comment]
@rowanmiller This was a separate idea that I had that would alleviate some confusion for devs as to what the hosting bundle installer installs. They show up on Slack asking what it is and what it installs because they haven't seen the IIS or ANCM topics but they see it in the list on that page.

:point_up: See the OP at the top for my idea. If this isn't something that you/they want to do, then I'll close this issue.

**Comment by rowanmiller** [comment]
Yep the (i) bubble makes total sense. We should probably have it for the ASP.NET Core Runtime too, as I don't think it's 100% obvious what that is for either.

Windows Hosting Bundle makes sense to me as the name on the download page. Not sure who else should agree on this before we make the change - @richlander @leecow any thoughts from you?

We also have "Server Hosting Binaries" for Linux - should that be renamed too?

**Comment by guardrex** [comment]
> Windows Hosting Bundle

That sounds great to me ... that's exactly what it is. I like the uppercase "Bundle," too. In the past, they had the word "bundle" in lowercase for some reason, so they had us calling it the "Windows Server Hosting bundle." Idk why "bundle" was lowercase. @shirhatti @Tratcher do u know?

> We also have "Server Hosting Binaries" for Linux - should that be renamed too?

"Linux Hosting Binaries" ??? ... sounds good anyway.

**Comment by Tratcher** [comment]
Unknown. @shirhatti ?

**Comment by shirhatti** [comment]
No idea about the casing.

**Comment by leecow** [comment]
I'm leaning toward something like '.NET Core Hosting Bundle' for the name as it is available on Windows and Linux. We do need to clean up the docs to get everything to align and add Linux info.

**Comment by rowanmiller** [comment]
I like that - seems clean

**Comment by rowanmiller** [comment]
Any push back on me updating the .NET Website to use `.NET Core Hosting Bundle` for the download names?

**Comment by guardrex** [comment]
I'll update the aspnet/Docs to match when the change goes live.

**Comment by rowanmiller** [comment]
When it's in the context of .NET Core, do we think it's OK to just use `Hosting Bundle`? E.g. on http://localhost:4689/net/download/dotnet-core/runtime-2.0.6 we don't prefix anything else with .NET Core.

**Comment by guardrex** [comment]
Seems fine to me. When I update the docs, I'll use ".NET Core Hosting Bundle" in the section title, but I'll just call it the "Hosting Bundle" in the text under the heading.

**Comment by guardrex** [comment]
@rowanmiller I'll use this issue to track the work in the aspnet/Docs repo. I'll ping u on the PR.

*This is blocked until the .NET site change is live.*
