### ISSUE TITLE
Issues i found at my Test of the Template

### ISSUE THREAD

**Issue by atmike** [aspnet/Docs#5509]
Hi I tested the latest version of the Template and found the following problems
1. Debugging Typescript is no longer possible within Visual Studio
2. References from package.json are no longer shown under references because you moved the file into the ClientApp folder
3. With the old template it was possible to switch the development into IIS. But I wasn't able to get that up and running.
May be that helps you 
Best regards Michael

**Comment by guardrex** [comment]
Hello @atmike ... this is the documentation repo. For templating, close this issue and open this over in the repo at :point_right: https://github.com/aspnet/templating.

**Comment by Rick-Anderson** [comment]
@atmike  and specify version when you do. Thanks
