### ISSUE TITLE
RP conventions features update

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5520]
mvc/razor-pages/razor-pages-convention-features.md 
https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/razor-pages-convention-features

[IPageHandlerModelConvention](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/ApplicationModels/IPageHandlerModelConvention.cs)

**Comment by guardrex** [comment]
Cross-reference:
* https://github.com/aspnet/Mvc/issues/6935
* https://github.com/aspnet/Mvc/pull/7144

**Comment by guardrex** [comment]
@pranavkm Looks like this should be focused on [IPageHandlerModelConvention](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/ApplicationModels/IPageHandlerModelConvention.cs) ... not `IPagePropertyModelConvention`.

**Comment by pranavkm** [comment]
@guardrex might be good to add a quip about property model \ parameter model conventions. Sort of along the lines of https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1#sample-modifying-the-parametermodel. For most parts, you could copy the docs \ samples verbatim.

**Comment by guardrex** [comment]
@pranavkm Where we stand today with this topic is that it focuses on conventions that implement `IPageConvention` ... so it's very RP `options.Conventions`-feature focused.

Given this issue is only to cover new 2.1 `IPageConvention`-based features (and there seems to be only one), let's address that :point_up: separately. https://github.com/aspnet/Docs/issues/5958
