### ISSUE TITLE
@GetAntiXsrfRequestToken()

### ISSUE THREAD

**Issue by pethumishara** [aspnet/Docs#5525]
How to call '@GetAntiXsrfRequestToken()' from external js file

**Comment by guardrex** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery
*aspnetcore/security/anti-request-forgery.md*

https://github.com/aspnet/Docs/blob/master/aspnetcore/security/anti-request-forgery/sample/MvcSample/Views/Home/Ajax.cshtml

@Rick-Anderson Should that show `@GetAntiXsrfRequestToken()` set into the value of a hidden field, then have the script read the value from there? That would work for both inline and external JS scenarios.

```cshtml
<input type="hidden" id="RequestVerificationToken" name="RequestVerificationToken" 
value="@GetAntiXsrfRequestToken()">

...

{
    "RequestVerificationToken": $('#RequestVerificationToken').val()
},
```
... I'd prefer to show `document.getElementById('RequestVerificationToken').value`, but jQuery is in use in the sample. At least the reader would see that the value is in a hidden field, and then hopefully they can work out how to read the value of a hidden field in JS if not using jQuery.

If you'd like me to update it, assign it to me, and I'll square it away today.

**Comment by Rick-Anderson** [comment]
@HaoK  is this something we should add to the docs? cc @scottaddie

**Comment by HaoK** [comment]
@blowdart thoughts?

**Comment by blowdart** [comment]
You can avoid jquery if you like, but yea it should be in the docs.

**Comment by scottaddie** [comment]
+1 to not using jQuery. Prefer `document.getElementById`.
