### ISSUE TITLE
Configuring status code pages 

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Docs#5536]
Please read the following:
https://github.com/aspnet/Home/issues/2862#issuecomment-364335927

Then:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling#configuring-status-code-pages

The first and second sentence are basically confusing:
"By default, your app won't provide a rich status code page for HTTP status codes such as 500 (Internal Server Error) or 404 (Not Found). You can configure the StatusCodePagesMiddleware by adding a line to the Configure method:"

A comment has even been added to the docs stating that this is confusing and I agree as it confused me too.

Are you happy for me to create a PR basically stating what Tratcher mentioned as the second sentence so that it reads something like:
"By default, your app won't provide a rich status code page for HTTP status codes such as 500 (Internal Server Error) or 404 (Not Found). If the app code generates a 500 it will be handled, but your app is generating an exception, not a 500. The 500 you see is a last ditch effort from the server to handle the exception. You can configure the StatusCodePagesMiddleware by adding a line to the Configure method:"

Will reword, this is just to give an idea of what the PR will contain.

**Comment by guardrex** [comment]
@Matthew-Bonner Go ahead. We might touch it up a bit to comply with grammar and style guidelines; but yes, please do go ahead and submit a PR. We'd be happy to have it. :+1:
