### ISSUE TITLE
Introduction to Identity - 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5537]
[Introduction to Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?tabs=visual-studio%2Caspnetcore2x)

per customer, for the 2.x version, 
` options.Cookie.Expiration = TimeSpan.FromDays(150);`   //  should be
`options.ExpireTimeSpan = TimeSpan.FromMinutes(30);`

@HaoK  is that correct? cc @scottaddie

**Comment by AlexInAk** [comment]
If I understand it correctly, based on [aspnet security #1293](https://github.com/aspnet/Security/issues/1293), `options.Cookie.Expiration` essentially gets set to null later in the pipeline:

https://github.com/aspnet/Security/blob/2b1dab2efed9d3ba74fa082d9f01ccbd1d05bd43/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L180

**Comment by HaoK** [comment]
Yeah that's correct, the underlying Cookie.Expiration property is not used/ignored for CookieAuthentication since that property is dealing with the HttpCookie, not the authentication cookie (confusing I know).
