### ISSUE TITLE
Add more samples with localization and routing

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/Docs#5544]
There's no official example on how to setup routes using `Microsoft.AspNetCore.Localization.Routing`. Every site I visit shows different method and most of these articles were written for version 1.x

Basically what if I want to make URL like this:

mywebsite.com/en/
en.mywebsite.com/

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  can you explain how to do this?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg can you explain how to do this?

**Comment by ryanbrandenburg** [comment]
In this particular area nothing that I'm aware of has changed since 1.x. Examples [such as this](https://joonasw.net/view/aspnet-core-localization-deep-dive) (Ctrl+F RouteDataRequestCultureProvider) represent out best advice in this area.

**Comment by Rick-Anderson** [comment]
replaced by #9252
