### ISSUE TITLE
version selector collision with "Your feedback about this content is important. "

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#556]
![capture3](https://cloud.githubusercontent.com/assets/3605364/10621582/80c1740a-7736-11e5-8076-67a6627637ef.PNG)

1. https://docs.asp.net/en/latest/index.html
2. scroll down until "Your feedback about this content is important. Let us know what you think. Yes No " is displayed. It's obscured by the version selector.

Repro's on FF/IE/Edge/Chrome

**Comment by danroth27** [comment]
@terrimorton What's the status of getting this fixed and adding back the helpfulness UI?

**Comment by danroth27** [comment]
This has been fixed.
