### ISSUE TITLE
explain Asp.Net Core Middleware's  `Invoke` and `InvokeAsync` 

### ISSUE THREAD

**Issue by John0King** [aspnet/Docs#5569]
From https://github.com/aspnet/Home/issues/2907

in [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?tabs=aspnetcore2x) ,  it use `public async Task Invoke(HttpContext httpContext, IMyScopedService svc)`, 

in [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility) it use `public async Task InvokeAsync(HttpContext context, AppDbContext db)` 

and `InvokeAsync` is support after *[2.0.0-preview1](https://github.com/aspnet/HttpAbstractions/releases/tag/rel%2F2.0.0-preview1)* , but not tell people.

please update the document about this change

**Comment by guardrex** [comment]
Thanks for reporting @John0King! I'll get this fixed soon.
