### ISSUE TITLE
Update host on Linux with Nginx

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#5575]
The doc currently advises you to build Nginx from source if you want the http_ssl_module. Looks like that is no longer required if you install nginx from the official PPA (at least 16.04).

https://www.nginx.com/resources/wiki/start/topics/tutorials/install/#official-debian-ubuntu-packages

We should simplify the doc and no longer ask folks to build nginx from source but instead install directly from the official PPA

**Comment by guardrex** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx
host-and-deploy/linux-nginx.md

@scottaddie I was just developing a To Do list, but ur prob more familiar with Nginx.

1. Under *Install Nginx*, change the bash from `sudo apt-get install nginx` to the five lines of code shown in *Ubuntu PPA* at https://www.nginx.com/resources/wiki/start/topics/tutorials/install/#official-debian-ubuntu-packages with similar lead-in language and link that content for more info. Should it also add the link for obtaining development versions? ... https://launchpad.net/~nginx/+archive/ubuntu/development
1. Under *Securing Nginx*, remove the note about building Nginx.
1. Remove the *Download the source and install the build dependencies* section.
1. Remove the *Change the Nginx response name* section.
1. Remove the *Configure the options and build* section. I presume the other modules are present ... the ones shown in addition to *http_ssl_module*?

**Comment by scottaddie** [comment]
@guardrex Feel free to take this one if you have time. I'm not super familiar with Nginx.

**Comment by guardrex** [comment]
Sure thing. I'm still trying to learn more about Nginx (when I have time 😅).

@shirhatti Let me know how that list :point_up: looks for action items here.

**Comment by shirhatti** [comment]
> Should it also add the link for obtaining development versions?

My preference is no.

> Under Securing Nginx, remove the note about building Nginx.

👍 

> Remove the Download the source and install the build dependencies section.

👍 

> Remove the Change the Nginx response name section

👍 

 > Remove the Configure the options and build section. I presume the other modules are present ... the ones shown in addition to http_ssl_module?

For the life of me I can't remember why we needed the stream module or PCRE. I can't see it used anywhere in our suggested configuration. If you were giving it a shot, I'd probably verify this before I sink any time into this doc.

**Comment by guardrex** [comment]
Sure ... I can do that. I'd like to give it shot with the revised steps and make sure it all works as advertised and pick up some additional experience along the way. For the test app, I plan to use our basic Razor Pages template with HTTPS enabled but not with auth or a dB (at this time).

Timing: I'll be out next week, so this one prob needs to wait until I get back. I can prob still hit this sprint tho.
