### ISSUE TITLE
UE pass on Host in a Windows Service doc

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#5578]
https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service

- [x] UE edit
- [x] ~Update template name referenced in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?tabs=aspnetcore2x#prerequisites~ No longer relevant.
- [x] Update sample for 2.1 (`CreateWebHostBuilder` approach).
- [x] Remove `UseApplicationInsights` calls.
- [x] ~Display necessary `using` statements in code snippets.~ They're in the sample app.
- [x] ~Address customer comments~ Except for the "namespace" remark, they're not actionable, and the remark on namespaces is covered by the sample app.

**Comment by guardrex** [comment]
@scottaddie Some of this work was covered by the updates on https://github.com/aspnet/Docs/pull/6860 and some of the patches thereafter. If you want to transfer this to me and email me the reader comments, I'll have the bandwidth later to react to the comments and take a look at the `using` statement item.

**Comment by scottaddie** [comment]
@guardrex Assigned and emailed you the verbatim / SkyRay info.
