### ISSUE TITLE
Missing screenshots in PrecompiledViews doc

### ISSUE THREAD

**Issue by dodegaard** [aspnet/Docs#5579]
I just reviewed the doc on PrecompiledViews and the screenshots or code blocks for this are missing and simply say [!code-xml]

Thanks!

https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-compilation.md

**Comment by guardrex** [comment]
@dodegaard The built doc is here :point_right: https://docs.microsoft.com/aspnet/core/mvc/views/view-compilation?tabs=aspnetcore2x

**Comment by guardrex** [comment]
I'm going to go ahead and close, but we can reopen for discussion if you have additional questions.
