### ISSUE TITLE
update Get Started with Entity Framework 7 using ASP.NET MVC 6

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#558]
It's beta5, update

**Comment by plitwin** [comment]
I'd like to work on this one.

**Comment by plitwin** [comment]
@Rick-Anderson I can't seem to get this line to compile: if (context.Database.AsRelational().Exists()) The compiler complains about the AsRelational() method and I can't figure out what replaces it in Beta8 or if that if statement is even needed anymore.

**Comment by Rick-Anderson** [comment]
@rowanmiller - Beta5 used if (context.Database.AsRelational().Exists())  - what's the Beta8 version?

**Comment by rowanmiller** [comment]
What's the scenario you are trying to achieve. Exists is hidden away a bit deeper but we have top level APIs to achieve most of the higher level tasks where this API is needed.

**Comment by Rick-Anderson** [comment]
@rowanmiller  see http://docs.asp.net/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html

public static class SampleData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            var context = serviceProvider.GetService<BookContext>();
            if (context.Database.AsRelational().Exists())
            {

**Comment by robbert229** [comment]
Guys I already have a RP in for this... Its been there for a while. https://github.com/aspnet/Docs/pull/582

**Comment by Rick-Anderson** [comment]
@robbert229  look great, next time ping the authors too :--) I gave it a :shipit:

**Comment by rowanmiller** [comment]
I commented on the PR with suggestions for this piece of code

**Comment by plitwin** [comment]
@robbert229 Oh well. Darn. Wish you would comment when you are working on something but thanks for letting me know.

**Comment by robbert229** [comment]
Sorry about that, I'm new to open source.
