### ISSUE TITLE
The startup page delivers a very different page compared to the one in the web documentation

### ISSUE THREAD

**Issue by jecalderon** [aspnet/Docs#5585]
## Issues with Existing Topics

If the issue is a simple typo or similar correction, just submit a PR.
Otherwise, let us know what's wrong or what we should improve. Include a
link to the topic.

I am new to MVC Core and DOT NET.  I downloaded the latest VS 2017 .The MVC tutorial do not look and feel VS 2017.  I created the MVCMovie solution and project. Here is a screenshot

The web documentation shows that after creating the MVC page shall render this

http://prntscr.com/ij6gf0

but instead getting this page

http://prntscr.com/ij4inv

When entering f5 or the start bottom in top , I get this error

http://prntscr.com/ij4j8g

**Comment by Rick-Anderson** [comment]
Your first image is the web browser of the created app. Your second is Visual Studio.

I've seen that error before. You need to see
![image](https://user-images.githubusercontent.com/3605364/37073352-793d75c2-216a-11e8-8448-33e196cf0b06.png)

Not start.

Did you install the latest released version? If not, that's what you should be using.
Why are you doing the MVC tutorial and not the Razor tutorial?
Try exit restart VS. If that doesn't work, try creating a new project and running it.

**Comment by guardrex** [comment]
This looks like a VS configuration problem. I'm going to fix the instruction at the top of the tutorial because everywhere we instruct how to use VS we call for .NET Core cross-platform development, which might explain why @jecalderon hit this.
