### ISSUE TITLE
Migrating an Existing NuGet Package Project

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#56]
ASP.NET 5->.NET Execution Environment (DNX)->Migrating an Existing NuGet Pacakge to Support .NET Core
- Why use DNX to build your NuGet packages?
- Cross-compilation
- Adding support for .NET Core
- Building portable libraries

**Comment by jimschubert** [comment]
The [docs for *Migrating an Existing NuGet Package Project*](https://docs.asp.net/en/latest/dnx/migrate-package.html) link to this issue and say "If you would like to review early drafts and outlines of this topic, please leave a note with your contact information in the issue."

What contact info would you need if I would like to review drafts and outlines?

**Comment by danroth27** [comment]
This topic will be covered as part of the .NET docs now that we are moving to the new [.NET CLI](https://github.com/dotnet/cli). Closing this issue.
