### ISSUE TITLE
Broken links in Processing Unhandled Exceptions page

### ISSUE THREAD

**Issue by guitarzan** [aspnet/Docs#5616]
The document [Processing Unhandled Exceptions](https://docs.microsoft.com/en-us/aspnet/web-forms/overview/older-versions-getting-started/deploying-web-site-projects/processing-unhandled-exceptions-cs) has two links at the top, "Download Code or Download PDF", both of which are broken.

This affects both CS and VB versions.

**Comment by guardrex** [comment]
I'll see if I can track the resources down and fix the links this evening.
