### ISSUE TITLE
Remove use of Html.Partial and replace with Html.PartialAsync

### ISSUE THREAD

**Issue by scottsauber** [aspnet/Docs#5636]
[Html.Partial has been deemed unsafe](https://github.com/aspnet/Mvc/issues/7083) and on the standup it's been mentioned that it will be removed in a future release.

It's mentioned 12 times on the Partial docs - https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial

I'm proposing to convert all these to Html.PartialAsync.

Happy to submit a PR for this if you want this change made.

**Comment by Rick-Anderson** [comment]
@dougbu  please review/approve suggested replacement of [Html.Partial deemed unsafe](https://github.com/aspnet/Mvc/issues/7083) with `Html.PartialAsync`.

**Comment by scottsauber** [comment]
Sounds good.  I'll submit a PR tonight.  

Although, if some first-timer is reading this and wants this issue, they can feel free to take it.  Happy to give it up and it's a fairly simple change.
