### ISSUE TITLE
Test XmlDsigXPathTransform sample

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5641]
See [XmlDsigXPathTransform Class
](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.xmldsigxpathtransform?view=netframework-4.7)

test sample.  Copy from [this bug](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/200269)

----------------------- 
Problem Description 
----------------------- 
Description: After MS16-035 security update this code from MSDN doesn't work: 

`[Edit: here is the dotnet link]`  See [XmlDsigXPathTransform Class
](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.xml.xmldsigxpathtransform?view=netframework-4.7)

https://msdn.microsoft.com/library/system.security.cryptography.xml.xmldsigxpathtransform.xmldsigxpathtransform%28v=vs.110%29.aspx 

`[Edit - not needed to repo]`
Repro Steps:- Install MS16-035 
- compile and execute exampkle from: https://msdn.microsoft.com/it-it/library/system.security.cryptography.xml.xmldsigxpathtransform.xmldsigxpathtransform%28v=vs.110%29.aspx 

Impact:Unable to verify XML signed document

**Comment by Rick-Anderson** [comment]
@rpetrusha  This is easy to run and verify you get 
```
New XML file created.
XML file signed.
Verifying signature...
The XML signature is not valid.
```

Where should I move this bug?

**Comment by rpetrusha** [comment]
@Rick-Anderson, I don't think it needs to be moved -- just assign it to me. (I don't recall having seen it earlier, though -- but now I know to look for it.)

**Comment by Rick-Anderson** [comment]
@rpetrusha looks like I can't assign it to you because you don't have write perm in this repo. Should I request that you be added to this repo?

**Comment by rpetrusha** [comment]
In looking at it, @Rick-Anderson, it strikes me that the issue should really be in the dotnet/docs repo, rather than here.  Why don't we close this issue, and I'll open a new issue there?

**Comment by Rick-Anderson** [comment]
@rpetrusha  agreed.

**Comment by Rick-Anderson** [comment]
moved to https://github.com/dotnet/docs/issues/4598
