### ISSUE TITLE
signalr/clients ASP.NET Core SignalR JavaScript client doc

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5646]
Previous version doc: https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client

Outline:

- Setup Client 
- Establish a Connection
  -includes cross domain connection
  -specify transport method
- Define client-side methods for hub to call
- Handle connection lifetime events
- Handle errors
- Client-side  logging

There's no generated proxy yet so we can add that part in a future PR.

**Comment by rachelappel** [comment]
@anurse Do we want how to send query string params in this doc?

**Comment by anurse** [comment]
No, that's not necessary in this doc IMO
