### ISSUE TITLE
aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events | Configure custom crypto providers 

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5648]
when there is a failover of the node 1(on which signalr is hosted), the client is not able to reconnect to the second live node (node 2). 
The client gets a 400 Bad request error “the ConnectionId is in incorrect format”

this is about how to configure custom crypto providers when scaling out in environments that don’t rely on machineKey (IIS) or DPAPI (AD accounts).

**Comment by rachelappel** [comment]
https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events

**Comment by bradygaster** [comment]
i think this one is safe to close, as this is in the non-Core area and we're effectively concentrating on the core area moving forward. If we uncover reasons this needs to be re-opened we can cross that bridge when we come to it.
