### ISSUE TITLE
Explain how to bind properties on Razor Pages GET requests

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#5657]
A customer was reading through the following section:
https://docs.microsoft.com/aspnet/core/mvc/razor-pages/#writing-a-basic-form

He wondered how to bind properties on GET requests. The current text says:
> Razor Pages, by default, bind properties only with non-GET verbs.

A note should be added to explain how to bind properties on GET requests.

**Comment by guardrex** [comment]
@Rick-Anderson shot this one down. https://github.com/aspnet/Docs/issues/4655
