### ISSUE TITLE
Update sociallogins to highlight additional providers in aspnet-contrib

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#566]
add  that additional providers for OAuth2/OpenID2 can be found on aspnet-contrib: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers and https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers

**Comment by PinpointTownes** [comment]
Don't hesitate to ping me if you need additional details about the OAuth2/OpenID2 providers or the aspnet-contrib initiative in general :clap:
