### ISSUE TITLE
Add the bootstrap 4.0.0 theme when available

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5671]
*Microsoft Ajax Content Delivery Network*
https://docs.microsoft.com/aspnet/ajax/cdn/overview
*aspnet/ajax/cdn/overview.md*

```
- http://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/css/bootstrap-theme.css
- http://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/css/bootstrap-theme.css.map
- http://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/css/bootstrap-theme.min.css
```

**Comment by guardrex** [comment]
@ChrisSfanos Can you help? The links are pulling down the 3.3.7 theme.

**Comment by guardrex** [comment]
@Eilon Do u know who we can ask about these aspnetcdn.com links? They're pulling down 3.3.7 instead of 4.0.0.

**Comment by Eilon** [comment]
@guardrex sorry I'm not clear on what exactly the problem is. I took a look at a few of the links and they seem to point to the right stuff?

**Comment by guardrex** [comment]
... and the answer is ... drum roll please 🥁 ... **the separate theme was removed from 4.0!**

> Replaced the separate optional theme with configurable options via SCSS variables

http://v4-alpha.getbootstrap.com/migration/#global-changes

Closing ... we're good!

**Comment by Eilon** [comment]
😄
