### ISSUE TITLE
Missing profile file on OSX and out of date nuget package in OSX sample

### ISSUE THREAD

**Issue by PureKrome** [aspnet/Docs#568]
Hi team :wave:

I've noticed two places that could be improved with some extra sentences.

### DNVM fails to install on newly installed OSX machines.

When trying to [Install the DNVM Manager](http://docs.asp.net/en/latest/getting-started/installing-on-mac.html#install-the-net-version-manager-dnvm) on a totally new OSX machine (where the developer has _never_ had to goto the command line or even installed anything onto the new machine) an error occurs, failing the install of dnvm. 

The reason is because i don't have a `profile` thingy file created. eg simple answer: `touch ~/.bash_profile`.

I would like to submit a simple PR, adding some `note` about this.

### Beta7 is mentioned in ze doc's for the OSX getting started.

when the docs talk about [getting started with OSX and scaffolding with yeoman](http://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html#scaffolding-applications-using-yeoman) the `project.json` lists:

```c#
{
  "sdk": {
    "version": "1.0.0-beta7"
  }
}
```

this is a simple replace to `beta8`. I'm very happy to submit a PR for this.

Finally, when reading the docs, it also mentioned this...

>Create a folder for your solution and then add an src subfolder for your project source code.
> In your solution folder add a global.json file ...

and then run `yo aspnet` .. etc.

I'm not the smartest tool in the shed ... so I sorta got a bit confused when I followed these simple instructions but then noticed my code in some weird locations. I didn't feel right. So - I think another screen shot here would be awesome which shows `Finder` and all the files in the folders, etc.. so we can confirm what we're trying to do .. is what the docs are saying. A confirmation step.

I'm happy to also try and provide this in the same PR :)

SIDE NOTE: on a totally freshly formated OSX, installing VSCode and then running VSCode, Omnisharp isn't working .. cause it required Mono and that's not installed by default (at least on my vanilla El Cap).

Thanks team - looking forward to your thoughts.

**Comment by danroth27** [comment]
The dnvm install script will check if a bash profile exists and it it doesn't it will let you know and tell you how to create one. Since this is an edge case I think we can do without explicitly listing this step in the docs.

It looks like the beta7 code is no longer present.

We plan to add instructions to install Mono in the Mac installation instructions as it is currently required for VSCode and to build for dnx451.

**Comment by danroth27** [comment]
OS X instructions have been updated with Mono installation instructions.
