### ISSUE TITLE
Update libuv references in Kestrel docs

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#5695]
https://github.com/aspnet/Announcements/issues/296

Per the announcement, managed sockets are replacing libuv in Kestrel as of ASP.NET Core 2.1. Update the docs to mention this and that libuv is used in versions prior to that.

Affected docs:
- [x] https://docs.microsoft.com/aspnet/core/fundamentals/servers/
- [x] https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel

**Comment by scottaddie** [comment]
@guardrex This seems like something you'd enjoy. You want this one?

**Comment by guardrex** [comment]
> Transport Extensibility

> The current implementation of the underlying libuv connection semantics has been decoupled from the rest of Kestrel and abstracted away into a new Transport abstraction. While we continue to ship with libuv as the default transport, we are also adding support for a new transport based on the socket types included in .NET.

**Comment by guardrex** [comment]
References:

* https://github.com/aspnet/KestrelHttpServer/issues/2361
* https://github.com/aspnet/Universe/pull/959
* https://github.com/aspnet/KestrelHttpServer/pull/2392/files
* https://github.com/aspnet/KestrelHttpServer/issues/2360
