### ISSUE TITLE
Application Startup

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#57]
ASP.NET 5->Runtime->Application Startup
- Accessing and using available runtime services during Startup
- Startup class conventions and discovery
    - Assembly determined by config (Hosting:Application), otherwise application name
    - Class named `Startup` in any namespace
    - Can be static (but then you get no DI)
- `ConfigureServices`
    - Link to DI (#65)
    - Can return IServiceProvider for wiring up 3rd party IoC (reference DI topic)
    - Analogous to `app.UseServices(services => { services.AddMvc(); ...  })`
- `Configure`
    - Must be public and return void
    - Used to construct a middleware pipeline using `IApplicationBuilder`
        - Link to Middleware (#109) topic
- Link to [Environments](http://docs.asp.net/en/latest/fundamentals/environments.html) content with

**Comment by ardalis** [comment]
Given the name of this article, shouldn't it also talk a bit about Startup.cs? Or should there be two articles, one that talks about Startup.cs and one that talks about the ASP.NET request pipeline?

**Comment by danroth27** [comment]
> shouldn't it also talk a bit about Startup.cs?

Absolutely! This article should really be all about Startup.cs.

Feel free to take my short outlines as a starting point and then evolve them as appropriate. I make no guarantee that they are complete :smile:

**Comment by ardalis** [comment]
Awesome, thanks.

**Comment by vossad01** [comment]
I am not sure if this is the place to mention this, but I think some guidance/guidelines/intentions on what belongs in `ConfigureServices` versus `Configure` would be good.  The answer may be really simple, but I am struggling to see the right division myself at the moment.

For example with the MVC middleware, configuration is done in `ConfigureServices` and cannot be specified via a `UseMvc` overload.
```
services.Configure<MvcOptions>(
    options =>
        {
            //  ...
        } );
```

However, the Diagnostics middleware requires configuration happen in `Configure`:

```
app.UseErrorPage( new ErrorPageOptions { ShowCookies = true, ShowSourceCode = false } );
```

On the surface this seems inconsistent.  While I am sure consistency cannot be forced, an accepted convention would make it easier for users (developers) to know where or whether to do configuration when working with a new component.

I do think that overall the distinction between the two is useful, I just have not fully grokked what goes where.
