### ISSUE TITLE
bad link: You are not using the most up to date version of the library. 1.0.0rc1 is the newest version.

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#570]
to repro, use the version selector for Beta8 (or just click on http://docs.asp.net/en/1.0.0-beta8/) now click on  the [RC1 link](http://docs.asp.net/en/1.0.0-rc1/)

You are not using the most up to date version of the library. [1.0.0rc1](http://docs.asp.net/en/1.0.0-rc1/) is the newest version.

**Comment by shirhatti** [comment]
@Rick-Anderson Seems fine now. Do you still have this problem?
