### ISSUE TITLE
Create include to drive traffic from SignalR to SignalR Core

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5700]
See https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/index as an example.

Obviously mention the core version is in preview.

**Comment by rachelappel** [comment]
The whole doc? And isn't it redundant if there is already an include stating where the new docs are? This issue needs to be more clear.

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr needs something.

Probably remove **Questions and comments**
