### ISSUE TITLE
Should I create pull requests for contractions I see? (or shouldn't I)

### ISSUE THREAD

**Issue by pkellner** [aspnet/Docs#5705]
## General

I'm going through the VS Mac EF tutorial now and see a lot of contractions. @guardrex mentioned he had a contraction fixer.  This page (as well as the other similar ones for other OS's) have lot's of isn't's.  

https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api-mac.md

**Comment by guardrex** [comment]
The contractions are correct. We are using them.

**Comment by guardrex** [comment]
https://github.com/aspnet/Docs/pull/5216

**Comment by guardrex** [comment]
@pkellner I'm going to close ... If I understand correctly, you're wondering if we are supposed to be using contractions. The answer is 'yes.' Let me know if I misunderstood the ask, and we can re-open.

**Comment by pkellner** [comment]
@guardrex Nope, I thought you told me on the bus that you wrote a script that went through docs and changed things like "isn't" to "is not".  Maybe I think that is a contraction and I'm wrong or maybe I misunderstood what you told me.

**Comment by guardrex** [comment]
Oh, I see. It was the reverse ... my script created contractions ... going from "is not" 👉 "isn't" (#5216).
