### ISSUE TITLE
Source code for Visual Studio Mac and EF Example Confusing

### ISSUE THREAD

**Issue by pkellner** [aspnet/Docs#5711]
## General
The example source code for this article:

https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/start-mvc

has a commented out controller2 method that looks like it is used to test adding an record to the inmemory database.  Then, you can see the data using the controller not commented out.

I doubt someone new to asp.net will figure that out. I think it would be better to have the test for 0 records in the same controller that displays that data. You've already got the context there so it would just add one line (like initData()) to populate the data if it does not exist already.
IMHO of course.

**Comment by Rick-Anderson** [comment]
@pkellner  can you send me a link to the commented out controller2?

**Comment by pkellner** [comment]
I think this is the one I was referring to.

https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/first-web-api/sample/TodoApi/Controllers
