### ISSUE TITLE
Link updates

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5735]
Coming up on that time again. I have some good software that will find the offensive links (301/302/401/403/404).

However, I might whip up a 😵 *mad Rex script* 😵 that will update 301/302 links ✨ auto-magically :sparkles:.

... actually ... I think I have that somewhere on the hard drive! :smile:

**Comment by Rick-Anderson** [comment]
@tdykstra 	@scottaddie 	what's the right tools to look for bad links?

**Comment by guardrex** [comment]
Not that you asked *me*, but I recommend http://home.snafu.de/tilman/xenulink.html ... I'm I 😵? ... but it works *InSaNeLy* well. Also note that the problem with script-kitty approaches on the repo is that because the content validator thing throws errors instead of warnings, we can't script massive sets of changes on PRs now. *Just say'in!* ... but perhaps you (admins) can merge anyway. That's an avenue because at least in the 301 case, the links can be updated via a script a heck of a lot faster than by a *lowly human*.

**Comment by tdykstra** [comment]
> tools to look for bad links?

CATS -- https://contentqacats.azurewebsites.net/

**Comment by Rick-Anderson** [comment]
We should probably run CATS a couple every 6 months - at least.
Last CATS output had about 50% false positives - not too bad.
