### ISSUE TITLE
Either set English as default language or give us the option to save our language preferences

### ISSUE THREAD

**Issue by andre-ss6** [aspnet/Docs#5746]
Please. Please! This was a big issue with old docs: it always came in the language set by the User Agent using machine-translated text (which, I don't know if you're aware, is complete garbage) and there was no way to save your preferences. There were several suggestions with tens of upvotes on msdn UserVoice to change/improve that in some way. Now we have an entirely new Docs platform and you still do the same thing! 

I don't want to have to go through the hassle of switching languges/editing the url every time I visit the docs. If it is not possible to save language preferences, then English should be default. I may be _very_ wrong as I have no data behind me, but I feel like the vast majority of professional developers search in English anyway; And not only that: I want to see dev _things_ in English so I see standard error messages, for example, and not biased translated ones.

**Comment by Rick-Anderson** [comment]
scroll to the bottom of a doc page, click on the language to change it.
The loc team is working on better options.

![image](https://user-images.githubusercontent.com/3605364/37681387-a4b6d1d8-2c2a-11e8-8410-fe727eee55f6.png)

**Comment by andre-ss6** [comment]
Oh really?
...
I'm sorry, but your answer make it feels like you didn't even read the title of my issue. I know how to change the language. Every single one of those who upvoted the suggestion on UserVoice years ago knew as well. I'm asking to: 

> Either set English as default language or give us the option to save our language preferences 

But well, I guess [keep] wait[ing] for the loc team who is working on better options.
After 10 years.

**Comment by Rick-Anderson** [comment]
The entire team reviewed this, not that ASP.NET experts have much expertise on a loc for docs.microsoft.com.
