### ISSUE TITLE
Add fundamentals/localization back to aspnet TOC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#575]
localization is missing from http://docs.asp.net/en/latest/fundamentals/index.html

**Comment by TomArcher** [comment]
The toc entry for localization was added when I wrote the first draft. Therefore, this work is already in that PR (554 = https://github.com/aspnet/Docs/pull/554/files) Once you fetch and checkout the branch, you'll have it locally.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/pull/651
