### ISSUE TITLE
How to clone this?

### ISSUE THREAD

**Issue by DanJ210** [aspnet/Docs#5751]
I'm using this [Microsoft documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?tabs=visual-studio%2Caspnetcore2x) to learn some new features and it shows a link to download examples which brought me here. Problem is that I can't find anywhere to download or clone this repo.

I've used GitHub for a while now and have never come across this before. A repo that can't be cloned. Sorry if this is a really newbish or bad issue/question but there is a ton of documentation here that I'm sure the creators want people to see. So figure I'd ask.

Thanks.

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/37681215-256b9436-2c2a-11e8-9166-a6980be32b7c.png)

**Comment by DanJ210** [comment]
Um thank you? I'm following a link in documentation which beginners are going to go through and follow and the project they are telling me to download has no such button. Navigating a repo of this massivity can be a little wow for someone trying to learn from the docs. I respect a little understanding in this. Wouldn't be too much to elaborate on where that button will appear when it doesn't from the doc link.

Thanks anyway.

![github](https://user-images.githubusercontent.com/16159685/37974762-ad97c4ca-31ab-11e8-836b-11594f1b29c5.PNG)
