### ISSUE TITLE
Document how to debug when hosted on IIS using AspNetCoreModule

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#577]
- [ ] When  remote debugging.
- [ ] link to https://blog.3d-logic.com/2016/06/08/running-asp-net-core-applications-with-iis-and-antares/

**Comment by Rick-Anderson** [comment]
http://docs.asp.net/en/latest/publishing/iis.html#comment-2360219699
How about a section on how to point Local IIS to wwwroot and just having your project work like previous ASP.NET versions. So you can have something like local-foo.com points to wwwroot, you cna make changes etc and see those changes without having to publish

**Comment by danroth27** [comment]
It won't be dnx.exe when we move to the .NET CLI, but we should still document how to do this.

**Comment by GuardRex** [comment]
@Rick-Anderson We have good amount of :cow2: 🔔 in the *Troubleshooting* section in the IIS doc. Is there anything for me to do here?

**Comment by danroth27** [comment]
🐄 🔔 ?

@GuardRex At some point I think we will need you to publish a @GuardRex Rosetta Stone 😃

**Comment by GuardRex** [comment]
*cowbell* ... you know ... https://www.nbc.com/saturday-night-live/video/more-cowbell-with-will-ferrell-on-snl--video--saturday-night-live--nbc/n41046?snl=1

**Comment by guardrex** [comment]
@danroth27 At this point for this issue :point_up:, are we just talking about documenting this :point_right: [Development time IIS support for ASP.NET Core Applications](https://blogs.msdn.microsoft.com/webdev/2017/07/13/development-time-iis-support-for-asp-net-core-applications/)? That's on my To Do list anyway, and it might knock this issue out (I'm thrown off a bit by the mention of the 3d-logic Azure Apps blog post in the OP).

**Comment by danroth27** [comment]
This bug is ancient and I honestly don't know what it's tracking anymore. @Rick-Anderson?

**Comment by guardrex** [comment]
In an offline chat several weeks ago with [@]Rick-Anderson and [@]tdykstra (prior to the 2.0 release), we discussed making an official doc from the [@]shirhatti blog post, so I suppose we could use this issue to track that work. My plan was to just copy it over with a few minor touches and put his name on it.

**Comment by danroth27** [comment]
That sounds fine to me!
