### ISSUE TITLE
Dependency injection in Blazor topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5770]
Title: Dependency injection in Blazor
UID: client-side/blazor/dependency-injection
URL: https://docs.microsoft.com/aspnet/core/client-side/blazor/dependency-injection

* Configuring services
* Resolving services
* Built-in services

**Comment by guardrex** [comment]
@rstropek will take this one. Thank you @rstropek! :rocket:

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/Blazor.Docs/issues/6

**Comment by nolisj** [comment]
Hi! This is more of an idea than an issue. The `@inject `keyword in Blazor can get really repetitive when you start to have a lot of items to inject. Example (from the BlazingPizza sample project):

```
@inject HttpClient HttpClient
@inject IUriHelper UriHelper
@inject OrderState OrderState
```

The more you want to use it, the more this can get really unwieldy. Also, it is not very clear to a new user (though one can deduce) that you are actually injecting a property.

I was thinking if it can be done this way:

```
@properties {
    inject {
        HttpClient HttpClient;
        IUriHelper UriHelper;
        OrderState OrderState;
    }
}

```
This has the following added benefits:
1. It is clear that you are actually creating a property.  
2. This also forces you to have the same mental model as when you are looking at the `@functions` keyword (which refers to, well, functions or methods in the class). This parallelism, especially in terms of structure, makes you think easily what the purpose of each ones are. This becomes even more apparent when they are placed close to each other (which will happen when you're actually coding)

```
@properties {
    inject {
        HttpClient HttpClient;
        IUriHelper UriHelper;
        OrderState OrderState;
    }
}

//UI code here

@functions {
    async Task PlaceOrder() { }
    protected override async Task OnInitAsync() {}
}

```
3. It looks cleaner and less repetitive.

For your consideration.

Noli San Jose

**Comment by guardrex** [comment]
Hello @nolisj ... That's product feedback, so open it over in the engineering repo for the engineers to take a look at ...

https://github.com/aspnet/AspNetCore/issues

**Comment by nolisj** [comment]
Ok. Thank you very much. I'll do that.
