### ISSUE TITLE
Unable to download just the relevant sample being worked on

### ISSUE THREAD

**Issue by therealjohn** [aspnet/Docs#5777]
The tutorials offer a helpful link to "View or Download sample". These types of links take you to the currently viewed file in the repo on GitHub. Unfortunately, because of the limitation in GitHub you can't download just the nested folder which contains the tutorial being viewed. Instead, you have to go back to the root on GitHub and clone/download the entire Docs repo. 

The [RazorPagesMovie tutorial is an example](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model). 

It would be great if we provided a way to download just the sample so it could be opened in Visual Studio. Leave the "View" as the link to GitHub, but the Download as a zip file of that tutorial.

**Comment by guardrex** [comment]
Hello @therealjohn ... _YES!_ It's coming. They're working on a solution for this as we speak. The new approach to downloading samples should be available soon, but we don't have an exact date yet. For reference, see https://github.com/aspnet/Docs/issues/5392. I'll go ahead and close here; but if you have further questions, please feel free to ping back.
