### ISSUE TITLE
Rename "Endpoints" in SignalR docs to "Connection Handlers"

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#5784]
We're making a change in Preview 2 to rename "Endpoints" to "Connection Handlers". The docs will need to be updated to respect this in Preview 2. There's no functional change (as far as the docs are concerned), just a straight rename.

cc @rachelappel @davidfowl

**Comment by rachelappel** [comment]
Renamed in https://github.com/aspnet/Docs/issues/5521
