### ISSUE TITLE
Add link to TagHelpers to the Bundling & Minification topic

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#579]
mike: except staging/production also includes "asp-file-version" which I guess is a tag helper? 
Tell them the environment tag uses tag helpers to do this and link to http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/intro.html

**Comment by Rick-Anderson** [comment]
@Erikre  can you add this?

**Comment by danroth27** [comment]
https://github.com/aspnet/docs/issues/101
