### ISSUE TITLE
Please update the sample because project.json is no longer supported

### ISSUE THREAD

**Issue by kevin-jing** [aspnet/Docs#5797]
Docs/aspnetcore/fundamentals/dependency-injection/sample/
Warning: project.json is no longer a supported project format for .NET Core applications. Update to the latest version of .NET Core (https://aka.ms/netcoredownload) and use 'dotnet migrate' to upgrade your project (see https://aka.ms/netcoremigrate for details).

**Comment by guardrex** [comment]
Hello @kevin-jing!

Thanks for commenting. This is a duplicate based on a tracking issue we have to update all of the samples to 2.1. The sample you mentioned is on the list for update. It should be updated fairly soon, but we don't have an exact estimate at this time.

Dup of: https://github.com/aspnet/Docs/issues/5495
