### ISSUE TITLE
Improve coordination of documentation publication to ease on-boarding --- Was: Make CLI utilities self-documenting

### ISSUE THREAD

**Issue by oheard** [aspnet/Docs#581]
I apologise if this isn't the appropriate place to submit this but I'm running into a lot of frustration just doing simple tasks with the dnu and dnvm CLI tools due to a lack of accessible documentation.

Documentation is out there, but it appears to surface out of the ether and then disappear never to be found again. A lot of pages simply say that the docs haven't been written yet, where Visual Studio does provide documentation upon project creation once that tab has been closed it's lost forever so this seems to partly be a coordination/communication problem (why isn't that documentation on docs.asp.net?)

Both Google and Bing have proved useless in trying to find out how to do simple tasks such as install nuget packages or install/remove versions of .Net. Results either point to empty documentation pages or lead down a labyrinth of vaguely related but ultimately unhelpful documents.

~~I think the most appropriate thing to do is to make dnvm and dnu self-documenting much like similar tools from other platforms (gem, pip, npm, etc). I personally have had countless start/stops over the last few months due to frustration in this area.~~ Please forgive my ignorance in this statement.

**Comment by oheard** [comment]
To clarify when I say accessible, I mean you literally cannot access it because it's impossible to find. When it is found it's either useful or out of date, though, which only serves to compound the problem.

**Comment by robbert229** [comment]
What documentation are you looking for specifically?

**Comment by oheard** [comment]
Mostly on the subcommands and options accepted by the dnvm and dnu commands in this particular instance. Now that I have the tools installed and working correctly they /are/ self-documenting, which is fantastic.

The larger problem is the documentation that's out there is incomplete (which means following link after link to empty pages, frustration growing with every click (if it's not written, don't give us false hope!)) or is some long-winded "tutorial"-style document written by a third-party. The latter type drowns out useful information in search results and appear to be an attempt at compensating for the absence of official documentation.

One such example when searching for "dnu options", the top result in Google (for me, at least), is this: http://typecastexception.com/post/2015/05/17/DNVM-DNX-and-DNU-Understanding-the-ASPNET-5-Runtime-Options.aspx

When really what I'm looking for is this: ...nevermind I've lost it again, there is a GitHub page on here somewhere with two header links, one for dnvm usage and one for dnu usage. But I literally can't find it anymore (perhaps I should employ CTRL-D next time).

But I think you can see that for someone used to consuming information-dense text the typecastexception.com article is not appropriate. It reminds me of those tortuous IT classes some people are forced to endure, along the lines of "1) Click Start; 2) Click Word; 3) Click File; 4) Click Open...". It's just a drag, really.

I hope by bringing this up we can do something about it, I don't want to come across as a whiner (which I'm starting to feel I may be).

**Comment by oheard** [comment]
For a comparison of how easy other platforms make it to find such documentation, the top results for others are:

"npm options": https://docs.npmjs.com/cli/npm
"gem options": http://guides.rubygems.org/command-reference/
"pip options": http://pip.readthedocs.org/en/stable/reference/pip_install/
"dnu options": http://typecastexception.com/post/2015/05/17/DNVM-DNX-and-DNU-Understanding-the-ASPNET-5-Runtime-Options.aspx

Obviously we can't do anything about Google but I'm convinced if the documentation is presented appropriately the search issue will take care of itself, but I'm probably missing something.

**Comment by oheard** [comment]
I have noticed that this is the usual pattern for .Net (for instance when the MSDN documentation browser appeared to have its usability sabotaged several years ago). Perhaps I'm being cynical, but should I sit back and expect a paperback to be released on Wrox?

**Comment by robbert229** [comment]
The new documentation is a work in progress, but I expect it to be much better than msdn docs as time goes on. I also am community member, I just have enough free time to lurk around here and attempt to solve issues and add to the docs.

**Comment by oheard** [comment]
I didn't mean to come across as hostile towards you personally. It's just frustrating that these sorts of things go on in the Microsoft world (and that there still /is/ a "Microsoft world").

I appreciate your efforts, hopefully thanks to people like you who keep the faith one day .Net will join the rest of the wider open source community in an integrated/philosophical sense.

Microsoft should be doing more. While good people such as yourself are contributing your time for free, it's the Microsoft printing press that is Wrox who are seeking to profit rather than commit to building a truly open, well-supported platform.

If we take a look at the author list for "Professional ASP.NET MVC 5" we see:
(Source: http://www.wrox.com/WileyCDA/WroxTitle/Professional-ASP-NET-MVC-5.productCd-1118794729,descCd-authorInfo.html)

 - Jon Galloway works at Microsoft as a Technical Evangelist focused on ASP.NET MVC.
 - Brad Wilson has been a professional software developer for more than 20 years, with 10 years in web development.
 - K. Scott Allen is the founder of OdeToCode LLC, which provides custom development, consulting, and mentoring services for clients worldwide.
 - David Matson is a software developer at Microsoft. He is part of the MVC 5 and Web API 2 product team.

So two Microsoft staffers, one of which is an evangelist who has chosen to try and profit the old Microsoft way by writing a book rather than contribute to the official documentation here. Way to go, Jon... So people on Microsoft's payroll, likely making hundreds of thousands of dollars a year, decide to not contribute to the project and try to profit off of it instead.

It's just depressing.

**Comment by MikeWasson** [comment]
The MVC 5 book is for the previous version of ASP.NET. (MVC 5 != ASP.NET 5)

**Comment by oheard** [comment]
Thank you for pointing out my ignorance @MikeWasson. I've updated my comment above to apologise.

I'll leave this issue open because I think my experience does highlight a valid problem in terms of documentation/developer communication and my embarrassment is worth resolving such an issue. I'll leave it up to the people in charge to decide whether to give this any attention whatsoever.

**Comment by danroth27** [comment]
While we are tracking adding reference pages for our command-line tools (#309, #310, #311), we haven't treated this as high priority under the assumption that you can just use the help text from the tool. We are planning to move off of DNX onto the new .NET CLI tools, so this documentation will move to the [.NET Core docs](https://github.com/dotnet/core-docs).
