### ISSUE TITLE
Update Kestrel host configuration guidance to include new HostFiltering middleware

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Docs#5812]
In 2.0 we issued a patch and guidance related to host configuration, especially for Kestrel that doesn't have built in support for host filtering.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x#host-filtering

In 2.1 preview2 we've taken that sample and created a new HostFiltering package & middleware. That's been added to WebHost.CreateDefaultBuilder and can be configured by setting "AllowedHosts" to a semicolon separated list like "locahost;example.com". The middleware is disabled by default.
RE: https://github.com/aspnet/MetaPackages/pull/261

Update the Kestrel docs accordingly.

**Comment by RehanSaeed** [comment]
The docs suggest using host filtering only if you are exposing Kestrel to the internet. Presumably, IIS and NGINX have host filtering built into them already.

@Tratcher According to your comment in https://github.com/aspnet/BasicMiddleware/pull/312 `ForwardedHeadersOptions` also now has an `AllowedHosts` property. If you are using the ForwardedHeaders middleware, then you are running behind a L7 load balancer like NGINX, so why would you need `AllowedHosts`? Also, if you are using ForwardedHeaders, presumably you don't need the host filtering middleware?

**Comment by Tratcher** [comment]
Nginx doesn't validate the host by default, nor does IIS, you have to specifically configure that, see our nginx and IIS docs. The host has to be validated somewhere, it's up to you to decide where.

And yes that scenario requires XForwardedHost.

**Comment by RehanSaeed** [comment]
@Tratcher If I use `ForwardedHeadersOptions.AllowedHosts`, I don't need to use the HostFiltering middleware right?

For IIS, don't use top-level wildcard bindings (http://*:80/ and http://+:80) [Source](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x).

For NGINX you have to set `server_name  example.com *.example.com;` [Source](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x).

For anyone else interested, [rfc7230](https://tools.ietf.org/html/rfc7230#section-5.4) shows why checking the header is important.

**Comment by Tratcher** [comment]
Right, ForwardedHeadersOptions.AllowedHosts and the HostFiltering middleware duplicate functionality for slightly different scenarios.
