### ISSUE TITLE
VS CODE - How to Build and Publish a C# Web API to IIS? 

### ISSUE THREAD

**Issue by dennisaubrey** [aspnet/Docs#5828]
What are the complete steps to Build and Publish a C# Web Service API using the IIS Web Site.

https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc#add-support-for-entity-framework-core

![image](https://user-images.githubusercontent.com/36566794/38095096-9d3af2e4-333d-11e8-868a-971ed54ad459.png)

**Comment by Rick-Anderson** [comment]
@dennisaubrey  the steps are the same for publishing a Web UI ASP.NET Core app. For example, a Razor Pages app or MVC controller app.

**Comment by girishuppal** [comment]
> What are the complete steps to Build and Publish a C# Web Service API using the IIS Web Site.
> 
> https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc#add-support-for-entity-framework-core
> 
> ![image](https://user-images.githubusercontent.com/36566794/38095096-9d3af2e4-333d-11e8-868a-971ed54ad459.png)

This link is not functional. Can anybody update the link ?

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api

**Comment by Rick-Anderson** [comment]
We don't update closed issues.
