### ISSUE TITLE
Document [Required] attribute for Razor Pages properties

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5834]
See [this video](https://youtu.be/-EgE79M3tuc?t=2750).

**Comment by Rick-Anderson** [comment]
@scottaddie  @guardrex  where should this be documented?  I can add it to my Razor Pages tutorials, but it needs to be documented outside a tutorials.  It could almost go in [Razor Pages route and app convention features](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/razor-pages-convention-features?view=aspnetcore-2.1)

**Comment by guardrex** [comment]
It's not really a "convention" in the strict sense, which is all that topic covers (at least in its current version). It focuses only on the [PageConventionCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.applicationmodels.pageconventioncollection?view=aspnetcore-2.0) bits.

**Comment by Rick-Anderson** [comment]
agreed, hence the *almost*. But where should it go?

**Comment by guardrex** [comment]
Maybe in here :point_right: https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio

... either near the first mention of how properties work with RP ... maybe even in its own little section.
