### ISSUE TITLE
Find a new home for EF MVC code in Code Gallery

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#5847]
Given the way Microsoft is moving toward using GitHub for code samples,  we should move our top sample off MSDN Code Gallery. The top download on the site is [EF MVC for EF 6 and MVC 5](https://code.msdn.microsoft.com/ASPNET-MVC-Application-b01a9fe8), and these versions are still relevant, so we should consider moving the sample:
* Update the project for VS 2017, and if time permits update package versions as well.
* Find a place for the project in the ASP.NET docs repository and put it there.
* Update the Code Gallery page to send people to the new location.

**Comment by Rick-Anderson** [comment]
@tdykstra 	is P1 correct?

**Comment by tdykstra** [comment]
Given the high number of downloads this sample gets, #1 on codeplex, P1 is correct.

**Comment by tdykstra** [comment]
The download link will change from

https://code.msdn.microsoft.com/ASPNET-MVC-Application-b01a9fe8

to

 https://github.com/tdykstra/aspnet-docs/blob/efmvc2/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/sample/ef6-mvc5-sample-app.zip?raw=true
