### ISSUE TITLE
Razor Sdk: Require docs on various available settings and instructions for users to use the Sdk in a class library 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5865]
Details in https://github.com/aspnet/Razor/issues/2119

Proposed title: Razor SDK for ASP.NET Core
Proposed path: /aspnet/core/mvc/razor-pages/sdk

@pranavkm I'd like to get this completed early next week so  you can update the fwlink to https://docs.microsoft.com/aspnet/core/mvc/razor-pages/sdk

**Comment by pranavkm** [comment]
@mkArtakMSFT could you update the fwlink you created (https://go.microsoft.com/fwlink/?linkid=868374) to point to https://docs.microsoft.com/aspnet/core/mvc/razor-pages/sdk?

**Comment by pranavkm** [comment]
Thanks @Rick-Anderson
