### ISSUE TITLE
Unclear documentation for Authorization Policy/Authentication

### ISSUE THREAD

**Issue by dave-hillier** [aspnet/Docs#5870]
Reposted from: https://github.com/aspnet/Security/issues/1715

I've attempted to follow this page: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies#using-a-func-to-fulfill-a-policy

I performed the following steps (a simplified contrived example):
* I created a new Web API project `dotnet new webapi`
* On the `Get` method of the values controller I added an attribute: `[Authorize(Policy = "AlwaysDeny")]`
* In `Startup.cs` I added the following to `ConfigureServices`:
```
      services.AddAuthorization(options =>
      {
        options.AddPolicy("AlwaysDeny", policy =>
        {
          policy.RequireAssertion(context => false);
        });
      });
```
When I get `http://localhost:5000/api/values` I would have expected a 401 response

I instead get a 500 the following exception:  `System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.`

The documentation does not indicate any requirement for authentication. I do not want to use JWT token or Cookies.

**Comment by blowdart** [comment]
I closed the issue in security however Rick if you want to add a line to every page which says "Authorization requires an authentication mechanism", which is what it would take, feel free.

**Comment by Rick-Anderson** [comment]
@dave-hillier  where exactly should we add "Authorization requires an authentication mechanism" to the article?

**Comment by dave-hillier** [comment]
@blowdart are you trolling? Did you not tell me to open it here? I'm guessing you designed this API and you feel as if I'm calling your baby ugly?

It's clear from a quick google that I'm not the first to have come across this exception. It would be useful to have some reference that helps with those specific examples. 

In this case, I'd suggest that the second paragraph would be a reasonable place.

**Comment by blowdart** [comment]
Not trolling, pointing out it's not a security issue, but a docs one. But I think if it goes on one authz page it'll need to go on all, because we can't expect everyone to land on the one page mentioned.

**Comment by dave-hillier** [comment]
Yeh, my bad, I raised it in the wrong repository. I did describe it as, "unclear documentation", not a security issue. I was referring to your comment about "every page".  That simply isn't true so it feels like you're trying to argue that a change would be impractical. If you felt it isn't a valid issue, you should just say so.

On the page in question, the first example is somewhat misleading as it looks complete. That is different to the way that configuration of authorization is described here: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?tabs=aspnetcore2x

Looking through the security issue tracker it seems like there might be a few for that same exception.

**Comment by Rick-Anderson** [comment]
>I think if it goes on one authz page it'll need to go on all, because we can't expect everyone to land on the one page mentioned.

I can create an include file and add it to the other pages. Let me know if you'd like that approach.
