### ISSUE TITLE
Docs - Standalone installation on Windows vs. Publishing on IIS

### ISSUE THREAD

**Issue by OndrejValenta** [aspnet/Docs#588]
I'd say after latest updates of [Publishing to IIS article](https://docs.asp.net/en/latest/publishing/iis.html#publishing-to-iis) installation documentation needs some consolidation. The problem is there are two articles which talk about the same, part of installation steps is in [Installing ASP.NET 5 On Windows](https://docs.asp.net/en/latest/getting-started/installing-on-windows.html) and part is in the *Publishing to IIS*. I would move the installation part of *Publishing to IIS* article to *Installating ASP.NET 5 on Windows*, so one system administrators can install and prepare everything without need to go through publishing process.

**Comment by Rick-Anderson** [comment]
Those are two different processes. You generally don't want to install ASP.NET on the server. Also, when you create a new linked issue add the link #571
