### ISSUE TITLE
Document Microsoft.AspNetCore.App 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5884]
Consider working with Andrew Lock and [his blog](https://andrewlock.net/exploring-the-microsoft-aspnetcore-app-shared-framework-in-asp-net-core-2-1-preview-1/)

related #5314

Update [Microsoft.AspNetCore.All metapackage](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage) to point out the App meta package is the recommended package.

See:
* https://github.com/aspnet/Announcements/issues/287
* [Exploring the Microsoft.AspNetCore.App shared framework in ASP.NET Core 2.1 ](https://andrewlock.net/exploring-the-microsoft-aspnetcore-app-shared-framework-in-asp-net-core-2-1-preview-1/)

[At 2.10 ](https://www.dropbox.com/s/jfxbdzigg7nmr41/Review%20ASP.NET%20Core%202.1%20doc%20priorities%20-%20Monday%2C%20April%209%2C%202018%208.24.29%20AM.mp4?dl=0) recommend .APP

https://github.com/aspnet/MetaPackages/issues/255
the new meta-package includes version restrictions, such that other packages you might bring in, can't unintentionally upgrade bits of what's in Microsoft.AspNetCore.App higher than the version included. This helps to ensure a more reliable experience, as it becomes harder to end up with untested version combinations of related bits being used together in the same app (a large cause of customer issues today, given it often happens completely silently). You'll still be able to force it in the cases you want to do so (by lifting the affected package references to be direct in your project) but at that point you're effectively in an unsupported state.

**Comment by guardrex** [comment]
Adding the blurb from the 2.1.0-preview2 roadmap blog post:

> ASP.NET Core 2.1 will introduce a new meta-package for use by applications: Microsoft.AspNetCore.App. The new meta-package differs from the existing meta-package in that it reduces the number of dependencies of packages not owned or supported by the ASP.NET or .NET teams to just those deemed necessary to ensure the major framework features function. We will update project templates to use the new meta-package. The existing Microsoft.AspNetCore.All meta-package will continue to be made available throughout the 2.x lifecycle. For additional details see https://github.com/aspnet/Announcements/issues/287.

**Comment by Rick-Anderson** [comment]
I'll think about that. I have it in PR, although not the TOC.
https://github.com/aspnet/Docs/pull/6069
