### ISSUE TITLE
Update source control guidance for publish profiles

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#5888]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?tabs=aspnetcore2x#publish-profiles

The **Publish profiles** section of the doc above contains the following text:
> The .pubxml file shouldn't be checked into source control because it depends on the .user file.

This guidance is incorrect in some cases. When using TFS or VSTS, the *.pubxml file needs to be checked in. The build/release definition will need access to it in source control.

There's also a related Livefyre comment:
> The aricle says "The .pubxml file shouldn't be checked into source control ". In case of using GitHub, Jenkins for continuous integration and Jenkins is configured to use MSBuild with publish profile, how it will work without .pubxml file? ( for that matter any CI tool configured to use MSBuild with publish profile)

**Comment by Rick-Anderson** [comment]
@vijayrkn  please review
