### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#59]
ASP.NET 5->Fundamentals->Servers
- Servers accept incoming requests and make them available to the application pipeline
- Built-in servers (list request features and configuration parameters supported, process model, .NET flavor and OS support)
    - IIS
    - WebListener
    - Kestrel
- Guidance on when to use which server
    - Prefer Windows optimized servers (IIS, WebListener) on Windows.
    - Use IIS for general web hosting and WebListener for custom hosting in your own process or service.
    - Use Kestrel for non-Windows environments
- Server specific programmatic configuration using `IApplicationBuilder.Server`
    - Downcast and configure
- Custom
    - Implement `IServerFactory`
    - Create a [feature](https://github.com/aspnet/docs/issues/293) collection _per request_ and invoke the provided application delegate
        - Mandatory features: `IHttpRequestFeature` and `IHttpResponseFeature`
        - All other features are optional
    - See #58 for details on how to use a custom server with ASP.NET Hosting

**Comment by ardalis** [comment]
Should I cover Feature Interfaces in this article, or link to another article on the topic? I'm thinking a section under Servers makes sense.
https://github.com/aspnet/HttpAbstractions/tree/dev/src/Microsoft.AspNet.Http.Features

**Comment by danroth27** [comment]
See the added details above. Because request features can be added by both servers _and_ middleware we should move the general discussion of request features to a separate topic (#293). This article should still include a discussion of the request features that the built-in servers provide and also how a custom server provides request feature implementations.
