### ISSUE TITLE
Security: Basic register/ login with ASP.NET Identity

### ISSUE THREAD

**Issue by rustd** [aspnet/Docs#590]
Add a basic walkthrough of using Identity in Empty project and create a basic walkthrough of register and login a user with username and password

**Comment by danroth27** [comment]
Possible duplicate of https://github.com/aspnet/Docs/issues/977.

**Comment by rachelappel** [comment]
This article might suffice.
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?tabs=visual-studio%2Caspnetcore2x

**Comment by Rick-Anderson** [comment]
Solved via multiple articles.
