### ISSUE TITLE
Need Article under Web API on Securing APIs

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#5900]
Currently there is no article (that I see) in the docs on Securing Web APIs. There should be. Ideally it should describe:

- Options for securing APIs in general
- Detail one specific approach (with pros and cons)
- Demonstrate how to implement this specific approach

Eventually additional articles could describe other approaches.

@blowdart 

## Requests for new Topics

1. Write a **short** paragraph describing what the topic will cover.

2. Write an outline of the proposed topic contents.

3. Where would you put the topic in the Table of Contents.

4. If you know who should review the issue, notify them by including @githubID in the issue description.

**Comment by Rick-Anderson** [comment]
Dup of #4556
