### ISSUE TITLE
Doc new IOptionsBuilder and related overloads

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#5924]
From #5922
another good 2.1 options feature to doc eventually is the new `IOptionsBuilder` and related overloads, see https://github.com/aspnet/Security/issues/1718#issuecomment-380204790 its related to this general idea of being able to more easily configure options with things from DI

**Comment by guardrex** [comment]
Adding the bit from the 2.1.0-preview2 roadmap:

> To configure options with the help of configured services, you can today implement `IConfigureOptions<T>`. In 2.1 we’re adding convenience overloads to the Configure method that allow you to configure options using services without having to implement a separate class:

```csharp
services.Configure<MyOptions, MyService, MyService2>((options, service, service2) =>
{
    options.Value = service.DoSomething(service2.DoSomethingElse())
});
```
> Also, the new `ConfigureOptions<TSetup>` method lets you register a single class that configures multiple options (by implementing `IConfigureOptions<T>` multiple times):

```csharp
public class MySetup : IConfigureOptions<Options1>, IConfigureOptions<Options2> 
{
    void Configure(Options1 o) { … }
    void Configure(Options2 o) { … }
}
```

**Comment by guardrex** [comment]
Fixed by https://github.com/aspnet/Docs/pull/9456.
