### ISSUE TITLE
Merge markers left in on SignalRChat.csproj

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#5943]
Looks like maybe there was a bad merge in SignalRChat.csproj:

https://github.com/aspnet/Docs/blob/8ad0c244667d054021c4d1346cb0270f94b5268d/aspnetcore/signalr/get-started/sample/SignalRChat.csproj#L15-L17

See https://github.com/aspnet/SignalR/issues/1930#issuecomment-380312647

**Comment by Rick-Anderson** [comment]
@rachelappel  can you fix this ASAP and let me know so I can merge to live.
