### ISSUE TITLE
Sample Docs/aspnetcore/mvc/models/validation/sample/ not compilable

### ISSUE THREAD

**Issue by MelnikovIG** [aspnet/Docs#5944]
Sample `https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/models/validation/sample` not compilable since `UserRepository` not implement 
https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation/sample/IUserRepository.cs#L6

method from `IUserRepository`
Looks like it was broken by https://github.com/aspnet/Docs/pull/4768

**Comment by Rick-Anderson** [comment]
@Rabadash8820 can you take a look at this?
