### ISSUE TITLE
Clearly state supported browsers for SignalR sample code

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#5945]
https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio

The sample code here uses modern ECMAScript 6 features and isn't supported in IE 11. We should do one (or multiple) of the following:

1. Clearly indicate that the sample does not support IE 11. Direct users to tools like https://babeljs.io/ to transpile for older browsers
2. Convert the sample code to ECMAScript 5 (again a tool like https://babeljs.io/repl can be used for this)

See https://github.com/aspnet/SignalR/issues/1954

**Comment by Rick-Anderson** [comment]
@anurse unless you object, I'll have @rachelappel take your first option.
@rachelappel  can you get this completed in the next couple days?

**Comment by anurse** [comment]
Yeah, I agree. Let's make sure to call out tools like Babel to transpiling so users can still make the sample work on IE 11 if they want.
