### ISSUE TITLE
Address how non-IPageConvention conventions are described for RP and MVC

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#5958]
WRT: Razor Pages route and app convention features in ASP.NET Core
* https://docs.microsoft.com/aspnet/core/mvc/razor-pages/razor-pages-convention-features
* aspnetcore/mvc/razor-pages/razor-pages-convention-features.md

From @pranavkm on #5520 ...

> might be good to add a quip about property model \ parameter model conventions. Sort of along the lines of https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model?view=aspnetcore-2.1#sample-modifying-the-parametermodel. For most parts, you could copy the docs \ samples verbatim.

The current RP conventions topic entirely focuses on conventions that implement `IPageConvention` ... so it's very RP `options.Conventions`-focused. Copying over other "conventions" that apply to both MVC and RP will probably lead to a duplication of content.

We might need to restructure how conventions that apply to both MVC and RP are covered.

**Comment by Rick-Anderson** [comment]
@guardrex 	can you move this to an integrated Doc/GitHub issue and label P1.

**Comment by guardrex** [comment]
Moved to https://github.com/aspnet/Docs/issues/9269.
