### ISSUE TITLE
Updating fundamentals/servers.rst

### ISSUE THREAD

**Issue by robbert229** [aspnet/Docs#596]
I am taking a look at updating fundamentals/servers.rst. I am wondering about what we are doing with WebListener. I was under the impression that WebListener is getting phased out. Is it getting removed from from the docs completely?

**Comment by ardalis** [comment]
Most likely. @danroth27 ?

**Comment by robbert229** [comment]
@ardalis @danroth27 any idea?

**Comment by danroth27** [comment]
No, WebListener will continue to exist. It supports features on Windows that Kestrel does not yet support.

The big change was the removal of the Helios host for hosting on IIS. Instead we are using the HttpPlatformHandler and Kestrel.

**Comment by robbert229** [comment]
Okay, thanks. I knew something was getting changed, just didn't know what.
