### ISSUE TITLE
Modern JavaScript and supported browsers in samples

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#5968]
@anurse RE: Extending the recent issue and PR about modern JS and IE11. (https://github.com/aspnet/Docs/issues/5945)

Take a look at chat.js and es5-chat.js at https://github.com/rachelappel/SignalRChat/tree/master/SignalRChat/wwwroot/js 
I would like to use chat.js with the comments in it, and add es5-chat.s alongside it to the samples.  I ran my sample that I use for the doc through Babel and copied the output to es5-chat.js. 
Even if we don't use es5-chat (it is for reader convenience), I believe at least moving the message about ES5/IE11 to the chat file will be better received as comment form in code than a note in the doc. 
Because:
-When people stumble on the sample straight from a search engine they will know what's going on without having to dig up the actual doc too. 
-All the docs so far use the same code sample (trying to keep it consistent), and therefore this message should be somewhere available across the other docs that use this sample. So why not add it to the sample itself? The comments can simply be added to the doc by showing the extra lines in the code snippets/samples, and then it works like an include file, but it now can be expressed in both docs and code or just code when we want. 
Thoughts?

**Comment by anurse** [comment]
Looks ok to me
