### ISSUE TITLE
Working with Static Files

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#60]
ASP.NET 5->Runtime->Working with Static Files
- Servicing static files
  - Use the static file middleware (package: Microsoft.AspNet.StaticFiles)
  - Web root defined in project.json
  - Populate with your static files
  - Link to how to setup with bower (http://docs.asp.net/en/latest/client-side/bower.html)
- Directory browsing
- Default files
  - URL rewrite to point to default files (ex index.html) if they exist
  - Generally used in conjunction with static file middleware
- File Server = Static files + directory browsing + default files
- Common options
  - Custom `IFileProvider` (ex service files from location other than web root or from embedded assembly resources)
  - "Request path" specifies a common prefix in the URL to handle
- General notes
  - Generally configure early in pipeline - everything falls through if the file/dir doesn't exist

**Comment by TomArcher** [comment]
http://docs.asp.net/en/latest/fundamentals/static-files.html
