### ISSUE TITLE
problems with "Using Gulp"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#600]
New ASP.NET Web Applications created in Visual Studio 2015 start with the Empty, Web API”, and *Web Site templates. 

In addition to unbalanced * - it's very clumsy - rewrite this- something like 
When you create a new asp.net web app (except for empty) with vs , NPM and Gulp is included. Don't use "by default" unless their is an option to not include it. 

*Gulp is configured to copy Bootstrap, Hammer and jQuery client libraries to your web app directory.*
As of B8 this doesn't appear to be true. Create an empty web app and copy bower.json from a full web app. As soon as you save, these assets are copied.

The best sample code is from the default web app - that should be featured and explained (ie, min, min:css, etc)

remove the following cliche - it adds nothing to the article
Modern web development has lots of moving parts.

**Comment by scottaddie** [comment]
@Rick-Anderson Are you looking for someone to take this on? I see that the RC1 changes still need to be incorporated. Let me know, and I'd be happy to help.

**Comment by Rick-Anderson** [comment]
@scottaddie that would be great.

**Comment by scottaddie** [comment]
@Rick-Anderson One of my favorite topics. I'm on it.

**Comment by Erikre** [comment]
@scottaddie & @Rick-Anderson - The "Using Gulp" topic was recently updated? What RC1 changes do you propose?

**Comment by scottaddie** [comment]
Many of the screenshots and code snippets reflect the Beta 8 release. I had 3 PRs in particular that are absent in the docs but are present in the Templates repo.

**Comment by Erikre** [comment]
Sounds good. I'd be happy to review any changes when you're ready. Thanks

**Comment by scottaddie** [comment]
@Erikre I appreciate it! I should have a PR ready for review within the next day or so.

**Comment by scottaddie** [comment]
@Erikre PR submitted. Go ahead and review. Thank you!

**Comment by Erikre** [comment]
@Rick-Anderson & @danroth27  - These updates look good to me. I believe "gulp" isn't meant to be capitalized, but that shouldn't hold up this PR. Please review.

**Comment by Erikre** [comment]
Including @rachelappel
