### ISSUE TITLE
Document LibMan (client-side content manager)

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6008]
References:
* https://github.com/aspnet/templating/issues/471
* https://blogs.msdn.microsoft.com/webdev/2018/04/17/library-manager-client-side-content-manager-for-web-apps/

I'll mark for 2.2, but this can be done earlier if it lands in a 2.1.x patch.

**Comment by guardrex** [comment]
Discussion of LibMan on the Community Standup: https://youtu.be/k0Xy-5zE9to?t=25m8s

**Comment by scottaddie** [comment]
Closing as a duplicate
