### ISSUE TITLE
ASP.NET Core SignalR: Supported Platforms Doc

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#6015]
We should get a doc out with the supported platforms for ASP.NET Core SignalR. This should be a fairly high priority for SignalR, as we've had some confusion around it in the previews.

The existing doc is https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/supported-platforms . I think the doc for Core can be a lot simpler, and doesn't need to dive in to which transports are supported where.

## Server system requirements

* This is much easier than the existing doc. We support any server platform ASP.NET Core supports.

## Client system requirements

Browser support:

* Microsoft Internet Explorer 11
* Microsoft Edge: current version
* Mozilla Firefox: current version
* Google Chrome: current version; includes Android.
* Safari: current version; includes iOS

.NET Client support:

* Any .NET platform that supports .NET Standard 2.0.

**Comment by rachelappel** [comment]
I was just about to ping you about pushing this up to a P1, as a few customers have had questions about it.
The current doc can be trimmed down quite a bit. 
I'll close this (dup) https://github.com/aspnet/Docs/issues/5300
