### ISSUE TITLE
Add Example of Testing Custom Handlers in Policy-based Authorization

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#6031]
## Requests for new Sub-Topic

1. Update the [Policy-based authorization in ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1) to include how to test our custom handlers.

2. Write a test for `MinimumAgeHandler`

3. [Policy-based authorization in ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1)

**Comment by spottedmahn** [comment]
SO Post: [Is it possible to write a test that can test an AuthorizationPolicy Object?](https://stackoverflow.com/questions/46651152/is-it-possible-to-write-a-test-that-can-test-an-authorizationpolicy-object)

**Comment by spottedmahn** [comment]
Thoughts 💭?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
