### ISSUE TITLE
Fix link on https://www.asp.net/mvc

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6038]
![image](https://user-images.githubusercontent.com/3605364/39022532-b612ac2c-43d1-11e8-8c2b-65820cea969f.png)

The best link I could find is https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet-framework

**Comment by Rick-Anderson** [comment]
@terrimorton  do you own this page?

**Comment by terrimorton** [comment]
Yes, we should have this fixed tomorrow.

**Comment by terrimorton** [comment]
That update is now live at [https://www.asp.net/mvc](https://www.asp.net/mvc)

**Comment by Rick-Anderson** [comment]
@terrimorton  thanks!
