### ISSUE TITLE
Missing Page: Step 2 'Add a Model'

### ISSUE THREAD

**Issue by scottcate** [aspnet/Docs#6047]
I thought this 404 was a bad link, but it turns out the actual content is missing.

https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/model

Maybe it was removed in a merge? 

Currently linked to from lots of places, including the TOC. 

Reported on Twitter, https://twitter.com/mdpopescu/status/987593945642360832

**Comment by guardrex** [comment]
@scottcate Thanks for reporting. The topic is present at ...

https://docs.microsoft.com/aspnet/core/tutorials/razor-pages/model

New versioning features change the URL in the TOC to ...

https://docs.microsoft.com/aspnet/core/group1-dest/tutorials/razor-pages/model

See the `group1-dest` segment :point_up:.

There's an internal issue open to investigate+fix the problem.

**Comment by guardrex** [comment]
We'll close this now, as the internal issue covers it. It should be fixed soon.
