### ISSUE TITLE
Broken Bullet in Publishing to IIS document

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#605]
@Rick-Anderson 

The bullet is slightly broken (two dashes perhaps?) at: https://docs.asp.net/en/latest/publishing/iis.html

![capture](https://cloud.githubusercontent.com/assets/1622880/10972822/ba6b7f10-838f-11e5-9312-a4331936d20c.PNG)

**Comment by Rick-Anderson** [comment]
@GuardRex  thanks - I'll get that fixed next update.

**Comment by billjwolff** [comment]
i have this fixed and will commit in a few minutes
