### ISSUE TITLE
Bad code block rendering with conceptual versioning

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6052]
[Internal bug](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1259263)
Example: https://docs.microsoft.com/aspnet/core/razor-pages/razor-pages-conventions

![capture](https://user-images.githubusercontent.com/1622880/39100890-13d2c31a-4657-11e8-8c1a-bdb09505f187.PNG)

... but the spacing for those code blocks is [correct in the source (L88-L108)](https://github.com/aspnet/Docs/blame/master/aspnetcore/mvc/razor-pages/razor-pages-convention-features.md#L88-L108) (backticks are converted to dashes for rendering here) ...

```
::: moniker range=">= aspnetcore-2.1"
**Add a handler model convention to all pages**

[!INCLUDE[](~/includes/2.1.md)]

Use [Conventions](/dotnet/api/microsoft.aspnetcore.mvc.razorpages.razorpagesoptions.conventions) to create and add an [IPageHandlerModelConvention](/dotnet/api/microsoft.aspnetcore.mvc.applicationmodels.ipagehandlermodelconvention) to the collection of [IPageConvention](/dotnet/api/microsoft.aspnetcore.mvc.applicationmodels.ipageconvention) instances that are applied during page handler model construction.

---csharp
public class GlobalPageHandlerModelConvention 
    : IPageHandlerModelConvention
{
    public void Apply(PageHandlerModel model)
    {
        ...
    }
}
---

`Startup.ConfigureServices`:

---csharp
services.AddMvc()
    .AddRazorPagesOptions(options =>
        {
            options.Conventions.Add(new GlobalPageHandlerModelConvention());
        });
---
::: moniker-end
```

cc/ @scottaddie @Rick-Anderson

**Comment by scottaddie** [comment]
@adkinn @Sampy Is this a bug?

**Comment by guardrex** [comment]
@scottaddie Looks like this was fixed. Is #1259263 closed? If so, :tada: 🎈 :beers:.

**Comment by adkinn** [comment]
@guardrex which page are you looking at? The link in this thread is 404ing.

**Comment by guardrex** [comment]
The Kestrel topic. Many of the code blocks (the ones in versioning ranges) were flat, but they're not flat any longer.

https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel

**Comment by scottaddie** [comment]
@guardrex It's still showing as open.

**Comment by guardrex** [comment]
Interesting ... both the Kestrel and the RP conventions topics no longer have the problem.
