### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by ebicoglu** [aspnet/Docs#6056]
Links don't work for example 

https://docs.microsoft.com/en-us/aspnet/core/group1-dest/tutorials/razor-pages-vsc/?view=aspnetcore-2.1
https://docs.microsoft.com/en-us/aspnet/core/group1-dest/mvc/overview?view=aspnetcore-2.1

![image](https://user-images.githubusercontent.com/9526587/39108715-501d342e-46d2-11e8-83d1-c4583ccca094.png)

**Comment by Kyappy** [comment]
Same problem, but until it is fixed, you can still access the link by removing "group1-dest" in the url.
So https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/?view=aspnetcore-2.1 and https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.1 will work

**Comment by ebicoglu** [comment]
@Kyappy  thanks

**Comment by guardrex** [comment]
Thanks for reporting. We have an internal issue tracking this and it should be fixed very soon. We're sorry for the trouble. I'll close this since we're tracking the work internally.
