### ISSUE TITLE
Should we link WebHost convienance methods under Startup class examples?

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6062]
> when you have some time

@scottaddie ... your Midwestern sense of humor is showing! 😀 lol

Let's go ahead and discuss openly ...

We can't have both the `WebHost` extension method and the `Startup` class shown for every example. However, a link might not be out of the question. Each place in the docs where a `Startup` class example is shown could have a link ... perhaps a floating link under the example ...

> \[See how to configure the preceding example using WebHost extension methods](xref:fundamentals/startup#convenience-methods).

[See how to configure the preceding example using WebHost extension methods](https://docs.microsoft.com/aspnet/core/fundamentals/startup#convenience-methods).

... and that goes to where we show how to do it ...

https://docs.microsoft.com/aspnet/core/fundamentals/startup#convenience-methods

... and that's pretty much all we'd need to do to surface it. As `@Tratcher` *lightly* implied in a passing remark, the 😀 *NutJob Pattern*:tm: 😀 is a good and valid approach to simplifying startup.

If we agree to do this (and I'd like to tackle it if so), it's a Backlog item. I would aim for June when *I have a bit more free time* ... if you catch my drift. :smile:

**Comment by scottaddie** [comment]
@guardrex Do we have many customers asking to see the `WebHost` extension methods instead? If not, let's stick with just the `Startup` class examples. That's what the templates use after all.

**Comment by guardrex** [comment]
Yes on Slack ... it has come up several times. Generally speaking ... and this isn't a conclusion based on any data ... when devs see the extension methods, they 😍 that approach for run-of-the mill LOB web apps with simple startup scenarios.

I took to them myself immediately. I hate looking around all over the bleed'in place for configuration: config files ... env vars ... classes in several different files ... managing all of that stuff. I like everything *in one place* and apps that detect their environment (dev, staging/testing, prod) (via the server they're on in my case) and then configure themselves accordingly. My apps almost never use config files or env vars. Most of the time, I use a single *Program.cs* that has everything. Downside: config requires restart. Upside ... most restarts involve more than just a simple config change, so it doesn't matter anyway ... a restart is usually needed when config changes. Admittedly, my apps are simple LOB web apps ... not some of these giant creatures in complex startup scenarios.

Anyway ... yes ... my gut tells me from Slack chats that devs :heart: the `WebHost` extension methods and they usually only find out about them because someone tells them or they randomly discover them looking at sample apps around the Net.

**Comment by guardrex** [comment]
I've given it some thought, and it feels like the trouble and physical space required to do this outweigh the benefit. If they see the section in the startup topic, they're good.
