### ISSUE TITLE
Add a doc for creating and using a Razor Class Library(RCL) project

### ISSUE THREAD

**Issue by kichalla** [aspnet/Docs#6073]
The topic should describe the following:
- How to find the RCL project in VS dialog (net461 & netcoreapp2.1 TFM's)
- Creating a new project and referencing it in a newly created Razor Pages(RP) web application project
- Launch the RP project and access the RCL project's page
- Override the RCL project's page in RP project and launch again to see the new changes.
- Table of Contents should probably have something saying "Creating a Razor Class Library project" or "Creating reusable UI using Razor Class Library project"

cc @danroth27 @mkArtakMSFT @Rick-Anderson 

@rick-anderson edit below:
Dup of #5409
aspnet/Razor#1809

**Comment by guardrex** [comment]
I'd like to plug that this cover xplat scenarios, too (e.g., VS Mac, VSC, and CLI).

**Comment by Rick-Anderson** [comment]
@kichalla I've had [Reusable Razor UI in class libraries with ASP.NET Core](https://review.docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class?view=aspnetcore-1.0&branch=pr-en-us-5980) in PR https://github.com/aspnet/Docs/pull/5980 for a couple weeks. Just need @javiercn or @pranavkm to review/ sign off and I'll publish.

**Comment by Rick-Anderson** [comment]
@kichalla  the fwlink will point to `https://docs.microsoft.com/aspnet/core/mvc/razor-pages/ui-class`

**Comment by Rick-Anderson** [comment]
A framework is typically referenced by a short target framework moniker or TFM.
