### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#61]
ASP.NET 5->Fundamentals->Routing
- Middleware
  - Maps a request to an `IRouteHandler`
  - The `IRouteHandler` returns a `RequestDelegate` or null
    - Example: is there a matching MVC action
  - If null, then routing continues
  - If no route handler can handle the request then the middleware calls next
- Configuration
  - Create RouteBuilder
- Code sample to reference: https://github.com/aspnet/Routing/blob/master/samples/RoutingSample.Web/Startup.cs
- Template routes
  - Ex: `{controller=Home}/{action=Index}/{id?}`
  - Stuff with curly braces defines a route value that will get bound
  - Stuff with an `=` defines a default value. If the path segment is not present then the default value is added to the route values
  - `?` defines an optional value
  - `:` to add inline constraints
    - Constraints can have parameters denoted by parens
    - Ex: int, bool, etc. See https://github.com/aspnet/Routing/blob/master/src/Microsoft.AspNet.Routing/RouteOptions.cs#L41
    - You can chain stuff. Ex `{id:int:range(0,100)}`
    - If the string doesn't match an inline constraint then its treated as a regex (ex match one of three values `{value:foo|bar|baz}`)
  - Prefix route parameter with `*` to bind to the rest of the URI. Ex `/blog/{*slug}`
  - Route templates need to be unambiguous. Ex this doesn't work: `{id?}/{foo}`
  - Complex segments can contain text and parameters. Ex `{mm}-{dd}-{yyyy}`
    - Special complex segment can have an optional file extension (i.e. the dot is special because it is optional too). Ex `/files/{filename}.{ext?}`
- MapRoute extension methods
  - Convenience methods for adding routes to the `RouteBuilder` via the `Route` class
  - https://github.com/aspnet/Routing/blob/master/src/Microsoft.AspNet.Routing/RouteBuilderExtensions.cs#L76
  - You can add additional route constraints using anonymous obj
    - Property values should generally be `IRouteConstraint` implementations
    - Built-in constraints: HTTP verb, regex, etc.
    - If the property value is a string it's treated as a regex constraint
  - Get merged with inline constraints in the template
- Default values
  - Get merged with the defaults in the template, but conflicts cause errors
- Data tokens
  - User defined data bag that gets carried along if the route matches
- Link generation
  - Give routing a set of route values and optionally a route name to produce a URL
  - Current route values of the current request are considered ambient values for link generation
    - Ex When on the About action of the Home controller to link to the Index page you don't need to specify the controller route value.
  - Ambient values that don't match a parameter are ignored
  - Ambient values are ignored when a value explicitly provided overrides it going from left to right in the URL
  - Values the are explicitly provided that don't match anything go into the query string
  - If a route has default values that don't match a parameter and that value is explicitly provided it must match the default value.

**Comment by Daniel15** [comment]
I know this is probably the wrong place to ask, but does ASP.NET 5 support attribute routing (ie. defining routes as attributes on the controllers/actions rather than in one giant config file)?

**Comment by davidfowl** [comment]
yes

**Comment by Daniel15** [comment]
Oh cool, thanks! I'm currently using MVC 4, I didn't realise that attribute routing is actually built into the framework starting from MVC 5 (and MVC 6 has the same attributes)

**Comment by danroth27** [comment]
We should probably also mention common conflicts with routing and IIS:
- Routes with dots generally have issues with static file handling
- Routes with "unsafe" characters get rejected by IIS

**Comment by rmcc13** [comment]
This may be the wrong place to ask, but would a third party person pick up an issue such as this one to work on it? The contributing guidelines say to open up a new issue, but there are many open issues that I would be interested in working on. Should I just work on one then submit a pr?

**Comment by Tessalator** [comment]
@danroth27 by "Routes with dots" you are talking about route templates correct? Or does this apply to route names too?

Also, I'd like to contribute to some type of migration documentation. I'm working on moving an MVC5 application to MVC6 and hit some major roadblocks due to discontinued features. As I find the way to implement my features in 6 I'd like to share those with others. Where would I contribute these things?

**Comment by Daniel15** [comment]
> by "Routes with dots" you are talking about route templates correct?

Yeah, route templates, things like these ones I use on my site:
```
[Route("[action].htm")]
```
```
[Route("category/{slug}.rss", Order = 2, Name = "BlogCategoryFeed")]
```

**Comment by kylone** [comment]
One of the issues I've had problems with ASP.NET MVC (4+) and IIS is handling making custom Not Found and Error pages is all cases. We eventually went with web server directives. Would a middleware piece be appropriate for this?

**Comment by ardalis** [comment]
All these links are to AspNetCore / RC2 files; should I target RC2 with this article or ?  @danroth27 @rynowak

**Comment by danroth27** [comment]
Target RC1. I moved the post-RC1 stuff to a separate issue: https://github.com/aspnet/Docs/issues/986

**Comment by ardalis** [comment]
@rynowak what is the purpose of DefaultHandler and ServiceProvider on RouteBuilder? They don't seem to be used anywhere except the sample project.

**Comment by ardalis** [comment]
Nevermind, it seems to be necessary for extension methods to work, such as MapRoute()

**Comment by ardalis** [comment]
@rynowak From our discussion (notes above): "If a route has default values that don't match a parameter and that value is explicitly provided it must match the default value." This relates to link generation.
I'm not sure how to create an example for this. Here's a route with default values:
"{controller=Home}/{action}"
I'm not sure what you meant by "that don't match a parameter" Now if I go to generate a link for this route, and I pass in an explicit value of "controller=Home", it should do what I expect. If I pass in an explicit value of "controller=Products" it should still do what I expect (generate /Products/something). When would the rule you're describing come into play?

thanks

**Comment by rynowak** [comment]
Here's the example:
```
routes.MapRoute("blog_route", "blog/{*slug}", defaults: new { controller = "Blog", action = "ReadPost" });
```

This will only generate a link when the matching values for controller and action are provided.
