### ISSUE TITLE
Document that [FromRoute] does not unescape %2F

### ISSUE THREAD

**Issue by gldraphael** [aspnet/Docs#6106]
Query string parameters are completely unescaped, but `%2F` from the route parameters are not unescaped to `/`. Not sure if this is the correct page, but this definitely needs to be documented somewhere.

Original discussion: aspnet/Mvc#4599

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Service: **unspecified**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per [`@ryanbrandenburg`](https://github.com/aspnet/Mvc/issues/4599#issuecomment-220113826)

 the guidance would be not to use `[FromRoute]` on any values which are likely to contain `%2f` (`/`)
 and instead use `[FromQuery]` which will give you an entirely URL decoded string 

@gldraphael  is that your understanding of what should be added?

**Comment by gldraphael** [comment]
That's a good recommendation.
I think it's also important to state that `%2F`s will not be unescaped to `/`, because there are other ways to handle it if `[FromRoute]` is desired.

**Comment by gldraphael** [comment]
I think the IIS behaviour must also be documented.

So 

1. `[FromRoute]` does not decode (or unescape) `%2F` to `/`.
1.  Exception: when the app is hosted in IIS, IIS decodes the `%2F`s.

PS: I haven't tested the IIS behavior.

**Comment by Rick-Anderson** [comment]
@gldraphael  we'd rather not document the exception.
