### ISSUE TITLE
Consider renaming Work with static files in TOC

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6108]
I run into this fairly regularly ... it could just be a personal problem or something more widespread ... I'm looking for "Static files" in the *Fundamentals* area of the TOC, and I often read past "Work with static files" because it doesn't match what I'm looking for exactly.

Thoughts on changing the TOC entry to just "Static files"? ... I'd probably stop reading past the link.

**Comment by rachelappel** [comment]
Agreed. "Work with" doesn't really add any value. Removing it is more concise.

**Comment by rachelappel** [comment]
Also "Work with multiple environments" may be better off as "Use multiple environments" or a shortened title.

**Comment by guardrex** [comment]
@scottaddie @Rick-Anderson Any consensus forming on this ...

Work with static files :point_right: Static files
Work with multiple environments :point_right: Use multiple environments

This is a quick patch fix if we do it, since it's only an issue for the sidebar TOC.

I need to take this anyway because we need to exclude the *forbidden word* ...

Route and app convention ~features~ :point_right: Route and app conventions

... and I'll run thru real quick and make sure that *accursed word* :smile: doesn't appear elsewhere.

**Comment by scottaddie** [comment]
@guardrex I like your suggested titles.

**Comment by Rick-Anderson** [comment]
We used to have "Working with Data"
Going to Data access ... was a HUGE improvement.

**Comment by guardrex** [comment]
kk ... should be fairly quick to knock this out. I'll tend to it later this week. I'm still busy bust'in out some 2.1 work right now.
