### ISSUE TITLE
new doc: how to create and use custom route constraints

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6114]
@mjrousos are you interested in providing a first draft of this?

**Comment by Rick-Anderson** [comment]
@mjrousos are you interested in providing a first draft of this?

**Comment by Rick-Anderson** [comment]
@mjrousos who can provide the first draft of this?

**Comment by rynowak** [comment]
I'm not really sure what this work item tracks - we have a doc here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#custom-route-constraints

I think this hits all of the important points already. So I'm closing this. Please reactivate if you think there's something specific we should add.
