### ISSUE TITLE
doc IActionResultExecutor<T> 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6115]
[ IActionResultExecutor<T>](https://github.com/aspnet/Mvc/pull/6822)

* [blog: Using MVC result executors in ASP.NET Core middleware](http://kristian.hellang.com/using-mvc-result-executors-in-middleware/)
* [GitHub comments](https://github.com/aspnet/Mvc/issues/7238)

**Comment by Rick-Anderson** [comment]
@mjrousos are you interested in providing a first draft of this?

**Comment by Rick-Anderson** [comment]
@guardrex 	is this something you could do?

**Comment by guardrex** [comment]
Sure ... I'll do it. I guess next sprint is ok? I have a full plate at the moment.

**Comment by guardrex** [comment]
@Rick-Anderson @tdykstra What's the *where* for this? The current response formatting topic **with controllers** is under web API ...

https://docs.microsoft.com/aspnet/core/web-api/advanced/formatting

... but this topic is `IActionResult` **_for middleware_**. Where would you want this? @tdykstra, I think you're moving middleware subtopics elsewhere leaving a single middleware topic in *Fundamentals* :+1::heart:. I think those other middleware topics are headed for the *Advanced* node? Would this one go in the *Advanced* node?

Content: @khellang, would you like to lend the *Turn it up to 11* section of your blog as the template (and example) for the topic with **_your name on the topic_**? I'll do the conversion if you agree, and you can add/subtract from it as you wish.

**Comment by tdykstra** [comment]
@guardrex This could go under Advanced but it's still about response formatting, so I think it fits better under Web API right after Format response data.

**Comment by guardrex** [comment]
Would never use the approach tho with web API AFAICT. Such projects would just use a controller and OOB `IActionResult` with either in-box output formatting or custom. This seems more like a hybrid middleware-`IActionResult` approach and would be used in middleware scenarios. Just reading the tea leaves tho ... Scott is really the *web API guy* around here. lol

**Comment by Rick-Anderson** [comment]
@jkotalik please suggest where in the TOC this topic should go.

**Comment by guardrex** [comment]
@jkotalik ping ... if too busy to :eyes: tho ... let me know ... I'll kick this back a sprint ... no worries.

**Comment by jkotalik** [comment]
I don't really know much about IActionResultExecutor. @rynowak ?

**Comment by rynowak** [comment]
I think that all that needs to be said is that these APIs allow you to customize what happens when an action result is executed. We shouldn't provide support or guidance for using them outside of MVC. I know that this works, and it's cool, but it's not an official recommendation from the team.

**Comment by guardrex** [comment]
@rynowak 

> customize what happens when an action result is executed

... that's not what a custom output formatter does in MVC/web API?

What's the difference between custom output formatters and using `IActionResultExecutor` in MVC/web API? All I see online is `IActionResultExecutor` with middleware.

**Comment by rynowak** [comment]
Formatters participate in content-negotiation based on a variety of data, and they are always concerned with *how do I write this thing to the response body*. In this case it's the `ObjectResultExecutor` that calls into the formatters. 

Action Results do a million different things. 

> How to use them in MVC/web API is what I need to consider/understand better.

I don't have a clear picture in mind of what kinds of things we'd document related to this.

**Comment by guardrex** [comment]
Ah ... in which case ... @Rick-Anderson, I recommend we close. This is very *edgy* for us, especially considering the workload. If devs want the middleware scenario for this, multiple blogs exist ... well written blogs (i.e., @khellang) ... to explain.

**Comment by zwcloud** [comment]
A related issue when I tried to use `IActionResultExecutor<NotFoundResult>`: https://stackoverflow.com/q/62422481/3427520
I don't know where's the the service containing it that should be added in `Startup.ConfigureServices`.

**Comment by zwcloud** [comment]
I found out
```C#
public static Task WriteActionResult(HttpContext context, NotFoundResult result)
{
       context.Response.StatusCode = result.StatusCode;
       return context.Response.Body.FlushAsync();
}
```

For `StatusCodeResult`, we shouldn't query a `IActionResultExecutor` but write to Response directly.

Learned from WebApiContrib:
https://github.com/WebApiContrib/WebAPIContrib.Core/blob/cfb6deeb0b2c132362597b2362232b5592f1ca1a/src/WebApiContrib.Core/Results/HttpContextExtensions.cs#L37
