### ISSUE TITLE
Doc WebApiCompatShim

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6116]
The [compat shim](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim/) is a useful tool for porting WebAPI 2 projects to ASP.NET Core. It’s well-explained in some [third-party blogs](https://www.strathweb.com/2015/01/migrating-asp-net-web-api-mvc-6-exploring-web-api-compatibility-shim/) and [here ](http://www.dotnetcurry.com/aspnet-mvc/1149/convert-aspnet-webapi2-aspnet5-mvc6) but I couldn’t find any first-party docs or blogs on it. Even the [GitHub repo](https://github.com/aspnet/Mvc/tree/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim) has no description.

**Comment by mjrousos** [comment]
@Rick-Anderson, I can take this one. Should be just a small update to existing migration docs.
