### ISSUE TITLE
Cover how to achieve a 'TryGetOrCreate' if it is possible

### ISSUE THREAD

**Issue by mungojam** [aspnet/Docs#6119]
We had the scenario where we sometimes wanted to abort a GetOrCreate, say if the underlying data isn't ready yet. We couldn't just return null because it would then end up in the cache and might be picked up by another consumer. We went for throwing a custom exception in the end and catching it when calling GetOrCreate, but it would be good to know if there is an intended way to achieve this such as setting a zero expiration time.

Would setting a zero expiration time guarantee that no other caller would pick up the value or would there be a race condition there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mungojam what do you want to `GetOrCreate` ?  Is it something like [TryUpdateModelAsync](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#tryupdatemodelasync) in [Update the Create page](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#update-the-create-page)

**Comment by mungojam** [comment]
@Rick-Anderson I'm not sure that it is. That doesn't seem to be covering the abort of a cache `GetOrCreate`.

In my case, I need to be able to retrieve a value from the cache, but if it doesn't exist yet then it could be either because it just hasn't been requested yet (i.e. `Create` is fine), or because it isn't ready yet in which case I want to abort the `GetOrCreate` without risking other consumers picking up a null or dummy value.

**Comment by mungojam** [comment]
So I think I want a `TryGetOrCreate` and in that sense maybe it is similar

**Comment by Rick-Anderson** [comment]
You could open an issue in the https://github.com/aspnet/EntityFrameworkCore
It might be a good idea to create a proto-type version to show what you want to do.

**Comment by mungojam** [comment]
Thanks, I've now raised https://github.com/aspnet/Caching/issues/390 with some example code

**Comment by Rick-Anderson** [comment]
Thanks.
