### ISSUE TITLE
Update Contributing instructions - Add use of sphinx-autobuild back in

### ISSUE THREAD

**Issue by SpaceShot** [aspnet/Docs#612]
I believe sphinx-autobuild is working again.  I used it today with a machine that didn't have python installed. 

**I can work on adding these back in and clarifying them...**

I installed Python 3.4.3 and followed the old directions to get sphinx-autobuild working:

Other folks working near me used 3.5 and also got this working.

**Should we have instructions to use 3.5 or stick with 3.4 as recommended**

 pip install sphinx
 pip install -U sphinx_rtd_theme
 pip install sphinx-autobuild

I cloned repo into c:\source\docs and after make.bat:

 C:\Source\Docs\aspnet>sphinx-autobuild . _build/html
 [I 151105 09:14:21 server:271] Serving on http://127.0.0.1:8000
 [I 151105 09:14:21 handlers:58] Start watching changes
 [I 151105 09:14:21 handlers:60] Start detecting changes
 [I 151105 09:14:28 handlers:131] Browser Connected: http://localhost:8000/
 [I 151105 09:15:24 server:291] Shutting down...

Opened docs in browser at: http://localhost:8000/

I made changes to .rst files and they were autodetected and the browser refreshed.

**Comment by ardalis** [comment]
Go ahead and recommend 3.5 if it's working; no need to have people installing older versions for no good reason. @danroth27 also wants a link to the video - can you add a section to the top as part of your PR that says "Watch a video showing how to get started building the docs locally" and link to http://ardalis.com/contributing-to-asp-net-5-documentation ?

Thanks!

**Comment by SpaceShot** [comment]
Yep will do... working on it now

**Comment by SpaceShot** [comment]
PR #614 

I backed off on Python 3.5 because, when following the instructions in a clean Win 8.1 VM, it didn't work.  A fellow attendee is working fine, but I'll investigate further before recommending.

But for Python 3.4, followed these instructions to the letter and got the nice autobuilding support in aspnet, mvc, or webhooks folders.

**Comment by Rick-Anderson** [comment]
@SpaceShot I've verified it works with 3.4 and the @ardalis  video is excellent and should be added back.
