### ISSUE TITLE
Default https debug needs to be addressed

### ISSUE THREAD

**Issue by sturlath** [aspnet/Docs#6122]
Hi 

While testing out [Integration testing](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing?view=aspnetcore-2.1) in my VS 15.7.0 preview 3 with .net Core 2.1 I could´t get the integration tests to pass because of  

> "Response status code does not indicate success: 307 (Temporary Redirect)."

I had to add the following line to get it to work. It just overrides the http to https

`_client.BaseAddress` = new System.Uri("https://localhost/");

Is that how you should do it or is there something else you should do. 
I could not find any "switch" for it.

At least this worked for me. 
But it feels somewhat hacky...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda5d096-4337-3256-afcd-fe45436a2067
* Version Independent ID: a9e691a2-a8bf-b477-88aa-73676896b75e
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/testing/integration-testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/testing/integration-testing.md)
* Service: **unspecified**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@sturlath You asked at the *perfect time*. We're working on the doc for this scenario as we speak on https://github.com/aspnet/Docs/pull/6086.

AFAIK, yes, you set the base address on the client options. We have this in the draft doc thus far ...

```csharp
var clientOptions = new WebApplicationFactoryClientOptions();
clientOptions.AllowAutoRedirect = true;
clientOptions.BaseAddress = new Uri("http://localhost");
clientOptions.HandleCookies = true;
clientOptions.MaxAutomaticRedirections = 7;

_client = testWebAppFactory.CreateClient(clientOptions);
```
... and it doesn't address your scenario (yet! :smile:) for testing against a secure endpoint.

I'll add a note+example to the *Client options* section if confirmed ... @javiercn, cool? ...

> To test against a secure endpoint, provide a secure endpoint address to the `BaseAddress` property of the client options:

> ```csharp
> clientOptions.BaseAddress = new Uri("https://localhost");
> ```

**Comment by javiercn** [comment]
Closing this as it has been answered. This can also be done when overriding the factory. On the derived factory constructor you can just do `ClientOptions.BaseAddress = new Uri("https://localhost");` and then on the tests you just call CreateClient().
