### ISSUE TITLE
Update the aspnetcore/mvc/models file-upload example

### ISSUE THREAD

**Issue by mohchari** [aspnet/Docs#6131]
The file-upload example does not build on OSX. I haven't looked through but I imagine this is the case in some of the other examples in the aspnetcore area. 

I can submit a pull request if necessary.

**Comment by Rick-Anderson** [comment]
> I can submit a pull request if necessary.

That would be great.

**Comment by guardrex** [comment]
Hello @mohchari - Thanks for commenting. The broken sample is tracked by https://github.com/aspnet/Docs/issues/4777. The topic and the sample are due for a major overhaul on https://github.com/aspnet/Docs/issues/5331.

@Rick-Anderson I was just about to close as a dup and tell @mohchari to talk to `@scottaddie` on those issues about helping with the work.
