### ISSUE TITLE
usings

### ISSUE THREAD

**Issue by gbjbaanb** [aspnet/Docs#6132]
In the code samples, it is important to show which using statements are required - particularly as CacheControlHeaderValue() requires Microsoft.Net.Http.Headers and not System.Net.Http.Headers (which is the first in the list intellisense suggests)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.0)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Service: **unspecified**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @gbjbaanb for reporting this. I'll get to it asap.
