### ISSUE TITLE
Request Features in ASP.NET Core needs a sample project with compiling code.

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#6134]
[Request Features in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/request-features?view=aspnetcore-2.1) needs a compilable sample project with actual code in order to be useful.

**Comment by user135711** [comment]
@Rick-Anderson I took a look at doing this one today and I think I'll do it next weekend. I started an example that I was going to show how to use the provided request features in middleware using context.Features.Get<IHttpRequestFeature>() and context.Features.Set<IHttpRequestFeature>(), and then implement a simple custom server feature but I haven't finished reverse engineering the syntax to register a custom feature from the source code as described in the Documentation. Hopefully next Saturday or Sunday I'll have time.

**Comment by Rick-Anderson** [comment]
@user135711  no problem, next week is fine.
@Tratcher  who can provide code to register a custom feature from the source code

**Comment by Tratcher** [comment]
Something like this?
https://github.com/aspnet/Session/blob/06f473724870cd4704ab48388d80ffdaddb0f630/src/Microsoft.AspNetCore.Session/SessionMiddleware.cs#L101-L111

**Comment by user135711** [comment]
@Rick-Anderson You're going to have to assign this to someone else. Landlord e-mailed me today saying he was doing unnecessary maintenance that I was going to pay for so I'm busy searching for a better place.

**Comment by Rick-Anderson** [comment]
@user135711  OK, thanks. Maybe you can do it in a few weeks.

**Comment by user135711** [comment]
@Rick-Anderson Sure, the synchronization context has been saved and whenever I get caught up I'll try and post a delegate sample on the Github thread where I left off.

**Comment by Rick-Anderson** [comment]
@user135711 	do you have a sample?

**Comment by user135711** [comment]
@Rick-Anderson Feel free to reassign these if you need them now. I'll see what I can do this upcoming week otherwise. The code sample Tratcher provided was the part I already understood. The more interesting part that I wanted to know how to do and may be an example too advanced for my time allotment was create and register a custom feature that doesn't already exist.

> Additionally, middleware can add to the feature collection established by the server. Existing features can even be replaced by middleware, allowing the middleware to augment the functionality of the server. Features added to the collection are available immediately to other middleware or the underlying application itself later in the request pipeline.

 I'll have to look at the code again to see how it's done for the existing features and get my brain back in ASP mode.

**Comment by user135711** [comment]
@Rick-Anderson Sometime in the next few weeks I'll likely have time to do this one and #6130. Been busy with stuff that I finished.

**Comment by Rick-Anderson** [comment]
Moved to  #10557
