### ISSUE TITLE
set-cookie

### ISSUE THREAD

**Issue by gbjbaanb** [aspnet/Docs#6135]
It would be worth noting for aps.net core 2.0, the default tempdata system uses cookies, and so if you put the above code in, response caching will still not work. Some note should be placed to highlight this and what to do to resolve it, even if its a link to the itempdata API reference.

A note about the antiforgery cookie is present, even though it doesn't say how to turn that off for a page you want cached.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10cda0f9-e2c7-015d-4fbf-d361f6c67d9f
* Version Independent ID: 13154131-c2b6-2c72-fb0e-1d83bca4e21a
* Content: [Response Caching Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/middleware?view=aspnetcore-2.0)
* Content Source: [aspnetcore/performance/caching/middleware.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/middleware.md)
* Service: **unspecified**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> Some note should be placed to highlight this and what to do to resolve it

We can note it, but we can't resolve it. The Response Caching Middleware follows the HTML caching specification (it isn't a server-side output cache), so this is normal behavior for this type of cache. There is a plan to build a server-side output cache, but it's just a plan at this point.

> it doesn't say how to turn that off for a page you want cached.

Sure, we can link over to it :point_right: https://docs.microsoft.com/aspnet/core/security/anti-request-forgery#aspnet-core-antiforgery-configuration
