### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by wcski** [aspnet/Docs#6141]
Hello, and thanks for the documentation. I have a quick question about adding search by genre.

The following code allows you to search by title and genre and seems to be a much simpler approach.

`public async Task<IActionResult> Index(string searchString)
        {
            var movies = _context.Movie.AsQueryable();
                         

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(movie => movie.Title.Contains(searchString) || movie.Genere.Contains(searchString));
            }

            return View(await movies.ToListAsync());
        }`

Is there a reason why I should do all of what the documentation describes, or was it just for practice' sake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Adding Search](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the article
However, you can't expect users to modify the URL every time they want to search for a movie. So now you'll add UI elements to help them filter movies.

**Comment by wcski** [comment]
Sorry, I don't see how that answer is relevant. That line from the article is in reference to querying without a search UI element. With the code in my original question there is no need to modify the URL.

No big deal, I was more just curious than anything.

**Comment by Rick-Anderson** [comment]
You could use that query. You'd also need to use a POST to bookmark the query. WIthout UI, how would the user know to hack the URL for a search.

**Comment by Rick-Anderson** [comment]
@wcski  no problem. I think the Razor Pages version does a better job of explaining it, and the code is simpler. The view model is build into Razor Pages, one of the advantages it has over MVC. 

BTW, why are you doing the MVC tutorial and not the Razor Pages version?

**Comment by Rick-Anderson** [comment]
@wcski  Your search does an `or`, but the search is an `and`. 
The view model needs to contain the list of genres and the specific genre selected.

**Comment by wcski** [comment]
Ah. I didn't look close enough. I see now that the tutorial has you create a select list (so you can filter by Genre and Title, like you said.) I told you it was a beginner question! Thanks for your help.

As for Razor vs MVC - I have already done the Razor pages tutorial. I am doing the MVC tutorial because the projects I will be working on at work are MVC and not Razor pages.

**Comment by Rick-Anderson** [comment]
@wcski  Thanks for the info. I added it to #6146 and I'll add a link to it to the tutorials.
