### ISSUE TITLE
Missing Info class details

### ISSUE THREAD

**Issue by raybo604** [aspnet/Docs#6143]
Great article. Filled this in from the Swashbuckle version:
app.UseSwagger(typeof(Startup).Assembly, settings =>
{
    settings.PostProcess = document =>
    {
        document.Info.Version = "v1";
        document.Info.Title = "ToDo API";
        document.Info.Description = "A simple example ASP.NET Core Web API";
        document.Info.TermsOfService = "None";
        document.Info.Contact = new NSwag.SwaggerContact
        {
            Name = "Shayne Boyer",
            Email = string.Empty,
            Url = "https://twitter.com/spboyer"
        };
        document.Info.License = new NSwag.SwaggerLicense
        {
            Name = "Use under LICX",
            Url = "https://example.com/license"
        };
    };
});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.0&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Service: **unspecified**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@raybo604 Thank you for reporting this problem. I've added the missing info. The change should go live later today.

**Comment by andycshi** [comment]
Hello,

I'm using NSwag.AspNetCore 12.0.13 version and all works great when I run in local machine. But, When I deploy code to Server with New Virtual Directory under IIS/DefaultSite/NewSite it gives me error Failed to load API definition.(Swagger/v1/swagger.json).


I'm using .net core 2.1 and Nswag.AspNetCore 12.0.13 version.

Code Block

ConfigureServices()

services.AddSwaggerDocument(configure =>
{
    configure.PostProcess = document =>
    {
        document.Info.Version = "v1";
        document.Info.Title = "My API";
        document.Info.Description = "ASP.NET Core Web API";
    };
});

Configure()  

app.UseSwagger();
app.UseSwaggerUi3();

Any help is appreciated.
