### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by Ikarus76** [aspnet/Docs#6144]
My observation is that the class name of the TagHelper is case sensitive. If you use the classname "EmailTagHelper", you have to use <Email> tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Ikarus76  the Razor Markup is not case sensitive. Is there anything in particular in the document you feel is incorrect or incomplete?

You can test case-insensitivity by with the built in templates.

**Comment by Ikarus76** [comment]
Hi,
I derived my class from SelectTagHelper. Implemented the c'tor and the Process method. Classname is 'myselectTagHelper'. In the view I can use the myselect-tag. When I use 'MySelectTagHelper' as class name, myselect in lower case doesn't work. Maybe it's because I derived from SelectTagHelper and not from TagHelper...

**Comment by Rick-Anderson** [comment]
C# is case-sensitive, Razor tags are not.
