### ISSUE TITLE
Custom providers

### ISSUE THREAD

**Issue by norachuga** [aspnet/Docs#6157]
"You can create your own custom providers as well"

How about some documentation on that? There's links to third-party providers, but due to their scale, they are terrible for use as examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#third-party-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Service: **unspecified**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@norachuga  thanks for the feedback. The built in provider is pretty good and the 3rd party loggers fill in most gaps. Why do you want to create your own custom provider?

**Comment by norachuga** [comment]
I have an existing logging service that I simply need to connect to. Using any third-party provider is overkill. I was able to figure out about 75% of it using guides I found on Google, but they are all written for 1.0 and don't address the changes to logging in 2.0+.

I find it quite bizarre that you would consider removing the line saying you can write a custom provider rather than provide a simple example of something like logging to the database.
