### ISSUE TITLE
Restoring Aspnet 5 project from cs online git repo cause visual studio to crash.  Cant delete the local repo due to file path too long error.

### ISSUE THREAD

**Issue by ltheONEl** [aspnet/Docs#617]
I have been working my way through the tutorial documentation, building various examples under a single solution.  I pushed this project into my git repo in visual studio online.
Later I tried pulling the project from git to another windows 10 pc, using visual studio (2015 pro).  
As soon as I opened the solution vs started executing various npm tasks.  before completing this visual studio crashed,  I rebooted and tried again,  visual studio crashed immediately.  
I assumed it had something to do with the solution I had just restored and went to the file system to delete the repository to see if I could get visual studio working again.
Turns out I cant delete the repository because the path to this file: bitbucket-https-with-embedded-auth.js is too long for the file system.   (really in this day and age!)

here is the path that was created during the package restore phase:
D:\GitRepos\Asp vNext Tutorials\AspVnextLearning\RequestPipelineExamples\node_modules\gulp\node_modules\gulp-util\node_modules\dateformat\node_modules\meow\node_modules\normalize-package-data\node_modules\hosted-git-info\test\bitbucket-https-with-embedded-auth.js

How on earth can I get my solution working again?

**Comment by Rick-Anderson** [comment]
You should be able to Shit + delete to delete the parent folder, but you can't delete it from the command line.
I use robocopy - see http://superser.com/questions/45697/how-to-delete-a-file-in-windows-with-a-too-long-filename
to delete the node directory when I need to delete it from a script.
mkdir empty_dir
robocopy empty_dir the_dir_to_delete /s /mir
rmdir empty_dir
rmdir the_dir_to_delete

You don' need to reboot. When this happens to me, I can usually get the solution to load on the 2nd attempt.
Open the project and give npm a chance to restore everything.

**Comment by Hamaze** [comment]
Make sure you have a .gitignore file in the solution

**Comment by ltheONEl** [comment]
seems it was a bug in visual studio:  https://connect.microsoft.com/VisualStudio/feedback/details/1988360/opening-aspnet5-solution-from-cloned-repository-causes-visual-studio-to-crash

I have a .gitignore,  but the problem occurred during npn restore tasks.

Shift + Del did not work still got the same error, however I mapped the deepest folder I could get to as a network drive which allowed me delete the contents then I was able to delete the local repo completely via the file system.

**Comment by danroth27** [comment]
Doesn't look like a doc bug.
