### ISSUE TITLE
Update razor-pages-convention-features.md

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#6173]
Three bugs:
1)Navigate to the sample app localhost:5000/TheContactPage
The index page is loaded instead of localhost:5000/Contact when the optional route is left off with the TheContact. I stepped through the call stack starting from the loading of RazorPages from the pages directory and haven't found the point where the index is loaded yet so I don't know if this is a doc or core bug.

2)Navigate to the sample app localhost:5000/TheContactPage/TextValue
Mouse over the links in the top and you will see that every link has been replaced with the TheContactPage appended to every link.

A confusing point in the article: The notes all indicate that the order property determines which route comes first {globalTemplate?} vs {aboutTemplate?}. This wording makes it seem like the order of directories /GlobalRouteValue/OtherPagesRouteValue was determined by this number but stepping through the sourcelink provided .NET CORE source code shows that the order of the route order is determined by the order that options.Conventions.Add are called in the startup. This is because the model.Selectors.Add in the sample adds a new selector attribute route model template on top of the one that already exists. So each route added creates a route plus the old ie 1,2, 1/2, 3, 1/3, 1/2/3, 1/4, 2/4, etc... The example happened to create a conflict by appending templates rather than adding a new template and the selection of the template when one value is provided then gets resolved between {globalTemplate?} vs {aboutTemplate?} using the order. I think you could make this clear just by adding one line at the top note saying the order of routes is determined by the template. You can see an example by switching the call order in startup between snippets 1 and 3 options.Conventions.AddFolderRouteModelConvention("/OtherPages" and options.Conventions.Add(new GlobalTemplatePageRouteModelConvention() and then navigating to localhost:5000/OtherPages/Page1/GlobalRouteValue/OtherPagesRouteValue and observe that the html now displays
"Route data for 'globalTemplate' was provided: OtherPagesRouteValue
Route data for 'otherPagesTemplate' was provided: GlobalRouteValue"
in contradiction with the note stating that the order property decided the route order "The Order property for the AttributeRouteModel is set to 1. This ensures that the template for {globalTemplate?} (set earlier in the topic) is given priority for the first route data value position". Here there was no conflict between equally specific routes and was determined by the calls to the order.

**Comment by user135711** [comment]
See the link for #2. The contact page appears correct because it's a link to the default index with TheContactPage appended. Each of the links will still load the correct link but the url link and the url in the address bar once clicked have an erroneous TheContactPage, that seems to be tolerated by the routing. 
<a href="https://drive.google.com/open?id=1yLCQgfULkiPRioaTNP9rhpNxayxe8agI"><img src="https://drive.google.com/open?id=1yLCQgfULkiPRioaTNP9rhpNxayxe8agI" alt="contact" height="42" width="42"></a>

**Comment by guardrex** [comment]
Sorry ... I didn't understand the repro. Yes, I see it now. I updated "Issue 2" and show the markup generated.

**Comment by guardrex** [comment]
@user135711 I'm working on this now. I ask the MVC/RP engineers about the behavior on https://github.com/aspnet/Mvc/issues/8385. After hearing back, I can proceed. They'll probably either say "by-design" or "bug." After Issues 1 and 2 are addressed here, I'll take a look at Issue 3.

**Comment by user135711** [comment]
@guardrex thanks for letting me know, I subscribed to the other thread.

**Comment by user135711** [comment]
@guardrex yes, I watched the solution as it unfolded :)

**Comment by guardrex** [comment]
Best intentions at least. I don't want multiple samples for any of these topics (if possible). It's unlikely that a given dev would be required to implement several of these *in one app*, but it's best for the repo if ww restrict sample proliferation. I suspect that when I move the `/TheContactPage` page route **_UP!_** in the order that it will match and the whole sample will work.
