### ISSUE TITLE
Add search to ASP.NET Core Razor Pages

### ISSUE THREAD

**Issue by RogExp** [aspnet/Docs#6174]
As searching is the heart of all applications, I would like you to advance multiple searching criteria examples.
It would be very nice to see some examples using some kind of generic filtering.
The filters should be generated based on an entity-object (usually outermost entity displayed), offering eg.:
DateTime (<, <=, ==, >, >=, >, InRange)
Int (<, <=, ==, >, >=, >, InRange)
String (Contains, Equals, StartsWith)

Regards Roger.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RogExp  thanks for your suggestion.

**Comment by Rick-Anderson** [comment]
@RogExp  searching is part of .NET Core, so we'll defer to them for searching tutorials.

**Comment by RogExp** [comment]
Yes it's of course the server side that is most affected by this. To explain what I mean, here are some links:
 http://www.palmmedia.de/blog/2012/2/18/aspnet-mvc-generic-filtering-based-on-expressions
https://stackoverflow.com/questions/45101979/add-paging-links-to-view-using-multiple-search-strings-asp-net-core-visual-studi

Getting eg. the scaffolded razor pages utilising this automatically, you would have some real interesting stuff. On the other hand it's probably some added product/templates which would handle this....

**Comment by Rick-Anderson** [comment]
The [ASP.NET MVC - Generic filtering based on expressions](http://www.palmmedia.de/blog/2012/2/18/aspnet-mvc-generic-filtering-based-on-expressions) blog is interesting, but it doesn't need to be tied to MVC.  @BillWagner  does the .NET docs have anything comparable? 

The [SO](https://stackoverflow.com/questions/45101979/add-paging-links-to-view-using-multiple-search-strings-asp-net-core-visual-studi) shows that Razor Pages are better - you don't need all the messy ` ViewData`

Compare the [EF/MVC sort](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.1) with the [RP/EF](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1) where I get rid of all the messy ` ViewData`

The searching in the .NET Core docs applies directly to ASP.NET Core.

**Comment by RogExp** [comment]
Thanks Rick, I really appreciate your answers and time. Doing desktop development, I have used some RAD tools that choosing an entity to show as the master-entity of the form, you have automatically got the searching functionality on the form adapting to the server/data-model functionality of the entity.
This is not always what you want, but usually it's a good starting point for the form, ie. it's usually better to remove some searching-functionality/searching-fields, than having to do all the programming needed to get some searching on the form(s).  But as we have stated, this is also a matter of synchronizing the form to the server-side/data-model functionality.
What I probably mean is that, eg, the initial scaffolded Razor pages could contain the searching functionality for almost all the fields of the entity.

**Comment by Rick-Anderson** [comment]
You could open an issue in https://github.com/aspnet/Scaffolding/issues requesting that feature, but I'm sure they will have the same opinion as me. That's best left to the developer. Searching can be very inefficient.

**Comment by RogExp** [comment]
Thanks Rick. I'll think about opening an issue. As one has done searching for one/two fields it's probably just a matter of copying to add more. However I think it would be a booster for .net core and Razor pages to have this kind of automatic search-functionality. It would be easier to show the company managements how effective the programming is ;-).
And it's always on  the programmer to create needed indexes or remove search-fields not needed.
