### ISSUE TITLE
Existing Database Example

### ISSUE THREAD

**Issue by jverbosky** [aspnet/Docs#6176]
Just thought my notes for using an existing database might help the next person.

    ------------------------------------------------------------
    
    # Add a model
    
    ---------------------------
    
    # - create a new table (Movie) in the JVTest DB using the MvcTutorial schema
    
    USE [JVTest];
    GO
    
    -- run this once to avoid error about schema not existing
    CREATE SCHEMA MvcTutorial
    
    CREATE TABLE [MvcTutorial].[Movie] (
        [ID] int NOT NULL IDENTITY,
        [Title] nvarchar(max) NOT NULL,
        [ReleaseDate] datetime NOT NULL,
        [Genre] nvarchar(max) NOT NULL,
        [Price] decimal(10,2) NOT NULL,
    	
        CONSTRAINT [PK_Movie] PRIMARY KEY ([ID])
    );
    GO
    
    # - note that using Entity Framework requires that the target table have a specified primary key
    #   and if multiple related tables are specified, that each have a primary key and the related table have a foreign key
    # - related: https://stackoverflow.com/questions/3996782/entity-framework-table-without-primary-key
    
    ---------------------------
    
    # - run dotnet commands to add necessary packages
    
    dotnet add package Microsoft.EntityFrameworkCore.SqlServer
    dotnet add package Microsoft.EntityFrameworkCore.Tools
    dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design
    dotnet restore
    
    ---------------------------
    
    # - update the .csproj file with a DotNetCliToolReference for Microsoft.EntityFrameworkCore.Tools.DotNet
    
    <Project Sdk="Microsoft.NET.Sdk.Web">
    
      <PropertyGroup>
        <TargetFramework>netcoreapp2.0</TargetFramework>
      </PropertyGroup>
    
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
      </ItemGroup>
    
      <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
        <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.2" />
      </ItemGroup>
    
    </Project>
    
    ---------------------------
    
    # restore the package/tool dependences, then scaffold model for MvcTutorial.Movie table
    
    dotnet restore
    dotnet ef dbcontext scaffold "Server=tcp:SQL123,1433;Initial Catalog=JVTest;User ID=******;Password=******;" Microsoft.EntityFrameworkCore.SqlServer -o Models --schema MvcTutorial -t Movie
    
    # results in this warning, but after researching determined this may just be related to schema/tables that don't match the command's constraints (schema/tables):
    
    Index column EFTutorial.Blog belongs to index PK_Blog on table BlogId which is not included in the selection set. Skipping.
    Index column EFTutorial.Post belongs to index PK_Post on table PostId which is not included in the selection set. Skipping.
    Index column eightyfourlumber.CreditApp belongs to index PK__CreditAp__3214EC2766603565 on table ID which is not included in the selection set. Skipping.
    Foreign key column BlogId belongs to foreign key FK_Post_Blog_BlogId on table EFTutorial.Post which is not included in the selection set. Skipping.
    
    # machine-generated files:
    # /Models/Movie.cs
    #   - model for the MvcTutorial.Movie table
    # /Models/JVTestContext.cs
    #   - DB connection & tables reference
    #     - per: https://stackoverflow.com/questions/31953317/what-is-the-purpose-of-a-db-context-class-in-asp-net-mvc
    
    ---------------------------
    
    # move the DB connection string into the configuration file (appsettings.json)
    
    # - add an entry for the connection string to ./appsettings.json:
    
    {
        "Logging": {
            "IncludeScopes": false,
            "LogLevel": {
                "Default": "Warning"
            }
        },
        "ConnectionStrings": {
            "MvcTutorial": "Server=tcp:SQL123,1433;Initial Catalog=JVTest;User ID=******;Password=******;"
        }
    }
    
    # - add the following namespaces to ./Startup.cs:
    #   - tip: MvcMovie.Models is the namespace used in JVTestContext.cs
    
    using Microsoft.EntityFrameworkCore;
    using MvcMovie.Models;
    
    # - add a service for AddDbContext to the ConfigureServices() method in the Startup class (./Startup.cs):
    
            public void ConfigureServices(IServiceCollection services)
            {
                services.AddMvc();
    
                // get connection string from configuration file (appsettings.json)
                services.AddDbContext<JVTestContext>(options => 
                    options.UseSqlServer(Configuration.GetConnectionString("MvcTutorial")));
            }
    
    # - delete the OnConfiguring method from the JVTestContext class (./Models/JVTestContext.cs):
    
            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                if (!optionsBuilder.IsConfigured)
                {
    #warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                    optionsBuilder.UseSqlServer(@"Server=tcp:SQL123,1433;Initial Catalog=JVTest;User ID=******;Password=******;");
                }
            }
    
    # - add the following to JVTestContext class (./Models/JVTestContext.cs - after "public virtual DbSet<Movie>..."):
    
            public JVTestContext(DbContextOptions<JVTestContext> options) : base(options)
            {
    
            }
    
    ---------------------------
    
    # scaffold a controller (with CRUD operations) for the Movie model
    # - Create a controller section in tutorial just gives point & click instructions using Visual Studio
    # - tip: ran "dotnet aspnet-codegenerator --help" and "dotnet aspnet-codegenerator controller --help" to get a list of command options
    #    -name <name of the controller file - should typically be ****Controller>
    #    -outDir <directory to output the new controller file - should typically be Controllers>
    #    -m <name of the model being used for generating the controller - looks in /Models directory>
    #    -dc <name of the context file used for generating the controller - looks in /Models directory>
    #    -udl <specifies that resulting CRUD views in /Views/[controller_name] should use the default layout file [/Shared/_Layout.cshtml]>
    # - tip: https://dev.to/andre2w/scaffolding-with-aspnet
    
    dotnet aspnet-codegenerator controller -name MoviesController -outDir Controllers -m Movie -dc JVTestContext -udl
    
    # machine-generated files:
    # /Controllers/MoviesController.cs
    # /Views/Movies/Create.cshtml
    # /Views/Movies/Edit.cshtml
    # /Views/Movies/Details.cshtml
    # /Views/Movies/Delete.cshtml
    # /Views/Movies/Index.cshtml
    
    # tip: the Views subdirectory name is based on the name of the controller (MoviesController > Movies view subdirectory)
    # tested CRUD operations via http://localhost:5000/movie and all working properly (verified DB table updates)
    
    ------------------------------------------------------------
    

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acf0cee-ea0e-b1ca-d239-a8f2bb465f5b
* Version Independent ID: 20f61d94-ae6a-af54-e089-dc6be40182a0
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/adding-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/adding-model.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jverbosky** [comment]
Ouch - I didn't realize this was going to use Markdown...

**Comment by Rick-Anderson** [comment]
@jverbosky  thanks!
