### ISSUE TITLE
CourseID property missing from code

### ISSUE THREAD

**Issue by tonogdlp** [aspnet/Docs#6183]
I think a CourseID property declaration is missing in the code where you modify Instructors/Index.cshtml.cs, in "Add courses taught by selected instructor". The code throws an error when trying to use "Model.CourseID" on Index.cshtml

Also, when you explain how selecting an Instructor works by
       if(item.ID == Model.InstructorID) {selectedRow = "success";}

 the code you show is from the next section:
       if (item.CourseID == Model.CourseID){ selectedRow = "success";}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's a parm in the function
`public async Task OnGetAsync(int? id, int? courseID)`

`?` means it's optional and might be null. That's why it's checked before using.

```
    if (courseID != null)
    {
        CourseID = courseID.Value;
        Instructor.Enrollments = Instructor.Courses.Where(
            x => x.CourseID == courseID).Single().Enrollments;
    }
```

**Comment by tonogdlp** [comment]
You use that nullable type value to set a property called "CourseID", with capital C. 
if (courseID != null)
    {
        CourseID = courseID.Value;
        //code omitted
    }

There should be a property declaration such as:

         public int CourseID {get; set;}

probably after..... InstructorID {get; set;}
That way, when you can actually use it in the Instructor/Index.cshtml file:

     string selectedRow = "";
            if (item.CourseID == Model.CourseID)
            {
                selectedRow = "success";
            }

Otherwise, Model.CourseID  and CourseID = courseID.value both throw errors.

**Comment by Rick-Anderson** [comment]
`CourseID` is declared in the PageModel class containing that method.

**Comment by Rick-Anderson** [comment]
@thomasiverson  so it's bringing in the wrong code snippet. Thanks, I'll get that fixed.

**Comment by thomasiverson** [comment]
Thanks Rick!  it appears there is an issue with the Html.ActionLink in the courses table as well (index.cshtml - line 87).  it is not rendering the link properly.

**Comment by zedOdin** [comment]
Now it's running--->
1)block "@if (Model.Instructor.Courses != null){ //code }" ~ must be in 'Pages/Instructors/Index.cshtml' not in 'Pages/Courses/Index.cshtml'.
2) in 'Pages/Instructors/Index.cshtml.cs' line "CourseID = courseID.Value;" ~ must be "InstructorID = courseID.Value;"
3) same with 'Pages/Instructors/Index.cshtml' line "if (item.CourseID == Model.CourseID)" ~ must be "if (item.CourseID == Model.InstructorID)".
