### ISSUE TITLE
Startup config is not necessary for .net core 2 apps, but this is not clear

### ISSUE THREAD

**Issue by tomstylesncc** [aspnet/Docs#6186]
Many users will arrive at this page because they are creating a new asp.net core 2 app and wanting to do things correctly. 
For example https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.1&tabs=aspnetcore2x

However the startup section in the tutorial is only applicable for .net core 1. Please can this be updated or at least made clear which step are for which environment. 

Bit of a time sink in the otherwise brilliant docs. Thanks for all the hard work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tomstylesncc  Is the problem with [Microsoft Account external login setup ](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins) ? It looks like you came from [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=visual-studio)

**Comment by tomstylesncc** [comment]
The problem is with the [safe storage of secrets page](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=visual-studio). 

The code referenced on line 100 of the .md file is only required for .net core 1 apps. In .net core 2 the set up is handled by default. 

[This PR](https://github.com/aspnet/Docs/pull/4290/files) updated some of the sample code for core 2 but the startup config didn't get updated.

**Comment by tomstylesncc** [comment]
Rick, Long time reader first time contributor here. How do you go about updating the docs for this change. In essence the config sections just need removing for core 2 but are still valid in core 1. Do you:
- A Write the docs just for core 2
- B Write the docs for core 2 but cover core 1 in a separate section
- C Just add a note to the existing document that say's you can skip this bit for core 2.

**Comment by scottaddie** [comment]
@Rick-Anderson That's accurate. You can also use `>=` and `<=`.

**Comment by NinoFloris** [comment]
Also no need for the tool install anymore as it's bundled in 2.1 by default as a global tool
