### ISSUE TITLE
Merge migration documentation

### ISSUE THREAD

**Issue by mjrousos** [aspnet/Docs#6192]
There are separate pages for [ASP.NET to ASP.NET Core 1.x migration](https://docs.microsoft.com/en-us/aspnet/core/migration/mvc?view=aspnetcore-2.1) and [ASP.NET to ASP.NET Core 2.0 migration](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.1) but they overlap and neither is specifically about migrating to a particular ASP.NET Core version. Both pages have good general migration advice. 

The -> ASP.NET Core 1.x migration section is a little more filled out so it probably makes sense to rename it to 'ASP.NET to ASP.NET Core' and merge whatever unique guidance is in the current ASP.NET Core 2.0 migration document.

**Comment by scottaddie** [comment]
@mjrousos This is currently being worked on. See the linked PR.
