### ISSUE TITLE
Alternate [HttpPost] Edit() methods to view raw form data

### ISSUE THREAD

**Issue by jverbosky** [aspnet/Docs#6196]
In case this might help anyone else understand the "[Bind(...) Movie movie" parameter in the [HttpPost] Edit() method a little better (or just be useful when troubleshooting), here's a couple of alternate methods that can be swapped in to view the raw POST data.  Might be useful down the road if values aren't being returned as expected.

    // POST: Movies/Edit/5
    // approach to view POST'd values - can return a string 
    [HttpPost]
    public string Edit(string Id, string Title, string ReleaseDate, string Genre, string Price)
    {
        string postValues = "Id: " + Id + " | ";
                postValues += "Title: " + Title + " | ";
                postValues += "ReleaseDate: " + ReleaseDate + " | ";
                postValues += "Genre: " + Genre + " | ";
                postValues += "Price: " + Price + " | ";

        return postValues;
    }

    // POST: Movies/Edit/5
    // approach to view POST'd values - can return ActionResult object as HTML using Content()
    [HttpPost]
    public ActionResult Edit(string Id, string Title, string ReleaseDate, string Genre, string Price)
    {
        string postValues = "<html><head>";
                postValues += "<style type='text/css'>tr:nth-child(even){background-color:#f2f2f2;}th,td{padding:6px;}</style>";
                postValues += "</head><body><table><tbody>";
                postValues += "<tr><th>Field</th><th>Value</th></tr>";
                postValues += "<tr><td>Id</td><td>" + Id + "</td></tr>";
                postValues += "<tr><td>Title</td><td>" + Title + "</td></tr>";
                postValues += "<tr><td>ReleaseDate</td><td>" + ReleaseDate + "</td></tr>";
                postValues += "<tr><td>Genre</td><td>" + Genre + "</td></tr>";
                postValues += "<tr><td>Price</td><td>" + Price + "</td></tr>";
                postValues += "</tbody></table></body></html>";

        return Content(postValues, "text/html");
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e5e9f5-3f30-a57c-15c1-8f748977e28f
* Version Independent ID: 3ad7ef27-c6ab-1ecb-00ee-918c2fa05a9f
* Content: [Controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/controller-methods-views?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/controller-methods-views.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/controller-methods-views.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jverbosky  Thanks for the info. Alternatively, you can inspect them in the debugger.
