### ISSUE TITLE
Strongly typed hubs

### ISSUE THREAD

**Issue by devindran** [aspnet/Docs#6204]
I can't find any information about this online so I'd like to ask here

In my Hub, by default any outgoing call needs to specify a string method. I have read and tested that if I strongly type the hub e.g. MyHub : Hub< IMyHub > then I get to write something like this
this.Clients.All.MyMethod();  instead of SendAsync("MyMethod")

I have the following scenario:
On my aspnet core code, I have a WebAPI that will accept post requests. The controller needs to be able to call MyHub.DoSomething() which would process some logic and finally call Clients.All.MyMethod();

However, if I declare the IHubContext<MyHub,IMyHub>, then I effectively get direct access to MyMethod, but I want to be able to call MyHub.DoSomething. This is weird because if I just declared it as IHubContext<MyHub> then I could do SendAsync("DoSomething"). 

I feel something is amiss here.  Is there another interface I can use in my Controller to hit the instance of MyHub and call DoSomething?

I really do not want to be managing all this string methods between the server and client. I thought strongly typing the hub was supposed to prevent that, but I'm getting nowhere with this approach.
Thanks.

**Comment by rachelappel** [comment]
Closing since there is another issue covering this. Can re-open if further questions arise.
