### ISSUE TITLE
How do i store secrets in production ?

### ISSUE THREAD

**Issue by aboyaniv** [aspnet/Docs#6205]
How to store secrets in production? 
In asp.net I used  aspnet_regiis.exe -pe . 

Edit: 
I need to encrypt the : 
Sql connection string, The JWT secret, application config keys ...
My production environment is on private cloud.

What is the best way to do it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the article
You can safeguard Azure test and production secrets with the Microsoft Azure Key Vault configuration provider. See Azure Key Vault configuration provider for more information.

When you deploy your application to a test or production server, you can override the DefaultConnection key value with an environment variable setting that contains the connection string (potentially with sensitive credentials) for a test or production database server.

**Comment by Palpie** [comment]
So not for use in IIS on a Windows Server?

**Comment by weifenluo** [comment]
#12428
