### ISSUE TITLE
Documentation error regarding skipping HTTPS in development

### ISSUE THREAD

**Issue by phybr** [aspnet/Docs#6206]
The documentation states that you should add "LocalTest:skipSSL" to the appsettings.Development.json file, but in the mvc options you are looking for the skipHTTPS value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@phybr  can you copy/paste the portion of the doc that's incorrect?

**Comment by phybr** [comment]
Certainly.

These lines instruct the program to look for a skipHTTPS line in the configuration file:

```
    var skipHTTPS = Configuration.GetValue<bool>("LocalTest:skipHTTPS");
    // requires using Microsoft.AspNetCore.Mvc;
    services.Configure<MvcOptions>(options =>
    {
        // Set LocalTest:skipHTTPS to true to skip SSL requrement in 
        // debug mode. This is useful when not using Visual Studio.
        if (Environment.IsDevelopment() && !skipHTTPS)
        {
            options.Filters.Add(new RequireHttpsAttribute());
        }
    });
```

And just a few lines below, you are instructed to add a skipSSL line in the config file.

"Set "LocalTest:skipSSL": true in the appsettings.Developement.json file."

It should be either skipSSL or skipHTTPS, it will not work if you combine these lines. To fix this, one could simply substitute the lines containing "LocalTest:skipSSL" with "LocalTest:skipHTTPS".

**Comment by Rick-Anderson** [comment]
@phybr  Thanks!
