### ISSUE TITLE
I have not worked with .NET since version one and the project I am supporting doies not use Razor Pages so would prefer to understand the basics and build up form there as opposed to having the majic done for me.

### ISSUE THREAD

**Issue by jswante** [aspnet/Docs#6210]
## General

We use issues to drive the discussion for changes to
existing topics and the creation of new topics.
This template offers some suggestions to consider
when creating an issue.

## Issues with Existing Topics

If the issue is a simple typo or similar correction, just submit a PR.
Otherwise, let us know what's wrong or what we should improve. Include a
link to the topic.

## Requests for new Topics

1. Write a **short** paragraph describing what the topic will cover.

2. Write an outline of the proposed topic contents.

3. Where would you put the topic in the Table of Contents.

4. If you know who should review the issue, notify them by including @githubID in the issue description.

**Comment by rachelappel** [comment]
Hi @jswante, which version and product are you using in this project you are supporting? Is this MVC? Web Forms? ASP.NET Core or ASP.NET 4.6?

**Comment by Rick-Anderson** [comment]
@jswante The best approach is to follow [Create a web app with ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-2.1) and when it covers things the framework does for you, look that up in the [fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.1&tabs=aspnetcore2x)
