### ISSUE TITLE
Boostrap Template

### ISSUE THREAD

**Issue by kwakuduahc1** [aspnet/Docs#6211]
There is a remarkable difference in the HTML markup for the nav-menu and any bootstrap template. As such, bootstrap files cannot be swapped to achieve same results. E.g. when you swap the bootstrap.min.css with any from bootswatch.com, the template jams quickly. It would be great the template could be made to comply with most others so that the template can be quickly swapped without tweaking here and there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Service: **unspecified**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/templating/issues/510, since this is a feature request in the project template.

**Comment by Rick-Anderson** [comment]
@kwakuduahc1 thanks for your suggestion. I'll pass this on to the development team.
