### ISSUE TITLE
Debugging Typescript

### ISSUE THREAD

**Issue by vwzhang** [aspnet/Docs#6214]
Not able to set breakpoint for angular project. Vue project is fine. I believe this may be related to srcRoot setting. Please fix the template or advise how to work around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Service: **unspecified**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/templating/issues/509.

**Comment by scottaddie** [comment]
@MACEL94 Please post your question here: https://github.com/aspnet/templating/issues/509. The engineers working on the templates will have to provide a recommendation.

**Comment by scottaddie** [comment]
@MACEL94 Glad to hear you got it working. Thank you for reporting back.
