### ISSUE TITLE
Just Developer.

### ISSUE THREAD

**Issue by Straightly** [aspnet/Docs#6219]
When I used Swagger before, the document generated have all the comments in ///  ****/// for all APIs and models.  When I tried this with appnet Core version, the comments are stripped.  Did I miss doing anything here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34eea37-51a4-6227-f5ed-6501624ad045
* Version Independent ID: 2994cf60-0cb7-afa2-20b8-7e2b1117f964
* Content: [ASP.NET Core Web API help pages with Swagger / Open API](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-help-pages-using-swagger.md)
* Service: **unspecified**
* GitHub Login: @RSuter
* Microsoft Alias: **scaddie**

**Comment by zuckerthoben** [comment]
Hi @Straightly, Have you enabled the XML documentation output in the project properties? 
NSwag will definetely pick that up and will show the comments in the Swagger UI.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
