### ISSUE TITLE
Force DISQUS to use HTTP not HTTPS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#623]
DISQUS saves comments from HTTPS requested docs are not visible to the same doc referenced using HTTP and vice-versa. For example see
https://docs.asp.net/en/latest/publishing/iis.html
http://docs.asp.net/en/latest/publishing/iis.html

see https://github.com/barryclark/jekyll-now/issues/165

**Comment by danroth27** [comment]
The whole site should redirect now to https.

**Comment by Rick-Anderson** [comment]
http://docs.asp.net/en/latest/fundamentals/localization.html#comment-2425944266
https://docs.asp.net/en/latest/fundamentals/localization.html#comment-2425944266

@danroth27   glitch?

**Comment by danroth27** [comment]
No longer an issue as the whole site now redirects to HTTPS.
