### ISSUE TITLE
There is no link to the Nuget package

### ISSUE THREAD

**Issue by mirsaeedi** [aspnet/Docs#6231]
We need to provide readers with the nuget package name that they need to install (Microsoft.AspNetCore.Authentication.Facebook).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mirsaeedi  thanks, I fixed that.
