### ISSUE TITLE
Possible Wrong Link in VS "Learn More"

### ISSUE THREAD

**Issue by joeruder** [aspnet/Docs#6235]
Hello,

In VS if you click on Learn More in "Create new project" under Web Application I believe it should take you to this page (Razor).  Instead it currently links to the same page as the standard MVC application here: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x  Is that the expected bahavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
Hi @joeruder. This will depend on the VS version you have. If RC1, then the link should take you here regardless of whether the project is Razor or MVC https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1

**Comment by rachelappel** [comment]
@joeruder Thanks for catching it! I'll look up who owns that feature for 15.6 and let them know. I don't see any reference to the "read more" in the doc itself, so I'll close this issue.
