### ISSUE TITLE
Create ClearDB UX on portal.azure.com for custom asp.net provider post

### ISSUE THREAD

**Issue by SychevIgor** [aspnet/Docs#6242]
## Issues with Existing Topics
Create ClearDB UX is different, because classic portal no longer available, instead in a documentation should be portal.azure.com UX

https://docs.microsoft.com/en-us/aspnet/identity/overview/extensibility/implementing-a-custom-mysql-aspnet-identity-storage-provider

@raquelsa @suhasj @tfitzmac

**Comment by rachelappel** [comment]
Closing this one, as 6241 is the same https://github.com/aspnet/Docs/issues/6241

**Comment by SychevIgor** [comment]
@rachelappel  not agree. one issue- one article. Look on the links in the end of each issue.
I don't think that fixing 2 post in the same issue- will a good idea.

**Comment by rachelappel** [comment]
@SychevIgor I see now. My mistake, they looked the same. It's early here. :D Reopening.

**Comment by SychevIgor** [comment]
Will be nice to finally make this update.

**Comment by Rick-Anderson** [comment]
Less than 1 K PV/month.
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
