### ISSUE TITLE
Fix for issue with creating new signalR.HubConnection()

### ISSUE THREAD

**Issue by natsch93** [aspnet/Docs#6244]
Great guide to get started with SignalR, thanks. Just a minor issue as the SignalR Connection was throwing an error stating that 'protocol' is required. I fixed this by replacing the new signalR Hub Connection line in chat.js with the following:

const connection = new signalR.HubConnectionBuilder()
    .withUrl("/chathub")
    .build();

Source: https://www.npmjs.com/package/@aspnet/signalr

This also worked with the latest version of @aspnet/signalr (1.0.0-rc1-update1 currently) as I initially thought the issue was with NuGet and Npm version mismatches but it didn't work with the same versions anyway (1.0.0-preview2-final) before I replaced how the hub connection is initialised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778aaeae-2fa8-fb73-b644-8e99ee06398e
* Version Independent ID: 159a95c8-7afd-bb03-fdfc-2323559ef50a
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/signalr/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/get-started.md)
* Service: **unspecified**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@natsch93  Thanks for the feedback. 
@rachelappel  can you get this fixed this week?

**Comment by rachelappel** [comment]
@natsch93 Thanks for the comment, however, you must use the full path in the .NET client when you use withUrl.  The shorter “/chathub” form only works because it’s on a web page that itself has a URL, so there’s something to resolve relative to. Otherwise, it will error,

**Comment by Hellpop** [comment]
Hey folks,
Is there a best practice solution for this issue yet?  
Thanks

**Comment by rachelappel** [comment]
@hellopop Hello there! See the above comment. Use the full path, that's the proper way to do it.

**Comment by SyntaxWarrior** [comment]
Hi.
@rachelappel  If I understand you correctly you want to write out the entire url in the .ts file. 

This is bad practice. How does this work with multiple environments. The URL will be different from Dev, Test, QA, and Production. The code should be URL agnostic. Even hard coding all the different urls and switching between them is bad practice. The code then needs to be recompiled for a url change.
