### ISSUE TITLE
where launchSettings.json ??   i can't find it

### ISSUE THREAD

**Issue by newpost** [aspnet/Docs#6245]
A change to the ASP.NET Core project's launch settings may be required to test the HTML page locally. Open launchSettings.json in the Properties directory of the project. Remove the launchUrl property to force the app to open at index.html—the project's default file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@newpost It's normally created when the project is created with the `dotnet new` command. I don't see a spot where `ExcludeLaunchSettings` is set to `true` (it looks like it defaults to `false` everywhere) ( https://github.com/search?p=3&q=org%3Aaspnet+ExcludeLaunchSettings&type=Code ). Did you create the project with the `dotnet new` command shown?

```console
dotnet new webapi -o TodoApi
```

**Comment by newpost** [comment]
Try again. Problem solved. @guardrex
