### ISSUE TITLE
Couple of possible typo's

### ISSUE THREAD

**Issue by Pangar** [aspnet/Docs#6246]
In this section https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.0#add-filtering-functionality-to-the-index-method says "Serve" and not "Server".
In this section: https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.0#add-a-search-box-to-the-student-index-view 
Shouldn't the path be Pages/Students/Index.cshtml and not Views/Student/Index.cshtml because its Razor Pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.0#add-a-search-box-to-the-student-index-view)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Service: **unspecified**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Pangar** [comment]
Can you do it? I would hate if I made it worst.
Thank you,
Antwon Garcia

Sent from Yahoo Mail on Android 
 
  On Mon, May 7, 2018 at 12:40 PM, Luke Latham<notifications@github.com> wrote:   
Yes, great catches @Pangar! Do you want to change them on a PR? (just click the "Edit" button on the topic to edit it) ... or would you prefer that I take care of these?

**Comment by guardrex** [comment]
Sure np. Thanks again for reporting!
