### ISSUE TITLE
Fix page titles to have the right version

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#625]
Currently the built docs have page titles that look like this:

```html
<title>ASP.NET 5 Documentation — ASP.NET 0.0.1 documentation</title>
```

The version is being pulled from the version in conf.py, which doesn't match the branch versions. We need to figure out how to get this cleaned up.

**Comment by shirhatti** [comment]
https://github.com/aspnet/Docs/blob/master/aspnet/conf.py#L58-L60
