### ISSUE TITLE
Razor Pages with EF Core - Sort, Filter, Paging

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6252]
RP topic ... however ... "view models" described in the topic.

* https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1
* https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md

**Comment by Rick-Anderson** [comment]
@guardrex 	I'm not clear on this issue.

**Comment by guardrex** [comment]
IIRC, this is a RP topic that refers to "view models," but that might be ok. I think I was fixing some typos and flagged this for a look to see if anything in these two topics pertaining to "view" were out-of-place for a RP topic.
