### ISSUE TITLE
namespace no longer reserved?

### ISSUE THREAD

**Issue by janis-veinbergs** [aspnet/Docs#6265]
> Reserved keywords not used by Razor: namespace

From what I read here: https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio#using-layouts-partials-templates-and-tag-helpers-with-razor-pages i see that @namespace is being used. 
Moreover VS 15.6.7 with ASP.NET core stuff when creating .NET Core project "ASP.NET Core Web Application" the file _ViewImports.cshtml also uses @namespace directive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
@janis-veinbergs  Your observations are correct. Thanks for the feedback!

**Comment by Rick-Anderson** [comment]
@NTaylorMullen  see [Reserved keywords not used by Razor](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#reserved-keywords-not-used-by-razor)

**Reserved keywords not used by Razor**
* namespace
* class

Should `namespace` be moved to [Razor keywords](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#razor-keywords)

**Comment by NTaylorMullen** [comment]
> Should namespace be moved to Razor keywords

Yes
