### ISSUE TITLE
Sendgrid section is outdated in email confirmation for MVC 5 app

### ISSUE THREAD

**Issue by Niladri24dutta** [aspnet/Docs#6268]
## Sendgrid section not updated with the V3 API code 

In the below article the "Hook Up Sendgrid" section is not updated yet,it's still following the old V2 API code. Currently Sendgrid uses API_KEY which is also not mentioned in the document. Please see the link below.
[Outdated section](https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-password-reset#hook-up-sendgrid)

I have updated a similar document for .NET Core like below before -
https://docs.microsoft.com/en-us/azure/sendgrid-dotnet-how-to-send-email 

let me know if I can submit a PR for this.

**Comment by rachelappel** [comment]
@Niladri24dutta Thanks for opening the issue. We greatly appreciate your contribution so feel free to open a PR. @cephalin, @TomArcher, or @syntaxC4 can assist in creating the PR in the Azure repo. Since this is the ASP.NET repo, I'll close the issue here and reopen in it the Azure repo for you.

**Comment by rachelappel** [comment]
New issue: https://github.com/MicrosoftDocs/azure-docs/issues/8238

**Comment by Rick-Anderson** [comment]
@Niladri24dutta  a PR would be very welcome.

**Comment by Rick-Anderson** [comment]
I think the instructions are correct in [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=aspnetcore2x)
You can probably get a good start by copying them.

**Comment by Niladri24dutta** [comment]
@Rick-Anderson Ok I will submit a PR as per the guidelines, I have already followed a similar approach to add the example in .NET Core version example of sendgrid in azure.
