### ISSUE TITLE
Rename of cs file required in view components sample

### ISSUE THREAD

**Issue by egmfrs** [aspnet/Docs#6269]
ToDoItem.cs should be renamed TodoItem.cs to match namespace throughout project.

Docs/aspnetcore/mvc/views/view-components/sample/StarterViewComp/Models/ToDoItem.cs

**Comment by Rick-Anderson** [comment]
@egmfrs  I don't understand the problem. The namespace for `public class TodoItem` is  `ViewComponentSample.Models1 and the class name is consistent with the filename.

**Comment by egmfrs** [comment]
@Rick-Anderson Todo vs ToDo ; lowercase D in namespace vs uppercase D in filename. It threw me for a short while when trying to get the sample working. I was typing it out manually (helps me learn better) and I typed in <ToDoItem> which it was not recognising. Thought I would try and save others the same problem.

**Comment by Rick-Anderson** [comment]
@egmfrs  I understand. Namespace and filename don't need to match, although that's a good convention. Next time we work on this tutorial that a great change to make.

Thanks again for your suggestion.
