### ISSUE TITLE
Does it work with Web API in Core 2.0 ?

### ISSUE THREAD

**Issue by alex-piccione** [aspnet/Docs#6270]
ASP.Net Web API with Core 2.0
This code:

```
public void ConfigureServices(IServiceCollection services) { 
    services.AddCors()
```
and
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env,  ....

    app.UseMvc();
    string[] corsOrigins = Configuration["AppSettings:CORS origins"].Split(',');

    // does not work (response does not contain the header "Access-Control-Allow-Origin")
  app.UseCors(builder => {
        if (env.IsProduction())
            builder.WithOrigins(corsOrigins);
        else
            builder.AllowAnyOrigin();
        });
```
With "CORS origins" set to "*" or "www.something,www.somethingelse"
and With different Environments
NEVER send the Access-Control-Allow-Origin header.

Why ?
The client is not able to use the API service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cors.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@rynowak Any ideas?

**Comment by Rick-Anderson** [comment]
@HaoK  please comment

**Comment by HaoK** [comment]
I'm not that familiar with CORS, @kichalla do you own CORS or do you know who does?

**Comment by TrustLRon** [comment]
Hi,
For us, it seems that the order of operations is important in the startup.cs file. 

We had the services.AddCors() and app.UseCors() after the services.AddMvc() and app.UseMvc() methods and our requests were failing with no Access-Control-Allow-Origin headers set.  

Moving the Cors methods above the mvc ones fixed the issue.  

Hopefully that info helps someone.

Got the hint from this post: https://stackoverflow.com/questions/44379560/how-to-enable-cors-in-asp-net-core-webapi

**Comment by silkfire** [comment]
@TrustLRon Thank you so much! This made it work for me in my Web API service. Strange that the order should even matter...

**Comment by HaoK** [comment]
Yeah order matters as its setting up the middleware which affects which gets called first

**Comment by scottaddie** [comment]
@silkfire Read more about middleware ordering here: https://docs.microsoft.com/aspnet/core/fundamentals/middleware/#ordering
