### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by isaaken** [aspnet/Docs#6272]
It would be great if this article contained the release date for ASP.NET Core and which language it is written in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
Hi @isaaken! Excellent question! Thank you!

We don't publish the release dates as part of the documentation at docs.microsoft.com, however there are a few ways to get that information:

-Check the release notes: https://github.com/dotnet/core/blob/master/release-notes/2.1/Preview/2.1.0-rc1.md 
-Check the date/time stamps on the ASP.NET core repo: https://github.com/aspnet/Home 
-Check the release pages: https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1
-Ask in an issue like this one, or Tweet or email folks on the team.

The release notes are the best way, in my opinion. You can use your favorite search engine to look for them and usually there is a link from the other locations to the notes and the announcements at [MSDN blogs](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/). 

Hope this helps! I'll close the issue but feel free to re-open if you have further questions/comments.

**Comment by Rick-Anderson** [comment]
@isaaken  the best place for the schedule is https://github.com/aspnet/Home/wiki/Roadmap
