### ISSUE TITLE
Remove version querystring from API Reference TOC link

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#6277]
The **API Reference** link in the TOC is hard-coded to use "?view=aspnetcore-2.0". We shouldn't assume the user always wants to view v2.0 of the API ref.

**Comment by scottaddie** [comment]
@Rick-Anderson Our TOC link to the ASP.NET Core API ref is the following:

```
# [API Reference](/dotnet/api/?view=aspnetcore-2.0)
```

The .NET docs repo just links to /dotnet/api/. Are you okay with me changing to that in our repo? This is a cleaner approach than the following:

```
::: moniker range="= aspnetcore-1.0"
# [API reference](/dotnet/api/?view=aspnetcore-1.0)
::: moniker-end
::: moniker range="= aspnetcore-1.1"
# [API reference](/dotnet/api/?view=aspnetcore-1.1)
::: moniker-end
::: moniker range="= aspnetcore-2.0"
# [API reference](/dotnet/api/?view=aspnetcore-2.0)
::: moniker-end
::: moniker range="= aspnetcore-2.1"
# [API reference](/dotnet/api/?view=aspnetcore-2.1)
::: moniker-end
```

**Comment by Rick-Anderson** [comment]
@scottaddie 	 can this be fixed?
