### ISSUE TITLE
View components for Razor Pages

### ISSUE THREAD

**Issue by janis-veinbergs** [aspnet/Docs#6278]
Cannot find View components article for Razor Pages (non-MVC). Was thinking where should I put my Components when I have Pages folder and then I find that on 3rd party site: https://www.learnrazorpages.com/razor-pages/view-components:

> By default, the view file is named default.cshtml. You can specify an alternative name for the view file by passing it to the return View(...) statement. The view file's placement within the application's file structure is important, because the framework searches pre-defined locations for it:

> /Pages/Components/<component name>/Default.cshtml
> /Views/Shared/Components/<component name>/Default.cshtml

Also for me, as a newb to this technology, this is kind of messy. Good thing that (Get started with ASP.NET Core MVC and Visual Studio)[https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x] says:
> We recommend you try the Razor Pages tutorial before the MVC version.

Which saved me to understand on which way should I go for a new web app. However, it is kind of messy to search between MVC/Razor Pages docs and find out Razor Pages tutorial/documentation misses bits & pieces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
Hi @janis-veinbergs MVC view and Razor Pages use the same ViewComponents, since Razor is what renders MVC views and Razor Pages so this doc can be used for either:  https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1

I will share your feedback with the rest of the team about the messiness of searching between MVC and Razor. It is very helpful!

I'll close the issue, but if you have more questions or comments, feel free to re-open or to open further issues.

**Comment by janis-veinbergs** [comment]
@Rick-Anderson thank for making it clearer.

What about https://www.learnrazorpages.com/razor-pages/view-components ? Is it true from that framework will search:
- /Pages/Components/<component name>/Default.cshtml
- /Views/Shared/Components/<component name>/Default.cshtml

If so, this piece of information seems important to be added to docs.

**Comment by Rick-Anderson** [comment]
@janis-veinbergs  that's right. Do you want to create another issue for that?

**Comment by janis-veinbergs** [comment]
@Rick-Anderson only if that is true. Its hard for me to judge, because I'm currently learning this stuff and haven't got my experimental view component to work yet. But it's late here and i'll get to it tomorrow.

**Comment by janis-veinbergs** [comment]
I validated that these paths are searched when providing "HelloWorld" as view name:

- /Pages/Components/HelloWorld/HelloWorld.cshtml
- /Views/Shared/Components/HelloWorld/HelloWorld.cshtml

I saw it in exception and I got it working.

This should be added to documentation for Razor Pages.

**Comment by Rick-Anderson** [comment]
I think it should be added to [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1)
