### ISSUE TITLE
2.0.8 .net run time core is missing from download page

### ISSUE THREAD

**Issue by AlejandroFlorin** [aspnet/Docs#6281]
There is no 2.0.8 version available for download so can't get the 2.0.8 hosting bundle for the new .net core version.

https://www.microsoft.com/net/download/all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Service: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@AlejandroFlorin Latest release is 2.0.7 ... https://github.com/dotnet/core/releases

Where did you see 2.0.8?

**Comment by guardrex** [comment]
@AlejandroFlorin I'm going to go ahead and close. We can re-open and discuss further if you have additional questions. If you saw something that indicated that there was a 2.0.8 release, please let us know about that. If its a Microsoft page, there might be a typo somewhere that we need to fix.

**Comment by AlejandroFlorin** [comment]
There is a new .Net Core updated in NuGet for Visual Studio:

Microsoft.AspNetCore.All v2.08

**Comment by AlejandroFlorin** [comment]
Also here:

https://www.nuget.org/packages/Microsoft.AspNetCore.All

**Comment by guardrex** [comment]
Yes, they updated the metapackage, but it isn't the same as a .NET Core release. That package version doesn't need to match the latest .NET Core release (although I definitely understand your interpretation looking at the numbers). For the latest released Hosting Bundle Installer, use the 2.0.7 runtime link. Use the 2.1.0-rc1 runtime link to get to the Hosting Bundle Installer for the 2.1.0 preview/prerelease. You can use the "All" 2.0.8 metapackage with your 2.0 apps, since it is now the current package release.

**Comment by AlejandroFlorin** [comment]
Good to know. Every previous .net core release had a matching package update so I assumed there was one now, though I did find it curious that 2.1.0 rc was published so soon after.

Thanks,

**Comment by AlejandroFlorin** [comment]
I just updated my project to Microsoft.AspNetCore.All v2.0.8 and published to my IIS test server that has hosting bundle 2.0.7. They are not compatible.  IIS returns back HTTP Error 502.5 - Process Failure, which is the error that I always get when there is a mismatch between the hosting bundle and the .net core version.

**Comment by guardrex** [comment]
That's interesting. Let's call in the big guns! lol

@leecow Can you comment on the "All" package revving to 2.0.8? We don't see a 2.0.8 official release, and the metapackage just notched up a version a day ago.

**Comment by leecow** [comment]
This is kind of a weird update and we obviously haven't figured out the best way to communicate the situation. 

There was a change in a single framework package (System.Security.Cryptograph.Xml - not part of netcore.app so no update there) and some ASPNETCore packages. (@danroth27 for details) The ASP changes are included in the SDK 2.1.200. 

There's still some plumbing work going on behind the scenes for the CLI and ASP and I expect the ASP and CLI repo release tags to be published before too long, which should help.

**Comment by leecow** [comment]
@JunTaoLuo to look at the HTTP error reported by @AlejandroFlorin

**Comment by leecow** [comment]
@preetikr for progress on ms.com download update.

**Comment by bencgreen** [comment]
Same 502.5 error here - any news on when the hosting bundle will be updated?  The issue for me is with an update to the AntiForgery package, which has been updated to 2.0.3 in the 2.0.8 metapackage.  As that isn't available yet for my hosting server, I've had to downgrade my projects to 2.0.7.

**Comment by VictorioBerra** [comment]
@bencgreen as per [this comment](https://github.com/aspnet/IISIntegration/issues/476#issuecomment-388125609) the bundle was updated 3 days ago on May 8th. Please install [DotNetCore.2.0.7-WindowsHosting.exe](https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/DotNetCore.2.0.7-WindowsHosting.exe) **which contains ASP.NET Core 2.0.8**. Verify the instillation was successful by navigating to `%PROGRAMFILES%\dotnet\store` and finding the 2.0.3 folder inside the microsoft.aspnetcore.antiforgery folder.

**Comment by guardrex** [comment]
Thanks for the update @VictorioBerra! :rocket:

There's nothing actionable for the docs, so I'm going to close this now.

**Comment by aligenc** [comment]
I've downgraded to v2.0.7 back and it works fine.  I know microsoft publishes do not give us confident anyway but it is sad to see dotnet core same.

**Comment by MattJeanes** [comment]
This has just caused us a world of pain too 😢 

The bundle download page currently links to an older version

`https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.0.7-windows-hosting-bundle-installer` ->`https://download.microsoft.com/download/A/9/F/A9F8872C-48B2-41DB-8AAD-D5908D988592/DotNetCore.2.0.7-WindowsHosting.exe`

When it looks like it should be going to your new link `https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/DotNetCore.2.0.7-WindowsHosting.exe`

After installing that new link, the `2.0.3` package installed and everything worked. Looks like you guys might need to update that download link.

I think this needs to be addressed more globally though, as I'm sure I won't be the last one to be hit by something like this. Re-publishing a newer version of the Windows Hosting package with newer binaries under the same version number doesn't seem right.

I appreciate that the actual net core runtime hasn't changed so you wouldn't want to change it to `2.0.8` but I do think something better needs to be done to prevent this confusion, even if it's just a better error message with more clues.

I also appreciate that this is the `aspnet/Docs` repository and not the core runtime one, so raising another issue linked to this one elsewhere may be a good idea. 

Thanks! 😄

**Comment by shelland** [comment]
I have a related issue after updating of NuGet packages:

Error:
  An assembly specified in the application dependencies manifest (MyApp.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.3'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'

  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.8.xml

The only solution for now is to add the following line to my web project file:

` <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>`

but it produces hundreds of DLL files in my application output directory. Actual download link will be appreciated.

Moreover, I still always need to remove  `-argFile IISExeLauncherArgs.txt` from my web.config file after publishing to remote IIS server.

**Comment by guardrex** [comment]
@shelland 

The `-argFile IISExeLauncherArgs.txt` problem has been fixed ... see https://github.com/aspnet/IISIntegration/issues/791#issuecomment-387505068.

WRT the error, that's also fixed ... see https://github.com/aspnet/IISIntegration/issues/476.

**Comment by VictorioBerra** [comment]
@shelland Did you read every single comment in this thread? This is solved. If you host on IIS, install the latest bundle [here](https://download.microsoft.com/download/E/F/7/EF7302FE-4F84-4529-9E3A-893450F76501/DotNetCore.2.0.7-WindowsHosting.exe).

**Comment by guardrex** [comment]
Thank you all very much for reporting and discussing the issue. There's no actionable docs issue to address for this, so I'm going to lock the convo at this point. If there are additional problems with the 2.0.8 All package pertaining to the hosting bundle/shared framework install, please post them in https://github.com/aspnet/IISIntegration/issues/476, where the engineers will re-open that issue to address any new or lingering problems.

If anyone feels that there is a docs issue that we've missed here, please open a new issue with the specifics of your request or concerns and we'll take look. :eyes:

*Thanks again everyone!* :rocket:
