### ISSUE TITLE
Need help running secure user data sample

### ISSUE THREAD

**Issue by AnthonySavitt** [aspnet/Docs#6288]
Hi, I am trying to get your final completed project file to work but when I try to run it I produce a 'HTTP Error 502.5 - Process Failure' page. I have also tried to follow the tutorial from the start, but this error gets produced as well at a certain point. I think it might have something to do with the SeedData but I am not sure. Any help would be fantastic because I'd love to be able to get something like this approve/reject method for a project I am working on. Thanks so much. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Service: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I just tested the starter and it runs fine. You might try putting a breakpoint in startup.

**Comment by Rick-Anderson** [comment]
Did you configure SeedUserPW?

**Comment by Rick-Anderson** [comment]
The sample needs to be updated for the much better 2.1 versions of HTTPS. To get it running for now comment out
            //        options.Filters.Add(new RequireHttpsAttribute());

**Comment by AnthonySavitt** [comment]
The commenting out of that line did the trick! Thanks so much!!

**Comment by Rick-Anderson** [comment]
You need to set up SSL in the project. Then it works with the SSL redirect. Right click on the project > properties > debug tab > enable SSL

**Comment by Rick-Anderson** [comment]
All that HTTPS/certs works much better with ASP.NET Core 2.1

**Comment by AnthonySavitt** [comment]
I enabled the SSL, thank you for that tip. I had seen something about enabling SSL but couldn't figure out how to access that at the time for some reason. Thanks again for all your help, it means a lot!

**Comment by Rick-Anderson** [comment]
I added a readme.md with that info.
Hopefully I can update it for the much better 2.1 bits.

**Comment by mtiganik** [comment]
I'm getting this same error that AnthonySavitt described, ArgumentNullException: Value cannot be null when code IR = await userManager.AddToRoleAsync(user, role); runs. I tried configure SeedUserPW, update database and to use SSL. Also I tried to
*comment out options.Filters.Add(new RequireHttpsAttribute());
*to use app.UseMvc(); instead of app.UseMvcWithDefaultRoute();  
*put some defaultConnection string to appsettings.json (don't know if I should of done that).
But this same error runs for both starter2 and for final2 program. I remember like 2 weeks ago those projects were running, but now that I installed RC 2.1, they don't want to run anymore

**Comment by tomaustin700** [comment]
I am having the same issue, has anyone got any ideas how to get this running? Thanks

**Comment by iamcraigw** [comment]
Had the exact same issue and I just figured it out.  For me (as usual) it was something dumb and I had to add an IdentityResult to the userManager.CreateAsync(user, testUserPw) line to finally see it.  Here's the whole method:

        private static async Task<string> EnsureUser(IServiceProvider serviceProvider,
                                                    string testUserPw, string UserName)
        {
            var userManager = serviceProvider.GetService<UserManager<ApplicationUser>>();
            IdentityResult IR = null;
            var user = await userManager.FindByNameAsync(UserName);
            if (user == null)
            {
                user = new ApplicationUser { UserName = UserName };
                IR = await userManager.CreateAsync(user, testUserPw);
            }

            return user.Id;
        }

My issue?  The secret password I was setting for SeedUserPW didn't contain a capital letter.  Ugh.  Apparently that password must abide by the other password rules: capital letter, number, special character.

**Comment by Rick-Anderson** [comment]
@iamcraigw  I thought I threw an exception when it failed to create a new user - for whatever reason. PW strength too low being the most common.

**Comment by Rick-Anderson** [comment]
`ArgumentNullException: Value cannot be null.`

That's a pretty big hint it didn't create the user. I'll add a code comment to that effect next update.

**Comment by tomaustin700** [comment]
@iamcraigw @Rick-Anderson Thanks, it was due to the password being too weak.
