### ISSUE TITLE
document how can inject scripts and css

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#629]
see request at http://docs.asp.net/en/latest/client-side/bower.html#comment-2330808685

@Erikre  can you fix this with all your bower work? I have some steps in  "
Migrating From ASP.NET MVC 5 to MVC 6"

**Comment by danroth27** [comment]
@Rick-Anderson Do you have more details on what to document here? Inject scripts and css where?

**Comment by Rick-Anderson** [comment]
per customer - http://docs.asp.net/en/latest/client-side/bower.html#comment-2330808685
Would be nice to add few words how bower can inject scripts and css 
http://tattoocoder.azurewebsites.net/using-gulp-for-asp-net-5-visual-studio-2015/

See the notes section.

I would also encourage the use of the wiredep package with gulp. This package injects the bower packages into your .html files by decorating them with a simple comment. Here is an example of that task.

**Comment by danroth27** [comment]
This doesn't sound ASP.NET Core specific.
