### ISSUE TITLE
Missing usings/cleanup?

### ISSUE THREAD

**Issue by SimonCropp** [aspnet/Docs#6292]
given `TestServer` and `HttpClient` are disposable, shouldnt they be cleaned up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda5d096-4337-3256-afcd-fe45436a2067
* Version Independent ID: a9e691a2-a8bf-b477-88aa-73676896b75e
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/testing/integration-testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/testing/integration-testing.md)
* Service: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by SimonCropp** [comment]
Bump

**Comment by guardrex** [comment]
@javiercn Do we need to address this?

**Comment by javiercn** [comment]
They get cleaned up when the WAF gets disposed.

**Comment by javiercn** [comment]
The WAF gets disposed when the fixture gets disposed after the tests run.

**Comment by SimonCropp** [comment]
@javiercn can u link to the line of code where that is happening? I cant seem tl see it

**Comment by javiercn** [comment]
https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs#L390

xUnit disposes the fixtures automatically after all the tests on the class have run.

**Comment by SimonCropp** [comment]
yep so in the dispose of the fixture we should be disposing of all the fields that are IDisposable. is that done?
