### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#63]
ASP.NET 5->Fundamentals->Logging

- Implementing logging in your app
  - Resolve `ILoggerFactor` or `ILogger<T>` from DI
  - Call `CreateLogger`, pass in a name for the log source
    - Names are by convention hierarchical with dots as separators
    - Name is specified by convention when resolving `ILogger<T>`
  - Log stuff
    - Format string, verbosity level, optional event ID (unique numeric ID within the named source)
    - Format strings are (loosely?) based on the [Serilog message template syntax](https://github.com/serilog/serilog/wiki/Writing-Log-Events#message-template-syntax)
    - Message properties may be preserved as name-value pairs by the underlying logging framework
    - [verbosity levels](https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging.Abstractions/LogLevel.cs)
  - Optionally (sparingly!) create a scopes for logical operations 
    - Something with a beginning and end. Ex A request, an MVC action, etc
    - Logging state is attached to the scope (ex transaction ID)
  - Guidance
    - User logging code should be related to business concerns of the application
    - Dial up verbosity to get framework related concerns
      - Ex MVC/TagHelpers will log certain error cases

- Configuring logging
  - During startup resolve `ILoggerFactory` from DI
    - Add `ILoggerProvider` implementations
    - Set minimum verbosity level, default is Verbose
    - Configure logging framework specific settings
  - Built-in loggers: Console, TraceSource

**Comment by ardalis** [comment]
Can I get some additional TOC detail for this one? I figure I should cover the built-in logging interfaces and implementations, as well as how to wire up a custom one (e.g. log4net). Anything else?

**Comment by danroth27** [comment]
@lodejard Please review the updated outline above and provide any additional guidance that you think should be added.

**Comment by danroth27** [comment]
@lodejard We have guidance published at https://github.com/aspnet/Logging/wiki/Guidelines. Is this guidance still accurate?
