### ISSUE TITLE
Document installation via OS X PKG

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#630]
Creating an issue to track writing documentation for installing via the OS X PKG installer. It's got a few small quirks that should be documented. Just wanted to open something to track my notes as I walk through the scenario for RC1 sign-off

/cc @danroth27 

Some things that need to be covered in the doc:

* [ ] The installer does not set up the `default` alias (because it installs globally and aliases are user-local), so the steps should describe using `dnvm list` and `dnvm alias` to set the `default` alias.

**Comment by danroth27** [comment]
Approved.

Daniel Roth

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/pull/652
