### ISSUE TITLE
Business Layer

### ISSUE THREAD

**Issue by RogExp** [aspnet/Docs#6300]
I understand that a tutorial is built this way. However I would like you to consider putting another folder "Business" into this structure,  ie. even the scaffolding should then make such a folder. You would then have Pages, Business and Models.
No page should have "using RazorPagesMovie.Models" but only "using RazorPagesMovie.Business" and hence the BusinessLayer would have  Movie.Add, Movie.Remove and other Business logic.
As someone wants to change the UI, everyone is happy as the programmer has understood to separate the business logic from the page and it's also a security issue. What's your opinion about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Service: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RogExp  Thanks for the suggestion.
We intentionally kept the tutorial as simple as possible. How to separate the business logic is hotly debated.
