### ISSUE TITLE
Wrong line highlighted in cross-origin communications code block

### ISSUE THREAD

**Issue by ManuelRauber** [aspnet/Docs#6303]
The code-block for cross-origin communications highlights two parts. The first is the part within the `ConfigureServices` methods, which is correct. The second is the part within the `Configure` method. Instead of highlighting `app.UseCors("CorsPolicy");` another line is highlighted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Service: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
Thanks @ManuelRauber, great catch!
