### ISSUE TITLE
View or download sample from GitHub links to .net core 1.1 project

### ISSUE THREAD

**Issue by reyou** [aspnet/Docs#6305]
When I try to run this project with VS 2017, and dotnet core 2.0 it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Service: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's an older 1.1-era sample (due for an upgrade and tracked by https://github.com/aspnet/Docs/issues/5495). To upgrade the project yourself, the migration topic is here :point_right: https://docs.microsoft.com/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1

**Comment by guardrex** [comment]
Since this is covered by #5495, I'll close it as a duplicate.
