### ISSUE TITLE
RemoveType the function not working ,why?

### ISSUE THREAD

**Issue by yxn03** [aspnet/Docs#6308]
factories.RemoveType<FormValueProviderFactory>();
        factories.RemoveType<JQueryFormValueProviderFactory>();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Service: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I can't say just looking at it. @scottaddie ... thoughts?

I'll cross-reference the issue tracking work for this topic in case this becomes actionable for the updates: https://github.com/aspnet/Docs/issues/5331

**Comment by scottaddie** [comment]
@yxn03 The [RemoveType](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.modelbinding.valueproviderfactoryextensions?view=aspnetcore-2.0) methods were introduced in ASP.NET Core 2.0. For versions prior to 2.0, you'll need to take the following approach:

```csharp
        public void OnResourceExecuting(ResourceExecutingContext context)
        {
 			// ==== ASP.NET Core 2.0+ ====
            //var factories = context.ValueProviderFactories;
            //factories.RemoveType<FormValueProviderFactory>();
            //factories.RemoveType<JQueryFormValueProviderFactory>();

			// ==== ASP.NET Core 1.1 ====
            var formValueProviderFactory = context.ValueProviderFactories
                .OfType<FormValueProviderFactory>()
                .FirstOrDefault();

            if (formValueProviderFactory != null)
            {
                context.ValueProviderFactories.Remove(formValueProviderFactory);
            }

            var jqueryFormValueProviderFactory = context.ValueProviderFactories
                .OfType<JQueryFormValueProviderFactory>()
                .FirstOrDefault();

            if (jqueryFormValueProviderFactory != null)
            {
                context.ValueProviderFactories.Remove(jqueryFormValueProviderFactory);
            }
        }
```

This doc is due for a rewrite and update. This change will be taken into account at that time. See #5331 to track its status.
