### ISSUE TITLE
CreatedAtRoute Issue

### ISSUE THREAD

**Issue by scottrudy** [aspnet/Docs#6310]
While working through this documentation I ran into an issue when returning a CreatedAtRouteResult where the code threw a System.InvalidOperationException "No route matches the supplied values." The reason was due to a missing Name parameter defined in the HttpGet attribute on the Get action. For example: [HttpGet("{id}", Name="GetTodo")]. I was able to see the Location show up in the HTTP headers after that change. I'm not sure if that is required, or if there is a default naming convention that would have also worked, but it would be nice to have a complete source example for this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Service: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
@scottrudy The topic's code blocks link to this sample; but yes, it isn't formally linked into the topic. See if this is helpful in that regard: https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/web-api-help-pages-using-swagger/samples/TodoApi.Swashbuckle

I'll leave this open so that @scottaddie can comment further.

**Comment by scottrudy** [comment]
Ah, I didn't read the topic first. That's great. Maybe consider a note in the doc to use that defined Name for the route, but otherwise I'm good.

**Comment by Joac89** [comment]
Hello, how could I use external definitions?
