### ISSUE TITLE
Note RE IP for KnownNetworks for Nginx topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6320]
https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx
aspnetcore/host-and-deploy/linux-nginx.md

@buvinghausen reports in https://github.com/aspnet/Docs/issues/2384#issuecomment-387875157 ...

> We are running on AWS in Docker on Linux with Nginx as the proxy back to kestrel.

> When we upgraded from .NET Core Preview 1 to Preview 2 the forwarded headers middleware stopped working because the `KnownNetworks` was no longer trusting the `IPNetwork` from our NGinx proxy. It turns out previously that address was regular IPV4 but after Preview 2 (and still true in RC1) the address from Nginx was now an IPv4MappedToIPv6 address so we just had to put the `::ffff:` prefix on the IP during the call to `IPAddress.Parse` and the rest fell in place.

> I'm guessing since this is still true after the RC1 bits have dropped it will make it into .NET Core 2.1 RTM so we may want to flag this in the Linux production conversion guide or something.

Thanks @buvinghausen for reporting. :rocket:

**Comment by buvinghausen** [comment]
@guardrex when answering Chris Ross question on the other thread this occurred when we moved from running the microsoft/aspnetcore:2.1.0-preview1 Docker image to the microsoft/dotnet:2.1-aspnetcore-runtime so it may actually be more Docker configuration changes than anything specific to .NET 2.1 itself.

**Comment by guardrex** [comment]
I see. Ok. Let's close unless/until there's a similar report or you find out that we're missing some coverage.
