### ISSUE TITLE
Microsoft.Extensions.Logging.Testing shouldn't be on docs web site

### ISSUE THREAD

**Issue by pakrym** [aspnet/Docs#6322]
It's internal use only `noship` package.
I couldn't find other `noship` packages that slipped into docs, what kind of filtering do we have?

**Comment by guardrex** [comment]
Where did u see that? ... I did a search, and I don't see a reference to it.

**Comment by pakrym** [comment]
Sorry, should've posted the link: https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.extensions.logging.testing

**Comment by guardrex** [comment]
It might be legacy API browsing at play tho ... trying this fails ... https://docs.microsoft.com/en-us/dotnet/api/?term=Microsoft.Extensions.Logging.Testing and this ... https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.testing ... is a 404 :boom:.

@mairaw Do u know if the `/aspnet/core/api` browser is depreciating?

**Comment by mairaw** [comment]
I think this should be redirected @guardrex. I just filed a request for the EF docs last night. It seems that only a few namespaces redirect while others stay in `/aspnet/core/api`. I don't have history there to know what to do with these APIs so I'd check with @Rick-Anderson and @scottaddie the right thing to do here.

**Comment by guardrex** [comment]
They're on the case. Just wondering if u knew. Thanks.

**Comment by dend** [comment]
Seems like this is a legacy API that was not generated via our pipeline. @Rick-Anderson @scottaddie have you already opened a work item to put the redirect in place?

**Comment by Rick-Anderson** [comment]
>  @Rick-Anderson @scottaddie have you already opened a work item to put the redirect in place?

No, can you do that or tell us how?

**Comment by Rick-Anderson** [comment]
@dend  opened 74385743

**Comment by Rick-Anderson** [comment]
Fixed in https://github.com/aspnet/ApiDocs/pull/74
