### ISSUE TITLE
signalr/* Insert note about SignalR service on Azure

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#6326]
@anurse 
Should we add in a note stating that the SignalR for Azure docs are over here https://azure.microsoft.com/en-gb/services/signalr-service?

Do you think there will be any confusion in which adding in a note like this will be helpful to readers?

**Comment by anurse** [comment]
We should include a note in the Deploying to Azure doc. Primarily because Azure Web App isn't great for apps that need a lot of concurrent connections and the service is a solution to that
