### ISSUE TITLE
How to use multiple external authentication?

### ISSUE THREAD

**Issue by llgjermeni** [aspnet/Docs#6330]
Hi, very good article, congrats. I have a question, how to implement multiple external authentications in same time  ( Facebook, Twitter, Google and Microsoft ).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@gjermeni Follow the instructions in each sub-topic: https://docs.microsoft.com/aspnet/core/security/authentication/social/?view=aspnetcore-2.1#setup-login-providers-required-by-your-application

Basically, you'll be adding each external auth service as an extension method on `services.AddAuthentication()`. You'll see it when you access each of the sub-topics. They're each setup and configured with a different extension method ... but in exactly the same way.

I'm going to close, but if you have additional questions, we can re-open to discuss further.

**Comment by guardrex** [comment]
Actually ... no so 🏃 *FAST!* 🏃 ... @scottaddie let's discuss for a sec. AFAICT, we don't show multiple providers *anywhere*. Therefore, the wiring isn't immediately apparent. I wonder if a short section in this topic could show a brief example and mention how these extension methods stack on there ...

```csharp
services.AddAuthentication()
    .AddFacebook(facebookOptions =>
    {
        ...
    })
    .AddTwitter(twitterOptions =>
    {
        ...
    });
```
... it would (should be) just enough to alleviate confusion on the wiring. Alternatively (or in addition), this topic could get a sample that wires them ALL up.

**Comment by scottaddie** [comment]
@guardrex Yes, we should document this somewhere.
@HaoK Is the sample provided above accurate for supporting multiple social auth providers?

**Comment by HaoK** [comment]
Yeah that's correct you just add them in a chain

**Comment by guardrex** [comment]
ty @HaoK ... I'll take this one.

Thanks @gjermeni for the report. I'll get to it within a couple of weeks.

**Comment by gjermeni** [comment]
Thanks @guardrex I was working before with external authentications and  faced with this problem.

**Comment by gjermeni** [comment]
To bee more specific my problem is how to enter multiple user-secret in secret manager.

**Comment by guardrex** [comment]
Each one gets a different configuration key. Did you see the secrets topic? ... https://docs.microsoft.com/aspnet/core/security/app-secrets

**Comment by guardrex** [comment]
I would add tho that if you saw that ... or are looking at it now ... and run into problems with the coverage there on secrets/Secret Manager, you can open a separate issue on that topic. Let's use this issue just to cover the multiple auth service providers problem.
