### ISSUE TITLE
 No service for type 'Microsoft.AspNetCore.Http.HttpContext' sessions issue

### ISSUE THREAD

**Issue by upixsoul** [aspnet/Docs#6333]
im using `https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1&tabs=aspnetcore2x` as guide, but seems to be not enough.

in Startup.cs
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddDistributedMemoryCache();
            services.AddMvc().AddSessionStateTempDataProvider();
            services.AddSession(options =>
            {
                // Set a short timeout for easy testing.
                options.IdleTimeout = TimeSpan.FromMinutes(1);
                options.Cookie.HttpOnly = true;
            });//<<==
        }
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
        app.UseStaticFiles();

        app.UseSession();//<<==

        app.UseMvc(routes =>
        {
            routes.MapRoute(
                name: "default",
                template: "{controller=Home}/{action=Index}/{id?}");

            routes.MapSpaFallbackRoute(
                name: "spa-fallback",
                defaults: new { controller = "Home", action = "Index" });
        });
    }

```

in home controller:
```
using Microsoft.AspNetCore.Http;

HttpContext.Session.SetString("TestName", user.UserName);
HttpContext.Session.SetString("TestVal", user.testVal.ToString());

```
to this point it seems to be working, im able to navigate through different pages and i can use/check sessions in controller side.

But the problem is when im trying to use sessions in any view

View side:

```
@using Microsoft.AspNetCore.Http
@inject HttpContext HttpContext


@if (@HttpContext.Session.GetString("testVal").Equals("True"))
{
<td><input type="checkbox"></td>
}
else
{
<td><input type="checkbox" readonly></td>
}  
```
when i try to get or set sessions cshtml/view side i get the error

can you please help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76e22150-f1f1-5e4f-0e97-39b1ac089297
* Version Independent ID: 687172c3-b7d8-525d-39dc-658b4a0f526f
* Content: [Session and application state in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/app-state.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/app-state.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@upixsoul In your view, use the following code to access data from session state:

```cshtml
@using Microsoft.AspNetCore.Http
Session Value = @Context.Session.GetString("TestName")
```
