### ISSUE TITLE
no description of project structure differences compared with Angular documentation

### ISSUE THREAD

**Issue by renathy** [aspnet/Docs#6339]
"There are slight differences between the Angular app created by this template and the one created by Angular CLI itself"

There could be at least some explanation on why and what exactly is different. Most of angular tutorials relay on a little bit different structure, so for beginners it would be helpful to understand thos "slight differences".

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
