### ISSUE TITLE
Setting environment variable

### ISSUE THREAD

**Issue by KevinBurton** [aspnet/Docs#6343]
I have three profiles the only difference between the three is that I would like to set ASPNETCORE_ENVIRONMENT in the web.config. Like  `@Rick-Anderson edit to show code`
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="dotnet" arguments=".\PocketNurse.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout">
            <environmentVariables>
                <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Omnicell" />
            </environmentVariables>
        </aspNetCore>
  </system.webServer>
</configuration>
```
Everytime I publish I have to edit the web.config file and add the <environmentVariables> section. I would like this to set ASPNETCORE_ENVIRONMENT to different values based on the profile that I am publishing with. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@KevinBurton  can you ask that on SO?

**Comment by KevinBurton** [comment]
I just did. Thank you.

**Comment by KevinBurton** [comment]
I added this line to the project file and my project will no longer load. Visual Studio indicates that the project is "unavailable"

**Comment by guardrex** [comment]
You put it into a `PropertyGroup`? ... Sorry if I didn't make that clear. Add it at the top where your target framework, etc. are located ...

```xml
<PropertyGroup>
  <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  <TargetFrameworks>netcoreapp2.1</TargetFrameworks>
</PropertyGroup>
```

**Comment by KevinBurton** [comment]
Thank you. Now web.config is not in the published output.

**Comment by phil123456** [comment]
does'nt work for me
I also tried  <ANCMPreConfiguredForIIS>true</ANCMPreConfiguredForIIS> and I get a 500 error
