### ISSUE TITLE
MessageSize Breaks Hub

### ISSUE THREAD

**Issue by bleekbless** [aspnet/Docs#6346]
When sending a message that exceeds 13kb the application stops and all current connections goes down. How to increse the message size limit ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/introduction.md)
* Service: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by anurse** [comment]
This isn't a content issue, it's a product issue. We have no Message Size limit so there is nothing to increase. Having said that, we have have issues with handling large messages. This should be filed in https://github.com/aspnet/SignalR

**Comment by rachelappel** [comment]
Closing since it's not a docs issue.
