### ISSUE TITLE
requesting sample:Custom Validation including client side

### ISSUE THREAD

**Issue by MaqSaid** [aspnet/Docs#6347]
Thanks for  https://github.com/aspnet/Docs/tree/master/aspnetcore/mvc/models/validation/sample. Can you please provide Sample project for Custom Validation. At the moment, there seems not many samples available for Asp.net Core 2.0 explaining Custom Validations talking in detail for both server and client using IsValid, AddValidation and jQuery.validate and jquery-validation-unobtrusive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Service: **asp.net-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I agree, a custom validation project would be nice.

**Comment by wgutierrezr** [comment]
I tried Custom Validation regarding this post and it the Controller/Action is never called (where I have my validation code). I have my project ASP.Net Core 2.1.5 MVC

**Comment by akki-s** [comment]
> I tried Custom Validation regarding this post and it the Controller/Action is never called (where I have my validation code). I have my project ASP.Net Core 2.1.5 MVC

Facing the same issue. Custom Validation Attribute is never triggered.
