### ISSUE TITLE
Update "Razor view compilation and precompilation in ASP.NET Core" to include content about Razor Sdk

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Docs#6351]
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.1&tabs=aspnetcore2x does not contain details about the Razor Sdk and following these instructions would actually turn it off. We should update it and likely for apps targeting 2.1, likely pointing to the Razor Sdk doc as also the one about Razor Class Library.

**Comment by Rick-Anderson** [comment]
@pranavkm  can you draft the changes and I'll get it updated?

**Comment by scottaddie** [comment]
Fixed by https://github.com/aspnet/Docs/pull/6379
