### ISSUE TITLE
excuse me ， I am new learner ,i don`t know page/Movie/create.cshtml is createed by me or cli 

### ISSUE THREAD

**Issue by zhangtingwz** [aspnet/Docs#6352]
[Enter feedback here]

excuse me ， I am new learner ,i don`t know page/Movie/create.cshtml is createed by me or cli 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The scaffolder creates that page.

**Comment by Travisaurus-Rex** [comment]
It certainly didn't make it for me.
