### ISSUE TITLE
[ViewData] does not exist

### ISSUE THREAD

**Issue by benoityip** [aspnet/Docs#6353]
Documentation is wrong on [ViewData], it does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ab455d-e8ea-39ff-3577-8b6ddc23f7b7
* Version Independent ID: 2ab43968-907a-78bf-6844-eaaf92d40da5
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/razor-pages/index.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`ViewData` requires version 2.1. Check your version selector.
cc @scottaddie
