### ISSUE TITLE
@page "{id:int?}" not required

### ISSUE THREAD

**Issue by benoityip** [aspnet/Docs#6354]
Visual studio 2017 auto generates the Edit view, it does not have @page "{id:int?}", it just uses @page. Even with @page, it will return 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ab455d-e8ea-39ff-3577-8b6ddc23f7b7
* Version Independent ID: 2ab43968-907a-78bf-6844-eaaf92d40da5
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/razor-pages/index.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your comment, however we are unable to reproduce this.

**Comment by Rick-Anderson** [comment]
Can you provide instructions on how the code was created? If possible, use CLI commands.

**Comment by Rick-Anderson** [comment]
Per the doc. Can you try this:

This document provides an introduction to Razor Pages. It's not a step by step tutorial. If you find some of the sections too advanced, see [Get started with Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1).

**Comment by benoityip** [comment]
Auto generated by visual studio 2017 by selecting the customer model, I don't write the code except the data layer

![image](https://user-images.githubusercontent.com/28388528/39908239-80d22d6a-5530-11e8-916d-0aba2c161e5c.png)

**Comment by benoityip** [comment]
Thanks for your reply, I am going through everything in the documentation

**Comment by Rick-Anderson** [comment]
Can you try reproducing with [Get started with Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1).

**Comment by benoityip** [comment]
Yes, here are my screenshot, even with {id:int?}, it will not throw 404 if you don't specify id in the query string, and it will hit the OnGet Method of the code

![image](https://user-images.githubusercontent.com/28388528/39908386-3fcfa558-5531-11e8-8daf-0d0ce1c7c429.png)

![image](https://user-images.githubusercontent.com/28388528/39908667-7a0e8bf2-5532-11e8-8992-80578e8d7779.png)

![image](https://user-images.githubusercontent.com/28388528/39908690-948e421a-5532-11e8-8fac-18800dd3f5ec.png)

![image](https://user-images.githubusercontent.com/28388528/39908705-a5db3c9e-5532-11e8-975c-2580e70205fa.png)

**Comment by benoityip** [comment]
Sorry, my silly mistakes, please close this ticket. Sorry for wasting your time
