### ISSUE TITLE
npm warning

### ISSUE THREAD

**Issue by ImageQC** [aspnet/Docs#6356]
Ref:
https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio

I understand the author is updating the article so might like to address the following WARN when running npm

`PM> npm install @aspnet/signalr
SignalRChat@1.0.0 C:\Users\Will\Source\Repos\Spikes\SignalRChat\SignalRChat
`-- @aspnet/signalr@1.0.0-rc1-update1 

npm : npm WARN SignalRChat@1.0.0 No description
At line:1 char:1
+ npm install @aspnet/signalr
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN Signal... No description:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm
 WARN SignalRChat@1.0.0 No repository field.`

**Comment by scottaddie** [comment]
@ImageQC @rachelappel After running `npm init -y`, setting the `private` property to `true` in the *package.json* file will eliminate the warnings. Most projects aren't intended for publication in the npm registry, so this property is probably a good thing to add.

**Comment by rachelappel** [comment]
@scottaddie @ImageQC  npm is outside the scope of the SignalR docset so the instructions belong in npm docs, not these docs. 
The property can go into the sample though.
