### ISSUE TITLE
Microsoft.EntityFrameworkCore progress

### ISSUE THREAD

**Issue by zhangtingwz** [aspnet/Docs#6357]
excuse me ，still is me , when i use dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries run in cmd ,a progress is show 
could not load file or assembly 'Microsoft.EntityFrameworkCord,Version=2.0.3.0,Culture=neutral,PublicKeyToken=abd9793829ddae60'.the located assembly'sman ifest definition does not match the assembly reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1#test-the-app)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by krittersg** [comment]
Hello, I ran into this issue as well. It seems like Install-Package Microsoft.VisualStudio.Web.CodeGeneration.Design has moved onto v2.0.4 since the article. It's causing a mismatch. While I'm guessing the better solution would be to move up the version number of the dependency I wasn't able to find what library I would need to do so  - and instead installed the older v2.0.3 of Microsoft.VisualStudio.Web.CodeGeneration.Design. It seems to have worked so far. That being said I'm not actually 100% complete with the tutorial.

**Comment by zhangtingwz** [comment]
hello @krittersg Are you deal with this question ？ I am a learner that can't to deal

**Comment by krittersg** [comment]
Hello @zhangtingwz - I ran into this issue also (I am new to .Net as well). I got through it by (Visual Studio 2017) - Tools -> NuGet Package Manager -> Manage NuGet Packages for solution -> Microsoft.VisualStudio.Web.CodeGeneration.Design --> Check the box next to the project name on the right. and Installed version 2.0.3. I then removed the Migration created by this step (Add-Migration Initial)  - I cheated slightly and just deleted the files in the Migrations folder in the project directory. Then redid the Add-Migration and it seemed to work. I got through to the next step. Hopefully I didn't miss any of the steps I took to get through it.

**Comment by krittersg** [comment]
![image](https://user-images.githubusercontent.com/32199125/39929604-5eb2e288-5530-11e8-81ca-2a8d1d08a019.png)

**Comment by zhangtingwz** [comment]
hello @krittersg ,very thanks your answer .but i can't find any file that name is Migrations (┬＿┬).
![image](https://user-images.githubusercontent.com/26179617/39952873-a42fbe7e-55d2-11e8-9f0b-281ca59586a9.png)

**Comment by zhangtingwz** [comment]
hello @krittersg very thanks again , by you way ,i have achieve it ,next thank you very much

**Comment by oudi** [comment]
It seems like Microsoft.EntityFrameworkCore would lower then current version. when i install version 2.0.4, it shows "Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.3.0", then i update the version to 2.0.3, and remove the Migrations folder, redid Add-Migration Initial, it shows "Could not load file or assembly 'Microsoft.EntityFrameworkCore, Version=2.0.2.0"....

**Comment by jaimelr** [comment]
Make sure you have Microsoft.AspNetCore.All v2.0.8 and Microsoft.EntityFrameworkCore v2.0.3, I had the same issue but by installing the latter package the problem disappeared.

**Comment by thassio-vinicius** [comment]
i ran into the same problem as well. Leveling all of the apps and frameworks versions using the NuGet worked for me.
