### ISSUE TITLE
Failed to start the connection: Error: Unable to initialize any of the available transports

### ISSUE THREAD

**Issue by ImageQC** [aspnet/Docs#6358]
I've spent the best part of the day trying (and failing) to get this sample working. Having installed the correct .NETCore SDK (see other post), updated VS2017 (hours) and then spent a few hours debugging / searching for solutions I'm still getting no response after pressing 'send' from either clients (https://localhost:44338/) using Edge 41.16299.402.0.

Running Dev Tools (F12) on Edge gives the following errors on Console when Index.cshtml opens 

- Error:  Failed to start the connection: Error: Unable to initialize any of the available transports.
- Error: Unable to initialize any of the available transports.

This is deeply frustrating. I'm deleting the project and moving on to another SignalR sample. I just hope this one works!

**Comment by ImageQC** [comment]
This one seems to work fine - ChatRoomLocal

https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/ChatRoomLocal

**Comment by rachelappel** [comment]
addressed https://github.com/aspnet/Docs/issues/6340
