### ISSUE TITLE
No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by StephenSZDai** [aspnet/Docs#6360]
One more issue is found.
I can run "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design" in cmd prompt, but I received the following error when running "dotnet ef migrations add Initial"

No executable found matching command "dotnet-ef"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by krittersg** [comment]
There seem to be some packages and additions to get the dotnet-ef working. I found the solution on 
https://stackoverflow.com/questions/37276882/no-executable-found-matching-command-dotnet-ef
Specifically for me the section titled - Specific to VS2017 15.3 or greater and ASP.NET CORE 2.0 or later... by Joe Healy

**Comment by scottaddie** [comment]
@StephenSZDai The CLI tool just hasn't been registered with the .NET Core CLI. Here are the instructions to solve that problem: https://docs.microsoft.com/ef/core/miscellaneous/cli/dotnet.
