### ISSUE TITLE
Recommended 

### ISSUE THREAD

**Issue by alex-piccione** [aspnet/Docs#6361]
As I understood the recommended way is to create a single .NET Core project that can self-host and be itself a Windows Service.
Why not create pure .NET Standard project that can run on every platform and then create a Windows Service project that just use the shared library?
Like described in this article:  https://stackify.com/creating-net-core-windows-services
I think this second way is much cleaner.
What are the Pros and Cons  of the two solutions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Service: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@alex-piccione  great question. Do you want to ask that on StackOverflow?
