### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by guilanhuang** [aspnet/Docs#6365]
Students/Index.cshtml page refers to the parameter HasPreviousPage, HasNextPage , PageIndex, which causes compiling error. PaginatedList.cs is in the project root, cannot be referred by Students/Index.cshtml. Student/Index.cshtml can only include one model file:  @model ContosoUniversity.Pages.Students.IndexModel.  How to solve this problem?  Can anyone help? Many Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Have you tried the download? It works as expected.

**Comment by Rick-Anderson** [comment]
@guilanhuang  asks to close this in #6366

**Comment by stephenmorton** [comment]
I have the same problem, dowloading the Students/index.cshtml and Students/index.cshtml.cs doesn't fix. Trying to respore now from previous steps.

**Comment by stephenmorton** [comment]
Must have downloaded the wrong github entry, tried again, and it works.
