### ISSUE TITLE
Sorry, I missed one line

### ISSUE THREAD

**Issue by guilanhuang** [aspnet/Docs#6366]
Sorry, check your Source code on Github, I realize I missed one line in Student/Index.cshtml.cs:
public PaginatedList<Student> Student { get; set; }. Please close my issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@guilanhuang  created this to close #6365
