### ISSUE TITLE
Doc AddDefaultIdentity 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6367]
Per Hao
AddDefaultIdentity is just syntatic sugar for the old code that used to be in startup + AddDefaultUI, whatever you are trying to do, 

Explain this in the docs, probably in [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)

Find out why [API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.identityservicecollectionuiextensions.adddefaultidentity?view=aspnetcore-2.1) doesn't contain [/// comments from source](https://github.com/aspnet/Identity/blob/master/src/UI/IdentityServiceCollectionUIExtensions.cs#L21-L33)

See #7633 - add link to this update

**Comment by pholly** [comment]
Would be good to document `AddIdentityCore` as well

**Comment by Rick-Anderson** [comment]
@pholly  thanks. Moved to #8434
