### ISSUE TITLE
Your First ASP.NET 5 Application Using Visual Studio javascript snippet

### ISSUE THREAD

**Issue by gkrilov** [aspnet/Docs#638]
This is very low priority but just putting it here to keep track.

The script section under the Adding Client-Side Behavior section is using the jQuery .bind() function. This function is the old way of binding to an event and post jQuery 1.7 the .on() function should be used instead

from jQuery's page on .bind() -  "As of jQuery 1.7, the .on() method is the preferred method for attaching event handlers to a document" - http://api.jquery.com/bind/ 

bind() still works but it calls .on() internally

**Comment by danroth27** [comment]
This code is no longer in this doc.
