### ISSUE TITLE
Framework Package conflict

### ISSUE THREAD

**Issue by jwgain0** [aspnet/Docs#6384]
Following the instructions. It tells you to down load the 2.1.200 dotnet sdk and use the cli to create the webapi project. That works fine, but the next step says update the TodoApi.csproj with adding a package reference to "Microsoft.AspNetCore.App" at version "2.1.0-rc1-final". When I add that reference and run Omnisharp in vs code, it fails with this message:

Error: Package Microsoft.AspNetCore.App 2.1.0-rc1-final is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package Microsoft.AspNetCore.App 2.1.0-rc1-final supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)

The cli create makes the TodoApi.cs have a target framework of netcoreapp2.0. If I update that to netcoreapp2.1. Then the error changes to:

Error: The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.

Even though if I do dotnet --version it states I have 2.1.200.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@jwgain0 You'll need to install the .NET Core 2.1 RC1 SDK. Use the following link to do that: https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-rc1. After doing so, `dotnet --version` will display `2.1.300-rc1-008673`. Running the `dotnet new` command at that point will generate a project targeting `netcoreapp2.1`.
