### ISSUE TITLE
Update Configure ASP.NET Core Identity for 2.1

### ISSUE THREAD

**Issue by joeruder** [aspnet/Docs#6386]
When you use VS 15.7.1 and create a new Web Application MVC project using Core 2.1, Individual User Accounts - Store account in-app it does not create the ApplicationUser.cs classs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3ac09f0-74ca-1a5d-4fec-695b84c1ac95
* Version Independent ID: cd2c1f5e-e4f0-d2c3-4737-8ff4f0c176c2
* Content: [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-configuration.md)
* Service: **asp.net-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **scaddie**

**Comment by zatanax** [comment]
same problem ,

**Comment by Rick-Anderson** [comment]
@joeruder  @zatanax do you want to create a class for custom user data?

**Comment by Rick-Anderson** [comment]
You can use [Scaffold Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
to add 
```
using Microsoft.AspNetCore.Identity;
using System;

namespace WebApp1.Areas.Identity.Data
{
    public class WebApp1User : IdentityUser
    {
        [PersonalData]
        public string Name { get; set; }
        [PersonalData]
        public DateTime DOB { get; set; }
    }
}
```

**Comment by vnextcoder** [comment]
@Rick-Anderson  1 query. How to modify the SigninOptions once it has been setup by ```IdentityHostingStartup.cs```
