### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#64]
ASP.NET 5->Fundamentals->Configuration
- Get, set, 
- Providers: JSON, XML, INI, env vars
- Custom providers
- Options model

**Comment by ardalis** [comment]
@danroth27 
Does it make sense to cover Microsoft.Framework.ConfigurationModel.UserSecrets in this article as well?

**Comment by danroth27** [comment]
Nah, we are going to have a specific topic covering handling app secrets. See #93.
