### ISSUE TITLE
Update Cache in-memory for RP

### ISSUE THREAD

**Issue by vsaranea** [aspnet/Docs#6402]
Can we get a sample for caching which targets the Razor Pages/Page Models workflow which is now recommended? I can't find one anywhere...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's pretty much the same thing, but rather than a controler you have a page model. I've scheduled this for update.

**Comment by vsaranea** [comment]
Thanks!

Is it possible to do on Partial Views? 

e.g. I have a sidebar which displays some menus, and shows status of each menu item (# items, etc.). The Partial View receives a Model, but not a page model. 

If I add a cache taking constructor to the model, will it work?

**Comment by Rick-Anderson** [comment]
fixed in #7792
