### ISSUE TITLE
New doc: How to upgrade ASP.NET Core 2.0 to 2.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6404]
URL must be `https://docs.microsoft.com/en-us/aspnet/core/migration/20-to-21/?view=aspnetcore-2.1`

Title **Migrate from ASP.NET Core 2.0 to 2.1**
See  #6069 ?
Update link in 
```
uid: aspnetcore-2.1
# What's new in ASP.NET Core 2.1
```
`See [Migrate from ASP.NET Core 2.0 to 2.1](xref:migration/index)`

See https://www.stevejgordon.co.uk/upgrading-aspnet-core-2-application-aspnet-core-2-1-preview-1 and ask Steve Gordon to review.

**Comment by scottaddie** [comment]
@Rick-Anderson See the instructions here: https://blogs.msdn.microsoft.com/webdev/2018/05/07/asp-net-core-2-1-0-rc1-now-available/#migrating-an-asp-net-core-2-0-x-project-to-2-1-0-rc1

**Comment by Rick-Anderson** [comment]
All that's in [CompatibilityVersion](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#setcompatibilityversion-for-aspnet-core-mvc) and  #6069 
I'll show the new code the templates generate.

**Comment by Rick-Anderson** [comment]
@natemcmaster  can you give me the elevator pitch on why the templates went from `BuildWebHost` to [CreateWebHostBuilder](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.testing.webapplicationfactory-1.createwebhostbuilder?view=aspnetcore-2.1#Microsoft_AspNetCore_Mvc_Testing_WebApplicationFactory_1_CreateWebHostBuilder)

I'd like to add that to this migration doc.

**Comment by Rick-Anderson** [comment]
@natemcmaster  bonus if you can tell me why ` "AllowedHosts": "*"` was added to *appsettings.json*.

**Comment by natemcmaster** [comment]
AllowedHosts was added due to https://github.com/aspnet/Home/issues/2954. @Tratcher is the expert on this one.

WebHostBuilder changes were made to make it easier to write integration tests. @javiercn's can share more.

**Comment by Rick-Anderson** [comment]
@guardrex  can you review what I say about `CreateWebHostBuilder` and the links I provide to your testing doc?

**Comment by Tratcher** [comment]
Nate is correct on AllowedHosts. 2.1 has a small new host filtering middleware included in CreateDefaultBuilder and setting a real body name in AllowedHosts activates it. The * is only a placeholder for discoverability.
