### ISSUE TITLE
UseStatusCodePagesWithRedirects doesn't work

### ISSUE THREAD

**Issue by sonichanxiao** [aspnet/Docs#6408]
Not sure if I did anything wrong or missed something. Tried to add app.UseStatusCodePagesWithRedirects("/error/{0}"); within Startup.cs under Configure, t gives me a Can't reach this page error. Error Code: INET_E_REDIRECT_FAILED.
Do I need to create a page e.g. 403.cshtml under /Error/ folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Service: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks @sonichanxiao for mentioning this. Yes, that's correct. Create a view/page for the endpoint. I just so happen to have such a endpoint in a few of my test Razor Pages apps because they use ...

```csharp
app.UseStatusCodePagesWithReExecute("/Error/{0}");
```
... so I have a Razor Page setup like this ...

```cshtml
@page "{statusCode?}"
@using testselfcontained
@model ErrorModel

<!DOCTYPE html>
<!-- REST OF THE PAGE FOLLOWS HERE -->
```

I'll do some work on the doc to make it clear that a page/view must be created to receive a redirect or re-execute.

**Comment by sonichanxiao** [comment]
Thank you @guardrex , Or an updated sample code in Github would also do the job.

**Comment by guardrex** [comment]
Good idea. I'll make a note on the sample tracking issue for this. #5495
