### ISSUE TITLE
Add IdentityUser POCO navigation properties - issue with generic value int

### ISSUE THREAD

**Issue by ltrader123** [aspnet/Docs#6414]
Hi,
for me the example of the navigation properties did not work when I tried to use Entity Framework Core Add-Migration along with it.
When calling 
Add-Migration MyMigrationName -Context "MyAppIdentityDbContext"
I received an error message similar to the following:
The entity type 'IdentityUserLogin<int>' requires a primary key to be defined.

The issue was that the properties have been defined as follows:
/// <summary>
/// Navigation property for the roles this user belongs to.
/// </summary>
public virtual ICollection<IdentityUserRole<int>> Roles { get; } = new List<IdentityUserRole<int>>();

public virtual ICollection<IdentityUserClaim<int>> Claims { get; } = new List<IdentityUserClaim<int>>();

public virtual ICollection<IdentityUserLogin<int>> Logins { get; } = new List<IdentityUserLogin<int>>();

As a generic type there is used an int. I changed that to string as the primary key in the AspNetUsers table is of type nvarchar.
Because of that it seems that the int considered as foreign key does not successfully map.

Change the properties from e.g.
public virtual ICollection<IdentityUserClaim<int>> Claims { get; } = new List<IdentityUserClaim<int>>();
to 
public virtual ICollection<IdentityUserClaim<string>> Claims { get; } = new List<IdentityUserClaim<string>>();
and it worked.

This might be an issue with the example?

Best Regards,
Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4b263b-e8f9-8b44-8c13-5bc0128fb1c9
* Version Independent ID: 985774b6-a165-f22c-c354-6c12a6783063
* Content: [Migrate authentication and Identity to ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/1x-to-2x/identity-2x.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/1x-to-2x/identity-2x.md)
* Service: **asp.net-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by mguinness** [comment]
Unfortunately this is very confusing as evidenced by the very long thread at https://github.com/aspnet/Identity/issues/1361.  Hopefully these navigation properties will be added to the new project templates when selecting individual user accounts.  Below is what I ended up using in my project:

```C#
public virtual ICollection<IdentityUserRole<string>> Roles { get; set; }
public virtual ICollection<IdentityUserClaim<string>> Claims { get; set; }
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
