### ISSUE TITLE
Microsoft.AspNetCore.All include EF Core is necessary?

### ISSUE THREAD

**Issue by CwjXFH** [aspnet/Docs#6423]
Include EF Core in Microsoft.AspNetCore.All is necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5324eda1-40f2-4e41-08ff-c2610f3853c2
* Version Independent ID: 99d54f78-d56e-8061-e821-90748722c184
* Content: [Microsoft.AspNetCore.All metapackage for ASP.NET Core 2.x and later](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.0#feedback)
* Content Source: [aspnetcore/fundamentals/metapackage.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/metapackage.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@CwjXFH EF Core 2.x package **are** in the metapackage; so yes, they are included by default ...

> All the features of ASP.NET Core 2.x and Entity Framework Core 2.x are included in the Microsoft.AspNetCore.All package. 

You raise an interesting side-point tho. @Rick-Anderson What do you think about the idea that the topic could have a short explanation on how to see what's in the metapackage (this could extend over to your "App" topic as well? Something like this ...

> To see a list of the packages included in the `Microsoft.AspNetCore.All` metapackage:
>
> 1. Navigate to the \[Microsoft.AspNetCore.All metapackage page on NuGet](https://www.nuget.org/packages/Microsoft.AspNetCore.All).
> 1. Open the \*\*Dependencies\*\* node.

**Comment by Rick-Anderson** [comment]
It's pretty clear

All supported packages by the ASP.NET Core team.
All supported packages by the Entity Framework Core.
