### ISSUE TITLE
.Net Client docs

### ISSUE THREAD

**Issue by hannesne** [aspnet/Docs#6429]
Hi there, it would be great if you could add some docs to describe .Net clients, similar to the docs for JavaScript clients. The current documentation is very thin on support for .Net clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Service: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
@hannesne Great timing! We're working on this right now, as there's a PR in process for it https://github.com/aspnet/Docs/pull/6200
Going to close this since it's almost published. Keep a lookout in the next few days for the doc.
