### ISSUE TITLE
IOptions<TOptions> doesn't just magically work as written in /fundamentals/configuration.rst

### ISSUE THREAD

**Issue by treestryder** [aspnet/Docs#643]
Please give the fully qualified name for IOptions<TOptions> or mention adding the using statement in /fundamentals/configuration.rst.

using Microsoft.Framework.OptionsModel;

 * Missing name spaces in documentation and tutorials is a general beef of mine.

**Comment by ardalis** [comment]
We should fix this as part of the update to RC1. Should just need to change this:
.. literalinclude:: configuration/sample/src/UsingOptions/Controllers/HomeController.cs
  :linenos:
  :language: c#
  :lines: 11-24
  :dedent: 4

to
.. literalinclude:: configuration/sample/src/UsingOptions/Controllers/HomeController.cs
  :linenos:
  :language: c#
  :lines: 1-24
  :dedent: 4

and perhaps emphasize the using statement.

**Comment by danroth27** [comment]
We don't want to add using statements for all code snippets. The code snippets come from sample apps that are included in the docs repo that you can look at. We could look into making it easier though to jump to the code from the snippet.
