### ISSUE TITLE
LogOut: Still signed in after SignOutAsync!

### ISSUE THREAD

**Issue by 0x0041764C** [aspnet/Docs#6439]
After calling SignOutAsync I was still signed in. When returning 'void' (async Task) the problem was solved.
Fatal is, that it seems to work with Postman during testing. But in the app after LogOut I was still logged in with the same user. Even after logging in as a different user.

See  https://stackoverflow.com/a/48460538/8405156
<quote>
The problem is that your RedirectToAction overwrites the redirect to the Identity Server endsession URL that SignOutAsync issues.
</quote>
I think the documentation should be updated to make aware that this is a problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.0&tabs=visual-studio%2Caspnetcore2x#feedback)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  should I add this to the doc?

**Comment by jgathairu** [comment]
Am unable to Authorize the application using the role after successful authentication. Am returning The Role from the ADFS Claims provider. The message from asp.net core 2.1 application Access denied
You do not have access to this resource. Need this to work as its currently working on an MV5 application
