### ISSUE TITLE
Document usage of ProducesResponseTypeAttribute 

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/Docs#6440]
There's no documentation for ProducesResponseType from what I saw.

https://github.com/aspnet/Mvc/blob/79e576b86c040d676dcd96a6e666dc75f79da211/src/Microsoft.AspNetCore.Mvc.Core/ProducesResponseTypeAttribute.cs#L14

I think this is a good place to document it:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.1

**Comment by enemyofthedawn** [comment]
It seems like it's here: https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml

**Comment by mintxelas** [comment]
That´s not documentation of the ProducesResponseTypeAttribute, it´s just an example usage (not even that I'd say)

**Comment by Rick-Anderson** [comment]
Moved to #9789
