### ISSUE TITLE
Thanks and Suggestion

### ISSUE THREAD

**Issue by marioguttman** [aspnet/Docs#6448]
This is a great course.  I've been exploring options for Visual Studio based Web design and was planning on learning about MVC but will likely just focus on Razor Pages instead.  (I do find it a little confusing that MVC function names seem to creep in to the Razor functionality.)
The only snag I found (and many others have reported this) was that I had to switch my Microsoft.VisualStudio.Web.CodeGeneration.Design from version 2.04 back to 2.03.
One other thought: I've looked around quite a bit for information about how to combine tutorials like this one with tutorials that show how to set up users and validate logins.  I haven't found much.  What I did in this case was select the "Users with individual logins" option when I set up the project.  Then I skipped several steps where this tutorial creates the database context.  In the code I had to generally replace "Models.MovieContex" with "Data.ApplicationDbContext".  It might be useful if the tutorial were set up this way or included instructions for doing this.
Thanks for the great work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1cf23f9-09c0-0776-2924-46ea571afb4c
* Version Independent ID: f7dbe836-768d-ea56-33d0-f8e42c166afd
* Content: [Upload files to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/uploading-files?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/uploading-files.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/uploading-files.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@marioguttman  thanks for your suggestion.
