### ISSUE TITLE
About Entifyframework initilaization-LocalDB

### ISSUE THREAD

**Issue by fallincloud** [aspnet/Docs#6456]
If I use the connection string such as `"  <add name="Default" connectionString="Data Source=(LocalDb)\MSSQLLocalDB;Initial Catalog=A1;Integrated Security=SSPI;AttachDBFilename=|DataDirectory|\T1.mdf" providerName="System.Data.SqlClient"/>"  `  I don't know when the Web app will create the T1.mdf, sometimes I can see it would be created during the Web app running, sometimes the Web app would throw exception such as 

> Cannot attach the file 'E:\Projects\DemoSource\...\T1.mdf' as database .

 How to solve this problem? or Can I manually create local DB before start up Web App? Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [ASP.NET Core MVC with EF Core - Migrations - 4 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.1#introduction-to-migrations)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@fallincloud  can you try asking this question on SO and reporting the link back here?
