### ISSUE TITLE
Add Example of RequireAssertion

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#6458]
What do you think about adding an example of [`RequireAssertion()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationpolicybuilder.requireassertion?view=aspnetcore-2.0)?

This [SO thread](https://stackoverflow.com/a/50393047/185123) is about checking the scope claim which is a space delimited list so the [`RequireClaim()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationpolicybuilder.requireclaim?view=aspnetcore-2.0) won't work it.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25051544-0e4d-1715-95b7-3a8616475127
* Version Independent ID: 50736569-fc04-ec6d-7b33-a3e0c860b1ed
* Content: [Claims-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-2.0)
* Content Source: [aspnetcore/security/authorization/claims.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/claims.md)
* Service: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  can you set a priority on this?

**Comment by blowdart** [comment]
Without knowing your scale I rate it mauve.

Oh. Ok. Medium :)

**Comment by spottedmahn** [comment]
If you think 💭 it is a good idea 💡, I’m happy to take a stab at and submit a PR?

Didn’t want to create a PR and have it declined...

**Comment by Rick-Anderson** [comment]
Sounds great.

**Comment by spottedmahn** [comment]
Look 👀 at what I just found: [Using a func to fulfill a policy](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.0#using-a-func-to-fulfill-a-policy).

I submitted a PR to refernce this doc in the claims-based auth page.
