### ISSUE TITLE
NPM?

### ISSUE THREAD

**Issue by chris-spain-ir** [aspnet/Docs#6459]
Perfect example of why Microsoft Development is going backwards, not forwards. Requirement of NPM? 
"Please go install a third party non-integrated trojan horse... Then go install some extensions that will use the horse... Then setup a poorly documented complex special configuration file for it..."
Oh yea.. one more thing.. if you don't have real job and actually can go to this level of work to integrate a preprocessor into visual studio 2017 on your own, then know all of this is temporary... With each weekly studio update, you never know what goodies are going to destroy this ridiculously fragile approach. … Find your rhythm...  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01743cdd-23a9-2846-1e6e-7fbccab03d7e
* Version Independent ID: c60c655f-92dd-5f4a-799f-d55b0e6700e8
* Content: [Less, Sass, and Font Awesome in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/less-sass-fa?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/less-sass-fa.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/less-sass-fa.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@chris-spain-ir Thanks for the feedback, but this is the documentation repo. The issues in this repo are only routinely monitored by documentation workers and community members working on documentation. We can't process general feedback here for products and services. Clicking the "Product Feedback" button on the topics takes you to the CONTRIBUTING page, where they recommend that you open an issue in the aspnet/Home repo for feedback: https://github.com/aspnet/Home/issues.
