### ISSUE TITLE
Update tutorials for 2.1 SDK you no longer need to manually add DotNetCliToolReference

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6461]
Most tools are bundled with the .NET Core CLI in .NET Core SDK 2.1. For .NET Core SDK 2.0 and earlier, tool installation is necessary.

[This query](https://docs.microsoft.com/en-us/search/index?search=DotNetCliToolReference&scope=ASP.NET+Core) finds `DotNetCliToolReference`

See https://github.com/aspnet/EntityFramework.Docs/issues/708

**Comment by Rick-Anderson** [comment]
@guardrex  should this issue be rolled into one of your issues?

**Comment by guardrex** [comment]
I think so. I have been removing them as I go on #5495.
