### ISSUE TITLE
New topic: SignalR to SignalR Core migration

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6463]
@BrennanConroy  is this something you could get started? 
cc @tdykstra

**Comment by rachelappel** [comment]
General feature differences
-transports
-auto reconnects
-protocol support 
-use with websockets directly
Server-side differences
-config
-middleware
Sticky sessions now required
Single hub per connection
Streaming
Client-side differences
-js syntax
-jqyery dep
-Typescript

**Comment by BrennanConroy** [comment]
I believe most of this has been covered by https://docs.microsoft.com/aspnet/core/signalr/version-differences?view=aspnetcore-2.2

I'll take a look and see if anything obvious is missing.
