### ISSUE TITLE
had a few issues with [HttpPost]  item.... im not sure what i did wrong.... i had to comment it out for the app to work

### ISSUE THREAD

**Issue by aaronlilly84** [aspnet/Docs#6465]
[HttpPost]
public string Index(string searchString, bool notUsed)
{
    return "From [HttpPost]Index: filter on " + searchString;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Adding Search](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@aaronlilly84  I'm not sure what you did wrong either. When you figure it out post your solution here.

**Comment by Rick-Anderson** [comment]
@aaronlilly84  looks like you're missing a trailing " on the string.

**Comment by Rick-Anderson** [comment]
@aaronlilly84  I think the tutorial has you remove the post at some point.

**Comment by Rick-Anderson** [comment]
Take a look at the completed download.

**Comment by aaronlilly84** [comment]
sorry? completed download? not sure what you mean by that, is there a file i can download to check against my code?
