### ISSUE TITLE
Which Index method?

### ISSUE THREAD

**Issue by aaronlilly84** [aspnet/Docs#6468]
first item on this page states "
Update the Index method with the following code:

however, which index method is it referring to

is this in MoviesConroller.CS
or is this HomeController.CS?
or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Adding Search](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by aaronlilly84** [comment]
I assume MoviesController.CS, as is the only file with 
" public async"
the previous code in Movies Controller.CS is
"public async Task<IActionResult> Index()
       {
           return View(await _context.Movie.ToListAsync());
       }"

**Comment by Rick-Anderson** [comment]
correct.
