### ISSUE TITLE
EntityFrameworkConfigurationSource sample is out of date

### ISSUE THREAD

**Issue by Eilon** [aspnet/Docs#647]
The code here: https://github.com/aspnet/Docs/tree/master/aspnet/fundamentals/configuration/sample/src/CustomConfigurationSource

Which shows up in this doc: http://docs.asp.net/en/latest/fundamentals/configuration.html

Needs to be updated to take into account many renames and API changes in configuration.

**Comment by danroth27** [comment]
@ardalis Is this getting addressed as part of https://github.com/aspnet/Docs/pull/1231?
