### ISSUE TITLE
Tutorial ends at Add Search, and link to next step at bottom goes to Visual Studio series

### ISSUE THREAD

**Issue by pfmvidal** [aspnet/Docs#6470]
VS Code tutorial covers until Add Search, but there is a link at the bottom of the page NEXT: ADDING A NEW FIELD. When I click on this link, it redirects to the Visual Studio series, not VS Code.

This is the last step in VS Code: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/search?view=aspnetcore-2.0

Clicking on the NEXT... link at the bottom of the page brings me to: https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.0

The difference is the /razor-pages-vsc/. I hope this can be corrected so the tutorial can be completed.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4236ea38-ddd9-3282-999f-3f318cd50c73
* Version Independent ID: 9f8a4ffd-07b3-5bd8-849d-0dddc0314711
* Content: [Adding search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/search?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/search.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pfmvidal  you'll have to follow the common instructions at that point. I don't think there's anything VS specific. See https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages-vsc

**Comment by Rick-Anderson** [comment]
@pfmvidal  this is by design.
