### ISSUE TITLE
ASP.NET Core 2.1 Angular 6.0 SPA Template 

### ISSUE THREAD

**Issue by Urgen-Dorjee** [aspnet/Docs#6481]
I have scaffolded Asp.Net Core 2.1 Angular 6.0 SPA template from cli and then installed npm package accordingly. However when i try to run the project "dotnet run" it does not start rather prompted with and error:- 

 Fail: Microsoft.AspNetCore.SpaServices[0]
        Unknown option: '--extractCss'
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.0&tabs=netcore-cli)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by damienbod** [comment]
I just removed this from the package.json file and it worked then

    "start": "ng serve --extract-css",

to 

    "start": "ng serve",

**Comment by damienbod** [comment]
Here's an example

https://github.com/damienbod/dotnet-template-angular/blob/master/dotnet-angular-google-oidc/ClientApp/package.json

**Comment by scottaddie** [comment]
@Urgen-Dorjee The Angular 6.0 template upgrade is in progress. See https://github.com/aspnet/templating/pull/515 for the status and upgrade steps.

**Comment by zhshqzyc** [comment]
I have a similar issue. My ng version is 1.7.0; node.js version is 10.16.0; angular: 5.2.0. Visual Studio 2017 Pro(15.9.13).

My package.json file some codes are:
`"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:ssr": "npm run build -- --app=ssr --output-hashing=media",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },`
The .net core code:
` app.UseSpa(spa =>
      {
        // To learn more about options for serving an Angular SPA from ASP.NET Core,
        // see https://go.microsoft.com/fwlink/?linkid=864501
 
        spa.Options.SourcePath = "ClientApp";
 
        if (env.IsDevelopment())
        {
          spa.UseAngularCliServer(npmScript: "start");
         }
      });`
If I click F5, the `ng serve` runs, however it hangs on somewhere, The message is:
`webpack: wait until bundle finished:
69% building modules 1878/1879 modules ...\sass\styles.scss`
Then throw exception `fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively
you may wish to switch to the Development environment.`
Then finally compiled finished. The web page also shows exception.
The interesting thing is if I run `ng serve` separately until webpack finish the the compiling. Then I run `dotnet run` it can pass no error.

One more thing is my coworker doesn't have the issue with the same configuration. I guess somehow the timing issue, we have to wait ng serve finishing something. I have spent a few days no luck. Please help me out.

Urgent request.


ok
Thanks
