### ISSUE TITLE
Update to 2.1 Razor Pages with Entity Framework Core in ASP.NET Core

### ISSUE THREAD

**Issue by crbeckman** [aspnet/Docs#6482]
`Edit` This series needs to be updated for 2.1

I am not smart enough to know the fixes.  Would my identifying the failings be an assist or a waste of time?  Or even be perceived as an insult to those that have built these pages.  Or should I post this elsewhere?
chuck

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Please not what has changed. Be sure to install the latest [.Net Core SDK 2.1](https://github.com/dotnet/versions/tree/0e9c116a41f5b1b6e92819b60604bbe4c0c999b8/build-info/dotnet/product/cli/release/2.1-rtm)

**Comment by jonathanmbaker** [comment]
Installing that latest SDK (2.1) worked for me. I started the tutorial with .NetCore 2.0, then I got errors at the point of running the scaffolding because my I had a mix of 2.0 and 2.1 packages. Which were resolved by installing 2.1, and replacing AspNetCore with a 2.1.X version

**Comment by Rick-Anderson** [comment]
@crbeckman  I'll be starting on this soon, hopefully you can review it when I'm finished.

**Comment by Pangar** [comment]
Hello, Not sure if its just me but "dotnet new webapp -o ContosoUniversity" command is not working.  It's saying that webapp is not a template.  I usually substitute webapp with razor.  Is there a reason why?

**Comment by Rick-Anderson** [comment]
@Pangar   `webapp` requires the 2.1 version of the .NET Core SDK.
