### ISSUE TITLE
Question for clarification?

### ISSUE THREAD

**Issue by gaazkam** [aspnet/Docs#6487]
This article says: "Applications that do not include authentication can apply the scaffolder to add the RCL Identity package."

Just to be sure. Does this mean that what this article describes can only be on projects that did not follow this tutorial: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x ? I mean, does this mean that if, while creating a new project, I click "change authentication" and select Individual User Accouts as this screenshot shows: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity/_static/03-new-project-auth.png - then I can no longer scaffold indentity into that project?

I'm sorry, this is not completely clear for me. Thank you in advance for clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
If you read the rest it does both projects.
