### ISSUE TITLE
dotnet publish -c release -o publish -r linux-x64

### ISSUE THREAD

**Issue by mattiasw2** [aspnet/Docs#6493]
Since this is about Linux, remember that you need to publish using "dotnet publish -c release -o publish -r linux-x64" since otherwise, you will not be able to start the web server. It will complain about Microsoft.ApplicationInsights.AspNetCore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by shirhatti** [comment]
@mattiasw2 That seems odd. You should be able to run a portable app on linux just fine and need not do a rid publish if you've installed the shared framework.
cc @JunTaoLuo

**Comment by mattiasw2** [comment]
I installed according to these instructions:

https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-current

**Comment by JunTaoLuo** [comment]
Can you share your project file (.csproj) and the output of `dotnet --info`?

**Comment by mattiasw2** [comment]
> dotnet --info
> .NET Command Line Tools (2.1.105)
> 
> Product Information:
>  Version:            2.1.105
>  Commit SHA-1 hash:  141cc8d976
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64
>  Base Path:   /usr/share/dotnet/sdk/2.1.105/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.7
>   Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
> 
> 

and the project file

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <Version>0.3.3</Version>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.2.2" />
    <PackageReference Include="ClosedXML" Version="0.92.1" />
    <PackageReference Include="Dapper" Version="1.50.4" />
    <PackageReference Include="HashDb" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.0.3" />
    <PackageReference Include="MySqlConnector" Version="0.40.2" />
    <PackageReference Include="MyStd" Version="1.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
    <PackageReference Include="ssclc" Version="1.0.1" />
    <PackageReference Include="ssclcserver" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Views\SignIn\Index.cshtml" />
    <None Include="Views\NoAccount\Index.cshtml" />
    <None Include="Views\LoggedOut\Index.cshtml" />
    <None Include="Views\Home\Index.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyStd2\MyStd2.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot\elm.js">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by JunTaoLuo** [comment]
There are several version mismatches between the Runtime and AspNetCore versions. 

I see that you are using 2.0 so the latest SDK to install is 2.1.201: https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.201 which contains AspNetCore 2.0.8. What I see in your project file is that you are using Microsoft.AspNetCore.All 2.0.6, this should be updated to 2.0.8, Microsoft.AspNetCore.Authentication.Cookies should be updated from 2.0.3 to 2.0.4. Finally, you need to make sure the machine you are deploying to also has the matching version of the runtimes installed: https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.8, for Linux, this would mean the Hosting Bundle Binaries.

**Comment by mattiasw2** [comment]
Thank you for pointing out the mismatches. How should I know about them? I have only used nuget to install things. Is there a tool or pointer to a webpage which describes how to make sure version match. 

Also, I do not think is the the cause of the original problem. At that time, the project was smaller and MS hadn't released 2.0.8. If I understand it correctly, Microsoft.ApplicationInsights.AspNetCore is not even supported on Linux.

**Comment by mattiasw2** [comment]
I assume 2.0.7 backwards compatible with 2.0.6.

Do I have to update all DLLs to 2.0.7 and recompile, just because I have installed 2.0.7?

**Comment by JunTaoLuo** [comment]
Yes you need to ensure the packages you reference `Microsoft.AspNetCore.All` matches the runtime that you installed on the production machine. Without the roll forward mechanism we introduced in 2.1, you will need to make sure they match exactly.

**Comment by shirhatti** [comment]
Closing this issue isn't it looks like the issue was resolved. Feel free to reopen if the issue persists.
