### ISSUE TITLE
How to prevent precompilation?

### ISSUE THREAD

**Issue by mattiasw2** [aspnet/Docs#6494]
My project works fine from within VS2017 on Windows 10 and Rider on Ubuntu.

However, when I start it from the command line or bash with dotnet XXXX.dll, it cannot find the views, see below. A Lic6.PrecompiledViews.dll file is generated

I tried turning it off by adding this .csproj, but no difference, the Lic6.PrecompiledViews.dll  is still generated.

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
```

```
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Lic6.Controllers.SignInController.Index (Lic6), returned result Microsoft.AspNetCore.Mvc.ViewResult.
dbug: Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine[1]
      View lookup cache miss for view 'Index' in controller 'SignIn'.
fail: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[3]
      The view 'Index' was not found. Searched locations: /Views/SignIn/Index.cshtml, /Views/Shared/Index.cshtml
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Lic6.Controllers.SignInController.Index (Lic6) in 13.3798ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLDTCR0QVJ9B", Request id "0HLDTCR0QVJ9B:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/SignIn/Index.cshtml
/Views/Shared/Index.cshtml
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation and precompilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mattiasw2** [comment]
Found the problem, some wizard had added these rows to .csproj, and they seems to be ignored by both VS2017 and Rider, but not by dotnet publish. Deleting made precompilation work.

```
  <ItemGroup>
    <Content Remove="Views\SignIn\Index.cshtml" />
    <Content Remove="Views\NoAccount\Index.cshtml" />
    <Content Remove="Views\LoggedOut\Index.cshtml" />
    <Content Remove="Views\Home\Index.cshtml" />
  </ItemGroup>
```

**Comment by Rick-Anderson** [comment]
@mattiasw2  Thanks for posting back the solution.
