### ISSUE TITLE
Simple and crisp

### ISSUE THREAD

**Issue by nishanthnow** [aspnet/Docs#6495]
Thank you for such a crisper version. Good enough to get started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5395e3-ffc8-99d9-5546-cf155f80c739
* Version Independent ID: 9b17fa82-ec20-8a47-415a-d33eebfff855
* Content: [Working with SQLite and ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/working-with-sql?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app-mac/working-with-sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-mac/working-with-sql.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @nishanthnow for the feedback! :smile:
