### ISSUE TITLE
Delete all records in the DB

### ISSUE THREAD

**Issue by satucker2** [aspnet/Docs#6497]
I got to this point with everything working correctly:
"If you delete all the records in the DB, the initializer will seed the DB and include the Rating field. You can do this with the delete links in the browser or from Sql Server Object Explorer (SSOX). To delete the database from SSOX: Select the database in SSOX. Right click on the database, and select Delete. Check Close existing connections. Select OK."
What database are we supposed to delete? I deleted the database that we viewed earlier in the tutorial under:
"(localdb)\MSSQLLocalDB (SQL Server 1) > Databases > Movie-1 > Tables > dbo.Movie"
This was a mistake as the Movies page will no longer load. I will have to start over on the tutorial which is okay but I would like to know how to fix this before I move past this part of the tutorial. 
Where would I find the "close existing connections" option to check? This answer may come when you answer the above questions. 
So far, this is a great tutorial; however, it would be extremely beneficial to have an "if you get this error then you probably did this..." for the major changes to the website. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Change the connection string and it will create a new DB.
