### ISSUE TITLE
Code to add the seed initializer could need a brief explanation of what's going on

### ISSUE THREAD

**Issue by CodeAphex** [aspnet/Docs#6499]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.0#add-the-seed-initializer

The start of the tutorial explains a lot of things in detail, this part is missing info or links for scoped context https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.0#service-lifetimes-and-registration-options, additionally the changed parts of the main method could be highlighted to make it clearer what exactly was added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with SQL Server LocalDB and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@CodeAphex  Thanks for your suggestion. The tutorial doesn't go into depth on anything. You'll need to find that out in other docs.

**Comment by cday9** [comment]
Rick,
Depth is a subjective term.  The added code snippets are clearly highlighted elsewhere in the TUTORIAL, and you just dismissed CodeAphex's comment without reading it - lazy, rude and un-Microsoft of you...  better work on those people skills if you ever want to make evangelist!
