### ISSUE TITLE
Remove -- from generated titles

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#650]
Yeah, this is the generated title from the html templates. We need to see if can fix the version number too (apparently it comes from conf.py).

File an issue and assign to me.

From: Rick Anderson (ASP.NET) 
Subject: Let's get rid of the double dash -- in the title

It hurts SEO and break zipping

**Comment by danroth27** [comment]
https://github.com/aspnet/docs/pull/731
