### ISSUE TITLE
Scaffold the Movie model

### ISSUE THREAD

**Issue by tbskill** [aspnet/Docs#6500]
Hi Im new in that and I don't understand where exactly I need to do that can someone help me please.

"The preceeding error happens when you are in the wrong directory. Open a command shell to the project directory (The directory that contains the Program.cs, Startup.cs, and .csproj files), and then run the preceeding command."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The directory that contains the Program.cs, Startup.cs, and .csproj files

**Comment by tbskill** [comment]
So what I have to paste in cmd something like that?:
dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir C:\Users\artur\Documents\Visual Studio 2017\Projects\RazorPagesMovie  --referenceScriptLibraries

doesnt work

**Comment by tbskill** [comment]
PM> dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
dotnet : No executable found matching command "dotnet-aspnet-codegenerator"
At line:1 char:1
+ dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No executable f...-codegenerator":String) [], R 
   emoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by Rick-Anderson** [comment]
@tbskill  you have to be in your project directory per the instructions. What version of .NET are you running?
`dotnet --version``

**Comment by tbskill** [comment]
Ok now I know how I go to folder with my project hold SHIFT + right click mouse and select Open in Visual Studio and then i copy and paste that to PM :
dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir --referenceScriptLibraries

and all is working fine:)
