### ISSUE TITLE
Not suitable for Angular 6

### ISSUE THREAD

**Issue by HEBOS** [aspnet/Docs#6501]
Hi,

Angular 6 introduced angular.json instead of .angular-cli.json, so instructions are not suitable for Angular 6.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.0&tabs=visual-studio)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@HEBOS The Angular 6 template upgrade is in progress. Please see https://github.com/aspnet/templating/pull/515 for the status and upgrade steps. The docs will be updated once the template changes are completed.
