### ISSUE TITLE
Change the default name wsfederation

### ISSUE THREAD

**Issue by jgathairu** [aspnet/Docs#6503]
I have posed my query on stackoverflow. How do i change the default name produced "wsfederation" to a name of my choice after enabling adfs (on premise) as shown above. The link https://stackoverflow.com/questions/50431964/asp-net-core-authetication-with-adfs-change-the-button-name-from-wsfederation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.0)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by jgathairu** [comment]
The overload suggested by poke is the solution that i was looking for

**Comment by guardrex** [comment]
This will auto-close when the PR merges.
