### ISSUE TITLE
'scaffolding field to edit startup class to register the new context using Dependency Injection' Error whe

### ISSUE THREAD

**Issue by hosseinRezaei188** [aspnet/Docs#6505]
I Followed last steps exactly but when i reached  Previous level i updated my visual studio to version 15.7.1,Now when i try to add Controller i received this error message.where is my mistake or fault?? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.0#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hosseinRezaei188  what was the exact error and at which step?

**Comment by hosseinRezaei188** [comment]
Error Message:'scaffolding field to edit startup class to register the new context using Dependency Injection'

**Comment by Rick-Anderson** [comment]
@hosseinRezaei188  can you send a screen shot? I don't see that error in our source. 

What version of the dotnet SDK are you using?

`dotnet --version`

**Comment by Rick-Anderson** [comment]
@hosseinRezaei188  you missed some steps. https://github.com/aspnet/Scaffolding/issues/603 shows what's wrong and should point you to what you missed.

**Comment by hosseinRezaei188** [comment]
Tank You @Rick-Anderson
