### ISSUE TITLE
List of Built-in Tag helpers on left navigator does not match list on page itself on right.

### ISSUE THREAD

**Issue by pkellner** [aspnet/Docs#6506]
That is, on left, it just lists my documention (anchor,cache,distr,env,image) but on right there are a bunch more written by Rick, Dave, etc.  Need to add to left navigator.  https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1692705d-02cc-f371-bae5-580380d2e877
* Version Independent ID: ec9bb36b-d744-5c66-8d60-b55ee2c7007a
* Content: [ASP.NET Core built-in Tag Helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/index.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @pkellner ... It's the *toc.md* file that requires the update. Did u want to submit a PR on it, or would you prefer that I take care of it?

**Comment by pkellner** [comment]
I’m rusty on the syntax.  If you could that would be great.

**Comment by guardrex** [comment]
Sure ... thanks for pointing it out ... and great to hear from you!

**Comment by rschindhelm** [comment]
As of 2019-09-13 there's still a mismatch. The Form Action Tag Helper isn't displayed in the TOC.
@guardrex If you would be so kind to update the document again.

**Comment by guardrex** [comment]
<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/1622880/64873301-62623400-d60e-11e9-9513-eee2cc341844.PNG">

**Comment by rschindhelm** [comment]
@guardrex What I see is that there is a distinction made between Form and Form Action tag helpers which isn't reflected in the table of contents:

![image](https://user-images.githubusercontent.com/15197864/65601826-1f577780-dfa3-11e9-9a7d-0e80d46e7780.png)

Also, there seems to be a duplicate entry for the Form Action tag helper, which I marked in red.

Is it the same concept or should they be separate entities?

**Comment by guardrex** [comment]
Hi @rschindhelm ... Would you mind pasting that into a new issue using the feedback form at the bottom of that topic? It will automatically ping the right doc author to address it, which I think is Rick.

**Comment by rschindhelm** [comment]
> Hi @rschindhelm ... Would you mind pasting that into a new issue using the feedback form at the bottom of that topic? It will automatically ping the right doc author to address it, which I think is Rick.

Done.
