### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by samboustani** [aspnet/Docs#6507]
The article seems to have ended abruptly.  Does just going to the browser default path for Nginx launch the application?  Where on the Linux server do you put the published .NET Core files?  Is there a common folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.0&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@samboustani Yes, navigating to the app launches the app. A remark along those lines should appear at the end of the https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx#configure-a-reverse-proxy-server section. I'll take care of it.

@shirhatti Can you remark on the most common location for web apps on an Nginx server?

We have an open PR for this topic with a number of updates at https://github.com/aspnet/Docs/pull/5687. I'll add these updates to that PR.

**Comment by shirhatti** [comment]
I prefer putting website content somewhere under `/var` which is similar to the defaults of other web servers (`/var/www/html`), but we don't have an established convention.
In the referenced doc, you can see that the service definition files uses the directory `/var/aspnetcore/hellomvc`.

**Comment by guardrex** [comment]
Thanks @shirhatti. I'll drop in some text like ...

> It's common to locate web apps under the *var* directory (for example, *var/aspnetcore/hellomvc*).

**Comment by stormyqq** [comment]
Put your all files here. 
WorkingDirectory=/var/aspnetcore/hellomvc
It says WorkingDirectory, meaning this is where your index file should be stored.
