### ISSUE TITLE
Does not work when trying to add-migration or update-database

### ISSUE THREAD

**Issue by jdarundell** [aspnet/Docs#6509]
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: GenericArguments[1], 'Microsoft.AspNetCore.Identity.IdentityRole', on 'Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9[TUser,TRole,TContext,TKey,TUserClaim,TUserRole,TUserLogin,TUserToken,TRoleClaim]' violates the constraint of type 'TRole'.

found the problem

article has:
public class ApplicationDbContext : IdentityDbContext<ApplicationUser, **ApplicationRole**, Guid>
needs to be:
public class ApplicationDbContext : IdentityDbContext<ApplicationUser , **IdentityRole< Guid>**, Guid>
with using Microsoft.AspNetCore.Identity;
in my case i used < int>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d03a65-2965-0261-3d05-bf2c89721fd2
* Version Independent ID: 37f74d7d-ed17-eb35-183d-02f04183f880
* Content: [Configure Identity primary key data type in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-primary-key-configuration?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity-primary-key-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-primary-key-configuration.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **scaddie**

**Comment by dotnetnoobie** [comment]
The way I got the above example to work was to deleted the migration files that are added by default when you create the project.

Then create a new migration which includes the changes and then update the database.

This also allowed me to add my own custom properties to ApplicationUser etc like I could do in previous versions.

**Comment by scottaddie** [comment]
Thoughts on this one, @HaoK?

**Comment by jdarundell** [comment]
I have resolved the problem above - it eventually worked - I must have made an error in my original code - i tried again in a fresh sample project 

Sorry if I caused any inconveinience

**Comment by scottaddie** [comment]
@jdarundell Thank you for letting us know.
