### ISSUE TITLE
Document overriding app settings in Azure Portal

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#6514]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/

This document doesn't talk about how the **Application settings** blade in the Azure Portal can be used to override app settings. I customer asked about it this morning. It's a common task that we should document. I suggest a new section in the document linked above.

**Comment by guardrex** [comment]
@scottaddie Would you like me to take this one on for the updates on https://github.com/aspnet/Docs/issues/7102?

**Comment by scottaddie** [comment]
Yes, please! I've had a couple customers ask about this now.
