### ISSUE TITLE
Generated Proxy

### ISSUE THREAD

**Issue by jfuji6** [aspnet/Docs#6518]
The .NET framework SignalR documentation mentions a generated client proxy.   I have been unable to determine if that is part of the ASP.NET Core 2.1 version or not.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@jfuji6  where does it mention generated client proxy?

**Comment by Rick-Anderson** [comment]
[Get a reference to the generated client proxy for the Hub](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client#how-to-get-a-proxy-for-a-hub-class)

@anurse  is that planned?

**Comment by anurse** [comment]
No, we have no plans to add client proxy generation at this time. It is a feature of ASP.NET SignalR though, so we're not ruling it out from ASP.NET Core SignalR, we just don't have plans to do it yet.
