### ISSUE TITLE
Hi Team, Can you please help where we have defined this key "DbPassword" in the code

### ISSUE THREAD

**Issue by gagandeepp** [aspnet/Docs#6524]
https://github.com/aspnet/Docs/blob/f567d0328efe25696d7cdd23ec50c0cf4328d0a6/aspnetcore/security/app-secrets/samples/2.1/UserSecrets/Startup2.cs#L26

**Comment by guardrex** [comment]
Hi @gagandeepp ... It's not defined in the code. It's defined on the command line. See: https://docs.microsoft.com/aspnet/core/security/app-secrets#string-replacement-with-secrets

```console
dotnet user-secrets set "DbPassword" "pass123"
```

**Comment by scottaddie** [comment]
@gagandeepp Also see the following section, which explains where the Secret Manager tool stores the secrets on your machine: https://docs.microsoft.com/aspnet/core/security/app-secrets?view=aspnetcore-2.0&tabs=windows#how-the-secret-manager-tool-works. The command provided above by @guardrex stores the `DbPassword` key-value pair in a *secrets.json* file.
