### ISSUE TITLE
Applying migrations in production

### ISSUE THREAD

**Issue by philip-reed** [aspnet/Docs#6525]
It would be nice if there was more advice on how to apply migrations in production.  Is there a way to get TFS/VSTS to create the migration script during a build, to be consumed during a release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145343de-9267-9171-b6c9-718703b7544d
* Version Independent ID: 2c2f791f-d41c-f995-a941-2461151a7db4
* Content: [Razor Pages with EF Core in ASP.NET Core - Migrations - 4 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-rp/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/migrations.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@philip-reed  thanks for the question. Unfortunately we don't have the resources to cover TFS/VSTS.

**Comment by Rick-Anderson** [comment]
@philip-reed  if you get a good response to your question can you post the link here?

**Comment by philip-reed** [comment]
Buck Hodges tweeted about this extension today by Benjamin Day.

https://www.benday.com/2018/07/05/deploy-entity-framework-core-2-1-migrations-from-a-dll/
