### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#653]
Fundamentals -> Localization

The following blogs have some initial content on the localization support in MVC 6:
- http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx 
- http://www.vodovnik.com/2015/09/20/localization-in-asp-net-5-mvc-6/

Also, some initial content was started here: https://github.com/aspnet/Docs/pull/554

**Comment by danroth27** [comment]
@Rick-Anderson is taking over this article from the work that @TomArcher had started.

**Comment by danroth27** [comment]
From https://github.com/aspnet/Docs/issues/522: - customer request:
calendar controls and date time formatting causing lot of issues which needed special care while coding. Please let me know if these have been specifically addressed as part of the latest framework or else is there a recommendation as to how best these can be done from the product team.

**Comment by Rick-Anderson** [comment]
dup of #305

**Comment by mkarlsson** [comment]
As stated here "If you would like to review early drafts and outlines of this topic, please leave a note with your contact information in the issue.". I would like to do that :)

**Comment by renattomachado** [comment]
Me too.

**Comment by Shrubs** [comment]
Hey, if I could get an early draft that would be just swell: moores@hotmail.co.uk

Much appreciated!

**Comment by marspd** [comment]
Please send me a copy of the draft if at all possible as I am really struggling with this and have an urgent project that I am working on.
paul@epsys-consultants.co.uk
Regards
Paul

**Comment by Montagne1984** [comment]
Would you please send me a copy of the draft to shifeng222@gmail.com?

**Comment by Rick-Anderson** [comment]
@Montagne1984 @marspd @Shrubs @renattomachado @mkarlsson 
https://docs.asp.net/en/dev/fundamentals/localization.html
