### ISSUE TITLE
Issue with the Update method example.

### ISSUE THREAD

**Issue by larntz** [aspnet/Docs#6531]
This is a great guide. I have found it very useful. I'm pretty green with c# and writing web api's, but I think I found a issue. 

In this section: https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.0#update

I believe this if statement:

``` 
    if (item == null || item.Id != id)
    {
        return BadRequest();
    }

````
should probably be:

```
    if (item == null)
    {
        return BadRequest();
    }

```

Otherwise the example json body does not work.  item.Id is always 0 unless specified (it isn't in the screenshot). If you specify the id in the request body and it matches the id in the url everything works, but that seems redundant. 

Not sure if that is the proper fix, but I wanted to send feedback so I can see what the proper fix should be. 

I apologize if this is a bonehead mistake on my part and the example is correct. 

Thanks again for the documentation. It has been extremely helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by SandraVoss** [comment]
if (item == null || **item.Id != id**)  makes sense there, BUT the Tutorial is missing something in the postman-testpart): 
There is  in Postman, PUT,Body: 

```
{
	"name": "walk cat out edit test",
	"isComplete": false,
}
```

there should be in Postman, PUT,Body the id (you got by adding Item) as param in the body for the Update Method:
```
{
	"id": 3, //!!!
	"name": "walk cat out edit test",
	"isComplete": false,
}
```

public IActionResult Update(long **id, [FromBody**] TodoItem item)
        {
            if (item == null || item.Id != id) 
            {
                return BadRequest();
            }
