### ISSUE TITLE
web.config generation is NOT clear

### ISSUE THREAD

**Issue by klick-barakgall** [aspnet/Docs#6534]
"Creating, transforming, and publishing web.config is handled by the .NET Core Web SDK (Microsoft.NET.Sdk.Web)"

The next lines of none code content specify that a web.config file will be generated with the correct parameters, but it doesn't actually state how to trigger this process? Is there a dotnet line that needs to be run? Will it be generated when the site is added to IIS? Need more details..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.0&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @klick-barakgall ... Specifically, it's handled by an MSBuild target ...

https://github.com/aspnet/websdk/blob/dev/src/Publish/Microsoft.NET.Sdk.Publish.Targets/netstandard1.0/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets#L30-L57

... unless you set a MSBuild property in your project file to disable it ...

```xml
<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
```

The `_TransformWebConfig` target is part of the Web SDK targets (i.e., brought in when the project file specifies `<Project Sdk="Microsoft.NET.Sdk.Web">` ... so you don't need to do anything to set it up) and activated **_when the project is published_**. I agree that more info here would be helpful. I'll see to it. Thanks for opening this issue.

**Comment by klick-barakgall** [comment]
Aha, that makes a lot more sense. Thanks for clarifying that for me!

**Comment by MarneeDear** [comment]
Is this true by default?
<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>

I published my app with dotnet publish and no web.config file was created.

Please explain this section like I am 5.

**Comment by MarneeDear** [comment]
IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled

**Comment by guardrex** [comment]
@MarneeDear If you set ...

```
<IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
```

... your *web.config* won't be touched when you publish.

> no web.config file was created

Does your project file specify the `Sdk.Web`? ...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```

**Comment by MarneeDear** [comment]
Yes I have <Project Sdk="Microsoft.NET.Sdk.Web"> in my project. I also tried using Visual Studio 2017 to publish and I do not get a web.config file in the published files.

**Comment by MarneeDear** [comment]
That app was created using `dotnet` and the Saturn template in F#. It is a web app. You can see all of the code here
https://github.com/MarneeDear/saturn-onion-template/tree/blog

I dont have a deployment scenario. I just want to publish to a local folder and host that in IIS.

Using Visual Studio 2017

1. Right click on my project in Visual Studio 2017
2. Select Publish
3. All the expected files are copied over except the web.config file. 

This is my publish profile
![image](https://user-images.githubusercontent.com/5660628/48678282-6af8f380-eb3e-11e8-81e2-bd55e4a2ab9a.png)

Using dotnet CLI

```
dotnet publish -o publish/ src/Template.Saturn.WebHost/Template.Saturn.WebHost.fsproj
```

All the expected files are are copied over except the web.config.

I hope this helps.

**Comment by MarneeDear** [comment]
I had to set a property on the web.config file. I had to set the `Build Action to Content`. This was not in the documentation. 

Thanks for your help, though.

![image](https://user-images.githubusercontent.com/5660628/48678453-d47a0180-eb40-11e8-8603-4252ba54226a.png)

**Comment by guardrex** [comment]
What you just said isn't required when using the `Microsoft.NET.Sdk.Web` SDK. I noticed that your projects' SDKs are `Microsoft.NET.Sdk` ...

```xml
<Project Sdk="Microsoft.NET.Sdk">
```

... you could try changing the SDK to `Microsoft.NET.Sdk.Web` and see how it goes.

If that doesn't work, my recommendation is to open an issue with the MS engineers in the [aspnet/Home issues](https://github.com/aspnet/AspNetCore/issues). They should be able to see what's going wrong. If you find out that we need to do some docs work, then open a new docs issue using the **Content feedback** button at the bottom of the topic :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis#feedback

**Comment by MarneeDear** [comment]
That seemed to work, thank you. I am sorry I missed that. Thanks for your help.
