### ISSUE TITLE
Clear Writing, Poor Example

### ISSUE THREAD

**Issue by rchrismon** [aspnet/Docs#6540]
This is a good article to get an experienced developer started with authorization. The example application, however, was poorly chosen, in  my opinion. The problem is that the app uses contacts to create, edit, approve, _contacts_! Consequently, the example does not draw a sharp distinction between the authorization scheme/model and the domain model. IOW, it's freaking confusing!

Readers would be better served, I believe, if this document were rewritten using Contoso, Northwinds, or any other example where who is authorized is sharply distinct from what is being authorized, and where. Further, changing the example requires only very little change in the text. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.0)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rchrismon  thanks for your comment. Unfortunately we don't have the resources to rewrite the app/doc. I hope to update it for 2.1 soon.
