### ISSUE TITLE
Put published date on articles

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#655]
Per customer comment

http://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html#comment-2360128457

**Comment by Matthew-Bonner** [comment]
The comment...
"It would be really great to have a published date on these types of articles considering it's covering beta software. I just downloaded Beta 8 and this article has a lot of differences between what it says I should see and what I'm actually seeing. But I have no way to tell what version this article was written against or when it was published."

**Comment by spboyer** [comment]
@dend @mairaw - do we have any plans to put this in?

**Comment by dend** [comment]
@spboyer is the ask about publishing date? Because we already support that.

Regarding versioning, this is currently work in progress.

**Comment by spboyer** [comment]
The documents show a date that is from the metadata which us "hardcoded" from the writers.  But is there a date displayed as to when OPS pushed to live?

**Comment by mairaw** [comment]
When the topic is updated, you need to update the ms.date value. We don't want to display the published date because all topics are published when we merge branches. That's what it was doing before and it was wrong. Unless I'm not understanding the ask.
@spboyer @dend

**Comment by spboyer** [comment]
Completely makes sense. We are putting it on the writer.  Closing the issue
