### ISSUE TITLE
Does this CDN support IPv6?

### ISSUE THREAD

**Issue by cdnjay** [aspnet/Docs#6553]
It appears that this CDN does not support IPv6. Tried to resolve against both Cloudflare and Google DNS.

**Comment by scottaddie** [comment]
@cdnjay Which CDN are you asking about?

**Comment by cdnjay** [comment]
ajax.aspnetcdn.com

**Comment by Rick-Anderson** [comment]
@cdnjay  have you seen [this](https://forums.verizon.com/t5/Fios-Internet/Unable-to-reach-ajax-aspnetcdn-com/td-p/735141/page/2)?

**Comment by cdnjay** [comment]
No, but when I do a AAAA dig for the subdomain it doesn't show an IPv6 entry and other CDN's do seem to work such as those provided by Cloudflare.

;; QUESTION SECTION:
;ajax.aspnetcdn.com.		IN	AAAA

;; ANSWER SECTION:
ajax.aspnetcdn.com.	3508	IN	CNAME	mscomajax.vo.msecnd.net.
mscomajax.vo.msecnd.net. 3509	IN	CNAME	cs22.wpc.v0cdn.net.

;; QUESTION SECTION:
;mscomajax.vo.msecnd.net.	IN	AAAA

;; ANSWER SECTION:
mscomajax.vo.msecnd.net. 3480	IN	CNAME	cs22.wpc.v0cdn.net.

;; QUESTION SECTION:
;cs22.wpc.v0cdn.net.		IN	AAAA

;; AUTHORITY SECTION:
wpc.v0cdn.net.		217	IN	SOA	ns1.v0cdn.net. noc.edgecast.com. 1524596026 3600 600 604800 600

Cloudflare:

;; QUESTION SECTION:
;cdnjs.cloudflare.com.		IN	AAAA

;; ANSWER SECTION:
cdnjs.cloudflare.com.	5	IN	AAAA	2400:cb00:2048:1::6813:c397
cdnjs.cloudflare.com.	5	IN	AAAA	2400:cb00:2048:1::6813:c497
cdnjs.cloudflare.com.	5	IN	AAAA	2400:cb00:2048:1::6813:c597
cdnjs.cloudflare.com.	5	IN	AAAA	2400:cb00:2048:1::6813:c697
cdnjs.cloudflare.com.	5	IN	AAAA	2400:cb00:2048:1::6813:c797

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/Docs/issues/5832
