### ISSUE TITLE
How do you "Create a new .NET Core project." on a Mac 

### ISSUE THREAD

**Issue by bpoker** [aspnet/Docs#6556]
There doesn't seem to be a straightforward way to do this on a Visual Studio Code on a Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2191c25-85c0-80b3-6e0e-f54aaf087150
* Version Independent ID: 5e0ec5a6-a0d1-b78f-b5cc-209f63a66c51
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started?view=aspnetcore-2.0)
* Content Source: [aspnetcore/getting-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@bpoker  can you take a look at https://docs.microsoft.com/en-us/aspnet/core/tutorials/xplat?view=aspnetcore-2.0 and try a couple of the MacOS tutorials and see if that answers you questions? If so, I might want to link to those tutorials in this article. 

Thanks for reporting this.

**Comment by Rick-Anderson** [comment]
@bpoker when I'm using VS Code, VS for macOS, or even VS on windows, I often run the commands from the command line. I use the VS version for editing.
