### ISSUE TITLE
@Url.Action("Index", "Home", new { area = "" }) doesn't work

### ISSUE THREAD

**Issue by dmitry-pavlov** [aspnet/Docs#6560]
This is related to [Generating links from an action within an area based controller to another action on a different controller and not in an area.](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)

It seems @Url.Action("Index", "Home", new { area = "" }) doesn't work. 

When I am generating link from an action within an area based controller to another action on a different controller and not in an area, I am getting "MyArea/Home/Index" instead of expected "Home/Index" 

I have posted this issue details on StackOverflow: https://stackoverflow.com/questions/50497300/how-to-get-controller-action-url-not-in-any-area-in-razor-view-in-specific-ar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jimmcslim** [comment]
I have also encountered this issue.

I attempted to use the TagHelper for <a> and it also didn't seem to work.

Worth mentioning that I am using 'feature folders', via the OdeToCode.AddFeatureFolders package.

**Comment by dmitry-pavlov** [comment]
Regarding areas I did the following additional things:

1. Configured views location in ConfigureServices 

```
            services.Configure<RazorViewEngineOptions>(options =>
            {
                options.AreaViewLocationFormats.Clear();
                options.AreaViewLocationFormats.Add("/MyArea/{2}/Views/{1}/{0}.cshtml");
                options.AreaViewLocationFormats.Add("/MyArea/{2}/Views/Shared/{0}.cshtml");
                options.AreaViewLocationFormats.Add("/Views/Shared/{0}.cshtml");
            });
```
2. Added _ViewImports.cshtml and _ViewStart.cshtml to Views folder for MyArea 

3. Configured routes - first for area, then the default one:

```
            app.UseMvc(
                routes =>
                {
                    routes.MapRoute(
                        name: "areaRoute",
                        template: "{area}/{controller}/{action=Index}/{id?}");

                    routes.MapRoute(
                        name: "default",
                        template: "{controller=Home}/{action=Index}/{id?}");
                });

```
Hope this helps.

**Comment by Rick-Anderson** [comment]
@rynowak  please review.

**Comment by rynowak** [comment]
It's definitely our guidance to put conventional routes with `{area}` first. Is there anything else you wanted me to review?

**Comment by Rick-Anderson** [comment]
@rynowak  from @dmitry-pavlov  notes above are complete. he's followed our document exactly and  getting "MyArea/Home/Index" instead of expected "Home/Index"

From our doc
![image](https://user-images.githubusercontent.com/3605364/43537272-195b5c74-957c-11e8-86e9-88d9998a55cc.png)

**Comment by rynowak** [comment]
The docs look correct to me. I'm not sure what's going on.

**Comment by Rick-Anderson** [comment]
@dmitry-pavlov  can you create the simplest possible project that reproduces the error. Post a link to the GitHub project and we'll investigate.

**Comment by dmitry-pavlov** [comment]
@Rick-Anderson @rynowak sure, I will create a sample next week. My laptop has died and I need to get a new one. In short, documentation proposes to use area:exists - it doesn't work and causes error. Also you should clearly state that folders should be configured before UseMvc call. You can create default ASP.NET Core Web Application and add area route as described in the documentation to reproduce the error. One more thing - when you add area with scaffolding it generates "route." instead of "routes." Minor issue, but also should be fixed I guess. Please let me know if the sample is still needed.

**Comment by Rick-Anderson** [comment]
@dmitry-pavlov 
> when you add area with scaffolding it generates "route." instead of "routes."

Can you open an issue for that at https://github.com/aspnet/Templating ?

> In short, documentation proposes to use area:exists - it doesn't work and causes error. 

That should be `template: "{area=Products}/{controller=Home}/{action=Index}/{id?}");`

> Please let me know if the sample is still needed.

Yes, a sample would be great.

**Comment by dmitry-pavlov** [comment]
Regarding typo in template, I have opened an issue here https://github.com/aspnet/Templating/issues/718

**Comment by dmitry-pavlov** [comment]
@Rick-Anderson  please find the sample project attached. In brief what I did:
- created new ASP.NET Core web app 
- added new Area
- added HomeController and Index view within th area.
- registered new area route in Startup.cs as described in discussed documentation article.
How to reproduce - run app - you wuill get the error. 
Once you fix the error - open this view ..\WebApp\Areas\MyNewArea\Views\Home
[WebApp.Sample.6560.zip](https://github.com/aspnet/Docs/files/2335675/WebApp.Sample.6560.zip)

**Comment by Rick-Anderson** [comment]
You're missing `[Area("MyNewArea")]`

```
[Area("MyNewArea")]
public class HomeController : Controller
```

Take a look at [What does “:exists” do on a route template?](https://stackoverflow.com/questions/44260468/what-does-exists-do-on-a-route-template)

**Comment by dmitry-pavlov** [comment]
Yep, Url.Action seems to work - at least I can't reproduce it anymore in the current version on VS2017 with .NET Core 2.1.0. 

@Rick-Anderson please feel free to close the issue. Thank you!
