### ISSUE TITLE
 .NET Core Hosting Bundle Link

### ISSUE THREAD

**Issue by AlexInAk** [aspnet/Docs#6566]
I can't find the download for the .NET Core Hosting Bundle using the link above: [.NET All Downloads page](https://www.microsoft.com/net/download/all).  I did find #1403 by searching the web, which led me to [the 2.0.7 release](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.7-download.md) which does include a link to the hosting bundle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.0&tabs=aspnetcore2x#install-the-net-core-hosting-bundle)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by AlexInAk** [comment]
Err, I meant to link to another repo. [Issue #1403](https://github.com/dotnet/core/issues/1403)

**Comment by guardrex** [comment]
It's listed as *Hosting Bundle Installer* here :point_right: https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7

See **Step b** of the instructions at :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis#install-the-net-core-hosting-bundle
