### ISSUE TITLE
new doc: What's new in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6568]
Need the 2.1 version of [What's new in ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0?view=aspnetcore-2.1)

Outline:
•	SignalR
•	Razor class libraries
•	Identity UI library & scaffolding
•	HTTPS
•	GDPR
•	MVC functional testing
•	[ApiController], ActionResult<T>
•	IHttpClientFactory
•	Kestrel on Sockets
•	Generic host builder
•	Updated SPA templates

Primary source of info for this article is published articles. After that:

* https://blogs.msdn.microsoft.com/webdev/2018/05/07/asp-net-core-2-1-0-rc1-now-available/
* https://blogs.msdn.microsoft.com/webdev/2018/04/12/asp-net-core-2-1-0-preview2-now-available/
* https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available/
* https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/

**Comment by isaac2004** [comment]
Propose to take the content from here

https://blogs.msdn.microsoft.com/webdev/2018/02/02/asp-net-core-2-1-roadmap/

If agreed, I can take this one.

**Comment by Rick-Anderson** [comment]
@isaac2004  that's a pretty good start. Can you post an outline here? I think @danroth27  will verify your outline.

**Comment by Rick-Anderson** [comment]
@danroth27  cancel the request above. @isaac2004  I put the outline at the top.
