### ISSUE TITLE
Please improve configuration documentation

### ISSUE THREAD

**Issue by BennieCopeland** [aspnet/Docs#6576]
1. Can the settings defined in "CreateDefaultBuilder" be overridden by calling individual elements like "UseKestrel(opt => {})" afterwards?
2. Document "ConfigureAppConfiguration"
3. Explain the difference between "UseConfiguration" and "ConfigureAppConfiguration" (hint: UseConfiguration doesn't support reloadOnChange)
4. Document "ConfigureLogging"
5. Document the difference between configuring the Host vs configuring the Application

There are too many ways to configure, but are undocumented. See:
https://github.com/aspnet/Hosting/issues/1430
https://github.com/aspnet/Hosting/issues/1148

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1&tabs=aspnetcore2x#override-configuration)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @BennieCopeland for opening this issue. Let me get back to you in a day or two. We have 2.1 coming out around May 30, and you can guess what that's like. 😅🏃🏃🏃🏃🏃🏃

**Comment by guardrex** [comment]
**You're *GO* for throttle up.** :rocket:

Let's use this issue to track the work. There will be a small PR to address the hosting topic, and the bulk of the work will be on the Configuration topic. I'll float an outline and questions for discussion here.
