### ISSUE TITLE
C19382: <script> tags in code should be removed 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#6578]
See https://github.com/aspnet/Docs/pull/6574
PR #6574

**Comment by christinethewitc** [comment]
I want to be removed totally from Github

Den tor. 24. mai 2018, 19:38 skrev Rick Anderson <notifications@github.com>:

**Comment by guardrex** [comment]
I'll code-fence them for now, which should fix the localization issue until I can get to this topic for re-write.
