### ISSUE TITLE
Update Get Started node for 2.1 release

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#6583]
Currently the [ASP.NET Core Get Started page for 2.1 RC1](https://docs.microsoft.com/en-us/aspnet/core/getting-started?view=aspnetcore-2.1) says to install ".NET Core SDK 2.0". We need to make sure this page (and any other places we have install steps or list prereqs) is updated for the 2.1 release.

`edit by` @rick-anderson 
See related #5716

**Comment by Rick-Anderson** [comment]
@danroth27  @scottaddie  OK to update this to 2.1 only? Do you want to keep the 2.0 version?

**Comment by danroth27** [comment]
For 2.1 we should point to: https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300

For 2.0 we should point to: https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.200

**Comment by danroth27** [comment]
Pretty soon we should unify the ASP.NET Core docs get started page with https://www.microsoft.com/net/learn/apps/web/get-started/windows. @rowanmiller is driving that effort.

**Comment by Rick-Anderson** [comment]
@guardrex  #6694 fixed this right?

**Comment by rowanmiller** [comment]
Do we need to have a Get Started page for past versions? I'm fine either way, but it seems like almost everyone going thru the Get Started flow would want to be on Current. 

As part of upcoming website changes, the Get Started on www.asp.net (https://www.asp.net/get-started) and the Get Started on the .NET Website (https://www.microsoft.com/net/learn/apps/web/get-started) will merge into the same thing. Agreed we should work out how to rationalize between website and docs too.

**Comment by Rick-Anderson** [comment]
>  it seems like almost everyone going thru the Get Started flow would want to be on Current.

Since 2.0 shipped, we've only had 2.0 and not 1.1 and we had ZERO complaints.

**Comment by rowanmiller** [comment]
Having one version also avoids issues where the older version out-ranks the current version in search results.

**Comment by Rick-Anderson** [comment]
With the 2.1 .NET SDK, you'll need to run:
`dotnet dev-certs https --trust`

See the instructions [here](https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-https-improvements/)

**Comment by guardrex** [comment]
@Rick-Anderson Sorry ... just got dug out from a pile of samples to see your question. No, the only thing addressed by #6694 was going from `dotnet new razor` to `dotnet new webapp` with moniker-ranges for 2.0 vs. 2.1 (thx @scottaddie for calling that out). I put in a post fix with https://github.com/aspnet/Docs/pull/6712 to update three of them where the moniker-ranges weren't necessary (one was nested :boom: and two were already 2.1-only topics).
