### ISSUE TITLE
X.509 security certificate prerequisite is never used?

### ISSUE THREAD

**Issue by bitdozer** [aspnet/Docs#6584]
"X.509 security certificate" is listed under prerequisite, but I don't see it mentioned in any of the later steps.  What was the reason for including this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@bitdozer  great question. I was just wondering that myself. @scottaddie  / @guardrex  do you know why that's listed? Can I remove it?

**Comment by guardrex** [comment]
It was added to cover [IIS dev scenario \#6415](https://github.com/aspnet/Docs/pull/6415), and this topic became caught up in that update. I'll refactor the IIS dev topic to have its own prereq section and not use the include. Thanks @bitdozer for letting us know.

**Comment by scottaddie** [comment]
@Rick-Anderson Looks to me like that include file was modified for the *development-time-iis-support.md* file (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.0). This doc does require a certificate.

**Comment by bitdozer** [comment]
My use case is I want to recommend this tutorial to some beginning .NET developers and needed to understand how to support/justify that pre-req.  I see the need in the IIS setup article, but agree it makes more sense as a local rather than global pre-req.  Thanks for considering this change.

**Comment by Rick-Anderson** [comment]
>  This doc does require a certificate.

And it requires a bunch of other under the hood stuff too. This is a VS tutorial and that's done for you automatically. Let's remove it.

**Comment by guardrex** [comment]
https://github.com/aspnet/Docs/pull/6585
