### ISSUE TITLE
Signalr.js file version confusion

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#6593]
@anurse @davidfowl Hey guys, it seems that a LOT of folks keep mismatching the SignalR server version with the client, and can't determine what the client version is that they're getting from npm. Is there any consideration for adding a version to the js file or noting it on the npm site, or something to help assuage the confusion?

**Comment by anurse** [comment]
Yep, we did this in RTM: https://github.com/aspnet/SignalR/issues/2130

Also, this confusion will be dramatically reduced after RTM because we'll have a stronger compatibility guarantee.

**Comment by rachelappel** [comment]
@anurse Yay!
