### ISSUE TITLE
Update kerstrel.md with changes in sample code's Program.cs

### ISSUE THREAD

**Issue by alfredmyers** [aspnet/Docs#6594]
https://github.com/aspnet/Docs/edit/master/aspnetcore/fundamentals/servers/kestrel.md#L436 was not updated after the sample it points to was removed in https://github.com/aspnet/Docs/commit/7c5772323fa7233c47275b59b677ebd59dd9d01b#diff-7655a566fdd31555e67645a072c511e5L28

Not sure if the section on the docs should be removed as well, or if the code that was removed should be put back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks for reporting @alfredmyers ... I'll get it patched.
