### ISSUE TITLE
Boilerplate for Testcases

### ISSUE THREAD

**Issue by caype** [aspnet/Docs#6596]
This template is missing some basic test cases for React components and Redux stores!
It would be nice if some tests are included with the frameworks configs setup in the template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c515542e-b3c6-6959-4104-20cee182b976
* Version Independent ID: ed86072e-40a6-67b5-81f7-144c5063772c
* Content: [Use the React-with-Redux project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/react-with-redux?view=aspnetcore-2.0)
* Content Source: [aspnetcore/spa/react-with-redux.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/react-with-redux.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/templating/issues/537.
