### ISSUE TITLE
Click Tracking

### ISSUE THREAD

**Issue by molund** [aspnet/Docs#6598]
Since this is being used for password resets, you will probably want to disable click tracking.  Otherwise your password reset links are being handled by Sendgrid.  Use msg.TrackingSettings to disable the ClickTracking

         public Task Execute(string apiKey, string subject, string message, string email)
        {
            var client = new SendGridClient(apiKey);
            var msg = new SendGridMessage()
            {
                From = new EmailAddress("michaelo@openroad.ca", "Mike Olund"),
                Subject = subject,
                PlainTextContent = message,
                HtmlContent = message
            };
            msg.AddTo(new EmailAddress(email));

            msg.TrackingSettings = new TrackingSettings
            {
                ClickTracking = new ClickTracking {Enable = false}
            };

            return client.SendEmailAsync(msg);
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@molund  great suggestion. Hopefully we can get this added to the next update.

**Comment by Rick-Anderson** [comment]
@HaoK  should we disable click tracking?
@molund  do you have a link to click tracking?

**Comment by HaoK** [comment]
Seems reasonable, @blowdart thoughts?

**Comment by blowdart** [comment]
Yup

**Comment by Rick-Anderson** [comment]
@molund  are you https://twitter.com/olund ? This issue is worth a tweet.

**Comment by molund** [comment]
Yes, that’s me.

Sent from my iPhone

On Jul 13, 2018, at 3:44 PM, Rick Anderson <notifications@github.com> wrote:

@molund <https://github.com/molund> are you https://twitter.com/olund ?
This issue is worth a tweet.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aspnet/Docs/issues/6598#issuecomment-404971805>, or mute
the thread
