### ISSUE TITLE
Hosting Bundle Installer? 

### ISSUE THREAD

**Issue by brockallen** [aspnet/Docs#6600]
> On the .NET Core runtime download page under Windows, select the Hosting Bundle Installer link to download the .NET Core Hosting Bundle.

Does this even exist anymore? I don't seem to see it where it says it should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.0&tabs=aspnetcore2x#install-the-net-core-hosting-bundle)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @GuardRex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes ... it's there.

https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7

... under **Windows**.

**Comment by guardrex** [comment]
Those download pages are under a redesign right now and being tracked by an internal issue. There's nothing actionable for the docs yet, so I'll close for now. @brockallen, we can re-open this issue if you'd like to discuss this further.
