### ISSUE TITLE
Better Examples Needed

### ISSUE THREAD

**Issue by tony-long** [aspnet/Docs#6609]
I wish someone would create better examples of file upload for specific use cases like photos for display,  file upload for backups,  file uploads for transfer to another storage server,  uploading files related to a database record (case/project), things that people can take and add into their own apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @tony-long for commenting. We have an open issue to overhaul the topic (and the examples). The work is being tracked on https://github.com/aspnet/Docs/issues/5331.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
