### ISSUE TITLE
Upload Example Fails to Build

### ISSUE THREAD

**Issue by tony-long** [aspnet/Docs#6610]
This two lines had to be commented out to build and run.  In file : DisableFormValueModelBindingAttribute.cs

            var factories = context.ValueProviderFactories;
            //factories.RemoveType<FormValueProviderFactory>();
            //factories.RemoveType<JQueryFormValueProviderFactory>();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Same on this issue: We have an open issue to overhaul the topic (and the examples). The work is being tracked on https://github.com/aspnet/Docs/issues/5331. 

Let's leave this issue open, and it will close when the PR merges.
