### ISSUE TITLE
SignalR full docs availability on MS Docs???

### ISSUE THREAD

**Issue by BenHayat** [aspnet/Docs#6613]
Hello SignalR Doc team;

When will you release full docs on SignalR Core 2.1 docs? Will they show up at 2.1 RTM?
Based on the intro video at Build, there are tons of new (an more complex) in the new Core version that is beyond the old docs on SignalR.

Thanks!
..Ben

**Comment by Rick-Anderson** [comment]
We're working on them.

**Comment by BenHayat** [comment]
Thank you Sir!

**Comment by Rick-Anderson** [comment]
We can keep this open. I'll see if @rachelappel  and the SignalR folks can at least let you know what's next.

**Comment by BenHayat** [comment]
That would be great Rick!

**Comment by rachelappel** [comment]
Some upcoming docs:
-Configuration
-Messagepack
-Connection lifetimes and reconnection inf
-Groups
-Security
-TypeScript integration
-Migration from .NET

**Comment by BenHayat** [comment]
Excellent Rachel;
When do you think these will take place?

Thanks!

**Comment by rachelappel** [comment]
They're in process now, and some have been merged and will be published soon.

**Comment by BenHayat** [comment]
Thank you!!!
