### ISSUE TITLE
Controller information missing

### ISSUE THREAD

**Issue by jwdavidson** [aspnet/Docs#6615]
The instructions for configuring error handling do not say which controller the error handler should be in (Section https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.0#configuring-a-custom-exception-handling-page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e03fdf4-b19b-17c3-04f4-336ab6d2ee06
* Version Independent ID: 38515dfb-91a5-b395-db9d-084bbaf095c8
* Content: [Handle errors in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.0)
* Content Source: [aspnetcore/fundamentals/error-handling.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/error-handling.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Great idea @jwdavidson! For MVC, we should call out the `HomeController`. For Razor Pages, we should call out the Error page.
