### ISSUE TITLE
Custom model binding does not bind two models

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#6618]
[Walking through](https://stackoverflow.com/questions/50507379/why-does-this-string-not-get-bound-to-a-filename-parameter-in-asp-net-core-api) the custom [model binder tutorial](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1#feedback), the image of Postman erroneously indicates that two separate primitive type models are bound by the action from the body. However, for some reason, I was not able to coerce the app to accept two primitives, one from the header or query, and the base64 string from the body regardless of whether I used a json primitive or `{file:"long String"}` ("Start Object" error), or string `"longstring"` even when using the [FromBody] attribute. It works to use a non body source(header/query) as long as the body is a complex type but I haven't been able to use a primitive from the body with another source bound in the same action method. The tutorial needs to be updated to show a working method.

**Comment by user135711** [comment]
@Rick-Anderson I must be be doing something wrong, because the API template does have a string, which is similar to a byte[]. I don't why the ByteArrayModelBinderProvider is not binding the body though...

**Comment by Rick-Anderson** [comment]
Thanks for the update. Let us know if you figure it out.
