### ISSUE TITLE
At the step "Add scaffold tuning and perform initial migration", I went to Tools->NuGetPackageManager->Package Manger Console and inserted: "InstallPackage.Microsoft.Visual Studio.....as specified.   Result from PM> : Add-Migration Initial build failed PM>Update-DataBAse.  Please come to my rescue

### ISSUE THREAD

**Issue by csebel** [aspnet/Docs#6621]
Great application. Need more of the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@csebel you can get that error for many reasons. Review the steps to see if you can find what you missed.

**Comment by csebel** [comment]
Okee Dokee. I'll do that and provide result. Thanks.
