### ISSUE TITLE
Server management with Windows Tasks

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6623]
@pakrym @Tratcher WRT ...

https://twitter.com/pakrym/status/996424063466668032

A few options:

* New topic in either the *fundamentals/servers* or *host-and-deploy* area and linked from the [fundamentals/servers/index topic Server startup section](https://docs.microsoft.com/aspnet/core/fundamentals/servers#server-startup): Surface using a task and setting the priority using either or both of ...
   - For Windows Task Scheduler: Manually set the priority in an exported/imported task.
   - For a task created with PowerShell: Use the `-Priority` switch.
* New section in [fundamentals/servers/index topic Server startup section](https://docs.microsoft.com/aspnet/core/fundamentals/servers#server-startup): Mention task scheduling and highlight the default (low) priority but don't show how to use Windows Task Scheduler or PS to set up a task with a given priority.
* Continue to not discuss tasks in the docs.

If we surface anything that speaks to setting the priority, we probably need to broach the subject of *what priority is recommended*, which might get thorny (i.e., environment-specific or app-specific conditions may apply).

For Windows Services, I read that Service Control Manager doesn't offer a way to control the priority. Perhaps, the user would need to set it directly using Task Manager (or a 3rd party tool). Any info on this should go in the [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service) topic.

**Comment by Rick-Anderson** [comment]
@guardrex  I'm guessing that's not a common scenario and all we need to do is mention it in a doc.

**Comment by guardrex** [comment]
I assume that with good services support these days and docs that we'll steer clear of describing the use of Windows Tasks. We'll apparently also avoid speaking to Windows Service priority management. Re-open if we need to discuss further.
