### ISSUE TITLE
Is there a difference in configuring in `services.Configure` or `services.AddIdentity`

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#6624]
In this topic the 2.x version configures everything on the options parameter of `services.Configure<IdentityOptions>(options =>,` however the 2.x version in Introduction to Identity uses the options parameter of `services.AddIdentity<ApplicationUser, IdentityRole>(options =>` which I suspect is the convention going forward. Does this need to be updated? Is there a reason to use one vs the other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.0&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@user135711  For ASP.NET Core 2.1, this is what the templates generate:
`services.AddDefaultIdentity<IdentityUser>()`

You're right, both topics need to be updated for 2.0 and 2.1.

**Comment by user135711** [comment]
@Rick-Anderson For clarification I'm talking about the options passed into the arrow method, not the generic parameters. There are two versions where the long list of settings are made like
  options.Password.RequireDigit = true;
        options.Lockout.AllowedForNewUsers = true;
(basically everything except for cookies which moved to `services.ConfigureApplicationCookie(`) 
In one version, everything happens in `services.Configure<IdentityOptions>(options =>` and in another option settings are set in `services.AddIdentity<ApplicationUser, IdentityRole>(options =>`. If one is on track to be deprecated, it needs to be documented.
