### ISSUE TITLE
Accepting Multiple Parameters from Get

### ISSUE THREAD

**Issue by rswetnam** [aspnet/Docs#6628]
I am trying to build an .Net Core API that will allow me to accept:

`https://localhost:44329/api/scoInfo?activityId=1&studentId=1&timestamp=1527357844844`

I have tried about a thousand variations on the following but cannot get it to work:

` [HttpGet("{activityId}/{studentId}/{timestamp}")]
        [Route("api/scoInfo/")]
        public async Task<IActionResult> GetLearningTask([FromRoute]int activityId, [FromRoute]int studentId, [FromRoute]int timeStamp)`

The following seems to work in .NET Framework 4.6.1

` [HttpGet]
        public async Task<HttpResponseMessage> Get(int activityId, int studentId, long timeStamp)
        {`

Any suggestions greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the question. You'll probably get a response much faster if you post that to a forum like StackOverflow.

**Comment by AdrianAbela** [comment]
`[HttpGet]
public async Task<HttpResponseMessage>Get([FromQuery] int activityId, [FromQuery]int studentId)`
