### ISSUE TITLE
Complete details page of getting started with MVC

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#663]

**Comment by danroth27** [comment]
@Rick-Anderson What is this tracking? Can this issue just be closed now?

**Comment by BenjaminLange** [comment]
This issue is tracking the completion of this page: http://docs.asp.net/projects/mvc/en/latest/getting-started/first-mvc-app/details.html

It is the last page of the tutorial called Building your first MVC 6 application.

Please reopen this issue so that the tutorial will get completed.

**Comment by Rick-Anderson** [comment]
I plan on completing that stage for [RC2](https://github.com/aspnet/Home/wiki/Roadmap).

**Comment by danroth27** [comment]
Looks like this is now done: https://docs.asp.net/en/latest/tutorials/first-mvc-app/details.html

**Comment by danroth27** [comment]
Looks like this is now done: https://docs.asp.net/en/latest/tutorials/first-mvc-app/details.html
