### ISSUE TITLE
Good work!

### ISSUE THREAD

**Issue by mavortius** [aspnet/Docs#6630]
Thanks for the excellent work!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.0&tabs=netcore-cli%2Cvisual-studio-code-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks for the feedback @mavortius! :+1: :smile:
