### ISSUE TITLE
Reusable UI class library for ViewComponents?

### ISSUE THREAD

**Issue by tekguy** [aspnet/Docs#6633]
Hello,

Is it possible to create a reusable class library for ViewComponents, similar to what was done recently for Razor Pages? (https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm - Is it possible to create a reusable class library for ViewComponents ?

**Comment by Rick-Anderson** [comment]
@pranavkm - Is it possible to create a reusable class library for ViewComponents ?

**Comment by Rick-Anderson** [comment]
@tekguy I'm pretty sure the answer is no.

**Comment by pranavkm** [comment]
> Is it possible to create a reusable class library for ViewComponents ?

Yeah, that should be fine. Mvc discovers view components from all registered application parts and ViewComponent views should compile along with other views in the project just fine.

**Comment by artyprog** [comment]
Hello it's perfectly possible look here  [https://github.com/ianbusko/reusable-components-library](https://github.com/ianbusko/reusable-components-library)

**Comment by artyprog** [comment]
I have adapted the extension method to make independant from a paticuliar Component

namespace ComponentLibrary
{
    public static class ServiceExtension
    {
        // Méthode d'extension permettant à l'application cliente
        // de rechercher les pages Razor dans la DLL 
        public static void AddComponentLibraryRazorPages(this IServiceCollection service, Assembly componentLibrary)
        {
            service.Configure<RazorViewEngineOptions>(options =>
            {
                options.FileProviders
                       .Add(new EmbeddedFileProvider(componentLibrary));
            });
        }

        public static void AddComponentLibraryScripts(this IApplicationBuilder builder, Assembly componentLibrary)
        {
            var embeddedProvider = new EmbeddedFileProvider(componentLibrary, "ComponentLibrary.Scripts");

            builder.UseStaticFiles(new StaticFileOptions()
            {
                FileProvider = embeddedProvider,
                RequestPath = new PathString("/Scripts")
            });
        }
    }
}

And here is the stratups.cs file from the main application

namespace ComponentLibraryUI
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // N'importe quel type contenu dans la DLL peut convenie ie:NavComponent
        // Ce qui nous intéresse ici c'est de recueillir les infos sur la DLL
        public Assembly ComponentLibrary = typeof(ServiceExtension).Assembly;

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });


            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
         
            // Permet l'accés aux pages Razor contenu dans la DLL ComponentLibrary
            services.AddComponentLibraryRazorPages(ComponentLibrary);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            // Ajouts des script JS contenus dans DLL ComponentLibrary
            app.AddComponentLibraryScripts(ComponentLibrary);

            app.UseCookiePolicy();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
