### ISSUE TITLE
Possible issue with the editor template example.

### ISSUE THREAD

**Issue by hallzhallz** [aspnet/Docs#6634]
The line on collections 'The Views/Shared/EditorTemplates/ToDoItem.cshtml template' uses tag helpers 'asp-for' but the github issue https://github.com/aspnet/Mvc/issues/399 states that you can't use them in EditorTemplates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hallzhallz  I remember reading an issue like that, but it's not the issue you list.
