### ISSUE TITLE
HtmlEncoder, JavaScriptEncoder and UrlEncoder injection

### ISSUE THREAD

**Issue by defilerc** [aspnet/Docs#6636]
Hi! Having worked with Autofac before, I was wondering where are these services (HtmlEncoder, JavaScriptEncoder, UrlEncoder) registered? Is there a pre-defined set of "services" that are already registered and can be injected into controllers, besides the above? If I could guess, I would think the `services.AddMvc()` extension method, inside `ConfigureServices()`. If so, is there a list of all the available services available out of the box?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.0)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.0#accessing-encoders-in-code

I don't know of a list of all available services.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
