### ISSUE TITLE
ASP.NET Core 2.0 examples for DataProtection using obsolete methods

### ISSUE THREAD

**Issue by rfcdejong** [aspnet/Docs#6639]
Cookie sharing topic
https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.0&tabs=aspnetcore2x

is using Obsolete extension method "app.UseCookieAuthentication"

https://go.microsoft.com/fwlink/?linkid=845470

**Comment by guardrex** [comment]
ping @HaoK 

TL;DR ... `UseCookieAuthentication` with Katana cookie authentication middleware isn't obsolete for netfx 4.6.1 (non-Core), right? Are the API comments just saying that because API comments can't be set up by-framework?

**Comment by HaoK** [comment]
Yeah nothing has changed for Katana, but for core UseAuthentication is obsolete
