### ISSUE TITLE
Issues while migrating from ASP.Net MVC to ASP.Net Core 2.1

### ISSUE THREAD

**Issue by joyalsttl** [aspnet/Docs#6641]
Hello Team,

I found below issues while migrating from ASP.Net MVC to ASP.Net Core 2.1.

1. Request.Form.GetValues is not supported. 
2. JsonRequestBehavior.AllowGet is not working
3. ViewEngines.Engines.FindView is missing
4. Session object is not working in the controller. I have added namespace named "using Microsoft.AspNetCore.Session;". But, still Session is not working.

Please let me know how the above points can be achieved in ASP.Net Core 2.1.

Thanks.

Regards,
Joyal

**Comment by joyalsttl** [comment]
Fore Session,  I found a good article for Session. So, Please ignore my question on session.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.0&tabs=aspnetcore2x

**Comment by joyalsttl** [comment]
One more thing is "AuthorizeAttribute". The "AuthorizeAttribute" is not working in asp.net core.

I already have a method named "OnAuthorization". But, it cannot be override in ASP.Net Core....

public override void OnAuthorization(AuthorizationContext filterContext)

**Comment by Rick-Anderson** [comment]
@joyalsttl See [Migration to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/?view=aspnetcore-2.1)

I'll have a new document there tomorrow on migrating from 2.0 to 2.1

If you're having problems migrating, you'll get alot quicker response from StackOverflow than here.

**Comment by davidfowl** [comment]
> Request.Form.GetValues is not supported.

`Request.Form[key]` gives you a `StringValues` instance that you can use to do similar things (loop over all values or treat like a single string).

> JsonRequestBehavior.AllowGet is not working

I believe that feature is gone in ASP.NET Core Mvc (/cc @rynowak )

> ViewEngines.Engines.FindView is missing

Did you implement a custom view engine or are you doing something else (like email templates?)

> One more thing is "AuthorizeAttribute". The "AuthorizeAttribute" is not working in asp.net core.

This is the new approach https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.0

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
