### ISSUE TITLE
Access config settings in a Controller

### ISSUE THREAD

**Issue by rustd** [aspnet/Docs#665]
We need to update this doc which shows how to access the appsettings in a Controller.
https://docs.asp.net/en/latest/fundamentals/configuration.html
This would involve adding Configuration to DI and accessing it from the Controller

**Comment by ardalis** [comment]
We're not putting MVC-specific details into those docs, typically. I'm working on a DI for Controllers article now and can be sure to cover access to configuration/IOptions in that article, and then we can link to it from the /fundamentals/configuration article. /cc @danroth27

**Comment by rustd** [comment]
sounds good. Thanks!

**Comment by danroth27** [comment]
:+1: to what @ardalis said.

**Comment by danroth27** [comment]
https://github.com/aspnet/docs/pulls/728

**Comment by ardalis** [comment]
#728 shipped. Closing this.
