### ISSUE TITLE
not found .netcore module download page.

### ISSUE THREAD

**Issue by jackcaicn** [aspnet/Docs#6652]
follow the description of "Install the .NET Core Hosting Bundle", but not found the download page URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @GuardRex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jackcaicn ... You need to select the runtime to get the Hosting Bundle Installer. It's on this page: https://www.microsoft.com/net/download/dotnet-core/runtime-2.0.7

Note that 2.1 will release this week in a few days. There will be a new installer when 2.1 comes out.

Also note that the download pages are under a redesign, so they will change at some point.
