### ISSUE TITLE
Safe to use HtmlHelper.Raw on HTML that is encoded?

### ISSUE THREAD

**Issue by bhlee90** [aspnet/Docs#6653]
Is it safe to use HtmlHelper.Raw on HTML that is encoded? Does simply encoding the HTML that HtmlHelper.Raw displays prevent XSS attacks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.0)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Before putting untrusted data inside an HTML element ensure it's HTML encoded. HTML encoding takes characters such as < and changes them into a safe form like &lt;

**Comment by Rick-Anderson** [comment]
@bhlee90 does that answer your question?
