### ISSUE TITLE
ASP.NET Core SignalR API docs out of date

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Docs#6654]
The API docs for ASP.NET Core SignalR on docs.microsoft.com are out of date.

The methods here were in preview2 but removed in RC1: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.hubconnectionbuilderhttpextensions?view=aspnetcore-2.1

**Comment by Rick-Anderson** [comment]
@danroth27  do you have an ETA on this? Getting more issues - see https://github.com/aspnet/SignalR/issues/2454

**Comment by anurse** [comment]
Another ping: https://github.com/aspnet/SignalR/issues/2462

**Comment by MaxxDelusional** [comment]
Were these logging extensions also removed in 1.0?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.signalr.client.ihubconnectionbuilder?view=aspnetcore-2.1

The only extension we have for logging is `ConfigureLogging()` but it's unclear how it works.

**Comment by BrennanConroy** [comment]
Yes, those are also gone
See:
https://github.com/aspnet/SignalR/blob/3345b6c3088e4e8992ba37cec9a19b1fcd80837e/samples/ClientSample/HubSample.cs#L34-L38

**Comment by anurse** [comment]
`ConfigureLogging` works the same way as on the server: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#how-to-add-providers

**Comment by MaxxDelusional** [comment]
I still don't know what I am missing. I don't have the AddConsole extension method.

![logging 2](https://user-images.githubusercontent.com/6978726/41424290-989b9124-6fcb-11e8-9dfa-954c12e24927.PNG)

![logging 1](https://user-images.githubusercontent.com/6978726/41424292-9af9a424-6fcb-11e8-84b6-e7fd4c730ab0.PNG)

**Comment by BrennanConroy** [comment]
You need to add a reference to https://www.nuget.org/packages/Microsoft.Extensions.Logging.Console/

**Comment by anurse** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x#built-in-logging-providers for a list of logging providers. Note that "built-in" refers to the fact that on the server (when you reference `Microsoft.AspNetCore.App`) they are automatically referenced. In client applications, you have to reference the provider packages directly (the package IDs are listed in the doc)

**Comment by MaxxDelusional** [comment]
Ah, thank you. I didn't realize that I had to manually add the references in client apps. It's working for me now.

**Comment by dend** [comment]
In terms of documentation, we are updating that right now. Stay tuned!

**Comment by Rick-Anderson** [comment]
@dend  can I close this now?

**Comment by dend** [comment]
@Rick-Anderson yes, as long as you can validate that the expected documentation is being rendered ☺

**Comment by scottaddie** [comment]
We should confirm with @Eilon that this was completed. @Eilon, any updates?

**Comment by anurse** [comment]
I can confirm that the APIs are correct.
