### ISSUE TITLE
Error when scaffolding: Version for package `Microsoft.VisualStudio.Web.CodeGeneration.Tools` could not be resolved

### ISSUE THREAD

**Issue by FraukeN** [aspnet/Docs#6658]
After some research, I managed to resolve this issue by running 'dotnet restore' before 'dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries'.

Is this a missing step in this document?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by cclark440** [comment]
I had this same issue and, resolved it the same way.

**Comment by Rick-Anderson** [comment]
@FraukeN @cclark440 restore should be implicit, but I added that step given it never hurts. Thanks for the feedback.

**Comment by bolorundurowb** [comment]
I had to run `dotnet tool install --global dotnet-ef` before I could get this to run successfully
