### ISSUE TITLE
Add packages or dependencies using NuGet

### ISSUE THREAD

**Issue by rustd** [aspnet/Docs#666]
https://docs.asp.net/en/latest/dnx/projects.html#adding-dependencies 
Add a section on using NuGet UI

**Comment by danroth27** [comment]
All the DNX docs are going away now that we are moving to .NET CLI.

**Comment by rhires** [comment]
I'm sorry to see the name of the commands of dnx and dnu going away - even if they are a bit confusing as to which to use when. They have coolness and cachet. Hopefully whatever new commands you guys and gals and the community comes up with will retain some of that. Cheers!

**Comment by danroth27** [comment]
You can check out the new stuff in progress at https://github.com/dotnet/cli.
