### ISSUE TITLE
Without Identity is it possible to use Google as an information provider but not actually authenticate for [Authorize] purposes?

### ISSUE THREAD

**Issue by klick-barakgall** [aspnet/Docs#6662]
I forget where but someone had suggested a workflow where essentially Google signs in as usual but instead of writing a user cookie we mine the information we need and drop that in a new Forms-auth style cookie.

I am NOT using Identity for this project. We have Google auth working but we need to do another level of authentication once Google is done. So we'd like to grab the information we need from the google ticket and suppress the cookie, then drive the user to another page to complete authentication.

Is this possible? I have tried a bunch of things nothing seems to work. At this point I am considering making my own AuthenticationBuilder. Could use some guidance..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @klick-barakgall ... You might get feedback here, but your question probably would get answered a lot faster on SO.

**Comment by klick-barakgall** [comment]
Fair enough. Thanks @guardrex I'll try over there.

**Comment by Rick-Anderson** [comment]
@klick-barakgall  if you get a good answer, please post the link here.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
