### ISSUE TITLE
SelectList class is unrecognized

### ISSUE THREAD

**Issue by BrittanyDilts** [aspnet/Docs#6664]
I had to add "using System.Web.Mvc;" 
AND I had to run "Install-Package Microsoft.AspNet.Mvc" in the Package Manager Console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by BrittanyDilts** [comment]
Further: this bit 
// Requires using Microsoft.AspNetCore.Mvc.Rendering;
Should be higher up in the tutorial.

**Comment by sidewinder040** [comment]
Yes - same here. Used 'Quick Action' to fix this.

**Comment by BrittanyDilts** [comment]
Just realized mine isn't very clear. The first comment was because I fixed that before moving on in the tutorial. After I moved on, I added the "using" statement that's commented out and it fixed the first problem. If you moved the comment about the using statement to above the first instance of "SelectList" it would be fixed.

**Comment by wcswanson** [comment]
Thanks to Brittany, I was able to find that 
using Microsoft.AspNetCore.Mvc.Rendering;
was missing. Now SelectList is recognized.

**Comment by Rick-Anderson** [comment]
That's all included in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app
