### ISSUE TITLE
The located assembly's manifest definition does n ot match the assembly reference

### ISSUE THREAD

**Issue by arcotek-ltd** [aspnet/Docs#6669]
At the step `dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries`, I get the following error:
```
D:\Users\John\Source\Repos\RazorPageMovie\RazorPageMovie>dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages\Movies --referenceScriptLibraries
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:10.63
```

```
C:\>dotnet --version
2.1.4
```

I've closed VS and made sure I am in the correct directory.

The only other thing could be to do with Microsoft.VisualStudio.Web.CodeGeneration.Design version. I left off the version and let it install the latest which is:

```
PM> Get-Package Microsoft.VisualStudio.Web.CodeGeneration.Design

Id                                  Versions                                 ProjectName                                                                                                                                                                                
--                                  --------                                 -----------                                                                                                                                                                                
Microsoft.VisualStudio.Web.CodeG... {2.1.0}                                  RazorPageMovie
```

Any ideas as to what is wrong?

T, A

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by nospoon4u** [comment]
I've run into the same issue, and dotnet restore did not resolve it.

**Comment by Rick-Anderson** [comment]
@nospoon4u  try the 2.1 version, it's much easier to follow.

**Comment by jtshannon** [comment]
@Rick-Anderson I get that error in the 2.1 version also. https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1

**Comment by HPringles** [comment]
I also get this issue, following.

**Comment by Rick-Anderson** [comment]
@jtshannon  @HPringles  you're getting `Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0` ?
Is that with the command line or VS?  Try with VS. Is VS up to date? What does `dotnet --version` report?

**Comment by zackshine** [comment]
I also met the same problem using vsCode. And `dotnet -- version ` is 2.1.4.

**Comment by Rick-Anderson** [comment]
@zackshine @HPringles @jtshannon  you need to update the .NET Core SDK. It needs to be `2.1.300` or higher.

**Comment by HPringles** [comment]
Where do I get that from?

**Comment by HPringles** [comment]
@Rick-Anderson So I managed to make it work. I had to manually edit the .csproj file to give ...CodeGeneration.Design version 2.0.0 instead of 2.1.0(or whatever it was before) that made it work - also updated the SDK.

My Full CSProj file is as follows : 

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Pages\Movies\" />
  </ItemGroup>
</Project>
```

**Comment by Rick-Anderson** [comment]
Can you use 2.1? Use M.A.App, not M.A.All
It's much simpler with 2.1

**Comment by doanbui-agilityio** [comment]
at ContosoUniversity.csproj file
change 
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="2.1.0" />
to
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="2.0.0" />

It worked for me.

**Comment by rog0rr** [comment]
For those following 2.1, the solution is actually created at 2.0 so my problem was the project target framework at 2.0, which was preventing Nuget from updating Microsoft.AspNetCore.All to 2.1

Change your target framework to 2.1 and then make sure you update Nuget package for Microsoft.AspNetCore.All
