### ISSUE TITLE
 page not found after the microsoft authentication tries to forward token to that url

### ISSUE THREAD

**Issue by michalhainc** [aspnet/Docs#6675]
You said: The Microsoft authentication scheme configured later in this tutorial will automatically handle requests at /signin-microsoft route to implement the OAuth flow. 

The /signin-microsoft is not handled automatically for me, I am getting a page not found after the microsoft authentication tries to forward token to that url 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.0&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@michalhainc  can you try it with the 2.1 templates? You can get that error for a variety of reasons so there's no way I could tell you what you've done incorrectly.

**Comment by michalhainc** [comment]
Hi @Rick-Anderson,
I'm sorry, It my was stupid mistake, I was missing UseAuthentication() call in Startup.cs, now when /signin-microsoft processes the authentication result, it retrieves this error message from the result: "{"error":"unauthorized_client","error_description":"AADSTS70001: Application with identifier '000000004C225DD9' was not found in the directory 9188040d-6c67-4c5b-b112-36a304b66dad\r\nTrace ID: 1c934dc0-2ea0-4edf-b650-285447173100\r\nCorrelation ID: 9f9835c3-0d01-4423-aa39-7483144ee9c2\r\nTimestamp: 2018-05-30 20:25:17Z","error_codes":[70001],"timestamp":"2018-05-30 20:25:17Z","trace_id":"1c934dc0-2ea0-4edf-b650-285447173100","correlation_id":"9f9835c3-0d01-4423-aa39-7483144ee9c2"};"

I have the feeling from the message that my live account "michalhainc@gmail.com" is linked to my employer company tennant and the oauth app is not enabled for this company account? Can this be the cause? 

Google oauth authentication from nuget Microsoft.AspNetCore.Authentication.Google works flawlessly within the very same csproj. 

Thanks for any ideas.

**Comment by michalhainc** [comment]
Hi, If it would help somebody, I had registered "Live SDK app" instead of "Converged app" in Microsoft app registration website. When I switched to a Convergent app, everything started running smoothly.
