### ISSUE TITLE
Movie or Movies?

### ISSUE THREAD

**Issue by jurva** [aspnet/Docs#6676]
Your screenshot shows "Movie/C..." but you ask to append "/Movies". Well, I guess it should be "Movies". My real problem is that after fiddling with the configuration (tried to add support for fi-FI because the decimal numbers are not accepted – please add example code to handle this) I cannot get to the movies database list any more. I even rolled back all changes but no help, it always goes to the "Home" page, as if I had not appended the "/Movies" suffix. It is also very unclear to me what steps need to be taken if anything is changed in the project. Do I have to run dotnet commands? Every time? Only if xxx is updated or what? I have tried both the "restore" and the "aspnet-codegenerator" commands but it doesn't help. Oh, I wish these "getting started" tutorials were good enough to work on everyone's desktop!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jurva This has been fixed and dramatically simplified in the 2.1 version which will be live in 30 minutes. Can you try that?

**Comment by jurva** [comment]
It is much simpler, thanks! However, the screenshot could be updated; the URL is not consistent with the text. Unless the localization issue is fixed in a later step, the problem with non-US languages remains. I would prefer not to have to switch to US region/language preferences just to make a tutorial accept floating-point numbers – using comma or period. Now it rejects both. I just assume that this sort of fix is something that a lot of developers face very soon.

**Comment by Rick-Anderson** [comment]
I updated the screenshot, it will go live tomorrow.
