### ISSUE TITLE
IUrlHelper Action Extension methods uses controller "route" name, not controller name

### ISSUE THREAD

**Issue by BennieCopeland** [aspnet/Docs#6682]
The documentation says that the IUrlHelper Action extension methods take the action name and controller name, but this is not accurate. The extension method takes the controller "route" name. If the controller name is "HomeController", the code must use "Url.Action("Index", "Home")". This also prevents using the convenience "nameof" call to allow controller name refactoring.

Also, the underlying code does not check the incoming data for validity allowing "Url.Action("foo", "bar")" to return a url to a nonexistent controller and action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.0)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> the underlying code does not check the incoming data for validity allowing "Url.Action("foo", "bar")" to return a url to a nonexistent controller and action.

@BennieCopeland  where do you propose this should be checked?

**Comment by Rick-Anderson** [comment]
@rynowak  In the following should I replace **controller name** with **controller root name** ?
I'd mention in the doc that controller root name is the name of the controller without the *controller* suffix. For example, the controller root name for the `HomeController` is `Home`.

Can you also respond to @BennieCopeland  suggestion that the underlying code does not check the incoming data for validity allowing "Url.Action("foo", "bar")" to return a url to a nonexistent controller and action.

**Comment by BennieCopeland** [comment]
I'm not saying it necessarily has to be checked, but it caught me off guard when I was expecting it to either return `null` like `Url.Link` or throw some sort of error instead of returning an invalid url.

I primarily do API work with named route attributes and `Url.Link`. When trying to generate an absolute url in an MVC app with `UseMvcWithDefaultRoute()` set, I realized during testing that `Url.Link` won't work. I tried adding a name to `[HttpGet]`, but the only way to make it work is to give it a route template.  I thought `Action` would work similar to `Url.Link` by checking the supplied action, controller, and route values.

The intellisense also uses the wording of **controller name** which contributed to my confusion.

**Comment by nguyenquyhy** [comment]
I believe UrlHelper.Action should also accept "HomeController" as the controller name so that we can use nameof feature. Currently it is a plain string, which is hard to maintain when there is a need to move Action around.

**Comment by Rick-Anderson** [comment]
The API docs and much of our docs use controller name. This doc doesn't have the following:

>The documentation says that the IUrlHelper Action extension methods take the action name and controller name, but this is not accurate. The extension method takes the controller "route" name. If the controller name is "HomeController", the code must use "Url.Action("Index", "Home")". 

This doc consistently shows sample like like the above (using "Home").
