### ISSUE TITLE
UseSqlite method Not Found!

### ISSUE THREAD

**Issue by billschen** [aspnet/Docs#6685]
I follow the step but  [DbContextOptionsBuilder](https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.dbcontextoptionsbuilder#methods)  class doesn't have   UseSqlite  method , Then I find UseSqlite is a extension method in  
[SqliteDbContextOptionsBuilderExtensions](https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.sqlitedbcontextoptionsbuilderextensions) 
in **Microsoft.EntityFrameworkCore.dll**
How can I add this assembly? 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1#migrating-from-microsoftaspnetcoreall-to-microsoftaspnetcoreapp

**Comment by billschen** [comment]
@Rick-Anderson thank you~
![err78](https://user-images.githubusercontent.com/19528399/40751679-d242b19c-649e-11e8-855e-6444cba8b56b.jpg)

**Comment by jtshannon** [comment]
Using ubuntu and get this error.
jeff@jeff-ThinkPad-T420:~/dev/RazorPagesMovie$ dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages/Movies --referenceScriptLibraries
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:07.11

dotnet --version
2.1.300

**Comment by Rick-Anderson** [comment]
@jtshannon 
> `'System.Collections.Immutable, Version=1.2.3.0, `

That's pretty old. What does you *.csproj* file look like?

**Comment by Ju2c0c0** [comment]
I had the same issue. Tried to add the reference as @billschen said but I got an exception at the `dotnet ef database update`.
Found out you need the following package instead (also giving a version to prevent warnings):
`<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1"/>`
and not Microsoft.EntityFrameworkCore.Sqlite.Core
