### ISSUE TITLE
Typo / Spelling Error / Grammar?

### ISSUE THREAD

**Issue by bchavez** [aspnet/Docs#6696]
In 2.1, Razor Pages search for Razor assets (such as layouts and partials) **in to** following **directorys** in the listed order:

In 2.1, Razor Pages search for Razor assets (such as layouts and partials) **in the** following **directories** in the listed order:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5e5a06-9628-5869-d25a-8c9988b739ec
* Version Independent ID: be7c2318-89d8-9cf7-e03e-31fc709bfece
* Content: [What's new in ASP.NET Core 2.1](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.1?view=aspnetcore-2.1)
* Content Source: [aspnetcore/aspnetcore-2.1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/aspnetcore-2.1.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@bchavez Thank you for reporting this. The fix will be live shortly.
