### ISSUE TITLE
Incorrect instructions for ASP.Net Core 2.1 and EF.Core 2.1

### ISSUE THREAD

**Issue by fmorriso** [aspnet/Docs#6714]
2018-05-30:  
The following instructions, located in this article, do not work (generates compile error):

public static void Main(string[] args)
{
    var host = BuildWebHost(args);

    using (var scope = host.Services.CreateScope())
    {
        var services = scope.ServiceProvider;
        try
        {
            var context = services.GetRequiredService<SchoolContext>();
            DbInitializer.Initialize(context);
        }
        catch (Exception ex)
        {
            var logger = services.GetRequiredService<ILogger<Program>>();
            logger.LogError(ex, "An error occurred while seeding the database.");
        }
    }

    host.Run();
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [ASP.NET Core MVC with Entity Framework Core - Tutorial 1 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@fmorriso That's a 2.0 tutorial and will probably not be upgraded to 2.1
I'm scheduled to update the Razor Pages version in a couple weeks to 2.1. Why aren't you doing the RP version?

**Comment by Rick-Anderson** [comment]
Take a look at https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.1#add-the-seed-initializer
to see the 2.1 version.

**Comment by oldpond** [comment]
Attempting to add scaffolding for a table in Postgres: Method not found: 'Void Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations..ctor(Microsoft.EntityFrameworkCore.Design.Internal.IOperationReporter, System.Reflection.Assembly, System.Reflection.Assembly)'.

**Comment by fmorriso** [comment]
Sounds like I need to give Rick Anderson time to upgrade the tutorial and then try again.

**Comment by fmorriso** [comment]
Closing since the tutorial will eventually be updated to version 2.1 as mentioned earlier.
