### ISSUE TITLE
en-us link and tr-tr link are different in asp.net core 2.1 signalR doc

### ISSUE THREAD

**Issue by gwlrs** [aspnet/Docs#6721]
tr-tr link and en-us link are diffrent for chat js . tr link : https://docs.microsoft.com/tr-tr/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio#create-the-signalr-client-code - en link: https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio#create-the-signalr-client-code . chat.js code on tr link doesn't work that is 
 `const connection = new signalR.HubConnection (
    "/chathub",
    { logger: signalR.LogLevel.Information }); `

**Comment by Rick-Anderson** [comment]
I think it takes a few days for updates to our docs to make it through localization.

@nokura  can you comment on how long it takes for changes to a doc to be localized?
