### ISSUE TITLE
Which extension?

### ISSUE THREAD

**Issue by yooakim** [aspnet/Docs#6726]
I am trying to get a .NET Core 2.1 app to work using the "Install extension" method. But the instructions above are not very clear on which extension should be installed.

When I look in the list of extensions the only one I find is "ASP NET Core Extensions", nothing else resembles ASP .NET Core runtime.

Can you explain which extension I should use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Host ASP.NET Core on Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1#install-the-preview-site-extension)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for pointing out the problem with the instruction. It looks like there was a miscommunication between engineering and the docs team when this was added. I'll fix it now. The extension is called **ASP.NET Core Extensions**.
