### ISSUE TITLE
Additional Information

### ISSUE THREAD

**Issue by serpent5** [aspnet/Docs#6728]
The Additional Information section refers to the 2.0 release notes in both text and link (should be 2.1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5e5a06-9628-5869-d25a-8c9988b739ec
* Version Independent ID: be7c2318-89d8-9cf7-e03e-31fc709bfece
* Content: [What's new in ASP.NET Core 2.1](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.1?view=aspnetcore-2.1)
* Content Source: [aspnetcore/aspnetcore-2.1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/aspnetcore-2.1.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
@serpent5  This is a copy/paste from the doc:
"For the complete list of changes, see the ASP.NET Core 2.1 Release Notes.
https://github.com/aspnet/Home/releases/tag/2.1.0"

I don't see where it's only referencing 2.0. Can you elaborate?

**Comment by serpent5** [comment]
On the live version of the docs page at https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.1?view=aspnetcore-2.1, it looks like this:

![image](https://user-images.githubusercontent.com/6025110/40776159-d9e88d90-64c1-11e8-8b91-d331edfafb89.png)

The link also takes you to https://github.com/aspnet/Home/releases/tag/2.0.0.

**Comment by rachelappel** [comment]
Ah, ok. Gotcha. I am wondering if something is out of sync with publishing. Will check on it.

**Comment by Rick-Anderson** [comment]
It was fixed at https://github.com/aspnet/Docs/pull/6697/files
We're having a problem right now merging to live, but that will be fixed by EOD.

**Comment by Rick-Anderson** [comment]
@serpent5  it's fixed on live now. Thanks for reporting this.
