### ISSUE TITLE
UE General Data Protection Regulation (GDPR)

### ISSUE THREAD

**Issue by serpent5** [aspnet/Docs#6729]
The text "UE General Data Protection Regulation (GDPR)" should be "EU ..." rather than "UE ...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e5e5a06-9628-5869-d25a-8c9988b739ec
* Version Independent ID: be7c2318-89d8-9cf7-e03e-31fc709bfece
* Content: [What's new in ASP.NET Core 2.1](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.1?view=aspnetcore-2.1)
* Content Source: [aspnetcore/aspnetcore-2.1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/aspnetcore-2.1.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **riande**

**Comment by serpent5** [comment]
This error also exists here: https://github.com/aspnet/Docs/blob/master/aspnetcore/security/gdpr.md.

**Comment by scottaddie** [comment]
Fixed by https://github.com/aspnet/Docs/pull/6730
