### ISSUE TITLE
how to identifying 404s with the new angular template

### ISSUE THREAD

**Issue by 3Shain** [aspnet/Docs#6734]
It seems that MapSpaFallbackRoute doesn't work with the new angular template
so all requests are handled by angular router

by the way, one node.js progress remains running while developing , so I have to close the console manually , how to deal with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/templating/issues/546 for the engineers to review.
