### ISSUE TITLE
The Razor SDK will not light up via transient reference

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Docs#6746]
The docs should note that in order for the Razor SDK to light up for a web project, the web project must explicitly reference an appropriate package (like `Microsoft.AspNetCore.All` or `Microsoft.AspNetCore.Mvc`), and that a transient reference to a class library that references `Microsoft.AspNetCore.All` or `Microsoft.AspNetCore.Mvc` will not suffice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65475f94-d29b-2960-2369-1529d5a7b329
* Version Independent ID: 52bdd7fb-02fd-1d66-87bb-9dfc4a3be707
* Content: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/razor-pages/sdk.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/razor-pages/sdk.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  should this be added to  [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/sdk?view=aspnetcore-2.1) ? Is the doc wrong?

**Comment by pranavkm** [comment]
> a transient reference to a class library

Is this a project reference, if so you will need an explicit package reference. If it's a package reference to the class library, you would need to set `PrivateAssets="None"` (by default NuGet makes analyzers and build assets as private).

**Comment by Rick-Anderson** [comment]
@pranavkm  can you propose text to that effect I can add to the doc?

**Comment by pranavkm** [comment]
I don't think we need to call out how NuGet's behavior for build targets work in the Razor Sdk.
