### ISSUE TITLE
adding dependency on Microsoft.Framework.DependencyInjection package results in 404

### ISSUE THREAD

**Issue by trendoid** [aspnet/Docs#677]
Docs/aspnet/tutorials/your-first-aspnet-application.rst advises the user to add package Microsoft.Framework.DependencyInjection but that results in 404.  That namespace is built in now I believe.

**Comment by leonardlabat** [comment]
This has moved to Microsoft.Extensions.DependencyInjection.

**Comment by shirhatti** [comment]
Closing since this was fixed in 89482489a6fae8deb4120c214b5dbb97773f46d1
