### ISSUE TITLE
Asynchronous Action example checks model state, even though invalid model state/BadRequest response occurs by default

### ISSUE THREAD

**Issue by fiksen99** [aspnet/Docs#6776]
see the asynch example on this page. It uses ModelState.IsValid as an example. But actually with an [ApiController] the model state is checked and BadRequest returned by default, which means this code would never be hit. We should update this to something more relevant (use the NotFound example from above?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.1#asynchronous-action-1)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@rynowak please suggest update.

**Comment by rynowak** [comment]
I think using `NotFound()` is fine also. I also don't think a change here is super high priority
