### ISSUE TITLE
Dependency injection with convenience methods

### ISSUE THREAD

**Issue by breyed** [aspnet/Docs#6783]
Using the convenience methods, how can I access services such as ILoggerFactory provided by the hosting service? Using Startup, they are available via dependency injection in the constructor and Configure. What is the equivalent for the convenience methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [Application startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @breyed -- It can be done this way, but I vaguely recall that this came up once before where we did something else. @Tratcher is this the correct approach or another one of my 😵 **_RexHacks_**:tm: 😵? 

Either way, I think the approach would be a good add. Perhaps, we'd put it over in the logging topic and cross-link to the content from a few other spots, including this topic.

```csharp
    public class Program
    {
        public static ILogger<Program> _logger;

        public static void Main(string[] args)
        {
            ILoggerFactory loggerFactory = new LoggerFactory()
                .AddConsole()
                .AddDebug();
            _logger = loggerFactory.CreateLogger<Program>();

            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    _logger.LogInformation("Loggin in ConfigureAppConfiguration!");

            ...
```

**Comment by Tratcher** [comment]
@guardrex that doesn't really answer the question, it bypasses DI altogether.

There's no direct way to get services into ConfigureServices. There are some indirect ways where you register your thing that needs a service as its own service and then resolve it later outside of ConfigureServices. People sometimes do this with IConfigureOptions.

In Configure you can call `IApplicationBuilder.ApplicationServices.GetRequiredService<T>()`. That might be worth providing an example for.

**Comment by guardrex** [comment]
> provided by the hosting service

Yes. I understand. @breyed You're looking for more than a hack to get a console logger?

> call `IApplicationBuilder.ApplicationServices.GetRequiredService<T>()`. That might be worth providing an example for.

Sounds good. I'll pitch a PR for that ... when I can. 🏃😅

**Comment by Tratcher** [comment]
Interesting point: IWebHostBuilder.ConfigureServices is not equivalent to Startup.ConfigureServices. IWebHostBuilder.ConfigureServices is called first and adds services to the host's DI container. That's why no DI services are available at this stage. Startup.ctor can consume the host's services and then Startup.ConfigureServices builds a secondary container.

**Comment by davidfowl** [comment]
It's a chicken and egg problem. You need a container to activate the Startup class so we have a bootstrapping container for this reason. When you're not using Startup there's nothing to activate and thus no way to get services. We don't have a ConfigureApplicationServices on WebHostBuilder which would be the equivalent of what Startup offers today.

**Comment by guardrex** [comment]
> Startup.ctor can consume the host's services and then Startup.ConfigureServices builds a secondary container.

Which means that we can expand our example for `Startup` to show an `ILoggerFactory` going into the ctor there for a `Startup` class logger. That's probably a good idea for that scenario.

Otherwise for the convenience methods, I'll just pitch that example with `GetRequiredService` in `Configure`.

**Comment by breyed** [comment]
FWIW, the reason this question even arose for me is not because I wanted to log the startup process. Rather, in ConfigureServices, in my `AddMvc`, I was replacing `ComplexTypeModelBinderProvider` with a custom binder provider that derives from it, with the added functionality of trimming whitespace.

This was all well and good (at least it worked - I can't say whether it was the best approach) until ASP.NET Core 2.1, when the `ComplexTypeModelBinder` constructor that doesn't take an `ILoggerFactory` parameter was deprecated. Hence my desire to access `ILoggerFactory` from ConfigureServices.

Based on the discussion here and in aspnet/Hosting#1150, it seems like ConfigureServices comes too early to access the logging service that will be used when model binding occurs. Not knowing how this is supposed be get hooked up, I decided to punt with a `#pragma warning` wrapper, but I thought I'd throw this out there in case it spurs any thoughts on the proper way to handle the situation.

**Comment by blyndcide** [comment]
Same problem here.  I want to add

`services.AddMvc(options =>
            {
                ...
                options.Filters.Add(new ResponseCacheFilter(new CacheProfile()
                {
                    Location = ResponseCacheLocation.None,
                    NoStore = true,
                    Duration = 0
                }, //how to get ILoggerFactory?));
                ...
            })`

There is no longer a ResponseCacheFilter constructor that doesn't require an ILoggerFactory.
