### ISSUE TITLE
Provide documentation on how to customize action selection

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Docs#6785]
Would be nice to see how one can customize the action selection with swagger. Does that use the same registered types from MVC to discover the actions or different? 

My use case here is to hide some of the APIs from the documentation based on a condition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@rynowak  can you comment on this? Should we consider adding this to our doc?

**Comment by RSuter** [comment]
You can implement this with a custom operation processor and add you logic there (return false to exclude operation): https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors#operation-processors

@Rick-Anderson how are question about the article content handled here (i.e. not actual article issues or enhancements)?
 I propose to avoid duplicating too much of the docs as it will be harder to maintain it in two places... hard to find the sweet spot 🙂

**Comment by Rick-Anderson** [comment]
@RSuter  This issue if it's related or create a new one. You can see open issues for a doc at the bottom of the page.

**Comment by rynowak** [comment]
I agree that it would be best to let NSwag's docs cover topics like this unless it's specific to an MVC feature.
