### ISSUE TITLE
services.AddWebApiConventions is wrong

### ISSUE THREAD

**Issue by aligneddev** [aspnet/Docs#6788]
it should be services.AddMvc.AddWebApiConventions. See my SO answer (https://stackoverflow.com/a/50646410/54288)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f83a3b4-28f6-5f0f-a8bf-aef76f05fe42
* Version Independent ID: 0d0bc32b-5909-580f-1030-edbf1d3d9a68
* Content: [Migrate from ASP.NET Web API to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/webapi.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@aligneddev Thank you for reporting this problem. The fix will go live later today.
