### ISSUE TITLE
'Movie' does not exist in the namespace

### ISSUE THREAD

**Issue by oxwilder** [aspnet/Docs#6790]
Using the code as shown to add validation to the movie.cs, the build fails and says that the namespace we're working in doesn't define 'Movie'.
I was able to use the validation code from the MVC web app tutorial to move forward, but replacing all the code with the #if MovieDatRatingDA code results in all grey text in Visual Studio's text editor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Service: **unspecified**
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@oxwilder  that's a great error message. VS should help you find your mistake.

**Comment by daveabrock** [comment]
In this file, would moving the region outside of the namespace resolve it, or does this file have uses in other places? When I tried to reproduce, I know that once I included the namespace everything was gravy.
