### ISSUE TITLE
Example code under the subject  "Cache Dependencies" not robust enough?

### ISSUE THREAD

**Issue by dkimbell13** [aspnet/Docs#6791]
Hi All,

Under the subject "Cache Dependencies" in the example method "CreateDependentEntries" the code is storing a "CancellationTokenSource" in the cache. This is fine...

But in the "RemoveChildEntry" method you are pulling this "CancellationTokenSource" from the cache and calling .Cancel() on the object. But there is no guarantee that the "CancellationTokenSource" is still in the cache. Since that particular cache key was never set to never expire, and it is also possible that automatic memory management might have removed that cache key to make room for other cache entries.

Am I misunderstanding how the cache entries are stored and managed? Will the "CancellationTokenSource" remain in the cache indefinitely, so that you can pull it to cancel the dependent cache entries?

Or should "CancellationTokenSource" cache entry be marked as "never to be removed". Is that even possible? Since the apppool could recycle or the automagically maintained cache memory could expire that cache entry?

Are these good examples of how to manage "CancellationTokenSource" tokens? Or should these be stored somewhere more permanent so you don't have worry about the "CancellationTokenSource" disappearing on you. 

Mostly I am wondering if the example code is real best practices or just something someone came up as an example without worrying about the overall implications. Since I could be completely misunderstanding what is really happening, I am really curious.

Thanks,
Dominique

`Edit`
Related #6958, #6402, #6791, #6808
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JunTaoLuo please comment.

**Comment by JunTaoLuo** [comment]
I think the sample was written for simplicity but as you point out there is no guarantee that the CTS is still in the cache. In fact, the sample that we have violates our main recommendation which is that you should never rely on a value being present in the cache. The values inside the cache are ephemeral and can be purged at any time for any reason (over-capacity, expiration, ...). The code in the docs is definitely not best practice.

**Comment by dkimbell13** [comment]
Thanks! I really appreciate your reply.

**Comment by Rick-Anderson** [comment]
> the sample that we have violates our main recommendation which is that you should never rely on a value being present in the cache.

I'll update the sample to not rely on the value being in the cache.

**Comment by Rick-Anderson** [comment]
fixed in #7792
