### ISSUE TITLE
Add instructions for registering IHttpContextAccessor service

### ISSUE THREAD

**Issue by qJake** [aspnet/Docs#6795]
When migrating from 2.0 to 2.1, users that have a scoped service of `IHttpContextAccessor` can sometimes receive the following error:

> System.InvalidOperationException: Cannot resolve 'Microsoft.AspNetCore.Http.IHttpContextFactory' from root provider because it requires scoped service 'Microsoft.AspNetCore.Http.IHttpContextAccessor'.

I originally had this line:

```csharp
services.TryAddScoped<IHttpContextAccessor, HttpContextAccessor>();
```

I replaced it with:

```csharp
services.AddHttpContextAccessor();
```

And that resolved the issue. This should be noted in the migration documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET MVC to ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Service: **unspecified**
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  should this be added to the migration doc?

**Comment by Tratcher** [comment]
I'm not sure why. TryAddScoped was an incorrect usage in the first place, not a behavior change in 2.1. AddHttpContextAccessor was added to discourage incorrect usage.

**Comment by Tratcher** [comment]
Except when they try to resolve it outside of a scope 😁

**Comment by davidfowl** [comment]
Then its just null

**Comment by Tratcher** [comment]
No, you get the error above about 
> System.InvalidOperationException: Cannot resolve 'Microsoft.AspNetCore.Http.IHttpContextFactory' from root provider because it requires scoped service 'Microsoft.AspNetCore.Http.IHttpContextAccessor'.

**Comment by davidfowl** [comment]
Wait, we added it as scoped? That's completely wrong.

**Comment by davidfowl** [comment]
https://github.com/aspnet/HttpAbstractions/blob/d6a3c3f83e0abb54472f19103bf385ca9d8ead5f/src/Microsoft.AspNetCore.Http/HttpServiceCollectionExtensions.cs#L27

Phew, it's a singleton

**Comment by qJake** [comment]
I can confirm that this line:

```csharp
services.TryAddScoped<IHttpContextAccessor, HttpContextAccessor>();
```

Used to work as of 2.0... improper or not. 😀

I think, if this was a breaking change made to 2.1, it should be included, no?

**Comment by Tratcher** [comment]
Where did you resolve it? That error isn't specific to IHttpContextAccessor, you'd get that for any scoped service resolved outside of a scope.

**Comment by davidfowl** [comment]
> I think, if this was a breaking change made to 2.1, it should be included, no?

It shouldn't be scoped. It should be a singleton.

**Comment by qJake** [comment]
@Tratcher Interestingly, I got it on this line:

```csharp
CreateWebHostBuilder(args).Build().Run();
```

**Comment by qJake** [comment]
@davidfowl Right - the breaking change would be, from 2.0 to 2.1, that

```csharp
services.TryAddScoped<IHttpContextAccessor, HttpContextAccessor>();
```

Though wrong, worked before (due to a shim I guess?), and doesn't work now.

Whether that's worth documenting isn't up to me 😁 But if I ran into the issue, surely there will be others who do, as well.

**Comment by davidfowl** [comment]
There's no breaking change. Your code used the wrong lifetime before.

**Comment by Rick-Anderson** [comment]
> But if I ran into the issue, surely there will be others who do, as well.

They can find it in this issue.

**Comment by OpticGenius** [comment]
Should be using

`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`
