### ISSUE TITLE
Managing Application State

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#68]
ASP.NET 5->Fundamentals->Managing Application State
- Per-Request State using HttpContext.Items (cover briefly)
- Caches (cover briefly; refer to Caching #69)
- Session (cover in more detail)

Cover:
Session is implemented on top of IDistributedCache (which can run on top of IMemoryCache for testing purposes)
Session is not there by default; must install and configure middleware
Session middleware must be earlier in pipeline than anything that uses it
Biggest difference from past Session implementation is no serialization by default. The methods take bytes, not objects. Also, there is no longer a public session key.
Session is non-blocking. This allows improved performance but also means that the last write wins, so if two requests both read from session and simultaneously try to write to it, the later one will overwrite the first one(s).
Session is a coherent session. That means the above still is true if the two requests were writing to different areas of the session.

**Comment by ardalis** [comment]
Starting work on this one, @danroth27

**Comment by eriksendc** [comment]
When reading https://readthedocs.com/projects/aspnet-aspnet/downloads/pdf/latest/ it stated under caching to leave a comment if I wanted to review documentation drafts. I'm Brian Eriksen, eriksendc@yahoo.com is my email. Would be happy to review content being developed. Thanks!
