### ISSUE TITLE
Add IPageHandlerModelConvention to sample

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6801]
`IPageHandlerModelConvention` is covered in the topic but should also appear as an example in the sample app.

*Razor Pages route and app conventions in ASP.NET Core*
mvc\razor-pages\razor-pages-conventions.md
https://docs.microsoft.com/aspnet/core/mvc/razor-pages/razor-pages-conventions

**Comment by guardrex** [comment]
@pranavkm Need a tip: What's a good sample app example of `IPageHandlerModelConvention` that you think readers would like to see?

```csharp
public class CustomPageHandlerModelConvention
    : IPageHandlerModelConvention
{
    public void Apply(PageHandlerModel model)
    {
        // Do something here
    }
}
```

**Comment by Rick-Anderson** [comment]
@guardrex 	should we close this?

**Comment by guardrex** [comment]
@NTaylorMullen ❓ ... Is this ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/razor-pages-conventions/sample/CustomPageApplicationModelProvider.cs

https://docs.microsoft.com/aspnet/core/razor-pages/razor-pages-conventions#replace-the-default-page-app-model-provider

... worth the effort with the (apparent) changes in protection level between 2.1 and 2.2?

If I try to base the custom page application model provider on `IPageApplicationModelProvider` (instead of `DefaultPageApplicationModelProvider`), it hates on me with further protected objects ...

* `Microsoft.AspNetCore.Mvc.RazorPages.Resources`
* `HandleOptionsRequestsPageFilter`
* `PropertyHelper`

I guess I could keep ripping the guts out of the framework to try and make it work, but is it worth the effort for this scenario.

**Comment by pranavkm** [comment]
Could we drop that topic? We generally discourage replacing the application model provider, a convention is what we'd expect most users to implement.

**Comment by guardrex** [comment]
@pranavkm You mean just drop the **section** and sample for it, right? ... you don't mean the entire topic, right?

**Comment by pranavkm** [comment]
> You mean just drop the **section** and sample for it, right?

Yup 👍
