### ISSUE TITLE
.NET Core for Mac & Linux not production ready?

### ISSUE THREAD

**Issue by optical** [aspnet/Docs#681]
Hi,

In the docs at https://github.com/aspnet/Docs/blob/master/aspnet/getting-started/choosing-the-right-dotnet.rst it states that .NET Core is not production ready.

I presume this information is now out of date as of RC1, as the blog post seems to imply .NET core is ready for production in all environments. Am I misinterpreting this blog post, or can this disclaimer be removed now?

**Comment by danroth27** [comment]
The disclaimer can now be removed.

**Comment by Erikre** [comment]
Updated the doc and created PR #735. Removing the following sentence:
However, the .NET Core support for Mac and Linux is still very new and not ready for production workloads.
