### ISSUE TITLE
Worked smoothly until testing the app

### ISSUE THREAD

**Issue by avaler** [aspnet/Docs#6810]
After successful migration and database update I tried to run the app using /Movies command but I got 404 error. I did not get any error earlier. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by avaler** [comment]
Problem solved. Scaffolding needs to take place in Pages subfolder and not in a folder somewhere in the root of the app.

**Comment by Rick-Anderson** [comment]
cc @seancpeters
