### ISSUE TITLE
Extra PackageReference Microsoft.VisualStudio.Web.CodeGeneration.Design?

### ISSUE THREAD

**Issue by AceHack** [aspnet/Docs#6811]
I've just created many different types of 2.1 projects and none of them seem to have the following PackageReference by default.

 &lt;PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" /&gt;

Are the new 2.1 templates missing this reference by mistake or is it not needed and the documentation is out of date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc
Remove all references to <DotNetCliToolReference> elements for "Microsoft.AspNetCore", "Microsoft.VisualStudio", and "Microsoft.EntityFrameworkCore" packages. These tools have been replaced by global tools.

**Comment by AceHack** [comment]
@Rick-Anderson Then your docks have a bug, in your new 2.1 example file you still have the reference

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>aspnet-{Project Name}-{GUID}</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

**Comment by AceHack** [comment]
@Rick-Anderson maybe not the documentation actually says


Remove all references to `<DotNetCliToolReference>` elements for "Microsoft.AspNetCore", "Microsoft.VisualStudio", and "Microsoft.EntityFrameworkCore" packages. These tools have been replaced by global tools.

This is not a `<DotNetCliToolReference>` but a `<PackageReference>` element.  So my question still stands is the bug in the documentation or the 2.1 project templates because they disagree with each other.

**Comment by Rick-Anderson** [comment]
@AceHack  the templates generate correct code. Where is the problem in the doc?

**Comment by AceHack** [comment]
@Rick-Anderson if you do the same thing from the UI in Visual Studio you are missing the following


`<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />`

This is what I'm talking about, is this needed or not and if it's needed why is Visual Studio not adding it.  Thanks.

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio
It's needed when you scaffold.

**Comment by ggirard07** [comment]
@Rick-Anderson same issue here, `Microsoft.VisualStudio.Web.CodeGeneration.Design` is not part of the code scaffolded by VS 15.8 for an ASP.NET Core WebAPI.

Is this dependency required in ASP.NET Core 2.1?

**Comment by Rick-Anderson** [comment]
@ggirard07  Code Generation tool for ASP.NET Core. Contains the dotnet-aspnet-codegenerator command used for generating controllers and views.
It's not used by runtime when you run your app.

**Comment by AceHack** [comment]
@ggirard07 not sure that fully answered the question.  Should VS be adding for compile-time scaffolding to work correctly?  Is this a bug in VS templates?

**Comment by Rick-Anderson** [comment]
No, VS correctly scaffolds without that.

**Comment by Rick-Anderson** [comment]
Yes, it's needed for CLI.

**Comment by AceHack** [comment]
@Rick-Anderson this seems like a bug in VS template then.  It should create a project that is compatible with vscode and CLI.  This is why I opened this bug in the first place, was to determine if this was a bug in VS template or the documentation.  Clearly this is a bug/oversight in the VS template.
