### ISSUE TITLE
Comments Section Disappeared

### ISSUE THREAD

**Issue by tonyawad88** [aspnet/Docs#6812]
Hello, I can no longer find the comments section where people can contribute / ask questions about a page? I remember very well commenting on one of the pages. Any idea how I can see it again? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification&view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tonyawad88  it's been replaced by this GitHub issue system.

![image](https://user-images.githubusercontent.com/3605364/40879242-f0c40b16-6638-11e8-8765-af404ea3692d.png)
