### ISSUE TITLE
2.1 update: Visual Studio Tools for Docker with ASP.NET Core

### ISSUE THREAD

**Issue by AceHack** [aspnet/Docs#6813]
This document is out of date, this is no longer what the "Enable Docker Support" checkbox does.  Instead, this is when you right click and Add Orchestrator support now.  Enabling docker support now just adds a Docker file and some debug settings for launching inside docker all in the *.csproj itself, so there is not seperate *.dcproj anymore with this checkbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@AceHack  thanks for pointing that out. I'll get it scheduled for an update.
Related #5631

**Comment by damienbod** [comment]
I'm also having problems getting this to work. I get exceptions with the default VS settings. Not sure if this is a docs issue, but docs for the new 2.1 would help. Before 2.1 this worked without problems.

Use Case which does not work for me:

Add docker to existing project - standard MVC Web API
Create a docker image (cmdline)
create a tag from this image (cmdline)
deploy to Docker Hub

I think you're doing an excellent job, and would be grateful if you could find time to improve this.

Greetings Damien

**Comment by scottaddie** [comment]
@AceHack Thank you for bringing this to our attention. The feature has changed as of VS 2017 15.8. I'm working on the doc updates now.
