### ISSUE TITLE
@aspnet/signalr js client version should be made clear

### ISSUE THREAD

**Issue by niwsa** [aspnet/Docs#6816]
For me coming from the JS world don't know if this is a big ask.I am missing the js client version number in this documentation and in the github repo(https://github.com/aspnet/SignalR) .Only the npm link https://www.npmjs.com/package/@aspnet/signalr clearly mentions the version (1.0.0 at the time I am writing this).Given the signalr client and server versions should match there are times at which we have to cross check the client/server version numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by davidfowl** [comment]
The client and server versions only have to match if you’re using pre-1.0.0 SignalR. From here on out the protocol version will be what matters.

**Comment by rachelappel** [comment]
Closing as answered.
