### ISSUE TITLE
Singleton dependency injection for SingalR hub

### ISSUE THREAD

**Issue by mittalthoria86** [aspnet/Docs#6823]
Hello,

We just now updated .Net core version to 2.1 and got SignalR Core. We have been able to replace most of the methods by their replacements in SignalR Core but couldn't find a replacement for the way we declared singleton instances of Hubs.

Currency with older version of SingalR, we used following syntax to declare each SignalR hub singleton. 

services.AddSingleton<IHubContext<MarketHub>, HubContext<MarketHub>>();

With SignalR Core, we do not find reference to HubContext anymore. Could you please guide us what is the replacement syntax for declaring SingalR hub singletons?

Thanks.

**Comment by Rick-Anderson** [comment]
@mittalthoria86  is you question about migrating from ASP.NET SignalR to ASP.NET Core 2.1 SignalR?

**Comment by rachelappel** [comment]
@mittalthoria86 IHubContext is already a Singleton and you no longer need to add it to Startup.

**Comment by mittalthoria86** [comment]
Yeah. That explains it. Thank you for your answer.
