### ISSUE TITLE
Linux with Apache topic issues

### ISSUE THREAD

**Issue by davidich** [aspnet/Docs#6827]
According to this guide, httpd-2.4.6-40.el7.centos.4.x86_64.rpm is good enough to proceed, but "service httpd configtest" command fails with an error: "Unrecognized header format %". I was able to solve it by installing the latest version of httpd (Apache/2.4.33).

Env details:
* Operating System: CentOS Linux 7 (Core)
* CPE OS Name: cpe:/o:centos:centos:7
* Kernel: Linux 3.10.0-693.21.1.el7.x86_64
* Architecture: x86-64

Moved from #6828 ...

&gt; ExecStart=/usr/local/bin/dotnet /var/aspnetcore/hellomvc/hellomvc.dll
there is no file dotnet in /usr/local/bin
I guess it should be one of the following:
* /usr/bin/dotnet
* /usr/share/dotnet/dotnet

Env details:
* .NET Core 2.1 Runtime (v2.1.0)
* Operating System: CentOS Linux 7 (Core)
* CPE OS Name: cpe:/o:centos:centos:7
* Kernel: Linux 3.10.0-693.21.1.el7.x86_64
* Architecture: x86-64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **asp.net-core**
* GitHub Login: @spboyer
* Microsoft Alias: **spboyer**

**Comment by guardrex** [comment]
Thanks @davidich for the report.

@shirhatti How do you want to proceed?

**Comment by user135711** [comment]
To be specific the error occurs below [2.4.10](https://serverfault.com/questions/748326/apache-2-4-unrecognized-header-format), so until centos repos advance beyond, I solved by installing from the non centos repo (instructions from [here](https://crosp.net/blog/administration/install-latest-apache-server-centos-7/)). Also, I kept getting "Config variable ${APACHE_LOG_DIR} is not defined" until I hard coded the variable reference in hellomvc.conf for  ${APACHE_LOG_DIR} to "/etc/httpd/logs/" so perhaps that could be addressed if anyone else reports it. There are many solutions for [Ubuntu](https://serverfault.com/questions/558283/apache2-config-variable-is-not-defined) but I couldn't find a solution on [centos](https://serverfault.com/questions/915198/in-centos-7-how-to-solve-config-variable-apache-log-dir-is-not-defined-apac).

**Comment by Rick-Anderson** [comment]
@shirhatti please comment

**Comment by blowdart** [comment]
Carefully checked and validated community contributions by someone that knows Linux security? SELinux is going into unsupported territory probably.

**Comment by ParidaPunyasloka** [comment]
Running the configtest gives me below warnings and https fails to restart

[root@###### conf.modules.d]# sudo service httpd configtest
[Thu Jul 12 19:20:05.273487 2018] [core:warn] [pid 5654:tid 140675401267392] AH00111: Config variable ${REQUEST_SCHEME} is not defined
[Thu Jul 12 19:20:05.273734 2018] [core:warn] [pid 5654:tid 140675401267392] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Thu Jul 12 19:20:05.273751 2018] [core:warn] [pid 5654:tid 140675401267392] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
Syntax OK

**Comment by guardrex** [comment]
This doesn't seem very actionable from a docs perspective. See: #9853 ... I'll close since there isn't much we can do here.
