### ISSUE TITLE
ASP.NET Core - Shared Resource (resx) Localization

### ISSUE THREAD

**Issue by tonyawad88** [aspnet/Docs#6830]
## General

I am looking for some help at trying to figure out how to create a shared resource (resx) file and use it from different Controllers.

I followed the localization tutorial from Microsoft but unable to get it to work:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1

Looking for some help on what I might be doing wrong. 

Thank you for any help. Details below of project.

**Startup.cs**
```
public void ConfigureServices(IServiceCollection services){
    ...
    services.AddLocalization(options => options.ResourcesPath = "Resources"); 
    ...
}
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    IList<CultureInfo> supportedCultures = new List<CultureInfo>{
                                                    new CultureInfo("en-CA"),
                                                    new CultureInfo("fr-CA")
            };
            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("en-CA"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            });
}
```

**Resources Folder Structure and Files:**
```
ProjectRoot/Resources
ProjectRoot/Resources/SharedResources.cs (dummy class)
ProjectRoot/Resources/SharedResources.resx (Not able to load / DI into Controller)
ProjectRoot/Resources/SharedResources.fr-CA.resx (Not able to load / DI into Controller)
ProjectRoot/Resources/Controllers/MyController.resx (works great)
ProjectRoot/Resources/Controllers/MyController.fr-CA.resx (works great)
```

**Dummy Class:**
```
    public class SharedResources
    {
    }
```
**Sample Controller:**
```
private readonly IStringLocalizer<SharedResources> _sharedLocalizer;
public SampleController(IStringLocalizer<SharedResources> sharedLocalizer){
    _sharedLocalizer = sharedLocalizer
}
[HttpGet]
public string MyMethod(){
 return _sharedLocalizer["GoodMorning"].toString(); //returns "GoodMorning" and not the actual translation.
}
```
## Requests for new Topics N/A

**Comment by Rick-Anderson** [comment]
@tonyawad88  Thanks for the question. I'm not sure what you're doing wrong. You'll probably get an answer sooner if you post the question to StackOverflow or another support forum.

**Comment by tonyawad88** [comment]
@Rick-Anderson I figured it out, any chance you can confirm the following:

The "SharedResources.cs" file has to be at the root of the project and not within the resources folder namespace. I am not sure why, if someone can shed some light on this, it will be great.

Cheers !

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please confirm.

**Comment by rodrozalaz** [comment]
Hey i tried to do that @tonyawad88 said but it didn't work :'(

**Comment by Rick-Anderson** [comment]
@hishamco please review

**Comment by Xerillio** [comment]
@tonyawad88 I hope it's all working great for you :) I believe what you found is that the namespace of "SharedResources" was causing the localizer to not be able to find the correct path of the resource file.

I found that using the following file structure works fine:
ProjectRoot/Resources/SharedResource.cs
ProjectRoot/Resources/SharedResource.resx

You just need to ensure the namespace in SharedResource.cs is without "Resources", e.g.:
```csharp
namespace ProjectRoot // Not "ProjectRoot.Resources"
{
    public class SharedResource
    {
    }
}
```

**Comment by tonyawad88** [comment]
@Xerillio good finding. So the shared class file can probably go under the folder Resources/SharedResource.cs as long as the namespace of the shared class is ProjectRoot.

**Comment by ahmedMgouda** [comment]
SharedResource also not working in both cases under root or in Resources folder
