### ISSUE TITLE
authentication issue when use ssl offloading

### ISSUE THREAD

**Issue by zhaokk** [aspnet/Docs#6832]
Hi I am offloading ssl to my loadbalance, so the server( the application) dont know itself has ssl certificate, so the facebook auth call will have a redirect_uri of something like http://..... which will make facebook upset (they dont allow http website anymore), so my main question is how do i set the website's facebook auth call's redirect_uri to use https:// instead of http, for exmple set the redirect_uri in facebookOptions variable (but i checded the documentation, there is no such option). Or the redirect_uri is decided by facebook? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@zhaokk  great question, but it doesn't seem to me to have anything to do with this document. You'll probably get a much quicker answer if you ask this question in a forum or StackOverflow.
