### ISSUE TITLE
Example given for factory-based middleware could have been clearer

### ISSUE THREAD

**Issue by 5a7335h** [aspnet/Docs#6833]
The current example given in the documentation of factory-based middleware is not very clear. A real-time use case with more clear example would have been much helpful.
Same is the case with "Middleware activation with a third-party container".

Any link to other examples/documentation elsewhere will be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f5eb44-55e5-d4a5-0ab1-5122c29a1db5
* Version Independent ID: 0b8da6a7-8333-5d8f-23a5-05bf0ca661f9
* Content: [Factory-based middleware activation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-2.1#imiddleware)
* Content Source: [aspnetcore/fundamentals/middleware/extensibility.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/extensibility.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello and thanks for the feedback @5a7335h. The sample does show a real-world use case: the database context used in the sample is a scoped service. Can you elaborate on what you find confusing?

**Comment by guardrex** [comment]
Both topics don't focus on real-world middleware implementations ... they focus on middleware activation patterns. If you would like to see real-world middleware examples, your best bet is to search broadly for blog posts and GH repo examples.

> Any link to other examples/documentation elsewhere will be much appreciated.

Yes, that's possible. We'd probably do that in the [main middleware topic](https://docs.microsoft.com/aspnet/core/fundamentals/middleware).

**Comment by 5a7335h** [comment]
Thanks for your super fast response @guardrex. 👍 
 [This discussion](https://github.com/aspnet/HttpAbstractions/issues/754) has clarified few things. Although the examples given in the documentation show the implementation of this concept, I was actually looking for a basic example that emphasizes the benefit of using `IMiddleware` and `IMiddlewareFactory`. I started looking for the blog posts to see more specific scenarios. I might find one soon. But thought I would share the feedback so that we would have more authentic example in MSDN docs.

**Comment by mattfrear** [comment]
Personally I find the class name `IMiddlewareMiddleware` jarring, since it looks like the name of an Interface not a class.

**Comment by guardrex** [comment]
I'd like to change the name to "FactoryActivatedMiddleware."

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
