### ISSUE TITLE
CREATE FILE encountered operating system error CREATE DATABASE failed. Some file names listed could not be created. Check related errors.

### ISSUE THREAD

**Issue by jetaimefrc** [aspnet/Docs#6837]
Access is denied ??? I hope someone help me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What is the complete error? Try exit/restart VS.

**Comment by jetaimefrc** [comment]
When I update-database Up -> CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\UserNameWebApplication1Context-d69ac59a-a7f9-41dc-987c-e83e17c12946.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
Can you help me resolve it ?

**Comment by Rick-Anderson** [comment]
`C:\Users\UserNameWebApplication1Context-d69ac59a-a7f9-41dc-987c-e83e17c12946.mdf` is not a valid path. I've seen that error before. Can you update Visual Studio? Do that from the Help menu (select check for updates.)

**Comment by jetaimefrc** [comment]
I tried it, but it didn't work... Why access is denied and not a valid path ...

**Comment by Rick-Anderson** [comment]
@jetaimefrc  what did set the full path using AttachDbFileName in the connection string to?

**Comment by jetaimefrc** [comment]
Oh ! Worked ! Thank's you. But I think it not generalize for any case. I don't know have other solution ?

**Comment by Rick-Anderson** [comment]
@jetaimefrc  what version of Visual Studio are you using?

**Comment by jetaimefrc** [comment]
VS Community 2017 - ver 15.7.3

**Comment by Rick-Anderson** [comment]
@jetaimefrc thanks, that's the current version.

**Comment by ivicacevis** [comment]
Did you try https://support.microsoft.com/en-us/help/4096875/fix-access-is-denied-error-when-you-try-to-create-a-database-in-sql-se
