### ISSUE TITLE
Can I use purpose string for password-based key derivation? 

### ISSUE THREAD

**Issue by ydekova** [aspnet/Docs#6842]
I read the docs linked below, and it seems like using purpose strings is similar to having a PBKD in a way.  It is not explicitly said it could be used for this purpose though, and I got the impression that the purpose strings main goal is isolation rather than authenticated encryption.

I can use Rfc2898DeriveBytes for this but since I am using DataProtection in my app I would like to take advantage of this higher level API.

In my case, I would like to give more control to the password owner over the encryption of her data.

My question is is it 'safe' to use data protector created with a purpose string for PBKD, as an alternative to deriving a brand new key with Rfc2898DeriveBytes? How easy is it to decrypt the data without the purpose string if you have access to the master key.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6d9987c-f303-4e15-1508-df7abbd61f70
* Version Independent ID: 9beabaf0-975a-38ab-c162-c6945cdd680c
* Content: [Subkey derivation and authenticated encryption in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/subkeyderivation?view=aspnetcore-1.1#data-protection-implementation-subkey-derivation)
* Content Source: [aspnetcore/security/data-protection/implementation/subkeyderivation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/implementation/subkeyderivation.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  can you respond?

**Comment by blowdart** [comment]
That's not what it's designed for, nor can we comment on how difficult it would be because we've not looked at it.
