### ISSUE TITLE
ProducesResponseType with no type + ActionResult<T> is not supported

### ISSUE THREAD

**Issue by NatMarchand** [aspnet/Docs#6844]
Hi,
It seems that there is a small misunderstanding as it appears that it is not possible to omit the type in the ProducesResponseType attribute and leave ActionResult&lt;T&gt; infer it.
Although I think the doc is right (it shows the behavior expected), it doesn't show the *current* behavior.
Please see: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/711

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
The fix for this problem lands in the ASP.NET Core 2.1.3 release. Closing this issue, as there's nothing to adjust in the docs at this time.
