### ISSUE TITLE
Why is it necessary to publish node_modules for SSR?

### ISSUE THREAD

**Issue by pavel-agarkov** [aspnet/Docs#6846]
It used to be unnecessary with webpack-based setup.
Can you please describe why exactly it is necessary now?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.0&tabs=visual-studio#server-side-rendering)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by SteveSandersonMS** [comment]
It's a known issue in newer versions of Angular: https://github.com/angular/angular-cli/issues/8616
