### ISSUE TITLE
unable to find SetCompatibilityVersion

### ISSUE THREAD

**Issue by dstruve** [aspnet/Docs#6848]
Any suggestions why it cant find SetCompatibilityVersion?

 services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by dstruve** [comment]
nvm, its because im running 2.0

**Comment by dstruve** [comment]
here is the link to install 2.1  https://www.microsoft.com/net/download/visual-studio-sdks

**Comment by scottaddie** [comment]
@dstruve You're correct that 2.1 is required to use the `SetCompatibilityVersion` method.
