### ISSUE TITLE
doc request: Custom InputFormatters

### ISSUE THREAD

**Issue by dotnetchris** [aspnet/Docs#6849]
This article clearly documents building a custom OutputFormatter, but no information at all is provided for building a custom input formatter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by dotnetchris** [comment]
[Off topic, but amazing work everyone to make this so seamlessly integrated for documentation efforts]

**Comment by Rick-Anderson** [comment]
@danroth27  do we want to add Custom InputFormatters  to this topic?

**Comment by danroth27** [comment]
Hmm, I'm not sure what is missing here. The doc talks about does talk about how to implement input formatters and the sample has an example implementation of a vCard input formatter.

**Comment by dotnetchris** [comment]
> Override ReadRequestBodyAsync/WriteResponseBodyAsync methods

```c#
public class VcardOutputFormatter : TextOutputFormatter
```
Inherited from OutputFormatter.

Where's the implementation of `ReadRequestBodyAsync`? 

There's 3 usages of `ReadRequestBodyAsync` on the page and none of the 3 usages is a code sample.

https://imgur.com/a/cFgjrpu

**Comment by Rick-Anderson** [comment]
@dotnetchris  you have to expand the #region to see it. It's there.
