### ISSUE TITLE
APIController attribute fails

### ISSUE THREAD

**Issue by dstruve** [aspnet/Docs#6851]
im getting the following error:
Error CS0246	The type or namespace name 'ApiControllerAttribute' could not be found (are you missing a using directive or an assembly reference?)	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by dstruve** [comment]
well, i did upgrade to 2.1 but it didnt change in my project and doesnt give the option to select it either, even after rebooting.

**Comment by dstruve** [comment]
ok after I did the update, i couldnt fix my existing project. but once i started over it seemed to work , i hope.

**Comment by dstruve** [comment]
Yes that fixed it.

**Comment by scottaddie** [comment]
@dstruve Glad you figured it out. Visual Studio 2017 15.7 is the minimum version required to support ASP.NET Core 2.1. As you probably know, the `[ApiController]` attribute is available as of ASP.NET Core 2.1.

**Comment by viktorKI3** [comment]
Exist two solutions:
1) Change version of tutorial. In the left top menu of the current website change ASP.NET Core 2.1 -> ASP.NET Core 2.0.
2) Upgrade asp.net core in your project to ASP.NET Core 2.1
