### ISSUE TITLE
Onchange event handler to ajax call?

### ISSUE THREAD

**Issue by pcalkins** [aspnet/Docs#6854]
I'm wondering how to add an onchange event to the pulldown for the search filter and then update the results div using an ajax call here.   It seems to be refreshing the whole page... i.e. the pulldown resets each time...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pcalkins  thanks for the question. To keep this tutorial focused on Razor Pages it doesn't go into detail on client side programming and AJAX. That would be a great topic for a new article.

**Comment by pcalkins** [comment]
I did get this to work by duplicating the index page and model as "jqindex" and removing the header part...  (I just return the resulting HTML into the main results div).  However, I'm getting 2 of these "© 2017 - RazorPagesMovies".  Where is this coming from?

**Comment by pcalkins** [comment]
btw, it confused me at first, but for paths to files you omit the .cshtml part and pretend it's a directory... so for my "jqindex.cshtml" file I used ".../jqindex/".

**Comment by pcalkins** [comment]
I found it, it's in the _Layout.cshtml file.  Remove the: "   <hr />
        <footer>
            <p>&copy; 2017 - RazorPagesMovies</p>
        </footer>" part ...

**Comment by NatanRibeiro** [comment]
How can I do a POST FORM returning my page updated without to do a refresh in the whole page?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
