### ISSUE TITLE
Create reference doc for ASP.NET Core code generation tool

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#6857]
Create a reference doc for the .NET Core CLI's [aspnet-codegenerator tool](https://www.nuget.org/packages/dotnet-aspnet-codegenerator/).

**Comment by Rick-Anderson** [comment]
Update [this link](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli#scaffold-identity-into-an-empty-project) and any others that use it.

**Comment by Rick-Anderson** [comment]
Dup of #3208

**Comment by Rick-Anderson** [comment]
@scottaddie 	see  https://github.com/dotnet/docs/issues/10100
