### ISSUE TITLE
Clarify Python requirement for contributing

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#686]
Step 1 of "Building the Docs" in [CONTRIBUTING.md](https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md) mentions using at least version 2.7.10 of Python with a recommendation of version 3.4. The Getting Started video, however, on that same page references version 3.5 as the ideal version. I sense that there may be a bit of confusion for those considering contributing to the docs.

Is it safe to change the 3.4 version recommendation to 3.5? Also, does it make sense to still list version 2.7.10?

**Comment by danroth27** [comment]
@ardalis The doc is right - 3.4 or higher and 2.7.10 or higher are both fine.
