### ISSUE TITLE
Loved it.

### ISSUE THREAD

**Issue by Lavacannon67** [aspnet/Docs#6863]
I definitely enjoyed this project. I appreciated the in-depth explanation of each step and never felt confused. Good stuff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97234f18-4009-0ebf-a379-9b63125529cd
* Version Independent ID: 1bf4792d-dab4-e03d-2021-3dcdcaff6a0f
* Content: [Examine the Details and Delete methods of an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/details.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/details.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Lavacannon67  thanks for the feedback. Why did you go with MVC over Razor Pages?

**Comment by Lavacannon67** [comment]
Even though Razor Pages is a simpler, more organized framework, I wanted make myself familiar with MVC as well. My understanding is that Razor Pages is in most ways an evolution of MVC, being more efficient and clean. I just like to be well-rounded.
