### ISSUE TITLE
AddSignalR method not found

### ISSUE THREAD

**Issue by aleGuardiola** [aspnet/Docs#6865]
Hi, I followed the example but when I publish the app to azure I get
 Method not found: 'Microsoft.AspNetCore.SignalR.ISignalRBuilder Microsoft.Extensions.DependencyInjection.SignalRDependencyInjectionExtensions.AddSignalR(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
The error only appears when I use AddSignalR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778aaeae-2fa8-fb73-b644-8e99ee06398e
* Version Independent ID: 159a95c8-7afd-bb03-fdfc-2323559ef50a
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/signalr/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by davidfowl** [comment]
What does your project file look like?

**Comment by aleGuardiola** [comment]
Here is my .csproj file

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview2-final" />
  </ItemGroup>


</Project>

**Comment by aleGuardiola** [comment]
```
here is my .csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview2-final" />
  </ItemGroup>


</Project>

```

**Comment by davidfowl** [comment]
@aleGuardiola you should upgrade to the final version of ASP.NET Core 2.1 instead of using preview2. You can get started here https://dot.net

**Comment by aleGuardiola** [comment]
Ok, I will Thanks I was getting frustrated

**Comment by aleGuardiola** [comment]
Cool, It is working now thanks very much
