### ISSUE TITLE
Razor Class Library project settings behave differently locally vs deployment

### ISSUE THREAD

**Issue by rahamohebbi** [aspnet/Docs#6869]
I started playing around with the new RCL project. Everything looks fine but I am having issues to deploy my project to Prod using publish profile.

I found a way to fix the problem but if I apply the fix the project wouldn't run locally.

I can run deploy if I set **MvcRazorCompileOnPublish** to true in the RCL project.

![capture](https://user-images.githubusercontent.com/330014/40988644-78c66d24-68a0-11e8-8042-645bb4c088ab.PNG)

It is not very productive to comment and un-comment this line every time I have to deploy my project versus running it locally.

If I remove that line and try to deploy. I get  bunch of errors saying that certain namespaces are not found and I need to use 'Using' directive to fix it.

Any ideas why this is happening ?

**Comment by Rick-Anderson** [comment]
@pranavkm should I move this issue to https://github.com/aspnet/Home/issues ?

[Create reusable UI using the Razor Class Library project](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)

**Comment by Rick-Anderson** [comment]
@rahamohebbi if this is still a problem can you open an issue at https://github.com/aspnet/Home/issues
