### ISSUE TITLE
Create sample showing how to ref JavaScript/CSS inside a View Component

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#687]
see http://docs.asp.net/projects/mvc/en/latest/views/view-components.html#comment-2369574517

Is there a mechanism for referencing JavaScript or CSS files from inside the component? It would ideal to be able to add to the "sections" of the host views. Right now, with Partial Views, we have to use a workaround of registering scripts and CSS in the HttpContext and then pulling them out later when the layout renders the script section. Same thing for CSS.

The host view shouldn't need to know anything about the components script requirements ahead of time.

**Comment by danroth27** [comment]
@rynowak Is this scenario possible to do today? What would this sample look like?

**Comment by adrianhara** [comment]
+1 for this feature

**Comment by ktulufrozen** [comment]
+1 as well

**Comment by davidmdem** [comment]
+1

**Comment by Rick-Anderson** [comment]
@rynowak Is this scenario possible to do today? What would this sample look like?
@rynowak  if you can send me some code, I'll get this article updated ASAP.

**Comment by SimonOrdo** [comment]
FWIW, here is what I ended up hacking together.  Would be an awesome if comparable functionality was part of the framework.  

I opted for an OrderedDictionary so that a.) items that are added to the resource cache more than once don't get rendered more than once and b.) items are rendered in the order that they are added to the resource cache so that you don't get bungled JS references.

Utility Code:
```C#
    public enum PageResourceType
    {
        JavaScript,
        CSS
    }

 public static bool IsAjaxRequest(this HttpRequest request)
        {
            if (request == null)
                throw new ArgumentNullException("request");

            if (request.Headers != null)
                return request.Headers["X-Requested-With"] == "XMLHttpRequest";
            return false;
        }
````
IHtmlHelper extensions:
```C#
 public static HtmlString AddResource(this IHtmlHelper HtmlHelper, PageResourceType resourceType, Func<object, HelperResult> Template)
        {
            /* Usage
                        @Html.AddResource(PageResourceType.JavaScript,
                        @<script type="text/javascript">
                            $(document).ready(function ()
                            {
                                //awesome code
                            });
                        </script>
                        )
            */
            // If it's an Ajax request, then we add the data inline, immediately.  Otherwise, store it in the context and
            // retrieve when the host view is rendering similar resource reference on the page.  Warning: This can possibly
            // generate "invalid" HTML if it's a CSS resource and we end up dumping a CSS tag in the middle of the body.
            if (HtmlHelper.ViewContext.HttpContext.Request.IsAjaxRequest() && Template != null)
            {
                HtmlHelper.ViewContext.Writer.Write(Template(null));
            }
            else
            {
                OrderedDictionary<int, Func<object, HelperResult>> allItems = HtmlHelper.ViewContext.HttpContext.Items[resourceType] as OrderedDictionary<int, Func<object, HelperResult>>;
                if (allItems == null)
                {
                    allItems = new OrderedDictionary<int, Func<object, HelperResult>>();
                    HtmlHelper.ViewContext.HttpContext.Items[resourceType] = allItems;
                }

                int hash = -1;
                using (var writer = new StringWriter(CultureInfo.InvariantCulture))
                {
                    Template(null).WriteTo(writer, Microsoft.Extensions.WebEncoders.HtmlEncoder.Default);
                    hash = writer.ToString().GetHashCode();
                }

                if (!allItems.ContainsKey(hash))
                {
                    allItems.Add(hash, Template);
                }                
            }

            return new HtmlString(String.Empty);
        }

 public static HtmlString RenderResources(this IHtmlHelper HtmlHelper, PageResourceType resourceType)
        {
            if (HtmlHelper.ViewContext.HttpContext.Items[resourceType] != null)
            {
                OrderedDictionary<int, Func<object, HelperResult>> Resources = (OrderedDictionary<int, Func<object, HelperResult>>)HtmlHelper.ViewContext.HttpContext.Items[resourceType];

                for(int i = 0; i < Resources.Count; i++)
                {
                    var Resource = Resources[i];
                    if (Resource != null)
                    {
                        HtmlHelper.ViewContext.Writer.Write(Resource(null));
                    }
                }
            }

            return new HtmlString(String.Empty);
        }
```

Then, in _Layout.cshtml:

    
        @Html.RenderResources(AdminWeb.App_Helpers.PageResourceType.JavaScript)
        @Html.RenderResources(AdminWeb.App_Helpers.PageResourceType.CSS)

**Comment by Rick-Anderson** [comment]
@rynowak can you review this approach?

**Comment by kspearrin** [comment]
@SimonOrdo I'm trying to use your method for this in ViewComponents. If I try to invoke some c# code in the JS code I get errors. For example:

````
@Html.AddResource( PageResourceType.JavaScript,
    @<script>
            var foo = '@Model.Bar';
    </script>)
````

> Cannot implicitly convert type 'Microsoft.AspNet.Mvc.Razor.HelperResult' to 'Microsoft.AspNet.Diagnostics.Views.HelperResult'	Web.DNX 4.5.1

and

> Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

Do you have a workaround for this? I am not familiar with the `@<script>` syntax used here for the `Template` delegate.

**Comment by dazinator** [comment]
I was successfully using this technique for a while in RC1, but as of RC2 i'm getting an issue, which I raised here: https://github.com/aspnet/Razor/issues/795

Greatful if anyone knows why this might have broken in RC2

**Comment by Rick-Anderson** [comment]
Can you test this with RTM bits?

**Comment by dazinator** [comment]
Can do. To be honest, I'd rather be able to eliminate this code all together and for the framework to provide a mechanism so that `ViewComponent` can include html and javascript on the page. Without this, it seems like they are a bit half baked imho. Any ideas if this ability is going to be coming in the future as if so, I don't really want to waste any further time on this issue.

**Comment by Rick-Anderson** [comment]
> framework to provide a mechanism so that `ViewComponent `can include html and javascript on the page.

We plan to do that. I'll see if I can get the tracking issue.

**Comment by CodingSamurai** [comment]
+1.  Without SOME method of including JS & CSS the entire purpose of ViewComponents being an encapsulated set of functionality is defeated.

**Comment by averes2** [comment]
This is a year old issue but I seem to have run into it and can't find a solution? May be I missed it?

This is what I've done to get JS working though I'd love to be able to include a script tag directly

`<style onload='if (typeof init_component == "undefined") $.loadScript("/js/Components/top_bar_selection_popup.js", function () {
        });'> </style>`

The style tag loads and inline JS works so this seems effective to a point

**Comment by Rick-Anderson** [comment]
@rynowak can you review showing how to ref JavaScript/CSS inside a View Components

**Comment by Rick-Anderson** [comment]
@rynowak can you review showing how to ref JavaScript/CSS inside a View Components

**Comment by dazinator** [comment]
Yes please. There has been a lot of demand for this - for example see this thread: https://github.com/aspnet/Mvc/issues/2910 - the solution up until today has been roll your own solution or use orchard core framework.

**Comment by Rick-Anderson** [comment]
Per @danroth27 

>We have a story for this with Blazor components. I expect that most folks trying to do this with View Components will want to move to the Blazor component model

**Comment by MichaelJohnBradley** [comment]
I would like to see example that demonstrates having multiple of the same view components on a page/view and how or if the javascript need to be set up so that the page doesn't have functions declared multiple times. Should the javascript functions have an view component Id appended to them that would come from the viewmodel? Or should the javascript just be external to the view component and referenced on the parent page/view.

**Comment by danroth27** [comment]
The experience with View Components and working with static assets is suboptimal; we don't really have a recommended solution for this scenario using the View Component model. We understand that having a solution for composable UI is an important scenario and it's something something we want to address with the Razor Components work in ASP.NET Core 3.0. I think we should hold off on providing any official guidance for how to accomplish this scenario with View Components and instead focus our efforts getting good support with Razor Components. If folks in the community would like to document and share their View Component based solutions we would welcome that.

**Comment by dazinator** [comment]
Erm.. what kind of answer is that? Are you saying there is no solution from
the framework that gives you view components as a paradigm so lets see what
others can suggest? Its your paradigm! Show some vision please.

**Comment by danroth27** [comment]
View Components are lacking here because this wasn't a scenario they were originally designed for. Could you get creative enough to extend things to get something working? Probably and I'm sure some folks already have. But it's not something that View Componentshave first class support for. The long term vision is to provide a component model that actually has a designed way to interact with the layout and enable composition. I'm sorry to disappoint on this one but I'm trying to be realistic here.

**Comment by viktors-telle** [comment]
I ended up using this approach to execute javascript code after page content has been loaded:

[https://stackoverflow.com/a/45292644/2804621](url)

**Comment by dazinator** [comment]
@danroth27 thanks for injecting the reality of the situation into my brain. As much as it is disappointing, atleast there is hope yet RE: Razor Components so I'll look forward to those.

**Comment by mrlife** [comment]
@danroth27 Razor Components sound promising. Can they be considered an analog to View Components that includes support for `@section` blocks?

**Comment by mrlife** [comment]
@danroth27 Razor Components sound promising. Can they be considered an analog to View Components but includes support for @section blocks?

**Comment by AlbertoPa** [comment]
Does this mean that instead of being able to include simple scripts inside a view component, the proposed solution is to use server-side Blazor (aka Razor Components), which would imply the inclusion in the app of SignalR? Isn't that overkill for several use cases?

**Comment by dazinator** [comment]
It's been a while since I touched razor, have been in Blazor SPA world. Is the outcome to this in dotnet8, to use razor components and SSR?
