### ISSUE TITLE
Sample download link broken

### ISSUE THREAD

**Issue by MohanVijayakumar** [aspnet/Docs#6872]
Getting 404 response from github when clicks the download sample link "https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authentication/cookie/sample"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rachelappel** [comment]
I think the sample link should be this one https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authentication/cookie/samples/2.x/CookieSample

**Comment by guardrex** [comment]
Thanks @MohanVijayakumar! ... The sample was just updated and the link broke on the update. I'll fix it now.
