### ISSUE TITLE
Hosting as a windows service no longer requires .NET Framework

### ISSUE THREAD

**Issue by gregbair** [aspnet/Docs#6876]
In the "Prerequisites" section, the first sentence is: "The app must run on the .NET Framework runtime." This seems to no longer be the case. I used this guide to host a .NET Core 2.0/ASP.NET Core 2.0 app as a Windows service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hi @gregbair ... The sample is undergoing an update to 2.1 as we speak on #6860, so we'll address this on the PR. Thanks for reporting this.
