### ISSUE TITLE
Slow Razor Build Times

### ISSUE THREAD

**Issue by barrettg** [aspnet/Docs#6880]
After following the instructions and upgrading my project to 2.1, I am experiencing very slow build times (+40 seconds).  Using the command "dotnet build --no-incremental --no-restore /clp:performancesummary", it says that RazorCoreCompile and ResolveTagHelperRazorGenerateInputs are occupying about 20 seconds each of the build time.  Is there something I can do to improve this? I am using Razor Pages and the new Razor Identity Library in my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm  should I move this to  aspnet/home ?

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Home/issues/3199
