### ISSUE TITLE
The use of ApiBehaviorOptions attribute needs additional information

### ISSUE THREAD

**Issue by Eneuman** [aspnet/Docs#6881]
It's essential that the 
services.Configure&lt;ApiBehaviorOptions&gt;(options =&gt;
{...}
code is added AFTER app.UseMvc(); otherwise it will not work.
The user could also use PostConfigure instead of Configure like this:
services.PostConfigure&lt;ApiBehaviorOptions&gt;(options =&gt;
{...}
to make sure the options are added last in the pipline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@guardrex Do we have `services.PostConfigure` ☝️ documented anywhere? If not, we should add it to one of the existing docs.

**Comment by guardrex** [comment]
Yeah ... it's over in the Options topic :point_right: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1#ipostconfigureoptions

That predates moniker ranges, so I'll do a quick patch on it now.

**Comment by scottaddie** [comment]
@Eneuman Thank you for bringing this to our attention. The changes are live now.
