### ISSUE TITLE
Incorrect examples about IncludeScopes in appsettings.json 

### ISSUE THREAD

**Issue by NiekGr** [aspnet/Docs#6883]
Dear maintainers,

I had some problems with getting Asp.Net Core 2.1 to include scopes when logging. I added ``"IncludeScopes: true``, just as some examples here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1&tabs=aspnetcore2x.
But I found out via https://github.com/aspnet/Logging/issues/835 that this line should be added in the ``"Console"`` scope of appsettings.json.

Thanks in advance.

Regards,

NiekGr

**Comment by guardrex** [comment]
Yes, @NiekGr ... that's correct. We just haven't reached this topic and sample yet with the 2.1 updates.

https://github.com/aspnet/Docs/issues/5495

We'll get to it asap. Thanks for commenting.

**Comment by guardrex** [comment]
Let's go ahead and patch it for now. A quick update to the appsettings files should be enough.
