### ISSUE TITLE
ServerTimeout 

### ISSUE THREAD

**Issue by mmfarahat** [aspnet/Docs#6885]
how to set "HubConnection.ServerTimeout" in javascript client , like .net client

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
Hello @mmfarahat, Great question! Here's a sample you should be able to use now. We will be publishing a document on [Configuration](https://github.com/aspnet/Docs/issues/6599) soon that will have this in it. 

const connection = new signalR.HubConnection(
    "/chathub",
    {  serverTimeout: 100  });

**Comment by BrennanConroy** [comment]
For the javascript client you can set the timeout after the connection has been created.
```javascript
const connection = new signalR.HubConnectionBuilder()
    .withUrl("/chatHub")
    .build();

connection.serverTimeoutInMilliseconds = 1000; // 1 second
```

**Comment by mmfarahat** [comment]
@rachelappel , @BrennanConroy  Thanks

**Comment by imsam67** [comment]
I believe the `serverTimeoutInMilliseconds` should have a larger value than the `KeepAlive` which is set on the server side. Is this correct?

**Comment by BrennanConroy** [comment]
That's correct, if `serverTimeoutInMilliseconds` is smaller than the keep alive on the server then it's very likely your client will think the server is gone and close.
