### ISSUE TITLE
signalr/hubs Add details around lifetime

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Docs#6888]
Hub instances are alive only for the duration of the method being invoked on them. That means non-static state can't be stored on them, and accessing the hub after the method exits (via a non-awaited task) will result in undefined behavior.

We should add a section or some notes about this in the hubs doc.

**Comment by wimvanhouts** [comment]
Is it possible to also add an example then how to notify clients connected to the hub from another object (e.g. how do I push an incoming mesage from a MQ to my clients, but many examples exist)? It seems this was available in the old documentation, but, is not yet available for ASP.NET Core 2.1 SignalR.

**Comment by wimvanhouts** [comment]
Update of my own question: the example exists for ASP.NET Core 2.1 exists in the Azure documentation located at https://github.com/aspnet/AzureSignalR-samples/tree/master/samples/FlightMap ... you might want to reuse that since it will be a common use case
