### ISSUE TITLE
Both linux tutorials should suggest using etc/hosts file as an option for testing with a domain name

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#6889]
Before your domain is registered, and to save the trouble of setting up Bind9 as a DNS, I think there should be a line at the beginning of both linux tutorials reminding the reader that for testing purposes you can use etc/hosts file to temporarily test your domain name in the tutorials.

**Comment by guardrex** [comment]
@shirhatti ... sound good?

**Comment by Rick-Anderson** [comment]
@user135711 	can you provide links to the two tutorials?
@shirhatti 	 you ok with

> Before your domain is registered, and to save the trouble of setting up Bind9 as a DNS, I think there should be a line at the beginning of both linux tutorials reminding the reader that for testing purposes you can use etc/hosts file to temporarily test your domain name in the tutorials.

**Comment by guardrex** [comment]
* https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx
* https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-apache

**Comment by Rick-Anderson** [comment]
Moved to #10587
