### ISSUE TITLE
exists in the templates of Area:exists needs explanation

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#6890]
In the [Area tutorial](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)  the `exists` delimiter needs to be explained. What exactly happens with vs without :exists in the line:
`template: "{area:exists}/{controller=Home}/{action=Index}/{id?}");`
The only thing I could find was an explanation by joonas/juunas on [stackoverflow](https://stackoverflow.com/questions/44260468/what-does-exists-do-on-a-route-template) that didn't make any sense to me.

**Comment by Rick-Anderson** [comment]
@rynowak  please comment.

**Comment by Rick-Anderson** [comment]
@rynowak  

> In the [Area tutorial](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)  the `exists` delimiter needs to be explained. What exactly happens with vs without :exists in the line:
`template: "{area:exists}/{controller=Home}/{action=Index}/{id?}");`

**Comment by rynowak** [comment]
Here's the historical context 👍 

Basically:
1. The area route needs to go first for link generation to work
2. If you have an area route declared, but don't have any controllers/actions in the area then things will match that shouldn't.

So this feature exists to make it possible to define the area route when you don't have any controllers in an area, basically for us to be able to put an area route in the template 😆 

@Rick-Anderson - if this is featured prominently in docs, we should de-emphasize it. It's a dusty corner of the framework that not many need to visit.

**Comment by user135711** [comment]
Perhaps a simple concrete single example in the docs of a link matching incorrectly without :exists and what matches after adding :exists would make it clear. One line examples always make more sense than trying to describe something with long paragraph descriptions.

**Comment by Rick-Anderson** [comment]
Fixed in #10978
