### ISSUE TITLE
issue with terminal input

### ISSUE THREAD

**Issue by yinanhu296** [aspnet/Docs#6892]
I'm not sure if I missed anything, but when I run "dotnet new webapp" on my terminal it says "No templates matched the input template name: webapp"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d466934-744e-673c-18a2-e312b04d7b28
* Version Independent ID: f52b6f6d-5aaf-c515-22af-a0aeaaf9b8e1
* Content: [Get started with Razor Pages in ASP.NET Core on macOS with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@yinanhu296  that tutorial requires .NET SDK 2.1

**Comment by bcisnero** [comment]
Change the command "dotnet new webapp for dotnet new razor" if you are using core 2.0

**Comment by Rick-Anderson** [comment]
See #6939
