### ISSUE TITLE
Split dynamic loading section into separate document

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Docs#6896]
This document describes how to use IHostingStartup in a completely dynamic way but fails to describe the HostingStartup assembly attribute that can point to types in existing referenced libraries. https://github.com/aspnet/Hosting/blob/8377d226f1e6e1a97dabdb6769a845eeccc829ed/samples/SampleStartups/StartupInjection.cs#L8

We should talk to about the IHostingStartup feature, what it does and then describe the various ways to consume it starting from the very simple attribute to the dynamic additional deps way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a759e56-4ba4-c464-ae74-e2705df72811
* Version Independent ID: 7a4ee224-ce61-ac3f-6b60-88c7a5a24f2c
* Content: [Enhance an app from an external assembly in ASP.NET Core with IHostingStartup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/platform-specific-configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/platform-specific-configuration.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
Also how did this topic end up under Configuration? It's a hosting feature and has nothing to do with configuration. We should move it as well.

**Comment by guardrex** [comment]
Move it to the *Host* node? https://docs.microsoft.com/aspnet/core/fundamentals/host

**Comment by guardrex** [comment]
Also need to describe the new exclusion machinery. https://github.com/aspnet/Hosting/pull/1243
