### ISSUE TITLE
Mention gelf extension

### ISSUE THREAD

**Issue by tomap** [aspnet/Docs#6897]
Hi,

Could you also mention https://github.com/mattwcole/gelf-extensions-logging as it's already mentionned here: https://github.com/aspnet/Logging#providers

Here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?view=aspnetcore-2.1&tabs=aspnetcore2x#third-party-logging-providers

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/index?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Cross-ref: https://github.com/aspnet/Logging/pull/680
