### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#69]
ASP.NET 5->Fundamentals->Caching
- In memory cache

**Comment by ardalis** [comment]
Working on this now, @danroth27

**Comment by ardalis** [comment]
Unless I'm missing something, Output Caching is an MVC feature, @danroth27

**Comment by ardalis** [comment]
Opened #733 for Output Caching.
@danroth27 Need to meet to discuss this topic and whether it makes sense to split Distributed Caching and Redis into a separate article (in memory cache article is already about 4-5 pages long).
