### ISSUE TITLE
ASP.NET Core 2.1 - Remove routes

### ISSUE THREAD

**Issue by JValck** [aspnet/Docs#6902]
By default all the available routes are provided OOTB.
What if I only want the users to access: 
- Account\AccessDenied
- Account\ForgotPassword
- Account\Logout
- Account\Login
- Account\ResetPassword (and its corresponding confirmation route)
All possible accounts are set up in a seeder. The other routes should not be available.

How does one configure this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3ac09f0-74ca-1a5d-4fec-695b84c1ac95
* Version Independent ID: cd2c1f5e-e4f0-d2c3-4737-8ff4f0c176c2
* Content: [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-configuration.md)
* Product: **asp.net-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **scaddie**

**Comment by HaoK** [comment]
This one is prob for @javiercn as its behavior from the UI

**Comment by javiercn** [comment]
You don't.

The default UI is all or nothing. If you want a subset of the functionality you remove the default UI, scaffold the bits you want, and tweak the code/configuration to suit your needs.

**Comment by javiercn** [comment]
I haven't seen the docs for the default UI. Can you point me to them?

**Comment by scottaddie** [comment]
@javiercn Please see https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1.

**Comment by javiercn** [comment]
@scottaddie Thanks.
I've looked at it and filed https://github.com/aspnet/Docs/issues/6915

**Comment by JValck** [comment]
@scottaddie @javiercn In my opinion this is not clearly explained in [https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1](https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1).

I did some research and came across [this issue](https://github.com/aspnet/Identity/issues/1706). I updated the `startup.cs] file in a newly created project.
**OLD**
```
services.AddDefaultIdentity<IdentityUser>().AddEntityFrameworkStores<ApplicationDbContext>();
```
**NEW**
```
services.AddIdentity<IdentityUser, IdentityRole>().AddEntityFrameworkStores<ApplicationDbContext>();
```
Now only the selected scaffolded items are available. I did not scaffold the register page to verify if it is doing what I want. And... it is!
Small problem: the url of the register route is displayed as: `https://localhost:44365/?area=Identity&page=%2FAccount%2FRegister` which is not that clean.
Is there anyway to solve this.

**Comment by scottaddie** [comment]
@Rick-Anderson Please see the feedback above from @JValck. Thoughts on making this clearer?

**Comment by javiercn** [comment]
> Small problem: the url of the register route is displayed as: https://localhost:44365/?area=Identity&page=%2FAccount%2FRegister which is not that clean.
> Is there anyway to solve this?

Did you move the pages out of the area? You probably need to change the links in your cshtml files to remove the area if that's the case. I'm not sure I understand what you are doing. A small repro would help me point you out in the right direction.

**Comment by JValck** [comment]
Steps to reproduce:
- create a new MVC project with authentication enabled (.NET core 2.1)
- Scaffold the Login and Logout
- Click the register button in the navbar

Also, how is it possible to change the logic in the controllers?

**Comment by javiercn** [comment]
@JValck I can't reproduce this. Can you provide what versions are you using by including the contents of the csproj file and the information produced by dotnet --info?

Thanks.

**Comment by javiercn** [comment]
@JValck As per changing the logic in the pagemodels, you can override the view and modify it to add your own redirection logic.

**Comment by JValck** [comment]
@javiercn Dump `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Contents `.csproj`:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>aspnet-example-4542A42C-9CCE-4983-91CA-9A7B8AEB168D</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Migrations\20180607064713_FirstDatabaseScheme.cs" />
    <Compile Remove="Data\Migrations\20180607064713_FirstDatabaseScheme.Designer.cs" />
    <Compile Remove="Data\Migrations\20180607074446_CreateDatabaseStructure.cs" />
    <Compile Remove="Data\Migrations\20180607074446_CreateDatabaseStructure.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="2.8.391" />
    <PackageReference Include="FirebirdSql.Data.FirebirdClient" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\Services\" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Areas\Administration\Views\Home\Index.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>

</Project>
```
