### ISSUE TITLE
IIS Hosted ASP.NET Core 2.0 Application AlwaysOn

### ISSUE THREAD

**Issue by orionstudt** [aspnet/Docs#6905]
Hi,

Is there any documentation for setting an ASP.NET Core 2.0 application to be AlwaysOn when hosted in IIS? Is there any application-side configuration or is it strictly on the IIS side via existing documentation [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc772112(v=ws.10))?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for asking @orionstudt. It's on the backlog, and there's a lively discussion (a wide discussion of App Pool 'warming' concepts and app 'warming' concepts) that you're welcome to participate in over in the IIS Integration repo: https://github.com/aspnet/IISIntegration/issues/507.

In the meantime for docs, I think we should address it. We're still working 2.1 issues, and that will keep us busy for a short time. I'll get to this asap, and let's use this issue to track the work.

**Comment by orionstudt** [comment]
Thanks for the response, @guardrex. It seems the issue I'm experiencing with my setup is what was concluded in the issue you linked - that the Application Pool starts, warms up Kestrel, and is "AlwaysRunning," but that Kestrel shuts down at some point independent of the Application Pool & needs to be warmed up again on next request.

Resolving that has apparently become a feature request so understandably that will take time, but in the meantime having a single doc page that has the information on the current state of "app warmup" for aspnetcore will be nice - since it seems there is something Kestrel-specific going on there. Thanks again!

**Comment by guardrex** [comment]
Yes ... and devs have worked around it with health check pings (AppInsights, Pingdom, etc.) and custom apps (e.g., one or more Windows Services to "warm" their apps).

I'll surface some coverage with the engineering team's input.

**Comment by alohaninja** [comment]
AlwaysOn + Application Initialization is a priority for our team - hoping to see these two issues get addressed - preloading the application is critical for multiple daily CI/CD.

**Comment by thurfir** [comment]
To bad this got excluded from the Q3 release: while pings works as a workaround, there are far from ideal when working with multiple services. This is expecially true during developpement when you have to keep track of which services to wake-up for every possible scenario and pray they won't go down again..

Hoping you'll consider this for Q4!

**Comment by guardrex** [comment]
@thurfir Thanks for your feedback, but the engineers won't see it here on the docs repo. You should probably move that over to https://github.com/aspnet/IISIntegration/issues/507.
