### ISSUE TITLE
Perform Initial Migration

### ISSUE THREAD

**Issue by geekRiddle** [aspnet/Docs#6906]
When doing the initial migration I encounter errors using either command:

_Add-Migration Initial_ gives me:
The specified deps.json [\\\\server\share\MyDocs\Visual Studio 2017\Projects\RazorPagesMovie\RazorPagesMovie\bin\Debug\netcoreapp2.1\RazorPagesMovie.deps.json] does not exist

Yet, The file does exist in that path.

Then, if I try _dotnet ef migrations add Initial_  I get:
MSBUILD : error MSB1009: Project file does not exist.
Switch: \\\\server\share\MyDocs\Visual Studio 2017\Projects\RazorPagesMovie\RazorPagesMovie\RazorPagesMovie.csproj
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

So I do a cd to the RazorMoviePages directory  which has the .csproj and still get the same error.

I've seen these errors mentioned online but have yet to find a solution.  I'm using Visual Studio 2017 15.7.3.  Any help would be greatly appreciated!

**Comment by Rick-Anderson** [comment]
See the suggestions under https://github.com/aspnet/EntityFrameworkCore/issues/7077#issuecomment-287701871
I've seen this error reported before. Something is wrong with VS. It looks like the code is on share - that might complicate solving the problem.

Try creating a new project and running migrations on it.
```
dotnet new webapp -au Individual  -o MyApp
cd MyApp
dotnet ef migrations add Initial
dotnet ef database update
```

**Comment by geekRiddle** [comment]
I moved the code to a local path and that fixed it.  Thank you for your help with this!
