### ISSUE TITLE
Undocumented breaking change in IApplicationBuilder.UseExceptionHandler()

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Docs#6909]
The migration guide doesn't notice anything about UseExceptionHandler. Usage of a simple call `app.UseExceptionHandler()` in one's `Startup.Configure` will fail at runtime with the exception:
System.InvalidOperationException: 'An error occurred when configuring the exception handler middleware. Either the 'ExceptionHandlingPath' or the 'ExceptionHandler' option must be set in 'UseExceptionHandler()'.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The templates use the overload of [UseExceptionHandler](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.exceptionhandlerextensions.useexceptionhandler?view=aspnetcore-2.1) that takes an `errorHandlingPath` parm
` app.UseExceptionHandler("/Error");`

@Tratcher this seems like an edge case with great error message. Should this be added to doc?

**Comment by Tratcher** [comment]
See https://github.com/aspnet/Diagnostics/issues/400. This wasn't a breaking change per-se, it didn't work before either. 2.1 added an exception to explain why it is mis-configured.
