### ISSUE TITLE
Where did GetErrorMessage() come from?

### ISSUE THREAD

**Issue by gojanpaolo** [aspnet/Docs#6910]
Where did GetErrorMessage() come from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **asp.net-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's in the sample in the *ClassicMovieAttribute.cs* file:

https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation/sample/ClassicMovieAttribute.cs#L55-L58

**Comment by guardrex** [comment]
I'll pop the lines into the topic where it mentions the `ValidationResult`.
