### ISSUE TITLE
Fucking DisplayNameFor with PaginatedList

### ISSUE THREAD

**Issue by nl20121974** [aspnet/Docs#6913]
I can't believe You did not resolve the Html.DisplayNameFor for PaginatedList. U don't give us a fully integrated solution to your own system, just in the official Microsoft docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [ASP.NET Core MVC with EF Core - Sort, Filter, Paging - 3 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
https://dotnetfoundation.org/code-of-conduct
