### ISSUE TITLE
Additional topics to cover in the default Identity UI doc

### ISSUE THREAD

**Issue by javiercn** [aspnet/Docs#6915]
Our default templates use IdentityUser as a starting point. There are a few steps you need to take when switching to use a custom user.
* Update the DbContext
* Update Startup
* Update _LoginPartial.cshtml
* Add Migration?
* Update the DataBase?

Could you take a look into adding a section in the default Identity UI topic that covers the steps required here?

**Comment by Rick-Anderson** [comment]
@javiercn  I believe this is all covered in [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=netcore-cli)
