### ISSUE TITLE
Link doesn't show how to install for core 2.0

### ISSUE THREAD

**Issue by joearmonic** [aspnet/Docs#6916]
The link 'installed the updated React project template' doesn't send us to a page that explains how to install the new templates for .net core 2.0. I remember that is as simple as adding a nuget package with the cli, but I don't know exactly its name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3154dec-545a-c749-76ac-1f4581c2f922
* Version Independent ID: cd33922a-0feb-2a37-4e8e-6d7856617a31
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/react?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@joearmonic The link in the doc is going to the wrong place. I'll fix it right now. Here's where it should go: https://docs.microsoft.com/en-us/aspnet/core/spa/index?view=aspnetcore-2.0#installation.
