### ISSUE TITLE
Now that ASP.NET Core 2.1 has been released is Generic Host recommended over Web Host for non-web apps?

### ISSUE THREAD

**Issue by connorads** [aspnet/Docs#6917]
> At this time, developers should use the Web Host based on IWebHostBuilder for hosting ASP.NET Core apps.

Now that ASP.NET Core 2.1 has been released is Generic Host recommended over Web Host for non-web apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c04398-d05e-490a-30b9-e677804012f5
* Version Independent ID: a534ebf2-ca56-d352-401e-5f3d01b30ac0
* Content: [Host in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/index.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting. When we wrote "at this time," we actually meant to include the 2.1 release. I asked `@DamianEdwards` ([Community Standup 6/5/18 33:20](https://youtu.be/LCV-JNOkZC4?t=33m20s)) about this, and he said that the Generic Host *probably* won't replace the Web Host until 3.0.

@Tratcher We could modify our sentence about this and make it more specific. Today, it reads ...

> The Generic Host will eventually replace the Web Host.

We could go with ...

> The Generic Host will eventually replace the Web Host, probably with the release of ASP.NET Core 3.0.

**Comment by connorads** [comment]
Thanks for the clarification about Generic Host replacing Web Host @guardrex

However, I'm still a little unsure about the guidance on using Generic Host in 2.1 specifically for **non-web/HTTP** related apps .
> At this time, developers should use the Web Host based on IWebHostBuilder for hosting ASP.NET Core apps.

Is this guidance still valid now that 2.1 is released?
If so, when should Generic Host be used? Does it mean that Generic Host should not be used until 3.0+?
If so, why? Is Generic Host not considered prod-ready until 3.0+, even for non-web/HTTP apps?

**Comment by guardrex** [comment]
Yes, you should be able to use it for non-web apps.

I'll defer to @Tratcher and @davidfowl to let us know if we need to be more specific than the current language on that point.

Thus far, here's the proposed revision that includes a mention of *when* the Generic Host *might* take over (the end of the last line) ...

> Generic Host (ASP.NET Core 2.1 or later) – Suitable for hosting non-web apps (for example, apps that run background tasks). In a future release, the Generic Host will be suitable for hosting any kind of app, including web apps. The Generic Host will eventually replace the Web Host, probably with the release of ASP.NET Core 3.0.

... and let's add the word "web" to this line ...

> At this time, developers should use the Web Host based on IWebHostBuilder for hosting ASP.NET Core **web** apps.

**Comment by Tratcher** [comment]
@DamianEdwards, you don't want to commit to a specific version for this, correct?

**Comment by DamianEdwards** [comment]
I wouldn't mention it at all in docs. It's not committed. WebHost is for web apps, generic host is for other apps. That's it.

**Comment by guardrex** [comment]
> generic host is for other apps

I guess you mean "production apps." Let me know if that's incorrect.

We still haven't clarified the choice for non-web apps. What's the deciding factor(s) on which one to use? That's what @connorads is asking. https://github.com/aspnet/Docs/issues/6917#issuecomment-395416452

**Comment by davidfowl** [comment]
Let me clarify what @DamianEdwards means:

- Both APIs are product ready and for production applications..
- The WebHost should be used for web applications
- The GenericHost should be used for non web applications (background processing etc)

You can run background tasks inside of either but you cannot host a webserver inside of the GenericHost (unless you wrote something custom).

**Comment by guardrex** [comment]
I got u. The PR covers your three points. I think we're good, but you might want to eyeball it just to make sure :point_right: #6922
