### ISSUE TITLE
Not being able to use partial views from outside the RCL is a major limitation

### ISSUE THREAD

**Issue by joeaudette** [aspnet/Docs#6918]
"For content outside the RCL, the ASP.NET Core runtime does not search for partial files in the RCL."

Why is this? Is there any way to make it look there or override that behavior? For example I have an RCL that provides some common shared stuff like alerts and the alert view is naturally a partial but I'm unable to shared it from my RCL and that is very disappointing.  I've been using embedded views in 2.0 and was looking forward to changing to all pre-compiled views in my libraries. But now consumers of my library won't be able to use the partial view unless they continue using it as an embedded view or copy it local to their app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92ffa7c-fd65-7dc3-194e-6a67a8a7f176
* Version Independent ID: 2df11a37-d64e-6353-bd92-0b7729070c3e
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/mvc/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/razor-pages/ui-class.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by pranavkm** [comment]
> For content outside the RCL, the ASP.NET Core runtime does not search for partial files in the RCL.
> For example, in the sample download, the RazorUIClassLib/Areas/MyFeature/Pages/Shared/_Message.cshtml partial view can not be referenced in WebApp1\Pages\About.cshtml. 

@Rick-Anderson that's actually not true. You should be able to resolve views from class libraries just fine.
