### ISSUE TITLE
Error IE9 signalr

### ISSUE THREAD

**Issue by alesendoh** [aspnet/Docs#6919]
## General

I getting error while connecting on IE9:

![image](https://user-images.githubusercontent.com/39783011/41110149-b473529a-6a46-11e8-9fef-fa9b8206397b.png)

while IE10 its ok:

![image](https://user-images.githubusercontent.com/39783011/41110175-c4336d28-6a46-11e8-90d0-9646ef18ae77.png)

My code client angular:

this._hubConnection = new signalR.HubConnectionBuilder()
        .withUrl('http://localhost:90/notify')
        .configureLogging(signalR.LogLevel.Trace)
        .build();

    this._hubConnection
      .start()
      .then(() => console.log('Connection started!'))
      .catch(err => console.log('Error while establishing connection :('));

Thanks you.

**Comment by alesendoh** [comment]
I think that was fixed add:

 import 'core-js/es6/typed';

Into polyfills.ts,

**Comment by Rick-Anderson** [comment]
@anurse  is IE9 supported?

**Comment by davidfowl** [comment]
IE9 is not supported. IE11 is the minimum supported IE version

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/supported-platforms?view=aspnetcore-2.1
