### ISSUE TITLE
TagHelper not found 

### ISSUE THREAD

**Issue by Dallas411** [aspnet/Docs#6920]
This taghelper seem does not  work with a pure mvc app project but only on Razor Pages. 
I add this 
@addTagHelper Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper, Microsoft.AspNetCore.Mvc.TagHelpers
in _ViewImports file and now works fine.
I'm wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4c23ba-19f6-d847-fefa-a61e283d5fde
* Version Independent ID: e7df465a-5f3b-1522-b2d9-5e3afbf74257
* Content: [Partial Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@Dallas411 The Partial Tag Helper does work with MVC projects. In fact, it's used in the *_Layout.cshtml* file of the MVC project template:

```cshtml
<partial name="_CookieConsentPartial" />
```

Please confirm that the project in which you're trying to use the Partial Tag Helper is on ASP.NET Core 2.1. 2.1 is the release that introduced this Tag Helper.

You're also correct that the Tag Helper has to be registered in the *_ViewImports.cshtml* file:

```cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

The preceding line registers the built-in Tag Helpers for use.
