### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TonyGerace** [aspnet/Docs#6933]
The "View or download the CommandLine configuration sample" gives 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @TonyGerace ... I just put the fix in on those links. Two links had casing problems in a URL segment ("docs" when it should have been "Docs"). One link further down was missing a URL segment ("configuration").

The samples link for this topic will be updated to ...

https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/configuration/index/sample

**Comment by TonyGerace** [comment]
Appreciate the fast fix!

**Comment by guardrex** [comment]
🏃 🏃 🏃 😅
