### ISSUE TITLE
Code generation for REST API

### ISSUE THREAD

**Issue by reberinformatik** [aspnet/Docs#6940]
Please show a real world example with REST URLs. The TodoController supports only CRUD operations. But what, when you add a "Details" or a "Search" action?
i.e.
api/todo/1/details
api/todo/search?isComplete=true

In my experience, this will break a clean code generation (MultipleClientsFromOperationId used): We end up having a "TodoClient", a "DetailsClient" and a "SearchClient" which is not what we want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by RSuter** [comment]
Why would this not generate a "nice" client? I expect that this will generate the following operations with the following operation ids: 

- Todo_Get
- Todo_GetDetails
- Todo_Search

Which will then translate in one TodoClient with three methods (Get, GetDetails, Search)

**Comment by RSuter** [comment]
I think NSwag.SwaggerGeneration.AspNetCore is fairly stable and safe to use via middleware (there are still some problems when using it via CLI but that's another story). With Swashbuckle, you can implement a custom operation filter and transform/generate the operation ids as expected. Probably there is already sample code for this somewhere as most code gens expect the operation in the form controller_operation (e.g. AutoRest, NSwag, swagger-codegen)
