### ISSUE TITLE
Must add reference to Microsoft.VisualStudio.Web.BrowserLink package

### ISSUE THREAD

**Issue by psijkof** [aspnet/Docs#6941]
I had to manually add a nuget packet reference to Microsoft.VisualStudio.Web.BrowserLink in ASP.NET Core 2.1 Web application. Also must add 'using ' statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1fa9-004b-0be3-6148-e8c075e5b2bc
* Version Independent ID: 78a1947e-dea7-65b4-2376-05c7795e4bf9
* Content: [Browser Link in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/client-side/using-browserlink.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-browserlink.md)
* Product: **asp.net-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@psijkof In which file did you have to add the `using` statement? I haven't been able to reproduce this.

**Comment by psijkof** [comment]
I'm using VS 2017 CE 15.7.3
New project, ASP.NET Core Web App, Web App.
In Startup.cs, Configure method, 
app.UseBrowserLink() does not resolve.
To resolve, must add reference to said nuget package and add using statement manually in startup.cs.
