### ISSUE TITLE
How to share an ASP.NET Core cookie with an ASP.NET 4.x VB application

### ISSUE THREAD

**Issue by pettno** [aspnet/Docs#6942]
I tried implementing a ConfigureAuth method based on C# code provided here, without any luck so far. My VB application targets .NET Framework 4.7 but the UseCookieAuthentication method is not a member of IAppBuilder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99307104-c0d7-3e82-f0b2-af61dcfe072a
* Version Independent ID: 315c02cb-54c4-e386-da85-6e4311ca10c2
* Content: [Share cookies among apps with ASP.NET and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/cookie-sharing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cookie-sharing.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
