### ISSUE TITLE
With 2.1, content of Program.cs is slightly different than what's shown in this doc

### ISSUE THREAD

**Issue by balachir** [aspnet/Docs#6943]
With 2.0
```
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }
```
With 2.1
```
            CreateWebHostBuilder(args).Build().Run();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @balachir - Yes, we haven't reached this doc yet for update. We should be getting to it soon. The work is being tracked by https://github.com/aspnet/Docs/issues/5495.

**Comment by balachir** [comment]
Sounds good, thanks @guardrex !
