### ISSUE TITLE
Great document! However, there is a missing piece.

### ISSUE THREAD

**Issue by JDebro** [aspnet/Docs#6945]
This is a great document. However, it would be nice to include information regarding the configuration for OAuth.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by JDebro** [comment]
This resolved the problem I was facing: https://stackoverflow.com/questions/43447688/setting-up-swagger-asp-net-core-using-the-authorization-headers-bearer

However, this would be a great add to the document.

**Comment by zuckerthoben** [comment]
In general this documentation is meant to give you a good start with the two mentioned toolsets, therefore it should not duplicate the already existing full documentation of the two (in my opinion). 

The NSwag Documentation already contains this topic, see
https://github.com/RSuter/NSwag/wiki/Middlewares

After a quick search I could not find the equivalent documentation for Swashbuckle, so I would suggest to add it there first.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
