### ISSUE TITLE
Wait till WebSocket connection is established

### ISSUE THREAD

**Issue by ferronsw** [aspnet/Docs#6948]
SignalR is working great except one thing. I establish a connection on document ready

$(document).ready(function () {
    const connection = new signalR.HubConnectionBuilder()
        .withUrl("/widgetHub")
        .build();
    
    connection.on("ReceiveEmailCount", (userId) =&gt; {
        console.log("UserId via SignalR:" + userId);
    });

    connection.start().catch(err =&gt; console.error(err.toString()));
    connection.invoke("GetEmailCount").catch(err =&gt; console.error(err.toString()));

});

The invoke is called after the connection.start(), but the connection is not established before the connection.invoke is called.
Because of this I get the error "Error: Cannot send data if the connection is not in the 'Connected' State."

If I build a delay for the execution of connection.invoke it works perfectly, but I don't want to wait longer than necessary.
Is there a way to wait till the WebSocket connection is established? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by BrennanConroy** [comment]
Yes, the `start` and `invoke` functions are async so you can `await` them or do `.then(() => connection.invoke(...))`

**Comment by ferronsw** [comment]
@BrennanConroy when I use await I get an error that the start and invoke function are not async...
The .then(() => is working perfectly thanks!

**Comment by rachelappel** [comment]
Closing as answered. Re-open if you have more issues.
