### ISSUE TITLE
Dependency injection: Hub lifetime

### ISSUE THREAD

**Issue by shatl** [aspnet/Docs#6949]
When registering Hub with DI, which lifetime should be specified?
Should it be Singleton or PerRequest?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by bcisnero** [comment]
For this particular use case, singleton, because each hub object provides a client to establish the communication between them so you only need one instance per hub.

**Comment by shatl** [comment]
If i understand correctly, Hubs does not have any state by default and can be registered as Singleton unless I (developer) introduce state or per-request dependency. 
Is this statement correct?

**Comment by davidfowl** [comment]
Hubs are transient. They are created per invocation not per connection. Adding it as transient is fine

**Comment by rachelappel** [comment]
Closing as answered, but if more questions pop up, feel free to re-open.

**Comment by glebkozh** [comment]
@davidfowl 
And what if I'd like to have some dependency injected in hub with connection scope? Is there any lifetime scope that is associated with connection itself? Or can I somehow create child scope for connection and resolve hub instances and their dependencies manually using this scope?
Thanks!

**Comment by davidfowl** [comment]
> And what if I'd like to have some dependency injected in hub with connection scope?

No but you can create one and stick the scope in the `Connection.Items` property bag in `OnConnectedAsync`, then you can dispose the scope in `OnDisconnectedAsync`. Hub instances can't be connection scoped.

**Comment by glebkozh** [comment]
@davidfowl I see, thank you
Am I right that the only solution is to resolve hub dependencies manually inside hub using lifetime scope stored in `Connection.Items`? Ideally I've wanted to get hub instance itself resolved via custom lifetime scope object. I can create scope, for example, in `OnConnectedAsync` of `HubDispatcher`, but it seems that I won't be able to access the scope in `HubActivator` `Create` method as it is unaware of connection-relevant information.

**Comment by davidfowl** [comment]
Yea that's not possible today.
