### ISSUE TITLE
What will be the order of middleware execution?

### ISSUE THREAD

**Issue by kiranj321** [aspnet/Docs#6951]
Middleware in configure method is executed in sequence. If I implement a middleware using IHostingStartup abstraction and use it in my project, when will this get executed? What if I want to include this only in development and after exception handler is executed? 

Here is the configure in your example:
```
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();
            app.UseMvc();
        }
```

And here is the configure implementation of the StartupDiagnosticsHostingStartup 
```
public Action<IApplicationBuilder> Configure(Action<IApplicationBuilder> next)
        {
            return app =>
            {
                // Use a terminal middleware that branches on a request for
                // /services. The middleware uses a factory to obtain the services
                // registered for the app and outputs them in a webpage.
                app.Map("/services", builder => builder.Run(async ctx =>
                {
                    // Make sure this only runs in the Development environment.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a759e56-4ba4-c464-ae74-e2705df72811
* Version Independent ID: 7a4ee224-ce61-ac3f-6b60-88c7a5a24f2c
* Content: [Enhance an app from an external assembly in ASP.NET Core with IHostingStartup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/platform-specific-configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/platform-specific-configuration.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
See: https://github.com/aspnet/Hosting/blob/ddb1bfeb201a75248d11efe415ebce9be183c127/src/Microsoft.AspNetCore.Hosting.Abstractions/IHostingStartup.cs#L17

@davidfowl, why does it say "intended" and not just "Configure is called before user code ..."?

**Comment by kiranj321** [comment]
@guardrex thanks. What happens if I include another IHostingStartup implementation like StartupDbVerifierHostingStartup? Which one will get executed first? StartupDiagnostics or StartupDbVerifierHostingStartup?

**Comment by guardrex** [comment]
Good question ... it might be in order provided in the hosting startup assemblies host configuration (in the sample, it comes from the env var). Let's see what @davidfowl says. I'll surface some content in the doc to cover it after we hear from him.

**Comment by guardrex** [comment]
@kiranj321 I traced thru some of the API and it doesn't look like an order is applied ...

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/WebHostOptions.cs#L37

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/WebHostOptions.cs#L72-L75

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L233-L251

... so it looks like the order in `configuration[WebHostDefaults.HostingStartupAssembliesKey]` determines the order. In the sample app, this is provided by the env var, so it would be the order listed in the env var, if I'm correct.

**Comment by kiranj321** [comment]
Thanks @guardrex that gives enough information that I am looking for!

**Comment by davidfowl** [comment]
Yes, the order is the declared order in the list of assemblies.

**Comment by aodl** [comment]
I'm aware that this issue is closed, but it seems to have the most relevant discussion. I'd like to confirm something about the behaviour of `IHostingStartup`s. Does this statement from [MSDN documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.2#class-library) still hold true, since configuration building has been moved out of the `Startup` class (since core 2.0)?

> IHostingStartup.Configure in the hosting startup assembly is called by the runtime before Startup.Configure in user code, which allows user code to overwrite any configuration provided by the hosting startup assembly.

From this^ I was of the impression that `IHostingStartup` code would be overridable by user code in terms of web host configuration.

The problem I'm having is that although `IHostingStartup.Congifure` gets called early on as suggested, the actual lambda's that I'm passing into things like `.AddConfigureAppConfiguration` don't get called until after the ones defined in the actual app (so the `IHostingStartup` in the external assembly actually overrides the app's configuration instead of the other way around). Is this expected to be the case?

**Comment by guardrex** [comment]
Hello @aodl ... Please open a new issue using the **Content feedback** button at the bottom of the topic. We don't work/respond (*much* :smile: lol) on closed issues. It's just a lot easier for us to track on and work the open ones. Just paste your remarks into that form and open a new one. We'll get right back to you.

**Comment by guardrex** [comment]
If you need to reference this, just include a link ...

https://github.com/aspnet/Docs/issues/6951
