### ISSUE TITLE
Update 2.0 -> 2.1 migration docs to cover AspNetCore shared runtime quirks

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Docs#6952]
There are some very specific rules for being able to use packages or projects targeting the shared runtime with Mvc. They are:

1) Project referencing `Microsoft.AspNetCore.All` or `Microsoft.AspNetCore.App` packages, must reference `Microsoft.Net.Sdk.Web` Sdk.
2) Projects referencing packages or projects that transitively reference `Microsoft.AspNetCore.All` or `Microsoft.AspNetCore.App` must reference `Microsoft.Net.Sdk.Web` Sdk and the same shared runtime package. E.g if LibraryA references `Microsoft.AspNetCore.App`, any projects referencing it must reference `Microsoft.AspNetCore.App`.
3) Executable projects, i.e. the app that you launch, must not specify the version. The Sdk will specify this for you e.g. `<PackageReference Include="Microsoft.AspNetCore.App" />` . This includes "apps" that run and test projects for apps. 
4) Referenced projects, i.e. projects that aren’t the entry point, that reference `Microsoft.AspNetCore.All` or `Microsoft.AspNetCore.App` must specify a package version.

**Comment by pranavkm** [comment]
cc @danroth27 \ @JunTaoLuo \ @Rick-Anderson 

We should add these details to the 2.1 migration docs - https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1.

**Comment by bcisnero** [comment]
I could probably recommend adding a new section in the document with information about the packages you are listing before the Update the project file to use 2.1 versions section.

**Comment by bcisnero** [comment]
And if you want, I can add this section.

**Comment by danroth27** [comment]
@Rick-Anderson We're seeing a fair amount of customer questions related to this issue that we would like to address by updating the migration doc. Can we please get this issue prioritized?
