### ISSUE TITLE
command : "dotnet new webapp -o RazorPagesMovie" is not working

### ISSUE THREAD

**Issue by jalvarezca** [aspnet/Docs#6956]
dotnet new webapp -o RazorPagesMovie doesn't work.
Instead need to use : dotnet new razor -o RazorPagesMovie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d466934-744e-673c-18a2-e312b04d7b28
* Version Independent ID: f52b6f6d-5aaf-c515-22af-a0aeaaf9b8e1
* Content: [Get started with Razor Pages in ASP.NET Core on macOS with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
`webapp` is an alias for `razor` with the 2.1 SDK. Install the 2.1 SDK to use `webapp` as the template name. If you continue to work with 2.0, then continue to use `razor`. If you flip the document over to "2.0" (upper left corner of the page), you'll see the command change to call for the `razor` template. We have some language going in to address this on https://github.com/aspnet/Docs/pull/6939. Thanks for commenting.

**Comment by Rick-Anderson** [comment]
see See #6939
