### ISSUE TITLE
Remove webapp alias notice

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#6959]
:hocho: *includes/webapp-alias-notice.md*

**Comment by guardrex** [comment]
@Rick-Anderson When do you want to remove this notice?

> [!NOTE] If the dotnet new webapp <OPTIONS> command loads the dotnet new command help instead of creating a new Razor Pages app, install .NET Core SDK 2.1.300 or later. As of .NET Core SDK 2.1.300, the webapp Short Name is an alias for razor.

https://github.com/aspnet/Docs/blob/master/aspnetcore/includes/webapp-alias-notice.md

It appears everywhere (I think) that we show ...

```console
dotnet new webapp ...
```

**Comment by Rick-Anderson** [comment]
I think we should remove it now unless @scottaddie  objects.

**Comment by guardrex** [comment]
Ok ... I'll wait to hear back from him, then do the deed if :+1:.
