### ISSUE TITLE
dotnet-watch

### ISSUE THREAD

**Issue by brockallen** [aspnet/Docs#696]
I guess here: https://docs.asp.net/en/latest/dnx/commands.html#global-commands-details

**Comment by GuardRex** [comment]
This might be a good spot for @tuespetre methods for setting up IIS (not Express) with `dnx-watch`.

References:

https://github.com/tuespetre/dnx-watch-iis
https://github.com/aspnet/Hosting/issues/364#issuecomment-158733918
https://github.com/aspnet/Hosting/issues/364#issuecomment-158765267

**Comment by danroth27** [comment]
Unfortunately I believe dnx-watch is broken for RC1 and it is getting replaced for RC2. @victorhurdugaci  can you confirm?

**Comment by victorhurdugaci** [comment]
`dnx-watch` is not broken :) The only big known issue is when running on OSX on CoreCLR: https://github.com/aspnet/dnx-watch/issues/21 and the CLR team is working on a fix.

**Comment by brockallen** [comment]
Also, can you document how to run dnx from a parent folder? It doesn't seem to have a `-p` as dnx doex.

**Comment by danroth27** [comment]
Holding off on this until we see what this tool looks like in the .NET CLI world.

**Comment by GuardRex** [comment]
@danroth27 

@tuespetre and I discussed his scenario of using `watch` with IIS 10 local for his build-and-refresh experience at https://github.com/tuespetre/dnx-watch-iis/issues/2 ... and I hope he'll take that forward with the changes in RC2. It rocks for a shop scenario where a normal IIS server isn't available or desired. When the time comes, I hope you'll decide to link him in somehow or have him or someone write up his approach for the official docs.

**Comment by danroth27** [comment]
DNX is going away with the move to .NET CLI, but there will still be a watch command/tool. Need to figure out if this tool will be part of the .NET CLI and if the docs belong here or somewhere else.

**Comment by GuardRex** [comment]
@tuespetre If you end up refactoring for a possible `dotnet cli` watch system for local IIS and you need a test :monkey:; ping me, and I'll give your revision a shot when you get there.

**Comment by tuespetre** [comment]
@GuardRex cool, I will probably be waiting for RC2 to revisit it

**Comment by danroth27** [comment]
Dropping this to P1 since this is a tool and not technically part of the runtime.
