### ISSUE TITLE
Needs a Typescript / Webpack example

### ISSUE THREAD

**Issue by robertmclaws** [aspnet/Docs#6965]
Hey, great work everyone. I was reading through the docs for the JS client, and right now they say to copy the JS file from the NPM folder into your project. If you're getting resources from NPM, that's not really a best practice to be communicating to people. Would it be possible to add in a section to show how you would reference it from TypeScript so that it gets bundled into Webpack properly? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by ssougnez** [comment]
Hi, if you’re still interesting by this, maybe you can have a look at the article I wrote about it : https://anotherdevblog.com/2018/06/12/using-signalr-core-with-typescript-and-webpack-in-an-asp-net-core-2-1-web-application/

**Comment by rachelappel** [comment]
@ssougnez Yes, this is absolutely the right place for your comment! Fantastic blog post! If you would like us to incorporate your content into docs.microsoft.com, please open a pull request and add your content to it. If you are unfamiliar with the docs OSS process (we try to make it as easy as possible) the docs team is here to help you, and you get some free professional editing of your content.

**Comment by ssougnez** [comment]
@rachelappel I'd be very happy to do so. Do you have a link with a documentation on how to proceed? I'll have to rework it a bit as I reference other post of my blog but that would be cool hehe

**Comment by rachelappel** [comment]
@ssougnez Here you go! The contributor's style guide. https://github.com/aspnet/Docs/blob/master/CONTRIBUTING.md 
Markdown is very simple if you haven't used it. We can help you convert the document as well and can enhance it for you for things like voice and tone.

**Comment by Rick-Anderson** [comment]
@ssougnez  the issue has links to the doc
![image](https://user-images.githubusercontent.com/3605364/41444936-05f7d802-6ffb-11e8-8bd4-70a81a72fed2.png)

**Comment by rachelappel** [comment]
@ssougnez That's great. When you asked for a link to the documentation, I believe Rick thought you were asking for a link to the JS doc, not to the contributor's guide.

**Comment by ssougnez** [comment]
Here it is: https://github.com/aspnet/Docs/pull/7088

I'm pretty I forgot some things but I think it's close to what I should have done :-D
