### ISSUE TITLE
Update the 2.1 authentication examples -> at Startup.cs .AddDefaultUI() method is missing

### ISSUE THREAD

**Issue by hubekpeter** [aspnet/Docs#6967]
Since 2.1 the identity views have been moved under the separate area. The examples would not work without .AddDefaultUI() method been called.

services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddDefaultUI();

Thanks
P.

**Comment by guardrex** [comment]
Which topic @hubekpeter?

**Comment by hubekpeter** [comment]
Hi Guys, 

 

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1 -> Add WS-Federation as an external login provider for ASP.NET Core Identity

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=aspnetcore2x -> Require email confirmation

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-2.1 -> Under the Facebook, Twitter, Google etc. 

 

Thanks

P.

 

 

 

Od: Luke Latham <notifications@github.com>
Príjemca odpovede: aspnet/Docs <reply@reply.github.com>
Dátum: sobota, 9. júna 2018, 22:50
Komu: aspnet/Docs <Docs@noreply.github.com>
Kópia: hubekpeter <hubekpeter@gmail.com>, Mention <mention@noreply.github.com>
Predmet: Re: [aspnet/Docs] Update the 2.1 authentication examples -> at Startup.cs .AddDefaultUI() method is missing (#6967)

 

Which topic @hubekpeter?

**Comment by guardrex** [comment]
I was just taking a look at the issues, and there are several that pertain to updating Identity for 2.1. Those issues should cover this one. The work is going on now, and I doubt it will take long to get the topics updated.

**Comment by samisin** [comment]
Did run into the same issue when using a customized Identity. If services.AddDefaultIdentity is used there is no issue with the separate area, but as soon as services.AddIdentity is used, AddDefaultUI needs to be added to get correct routing. Otherwise (it not authorized, for example) it routs to /Account/Login and not to /Identity/Account/Login. My two cents.

**Comment by Rick-Anderson** [comment]
Dup of #9706, #9706, #10418
