### ISSUE TITLE
FromBody needs a correct way example

### ISSUE THREAD

**Issue by fotoguy42** [aspnet/Docs#6968]
In the frombody section, it shows three ways not to define the method with multiple complex parameters, but it does not provide a correct way to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@fotoguy42 Expressed in terms of HTTP, what are you trying to achieve? You don't generally send 2 complex objects in the request body (other than multipart).

**Comment by erguergu** [comment]
Well, in your example, the three actions appear to want to accept a product and an order. I can imagine a world in which your api has an action called AddProductToOrder, and, for some reason, it is inappropriate to pass the IDs of either. Is it not possible to do something like this with both items in the body?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
