### ISSUE TITLE
Where Is the Account Controller?

### ISSUE THREAD

**Issue by saviour123** [aspnet/Docs#6970]
* create a new project
`dotnet new mvc -uld --auth Individual -o Shalom.Core`

* After restoration and updating the database to use npgsql. I started the project fine. I was able to register and login. 
Now the problem is, where is the Account and Login Manage controllers, its not in the project dir. 
I wanted to tweak the login and adjust the UI. the controller and the UIs are not available yet the project works. 

Has something change about the login manager controllers with dotnet 2.1.300?

## URL Change?
http://localhost:5000/Identity/Account/Manage
Url now pointing to the above? Where from the Identity? Can someone point me me any blog?

**Comment by guardrex** [comment]
Identity UI is a library now. See: https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/

The Identity topic hasn't been updated yet. There are a few open issues to update the topics. https://github.com/aspnet/Docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+identity

In the meantime, I see a few blogs searching for "identityui" ... https://www.google.com/search?q=identityUi

**Comment by saviour123** [comment]
Thanks for the Reply. It really saved my day..
Found this command on the blog that generated the Controllers for me!!
`> dotnet aspnet-codegenerator identity -dc Shalom.Core.Data.ApplicationDbContext --force`
