### ISSUE TITLE
I think some of the sections are incorrect.

### ISSUE THREAD

**Issue by songgun** [aspnet/Docs#6971]
For example, descriptions of "vary-by-query", "vary-by-route", and "vary-by-cookie" are all based on headers. For example:

Description of the current "vary-by-query" section:

"Accept a single header value or a comma-separated list of header values that trigger a cache refresh when the header value changes."

Description of the "vary-by-query" section after the modification I think is correct:

"Accepts a single query parameter key or a comma-separated list of query parameter keys that trigger a cache refresh when the query parameters value changes."

Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 858d5899-e1a2-ce10-16d3-71006229b85b
* Version Independent ID: abd7d27e-915c-6bf0-f5de-770d6a95d467
* Content: [Cache Tag Helper in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/cache-tag-helper?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pkellner can you review?

**Comment by Rick-Anderson** [comment]
@pkellner can you review?

**Comment by Rick-Anderson** [comment]
@NTaylorMullen please review

**Comment by NTaylorMullen** [comment]
@songgun I don't see the issue in `vary-by-query`; however, I do see that vary-by-route and `vary-by-cookie` are incorrect as you mentioned.

**Comment by Rick-Anderson** [comment]
@songgun can you create a PR to fix this? [Click this link](https://github.com/aspnet/Docs/edit/master/aspnetcore/mvc/views/tag-helpers/built-in/cache-tag-helper.md) to edit in the browser and create a PR.
