### ISSUE TITLE
how to use MessagePack missing

### ISSUE THREAD

**Issue by cyberh0me** [aspnet/Docs#6972]
the documentation mention MessagePack protocol but it does not show how to use this protocol, what needs to be installed ? what configuration is needed ? client code ?

keyword msgpack5.js, signalr-protocol-msgpack.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22325a88-5e1d-7b54-87b7-ea331a6c73b6
* Version Independent ID: b92a4bf5-f7c9-50b9-d7d7-46ebcf7387b0
* Content: [ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/index.md)
* Product: **asp.net-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by BrennanConroy** [comment]
A doc has been written for this but isn't pushed to the site yet, you can view it at https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/messagepackhubprotocol.md

**Comment by cyberh0me** [comment]
thx this document is helpful except it mention you also need to add msgpack5 lib but does not describe the way to install msgpack5.js
