### ISSUE TITLE
Errors in Visual Studio startup tutorial for C#

### ISSUE THREAD

**Issue by eddye0** [aspnet/Docs#6973]
I'm new to MVC and Visual Studio 2017 so I've been doing the startup tutorial. Near the end of the Work with SQL Server LocalDB section when I was instructed to test the app I got the following errors in the output:
 Build FAILED.
 1&gt;
 1&gt;Program.cs(12,7,12,13): warning CS0105: The using directive for 'System' appeared previously in this namespace
 1&gt;Models\SeedData.cs(17,52,17,85): error CS0246: The type or namespace name 'DbContextOptions&lt;&gt;' could not be found (are you missing a using directive or an assembly reference?)
 1&gt;Models\SeedData.cs(20,29,20,34): error CS1061: 'MvcMovieContext' does not contain a definition for 'Movie' and no extension method 'Movie' accepting a first argument of type 'MvcMovieContext' could be found (are you missing a using directive or an assembly reference?)
 1&gt;Models\SeedData.cs(25,25,25,30): error CS1061: 'MvcMovieContext' does not contain a definition for 'Movie' and no extension method 'Movie' accepting a first argument of type 'MvcMovieContext' could be found (are you missing a using directive or an assembly reference?)
 1&gt;Models\SeedData.cs(26,26,26,31): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
 1&gt;Models\SeedData.cs(34,26,34,31): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
 1&gt;Models\SeedData.cs(42,26,42,31): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
 1&gt;Models\SeedData.cs(50,24,50,29): error CS0246: The type or namespace name 'Movie' could not be found (are you missing a using directive or an assembly reference?)
 1&gt; 1 Warning(s)
 1&gt; 7 Error(s)
I don't know how to correct this and need this corrected in order to continue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x&view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@eddye0  looks like you made some copy/paste errors. They're great errors, read them and look at the download code to find the includes you've duplicated/missed.

**Comment by Rick-Anderson** [comment]
@eddye0  Why are you doing this and not the Razor Pages version?

**Comment by eddye0** [comment]
I was trying to do what you told me I should do. I find Github very difficult to navigate. What did I do wrong and what do I need to do. I just need to know how to proceed

**Comment by Rick-Anderson** [comment]
@eddye0  I recommend starting over with the 2.1 version of RP. It's easier to follow. You've left out includes and duplicated others as the error message states.

**Comment by CharlieIoD** [comment]
In: Add a view to an ASP.NET Core MVC app,
I get to: "Create a Welcome view template named Views/HelloWorld/Welcome.cshtml." This I take to mean that the Welcome.cshml is inside the HelloWorld folder. I follow the same process as for creating the HelloWorld Razor View then replace the contents of the Welcome.cshml as before and everything seems OK. However when I save the files an press Ctrl/F5 the build does not proceed as normal I just immediately opens the browser. When I run the URL: https://localhost:44300/HelloWorld/Welcome?name=Rick&numtimes=4 Iget: "Internal Server Error. The view Welcome was not found." If I delete the Welcome file and recreate it under Views, I get the same result.
