### ISSUE TITLE
Bad link to the samples

### ISSUE THREAD

**Issue by progala2** [aspnet/Docs#6975]
The link should be: https://github.com/aspnet/Docs/tree/master/aspnetcore/test/razor-pages-tests/samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor Pages unit tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/razor-pages-tests.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @progala2 ... I'll patch that right now.
