### ISSUE TITLE
Async ActionResult<T> Json Deserialization 

### ISSUE THREAD

**Issue by morrisandy** [aspnet/Docs#6980]
In the example it shows the recommended use with a web api controller using ActionResult&lt;T&gt; which works great. However, I'm noticing when I try to use an async web api ActionResult, for example: 

public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; Create(TodoItem item)

NSwag Studio will generate an associated object of ActionResultOfTodoItem which seems is not able to deserialize. 

Below is part of the generate code from NSwag Studio that is trying to deserialize the response data tha comes from an public async Task&lt;ActionResult&lt;List&lt;ProductDto&gt;&gt;&gt; GetAsync() end point:

var status_ = ((int)response_.StatusCode).ToString();
                        if (status_ == "200") 
                        {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                            var result_ = default(ActionResultOfListOfProductDto); 
                            try
                            {
                                result_ = Newtonsoft.Json.JsonConvert.DeserializeObject&lt;ActionResultOfListOfProductDto&gt;(responseData_, _settings.Value);
                                return new SwaggerResponse&lt;ActionResultOfListOfProductDto&gt;((int)response_.StatusCode, headers_, result_); 
                            } 
                            catch (System.Exception exception_) 
                            {
                                throw new SwaggerException("Could not deserialize the response body.", (int)response_.StatusCode, responseData_, headers_, exception_);
                            }
                        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **asp.net-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by morrisandy** [comment]
defining the type, like below, on the api controller's action result resolves the issue i was having above:

[SwaggerResponse("200", typeof(Person))]

**Comment by RSuter** [comment]
If this is not yet fixed, I think this fixed it: https://github.com/RSuter/NSwag/pull/1396

**Comment by morrisandy** [comment]
You're correct. that PR has resolved the issue. However, I'm coming across the same issue with custom classes using T. For example, blow is a PaginatedList extension I use to return a sub set of items. When returning this type from a web api end point, the same issue occurs: **PaginatedListOfTodoItem**

In NSwagStudio I did consider change the generic response type for an arry from System.Collections.ObjectModel.ObservableCollection to PaginatedList but I don't believe that would be a good solution? 

Do you have any other recommendations?

Thanks again

TodoItemController
```
public async Task<ActionResult<PaginatedList<TodoItem>>> GetAsync([FromBody]TodoItemRequestDto dto)
{

}

```
PaginatedList.cs
```
public class PaginatedList<T> : List<T>
    {
        public PaginatedList(IEnumerable<T> items, int count, int pageIndex, int pageSize)
        {
            PageIndex = pageIndex;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);
            AddRange(items);
        }

        public int PageIndex { get; private set; }
        public int TotalPages { get; private set; }
        public bool HasPreviousPage => (PageIndex > 1);
        public bool HasNextPage => (PageIndex < TotalPages);
    }
```

**Comment by RSuter** [comment]
Generating `PaginatedListOfTodoItem` is by design, because Swagger/OpenAPI and it's underlying JSON Schema does not support generics, for more info, see: https://github.com/RSuter/NJsonSchema/issues/23
