### ISSUE TITLE
MVC Application Approach

### ISSUE THREAD

**Issue by mikaelsnavy** [aspnet/Docs#6985]
What is the proper approach for the "Enable account confirmation and password recovery" with a MVC application? Can this be added or is this not the correct place? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by bcisnero** [comment]
You mean the steps needed to accomplish that? Because there's already a section in this doc about that, although it really doesn't explain how to do it.

**Comment by guardrex** [comment]
This particular sample app doesn't have the 'download this sample' link. They're here ...

https://github.com/aspnet/Docs/tree/master/aspnetcore/security/authentication/accconfirm/sample

One of them is an older-ish 1.x-era sample, and the other one is a 2.0 sample. This topic and the two samples are due for upgrade on #5495.

**Comment by guardrex** [comment]
Oh ... also this is a dup of https://github.com/aspnet/Docs/issues/6632.

**Comment by mikaelsnavy** [comment]
Thanks for all you do @guardrex and @bcisnero! :+1:
