### ISSUE TITLE
2.1: document the ManifestEmbeddedFileProvider

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Docs#6988]
## Requests for new topic

1. Write a **short** paragraph describing what the topic will cover.

ASP.NET Core 2.1 adds a new file provider for serving files embedded in an assembly, `ManifestEmbeddedFileProvider`. This solves may of the problems with using the first version of an embedded file provider (EmbeddedFileProvider) which was introduced in from ASP.NET Core 1.0.0.

2. Write an outline of the proposed topic contents.

* Comparison of ManifestEmbeddedFileProvider and EmbeddedFileProvider
   * Difference between them
   * When to use ManifestEmbeddedFileProvider
* Show how to enable ManifestEmbeddedFileProvider (requires an MSBuild variable in the .csproj, IIRC)

3. Where would you put the topic in the Table of Contents.

Update this https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers

4. If you know who should review the issue, notify them by including @githubID in the issue description.

@javiercn

**Comment by Rick-Anderson** [comment]
@javiercn  we need more details, sample code, etc.  Can you write up 
* Comparison of ManifestEmbeddedFileProvider and EmbeddedFileProvider
   * Difference between them
   * When to use ManifestEmbeddedFileProvider

**Comment by javiercn** [comment]
@Rick-Anderson The manifestembeddedfileprovider respects the structure of the file system with full fidelity at the time the assembly got build and allows you to properly enumerate directories. IMO there's no reason to use the old one at all, there are no advantages to it, only drawbacks.
