### ISSUE TITLE
having to download 804MB when I just want a small project

### ISSUE THREAD

**Issue by pkellner** [aspnet/Docs#6991]
I'm sure you guys have your reasons, but every time I've wanted to download a sample project, I've gotten to this dialog that explains I need to download the ocean and then swim through it to find the project I want. I'm guessing that almost no one does that which means the value of the doc is reduced to just explanation with no real examples people can test. Personally, I think this should be prioritized so that code downloads work as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c461e1d-5771-20f9-c9b3-ac4ee7661ee0
* Version Independent ID: e06d8e48-cee4-0c0c-39aa-97abe228c370
* Content: [ASP.NET Core tutorials](https://docs.microsoft.com/en-us/aspnet/core/tutorials/index?view=aspnetcore-2.1#how-to-download-a-sample)
* Content Source: [aspnetcore/tutorials/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/index.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pkellner There's an internal issue to address it. See: https://github.com/aspnet/Docs/issues/5392

cc/ @dend

**Comment by scottaddie** [comment]
Adding @dend, who may be able to provide an update on this initiative.

**Comment by veljkoz** [comment]
Until this gets rationalized, here's a temporary solution (works beautifully): [DownGit](https://stackoverflow.com/a/38879691/79444)

**Comment by dend** [comment]
There is a project in the works that will make sample management much easier and efficient for end-user. At this time, there are no specific announcements, however I would like to re-assure that this is something that we are fixing in the near-term.

**Comment by scottaddie** [comment]
Closing this issue. It's much broader than this particular docset, and it's an enhancement that's already in the works.
