### ISSUE TITLE
No Warning Message, Can't Start App

### ISSUE THREAD

**Issue by Rexxrally** [aspnet/Docs#6992]
I open the RazorPagesMovie folder in VSCode. I get no warning message or info message.
I then click Ctrl + F5 to start the app, and I get 

"Cannot launch program 'e:\RazorPagesMovie\Pages\Index.cshtml'; setting the 'outFiles' attribute might help."
and it gives me "Open launch.json" and "Cancel" buttons.

Not sure how to proceed from here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cafe31d3-11f1-d679-1937-915690ac7360
* Version Independent ID: e6b12009-be25-33e0-c5a8-8a1bd686b387
* Content: [Get started with ASP.NET Core Razor Pages in Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Rexxrally Is the [C# Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) installed? ... and did you install the [2.1 SDK](https://www.microsoft.com/net/download/windows)?

**Comment by scottaddie** [comment]
These instructions should probably be adjusted, as Ctrl + F5 is specific to Windows. Try the following:
1. Delete your *launch.json* file in the *.vscode* folder
1. Go to **View** > **Command Palette**, and type "launch" in the Command Palette box
1. Select *Debug: Open launch.json* from Command Palette
1. Select *.NET Core* from the Environment options that appear
1. A new *launch.json* file is added to the *.vscode* folder. Click the _Debug_ view from the side bar. Select the *.NET Core Launch (web)* configuration from the drop-down next to the green play button. Click the green play button.
![image](https://user-images.githubusercontent.com/10702007/41300245-d9851824-6e2a-11e8-85b6-103e20eeaef5.png)
