### ISSUE TITLE
Is Generic Host suitable for runnings apps in IIS?

### ISSUE THREAD

**Issue by simon-michaud** [aspnet/Docs#6995]
Is Generic Host suitable for runnings apps in IIS or it is meant only being started from the command line or a a service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c04398-d05e-490a-30b9-e677804012f5
* Version Independent ID: a534ebf2-ca56-d352-401e-5f3d01b30ac0
* Content: [Host in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/index.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @simon-michaud - Since it isn't recommended for web workloads, it would be more suitable as a service. We recommend it by virtue of showing a service sample. The sample does run as a console app, but that's more geared towards testing and debugging.

@Tratcher, We already say 'not for web workloads,' but I'd like to call out more explicitly that we recommend a service-based hosting set-up for production environments at this time. Any objections?

**Comment by Tratcher** [comment]
? How you run your project is distinct from what you run inside of it (except with IIS). I don't know how much more you really need to add here.

**Comment by guardrex** [comment]
@simon-michaud Thanks for asking.

**Comment by simon-michaud** [comment]
Maybe it should be more explicit that is has nothing to do with web apps /
web servers, it is promoted as an asp.net core feature but as no relation
to it at all in its purpose.

I understand you plan is to make this host the one host for everything, but
for now it is specifically for non-asp.net core scenarios.

**Comment by guardrex** [comment]
> has nothing to do with web apps / web servers

... but that is what is says ...

> Generic Host (ASP.NET Core 2.1 or later) – Suitable for hosting non-web apps (for example, apps that run background tasks). In a future release, the Generic Host will be suitable for hosting any kind of app, including web apps. The Generic Host will eventually replace the Web Host.

... not "non-asp.net core scenarios" ... just "non-web app" scenarios.

**Comment by simon-michaud** [comment]
Ok, but still does not clarify if background jobs are suitable to be run
from IIS or should be console/service only... background job framework do
exists in asp.net/IIS context (Hangfire for example, lot more elaborate,
but you get the idea)  Wondered if it was for that purpose or not.

**Comment by guardrex** [comment]
I agreed, which is why I asked @Tratcher.

We won't update the language unless he approves ... "**_In @Tratcher We Trust_**" is printed on MS money. :smile:

**Comment by Tratcher** [comment]
Background jobs can be run as part of your web app or non-web app, such as hangfire in an IHostedService:
https://github.com/geirsagberg/HostFun/blob/master/HostFun/HangfireService.cs

Right now the limiting distinction is that the web work loads don't work in the generic host, and such you must use the WebHost in IIS. You could combine this with background tasks if you like, but that's not relevant to the choice of host.
