### ISSUE TITLE
UserID for sending to specific user

### ISSUE THREAD

**Issue by ferronsw** [aspnet/Docs#6998]
With the Hub context you can access two different UserId's:

1. Through Context.User > System.Security.Claims.Claimsprincipal
2. Through Context.UserIdentifier > HubCallerContext

The first option is associated with the Azure Authentication I use within my application.
But when I use this ID to send a message to the clients nothing happens. 

So I'm thinking the second option is used as userId to send messages to specific users. How can I access this ID from another class or can I override the use of this ID?

I'm using the IHubContext to call SignalR methods from my helper class.

` private readonly IGraphSDKHelper _graphSDKHelper;
        private readonly IHubContext<WidgetHub> _widgetHub;

        public NotificationsHelper(IGraphSDKHelper graphSDKHelper, IHubContext<WidgetHub> widgetHub)
        {
            _graphSDKHelper = graphSDKHelper;
            _widgetHub = widgetHub;
        }

        public async Task GetAndSendMailCount(string userId)
        {
            var graphClient = _graphSDKHelper.GetAuthenticatedClient();
            string mailCount = await GraphService.GetUserMailCount(graphClient,userId);
            await _widgetHub.Clients.User(userId).SendAsync("ReceiveMailCount", mailCount);
            
        }`

**Comment by Rick-Anderson** [comment]
@anurse  please comment.

**Comment by anurse** [comment]
The `Context.UserIdentifier` is the value that you can use in `.User(...)`. It is determined by the `IUserIdProvider` you have registered in services. The default one uses the [`NameIdentifier`](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes.nameidentifier?view=netstandard-2.0) claim on the `Context.User`, but you can change that by registering a custom one in your DI container. Check the docs on [Users](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1) for more information.
