### ISSUE TITLE
No executable found matching command "dotnet-aspnet-codegenerator"

### ISSUE THREAD

**Issue by Languafe** [aspnet/Docs#6999]
After adding package Microsoft.VisualStudio.Web.CodeGeneration.Design I still get error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You need .NET SDK 2.1

**Comment by Languafe** [comment]
I forgot to add the <DotNetCliReference /> element to csproj.

**Comment by touhidulfahim** [comment]
No executable found matching command "dotnet-aspnet-codegenerator" I got this error !!

**Comment by Rick-Anderson** [comment]
install the latest version of the [.NET Core SDK](https://www.microsoft.com/net/download/archives) But not the preview version.
It's no longer a DotNetCliToolReference 
It's a global tool.

**Comment by tisRnjp** [comment]
Follow this link
https://stackoverflow.com/questions/51128038/no-executable-found-matching-command-dotnet-aspnet-codegenerator-asp-net-core

**Comment by Rick-Anderson** [comment]
@bricelam  is MacOS the only platform you need to explicitly `dotnet tool install --global dotnet-aspnet-codegenerator`

**Comment by bricelam** [comment]
No idea. The [aspnet/Scaffolding](https://github.com/aspnet/Scaffolding) folks own that tool.

**Comment by xamadev** [comment]
`dotnet tool install --global dotnet-aspnet-codegenerator` works also on Windows for me! Could'nt install it via nuget neither by adding an item group to the .csproj file.

Thanks @Rick-Anderson

**Comment by dot-sent** [comment]
I was able to reproduce the same issue on Linux/VSCode and Linux/dotnet CLI. My current setup gives pretty confusing results:

`dot_sent@sergey-pc:~/Projects/MVCTest/MvcIdentity$ dotnet tool install --global dotnet-aspnet-codegenerator
Tool 'dotnet-aspnet-codegenerator' is already installed.
dot_sent@sergey-pc:~/Projects/MVCTest/MvcIdentity$ dotnet aspnet-codegenerator --help
No executable found matching command "dotnet-aspnet-codegenerator"
`

`dotnet --info` output, in case it helps:

`dot_sent@sergey-pc:~/Projects/MVCTest/MvcIdentity$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.504
 Commit:    91e160c7f0

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.504/

Host (useful for support):
  Version: 2.1.8
  Commit:  209f8aa25c

.NET Core SDKs installed:
  2.1.101 [/usr/share/dotnet/sdk]
  2.1.504 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
`

**Comment by Rick-Anderson** [comment]
@dot-sent  can you open an issue at https://github.com/dotnet/cli/issues/new

**Comment by Rick-Anderson** [comment]
@dot-sent install the latest SDK first, 2.2

**Comment by dot-sent** [comment]
@Rick-Anderson Done, still the same problem. Tried also uninstalling 2.0 and 2.1, reinstalling the aspnet-codegenerator - all to no avail. Finally installing it in a specific directory and running it via absolute path worked well. I guess some paths were not registering properly. Should I still open the issue on dotnet-cli?

**Comment by Rick-Anderson** [comment]
```
dotnet --version
2.2.103
```

**Comment by BlackBoxRecorder** [comment]
`dotnet tool install --global dotnet-aspnet-codegenerator`

`/home/yinnan/.dotnet/tools/dotnet-aspnet-codegenerator -h`

**Comment by JwanKhalaf** [comment]
`dotnet tool install --global dotnet-aspnet-codegenerator` worked on Ubuntu too.

**Comment by marciocleberbrazil** [comment]
@JwanKhalaf It worked for me on Windows 10. Thanks a lot!

**Comment by rlassche** [comment]
I just typed:
 ~/.dotnet/tools/dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries

So, I did not start with 'dotnet'.

**Comment by RockmanR** [comment]
> I just typed:
> ~/.dotnet/tools/dotnet-aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries
> 
> So, I did not start with 'dotnet'.

Alright, thanks @rlassche that worked for me. I have no clue why this solves it. can someone explains this issue?

**Comment by rlassche** [comment]
I checked this issue again. This looks better:
1. My PATH on Linux was not correct. 
`export PATH=~/.dotnet/tools:$PATH`
2. The command in tools directory is called **dotnet-aspnet-codegenerator** and exists now in the PATH.
3. Test  it with dotnet now:
`$ dotnet aspnet-codegenerator`
The help-text is displayed.
