### ISSUE TITLE
wrong DI file in tutorials/your-first-aspnet-application 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#700]
Microsoft.Framework.DependencyInjection should be remove from tutorial. That's the beta8 package ID. In rc1 it was changed to Microsoft.Extensions.DependencyInjection. 

see comments in https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html

**Comment by Erikre** [comment]
Fixed. Thanks

**Comment by Rick-Anderson** [comment]
@Erikre  thanks. Add PR and close this issue.

**Comment by Erikre** [comment]
It's already fixed. Closing.
