### ISSUE TITLE
Why the docs uses the namespace `aspnetcoreapp` in lowercase instead of `AspNetCoreApp` in PascalCase?

### ISSUE THREAD

**Issue by lmcarreiro** [aspnet/Docs#7000]
Doesn't the [names conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces) says to use PascalCase in namespaces names? The example for .NET Core 2.x uses this:

```c#
namespace aspnetcoreapp
```

Why is it different here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e622e9-c567-00b9-3788-d6a01934b314
* Version Independent ID: 8e663029-63b9-2622-f852-9f8a2ec70db3
* Content: [ASP.NET Core fundamentals](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/index?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/index.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @lmcarreiro. I'm coming up on this sample fairly soon (see #5495), and I'll take care of this.

**Comment by Rick-Anderson** [comment]
As with other naming guidelines, the goal when naming namespaces is creating sufficient clarity for the programmer using the framework to immediately know what the content of the namespace is likely to be.
