### ISSUE TITLE
Possible incorrect information. 

### ISSUE THREAD

**Issue by jonathanperot** [aspnet/Docs#7002]
I'm an intern so ill try to explain this as best as I can.

In the step below is where I start having errors:

"In Program.cs, modify the Main method to do the following on application startup:
Get a database context instance from the dependency injection container.
Call the seed method, passing to it the context.
Dispose the context when the seed method is done." 

All steps previous to this I had no issues but the line:

" var host = CreateWebHostBuilder(args);" 

in order to get it working he build command for the host variable to 

"var host = CreateWebHostBuilder(args).Build();"

and moved the try/catch that Initializes the DB from the Startup.cs to Program.cs after the method that configures the pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [ASP.NET Core MVC with Entity Framework Core - Tutorial 1 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@jonathanperot  that tutorial has not been updated to 2.1
Take a look at https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.1#add-the-seed-initializer

Why are you doing the MVC and not the RP version - I might have to report you to fowler :)

I'd love to get your feedback on the RP version https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.1
