### ISSUE TITLE
Incorrect instruction

### ISSUE THREAD

**Issue by FDillon00** [aspnet/Docs#7004]
The instruction says "Run the app in non-debug mode and append "HelloWorld" to the path in the address bar. "
However the class is named "HelloWorldControler" per the previous step of replace contents of the new controller with the example. 

Either the instruction should be to append "HelloWorldControler" to the URL or change class name to "HelloWorld" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@FDillon00 In MVC, the "Controller" suffix is excluded from the URL. By convention, the suffix "Controller" is used for the class name. MVC uses convention over configuration. Are the instructions not working for you?

**Comment by FDillon00** [comment]
NVM.... Looks like I failed to name the class correctly... apparently I think it's "controler"  thank you for you time. Sorry.

**Comment by scottaddie** [comment]
@FDillon00 Glad to hear you figured it out. Thanks for reading our docs!

**Comment by merrickw** [comment]
@scottaddie just a comment; typos aside, it appears if the class name was set to HelloWorld instead of HelloWorldController, the URL remains the same.  Wouldn't it be clearer to use the exact URL name rather than knowing the Controller suffix will automagically be stripped?  These hidden operations are vulnerable to typos with no warning, as in this original issue.
