### ISSUE TITLE
Feedback - Add custom user data to the Identity DB

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/Docs#7006]
I think it would be very helpful if it is mentioned or explained (If I am right), once scaffold-ed the IdentityUser needs to be changed everywhere (I think  in 19 files) to WebApp1User in this example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Were you starting with a 2.0 project? The instructions in the article work without any name changes.

**Comment by VaclavElias** [comment]
I am doing it in 2.1 and you have also changed it to WebApp1User in the section Update the Account/Manage/Index.cshtml page

**Comment by Rick-Anderson** [comment]
Where are the other 18 files?

**Comment by VaclavElias** [comment]
I have scaffold-ed Identity UI. So it means in all other 18 pages. I think that is right procedure to replace it also in those 18 files if there were scaffold-ed?

**Comment by VaclavElias** [comment]
@Rick-Anderson I know where I got confused. When I do scaffolding, I can **override files**, **set Data Context class** but my **User class** is disabled. So I simply scaffold-ed it without my custom user class included and I had to create it myself. Obviously all was with default IdentityUser. So the documentation is probably right :( I will close this till I figure out why my User class field in UI is disabled. Thanks.

**Comment by VaclavElias** [comment]
@Rick-Anderson I found it! When I want my own **User Class** I must select a **new** Data Context, then I am able to select new User class and so on.. 

Ok, just  a bit more playing, I am closing this.

**Comment by Rick-Anderson** [comment]
Ya, that's a bit tricky. I think I mentioned it in https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio

see also #6915

**Comment by VaclavElias** [comment]
Yep, it is a bit tricky :) but works well once you figured it out. At least we have got a reference here and whoever would google it is going to find it here or in docs. Thanks @Rick-Anderson.
