### ISSUE TITLE
Are there any examples using the Secret Manager in VS 2017?

### ISSUE THREAD

**Issue by rweekes4** [aspnet/Docs#7009]
I've tried running the final2 project and I get an error seeding the database. I believe the password is not being set properly as the error says "ArugmentNullException: Value cannot be null." I've tried following the instructions for Secrets Manager at https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows, but I can't seem to get it to work. Any help or direction is appreciated.

**Comment by scottaddie** [comment]
@rweekes4 Do you have a link to the "final2" project that's giving you trouble?

**Comment by Rick-Anderson** [comment]
@rweekes4  that's usually because the password you're using is too weak.
