### ISSUE TITLE
How to include the tag helper in view imports

### ISSUE THREAD

**Issue by anuraj** [aspnet/Docs#7017]
For this SO question - https://stackoverflow.com/q/48271514/38024, tag helpers not working - got few responses like it is not mentioned properly in the documentation. Please have a look into it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It is mentioned clearly. Where the topic describes the The `@addTagHelper` directive, it states ...

> The code above uses the wildcard syntax ("*") to specify that all Tag Helpers in the specified assembly (Microsoft.AspNetCore.Mvc.TagHelpers) will be available ...

... in same paragraph it goes on to say ...

> ... and the second parameter "Microsoft.AspNetCore.Mvc.TagHelpers" specifies the assembly containing the Tag Helpers. Microsoft.AspNetCore.Mvc.TagHelpers is the assembly for the built-in ASP.NET Core Tag Helpers.

An example follows, where it states ...

> To expose all of the Tag Helpers in this project (which creates an assembly named AuthoringTagHelpers), you would use the following:

```cshtml
@using AuthoringTagHelpers
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
```

There's a third mention further down, where it states (and an example follows) ...

> To add a Tag Helper to a view using an FQN, you first add the FQN (AuthoringTagHelpers.TagHelpers.EmailTagHelper), and then the assembly name (AuthoringTagHelpers).

**Comment by guardrex** [comment]
Thanks @anuraj for letting us know. We definitely don't get to keep up with all of the SO stuff going on, and we do get prompts to update based on discussions there. We do appreciate you mentioning this to us.
