### ISSUE TITLE
Is there a wrong img?

### ISSUE THREAD

**Issue by CeciAc** [aspnet/Docs#7020]
@MoeShan commented on [Wed Jun 13 2018](https://github.com/aspnet/Docs.zh-cn/issues/53)

https://docs.microsoft.com/zh-cn/aspnet/mvc/overview/getting-started/introduction/adding-a-controller

image 8  should be like newimage8

![image8](https://user-images.githubusercontent.com/8566898/41335844-d017bfec-6f1c-11e8-9ffe-55a029da055c.png)
![newimage8](https://user-images.githubusercontent.com/8566898/41335845-d047ef14-6f1c-11e8-9ccb-c041af0df31c.png)

**Comment by Rick-Anderson** [comment]
@MoeShan you're correct.
