### ISSUE TITLE
Scaffolding not working

### ISSUE THREAD

**Issue by pelsted** [aspnet/Docs#7022]
I'm following these guidelines:  "Scaffold identity into a Razor project WITHOUT existing authorization".

My setup:
* ASP.NET Core 2.1.
* No authentication / identity before this.
* Visual Studio 17.5.3

After running the Scaffold command, the code generation log says:
Finding the generator 'identity'...
Running the generator 'identity'...
....and it just waits there forever (not user friendly).

Only the following files are created: 
* Areas/Identity/{Data,Pages,Services} folders
* ScaffoldingReadme.txt
but all /Account/* files are missing.

When I re-ran this Add | New Scaffolded item, and then selected at the prompt to overwrite all /Account files, the files were finally created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by levanijincharadze** [comment]
I have similar problem. From the left pane of the Add Scaffold dialog,  Identity option not exist.

**Comment by Rick-Anderson** [comment]
@levanijincharadze  You need the 2.1 SDK installed, VS updated and you need to select .NET Core 2.1 to get Identity templates.

**Comment by Rick-Anderson** [comment]
@pelsted  can you try again. Sounds like a glitch.

**Comment by pelsted** [comment]
@Rick-Anderson Same problem after restart of VS.  Visual Studio is a fresh install too - had problems with Win10 so did a complete 'Fresh start via Windows Defender Security System' of the system and reinstalled all apps.

Another minor issue with the generated templates is that they are not using the new <partial name="_StatusMessage"...> tag.

**Comment by Rick-Anderson** [comment]
Are you generating a 2.1 project?

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/41377595-636a2ae8-6f11-11e8-9d89-dab5cd53dbd9.png)

**Comment by pelsted** [comment]
My .csproj file: 

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BuildBundlerMinifier" Version="2.8.391" />
    <PackageReference Include="Dapper" Version="1.50.5" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.2" />
    <PackageReference Include="WebMarkupMin.AspNetCore2" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

  <Target Name="CreateLogsFolder" AfterTargets="Publish">
    <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
    <WriteLinesToFile File="$(PublishDir)Logs\.log" Lines="Generated file" Overwrite="True" Condition="!Exists('$(PublishDir)Logs\.log')" />
  </Target>

</Project>

As I wrote earlier, I solved the problem by ticking all the boxes (Overwriting files that actually arent there).

**Comment by pelsted** [comment]
![1](https://user-images.githubusercontent.com/29387615/41380565-a457ff5e-6f65-11e8-9cd5-c59fae474ceb.PNG)
![2](https://user-images.githubusercontent.com/29387615/41380566-a4756a44-6f65-11e8-8102-4060caf3307e.PNG)
![3](https://user-images.githubusercontent.com/29387615/41380567-a48f9ba8-6f65-11e8-9a01-4343ffd0def9.PNG)

**Comment by pelsted** [comment]
If I start a blank project and check the boxes, I get all files.

![5](https://user-images.githubusercontent.com/29387615/41381216-48190b6e-6f67-11e8-9a18-6e3f54cc9954.PNG)

![6](https://user-images.githubusercontent.com/29387615/41381215-47fb907a-6f67-11e8-944f-6213f2270062.PNG)

**Comment by Rick-Anderson** [comment]
@pelsted  read the article, the default is using a RCL and no files. That's correct. You don't want to generate all the files unless you need to modify them.

**Comment by pelsted** [comment]
> read the article, the default is using a RCL and no files. 
Doh... I should have looked closer / new to Identity and was not aware of Identity UI thingy.
