### ISSUE TITLE
Combine Razor with Identity?

### ISSUE THREAD

**Issue by ayinn** [aspnet/Docs#7026]
Identity 2.0 with Razor Page not working

I get message that the view pages can't find the ApplicationUser. Have carefully followed Tut and all supplied documents. Seems that moving the ApplicationUser from Data Folder to Models Folder does not work?

**Comment by guardrex** [comment]
Unfortunately, our [Identity tutorial](https://docs.microsoft.com/aspnet/core/security/authentication/identity) is MVC at this time. It's on the list for update, and I presume we'll replace the MVC app with a Razor Pages app on #5495.

Note: You said "2.0." Install the 2.1 SDK ([download page](https://www.microsoft.com/net/download/windows)) to get the latest bits.

Perhaps, the best approach is:

1. `dotnet new webapp --auth Individual`
1. To secure pages and folders, follow the guidance in https://docs.microsoft.com/aspnet/core/security/authorization/razor-pages-authorization

@Rick-Anderson @scottaddie Thoughts?

**Comment by ayinn** [comment]
ok, thanks very much

**Comment by ayinn** [comment]
Can we not use NuGet with Razor pages?

**Comment by scottaddie** [comment]
@ayinn You can use NuGet with all of ASP.NET, including Razor Pages.
