### ISSUE TITLE
Fetch Data feature of dotnet new react not working for me on Mac

### ISSUE THREAD

**Issue by toddlangdon** [aspnet/Docs#7032]
I'm not following directions correctly or there is a problem...clicking Fetch Data (Mac with 2.1.300) after dotnet run gives me error: Unhandled Rejection (SyntaxError): Unexpected token &lt; in JSON at position 0

If I look in Chrome Dev tools is looks like fetch(api/sampledata/weatherforecasts) call is resolving to public/index.html instead of .NET core web app and returning:  

&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
  &lt;head&gt;
    &lt;meta charset="utf-8"&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"&gt;
    &lt;meta name="theme-color" content="#000000"&gt;
    &lt;base href="/" /&gt;
    &lt;!--
      manifest.json provides metadata used when your web app is added to the
      homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
    --&gt;
    &lt;link rel="manifest" href="/manifest.json"&gt;
    &lt;link rel="shortcut icon" href="/favicon.ico"&gt;
    &lt;!--
      Notice the use of  in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    --&gt;
    &lt;title&gt;portal2&lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;
    &lt;noscript&gt;
      You need to enable JavaScript to run this app.
    &lt;/noscript&gt;
    &lt;div id="root"&gt;&lt;/div&gt;
    &lt;!--
      This HTML file is a template.
      If you open it directly in the browser, you will see an empty page.

      You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the &lt;body&gt; tag.

      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.
    --&gt;
  &lt;script type="text/javascript" src="/static/js/bundle.js"&gt;&lt;/script&gt;&lt;/body&gt;
&lt;/html&gt;

Do I need to tell the javascript fetch to use a different port for api/sampledata/weatherforecasts?

Thanks in advance for any help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3154dec-545a-c749-76ac-1f4581c2f922
* Version Independent ID: cd33922a-0feb-2a37-4e8e-6d7856617a31
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by toddlangdon** [comment]
![image](https://user-images.githubusercontent.com/177922/41379798-ffc39c84-6f30-11e8-88e6-5921b0bb27a3.png)

![image](https://user-images.githubusercontent.com/177922/41379829-1417e276-6f31-11e8-8388-95e2a40334eb.png)

**Comment by toddlangdon** [comment]
dotnet run reports the ASP.NET portion is listening on https://localhost:5001 and http://localhost:5000 and get requests using postman on those to api/sampledata/weatherforecasts return the expected json...just not working for me when call is made from react app

**Comment by toddlangdon** [comment]
I got around this by editting ClientApp/package.json and adding the following line:

"proxy":"https://localhost:5001"

**Comment by marmals** [comment]
Hey.
I have similar problem but when i "http://localhost:5000/api/sampledata/weatherforecasts" on postman i don't get any respone.
