### ISSUE TITLE
GenericHostSample as a Windows Service

### ISSUE THREAD

**Issue by darthg8r** [aspnet/Docs#7040]
I'm struggling to figure out how to get this source under GenericHostSample to run as windows service.  Previously, under IWebHost, we had an extenions method for RunAsService().  I can't find this method.  Can someone throw me a bone and point me in the right direction?

**Comment by guardrex** [comment]
There's a topic to cover the config ... did you see :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service

**Comment by guardrex** [comment]
@darthg8r I was just alerted to more info on this subject: https://github.com/aspnet/Hosting/pull/1492#issuecomment-405298223

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
