### ISSUE TITLE
How to restrict access to some actions?

### ISSUE THREAD

**Issue by alexiordan** [aspnet/Docs#7041]
Formerly one could use something like this in Account Controller:

 [HttpGet]
 [Authorize(Roles = "Master")]
 public IActionResult Register(string returnUrl = null)

How can I do the same thing with the new approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What new approach prevents you from doing that?

**Comment by Rick-Anderson** [comment]
Added to #7042
