### ISSUE TITLE
Scaffolding over existing authorization

### ISSUE THREAD

**Issue by alexiordan** [aspnet/Docs#7042]
Authentication works, but User.IsInRole("X") does not return the expected value (it worked with previous version).
Is this expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by alexiordan** [comment]
Ok, so in the first place I hade to add the AddRoles to Identity configuration
services.AddDefaultIdentity<ApplicationUser>()
                .AddRoles<IdentityRole>()
                .AddEntityFrameworkStores<CityPointDbContext>();

Now it still doesn't work. However, it works the following construction

var user = await UserManager.GetUserAsync(User);
var roles = await UserManager.GetRolesAsync(user);

So, how com User.IsInRole does not work while UserManager.GetRolesAsync works?

**Comment by guardrex** [comment]
Hello @alexiordan ... did you see :point_right: https://docs.microsoft.com/aspnet/core/security/authorization/roles

**Comment by alexiordan** [comment]
Yes, but what is the actual answer to my question though?

**Comment by Rick-Anderson** [comment]
@HaoK  see related #7041

Formerly one could use something like this in Account Controller:
```
 [HttpGet]
 [Authorize(Roles = "Master")]
 public IActionResult Register(string returnUrl = null)
```

How can I do the same thing with the new approach?

**Comment by HaoK** [comment]
Its a bug in AddDefaultIdentity/AddIdentityCore, see: https://github.com/aspnet/Identity/issues/1813

**Comment by Yanal-Yves** [comment]
I followed instructions "Create full identity UI source" after creation of an MVC project with authorization.
When I start the application, click register, fill the form and click "register" button I got an exception : `NotSupportedException: No IUserTwoFactorTokenProvider<TUser> named 'Default' is registered.`

I fixed it by calling .AddDefaultTokenProviders() in the ConfigureServices method like this:
```
services.AddIdentity<IdentityUser, IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();
```
