### ISSUE TITLE
Mention that @inject requires the service

### ISSUE THREAD

**Issue by atifaziz** [aspnet/Docs#7044]
[There's a tip](https://github.com/aspnet/Docs/blame/40ea2f576775f2b95f08292ee1cb7de3cac80dcc/aspnetcore/mvc/views/dependency-injection.md#L67) that reads:

> Don't forget to register types you will request through dependency injection in the  `ConfigureServices` method in *Startup.cs*.

This sounds more like a warning than a tip and leaves a cliffhanger. What will happen if you don't register the types? I suggest the following addition:

> Don't forget to register types you will request through dependency injection in the  `ConfigureServices` method in *Startup.cs*. <ins>Otherwise an exception will get thrown at run-time because internally the service provider is queried via `GetRequiredService`.</ins>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed756b9c-1d37-cd29-dbca-2838ddf152fb
* Version Independent ID: 06064983-8ada-c25d-2adc-ffb4059978f2
* Content: [Dependency injection into views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/dependency-injection.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Great idea @atifaziz! ... I'll take care of it. Thanks for commenting.
