### ISSUE TITLE
Here is where I stand on the whole .NET Core thing

### ISSUE THREAD

**Issue by parkstech** [aspnet/Docs#7045]
I find it wonderful that Microsoft chose to back up 20 years and reinvent the wheel.  I also find it very interesting that 1 million people, mostly off shore resources, chose to copy the Microsoft documentation for the code generator to their own web pages.  The technology is extremely basic and hardly "Real World"!!  There is still no support for saving multiple rows of data from a form to a database (Seems to me that new technology should be a bit more than the predecessor).  This documentation is very, very low in detail and as usual the framework, being very basic and low in functionality, is DOA as usual.  It seems that Microsoft still believes that all businesses have an infinite cash flow and unlimited amount of time for developing applications thus distracting businesses from the real reason they exist in the first place.....to make money!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [ASP.NET Core MVC with EF Core - CRUD - 2 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
Thank you for your feedback. Closing this issue, as the concerns cannot be addressed through docs.
