### ISSUE TITLE
No AccountController in 2.1 template

### ISSUE THREAD

**Issue by jtheisen** [aspnet/Docs#7046]
With 2.1, there's no AccountController being created by the Wizard. Very confusing. Indeed the screenshots are still from 2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jtheisen ... this topic hasn't been updated for 2.1 yet. The work is being tracked on https://github.com/aspnet/Docs/issues/5495. We'll get to it asap.
