### ISSUE TITLE
Code Correction

### ISSUE THREAD

**Issue by RahlForge** [aspnet/Docs#7051]
There is a bug in the example code provided for the second iteration of the Welcome() method. The routing information specifies a default parameter of {id}, which is case sensitive. The method example shows "int ID = 1" as the parameter that is supposed to correlate. This fails, because parameter "ID" != "id". The Welcome() method should be declared as follows:

Welcome(string name, int id = 1)

Note the lowercase "id" parameter, matching the routing information parameter in the Startup.cs file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RahlForge  it's not case sensitive, that's why the image shows 3. It's probably better style to be consistent.

**Comment by RahlForge** [comment]
@Rick-Anderson Weird. When I ran this the first time, it came through with no name and the default 1 for ID. I refreshed twice with the same result (yes, I am running it in non-debug mode). It only ran correctly once I matched the case of the routing information (lowercase 'id'). I just ran it using the uppercase designation, and now it's working as expected. Something went funky the first few times I tried it, apparently. However, I agree that consistency is important, and standard convention would normally indicate that a method parameter should be camel-case (in this case, lowercase). So not a bug, but probably a better convention to make it lowercase. Thank you!

**Comment by Rick-Anderson** [comment]
@RahlForge  why are you doing this and not the Razor Pages version?

**Comment by RahlForge** [comment]
@Rick-Anderson I am behind in my C# learning, so I'm learning both methods. By doing both tutorials, I'll be able to understand how both methods work, their differences, strengths and weaknesses so I can use either method. I understand the Razor Pages version is preferred, but I am not a person who is happy with "just do it because"...I want to know WHY.

**Comment by Rick-Anderson** [comment]
@RahlForge  fantastic. Great idea. When you've finished this series, try https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1

**Comment by RahlForge** [comment]
@Rick-Anderson Thank you. I have added that to my long, long list of "catch up on current C# concepts". 10 years of development experience and a childhood with a teacher as a mother have taught me that "it works so do it that way" isn't enough...you have to know WHY it works that way, because there will come a day it inevitably DOESN'T work that way, and if you don't know WHY it worked in the first place, you won't be able to fix it.
