### ISSUE TITLE
Expand the DI into a view topic to include RP pages?

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#7052]
Dependency injection into views in ASP.NET Core
https://docs.microsoft.com/aspnet/core/mvc/views/dependency-injection

If we update the existing topic to include pages, then we can cross-link the updated topic into the RP area of the TOC (with a revised topic title) ...

Dependency injection into Razor Pages and MVC views in ASP.NET Core

**Comment by Rick-Anderson** [comment]
moved to #10590
