### ISSUE TITLE
Add a warning about 301 Redirects during development

### ISSUE THREAD

**Issue by norachuga** [aspnet/Docs#7053]
The example code for AddHttpsRedirection uses a 301 redirect.

    services.AddHttpsRedirection(options =>
    {
        options.RedirectStatusCode = StatusCodes.Status301MovedPermanently;
        options.HttpsPort = 5001;
    });            

After running this once, the browser will cache that 301. During development, this means changes to this redirection code after that will not be picked up, because the browser will just continue to redirect to 5001. You will have to manually clear the cache after each change.

There should be a note or warning to use 302 status codes during testing (or make use of IHostingEnvironment).

In the next section of this document, there is already a warning against using `UseHsts` in development for comparable reasons, as it will be cached by the browser. It seems desirable to me that a comparable heads-up be given for `AddHttpsRedirection`.

Full disclosure: I was actually stumped by this for over 15 minutes before I realized it was the browser and not some leftover build or IIS config fragment. :sweat_smile:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  should we add this comment to the doc?

**Comment by Tratcher** [comment]
Yeah, 301 is a pain. That's why the middleware defaults to 307. The example can show setting the default. https://github.com/aspnet/BasicMiddleware/blob/5c39221ba3077a957dfea6f2b8161dfa2ba0b636/src/Microsoft.AspNetCore.HttpsPolicy/HttpsRedirectionOptions.cs#L16

We rely on HSTS in the Production environment for permanent client side redirects.
