### ISSUE TITLE
Twitter authentication does not work in ASP.NET Core 2.1

### ISSUE THREAD

**Issue by csharpfritz** [aspnet/Docs#7054]
Tried adding Twitter authentication information to the new Identity model in ASP.NET Core 2.1 and it never routes to the Twitter service to prompt me to login.  Source we tried is in the dev branch at:  https://github.com/csharpfritz/corewiki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb577d84-a06b-4d3e-a1c4-92c8a97a85aa
* Version Independent ID: 528fcbb8-5b0f-8340-743f-df612319a229
* Content: [Twitter external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/twitter-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@01binary can you review?

**Comment by 01binary** [comment]
This may take me a day to get to, will do as soon as I can.

**Comment by blowdart** [comment]
It wasn't an asp.net error, it was Jeff's javascript which disabled buttons on form submit, when the buttons had values that the asp.net needed. So no doc updates needed.
