### ISSUE TITLE
what is different with RewriteMiddleware

### ISSUE THREAD

**Issue by infofromca** [aspnet/Docs#7059]
use RewriteOptions.AddRedirectToHttps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Are you asking why [AddRedirectToHttps](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.rewrite.rewriteoptionsextensions.addredirecttohttps?view=aspnetcore-2.1#Microsoft_AspNetCore_Rewrite_RewriteOptionsExtensions_AddRedirectToHttps_Microsoft_AspNetCore_Rewrite_RewriteOptions_System_Int32_System_Nullable_System_Int32__) is not used in place of `app.UseHttpsRedirection();` ?

**Comment by Rick-Anderson** [comment]
[URL redirect to a secure endpoint](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1&tabs=aspnetcore2x#url-redirect-to-a-secure-endpoint) uses `AddRedirectToHttps`

@Tratcher  should that be updated to recommend `app.UseHttpsRedirection();` ?
Why is `app.UseHttpsRedirection();`  used rather than `RewriteOptions.AddRedirectToHttps` ?

**Comment by guardrex** [comment]
You can set the status code and port with the URL Rewriting Middleware.

We already have this note in the URL Rewriting Middleware topic ...

> When redirecting to HTTPS on port 443 without the requirement for additional redirect rules, we recommend using HTTPS Redirection Middleware. For more information, see the Enforce HTTPS topic.

**Comment by guardrex** [comment]
@Rick-Anderson How about a reverse note ... link from this topic (Enforce HTTPS) out to the URL Rewriting Middleware topic that says 'if you need to set the status code or status code and port, use the rewriting middleware.'

**Comment by Rick-Anderson** [comment]
@guardrex fantastic idea.

**Comment by guardrex** [comment]
Sure ... piece of :cake:
