### ISSUE TITLE
ASPNET_ENV variable should be changed in docs to Hosting:Environment

### ISSUE THREAD

**Issue by st-gwerner** [aspnet/Docs#706]
It appears that in ASP.NET 5 RC1, the ASPNET_ENV environment variable was changed to Hosting:Environment. http://docs.asp.net/en/latest/fundamentals/environments.html should be updated to reflect the change.

**Comment by RehanSaeed** [comment]
It seems to be `Hosting:Environment` for Windows and `Hosting__Environment` (Note the double underscore) for Linux and OSX according to [IHostingEnvironment](https://github.com/aspnet/Hosting/blob/04c30c8bb769aa5aea9fc7e63b0f8d47b81bdb72/src/Microsoft.AspNet.Hosting.Abstractions/IHostingEnvironment.cs).

Is that correct? Why have different names based on the OS?

**Comment by GuardRex** [comment]
... on the same subject (referring to http://docs.asp.net/en/latest/fundamentals/environments.html#determining-the-environment-at-runtime ), it might be good to mention setting the environment (outside of Program:Main) isn't a good idea per https://github.com/aspnet/dnx/issues/3214#issuecomment-160432649. I think explicitly showing how to set it in code with Program:Main would be good for those cases where the app should detect its environment on its own (no config files) and set the env var itself.

**Comment by davidfowl** [comment]
The variables are changing again post RC1 so I wouldn't change asp_env just yet

**Comment by csunali** [comment]
@davidfowl - What are they changing to?

I have an application that ignores "Hosting:Environment" but accepts "ASPNET_ENV" at the moment.

It is an RC 2 application. 

I have another application which I created using ASP.NET Tools RC1 Update 1 templates and it just works fine with "Hosting:Environment".

Do you have any clue?

**Comment by danroth27** [comment]
We should update the RC1 docs and then track changing this again for RC2.

**Comment by mikes-gh** [comment]
Now its decided that `Hosting:Environment` is no longer and `ASPNET_ENVIRONMENT` is the replacement is it time for the change?  I tried to do a search to see how much work it would be but for some reason github search removes colon which gives me way to many hits for `Hosting:Environment`  From browsing I know its in a lot of places.

Also is it visual studio that creates launchSettings.json  If so is a tooling update required

**Comment by davidfowl** [comment]
The tooling has been updated, it's just not released yet :smile:

**Comment by mikes-gh** [comment]
Just out of interest will we see a tooling update with RC2?

**Comment by davidfowl** [comment]
Yes, there's always a tooling update paired with major releases.

**Comment by optlink** [comment]
Setting ```ASPNET_ENVIRONMENT``` appears to do nothing at all. I always see ```Hosting environment: Production``` as of several versions ago. I'm running on the latest dev packages. Can anyone shed some light on this?

**Comment by davidfowl** [comment]
@optlink Posting a sample solution would be most helpful.

**Comment by optlink** [comment]
Here is a simple solution I updated to the latest RC2 build that exhibits the same issue: [WebApplication2.zip](https://github.com/aspnet/Docs/files/88531/WebApplication2.zip)

**Comment by mikes-gh** [comment]
@optlink Sounds like you're hitting the tooling bug when tooling gets out of sync with launchSettings.json
When this happens launchSettings.json can show APNET_ENVIRONMENT but the tooling and the laugh are using Hosting:Environment.  When it gets to this stage because Hosting:Environment is no longer valid it defaults to Production.

I am not sure of the exact scenarios where it happens but I have seen it more than once on my machine.
If you rest the  variable in the GUI it should work again.

**Comment by optlink** [comment]
Yes, that was the issue. Thank you very much, that one has been bugging me for a while.

**Comment by mikes-gh** [comment]
@davidfowl The title of this issue is no longer correct as things are moving to ASPNET_ENVIRONMENT.  Probably best to close to save confusion

**Comment by danroth27** [comment]
Closing this issue as we will be moving to ASPNET_ENVIRONMENT

**Comment by davenewza** [comment]
Note to those who stumble across this thread.  It has changed to `ASPNETCORE_ENVIRONMENT  `in RC2.
