### ISSUE TITLE
Error in the "Resolve a scoped service within the application scope" section for .NET Core 2.0

### ISSUE THREAD

**Issue by CricutBrad** [aspnet/Docs#7060]
The line in the catch statement below gives a compiler error about Program being a static class.  
 var logger = services.GetRequiredService&lt;ILogger&lt;Program&gt;&gt;();

Error	CS0718	'Program': static types cannot be used as type arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@CricutBrad Your timing is *timely* :watch:. I was going to address this sample next for our 2.1 sample updates on #5495.

Although I haven't looked at the topic+sample yet, I'll open it and see what's what. I'll get back to you soon.

**Comment by guardrex** [comment]
Yes, @CricutBrad ... this was just about to be updated on #5495. It's next on my list.

For 2.1, do it this way ...

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        var host = CreateWebHostBuilder(args).Build();

        using (var scope = host.Services.CreateScope())
        {
            var services = scope.ServiceProvider;
            var db = services.GetRequiredService<ApplicationDbContext>();

            db.Database.EnsureCreated();

            if (!db.Messages.Any())
            {
                try
                {
                    db.Initialize();
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, $"An error occurred seeding the database. Error: {ex.Message}");
                }
            }
        }

        host.Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseStartup<Startup>();
}
```
That should work. This particular example is what we settled on for initializing databases in the samples. If it doesn't work, ping back here, and we'll dig a little deeper.

That's 2.1 code I'm showing. If you're still on 2.0, you'll need the 2.1 SDK [download](https://www.microsoft.com/net/download/windows) and a 2.1 project.

**Comment by CricutBrad** [comment]
Hey Luke,

Thanks for a quick reply!  Funny that this was about to be done, one of those “speak of the devil” type scenarios…

I am using this to initialize a connection to the Amazon SQS service, and I was a bit perplexed how to do it when it is an async operation.  You typically don’t kick off an async op in a constructor, unless it is an async void.  That is ultimately what I ended up doing, having a function that gets called in the code below that is an async void connection initialization.

I’ll let you know if I run into anything,

Thanks!

Brad
