### ISSUE TITLE
Update .openpublishing.publish.config.json to support xref links on API

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#7064]
Per `@mairaw`
, I’d always use xref links and not regular links that. 

For example, to be able to reference APIs from the UWP reference, we added the following line to our repo:
https://github.com/dotnet/docs/blob/master/.openpublishing.publish.config.json#L28

* Enable xref links for API
* Update a doc with xref API

**Comment by Rick-Anderson** [comment]
@scottaddie  can you do this on current sprint?

**Comment by scottaddie** [comment]
@Rick-Anderson Yes. I plan to do this after I finish the LibMan docs, which I'm currently working on.
