### ISSUE TITLE
explain how to set environment in Azure better

### ISSUE THREAD

**Issue by samnaseri** [aspnet/Docs#7068]
For setting environment in Azure this documentation only says "Add the key and value in App settings.". But it does not say what should I set for key. Is it Aspnetcore_Environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @samnaseri ... this topic + sample is coming up for the 2.1 update on #5495. I'll address this at the same time.

**Comment by davidfowl** [comment]
@guardrex this should be part of the configuration docs. There's nothing here about app service:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration

**Comment by guardrex** [comment]
@davidfowl Config of environment is only lightly covered, and the topic throws the reader over to the *Multiple environments* topic to deal with the subject in detail.

I opened https://github.com/aspnet/Docs/issues/7102 so that we can discuss config broadly later ... after a handful of issues are fixed first.
