### ISSUE TITLE
ASP.NET 5 RC1 Documentation For Social Logins Missing NuGet Package Microsoft.AspNet.Authentication.Facebook

### ISSUE THREAD

**Issue by renzska** [aspnet/Docs#707]
The article at https://docs.asp.net/en/latest/security/sociallogins.html needs to note that the NuGet package, Microsoft.AspNet.Authentication.Facebook, needs to be added for the code in the article to work, explicitly:

app.UseFacebookAuthentication(options =>
{
  options.AppId = Configuration["Authentication:Facebook:AppId"];
  options.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
});

**Comment by Rick-Anderson** [comment]
While fixing this another customer requests more info on each provider. See https://docs.asp.net/en/latest/security/sociallogins.html#comment-2387653643

**Comment by danroth27** [comment]
Yeah, it used to be that all of the packages for the external authentication providers were included in the template, but now they are not and you have to add the packages you need.

**Comment by danroth27** [comment]
@Rick-Anderson Please handle this as part of https://github.com/aspnet/Docs/issues/1187.
