### ISSUE TITLE
User not in sample

### ISSUE THREAD

**Issue by Alienroid** [aspnet/Docs#7072]
The code is not in the sample. 

public Task SendPrivateMessage(string user, string message)
{
    return Clients.User(user).SendAsync("ReceiveMessage", message);
}

Also, I couldn't get User to work. What's the 'user' in "string user" above? connection.User?.FindFirst(ClaimTypes.Email)?.Value; I got null.

--edit--
I removed user identifier customization (which in the sample was Claim.Email). The default ClaimTypes.NameIdentifier is working

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@rachelappel  can you verify the samples folder has a full working version used in the tutorial?

**Comment by rachelappel** [comment]
@Alienroid Correct. That is the one snippet in the doc that is not part of the sample. I will move it into the sample. For now, you can copy and paste it into the `ChatHub`  class. It's fine for the hub to have multiple public methods that SignalR can call.

It looks like Brennan is using the Context.ConnectionId in the rest of the sample to get the user.

**Comment by BrennanConroy** [comment]
User is `Context.UserIdentifier`

**Comment by Alienroid** [comment]
if I follow the tutorial to change ChaimType to Email: 
` return connection.User?.FindFirst(ClaimTypes.Email)?.Value;`
then, UserIdentifier I got null.

remove customization, using the default, which is ClaimTypes.NameIdentifier, UserIdentifier is correct.

**Comment by shlomitubul** [comment]
whare i can find Authentication and Authorization  for wpf client ?

**Comment by tdykstra** [comment]
@Coscotex -- adding here your comment from #8285, will close #8285 as a duplicate.

> Can we please have a working sample where you actually used "connection.User?.FindFirst(ClaimTypes.Email)?.Value;"

> Since ClaimTypes.Email is more unique than just the User's Name, it would be really helpful to see a working example.

**Comment by Alienroid** [comment]
Hi,

@bradygaster 

The original ask has nothing to do with Group. The article is "Manage users and groups in SignalR". The issue is with the 'users' section, not the group section. The issue is sample code on page doesn't work (with ClaimTypes.Email). The sample code in github also doesn't include this.

This comment is just as recommendation to either update the sample that works with ClaimTypes.Email, or leave the customization and stick with default which is ClaimTypes.NameIdentifier, or remove this misleading sample.

I removed customization and I am using the default, which is ClaimTypes.NameIdentifier.

**Comment by bradygaster** [comment]
re-opening issue as it would be better if the doc's sample could be cleaned up to work.

**Comment by Rick-Anderson** [comment]
@BrennanConroy 	can you update this or assign someone?

**Comment by bradygaster** [comment]
@Rick-Anderson assigning the new-and-awesome SignalR label so we can triage these during our regular team triage.

**Comment by bradygaster** [comment]
Closing as this will be repaired by #10632
