### ISSUE TITLE
The Kestrel port is shown in the browser

### ISSUE THREAD

**Issue by jbltx** [aspnet/Docs#7073]
With this documentation, i ended up with the Kestrel port (5000/5001) shown in the browser. So when I go to http://example.com it becomes https://example.com:5001.

Is it possible to "hide" this port ? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
ping @shirhatti

**Comment by shirhatti** [comment]
Unless you're using the default ports (80 for HTTP and 443 for HTTPS), you can't **hide** the port in your browser.
