### ISSUE TITLE
Couple of fixes needed to doc

### ISSUE THREAD

**Issue by dmcquiston** [aspnet/Docs#7075]
4th screenshot doesn't include HTTPS checkbox checked by default. So I unchecked it not knowing if it was right.

I just installed .NET Core 2.1.300 today and this sample doesn't work. I was able to start the application, but the chat messages/user names didn't show up in either browser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778aaeae-2fa8-fb73-b644-8e99ee06398e
* Version Independent ID: 159a95c8-7afd-bb03-fdfc-2323559ef50a
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/get-started?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/signalr/get-started.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/get-started.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by dmcquiston** [comment]
Not to mention that the default Startup.cs with 2.1 looks different than what you have above. I tried both what is above and what is comes in the template VS version 15.7.3

**Comment by rachelappel** [comment]
@dmcquiston It doesn't matter of the HTTPS checkbox is checked or not. VS will run the project exactly the same, but with an https URL if it is checked.
In Startup, there are some calls that setup CORs (cross origin requests). Keeping it or not using it should have no effect on working through the sample.
Can you provide some more details on it not working? If you use F12 or dev tools in the browser, is there a JavaScript error? If you try to debug with the VS debugger, what happens?

**Comment by Rick-Anderson** [comment]
@rachelappel  can you update the screenshots so they match and verify the code matches?

**Comment by dmcquiston** [comment]
Got it to work...just missed the tidbit saying to put signalr.js in a sub-folder of lib called signalr. Thank you!

- Dan McQ
________________________________
