### ISSUE TITLE
Object arrives empty in method

### ISSUE THREAD

**Issue by jonasmarco** [aspnet/Docs#7077]
In my case, the ajax request works correctly, it prints the values in the console, but when it arrives in the Create method, the object is empty. And then it registers the name as null.

![Print 1](https://i.imgur.com/cs9jzOm.jpg)

![Print 2](https://i.imgur.com/EQUO2uo.jpg)

**Comment by scottaddie** [comment]
@jonasmarco Can you please provide a link to the doc you're looking at?

**Comment by jonasmarco** [comment]
hi @scottaddie there is https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1

**Comment by davidfowl** [comment]
Can you show your entire controller and show how you are posting the form body?

**Comment by davidfowl** [comment]
You have some JavaScript code that’s doing the post right? What does that look like?

**Comment by jonasmarco** [comment]
Here: https://hastebin.com/fegayoyuno.js

**Comment by jonasmarco** [comment]
I think I found the problem, it was the lack of encode, I just added these two lines of code in the ajax call.

`dataType: "json",
contentType: "application/json; charset=utf-8",`

**Comment by jonasmarco** [comment]
@davidfowl and @scottaddie 
Thanks for helping me!
