### ISSUE TITLE
Broken links in “ASP.NET Core Model Providers Sample” README 🔗

### ISSUE THREAD

**Issue by atifaziz** [aspnet/Docs#7078]
All the links in the [README for “ASP.NET Core Model Providers Sample”](
https://github.com/aspnet/Docs/tree/f3504759386ce84d3d87196058b8c1be4a3f4333/aspnetcore/mvc/razor-pages/razor-pages-conventions/sample) are broken (i.e. 404).

**Comment by guardrex** [comment]
Ah ... so they are. Thanks for the catch @atifaziz ... I'll fix those up right now.
