### ISSUE TITLE
Introduce DataType.Date in this tutorial.

### ISSUE THREAD

**Issue by RahlForge** [aspnet/Docs#7081]
I had to add [DataType(DataType.Date)] before my declaration of ReleaseDate in Movie.cs in order to get the correct format on my CRUD pages, as my Create page wanted to include the Time and would throw a required field error if I didn't.

[DataType(DataType.Date)]
[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", 
    ApplyFormatInEditMode = true)]
public DateTime ReleaseDate { get; set; }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, the tutorial has you do that.

**Comment by RahlForge** [comment]
@Rick-Anderson The tutorial has you add the DisplayFormat, but not the DataType. DataType.Date was required when I ran it to remove the time from the ReleaseDate.

**Comment by Rick-Anderson** [comment]
@RahlForge  keep going, it does use `DateType`

**Comment by RahlForge** [comment]
@Rick-Anderson I don't see it. Is it in a later lesson?

**Comment by Rick-Anderson** [comment]
yup.
Entering Time is super annoying. 
I think I'll introduce data type date sooner.

**Comment by RahlForge** [comment]
@Rick-Anderson I agree. Since this page of the tutorial is where the ReleaseDate is created and modeled, and it includes the portion on adding the DisplayFormat annotation, it would make sense to add the DataType.Date annotation on this page so the reader's compilation will match the examples (the example screenshots do not include the Time entry). Annotations can still be clarified later, but for consistency, the ReleaseDate should be formatted here to match the example pictures. Otherwise, it's confusing (and, as you mentioned, annoying) to have to enter the time. Alternatively, you could update this page to note that the Time will have to be entered until the annotations are clarified later.
