### ISSUE TITLE
Missing/incomplete information on resolving scaffolding error

### ISSUE THREAD

**Issue by skeeler** [aspnet/Docs#7089]
Some information missing in the following section of this content:

Scaffold the model
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1#scaffold-the-model

Receiving the following error:

   No executable found matching command "dotnet-aspnet-codegenerator"

But the content does not specify how to resolve this issue. After some research, I found one way (there may be others) as follows:
1. Navigate to: https://www.nuget.org/packages/dotnet-aspnet-codegenerator/
2. Open a console window and enter the command to install the aspnet-codegenerator tool

Regards,
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@skeeler  thanks for pointing that out. It's a change for 2.1
