### ISSUE TITLE
Core 2.1 Projects do not include bundleconfig.json file

### ISSUE THREAD

**Issue by MSIH** [aspnet/Docs#7090]
None of the Core 2.1 Web seems to contain the bundleconfig.json file. I think you now have to create it manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minifiy static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Cross-reference: https://github.com/aspnet/templating/issues/326

**Comment by sbsw** [comment]
What is the status of the "new package management/bundle+minify system"? VS 15.8 acquired the new LibraryManager, which knows how to fetch packages from cdnjs.com (which contains maybe 50% of the stuff I need, but that's a separate issue). Is LibraryManager going to support bundling and minification, or are we still waiting for some other supported tool to show up in a future VS release?

**Comment by guardrex** [comment]
Our topic is about to go live: https://github.com/aspnet/Docs/pull/8008

Before it goes live, you can look at the diff to see the topic's content.

> Is LibraryManager going to support bundling and minification

No, it's not a package manager, bundler, or minifier. We document the currently recommended approaches: https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification

> some other supported tool to show up in a future VS release

See the discussion here: https://github.com/aspnet/Home/issues/3023
