### ISSUE TITLE
Need more details on opting out of HTTPS after project upgrade

### ISSUE THREAD

**Issue by agr** [aspnet/Docs#7096]
Just upgraded old project to latest ASP.NET core and now it fails to start complaining about being unable to configure HTTPS endpoint (which it shouldn't have being doing in the first place - project never used HTTPS) and it is unclear how do I opt out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Why would you want to opt out?  The document is not about optioning out of HTTPS.
What is the error message?
You can build a new project without HTTPS
`dotnet new webapp --no-https -au Individual`

**Comment by agr** [comment]
> Why would you want to opt out?

I don't even know what to say... Because I don't want HTTPS on my web site? Because I don't like when framework decides for me when it is time to start using it?

The error message went away after installing the .net core SDK 2.1 (logical, right?), but it started with "Unable to configure HTTPS endpoint" and suggested to run `dotnet dev-certs <something>` (which failed when I tried it, and I don't remember how).

I am yet to deploy it to the actual hosting location, so maybe it'll reproduce there.

I don't want a new web app. I was upgrading existing asp.net core 2.0 project to asp.net core 2.1. HTTPS was never mentioned anywhere neither in code nor in configuration, yet it failed to start attempting to configure it (or at least complaining about its inability to configure it) after the upgrade.

As far as I can see, new project with HTTPS differs from the one without only by having additional 

            app.UseHsts();
            app.UseHttpsRedirection();

lines in `Startup.cs`. My project had neither of those and yet I saw the HTTPS related error...

**Comment by agr** [comment]
In my hosting environment it didn't reproduce and I see in logs that Kestrel does not try to listen for https, but on my dev box it does:
```
Now listening on: https://localhost:5001
Now listening on: http://localhost:5000
```
I don't see any place where it is configured and I have no idea how it picks a certificate to use for HTTPS.

On my hosting I have an nginx in front of Kestrel, so if I ever decide to use HTTPS it will be terminated there and I *never* would need to have HTTPS enabled in a Kestrel.

**Comment by Rick-Anderson** [comment]
You can build a new project without HTTPS
`dotnet new webapp --no-https -au Individual`

And see how that opts-out of HTTPS.

**Comment by idoop** [comment]
I also config https at load lalancer, so I don't want enable https in my project.
Is there any way to close https to asp .net core 2.1.1 envirnment?

**Comment by idoop** [comment]
@agr I find a way to close https.
Just add `"applicationUrl": "http://*:PORT"` in *launchSettings.json* file.
Like this:
```
{
  "profiles": {
    "Your_Proj_Name": {
      "commandName": "Project",
	  "applicationUrl": "http://*:5000"
    }
  }
}
```

**Comment by goldenbeard** [comment]
I have also found that if the sslPort is set to anything other than zero in the following section of the _launchSettings.json_ file, kestrel will still attempt to bind an SSL port during debug sessions:

``` json
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:52901",
      "sslPort": 0
    }
  }
```
Yes, that's right, kestrel is using the iisExpress section of this file to pick up some of its config.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
