### ISSUE TITLE
Clarify code

### ISSUE THREAD

**Issue by dementic** [aspnet/Docs#7103]
Where does `_defaultFormOptions` come from ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's in the StreamingController ...

https://github.com/aspnet/Docs/blob/74a44669d5e7039e2d4d2cb3f8b0c4ed742d1124/aspnetcore/mvc/models/file-uploads/sample/FileUploadSample/Controllers/StreamingController.cs#L25

Note that the topic+sample are due for an overhaul on #5331, and we've had some reports that the sample is broken.

@dementic, I'll close now, but we can re-open this issue if you want to discuss it further.
