### ISSUE TITLE
localhost is currently unable to handle this request.

### ISSUE THREAD

**Issue by kudlatiger** [aspnet/Docs#7105]
I have downloaded the code from [https://github.com/aspnet/Docs/tree/master/aspnetcore/host-and-deploy/windows-service/sample](https://github.com/aspnet/Docs/tree/master/aspnetcore/host-and-deploy/windows-service/sample) and hosted as windows service.

But when I enter http://localhost:5000 , page is not loading.
What I might be missing?

I have installed using below command
sc create MyService binPath= "c:\svc\aspnetcoreservice.exe"

**Comment by guardrex** [comment]
1. Does the app run as a console app (`dotnet run --console` from the project folder at a command prompt)?
1. You started the service after you created it (`sc start MyService`)?
1. Is the app on an IIS server behind a firewall (open port 5000 in the firewall)?

**Comment by guardrex** [comment]
AFAIK the sample and instructions are good. I need more info to diagnose further. Closing now, but we can re-open if needed.
