### ISSUE TITLE
Please provide a clean example for Core 2.1 that doesn't use ApplicationUser and Scaffolding (or Roles)

### ISSUE THREAD

**Issue by sumnone** [aspnet/Docs#7108]
In general, we're not supposed to use Roles now (vs Claims moving forward except in limited cases), and everything is tucked away nice and clean in Core 2.1, only for all the examples (that I can find) to tell us to use Roles or scaffold everything out again and revert back to ApplicationUser. I realize this example will probably work in Core 2.1. However, can you please provide an example that does something similar as the above example and conforms to how Core 2.1 leaves everything tucked away clean with IdentityUser? In other words, for those that don't need to customize their Identity user, what is the solution for authorization and policies? How would you do like an admin or owner type of user? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b66f8ffa-699c-8b11-0cab-805f5953805f
* Version Independent ID: 7c151ed5-fd78-84fd-a08a-88912990c4ca
* Content: [Create an ASP.NET Core app with user data protected by authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/secure-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/secure-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
We're scheduled to update this topic/sample for 2.1 in #6290

**Comment by Rick-Anderson** [comment]
@sumnone  the 2.1 version uses `IdentityUser`
See #7651
