### ISSUE TITLE
Links to docs broken

### ISSUE THREAD

**Issue by chevinbrown** [aspnet/Docs#7110]
While reading this page: https://aspnetcore.readthedocs.io/en/stable/tutorials/dotnet-watch.html, I found that the link to "download sample application" is broken.

Upon trying to edit that page in github, I found it was either not editable or also missing.

**Comment by guardrex** [comment]
Hi ... that's an ancient link to a retired topic. Try this one ...

https://docs.microsoft.com/aspnet/core/tutorials/dotnet-watch

**Comment by guardrex** [comment]
I'll close now; but if you would like to discuss further, we can re-open this issue.

**Comment by guardrex** [comment]
cc/ @Rick-Anderson @scottaddie There's no redirection in place for these ...

http://aspnetcore.readthedocs.io/en/stable/

... and they're not super helpful about directing away from their service ...

http://docs.readthedocs.io/en/latest/user-defined-redirects.html

... but perhaps all of these topics could redirect a Read the Docs landing page that tells folks "Go here" to get to our docs.

**Comment by chevinbrown** [comment]
This is one of the hardest things about learning dotnet and asp is the legacy that comes up upon googling naive terms. 
Thanks for the quick response!

**Comment by guardrex** [comment]
Sure ... sorry about the confusion there. I'm not sure if anyone knew about the old doc set. I personally don't see any impediment to redirecting all of them to that Read the Docs landing page and then having that say readers should come over here. It's "above my pay grade" tho. :smile: lol ... They'll figure it out now that you surfaced the problem. Thanks for letting us know.

**Comment by Rick-Anderson** [comment]
@danroth27  http://aspnetcore.readthedocs.io/en/stable/ gets a fair amount of traffic - Should we try to get them to remove it?

**Comment by danroth27** [comment]
I can delete the aspnet readthedocs project, but I'm worried about what that would break.

**Comment by Rick-Anderson** [comment]
I get alot of comments from http://jakeydocs.readthedocs.io too. I've left feedback asking him to pull it down.
http://jakeydocs.readthedocs.io/en/latest/security/authentication/2fa.html#comment-3940987563


AvInAsH BARNWAL • 6 days ago 
i really cant find ISmsSender interface. I have .netcoreapp2.1 app with Individual Authentication (having RCL) , and I want to add Twilio Provider to my app, however, the ISmsSender cannot be found. What is the library in which it can be found ?
