### ISSUE TITLE
Environment setting requires to be manually set

### ISSUE THREAD

**Issue by KyleGobel** [aspnet/Docs#7111]
I'm leaving this feedback in the docs because I'm unsure if this is a bug or intended.

It states in the docs that the default environment variable for environment is ASPNETCORE_ENVIRONMENT.  This makes it sound like if I set that variable that the host will use that for it's hosting environment by default.

This is not the case

```cs
   static async Task Main(string[] args)
   {
       var host = new HostBuilder()
           .ConfigureHostConfiguration(c => { c.AddEnvironmentVariables(); })
           .ConfigureAppConfiguration(c => { c.AddEnvironmentVariables(); })
           .Build();

       var expectedEnv = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
       var actualEnv = host.Services.GetRequiredService<IHostingEnvironment>();
       Console.WriteLine($"Environment should be: {expectedEnv}, actual is {actualEnv.EnvironmentName}");
       // Environment should be: Development, actual is Production

       await host.RunAsync();
   }
```

I think this is fine, but I think the docs are misleading.  To get the behavior I desired I have the following to the builder.

```
    .UseEnvironment(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT"))
```

If this is the way it's intended this should be clarified in the docs, and also probably no mention of the ASPNETCORE_ENVIRONMENT since this doesn't have a whole lot to do with "ASPNETCORE" the product as we think about it (web things).

Just some thoughts

**EDIT**
After re-reading the section a couple times, I see the 'SetUsing' section, so I guess this could make sense.  Though in my opinion it could be explained a bit better?  I'm not sure how many people would pick up on that.  Maybe I'm just the dummy though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **asp.net-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @KyleGobel. Thanks for commenting ...

> It states in the docs that the default environment variable for environment is ASPNETCORE_ENVIRONMENT. 

By "the docs" and "but I think the docs are misleading" ... you mean the docs in general, correct? This topic doesn't get into the env var prefix. For the Web Host and *Multiple environments* topics, we fixed things up on #7092, which is in the final stages of review now and will appear live within a day or two.

@Tratcher, shouldn't we mirror that prefix info from the web host topic over here?

To go with `c.AddEnvironmentVariables()` you'd need to set the `ENVIRONMENT` env var. Otherwise to use `ASPNETCORE_ENVIRONMENT`, use `c.AddEnvironmentVariables(prefix: "ASPNETCORE_")`.

> this doesn't have a whole lot to do with "ASPNETCORE" the product as we think about it (web things).

Coming later according to the engineers. The Generic Host will replace the Web Host and also handle request-response workloads.

**Comment by KyleGobel** [comment]
> By "the docs" and "but I think the docs are misleading" ... you mean the docs in general, correct? This topic doesn't get into the env var prefix. 

I'm referring to the generic-host docs, and trying to troubleshoot why my environment was not being set correctly.

This is the part I was referring to, which in my opinion, is wrong.
![image](https://user-images.githubusercontent.com/4460054/41611206-289ce83c-73bd-11e8-8059-697f2d902e5e.png)

**Comment by Tratcher** [comment]
Yeah, ASPNETCORE_ env vars aren't read by default for generic host.

**Comment by guardrex** [comment]
Yes ... I think we should mirror what we did with the Web Host there.

**Comment by guardrex** [comment]
Thanks for reminding me @KyleGobel ... *I obviously didn't look!* 🤦‍♂️

I'm going to squeeze this on to #7098 right now.

**Comment by guardrex** [comment]
Oh ... we have it on #7092. We're good. That PR hasn't merged to live yet. Stand-by for 24 hours @KyleGobel for the updated topic to appear in the docs. This issue is a dup of #6760.
