### ISSUE TITLE
A tiny Typo discovered

### ISSUE THREAD

**Issue by yamazaroon** [aspnet/Docs#7125]
Under the section Scaffold the Instructor Model
 https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.0#scaffold-the-instructor-model
Towards the lower part of this section when referring to the "OnGetAsync" method having two includes, it instructs the user to:
"Examine the query on the Pages/Instructors/Index.cshtml page:"  
This should actually read:
"Examine the query on the Pages/Instructors/Index.cshtml.cs page:"  
Just the ".cs" is missing from the filename.  Probably not something that will throw many people off.

Thank you again for all of your tutorials!  They are proving to be a valuable resource for my learning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.0#scaffold-the-instructor-model)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @yamazaroon ... I'll patch that up right now.
