### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by mcfin** [aspnet/Docs#7129]
Where you say: "Add the following markup to the end of the Pages/Courses/Index.cshtml Razor Page:"

Shouldn't it read: "Add the following markup to the end of the Pages/Instructors/Index.cshtml Razor Page:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mcfin** [comment]
Sorry, just saw that this was already reported by Pangar

**Comment by guardrex** [comment]
Dup of #6427 

Thanks @mcfin ... I just fixed it on #7137.
