### ISSUE TITLE
Identity - Update to  2.1

### ISSUE THREAD

**Issue by martinpetrovaj** [aspnet/Docs#7131]
Guys, you can't be serious about completely changing Identity from 2.0 to 2.1 and totally ignoring the docs. Besides, why do we now have to deal with this Razor code behind nonsense in MVC applications instead of controllers? You're totally arbitrarily mixing two different approaches and forcing us to work with this mess - all that without any proper documentation. Is there still a way to scaffold MVC like Identity code when creating a new project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by tstivers1990** [comment]
You don't *have* to deal with Razor Pages if you don't want to. Identity UI is just a UI implementation of Identity. It can still be used without Identity UI at all. The documentation is lacking on how to go about doing this. There has been an issue raised for the documentation issues (#6990), and it appears the docs have been updated in the repo, and are just waiting for the next publish.

While I'm a fan of Razor Pages, I'm not a fan of how Identity UI uses Areas by default. I'm not a big fan of areas because I find it counter-intuitive for my projects. But you can write your own implementation of the Identity UI. And I think, in a lot of cases, that's probably the best approach anyway.

Identity itself hasn't changed much. It's just the default template that has changed.

**Comment by Rick-Anderson** [comment]
Per https://github.com/aspnet/Identity/issues/1825

>Maintaining two versions of the same codebase (MVC and Razor Pages) is very expensive for us and there are no real benefits from having an MVC implementation compared to a Razor Pages version. Both flavors are fully in ASP.NET.

**Comment by plamenyovchev** [comment]
Guys, this is really nonsense. I don't know why you did this.

**Comment by sbsw** [comment]
This documentation doesn't match the current reality.  At step 2, you tell us to add this code to Startup.cs:

    services.AddIdentity<ApplicationUser, IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

But (1) the new project already has a call to

            services.AddDefaultIdentity<IdentityUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

and, (2) the new project doesn't have an ApplicationUser class, so your code doesn't compile.

**Comment by Rick-Anderson** [comment]
@seejessicacode 

>- find what to use in place of ApplicationUser.

`ApplicationUser` -> `IdentityUser`

>- compares AddDefaultIdentity() and AddIdentity() to guesstimate which is appropriate going forward
>- roll with AddDefaultIdentity() and hope it doesn't negatively impact later steps

No need to change from `AddDefaultIdentity` per [Changes to authentication code](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-authentication-code)

**Comment by pangjianxin** [comment]
when the docs would be updated?,what the hell you doing?

**Comment by tstivers1990** [comment]
@pangjianxin Feel free to submit a pull request if you don't feel like progress is moving quickly enough on this.

**Comment by Baxtex** [comment]
Please update the docs, been ripping my hair on how to set this thing up.

**Comment by Rick-Anderson** [comment]
Note to self. 40K PV
