### ISSUE TITLE
Missing "Select Department" line of code, or, code description is inaccurate. 

### ISSUE THREAD

**Issue by yamazaroon** [aspnet/Docs#7132]
There appears to be one line of code missing in the following section:
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1#update-the-courses-edit-page

Under the section that instructs us to "Update Pages/Courses/Edit.cshtml" the instructions state that the "preceding markup" has added a "Select Department" statement to the pull-down list.  However, it appears that the line of code to add the statement is left out in the example.

On the other hand, it may have been intentionally left out for editing section as a Department would have already been selected when the Course was created.  If this is the case, then the statement describing what the preceding code has added should not include the statement:
"Adds the "Select Department" option. This change renders "Select Department" rather than the first department.

Removing the "Select Department" option would also seem to render the validation statement unnecessary, as there would be no way to unselect a department before saving changes.

Once again, thank you for the great tutorials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by m-henderson** [comment]
@Rick-Anderson can you assign this issue to me so I can fix it up and submit a PR?

**Comment by Rick-Anderson** [comment]
@m-henderson  sorry missed this. I got it fixed. Thanks for the offer.
