### ISSUE TITLE
Out of date document

### ISSUE THREAD

**Issue by EdiWang** [aspnet/Docs#7135]
As far as I know, bower is removed in the latest ASP.NET Core 2.1 release. There are no menus in VS2017 under asp.net core projects. Please update this document.

FYI: 
https://github.com/aspnet/templating/issues/48 
https://stackoverflow.com/questions/48268700/no-bower-npm-config-files-are-part-of-the-latest-net-core-2-0-web-app-templates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd636ce2-7f47-77e4-e12c-461bd6951c65
* Version Independent ID: 86160014-970f-5662-a446-308fd4c1b331
* Content: [Manage client-side packages with Bower in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/bower.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bower.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
One possibility is to state the version of VS where support for Bower was dropped.

@justcla Was Bower in the VS UI up to version 15.5, then went away in 15.6?

**Comment by benoityip** [comment]
I am using VS2017 15.7.5 No Bower
