### ISSUE TITLE
id tag mismatch

### ISSUE THREAD

**Issue by danjhetherington** [aspnet/Docs#7136]
the div id in the current template is "qrCodeData" on line 25 while the script sample code is using "qrCode".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by danjhetherington** [comment]
Sorry yes agreed it does indeed appear on line 26/27 - accidental deletion when trying it out!

**Comment by Rick-Anderson** [comment]
Does that answer your question?
