### ISSUE TITLE
Please use the correct syntax highlighting!!!

### ISSUE THREAD

**Issue by Matthew-Bonner** [aspnet/Docs#7138]
Please use the correct syntax highlighting!!!

aspx-csharp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial Views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting, but the correct code language is `cshtml`.

**Comment by Matthew-Bonner** [comment]
cshtml does not work correctly with Razor, the regex registered with highlight.js for aspx-csharp works better, take a look at the source.

**Comment by Matthew-Bonner** [comment]
My bad sorry, I've opened up a new issue which I think better reports the problem I was trying to solve:
https://github.com/aspnet/Docs/issues/7172
