### ISSUE TITLE
Duplicate code block

### ISSUE THREAD

**Issue by MinhThienDX** [aspnet/Docs#7140]
The code blocks below these two line in this document are exactly the same:
The following code configures ASP.NET Core to authorize the Identity pages that require authorization:
The following the code sets the Identity cookie to use the correct Identity pages path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio#scaffold-identity-into-an-mvc-project-without-existing-authorization)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for letting us know @MinhThienDX ... I'll square that away right now.
