### ISSUE TITLE
Bug in the hub?

### ISSUE THREAD

**Issue by CodeX604** [aspnet/Docs#7143]
Compiling the stream sample gives the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'channel' does not exist in the current context	SignalRStreaming	\Hubs\StreamHub.cs	32	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a02b4e7d-971a-670b-02eb-89c5456ec8f2
* Version Independent ID: 5f2f089e-310d-83a1-9c56-9cb441b9914a
* Content: [Use streaming in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/streaming.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/streaming.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
@BrennanConroy Have you seen this error. Any advice?

**Comment by BrennanConroy** [comment]
Whoops, looks like a copy-paste error when editing the sample.

https://github.com/aspnet/Docs/blob/30a88bd0105f57ec538d140860901007d5ada7a2/aspnetcore/signalr/streaming/sample/Hubs/StreamHub.cs#L32
needs to change to 
https://github.com/aspnet/Docs/blob/30a88bd0105f57ec538d140860901007d5ada7a2/aspnetcore/signalr/streaming/sample/Hubs/StreamHub.cs#L28
needs to change to

**Comment by rachelappel** [comment]
@BrennanConroy Ok to close this?

**Comment by BrennanConroy** [comment]
Yep :+1:
