### ISSUE TITLE
The Angular experience with Visual Studio is the worst

### ISSUE THREAD

**Issue by ccottrell** [aspnet/Docs#7145]
Seriously.. There should be no reason whatsoever that I should be able to use the Angular template (used the version for .net core for 2.0 and 2.1) and both do not run without changing a thing. Absolute crap. I am stuck between two crappy tools now. VS Code works well with Angular, but not as good for the rest of the coding. Visual Studio is best for the coding, but does not work at all for Angular. I am trying to upgrade a huge app from AngularJS that was never an issue and just find the whole thing unworkable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c047bdd1-1464-4398-92c6-65ab88093525
* Version Independent ID: 1ea83a29-79de-272f-fea0-fb6b3ea1a444
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Closing, as there's no actionable feedback here for the docs. For assistance with the Angular template, please open an issue at https://github.com/aspnet/templating/issues.
