### ISSUE TITLE
Update aspnetcore/security/authentication/accconfirm for 2.1

### ISSUE THREAD

**Issue by BlackyWolf** [aspnet/Docs#7146]
I came here to see how to validate the reset password token... and I see that no where. I am referring to the userManager.VerifyUserTokenAsync() method. I don't even see a reference to ResetPasswordAsync(). Also, the scaffolding for ASP.NET 2.1 is missing the account pages normally shown with ASP.NET Core 2.0 for some reason... If y'all could put some code briefly showing the ResetPasswordAsync method in action it would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=aspnetcore2x#enable-account-confirmation-and-password-recovery)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio

We'll look at this when we refresh the doc.

**Comment by BlackyWolf** [comment]
Oh, okay. Gotcha and thanks.

**Comment by Faraz2018** [comment]
Well!
While the current document found to be outdated, with revolutionary change of 2.1, namely in respect of Identity in RCL shape, any worthy location on net for setting up Mail Settings in respect of "Account Confirmation and Password Recovery"?

**Comment by mskovacic** [comment]
Any updates regarding ResetPasswordAsync() coming soon?

**Comment by mskovacic** [comment]
Also the email confirmation step after registration and before logging in is missing. UserManager in ASP.NET Core 2.1 doesn't have appropriate overloads for handling userId as string.

**Comment by Rick-Anderson** [comment]
Are you asking for an async version?
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?tabs=visual-studio&view=aspnetcore-2.1#test-password-reset

**Comment by mskovacic** [comment]
It doesn't have to be an async version, but I suppose it will be because most of the UserManager methods are async. I'd just like to see how to verify the password reset token? I found the ConfirmEmail implementation https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity
but for ResetPassword it is missing.
