### ISSUE TITLE
Need additional namespace for Column annotation

### ISSUE THREAD

**Issue by jverbosky** [aspnet/Docs#7147]
Not sure if it's being left out intentionally or not, but the following line needs added to Movie.cs in order to resolve the "namespace cannot be found" error for the [Column...] annotation:

using System.ComponentModel.DataAnnotations.Schema;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee5529f8-7563-c18b-87f5-c9df4f1bc9f9
* Version Independent ID: 22986e34-4aa4-f470-fac4-38f6a9c498cd
* Content: [Adding Validation](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/validation.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jverbosky  thanks. We'll get this fixed in the next refresh.

**Comment by Rick-Anderson** [comment]
Fixed in unified release.
