### ISSUE TITLE
Possible typo in documentation

### ISSUE THREAD

**Issue by titonton** [aspnet/Docs#7158]
In "Create the SignalR Hub" section, you say to create the `SendMessage` method but it says `RecieveMessage` in the sample code. Is that supposed to be there?

**Comment by rachelappel** [comment]
@titonton Great question! 

In the `ChatHub` class, the method is named `SendMessage`  but it calls the client-side `ReceiveMessage`  method. It does the call through the use of `SendAsync`. Below, the line that starts with `public async` is the `SendMessage` definition. The line that starts with `await` is the call to `ReceiveMessage`.

public class ChatHub : Hub
{
    public async Task SendMessage(string user, string message)
    {
        await Clients.All.SendAsync("ReceiveMessage", user,message);
    }
}

Later, under "Create the SignalR client code", the article goes over creating the client-side method. The client-side JavaScript is named `ReceiveMessage`, defined in the `connection.on` method in the chat.js file.

connection.on("ReceiveMessage", (user, message) => {
    const msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    const encodedMsg = user + " says " + msg;
    const li = document.createElement("li");
    li.textContent = encodedMsg;
    document.getElementById("messagesList").appendChild(li);
});

Hopefully this clears things up!

**Comment by titonton** [comment]
Yea i had to read it again to realize my comment was extremely silly. Apologies for my negligence

**Comment by titonton** [comment]
Thank you for clearing it up!

**Comment by rachelappel** [comment]
@titonton Not silly at all! We appreciate your questions. They help us write docs better.
