### ISSUE TITLE
 "Working with Static Files"

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#716]
- [x] bring in PR https://github.com/aspnet/Docs/pull/1254 
- [ ] per barry - change the first example so it's not browsing on root.
- [ ] add Warning: Enabling directory browsing can leak secrets. We recommend that you **not** enable directory browsing in production.
- [ ] StaticFiles should mention that the webroot is defined in hosting configuration and link back to Hosting for details.
- [ ] StaticFiles  in wwwroot are not protected by auth
- [ ] If you want to protect static files create a directory for them
- [ ]  #453 
- [ ] review "where the static files you wish to serve are outside the webroot" - why would you do that? The code shows an absolute path - can you at least show the code to do this with a relative path?

hosting.json is no longer read by default. aspnet/Announcements#174

**Comment by Rick-Anderson** [comment]
See also #453 
Per http://docs.asp.net/en/latest/fundamentals/static-files.html#comment-2383688546 this is out of date

**Comment by danroth27** [comment]
Yup, we need to doc hosting.json, but I'm not sure the static files doc is the right spot. @Tratcher thoughts on this?

**Comment by ardalis** [comment]
Configuration makes the most sense to me, with reference from Servers.

**Comment by Tratcher** [comment]
StaticFiles should mention that the webroot is defined in hosting configuration and link back to Hosting for details.

**Comment by danroth27** [comment]
I think the webroot notion is mentioned in several places, for example:
- Static files
- [Understanding ASP.NET](https://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html)
- [Introduction to ASP.NET](https://docs.asp.net/en/latest/conceptual-overview/aspnet.html)

I think we should do a clean up to consolidate where webroot is defined and discussed and update all the relevant examples and samples. Any older samples will still have webroot defined in project.json.

**Comment by Rick-Anderson** [comment]
@blowdart  [Working with Static Files](https://docs.asp.net/en/latest/fundamentals/static-files.html) does not mention there are no auth checks for static files in the _webroot_ directory. Should we state that? Also, can we quote you and say.
To have  authorization middleware applied to static files, put them in a directory such as App_Data.

**Comment by blowdart** [comment]
That wouldn't be correct though.

"The static file module provides no authorization checks. Any files server by it, including those under www_root are publicly available. If you want to serve files based on authorization you should store them outside of www_root and any directory accessible to the static file middleware and deliver them via a controller action, returning a FileResult where authorization is applied."

FileResult is still there right?

**Comment by Rick-Anderson** [comment]
@blowdart  https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/FileResult.cs
Yes it's still there.

**Comment by blowdart** [comment]
So something like that then, except worded better :)

**Comment by Rick-Anderson** [comment]
@Tratcher - can you help me rewrite the following on middleware:

 the order in which you arrange your Use[Middleware] statements in your application’s Configure method is very important. Be sure you have a good understanding of how your application’s request pipeline will behave in various scenarios.

This is a doc on middleware and the above doesn't tell me anything. Is it something like this:

Generally, the order you register middleware is the order the middleware runs. You can't register non-authentication middleware before middleware (why - how is that prevented).

I'm guessing you need to order middleware for security + performance + interoperability.

**Comment by Rick-Anderson** [comment]
@Tratcher - never mind - it works. Bug in my code.

**Comment by Rick-Anderson** [comment]
fixed via e36c065f5f2e05f0bf2f0e5577bd67fec9cf7034
