### ISSUE TITLE
 Web API  + EF 6

### ISSUE THREAD

**Issue by Bridgeway** [aspnet/Docs#7168]
I am putting together a Web API that uses .net core 2.1 and want to use entity framework 6.
I understand that because of compatibility issues it is best to create a separate project for the EF and reference it.
I was directed here from this link:
https://docs.microsoft.com/en-us/aspnet/core/data/entity-framework-6?view=aspnetcore-2.1

I was hoping to find a simple example or walkthrough of how to add EF 6, instead I was directed to github ?

**Comment by Rick-Anderson** [comment]
@Bridgeway  this is a good tutorial for EF 6
You'll need to follow other tutorials for Web API and combine the two.
