### ISSUE TITLE
Unit Testing MemoryCache

### ISSUE THREAD

**Issue by jaikumarhm** [aspnet/Docs#7169]
I could not see good examples of unit testing services/controllers that are using memory caching mechanism, can we include some samples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jaikumarhm  That's a very specific request. If we had a sample, it wouldn't go in this doc, it would go in https://docs.microsoft.com/en-us/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.1

**Comment by StingyJack** [comment]
@jaikumarhm - Since you mention Services and Controllers, are you looking for System.Runtime.Caching.MemoryCache (the general purpose .net caching option)?
