### ISSUE TITLE
C# Code block is not loaded

### ISSUE THREAD

**Issue by DevOpsChallengeBr** [aspnet/Docs#7170]
The C# code no is loading after text “Port 0
When the port number 0 is specified, Kestrel dynamically binds to an available port. The following example shows how to determine which port Kestrel actually bound at runtime:”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@DevOpsChallengeBr  thanks for bringing this to our attention.

![image](https://user-images.githubusercontent.com/3605364/41665725-83162a3a-745d-11e8-8882-323d89d596ea.png)

**Comment by guardrex** [comment]
Thanks @DevOpsChallengeBr ... I'll get this fixed in a few hours. Thanks again for calling it out.
