### ISSUE TITLE
Is this page not browsable from the tree view?

### ISSUE THREAD

**Issue by totht91** [aspnet/Docs#7171]
I can find this page from Google but cannot from the asp.net core table of contents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **asp.net-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@totht91 If you click the **Security** > **Authorization** ToC node, you will see a link to it. However, the link is missing from the main ToC. I've submitted a PR to correct this. Thank you for reporting the problem.

**Comment by scottaddie** [comment]
@totht91 This change will go live within the next 24 hours.
