### ISSUE TITLE
Modernized

### ISSUE THREAD

**Issue by mxmissile** [aspnet/Docs#7176]
With bower dead/dying. Is this article relevant? What *is* the current MS recommended client side framework package manager flavor of the day?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90c973b-dd21-5dc6-4c70-7ddfba51271e
* Version Independent ID: b20b9d8e-e29a-44a4-18d0-e78f4e8dc51f
* Content: [Build beautiful, responsive sites with Bootstrap and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bootstrap?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/bootstrap.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bootstrap.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@mxmissile You're correct that Bower is no longer relevant. LibMan will soon replace Bower in the project templates. See https://github.com/aspnet/LibraryManager/wiki for more info. LibMan will also be documented here. The following issue tracks that work: https://github.com/aspnet/Docs/issues/7246
