### ISSUE TITLE
DotNetCli

### ISSUE THREAD

**Issue by eloekset** [aspnet/Docs#718]
All the DNVM, DNU and DNX stuff is outdated now, right? So the tutorial for ASP.NET 5 on a Mac, for instance, should be rewritten? https://github.com/aspnet/Docs/blob/master/aspnet/tutorials/your-first-mac-aspnet.rst

**Comment by davidfowl** [comment]
It'll be outdated when RC2 is released.

**Comment by scottaddie** [comment]
@davidfowl Where can I find some more info on this? Wondering whether the DN* tooling is now completely obsolete or if there are pieces of it I may still need to use.

**Comment by davidfowl** [comment]
There is no documentation on this yet. We spoke about it in the last community stand up. By the time RC2 ships there hopefully be a smooth transition over (we have to do it ourselves) to the CLI.

**Comment by rhires** [comment]
I actually watched some of that standup the other night! To re-iterate: RC1 is current, will be until February (according to the standup), all tooling/commands/etc. is good and fine until then. RC2 stuff on top will change, but under the hood it will all work roughly the same. We will see as time goes forward how this plays out in terms of what changes need to be made to get things going - such as commands on the command line, etc. I admit I don't completely understand everything that will be happening, or why - I guess I was only half-listening - but I'm sure it will come out in the wash :-)

**Comment by eloekset** [comment]
@scottaddie @rhires Here is the start of RC1, RC2, DN* and DotNetCli talk in the standup: https://youtu.be/UvkJJGVq-b0?list=PL0M0zPgJ3HSftTAAHttA3JQU4vOjXFquF&t=9m07s

**Comment by danroth27** [comment]
Yup, we need to do these updates for RC2. We'll start this as the port to .NET CLI gets further along - probably early next year.

**Comment by danroth27** [comment]
#1049
