### ISSUE TITLE
Highlights are off on Change the title and menu link in the layout file

### ISSUE THREAD

**Issue by ecaoile** [aspnet/Docs#7187]
They're above the sections you want to change...at least on Firefox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Adding a view](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ecaoile  thanks, we'll get this corrected in the next update.

**Comment by Rick-Anderson** [comment]
[Change the title and menu link in the layout file](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1#change-the-title-and-menu-link-in-the-layout-file)

![image](https://user-images.githubusercontent.com/3605364/41675170-d388e606-7476-11e8-8c7d-a2c68e99f7d5.png)
