### ISSUE TITLE
Name Discrepancy for MovieContext

### ISSUE THREAD

**Issue by trentonshell** [aspnet/Docs#7191]
Just in case anyone else runs into this issue, the documentation says to update the MovieContext.cs class, but you're actually going to want to update the RazorPagesMovieContext.cs class you created earlier in the tutorial. It took me a few minutes to discover this discrepancy but afterwards was smooth sailing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1cf23f9-09c0-0776-2924-46ea571afb4c
* Version Independent ID: f7dbe836-768d-ea56-33d0-f8e42c166afd
* Content: [Upload files to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/uploading-files?view=aspnetcore-2.1#update-the-moviecontext)
* Content Source: [aspnetcore/tutorials/razor-pages/uploading-files.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/uploading-files.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Must have been a name change at some point. I'll update it asap. Thanks for the report @trentonshell.

**Comment by guardrex** [comment]
Hum ... the plot thickens because the file seems correct wrt the sample app ...

https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie/Models/MovieContext.cs

**Comment by guardrex** [comment]
@Rick-Anderson Should I walk these steps? https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1

... to see what happens with the naming. According to our sample, the file name in the topic is correct.

**Comment by guardrex** [comment]
Well ... so much for my "easy fix" :cake: comment. I should'a known that was going to come back and bite me. 🤦‍♂️ The 2.1 sample at ...

https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/razor-pages/razor-pages-start/sample/RazorPagesMovie21

... didn't get the bits for File Uploads, so I can't just link that into the topic. I'll need to move the File Upload bits over from the prior sample to the new one before I can update the links.

I'm going to push this back a bit. @trentonshell I'll get to this asap. Thanks for alerting us to the problem.
