### ISSUE TITLE
ShareResource should be a dummy class and should be in the root namespace

### ISSUE THREAD

**Issue by szykov** [aspnet/Docs#7197]
Hello, it took me few hours to realize that if dummy class ShareResource isn't in the root namespace as startup class then localization isn't working. Please put it in docs. Data Annotation -&gt; Using one resource string for multiple classes.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#using-one-resource-string-for-multiple-classes)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **asp.net-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the comment. We'll get to this in the next doc sweep.

**Comment by Rick-Anderson** [comment]
@szykov  it's mentioned at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#resource-file-naming

**Comment by szykov** [comment]
@Rick-Anderson Sorry, my bad. You're right. By mistake, I wasn't expecting that for my dummy class same file naming rules applies. Now it makes sense. Thanks.

**Comment by OrihuelaConde** [comment]
Another way to solve this issue is:

.AddDataAnnotationsLocalization(options =>
{
    options.DataAnnotationLocalizerProvider = (type, factory) =>
    {
        var assemblyName = new AssemblyName(typeof(SharedResource).GetTypeInfo().Assembly.FullName);
        return factory.Create("SharedResource", assemblyName.Name);
    };
});

Source: https://damienbod.com/2017/11/01/shared-localization-in-asp-net-core-mvc/

**Comment by szykov** [comment]
@OrihuelaConde nice catch, thanks.
