### ISSUE TITLE
update Docs » Fundamentals » Servers 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#720]
https://docs.asp.net/en/latest/fundamentals/servers.html#comment-2382329700

**Comment by Tratcher** [comment]
Also https://github.com/aspnet/StaticFiles/issues/86#issuecomment-160302067

**Comment by qin-nz** [comment]
maybe you should also tell us how to listen multiple domains/ports in `hosting.json` configuration section `server.urls`

**Comment by Tratcher** [comment]
@qin-nz use a semi-colon separated list like `http://localhost:5000/;http://*:5001/;5002;`

**Comment by shirhatti** [comment]
Also update Servers article for HttpPlatformHandler changes
