### ISSUE TITLE
User Secrets flatten settings

### ISSUE THREAD

**Issue by MasterSkriptor** [aspnet/Docs#7201]
Please update this article to state that user secrets are flattened so that you can not nest settings such as AppSettings: { TestSetting1: "this is a test" } using the command line. What you get from the command is AppSettings:TestSetting1: "this is a test.". I saw where this was added as a bug, then closed as being intentional. The documentation should reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=windows&view=aspnetcore-2.0)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@MasterSkriptor  do you have a link to the bug?

**Comment by MasterSkriptor** [comment]
@Rick-Anderson I don't think this is a bug, necessarily. From the documentation this is its intended function. It also works the same when you call it from code. For some reason it confused me, and it turned out that I had another issue that was giving me the issues. I thought it may be a good idea to clarify that the settings were not nested. It says that they are here: [https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows](url)

Notice that they use hierarchies all through out this documentation. But if you use the dotnet user-secrets set key value command it is flattened in the secrets.json file. I'm sure, however you guys have enough to work on. So feel free to close this issue if you like.

**Comment by scottaddie** [comment]
@natemcmaster Thoughts on this?

**Comment by natemcmaster** [comment]
Flattening is intended behavior of tools, but it's okay for users to use structured objects in JSON if they want. The structure won't round trip through dotnet-user-secrets or some VS extensions, though.
