### ISSUE TITLE
Authorize attribute is not a filter

### ISSUE THREAD

**Issue by Cepheix** [aspnet/Docs#7202]
In the text there is information that authorize attribute is a mvc filter 

> Several filters (such as Authorize) are included in the framework.

This is however not true as the [authorize attribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizeattribute?view=aspnetcore-2.1) only inherits from the attribute class and implements IAuthorizeData interface

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b26c2a-d481-043c-e37b-cbe3ad427d41
* Version Independent ID: d7d85488-c055-7aea-0664-2e97bc937a04
* Content: [Overview of ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/overview.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  please review.

**Comment by HaoK** [comment]
@javiercn can you help with the proper verbiage for this?  Authorize is the attribute, that is used to create MVC authorize filters?
