### ISSUE TITLE
Consider documentation for SignalR Redis lifetime manager

### ISSUE THREAD

**Issue by nphmuller** [aspnet/Docs#7204]
I'm mainly interested in what benefits this adds and how to configure it. App (aspnetcore) and server (Redis) configuration.

Also: Does ARR Affinity still have to be turned on (see ` Publish to Azure`) when using the Redis extension?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22325a88-5e1d-7b54-87b7-ea331a6c73b6
* Version Independent ID: b92a4bf5-f7c9-50b9-d7d7-46ebcf7387b0
* Content: [ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/index.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
@anurse Your thoughts?

**Comment by nphmuller** [comment]
In the meantime I've learned that you also have to disable negotiation for now if you don't want sticky sessions (ARR Affinity). Configuring Redis is not enough.

Would still be nice to have this documented. :)

**Comment by anurse** [comment]
We have some of this documented now in the [Configuration](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md#configure-additional-options) doc that is going to be published to docs.microsoft.com shortly.

**Comment by anurse** [comment]
Filed #7814 for tracking scale-out docs (including Redis config)
