### ISSUE TITLE
syntax highlighting  missing string interpolation

### ISSUE THREAD

**Issue by mozts2005** [aspnet/Docs#7207]
the code samples on this are hard to read given the fact that string interpolation is used but not being highlighted as it would be in an editor.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Kind'a falls into the https://github.com/aspnet/Docs/issues/7172 bucket.

cc/ @vicancy @superyyrrzz 

@Rick-Anderson I'm going to take this one because it possibly falls into updates on https://github.com/aspnet/Docs/issues/7102; but unless DocFX takes steps, I don't think it will be actionable for us.

**Comment by Thehardtimesofbeans** [comment]
it's useLess when  I used  config.GetSection("LogConfig").Get<LogConfig>().please help.thanks

**Comment by Thehardtimesofbeans** [comment]
I see it has  to be used config.GetSection("LogConfig:StoreName").
appsettings.json file:
 {"LogConfig": {
    "ProjectName": "com-ny-erp",
    "StoreName": "default",
    "DefaultOut": "Local"
  }
}

**Comment by guardrex** [comment]
Let's track this over on the DocFX issue that I just opened. We have no control over this here.
