### ISSUE TITLE
Expand thread safety section with respect to singleton factory

### ISSUE THREAD

**Issue by atifaziz** [aspnet/Docs#7208]
The thread-safety section talks about services:

> ### Thread safety
>
> Singleton services need to be thread safe. If a singleton service has a dependency on a transient service, the transient service may also need to be thread safe depending how it's used by the singleton.

However, it would be help to add a word or two about the thread-safety of a _singleton factory_ when using something like [`AddSingleton<TService>(IServiceCollection, Func<IServiceProvider,TService>)`][AddSingleton], as in:

```c#
services.AddSingleton<IFoo>(sp =>
{
    // initialization code...
    return new Foo(/* ... */);
});
```

One would imagine that the factory will be called lazily, when the service is requested for the first time. What happens, though, if multiple threads request the singleton service simultaneously that in turn incurs its initialization?

1. Does the initialization code run once and run by one thread alone, like a static type constructor?
2. Does the factory need to be _idempotent_ and so may be called more than once, by more than one thread? The assumption here is that one of those will win (rest discarded) but will effectively return the same result that's used for all subsequent requests.

I'm guessing it's the first case but it would help to clarify in that section. It avoids:

- people being paranoid and adding locks in their factory code.
- asking Luke to [use The Source](http://wiki.c2.com/?UseTheSourceLuke). 😉 

[AddSingleton]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addsingleton?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_ServiceCollectionServiceExtensions_AddSingleton__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Func_System_IServiceProvider___0__

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#recommendations)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @atifaziz ... I'm working on this topic **_TODAY!_** 😄 

Samples are updated, and I'm getting into the topic content now. I'll get back to you soon.

**Comment by guardrex** [comment]
... and the Force says to ping @davidfowl ...

@davidfowl, I can convert your answers to questions 1 & 2 for that section of the topic.

**Comment by atifaziz** [comment]
> btw ... My name is "Luke," so rest assured I'll use the Force on this...and the Force says to ping @davidfowl ...

[![](https://media.giphy.com/media/PpvEFs2OsDOXC/giphy.gif)](https://giphy.com/gifs/star-wars-yoda-PpvEFs2OsDOXC)

Thanks for picking this up so quickly! 💯

**Comment by davidfowl** [comment]
Yes initialization code runs once and everything waits on it.

**Comment by atifaziz** [comment]
@davidfowl Thanks for the clarification.

Here's a proposal of the section could be expanded:

> ### Thread safety
>
> Singleton services need to be thread safe. If a singleton service has a dependency on a transient service, the transient service may also need to be thread safe depending how it's used by the singleton.
>
> <ins>The factory method of single service, such as the second argument to [`AddSingleton<TService>(IServiceCollection, Func<IServiceProvider,TService>)`][AddSingleton], does not need to be thread-safe. Like a type (`static`) constructor, it's guaranteed to be called once and by one thread alone.</ins>

[AddSingleton]: https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectionserviceextensions.addsingleton?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_ServiceCollectionServiceExtensions_AddSingleton__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_Func_System_IServiceProvider___0__

**Comment by guardrex** [comment]
Thanks ... I'll get this on the PR that I'm putting up today.
