### ISSUE TITLE
Cloud authentication with Azure Active Directory B2C in ASP.NET Core work anymore in .Net Core 2.1

### ISSUE THREAD

**Issue by kennzhang** [aspnet/Docs#7209]
Seems like it's broken.. the URL is wrong 
InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://login.microsoftonline.com/vidiwaveusers.onmicrosoft.com/B2C_1_vidicloudAddPolicy /v2.0/.well-known/openid-configuration'.

Should be 
https://login.microsoftonline.com/vidiwaveusers.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_vidicloudAddPolicy

Can't seems to know how to change the URL..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper

**Comment by CamSoper** [comment]
@Rick-Anderson I was unable to get to this this sprint. Please add to Sprint 139 and I'll get it when I get back from vacation. @scottaddie

**Comment by CamSoper** [comment]
@kennzhang - I just ran through it end-to-end with .NET Core SDK 2.1.401 and VS 2017 15.8.2.  Seems fine other than some minor text and image updates.
