### ISSUE TITLE
Key name is not correct

### ISSUE THREAD

**Issue by rockfordlhotka** [aspnet/Docs#7214]
In the section discussing how to retrieve a setting, the doc shows the key as "MoviesApiKey", but a colon is required. It needs to be "Movies:ApiKey".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c99993c-c983-6fda-6c3a-ce4ec8c1d5db
* Version Independent ID: ba688ac2-e90e-fce5-f60d-40c2553c3efd
* Content: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.1&tabs=windows)
* Content Source: [aspnetcore/security/app-secrets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/app-secrets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Thank you for reporting this, Rocky! I'm looking at it right now.
