### ISSUE TITLE
Redis missing prereq

### ISSUE THREAD

**Issue by sammarcow** [aspnet/Docs#7220]
`install-package Microsoft.Extensions.Caching.Redis.Core` from VSStudio Package Manager Console.  This is required to configure Services in startup.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Work with a distributed cache in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **asp.net-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by toddheckel** [comment]
This is the wrong package. See https://github.com/aspnet/Caching/issues/348
