### ISSUE TITLE
Don't forget the Dockerfile !

### ISSUE THREAD

**Issue by Necriis** [aspnet/Docs#7227]
If you package your ASP.Net Core project in a Docker container, don't forget to update the Dockerfile, because the error message is not obvious !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher should I add that?

**Comment by Tratcher** [comment]
What was the error message?

@natemcmaster ?

**Comment by natemcmaster** [comment]
See https://github.com/aspnet/aspnet-docker/blob/master/2.1/README.md for details on how to migrate your dockerfile.

**Comment by Necriis** [comment]
Here is the error message:
```It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '2.1.1' was not found.
- Check application dependencies and target a framework version installed at:
/
- Alternatively, install the framework version '2.1.1'.
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.

**Comment by scottaddie** [comment]
@Rick-Anderson I'll take this one, since I'm updating other Docker docs for 2.1.
