### ISSUE TITLE
DotNetCliToolReference 

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/Docs#7228]
According to messages from SDK 2.1 tools, using the element DotNetCliToolReference (e.g. for reference to Microsoft.EntityFrameworkCore.Tools.DotNet) is deprecated, because it is included in .NET Core SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by gjaryczewski** [comment]
To complement: this tutorial ("Razor Pages web app with VS Code") has .NET Core 2.1 SDK or later as a prerequisite. So using older techniques is misleading a bit.

**Comment by Rick-Anderson** [comment]
Dup of #7233

**Comment by gjaryczewski** [comment]
This is not a duplicate #7233, again, because it is about another behavior.
