### ISSUE TITLE
The ID field is NOT required

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/Docs#7229]
It is not true, that "The ID field is required by the database for the primary key". In context of Entity Framework, you can use Data Annotation or Fluent API to use other name for the primary key. And in wide context of database design it is generally false also. although MongoDb reserves name "_id" for the primary key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@gjaryczewski  true but it's required by the app. I added that sentence when I got alot of questions what's the ID for. I
