### ISSUE TITLE
2.1 - Add the seed initializer

### ISSUE THREAD

**Issue by MNashSparta** [aspnet/Docs#7230]
Using the code in the section "Add the seed initializer" while using dotnet --version 2.1.4 works until later in the tutorial in "Add a new field". At this point, the command "dotnet ef database drop" gives an error of "Unable to create an object of the type 'MvcMovieContext'. Add an implementation of 'IDesignTimeDbContextFactory&lt;MvcMovieContext&gt;' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time." However, when using the code section given for the 1.0 - 2.0 allows the database commands to work again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f5395e3-ffc8-99d9-5546-cf155f80c739
* Version Independent ID: 9b17fa82-ec20-8a47-415a-d33eebfff855
* Content: [Working with SQLite and ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/working-with-sql?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/first-mvc-app-mac/working-with-sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-mac/working-with-sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MNashSparta  I hope to get this updated soon.
