### ISSUE TITLE
Microsoft.VisualStudio.Web.CodeGeneration.Design - which version?

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/Docs#7232]
When using SDK 2.1.0, I received an error message about not available local source of packages. (My messages are in Polish, I could not find how it was translated from English). I resolved the case by adding version, so "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design" becomes "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --version 2.1.0".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #7233

**Comment by gjaryczewski** [comment]
Maybe I am wrong, but IMHO this is not a duplicate: #7233 is about Microsoft.VisualStudio.Web.CodeGeneration.Tools, not about Microsoft.VisualStudio.Web.CodeGeneration.Design.

**Comment by daveabrock** [comment]
This is resolved with an upcoming PR of this document.
