### ISSUE TITLE
dotnet-aspnet-codegenerator unavailable

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/Docs#7233]
A similar issue was closed (#6999). I could not execute dotnet-aspnet-codegenerator with SDK 2.1 until I do two things: 1) run: "dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Tools --version=2.0.2, 2) add in .csproj: "&lt;ItemGroup&gt;&lt;DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" /&gt;&lt;/ItemGroup&gt;". Up to this day I cannot use install the NuGet package dotnet-aspnet-codegenerator, because of configuration errors - maybe in the next version all these behaviors will be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This needs an update for 2.1 -
The following instruction are for the updated https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro#scaffold-the-student-model (in PR now)
``
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --version 2.1.0
dotnet aspnet-codegenerator razorpage -m Student -dc ContosoUniversity.Models.SchoolContext -udl -outDir Pages\Students --referenceScriptLibraries
