### ISSUE TITLE
If you follow these instructions you'll get an error about DOCKER_REGISTRY not being set that won't allow you to continue

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/Docs#7234]
The documentation should include how to set this and what it does. I.e. if you're using Azure it should either link to instructions to set it or tell you exactly how to do it. Same with Docker.io.  

I found other documentation that you need to set an env in the dockerfile. That doesn't work, so I'm blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by mosharafMS** [comment]
I had the same error but it's not a blocking error, copy the detailed error message outside the grid in visual studio and read it, most probably the blocking error was because permissions denied

**Comment by JohnGalt1717** [comment]
Sadly this is the only error you'll ever get from docker in the errors list.  All other errors are ignored after this one.  You have to go digging through the log. Hence this is a bug.

**Comment by YeyoCoder** [comment]
**I having the same problem**. Also run VS as administrator as David Silwal suggest and still not working https://stackoverflow.com/questions/51082120/the-docker-registry-variable-is-not-set-defaulting-to-a-blank-string.

**Comment by YeyoCoder** [comment]
Check the answer of https://github.com/t-o-o-m. Disabling Windows fast startup work for me! https://github.com/docker/for-win/issues/573

**Comment by scottaddie** [comment]
The message `The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.` is a warning. Because the message is confusing and somewhat bogus, engineering has suppressed the warning as of VS 2017 15.8 Preview 5. The user will see the actual error instead.

This problem can be tracked in the product's repo at https://github.com/Microsoft/DockerTools/issues/130.

**Comment by JohnGalt1717** [comment]
Note that that's great, however the error list only ever shows one docker error not many which is really what this is about.  VS.net needs to be fixed so that it returns ALL docker errors except this one.

**Comment by scottaddie** [comment]
@JohnGalt1717 My understanding is that's the plan. Apologies if my response wasn't clear.

**Comment by JohnGalt1717** [comment]
Excellent! Thanks!
