### ISSUE TITLE
Nuget package reference conflict

### ISSUE THREAD

**Issue by grahambunce** [aspnet/Docs#7235]
If you create a clean .net core 2.1 web app to host Signal-R and then use the latest package (1.0.1) of Microsoft.AspNetCore.SignalR then you get a package conflict. Only 1.0.0 version of the package can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@grahambunce  Can't you use the version-less  [Microsoft.AspNetCore.App metapackage](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1)

**Comment by grahambunce** [comment]
@Rick-Anderson Thanks for this but I don't know - I was just following the usual steps when creating a clean project from Visual Studio - I didn't even know this package exists - but either way I wouldn't have expected a package conflict out of the box.

**Comment by rachelappel** [comment]
@grahambunce You should do a File-> New Project and NOT add in any more NuGet packages. Doing t with the latest should also use the version-less reference as well. Using other Nuget packages will result in an error, and no other NuGet packages are in the steps.

The doc specifically says "Visual Studio includes the Microsoft.AspNetCore.SignalR package containing its server libraries as part of its ASP.NET Core Web Application template. However, the JavaScript client library for SignalR must be installed using npm.".
