### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by erick2red** [aspnet/Docs#7238]
Please, add a Next button to this, so one can navigate the documentation without thinking where I left.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f27118-7ff2-709d-b14f-6b9c1da648cc
* Version Independent ID: ad44e4f1-0173-574d-ebf9-83534aab2f9a
* Content: [Authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@erick2red  we only use `Next` when a tutorial has to be followed in order. That wouldn't apply here.

**Comment by Rick-Anderson** [comment]
That's not the next article. There is no order. They are loosely related. You are looking at  [Authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/?view=aspnetcore-2.1) - right?

**Comment by Rick-Anderson** [comment]
@erick2red  adding `Next` would imply an order, something we don't want to do.
