### ISSUE TITLE
Content Feedback

### ISSUE THREAD

**Issue by jerrypalladino** [aspnet/Docs#7240]
Just some suggestions - I noticed that some of the directions were in the Visual Studio tabs but not in the Visual Studio Code tabs:  when adding the ChatHub class, nowhere in the VS Code tab does it mention the name of the class.  Also, it would be helpful to have the full code snippet that appears in the VS tab be in the VS Code tab as well.  Other than that, its a great tutorial! Thanks Rachel!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
Thanks @jerrypalladino! I'll change the doc to add in more details on the Code tabs.

**Comment by bayangan** [comment]
Link to sample code is broken
