### ISSUE TITLE
Create docs for LibMan

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#7246]
LibMan (Library Manager) will ship with 15.8 Preview 3. We should have some docs out before that release.

See the [GitHub Wiki](https://github.com/aspnet/LibraryManager/wiki) for docs that already exist.

Also update client-side docs referencing Bower, such as https://docs.microsoft.com/aspnet/core/client-side/bootstrap.

- [x] LibMan overview / landing page (https://github.com/aspnet/Docs/pull/8008)
- [x] LibMan in Visual Studio (https://github.com/aspnet/Docs/pull/8008)
- [ ] LibMan CLI (https://github.com/aspnet/Docs/pull/8260)

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/6008, but you can close that one. I didn't assign it.

**Comment by guardrex** [comment]
These may or may not be helpful. It was all there was at the time:

* aspnet/templating#471
* https://blogs.msdn.microsoft.com/webdev/2018/04/17/library-manager-client-side-content-manager-for-web-apps/
* https://youtu.be/k0Xy-5zE9to?t=25m8s
