### ISSUE TITLE
Update DI article to reflect RC1 change

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#725]
ApplicationServices has been removed per https://github.com/aspnet/Announcements/issues/118.

Update dependency-injection section on ApplicationServices and RequestServices to reflect this.

**Comment by Rick-Anderson** [comment]
Also fix the following opening:
If desired, developers can replace the built-in services container with a custom or third party implementation.
with something like:
The default provided in ASP.NET 5 provides a minimal feature set and is not intended to replace other containers.

**Comment by ardalis** [comment]
ApplicationServices is still in RC1; revisit this in RC2 timeframe.
