### ISSUE TITLE
Redundant usings?

### ISSUE THREAD

**Issue by BrittanyDilts** [aspnet/Docs#7252]
Is there a reason the generated files reference both `using RazorPagesMovie.Models;` and `private readonly RazorPagesMovie.Models.RazorPagesMovieContext _context;`? 

Wouldn't it only need `private readonly RazorPagesMovieContext _context;`? 

It doesn't look like it's confusing Visual Studio, so it may not be important for anything more than showing multiple ways of utilizing namespaces, I guess...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The scaffolder generates the Fully Qualified Name (FQN) even though there is a using. You are correct.

@seancpeters  - should the next release of the scaffolder not use the FQN?

**Comment by seancpeters** [comment]
The FQN seems unnecessary. @danroth27 @javiercn - this is regarding content details of scaffolded pages, thoughts?

**Comment by Rick-Anderson** [comment]
@javiercn  and while you're fixing that, fix the incorrect FQN it generates. It uses `Model` when it's in the `Data` folder, not the `Model` folder. So the namespace in the DC files should be `RazorPagesMovie.Data.RazorPagesMovieContext` not `RazorPagesMovie.Models.RazorPagesMovieContext`
