### ISSUE TITLE
Clarification of instructions for Add the seed initializer

### ISSUE THREAD

**Issue by Stumpy842** [aspnet/Docs#7254]
On the page "Work with SQL Server LocalDB in ASP.NET Core" in the section "Add the seed initializer" it should state to replace the contents of Program.cs with the following code. This might be obvious to more experienced individuals but not so to beginners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a4022c-7ef1-3c30-4f9d-cf521a57a44a
* Version Independent ID: a0b5e15c-d747-8710-95fb-a55c09861a1e
* Content: [Work with SQL Server LocalDB in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/working-with-sql?view=aspnetcore-2.1&tabs=aspnetcore2x#add-the-seed-initializer)
* Content Source: [aspnetcore/tutorials/first-mvc-app/working-with-sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/working-with-sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Stumpy842  agreed.

**Comment by brainoverflow98** [comment]
This part was causing errors for me: saying that Movie object already exists. When I deleted the dbo.Movie object problem was fixed. Later on I realized I don't need that part of the code since it trying to migrate the database again:

var context = services.GetRequiredService<MvcMovieContext>();
context.Database.Migrate();

just delete this 2 lines of code and it works just fine.

**Comment by pfmvidal** [comment]
In Razor Pages tutorial, that was pointed out, exactly as you said it. My chosen workaround was also to delete the dbo.Movie table (while I was following the Razor Pages tutorial). Good catch, by the way. Kudos!

**Comment by pfmvidal** [comment]
I forgot to mention, when encountering the same error, the other fix is to stop IIS Express, so this will 'force' the recreation of the table. I believe it is worth mentioning this, too. Just in case somebody does not like the idea of deleting the dbo.Movie table. I got this to work, without deleting the table, but stopping IIS Express.
