### ISSUE TITLE
ViewData attribute Error

### ISSUE THREAD

**Issue by xiemosi** [aspnet/Docs#7257]
An unhandled exception occurred while using @Model.Title in about view:
RuntimeBinderException: Cannot perform runtime binding on a null reference 
CallSite.Target(Closure , CallSite , object )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e47828-6da8-2323-053f-dcbf7475b1b6
* Version Independent ID: 62d4c2be-4233-64e1-2a3d-8a5e98d9d941
* Content: [Views in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.1#passing-data-to-views)
* Content Source: [aspnetcore/mvc/views/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/overview.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@xiemosi That's a pretty good error message. Can you figure out why the title is null?

**Comment by xiemosi** [comment]
I don't know why the title is null.
I just can leave some error information.
![viewdataattributeerror](https://user-images.githubusercontent.com/15097553/41819293-8ffc8b36-77f0-11e8-8761-1bce8707444c.png)

**Comment by Rick-Anderson** [comment]
Where is it set?

```@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>
```

**Comment by xiemosi** [comment]
I set it in HomeCotroller.cs
```
        [ViewData]
        public string Title { get; set; }
        public IActionResult About()
        {
            Title = "About Us";
            ViewData["Message"] = "Your application description page.";

            return View();
        }
```

**Comment by Rick-Anderson** [comment]
Run `dotnet new mvc` and test it out. Compare to the code you're having a problem with.
