### ISSUE TITLE
ResponseCompression - Troubleshooting Tips

### ISSUE THREAD

**Issue by alohaninja** [aspnet/Docs#7258]
You should also note that `app.UseResponseCompression();` needs to be before ` app.UseMvc()` or compression will not happen during `Configure()`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response Compression Middleware for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by alohaninja** [comment]
`app.UseMvc();` should be added under the `Configuration` heading to make this clearer

**Comment by guardrex** [comment]
@alohaninja Thanks for commenting. This is somewhat the result of the sample app not being Razor Pages but actually being a middleware-based demonstration app.

I like what you're suggesting. If I refactor this sample to Razor Pages, then it will display `UseMvc` after `UseResponseCompression`. We can still keep some or all of the middleware demonstration pieces. We'll just have pages in it as well.

Let's use this issue to track the work.
