### ISSUE TITLE
Method-based URL rewriting 

### ISSUE THREAD

**Issue by raberana** [aspnet/Docs#7260]
Any examples of URL rewriting using the method-based approach? I'm interested on how it should be properly done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f7c61-a9fa-bd34-001d-217477874bb6
* Version Independent ID: 9c48da92-af90-3fc1-fde0-c3f74fa88510
* Content: [URL Rewriting Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1&tabs=aspnetcore2x#additional-resources)
* Content Source: [aspnetcore/fundamentals/url-rewriting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/url-rewriting.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Just the one shown in the topic. Are you looking for additional examples?

https://docs.microsoft.com/aspnet/core/fundamentals/url-rewriting#method-based-rule

**Comment by raberana** [comment]
As I understand it, the example shows a redirection. I am looking for a URL rewrite example since I am not sure how to process the response, or how to proceed with the rewrite.

**Comment by guardrex** [comment]
In that case, you'll want to change the `request.Path` before you process the request (before you call `app.UseMvc` or `app.UseStaticFiles`). I'll hack up a quick example for you ...

To rewrite requests for all text files (`request.Path` ends with `.txt`) to serve back a *TextFile.txt* in the `wwwroot` folder with Static File Middleware, you would do the following ...

1. Put a *TextFile.txt* into the *wwwroot* folder.

```txt
This is a text file.
```

2. Create a rewrite method for the rewrite. Note that all you need to do in processing your request is change the `request.Path` ...

```csharp
public static void RewriteTXTRequests(RewriteContext context)
{
    var request = context.HttpContext.Request;

    if (request.Path.Value.EndsWith(".txt", StringComparison.OrdinalIgnoreCase))
    {
        request.Path = "/TextFile.txt";
    }
}
```

3. Add the rewrite method to the `RewriteOptions` and call `UseRewriter` before calling `UseStaticFiles` ...

```chsharp
public void Configure(IApplicationBuilder app)
{
    var options = new RewriteOptions()
        .Add(MethodRules.RewriteTXTRequests);

    app.UseRewriter(options);

    app.UseStaticFiles();
}
```

Make a request for some text file ... `http://localhost:5000/give-me-a-text-file.txt`.

The rule will process, the `request.Path` is changed, and Static File Middleware will honor the new `request.Path` and return the *TextFile.txt* file.

If you check the request-response in Postman or Fiddler, you'll see that no redirect took place.

Side Note: I think an example like this should be added to the topic and sample app. Let's leave this issue open to track the work. I'll get to it within a few weeks (*or a month!* 🏃😅).

**Comment by raberana** [comment]
Wow! Thanks @guardrex! I just have some concerns since what I am rewriting are API requests (from a gateway to a microservice) and I thought maybe it it would involve more modifications but if it's only changing the `request.Path`, then I'm already happy! 😄

**Comment by guardrex** [comment]
Sure ... np. In addition to the `request.Path`, there's also a `request.QueryString` that you should be able to read and write in case you need to make changes to a query string.

The nice thing about this method-based approach for a rewrite is that you can put some super complicated logic in there if need to (much more complex than just a simple RegEx expression) but at the end all you're really doing is setting a new `request.Path` for RazorPages/MVC or Static File Middleware. The downstream middleware is just going to think that's the path it should be processing.

I'm glad you brought this up. It will make a nice edition to the topic.

........ when I get to it in the year 2027. 🏃🏃🏃🏃🏃🏃🏃😅
