### ISSUE TITLE
DeleteConfirmed could be more secure

### ISSUE THREAD

**Issue by JohnCOsborne** [aspnet/Docs#7263]
I'm not sure how secure the examples should be but technically a user could use developer tools and modify the hidden value of the Id, then submit. If error pages are turned on then no stack trace... if not then stack trace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97234f18-4009-0ebf-a379-9b63125529cd
* Version Independent ID: 1bf4792d-dab4-e03d-2021-3dcdcaff6a0f
* Content: [Examine the Details and Delete methods of an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/details?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/details.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/details.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The id is not hidden, it's a route value. All you need to do is change the URL. A real app would verify the used owned the data. See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1

**Comment by JohnCOsborne** [comment]
@Rick-Anderson I was referring to the form in Delete.cshtml

`<form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>`

**Comment by Rick-Anderson** [comment]
@JohnCOsborne  comment out the hidden markup. That code is not used. Hover over a delete link. It's passed explicitly. 

It wouldn't matter if it was hidden anyway, it's the responsibility of the app to verify the data. See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1

**Comment by JohnCOsborne** [comment]
@Rick-Anderson hmm, well that's odd. It was obviously being used because if I modified the hidden ID via developer tools and that is the ID that was submitted. I comment it out, as you said, and it is retrieved via the form action attribute(Seems model binding chooses form elements over the action attribute). The first point I was trying to make is what you're saying: _The app should verify the data_ and my second point is that it isn't. I just wanted to point it out. I'm not sure how secure MSFT wants their examples to be... Please see the images below to see what i was doing and see below the images for my other question:


![image](https://user-images.githubusercontent.com/14142986/41823994-e5f4dc7e-77d6-11e8-8077-5b981c7d032f.png)
then
![image](https://user-images.githubusercontent.com/14142986/41824003-ffd7dfb0-77d6-11e8-99f0-5ff745792542.png)
then
![image](https://user-images.githubusercontent.com/14142986/41824010-20e44798-77d7-11e8-80ea-f3ce913fe9f4.png)
I change the ID to some random number
![image](https://user-images.githubusercontent.com/14142986/41824053-ec49b382-77d7-11e8-8d07-affe404132e2.png)
 then click the delete button
![image](https://user-images.githubusercontent.com/14142986/41824032-918358f4-77d7-11e8-8dc6-74b60c9de1f2.png)
then
![image](https://user-images.githubusercontent.com/14142986/41824041-b38138c2-77d7-11e8-97c4-3ed0044e0fe7.png)

It is **clearly** used. _So what is the point of having duplicate code?_

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authorization/secure-data?view=aspnetcore-2.1

**Comment by JohnCOsborne** [comment]
If I recall correctly, that code was made via scaffolding. Which means the scaffolding is creating duplicate/unused code. A small little issue, but I think an issue none-the-less. @guardrex Am I seeing this right, is the scaffolding creating duplicate/unused code? TL;DR - The Delete View renders both an action="Movies/Delete/7" in the form element and an hidden input with name="ID". The hidden input seems to have higher priority when being bound. Why have two IDs being passed when you only need one?

**Comment by Rick-Anderson** [comment]
The scaffolder is creating correct code. I was pointing out that even if you removed hidden the latent value will carry the ID. The question you raised on security is answered in the links I sent you.
