### ISSUE TITLE
Where is ASP.NET Core 2.1

### ISSUE THREAD

**Issue by jgpaterson** [aspnet/Docs#7267]
I have just updated VS2017 to 15.7.4 and I cannot see ASP.NET Core 2.1 as an option. Only 2.0 appears in the drop down. 
I also can't see the tickbox to "configure for https" as shown in the second screenshot in this tutorial.
Did I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by jgpaterson** [comment]
My bad, I re-looked at the pre-reqs and realised that 2.1 was a stand alone installer and not bundled into a workload through the VS installer. Am all set now

**Comment by kztd** [comment]
y, me too.  You'd  think you could get it from the installation program, but I had to go here https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md to find it.
