### ISSUE TITLE
RestartSec=10 comment returns a parsing error when starting the service

### ISSUE THREAD

**Issue by FrancescoBonizzi** [aspnet/Docs#7278]
With `Ubuntu 18.04 LTS`, when you write the comment on `RestartSec` inline and then you start the service, in the status you can see a parsing error: `Failed to parse sec value, ignoring: 10`.

If you remove the comment, `# Restart service after 10 seconds if dotnet service crashes`, it works correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti
