### ISSUE TITLE
Possible Typo: "If you apply combine ..."

### ISSUE THREAD

**Issue by jwatkin** [aspnet/Docs#7289]
In the "Warning" paragraph, the phrase "If you apply combine ..." should probably be "If you combine ...".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @jwatkin ... I'll patch that up right now.
