### ISSUE TITLE
Update introduction section which still says "SignalR Core isn't released"

### ISSUE THREAD

**Issue by d-dizhevsky** [aspnet/Docs#7293]
The info here: 'https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1#when-to-use-websockets' is outdated since SignalR Core released 'https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-2.1'.

IMO it should clearly say that SignalR Core has been already released with ASP.NET Core 2.1.0 with these links provided:
https://blogs.msdn.microsoft.com/webdev/2018/05/30/asp-net-core-2-1-0-now-available/
https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1#when-to-use-websockets)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by rachelappel** [comment]
Good catch @d-dizhevsky!
