### ISSUE TITLE
Configuring the firewall - installing ufw disables all ports - unable to ssh

### ISSUE THREAD

**Issue by aseemgautam** [aspnet/Docs#7294]
This just creates so much problem as new users will just install ufw and now its impossible to access the machine. Port 22 is permanently disabled and ssh is not possible at all. 

Even adding a firewall rule on google console does not help at all.

I have no choice but to delete the VM and install it again. UFW now rejects all traffic on ports except 80 and 443.

Documentation should add some warning sign or update the docs on what all can go wrong when ports are closed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @aseemgautam.

@shirhatti, can you comment?

**Comment by hrnsky** [comment]
DO NOT configure firewall if you don't know how to do. Doesn't matter whether if you configure ufw or not, just run your project for test purposes. If you want to configure ufw, check these pages before doing something.

https://help.ubuntu.com/community/UFW 
http://manpages.ubuntu.com/manpages/bionic/man8/ufw.8.html

**Comment by shirhatti** [comment]
They're not wrong. Configuring `ufw` will block everything else including access to ssh.
It's a really a slippery slope to go down. Everything in the securing your app section could come to bite you. For e.g., enabling HSTS which we do in the nginx configuration could you put you in a irreparable state.

Maybe considering adding a giant warning about everything in the securing your app section?
