### ISSUE TITLE
Asp.net Core MVC with Universal Rendering engine

### ISSUE THREAD

**Issue by vijaytanwar** [aspnet/Docs#7296]
We can create single page application using Asp.net core and Angular or React. But we don't have something like "zeit/next" for universal rendering.  If we can have universal rendering in Asp.net core then it will be the coolest framework for developing web application as it will have power of c# and SEO enabled SPAs, fastest initial rendering, state management using single source of truth, same rendering region on client and server and many more.

Regards,
vijaytamar@live.in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @vijaytanwar ... thanks for the feedback. Note that this is the documentation repo and most issues opened here are only seen by a handful of documentation authors. I recommend you leave feedback at UserVoice or on the aspnet/Home issues.

* https://aspnet.uservoice.com/forums/41199-general-asp-net
* https://github.com/aspnet/Home/issues
