### ISSUE TITLE
Configure Authentication with ASP.NET Identity

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#73]
ASP.NET 5->Security->Configure Authentication with ASP.NET Identity
- Account confirmation
- Password reset

**Comment by rustd** [comment]
We can use the same outline as this article.
http://www.asp.net/mvc/overview/security/create-an-aspnet-mvc-5-web-app-with-email-confirmation-and-password-reset
Following is the outline
* Create an ASP.NET 5 Website 
* Uncomment code in template to enable Email confirmation and Password recovery
* Hook up SendGrid. Use the User Secrets feature to add the keys for SendGrid
* Require email confirmation before log in
* Password recovery/reset
* Publish the app to Azure Web App
* Set the keys for SendGrid in the AppSettings in the portal

**Comment by danroth27** [comment]
@rustd Can this issue now be closed?

**Comment by rustd** [comment]
Yes
