### ISSUE TITLE
Sample Download Is Unwieldy

### ISSUE THREAD

**Issue by michaelbunney** [aspnet/Docs#7302]
The only way to download this sample from GitHub as a .zip is to download the whole Docs repository, which is nearly a gigabyte.  Even just extracting it takes a long time, and then I have to find the sample within it.

Please provide a link to download just the sample for the current topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @michaelbunney ... Thanks for commenting. A solution is in the works. See: https://github.com/aspnet/Docs/issues/6991#issuecomment-398104010
