### ISSUE TITLE
Mac OS .NET CLI: not contains Identity files

### ISSUE THREAD

**Issue by agiletuan** [aspnet/Docs#7303]
Steps to reproduce
run the following command at the command line:

dotnet new mvc --auth Individual

Expected behavior
Project will contains Asp.Net Identity module.

File: Controllers/AccountController.cs
File: Controllers/ManageController.cs
File: Models/ApplicationUser.cs
Folders: AccountViewModels (and files), ManageViewModels (and files)
Actual behavior
Project not contains Asp.Net Identity module.

Environment data
dotnet --info output:

.NET Core SDK (reflecting any global.json):
Version: 2.1.301
Commit: 5952487

Runtime Environment:
OS Name: Mac OS X
OS Version: 10.13
OS Platform: Darwin
RID: osx.10.13-x64
Base Path: /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
Version: 2.1.1
Commit: 6985b9f684

.NET Core SDKs installed:
2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

https://github.com/dotnet/cli/issues/9561

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=netcore-cli%2Caspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It's there, see https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.1?view=aspnetcore-2.1 and https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio

**Comment by agiletuan** [comment]
@Rick-Anderson thank you so much! I see: must scaffold after create new project!

**Comment by Rick-Anderson** [comment]
Only if you want to generate the Identity code. You don't need to scaffold.  Run the app you created and register a user. It's all there in a RCL.

**Comment by agiletuan** [comment]
Run CLI on windows always working.
