### ISSUE TITLE
/movies doesn't load.  

### ISSUE THREAD

**Issue by rtrunkhill** [aspnet/Docs#7305]
/movies doesn't load.  No SQL error when I run `Update-Database` I get ```      No migrations were applied. The database is already up to date. No migrations were applied. The database is already up to date. Done.```  but  `http://localhost:port/movies` doesn't load.  the root page loads and works fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rtrunkhill** [comment]
I've redone the steps. Shut down VS and restarted it.  Checked all my files and migrations.  not sure how to continue

**Comment by Rick-Anderson** [comment]
@rtrunkhill  try downloading the completed app and running it. That should help you find the mistake you made.

**Comment by shlomitubul** [comment]
A.Make sure the dbset is define and initial properly
B.if you only have one or two migrations try to delete him (include the snapshot) then create and update again.

**Comment by rtrunkhill** [comment]
Thank, Still no idea what went wrong.  I just deleted the project and
started all over.  works fine now

**Comment by McKlatch** [comment]
This should not be marked as "closed".
I'm having the same problem, and the solution is not here.

**Comment by Rick-Anderson** [comment]
There are lots of ways to make mistakes and have that problem. We have lots of customers confirming that the code works.

**Comment by jasonwongys** [comment]
i have found the solution while scaffolding the project, the scaffolding was unable to find the Movies folder. Change it to below. Use backslash instead of forward slash. Before excuting the below command, you may want to create a Movies folder first inside your Pages folder. I am using VS code.

dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries

**Comment by Maracaipe611** [comment]
> i have found the solution while scaffolding the project, the scaffolding was unable to find the Movies folder. Change it to below. Use backslash instead of forward slash. Before excuting the below command, you may want to create a Movies folder first inside your Pages folder. I am using VS code.
> 
> dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries

It worked for me
