### ISSUE TITLE
Typo on select taghelper

### ISSUE THREAD

**Issue by ghandlin** [aspnet/Docs#7309]
The get action is named IndexOption instead of just Index

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.1#the-select-tag-helper)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ghandlin  I think you're right. We'll get this fixed in the next sweep.
