### ISSUE TITLE
Regular expression mismatch

### ISSUE THREAD

**Issue by masaha03** [aspnet/Docs#7318]
Genre's rule is @"^[A-Z]+[a-zA-Z""'\s-]*$" so it can contain whitespace.
Rating's rule is @"^[A-Z]+[a-zA-Z0-9""'\s-]*$" so it can contain whitespace and numbers.
But in the explanation below the code, it says "Genre and Rating must use only letters (whitespace, numbers, and special characters aren't allowed)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @masaha03 ... I'll patch that up right now.

**Comment by mochr** [comment]
This issue does not seem to be fixed.
Regular expressions are still the same, but the text does not match. 

> "Genre":
>
>-Must only use letters.
>-The first letter is required to be uppercase. White space, numbers, and special characters are not allowed.

>"Rating":
>
>-Requires that the first character be an uppercase letter.
>-Allows special characters and numbers in subsequent spaces. "PG-13" is valid for a rating, but fails for a "Genre".

The pull request #7323 seems to describe the correct behavior, but this is not the text that is displayed on https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.2

**Comment by guardrex** [comment]
Hello @mochr ... Recommend a new issue. We can't track work on closed issues. Open it using the **This Page** feedback button at the bottom of the topic.
