### ISSUE TITLE
Document IHttpContextAccessor

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#7328]
[IHttpContextAccessor](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor) is only documented in a migration topic: https://docs.microsoft.com/aspnet/core/migration/claimsprincipal-current#retrieve-the-current-user-in-an-aspnet-core-app

[:point_up: That bit needs a touch of work as well.]

@davidfowl We can add a new section to the DI topic. I'm working on the DI topic now, so this is a good time to add it to that topic if you agree with the location.

Include best practices (e.g., https://github.com/aspnet/KestrelHttpServer/issues/2591).

**Comment by davidfowl** [comment]
We have this https://github.com/aspnet/Docs/pull/6489
