### ISSUE TITLE
Response Caching

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#733]
- Intro to response caching
  - Specify how you want to cache response messages- 
- Response Cache Attribute
  - A filter that specifies what HTTP cache headers to set
  - Duration, location (anyclient/none), vary by header value, no store
    - Any = proxy or client
    - Client = client only
    - None - no caching
  - Multiple named cache profiles can be configured on MvcOptions and specified using the CacheProfileName property on the attribute
    - Analog to output cache profiles in System.Web
  - Attribute settings win over cache profile
- Server caching behavior
  - IIS, WebListener will do kernel mode caching
  - Typically IIS is used as a reverse proxy, so you will need to specify Any for the location
  - No caching support in Kestrel, but Kestrel is typically run behind a reverse proxy that could do caching.

**Comment by ardalis** [comment]
Can we schedule a meeting to discuss this topic next week as well, @danroth27 ?

**Comment by ardalis** [comment]
Add this to mvc team meeting agenda @danroth27 . Per our email discussion, we were going to put this article in a new section called Performance under the MVC docs (just documenting that here).

**Comment by danroth27** [comment]
@Tratcher Can you comment on the caching behavior of IIS and WebListener?

**Comment by Tratcher** [comment]
By moving out of process (Beta8) I think we've lost access to most of IIS's static caching features. I'm not sure if dynamic caching or compression still work.

WebListener will attempt to cache responses in kernel mode if A) the entire response fits within the default buffer size (?), and there are cache headers on the response. The kernel cache doesn't support any vary-by conditions, so it's rather limited what can be cached.

**Comment by ardalis** [comment]
@danroth27 Given that ResponseCaching does no in-memory caching on the server, does it still make sense to have the server caching section in this article? I'm thinking it will only confuse the reader. I think it makes sense to have an architectural-level article somewhere that talks about reverse proxies and multi-server configurations, but I don't think this is the place for it. I have a pretty detailed article at this point covering Response Caching that I'm going to submit as a PR now - let me know if you want me to add Server Caching Behavior back into it.

**Comment by danroth27** [comment]
@ardalis Leaving the server caching section out is fine.

**Comment by GuardRex** [comment]
Side note: Dynamic compression seems ok ...

Dynamic Compression Enabled:
![with_dynamic_compression_enabled](https://cloud.githubusercontent.com/assets/1622880/12347578/0c80dfe6-bb14-11e5-81aa-ebbd967580a6.png)

Dynamic Compression Disabled:
![with_dynamic_compression_disabled](https://cloud.githubusercontent.com/assets/1622880/12347580/1216e68a-bb14-11e5-8377-be55043e2d22.png)

If you want me to test anything for you, give me a shout.
