### ISSUE TITLE
Great article!

### ISSUE THREAD

**Issue by JuanGarciaCarmona** [aspnet/Docs#7341]
Very useful, thank you, I'll refactor some of my code due to few ideas that came to my mind while reading.

Juan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a25f836-b946-9056-5fbc-1b47ff72efd0
* Version Independent ID: 5d189a96-a529-6afa-e05d-85cfa05c5c9f
* Content: [Identity model customization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/customize_identity_model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/customize_identity_model.md)
* Product: **asp.net-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by scottaddie** [comment]
@JuanGarciaCarmona It's great to hear the doc was valuable to you. Thank you for the feedback!
