### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by tuda224** [aspnet/Docs#7344]
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.1#custom-iauthorizationpolicyprovider --&gt;The second bullet point has a typo: AuthorizationPolicyBuil*d*er 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @tuda224 ... I'll patch that up right now.
