### ISSUE TITLE
Debug with Visual Studio Code

### ISSUE THREAD

**Issue by gjaryczewski** [aspnet/Docs#7345]
There is no info about how to debug with Visual Studio Code. The linked article ("Debug ASP.NET Core 2.x source") references to the Git issue, which is closed, and applies only to Visual Studio. A brief information here about possibilities in age of SDK 2.1 will be very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ab9158-909a-0cff-b620-e7248705d324
* Version Independent ID: 2c17f962-118c-3af1-337a-5d827fd31ac1
* Content: [Test, debug, and troubleshoot in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @gjaryczewski Can you clarify your ask? Are you looking for general debug instructions for IDEs, or are you are asking specifically about debugging source?

I agree that this page is a good spot to surface general debugging topics on IDE debuggers, so I'll add some links to the page ...

* https://code.visualstudio.com/docs/editor/debugging
* https://docs.microsoft.com/visualstudio/debugger/getting-started-with-the-debugger

RE: Debugging source

> The linked article ("Debug ASP.NET Core 2.x source") references to the Git issue, which is closed, and applies only to Visual Studio.

AFAIK that's the result of an editorial decision. @Rick-Anderson, do you prefer to leave source debugging out of the docs and continue to roll with the linked issue remarks by `@vancem`?

**Comment by Rick-Anderson** [comment]
@gjaryczewski  see the VS Code doc's for debugging.

**Comment by guardrex** [comment]
I was just going to drop the links in ... will only take a few seconds.

**Comment by Rick-Anderson** [comment]
@guardrex  why drop it? It's great info.

**Comment by guardrex** [comment]
huh ... I meant my plan here is to add the links to the topic. We don't have them right now. I'd add links to (at least) ...


* https://code.visualstudio.com/docs/editor/debugging
* https://docs.microsoft.com/visualstudio/debugger/getting-started-with-the-debugger
