### ISSUE TITLE
Issues with the migration document.

### ISSUE THREAD

**Issue by omnoms** [aspnet/Docs#7346]
Since it says that Microsoft.AspNetCore.App requires Microsoft.Net.Sdk.Web to be included, I added it. This wasn't in my old 2.0 project. The template generated csproj file mentioned above doesn't include it. But I added it and it has issues. It requires a specific version and the currently only available version is an alpha version that VS2017 15.7.4 with pre-release checkbox checked doesn't install. I had to add the alpha version string explicitly to get that to work. 

So is it required or not?     &lt;PackageReference Include="Microsoft.Net.Sdk.Web" Version="1.0.0-alpha-20161104-2-112" /&gt;

Also encountered issue with that if you use application insights, you now need to explicitly add
&lt;PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.1" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @omnoms Slight misunderstanding from the text (it's probably not specific enough; it shouldn't casually use the word "reference" in that way). It just means to set the SDK in the **\<Project>** tag at the top ...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```
... you **_don't_** add a package reference for `Microsoft.NET.Sdk.Web`.

I'll see if I can clarify it in the topic. Thanks for reporting this.
