### ISSUE TITLE
Easy to Follow!

### ISSUE THREAD

**Issue by bradfriedlander** [aspnet/Docs#7355]
The documentation was straight forward and easy to follow. Everything worked the first time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@bradfriedlander It's great to hear the doc was useful to you, and the feedback is appreciated.

**Comment by LeongTang** [comment]
It seems I can't find Swagger UI at http://localhost:<port>/swagger, I can only find it at http://localhost:<port>/index.html with VS 2017 15.7
