### ISSUE TITLE
Should SetCompatibilityVersion(CompatibilityVersion.Version_2_1) be used?

### ISSUE THREAD

**Issue by jwatkin** [aspnet/Docs#7361]
In your examples, should SetCompatibilityVersion(CompatibilityVersion.Version_2_1) be used?

public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc()
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jwatkin ... For 2.1, yes. Sample updates are tracked by #5495, but I think that @Rick-Anderson will be updating this along with https://github.com/aspnet/Docs/issues/7298.

**Comment by Rick-Anderson** [comment]
@jwatkin  It's not needed.
