### ISSUE TITLE
6 months old, please update.

### ISSUE THREAD

**Issue by nezoic** [aspnet/Docs#7364]
I can't get anything other than:
"invalid_request"
error_description:"AADB2C90205:+This+application+does+not+have+sufficient+permissions+against+this+web+resource+to+perform+the+operation

Is this documentation up to date? Are we missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebb27a5-41cc-b64f-de68-2f0df6b02f8d
* Version Independent ID: 31de5338-ace5-b8c4-88e8-54863428fc61
* Content: [Cloud authentication in web APIs with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c-webapi?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c-webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c-webapi.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by nezoic** [comment]
Also forgot to ask, depending on the documenation, there are two varatiations of the B2C Authentication url.
https://login.microsoftonline.com/tfp/<tenant domain >/b2c_1_sign_up_in/oauth2/v2.0/authorize
https://login.microsoftonline.com/<tenant domain >/oauth2/v2.0/authorize?p=b2c_1_sign_up_in

Which is correct or what are the differences?

**Comment by scottaddie** [comment]
@yoelhor @parakhj Any ideas?

**Comment by parakhj** [comment]
No difference. Just two ways of calling the service

**Comment by nezoic** [comment]
@parakhj Thanks for that clarification. Any idea on what I could be doing wrong with postman? Do I need an additional access per user step even though they've registered through the same postman, and verified the account. I get the same with manually created users as well.

**Comment by CamSoper** [comment]
@nezoic - I'll run through this walkthrough again on Monday and see if anything's changed.

**Comment by parakhj** [comment]
The error code indicates that you didn't configure the scopes and permissions correctly through the azure portal. Are you trying to get an access token to call an API? See https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens

**Comment by thuannguy** [comment]
I would suggest the doc mentions about https://login.microsoftonline.com/tfp/ and https://login.microsoftonline.com/ (without tfp)
Visual Studio template uses the former while Azure B2C uses the latter on its UI for testing policy set up. As a result, they are very confusing when something goes wrong.

**Comment by CamSoper** [comment]
Just merged https://github.com/aspnet/Docs/pull/8661.  Should take care of most of the issues.

I'll add the suggestion from @thuannguy on Monday.
