### ISSUE TITLE
Complete source code for filter examples

### ISSUE THREAD

**Issue by jwatkin** [aspnet/Docs#7365]
The source code targeted with the link named "View or download sample code" doesn't seem to contain the filter examples on this page.

I'm new to ASP.NET Core logging. I wasn't able to see the logging results just by following the examples on this page. In the Startup class, the "GlobalFiltersLogger" type doesn't appear to be defined. Also, is an explicit logging configuration required? Perhaps I'm doing something wrong, but it would be nice if one could see logging results in a documented location just by following the examples on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jwatkin  thanks for pointing this out. I'll fix that link.

**Comment by Rick-Anderson** [comment]
@jwatkin  correct link [View or download sample code](https://github.com/aspnet/Docs/tree/master/aspnetcore/razor-pages/filter/sample/PageFilter) ([how to download](xref:tutorials/index#how-to-download-a-sample))
