### ISSUE TITLE
Navigation on EF Core doesn't work

### ISSUE THREAD

**Issue by jyotendra** [aspnet/Docs#7370]
Having issue while navigating EF Core docs on following [url](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1). 

Precisely, the sidebar hyperlinks nor the "next"-"previous" button leads to new content:

![image](https://user-images.githubusercontent.com/4627495/42085128-2c7dd482-7bad-11e8-93cb-2a5d77fa45f2.png)

![image](https://user-images.githubusercontent.com/4627495/42085144-391ffed6-7bad-11e8-8753-bc3de095ffbc.png)

**Comment by jyotendra** [comment]
As shown in second screen-shot (attached above) the second part should have been about: "Create, Read, Update, and Delete operations". But as can be seen, content didn't changed.

**Comment by Rick-Anderson** [comment]
@jyotendra you must be looking at cached page for the screen shot. That tutorial is not being updated for 2.1. The RP version has been updated.
