### ISSUE TITLE
Hosting in a .Net Core 2.1 Windows Service on Windows Server 2016

### ISSUE THREAD

**Issue by mmaguirehub** [aspnet/Docs#7372]
I've followed the instructions here "https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1" to the letter and my .Net Core 2.1 Windows Service works perfectly when I create and start the service on my Windows 10 Pro machine.

The problem arises when I deploy on to our **Windows Server 2016 Datacenter OS**.  It creates the service as expected, but when I go to start the service I immediately get the following error:

**The service did not respond to the start or control request in a timely fashion.**

To emphasize, the service instantly fails to start with the above error.

If I try to run the exe itself I get the following error:

**Error:
  An assembly specified in the application dependencies manifest (TestService.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Hosting.WindowsServices', version: '2.1.1'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Hosting.WindowsServices.dll'**

I suspect the two error are interlinked somehow.

I'm fairly convinced that the code is not being hit in Program.Main as I've added logging in the first line of code to be ran but nothing happens.  I've tried adding the ServicesPipeTimeout registry entry to extend the time given for the service to start but I still get an instant fail.  I've ensured that the server has the required versions of .Net Core installed and they are:

- Microsoft. NET Core 2.1.1 - Windows Server Hosting - v2.1.13007.0
- Microsoft .NET Core Runtime - 2.1.1 (x64) - 2.1.1.26606

I've also ensured the IIS is enabled on the system.

I've been struggling with this for 2 days and cannot find the answers to resolve these issues anywhere.

Can this document be updated with instructions on how to deploy to the server to ensure all the pre-requisites are covered so that these issues don't occur?

I'd really like an answer to this, thanks in advance :)

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/7373
