### ISSUE TITLE
Edit() - FindAsync() instead of SingleOrDefaultAsync()

### ISSUE THREAD

**Issue by DutchmanDavid** [aspnet/Docs#7375]
In the Edit(int? id) functions there's the next line:
.SingleOrDefaultAsync(m =&gt; m.CourseID == id);

Couldn't that be simplified to:
.FindAsync(id);

Greetings,
David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938b178b-5f78-e673-df41-0409ad4412e1
* Version Independent ID: c06d8343-1407-aa05-de96-c1aca71ba232
* Content: [ASP.NET Core MVC with EF Core - Update Related Data - 7 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/update-related-data?view=aspnetcore-2.0#feedback)
* Content Source: [aspnetcore/data/ef-mvc/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Yes. See https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#singleordefaultasync-vs-firstordefaultasync
