### ISSUE TITLE
Can't use "Options pattern" with generic host

### ISSUE THREAD

**Issue by andriialbumentormate** [aspnet/Docs#7377]
Can't understand how to grab data using  "Options pattern" from appsettings.json file.
I have next code (part of Main method):

```
var environment = EnvironmentName.Development;

            var config = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", optional: true)
                .AddJsonFile(
                        $"appsettings.{environment}.json",
                        optional: true)
                .AddCommandLine(args)
                .AddEnvironmentVariables()
                .Build();


            var host = new HostBuilder()
                .ConfigureAppConfiguration(configApp => {
                    configApp.AddConfiguration(config);
                })
                .ConfigureLogging((hostContext, configLogging) =>
                {
                    configLogging.AddConsole();
                    configLogging.AddDebug();
                })
                .ConfigureServices((hostContext, services) => {
                    services.AddLogging();
                    services.AddHostedService<SomeService>();
                    services.AddSingleton<ISomeHelperService, SomeHelperService>();
                    services.Configure<MyOptions>(config);
                })
                .UseEnvironment(environment)
                .Build();
```

My app settings file contains
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "option1": "value1_from_json",
  "option2": -1
}
```

Options class
```
public class MyOptions
    {
        public string Option1 { get; set; }
        public int Option2 { get; set; }
    }
```
SomeService looks like

```
internal class SomeService : IHostedService
    {
        private readonly ILogger _logger;
        private readonly MyOptions _myOptions;
        private readonly ISomeHelperService _someHelperService;

        public SynchronizationService(ISomeHelperService someHelperService, ILogger<SomeService> logger, IOptions<MyOptions> optionsAccessor)
        {
            _someHelperService = someHelperService;
            _logger = logger;
            _myOptions = optionsAccessor.Value;
        }

        public Task StartAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }
    }
```
When I run app _myOptions' fields have default values, but have to hold values from settings file.
What can be the reason of this issue and how to solve it ?

Thanks a lot for any answer !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Ping @HaoK

**Comment by guardrex** [comment]
@andriialbumentormate I am able to repro the behavior you're seeing here with one of my test apps.

**Comment by guardrex** [comment]
@Tratcher Are u aware of any *gotchas* for options and the Generic Host?

**Comment by guardrex** [comment]
Nevermind ... I think this is just the 'old base path situation.

@andriialbumentormate Can you set ...

```csharp
.SetBasePath(Directory.GetCurrentDirectory())
```
... and try again.

**Comment by guardrex** [comment]
I'd like to surface this in the options topic where we show the use of the *appsettings.json* file for the sample app.

**Comment by HaoK** [comment]
Everything all figured out here @guardrex ?  Or did you have something you wanted me to look at still?

**Comment by guardrex** [comment]
Thanks @HaoK ... I've done the same thing as @andriialbumentormate ... *twice!* I think we're good here. I'm just waiting on confirmation from @andriialbumentormate that the app is working there with the base path set.

**Comment by andriialbumentormate** [comment]
@guardrex , hi !
I've added `SetBasePath` to my app:
```
var config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: true)
                .AddJsonFile(
                        $"appsettings.{environment}.json",
                        optional: true)
                .AddCommandLine(args)
                .AddEnvironmentVariables()
                .Build();
```
in configure services I have the same
```
.ConfigureServices((hostContext, services) => {
                    // add services
                    services.Configure<MyOptions>(config);
                })
```
But still can't retrieve values from `appsettings.json` file.
Probably I do something wrong ?

1. This project is just console app and in `main` method I configure host and run it.
2. `appsettings.json` and `appsettings.environment.json` files are in root of my project.
![capture1](https://user-images.githubusercontent.com/33482789/42156692-6a0aaf98-7df4-11e8-9ed5-947cb2c81939.JPG)
3. I run this app using VS 2017 (the latest update)
4. The path when I use `Directory.GetCurrentDirectory()` points to `D:\....\Proj\bin\Debug\netcoreapp2.1`

The only one way in which I can retrieve some data from `appsettings.json` is to set `Copy to Output Directory` property to `Copy Always`.
![capture2](https://user-images.githubusercontent.com/33482789/42157215-c7dcf4f4-7df5-11e8-84d3-055d5a301b0b.JPG)

If I do like this I can get `option1 and option2` from settings even without using of `SetBasePath(Directory.GetCurrentDirectory())` 
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "option1": "value1_from_json",
  "option2": -1
}
```

My question - did I do something wrong when I read [https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1](url) ?

Thanks for help and any answers !

**Comment by guardrex** [comment]
Oh ... I thought u were working with the Web SDK (`<Project Sdk="Microsoft.NET.Sdk.Web">`). `SetBasePath` is effective with the Web SDK but not a console app that sets the SDK to `Microsoft.NET.Sdk`. You'll probably need move files (settings files or any other types of developer-added files) manually. You may have noticed that when you set the build action that it adds the following to to your project file ...

```xml
<ItemGroup>
  <None Update="appsettings.json">
    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </None>
</ItemGroup>
```

We don't document this requirement in the ASP.NET Core docs because this doc set is very focused on the Web SDK and web apps in general. If you change your SDK over to the Web SDK, then you'll see that you won't need to move the settings file manually when you have `SetBasePath` present.

**Comment by andriialbumentormate** [comment]
@guardrex  thanks a lot for quick answer and clarification !

**Comment by andriialbumentormate** [comment]
@guardrex want to mention that in example https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host/samples/2.x/GenericHostSample/GenericHostSample.csproj you use `Sdk="Microsoft.NET.Sdk"`. 
Thanks a lot !

**Comment by guardrex** [comment]
Good point. @Tratcher `SetBasePath` isn't effective without the Web SDK AFAICT. What's our guidance for the Generic Host in this circumstance where the appsettings file(s) need to be moved and the app SDK is `Microsoft.NET.Sdk`?

**Comment by guardrex** [comment]
Same deal with the **ConfigJson** sample ... https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index/sample/ConfigJson/Program.cs . That sample project has a project SDK of `Microsoft.NET.Sdk`. It doesn't run in VS ...

<img width="417" alt="capture" src="https://user-images.githubusercontent.com/1622880/42170043-0b2bb35a-7ddb-11e8-8db6-275501697ac4.PNG">

Change the SDK to `Microsoft.NET.Sdk.Web` and :tada: ...

<img width="237" alt="capture2" src="https://user-images.githubusercontent.com/1622880/42170090-27d21e72-7ddb-11e8-8c3b-4a5f1299ce99.PNG">

**Comment by andriialbumentormate** [comment]
@guardrex probably better to mention this somewhere in generic host article or in another one. Because this issue (don't know how to name it correctly) can confuse.

**Comment by Tratcher** [comment]
The short answer is that we haven't given any guidance here yet. I suggest manually marking those config assets as `<CopyToOutputDirectory>Always</CopyToOutputDirectory>`.

**Comment by guardrex** [comment]
In that case, I'll add a bit to the Generic Host topic to cover this. The project SDK is `Microsoft.NET.Sdk`, so I agree with @andriialbumentormate that readers need a little coverage on this.

As for the config topic, I'll add it there, too. We're planning a major config overhaul where the sample will go to RP and this won't be an issue, but I don't know exactly when that overhaul will occur.
