### ISSUE TITLE
SignalR topics ToC enhancements

### ISSUE THREAD

**Issue by rachelappel** [aspnet/Docs#7378]
https://github.com/aspnet/Docs/pull/7285#issuecomment-401417051

From @anurse: "Should we consider having a subnode for "Using SignalR with Module Loaders" or "Using SignalR with JavaScript Frameworks" (as I wouldn't be surprised if we ended up with Angular/React/Vue/etc. guides in here)?" f

What else do we want? Something like below?

* SignalR
  * Module Loaders
  * JavaScript & TypeScript 
  * Clients 
  * Security

**Comment by rachelappel** [comment]
Current ToC

Introduction
Get started
Hubs
JavaScript client
.NET client
HubContext
Users and groups
Configuration
MessagePack Hub Protocol
Publish to Azure
Streaming
Supported platforms
Differences between SignalR versions

**Comment by anurse** [comment]
I don't think everything needs to be grouped into a mid-level node, we can have a bit of a hybrid layout:

* SignalR
  * Getting started (nice to keep this at the top-level IMO)
  * Server Concepts
    * Supported platforms
    * Hubs
    * HubContext
    * Users and groups
    * Publishing to Azure
  * Clients
    * JavaScript
    * .NET
    * Java (2.2; no docs yet)
    * C++ (2.2; no docs yet)
  * Configuration (alternatively we could split the docs into a Server doc and one for each client)
  * MessagePack Protocol
  * Streaming
  * Differences between versions
