### ISSUE TITLE
Doc WS-Federation provider specifically for core

### ISSUE THREAD

**Issue by saikrishnaadapa** [aspnet/Docs#7381]
Is there any way to Autenticate using Ws Federation  in ASP.Net Core 2.1 MVC using the existing WIF Implemented Ws Federation Provider in .Net Framework.

Which seems to be not working, I didnt find any helpful document to work on this thing.

**Comment by scottaddie** [comment]
@blowdart Do you know?

**Comment by blowdart** [comment]
No, there's no way. Which is why there's a WS-Federation provider specifically for core. Which I guess we haven't documented. https://github.com/aspnet/Security/tree/dev/src/Microsoft.AspNetCore.Authentication.WsFederation

**Comment by Rick-Anderson** [comment]
@blowdart  who can outline this?

**Comment by blowdart** [comment]
Oh wait, it is there https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1

**Comment by saikrishnaadapa** [comment]
@blowdart 
No It isn't applicable for my scenario as mentioned below,

I have a ASP.Net application (WIF) consuming the Ws federation Services for the authentication. So that other applications can Utilize this Federation Provider for authentication and authorization.

How can we use this existing Federation Provider Application in another application build on ASP.Net Core 2.x for authentication and authorization.

**Comment by blowdart** [comment]
When you say you're consuming this indicates (to me) that you have a WS-Fed provider elsewhere. So you'd configure core in the way that [documentation details](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1#use-ws-federation-without-aspnet-core-identity), which would call out to the WS-Fed provider, then use cookies to create the identity that persist between calls. So what is missing here?

**Comment by saikrishnaadapa** [comment]
@blowdart i have few more questions where should we configure the thumbprint in the core application?

**Comment by saikrishnaadapa** [comment]
Code Snippet for configuring WS-Federation is as follows.
 services
            .AddAuthentication(sharedOptions =>
            {
                
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
            })
            .AddWsFederation(WsFederationDefaults.AuthenticationScheme, WsFederationDefaults.DisplayName, options =>
            {
               

                options.Wtrealm = "https://localhost:44338/";

                //For Bypassing Metadata Address
                options.MetadataAddress = string.Empty;
                

                options.Configuration = new Microsoft.IdentityModel.Protocols.WsFederation.WsFederationConfiguration
                {
                    TokenEndpoint = Configuration["SSOSettings:WIFFederationProviderAddress"],
                    Issuer = "FP"

                };


                options.RequireHttpsMetadata = false;

                options.TokenValidationParameters.ClockSkew = TimeSpan.FromMinutes(5);

                options.ClaimsIssuer = Configuration["SSOSettings:WIFFederationProviderAddress"];



                options.TokenValidationParameters.ValidateIssuer = true;
                options.TokenValidationParameters.ValidateLifetime = true;

                options.TokenValidationParameters.ValidateAudience = true;
                options.TokenValidationParameters.ValidateTokenReplay = false;
                options.TokenValidationParameters.RequireSignedTokens = true;


                options.CallbackPath = new PathString("/signin-wsfed");
                options.SkipUnrecognizedRequests = true;


            })
            .AddCookie();

**Comment by blowdart** [comment]
Then you haven't configured your provider correctly. In WS-Fed that would be the Relying Party protocol URL. The return URL is configured in the identity provider.

**Comment by blowdart** [comment]
And the thumbprint comes from the metadata endpoint, which allows for cert rotation.

**Comment by saikrishnaadapa** [comment]
@blowdart I tried either way but the result was the same.

**Comment by blowdart** [comment]
I'm afraid there's not a lot more I can offer. It worked in our testing, when the provider was configured correctly. I'd suggest talking to your federation provider at this point.

**Comment by saikrishnaadapa** [comment]
Federation Provider is configured in such a way that it cross checks the Thumbprints(from the receiving end and fed provider) in order to authenticate.

**Comment by blowdart** [comment]
Not this one. Nor did the Owin implementation. WIF is 10+ years old. The standard is to get the metadata and use that, because it allows for certificate rotation. We moved away from thumbprints over 5 years ago.

**Comment by saikrishnaadapa** [comment]
Can you please provide the link with the full-example for the WS-Fed using Core along with the Federation Provider implementation in order to get the over all view of it. 
So that i can point it in the Right direction.

**Comment by blowdart** [comment]
https://github.com/aspnet/Security/tree/dev/samples/WsFedSample

And as this isn't a docs issue I'm going to close this issue.
