### ISSUE TITLE
Docs/aspnet/ajax/cdn/overview.md what are those 'glyphicons' resources non existing in Bootstrap 4.*? 

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Docs#7382]
## Issues with Existing Topics

The docs about MS Ajax CDN list Bootstrap related resources:
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#bootstrap-version-400

```
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/fonts/glyphicons-halflings-regular.eot
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/fonts/glyphicons-halflings-regular.svg
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/fonts/glyphicons-halflings-regular.ttf
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/fonts/glyphicons-halflings-regular.woff
https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/fonts/glyphicons-halflings-regular.woff2
```
AFAIK BS4 does not ship with icon library bundled and that is left to users to pick a icon/font library of their choice:

https://getbootstrap.com/docs/4.0/extend/icons/

## Requests for new Topics

I'd review the section about the BS4 having first asked someone from team responsible for Ajax CDN what was the intent of these links. 
At the moment I think these links serve no purpose and add noise

Thanks!

**Comment by Rick-Anderson** [comment]
Why don't we just remove them? cc @scottaddie

**Comment by scottaddie** [comment]
@Rick-Anderson It's true that the glyphicons didn't live on past Bootstrap 3.x. Thank you for pointing this out, @peterblazejewicz!

**Comment by peterblazejewicz** [comment]
@scottaddie 
You're welcome. We could work-out some solution. Ping me if you need anything.
