### ISSUE TITLE
Can redirect target a different host?

### ISSUE THREAD

**Issue by MNF** [aspnet/Docs#7389]
E.g can https://myhost.com/resource1 be redirected outside of current host to https://myfriendhost.com/resource2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5f7c61-a9fa-bd34-001d-217477874bb6
* Version Independent ID: 9c48da92-af90-3fc1-fde0-c3f74fa88510
* Content: [URL Rewriting Middleware in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/url-rewriting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/url-rewriting.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Sure ... just provide the redirect endpoint. For example,

```
var options = new RewriteOptions()
    .AddRedirect("redirect-me", "https://www.doctorwho.tv/");

app.UseRewriter(options);
```

A request to `http://localhost:5000/redirect-me` will redirect to BBC's Dr. Who website:

```
HTTP/1.1 302 Found
Date: Fri, 29 Jun 2018 23:36:35 GMT
Server: Kestrel
Content-Length: 0
Location: https://www.doctorwho.tv/
```
