### ISSUE TITLE
Errors Running Project

### ISSUE THREAD

**Issue by regal60740** [aspnet/Docs#7391]
When I do this:
Launch the app
In Visual Studio, press CTRL+F5 to launch the app. Visual Studio launches a browser and navigates to http://localhost:&lt;port&gt;/api/values, where &lt;port&gt; is a randomly chosen port number. Navigate to the Todo controller at http://localhost:&lt;port&gt;/api/todo.

I get 6 Build errors. I copied your code and replaced my code and when I go to run it, I get the 6 errors. I obviously am missing usings of some kind. Should I have to figure out what is missing or am I replacing usings that came with the original program that should not be replaced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@regal60740 A couple questions for you:
1. What are the 6 build errors you're seeing?
1. Which version of the tutorial are you reading? ASP.NET Core 2.1?

**Comment by regal60740** [comment]
I just reopened the project, which is built in ASP.NET Core 2.1 (TodoApi). Now, I'm only seeing 4 errors:
Error	CS0246	The type or namespace name 'ApiControllerAttribute' could not be found (are you missing a using directive or an assembly reference?),
Error	CS0246	The type or namespace name 'ApiController' could not be found (are you missing a using directive or an assembly reference?),
Error	CS0308	The non-generic type 'ActionResult' cannot be used with type arguments,
Error	CS0308	The non-generic type 'ActionResult' cannot be used with type arguments.

Again, I'm just using the code from the tutorial, replacing my code. It looks exactly the same as the code on GitHub.

**Comment by Rick-Anderson** [comment]
Try `dotnet new webapi`
and run the project. Compare to the code in the instructions.

**Comment by regal60740** [comment]
I went back and ran the tutorial for ASP.NET Web Application (.NET Framework) with Web API. Everything worked out fine. For now, I'm just going to run all my projects this way. Saves time.

**Comment by scottaddie** [comment]
@regal60740 The errors you provided indicate that either you don't have the .NET Core SDK 2.1 installed or you aren't using at least version 15.7.3 of Visual Studio 2017. I hope that helps. Keep in mind that you're not using ASP.NET Core when you use the **ASP.NET Web Application (.NET Framework)** project template. That's ASP.NET 4.x., and much of what's described in this tutorial won't work in that framework.

**Comment by regal60740** [comment]
I checked both and I am running .NET Core 2.1 and my VS 2017 is running
version 15.7.1. I checked under tools menu and there were no updates even
though my settings are set to automatically update my software. I found
online that there is a notification flag at the top on VS 2017 and when I
clicked on it, it showed an update for 15.7.4. I did the upgrade and it
shows I'm now running version 15.7.4 but I'm still getting the same 4
errors I did earlier in my project. I've tried cleaning and rebuilding the
solution but nothing changes. Again, this is the same code from the TodoApi
tutorial from your site for .NET Core 2.1.

**Comment by Rick-Anderson** [comment]
@regal60740  I'm not sure what you're doing wrong but we have thousands of customers reporting success on this tutorial. 
VS update won't update the .NET Core SDK.
Did you try  `dotnet new webapi`

**Comment by Rick-Anderson** [comment]
As a tip, you can run `dotnet --version` from the command shell to see the SDK version. A value equal to or greater than 2.1.300 means you have the 2.1 SDK installed.

**Comment by regal60740** [comment]
I tried .Net Core Tutorial first using the exact code from the website
(replacing all usings with the suggested usings as well). I then ran the
older tutorial with .Net with no issues. It seems odd that
'[ApiController]' and 'ActionResult<List<TodoItem>>' would show red
squiggles and errors. It seems to me that the right 'using' or references
are missing.

**Comment by regal60740** [comment]
Hey Scott, I found out that I did not have .NET Core 2.1 installed after
all. I just installed and updated to .NET Core 2.1.1 and errors are gone. I
do apologize for all the trouble. I appreciate what you have done greatly.
Have a great 4th of July!

**Comment by scottaddie** [comment]
@regal60740 I'm glad you figured it out. Thank you for reporting back, and thank you for reading our docs. Happy 4th to you too!

**Comment by safestudent** [comment]
I'm getting the same problem and I'm trying to just build the 'TestingControllersSample' project using the 'dotnet build' command. I had the same problem in Visual Studio. I am using .NET Core version 2.1.500.

`$ dotnet --version
2.1.500

$ dotnet build  TestingControllersSample.csproj

Build FAILED.

Api\IdeasController.cs(75,27): error CS0308: The non-generic type 'ActionResult'                                            cannot be used with type arguments [C:\Users\stude\Desktop\Docs\aspnetcore\mvc\                                           controllers\testing\sample\TestingControllersSample\src\TestingControllersSample                                           \TestingControllersSample.csproj]
Api\IdeasController.cs(101,27): error CS0308: The non-generic type 'ActionResult                                           ' cannot be used with type arguments [C:\Users\stude\Desktop\Docs\aspnetcore\mvc                                           \controllers\testing\sample\TestingControllersSample\src\TestingControllersSampl                                           e\TestingControllersSample.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:01:37.27`

Is this a problem in the latest version of .NET core?
