### ISSUE TITLE
Include a section on how to enable Authorization on the Hub

### ISSUE THREAD

**Issue by grahambunce** [aspnet/Docs#7395]
You have a new section on client authentication requests but it's not clear what needs to be done on the Hub. I *think* you need an [Authorize] attribute at the hub class level, and then the usual app.UseAuthentication()... which I managed to find in a github ticket, but as you only client side in your example it's not clear what's needed server side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
@grahambunce  There are some security docs [here](https://github.com/aspnet/Docs/pull/7312) that should provide those details. Should be published quite soon.

**Comment by Rick-Anderson** [comment]
@grahambunce  fixed via https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1
