### ISSUE TITLE
Deleting table crashes app

### ISSUE THREAD

**Issue by kztd** [aspnet/Docs#7396]
I delete the table, then then Update-Database in pmc, pmc says:

No migrations were applied. The database is already up to date.

but there is no database I can see and the app is crashed.  The instruction to "Change the connection string and it will create a new DB." in previous post is hopeful, but cryptic.  There are connection strings all over the place, and change it to what exactly?  

ok, so this worked to fix:
1. from SSOX create a new SQL db, Movies
  - for this exercise I stuck it in the same folder with the source so it would be under version control
2. from SSOX, properties, I got the connection string and replaced the one in the appsettings.json file
3. ran Update-Database in PM, this time it worked

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kztd  sounds like you solved the problem.
