### ISSUE TITLE
BackgroundTaskQueue Confusion why do we need a semaphore

### ISSUE THREAD

**Issue by granthoff1107** [aspnet/Docs#7398]
I'm looking at the implementation of the BackgroundTaskQueue I'm a bit confused on the implementation.

    public class BackgroundTaskQueue : IBackgroundTaskQueue
    {
        private ConcurrentQueue<Func<CancellationToken, Task>> _workItems = new ConcurrentQueue<Func<CancellationToken, Task>>();
        private SemaphoreSlim _signal = new SemaphoreSlim(0);

        public void QueueBackgroundWorkItem(Func<CancellationToken, Task> workItem)
        {
            if (workItem == null)
            {
                throw new ArgumentNullException(nameof(workItem));
            }

            this._workItems.Enqueue(workItem);
            this._signal.Release();
        }

        public async Task<Func<CancellationToken, Task>> DequeueAsync(
            CancellationToken cancellationToken)
        {
            await this._signal.WaitAsync(cancellationToken);
            this._workItems.TryDequeue(out var workItem);

            return workItem;
        }
    }

Why do we need a SemaphoreSlim if we're using a concurrent queue?

**Comment by davidfowl** [comment]
If the queue is empty you need to wait until there’s more data in the queue. The semaphore helps with that. It’s being used to wait asynchronously if there the queue is empty.

**Comment by granthoff1107** [comment]
@davidfowl, I’d just would have figured the semaphore should have been in the service instead of the queue, but thanks this makes more sense now

**Comment by davidfowl** [comment]
Ownership would be split between the queue and the hosted service. The semaphore needs to be signaled on enque. The implementation isn’t as optimal as it could be though as there’s no need to wait for the semaphore if there’s data in the queue

**Comment by pvenky** [comment]
This tripped me up as well. Perhaps, add comment lines in the sample code for clarity?

**Comment by davidfowl** [comment]
We should just change this code to use Channels
