### ISSUE TITLE
Setting up Two Factor Authentication with ASP.NET Identity

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#74]
ASP.NET 5->Security->Setting up Two Factor Authentication with ASP.NET Identity

**Comment by rustd** [comment]
You can follow the flow in this article http://www.asp.net/identity/overview/features-api/two-factor-authentication-using-sms-and-email-with-aspnet-identity

Following is the outline:
* Create ASP.NET 5 Web Site template
* Enable Two-factor authentication by uncommenting the code in Views\Manage\Index.cshtml
* Explain the wire up Startup.cs
* Set up SMS for Two-factor authentication
* Use the SecretManager to add the Keys for Twilio and wire them up in MessageService.cs
* Run the app with the 2FA flow and show screenshots and code
* Show how Account lockout prevents against brute force attacks
