### ISSUE TITLE
Code, or screenshots of code?

### ISSUE THREAD

**Issue by robbert229** [aspnet/Docs#740]
In several areas of the documentation there are screenshots of code instead of code blocks. Is this how things are intended or are we planning on fixing this? 

[Example](http://docs.asp.net/projects/mvc/en/latest/views/tag-helpers/intro.html)
@Rick-Anderson

**Comment by danroth27** [comment]
Should be code that you can copy and paste.

**Comment by Rick-Anderson** [comment]
@robbert229  @danroth27  99.9%  of the time we want code, not screen shots. This is a .1% case where showing the TH formatting in VS is far more important than the actual code. This call was made by @NTaylorMullen and I agree with it.
