### ISSUE TITLE
ASP.NET Core 2.1 Version

### ISSUE THREAD

**Issue by Faraz2018** [aspnet/Docs#7402]
Hi colleagues,
Any similar complex simple to complex complete project for ASP Core 2.1?
Dying hard for an updated Contoso University or some other FULL tutorial covering ALL topics for a DEEP-DIVE with valuable guidelines from ideal programmers like you all.
:-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [ASP.NET Core MVC with EF Core - Data Model - 5 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@Faraz2018  unfortunately we don't have the resources to update this tutorial. The deep dive EF will need to come from  https://docs.microsoft.com/en-us/ef/core/get-started/

**Comment by Bud91** [comment]
Hi,
I don't mean this in a bad way, but you guys go through a lot to update ASP.NET Core and all relevant libraries to make it better. Not having an updated tutorial for it is a shame. I am currently going through the razor pages tutorial but unsure if all those methods will work without razor pages or in an API and was hoping for an updated tutorial myself as I am learning .NET core still.
