### ISSUE TITLE
Why is it that i can't configure or use hsts except the startup class ? 

### ISSUE THREAD

**Issue by blink2linkme** [aspnet/Docs#7405]

**Comment by Rick-Anderson** [comment]
@blink2linkme  `UseHsts` was designed to be called from `Startup.Configure`

**Comment by blink2linkme** [comment]
@Rick-Anderson so if i'm having a base class to configure all my services and applications then i won't be able to make use of hsts ? Is there an alternative or do i still have to configure everything only in startup class ?

**Comment by Rick-Anderson** [comment]
@dougbu 	please respond.

**Comment by dougbu** [comment]
@blink2linkme
> do i still have to configure everything only in startup class ?

If you're calling into another class from `Startup.Configure(...)`, the only thing calling `UseHsts()` requires is that you've got the `IApplicationBuilder` and a `using Microsoft.AspNetCore.Builder;` statement in the called class.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
