### ISSUE TITLE
How does the created angular app differ from an angular app created using Angular CLI

### ISSUE THREAD

**Issue by rhegner** [aspnet/Docs#7406]
In this article you mention "There are slight differences between the Angular app created by this template and the one created by Angular CLI itself".

What are those differences?

Let's say I create a new ASP.NET Core Angular project and I want to replace the content of the ClientApp folder with an angular app which I created using Angular CLI. What exactly do I need to change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#create-a-new-app)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/Templating/issues/630
