### ISSUE TITLE
Should note that ApiController attribute might need compatibility setting

### ISSUE THREAD

**Issue by phatcher** [aspnet/Docs#7407]
The ApiController attribute might not work unless the services.SetCompatibilityVersion(CompatibilityVersion.Version_2_1) is set in startup - see https://github.com/aspnet/Mvc/issues/7546

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by SuddenGunter** [comment]
Asp.Net Core 2.1, ApiController works without compability setting perfect
