### ISSUE TITLE
Have I missed something? Doesn't seem to work with .net 2.0 projects

### ISSUE THREAD

**Issue by ianpowell2017** [aspnet/Docs#7418]
Hi, Despite the filter in the menu bar, this seems to be only for .net 2.1
Is that right?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/test/integration-tests?view=aspnetcore-2.0)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@ianpowell2017 Hello ... Yes, 2.1 only. I'm missing a setting in the metadata. I'll patch that right now. Thanks for letting me know. :+1:

**Comment by ianpowell2017** [comment]
Thanks Luke,

Do you have any links for .net core 2.0

I have a .net core app with controllers without any tests and no descent articles to point me in the right direction

Thanks for your help

Ian

**Comment by guardrex** [comment]
We have yet to upgrade the one on testing controllers (the sample on this one is still 2.0) :point_right: https://docs.microsoft.com/aspnet/core/mvc/controllers/testing
