### ISSUE TITLE
Update Integration Testing article to RC1

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#742]
https://docs.asp.net/en/latest/testing/integration-testing.html#comment-2391378407

**Comment by robbert229** [comment]
Is it okay if I update this? @danroth27

**Comment by ardalis** [comment]
@robbert229 go for it and I can review.

**Comment by robbert229** [comment]
Thanks, will do.

**Comment by robbert229** [comment]
PR #746

**Comment by robbert229** [comment]
@danroth27 This should be closed.
