### ISSUE TITLE
Update Disqus configuration to specify page URL and page ID

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#743]
Our entire site now redirects to https, but we should still do this at some point:

https://help.disqus.com/customer/en/portal/articles/2158629

**Comment by shirhatti** [comment]
It is also worth noting that Disqus allows you to merge threads which may be of value to us
https://help.disqus.com/customer/portal/articles/286778-using-the-migration-tools

**Comment by Rick-Anderson** [comment]
@danroth27 @shirhatti  Should I add "migrate DISQUS MVC comments" to this issue or open a new one? Customer feedback should always be reviewed before updating an article. cc/ @rachelappel 
If we can't migrate, we need to archive for review.
