### ISSUE TITLE
Show a sample for Custom Key Encryption

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#744]
@danroth27 @Rick-Anderson @ardalis @muratg @blowdart @GrabYourPitchforks 

RE: https://docs.asp.net/en/latest/security/data-protection/implementation/key-encryption-at-rest.html#custom-key-encryption

When you think about the multitude of scenarios where Data Protection is going to need to work, many will want to know more specifically how to replace the encryption/decryption mechanism of Data Protection.

There is a great built-in system for using DPAPI-NG with a certificate, but consider some won't want the overhead of dealing with certs or have some other anti-cert sentiment. It also looks like DPAPI-NG is for Windows 8.1/Windows Server 2012 R2 only ... what about other OS's?

To speed things up for folks that would like to drop in their own algorithms there [and without getting into the thorny issue of which one (or ones) to suggest], I'd like to propose a code sample be provided in the Custom Key Encryption section that isn't specific about the algorithm but lays out the basics.

Something along the lines of this would be nice and speed up devs quite a bit ... but not necessarily this of course, as @blowdart or another team member could probably do better.
```c#
using System.Xml.Linq;
using Microsoft.AspNet.DataProtection.XmlEncryption;

namespace MyApp.DataProtection
{
    public class ICustomXmlEncryptor : IXmlEncryptor
    {
        public EncryptedXmlInfo Encrypt(XElement plaintextElement)
        {
            XElement encryptedElement = new XElement(plaintextElement);
            // REPLACE THE NEXT LINE: Instead of adding a goofy word to the 
            // value, drop in an algorithm that takes the value stored in 
            // plaintextElement.Value and encrypts it with a suitable
            // encryption algorithm. The key for your encryption could be 
            // pulled down from Azure Key Vault.
            encryptedElement.Value = plaintextElement.Value + "_GOOBERSIS!";
            EncryptedXmlInfo encryptedTextElement = new EncryptedXmlInfo(encryptedElement, typeof(ICustomXmlDecryptor));
            return encryptedTextElement;
        }
    }

    public class ICustomXmlDecryptor : IXmlDecryptor
    {
        public XElement Decrypt(XElement encryptedElement)
        {
            XElement decryptedElement = new XElement(encryptedElement);
            // REPLACE THE NEXT LINE: Instead of removing the goofy word 
            // '_GOOBERSIS!' from the end of the value, drop in the 
            // decryption algorithm matched to your encryption above. The
            // key for your decryption could be pulled down from Azure Key 
            // Vault.
            decryptedElement.Value = encryptedElement.Value.Substring(0, encryptedElement.Value.Length - 11);
            return decryptedElement;
        }
    }
}
```
Then, `Startup.cs` needs ...
```c#
services.AddSingleton<IXmlEncryptor, ICustomXmlEncryptor>();
services.AddSingleton<IXmlDecryptor, ICustomXmlDecryptor>();
```
... or is it `.AddTransient<...>()`>, and forgive me if I hosed the naming `I` for an interface that replaces an interface that perhaps should just be named like a class. Can you tell I started programming on a Timex Sinclair 1000??!! Yeah ... it wasn't an issue. It wasn't a pressing issue on a TRS-80 Model I either!

One other nit ... maybe best to go with gender-neutral language in the docs. Replace "his" in "the developer can specify his own key encryption mechanism" with "their" to cover everyone.

**Comment by muratg** [comment]
I think a sample would be a useful idea, and above looks good for documenting it, but I'd like to hear what @blowdart and @GrabYourPitchforks think about it as well.    

A sample in Entropy repo would also be interesting, perhaps implementing a custom key encryption using a real world encryption solution.

**Comment by blowdart** [comment]
The problem we have is there is NOTHING on other OSes right now, so there's nothing to document.

There's a reason we don't document examples for this beyond an azure key store example which will probably end up in the actual code base - it's hard to get right and frankly we don't want to encourage it for the every day developer - the sorts of real world examples would be using an HSA. 

Giving an example would encourage every day developers to experiment in something very dangerous - I think this is a bad idea and I'd discourage any PR which tries it.

File a separate issue for gender neutral language and tag @danroth27

**Comment by GrabYourPitchforks** [comment]
One of the libraries we considered very early on was [Google Keyczar](https://github.com/google/keyczar). There are a variety of reasons we ended up not going with it. However, it should be possible for an interested party to create an implementation of `IDataProtectionProvider` that wraps the Keyczar libraries.

Some things an implementer would need to be aware of: (a) key creation would be challenging since Keyczar assumes that keys are created ahead of time rather than on-demand, (b) the concept of "purpose" would need to be flowed manually, and (c) AES-CBC+HMAC should be preferred over AES-GCM if there's no automatic key rolling. These aren't insurmountable obstacles, but they do present interesting technical challenges of various difficulty.
