### ISSUE TITLE
Post Function Requires [FromBody] Attribute

### ISSUE THREAD

**Issue by pobartlett** [aspnet/Docs#7442]
As it is given in the tutorial, the HttpPost "Create" function will not allow you to enter new data.
Given the JSON`{
  "name":"walk dog",
  "isComplete":true
}`, the object that is read in by the controller is 

![image](https://user-images.githubusercontent.com/13867306/42243533-b3a9574e-7edf-11e8-9de8-fb60a3c99dfe.png)

Updating the function signature to `public IActionResult Create([FromBody]TodoItem item)` allows the request data to be read properly.

![image](https://user-images.githubusercontent.com/13867306/42243658-10a42f3c-7ee0-11e8-9ec6-a700b2ab7d9d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pobartlett  I can't reproduce this problem. The sample download works fine. 

![image](https://user-images.githubusercontent.com/3605364/42246696-c7fc43e6-7eda-11e8-8ddb-e134c570fd7c.png)

**Comment by Dc9894** [comment]
@pobarlett I think the issue is because you may have forgot to anótate the controller class with the ```[ApiController]``` attribute.

**Comment by scottaddie** [comment]
@pobartlett I suspect the suggestion from @Dc9894 will fix the problem. The `[FromBody]` attribute is only inferred for complex types when the controller is annotated with `[ApiController]`. `[ApiController]`, of course, requires ASP.NET Core 2.1 or later. For ASP.NET Core 2.0 and below, the `[FromBody]` attribute is required.
