### ISSUE TITLE
ASP.NET core 2.1

### ISSUE THREAD

**Issue by 2muchdemon4u** [aspnet/Docs#7446]
What if I don't have the option to pick ASP.NET Core 2.1 in the drop down menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/42248750-77726004-7ee4-11e8-8161-36bd83bc2f6d.png)

![image](https://user-images.githubusercontent.com/3605364/42248764-854cfc98-7ee4-11e8-996c-407918994cbc.png)
