### ISSUE TITLE
Business logic in Views ?

### ISSUE THREAD

**Issue by ParidaPunyasloka** [aspnet/Docs#7452]
The logic to display "Rick", 'n' number of times has been implemented in the View File. This can be achieved via the controller as well, right? And as mentioned previously, isn't it a good practice to keep the business logic in the controller ? or does this part doesn't qualify as business logic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e594e5d1-6989-539e-859c-77004f89ffe1
* Version Independent ID: 2c9aa3e5-5ce7-c9d6-27c1-b6707dc0aa44
* Content: [Add a view to an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/adding-view?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ParidaPunyasloka  it's a demo - trivial code to introduce you to controllers and view. It's not best practices.
