### ISSUE TITLE
Errors with first Tutoral ASP.NET Core MVC web development with controllers and views

### ISSUE THREAD

**Issue by WayneSudol** [aspnet/Docs#7453]
Installed VS 2017 and tried the first tutorial. Crating a new project says to use "ASP.NET Core Web Application (.NET Core)".  That template doesn't exist in the center choices. I reinstalled core 2.1 SDK and it didn't make any difference. The other 4 templates as shown in the example under new projecr &gt;web&gt; .NET Core do exist. I.E. Console app (.Net Core), Class Library(&gt;NET Core), MSTest Test Project(.NET Core), and xUnit Test Project(.NET Core)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x&view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@WayneSudol Which version of VS 2017 did you install (I think current is 15.7.4)? My screens match the tutorial (except that I also have Blazor installed) ...

<img width="707" alt="capture" src="https://user-images.githubusercontent.com/1622880/42298892-ea3b5f8e-7fcd-11e8-8d65-76768d2e1d5c.PNG">

<img width="590" alt="capture1" src="https://user-images.githubusercontent.com/1622880/42298896-ecedbc0e-7fcd-11e8-963e-2bf5f9ff4fff.PNG">

**Comment by WayneSudol** [comment]
Latest one. Installed 4 days ago.

Sent from my iPhone

On Jul 4, 2018, at 19:07, Luke Latham <notifications@github.com<mailto:notifications@github.com>> wrote:


@WayneSudol<https://github.com/WayneSudol> Which version of VS 2017 did you install (I think current is 15.7.4)? My screens match the tutorial (except that I also have Blazor installed) ...

[capture]<https://user-images.githubusercontent.com/1622880/42298892-ea3b5f8e-7fcd-11e8-8d65-76768d2e1d5c.PNG>

[capture1]<https://user-images.githubusercontent.com/1622880/42298896-ecedbc0e-7fcd-11e8-963e-2bf5f9ff4fff.PNG>

**Comment by guardrex** [comment]
Confirm your version just to make sure: **Help** > **About Microsoft Visual Studio**.

<img width="585" alt="capture" src="https://user-images.githubusercontent.com/1622880/42299139-28582d1e-7fcf-11e8-97a0-e39d436552c7.PNG">

**Comment by WayneSudol** [comment]
it's 15.7.4

Here's what's installed from VS Help About


Microsoft Visual Studio Professional 2017
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA369
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40608.0
Azure App Service Tools v3.0.0

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27625.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.123.7408.1
Visual Studio Tools for Apache Cordova

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27703.2035
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.



Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by guardrex** [comment]
Good ... and since you installed 2.1 ... when you go to `%ProgramFiles%\dotnet\sdk`, you see the 2.1.301 SDK installed?

<img width="295" alt="capture" src="https://user-images.githubusercontent.com/1622880/42300577-bf86f6e6-7fd6-11e8-8187-b55d77f5d341.PNG">

**Comment by guardrex** [comment]
... and I guess you did check off the "Cross platforms and web dev workload" when installing, right?

**Comment by WayneSudol** [comment]
Hi Luke. Nope, it's 300 and 201.

As you can see,  2.1.300 was installed a few hours ago when i did a control panels -> programs --> change -> repair


Here's the verification.


[cid:3500e3cc-59a2-4a27-a5b5-42f8d28d846e]


[cid:d424c19a-c751-4d5f-bab1-926d8a74d000]


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by guardrex** [comment]
You'll want the 2.1.301 SDK. https://www.microsoft.com/net/download/windows ... top button on the left

**Comment by WayneSudol** [comment]
I Don't remember if i did that.


On the web page tutorial, there is a install sdk 2.1 link as a prerequsite. I did install from that as i didn't remember if i had installed it as an option from the original install.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by guardrex** [comment]
If you need to confirm workloads, you can call up the installer to check by going to **Tools** > **Get Tools and Features**.

**Comment by guardrex** [comment]
".NET Core cross-platform development" is all the way at the bottom under "Other Toolsets"

**Comment by WayneSudol** [comment]
Still no joy. All info below after install of 301 and reboot.


[cid:ab9c804d-b298-4eea-b957-9bb5757651ee]



Microsoft Visual Studio Professional 2017
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA369
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40608.0
Azure App Service Tools v3.0.0

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.27625.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Apache Cordova   15.123.7408.1
Visual Studio Tools for Apache Cordova

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27703.2035
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.


[cid:d5850796-2697-4289-8b60-a663a4fa5599]


[cid:dadba83a-c6b2-46b7-96c4-17c1b2097efb]




Sent from Outlook<http://aka.ms/weboutlook>


________________________________
