### ISSUE TITLE
Apply Core and netfx framework naming consistently across the repo

### ISSUE THREAD

**Issue by StingyJack** [aspnet/Docs#7455]
&gt; This article demonstrates migrating the database schema for ASP.NET apps using Membership authentication to ASP.NET Core 2.0 Identity.

&gt; Prior to ASP.NET 2.0, developers were tasked with creating the entire authentication and authorization process for their apps. With ASP.NET 2.0, Membership was introduced, providing a boilerplate solution to handling security within ASP.NET apps.

Is this talking about Asp.Net full framework 2.0, or is it referring to Asp.Net Core 2.0 and is just missing the word "core" in a few places?  I can never tell and it makes _so many_ articles result in confusion, consternation/profanity, 
and usually broken code at the end of the walkthrough. 

Can you please designate the full, non-classic, non-legacy, non-core, non-"standard", .net framework, aka "netfx" by something other than the omission of the word "core"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef1bf52a-1488-eb9b-9961-7843704d2717
* Version Independent ID: 1983fca0-2c10-a835-7a37-e67ad97793a1
* Content: [Migrate from ASP.NET Membership authentication to ASP.NET Core 2.0 Identity](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/membership-to-core-identity?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/proper-to-2x/membership-to-core-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/proper-to-2x/membership-to-core-identity.md)
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
> Is this talking about Asp.Net full framework 2.0, or is it referring to Asp.Net Core 2.0

It's referring to the old ASP.NET 2.0 full framework. The word "membership" has gone away in favor of "identity."

> just missing the word "core" in a few places

That is how it's distinguished. It's "ASP.NET" or "ASP.NET Core." Sometimes, you'll see "ASP.NET 4.x," which is more obvious.

**Comment by StingyJack** [comment]
The problem is not really about one singular article. The ask is to remove the general point of confusion from documentation.

**Comment by isaac2004** [comment]
@StingyJack curious if you have a preference here? In blog posts, docs, articles, books, and in training material there is ASP.NET and ASP.NET Core, so there is a lot of content that adheres to this convention, most not published by Microsoft.

**Comment by guardrex** [comment]
I took a look to see how consistent usage is and the results aren't very encouraging. Although in the majority of cases "ASP.NET Core" is used, I found perhaps 100-200 spots where docs say "ASP.NET" but are actually referring to "ASP.NET Core." I would like to at least improve the consistency of usage.

RE: "ASP.NET Full Framework" alongside "ASP.NET Core" ("ASP.NET" can refer to both if called for)

Seems like a reasonable suggestion. @Rick-Anderson @scottaddie Any interest in going that way?

**Comment by isaac2004** [comment]
Is it a matter of find and replace the docset? Also, ASP.NET 4.x does not work in some cases (this doc referenced is for 2.x)

**Comment by guardrex** [comment]
I assume you mean when not referring to a historical release (as @isaac2004 just said).

In that case, I'll swing thru and touch them up as "ASP.NET 4.x" and "ASP.NET Core."

> Is it a matter of find and replace the docset?

I gravely doubt it! ... That's probably not going to end well. lol

**Comment by scottaddie** [comment]
I agree there will be cases in which ASP.NET 4.x usage is awkward or doesn't work at all. We'll have to evaluate each case separately.

**Comment by guardrex** [comment]
✨ **_RexEx RegEx magic_**:tm: ✨ will help! :smile:

**Comment by isaac2004** [comment]
We had to do something similar in dotnet-docs. Pinging @mairaw as I think there was some tool that was used to detect things like this.

**Comment by Rick-Anderson** [comment]
> Can you please designate the full, non-classic, non-legacy, non-core, non-"standard", .net framework, aka "netfx" by something other than the omission of the word "core"?

Management has specifically rejected your proposal before Core was introduced.  We can however make sure we use Core consistently.

**Comment by guardrex** [comment]
@Rick-Anderson I was going to use this issue to track the work on consistency.

**Comment by Rick-Anderson** [comment]
@guardrex Rename the title

**Comment by StingyJack** [comment]
> Management has specifically rejected your proposal before Core was introduced. 

Naming is hard, and management would benefit from being less rigid, especially when it comes to to predicting my thoughts. =D

> We can however make sure we use Core consistently

I appreciate this very much as I'm starting to refer teammates to these.
