### ISSUE TITLE
Misspelled 'preceding'

### ISSUE THREAD

**Issue by dbiehle** [aspnet/Docs#7470]
_A production app would not call Database.Migrate. It's added to the **preceeding** code to prevent the following exception when Update-Database has not been run:_

Should be spelled **preceding**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with SQL Server LocalDB and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dbiehle  Thanks
