### ISSUE TITLE
Missing folder ~/lib/signalr/ in the tutorial code

### ISSUE THREAD

**Issue by benoityip** [aspnet/Docs#7480]
Missing folder ~/lib/signalr/ in the tutorial code, so when I run it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by rachelappel** [comment]
Hi @benoityip. Thanks for the question!
You're supposed to create that folder as part of the tutorial. 
Step 4 under Visual Studio or Step 3 under VS Code has this line:
"Create a new folder named "signalr" inside the lib folder in your project. Copy the signalr.js file from node_modules\@aspnet\signalr\dist\browser to this folder."
The lib folder is under wwwroot and is part of the VS new web app template.
