### ISSUE TITLE
Is the layout in Pages/Shared or Shared/Pages?

### ISSUE THREAD

**Issue by ddrewd** [aspnet/Docs#7482]
Both are entered here, in the section "Using Layouts, partials, templates, and Tag Helpers with Razor Pages"

> 
> The layout is in the Shared/Pages folder. Pages look for other views (layouts, templates, partials) hierarchically, starting in the same folder as the current page. A layout in the Shared/Pages folder can be used from any Razor page under the Pages folder.
> 
> The layout file should go in the Pages/Shared folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's a typo @ddrewd ... thanks for letting us know. I'll patch it up.
