### ISSUE TITLE
Add .gitattributes files to repos to normalize line endings

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#7485]
Hello 👋 - can you update the repo to address problems like [#577 from the VSTS docs repo](https://github.com/MicrosoftDocs/vsts-docs/pull/577) (proactive change here...)?  Thanks 🙏

Apparently, there is a fix here: [MSFT Docs Issue 362](https://github.com/MicrosoftDocs/feedback/issues/362#issuecomment-402889434)

**Comment by guardrex** [comment]
MicrosoftDocs/vsts-docs#577

**Comment by spottedmahn** [comment]
Thanks @guardrex.  I've fixed my original post...

**Comment by spottedmahn** [comment]
FYI, [.gitattributes contents are here](https://github.com/MicrosoftDocs/feedback/issues/362#issuecomment-403932911)

**Comment by cillroy** [comment]
I update issue 362 with our .gitattributes that is added to new repo's by default

**Comment by spottedmahn** [comment]
that's great, thanks for the follow through!
