### ISSUE TITLE
Error: 'DbContextOptionsBuilder' does not contain a definition for 'UseSqlite' 

### ISSUE THREAD

**Issue by dasoussan** [aspnet/Docs#7486]
After registering the database context when attempting to build, this error appears:

error CS1061: 'DbContextOptionsBuilder' does not contain a definition for 'UseSqlite' and no extension method 'UseSqlite' accepting a first argument of type 'DbContextOptionsBuilder' could be found (are you missing a using directive or an assembly reference?)

Searched a lot, installed SQLite from https://www.nuget.org/packages/System.Data.SQLite/ , tried searching, all without success. What am I missing? (or what is missing from the step-by-step instructions)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@dasoussan You're missing the following code at the top of your *Startup.cs* file:

```csharp
using Microsoft.EntityFrameworkCore;
```

**Comment by Smilebags** [comment]
I'm running into the same issue, but I have the above using statement.
Closing and re-opening VS Code removes the error but the build still fails with the same error CS1061
Something pretty funky is going on here.

**Comment by Smilebags** [comment]
Adding <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1"/> to a new ItemGroup in the csproj and then restoring seemed to resolve the issue.

**Comment by endian02** [comment]
I ran into the same issue today, while trying to follow the tutorial, but the comment from Smilebags seems to work for me too.. The tutorial should probably be updated.

**Comment by Rick-Anderson** [comment]
Wow, that's a really great error message. Add the right `using`

**Comment by armydee** [comment]
@Rick-Anderson Love the sarcasm..... 
![image](https://user-images.githubusercontent.com/7499037/46922436-027b9b80-d001-11e8-9d15-7294450823f5.png)

I restarted VS Code and the error was gone. Appreciate the help..... seriously. Thanks.

**Comment by tombradev** [comment]
> 
> 
> Adding `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1"/>` to a new ItemGroup in the csproj and then restoring seemed to resolve the issue.

Thank you, this solution works for me while following the MVCmovie VS CODE tutorial

**Comment by jangix** [comment]
Install-Package Microsoft.EntityFrameworkCore.InMemory

**Comment by courageDeveloper** [comment]
@Smilebags Kudos, That solved it

**Comment by malwareoverflow** [comment]
please check out my answer this is happening due to version https://stackoverflow.com/questions/43098065/entity-framework-core-dbcontextoptionsbuilder-does-not-contain-a-definition-f/56443050#56443050

**Comment by danilDelete** [comment]
Add `Microsoft.EntityFrameworkCore.SQLite` worked for me.

**Comment by LynneKirsch** [comment]
FYI, 2019, @Smilebags comment is still the solution. Thanks dude.

**Comment by mohammad-khoddami** [comment]
I just changed the Microsoft.EntityFrameworkCore.Sqlite version with NuGet package manager.

**Comment by oms064** [comment]
On the terminal I ran 'dotnet add package Microsoft.EntityFrameworkCore.Sqlite' and it worked for me.

**Comment by pinpoint-forest** [comment]
Is just missing Microsoft.EntityFrameworkCore.InMemory package

**Comment by dianejason** [comment]
add package Microsoft.EntityFrameworkCore.Sqlite

**Comment by Braath1** [comment]
@dasoussan Thank you! I have been trying for 3 days before I found your solution!

**Comment by Rick-Anderson** [comment]
That's in the tutorial
![image](https://user-images.githubusercontent.com/3605364/84075472-ecf27c80-a96f-11ea-91fd-4f7013d3f334.png)

**Comment by ayaanqui** [comment]
Adding the `Microsoft.EntityFrameworkCore.InMemory` package helped me with the issue.

> [https://stackoverflow.com/a/56684097/5834961](https://stackoverflow.com/a/56684097/5834961).

**Comment by Rick-Anderson** [comment]
That's in the tutorial
![image](https://user-images.githubusercontent.com/3605364/84075472-ecf27c80-a96f-11ea-91fd-4f7013d3f334.png)

**Comment by mPiotrek** [comment]
@scottaddie 
> ```cs
> using Microsoft.EntityFrameworkCore;
> ```

Indeed this line is missing from `Startup.cs` when one follows the [Razor Pages tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)

**Comment by mPiotrek** [comment]
Same error and same solution with the [MVC tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-5.0&tabs=visual-studio-code)

**Comment by Folasayo-Samuel** [comment]
> @dasoussan You're missing the following code at the top of your _Startup.cs_ file:
> 
> ```cs
> using Microsoft.EntityFrameworkCore;
> ```
> 
> I'll update this section of the tutorial to make the 2 required `using` statements more obvious.

using Microsoft.EntityFrameworkCore; namespace works for me. You can try it out. Thanks @Rick-Anderson @scottaddie

**Comment by Rick-Anderson** [comment]
@mskiptr  why are you following an old version (.NET 5) of the tutorial?

> Indeed this line is missing from Startup.cs when one follows the [Razor Pages tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-5.0&tabs=visual-studio-code)

**Comment by Ekaterina-Ryzhkova** [comment]
I have solved this problem by reinstall EntityFrameworkSqllite with the version below and rebuilding solution

**Comment by mskiptr** [comment]
> @mskiptr why are you following an old version (.NET 5) of the tutorial?

That was the one our lecturer linked and I guess it wasn't immediately obvious to me a newer version is available.

**Comment by mskiptr** [comment]
@Rick-Anderson Sorry for not following up until now.

> @mskiptr why are you following an old version (.NET 5) of the tutorial?

That was the one our lecturer linked and I guess it wasn't immediately obvious to me a newer version is available. Maybe a warning about newer tutorial version could help in situation like that.

Still, updating links is the proper solution so 'not really your bug' then.
