### ISSUE TITLE
More information on handling Errors

### ISSUE THREAD

**Issue by chadAtGA** [aspnet/Docs#7494]
Where do I find more information on handling errors and configuration of the java script client? I want to be able to set the keepalive, retry, etc as well as determine when the connection has disconnected so I can try to reconnect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#related-resources)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by scottaddie** [comment]
Paging @BrennanConroy and @anurse

**Comment by BrennanConroy** [comment]
We have a doc on [configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1#configure-client-options). Do note that some options are different between the JS and .NET clients.

**Comment by chadAtGA** [comment]
I think I got it using this and the code but a sample showing how to reconnect after the connection is closed unexpectedly would be nice. I assume most people have to handle that

On Jul 6, 2018, at 1:28 PM, Scott Addie <notifications@github.com<mailto:notifications@github.com>> wrote:


@chadAtGA<https://github.com/chadAtGA> Does this doc answer your questions? If not, what questions remain?

**Comment by scottaddie** [comment]
@BrennanConroy Do you have anything demonstrating reconnecting after the connection is unexpectedly closed?

**Comment by chadAtGA** [comment]
Here is what I did let me know if you have anything better

`this.hub.onclose(function (error) {
			console.log("lost hub connection trying to reconnect");
			var intervalId = setInterval(function () {

				if (this.hub.connection.connectionState == 2) { //disconnected
					this.metisHub.start().catch(err => console.error(err.toString()));
				}
				
				if (this.hub.connection.connectionState == 1) { //connected
					clearInterval(intervalId);
				}
			}.bind(this), 3000);
			
`

**Comment by BrennanConroy** [comment]
@chadAtGA Accessing `connection.connectionState` is not supported, those are "private" properties.

Here is a nice simple example of reconnect logic: https://github.com/davidfowl/UT3/blob/fb12e182d42d2a5a902c1979ea0e91b66fe60607/UTT/wwwroot/js/utt.js#L140

**Comment by anurse** [comment]
#6757 is tracking adding a sample of this kind of reconnection logic.
