### ISSUE TITLE
Enabling Social Logins

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#75]
ASP.NET 5->Security->Enabling Social Logins

**Comment by rustd** [comment]
Please base it on the following sample http://www.asp.net/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on
Following is the outline to use:

* Creating ASP.NET 5 Web Site
* Setting up SSL in the Project
* Creating a Google app for OAuth 2 and connecting the app to the project
* Creating the app in Facebook and connecting the app to the project
* Use the Secret Manager to add the keys for Facebook & Google
* Login with Facebook
* Show that there is no password and you can create one if needed
* Associate with Google Account
* Publish to Azure Web App
* Set the Facebook/ Google Keys in the portal in AppSettings
* Update the Facebook App with the new URLs

**Comment by danroth27** [comment]
@rustd Can this issue now be closed?

**Comment by rustd** [comment]
yes
