### ISSUE TITLE
ReleaseDate format in Movie.cs

### ISSUE THREAD

**Issue by apalix** [aspnet/Docs#7510]
My website displayed the date in mm/dd/yyyy hh:mm format when I wanted only the date. After a lot of research, I found the solution by adding the following
using System.ComponentModel.DataAnnotations;

Then in the class:
 [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime ReleaseDate { get; set; }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@apalix  the tutorial shows how to do this.
