### ISSUE TITLE
Razor page Tutorial doesn't tell user to install the SQLite provider

### ISSUE THREAD

**Issue by define-private-public** [aspnet/Docs#7516]
I was trying to run through the tutorial here: https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md

And got to the portion where it tells me I need to add this to my code:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<MovieContext>(options =>
        options.UseSqlite(Configuration.GetConnectionString("MovieContext")));
    services.AddMvc();
}
```
No where in the document did it tell me that I need to add in `Microsoft.EntityFrameworkCore.Sqlite` as a project dependency.  As a newcomer to .NET core/ASP.NET/Razor Pages, etc, this was really confusing and a pain to figure out how to get the `UseSqlite()` function.  Maybe this page should be linked in the document somewhere:

https://docs.microsoft.com/en-us/ef/core/providers/sqlite/

**Comment by guardrex** [comment]
Dup of #6938 

@define-private-public Thanks for commenting. @Rick-Anderson has that one marked for this sprint, so it should be addressed shortly.

**Comment by CaptainBlain** [comment]
For anyone else follwoing the latest tutorial. I had to use the following

`// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            //var connectionString = Configuration.GetConnectionString("MovieContext");

            services.AddEntityFrameworkSqlite().AddDbContext<MovieContext>(options => options.UseSqlServer(Configuration.GetConnectionString("MovieContext")));
            //services.AddDbContext<MovieContext>(options => options.UseSqlServer(Configuration.GetConnectionString("MovieContext")));

        }
`
