### ISSUE TITLE
Enabling startup logging in stdout should be covered (or linked)

### ISSUE THREAD

**Issue by laazik** [aspnet/Docs#7517]
I had some seriously hard times trying to figure out how to get the logs emitted in the Startup class to appear anywhere.

Using the default .net core 2 approach to web apps and deployments, the web.config file is autogenerated. And this specifically turns off the stdoutLogEnabled logging, which after some thought makes a lot of sense.

First problem for me is that this is covered under troubleshooting, but to me this is not a troubleshooting problem, but seeing/accessing the log statements problem. I never really thought about looking into the troubleshooting instead of the logging documentation.

Second problem is that logs from the Startup (or events) do not appear anywhere, and it was only I randomly stepped onto the blogpost, which explained that turn on the stdoutLogEnabled to get access to those statements.

I would definitely recommend to cover this aspect of the Startup here, even as a link to actual troubleshooting documentation, under the Azure logging parts. It would have saved me at least several days of trying to figure out why the log statements do not appear anywhere.

There is very good explanation of the whole thing in the documentation here https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/troubleshoot?view=aspnetcore-2.1

Perhaps the same information would make sense in "Handle errors" sections as well, as I recall looking there, but the problem was my whole service was crashing before Kestrel came up, so obviously wasn't able to get any information out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @laazik. Thanks for commenting.

The underlying reason is that the docs are somewhat compartmentalized according to the API. The logging topic is focused on *application logging* available via the Logging API and logging providers that load *when the app successfully starts*. Therefore, we don't cover the stdout logging in the Logging topic. It's treated a different API/layer. What we can do is link at very top of the Logging topic over to the stdout logging information for both IIS and Azure for troubleshooting app startup issues. That should get cats over to the right spot.

RE: Handle errors topic

https://docs.microsoft.com/aspnet/core/fundamentals/error-handling#startup-exception-handling

> When running on IIS or IIS Express, a *502.5 Process Failure* is returned by the ASP.NET Core Module if the process can't be started. Follow the troubleshooting advice in the *Troubleshoot ASP.NET Core on IIS* topic.

... almost covers it. I don't like that the Azure Troubleshooting link is only down in the *Additional resources* section, and a brief shout out to the stdout log might be a good add here. Certainly, I'd like that Azure troubleshooting link in the *Startup exception handling* section.

**Comment by guardrex** [comment]
I think I see why I don't have that additional link to the Azure troubleshooting topic. When one goes to the Troubleshoot on IIS topic, there's a list of other resources at the top. One of those links is over to the Azure topic.

**Comment by laazik** [comment]
As a side note, I was actually injecting the configured ILoggerFactory in the initial Startup method, as I'm usually accustomed to initialise the common logging system as really the first thing in the application (if there is a need for automated log processing etc. it's pretty convenient to have a common way how to emit information from the app). I can definitely see the merit in App initialised and running part.

Also it did not really seem to be a "troubleshooting IIS" issue, as I knew that something in the code itself must have been broken and it wasn't really related to actual hosting/IIS integration layer.

To give a bit context, my use case was initialisation of the keys from key vault as part of the configuration bootstrapping, which then are later used in configuring the auth providers, all which is happening in the starting up phase and it had some rights issues. Obviously everything was working pretty correctly in the local env, where the console is available and also in Azure from the controllers, so made me wonder really hard, why I wasn't able to get anything out anywhere in production.

Also, after I found the right place to look into, it was actually very straightforward after that to get it working and the documentation itself is really good. So this ended up to be mainly about the search engine query and finding the right place to look info from 🤓.
