### ISSUE TITLE
Pages/Account folder

### ISSUE THREAD

**Issue by paul000** [aspnet/Docs#7521]
In the Account Confirmation and Password Recovery section the code sample is supposed to be in the Pages/Account folder, but I've created this project a couple of times and no Account folder was ever created. Did I miss something or are we supposed to add the folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=aspnetcore2x#enable-account-confirmation-and-password-recovery)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The UI is created by a Razor Class Library now, but you can scaffold the UI into a project if you need to. See ...

* https://docs.microsoft.com/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-authentication-code
* https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio

**Comment by paul000** [comment]
Thank you.
