### ISSUE TITLE
Consider splitting up the samples repository

### ISSUE THREAD

**Issue by phatcher** [aspnet/Docs#7524]
Having to download ~800Mb just to have a look at one particular sample can be problematic 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c461e1d-5771-20f9-c9b3-ac4ee7661ee0
* Version Independent ID: e06d8e48-cee4-0c0c-39aa-97abe228c370
* Content: [ASP.NET Core tutorials](https://docs.microsoft.com/en-us/aspnet/core/tutorials/index?view=aspnetcore-2.1#how-to-download-a-sample)
* Content Source: [aspnetcore/tutorials/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @phatcher Thanks for commenting. The doc engineers are working on a solution for this now. See: https://github.com/aspnet/Docs/issues/6991#issuecomment-398104010
