### ISSUE TITLE
.Net Type DateTime correlates to input type="datetime-local"

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/Docs#7531]
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.1#the-input-tag-helper
In the table corelating .net type to input type it states
DateTime type=”datetime”

And it should state DateTime correlates to type="datetime-local"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@StevenTCramer  thanks, we'll address this in the next doc review.

**Comment by dpaquette** [comment]
@Rick-Anderson  There is such a thing: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

and it is used by the Input Tag helper when binding to DateTime properties:
https://github.com/aspnet/AspNetCore/blob/321327f84b2b22dcff2e9beb06a9a64236c5cced/src/Mvc/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs#L34

I think this should be re-opened. I agree with @StevenTCramer that the docs are not correct.
