### ISSUE TITLE
Not providing a version for Microsoft.AspNetCore.App results in a package version error

### ISSUE THREAD

**Issue by cocowalla** [aspnet/Docs#7532]
See [here](https://github.com/aspnet/Home/issues/3250) for a related Github issue.

It would be nice to update these docs and/or fix the problem, to stop others falling into a pit of despair after following this advice to migrate to 2.1

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabe9331-b438-fabe-18ca-15f752ec6778
* Version Independent ID: 3294609f-b881-1fec-de04-2021b48de489
* Content: [Microsoft.AspNetCore.App metapackage for ASP.NET Core 2.1 and later](https://docs.microsoft.com/en-gb/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/metapackage-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/metapackage-app.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
They're reversing course on this for 2.1.3. Let's use this issue to track the work.

https://github.com/aspnet/Home/issues/3292

@Rick-Anderson They're fixing package resolution, and there's nothing wrong with us going ahead with documenting the change now. Thoughts?

**Comment by scottaddie** [comment]
@guardrex My recommendation is to add the `Version` attribute back to each sample app's project file. That's the direction the product unit is headed, so we should get out ahead of it.

**Comment by guardrex** [comment]
Yes, I was just waiting on @Rick-Anderson approval. I'll take care of this today.
