### ISSUE TITLE
How can something be so fantastically useless

### ISSUE THREAD

**Issue by jkenny6** [aspnet/Docs#7533]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @jkenny6 ... We need a bit more to go on than that. If you'll be more specific, we can probably address your concerns. Please don't use the docs repo for rants.
