### ISSUE TITLE
Why aren't the other methods async? (the one that gets the data)

### ISSUE THREAD

**Issue by jintux** [aspnet/Docs#7536]
https://github.com/aspnet/Docs/blob/8b3f48d530e41a0dfbe59d35cde5bcf2744ac8de/aspnetcore/web-api/define-controller/samples/WebApiSample.DataAccess/Repositories/PetsRepository.cs#L59

**Comment by scottaddie** [comment]
@jintux No reason in particular, but they probably should be. I'll covert them to async today.
