### ISSUE TITLE
Getting started without tooling

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Docs#754]
I've noticed a few issues for newcomers to the .NET and ASP.NET world in the documentation.

The main issue is that a lot of it is centered around the convenience of being able to just hit *file->new* and then have an entire project scaffolded out.  These walkthroughs are okay, but I think it's easy to see that they end up focusing more on the tooling than the actual technology itself.  This is especially evident when Visual Studio is the environment.

Something I've been doing to study ASP.NET is create a new **empty** project and then add in MVC and some basic error handling and routes.  This has been extremely helpful in learning my first batch of ASP.NET APIs.  The difference in this case compared to just being given a fully built out project is that it's helped me understand the boundaries of the environment and frameworks.

When someone clicks to obtain introductory documentation, the idea of just having some scaffolding wizards ratchets up the complexity.  In my case, I end up overwhelmed trying to understand the stack that was assembled for me.  The scaffolding and wizard tools certainly do have their place, but I'm wondering if there should be a *"guide you through your first project"* link that most people end up at after downloading.

Most useful for me so far has been to:

 - Look at `project.json`
 - Look at `Startup.cs`, see that it's empty
 - Try adding MVC to `Startup.cs`
 - Learn about the router
   - What's `name`?
   - What's `template`?
   - What's `defaults`?
 - Create a first controller, action and route.  Nothing too fancy though, just point to a single controller using string names
 - Return `Content("ASP.NET!")` from the controller
 - Add environment detection and set up `BrowserLink` and `DeveloperExceptionPage`

That could easily conclude the first tutorial which should leave ANYONE confident in just building simple controller flows.  Very focused and very low overhead.
As a first encounter document, it won't drop someone right in the deep end of a fully scaffolded EF7, identity project.  Most importantly, an amount of effort will have been made to emphasize the routing layer.

I know a lot of work has been done already to describe what I'm talking about here, but the key differentiator is the presentation and intention of the doc which is to say *"here's how we see things working"*

Anyway, just had this brain dump, figured I should write it before I forgot.

**Comment by danroth27** [comment]
The focus has been on helping folks get started and be productive with the help of the tooling.

We should consider having a simple getting started doc that doesn't require any tooling. Ex http://expressjs.com/en/starter/hello-world.html.

**Comment by danroth27** [comment]
See https://docs.asp.net/en/latest/getting-started.html
