### ISSUE TITLE
Change return to await

### ISSUE THREAD

**Issue by charinirao** [aspnet/Docs#7545]
In the following lines - change return to await. 

            // Call the next delegate/middleware in the pipeline
            return this._next(context);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I got it Rick if you want ... I was just patching it.

**Comment by Rick-Anderson** [comment]
@guardrex  OK, I'll close my PR

**Comment by guardrex** [comment]
Nah ... that's ok. I'll review it.

**Comment by Rick-Anderson** [comment]
@charinirao  thanks for pointing this out, it's fixed now.
