### ISSUE TITLE
Add note that IConfiguration.Bind extension method requires specific nuget package

### ISSUE THREAD

**Issue by d-dizhevsky** [aspnet/Docs#7548]
Consider making doc explicitly saying that IConfiguration extension methods are shipped within specific Nuget package `Microsoft.Extensions.Configuration.Binder` somewhere outside of the code blocks (perhaps `[!NOTE]` section would be enough?). Personally, I think that such note sections were designed exactly to attract user's attention, whereas comments in code samples are going to be ignored 9/10 times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration#feedback)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@d-dizhevsky  yes,  `[!NOTE]` sections were designed for that but we find most programmers pay more attention to the code.

**Comment by guardrex** [comment]
I'll see what I can do with this when I get to the Configuration overhaul issue. Thanks for commenting @d-dizhevsky.

**Comment by guardrex** [comment]
https://github.com/aspnet/Docs/issues/7557#issuecomment-404160776
