### ISSUE TITLE
Hide/Collapse Menu Usability Feature Request

### ISSUE THREAD

**Issue by mattferderer** [aspnet/Docs#7549]
When reading the documentation, going through a tutorial especially, it would be nice to hide or collapse the menu on the left. It makes it easier to read, especially when increasing the font size.

Since you're using JQuery & have the layout setup nicely, it is easy for a developer reading it to just do `$('#sidebar').hide()` and `$('#sidebar').show()` so it's not a huge deal.

**Comment by guardrex** [comment]
I recommend closing here and opening over at https://github.com/MicrosoftDocs/feedback. We're just a slice here of the big MS docs pie and have no direct control over this type of scenario.

**Comment by mattferderer** [comment]
Thanks. Added to https://github.com/MicrosoftDocs/feedback/issues/503
