### ISSUE TITLE
Replace Instance with another Singleton overload in fundamentals/dependency-injection

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#755]
update the Service Lifetimes and Registration Options section in http://docs.asp.net/en/latest/fundamentals/dependency-injection.html to remove the mentions of "Instance" because it's not (and never was) a concept of its own.

**Comment by ardalis** [comment]
This change should be made once RC2 ships.

**Comment by danroth27** [comment]
@ardalis I see you marked this as Done. Should this issue now be closed?
