### ISSUE TITLE
How to access RCL without areas

### ISSUE THREAD

**Issue by A-Gaston** [aspnet/Docs#7550]
I don't use Areas in my web apps, so I had to move RazorUIClassLib/Areas/MyFeature/Pages to RazorUIClassLib/Pages to have global access to my razor views. This is important because all of our web apps share common headers, footers, and other pages and none of them have areas. I think the inclusion of areas over-complicates the example code and I also wanted to post for any other folks who might employ the same tactics as I do.

So instead of navigating to /MyFeature/Page1, I can just navigate to /Page1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You don't need to use Areas in your web app and you don't need  to remove the Razor class lib area for your app to work correctly.

**Comment by A-Gaston** [comment]
In order for it to work how I expected it to work, I absolutely had to remove the area. I put my header and footer partials in the class lib, then tried to add them as partials to my _Layout.cshtml file in my webapp. This didn't work until I moved them out of the area in the class lib. Sure, razor pages within the class lib could find each other no problem. Definitely had me scratching my head for a while.

**Comment by Rick-Anderson** [comment]
@pranavkm please comment.

**Comment by pranavkm** [comment]
For 2.1.0, we didn't have a very good idea on how users would use re-usable class libraries. Our guess was that we'd more commonly see users building "isolated" components - the way IdentityUI works while the app provides the mesh (Layout \ headers & footers \ css). This led us to producing a template \ writing docs that use an area by default <sup>[1]</sup>.

There's clearly also room for the sort of thing you're trying to do - a UI library that provides common UI components (layout \ themes etc) which the app consumes. This would require having the cshtml files located in the root of the app (`/Pages` or `/Views/Shared`). Perhaps a subsection in the doc that talks about how you should organize your files to achieve either ends would suffice here?

----------------------------
<sup>[1]</sup> - There was also the issue that we hadn't solved the problem detailed here - https://github.com/aspnet/Mvc/issues/7608 - with `RazorPagesOptions.RootDirectory`.

**Comment by A-Gaston** [comment]
@pranavkm I think that would be helpful and I can see the thought process. How can I help?

Thanks @Rick-Anderson and @pranavkm for the quick replies.

**Comment by Rick-Anderson** [comment]
@A-Gaston  Select edit on  [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md) and create a PR. Mention me and @pranavkm  to review the PR.

![image](https://user-images.githubusercontent.com/3605364/42582622-e1feab68-84ec-11e8-9a72-c38441476b63.png)
