### ISSUE TITLE
minor : json formatting in 'Settings file configuration'

### ISSUE THREAD

**Issue by mishal153** [aspnet/Docs#7553]
the json is not showing up as formatted in '[Settings file configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#settings-file-configuration)'. it shows formatted in another example on the same page ['Log filtering' ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#log-filtering)

**Comment by guardrex** [comment]
Hello @mishal153 ... there's an issue in the documentation build system. In places where we use our markdown feature for versioning, it flattens our code blocks (removes the indentation). It's being tracked internally, so I'll close this.

cc/ @scottaddie
