### ISSUE TITLE
How to quickly download partial sample code?

### ISSUE THREAD

**Issue by reponemec** [aspnet/Docs#7555]
I would like to download sample code from https://github.com/aspnet/Docs/tree/live/aspnetcore/security/gdpr/sample. One way is to navigate to https://github.com/aspnet/Docs/tree/live and download the 836MB whole Docs-live.zip. It is too tedious. Is there any simpler way here?

**Comment by guardrex** [comment]
Hello @reponemec ... Unfortunately, there isn't a way ... *YET*. The documentation engineers are working on a fix for this so that individual samples can be downloaded. https://github.com/aspnet/Docs/issues/6991#issuecomment-398104010 The work is being tracked internally, so I'll close this.
