### ISSUE TITLE
get appSettings.json's  GetSection

### ISSUE THREAD

**Issue by Thehardtimesofbeans** [aspnet/Docs#7557]
I looked at the "https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?tabs=basicconfiguration&view=aspnetcore-2.1".
Get appSettings.json's GetSection .
can use "var appConfig = config.GetSection("App").Get<AppSettings>();" get
{
  "App": {
    "Profile": {
      "Machine": "Rick"
    },
    "Connection": {
      "Value": "connectionstring"
    },
    "Window": {
      "Height": "11",
      "Width": "11"
    }
  }
}.
but  I find must use _config.GetSection(" #App:Profile:Machine"). 
can't  get clase  by GetSection("App").Get<AppSettings>() .
please help me ,thanks

**Comment by d-dizhevsky** [comment]
This is the same issue I raised yesterday, see https://github.com/aspnet/Docs/issues/7548
To get this work do `dotnet add package Microsoft.Extensions.Configuration.Binder`

**Comment by guardrex** [comment]
Let's consider all of the possibilities. As we do for many tutorials, we should consider having a *Prerequisites* section at the tops of our reference topics. We can say in that section what these scenarios require ... e.g., a package reference.

**Comment by guardrex** [comment]
I'm not closing this as a dup (just yet anyway). We don't quite document grabbing the section first. We document grabbing the section and immediately binding. I want to leave this open as a reminder to take a look at how we cover binding to a configuration class.

```csharp
var appConfig = new AppSettings();
config.GetSection("App").Bind(appConfig);
```

I'll take a second look when I get to that issue.
