### ISSUE TITLE
upgrade to @angular latest

### ISSUE THREAD

**Issue by crh225** [aspnet/Docs#7559]
This project is outdated. Can you upgrade to angular 6?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Closing, as the Angular 6 upgrade is a templating issue. See https://github.com/aspnet/Templating/issues/573 for the status of it. Looks to me like this will ship with the upcoming 2.2.0 Preview 1 release.
