### ISSUE TITLE
Migrate Identity ConfigureServices to 2.1: add before/after code, example with services.AddIdentity<TUser, TRole> migration

### ISSUE THREAD

**Issue by pholly** [aspnet/Docs#7561]
It would be helpful to have before and after code for the `ConfigureServices` Identity changes.

I didn't realize I should change `services.AddIdentity` to `services.AddDefaultIdentity`. That change is very important because it eventually calls `AddDefaultUI` which does some important setting up of the Identity Area, like adding authorization to /Identity/Account/Manage pages.

It would also be helpful to show how to migrate `services.AddIdentity` overloads. Specifically, I ran into a problem where I had:

```c#
services.AddIdentity<ApplicationUser, IdentityRole>(options => ...)
.AddEntityFrameworkStores<ApplicationDbContext>()
...
```

There's no `services.AddDefaultIdentity` overload for `TRole`. When I used the regular `services.AddDefaultIdentity<ApplicationUser>` I got dependency injection exceptions because `RoleManager<IdentityRole>` was not registered.

Looking at the default IU sample (https://github.com/aspnet/Identity/blob/master/samples/IdentitySample.DefaultUI/Startup.cs) led me to change my code to 

```c#
services.AddDefaultIdentity<ApplicationUser>(options => ...)
.AddRoles<IdentityRole>() //MUST come before AddEntityFrameworkStores
.AddEntityFrameworkStores<ApplicationDbContext>()...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  Should I add a section:

**Migrating AddIdentity overloads**

@pholly  can you provide the before/after code?

**Comment by pholly** [comment]
@Rick-Anderson AddIdentity overloads may not need its own section - I updated your suggested changes in your pull request https://github.com/aspnet/Docs/pull/7562 .

**Comment by HaoK** [comment]
So apps shouldn't need to change their identity code when they migrate to 2.1, switching to DefaultUI is not required, its probably better to just recommend adding a call to AddDefaultUI if they want to start using that as opposed to switching to the AddDefaultIdentity which isn't meant to be the replacement for AddIdentity or AddIdentityCore

**Comment by HaoK** [comment]
AddDefaultIdentity is targeted at making the intial template code simplier, its not meant to be the replacement for AddIdentity/Core

**Comment by Rick-Anderson** [comment]
@HaoK  Currently I have
The default 2.1 Identity UI doesn't currently provide significant new features over the 2.0 version. Replacing Identity with the RCL package is optional.
...

If you've made non-trivial changes to the template generated Identity code:

The preceding advantages may not justify converting to the the RCL version.
You can keep your ASP.NET Core 2.0 Identity code, it's fully supported.

I'll find a way to repeat or point to that section.

**Comment by HaoK** [comment]
Yeah we just need to make it very clear that they shouldn't replace existing identity configuration with AddDefaultIdentity, it most likely will break their app.

**Comment by pholly** [comment]
I know this was just closed, but somewhere it should be stated that AddDefaultUI provisions the Identity Area, most notably adding authorization to /Identity/Account/Manage and /Identity/Account/LogOff. Developers migrating from Identity 2.0 MVC, where the whole ManageController had authorization, after scaffolding Identity or using the built-in compiled views will not have the new Manage pages authorized unless they manually add the auth code, as in https://github.com/aspnet/Identity/blob/c7276ce2f76312ddd7fccad6e399da96b9f6fae1/test/WebSites/Identity.DefaultUI.WebSite/NoIdentityStartup.cs#L33 .
