### ISSUE TITLE
dotnet publish is not constructing the msdeploy command correctly

### ISSUE THREAD

**Issue by davidsk** [aspnet/Docs#7563]
Specifying replace rules in a publish profile causes the build to fail.  It appears that dotnet publish is not constructing the command line properly, specifically it's leaving the match and replace values blank:

```
...
Task Parameter:
  ReplaceRuleItems=
    replaceFullPath
      Match=C:\\dev\\Test Projects\\MsDeployReplaceRuleTest\\bin\\Debug\\netcoreapp2\.1
      Replace=Files (TaskId:90)
      ...
  Running msdeploy.exe. (TaskId:90)
  "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:manifest='C:\dev\Test Projects\MsDeployReplaceRuleTest\bin\Debug\netcoreapp2.1\MsDeployReplaceRuleTest.SourceManifest.xml' -dest:Package='C:\dev\Test Projects\MsDeployReplaceRuleTest\bin\Debug\netcoreapp2.1\MsDeployReplaceRuleTest.zip' -verb:sync -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -replace:match,replace -declareParamFile:"C:\dev\Test Projects\MsDeployReplaceRuleTest\bin\Debug\netcoreapp2.1\MsDeployReplaceRuleTest.Parameters.xml" -retryAttempts=2 (TaskId:90)
...
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Andrew-MSFT  @guardrex  should this issue be moved?

@davidsk  *Specifying replace rules in a publish profile* is outside the scope of this article.

**Comment by guardrex** [comment]
Those `ReplaceRuleItems` bits are over in Web Sdk ... @davidsk, I recommend moving this over to [aspnet/websdk issues](https://github.com/aspnet/websdk/issues).

**Comment by davidsk** [comment]
Done. [https://github.com/aspnet/websdk/issues/383](https://github.com/aspnet/websdk/issues/383).

@Rick-Anderson Can you clarify the difference between the product and content feedback buttons?  I opened this using the product feedback as it's not an issue with the content...

**Comment by guardrex** [comment]
We get issues where I'm wondering why the reader didn't click the 'product feedback' button ... *They may have done so!*

I have a *wild and crazy idea* ... brb ... I'm going to click that product feedback button and see what happens.

**Comment by guardrex** [comment]
Glad u said something @davidsk ... I think readers click it ... get the 404 ... 'Oh, well! 😞 I'll try the other one.'

**Comment by davidsk** [comment]
@guardrex It didn't 404 for me, worked like a charm...

**Comment by guardrex** [comment]
@davidsk What's the link it points to when you rollover the "Product Feedback" button?

**Comment by davidsk** [comment]
My mistake, it does 404.  I distinctly remember thinking that I was reporting product feedback, not content, and that was the correct button to push...

I think I misread the other button as "sign in to give feedback"...

**Comment by guardrex** [comment]
@Rick-Anderson opened an internal issue for investigation.

Since your main issue :point_up: is open over at https://github.com/aspnet/websdk/issues/383, I think you can close here. If you get an answer that seems actionable for docs, then ping us back over here. We can re-open this if needed.

**Comment by davidsk** [comment]
Sure.  Thanks for taking the time.
