### ISSUE TITLE
The Visual Studio Instructions is missing I step....I think

### ISSUE THREAD

**Issue by davidleedom** [aspnet/Docs#7564]
It seems the visual studio instructions is missing a section called:

Replace the markup in RazorUIClassLib/Areas/MyFeature/Pages/Page1.cshtml with the following code:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@davidleedom  thanks for pointing this out.  I'll get it fixed in the next couple of days.
