### ISSUE TITLE
Another inconsistency with Tutorial 

### ISSUE THREAD

**Issue by MichaelVaughnGraber** [aspnet/Docs#7566]
When selecting the project template ASP.NET Core 2.1 > Web Application  the check box labeled "Configure for HTTPS" is not available. 
[errataOnGetStartedWithRazorPagesInASPNETCore.docx](https://github.com/aspnet/Docs/files/2185756/errataOnGetStartedWithRazorPagesInASPNETCore.docx)
[errataOnGetStartedWithRazorPagesInASPNETCore.docx](https://github.com/aspnet/Docs/files/2185760/errataOnGetStartedWithRazorPagesInASPNETCore.docx)

**Comment by Rick-Anderson** [comment]
@MichaelVaughnGraber  you need the current VS and .NET Core SDK 2.1
