### ISSUE TITLE
Call to GDPR functionality appear to be removed from demo

### ISSUE THREAD

**Issue by MikeHowellTransferenceLtdCoUk** [aspnet/Docs#7569]
Starting the demo on VS 2017 15.7.3 I can't find any calls to generate the consent request for GDPR compliance.  Your links to the articles on this subject (https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1) would appear to indicate that some of the contents of ConfigureServices have changed or am I using an out-of-date version of VS 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MikeHowellTransferenceLtdCoUk  per the tutorial
Prerequisites
Visual Studio 2017 version 15.7.3 or later with the following workloads:

ASP.NET and web development
.NET Core cross-platform development
.NET Core 2.1 SDK or later
