### ISSUE TITLE
Need a walkthrough of EF/DB to Azure

### ISSUE THREAD

**Issue by vkichline** [aspnet/Docs#757]
Examples that publish DNX to Azure do not include databases, and examples that include databases do not include publishing to Azure.
An ideal example would be a Starter app with authentication, published to Azure.

**Comment by danroth27** [comment]
@sayedihashimi @rowanmiller what's the guidance on when we should document this scenario? Is the DB publishing support still if flux?

**Comment by rowanmiller** [comment]
Yes, still very much in flux. We should have proper support in RC2 (i.e. integration into the publish dialog).

**Comment by danroth27** [comment]
Our existing getting started article covers publishing the starter web app to Azure: https://docs.asp.net/en/latest/tutorials/your-first-aspnet-application.html
