### ISSUE TITLE
What Schedule class?

### ISSUE THREAD

**Issue by MikeHowellTransferenceLtdCoUk** [aspnet/Docs#7570]
You don't seem to have defined the Schedule class or have I read over things too fast?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MikeHowellTransferenceLtdCoUk  why do you need a schedule class?

**Comment by Rick-Anderson** [comment]
@guardrex  is this your file uploads code?

**Comment by Rick-Anderson** [comment]
@guardrex  make a copy of the file or something. You can't break this tutorial for the file uploads. It's clearly broken.

**Comment by Rick-Anderson** [comment]
@guardrex  I import that file - it breaks the tutorial.

**Comment by Rick-Anderson** [comment]
@guardrex  I don't want the final bits to have file upload code in it. They should be able to download the final project and have a working app without uploads. Uploads should be a different topic not part of this series.

**Comment by guardrex** [comment]
I see. That's cool. I'll move it to the RP area as a separate topic. I'll do it without a dedicated sample app tho just so that we can get beyond this issue quickly.

**Comment by Rick-Anderson** [comment]
Fixed by #7574 

@MikeHowellTransferenceLtdCoUk  thanks for reporting this.
