### ISSUE TITLE
Can't get dotnet to work

### ISSUE THREAD

**Issue by MikeHowellTransferenceLtdCoUk** [aspnet/Docs#7571]
I have tried the normal and VS command prompt to try the dotnet command (being bored with the ridiculously misnamed package manager console promp, come on, its just powershell inside VS)  You do not set any sort of project context so how can the command know what project to apply itself to.   If typed in as is in your tutorial or if I append the --project and give it a c:...... etc. path to my csproj file (the Microsoft documentation unhelpfully says supply --project with path to webapp(what?????) I simply get "no executable found matching command "dotnet-ef".  Is dotnet-ef an executable called by dotnet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MikeHowellTransferenceLtdCoUk  Per the instructions you need to be in the project directory. `dotnet` looks for a .csproj file in the current directory.
You also need the current 2.1 SDK.
