### ISSUE TITLE
Review comments in SignalR AuthN/AuthZ and Security Concepts  PR

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#7579]
Review comments in https://github.com/aspnet/Docs/pull/7312 and update based on comments.

**Comment by tdykstra** [comment]
>Review comments in #7312 and update based on comments.

I went through the comments and didn't find anything significant that wasn't addressed.  There's a discussion about the ToC and a suggestion wasn't adopted, but what we ended up with seems better to me than the alternative that was proposed.
