### ISSUE TITLE
Microsoft.Extensions.Configuration.FileExtensions is needed use SetBasePath()

### ISSUE THREAD

**Issue by andrewliang** [aspnet/Docs#7580]
It would be helpful to include what nuget packages are needed to execute the snippets. For example, to use SetBasePath(),  the Microsoft.Extensions.Configuration.FileExtensions nuget is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @andrewliang ... We have a list of things to address on a configuration overhaul. I'll add this to the tracking issue.

**Comment by Rick-Anderson** [comment]
@andrewliang @guardrex  We generally don't list each package for each API.  M.A.App includes the right package. Listing the package for the API would be a great feature for the [.NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.0) 

cc/ @dend
