### ISSUE TITLE
Development Mode Error

### ISSUE THREAD

**Issue by donalatorre** [aspnet/Docs#7581]
I followed this tutorial. It worked fine in the local host. When I deployed it in my azure website, I obviously changed the reply url to the public link. So I was able to select an account, enter password, and allow the permissions, but then I got this error:

An error occurred while processing your request.
Request ID: 0HLF7H4694HLM:00000006 
Development Mode
Swapping to Development environment will display more detailed information about the error that occurred. 
Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application. 

I changed the environment mode to Production in my App, same error. I'm starting to suspect it has to do with something else. Any help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/troubleshoot?view=aspnetcore-2.1

And try setting the ASPNETCORE_ENVIRONMENT environment variable to Development,

**Comment by donalatorre** [comment]
Thank you for your quick response, Rick. This link did not have the answer, however, I was able to solve it. Turns out, when you deploy your web app, you must go to the appsettings.json file, and replace the "DefaultConnection" from "ConnectionStrings" with a server key generated in azure or some other database service. Indeed the log is misleading, since when the app is deployed, it is in Production mode, but the debugger notes a local default connection string, so it gets confused and assumes it is in Development mode instead.

This tutorial is very complete, but I strongly recommend the writers to include this key piece of information, since it is essential for deploying the app.

**Comment by Rick-Anderson** [comment]
@donalatorre  a link to https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-2.1 should solve the problem

**Comment by joseffaghihi** [comment]
Hello, 
When I paste the following code in the Startup, I get an error on ApplicationUser. It says the type or namespace ApplicationUser could not be found or you are missing an assembly reference. I was wondering if know why?  
services.AddIdentity<ApplicationUser, IdentityRole>()
        .AddEntityFrameworkStores<ApplicationDbContext>()
        .AddDefaultTokenProviders();

**Comment by KathyWebTest** [comment]
Hi, I think your solution "...appsettings.json file, and replace the "DefaultConnection" from "ConnectionStrings" with a server key generated in azure..." could really help me. Would you be able to give me some more information about where you found the server key generated in Azure please - and also the syntax you used in the JSON file? Would really appreciate your help. Cheers

**Comment by Rick-Anderson** [comment]
> you must go to the appsettings.json file, and replace the "DefaultConnection" from "ConnectionStrings" with a server key generated in azure or some other database service

That's the wrong approach. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#providers

**Comment by joseffaghihi** [comment]
Thank you so much!

**Comment by priyankagargc27** [comment]
Hi Dona, I having the same issue. I put the right serve connection string in my appsetting.json file but still getting the same error. can you please help me out with this.

**Comment by koo9** [comment]
deploy to IIS not azure, getting the same error, anything else?

**Comment by koo9** [comment]
had the same issue, turned out to be the this call
//.AddValidationKeyFromFile(Configuration.GetSection("SigninKeyCredentials"), _loggerFactory.CreateLogger<Startup>())

that caused the trouble. use the developersigningcredentials seems to work fine.

**Comment by abdullah-alimam** [comment]
I think this will help
all you need is to display the real error by adding these lines in startup:

`app.UseDeveloperExceptionPage();`
`app.UseDatabaseErrorPage();`

without the condition of `if (env.IsDevelopment())`

and remove these lines if exists

`app.UseExceptionHandler("/Error");`
`app.UseHsts();`

then just let the app displaying the error like in development mode so you can search about it and fix it

**Comment by jais232** [comment]
> Thank you for your quick response, Rick. This link did not have the answer, however, I was able to solve it. Turns out, when you deploy your web app, you must go to the appsettings.json file, and replace the "DefaultConnection" from "ConnectionStrings" with a server key generated in azure or some other database service. Indeed the log is misleading, since when the app is deployed, it is in Production mode, but the debugger notes a local default connection string, so it gets confused and assumes it is in Development mode instead.
> 
> This tutorial is very complete, but I strongly recommend the writers to include this key piece of information, since it is essential for deploying the app.
Can you please help me how to find the server key generated in Azure

**Comment by Rick-Anderson** [comment]
This has nothing to do with Azure deployment. That's a different article.

**Comment by FahimNuman** [comment]
i face same problem in 3.1 . any one help me?

**Comment by oshinanika** [comment]
> I think this will help
> all you need is to display the real error by adding these lines in startup:
> 
> `app.UseDeveloperExceptionPage();`
> `app.UseDatabaseErrorPage();`
> 
> without the condition of `if (env.IsDevelopment())`
> 
> and remove these lines if exists
> 
> `app.UseExceptionHandler("/Error");`
> `app.UseHsts();`
> 
> then just let the app displaying the error like in development mode so you can search about it and fix it
> 
> after you fix the error(s) you can remove these changes so users can not see the error :)

@abdullah-alimam, Your solution helped me a lot.

Here's how my I solved my problem:

I had the same problem (ASP.NET CORE 3.1) but changing "ASPNETCORE_ENVIRONMENT" did not helped.

Seeing @abdullah-alimam 's answer, I found that in Startup.cs, Configure method, this code was hiding the real issue.
```
 if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
```

Then I deleted the If block and added Database error pages ( You might need to Install Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore from NuGet )
```
app.UseDatabserrorPages();
```
So your Startup.cs will look like this
```
app.UseDeveloperExceptionPage();
app.UseDatabaseErrorPage();
            
app.UseHttpsRedirection();

//Others will be Okay
```

Then you will see the real errors on the webpage. For me it was

```
Login failed for user IIS APPPOOL\DefaultAppPool
```

So I had to run a GRANT SCRIPT. I just had to run this script on my SQL Server
```
IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'IIS APPPOOL\DefaultAppPool')
BEGIN
    CREATE LOGIN [IIS APPPOOL\DefaultAppPool] 
      FROM WINDOWS WITH DEFAULT_DATABASE=[master], 
      DEFAULT_LANGUAGE=[us_english]
END
GO
CREATE USER [WebDatabaseUser] 
  FOR LOGIN [IIS APPPOOL\DefaultAppPool]
GO
EXEC sp_addrolemember 'db_owner', 'WebDatabaseUser'
GO
```
You can see this link : https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/deploying-to-iis

And my problem was solved. Hope this helps somebody.

**Comment by DanBer39** [comment]
@abdullah-alimam's  solution worked for me. Thanks
