### ISSUE TITLE
This article seems time travelling published with a future date

### ISSUE THREAD

**Issue by Parbil** [aspnet/Docs#7584]
Have you noticed the date it published, today is 12th Jul 2018 and this article is published on 27th Jul 2018.
Is it expiry date or it is going to be applicable on that date... Or I am living in another world :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Parbil  we project the publish date and sometimes get things done sooner.
