### ISSUE TITLE
SignalR with Windows Authentication in Asp.Net Core MVC v2.1

### ISSUE THREAD

**Issue by SigmaSolutions** [aspnet/Docs#7586]
Under Asp.Net Core MVC, I have SignalR (v2.1 Preview) implemented with Windows Authentication.  When the client, WPF app, call to the SignalR server and received 401 error. Should the client app be configured for Windows Authentication? Would you give a code sample for such settings? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@SigmaSolutions  have you seen https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1 and https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1

**Comment by SigmaSolutions** [comment]
Hi Rick-Anderson, still not be able to figure our the solution. I received HTTP 502.x error when running the code samples from both references. 

At server side, I understand to add implementation of IUserIdProvider and register it in Startup.ConfigureServices. However the at client side (I use WPF as client), should I pass on authenticated user information via connection = new HubConnectionBuilder().WithUrl().Builder()? If so, would you be able provide code sample? If not, where should it be? Thanks.

**Comment by Rick-Anderson** [comment]
@anurse  please comment

**Comment by anurse** [comment]
You need to set the `UseDefaultCredentials` property on [`HttpConnectionOptions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.connections.client.httpconnectionoptions.usedefaultcredentials?view=aspnetcore-2.1#Microsoft_AspNetCore_Http_Connections_Client_HttpConnectionOptions_UseDefaultCredentials):

```csharp
var connection = new HubConnectionBuilder()
    .WithUrl("https://example.com/myhub", options => {
        options.UseDefaultCredentials = true;
    })
    .Build();
```

**Comment by SigmaSolutions** [comment]
That works. Thanks.

**Comment by SigmaSolutions** [comment]
The issue has been resolved. Thanks for help!
Solution here is for Windows Authentication configuration. Refer Rick-Anderson's first correspondence for Hub side implementation; anurse's for client side implementation.

**Comment by anurse** [comment]
The docs are lacking here a little bit, so I opened https://github.com/aspnet/Docs/pull/7670 to fill that gap and making things clearer for others looking for this information.

Thanks for the report @SigmaSolutions !
