### ISSUE TITLE
Login with Twitter always redirects to Twitter authenticate/authorize page

### ISSUE THREAD

**Issue by Orgbrat** [aspnet/Docs#7588]
I have added Facebook and Twitter social logins to my new ASP.NET Core 2.1 w/Identity web site using these tutorials. Facebook has associated with the Identity user fine and and then just logs in as it should when performing any future Facebook logins for that user.  Twitter also associated with the Identity user and logs in just fine except!.  Every time you perform a Twitter login after the initial association,  when the ChallengeResult gets performed the user is always taken back to the Twitter authenticate/authorize page on the Twitter site instead of just logging in. If the user then inputs his user name and password then on callback the web site will log them in just fine.  So what am I missing in this tutorial for Twitter that makes the web site authorize at Twitter on every Twitter login?

Orgbrat

**Comment by Rick-Anderson** [comment]
@01binary please review
[Twitter external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)

**Comment by 01binary** [comment]
I will take a look, thanks.

**Comment by 01binary** [comment]
I confirmed the issue reproduces as described. I will try a couple of other OAuth providers and check Twitter documentation to determine if this is actually an issue (I am not an OAuth expert, otherwise I wouldn't need a Nuget package to do it :)  )

**Comment by Orgbrat** [comment]
One of us is missing the point here, it could very well be me but Facebook, Google and Twitter are not working same way.  Use case is user goes to web site and logs in with social account and when user comes back to web site they are asked to associate with web site local account which creates a records in Identity tables which works as expected. But on the users web site visits after that when the user goes to login page and clicks "Facebook" or "Google" the user is just logged in and not rerouted anywhere. The user is just automatically logged in. But with Twitter, even though Twitter has been associated with local Identity account and has a record in AspNetUserLogins table the user is taken out to the Twitter authenticate URL "https://api.twitter.com/oauth/authenticate" every time they use their Twitter login. Now when the user enters their Twitter credentials and they are returned back to the web site they are converted to an authenticated user and logged in.  My issue is that every time they login with Twitter only they are taken out to the Twitter API authenticate page and Facebook or Google does not work this way.  The issue is not when you first signup using you Twitter account it is with any successive logins after the first signup.


Am I incorrect in my thinking that Twitter should work just like Facebook and Google on future logins?  Have I missed doing or adding something that would cause only Twitter to act this way?

**Comment by 01binary** [comment]
I double-checked, see results below. I don't think I can participate in further discussion here, as we are getting into the technical weeds of OAuth2 as implemented by Twitter. Perhaps @Rick-Anderson can pull in one of the team members who worked on the NuGet packages.

> Go back to Sketchfab web site and login again with Twitter and you will see that you are not required to go to Twitter API to authenticate.

I don't doubt your report but I am seeing the same behavior as in the ASP.NET Core web app with Twitter authentication as described in the documents, when experimenting with the Sketchfab site:

* Click login on the site (assumes you already created an account and logged out)
* Observe that you are redirected to twitter:

![image](https://user-images.githubusercontent.com/19985964/42739637-a89ea934-884f-11e8-89e3-f6c320d60a01.png)

* With no further user action, you are redirected back to the site
* Observe that you are now logged in

This behavior matches the one described by Twitter documentation:

https://developer.twitter.com/en/docs/twitter-for-websites/log-in-with-twitter/guides/browser-sign-in-flow

> The browser sign in flow is appropriate for websites and applications which are able to open or embed a web browser. At a very high level:
> * The application renders a “Sign in with Twitter” link or button.
> * The user clicks the sign in button.
> * The current web browser is redirected to Twitter (or a new browser is opened and directed to Twitter).
> * The user completes a login and authorization step at Twitter if needed.
> * Twitter redirects back to an URL under the application’s control, passing authorization information for the user.

Even if Sketchfab implemented Twitter OAuth incorrectly, there is still the fact that it appears to match the official Twitter documentation.

Also, regarding this:

> My issue is that every time they login with Twitter only they are taken out to the Twitter API authenticate page and Microsoft, Facebook or Google does not work this way.

I am observing (as I mentioned in my first post) that Google is behaving the same way as Twitter.

Lastly, I double-checked both Google and Twitter app settings and I haven't seen a configuration setting that has some kind of "remember me" effect which happens to be turned on in Facebook by default, but off by default in Google and Twitter (I haven't tested Microsoft auth). Perhaps such a setting does exist but I am not aware of it. For example, these two settings seem suspect:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.twitter.twitteroptions?view=aspnetcore-2.1

* SaveTokens
* StateCookie

**Comment by 01binary** [comment]
Final test for posterity. I recorded the results for Facebook OAuth flow from an ASP.NET Core app, and confirmed that it is redirecting you to Facebook OAuth dialog, which does not render and sends a redirect immediately from their server-side endpoint. This differs from Twitter and Google flow in that they actually render their OAuth dialogs by responding with HTML, and then sending a response to the backchannel. In other words, ASP.NET code is exactly the same but Facebook appears to respond faster because it does not send an HTML page for the browser to render, which makes the callback into your application look more immediate.

![image](https://user-images.githubusercontent.com/19985964/42740520-975ffd54-885d-11e8-8393-1d2e88af6f2e.png)

In the screenshot above:
1. (blue) Facebook NuGet package redirects to the Facebook OAuth dialog at facebookcom/v2.6/dialog/ouath?xxx
2. (red) Facebook OAuth dialog receives the claims but does not send HTML back
3. (green) Facebook server immediately calls the backchannel opened by the Microsoft Facebook NuGet package to give the auth code
4. (dark red) Facebook OAuth dialog immediately redirects back to our app

**Comment by Rick-Anderson** [comment]
@HaoK  who's the right resource to figure out FB auth?

**Comment by HaoK** [comment]
@Tratcher and me

**Comment by Tratcher** [comment]
I just tested Twitter again and I get the same results as @01binary, Twitter does not ask me for credentials each time, only if I explicitly sign out of Twitter. If you did not select the "Remember Me" option on Twitter's login page then this is the result I'd expect if you closed the browser between tests.

**Comment by Orgbrat** [comment]
Ok, you folks have convinced me.  For Twitter you must select the "Remember Me" option on Twitter's login authentication page for it to work as I was expecting. I guess it really is a Twitter auth thing. I am sorry for causing anyone any issues or hardships determining that this was working as it should. Again this was very very much appreciated and I am sorry for this effort.
