### ISSUE TITLE
Change ambiguous wording

### ISSUE THREAD

**Issue by cmatskas** [aspnet/Docs#759]
Hi
On this page:

https://github.com/aspnet/Docs/blob/master/aspnet/conceptual-overview/understanding-aspnet5-apps.rst#server-side-dependency-management

 half way down the post, where it talks about Client-Side dependencies, there's a phrase that doesn't make lots of sense:

*Dependency are then further configured in their own section within each bower.json file, indicating how it should be deployed to the wwwroot folder.*

I would like to send a PR with the following correction:

**"Each dependency is then further configured within it's corresponding section using its own *bower.json* file, indicating how it should be deployed to the *wwwroot* folder."**

**Comment by ardalis** [comment]
"within it's corresponding" this is possessive so should be "within its corresponding".

**Comment by cmatskas** [comment]
Hi @ardalis lol, you're correct. Are you still happy with me to progress with the change? Does it make more sense? Thanks for looking into this by the way

**Comment by ardalis** [comment]
Sure, go for it.

**Comment by cmatskas** [comment]
Hi @ardalis. I've raised the PR( #759) but there seems to be and issue with the CI build. Quite a few errors in the last couple of hours and it seems to be a red herring as the warnings are about files that are already in the repo. Is there anything I can do to help? thanks

**Comment by ardalis** [comment]
I don't think 759 is actually your PR number since it's this issue number - looks like it's #765

**Comment by ardalis** [comment]
PR looks good; closing this issue.

**Comment by cmatskas** [comment]
You're right. The PR is #765. Apologies for the confusion
