### ISSUE TITLE
Bug in ModelState validation

### ISSUE THREAD

**Issue by gtbee** [aspnet/Docs#7593]
I have a React client application that PUTS a JSON object in the Http Body to a an ASP.Net Cre web api. The method gets called and, with a [FromBody] attribute the Http Body is successfully read into a class defined in c#. However when I look at the ModelState it has returned one error for the Id field (which is a string). The class property has no other validation attributes decorating it, just a JsonProperty to write to/from a lowercase property name "id". 
The message in the ModelState results collection (ModelError) object is:
ErrorMessage	"The value '42dd2766-b1e9-4733-b1b1-78a976ccd96c' is not valid."	string

Last time I looked this was a valid string so where is the out of the box ASP.Net Core code finding an error from? Is it a length issue, the fact it looks like a GUID, the fact it starts with a number? My easy workaround is simply to ignore the use of ModelState but it feels better to have someone look at this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@gtbee  Can you open an issue at https://github.com/aspnet/Mvc 
Provide a gitHub link to the simplest possible project the reproduces the bug.

**Comment by tdykstra** [comment]
@gtbee Thanks for reporting this product bug.  But as this is a product bug and not a doc bug, we’re going to close the issue in this repo. Feel free to reopen if you want to continue the discussion here.
