### ISSUE TITLE
Please update the content

### ISSUE THREAD

**Issue by benoityip** [aspnet/Docs#7594]
Although I can follow, but the content is little outdated with my Visual Studio 2017 15.7.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3b23da-ff3d-daf6-c56a-2b8ddf79f805
* Version Independent ID: 5ea39e72-fcfc-ddbe-2f4d-f4166dfbe5a8
* Content: [Use Grunt in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-grunt?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/using-grunt.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-grunt.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@benoityip  thanks for reporting.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
