### ISSUE TITLE
What about Angular 6?

### ISSUE THREAD

**Issue by Martin-Andersen** [aspnet/Docs#7597]
Is there a way to create a new app using Angular 6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS do we have a timeline for Angular 6? cc @scottaddie

**Comment by purplepiranha** [comment]
This would be good - the upgrade process is a pain!

**Comment by scottaddie** [comment]
@Martin-Andersen The Angular 6 template will ship with the upcoming ASP.NET Core 2.2 release. See https://github.com/aspnet/Templating/pull/581 for more info.
