### ISSUE TITLE
.Net Type DataTime

### ISSUE THREAD

**Issue by zhangtingwz** [aspnet/Docs#7598]
I am a new learner ,if i create a Class  public  DataTime  BeginDay{get;set;} public DataTime  EndDay{get;set;} 
how Can i set EndDay BIgger than BeginDay in the my Index.cshtml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96bbb2e-2611-525f-129d-b86a491e423c
* Version Independent ID: 4e39097d-b058-d4e2-8780-31b0067b6717
* Content: [Tag Helpers in forms in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/working-with-forms?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/working-with-forms.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/working-with-forms.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@zhangtingwz  you'll probably get a much quicker response if you post this question to a forum like StackOverflow.

**Comment by Rick-Anderson** [comment]
@pupultukas  agree with what? What does it mean to EndDay BIgger than BeginDay ?  `EndDay BIgger` `BeginDay` are not in the article.
