### ISSUE TITLE
Error creating DB when entering lines via PMC

### ISSUE THREAD

**Issue by MikeVillareal** [aspnet/Docs#7599]
## Issue

I'm currently following a tutorial via this link - https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1 but  can't get pass through due to an error when entering lines via PMC (Package Manager Console):
Add-Migration Initial
Update-Database

## Error

Failed executing DbCommand (15ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [MvcMovieContext-dc349dc9-ac53-48fb-9b34-80ac9a708970];

CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\SandraMvcMovieContext-dc349dc9-ac53-48fb-9b34-80ac9a708970.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.

Am I missing a configuration that links Visual Studio connection to the MS SQL Server ?

Thanks,
Michael

**Comment by MikeVillareal** [comment]
Thanks for dropping a hint @Rick-Anderson! I've followed the thread in the link you've provided and then used a hotfix (Cumulative update 6 for SQL Server 2017) , glad it worked.

Cheers!

**Comment by Rick-Anderson** [comment]
@MikeVillareal  thanks for the update. Glad you got it working. There should be an easier way to resolve the problem.
