### ISSUE TITLE
Demo code shown for change to Register.cshtml is duplicated

### ISSUE THREAD

**Issue by scraping-infinity** [aspnet/Docs#7603]
This documentation needs a little tweaking: The demo code shown for the Areas/Identity/Pages/Account/Register.cshtml is repeated.  See the highlighted markup section, and the two DIV elements directly below it.  The Input.Name and Input.DOB sections are present twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scraping-infinity  nice catch - thanks for reporting.
