### ISSUE TITLE
IDesignTimeDbContextFactory class

### ISSUE THREAD

**Issue by DesertBreeze** [aspnet/Docs#7615]
Just a note that in my tutorial project, in order to get the Add-Migration Rating and Update-Database to work in PMC, I had to add a new class file for the IDesignTimeDbContextFactory and update the appsettings.json file to "DefaultConnection".  Sample in link: https://github.com/Ibro/DesignTimeDbContextFactory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@DesertBreeze  those steps are not necessary. *appsettings.json* should have the correct `DefaultConnection`

**Comment by Rick-Anderson** [comment]
@DesertBreeze  are you using the latest Visual Studio and the .NET Core SDK 2.1?

**Comment by DesertBreeze** [comment]
I have the latest Visual Studio but not the .NET Core SDK 2.1.  It's .NET Core SDK 2.0.  That's probably why.  Thanks for helping!

**Comment by ajackson4598** [comment]
I had to add a DesignTimeDbContextFactory: 

using System.IO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using MvcMovie.Models;

namespace Web
{
    public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<MvcMovieContext>
    {
        public MvcMovieContext CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();

            var builder = new DbContextOptionsBuilder<MvcMovieContext>();

            var connectionString = configuration.GetConnectionString("MvcMovieContext");

            builder.UseSqlServer(connectionString);

            return new MvcMovieContext(builder.Options);
        }
    }
}

**Comment by jdmagic21** [comment]
@ajackson4598 Where did the namespace of web come from?

**Comment by ajackson4598** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.web?redirectedfrom=MSDN&view=netframework-4.7.2

**Comment by Rick-Anderson** [comment]
>I had to add a DesignTimeDbContextFactory:

That's not necessary. I'm not sure what you did wrong but you don't need to add that.

**Comment by ajackson4598** [comment]
ok Kewl.

**Comment by jdmagic21** [comment]
I would look at https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1. Fixed my issue.

**Comment by Rick-Anderson** [comment]
@jdmagic21 that wouldn't apply if you used the current SDK/VS - version 2.1

**Comment by Boxarve** [comment]
This fixed my issue:

Make sure to install
    Microsoft.EntityFrameworkCore.SqlServer
    Microsoft.EntityFrameworkCore.Design

https://stackoverflow.com/questions/49521315/cannot-add-migration-with-asp-net-core-2

**Comment by cabisadaandrian** [comment]
install via nuget console? or put it on program.cs?

**Comment by Boxarve** [comment]
Install using Package Manager
```
Install-Package "Microsoft.EntityFrameworkCore.SqlServer"
Install-Package "Microsoft.EntityFrameworkCore.Design"
```
