### ISSUE TITLE
Tutorial completed!

### ISSUE THREAD

**Issue by BrianRCook2010** [aspnet/Docs#7617]
I would like to thank the contributors for providing an excellent tutorial. This, together with the ASP.Net Core learning stream on MVA, provides an very good grounding in the subject. As a 68 year-old newbie to ASP.NET, I cannot say I understand all of it, but I definitely know more than when I started! The next challenge is to adapt the code to my own databases!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@BrianRCook2010  thanks for the feedback.  cc @tdykstra
