### ISSUE TITLE
CORS not blocking requests?

### ISSUE THREAD

**Issue by raberana** [aspnet/Docs#7618]
I tried to create a sample project implementing a CORS policy. My CORS configuration specifically indicated that the allowed origin should come from `http://microsoft.com`.

```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("CORSPolicy", builder=>builder.WithOrigins("http://microsoft.com"));
            });

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCors("CORSPolicy");

            app.UseMvc();
        }
```

However, when I ran the project, the APIs were still accessible via my local browser. 

![capture](https://user-images.githubusercontent.com/3053739/42723862-11f2dc36-879a-11e8-83ed-f83d3065791e.PNG)

I'm sorry if I am missing something here but is ASP.NET Core smart enough not to execute the CORS Policy if it sees that the request actually comes from the same domain?

If it is, maybe we can update the **How CORS works** section so noobs like me knows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.1#how-cors-works)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Localhost is not a cross-origin request to your site. You might want to post this to StackOverflow to get help.

**Comment by raberana** [comment]
Hi, I am aware of that. But I specified that my AllowedOrigin is only from microsoft.com. Does it mean that ASP.NET Core does not implement the CORS policy because it knows that the request only came from localhost? Because I was assuming that it will always implement the CORS policy; since localhost and microsoft.com are different, I thought it will block it.

**Comment by Rick-Anderson** [comment]
Browser security prevents a web page from making requests to a different domain than the one that served the web page. This restriction is called the same-origin policy. 

No, it means the domain didn't change.
