### ISSUE TITLE
False positives during build

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#7622]
@Rick-Anderson @scottaddie Looks like we have some false positives during build ...

<img width="436" alt="capture" src="https://user-images.githubusercontent.com/1622880/42724697-af5f0552-873c-11e8-95f9-eafdeab3fb73.PNG">

Warning | Unspecified | aspnetcore/security/enforcing-ssl.md | Cannot resolve 'authentication/accconfirm/sample/WebApp1/Startup.cs' relative to 'security/enforcing-ssl.md'. | 0 | 07/14/2018 12:09:29
-- | -- | -- | -- | -- | --
Warning | Unspecified | aspnetcore/security/enforcing-ssl.md | Cannot resolve 'authentication/accconfirm/sample/WebApp1/Startup.cs' relative to 'security/enforcing-ssl.md'. | 0 | 07/14/2018 12:09:29

The lines are ...

```
[!code-csharp[](authentication/accconfirm/sample/WebApp1/Startup.cs?name=snippet2&highlight=4-999)]
```

```
[!code-csharp[](authentication/accconfirm/sample/WebApp1/Startup.cs?name=snippet_AddRedirectToHttps&highlight=7-999)]
```

The links are correct, and rendering is nominal:

<img width="253" alt="capture1" src="https://user-images.githubusercontent.com/1622880/42724705-e14646fc-873c-11e8-9760-019961b4bc2f.PNG">

[I've always wanted to use the word "nominal" (per Star Trek) in a sentence like that. *My dreams have been fulfilled!* :smile:]

**Comment by Rick-Anderson** [comment]
@guardrex  I fixed this.
