### ISSUE TITLE
Migration instructions are for Visual Studio

### ISSUE THREAD

**Issue by ghidalgo3** [aspnet/Docs#7623]
The previous steps of this guide assume you are using Visual Studio Code, and they give the dotnet commands. This page now switches to using the VS package manager console. That's not consistent :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ghidalgo3  nothing assumes VS Code. What step are you talking about and what version of the tutorial (2.0 or 2.1?)

**Comment by ghidalgo3** [comment]
Following this set link:
1. https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/index?view=aspnetcore-2.1
2. Click on Add Search
3. Then at the end of the page: Add a new field.

Actually now I see that the first page mentions that the last two steps are only for Visual Studio. It was confusing that the Visual Studio Code tutorial path led into the pages for Visual Studio.

It wasn't a blocker, I figured out the dotnet commands. but someone else might get stumped and give up.

**Comment by Rick-Anderson** [comment]
@ghidalgo3  Thanks - I see now. 
I'll add CLI instructions.

**Comment by theitsloth** [comment]
SQLite does not support this migration operation. Better go and rebuild the database from scratch, or change the schema by hand

**Comment by Rick-Anderson** [comment]
@theitsloth 	correct, thanks.
