### ISSUE TITLE
Code snippet for JWT Bearer token configuration is incomplete

### ISSUE THREAD

**Issue by jerriep** [aspnet/Docs#7624]
The code snippet for the `ConfigureServices` method, which shows how to configure the JWT Bearer token middleware is missing parts of the code. I would have just fixed it, but I am not sure what the intention was in terms of which parts you wanted to highlight. So, it is perhaps best if the original author addresses this since they know what their intention was.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **anurse**

**Comment by ransagy** [comment]
Just came across this as well. @jerriep, Just for clarity - What did you have in mind here as a fix?

**Comment by jerriep** [comment]
I think their intention was to display the entire `ConfigureServices` method and then highlight some of the JWT configuration lines. But I am not sure, which is why I referred it to them since they know better what the intention was.

**Comment by BrennanConroy** [comment]
The code is a snippet from the sample for that doc, see https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz/sample/Startup.cs for the full method. @anurse for whether more lines should be shown in the doc.
