### ISSUE TITLE
Invalid indentation

### ISSUE THREAD

**Issue by VPeruS** [aspnet/Docs#7626]
Some code samples missing indentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1#)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @VPeruS ... Thanks for commenting. We have an internal issue tracking it.
