### ISSUE TITLE
Include section about replicating old asp.net signal QueryString functionality

### ISSUE THREAD

**Issue by tomzorz** [aspnet/Docs#7629]
Adding parameters at the end of the `connectionBuilder` `.withUrl("/transportHub?param=foobar")` like this, and accessing it in the Hub `OnConnectedAsync` override like this `Context.GetHttpContext().Request.Query["foobar"]`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@BrennanConroy  please comment

**Comment by BrennanConroy** [comment]
Maybe we should add a section in the hubs doc for the Context object, similar to the Clients one https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1#the-clients-object

**Comment by tdykstra** [comment]
@tomzorz Thanks for the suggestion. PR #8486 adds a Context property section to the doc, including a note on how to get query strings.

**Comment by tomzorz** [comment]
@tdykstra excellent, thank you! :)
