### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by pekspro** [aspnet/Docs#7630]
Thanks for a nice article. But I think it would be easier if the JavaScript was changed so IE11 is supported. I know it references to a transpiler, but why not support this from start? The code is very similar to the original one:

        var connection = new signalR.HubConnectionBuilder()
            .withUrl("/chatHub")
            .build();

        connection.on("ReceiveMessage", function (user, message) {
            var msg = message.replace(/&/g, "&amp;").replace(/&lt;/g, "&lt;").replace(/&gt;/g, "&gt;");
            var encodedMsg = user + " says " + msg;
            var li = document.createElement("li");
            li.textContent = encodedMsg;
            document.getElementById("messagesList").appendChild(li);
        });

        connection.start().catch(function (err) {
            return console.error(err.toString());
        });

        document.getElementById("sendButton").addEventListener("click", function (event) {
            var user = document.getElementById("userInput").value;
            var message = document.getElementById("messageInput").value;
            connection.invoke("SendMessage", user, message).catch(function (err) {
                return console.error(err.toString());
            });
            event.preventDefault();
        });

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by Rick-Anderson** [comment]
@BrennanConroy  please comment

**Comment by BrennanConroy** [comment]
I think for this sample we can just replace chat.js with the es5-chat.js file so the code sample works with IE11 too. The only real difference in the transpiled version is `var` instead of `const` and a couple minor syntax differences.
