### ISSUE TITLE
Gulp 3.9 vs ^4.0 syntax,  AssertionError

### ISSUE THREAD

**Issue by LukaszJuroszek** [aspnet/Docs#7632]
Just to remind, syntax of gulp has changed since 4.0+ and gulpfile.js will throw AssertionError
Use
`gulp.series()`
 example:
`gulp.task("clean", ["clean:js", "clean:css"]);`
 to:
`gulp.task("clean", gulp.series("clean:js", "clean:css"));`

> added gulp.series and gulp.parallel methods for composing tasks. Everything must use these now.

[https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md](from)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb34beb-733d-ad1e-37a7-cbe045ee9f15
* Version Independent ID: 02319a95-6eb9-59cd-f5fc-747c61e90123
* Content: [Use Gulp in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/using-gulp.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-gulp.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by LukaszJuroszek** [comment]
//gulp.task("clean", ["clean:js", "clean:css"]);
gulp.task("clean", gulp.series("clean:js", "clean:css"));
"added gulp.series and gulp.parallel methods for composing tasks. Everything must use these now." from https://github.com/gulpjs/gulp/blob/4.0/CHANGELOG.md

**Comment by Rick-Anderson** [comment]
@scottaddie  what's the plan for Gulp documents?
