### ISSUE TITLE
why can't i use enable-migrations ??

### ISSUE THREAD

**Issue by shahoud** [aspnet/Docs#7635]
You have to install this package by editing the .csproj file; you can't use the install-package command or the package manager GUI.
can i use package manager console to enable migrations ??? if not , why ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e675b-5964-a75b-7e45-6f6d1a607e65
* Version Independent ID: 78e47218-58a3-f8d9-e091-306126871a67
* Content: [ASP.NET Core MVC with EF Core - Migrations - 4 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-mvc/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/migrations.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@shahoud  that's correct with .NET Core 2.0
Can you try the updated [Razor Pages version](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/?view=aspnetcore-2.1) which doesn't have this problem?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
