### ISSUE TITLE
Unable to create an object of type 'MvcMovieContext'

### ISSUE THREAD

**Issue by msharps** [aspnet/Docs#7636]
Encountered the following error when executing "Add-Migration Rating":

Unable to create an object of type 'MvcMovieContext'. Add an implementation of 'IDesignTimeDbContextFactory&lt;MvcMovieContext&gt;' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

Visiual Studio Community 2017 version 15.7.5
.NET Framework version 4.6.01590

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca95f5e-0fe4-bbd2-fd23-13562e02f888
* Version Independent ID: c3fb9673-4da6-5eeb-08bb-6f8e7bc8e0c6
* Content: [Add a new field to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/new-field?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@msharps  I'm not sure what you did wrong but that error is misleading. You might compare your code to the download to see what when wrong.

**Comment by hoangpham0501** [comment]
You need to add an implementation of IDesignTimeDbContextFactory where the ApplicationDbContext is put (in my case it's in Data folder)
Sample code:
public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<StartProjectContext>
    {
        public StartProjectContext CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();
            var builder = new DbContextOptionsBuilder<StartProjectContext>();
            builder.UseSqlServer<StartProjectContext>("Server=(localdb)\\mssqllocaldb;Database=StartProjectContext-af90bdd0-0ac9-4522-b642-e1bec9d28c74;Trusted_Connection=True;MultipleActiveResultSets=true");
            return new StartProjectContext(builder.Options);
        }
    }

**Comment by Rick-Anderson** [comment]
@hoangpham0501  You do **not** have to add an implementation of `IDesignTimeDbContextFactory`

**Comment by hoangpham0501** [comment]
Maybe you should check it again :D I have followed this tutorial step by step and I got same error with msharps. So I added an implementation of IDesignTimeDbContextFactory and then it worked :D

**Comment by paulowendevelopment** [comment]
I'm getting exactly the same error running Dotnet version 2.1.202

**Comment by paulowendevelopment** [comment]
As this tutorial is from 2016, I'd imagine it's quite feasible for something to have changed, so saying "The instructions in the tutorial are complete and correct." is quite a bold statement?

**Comment by Rick-Anderson** [comment]
@hoangpham0501  see https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x#install-visual-studio-and-net-core

You need the current .NET Core SDK

**Comment by jdmagic21** [comment]
@Rick-Anderson Upgrading the latest version of the .NET Core SDK does not make this problem go away. Also, following the tutorial to the T does not make the error go away.

**Comment by paulowendevelopment** [comment]
@jdmagic21 no you're right it is misleading, I even downloaded the latest from the website and it made no difference. What fixed it for me was to update the Nuget packages. Right click on your project in solution explorer and select manage Nuget packages, and update the ones that have a little blue arrow . Hope that fixes it for you!

**Comment by jdmagic21** [comment]
Make sure that your progam.cs file is correct. Use BuildWebHost().

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
