### ISSUE TITLE
800MB ZIP to "download __a__ sample"

### ISSUE THREAD

**Issue by ferzkopp** [aspnet/Docs#7637]
The whole Docs-master.zip file is 800MB. In my view this is massive waste of my networking resources and unpack time when I just wanted to see one of the starter app samples. Please make these downloads more fine grained!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c461e1d-5771-20f9-c9b3-ac4ee7661ee0
* Version Independent ID: e06d8e48-cee4-0c0c-39aa-97abe228c370
* Content: [ASP.NET Core tutorials](https://docs.microsoft.com/en-us/aspnet/core/tutorials/index?view=aspnetcore-2.1#how-to-download-a-sample)
* Content Source: [aspnetcore/tutorials/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ferzkopp ... Yes, the docs engineering team is working on a solution. We don't have an ETA, but the new system should avoid having to download the entire repo just to get one sample.
