### ISSUE TITLE
Incorrect exiting ASP.NET Core application with systemd configuration

### ISSUE THREAD

**Issue by harrison314** [aspnet/Docs#7641]
In Linux guides in systemd service configurtaion `/etc/systemd/system/kestrel-hellomvc.service` missing KillSignal specification.

In default (using `systemctl restart kestrel-hellomvc.service` or stop) kill ASP.NET Core application without execution dispose on singlton services, finaly bloks and [IApplicationLifetime.ApplicationStopped and IApplicationLifetime.ApplicationStopping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iapplicationlifetime?view=aspnetcore-2.1).

For fix add `KillSignal=SIGINT` to systemd configuration .

New version  is:
```
[Unit]
Description=Example .NET Web API App running on CentOS 7

[Service]
WorkingDirectory=/var/aspnetcore/hellomvc
ExecStart=/usr/local/bin/dotnet /var/aspnetcore/hellomvc/hellomvc.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=dotnet-example
User=apache
Environment=ASPNETCORE_ENVIRONMENT=Production 

[Install]
WantedBy=multi-user.target
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **spboyer**

**Comment by guardrex** [comment]
ping @shirhatti

**Comment by shirhatti** [comment]
It looks like systemd defaults to sending `SIGTERM`, so this is a useful change.
It's probably also worth mentioning `TimeoutStopSec=` as way of configuring the duration between the initial kill signal and the eventual `SIGKILL` that gets sent if the process hasn't shutdown by then
