### ISSUE TITLE
string or GUID

### ISSUE THREAD

**Issue by AminTakhtiNejad** [aspnet/Docs#7642]
hey,
what is difference between string and Guid as primary id type?
is there any benefit using one over another?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d03a65-2965-0261-3d05-bf2c89721fd2
* Version Independent ID: 37f74d7d-ed17-eb35-183d-02f04183f880
* Content: [Configure Identity primary key data type in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-primary-key-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity-primary-key-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-primary-key-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@AminTakhtiNejad  see [this](https://www.google.com/search?q=identity+string+and+Guid+as+primary+id&rlz=1C1CHBF_enUS801US801&oq=identity+string+and+Guid+as+primary+id&aqs=chrome..69i57.3556j0j7&sourceid=chrome&ie=UTF-8)
