### ISSUE TITLE
Wasn't familiar with node.js

### ISSUE THREAD

**Issue by Sothecom** [aspnet/Docs#7643]
I'm sure most Developers dabbling in SignalR would immediately have known that npm was a reference to node.js Prerequisites Step 4), however I didn't as I have no experience with it. 
I did find the relevant info after some googling although I'm sure finding where the @aspnet folder is straight forward to find. 
May I suggest you add a small snippet to say make it clear that the Package Console mentioned is totally different to the one found in VS. 
Great intro for a first timer though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @rachelappel
* Microsoft Alias: **rachelap**

**Comment by tdykstra** [comment]
@Sothecom Thanks for the suggestion - I added a note explaining that npm is a package manager for Node.js.

**Comment by Coscotex** [comment]
I spent way too much time on this because I wasn't familiar with node.js. I just recently updated my visual studio and went to take this tutorial. I t would do some of us beginners much good, if you expressly state that node.js has to be installed on your machine.

**Comment by Rick-Anderson** [comment]
@tdykstra  can you make sure that's clear?

@Sothecom 
> make it clear that the Package Console mentioned is totally different to the one found in VS.

The only PMC mentioned is the VS PMC.
