### ISSUE TITLE
ws-federation side by side with asp.net core identity

### ISSUE THREAD

**Issue by dacken** [aspnet/Docs#7653]
I've copied the same code from above. But it seems once I have asp.net core identity with ws-federation as the same time, the ws-federation won't work. The user can be redirected to the federated login page, and post back looks correct but the origin action always complains identity is not authenticated. 
I can see that the incoming ws-federation response is correct from the OnTicketReceived event, and the identity is authenticated in the OnTicketReceived event,  set-cookie for "identity.external" can be found in redirect to origin URL response. However the origin URL seems does not recognize the identity.external cookie.
Is that the issue of sequence of service configuration? Or I missed something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@chlowell can you respond?

**Comment by chlowell** [comment]
It could be a configuration problem. You might find a full sample app more helpful than the snippets in the doc. There's one in [aspnet/Security](https://github.com/aspnet/Security/blob/master/samples/WsFedSample/Startup.cs).

**Comment by dacken** [comment]
I was using the sample app to add the asp.net core identity side by side with wsfederation.  Once I add the services.AddIdentity, the wsfederation will not work.  It looks like both asp.net core identity and wsfederation will register authentication scheme, but the authentication middleware will use the default one only.  Can I register two authentication middleware?  
My current solution is to map the wsfederation user to asp.net core identity user and call signinmanger to signin in the OnTokenValidated event. This is a little bit ugly. 

Here is the code from authentication middle ware:
  var defaultAuthenticate = await Schemes.GetDefaultAuthenticateSchemeAsync();
            if (defaultAuthenticate != null)
            {
                var result = await context.AuthenticateAsync(defaultAuthenticate.Name);
                if (result?.Principal != null)
                {
                    context.User = result.Principal;
                }
            }

**Comment by chlowell** [comment]
I don't quite follow you. Like oauth middleware, the ws-fed middleware integrates with Identity as an external authentication provider. So Identity handles login and registration, and manages accounts, but accepts authentication from the ws-fed provider.

Using the MVC 2.1 new project template with individual user accounts as an example, your configuration would look something like this:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(
            Configuration.GetConnectionString("DefaultConnection")));
    services.AddDefaultIdentity<IdentityUser>()
        .AddEntityFrameworkStores<ApplicationDbContext>();

    services.AddAuthentication()
        .AddWsFederation(options =>
        {
            //  your ws-fed config here
        });

    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
