### ISSUE TITLE
I’d like to express my appreciation ...

### ISSUE THREAD

**Issue by jwatkin** [aspnet/Docs#7654]
I’d like to express my appreciation to you and your team for your great work on Microsoft’s developer documentation. Your documentation is a crucial part of what makes developing within Microsoft’s ecosystem so efficient and pleasurable. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jwatkin  Thanks!
