### ISSUE TITLE
Doc for publishing to IIS with MSDeploy

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Docs#766]
Scott Hunter asked me to write up a doc for publishing to IIS with MSDeploy that he would like to see on this site. I have written up the doc and attached it here [Publishing-to-IIS-with-MSDeploy.zip](https://github.com/aspnet/Docs/files/56165/Publishing-to-IIS-with-MSDeploy.zip).

Can someone help me convert this to .rst and get it added here?

**Comment by robbert229** [comment]
I can if that is okay with you.

**Comment by sayedihashimi** [comment]
@robbert229 works for me, thanks

**Comment by robbert229** [comment]
ok.

**Comment by robbert229** [comment]
PR is in. For now I am just having your name point to your github account. @sayedihashimi

**Comment by robbert229** [comment]
I think this should be closed @sayedihashimi
