### ISSUE TITLE
Can't get error message from resource file when use custom validation attribute

### ISSUE THREAD

**Issue by andriialbumentormate** [aspnet/Docs#7660]
I have one attribute which is inherited  from ValidationAttribute

```
public class CustomAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            //some logic here
            bool isValid= result;// can be true or false
            if (!isValid)
            { 
                return new ValidationResult(ErrorMessage);
            }

            return ValidationResult.Success;
        }
    }
```
And I use it in model like this
```
[Display(Name = "SomeField")]
[Custom(ErrorMessage = "The filed is required.")]
public sometype SomeField{ get; set; }

```
When I use validators out of box (`EmailAddress, StringLength, etc.`), I can grab error message from resource file.

What do I need to add or change to get error message from resource file when I use my custom validator ?

Is this the only way I can get error messages from resource files when I use custom attribute ?

https://stackoverflow.com/questions/42784311/asp-net-core-custom-validation-attribute-localization
https://blogs.msdn.microsoft.com/mvpawardprogram/2017/01/03/asp-net-core-mvc/

Thanks for any help.
Kind regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#dataannotations-localization)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  is this something we need to add to the doc?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  Thanks. GitHub issues are very discoverable, so this is a pretty good place for that info. Additionally, this issue is displayed on
