### ISSUE TITLE
Is it possible to include images/scripts/css in Razor Class Libraries?

### ISSUE THREAD

**Issue by k3davis** [aspnet/Docs#7662]
If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm should I change the opening paragraph from

Razor views, pages, controllers, page models, View components, and data models can be built into a Razor Class Library (RCL)

to

Razor views, pages, controllers, page models, View components, data models,  and images/scripts/css can be built into a Razor Class Library (RCL)

@pranavkm  is there any trick to adding  images/scripts/css

**Comment by k3davis** [comment]
@Rick-Anderson your comment implies that the answer to my first question is "yes" - if so it would be great to have the sample code expanded to include some of this.

**Comment by Rick-Anderson** [comment]
@pranavkm  can you point to a sample that includes static assets?

**Comment by SperoSophia** [comment]
This should be a default feature:

    public class MiniCMSContentController : Controller
    {
        static Dictionary<string, string> mime = new Dictionary<string, string> {
            { ".js", "text/javascript" },
            { ".css", "text/css" },
        };

        [Route("/MiniCMS/Content/{filename}")]
        public IActionResult Index(string filename)
        {
            string outMime = "application/unknown";
            mime.TryGetValue(Path.GetExtension(filename).ToLower(), out outMime);
            return new FileStreamResult(Assembly.GetExecutingAssembly().GetManifestResourceStream("MiniCMS.Content." + filename), outMime);
        }
    }

**Comment by Rick-Anderson** [comment]
@pranavkm  please comment

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Docs/issues/6838?

**Comment by Rick-Anderson** [comment]
See https://github.com/aspnet/Razor/issues/2391

**Comment by k3davis** [comment]
This is way too cryptic for me. I hope the documentation will be improved to include some of this information. The code attached in #6838 may be sufficient for people who speak that language.

**Comment by pflannery** [comment]
@k3davis I found the example by @dodyg useful thanks, but when I tried to use the `asp-append-version` attribute it failed to append a version to any embedded resource contained within my RCL. 

I did some searching and https://github.com/aspnet/Mvc/issues/7459 explains how to fix this. 

So by appending this line `Environment.WebRootFileProvider = new CompositeFileProvider(Environment.WebRootFileProvider, filesProvider);`
 to the [BaseModuleUiConfigureOptions class here](https://github.com/dodyg/practical-aspnetcore/blob/master/projects/mvc/razor-class-library-with-static-files/src/RazorClassLibraries.Mvc.Core/BaseModuleUiConfigureOptions.cs#L36) seems to fix this problem.

Is this the best approach?

**Comment by JeanCollas** [comment]
I add my 2 cents, with 2 blog articles:
[How to Include static files in a Razor library](https://dotnetstories.com/blog/How-to-Include-static-files-in-a-Razor-library-en-7156675136)
[How to automatically embed static files in ASPNET Core libraries and Razor libraries](https://dotnetstories.com/blog/How-to-automatically-embed-static-files-in-ASPNET-Core-libraries-and-Razor-libraries-en-7190877935)

**Comment by nacoleman** [comment]
Based on the last 3 comments and the workload required to get this working would it be fair to say the documentation here https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.2&tabs=visual-studio#create-an-rcl-with-static-assets is too simple and fails to mention any of what is actually required?
