### ISSUE TITLE
Razor Pages compatibility

### ISSUE THREAD

**Issue by Ponant** [aspnet/Docs#7664]
Are there any Localization features which are not compatible with Razor Pages as of today? For instance, invoking localization in the controller?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Ponant not that I know of. @ryanbrandenburg  will correct me if I'm wrong. If so, we need to update the doc.

**Comment by ryanbrandenburg** [comment]
Not that I'm aware of. If you find any let us know by filing an issue [here](https://github.com/aspnet/Home/issues/new) with the `repo:Localization` label.
