### ISSUE TITLE
ReleaseDate not allowed in DateTime format

### ISSUE THREAD

**Issue by Rakesh6720** [aspnet/Docs#7665]
After initializing migrations and updating the database with the Movie Model, I create a movie from the app.  However, the app will not allow me to submit a release date, no matter what date I enter.  The error in red I receive below the ReleaseDate field is: The ReleaseDate field is required.
To be clear, I have filled out every field, including the Price field with a decimal value of 5.00 and 3.50 on two separate attempts, respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Rakesh6720  decorate with
`        [DataType(DataType.Date)]`

as in 

```
public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
```

**Comment by autoid-lee** [comment]
I had the same error. Although I am using chrome(not sure if it matters) and I saw that there was a colon showing after the date I entered.  I added the time to the end of the date 12:00 AM and it saved.

**Comment by DazzaJ** [comment]
[Display(Name = "Release Date")]
        [DataType(DataType.Date)]
Returns errors on both lines.
Error	CS0246	The type or namespace name 'DisplayAttribute' could not be found (are you missing a using directive or an assembly reference?)
 Needed to add :
using System.ComponentModel.DataAnnotations;
to the top of Movies.cs
ie
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RazorPagesMovie.Models
{
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
}
