### ISSUE TITLE
Document how to customize the view component search path

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#7667]
We have already documented where ASP.NET Core searches for views:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1#view-search-path

We need to add how to customize that search path.

**Comment by pranavkm** [comment]
There was an issue filed to allow further customization here - https://github.com/aspnet/Mvc/issues/6426, although it looks like it was closed by the author. It did seem like triage wanted to consider it for a future release.

**Comment by Rick-Anderson** [comment]
moved to #10385 ****
