### ISSUE TITLE
Page Directive

### ISSUE THREAD

**Issue by louvipi** [aspnet/Docs#7671]
Maybe I was skimming too quickly, but I had to do a serious double take and slow down on the section regarding the page directive,
"Update the Edit, Details, and Delete Razor Pages to use the "{id:int}" route template. Change the page directive for each of these pages from @page to @page "{id:int}"."

It might be helpful to mention that this is at the top/first part of the code.

Nevertheless, thanks for an amazing tutorial.  This stuff just finally might make sense.  MANY THANKS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71b0095-5175-f2e8-1db2-a800e0f77ce2
* Version Independent ID: 6886d687-d6bf-2652-4583-5de7b7353e45
* Content: [Update the generated pages in an ASP.NET Core app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/da1?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/da1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/da1.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@louvipi  thanks for your suggestion.

**Comment by dezryth** [comment]
The section about making the ID optional using @page "{id:int?}" did not work for me. Are you sure this is correct?

**Comment by Rick-Anderson** [comment]
Yes, it's correct.

**Comment by helpimajosh** [comment]
> The section about making the ID optional using @page "{id:int?}" did not work for me. Are you sure this is correct?

Agreed, this part was a little unclear for me, because the behavior is the same (page not found) whether the ID is set to optional or not. Perhaps it would be more helpful to show a scenario in which the ID is optional and leaving it out does not result in a 404, (for example, if the ID is not included, redirect to the index page, or prompt the user to choose a Movie?)

**Comment by Rick-Anderson** [comment]
@page "{id:int}"
https://localhost:44343/Movies/Details/
results in 404 error

@page "{id:int?}"
set break point in Pages\Movies\Details.cshtml.cs
and BP is hit. With @page "{id:int}", BP is not hit.

**Comment by helpimajosh** [comment]
> @page "{id:int}"
> `https://localhost:44343/Movies/Details/`
> results in 404 error and BP in Pages\Movies\Details.cshtml.cs is never hit.
> 
> @page "{id:int?}"
> set break point in Pages\Movies\Details.cshtml.cs
> and BP is hit.

A perfect clarification, thank you!

**Comment by Rick-Anderson** [comment]
@helpimajosh 	thanks.
I'll add this next time I'm updating the doc.
