### ISSUE TITLE
If I want to implement SiganalR on Android, how can I achieve this?

### ISSUE THREAD

**Issue by imfrank** [aspnet/Docs#7672]
Hello           
 In the use of.Net Core, I found that  SignalR doesn't seem to provide support for the Android version. 

If I want to implement SiganalR on Android, how can I achieve this?

**Comment by scottaddie** [comment]
@BrennanConroy or @anurse, Do you have any guidance to provide?

**Comment by anurse** [comment]
The SignalR *client* fully supports Xamarin. Are you seeing errors using it?

**Comment by imfrank** [comment]
@anurse  I tried to request chat hub, but the resulting network request was fed back to http405 error.

**Comment by anurse** [comment]
I'm going to need a lot more detail as to how your server is configured and how your client is written. I suggest you take a look at our Xamarin client sample: https://github.com/aspnet/SignalR-samples/tree/master/Xamarin

If you're still stuck, please collect server and client traces as suggested in the [Diagnostics Guide](https://github.com/aspnet/SignalR/wiki/Diagnostics-Guide) and provide an example of your client and server (Startup, as well as the Hub) code.

We've got examples of SignalR working fine in Xamarin scenarios so we need to try and track down what might be different about your scenario :).

**Comment by Rick-Anderson** [comment]
@anurse do we have a public sample we can point to?

**Comment by anurse** [comment]
Yep, the one I mentioned in my comment: https://github.com/aspnet/SignalR-samples/tree/master/Xamarin

**Comment by tdykstra** [comment]
Closing this, assuming the sample provided in preceding comment helped to resolve the issue.  Feel free to reopen if that is not the case.
