### ISSUE TITLE
This code doesn't run

### ISSUE THREAD

**Issue by JDGHHou** [aspnet/Docs#7684]
There are all kinds of steps missing. I followed these instructions and I get error after error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Windows](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JDGHHou  that tutorial has not been updated for 2.1 yet. Can you try https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1 ?

We've got thousands of users reporting success on that one.

**Comment by PandaWood** [comment]
Actually, I used this tutorial with .NET Core 2.1 and didn't have any issues.

**Comment by Rick-Anderson** [comment]
@PandaWood  Thanks for the comment. You have to make a few adjustments using 2.1
In other words, it's more difficult to follow not being updated.
