### ISSUE TITLE
Different code

### ISSUE THREAD

**Issue by wtilton** [aspnet/Docs#7685]
The documentation refers to points in the code that allow you to enable Server-side rendering. After running 
```
dotnet new angular -o my-new-app
cd my-new-app
```

Startup.cs looks like this 
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.SpaServices.Webpack;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Web
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =&gt;
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapSpaFallbackRoute(
                    name: "spa-fallback",
                    defaults: new { controller = "Home", action = "Index" });
            });
        }
    }
}
```

As you can see there is no "app.UseSpa" anywhere in there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@wtilton What do you see when you run `dotnet --info`. The project template being used here seems older.

**Comment by wtilton** [comment]
I will check when I'm at work on Monday. I was thinking that could be the issue, but I did have Core 2.1 installed.

**Comment by wtilton** [comment]
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

**Comment by scottaddie** [comment]
@wtilton You're using v1.0.4 of the .NET Core SDK. You'll need to install at least v2.0 to take advantage of the server-side rendering feature.

**Comment by wtilton** [comment]
Ok, my bad. I thought I had? Maybe I have to uninstall the earlier versions first.

**Comment by scottaddie** [comment]
@wtilton There's no need to uninstall earlier versions. One of the really cool things about .NET Core is you can run multiple versions side-by-side.

**Comment by wtilton** [comment]
I think I downloaded 2.1 and then ...nothing. My bad. Install and everything is fine. Sorry for wasting your time.

**Comment by scottaddie** [comment]
@wtilton Not a problem. Thank you for letting me know.
