### ISSUE TITLE
why call next() instead of next(context)

### ISSUE THREAD

**Issue by newbienewbie** [aspnet/Docs#7686]
Hi ,
[the Middleware](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index/sample/Culture/StartupCulture.cs#L27) use a `next()` here .  The code is pasted here for convenience
```csharp
 public void Configure(IApplicationBuilder app)
{
    app.Use((context, next) =>
    {
        var cultureQuery = context.Request.Query["culture"];
        if (!string.IsNullOrWhiteSpace(cultureQuery))
        {
            var culture = new CultureInfo(cultureQuery);
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
        }
        // Call the next delegate/middleware in the pipeline
        return next();
    });
    app.Run(async (context) =>
    {
        await context.Response.WriteAsync(
            $"Hello {CultureInfo.CurrentCulture.DisplayName}");
    });
}
```

 I'm wondering why the middleware call a `next()` instead of a `next(context)`
Any Help ? Thanks a lot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher It would be good for me to hear this answer, too, as I'm also wrapping a few brain cells around this. It's obvious that `next` (`Func<Task>`) doesn't accept an HttpContext. Is it because the context is available to all of the delegates in `Configure`, so it isn't necessary for each chained delegate to pass the context to the next one?

**Comment by Tratcher** [comment]
It's just sugar we added so you had one less redundant parameter. The httpContext is captured inside the next func.

**Comment by newbienewbie** [comment]
@guardrex @Tratcher  thanks !

I finally got it by reading [the source code here](https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http.Abstractions/Extensions/UseExtensions.cs#L27]

```csharp
public static IApplicationBuilder Use(this IApplicationBuilder app, Func<HttpContext, Func<Task>, Task> middleware)
{
    return app.Use(next =>
    {
        return context =>
        {
            Func<Task> simpleNext = () => next(context);   // context is captured here !
            return middleware(context, simpleNext);
        };
    });
}
```
the `next` pass to in-line `middleware` is an instance of `Func<Task>` which means it has no context parameter . However , the `next` used in `Use()` method is a `ReqeustDelegate` which means it will receive a context parameter and will be wrapped to `Func<Task>` by : `()=> next(context)` .

**Comment by Rick-Anderson** [comment]
Issue documents what's going on. Thanks for pointing this out.
