### ISSUE TITLE
Will giving the Genre <option>'s "values" make the filtering work?

### ISSUE THREAD

**Issue by johnbyers** [aspnet/Docs#7688]
## General

The tutorial is good, but filtering by Genre doesn't work. I don't think the MovieGenre request parameter ever comes through, since the select `<option>`'s on the page don't have a value.

How can we make the Genre filter work? I think this line:
`
Genres = new SelectList(await genreQuery.Distinct().ToListAsync());
`
needs to be modified to give us both text and a value. How can we do that?

**Comment by scottaddie** [comment]
@johnbyers Please provide a link to the doc you're looking at.

**Comment by johnbyers** [comment]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.1

**Comment by johnbyers** [comment]
I didn't realize this project isn't directly linked to that tutorial page. I will open the issue there, it doesn't make sense here.
