### ISSUE TITLE
Add docker support to React SPA

### ISSUE THREAD

**Issue by Rocinante89** [aspnet/Docs#7696]
Any documentation on how to add a dockerfile to the react SPA templates? I've had a stab at a multistage dockerfile (that i adapted from the eShopOnContainers project) but i'm getting stuck with this error on the RUN dotnet publish -c Release -o /app stage. 

Here's the dockerfile:

`ARG NODE_IMAGE=node:8.11
FROM microsoft/dotnet:2.1-sdk AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk as dotnet-build
WORKDIR /src

FROM ${NODE_IMAGE} as node-build
WORKDIR /web
COPY src/Web/App/ClientApp .
RUN npm install
RUN npm run build

FROM dotnet-build as publish
WORKDIR /src/src/Web/App/ClientApp
COPY --from=node-build /web/build .
WORKDIR /src
COPY . .
WORKDIR /src/src/Web/App
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "react.dll"]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
We don't currently have any docs for it, since it's not supported in VS. The templating team does, however, have an issue to track enabling this scenario. See https://github.com/aspnet/Templating/issues/483.

**Comment by Rocinante89** [comment]
Thanks!
