### ISSUE TITLE
Deleting the last todo creates a new default todo, causing confusion

### ISSUE THREAD

**Issue by jwbrady** [aspnet/Docs#7699]
Because this example adds a default todo whenever there are no todos, you can't delete all the todos and makes you think it isn't working.

Seeding was discussed [here](https://blogs.msdn.microsoft.com/dotnet/2016/09/29/implementing-seeding-custom-conventions-and-interceptors-in-ef-core-1-0/). Surprised there isn't a better article on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
This topic sample was apparently created before we instituted a better approach to seeding. Next, we're planning to update seeding to an even better approach based on a new seeding scenario in EF Core.

I'll cross-reference this issue on that one to make sure this sample gets the updates. Thanks for calling this one out. If you hadn't said anything, it might have slipped through the cracks.
