### ISSUE TITLE
Add more complete next steps to the end of this series.

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/Docs#7700]
I really enjoyed this tutorial, and I'm glad it recommends a good follow-up to the tutorial at the end, but the last step is missing something pretty important: what would you do if you wanted to take this further (i.e. to production)? During the tutorial it talks about setting up LocalDB, etc., and at the end it links to instructions on how to publish this app to Azure, but it is missing key details (advice, really) on how to fill in the gap between a tutorial and a production application. Further, I think many of the steps in this tutorial could benefit from a "going further" section at the bottom of each page that would help you push this specific tutorial a little further, to build on what is taught and provide even more useful knowledge so that developers can hit the ground running after going through a few of these tutorials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@KirkMunro fyi ... @Rick-Anderson is OOF until Monday, so there might be a short delay getting back to you on this.

**Comment by KirkMunro** [comment]
No problem for the delay @guardrex, and thanks for the heads up.

**Comment by KirkMunro** [comment]
Here are a few specific sentences from some of the ASP.NET Core Razor Pages tutorials that raise questions without really providing answers or directions:

> Some developers use a service layer or repository pattern in to create an abstraction layer between the UI (Razor Pages) and the data access layer.

That's a great tip, but it doesn't come with any links or documentation or references. At the end of the tutorial where this is mentioned (the 2nd part of the 2nd ASP.NET Core Razor Pages tutorial), it would be great to call that suggestion out specifically, with docs/instructions that help you apply a service layer or repository pattern to do exactly what is described here.

> LocalDB is a lightweight version of the SQL Server Express Database Engine and is intended for app development, not production use.

Also a great point. This one was included in both Razor Pages tutorials I've gone through. Yet at the end, where is the guidance for someone completely new to this to move the tutorial they've built into production so that they can learn not only the differences between the two, but how to evolve from one into the other.

There are more examples, but I wanted to call out these ones specifically so that you have context for the issue described here.

**Comment by guardrex** [comment]
> repository pattern

That will be a standalone topic after https://github.com/aspnet/Docs/pull/7412 is merged. Today, it's in the DI topic, but we don't want to link that now given the impending changes.

**Comment by guardrex** [comment]
I added it to that PR. Thanks for noting it ... I found a few other places to cross-link it as well.

**Comment by Rick-Anderson** [comment]
@KirkMunro  the first recommendation at the end is 
Get started with Razor Pages and EF Core shows advanced EF Core operations with Razor Pages.

That should cover your request for *I think many of the steps in this tutorial could benefit from a "going further" section at the bottom of each page*

**Comment by KirkMunro** [comment]
@Rick-Anderson I'm not so sure I agree. That second tutorial helps learn some new content, and repeats some of what is learned in the first tutorial (which is not a bad thing). But I still feel tutorials like these (both of them) need to do more to guide users further. Think of it like a Choose Your Own Adventure book.

Do you want to learn more about ASP.NET Core 2.1 and what you can do with Razor Pages and EF Core? Take the "Get started with Razor Pages and EF Core" tutorial to continue learning more.

Do you want to know what would be required to take your RazorPagesMovie app to production? Go to this page to learn more about next steps you could take with the web application you just built.

Do you want to add more functionality to your RazorPagesMovie app? Go to...

Do you get the idea? You can't possibly know the skill level of a developer going through a tutorial like this, nor the needs of that developer, but by providing multiple options at the end (not just linking to documents -- context sensitive options) will likely do a better job helping them get to where they are trying to reach by going through the tutorial in the first place.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
