### ISSUE TITLE
Create full identity UI source >> EmailSender is inaccessible

### ISSUE THREAD

**Issue by DMcHd** [aspnet/Docs#7703]
I am trying to get full control of the Identity UI and I ran the Identity scaffolder. I follow all the steps and i got this error:
Error CS0122 'EmailSender' is inaccessible due to its protection level.
May i have your advice?
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@DMcHd fyi ... @Rick-Anderson is OOF until Monday, so there might be a short delay getting back to you.

**Comment by DMcHd** [comment]
Okay, but.. 
is there any example without using SendGrid as the email provider? like.. the standard system.net.mail ?
