### ISSUE TITLE
Where can I ask questions about HubContext Send messages from outside a hub sample?

### ISSUE THREAD

**Issue by Carneno** [aspnet/Docs#7704]
Hello,

Can I ask questions here about why the sample program presented at this [tutorial](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1) is not working?

Thanks,
Tony

**Comment by guardrex** [comment]
@Carneno Go ahead ... some of the engineers working on SignalR do monitor the issues here.

**Comment by Carneno** [comment]
Thank you.

The main issue I am having is I can't get that sample to show a hub message as expected.

I have tried it in Mozilla Firefox, Internet Explorer and Microsoft Edge.

I did not change any of the code.  I have tried clearing all my caches, cookies and temporary files.  I have tried restarting my system.

It looks like it is supposed to show "Home page loaded at: {DateTime.Now}".  I have not been able to see anything like that.

Thanks,
Tony

**Comment by guardrex** [comment]
cc/ @BrennanConroy

**Comment by mikaelm12** [comment]
I'll take a look!

**Comment by Carneno** [comment]
Hello Mikael.

Have you had a chance to look at this yet?

Thanks,
Tony

**Comment by mikaelm12** [comment]
Hi @Carneno , sorry things are a little different since it's Microsoft's hackathon week so regular work is basically on pause

**Comment by Carneno** [comment]
Thank you Mikael.

Keep up the good work.

**Comment by BrennanConroy** [comment]
Should be able to close this, discussion was moved to https://github.com/aspnet/SignalR/issues/2688
