### ISSUE TITLE
npm install @aspnet/signalr

### ISSUE THREAD

**Issue by freerider7777** [aspnet/Docs#7705]
For current version (1.0.2)
install tslib is also needed :)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1#connect-to-a-hub)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@anurse  please comment

**Comment by anurse** [comment]
See https://github.com/aspnet/SignalR/issues/2410

**Comment by freerider7777** [comment]
Yep, this issue.
BTW guys, could you add a section how to set up reconnection if server is temporary down? (Or make a new issue for this?)

**Comment by anurse** [comment]
#6757 is tracking this. That bug also includes a sample you can review while we work on improving this documentation.
