### ISSUE TITLE
Edit and Continue with Windows host to Linux container

### ISSUE THREAD

**Issue by djhmateer** [aspnet/Docs#7707]
I've been unsuccessful getting Edit and Continue mentioned above working.

Windows 10 host to Linux container using ASP.NET Core 2.1 being able to update a .cshtml and see the changes in the browser (after doing F5 in browser) without doing a Ctrl F5 in Visual Studio.

Details of what I did are in: https://stackoverflow.com/questions/51441893/visual-studio-2017-docker-edit-and-continue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1#edit-and-continue)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@spboyer is edit/continue supported?

**Comment by djhmateer** [comment]
Found that an MVC project works fine, but razor pages project doesn't.

**Comment by spboyer** [comment]
@danroth27

**Comment by scottaddie** [comment]
@danroth27 Is there a difference in Razor SDK behavior between Razor Pages and MVC? It's interesting that this would work for MVC but not Razor Pages.

**Comment by danroth27** [comment]
> s there a difference in Razor SDK behavior between Razor Pages and MVC? It's interesting that this would work for MVC but not Razor Pages.

Not that I can think of. 

@ToddGrun @pranavkm Any ideas on this one?

**Comment by djhmateer** [comment]
Updated the SO question with more detail. Essentially

dotnet new mvc - works
dotnet new razor - doesn't work. 

docker run --rm -it -p 8000:80 -v %cd%:/app/ -w /app/aspnetapp microsoft/dotnet:2.1-sdk dotnet watch run --no-launch-profile

**Comment by Rick-Anderson** [comment]
@ToddGrun @pranavkm  please review

**Comment by mkArtakMSFT** [comment]
Moving this to `aspnet/mvc` repo for investigation.

**Comment by scottaddie** [comment]
@mkArtakMSFT Do you have an issue in that repo we can link to? I didn't see one.

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/Mvc/issues/8173 for further investigation.
