### ISSUE TITLE
Add ASPNETCORE_HTTPS_PORT to this doc for https redirection middleware

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#7711]
We need guidance on how to setup proxies for https redirection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti Should I link over to the content from the proxy/LB topic? Link to ...

* https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx#configure-ssl
* https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-apache#ssl-configuration

**Comment by guardrex** [comment]
@shirhatti Nevermind ... missed ur title. I'll take care of it.

**Comment by guardrex** [comment]
Looks like overlap with https://github.com/aspnet/Docs/issues/6538.

**Comment by shirhatti** [comment]
Whoops, my bad. I'd remembered filing a bug before but I couldn't find it via search.

**Comment by guardrex** [comment]
No worries ... I was about to suggest to `@Rick-Anderson` and @scottaddie that the P4s are piling up to such a degree that they're interfering with issue searches.

Issue search is rapidly becoming 👊 *hand-to-hand combat* 👊.
