### ISSUE TITLE
Brotli compression

### ISSUE THREAD

**Issue by aligneddev** [aspnet/Docs#7715]
Sonarwhal.com is telling me to use Brotli and/or Zopfli compression. It'd be great to have an official example of Brotil and Zopfli if available. I've found one here: https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.1&tabs=aspnetcore2x.

https://sonarwhal.com/docs/user-guide/rules/rule-http-compression/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response Compression Middleware for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Looks like it's coming down the pipe for 2.2.

https://github.com/aspnet/BasicMiddleware/pull/342
