### ISSUE TITLE
For the delete error example, it would be better to provide a scenario that developers can reproduce/see in action

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/Docs#7718]
In the https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#the-delete-pages-onpostasync-method section, this tutorial talks about delete anomalies that can occur, with transient network errors. Yet you can't reproduce that. What about extending this to also include an example that shows the dynamic delete error text in action? For example, open two tabs on the Student index page, click on Delete next to the same student in each tab, then on one page click the Delete button. Once that finishes, on the other page, click the Delete button. The Student no longer exists at this point, so a 404 is returned. I think it would be more impactful to display an appropriate error message when Delete is clicked and the Student no longer exists as part of this tutorial first. Then talk about possible errors that can occur in the cloud and how to handle them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#the-delete-pages-onpostasync-method)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@KirkMunro I think I do that later in the tutorial.

**Comment by Rick-Anderson** [comment]
@KirkMunro let me know of part 8 doesn't do that and i'll reopen this issue.

**Comment by KirkMunro** [comment]
Will do, thanks @Rick-Anderson.
