### ISSUE TITLE
Async Result<T> applies ProducesResponseType(201)

### ISSUE THREAD

**Issue by Deegava** [aspnet/Docs#7723]
The AsyncResult&lt;T&gt; section states "The [ProducesResponseType] attribute's Type property can be excluded" and then goes on to use them in it's example code. his is confusing - should the be used or not and if not why not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa03501b-5e71-4c18-0269-39babbf9d93c
* Version Independent ID: b51bc104-a6e2-b21f-8362-45cee22e8c22
* Content: [Controller action return types in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/action-return-types.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/action-return-types.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by martyngta** [comment]
I think the comment is referring to the "Type = typeof(Product)" portion of the attribute not the usage of the attribute itself.  You don't need to provide this information because the compiler / runtime can infer the type from the generic specified on the return type.

**Comment by scottaddie** [comment]
@martyngta is correct with that explanation. I'm updating the doc to make this clearer.
