### ISSUE TITLE
CourseAssignment vs CourseInstructor

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/Docs#7725]
What this tutorial fails to mention (or recognize?) is that CourseAssignment isn't necessarily the best name for the many-to-many relationship between courses and instructors in a system that reports grades that students receive for courses, where they will inevitably have course assignments. See what I'm getting at? It's a tutorial that recommends CourseAssignment as a better name than CourseInstructor, recommending that join relationship table names describe what they do rather than simply represent the entities they join, yet in this case I feel they are one and the same: CourseInstructor represents the entities that they join _and_ what the join does (identifies the instructor for a course). Maybe this point would be better illustrated using InstructorAssignment, which leaves CourseAssignment open for future use (when you want to define multiple assignments offered in a course, and then track student scores on them)? There may be no action here, I just wanted to offer my thoughts on this because CourseAssignment felt misleading to me when I went through this content for the reasons described here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@KirkMunro  we had an extensive debate on this years ago. It could be debated forever.
cc @tdykstra
