### ISSUE TITLE
Warning provided too late to do anything about it

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/Docs#7728]
At the end of this part of the tutorial, you talk about an optional step that can be used to fix a foreign key constraint with legacy data. That section includes the following warning:

&gt; Don't make these code changes if you completed the previous section and updated the database.

Unfortunately, by the time you get here, if you're following along all of the steps in the tutorial, you have already updated the database, and so there's not really any way for you to proceed with this optional content. Perhaps you could move this section earlier in the tutorial, or call out the optional section higher up in the tutorial, and use anchor links to take learners to the optional section, and then back to where they should be once they have completed that section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@KirkMunro  we'll fix this in the next sweep.

**Comment by bill1109** [comment]
I ran into the same issue and couldn't continue with scaffolding the Pages.Instructors pages... what could I have done to have continued with the tutorial at this point?  I'd like to understand and learn how this may have affected the scaffolding?

**Comment by Rick-Anderson** [comment]
@bill1109  the optional section has nothing to do with https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-instructor-model

**Comment by bill1109** [comment]
I get that... but when I scaffolded the Pages.Instructors prior to correcting all the original entities in the DbContext from singular to plural Pages.Instructors.Index.cshtml.cs was created as:

namespace ContosoUniversity.Pages.Instructors
{
    public class IndexModel : PageModel
    {
        private readonly ContosoUniversity.Data.SchoolContext _context;

        public IndexModel(ContosoUniversity.Data.SchoolContext context)

I then changed it to be consistent with Pages.Students.Index.cshtml.cs and Pages.Courses.Index.cshtml.cs as below and it seems to be Ok now... 

My Question would be with how the scaffold process establishes/gets the location of the DbContext in the project?

Thanks in advance for your help... the tutorial has been a big help for me!

namespace ContosoUniversity.Pages.Instructors
{
    public class IndexModel : PageModel
    {
        private readonly ContosoUniversity.Models.SchoolContext _context;

        public IndexModel(ContosoUniversity.Models.SchoolContext context)

**Comment by Rick-Anderson** [comment]
@bill1109  the `DbContext` is a parameter to the scaffolder.
