### ISSUE TITLE
Issue #7600 should not be closed, because it is not resolved

### ISSUE THREAD

**Issue by KirkMunro** [aspnet/Docs#7729]
@Rick-Anderson: #7600 is not resolved. If learners go through this tutorial following the Visual Studio steps (not the dotnet cli steps), they will run into the same issue described in #7600 when they get to this part of the tutorial. For some reason, at this point in the tutorial you instruct users to close Visual Studio and work from the command line, but they aren't properly set up to work from the command line, even with the update you made to "resolve" #7600. You really need to work out what is missing from the dotnet command line tasks for users who have used Visual Studio/PowerShell when presented with an option between that and dotnet CLI once they arrive at this step; otherwise they'll simply be stuck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1#scaffold-the-course-model)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by KirkMunro** [comment]
FYI, I went back to [this tutorial section](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-student-model) and repeated those steps, using the Course model instead, to work around this issue (i.e. create a Pages/Courses folder, then follow those earlier steps, using the Course model when generating the scaffolding).

**Comment by KirkMunro** [comment]
It's missing the choice between Visual Studio and the dotnet CLI, providing the exact same instructions that are offered [here](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-student-model), but instructing users to use the Course model instead of the Student model. The dotnet CLI instructions really only work if you started using them from the beginning of the tutorial.

**Comment by Irene726** [comment]
Hi Kirk, I replied to one of your posts previously regarding this issue. Were you able to see my response?

**Comment by Irene726** [comment]
I agree with you that this issue should not be closed. Kirk, I tried to scaffold the Course model following the instructions you sent and I got this error instead (See second image below). Any ideas on how to fix this?
![1](https://user-images.githubusercontent.com/41277836/43554425-95ed4e80-9637-11e8-9bb1-1287ba8723a0.JPG)
![2](https://user-images.githubusercontent.com/41277836/43554426-96240b96-9637-11e8-95b9-be4e9aefd0be.JPG)

**Comment by Rick-Anderson** [comment]
The instructions have been updated. Your project file is incorrect.

**Comment by Irene726** [comment]
I have followed the updated instructions and that is the error its giving me. Project file is not incorrect. Please see screenshots attached in my previous message.

**Comment by Rick-Anderson** [comment]
That's not correct. Project file should be
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.2" />
  </ItemGroup>

</Project>
```

Do you have the .NET Core SDK 2.1 installed?

**Comment by Irene726** [comment]
Just letting you know that I resolved the issues that I was having with the scaffolding of the Course model and I was able to finish the whole Razor pages with EF Core in ASP.NET Core tutorial thanks to the tutorial updates. Thank you for all the help Kirk and Rick, really appreciate it.
