### ISSUE TITLE
project.json dependencies Article

### ISSUE THREAD

**Issue by ardalis** [aspnet/Docs#773]
@danroth27 
Where should the dependencies section be covered in more depth? Currently we have
/dnx/diagnosing-project-dependency-issues.html #200 but I think we need an overview before we send people to a topic on diagnosing problems,

and some coverage in 
https://docs.asp.net/en/latest/conceptual-overview/understanding-aspnet5-apps.html

I'd like to add a link from the Understanding ASP.NET 5 Web Apps article to learn more about project.json dependencies (including wildcard behavior, tooling support, and probably project.lock.json).

**Comment by danroth27** [comment]
There is a bunch of stuff in the [Working With DNX Projects](https://docs.asp.net/en/latest/dnx/projects.html#adding-dependencies) article. But all of the DNX content will be moving out of the ASP.NET docs now that we are moving to the new [.NET CLI](https://github.com/dotnet/cli).

**Comment by danroth27** [comment]
Closing since we are not adding more DNX docs to the ASP.NET site.
