### ISSUE TITLE
Permission to use your data model illustration

### ISSUE THREAD

**Issue by kkagill** [aspnet/Docs#7738]
Hi,

Thanks for this top quality tutorial. 
I'm just wondering if I am allowed to use the data model image on the very top of the page for an online asp.net core course which is going to be introduced to programmers in South Korea. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [ASP.NET Core MVC with EF Core - Data Model - 5 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-2.0#fluent-api-alternative-to-attributes)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @kkagill The docs are provided under the CC license, and by 2(a)(1)(a) and 2(a)(1)(b) you are allowed to ...

> reproduce and Share the Licensed Material, in whole or in part; and

> produce, reproduce, and Share Adapted Material.

Modifications are allowed under 2(a)(4).

Section 3 covers attribution, and CC recommends text along the lines of this (this is just a suggestion) ...

Markdown version:

> \[ASP.NET Core MVC with EF Core - Data Model: Entity diagram](https://docs.microsoft.com/aspnet/core/data/ef-mvc/complex-data-model) by \[T. Dykstra](https://github.com/tdykstra)/[R. Anderson](https://twitter.com/RickAndMSFT) is licensed under \[CC BY 4.0](https://github.com/aspnet/Docs/blob/master/LICENSE)

HTML version:

> \<a href="https://docs.microsoft.com/aspnet/core/data/ef-mvc/complex-data-model">ASP.NET Core MVC with EF Core - Data Model: Entity diagram\</a> by \<a href="https://github.com/tdykstra">T. Dykstra\</a>/\<a href="https://twitter.com/RickAndMSFT">R. Anderson\</a> is licensed under \<a href="https://github.com/aspnet/Docs/blob/master/LICENSE">CC BY 4.0\</a>

... which would render with the links like this ...

> [ASP.NET Core MVC with EF Core - Data Model: Entity diagram](https://docs.microsoft.com/aspnet/core/data/ef-mvc/complex-data-model) by [T. Dykstra](https://github.com/tdykstra)/[R. Anderson](https://twitter.com/RickAndMSFT) is licensed under [CC BY 4.0](https://github.com/aspnet/Docs/blob/master/LICENSE)

Sometimes, the alt text of an image is a title. The image you're asking about does have a title, "Entity diagram." You'll find that we often have an image description in the alt attribute and not a title. If the image has no title, I recommend just linking the topic title.

For more information, see:

* https://github.com/aspnet/Docs/blob/master/LICENSE
* https://wiki.creativecommons.org/index.php/Best_practices_for_attribution

**Comment by kkagill** [comment]
Thanks a lot! Good that I'm allowed to share and reproduce. The image is going to be used for educational purposes. I'll make sure to include the link.
