### ISSUE TITLE
Fails to build : value of type 'Microsoft.Extensions.Primitives.StringSegment' cannot be converted to 'System.string'

### ISSUE THREAD

**Issue by Praveen-Rai** [aspnet/Docs#7742]
## General

There are lot of instances of 'Microsoft.Extensions.Primitives.StringSegment' referred in MultipartRequestHelper.cs and StreamingController.cs where string operations such as "string.IsNullOrEmpty()" are being applied on StringSegment. More specifically properties of ContentDispositionHeaderValue are of type StringSegments.

**Comment by guardrex** [comment]
Thanks @Praveen-Rai ... yes ... I think in these cases pulling a [Value](https://docs.microsoft.com/dotnet/api/microsoft.extensions.primitives.stringsegment.value) will do the trick prior to the conditional looking at it.

Are you referring to the *File uploads* topic here? https://docs.microsoft.com/aspnet/core/mvc/models/file-uploads

There's an open issue to overhaul that topic on #5331. I'll add this to the list there.

**Comment by Praveen-Rai** [comment]
@guardrex Yes, i am referring to the article that you pointed. I am glad to learn that the topic is being overhauled and lot of amazing stuff is already suggested by you and others #4777 (Thanks for bringing up Chunk and Byte-Range. Being a beginner i didn't even knew that they exist ;-)). Looking forward to see the new articles.

**Comment by Rick-Anderson** [comment]
CLosing as dup of #5331
