### ISSUE TITLE
"Unable to launch the IIS Express Web server"

### ISSUE THREAD

**Issue by rfbu** [aspnet/Docs#7747]
I followed the steps in "Add EF tooling and perform initial migration". However, I ran into issues as mentioned in the title. To resolve it, I had to reboot my machine.

Please review the tutorial to provide a better learning experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1#add-ef-tooling-and-perform-initial-migration)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rfbu  this happens occasionally and is usually fixed by exit/restart VS.  You might want to open a bug with the Visual Studio team.
