### ISSUE TITLE
ASPNET_ENV is now Hosting:Environment

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#775]
This needs to be addressed in the [Working with Multiple Environments](http://docs.asp.net/en/latest/fundamentals/environments.html) article.

**Comment by ardalis** [comment]
Is that new name being used on all platforms? I saw in another issue a user stated Hosting__Environment was being used on non-Windows platforms.

**Comment by danroth27** [comment]
Duplicate of #706
