### ISSUE TITLE
dotnet add package steps missing

### ISSUE THREAD

**Issue by NathanMCarlson** [aspnet/Docs#7752]
I see these items addressed in odd ways in the closed issues- but there are some steps missing. You don't need to hand-edit the csproj file; though maybe that has changed since release?

dotnet add package Microsoft.EntityFrameworkCore.SQLite
(this will fix the SQLite dependency problems)
dotnet add package Microsoft.EntityFrameworkCore.Tools.DotNet
(I think this is preferable to the instructions to modify the csproj file directly)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by NathanMCarlson** [comment]
Also had to do this:

dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Tools

Then update the versions in the second section... and yes, turns out I did have to edit the csproj file. Seems like that should be part of the command-line options.

**Comment by Rick-Anderson** [comment]
@NathanMCarlson  thanks for pointing this out. The document is out of date. I think the best way to fix this is to combine it with the VS version of the document and have tabs for using VS, VS Code.

**Comment by MrArca9** [comment]
Took me a while to figure out this issue, would recommend a quick edit at the beginning when creating the project folder.
