### ISSUE TITLE
Error Scaffolding from command line

### ISSUE THREAD

**Issue by srifellc** [aspnet/Docs#7755]
When I run:
dotnet aspnet-codegenerator razorpage -m Department -dc SchoolContext -udl -outDir Pages\Departments --referenceScriptLibraries

I get an error message that says "No executable found matching command "dotnet-aspnet-codegenerator"

I can scaffold the pages in VS to get around the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@srifellc  See #7760 which should solve the problem. We should probably update the tutorials to say use VS scaffolding if that's what you've been doing.

**Comment by Rick-Anderson** [comment]
@srifellc  when you were in https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data did you use the VS Scaffolder?

**Comment by srifellc** [comment]
The first line:
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration.Design --version 2.1.0

ran with no errors
but the second line:
dotnet aspnet-codegenerator razorpage -m Course -dc SchoolContext -udl -outDir Pages\Courses –referenceScriptLibraries

Failed with the same error.
When it didn’t work, I just used the same process as described at https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-student-model

Oddly the error message returns the command name “dotnet-aspnet-codegenerator”, not “dotnet aspnet-codegenerator”.  It looks like a the code generation program is not installed.
