### ISSUE TITLE
Document Nuget package name containing AddHttpClient extension

### ISSUE THREAD

**Issue by kevbry** [aspnet/Docs#7762]
New ASP.Net Core 2.1 projects targeting full framework created using Visual Studio 2017 Enterprise project templates do not reference the Microsoft.Extensions.Http package by default, and therefore services.AddHttpClient does not work out of the box. The documentation should specify which NuGet package needs to be installed for users targeting the full framework.

This isn't just an issue with this particular feature - most of the documentation seems to assume that the user is running on .net core using Microsoft.AspNetCore.App and does not specify the NuGet package that must be installed if one is not using that metapackage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Initiate HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@kevbry Thank you for pointing this out. You're correct that many of the docs assume a target framework of .NET Core. This is a problem we're aware of and are slowly addressing.

**Comment by kevbry** [comment]
Thank you very much for the quick fix. It's great to hear that it's on the radar. 

Not exactly related, but thank you for the fantastic docs around ASP.Net Core Data Protection - they're some of the best I've read for any product. Having the design rationale is super helpful.

**Comment by scottaddie** [comment]
@kevbry Thank you for the kind words. This fix will go live within the next hour.
