### ISSUE TITLE
Is there a way to Create full identity UI source first and then Customize Identity? Because maybe in the future I need to modify my model.

### ISSUE THREAD

**Issue by YeyoCoder** [aspnet/Docs#7764]
I am a little confuse. If I create an MVC with Authentication: **Individual User Accounts**. I scaffold it following the steps of [Scaffold identity into an MVC project with authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio#scaffold-identity-into-an-mvc-project-with-authorization) then I try to [Customize Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1#customizing-the-model)  but always get errors ( `InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager``1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.` was the most common).
So I have to create a new project and [Customize Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1#customizing-the-model) first and then [Create full identity UI source](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio#scaffold-identity-into-an-mvc-project-with-authorization). Now my app is working! 

Is there a way to [Create full identity UI source](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio#scaffold-identity-into-an-mvc-project-with-authorization) first and then [Customize Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1#customizing-the-model)**?** Because maybe in the future I need to modify my model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a25f836-b946-9056-5fbc-1b47ff72efd0
* Version Independent ID: 5d189a96-a529-6afa-e05d-85cfa05c5c9f
* Content: [Identity model customization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/customize_identity_model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/customize_identity_model.md)
* Product: **aspnet-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by YeyoCoder** [comment]
When necessary I will open this.

**Comment by plus1319** [comment]
same problem , but does'nt work for me when I scaffold UI identity
