### ISSUE TITLE
Very minor issue

### ISSUE THREAD

**Issue by ciaran036** [aspnet/Docs#7768]
The formatting of the code sample for the ViewData attribute is a bit wonky/off. accidentally is also spelled as "accidently". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e47828-6da8-2323-053f-dcbf7475b1b6
* Version Independent ID: 62d4c2be-4233-64e1-2a3d-8a5e98d9d941
* Content: [Views in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/overview?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/overview.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@ciaran036 Thank you for reporting the spelling mistake. The code formatting issue you point out is known and is being tracked internally. See https://github.com/aspnet/Docs/issues/6052.
