### ISSUE TITLE
Example Image doesn't make it clear that Release Date field requires date as well

### ISSUE THREAD

**Issue by hkalia** [aspnet/Docs#7774]
The Example image showing how to test the Create Link with Title "The Good, the bad, and the ugly" gives the impression that when copied exactly it will create an entry in the database. However, once you click Create, it will give the error "The ReleaseDate field is required" since the date and time are both required. Simply, change the image to a screenshot of ReleasDate field filled with both date and time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hkalia  I think I'll introduce the Date attribute sooner so you won't have to enter time.

**Comment by Rick-Anderson** [comment]
Dup of #7665
Will fix in next release.
