### ISSUE TITLE
AddCors in Startup ConfigureServices

### ISSUE THREAD

**Issue by srifellc** [aspnet/Docs#7775]
This is my first exposure to SignalR and I followed the example.  The services.AddCors in the Startup ConfigureServices is show in the example, but it is not highlighted in yellow as code to add.  The lines for CORS are not part of the template and on my first go around, I did not add them.  The chat did not work.  I did figure out what was wrong, but I thought you might like to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@srifellc Can you tell me a little more about what happens without CORS - are you using VS or VS Code, what browser are you using, what error do you see in browser dev tools?  I've run through the tutorial with both VS and VS Code, using Edge, Chrome, and Firefox, and it works for me with the template code without adding CORS.

**Comment by tdykstra** [comment]
Closing, as I can't repro the problem.
