### ISSUE TITLE
Is it possible to use RCL with MVC with dotnet watch run with recompiling changed templates?

### ISSUE THREAD

**Issue by PudottaPommin** [aspnet/Docs#7783]
Hey,

I tried to separate templates from .net core MVC app, but I could not get working updating page after change of templates. It served files, which were compiled at the moment of initial run.

Is it supported or will be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You need to make sure the new RCL build is loaded.

**Comment by MichalHanajik** [comment]
Well, yes, but I could not figure how. Can you point me?

**Comment by Rick-Anderson** [comment]
@pranavkm I noticed when writing the article it was sometimes difficult for a project to load the updated RCL library. Can you suggest how to get this working with dotnet watch?

**Comment by GerardSmit** [comment]
I also ran in this issue, any solutions to this?

**Comment by pranavkm** [comment]
See the discussion here - https://github.com/aspnet/Razor/issues/2426

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
