### ISSUE TITLE
In ASP.NET Core 2.x, the [Authorize] attribute requires additional configuration in Startup.cs to challenge anonymous requests for Windows authentication.

### ISSUE THREAD

**Issue by stevozilik** [aspnet/Docs#7789]
Can you please point to any resources describing how to do this, I can't figure out how to trigger the challenge. Using .UseHttpSys(options =&gt;
            {
                options.Authentication.Schemes = 
                    AuthenticationSchemes.NTLM | AuthenticationSchemes.Negotiate;
                options.Authentication.AllowAnonymous = true;
            })

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @stevozilik -- Hypothetically for HTTP.sys self-hosted, it's ...

```csharp
services.AddAuthentication(HttpSysDefaults.AuthenticationScheme);
```

... in `Startup.ConfigureServices`.

For IIS hosting, it would be ...

```csharp
services.AddAuthentication(IISDefaults.AuthenticationScheme);
```

... in `Startup.ConfigureServices`.

Are either of these (depending on how you're hosting) not working for you?

**Comment by guardrex** [comment]
There are couple of related sections in the IIS topic. For example ...

Step 5 of https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis#iis-configuration

Automatic auth should default to `true`, so you shouldn't need to do anything on that count ... https://docs.microsoft.com/aspnet/core/host-and-deploy/iis#iis-options

**Comment by guardrex** [comment]
Although the cross-link to the IIS topic is present, I feel the topic could use an *Additional resources* section with at least this link (perhaps more) to better surface the content. Because the IIS topic is so long, I'll link to the relevant sections instead of the entire topic.

**Comment by dotNetAthlete** [comment]
The Angular and Web API tutorials also fail to emphasize this important topic and you only start to look at this after your [Authorize] attribute on your controller methods causes a 500 internal server error !
