### ISSUE TITLE
HPV low CSAT

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#7790]
HPV low CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@Rick-Anderson Didn't @guardrex handle this with https://github.com/aspnet/Docs/pull/7412?

**Comment by guardrex** [comment]
I hope so. 🤞 I'm still waiting on engineering; but with hackathon, we might be looking at next week for more engineering feedback.
