### ISSUE TITLE
Missing info about multiple inline constraints

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Docs#7793]
The routing doc is excellent, but it lacks information if a user can specify multiple inline route constraints and how or if the framework is only limited to 1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
Paging @rynowak

**Comment by rynowak** [comment]
hi

**Comment by scottaddie** [comment]
@rynowak Does the framework enforce a limit on the number of inline route constraints?

**Comment by rynowak** [comment]
`/{x:int:regex(...)}`

**Comment by rynowak** [comment]
I'm not sure that there's a limit.
