### ISSUE TITLE
Recommendation for Ignoring CS1591 Warning (XML comments)

### ISSUE THREAD

**Issue by mmillican** [aspnet/Docs#7795]
In my project, I enabled XML docs to enhance the Swagger output, which obviously renders warnings for all public members that don't have XML docs on them.  The docs talk about ignoring all `CS1591` warnings at the project level (in `.csproj`). However, If you want to ensure your public members have documentation, this isn't a great approach. 

My approach was to add `#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member` around my `Program` and `Startup` classes. For example:

```
namespace MyApi
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .Build();
    }

#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}
```

Note that doing including the disable tag does not seem to work as it does not throw warnings for other members in the project that are missing docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@mmillican As discussed via Slack, we'll look for a PR from you to address this.

**Comment by LeonardoDaLuz** [comment]
This problem is completly annoing and hard to rid. 
These warnings are more of a hindrance than a help.
