### ISSUE TITLE
await movies.ToListAsync() redundant?

### ISSUE THREAD

**Issue by feynmanliang** [aspnet/Docs#7796]
In the first code snippet, it seems the construction of the Task and the subsequent await can be simplified to a single blocking call to movies.ToList(); am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by theitsloth** [comment]
Blocking calls take up threads while waiting for the database query to complete, so you shouldn't use them at all.

**Comment by feynmanliang** [comment]
I agree, but the `await` in 
```
Genres = new SelectList(await genreQuery.Distinct().ToListAsync())
```
already makes this blocking (within the `Task`). What I'm proposing is that we rewrite this as
```
Genres = new SelectList(genreQuery.Distinct().ToList());
```

In other languages, lifting into an async task and then directly awaiting it it is considered poor practice (e.g. https://eslint.org/docs/rules/no-return-await).

**Comment by theitsloth** [comment]
I think awaiting the async call will break up the function into two parts and still free up the thread while the program is waiting for a response, whereas a synchronous call will hold up the thread.

**Comment by feynmanliang** [comment]
Thanks for the help! I think I understand what you're saying. The `await` yields control flow to the caller of `OnGetAsync`, effectively breaking the function up into coroutines than can be scheduled at different times rather than one large synchronous computation. Is that right?
