### ISSUE TITLE
Section "Mark page properties required"

### ISSUE THREAD

**Issue by reponemec** [aspnet/Docs#7807]
Have a look at https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio#mark-page-properties-required.

It looks it's not working in razor pages. Although the required property Color comes as null into the OnPostAsync, ModelState.IsValid is still true.

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/7806
