### ISSUE TITLE
Add-Migration initial error

### ISSUE THREAD

**Issue by Akramshenoda** [aspnet/Docs#7808]
following the article steps but i got an error in all CRUD pages says "Movie is namespace but it used like type"
when I'm trying to execute Add- migration initial I got "Build failed" any help?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Akramshenoda  compare your code to the download code to figure out what you did wrong.

**Comment by Rick-Anderson** [comment]
@Akramshenoda  is exactly right.  You could try starting over and carefully following the directions.
