### ISSUE TITLE
Can not access swagger when deploy to ubuntu

### ISSUE THREAD

**Issue by taivt0109** [aspnet/Docs#7809]
I have an issue with NGINX.
After I installed Swashbuckle.AspNetCore (3.0.0) and deployed to Ubuntu server.
I can not access to http://mydomain/swagger
this is my config on DOTNET core (version 2.1)

       // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "Test API", Version = "v1" });
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), 
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
                c.RoutePrefix = "swagger";
            });
            app.UseMvc();
        }

Nginx config:

	user www-data;
	worker_processes auto;
	pid /run/nginx.pid;
	include /etc/nginx/modules-enabled/*.conf;
	events {
			worker_connections 768;
			# multi_accept on;
	}

	http {
			include /etc/nginx/proxy.conf;
			limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;
			server_tokens off;

			sendfile on;
			keepalive_timeout 29; # Adjust to the lowest possible value that makes sense for your use case.
			client_body_timeout 10; client_header_timeout 10; send_timeout 10;

			upstream diemx{
					server localhost:5000;
			}
			 server {
					listen 80 default_server;
					listen [::]:80 default_server;
					add_header Strict-Transport-Security max-age=15768000;
					return 301 https://$host$request_uri;
			}

			server {
					listen 443 ssl http2 default_server;
					listen [::]:443 ssl http2 default_server;
					ssl_certificate /etc/ssl/certs/diemx.vn.crt;
					ssl_certificate_key /etc/ssl/certs/diemx.vn.rsa;
					ssl_protocols TLSv1.1 TLSv1.2;
					ssl_prefer_server_ciphers on;
					ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
					ssl_ecdh_curve secp384r1;
					ssl_session_cache shared:SSL:10m;
					ssl_session_tickets off;
					#ssl_stapling on; #ensure your cert is capable
					#ssl_stapling_verify on; #ensure your cert is capable
					add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
					add_header X-Frame-Options DENY;
					add_header X-Content-Type-Options nosniff;
					add_header X-debug $host$request_uri;
					#Redirects all traffic
					location / {
							proxy_pass  http://diemx;
							limit_req   zone=one burst=10 nodelay;
					}
			}
	}

**Comment by scottaddie** [comment]
@taivt0109 Is there an error message?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
