### ISSUE TITLE
Create a Razor Pages web app with ASP.NET Core and Visual Studio Code

### ISSUE THREAD

**Issue by spboyer** [aspnet/Docs#7810]
Needs update for ASP.NET Core 2.1

- [ ] aspnet/core/tutorials/razor-pages-vsc/model
* `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />`  
* Change to `.App` and do not include version.
* Remove `<DotNetCliToolReference...` these are now included in the SDK
- [ ] aspnet/core/tutorials/razor-pages-vsc/sql
* Must add `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1" />` to support SQLite
* Seed Database section: update to `public static IWebHostBuilder CreateWebHostBuilder ...` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de015a45-9c6e-97f9-6f9a-4270898036e0
* Version Independent ID: 9078c3e4-ede9-bcec-28d2-26d59d2525b8
* Content: [Create a Razor Pages web app with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Part 3 (scaffold RP) had 643 PV for the month. This will need to go into an effort to integrate VS Code/VS Mac and VS into one tutorial.

**Comment by Rick-Anderson** [comment]
This was fixed in the unification of the 3 versions (VS/VSC/VSmac)
