### ISSUE TITLE
Integration tests in ASP.NET Core 2.1 + SpaServices / UseSpaStaticFiles

### ISSUE THREAD

**Issue by devna13** [aspnet/Docs#7815]
Does WebApplicationFactory works with Microsoft.AspNetCore.SpaServices ? 
I'm following this example but I'm getting Error: "The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request."

 public class WebAppBasicTests : IClassFixture&lt;CustomWebApplicationFactory&lt;Startup&gt;&gt;
{
        private readonly HttpClient _client;
        public WebAppBasicTests(CustomWebApplicationFactory&lt;Startup&gt; factory)
        {
            _client = factory.CreateClient();
        }
        [Fact]
        public async Task GetHomePage()
        {
            var response = await _client.GetAsync("/"); //&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt; EXCEPTION
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        }
    }

 public class CustomWebApplicationFactory&lt;TStartup&gt; : WebApplicationFactory&lt;Startup&gt; where TStartup : class
    {
        public CustomWebApplicationFactory() { }
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.UseEnvironment("Development");
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
cc/ @javiercn

**Comment by javiercn** [comment]
@devna13 WebApplicationFactory is not a good approach for testing your SPAs as its not meant to replace a browser. You should be able to test server side code (Traditional Web Apps + APIs) but for SPAs a separate approach is recommended (Like Selenium)

Hope this helps

**Comment by guardrex** [comment]
🤔 ... Now that I mull this over, we should say something in the topic. Let's surface this.
