### ISSUE TITLE
Why is the Razor UI class library built as .NET Standard, whereas the web app is built as .NET Core?

### ISSUE THREAD

**Issue by eric-914** [aspnet/Docs#7816]
Pardon my ignorance, but why is the library built as .NET Standard, and the parent built as .NET Core?  Why not both as .NET Core?

Is there a way to build the library as .NET Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@eric-914  good question. I believe it's .NET Core to allow it to target .NET Framework and .NET Core.

@pranavkm @scottaddie  Is that right? I think that's worth mentioning in the article.

**Comment by eric-914** [comment]
Well, I just found out you can edit the library project, and make the following change, and voilà, it's .NET Core.

____<TargetFramework>netstandard2.0</TargetFramework>
to:
____<TargetFramework>netcoreapp2.1</TargetFramework>

(Probably want to have the library project unloaded while doing this, though)

**Comment by eric-914** [comment]
Apparently, this editor doesn't handle me entering tag elements...

The above is supposed to include tag elements:
   &lt; TargetFramework &gt; (value) &lt; /TargetFramework &gt;

(Oh man, wish there was a preview here...)

**Comment by drbaileyii** [comment]
Is there a way to use MEF to load these .dll's like a plugin?  I understand that MEF is included in .net core too.

**Comment by pranavkm** [comment]
>  I believe it's .NET Core to allow it to target .NET Framework and .NET Core.

Yup, it's the least common denominator that ASP.NET Core supports and consequently makes it easier to reuse across a variety of projects. Editing the project file to say `<TargetFramework>netcoreapp2.1</TargetFramework>` is perfectly acceptable if you want to use features in .NET Core that aren't available in NetStandard2.0.

> Is there a way to use MEF to load these .dll's like a plugin?

I'm not sure if MEF specifically works, but we've had users build plugin systems with RCLs. e.g. https://github.com/aspnet/Razor/issues/2596. I'd recommend following up on this question on StackOverflow

**Comment by danroth27** [comment]
Seems to be answered, so closing.
