### ISSUE TITLE
programmer

### ISSUE THREAD

**Issue by ChrisBashaw** [aspnet/Docs#7817]
Would be helpful if this included an example of the partial with path and name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4c23ba-19f6-d847-fefa-a61e283d5fde
* Version Independent ID: e7df465a-5f3b-1522-b2d9-5e3afbf74257
* Content: [Partial Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/partial-tag-helper?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/partial-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@ChrisBashaw Thank you for the feedback. Does the following section help you? https://docs.microsoft.com/aspnet/core/mvc/views/partial?view=aspnetcore-2.1#partial-view-discovery

**Comment by ChrisBashaw** [comment]
Yes, thanks. You were so quick with the answer!   Seeing that example of syntax solved my problem.

**Comment by scottaddie** [comment]
@ChrisBashaw Glad to hear that helped. I'll link to it from the Partial Tag Helper doc, since someone else is likely to have the same question.
