### ISSUE TITLE
difference between default template by VS and template used in docs?

### ISSUE THREAD

**Issue by mshwf** [aspnet/Docs#7823]
I created new ASP.NET Core project 2.1, and the startup class is different than what's based on here, first there's AddDefaultIdentity but here (non-yellowish code) it's AddIdentity, also instead of services.Configure<CookiePolicyOptions> there, it's services.ConfigureApplicationCookie here.
So I'm confused to continue with this tutorial with these differences. need some clarifications please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@mshwf  it hasn't been updated for 2.1 yet, but is scheduled

**Comment by mshwf** [comment]
Thanks, Rick. 
But I noticed that the ASP.NET core 2.1 version is selected in the doc page! 
Will the update take place soon? I may wait the updated version

**Comment by Rick-Anderson** [comment]
It's schedule for next month.
