### ISSUE TITLE
Dependency injection fails for lazy loaded module

### ISSUE THREAD

**Issue by tedishero** [aspnet/Docs#7826]
Lazy loading itself works, however as soon as I introduce a dependency to a component or service in the lazy loaded module, it starts to complain about not able to resolve dependencies.

**Comment by scottaddie** [comment]
@tedishero Please provide a link to the doc you're looking at.

**Comment by tedishero** [comment]
https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/Templating/issues/641.
