### ISSUE TITLE
Image File To WebApi

### ISSUE THREAD

**Issue by ChrisBashaw** [aspnet/Docs#7828]
Would be helpful if there was a simple example of syntax for ASP.net Core 2.1 WebAPI function that accepted an image jpg file along with maybe another integer or string parameter that indicated the owner use rid.

27K PV/month low CSAT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by vanillajonathan** [comment]
I use something like this.

- New file upload creates a resource hence uses a POST verb. File replace would use a PUT verb.
- Annotation that hints that it consumes multipart/form-data.
- Annotations that hints that it produces a response with the status codes 201, 409, 413 and 415.
- Model or parameter with the `IFormFile` (or `IEnumerable<IFormFile>`) type.
- Checks if the file already exists, exceeds allowed size and if the file type is allowed.
- Method declared as `async` to take advantage of async semantics.
- Restfully returns a 201 Created result that points to the newly created resource.

Action in controller:
```cs
        // POST: api/File
        [HttpPost]
        [Consumes("multipart/form-data")]
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status409Conflict)]
        [ProducesResponseType(StatusCodes.Status413PayloadTooLarge)]
        [ProducesResponseType(StatusCodes.Status415UnsupportedMediaType)]
        public async Task<IActionResult> Post(PostModel model)
        {
            if (FileExists(model.File.FileName))
            {
                return StatusCode(StatusCodes.Status409Conflict);
            }

            const int megabyte = 1024 * 1024;
            if (model.File.Length > 8 * megabyte)
            {
                return StatusCode(StatusCodes.Status413PayloadTooLarge);
            }

            if (!IsValidFileExtension(model.File.FileName))
            {
                return StatusCode(StatusCodes.Status415UnsupportedMediaType);
            }

            await _storage.CreateAsync(model.File);

            return Created($"https://files.example.com/{file.FileName}", null);
        }
```

Model:
```cs
    public class PostModel
    {
        [Required]
        public IFormFile File { get; set; }

        public string Owner { get; set; }
    }
```

**Comment by welkie** [comment]
Another example if you're interested, where I have a POST endpoint that accepts one file. The Content-Type isn't form data, but the data type of the file being upload. A header which contains the API key determines the owner so the file can be stored properly server side:

```csharp
HttpPost("<route>")]
public async Task<ActionResult<ResultDto>> UploadFile()
{
    var headers = Request.Headers;
    var userId = // do stuff with headers to determine user ID
    var fileData = Request.Body;

    // Store the file using the request body (which is a stream for the file).

    // Return status code.
}
```

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
