### ISSUE TITLE
Is there an example using ASP.NET Core 2.1 for Unit Testing?

### ISSUE THREAD

**Issue by YeyoCoder** [aspnet/Docs#7829]
The target framework of the sample from GitHub is netcoreapp 2.0  
I'm trying to build an app using **ASP.NET Core 2.1** but due the **lack of documentation** I'm now considering use 2.0 instead.  
Is there an example using ASP.NET Core 2.1 for Unit Testing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by ardalis** [comment]
There shouldn't be any difference in unit testing an ASP.NET Core application built targeting 2.0 vs. 2.1. Are you seeing a specific issue that you attribute to the minor version mismatch?

**Comment by YeyoCoder** [comment]
This is the error that I get:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'IActionResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.	WebApplication1.Test.UnitTest	C:\Users\Diego\source\repos\aspnet2.1\Docs\aspnetcore\mvc\controllers\testing\sample\WebApplication1\WebApplication1.Test.UnitTest\UnitTest1.cs	17	Active
`  

I see in _Quick actions and Refactorings..._  the following suggestion:

> Add Reference to 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
  
I clic on the _light bulb_ icon but the error continue.

Do I have to edit the _.csproj_ file  or what can solve this **?**

P.S. I leave here the project sample that I am using https://github.com/YeyoCoder/aspnet2.1/tree/master/Docs/aspnetcore/mvc/controllers/testing/sample/WebApplication1

**Comment by YeyoCoder** [comment]
I use the _NuGet Package Manager_ and install 

- Microsoft.AspNetCore.Mvc.Abstractions v2.1.1
- Microsoft.AspNetCore.Mvc.Core v2.1.1  

That **fix the error** and now the test pass **!**
