### ISSUE TITLE
Injecting HttpContextAccessor

### ISSUE THREAD

**Issue by juniormayhe** [aspnet/Docs#7832]
From razor views (cshtml) you can access HttpContext by:

@inject IHttpContextAccessor HttpContextAccessor

@{
    string yourVariable =HttpContextAccessor.HttpContext.Session.GetString("YourVariable");
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
Thank you for pointing out this gap in the doc, @juniormayhe. I'll get this added today.

**Comment by scottaddie** [comment]
@davidfowl I've seen it in the wild at a couple of different companies. Are we discouraging this technique? If so, I think it's worth keeping in the docs as an example of what not to do.
