### ISSUE TITLE
Showing errors on hosting environment

### ISSUE THREAD

**Issue by juniormayhe** [aspnet/Docs#7835]
Steveland provides here a way to show errors when .NET Core app is not starting
https://stackoverflow.com/questions/41915522/asp-net-core-1-1-runs-fine-locally-but-when-publishing-to-azure-says-an-error-o

public class Program  
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =&gt;
        WebHost.CreateDefaultBuilder(args)
            .CaptureStartupErrors(true)
            .UseSetting("detailedErrors", "true")
            .UseStartup&lt;Startup&gt;()
            .Build();
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 691b09ef-0baf-fdec-b038-49022d4fd85e
* Version Independent ID: daf78291-6119-23c6-e1b1-0606a74bd510
* Content: [Common errors reference for Azure App Service and IIS with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/azure-iis-errors-reference.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-iis-errors-reference.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @juniormayhe ... Thanks for commenting.

We document those settings in the error handling topic: https://docs.microsoft.com/aspnet/core/fundamentals/error-handling#startup-exception-handling

... and capture startup errors is automatically configured for IIS/Azure App Service hosting ...

https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/Microsoft.AspNetCore.Server.IISIntegration/WebHostBuilderIISExtensions.cs#L81

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
