### ISSUE TITLE
Pages/_Layout.cshtml to Pages/Shared/_Layout.cshtml

### ISSUE THREAD

**Issue by Pangar** [aspnet/Docs#7838]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1#viewdata-and-layout

The very last paragraph "The preceding markup sets the layout file to **Pages/_Layout.cshtml** for all Razor files under the Pages folder. See Layout for more information." 
I believe it should be "The preceding markup sets the layout file to **Pages/Shared/_Layout.cshtml** for all Razor files under the Pages folder. See Layout for more information."

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1#update-the-layout

2 Places:
First sentence "Change the <title> element in the **Pages/_Layout.cshtml** file to use a shorter string."
Should be "Change the <title> element in the **Pages/Shared/_Layout.cshtml** file to use a shorter string.

Second sentence after picture "Find the following anchor element in the **Pages/_Layout.cshtml** file."
Should be "Find the following anchor element in the **Pages/Shared/_Layout.cshtml** file.

I believe I submitted an issue previous to this in error.  My apologies.

Thank you,

Antwon Garcia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f6104a-a223-4bb3-4101-f553002b9b26
* Version Independent ID: 15e79e80-8d46-7cd5-c883-6cc0f5940a1b
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/page?view=aspnetcore-2.1#viewdata-and-layout)
* Content Source: [aspnetcore/tutorials/razor-pages/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Pangar  Thanks for pointing this out. I'll get it fixed this sprint.
