### ISSUE TITLE
There was an error trusting HTTPS developer certificate

### ISSUE THREAD

**Issue by joe-we** [aspnet/Docs#7839]
I installed the dotnet-dev-certs v2.1.1 tool and it generates an error when trying to trust the certificate:

![image](https://user-images.githubusercontent.com/41772097/43303219-655022c4-91a1-11e8-83fe-569e99d66a6c.png)

When I tried trusting it via the certificate manager, it returns this error:

![image](https://user-images.githubusercontent.com/41772097/43303236-71aeec76-91a1-11e8-8681-56cebec831bc.png)

**Comment by Rick-Anderson** [comment]
Take a look at CLI cert instructions: dotnet dev-certs https --trust #6066
