### ISSUE TITLE
Links in articles

### ISSUE THREAD

**Issue by robbert229** [aspnet/Docs#784]
I was looking through some of the docs rst files and I have seen links using `Link <http://docs.asp.net/somearticle.html>`  as well as links using `:doc: somearticle`. Is there a preference? 
@danroth27 @ardalis @Rick-Anderson

**Comment by ardalis** [comment]
:doc: is the preference. Sometimes http is used for links between sphinx document repositories, although intersphinx allows these also to work (but at greater effort from the doc author).

**Comment by robbert229** [comment]
Thanks.
