### ISSUE TITLE
Changing the port number

### ISSUE THREAD

**Issue by Hugh-walsh** [aspnet/Docs#7842]
The functionality worked OK but I cannot determine how to run as a windows service and use a none default port number

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by Hugh-walsh** [comment]
If I want to run as a console application I can run 
"D:\services\RxsDirectoryWebApi\RxsDirectoryWebApi.exe" --console --server.urls=https://*:5011;http://*:5010
this works fine and I can see the api on https://localhost:5011/ but if I want to do the same thing when running as a windows service 
sc create RxsDirectoryWebApi binPath= "\"D:\services\RxsDirectoryWebApi\RxsDirectoryWebApi.exe\" --server.urls=https://*:5011;http://*:5010"
sc start RxsDirectoryWebApi

On start the service will stop immediately.

**Comment by guardrex** [comment]
Hello @Hugh-walsh ... That doesn't surprise me too much (but it might make a good feature request). Are you not able to specify those ports with a `UseUrls` on the `WebHost`? https://docs.microsoft.com/aspnet/core/fundamentals/host/web-host#server-urls

**Comment by guardrex** [comment]
I don't like that we left off the link over to the hosting topic, so I'll add that to the WS topic.

**Comment by Hugh-walsh** [comment]
Hello @guardex,

If I state one url and it is not the https one then it works:
* sc create RxsDirectoryWebApi binPath= "\"D:\services\RxsDirectoryWebApi\RxsDirectoryWebApi.exe\" --server.urls=http://*:5010"

If I have both or I have the https one then it does not 
* sc create RxsDirectoryWebApi binPath= "\"D:\services\RxsDirectoryWebApi\RxsDirectoryWebApi.exe\" --server.urls=https://localhost:5011;http://localhost:5010"
* sc create RxsDirectoryWebApi binPath= "\"D:\services\RxsDirectoryWebApi\RxsDirectoryWebApi.exe\" --server.urls=https://localhost:5011"

The same is true if I change to UseUrls as per the link.

**Comment by guardrex** [comment]
Looks thus far like the problem is in Kestrel endpoint configuration. I started testing with ...

```csharp
var host = WebHost.CreateDefaultBuilder(args)
    .UseKestrel((context, options) =>
    {
        options.ListenAnyIP(5001, listenOptions =>
        {
            listenOptions.UseHttps(httpsOptions =>
            {
                httpsOptions.ServerCertificateSelector = (connectionContext, name) =>
                {
                    return CertificateLoader.LoadFromStoreCert("localhost", "My", StoreLocation.CurrentUser, allowInvalid: true);
                };
            });
        });
    })
    .UseContentRoot(pathToContentRoot)
    .UseStartup<Startup>()
    .Build();
```

... but that :boom: that it can't find the cert (btw - it's logged in the Application log in Event Viewer).

However when I supply a cert in the app (*testCert.pfx*) ...

```csharp
.UseKestrel(options =>
{
    options.Listen(IPAddress.Loopback, 5001, listenOptions =>
    {
        listenOptions.UseHttps("testCert.pfx", "testPassword");
    });
})
```

It works.

btw: Use the `--urls` switch. The `--server.urls` is the old switch. It may still work, but it's not current.

```console
sc create MyService binPath= ""C:\_apps\WindowsServiceSample\bin\Release\netcoreapp2.1\win7-x64\publish\AspNetCoreService.exe" --urls=https://*:5001"
```

@Tratcher @shirhatti Any ideas on why my first attempt failed using the `localhost` dev cert in the cert store?

**Comment by Tratcher** [comment]
A) don't load the cert on every request.
https://github.com/aspnet/KestrelHttpServer/blob/47e643f20a3ab74a466b320f830ffb81da55eb68/samples/SampleApp/Startup.cs#L109-L120

B) This is a Windows Service? Running as what user? Users have different "My" cert stores, the windows service user may not have a dev cert.

**Comment by guardrex** [comment]
I think we'll need to address (B) in the topic, so I'll leave this open for additional work.

As for (A), it's covered by ...

> The callback is invoked once per connection to allow the app to inspect the host name and select the appropriate certificate.

Which I totally forgot about when I hacked that up for the test. We're good on that one.
