### ISSUE TITLE
SSR Inconsistent with initial load of async data of application.

### ISSUE THREAD

**Issue by daveharmswebdev** [aspnet/Docs#7848]
When a site loads initially (localhost, IIS Express or IIS Server), async data is not rendered (as seen by Viewing Page Source). However on reload it is rendered. Instead of async data, a commented html line is present. Also, sometimes &lt;router-outlet&gt; is not rendered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/Templating/issues/642
