### ISSUE TITLE
https://docs.asp.net/en/latest/data/index.html need pointer to http://docs.efproject.net/en/latest/index.html

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#785]
customer found this page confusing, so did I.
https://github.com/aspnet/Docs/issues/72#issuecomment-163796450

Need link to EF7 http://docs.efproject.net/en/latest/index.html

**Comment by danroth27** [comment]
Two of the links on https://docs.asp.net/en/latest/data/index.html already point to the EF7 docs. I've submitted a PR to clean up this page to make that clearer.
