### ISSUE TITLE
Tell about route cascading

### ISSUE THREAD

**Issue by juniormayhe** [aspnet/Docs#7850]
In NET Core web api, which is this page about, you should tell about cascading

        [HttpGet("state/{stateName}")]
        [HttpGet("state/{stateName}/city/{cityName}")]
        public JsonResult Get(string stateName, string cityName)
        {
             ...
            return new JsonResult("done");
        }

This sample you can call GET controllerName/state/Michigan or controllerName/state/Michigan/city/Detroit
and you do not need to create custom routes templates at app.UseMvc() in Configure Method of Startup.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@rynowak Should we add a section on cascading?

**Comment by rynowak** [comment]
This is not a term I've ever heard before. There are two routes in this example, and the most specific one matches first, that's how attribute routing behaves.
