### ISSUE TITLE
Does `AuthorizeFolder` work with areas too?

### ISSUE THREAD

**Issue by fleed** [aspnet/Docs#7856]
Does `AuthorizeFolder` work with areas too? I tried with different approaches (e.g.: `AuthorizeFolder("/Areas/Admin/Pages")`, `AuthorizeFolder("/Areas/Admin")`, `AuthorizeFolder("/Admin")`, but it seems that I'm always able to access those areas even if I'm not authenticated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a49eaa-a2ee-baac-e614-5e2f7c74072a
* Version Independent ID: 09513dc8-546a-ea10-9f0b-cde361127647
* Content: [Razor Pages authorization conventions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/razor-pages-authorization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/razor-pages-authorization.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@pranavkm

**Comment by pranavkm** [comment]
There's a separate set of overloads for areas - https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.pageconventioncollectionextensions.authorizeareafolder?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_PageConventionCollectionExtensions_AuthorizeAreaFolder_Microsoft_AspNetCore_Mvc_ApplicationModels_PageConventionCollection_System_String_System_String_

**Comment by guardrex** [comment]
Thanks @fleed. Thanks @pranavkm. I'll get this asap, but I need to push it back a bit. 🏃🏃🏃🏃😅

**Comment by fleed** [comment]
Thank you @pranavkm , but how can I protect an entire area? The `folderPath` parameter is not optional.. does it work with an empty string?

**Comment by pranavkm** [comment]
`/` would be the right value to use here.

**Comment by FanrayMedia** [comment]
Thank you all, I was facing the same issue and got it working with 

```c#
// authenticated user only
options.Conventions.AuthorizeAreaFolder("Admin", "/");

// user with certain roles only
options.Conventions.AuthorizeAreaFolder("Admin", "/", "AdminRoles");
```
