### ISSUE TITLE
Hot reloading support

### ISSUE THREAD

**Issue by hyounoo** [aspnet/Docs#7858]
Hi is there hot reloading support for .net core MVC?
Since we don't need to build the app after changing code, I think it is possible to apply hot reloading where we don't have to refresh our browser.

I found below document seems what I was looking for but it needs quite a work to configure the feature.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
`dotnet watch run` is for development work.

**Comment by Rick-Anderson** [comment]
Sorry, no.
