### ISSUE TITLE
IIS hosting scenarios coverage with the aspNetCore element

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#786]
@danroth27 @Rick-Anderson

I was just communicating with @Aerendel and runtime location in an IIS hosting environment came up tangentially in the issue comments: https://github.com/aspnet/Hosting/issues/364#issuecomment-164108002

Within the discussion, I worked out that an alternate runtime location can be setup like this ...
```xml
<httpPlatform 
    processPath="F:\runtimes\dnx-coreclr-win-x64.1.0.0-rc2-16249\bin\dnx.exe" 
    arguments="--project F:\MyApp\approot\packages\MyApp\1.0.0\root web" 
    stdoutLogEnabled="true" 
    stdoutLogFile="..\logs\httpplatform" 
    startupTimeLimit="3600"></httpPlatform>
```

Perhaps an official doc could show how to configure the `httpPlatform` element for various IIS hosting scenarios. I have a gut feeling that a lot of folks are going to be asking things like, 'How can I have my runtime (or packages) over there?' or 'How can I state the configuration should be different than the default?'

Otherwise, this might just make for a good section to add to the current [Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html) doc. ~~If so, and if you want me to send you, @Rick-Anderson, a draft section, I'd be happy to work that up ... or even just supply the testing and notes you would need for the section.~~ (see below)

**Comment by GuardRex** [comment]
... and I understand that the changes from `dnx web` to `dotnet run` may change what configuration is possible and what such a doc or section of a doc would say per https://github.com/dotnet/cli/issues/254#issuecomment-158124295. Therefore, I expect you'll backlog if you're not going to reject my suggestion outright.

**Comment by danroth27** [comment]
You can find the configuration reference docs for the HttpPlatformHandler at http://www.iis.net/learn/extensions/httpplatformhandler/httpplatformhandler-configuration-reference. We should link to them from the ASP.NET docs.

**Comment by GuardRex** [comment]
@danroth27 When the time comes for this [(1) `dotnet` CLI is implemented for IIS scenarios, and (2) VS publish stops replacing settings in `web.config`], give me a holler if I can take some worker bee tasks off of @Rick-Anderson's plate in the way of testing and notes.

**Comment by danroth27** [comment]
@GuardRex Was this already covered by your updates to the IIS publishing doc?

**Comment by GuardRex** [comment]
Yes, the "better idea" that has emerged is that we have Slack #iis channel Shared Files. There are some *good vibes* about folks with special hosting scenarios (e.g., @tuespetre `dnx-watch` and IIS Local ... or my "simple console logging for small shops pattern") that will go great in the Slack #iis channel. Yeah ... we're done here.
