### ISSUE TITLE
Is it possible to list all built-in schema available?

### ISSUE THREAD

**Issue by shampeter** [aspnet/Docs#7864]
Is it possible to list all ASP.Net Core built-in schema available to this `AddAuthentication` method?  Or provide some guidelines for where to find this list?

**Comment by guardrex** [comment]
@shampeter Are you looking for the `AuthenticationSchemes` enum? https://docs.microsoft.com/dotnet/api/system.net.authenticationschemes?view=netcore-2.1

**Comment by shampeter** [comment]
Not exactly.  From [this page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.authenticationservicecollectionextensions.addauthentication?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_AuthenticationServiceCollectionExtensions_AddAuthentication_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_String_),  it is explained that the scheme parameter is just a string.  Then from varies examples on the internet, I learn that there are constants like `AzureADDefaults.AuthenticationScheme` for this scheme parameter.  So I suppose within ASP.Net Core, there must be other scheme pre-defined.  Just want to know if there is a reference or list of schemes already defined with ASP.Net Core before I start to define one myself.  Don't want to re-invent the wheel.

**Comment by guardrex** [comment]
The ones that are associated with the providers are just constants in each provider's package. Facebook for example ...

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.facebook.facebookdefaults.authenticationscheme?view=aspnetcore-2.1

You can see them in the API browser, but it's a pain. You have to start with the [auth builders page](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.authenticationbuilder?view=aspnetcore-2.1) ... click one of the providers `AddX` extensions ... find it's options ... then click in the sidebar for it's defaults ... and then it doesn't even show you the value! No so good.

A search in the aspnet/Security repo tho shows the ones for the main providers ...

https://github.com/aspnet/Security/search?q=%22public+const+string+AuthenticationScheme%22&unscoped_q=%22public+const+string+AuthenticationScheme%22

**Comment by shampeter** [comment]
Really didn't think of searching the repo, so it's good trick.  I guess I can live with this for the time being.  Thanks.
