### ISSUE TITLE
Errors at the "Create the database context" step

### ISSUE THREAD

**Issue by StingyJack** [aspnet/Docs#7866]
I get a bunch of errors at that step, they are all about EF.
```
The type or namespace name 'DbContext' could not be found (are you missing a using directive or an assembly reference?)
```
Did I miss a step to add a specific EF nuget package? If so, which one? (I dont know because I dont use EF)

I also get this warning in the output window....  
warning NU1604: Project dependency Microsoft.AspNetCore.App does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.  (I dont use package ref either)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by StingyJack** [comment]
At this step, the entire csproj should contain
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.1" />  
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
  </ItemGroup>
</Project>
```

**Comment by Rick-Anderson** [comment]
I think it should be

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by Rick-Anderson** [comment]
I'll get this updated and unified with the VS/macOS tutorials.

**Comment by Rick-Anderson** [comment]
21K PV last 30 days

**Comment by guardrex** [comment]
2.1.2 on the package ... https://www.nuget.org/packages/Microsoft.AspNetCore.App/

**Comment by StingyJack** [comment]
Sorry if I was unclear, I mean this step. 
![image](https://user-images.githubusercontent.com/15381181/43373484-d619c424-9377-11e8-9fab-07c314da1dd9.png)

At that step in the tutorial, if I have a csproj with only that package ref of that version number, the code does not compile due to things like "DbContext" being unknown.  This is additionally confusing as it says I dont need to install EF "something" (i dont use EF and am unfamiliar with its ecosystem).

**Comment by Rick-Anderson** [comment]
Did you add the right include?

**Comment by StingyJack** [comment]
Yes, I had the correct using inside the namespace. I've rebooted and removed the EF package ref and now its compiling fine without the extra package. I'm not sure why it was sticking like that, but I am sure that I don't need to spend any more time on it. Thanks!
