### ISSUE TITLE
Missing reference when trying to test any controller method

### ISSUE THREAD

**Issue by guillemsola** [aspnet/Docs#7868]
The provided examples are awesome. But If I try to test my controllers in a separate project following the XUnit VS 2017 template or even in an empty console project with NUnit VS is always telling me that there is a missing reference.

```
Error	CS0012	The type 'IActionResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.AspNetCore.Mvc.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.	ASG.DHW.HealthCheck.Tests	
```

Is there any specific requirement for a test project to access IActionresult and BaseController?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1#testing-controllers)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guillemsola** [comment]
I found that my csproj was not correct

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App"  />
  </ItemGroup>

</Project>
```

It was missing the version in this reference.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />
  </ItemGroup>
```

Maybe this is more an issue with VS 15.7.5 as I was relying on it to handle my dependencies.

It may be interesting to have a sample csproj files if this is something that may happen.

In any way again thanks for this excellent post.

**Comment by guardrex** [comment]
The sample on this topic hasn't been updated yet (#5495), and we might not even keep it given https://docs.microsoft.com/aspnet/core/test/integration-tests (which does have an updated sample for 2.1).

**Comment by FelixPatric** [comment]
I had a similar situation and after getting to this link and changing the version number on my csproj file it worked .Thanks so much, very helpful!
