### ISSUE TITLE
How to update BS4

### ISSUE THREAD

**Issue by chamaraonline** [aspnet/Docs#7869]
HI
How to update  Defult Bootstrap v3.3.5 to BS 4 without bower/node

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90c973b-dd21-5dc6-4c70-7ddfba51271e
* Version Independent ID: b20b9d8e-e29a-44a4-18d0-e78f4e8dc51f
* Content: [Build beautiful, responsive sites with Bootstrap and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bootstrap?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/client-side/bootstrap.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bootstrap.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @chamaraonline ... We're documenting the usual approaches (e.g., Gulp) for now ... https://docs.microsoft.com/aspnet/core/client-side/

When VS 15.8 Preview 3 is released, we'll document the new LibMan ("Library Manager"). I'll close this as a dup of *Create docs for LibMan* #7246, but we can re-open to discuss further if you need to.
