### ISSUE TITLE
Convert to plugin architecture?

### ISSUE THREAD

**Issue by eric-914** [aspnet/Docs#7871]
I very much appreciate this page, and the idea of pushing views into reusable components.  But I'm wondering if this can be pushed to the next step, and have these components loaded as plugins?  This way the website wouldn't require a direct dependency to the component?

I suspect this is possible based on the following successful experiment:
1) I built the above project/library combo with the dependency, and it created a .deps.json file.  This is able to find the library views ok.
2) I built the above project/library combo, but this time w/out the dependency.  It created a different .deps.json file.  This time, it was NOT able to find the library views.  (Expected)
3) However, if I overwrite the .deps.json file with the original .deps.json file, when I run the project, it finds the library views.

This shows me it is possible to build the project w/out a direct dependency on the library, and still be able to make use of it at runtime, by manipulating the .deps.json file.  (Hmmmm, I wonder if this is a security risk?)

Anyway, it's a hack, and would prefer to load the library views as a plugin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm please comment.

**Comment by pranavkm** [comment]
Instead of dropping code into the running app we would recommend using a module system, like the one Orchard Core provides. Orchard Core modules allow you to build modules as NuGet packages that can be added to your application on the fly. And you can use them as a low level framework without adopting the entire Orchard CMS infrastructure. Check out https://github.com/OrchardCMS/OrchardCore.Samples to see what this looks like.

https://github.com/aspnet/Mvc/issues/7825#issuecomment-392129629 has some relevant comments about why dynamically loading assemblies might not be a very good idea.

**Comment by eric-914** [comment]
Some clarification: I'm not trying to bring in multiple plugins, only one plugin that would override a small set of views.

My particular situation is trying to port to .NET Core a legacy system applied to many different clients.   Though each client shares a common history, each client system has unfortunately diverged as it became more customized to that particular client.  

I'm researching an idea around (a small set of) client customized views, each client all sharing the same controller and model.  Theory being compiling the client views separately, and using the appropriate client view library at run-time.  (Additional issues such as CSS, JS, images, etc. to be dealt with later)

This article comes so close by offering a means of putting the views into a library.  It's just that to work a project reference to the library must exist.  It's purpose isn't to help the project compile, but rather the library is copied to the /bin/ folder, and the .deps.json file updated to load the library at run-time.

**Comment by eric-914** [comment]
I downloaded OrchardCore, got it to build and run the OrchardCore.Mvc.Web sample project.  However, this demo is showing that a project reference to the modules it loads is still required.  I'm trying to break this coupling.  At the moment, it looks like Orchard is not going to help.

**Comment by Jetski5822** [comment]
@eric-914 What you are trying to do is to load an assembly without a direct reference to that assembly, right? And then have that assembly override internal components?

If so... that yeah, we took that support out of Orchard Core for a number of reasons.

What *you* could do is to... when the application is loaded, look inside a predetermined folder for any order assemblies, load those up in to your DI. Make sure you load them last so they over ride any internal components.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
