### ISSUE TITLE
Publishing to IIS perhaps should include non-VS publishing prior to deployment

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#788]
@danroth27 @Rick-Anderson RE: https://docs.asp.net/en/latest/publishing/iis.html

[I don't think this quite fits for *How to Customize Publishing*, so I'll continue.]

As pointed out by @Aerendel in https://github.com/aspnet/Hosting/issues/364#issuecomment-164171065, the `Publishing to IIS` doc assumes that prior to deploying to IIS the developer will be using VS to publish locally. However, I think its a safe bet that there will be non-VS folks trying to CLI publish and deploy to IIS.

I doubt anything can be done about this right now just prior to the move to CLI https://github.com/dotnet/cli/issues/254#issuecomment-158124295, so I speculate this is a backlog issue unless you reject it outright.

**Comment by danroth27** [comment]
@GuardRex Can this now be closed with your most recent updates to the article?

**Comment by GuardRex** [comment]
Yes
