### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ttugates** [aspnet/Docs#7880]
Broken link to aspnet/DataProtection samples currently points to: https://github.com/aspnet/DataProtection/samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59850a13-1322-0c54-9fd3-75ce837c2b1a
* Version Independent ID: 7d481dae-d27d-909c-a35d-bad66c7508d2
* Content: [Key storage providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-storage-providers?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/data-protection/implementation/key-storage-providers.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/implementation/key-storage-providers.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@ttugates Thank you for reporting this. I've submitted a PR to address it. The correct link is https://github.com/aspnet/DataProtection/tree/master/samples.
