### ISSUE TITLE
5 minute app Visual Studio

### ISSUE THREAD

**Issue by sjmcdonald** [aspnet/Docs#7884]
It is absurd to offer a 5 minute app tutorial and then urge the user to decide between a Razor and a MVC solution. Having done them both, I am still a neophyte Visual Studio user. The differences between the two approaches are not the first thing one thinks about when one is producing "Hello World!" Start with Razor Pages and explain how the approach is different from a Model-View-Controller discipline after I've modified a couple objects and need to validate user entry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x&view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sjmcdonald  we don't ask the user to decide, we recommend new users try Razor Pages.

**Comment by Rick-Anderson** [comment]
Fixed via fwlink now points to RP version.
