### ISSUE TITLE
Can the same work on Mobile Devices

### ISSUE THREAD

**Issue by MaqSaid** [aspnet/Docs#7886]
Excellent example of model binding to upload files. How would you do, if image captured by mobile camera has to be uploaded.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f20f2e-587a-57cb-2f10-07801087f963
* Version Independent ID: 24123f8a-e64d-ca43-368b-7cdfe31aa77c
* Content: [Upload files to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/upload-files?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/upload-files.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/upload-files.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MaqSaid ... The code at https://docs.microsoft.com/aspnet/core/razor-pages/upload-files#save-the-file-to-disk should work regardless of the type of device that the browser is running upon.
