### ISSUE TITLE
problem with dotnet core and angular in vs 2017

### ISSUE THREAD

**Issue by lim2hooi** [aspnet/Docs#7891]
System.xml.xmldocument 4.3.0 not compatible with netcoreapp 2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@lim2hooi I'll need some more information to help you with this. I have the following questions:
1. What do you see when you run `dotnet --info` in the command shell?
2. Which version of VS 2017 are you using?

**Comment by shahishani06** [comment]
Test Comment
