### ISSUE TITLE
Generic Host - Is there any way to handle stopping service beside writing log?

### ISSUE THREAD

**Issue by huyjack178** [aspnet/Docs#7892]
Hi all, I am currently implement a Windows Service by Generic Host of .net core 2.1. I implement a timer run periodically in there, but still don't know the official way to manage the service or the timer (Like Hangfire dashboard). 
Do you have any best practice, can share for me? Thank you so much

**Comment by guardrex** [comment]
Hello @huyjack178 ... The only information we have at this time on using the Generic Host as a Windows Service is the comment on the prototype posted here :point_right: https://github.com/aspnet/Hosting/pull/1492#issuecomment-405298223. If you need further information on the prototype, I recommend asking on that issue.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
