### ISSUE TITLE
I did not find the file EnableAuthenticator.cshtml

### ISSUE THREAD

**Issue by sultanaalyami** [aspnet/Docs#7893]
https://localhost:44311/Identity/Account/Manage/TwoFactorAuthentication
I did not find the file EnableAuthenticator.cshtml
How do I do that

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](https://docs.microsoft.com/ar-sa/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sultanaalyami** [comment]
How do I do that

**Comment by Rick-Anderson** [comment]
@sultanaalyami  I guess you figured out with 2.1 you need to generate these templates.
