### ISSUE TITLE
Sample of client-side validation of IClientModelValidator doesn't work

### ISSUE THREAD

**Issue by nicholasyin** [aspnet/Docs#7894]
Full file path needing fix:

aspnetcore\mvc\models\validation\sample\Views\Movies\Create.cshtml

![image](https://user-images.githubusercontent.com/17007651/43455910-fa5df99a-94f3-11e8-86a2-29c1527f63d4.png)

Google search result from stackoverflow told me this solution, moving the 2 js functions outside of document ready function. Otherwise the client-side validation won't get fired.

**Comment by scottaddie** [comment]
@nicholasyin That jQuery document.ready call can be removed. I've submitted a PR to address this.
