### ISSUE TITLE
How can I use a custom user in ASP.NET Core 2.1 ?

### ISSUE THREAD

**Issue by YeyoCoder** [aspnet/Docs#7900]
I am trying to use a **custom User** in  my ASP.NET Core **2.1** project but when I run the [project](https://github.com/YeyoCoder/aspnet2.1/tree/master/security/authentication/identity/sample/WebApplication) I get the following error :  
> InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered. 

 

I follow the instructions of [Using a custom User type](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1#using-a-custom-user-type)

**How can I use a custom user in ASP.NET Core 2.1 ?**

Also, I need a recommendation, I am a junior developer and I'm really struggling using .NET Core 2.1 due to the lack of examples and documentation.  
**Is it better for me (a junior developer) to start my project using .NET Core 2.0?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a25f836-b946-9056-5fbc-1b47ff72efd0
* Version Independent ID: 5d189a96-a529-6afa-e05d-85cfa05c5c9f
* Content: [Identity model customization](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize_identity_model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/customize_identity_model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/customize_identity_model.md)
* Product: **aspnet-core**
* GitHub Login: @ajcvickers
* Microsoft Alias: **avickers**

**Comment by Rick-Anderson** [comment]
For custom user, see https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio

> Is it better for me (a junior developer) to start my project using .NET Core 2.0?

I recommend 2.1
