### ISSUE TITLE
Simpler ConfigureAppConfiguration

### ISSUE THREAD

**Issue by nickwalkmsft** [aspnet/Docs#7908]
In the samples, is there any benefit to creating a new `ConfigurationBuilder` to run `AddAzureKeyVault`? What you had [here](https://github.com/aspnet/Configuration/pull/719#issuecomment-327276517) works. I'm using the following in a demo:

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((context, config) =>
        {
            var builtConfig = config.Build();

            var vaultUrl = $"https://{builtConfig["VaultName"]}.vault.azure.net/";

            config.AddAzureKeyVault(vaultUrl);
        })
        .UseStartup<Startup>();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @nickwalkmsft ... No, not at all ... u did the right thing. I was going to update/upgrade the samples on #6821 ... and hopefully I would've fixed the chained configuration issue you raise here. This is such a quick fix tho, that I'll put the update in now. Thanks for filing this issue.
