### ISSUE TITLE
How will I do to compare hash if I use random salt?

### ISSUE THREAD

**Issue by zalza13** [aspnet/Docs#7909]
If I save a password with random salt, and then I want to compare that password with the hash but I do not have the salt, how do I do this? or in that case I must use a fixed salt.
Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1052d7-e93f-fcb8-6d87-d86cededad23
* Version Independent ID: 61e65ca8-4008-ed27-7254-93385a9ed6d7
* Content: [Hash passwords in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/password-hashing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/consumer-apis/password-hashing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@blowdart  ?

**Comment by blowdart** [comment]
Store the salt along side the hash. It doesn't have to be protected.

**Comment by zalza13** [comment]
Thank you very much for your answer!
