### ISSUE TITLE
Can SpaServices be used with .netframework?

### ISSUE THREAD

**Issue by sirigere** [aspnet/Docs#7911]
In the section "Prerequisites for using SpaServices", you have mentioned ".NET Core SDK 2.0 or later". I guess this is false. We can use the SpaServices even with .net framework. Example use the command "dotnet new angular --target-framework-override net462"

Please let me know if my observation is not correct.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c771657b-a681-8e8a-52ed-3d974520f528
* Version Independent ID: 318e32fc-62f2-c0e5-4658-5729aad48c91
* Content: [Use JavaScriptServices to Create Single Page Applications in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa-services.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa-services.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@sirigere You can indeed use SpaServices in an ASP.NET Core project targeting .NET Framework. The .NET Core SDK is necessary for the following 2 reasons:

* It installs the .NET Core SDK, thus allowing you to run a command such as `dotnet new angular.
* It installs ASP.NET Core.

**Comment by scottaddie** [comment]
ASP.NET Core is a collection of .NET Standard libraries. This is what allows you to target either .NET Framework or .NET Core in your ASP.NET Core project. Another example is ASP.NET Core MVC, which targets .NET Standard 2.0:

https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc/Microsoft.AspNetCore.Mvc.csproj#L5.

The [Microsoft.AspNetCore.SpaServices NuGet package](https://www.nuget.org/packages/Microsoft.AspNetCore.SpaServices/) is part of ASP.NET Core, and the ASP.NET Core runtime is included with the .NET Core runtime. The .NET Core SDK installs the runtimes.
