### ISSUE TITLE
ASP.Net core 2.1 Infinite redirects for enforcing HTTPS with AWS

### ISSUE THREAD

**Issue by MartinDawson** [aspnet/Docs#7913]
@Tratcher 

```c#

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    app.UseForwardedHeaders(new ForwardedHeadersOptions { ForwardedHeaders = Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.All });

    if (environment.IsProduction() {
      app.UseHsts();
    }

    app.UseHttpsRedirection();
}

public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();
    services.Configure<MvcOptions>(options =>
    {
      options.Filters.Add(new RequireHttpsAttribute());
    });
    services.AddHsts(options =>
    {
        options.Preload = true;
        options.IncludeSubDomains = true;
        options.MaxAge = TimeSpan.FromDays(60);
    });

    services.AddHttpsRedirection(options =>
    {
        options.RedirectStatusCode = StatusCodes.Status307TemporaryRedirect;
        options.HttpsPort = 443;
    });            
}
```

If I go my production website as http:// it successfully redirects to https:// (I can see in the url) but it then keeps redirecting on an infinite loop and throws the error.

The same issue as: https://stackoverflow.com/questions/48479608/infinite-redirect-loop-in-asp-net-core-while-enforcing-ssl/48491965#48491965

I don't know if it matters but in AWS I configured my load balancer for http to be on port 80 and my https to be on port 443.

![screenshot](https://user-images.githubusercontent.com/15030491/43508242-ae578d96-956f-11e8-9a26-fcb5c5d35ecc.png)

**Comment by Tratcher** [comment]
What were your results from the troubleshooting steps?
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1#troubleshoot

FYI: Remove RequireHttpsAttribute, it's redundant with UseHttpsRedirection (but it wouldn't cause this problem).

**Comment by MartinDawson** [comment]
IE11:

```
Request Method: GET
Request Scheme: http
Request Path: /
Request Headers:
Connection: Keep-Alive
Accept: text/html, application/xhtml+xml, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-GB
Host: www.onboardor.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
X-Forwarded-For: 94.130.51.2
X-Forwarded-Port: 80
X-Forwarded-Proto: http
MS-ASPNETCORE-TOKEN: 954dfbde-d280-4f1b-8925-664f8bfe9acd
X-Original-For: 127.0.0.1:55517
X-Original-Proto: http

Request RemoteIp: 172.31.19.241
```

Chrome:

```
Request Method: GET
Request Scheme: http
Request Path: /
Request Headers:
Connection: Keep-Alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Host: www.onboardor.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 94.130.51.2
X-Forwarded-Port: 443
X-Forwarded-Proto: https
MS-ASPNETCORE-TOKEN: 954dfbde-d280-4f1b-8925-664f8bfe9acd
X-Original-For: 127.0.0.1:55517
X-Original-Proto: http

Request RemoteIp: 172.31.38.214
```

Do you know why chrome forwards correctly to port 443 but IE11 doesn't?

**Comment by Tratcher** [comment]
Was the redirect generated correctly in the prior response? What's the Location header?

**Comment by MartinDawson** [comment]
How do I see the location header? Their is no location header in the response or request when I check the network tab.

**Comment by Tratcher** [comment]
Fiddler would give you a more accurate view of the requests.

**Comment by OpenSpacesAndPlaces** [comment]
Is there any fix for this problem - seeing the same thing in 2.2 with:
```
    services.AddHttpsRedirection(options =>
                {
                    options.HttpsPort = 443;
                });
......
  app.UseHsts();
  app.UseHttpsRedirection(); 

```

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#troubleshoot
