### ISSUE TITLE
Are multiple async ViewComponents executed in parallel

### ISSUE THREAD

**Issue by phatcher** [aspnet/Docs#7914]
If I have multiple async ViewComponents on a page, are they executed with a WaitAll or is the page waiting on each on in turn?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@NTaylorMullen Any ideas? This is info I'd like to add to the doc.

**Comment by NTaylorMullen** [comment]
if you `@await Component.InvokeAsync(...)` or `<vc:MyComponent ... />` then the page waits on each ViewComponent to finish rendering.

If you capture the task like:
```
@{
    var tasks = new[] { Component.InvokeAsync(...), Component.InvokeAsync(...) };
}

... Do Stuff ...

@{
Task.WaitAll(tasks);
}
```

then they will execute concurrently. I highly discourage this pattern however. If a ViewComponent is executed concurrently you will get misordered  output which will result in a broken page.

**Comment by phatcher** [comment]
@NTaylorMullen This is rather disappointing as one of the main point of asynchronous components is so that you can parallelize the execution, handing off multiple tasks to background threads.  I suppose it would be difficult to stitch the various components into the appropriate place especially if the page is being emitted a stream rather than say a donutted page with placeholders.

On one project I'm working on at the moment we are trying for a portal/microservice approach where each screen element is produced by its own ViewComponent, with what you are saying we will have 20 serial calls to each of the responsible services rather than 20 calls in parallel.

So it looks like we have to wrapper each of the ViewComponents with an ajax invocations to gain any parallelism?

**Comment by NTaylorMullen** [comment]
> So it looks like we have to wrapper each of the ViewComponents with an ajax invocations to gain any parallelism?

Yes, that's a sufficient solution.

**Comment by pkellner** [comment]
Hey @phatcher Curios if you got the parallelism working.   I'd think as @NTaylorMullen says, it would kill the razor processing (assuming razor is not designed to handle that).  Seems like parallelism in viewcomponents would be a bad idea to me.  Better to do the service calls outside the razor processing, waitall, then blast out the completed razor page.  Crazy thinking?  anything change in later versions of asp.net core that affect this?

**Comment by saliksaly** [comment]
I found a solution for me to execute view components in parallel.
But, it requires client-side "ajax" to load them additionally.
Maybe the principle of replacing placeholders could be done competely server-side in a middleware (buffering response from Razor middleware and placing view components results in the right places) but I did not try. 
Maybe somebody here could :-)

It works so:
In the place a view component is invked, i leave a placeholder with identifier. 
The task is started but not awaited, only added to tasks collection. Only callback for the task is defined to store the result HTML to cache under the identifier.
Somewhere on the very end of Razor view, I await all the tasks.
So, all the components are rendered  simulatenously. 
Client script for every placeholder call by "ajax" backend API to get the HTML content.

These are the components invocations (CSHTML view):
```
@inject IMemoryCache _cache

@{
    var tasks = new List<Task<IHtmlContent>>();
}

@for (int i = 1; i <= 9; i++)
{
    Task<IHtmlContent> invocationTask = Component.InvokeAsync("Pokus", i);

    tasks.Add(invocationTask);

    string cacheKey = Guid.NewGuid().ToString();

    <div class="ajax-component">
        <div data-cache-content="@cacheKey">
            __PLACEHOLDER__<br>
            @cacheKey<br>
        </div>
        @Html.ActionLink("get from cache", "GetFromCache", "Home", new { cacheKey = cacheKey })
    </div>

    invocationTask.ContinueWith(t =>
    {
        IHtmlContent htmlContent = t.Result;

        string html = ToHtmlString(htmlContent);

        _cache.Set(cacheKey, html);
    });
}

@{
    await Task.WhenAll(tasks);
}
    
@functions
{
    public string ToHtmlString(IHtmlContent content)
    {
        if (content is HtmlString htmlString)
        {
            return htmlString.Value;
        }

        using (var writer = new StringWriter())
        {
            content.WriteTo(writer, System.Text.Encodings.Web.HtmlEncoder.Default);
            return writer.ToString();
        }
    }
}
```

This is controller's action to get component content:
```
public async Task<ActionResult> GetFromCache(string cacheKey)
{
    await Task.Delay(2000);

    if (_cache.TryGetValue(cacheKey, out string? value))
    {
        return Content(value!, "text/html");

        // TODO: remove the item immediately after reading it
        //_cache.Remove(cacheKey);
    }

    return NotFound();
}
```

This is JavaScript (jQuery) code to place all the components to their placeholders:
```
<script>
    $(document).ready(function () {
        var divs = $("div[data-cache-content]");

        for (var i = 0; i < divs.length; i++) {
            (function (currentDiv) { // Create a closure to capture the current value of currentDiv
                var cacheKey = currentDiv.getAttribute("data-cache-content");

                $.ajax({
                    url: "/Home/GetFromCache?cacheKey=" + cacheKey,
                    type: "GET",
                    dataType: "html",
                    success: function (data) {
                        $(currentDiv).html(data); // Use the captured currentDiv within the closure
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        // Handle AJAX errors
                        console.error("AJAX error:", textStatus, errorThrown);
                    }
                });
            })(divs[i]); // Immediately invoke the closure, passing the current div
        }
    });
</script>
```

This is the view component:
```
[ViewComponent(Name = "Pokus")]
public class PokusVC : ViewComponent
{
    public IViewComponentResult Invoke(int id)
    {
        return View(id);
    }
}
```

This is the view components's view (Default.cshtml):
```
@{
    await Task.Delay(1000);
}

@model int

<div>POKUS-VIEW-COMPONENT <strong>@Model</strong></div>
@DateTime.Now<br/>
```

As seen, every component delays 1second.
Entire response of Action with that 9 views takes approximately just the one second.


If the components were called by default (each awaited via Component.InvokeAsync or via tag helper), the total time would be the sum of the processing times of all components.

The caching for component results could be tweaked - short expiration and removing after item retrieval.
