### ISSUE TITLE
Saving to DB and Class Explanation

### ISSUE THREAD

**Issue by se-augustus** [aspnet/Docs#7917]
This is my first time setting up external auth. 

My first question is, do we need to save the users credentials to a DB? I thought the whole point of ext. auth. was to use the third party providers datastore for checking credentials?

My second question is: for the following extension method:

services.AddIdentity&lt;ApplicationUser, IdentityRole&gt;()...
What is the "ApplicationUser"? Is that a class? I don't see this in sample code solutions from Microsoft? Is this even necc. if we don't plan on saving the user credentials to our own database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c264c0-0c5c-298e-bb45-9b4891c8d162
* Version Independent ID: ce69b990-0b4c-abda-cd2d-68f85cd8031e
* Content: [Microsoft Account external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/microsoft-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/microsoft-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/microsoft-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@se-augustus  Identity doesn't save user credentials in the DB, but it must save some information.

`services.AddIdentity<ApplicationUser, IdentityRole>(). is from the 2.0 templates. The tutorial needs to be updated.  The current templates use
`services.AddDefaultIdentity<IdentityUser>()`
