### ISSUE TITLE
"Filter by title" does not work if the search term contains any upper case characters

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Docs#7923]
![search](https://user-images.githubusercontent.com/174281/43553176-97b44ee8-95a2-11e8-8aeb-42326c51f864.gif)

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by scottaddie** [comment]
I've opened Live Site Incident [78964352](https://icm.ad.msft.net/imp/v3/incidents/details/78964352/home) to track this issue. Closing here, since this issue exists outside of ASP.NET Core docs too.
