### ISSUE TITLE
return type of Task<IActionResult>

### ISSUE THREAD

**Issue by wakry** [aspnet/Docs#7925]
in the following code in the article 

public Task&lt;IActionResult&gt; Edit(int id, Customer customer)
{
    if (ModelState.IsValid)
    {
        // Update DB with new details.
        return RedirectToAction("Index");
    }
}

return  RedirectToAction("Index") throws an error since the return type is not Task&lt;IActionResult&gt;. Is this intended? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee6ad2f-1667-8d5c-1f36-9d0511e3720f
* Version Independent ID: 7838ccec-c8e8-9baa-2b3e-220b2af5fc58
* Content: [Routing to controller actions in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/routing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the report @wakry ... I'll patch it up.
