### ISSUE TITLE
Missing examples for configuration in ConfigureServices

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/Docs#7927]
This paragraph:

> Since options are typically loaded from configuration, configuration can be used in startup in both Configure and ConfigureServices. For examples of using configuration during startup, see the Application startup topic.

It links to a page that doesn't actually show how to get an IOptions&lt;&gt; in the Configure or ConfigureServices methods.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by StevenLiekens** [comment]
+ this sounds contradictory

> If a service provider is built in ConfigureServices to access options, it wouldn't contain any options configurations provided after the service provider is built. 

...

> Since options are typically loaded from configuration, configuration can be used in startup in both Configure and ConfigureServices.

**Comment by guardrex** [comment]
Hello @StevenLiekens ... Thanks for commenting. Yes, I agree that the paragraph needs work. I'll attempt to clarify.

**Comment by StevenLiekens** [comment]
Nice, thanks :)

**Comment by guardrex** [comment]
@Allann Configure the providers with `ConfigureAppConfiguration`. See ...

https://docs.microsoft.com/aspnet/core/fundamentals/configuration#providers

... and then you can access config in `Startup.ConfigureServices` ...

https://docs.microsoft.com/aspnet/core/fundamentals/configuration#access-configuration-during-startup
