### ISSUE TITLE
Does this feel like Web Forms all over again?

### ISSUE THREAD

**Issue by fernandezjose** [aspnet/Docs#7929]
I would like to know the motivation behind this new approach.  Anyone know about a blog's post that explains the 'why' of this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@fernandezjose  motivation is it's more productive for many. See https://github.com/aspnet/Docs/pull/7801

**Comment by ashutoshkushawaha** [comment]
@fernandezjose, i am also in confusion, where is controller.
