### ISSUE TITLE
How to get current culture name in view?

### ISSUE THREAD

**Issue by Anduin2017** [aspnet/Docs#7936]
How to get current culture name in view?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#globalization-and-localization-terms)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Anduin2017  Use [Implicit Razor expressions](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#implicit-razor-expressions)

**Comment by Anduin2017** [comment]
I am writing an extension method to allow using `@UseChinaRegisterInfo` in the view page.
And I need to get the culture here. Only display that info to Chinese users.

But here I could only access the page context. Not the localizer.
How can I achieve that?

Here is my code:
```C#
        public static IHtmlContent UseChinaRegisterInfo(this RazorPage page)
        {
            var content = new HtmlContentBuilder();
            if(culture == "zh-CN")
            {
                content.SetHtmlContent("<a href='http://www.miitbeian.gov.cn' target='_blank'>辽ICP备17004979号-1</a>");
            }
            return content;
        }
```

**Comment by hishamco** [comment]
If I understand you correctly, you can access the `RequestCulture` using:
```csharp
var requestCultureFeature = context.Features.Get<IRequestCultureFeature>();
var requestCulture = requestCultureFeature.RequestCulture;
```

You can access the `context` from within the `RazorPage` itself

@Rick-Anderson how this is related to Docs?!! It can be moved to the home repo

**Comment by Anduin2017** [comment]
@hishamco 
Thank you so much. Your solution solved my problem.
And here is the code:
```C#
        public static IHtmlContent UseChinaRegisterInfo(this RazorPage page)
        {
            var requestCultureFeature = page.Context.Features.Get<IRequestCultureFeature>();
            var requestCulture = requestCultureFeature.RequestCulture.UICulture.IetfLanguageTag;
            
            var content = new HtmlContentBuilder();
            if (requestCulture == "zh")
            {
                content.SetHtmlContent("<a href='http://www.miitbeian.gov.cn' target='_blank'>辽ICP备17004979号-1</a>");
            }
            return content;
        }
```
I didn't mean to submit an issue here. I have just commented under: 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1

And it seems that the content was synced here. Sorry for disturbing.
