### ISSUE TITLE
SonarWhal suggestion for cache-control

### ISSUE THREAD

**Issue by aligneddev** [aspnet/Docs#7939]
Since the Sonarwhal.com scanner is suggesting longer, I recommend the documentation here to reflect that.
 // sonarwhal suggests 31536000 seconds = 1 year
// note all images and svgs will need a filename rename or the browsers won't get the new image
double seconds = TimeSpan.FromDays(366).TotalSeconds;
 ctx.Context.Response.Headers.Append("Cache-Control", $"public,max-age={seconds}");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?tabs=aspnetcore2x&view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher  should we change 
` ctx.Context.Response.Headers.Append("Cache-Control", "public,max-age=600");`
from 600 to 31536000 seconds = 1 year ?

**Comment by Tratcher** [comment]
No, we don't do use a permacaching pattern in our project templates. We rely on expiration to pick up changes. That said 600 (10m) may be a bit short. Can you show it setting 600 for in a Development environment and 1 week in Production?

**Comment by aligneddev** [comment]
That sounds good. I wasn't thinking about the complexities of explaining
cache busting with hashes or query strings. My team is using webpack and
dealing with having to remember to change updated image filenames.

Thanks for considering my request.
