### ISSUE TITLE
Is there a way to retrieve data from the server-side rendering server?

### ISSUE THREAD

**Issue by johnrom** [aspnet/Docs#7942]
If I understand correctly the `asp-prerender-module` tag helper calls the server-side renderer, which then returns a response with `{ html: "<prerenderedhtml />", globals: {} }`, which the Tag Helper can access and then write to the view.

My question is whether other parts of the view can access this, and even if there is a way to pre-render outside of this tag helper to directly use that content. I'm looking to generate the `meta` and `title` tags once for both server- and client- side code, using something like the following (also using react-helmet)

```
params.domainTasks.then(() => {
    const html = ReactDOMServer.renderToString();
    const helmet = Helmet.renderStatic();

    resolve({
        html,
        globals: { initialReduxState: store.getState() }
        meta: { // can this be retrieved before printing document head?
            title: Helmet.title.toString(),
            // etc
        }
    });
}
```

**Comment by Rick-Anderson** [comment]
@johnrom  thanks for the question. You'll probably get a quicker response from StackOverflow than from the doc team.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
