### ISSUE TITLE
Inadequate examples or discussion

### ISSUE THREAD

**Issue by kevinknowscs** [aspnet/Docs#7951]
For properties such as EnableDefaultContentItems, this document fails to clarify which node it is attached to. The Project node? The PropertyGroup? The ItemGroup? The PackageReference? This document is super confusing because it discusses the Razor SDK and then jumps directly into XML nodes. Please give examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e930c44-70f6-8820-1451-d1f781ded7a0
* Version Independent ID: 6a25fc79-b9b3-4bbf-4fde-8e44b3d8014e
* Content: [ASP.NET Core Razor SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/sdk.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/sdk.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kevinknowscs  thanks for your comment. We'll get to this in the next doc sweep.

**Comment by jameswilddev** [comment]
Was this revisited or is it still planned for the future?

**Comment by Rick-Anderson** [comment]
planned

**Comment by qujck** [comment]
timeline?

**Comment by Rick-Anderson** [comment]
@pranavkm can you let me  know where these properties go and I'll get the doc updated.

**Comment by pranavkm** [comment]
Could we point to the MSBuild documentation - https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties instead?
