### ISSUE TITLE
What is the purpose of SendGridUser

### ISSUE THREAD

**Issue by MSIH** [aspnet/Docs#7955]
The SendGridUser is never used in the code. What is the purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MSIH  you're right, it's not used in the sample. It could be used in `From = new EmailAddress("Joe@contoso.com", "Joe Smith"),`

I think it was used in an earlier version when it was required by the SendGrid API.
