### ISSUE TITLE
Database Update after Migration

### ISSUE THREAD

**Issue by premchrprem** [aspnet/Docs#7961]
I am new to Razor Pages. While struggling to update the Database, I found 
context.Database.EnsureCreated(); instead of DbInitializer.Initialize(context);  in Program.cs. The first method won't accept migrations. Since I am working with migrations I used the second method "DbInitializer.Initialize(context);" Database Updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio#fk)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Both approaches are explained in the tutorial.

**Comment by Magz007** [comment]
Data.DbInitializer.Initialize(context); Database Updated
