### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#797]
MVC -> Views -> Layout
Should cover ViewStart as well.

Taylor will cover view basics in his article (link)

Structure:
- Introduction - What is a layout
- Specifying a Layout
- View Start (running code before each view)
- View Imports (importing shared directives)

Layout
- Convention: _Layout.cs (but can be anything)
- Naming it with _ in razor had some historical meaning
- Layout is a top level template for views in the app
- Razor pages have a Layout property
  - full path or partial name - partial name will use razor discovery (controllername, shared)
  - shared is the last place searched; can override 
  - Discovery looks in same places as partial views
- Layouts are rendered ViewStart, then View.cshtml, then one or more layouts
- RenderBody (required unless you call IgnoreBody in the Layout)
    - Will render the whole page defined in the view
- Sections
  - RenderSection
    - Section must be defined unless layout indicates it is optional
  - Pages define sections with @section
  - A section that is defined in a page must be rendered, unless IgnoreSections
  - Sections only flow from regular views, not partials, viewstarts, view components, etc.

- ViewImports
  - Used to add includes to views
  - addTagHelper, removeTagHelper, tagHelperPrefix, using, model, inherits, inject
  - not supported: functions, section
  - hierchical in the view folder structure like viewstart

ViewStart
  - Code that runs before every full view (not for layout, not for partials)
  - Used to run initialization logic (ex: setting the Layout) (referring to views doesn't include file extension)
  - View imports and ViewStart share the same discovery algorithm
  - You can have multiple ViewStarts in your page; run hierarchically
      - Starts at root, toward specific view
  - ViewStart doesn't go in Shared

**Comment by ardalis** [comment]
Does this even have a placeholder file yet? @danroth27

**Comment by danroth27** [comment]
Nope

**Comment by ardalis** [comment]
Are IgnoreBody and IgnoreSection in RC1? @NTaylorMullen can you point me to or show me a sample?

**Comment by NTaylorMullen** [comment]
@ardalis no they are not. I'm not aware of any fully end-to-end samples of the feature but we do have some unit tests showcasing it. See:

https://github.com/aspnet/Mvc/blob/6bf25cecec093ecd5e103a9c038e023f82605ef6/test/Microsoft.AspNetCore.Mvc.Razor.Test/RazorPageTest.cs#L439

https://github.com/aspnet/Mvc/blob/6bf25cecec093ecd5e103a9c038e023f82605ef6/test/Microsoft.AspNetCore.Mvc.Razor.Test/RazorPageTest.cs#L634

**Comment by ardalis** [comment]
@NTaylorMullen ok, thanks. I'm going to pull them out of the article for now, then, since it's targeting RC1 until RC2 ships with VS tooling.
