### ISSUE TITLE
Explain AddCors and                 builder.AllowAnyMethod().AllowAnyHeader()

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#7972]
Explain [this](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr/sample/Startup.cs#L29-L35)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
Ok, multiple people have complained about this, we should either remove it from this basic sample, or point to https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1#cross-origin-resource-sharing

**Comment by BrennanConroy** [comment]
@anurse thoughts?

**Comment by Rick-Anderson** [comment]
@tdykstra  and I chatted about this. The plan is to remove it from the sample **and** below the sample say something like 

A real deployed app needs CORS to work.  For more info, see

**Comment by Rick-Anderson** [comment]
Perhaps it's better to call out the code and say it's not required to run the app locally, but is required when  ...
