### ISSUE TITLE
Checkbox Checked Value is not Updated properly in UI

### ISSUE THREAD

**Issue by hftl-kalle** [aspnet/Docs#7976]
If you edit an item and set it to checked the next item that will be edited will also have a checked checkbox even though it is not checked in the list.

Line 80 in the site.js needs to be:
$('#edit-isComplete')[0].checked=item.isComplete;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@hftl-kalle Thank you for reporting this problem. The fix will go live within the next 24 hours.
