### ISSUE TITLE
ASP.NET 2.1 not available?

### ISSUE THREAD

**Issue by GuSoder** [aspnet/Docs#7978]
I followed this guide today, I could not Choose ASP.NET 2.1, only 2.0 in the first step

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
What version of VS do you have? Latest is 15.7.6.

**Comment by GuSoder** [comment]
I have 15.7.6, I downloaded right before taking the tutorial.

**Comment by guardrex** [comment]
@GuSoder That's strange ... install the SDK v2.1.302 and see if that does the trick.

https://www.microsoft.com/net/download

**Comment by GuSoder** [comment]
Yeah, that fixed it
