### ISSUE TITLE
Mention about Services

### ISSUE THREAD

**Issue by Praveen-Rai** [aspnet/Docs#7980]
I've recently started learning web-dev using ASP.Net Core and what i understand is that in ASP.Net Core MVC, the model is just an entity object that is mapped to the database. Due to this the Business logic get's concentrated into the Controllers and Code Sharing is hindered. To avoid this ASP.Net Core supports Services, but the documentation doesn't mention much in this context about the services. So, getting a mention of the Services at this page will give the reader introduction about using services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b26c2a-d481-043c-e37b-cbe3ad427d41
* Version Independent ID: d7d85488-c055-7aea-0664-2e97bc937a04
* Content: [Overview of ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/overview?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/overview.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/overview.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Praveen-Rai ... The topic that pertains to services (dependency injection) at https://docs.microsoft.com/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1 appears early in the TOC. Generally, we hope devs will read the major topics in the *Fundamentals* node before they look at the *MVC* node.

Also, the topic does have what you're asking for ... https://docs.microsoft.com/aspnet/core/mvc/overview#dependency-injection ... in the *Features* area of the topic. It links over to the services (DI) topic.

**Comment by Praveen-Rai** [comment]
@guardrex It's fair to assume that the developer reads the documentation sequentially, but on the other hand elsewhere as well the MVC pattern does not mention anything about services. May be other frameworks might support writing business-logic in the Models, i have absolutely no idea on this as i am just walked first few steps towards web-development and MVC. The point i want to make here is that when a person like me starts with ASP.Net Core MVC, the page under discussion would be the first introduction about MVC from aspnet team. So, it would be better if we talk about MVC in context of ASP.Net Core (where services are the business logic containers) and hence we should at least mention Services and their importance.

Secondly, the links that you pointed talks more about Dependency injection and does not explicitly say that one should create services to contain and share the Business Logic. Again, for an expert DI might directly imply Services, but to me DI appears to be an implementation method for Services rather the concept of Service itself ( please correct me if i am mistaken ). 

Hope i make sense to you :-)

**Comment by Praveen-Rai** [comment]
And how about if we can move this page up in the sequence ?

**Comment by guardrex** [comment]
Thanks for your feedback. I defer to management. @Rick-Anderson @scottaddie

**Comment by Praveen-Rai** [comment]
@Rick-Anderson @scottaddie Any comments / updates ??

**Comment by Rick-Anderson** [comment]
Details like this wouldn't go in the overview document.  I think it's covered adequately in several places like
 
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio
and https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1

**Comment by ardalis** [comment]
Let me chime in here as author of some of the content you're referencing.

The Model in MVC refers to not just a given ViewModel or Entity, but to the *domain model* or application model, which may include services. You won't find any of the typical UI design patterns including "services" in their names (MVC, MVP, MVVM, etc) because services are a part of the Model in these patterns. Services is also an ambiguous term, since there can be services at any/all levels of abstraction. You can have a "service" that exists only in the UI layer for performing some UI work. You can have a "service" that exists only in an infrastructure library for performing some low level detailed work. And as I mentioned you can have "services" in your domain model providing business logic (in addition to logic that may be on entities and value objects, etc. in the domain model).

This link provides some more info: https://deviq.com/kinds-of-models/ Note when referring to the domain model: 

> The domain model will often include abstractions and **services** that allow the Controller to operate at a higher level of abstraction, and keep low-level plumbing code from cluttering the Controller and making it harder to test.

**Comment by rsanhuez** [comment]
I agree with @Praveen-Rai. The role of the services are not emphazised enough. I (as a newbie asp.net core MVC developer) started adding all the business logic into the controller. In my opinion this page should guide the readers when they are trying to learn the recommended or best practices to implement the MVC pattern using this framework, and the services are an integral part of that.
