### ISSUE TITLE
This tutorial still lives in parallel to Identity (without individual student/teacher authentication).

### ISSUE THREAD

**Issue by 3strategy** [aspnet/Docs#7986]
The fact that this tutorials still lives in parallel to Identity (skipping the work of making student an identity, seeding identities/roles/policies/claims) is a mistake. It keeps is very far from real life needs.
The real problem is that seeding identity + roles is complicated in netcore 2.1 (or simple but not documented). There is no official documentation of how to do it correctly. Every thing that worked in 1.1 for seeding Identity has to be re-written.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@3strategy  This tutorial has never included Identity. There are many docs on Identity in https://docs.microsoft.com/en-us/aspnet/core/security

**Comment by 3strategy** [comment]
It's exactly my point. This tutorial has never included Identity. and as time passes (years), it becomes more of a problem (and the tutorial's relevancy to real world scenario decreases). What's missing is an app tutorial that does incorporate identity. I've read the doc about identity and Role/Claims based authorization and it does not address seeding entities and roles.
When a breaking change like 2.1 comes new tutorials are needed, or existing ones need to go deeper. Maybe my post is at the wrong place, but I'm read by the right person :-)

**Comment by Rick-Anderson** [comment]
See #7651 which is blocked for a couple weeks
