### ISSUE TITLE
asp-all-route-data

### ISSUE THREAD

**Issue by OblivionSY** [aspnet/Docs#7992]
This option clears any asp-route-xxxx entry created? Should it not append to it? Irrespective of the order used in the form, asp-all-route-data takes precedence. 

Consider sorting examples on a grid: 

&lt;a asp-page="./Index" asp-all-route-data="@Model.CurrentFilterSettings" asp-route-sortOrder="Name"&gt;Name&lt;/a&gt; 

In this example, the SortOrder is never applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.1#asp-all-route-data)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by l-matti** [comment]
I was hoping asp-route- would take priority over any same entries in the asp-all-route-data dictionary.
Currently it throws: 
> ArgumentException: An element with the key 'id' already exists in the RouteValueDictionary. Parameter name: values
