### ISSUE TITLE
How do you enable SSL/https in Visual Studio for Mac?

### ISSUE THREAD

**Issue by borglin** [aspnet/Docs#7995]
It seem that the server only responds to http requests by default but in this tutorial you use https for sending POST requests to create new todo items. How do you enable that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caaef794-56f4-43bd-3db7-55e818614abd
* Version Independent ID: 4c3ff8b2-1ffd-78d7-6877-e218ea993666
* Content: [Create a Web API with ASP.NET Core and Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api-mac?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api-mac.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api-mac.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sayedihashimi 	how do you  enable SSL/https in Visual Studio for Mac?
Let me know and I'll get this updated.

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos
