### ISSUE TITLE
Searchstring not displayed after search

### ISSUE THREAD

**Issue by aarongoldenthal** [aspnet/Docs#8000]
With the implementation for the search textbox, after searching the search results are correctly displayed, but the search textbox is blank.  Recommend:

1. Add public string SearchString { get; set; } to class MovieGenreViewModel
2. Populate value in Index controller (movieGenreVM.SearchString = searchString;)
3. Change title search textbox on Index view to &lt;input asp-for="SearchString"&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9859c-b83c-5fc3-41d5-15531232185f
* Version Independent ID: 5438de31-8562-3747-d1a5-2a4622252fc1
* Content: [Add search to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@aarongoldenthal  great suggestion. I'll do that next doc update.
