### ISSUE TITLE
Add metadata to whitelist to fix SkyEye

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#8004]
Add the `ms.product` and `ms.technology` values, for the ASP.NET 4.x and ASP.NET Core conceptual docsets, to the whitelist. This will fix the problem we see with certain docs for which SkyEye doesn't work.

**Comment by scottaddie** [comment]
@Rick-Anderson Are you seeing the data now?

**Comment by Rick-Anderson** [comment]
YEs, it's working. Thanks.
