### ISSUE TITLE
[ProducesResponseType(200)] - Line of code removes Model documentation from Swagger UI

### ISSUE THREAD

**Issue by DanJ210** [aspnet/Docs#8007]
I'm using the doc below to add Swagger to an ASP.Net Core 2.1 Web API. When adding the `[ProducesResponseType(200)]` to a method, the generated models are removed from being displayed on the Swagger UI. I've attached the screen shot showing where Models are displayed and you'll see only one Model underneath it when there should be two. One is removed because I added the above line of code. I've tried adding XML doc tags to the model class itself to see if it gets picked back up but it doesn't

So do we use this and lose the models documented by Swagger? Or is there something I'm not seeing in the docs? I've looked over the docs a few times but haven't seen anything else.

Thanks,

https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio-code%2Cvisual-studio-xml

![openapi-swagger](https://user-images.githubusercontent.com/16159685/43908114-24410b6c-9bc5-11e8-849a-4cfad6ef40f8.PNG)

**Comment by Rick-Anderson** [comment]
Moved to  #8018 so visible on doc page.
