### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by spacecat** [aspnet/Docs#8009]
Don't think I'm the only one but one would expect vanilla JS in favor of jQuery these days. I understand the "it's easy" and "get started quickly" aspect of jQuery, and that it's been there for ages - since the beginning of ASP.NET MVC, but surely there must be a different approach now after all these years? Or is it because it is deeply rooted in the ASP.NET MVC/Razor Pages templates/framework that it's still being used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The validation was written in jQuery. Most of the Validation is automatic, you don't need to write jQuery.

**Comment by spacecat** [comment]
Not sure I follow..
Read through the first tutorials of Razor Pages and most of the validation code look similar to MVC tutorials with validationsummary etc
Haven't checked the RP validation tutorial.. maybe it's explained there in more detail.

**Comment by spacecat** [comment]
It's nice that it's auto but I still would use client side validation with something that is not jquery.  Is this possible and if so , how?
