### ISSUE TITLE
TIL: libuv1 is now on wily

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Docs#801]
Not sure if this has some positive implications for the linux/ubuntu install instructions.  Instead of having to compile libuv, people should be directed to `apt-get` it.

https://github.com/libuv/libuv/issues/643#issuecomment-164766351

**Comment by shirhatti** [comment]
Our install instructions were written with 14.04 in mind. Look [here](https://github.com/aspnet/Docs/blob/dee2e5c7eb3272b56cf89b0e3383879723f7f7dd/aspnet/getting-started/installing-on-linux.rst#id19)

This is definitely worth re-visiting there is a new LTS version of Ubuntu which I believe is April of 2016.
Feel free to re-open then or if you have a compelling reason that we should do it now.

**Comment by atrauzzi** [comment]
Compelling alternative would be to support both.
