### ISSUE TITLE
Curious to know why this template does not let you choose Authentication

### ISSUE THREAD

**Issue by RajeshNarkhede** [aspnet/Docs#8010]
I am just curious to know why this template does not let you choose any other authentication than 'No Authentication' . Is it intentional? If yes then what are the reasons.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@RajeshNarkhede This is intentional.

@danroth27 The last time I asked about enabling auth for SPA templates, you mentioned this is being worked on. Any status to provide?

**Comment by danroth27** [comment]
It's still something we want to do, but I don't have a committed timeframe for you yet.
