### ISSUE TITLE
Is there a way to start a singleton service when the container is built

### ISSUE THREAD

**Issue by dendle** [aspnet/Docs#8016]
Similar to AutoFac's IStartable or Auto-Activate functionality?

https://autofaccn.readthedocs.io/en/latest/lifetime/startup.html

I know I can substitute in AutoFac, but i'd just like to know if its possible with the built in DI in ASP.NET Core 2.1.

Thanks,
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#service-lifetimes)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @dendle ... You should probably move this over to the aspnet/Home issues for a faster answer. https://github.com/aspnet/Home/issues

**Comment by AccraNET** [comment]
"Singleton lifetime services are created the first time they're requested (or when ConfigureServices is run and an instance is specified with the service registration)."

You should pass an instance to the "AddSingleton" extension method

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
