### ISSUE TITLE
Good one but Link is broken !!

### ISSUE THREAD

**Issue by ajithk444** [aspnet/Docs#8019]
good tutorial. but the link broken for "Scaffold identity into a Razor project with authorization" . please fix it ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ajithk444  thanks for pointing that out. I'm fixing it now in #8020

**Comment by Rick-Anderson** [comment]
@ajithk444 fixed. It should go live in the next 24 hours. Hope you found the correct link.

**Comment by ajithk444** [comment]
Thanks ! that was so quick. but still link is broken as it is not live yet i guess. Will check after 24 hrs. :)
