### ISSUE TITLE
Are the Normalized Values in Identity Supposed to be Lowercase or Uppercase?

### ISSUE THREAD

**Issue by danielcongrove** [aspnet/Docs#8022]
On the documentation for Migrate from ASP.NET Membership authentication to ASP.NET Core 2.0 Identity, it appears that the article is suggesting to copy the lowercase values into the normalized columns. However, aren't the normalized columns in Core Identity supposed to be uppercase?

```
NormalizedUserName 	string 	aspnet_Users.LoweredUserName 	string
NormalizedEmail 	string 	aspnet_Membership.LoweredEmail 	string


NormalizedUserName 	string 	aspnet_Users.LoweredUserName 	string
NormalizedEmail 	string 	aspnet_Membership.LoweredEmail 	string
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef1bf52a-1488-eb9b-9961-7843704d2717
* Version Independent ID: 1983fca0-2c10-a835-7a37-e67ad97793a1
* Content: [Migrate from ASP.NET Membership authentication to ASP.NET Core 2.0 Identity](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/membership-to-core-identity?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/proper-to-2x/membership-to-core-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/proper-to-2x/membership-to-core-identity.md)
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@isaac2004 @blowdart Do either of you know?

**Comment by Rick-Anderson** [comment]
@HaoK please respond. 30 second question.
https://github.com/aspnet/Identity/graphs/contributors

**Comment by HaoK** [comment]
Yeah in core they are uppercase, by default they are normalized via: `.Normalize().ToUpperInvariant();`

**Comment by Rick-Anderson** [comment]
@danielcongrove 	any chance you could PR this article and add that information?

**Comment by danielcongrove** [comment]
@Rick-Anderson looks like @scottaddie beat me to it. Changes look good to me.

https://github.com/aspnet/Docs/pull/10310

**Comment by IArnaut2** [comment]
Shouldn't be emails in lowercase? Why are they normalized to uppercase? It makes no sense.
