### ISSUE TITLE
Validation with vanilla HTML5

### ISSUE THREAD

**Issue by eyadraschad** [aspnet/Docs#8034]
Why model validation on the client side is tied to jQuery library? What if we don't want to include jQuery in the project? Is there a way to allow simple validations with HTML5 only without having to include jQuery and generate all those data-* attributes? For example, if the field is annotated as [Required] and [DataType(DataType.EmailAddress)] then HTML5 validation would be sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for your request.

**Comment by Rick-Anderson** [comment]
@eyadraschad  the team has decided to go with jQuery. You could open an issue at https://github.com/aspnet/Templating/issues if you like.
