### ISSUE TITLE
Dependencies are out of date

### ISSUE THREAD

**Issue by thzero** [aspnet/Docs#8035]
Dependencies are out of date!  There isn't a sane way to actually update dependencies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7264db1b-55ec-e419-d2c4-bd4fe64922a2
* Version Independent ID: 720995d2-006a-3573-4868-d253c8a2acc7
* Content: [Use the React-with-Redux project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react-with-redux?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa/react-with-redux.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react-with-redux.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by thzero** [comment]
@types/history                       4.6.0          4.6.0   4.7.0  WebApplication1
@types/react                       15.0.35        15.0.35  16.4.9  WebApplication1
@types/react-dom                    15.5.1         15.5.1  16.0.7  WebApplication1
@types/react-hot-loader              3.0.3          3.0.3   4.1.0  WebApplication1
@types/react-redux                  4.4.45         4.4.45   6.0.6  WebApplication1
@types/react-router                 4.0.12         4.0.12  4.0.30  WebApplication1
@types/react-router-dom              4.0.5          4.0.5   4.3.0  WebApplication1
@types/react-router-redux            5.0.3          5.0.3  5.0.15  WebApplication1
@types/webpack                      2.2.15         2.2.15   4.4.9  WebApplication1
@types/webpack-env                  1.13.0         1.13.0  1.13.6  WebApplication1
aspnet-webpack                       2.0.1          2.0.3   3.0.0  WebApplication1
awesome-typescript-loader            3.2.1          3.2.1   5.2.0  WebApplication1
bootstrap                            3.3.7          3.3.7   4.1.3  WebApplication1
css-loader                          0.28.4         0.28.4   1.0.0  WebApplication1
event-source-polyfill                0.0.9          0.0.9  0.0.12  WebApplication1
extract-text-webpack-plugin          2.1.2          2.1.2   3.0.2  WebApplication1
file-loader                         0.11.2         0.11.2  1.1.11  WebApplication1
history                              4.6.3          4.6.3   4.7.2  WebApplication1
jquery                               3.2.1          3.2.1   3.3.1  WebApplication1
react                               15.6.1         15.6.1  16.4.2  WebApplication1
react-dom                           15.6.1         15.6.1  16.4.2  WebApplication1
react-hot-loader              3.0.0-beta.7   3.0.0-beta.7   4.3.4  WebApplication1
react-redux                          5.0.5          5.0.5   5.0.7  WebApplication1
react-router-dom                     4.1.1          4.1.1   4.3.1  WebApplication1
react-router-redux           5.0.0-alpha.6  5.0.0-alpha.6   4.0.8  WebApplication1
redux                                3.7.1          3.7.1   4.0.0  WebApplication1
redux-thunk                          2.2.0          2.2.0   2.3.0  WebApplication1
style-loader                        0.18.2         0.18.2  0.22.1  WebApplication1
typescript                           2.4.1          2.4.1   3.0.1  WebApplication1
url-loader                           0.5.9          0.5.9   1.0.1  WebApplication1
webpack                              2.5.1          2.5.1  4.16.5  WebApplication1
webpack-hot-middleware              2.18.2         2.18.2  2.22.3  WebApplication1
webpack-merge                        4.1.0          4.1.0   4.1.4  WebApplication1

**Comment by andrewwilkin** [comment]
Totally second this. Wanted to play with React 16 and the project template is nice but too dated.

Trying to update individual packages and you quickly come unstuck.

**Comment by andrewwilkin** [comment]
Might be worth reading this - seems that default templates are changing:
https://github.com/aspnet/JavaScriptServices/issues/997

**Comment by SteveSandersonMS** [comment]
That's correct - they are being updated as part of the 2.1 release.
