### ISSUE TITLE
These lines should be highlighted in the doc

### ISSUE THREAD

**Issue by ogoldes** [aspnet/Docs#8036]
In  class definition "public partial class IndexModel : PageModel"
The lines 
    private readonly UserManager&lt;WebApp1User&gt; _userManager;
    private readonly SignInManager&lt;WebApp1User&gt; _signInManager;
        UserManager&lt;WebApp1User&gt; userManager,
        SignInManager&lt;WebApp1User&gt; signInManager,

Should be highlighted as &lt;IdentityUser&gt; must be replaced with &lt;WebApp1User&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ogoldes  thanks for the report.

**Comment by ogoldes** [comment]
Please disregard the report. I was looking at code generated previously.
