### ISSUE TITLE
namespace ContosoUniversity.Data should be ContosoUniversity.Models

### ISSUE THREAD

**Issue by edikaufmann** [aspnet/Docs#8040]
IN.
"Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8"
following code is used:

…..
using System.Linq;
namespace ContosoUniversity.Data
{
   public static class DbInitializer
    {
…..
I think 'namespace' should read ContosoUniversity.Models'

… or might be you just want to test the 'student'!?!

regards ed K.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@edikaufmann  yes, that's an artifact of the previous version. We'll get this fixed in the next sweep. Hopefully it didn't slow you down.

**Comment by edikaufmann** [comment]
well, not really. But thanks for the explanations
