### ISSUE TITLE
In Startup.Config TempData not working if UseCookiePolicy is placed before UseMvc

### ISSUE THREAD

**Issue by hmdhasani** [aspnet/Docs#8041]
I followed these instructions to migrate my app and after migration temp data was not working. After testing many things find out that if UseCookiePolicy() is placed before UseMvc() TempData brokes, I dont know why and did not find any documentation about this. I have also created an issue in MVC about it (https://github.com/aspnet/Mvc/issues/8233). I think here UseCookiePolicy() should be after use UseMVC() so other people don't get encounter by this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @hmdhasani ... The location to place Session State Middleware (that makes TempData work) relative to the other middlewares (after Cookie Policy Middleware and before MVC) is shown in the *Application state* topic ...

https://docs.microsoft.com/aspnet/core/fundamentals/app-state#configure-the-tempdata-provider

... so I'll mirror that location in the migration topic with a code comment to activate the line for session (or TempData).

Thanks for letting us know.

**Comment by hmdhasani** [comment]
@guardrex thanks for the response.

I see you changed the sample code.

A) in the documentation of migration (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1#configure-the-tempdata-provider)
these is piece of code for Startup class and in this code app.UseCookiePolicy(); is placed before app.UseMvc(); and that's invalid I think (if you try to use TempData you see that TempData is not working but if you only move app.UseCookiePolicy(); to after app.UseMvc();  TempData will work) 

Let's see if what I did is wrong:
1) I created an ASP.Net Core Web Application (Selecting Web Application in the creating wizard) in Visual Studio 
2) Now I want to use TempData so according to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state?view=aspnetcore-2.1#configure-the-tempdata-provider
I added the three highlighted lines to the startup exactly where the documentation says
3) I Added A Simple Controller for testing TempData:

```
public class DefaultController : Controller
{
        public ActionResult Index()
        {
            TempData["A"] = "TempData Works!";
            return RedirectToAction("Index2");
        }

        public string Index2()
        {
            return TempData != null ? (TempData["A"]?.ToString() ?? "No TempData Value") : "No TempData";
        }
}
```

4)After running the app and calling /Default/Index I see "No TempData Value"
5) If I only move app.UseCookiePolicy(); to after app.UseMvc();  I see "TempData Works!"


B) I read https://docs.microsoft.com/aspnet/core/fundamentals/app-state#configure-the-tempdata-provider and then https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.1&tabs=aspnetcore2x#ordering

In the first one it says

> The order of middleware is important. In the preceding example, an InvalidOperationException exception occurs when UseSession is invoked after UseMvc,

this one says nothing about UseCookiePolicy() and we will not get a exception it this situation, only temp data is always empty

And in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/index?view=aspnetcore-2.1&tabs=aspnetcore2x#ordering I did not find any thing about UseCookiePolicy() too

**Comment by guardrex** [comment]
I'm re-opening this for further investigation. I should be able to get to it on the next sprint (*in theory* 😅).
