### ISSUE TITLE
There was an error trusting HTTPS developer certificate

### ISSUE THREAD

**Issue by rodrickmakore** [aspnet/Docs#8043]
I am unable to trust dev-certs on my machine. The error I am getting when I run the command is "**There was an error trusting HTTPS developer certificate**". I am running Windows 10 version 1803 (OS Build 17134.191).

![image](https://user-images.githubusercontent.com/2578638/44002367-b4b15098-9e41-11e8-80a4-f031f64e3e69.png)

**Comment by guardrex** [comment]
Hello @rodrickmakore ... that will get better visibility to the MS engineers if you open it over on the aspnet/Home issues. If you find a docs enhancement opportunity after you find out why it's failing, please post back over here on this issue. https://github.com/aspnet/Home/issues

**Comment by rodrickmakore** [comment]
Thank you, I have done so.
