### ISSUE TITLE
Internal Server Error. The view Welcome was not found.

### ISSUE THREAD

**Issue by CharlieIoD** [aspnet/Docs#8044]
In: Add a view to an ASP.NET Core MVC app,
I get to: "Create a Welcome view template named Views/HelloWorld/Welcome.cshtml." This I take to mean that the Welcome.cshml is inside the HelloWorld folder. I follow the same process as for creating the HelloWorld Razor View, then replace the contents of the Welcome.cshml as before and everything seems OK. However, when I save the files and press Ctrl/F5, the build does not proceed as normal it just immediately opens the browser. When I run the URL: https://localhost:44300/HelloWorld/Welcome?name=Rick&numtimes=4 Iget: "Internal Server Error. The view Welcome was not found." If I delete the Welcome file and recreate it under Views, I get the same result. What am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x&view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The instructions are at https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1
