### ISSUE TITLE
Too many digressing links. The tutorial seems to be talking to an experienced programmer and gives too much information too soon.

### ISSUE THREAD

**Issue by CharlieIoD** [aspnet/Docs#8046]
oo many digressing links. The tutorial seems to be talking to an experienced programmer and gives too much information too soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by JonWilmer** [comment]
I didn't feel there were too many links, as it was mitigated by (most of) them being prefaced by "You don't need to review each link provided below. The links are provided as a reference when you need more information..."

**Comment by Rick-Anderson** [comment]
@JonWilmer Thanks for your comment. My feeling is these links help those who want to dive deeper - maybe on a 2nd look at the tutorial.

**Comment by Rick-Anderson** [comment]
cc @BillWagner @tdykstra I think removing all external links would be a disaster for this tutorial and turn it into a cook-book recipe that must be followed exactly. When you have time take a look at the links. For example, most folks want to know why the app is asking about privacy. You have to accept to unmask the menu items. I think the GDPR link is essential.

**Comment by Gaelmart** [comment]
Bower is no more. 
How do move forward with this as its now completely out  of date.
