### ISSUE TITLE
Diagram for filter execution is incorrect

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Docs#8053]
The diagram here - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#filter-types - is incorrect. I wasn't sure what was used to draw it, so I couldn't send a PR, but here's what it needs to look like:

![image](https://user-images.githubusercontent.com/174281/44052667-0e9dd03a-9ef2-11e8-9385-0a3caf992e26.png)

**Comment by scottaddie** [comment]
Submitted artwork creation request [1323083](https://mseng.visualstudio.com/TechnicalContent/Art/_workitems/edit/).
