### ISSUE TITLE
This is a great getting started course!

### ISSUE THREAD

**Issue by alarum** [aspnet/Docs#8054]
Having recently moved platforms at my place of employment from PHP to Microsoft stack, this is definitely a fantastic, comprehensive walkthrough of how to stand up a .NET MVC application that is amazingly easy to follow along with!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@alarum  thanks for the feedback.
