### ISSUE TITLE
No explanation for how multiple parameters are inferred

### ISSUE THREAD

**Issue by alexdresko** [aspnet/Docs#8057]
Prior to the new ApiController, the follow code worked fine:

[HttpPost("Name/{name}/Status")]
public Task&lt;ActionResult&lt;bool&gt;&gt; Status(string name, [FromBody]string status)
Our presumption was that the following would be equivalent after the 2.1 changes (the only difference being that [FromBody] was removed):

[HttpPost("Name/{name}/Status")]
public Task&lt;ActionResult&lt;bool&gt;&gt; Status(string name, string status)
I don't see anything in this document that explains how the two signatures are treated differently.

For the record, we now get a model binding error (400 bad request) saying that "name is required". I'm unable to determine if it's referring to the name parameter in the Status method, or if it's somehow picking a different action on the controller and complaining about that.

Further, POSTing to the API like this does work: /name/whatever/status?status=anything. But since we need to post status in the body, this solution does not work.

Do we need to go back to [FromBody] or is there something else we're missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b391017f-25e1-d5e1-c4f7-020408ade7b5
* Version Independent ID: 263a7b64-2e42-bbfc-c1d3-61680438e1e4
* Content: [Build web APIs with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/web-api/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/index.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by alexdresko** [comment]
Well, I _may_ have figured it out. Went hunting through the source code (I'm always amazed when I'm able to do this quickly and easily), and found this:

https://github.com/aspnet/Mvc/blob/504da3c565a9a159365b4564dba5f2cd7d059e7f/src/Microsoft.AspNetCore.Mvc.Core/Internal/ApiBehaviorApplicationModelProvider.cs#L229

So I came back to the doc find found this: "[FromBody] is inferred for complex type parameters.". 

Why such a limitation? Feel free to close if necessary. Or I can create an issue to request an explanation for why simple types aren't supported.

**Comment by scottaddie** [comment]
@alexdresko You can open an issue in the aspnet/Mvc to ask engineering about the limitation.

**Comment by alexdresko** [comment]
Done. https://github.com/aspnet/Mvc/issues/8267
