### ISSUE TITLE
Unit testing filters

### ISSUE THREAD

**Issue by kajbonfils** [aspnet/Docs#8061]
Hi,

Great documentation!

 I would like some more details on unit testing filters. It's not exactly straigt forward to mock the context objects that is needed. Please provide some advice on that.

-Kaj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kajbonfils  thanks for the suggestion.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
