### ISSUE TITLE
How to download just the sample

### ISSUE THREAD

**Issue by ImageQC** [aspnet/Docs#8062]
I am looking at cookie authentication without ASP.NET Core Identity

- https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.mdl

and want to download just the sample rather than the entire github.com/aspnet/Docs.git which takes hours. The documentation gives a hopeful link "View or download sample code (how to download)", but unfortunately there isn't any explanation. 

I've tried doing sparse checkout, but it still is taking hours. I just want to download your sample to see if it meets my needs. Would it be possible to provide a ZIP for just the sample?

In case someone want to know how to do sparse checkout the following might help, but it still involves downloading the entire Docs.git into the git directory which takes some time.

```
cd C:\Users\Will\Source\Repos\Spikes\cookie\2.x
git init
git remote add -f origin git://github.com/aspnet/Docs.git
git config core.sparsecheckout true
echo "tree/master/aspnetcore/security/authentication/cookie/samples2.x/CookieSample" >> .git/info/sparse-checkout
git pull origin master

```

By the way, anyone wanting to rebuild the sample will need to install .NET Core SDK 2.1.302 [getting started](https://www.microsoft.com/net/learn/get-started-with-dotnet-tutorial) or elsewhere

**Comment by guardrex** [comment]
The docs engineers are working on a solution that will allow individual sample downloads. We don't have an ETA yet for it. https://github.com/aspnet/Docs/issues/6991#issuecomment-398104010

**Comment by ImageQC** [comment]
Thanks. In the interim, I suggest you post a link on the page to this issue.
