### ISSUE TITLE
Generic host can not read app setting when I install as Windows Service

### ISSUE THREAD

**Issue by huyjack178** [aspnet/Docs#8065]
I use this code to read Configuration, after build, I execute the exe file. It runs perfectly. But after install as Window Service, it throw null exception when get config. Can anyone help me?

```
 var currentDirectory = Directory.GetCurrentDirectory();
            var configFileName = "appsettings.json";

            Console.WriteLine("Get Configuration");

            if (File.Exists(Path.Combine(currentDirectory, configFileName)))
            {
                Console.WriteLine("Exist Configuration");

                var builder = new ConfigurationBuilder()
                    .SetBasePath(currentDirectory)
                    .AddJsonFile(configFileName);

                return builder.Build();
            }

            return null;
```

**Comment by guardrex** [comment]
Hello @huyjack178 ... A Windows Service runs out of the `C:\WINDOWS\system32` folder. It would work if your *appsettings.json* file was placed there, but that's not a good solution. Instead of using `Directory.GetCurrentDirectory()`, set your `currentDirectory` to a stable location on disk (absolute path) where you can keep the settings file.

**Comment by guardrex** [comment]
I'd like to add a note on this to the topic. This is going to be a common scenario, and devs should be told what the current directory is for a Windows Service.

**Comment by guardrex** [comment]
One possibility is to use the `IHostingEnvironment.ContentRootPath` ... it will point to the same path that the `binPath` that was used to create the service.

**Comment by huyjack178** [comment]
Can you explain more how to use it ?

**Comment by huyjack178** [comment]
![image](https://user-images.githubusercontent.com/11793001/44142460-687e926a-a0aa-11e8-9ee2-1448ec9d9d54.png)
I use content root path but still got error
The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\WINDOWS\system32\appsettings.json'.

**Comment by guardrex** [comment]
@huyjack178 What does ...

```
hostContext.HostingEnvironment.ContentRootPath
```
... return?

Does it return the same path as the `binPath` you supplied when creating the service? If so, then you should be able (in theory) to have the *appsettings.json* file in the published output at that path and it should find it, not in the *system32* folder. The *system32* folder is what `Directory.GetCurrentDirectory()` returns.

I had a successful test here yesterday, but I was using a Web Host-based Windows Service. If you still have trouble with it, let me know, and I'll run a test here with a Generic Host-based Windows Service.
