### ISSUE TITLE
document `HubConnection.onclose(callback);`

### ISSUE THREAD

**Issue by yzorg** [aspnet/Docs#8077]
There seems to be no documentation on `HubConnection.onclose(callback);`.

https://github.com/aspnet/SignalR/blob/fc8979aecab257c1d837ccfab0f6694e4f2e9179/clients/ts/signalr/src/HubConnection.ts#L275 

Also, if there are samples for client automatically reconnecting?  I couldn't find them.  I was porting from server-sent-events (aka `new EventSource(url)`) which provides automatic reconnect (by the browser/platform).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@anurse Do you have any docs covering this?

**Comment by BrennanConroy** [comment]
There is a link to the [JavaScript API](https://docs.microsoft.com/en-us/javascript/api/?view=signalr-js-latest) in the `Table Of Contents` although it would probably be useful to link it in the javascript-client doc too.

**Comment by scottaddie** [comment]
@BrennanConroy I'll take care of adding that link.

@yzorg Does this help you? https://docs.microsoft.com/en-us/javascript/api/%40aspnet/signalr/hubconnection?view=signalr-js-latest#onclose

**Comment by yzorg** [comment]
@scottaddie Yes!

I didn't notice it in the MS docs table of contents, but I did look for it on [NPM page for the JS/TS client](https://www.npmjs.com/package/@aspnet/signalr).  The NPM page links here.

Consider adding a link from the NPM page to the detailed JS API docs?

**Comment by scottaddie** [comment]
@BrennanConroy Any interest in adding a JS API ref link on the npm package page? Not sure who owns that.

**Comment by BrennanConroy** [comment]
Sounds good, we can look at doing this for 2.2.0 (we own that page, it is from https://github.com/aspnet/SignalR/blob/release/2.2/clients/ts/signalr/README.md)

**Comment by BrennanConroy** [comment]
Filed https://github.com/aspnet/SignalR/issues/2806

**Comment by yzorg** [comment]
@scottaddie After thinking about it for 24 hours... I ask you to consider `onclose()` for attention in the JS client docs page.

Do you think a section about handling disconnect/reconnect is unique to me, or do you think it might be common enough to cover in the main docs?

Of course it would change when SignalR clients get automatic reconnection feature, [aspnet/SignalR#1057](https://github.com/aspnet/SignalR/issues/1057).  (At which point I assume disconnect/reconnect would need to be covered in the docs.)

**Comment by anurse** [comment]
#6757 is tracking reconnect documentation.
