### ISSUE TITLE
Videos of this tutorial

### ISSUE THREAD

**Issue by krchome** [aspnet/Docs#8085]
Hi Rick,
Greetings! I have been following your articles and doing the steps at my own time and pace and have found them extremely useful for enhancing my knowledge. Can I have your permission to create  a series of videos of these articles and publish it on YouTube? 
Regards,
Kaushik Roy Chowdhury, Christchurch, NZ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@krchome  thanks for the complement.
See https://github.com/aspnet/Docs/blob/master/LICENSE 
Looks like it's OK as long as you :

* Don't charge
* Provide proper credit to the official Docs

**Comment by Rick-Anderson** [comment]
@krchome  and we look forward to the videos.
