### ISSUE TITLE
clarification: SignalR token authN

### ISSUE THREAD

**Issue by foxjazz** [aspnet/Docs#8094]
For token authentication, signalR is required? Are any open source databases to be supported in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **anurse**

**Comment by scottaddie** [comment]
@anurse @BrennanConroy Thoughts?

**Comment by anurse** [comment]
I don't understand the question. SignalR requires that you use either cookie authentication or token authentication. We don't specify the kind of database you use for authentication, you can use anything you want.
