### ISSUE TITLE
Had to Add Microsoft.AspNetCore.StaticFiles

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#8099]
**Env:** ASP.Net Core 2.1 (API Project Template) **on Full Framework**

After I added the code to `ConfigureServices` and `Configure`, `/swagger/v1/swagger.json` worked but `/swagger` didn't.

I was getting:
![image](https://user-images.githubusercontent.com/14079228/44160705-3716b980-a089-11e8-8649-92ed9b8d7da9.png)

I found [this issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/483) and once I added a reference to `Microsoft.AspNetCore.StaticFiles` it worked!

![image](https://user-images.githubusercontent.com/14079228/44160884-c2904a80-a089-11e8-86f3-5e51eba88d29.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@spottedmahn  The 2.1 templates generate the following in the project file
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.3" />
  </ItemGroup>
```

`"Microsoft.AspNetCore.App"` includes `Microsoft.AspNetCore.StaticFiles`

**Comment by Rick-Anderson** [comment]
Never mind, missed the full framework part.

**Comment by spottedmahn** [comment]
Hi @Rick-Anderson - this might not be a documentation issue and a product issue?  Thoughts? 💭

**Comment by Rick-Anderson** [comment]
@spottedmahn  sounds like a doc issue. @scottaddie  do you need to add that on the doc page?

**Comment by scottaddie** [comment]
@spottedmahn Thank you for reporting this issue. When targeting .NET Framework, you do need a reference to the StaticFiles package. I'll get the doc updated today.
