### ISSUE TITLE
Cancellation and short circuiting instructions

### ISSUE THREAD

**Issue by thutson** [aspnet/Docs#8101]
The link in here for instructions on how to cancel/short circuit the pipeline  points to the Advanced MVC filters section(https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#cancellation-and-short-circuiting) however the top of that page states that the topic does not refer to Razor Pages and points back to this page. What is the proper way to do this in Razor Pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm [See Cancellation and short circuiting for instructions to short-circuit the filter pipeline from a filter.](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1#authorize-filter-attribute) link here which points to [Cancellation and short circuiting](xref:mvc/controllers/filters#cancellation-and-short-circuiting) 

How do you cancel in RP?

**Comment by Rick-Anderson** [comment]
@pranavkm [See Cancellation and short circuiting for instructions to short-circuit the filter pipeline from a filter.](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/filter?view=aspnetcore-2.1#authorize-filter-attribute) link here which points to [Cancellation and short circuiting](xref:mvc/controllers/filters#cancellation-and-short-circuiting) 

How do you cancel in RP?

**Comment by pranavkm** [comment]
The filter pipeline is identical except for Action Filters - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#filter-types. Canceling and short-circuiting work the same way as it does for controller actions.
