### ISSUE TITLE
MinimumAgeRequirement

### ISSUE THREAD

**Issue by fabercs** [aspnet/Docs#8117]
I didn't see any reference or declaration for "MinimumAgeRequirement" object defined on line, 
policy.AddRequirements(new MinimumAgeRequirement(age));
Where does it come from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150023ea-e35a-4a06-6f71-7ab63994b07f
* Version Independent ID: 7b5c3832-a5a3-a27a-eed3-3ecfc3e8dbe2
* Content: [Custom Authorization Policy Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/iauthorizationpolicyprovider.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/iauthorizationpolicyprovider.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
See the linked sample app in the aspnet/AuthSamples repo ...

https://github.com/aspnet/AuthSamples/blob/master/samples/CustomPolicyProvider/Authorization/MinimumAgeRequirement.cs

**Comment by guardrex** [comment]
I'll make that sample app more visible by placing a link to at the top of the topic.
