### ISSUE TITLE
docs translation

### ISSUE THREAD

**Issue by KantJoe** [aspnet/Docs#812]
hi guys,i'm newly learn asp.net5 and i new to github,and there's a interesting idea on my mind.can i build a new branch on chinese version of this doc?

**Comment by shirhatti** [comment]
@KantJoe We definitely plan to support localized docs at some point in the future, but at the moment are docs are still churning pretty rapidly.

We already have an issue tracking this, so I'm closing this as a dupe https://github.com/aspnet/Docs/issues/416
