### ISSUE TITLE
Great tutorial, minor change needed however

### ISSUE THREAD

**Issue by motor75** [aspnet/Docs#8121]
I just ran thru the whole tutorial but the screen shots for Postman were not working for me.  First, I had to remove the "https" in the URL and second I had to adjust the Port to 5000 in the address.  The screenshots should be updated to reflect these changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@motor75  thanks for the report. I'll get this updated.

**Comment by gagouche** [comment]
Could you create another walk through showing how to secure and deploy this API to Azure?

**Comment by Rick-Anderson** [comment]
@gagouche  that's planned in #6233

**Comment by daveabrock** [comment]
@Rick-Anderson I will do this one. Update to come in the next day or so.

**Comment by Rick-Anderson** [comment]
@daveabrock wait until #9469 merges after RTW

> Could you create another walk through showing how to secure and deploy this API to Azure?

Secure is covered by #6233

Deploy to Azure is no different than the many azure deployment tutorials. I'd rather not create a duplicate topic, too much maintenance on Azure deployment.

**Comment by Rick-Anderson** [comment]
@motor75 	> I had to remove the "https" in the URL

You're doing something wrong. You don't want to do that.
