### ISSUE TITLE
fatihkurul

### ISSUE THREAD

**Issue by FatihKurul34** [aspnet/Docs#8127]
good vibes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e3baf6-6cba-aee0-9a8d-1e1fced2b690
* Version Independent ID: 74b76258-36a3-17de-6648-292da0a9e400
* Content: [Create a web app with ASP.NET Core MVC on Windows with Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@FatihKurul34  thanks.
