### ISSUE TITLE
Seed Data as Migration 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8137]
See #7342

Do this on next tutorial update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 145343de-9267-9171-b6c9-718703b7544d
* Version Independent ID: 2c2f791f-d41c-f995-a941-2461151a7db4
* Content: [Razor Pages with EF Core in ASP.NET Core - Migrations - 4 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/migrations?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/migrations.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/migrations.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Cross-references:

* https://github.com/aspnet/Docs/issues/9205
* https://github.com/aspnet/Docs/pull/9282

**Comment by Rick-Anderson** [comment]
Dup of #9205
