### ISSUE TITLE
Update Angular SSR docs to match updated Angular 6 template

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#8139]
_From @SteveSandersonMS on August 16, 2018 17:24_

The current docs are at https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#server-side-rendering

Discussed with @ryanbrandenburg

_Copied from original issue: aspnet/Templating#677_

**Comment by danroth27** [comment]
@RickAndMSFT This needs to be done as part of the 2.2 doc effort.

**Comment by ryanbrandenburg** [comment]
It seems that `AngularCliBuilder` is broken for our scenario here. Basically we're [ending up with](https://github.com/aspnet/JavaScriptServices/blob/master/src/Microsoft.AspNetCore.SpaServices.Extensions/AngularCli/AngularCliBuilder.cs#L55) `npm run build:ssr -- --watch`, which fails with `Unknown option: '--watch'`. @SteveSandersonMS do you have any history on why that --watch is there and how we might better handle this situation?

**Comment by SteveSandersonMS** [comment]
The `--watch` is so it keeps running in the background to regenerate the dist files whenever the developer modifies `.ts` sources. Maybe Angular 7 has renamed the option, in which case we should update to match (though then we need to drop compatibility with older versions of Angular).

**Comment by mkArtakMSFT** [comment]
Talked to @danroth27 regarding this. The plan is to remove Angular SSR docs as it'll be a headache to keep up with the changes they will come up.

**Comment by ryanbrandenburg** [comment]
Fixed by #11151.
