### ISSUE TITLE
[Question] Where does 'package' name come from?

### ISSUE THREAD

**Issue by d-dizhevsky** [aspnet/Docs#8140]
In this section: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1#url-generation-reference it says that the code above results in such url `/package/create/123`. I assume that the route is `{controller}/{action}/{id}`, but where does `package` come from in url? 

```
    var dictionary = new RouteValueDictionary
    {
        { "operation", "create" },
        { "id", 123}
    };
```

Based on the given dictionary shouldn't it be `operation/create/123`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1#url-generation-reference)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It comes from the "Track Package Route" template ([Using Routing Middleware section](https://docs.microsoft.com/aspnet/core/fundamentals/routing#using-routing-middleware)) ...

```csharp
routeBuilder.MapRoute(
    "Track Package Route",
    "package/{operation:regex(^track|create|detonate$)}/{id:int}");
```

The dict is supplying the operation and id.

**Comment by guardrex** [comment]
As you suggest, it's not plain enough ... I'll add a little blurb there where the value is stated to clarify it.

**Comment by d-dizhevsky** [comment]
@guardrex I see, thanks. This happens when you are reading specific section of the doc/tutorial only and thus, loses the context/meaning/reference between code samples.

**Comment by guardrex** [comment]
I agree ... and that template was shown *forever ago* reading the topic top-to-bottom. I'll show the template again and say the dict is filling in those two segments.
