### ISSUE TITLE
ActionResult<T> controller method example

### ISSUE THREAD

**Issue by mberginbh** [aspnet/Docs#8147]
How do I test a controller method returning ActionResult&lt;T&gt; or Task&lt;ActionResult&lt;T&gt;&gt; in 2.1?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@guardrex The sample you provided above reflects what I would've recommended.

**Comment by guardrex** [comment]
Ty @scottaddie I'll get something along those lines surfaced when I perform the sample upgrade on #5495.

**Comment by mberginbh** [comment]
Thank you both. Might be worth adding an example unit test for a failure case e.g. `BadRequestResult` too.

**Comment by guardrex** [comment]
@mberginbh As far as I can tell, a `BadRequestResult` won't be returned ... the `ActionResult<T>` resolves to `NotFoundObjectResult` when the controller is executed and returns a `NotFound` on whatever non-existent ID is given to it. What we'll do is have the engineers (who really know how to write software :smile:) tell me if the test I'm setting up is sane.

Regarding the `Task<ActionResult<T>>` test, which was your original suggestion :point_up:, that seems fine the way I have it set up. I think the engineers will be ok with it, but we'll find out soon enough.

I'll have this PR submitted soon ... I still need to update the topic text for the action and tests and make sure the 2.1 updates are all good. I'll ping u on the PR.

**Comment by pascalpfeil** [comment]
Do unit tests really change that much when using
```csharp
ActionResult<T>
```
instead of
```csharp
IActionResult
```
?

Doesn't
```csharp
// Assert
var redirectToActionResult = Assert.IsType<RedirectToActionResult>(result);
Assert.Null(redirectToActionResult.ControllerName);
Assert.Equal("Index", redirectToActionResult.ActionName);
```
just become
```csharp
var redirectToActionResult = Assert.IsType<RedirectToActionResult>(result.Result);
Assert.Null(redirectToActionResult.ControllerName);
Assert.Equal("Index", redirectToActionResult.ActionName);
```
?

Or am i doing ith wrong?

**Comment by guardrex** [comment]
@pascalpfeil 

Those would be fine for integration tests. This topic focuses on unit tests. In a unit test, I'd like to confirm the following ...

1. Is the return type an `ActionResult`?
1. Is the `ActionResult`'s value the correct type?
1. Is the first value of that returned object the correct?

... then when the `ActionResult` comes back with no objects, I want to know ...

1. (Same as before ...) Is the return type an `ActionResult`?
1. Is the `ActionResult` a `NotFoundObjectResult`?

Take a look at the tests I did for the PR: https://github.com/aspnet/Docs/blob/74ba2ecf00796a1ac7589320a8fc5ddf1e053308/aspnetcore/mvc/controllers/testing/sample/TestingControllersSample/tests/TestingControllersSample.Tests/UnitTests/ApiIdeasControllerTests.cs#L134-L170

**Comment by pascalpfeil** [comment]
@guardrex thank you for your response. That cleared things up.

But how would i test the following code?
```csharp
public async Task<ActionResult<Entity>> PostEntity(/* ... */)
{
    if (!ModelState.IsValid)
        return BadRequest(ModelState);
    try
    {
        var entity = await _repo.CreateEntity(/* ... */);
        return CreatedAtAction("GetEntity", new { id = entity.Id }, entity);
    }
    /* ... */
}
```

My Test with ```Microsoft.VisualStudio.TestTools.UnitTesting``` looks something like this:
```csharp
[TestMethod]
public async Task TestPostEntity_OK()
{
    //Arrange
    var entity= new Entity { /* ... */ };
    mockRepo.Setup(repo=> repo.CreateEntity(/* ...*/)).Returns(Task.FromResult(entity));

    //Act
    var result = await sutController.PostEntity(/* ...*/);

    //Assert
    //This works
    Assert.IsInstanceOfType(result, typeof(ActionResult<Entity>));

    //This fails, entity is null
    Assert.AreEqual(entity, result.Value);
}
```

As you can see, the ```result.Value``` property stays null, while your ```actionResult.Value``` in line 148 is populated.

**Comment by guardrex** [comment]
Not sure ... what is `result.Result` when `result.Value` is `null`?

**Comment by pascalpfeil** [comment]
It is a ```CreatedAtActionResult``` whose ```object Value``` property is ```entity```. This must be because i do ```return CreatedAtAction(/* ... */)``` instead of ```return entity```, right? Whats the right way to unit test this?

**Comment by guardrex** [comment]
I understand you want to return a 201 with your POST. A `CreatedAtActionResult` is something that we may need to add to the examples. Thus far, the example just returns a list of `IdeoDTO` objects ...

```csharp
public async Task<ActionResult<List<IdeaDTO>>> ForSessionActionResult(int sessionId)
{
    var session = await _sessionRepository.GetByIdAsync(sessionId);

    if (session == null)
    {
        return NotFound(sessionId);
    }

    var result = session.Ideas.Select(idea => new IdeaDTO()
    {
        Id = idea.Id,
        Name = idea.Name,
        Description = idea.Description,
        DateCreated = idea.DateCreated
    }).ToList();

    return result;
}
```

I need to step out for a couple of hours, but I'll be back later today. I'll see what I can do with the sample app (and PR) and then report back to you. I'm new to `ActionResult<T>` and testing `ActionResult<T>` myself, so I'll need to work through it and see what's what. I'll get back to you in a couple of hours.

**Comment by pascalpfeil** [comment]
Thank you very much for your time!

**Comment by guardrex** [comment]
@pascalpfeil I think this worked out fairly well so far. I created a method to receive a POST, lookup a session, add a new idea to it, and then return the session. It's nearly a copy of the existing method (`Create`) that was already in the topic sample ...

```csharp
[HttpPost("createactionresult")]
[ProducesResponseType(201)]
public async Task<ActionResult<BrainstormSession>> CreateActionResult([FromBody]NewIdeaModel model)
{
    if (!ModelState.IsValid)
    {
        return BadRequest(ModelState);
    }

    var session = await _sessionRepository.GetByIdAsync(model.SessionId);
    if (session == null)
    {
        return NotFound(model.SessionId);
    }

    var idea = new Idea()
    {
        DateCreated = DateTimeOffset.Now,
        Description = model.Description,
        Name = model.Name
    };
    session.AddIdea(idea);

    await _sessionRepository.UpdateAsync(session);

    return session;
}
```

Then, I based three tests on it ...

```csharp
[Fact]
public async Task CreateActionResult_ReturnsNewlyCreatedIdeaForSession()
{
    // Arrange
    int testSessionId = 123;
    string testName = "test name";
    string testDescription = "test description";
    var testSession = GetTestSession();
    var mockRepo = new Mock<IBrainstormSessionRepository>();
    mockRepo.Setup(repo => repo.GetByIdAsync(testSessionId))
        .Returns(Task.FromResult(testSession));
    var controller = new IdeasController(mockRepo.Object);

    var newIdea = new NewIdeaModel()
    {
        Description = testDescription,
        Name = testName,
        SessionId = testSessionId
    };
    mockRepo.Setup(repo => repo.UpdateAsync(testSession))
        .Returns(Task.CompletedTask)
        .Verifiable();

    // Act
    var result = await controller.CreateActionResult(newIdea);

    // Assert
    var actionResult = Assert.IsType<ActionResult<BrainstormSession>>(result);
    var returnValue = Assert.IsType<BrainstormSession>(actionResult.Value);
    mockRepo.Verify();
    Assert.Equal(2, returnValue.Ideas.Count());
    Assert.Equal(testName, returnValue.Ideas.LastOrDefault().Name);
    Assert.Equal(testDescription, returnValue.Ideas.LastOrDefault().Description);
}

[Fact]
public async Task CreateActionResult_ReturnsNotFoundObjectResultForNonexistentSession()
{
    // Arrange
    var nonExistentSessionId = 999;
    string testName = "test name";
    string testDescription = "test description";
    var mockRepo = new Mock<IBrainstormSessionRepository>();
    var controller = new IdeasController(mockRepo.Object);

    var newIdea = new NewIdeaModel()
    {
        Description = testDescription,
        Name = testName,
        SessionId = nonExistentSessionId
    };

    // Act
    var result = await controller.CreateActionResult(newIdea);

    // Assert
    var actionResult = Assert.IsType<ActionResult<BrainstormSession>>(result);
    Assert.IsType<NotFoundObjectResult>(actionResult.Result);
}

[Fact]
public async Task CreateActionResult_ReturnsBadRequest_GivenInvalidModel()
{
    // Arrange & Act
    var mockRepo = new Mock<IBrainstormSessionRepository>();
    var controller = new IdeasController(mockRepo.Object);
    controller.ModelState.AddModelError("error", "some error");

    // Act
    var result = await controller.CreateActionResult(model: null);

    // Assert
    var actionResult = Assert.IsType<ActionResult<BrainstormSession>>(result);
    Assert.IsType<BadRequestObjectResult>(actionResult.Result);
}
```

... and those tests pass.

Before going any further and adding text to the topic in the PR, I'd like to wait until @scottaddie gets back (he's OOF for a bit) so that we can discuss further the 200/201/400 situation. 

I added the `ProducesResponseType` decorations ...
```csharp
[ProducesResponseType(200)]
```
... and ...
```csharp
[ProducesResponseType(201)]
```
The question is are those obtainable in the tests when the methods fully execute and return a valid result?

The `ActionResult<T>.Result` only appears to receive a value when the method returns a non-200/201. 

The tests with the failure assertions get the right types checked with ...

```csharp
Assert.IsType<NotFoundObjectResult>(actionResult.Result);
```
... and ...
```csharp
Assert.IsType<BadRequestObjectResult>(actionResult.Result);
```

... but I am unclear on when `ActionResult<T>.Value` receives a value and the result is a 200/201 how to test for a 200/201 status code (i.e., `ControllerBase.Ok`).

**Comment by pascalpfeil** [comment]
I don't think
```csharp
[HttpPost("createactionresult")]
[ProducesResponseType(201)]
public async Task<ActionResult<BrainstormSession>> CreateActionResult([FromBody]NewIdeaModel model)
{
    /* ... */
    return session;
}
```
will actually return 201 but will return 200.

As shown [here](https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-2.1#asynchronous-action) you'd have to ```return CreatedAtAction(/* ... */)``` to get a 201. Or am i wrong?

**Comment by guardrex** [comment]
Yes, I copied the original test *too closely*. I'll mirror the one for async `ActionResult<T>` that Scott placed here ...

https://docs.microsoft.com/aspnet/core/web-api/action-return-types#asynchronous-action-1

**Comment by guardrex** [comment]
`CreatedAtAction` did produce the desired `ActionResult<T>.Result` of `CreatedAtActionResult` and ...

```
Assert.IsType<CreatedAtActionResult>(actionResult.Result);
```

... passes. However, now `ActionResult<T>.Value` is `null`. Again, `.Value` and `.Result` never seem to be populated simultaneously.

**Comment by pascalpfeil** [comment]
@guardrex 
Yes, this is what i oberserved, too. So in unit tests, you would just check the ```CreatedAtActionResult.Value``` property, right?

**Comment by guardrex** [comment]
**_Yes!_** Now, we're cook'in. This works ...

```csharp
// Assert
var actionResult = Assert.IsType<ActionResult<BrainstormSession>>(result);
var createdAtActionResult = Assert.IsType<CreatedAtActionResult>(actionResult.Result);
var returnValue = Assert.IsType<BrainstormSession>(createdAtActionResult.Value);
mockRepo.Verify();
Assert.Equal(2, returnValue.Ideas.Count());
Assert.Equal(testName, returnValue.Ideas.LastOrDefault().Name);
Assert.Equal(testDescription, returnValue.Ideas.LastOrDefault().Description);
```

**Comment by guardrex** [comment]
... and now, I can set the other response types on the method ...

```
[ProducesResponseType(400)]
[ProducesResponseType(404)]
```
... and check for the status codes. For example for *Not Found* ...

```csharp
// Assert
var actionResult = Assert.IsType<ActionResult<List<IdeaDTO>>>(result);
var createdAtActionResult = Assert.IsType<NotFoundObjectResult>(actionResult.Result);
Assert.Equal(404, createdAtActionResult.StatusCode);
```

![hannibalsmith](https://user-images.githubusercontent.com/1622880/44855749-5e48bb80-ac31-11e8-97ff-36bff48a86a3.jpg)


_"I love it when a plan comes together!"_ - John "Hannibal" Smith ([George Peppard](http://www.imdb.com/name/nm0000577/)), [The A-Team](https://www.nbc.com/the-a-team), ©1983-87 [Universal Television](http://www.nbcuniversal.com/business/universal-television) [Stephen J. Cannell](http://www.cannell.com/)

**Comment by pascalpfeil** [comment]
Shouldn't it be
```csharp
// Assert
var actionResult = Assert.IsType<ActionResult<List<IdeaDTO>>>(result);
var notFoundObjectResult= Assert.IsType<NotFoundObjectResult>(actionResult.Result);
Assert.Equal(404, notFoundObjectResult.StatusCode);
```
?

And aren't those two lines redundant?
```csharp
var createdAtActionResult = Assert.IsType<NotFoundObjectResult>(actionResult.Result);
Assert.Equal(404, createdAtActionResult.StatusCode);
```

Also nice meme :ok_hand:

**Comment by guardrex** [comment]
> aren't those two lines redundant?

Probably ... I just wanted to see the status code. There are two approaches, and the first one I had is better (shorter) ...

```csharp
Assert.IsType<NotFoundObjectResult>(actionResult.Result);
```

I note that I didn't have to have the `ProducesResponseType`s to get those to pass either. Anyway, I'll leave the `ProducesResponseType`s on the method.

**Comment by guardrex** [comment]
Still wish I could get an `OkObjectResult` out of the `return` ...

```csharp
// Assert
var actionResult = Assert.IsType<ActionResult<List<IdeaDTO>>>(result);

Assert.IsType<OkObjectResult>(actionResult.Result);

var returnValue = Assert.IsType<List<IdeaDTO>>(actionResult.Value);
var idea = returnValue.FirstOrDefault();
Assert.Equal("One", idea.Name);
```

`ActonResult<T>.Result` is `null`, so that doesn't work.

**Comment by thabisomofokeng** [comment]
> **_Yes!_** Now, we're cook'in. This works ...
> 
> ```cs
> // Assert
> var actionResult = Assert.IsType<ActionResult<BrainstormSession>>(result);
> var createdAtActionResult = Assert.IsType<CreatedAtActionResult>(actionResult.Result);
> var returnValue = Assert.IsType<BrainstormSession>(createdAtActionResult.Value);
> mockRepo.Verify();
> Assert.Equal(2, returnValue.Ideas.Count());
> Assert.Equal(testName, returnValue.Ideas.LastOrDefault().Name);
> Assert.Equal(testDescription, returnValue.Ideas.LastOrDefault().Description);
> ```

@guardrex your solution just saved me from hours of struggle. Thanks :)

**Comment by dfoulk** [comment]
> Still wish I could get an `OkObjectResult` out of the `return` ...
> 
> ```cs
> // Assert
> var actionResult = Assert.IsType<ActionResult<List<IdeaDTO>>>(result);
> 
> Assert.IsType<OkObjectResult>(actionResult.Result);
> 
> var returnValue = Assert.IsType<List<IdeaDTO>>(actionResult.Value);
> var idea = returnValue.FirstOrDefault();
> Assert.Equal("One", idea.Name);
> ```
> 
> `ActonResult<T>.Result` is `null`, so that doesn't work.
> 
> [EDIT] Just tacking on to the discussion here that the engineer said that `OkObjectResult` can't be tested under this scenario where the method succeeds and returns the list. In this case, we'll just check the type and a test item. If the test succeeds, we assume a _200 Ok_ is the HTTP response.

I was able to gain access to the `OkObjectResult.Value` in .NET Core 2.2 using xUnit. Not sure which testing framework you are using or if that matters here. Anyways, I was having trouble accessing the returned `IEnumerable<T>` until I set `var okObjectResult = Assert.IsType<OkObjectResult>(...)`.

The below is an example of a working test that accesses the value of the `OkObjectResult`:

```csharp
// Arrange
var controller = new AircraftStatusController(_context);

// Act
var actionResult = await controller.GetAircraftStatuses();

// Assert
Assert.IsType<ActionResult<IEnumerable<ObstAircraftStatus>>>(actionResult);
var okObjectResult = Assert.IsType<OkObjectResult>(actionResult.Result);
var returnValue = Assert.IsAssignableFrom<IEnumerable<ObstAircraftStatus>>(okObjectResult.Value).ToList();
Assert.NotEmpty(returnValue);

// Included this for fun...
Assert.True(returnValue.Count == _context.ObstAircraftStatus.ToList().Count);
```

I found some tests I wrote in a .NET Core 1.1 project that also make use of the `OkObjectResult.Value`. Dont judge, it was early in my testing education :)

Other example of accessing this value:
```csharp
// Arrange
var controller = _fixture.GetAircraftController(true);

// Act
var objectResult = controller.GetAll().Result as OkObjectResult;
var enumerable = objectResult?.Value as IEnumerable<SharedModels.Aircraft>;
var result = enumerable?.ToList();

// Assert
Assert.NotNull(result);
Assert.True(_fixture.AircraftCdi.Any());
Assert.True(result.Count == _fixture.Aircraft.Count);
```

**Comment by moh-hassan** [comment]
The next extension method handle both Result and Value and return the typed object T
```cs
public static T GetObjectResult<T>(this ActionResult<T> result)
        {
            if (result.Result != null)
                return (T)((ObjectResult)result.Result).Value;
            return result.Value;            
        }
```
see my [answer ](https://stackoverflow.com/a/65558567/3142139)on SO
