### ISSUE TITLE
Document known storage libraries with coreclr support.

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Docs#815]
Might be nice to have a page in the docs that talks about what storage engines have produced official drivers that will work with coreclr.

There could be two headings, "Officially Released" and "WIP".

**Comment by atrauzzi** [comment]
Also, perhaps another section with officially released and WIP references to Entity Framework drivers.

**Comment by danroth27** [comment]
We don't plan to document these community offerings in the ASP.NET Core docs.

@rowanmiller The EF Core folks have https://docs.efproject.net/en/latest/providers/index.html.

**Comment by atrauzzi** [comment]
Perhaps if EF is covered anywhere in asp.net docs, you could link to **that** page instead?

**Comment by danroth27** [comment]
EF is covered under https://docs.asp.net/en/latest/data/index.html
