### ISSUE TITLE
Better call AddAzureKeyVault inside Startup class

### ISSUE THREAD

**Issue by kai-wang-** [aspnet/Docs#8153]
Calling AddAzureKeyVault inside Main() method seems not that ideal:
 - Service Fabric app initialized web listener inside CreateServiceInstanceListeners(), not the Main() method.
 - Some other hosting technologies (NT Service, CloudService/WebRole) may also initialize the listener in other methods rather than Main() method. 

‘Startup’ class seems a better place to do  initialization logic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by davidfowl** [comment]
No that’s not ideal. It’s not about main vs startup it’s about using ConfigureAppConfiguration on the WebHostBuilder. In our default template, that happens to be in Main
