### ISSUE TITLE
No VB version of 5 minute app?

### ISSUE THREAD

**Issue by andrewba10** [aspnet/Docs#8154]
There must be a VB version of this app mustn't there? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?tabs=aspnetcore2x&view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@andrewba10  sorry, no.

**Comment by yannpariseau** [comment]
@andrewba10, if you look the comparaison between asp.net and asp.net core, you can see that VB is not available in .net Core, only C# and F#.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/choose-aspnet-framework?view=aspnetcore-2.2

HTH

**Comment by baktay** [comment]
I seems VB is going to be left behind for the new stuff, unfortunately. I am trying to learn c# but its like learning to play guitar all over again switching hands. All the fun is out, struggle with semi columns begin...
