### ISSUE TITLE
Possible to simplify SignalR client library instructions

### ISSUE THREAD

**Issue by manukautech** [aspnet/Docs#8155]
"Add the SignalR client library" instructions in this tutorial need to be simpler. I downloaded one file "signalr.min.js" from the SignalR samples sub-folder on Github and pasted that under "wwwroot". Simple copy and paste works well. No need for the drama of node.js and npm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Tutorial: Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@BrennanConroy  or @anurse please review.

**Comment by BrennanConroy** [comment]
I don't think there is anything to do here. Copying a random "signalr.min.js" file is definitely not the recommended way to get the javascript client.

**Comment by Rick-Anderson** [comment]
Do you have any plans in the future to add *signalr.min.js*, *signalr.js* to the templates?

**Comment by davidfowl** [comment]
We can mention the cdn way to get signalr:
- https://unpkg.com/@aspnet/signalr@1.0.2/dist/browser/signalr.min.js
- https://cdn.jsdelivr.net/npm/@aspnet/signalr/dist/browser/signalr.min.js

**Comment by scottaddie** [comment]
I like @davidfowl's suggestion. If using VS, LibMan is a simple way to do this (as of VS 2017 15.8). The supporting LibMan docs are being published this week.

**Comment by davidfowl** [comment]
Can we show a pure CDN usage as well?

**Comment by tdykstra** [comment]
The general rule for tutorials is to show just one way to do things.  The CDN way would be simpler and probably the better choice for this tutorial.  @scottaddie How about I relegate LibMan to Next steps and redo this to use CDN directly?

**Comment by anurse** [comment]
I'm very much in favor of using CDN instead of LibMan. If npm is too much ceremony, I think LibMan would also be too complicated for the same reasons (and it's much less commonly known).

**Comment by anurse** [comment]
Though we should use [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) and reference a specific version which means the sample could get out of date as new versions are published.

We'd use a reference like this:

```html
<script src="https://unpkg.com/@aspnet/signalr@1.0.2/dist/browser/signalr.min.js" integrity="sha384-T1M/vJFz1G/wS//QkHGRmFPa7P60cK2jnHihXkdaa3Uxip28viR0Xw+A4LHYOc+9" crossorigin="anonymous"></script>
```

But when we want to update the version we'd need to update both the version number (easy but tedious) and the SRI hash (also easy, using https://www.srihash.org/, but still tedious). Perhaps we could add a blurb explaining this to users?

**Comment by tdykstra** [comment]
How often would the file change significantly enough that we would need to change the reference?
