### ISSUE TITLE
Slightly misleading line in Getting Started: Installing ASP.NET 5 On Windows doc

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#816]
@Rick-Anderson @ardalis @danroth27 

RE: https://docs.asp.net/en/latest/getting-started/installing-on-windows.html

The line ...

> 4 On Windows 7 and Windows Server 2008 R2 you will also need to install the Visual C++ Redistributable for Visual Studio 2012 Update 4.

... is a little misleading. It conflates the issue of requiring the install on a machine where the development is occurring (a dev box with VS) with the issue of not requiring that install where the .NET 5 applications may be served (i.e., a WS 2008 R2 box without VS). 

May I suggest some kind of change to clear up any confusion:

A short and sweet change ...

> 4 On Windows 7 and Windows Server 2008 R2 you will also need to install the Visual C++ Redistributable for Visual Studio 2012 Update 4. Note: This step only applies to computers where Visual Studio will be installed.

A professorial long-winded, bloated explanation ...

> 4 On Windows 7 and Windows Server 2008 R2 you will also need to install the Visual C++ Redistributable for Visual Studio 2012 Update 4. Note: This install is only required on Windows Server 2008 R2 if Visual Studio is installed on the server for development purposes. If the server is being used solely to serve ASP.NET 5 applications via IIS, this install is not required on the server. See [Publishing to IIS](https://docs.asp.net/en/latest/publishing/iis.html) for details on Windows Server configuration for ASP.NET 5 application hosting.

**Comment by danroth27** [comment]
@saurabh500

**Comment by kkurni** [comment]
@GuardRex VC++ Redis 2012 is needed because of this open issue.
https://github.com/dotnet/corefx/issues/3760

This will appear if you are using SqlClient. 
AFAIK, Only SqlClient which currently depend on this.
So if it doesn't have sql client dependency, you will not need this VC++ Redis 2012.

I had tried to published web application into IIS, and both still required VC++ redis 2012 to use SqlClient.

**Comment by kkurni** [comment]
OS may automatically installed VC++ Redis 2012 as part of the update.
Or It could be automatically installed on Visual Studio 2012 +.

Maybe we need to change the text to ***"make sure that VC++2012 is installed"*** instead of putting this as a "Step"
Or we can put this into ***"troubleshooting"*** section

**Comment by GuardRex** [comment]
@kkurni I see. I'm not sure where my ref to VS came from. At time, it may have just been confusing to me why this was being required and I guessed wrong.

Whatever is done, I hope the reason that the install is being required can be stated and the platforms and/or application context to which it applies is stated. It's just helpful to know when one can skip it if they don't need it.

**Comment by danroth27** [comment]
Sure we can add a comment clarifying that this is really only required to get SqlClient to work.

**Comment by danroth27** [comment]
This issue is no longer relevant since we have moved to .NET Core.

**Comment by GuardRex** [comment]
@danroth27 There might still be a lingering issue there. I noticed that the VC++ was there by default when I spun up a 2008R2 VM in Azure, but this cat had a problem with an existing server ... https://github.com/aspnet/IISIntegration/issues/179#issuecomment-220172988.

I'll play with it today and see if I can repro what was described there and see how that exception shows up in the various logging. Then, I'll open a normal issue with my findings in the Doc repo for discussion.
