### ISSUE TITLE
worthless if you want to use vb.net.

### ISSUE THREAD

**Issue by eschneider999** [aspnet/Docs#8161]
I guess Microsoft is not smart enough to make it work for vb.net.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf18d20-d28f-1efa-d329-181fff3630fa
* Version Independent ID: 46a7c2e0-4871-491f-02c2-54f7df2237b1
* Content: [Get started with ASP.NET Core MVC and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/tutorials/first-mvc-app/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @eschneider999 ... See the discussion in the aspnet/Home issues. https://github.com/aspnet/Home/issues/2738

**Comment by eschneider999** [comment]
Thanks, saw that.
