### ISSUE TITLE
JWT Token re-new sample

### ISSUE THREAD

**Issue by cnlogistics** [aspnet/Docs#8164]
Regarding your hint, please provide a sample on how to do that on the client side for javascript and C#. Or is the accessTokenFactory automatically invoke again when the Token has expired?

"The access token function you provide is called before every HTTP request made by SignalR. If you need to renew the token in order to keep the connection active (because it may expire during the connection), do so from within this function and return the updated token."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0da2144-3730-f8ef-1d16-a89f11fd6198
* Version Independent ID: 6d8f5bc8-8f5c-ba13-b7f2-0366eac46f81
* Content: [Authentication and authorization in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/authn-and-authz.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/authn-and-authz.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **anurse**

**Comment by Rick-Anderson** [comment]
@anurse  please respond.

**Comment by anurse** [comment]
> Or is the accessTokenFactory automatically invoke again when the Token has expired

The accessTokenFactory is invoked for every request, so you can check the expiry of the token within it. Here's some pseudo-code (`AccessToken`, `IsExpired` and `GetTokenAsync` need to be provided, the implementation depends on how your tokens work):

```csharp
AccessToken currentToken = null;
var connection = new HubConnectionBuilder()
    .WithUrl("...", options => {
        options.AccessTokenFactory = async () =>
        {
            if(currentToken == null || IsExpired(currentToken))
            {
                currentToken = await GetTokenAsync();
            }
            return currentToken.BearerToken;
        };
    })
    .Build();
```

A JWT token should include the expiry in the token itself, so it should be possible to check this against `DateTime.Now` in your `IsExpired` method. Exactly how that works depends on what you are using to provide your tokens.

**Comment by Rick-Anderson** [comment]
@anurse  thanks for the response. I'll leave it up to you if you want to add this to the doc. It's very discoverable from the page.

![image](https://user-images.githubusercontent.com/3605364/44553931-03b8d800-a6e4-11e8-8e7d-ef36774cb098.png)

**Comment by ericbrunner** [comment]
@anurse Thanks for clarifications about the invocation cycle.
At least I expected a running sample for a Javascript Client and a .Net Client. and
why do you close that issue. Documenation os still not updated!
@Rick-Anderson I guess you never developed a real project otherwise you couldn't say "it's discoverable
from the page". Because it's not.

**Comment by ericbrunner** [comment]
Please provide in the documention following examples

1. Javascript Client with JWT auth/re-auth to real Asp.Net Core WebApp with SignalR hub
2. .NET Client with JWT auth/re-auth to real Asp.Net Core WebApp with SignalR hub

**Comment by ericbrunner** [comment]
You can close that issue. I digged through the samples and with regards to that issue I now know how to do it https://github.com/aspnet/SignalR/issues/2864#issuecomment-415953308

Maybe you can reference that samples in the documenation

**Comment by Rick-Anderson** [comment]
@ericbrunner thanks for reporting back. It looks like this is the sample
https://github.com/aspnet/SignalR/tree/release/2.2/samples/JwtSample

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by maxisam** [comment]
I think this can be clearer than "The access token function you provide is called before every HTTP request made by SignalR" If users use websocket, there will be only one http request in the very beginning. The method invoke later won't be able to get updated token if the first token expired. On the other hand, the server side can't really check if the beginning token is expired like your example here
https://github.com/aspnet/SignalR/blob/d0bcdf3dd92afba858fca2871535faf4594c81de/samples/JwtSample/Startup.cs#L49

I feel like the only way to handle this properly is attach the token in every invocation. Am I right?

**Comment by jstallm** [comment]
> > Or is the accessTokenFactory automatically invoke again when the Token has expired
> 
> The accessTokenFactory is invoked for every request, so you can check the expiry of the token within it. Here's some pseudo-code (`AccessToken`, `IsExpired` and `GetTokenAsync` need to be provided, the implementation depends on how your tokens work):
> 
> ```cs
> AccessToken currentToken = null;
> var connection = new HubConnectionBuilder()
>     .WithUrl("...", options => {
>         options.AccessTokenFactory = async () =>
>         {
>             if(currentToken == null || IsExpired(currentToken))
>             {
>                 currentToken = await GetTokenAsync();
>             }
>             return currentToken.BearerToken;
>         };
>     })
>     .Build();
> ```
> 
> A JWT token should include the expiry in the token itself, so it should be possible to check this against `DateTime.Now` in your `IsExpired` method. Exactly how that works depends on what you are using to provide your tokens.

Do you have a similar code snippet for javascript?
