### ISSUE TITLE
is there any book to introduce kestrel?

### ISSUE THREAD

**Issue by tomkluas** [aspnet/Docs#8165]
is there any book to introduce kestrel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@tomkluas There's some discussion about Kestrel in the following book from @andrewlock: https://www.manning.com/books/asp-net-core-in-action. With that being said, is there something lacking or confusing in our doc that we could improve?

**Comment by orangudan** [comment]
@tomkluas Tom, a good place to start looking if you want to understand the request pipeline would be Kestrel's "middleware". You can find more about that here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.2

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
