### ISSUE TITLE
indentation mistake in the text

### ISSUE THREAD

**Issue by pserou** [aspnet/Docs#8166]
In the "Set up a host" paragraph, the indentation of the text should be indented like this instead of the existing text: 

CreateDefaultBuilder performs the following tasks:
…
...
⦁	Loads host configuration from:
		- Environment variables prefixed with ASPNETCORE_ (for example, ASPNETCORE_ENVIRONMENT).
		- Command-line arguments.
⦁	Loads app configuration from:
		- appsettings.json.
		- appsettings.{Environment}.json.
		- User secrets when the app runs in the Development environment using the entry assembly.
		- Environment variables.
		- Command-line arguments.
…
…

otherwise, I really appreciate the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04eafd1b-403a-4aa3-48bc-78fed5b4d05e
* Version Independent ID: f35451f4-7c74-3ada-e969-b769428b94f4
* Content: [ASP.NET Core Web Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/web-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/web-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pserou ... It's a known bug. They're working on a fix. https://github.com/aspnet/Docs/issues/6052
