### ISSUE TITLE
Environment.UserInteractive

### ISSUE THREAD

**Issue by NidhiNagarro** [aspnet/Docs#8167]
Environment.UserInteractive is preferred over (Debugger.IsAttached || args.Contains("--console")) . Then why are we still using this at many places

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
I haven't tested to see if that property would be effective under these circumstances.

@shirhatti

**Comment by guardrex** [comment]
Thanks for commenting @NidhiNagarro ... Test runs didn't produce useful results. `Environment.UserInteractive` returned `True` both when run from the console and run as a service. Engineering provided the current approach, so let's stick with what they suggest.
