### ISSUE TITLE
Thank you for this information)

### ISSUE THREAD

**Issue by OlegLviv** [aspnet/Docs#8169]
Can you help me with reference on same article but i need to deploy on Azure Virtual Machine from vs?
Thank you)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 1a7d2cbf-8299-4482-5113-6a7835ce1064
* Version Independent ID: 9db3a696-1da4-42f0-98b0-3393e83ef582
* Content: [DevOps with ASP.NET Core and Azure](https://docs.microsoft.com/ru-ru/aspnet/core/azure/devops/deploying-to-app-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/azure/devops/deploying-to-app-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/azure/devops/deploying-to-app-service.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by guardrex** [comment]
There's a publish profile for VM's in VS. When you open **Publish**, select for a **New profile**, and you'll see it there.

<img width="360" alt="capture" src="https://user-images.githubusercontent.com/1622880/44347242-e9b99400-a45c-11e8-874e-9e10c2457a18.PNG">

Info on publish profiles is in :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/visual-studio-publish-profiles

**Comment by CamSoper** [comment]
What @guardrex said. Also, [check this doc](https://docs.microsoft.com/azure/virtual-machines/windows/publish-web-app-from-visual-studio).

**Comment by OlegLviv** [comment]
thanks for references but i can't configure web deploy on VM with Windows 10 in example i see only how to deploy on Windows Server so can i actually do that?
