### ISSUE TITLE
SetCompatibilityVersion in the Application startup topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#8170]
@Rick-Anderson @scottaddie Why is `SetCompatibilityVersion` for ASP.NET Core MVC in the *Application startup* topic? ... just to surface it? The content seems much better suited for topics on migration, What's new, release notes, and MVC ... *especially MVC*. `SetCompatibilityVersion` doesn't have anything (directly) to do with app startup.

If it's felt that it's critical to surface it here regardless of its direct relevance, what we could do is leave the extension in the example and have a one-liner mention that links out to the [MVC overview](https://docs.microsoft.com/aspnet/core/mvc/overview), where I think this section should appear. We then link to the section in the *MVC overview* from elsewhere (migration, What's new, release notes, app startup).

**Comment by scottaddie** [comment]
@guardrex Rick may know why it lives there. I personally wouldn't know to look for it in the app startup doc. Instead, I'd look for a "Compatibility modes" topic.

**Comment by guardrex** [comment]
Yes, I think it could either be a section in the MVC overview ... or a whole topic under the MVC node. Either way ... *App startup* concepts don't directly pertain to middleware configuration things.

It's a quick update either way. If I do this, I just need to know if it should be an MVC subtopic or if the section should just be placed in the MVC overview. It's not a heavy concept ... I think we could just place it as a section in the MVC overview.

**Comment by scottaddie** [comment]
I vote for making it an independent doc. Are we sure it has no effect outside of MVC? For example, is there anything in SignalR that would rely on it?

**Comment by BrennanConroy** [comment]
SignalR has no dependency on MVC so unless it affects some global app services it shouldn't affect SignalR.

**Comment by guardrex** [comment]
I'm ok with an independent subtopic under MVC. I'll wait for @Rick-Anderson to decide our direction.

**Comment by scottaddie** [comment]
@guardrex The `SetCompatibilityVersion` method does affect behavior in web APIs, and we decided to create a dedicated ToC node for web APIs. This is why I'm not completely sold on the idea of putting the topic under the MVC ToC node. How about adding a child ToC node under "Application startup"?

**Comment by guardrex** [comment]
Isn't it still an MVC concept tho (i.e., Web API runs on MVC infrastructure/middleware)? There's already coverage for it in the Web API topic at https://docs.microsoft.com/aspnet/core/web-api#annotate-class-with-apicontrollerattribute ... and that can stay as it is with an added link over to wherever this content appears.

**Comment by scottaddie** [comment]
@guardrex It is technically MVC, yes. Thinking on it some more, I guess the MVC ToC node does make the most sense.
