### ISSUE TITLE
It is hard to understand where has the "AccountController" in previous version has gone to ,and what replaces it.

### ISSUE THREAD

**Issue by tshaiman** [aspnet/Docs#8179]
It is hard to understand where has the "AccountController" in previous version has gone to ,and what replaces it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See The [2.1  Migration doc/Changes to authentication code](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-authentication-code)

**Comment by tshaiman** [comment]
Thanks a lot !

also : How come that for Asp.NET WebAPI projects you can use Individual Authentication using local storage and the template "forces" you to use Active Directory B2C ?

**Comment by Rick-Anderson** [comment]
> How come that for Asp.NET WebAPI projects you can use Individual Authentication using local storage and the template "forces" you to use Active Directory B2C ?

@blowdart  Can you answer? that's probably worth documenting.  cc/ @CamSoper

**Comment by blowdart** [comment]
Bug - you shouldn't be scaffolding identity into an API project :)

**Comment by tshaiman** [comment]
Sorry, I gave wrong description.

How come that for MVC project you can use Identity with local storage 
And for WebApi you must use AD ?
What do you mean “bug”? 
We have been using Identity in WebAPI for years , there is even a pluralsight course on this topic ( approx 2015)

**Comment by blowdart** [comment]
Because WebApi shouldn't be authenticated with cookies, it should be with JWT. When we moved to Core the JWT service went away. It's planned to come back in some form soon.
