### ISSUE TITLE
Supported versions of full .NET FW for SignalR Core

### ISSUE THREAD

**Issue by rjmille2** [aspnet/Docs#8182]
https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1#how-to-identify-the-signalr-version

I assume the versions are minimum versions.  I would like to verify that .NET FW 4.7.x is also supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f4bdfd-dfac-d6ae-4bd9-57439d300a5d
* Version Independent ID: 1f37f1ba-3e43-e726-f231-52acc6d26516
* Content: [Differences between SignalR and ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/version-differences?view=aspnetcore-2.1#how-to-identify-the-signalr-version)
* Content Source: [aspnetcore/signalr/version-differences.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/version-differences.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@BrennanConroy Shouldn't the doc should say ".NET Framework 4.6.1 or later"?

**Comment by BrennanConroy** [comment]
:+1: more clarity is always better
