### ISSUE TITLE
Document ASP.NET config builders

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#8184]
We should move the content in https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/master/README.md into the official ASP.NET docs.

**Comment by guardrex** [comment]
@danroth27 What's your priority for this ....... now, soon-ish, later-ish, or *when the cows come home*. :smile:

**Comment by danroth27** [comment]
P1 sounds right. Could we get this done by the end of Sept?

**Comment by guardrex** [comment]
@danroth27 *The word is given. Warp speed.* - Admiral James T. Kirk, *Star Trek II: The Wrath of Khan*, 1982

**Comment by guardrex** [comment]
@Rick-Anderson There's no *Fundamentals*/*Configuration* corollary in the aspnet docs. Configuration subject matter is sprinkled around in topics and dedicated configuration subject matter appears in *Older Versions* content. Where should a config topic on this subject be placed in the aspnet TOC?
