### ISSUE TITLE
Expand roles security documentation to include samples for creating & assigning roles 

### ISSUE THREAD

**Issue by AlexChesser** [aspnet/Docs#820]
Per a discussion here: https://docs.asp.net/en/latest/security/authorization/roles.html I'd like to see that we add documentation for how to create roles and how to assign roles to a user.

Fortunately Víťa Tauer  has done the research here http://stackoverflow.com/a/34381864/398055
SO the only steps left to take are formatting and writing it up into a commit for the Docs.

Per the contribution process, the article I would like to write is an expansion of the https://docs.asp.net/en/latest/security/authorization/roles.html article to add two new headings

### Assigning roles to users

These would use the samples as provided in Víťa Tauer's sample code. While combining any additional suggestions from the experts that crop up in this posted issue.

**Comment by GuardRex** [comment]
:+1: ... perhaps this is a bit of a premature suggestion given the current state of flux in ADAL/AAD/AB2C, but it would be nice to add a passing nod here (a paragraph) with the best source of info for getting the roles set out of AAD (and/or AB2C) using ADAL. That's a sample that I would think @dstrokis will probably put up at some point down the road, but it would be nice, since we're talking "how to create roles and how to assign roles to a user" here, that a mention and a link or two be part of this expansion to point folks in the right direction.

**Comment by AlexChesser** [comment]
Yeah - I'm not sure the code supplied is exactly right in all situations. I've been trying to port it into my own code and I'm fighting to get it right. Definitely need either expert input to make it work or quite a bit more time to figure out the details.

**Comment by GuardRex** [comment]
I'd like to point you to my hack code and see what @dstrokis latest bits
looks like in the event they let u expand this section. I'll be back in the
office in a few hours and ping u back.

**Comment by yossarianeq** [comment]
@GuardRex, do you expect API to change significantly? We decided for investing time into ASP.NET 5 because it entered RC phase, believing that the API changes will be just minor.

**Comment by GuardRex** [comment]
Not so much but B2C still lacked the ability to get bearer tokens for other
services ... e.g. Graph API, Azure Key Vault, etc. Getting the claims from
ADAL into app ClaimsPrincipal claims was a bit rough. The logic for issuing
challenges to AAD was a bit rough (but I think that part was addressed
recently). It was (couple of months ago) just generally rough around the
edges, and that's prob expected.

**Comment by GuardRex** [comment]
@AlexChesser Good, I left that old sample online. If you check https://github.com/GuardRex/AD-Sample/blob/master/src/ADSample/Startup.cs ... you'll see a mess in there for the `AuthorizationCodeReceived` notification. That creates claims based on a Graph API hit for the user's group membership(s) to establish role claims.

It's kind'a nasty the way I did it, but it works. What I'd like to see in the docs even if just a passing mention is the best practices way to create roles claims (even better ... policies for role claims) for vanilla AAD and AB2C scenarios. If you get the green light to go forward with an expansion for this section on roles claims, then at least touching on (if not actually showing how it could be done with code samples) with AAD and AB2C would be very helpful ... and cross-link .NET 5 to Azure Identity services.

@yossarianeq Identity has experienced major changes over the last few years, but I remain hopeful that it (the code) will stabilize now. I hope API changes are minor, and I think they probably will be. Jumping in now will be much better for you than jumping in even just three months ago. Keep an eye on this cat ... https://github.com/dstrockis ... his samples rock! He's keeping them updated as best he can (note to MS ... give Danny a team of his own!).

**Comment by blowdart** [comment]
The documentation you want to merge into is for authorization NOT authentication.

There are two separate subjects, and how you assign roles depends on the authentication method, be it ASP.NET identity, Active Directory or any other myriad of things you can authenticate with. 

So, the authorization documentation is not the right place for this, especially as it's limited to sites using ASP.NET identity. You might suggest that the identity documentation includes this, but it's not an authZ concern.

**Comment by GuardRex** [comment]
@AlexChesser I don't think the title or overall suggestion is off, just the link perhaps. I guess referring to https://docs.asp.net/en/latest/security/authentication/index.html is better. Either way, I think this is a good suggestion ... even if I do have "bad" and "dangerous" ideas from time-to-time. :smile:

Side note: More time is devoted to Facebook, Twilio, etc. than Azure services. If the marketing folks would take a break from renaming things over and over ... and over ... and take a look at how Azure is being integrated into the docs, they might have said something already. The resistance down here in Orange County to Azure is legendary. Every little bit helps (me at least) get Azure picked up more by companies.

**Comment by blowdart** [comment]
Also note the ADAL pieces are from another team, we have no control over their documentation.

**Comment by AlexChesser** [comment]
@blowdart - I'm not sure I understand completely.  I may be talking about a much narrower scope of documentation than you and @GuardRex are talking about. The talk of ADAL, AAD, and AB2C are all over my head at the moment. I'm even struggling with what they stand for. (Active Directory Application Library?)

Specifically the authorization page discusses in detail the way to decorate controllers with role-based authentication schemes (for example)

```
[Authorize(Roles = "Administrator, PowerUser")]
public class ControlPanelController : Controller
```

I was unable to find any documentation around how to ensure an application has roles persisted. Or users have roles assigned. For that, it appears we should document the use of `RoleManager<T>` to create roles as well as the `UserManager<T>` to assign roles to the user.

Limiting a controller to use by `Administrator, PowerUser` user types won't do any good if we can't add those roles to individuals, and we can't add those roles if they've not been added to the system yet.

Looking at the table produced, it isn't as simple as inserting a string in a table

```
SELECT [Id]
      ,[ConcurrencyStamp] -- what is this? why is it here? how would I make one from scratch?
      ,[Name]
      ,[NormalizedName] -- what are the parameters of a Normalized name? uppercase & no spaces? uppercase only?
  FROM [AspnetIdentitySample].[dbo].[AspNetRoles]
```

Sounds like the scope of what you're referring to is for  obtaining roles via Active Directory something external to the core application logic?

**Comment by blowdart** [comment]
How roles are persisted is a function of authentication. It is not part of authorization.

So documenting it in authorization is impossible, because authorization doesn't *care* about how you authenticated, or how you add roles or persist them.

RoleManager<T> only works if you are using ASP.NET identity. It does not work with AD. So any mention of it in Authorization is misleading, and potentially very wrong. It is external to authorization logic.

Hence it's not suitable for documenting in authorization and should, instead be in the authentication documentation for whatever authentication source you are using.

**Comment by AlexChesser** [comment]
So this issue should maybe be on the https://github.com/aspnet/Identity project and not under documentation?

**Comment by blowdart** [comment]
Well it depends. If that's what your using for authentication then yes, probably. But it's certainly **not** a topic for documentation under authorization.

**Comment by AlexChesser** [comment]
OK -  I'll admit I'm still unclear on the concepts here but I guess we can close this one.
