### ISSUE TITLE
Troubleshooting 502/503 errors link is broken

### ISSUE THREAD

**Issue by phatcher** [aspnet/Docs#8200]
On the [troublshooting guide](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/troubleshoot.md) the link to 
https://github.com/aspnet/Docs/blob/master/app-service/app-service-web-troubleshoot-http-502-http-503 is broken

**Comment by guardrex** [comment]
Thanks @phatcher ... I'll patch that up right now.

**Comment by guardrex** [comment]
It was missing a URL segment. The update is in, and it should go live by the end of the day. Thanks again for letting us know.

**Comment by phatcher** [comment]
@guardrex Am trying to debug why an Asp.Net core app suddenly started returning 503's so it was in my interest ;-)
