### ISSUE TITLE
WebApplicationFactory and Test Collections

### ISSUE THREAD

**Issue by tulde23** [aspnet/Docs#8204]
Integration Testing Documentation states that all tests should implement IClassFixture<TEntryPoint>.  Does this mean that the TestServer will be instantiated per test class?  What is the recommended approach for sharing context across test classes?  I tried using an ITestCollection but xunit has strict requirements on your constructor parameters preventing me from injecting a WebApplicationFactory instance.

In netcore2, I created a common fixture shared using a test collection.  Within my fixture I bootstrap the WebHost and create my TestServer.  It still works, but I wanted to utilize the new abstractions in 2.1

Thanks

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
