### ISSUE TITLE
Are Head, Options and Patch part of the action convention for HTTP methods?

### ISSUE THREAD

**Issue by marcosdimitrio** [aspnet/Docs#8208]
The "[Routing in WebApi page](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/routing-in-aspnet-web-api)" ([source](https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/web-api-routing-and-actions/routing-in-aspnet-web-api.md)) says:

> For example, with a GET request, Web API looks for an action that starts with "Get...", such as "GetContact" or "GetAllContacts". This convention applies only to GET, POST, PUT, and DELETE methods.

But the next page, "[Routing and Action Selection in ASP.NET Web API](https://docs.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/routing-and-action-selection)" ([source](https://github.com/aspnet/Docs/blob/master/aspnet/web-api/overview/web-api-routing-and-actions/routing-and-action-selection.md)) says:

> Otherwise, if the name of the controller method starts with "Get", "Post", "Put", "Delete", "Head", "Options", or "Patch", then by convention the action supports that HTTP method.

Which one is correct?

**Comment by rynowak** [comment]
What does WebAPI mean in this context? IIRC it's a pre-asp.net-core framework.

**Comment by guardrex** [comment]
Yes ... both topics are in the aspnet doc set. I suspect that we can update one or the other to make what they say about matching verbs the same. @MikeWasson, do u recall if the second topic listed is correct? ... HEAD, OPTIONS, and PATCH also work by convention?

**Comment by Sebazzz** [comment]
Based on [this](https://github.com/aspnet/AspNetWebStack/blob/749384689e027a2fcd29eb79a9137b94cea611a8/src/System.Web.Http/Controllers/ApiControllerActionSelector.cs#L102-L109) all (even unknown) HTTP methods are supported, but only GET/PUT/POST are cached.
