### ISSUE TITLE
Select the following files to override:

### ISSUE THREAD

**Issue by paul000** [aspnet/Docs#8210]
When starting the web page this is stated :
Select the following files to override: 
Account/Register
Account/Manage/Index

But then this is discussed :
Properties decorated with the PersonalData attribute are:
Deleted when the Areas/Identity/Pages/Account/Manage/DeletePersonalData.cshtml Razor Page calls UserManager.Delete.
Included in the downloaded data by the Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml Razor Page.

Should we have selected DeletePersonalData and DownloadPersonalData as files to override also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@paul000  those pages are **not** modified so you don't need to generate them. I suppose it might be good to generate them so you can view them. I think I'll add that to the next update. Thanks for asking this question.
