### ISSUE TITLE
Provide a source code please

### ISSUE THREAD

**Issue by mchudinov** [aspnet/Docs#8216]
Provide a source code please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59d6d442-8d46-3f9e-e75a-ad9d900fc117
* Version Independent ID: d07c4058-452f-cdac-c59d-8f09e70a43f3
* Content: [Authenticate users with WS-Federation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/ws-federation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/ws-federation.md)
* Product: **aspnet-core**
* GitHub Login: @chlowell
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@mchudinov what source do you want? The sample contains all the source required.
