### ISSUE TITLE
Invalid object name 'AspNetRoles' after migrating from 2.0 to 2.1

### ISSUE THREAD

**Issue by seanronan** [aspnet/Docs#8218]
A working 2.0 with ef + identity project has been upgraded to 2.1 and the Identity UI and controller left as is. Project builds fine, but when run and any identity action used the exception "Invalid object name 'AspNetRoles'" is triggered by
var result = await _signInManager.PasswordSignInAsync(userName, model.Password, model.RememberMe, lockoutOnFailure: true);
What am I missing? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-gb/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
I would following the instructions in  Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-gb/aspnet/core/migration/20_21?view=aspnetcore-2.1)

A quick way to get an overview of the changes in 2.1 is to:

* Create an ASP.NET Core 2.0 web app named WebApp1.
* Commit the WebApp1 in a source control system.
* Delete WebApp1 and create an ASP.NET Core 2.1 web app named WebApp1 in the same place.
* Review the changes in the 2.1 version.

And see if you can reproduce the problem. If you can't, figure out how that differs from your code.

**Comment by Rick-Anderson** [comment]
@seanronan  is this what you did:

Use the Identity UI 2.0 code with no changes. Using Identity UI 2.0 code is fully supported. This is a good approach when significant changes have been made to the generated Identity code.

**Comment by seanronan** [comment]
Yes. The only change I made in Identity 2.0 was to manually add the Claims table as per the docs. I will try the the source control diff. Was hoping this was an exception seen before.

**Comment by Rick-Anderson** [comment]
> The only change I made in Identity 2.0 was to manually add the Claims table as per the docs.

Where does it stay that?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
