### ISSUE TITLE
Changes on the Facebook side of this doc, no App Secret on the developer page

### ISSUE THREAD

**Issue by jeffmu** [aspnet/Docs#8220]
I used this guide/doc to try and create a test web app, Facebook has changed the Dashboard for the project. It no longer has the appSecret on the page anymore.

https://developers.facebook.com/docs/facebook-login/web

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jeffmu  thanks for bringing this to our attention. Can you review my fix in #8222
