### ISSUE TITLE
Add Course assignments to the instructor Edit and Create pages

### ISSUE THREAD

**Issue by apalix** [aspnet/Docs#8224]
I have a 27" screen and with a 1/2 - 2/3 screen size page, and everything looks good. The instructor fields are centered with proportionate padding (about 1") on either side and the Course checkboxes and courses are in a 3 column table (albeit too narrow to fit the courses) . As soon as I increase the page width past 2/3 of the screen, the Instructor fields shrink to about 1/3 their original size, and are left justified. The checkboxes and courses become stacked with the exception of the "1045 Calculus cell", which remains ok probably due to its size.

At 2/3 screen page width: X=checkbox.
&emsp;X 1045 Calculus&emsp;&emsp;&emsp;&emsp;X 1050 Chemistry&emsp;&ensp;X 2021 Composition
&emsp;X 2042 Literature&emsp;&emsp;&emsp;&ensp;X 3141 TrigonometryX 4022 Microeconomics
&emsp;X 4041  Macroeconomics

At greater than 2/3 screen page width it looks like the following:
&emsp;X 1045 Calculus&emsp;X 1050&emsp;&emsp;&emsp;&emsp;X 2021 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Chemistry&emsp;&emsp;&ensp;Composition 
&emsp;X 2042 Literature &nbsp;X 3141&emsp;&emsp;&emsp;&emsp;X 4022 
&emsp;Literature&emsp;&emsp;&emsp;&emsp;Trigonometry&emsp;Microeconomics
&emsp;X 4041
&emsp;Macroeconomics

Why is this happening? I've tried various bootstrap col-md settings and I cannot vary the width of the columns  until I increase 2/3 screen size and then everything goes haywire. Other than this, the app works fine.
I'm new to bootstrap code and razor pages and would appreciate some help.
Thanks in advance

**Comment by Rick-Anderson** [comment]
@apalix  the tutorial is about EF and ASP.NET Core Razor Pages. You might try posting this on StackOverflow.

**Comment by apalix** [comment]
Thanks. Will do.
