### ISSUE TITLE
Phone attribute specific regex

### ISSUE THREAD

**Issue by Dc9894** [aspnet/Docs#8227]
Hi, so I've spend some time searching on How does exactly the phone attribute validates a phone number? or, What Regex pattern does it use behind the scenes to validate a field?. Should this information be here, or in the API browser site? I can't find it.

Could you point me to where this info is, or if it should be included in this article?

Thank you very much for the help in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#validation-attributes)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Dc9894  I would search for "Regex phone number". RegEx is beyond the scope of this tutorial.

**Comment by tdykstra** [comment]
@Dc9894 

> How does exactly the phone attribute validate a phone number? 

The source code for the attribute is here:  https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/PhoneAttribute.cs
You'll see here that the .NET Core version of the attribute does not use a regex. (Note that this link goes to .NET Core source code; the source code referenced in https://github.com/dotnet/docs/issues/7213 is for .NET Framework.  For future reference, note that you can also find source code for .NET Core at https://source.dot.net/ )

> Should this information be here, or in the API browser site?

An explanation of the validation rules -- not necessarily implementation details such as regex patterns -- should be in the API reference for this class. It doesn't fit here in an overview article.

I'm closing this issue as I believe this answers your question; if not, please let me know and we can reopen.
