### ISSUE TITLE
Identity Scaffolding creates empty Services folder

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8233]
https://github.com/aspnet/Scaffolding/issues/857

cc @isaac2004
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by isaac2004** [comment]
@Rick-Anderson I planned on adding a note to this doc basically saying that Services are not generated by default when scaffolding, and if email/sms functionality is needed, they will need to be added and registered manually. Sound Good?

**Comment by Rick-Anderson** [comment]
@isaac2004  AFAIK
Services are not generated ~by default~ when scaffolding. There is no option to generate services - they need to be added manually.

Sounds good.

**Comment by C-BERBER** [comment]
Hi, I manually copied a scaffold I created from another project, and strangely when I go to the Account management (_manageNav.cshtml and ManageNavPages) It goes thru the proper _layout in the proper directory, but it is rendering the MS version and I have tried to search my solution directory for various key words in the following section but they don't exist! where is this code coming from and how do I get it to use my base layout? TIA


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> - SCPI_Site</title>

    
        <link rel="stylesheet" href="/Identity/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="/Identity/css/site.css" />
    
    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">SCPI_Site</a>
            </div>
            <div class="navbar-collapse collapse">
                


    <form method="post" id="logoutForm" class="navbar-right" action="/Identity/Account/Logout?returnUrl=%2F%3Fpage%3D%252FIndex">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a title="Manage" href="/Identity/Account/Manage">Welcome Chris Berberich </a>


            </li>
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Logout</button>
            </li>
        </ul>
    <input name="__RequestVerificationToken" type="hidden" value="CfDJ8N4dU6zV7OlApAhbZ5op_eJTiinGF36iMdxWw5Gc7Ce3kQeX2-cj32T4cT5BCJBH_NIanLXWiQ7x6Kzu8W8cqRHqS5E_n6qYnVKTP4USBSJWHAGXeVn04RzgxWS_hUajZIUOAnmlpDJFcEO-3OJCLEFakne1JeRpU1AIesDFOx2T1GND50rgwohvZHsn5jQZ4g" /></form>
            </div>
        </div>
    </nav>
    <div class="container body-content">

**Comment by Rick-Anderson** [comment]
@C-BERBER  see https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class and 
https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-2.1?view=aspnetcore-2.1#identity-ui-library--scaffolding
and
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity
and 
https://docs.microsoft.com/en-us/aspnet/core/migration/20_21

**Comment by C-BERBER** [comment]
Thank Rick, However after reading those links I am still not seeing how HTML, not defined anywhere in my project is getting rendered in the page. I have traced the code in the debugger and honestly cannot understand where it would be pulling from. searching for any number of unique bits from below yields nothing, the code has to be coming from somewhere right?

this "navbar navbar-inverse navbar-fixed-top" is not anywhere in my project directory...

If you have anything else to read or something to key in on I would appreciate it, have a nice weekend

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> - SCPI_Site</title>

    
        <link rel="stylesheet" href="/Identity/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="/Identity/css/site.css" />
    
    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">SCPI_Site</a>
            </div>
            <div class="navbar-collapse collapse">
