### ISSUE TITLE
Deprecation MvcRazorCompileOnPublish 

### ISSUE THREAD

**Issue by DavidDeSloovere** [aspnet/Docs#8235]
Per this post https://github.com/aspnet/Announcements/issues/315 the MvcRazorCompileOnPublish option will be deprecated soon and removed in v3. Correct? Might be best to mention this here people don't start using this anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a83deb2-e035-bb66-be4f-68709bcad341
* Version Independent ID: 16438f35-f35d-c097-0903-ec17e83e051e
* Content: [Razor file compilation and precompilation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/view-compilation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-compilation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm please review

**Comment by pranavkm** [comment]
I guess adding a note to the *Important* section would help:

> The Razor SDK is effective only when no precompilation-specific properties are set in the project file. For instance, setting the .csproj file's MvcRazorCompileOnPublish property to true disables the Razor SDK. The precompilation tool will be removed in 3.0 and we recommend migrating to Razor Sdk.

**Comment by DavidDeSloovere** [comment]
@Rick-Anderson Great follow-up!
