### ISSUE TITLE
how can i see version to version document diff

### ISSUE THREAD

**Issue by mhamri** [aspnet/Docs#8236]
how can i know what has changed in the documentation since the last version? 

I checked the branches names and commits names. couldn't find any way to figure out version to version changes . for example, asp.net core 2.1 to 2.2 documentation had a lot of changes, but it's not visible atm. it's impossible on every release I go to all pages in the documentation to see what is deprecated and what is not or what is new. so I am looking for a way to get a version to version diff. unfortunately, current branching and tagging don't support this. 

I was thinking something like this should be possible with the power of git. I should be able to compare the commit or branch of different releases and get all the changes summary. so, I can update my knowledge only in those areas. in this way, I don't need to go through all the pages and read the whole documentation again and again on each new version release.

**Comment by guardrex** [comment]
> 2.1 to 2.2 documentation had a lot of changes

Release 2.2 isn't out yet and very little content for 2.2 has been produced (18 open; 1 closed): https://github.com/aspnet/Docs/issues?q=is%3Aopen+is%3Aissue+label%3A2.2 ... Did you mean 2.0 vs. 2.1? There's a migration guide for that set of changes: https://docs.microsoft.com/aspnet/core/migration/20_21

Version-to-version changes are covered by the [Migration topics](https://docs.microsoft.com/aspnet/core/migration/) and the [Release Notes](https://github.com/aspnet/Home/releases/).

With regard to the work we did on the repo, you could use our issue labels, but it might be a bit of a rough experience. For example, for the 2.1 closed issues ... https://github.com/aspnet/Docs/issues?q=is%3Aissue+label%3A2.1+is%3Aclosed

You're correct about the doc branches ... they don't coincide with engineering releases. We work on a rolling basis and have versioning capabilities for content. Therefore, we can work on any release at any time.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
