### ISSUE TITLE
The [Required] attribute for Instructor property in OfficeAssignment is not only unnecessary but also troublesome

### ISSUE THREAD

**Issue by Jinqiao** [aspnet/Docs#8242]
If we add a [Required] attribute for Instructor property in OfficeAssignment. Later in this series, part 7 update related data, we cannot Edit/Create Instructor, as the model will always be invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Jinqiao  that property should not be required.

**Comment by Jinqiao** [comment]
Yes, exactly. However, this sentence: "The [Required] attribute could be applied to the Instructor navigation property" makes me feel it is optional...

**Comment by Rick-Anderson** [comment]
@Jinqiao  why? that's not the `OfficeAssignment` property.
