### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ayinn** [aspnet/Docs#8243]
I have not been able to publish an aspnetcore 2.0 web app to my web hosting company site (DASP). I need to know if there is some reason the Microsoft.AspNetCore.Antiforgery assembly will not compile.
Also, can I use MVC if I upgrade to aspnetcore 2.1? thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.1&tabs=aspnetcore2x#common-errors)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ayinn  can you check with  your hosting company and see if they support ASP.NET Core 2.0?

**Comment by guardrex** [comment]
Closing as answered.
