### ISSUE TITLE
Use DataAnnotaations so Date field doesn't require time

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8250]
When testing where my STUDENT form was working, I see that I an FORCED to enter a TIME as well as a date. I presume that this is because there is no way to differentiate between the DATE datatypes/signatures when creating the model?....so when the DB is built, its defaulting to a date/time format.   Perhaps there is a way default the current date/time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed.
