### ISSUE TITLE
And this is a sample of.....

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8252]
Not only is this 800mb of GARBAGE.....containing corrupt files, but (if you are lucky enough to get all the contents) who knows how to use it? This appears to be a collection of random 'stuff'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c461e1d-5771-20f9-c9b3-ac4ee7661ee0
* Version Independent ID: e06d8e48-cee4-0c0c-39aa-97abe228c370
* Content: [ASP.NET Core tutorials](https://docs.microsoft.com/en-us/aspnet/core/tutorials/index?view=aspnetcore-2.1#how-to-download-a-sample)
* Content Source: [aspnetcore/tutorials/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
> Unzip the Docs-master.zip file.
> Use the URL in the sample link to help you navigate to the sample directory.

The docs engineering team is working on a formal solution to the problem of downloading individual samples. We don't have an ETA for it yet. Hopefully, it will be available soon.
