### ISSUE TITLE
View Model content

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8253]
This section is confusing to say the least.
1. The VM listing (ie StudentVM.CSHTM) appears to be no different to the originals (IE Student.CSHTML)….except that the word 'student' now contains two additional letters 'VM' appended to the end. So, for this tutorial, what exactly are you trying to show me here?
It would be REALLY helpful if you could show me the effects in a video.

2. Where am I supposed to put this code? 
Do I simply rename student.CSHTML to studentVM.CSHTML (and search/replace 'student') or am I supposed to create a new razor page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by lm28** [comment]
Ditto for the Edit pages section

**Comment by Rick-Anderson** [comment]
`StudentVM` doesn't contain `public string Secret { get; set; }`

**Comment by Rick-Anderson** [comment]
It's *StudentVM.cs*, not a cshtml file.
