### ISSUE TITLE
SignalR: Java client

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#8256]
See https://blogs.msdn.microsoft.com/webdev/2018/08/23/asp-net-core-2-2-0-preview1-signalr-java-client/ for more info.

**Comment by scottaddie** [comment]
@mikaelm12 Any interest in providing a draft of this doc?

**Comment by mikaelm12** [comment]
Sure. I can get started on this next week if that's okay?

**Comment by scottaddie** [comment]
@mikaelm12 That sounds great! Thank you for the help.
