### ISSUE TITLE
Where to start? I can't keep up!

### ISSUE THREAD

**Issue by FakeSaint41** [aspnet/Docs#8266]
I feel like I'm being strapped to a pickle in a blender trying to find the right starting point to learn ASP.net Core... As a beginner I'm terribly confused and don't see a clear way to logically progress through these resources.  This "Get started" category could be a bit more clear on how to get started, the suggested "Get started with Razor Pages" seems to assume prior knowledge about ASP.Net and contains a hurricane of cross-links 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per this doc
This document provides an introduction to Razor Pages. It's not a step by step tutorial. If you find some of the sections too advanced, see [Get started with Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1) . 

No need to click all the links in [Get started with Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1) unless you  need to dive deeper. Folks often do  that on the 2nd pass.

[Get started with Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1) assumes no prior knowledge.
