### ISSUE TITLE
Typo on an example

### ISSUE THREAD

**Issue by sangheestyle** [aspnet/Docs#8268]
I think `await _myDependency.WriteMessage` should be `await _dependency.WriteMessage` at the following page:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1

Also, could you check indentation of the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sangheestyle ... Thanks for commenting on the topic.

> check indentation of the example

That one is a known issue. The docs engineers are working on it. See: https://github.com/aspnet/Docs/issues/6052

> I think await _myDependency.WriteMessage should be await _dependency.WriteMessage at the following page

*Yes, indeed!* ... Thanks for letting us know. I'll patch that up right now.
