### ISSUE TITLE
Request for DB first approach

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#827]
Several customers have requested a DataBase first - not  CodeFirst.
see http://docs.asp.net/projects/mvc/en/latest/getting-started/first-mvc-app/working-with-sql.html#comment-2423386435

**Comment by shirhatti** [comment]
@rowanmiller Do we have any content in this space? Should this reside in the EF docs or the ASP.NET docs?

**Comment by rowanmiller** [comment]
http://docs.efproject.net/en/latest/getting-started/aspnet5/existing-db.html

**Comment by danroth27** [comment]
This is documented in the EF docs.
