### ISSUE TITLE
UseSignalR

### ISSUE THREAD

**Issue by xeo545x39** [aspnet/Docs#8277]
Statement `app.UseSignalR` does not work because this extension method is not found. I found some info here https://github.com/aspnet/SignalR/issues/491#issuecomment-413570259  that I need add `Microsoft.AspNetCore.SignalR.Http` but I don't understand why it's not present in this documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Tutorial: Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by xeo545x39** [comment]
I just installed SignalR.Core without SignalR full dependency

**Comment by davidfowl** [comment]
Are you on .NET Framwork?

**Comment by kiske1** [comment]
I'm on .net Framework 4.6.2, and have the same problem. 
Is there any solution to the problem?
