### ISSUE TITLE
Course assignment at Student Create time

### ISSUE THREAD

**Issue by edikaufmann** [aspnet/Docs#8280]
After familiarizing myself I miss a 'Course assignment at Student Create time' ...
... might be I just have a blackout!

Right now I do this manually by updating the 'enrollemt'_DB manually (or by updating the 'DbInitializer.cs' and run 'nuget' commands!)

I see this relation via 'Instructors' ... 'Students enrolled in selected courses'

Question:
Are there any plans to provide an enrollmntDB update to reflect the **Course assignment at Student Create time**? 

OR, again, what I'm missing here?!
Thanks for your time, ed

#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@edikaufmann No plans to change the schema.
