### ISSUE TITLE
'IActionResult'  and  'ActionResult'  returned

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8284]
Should consistently return `ActionResult`
See #8281

`dotnet new webapi` uses `ActionResult`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rutix** [comment]
@Rick-Anderson I am trying to understand the reason to prefer over IActionResult over ActionResult<T> could you explain this a little better?

**Comment by Rick-Anderson** [comment]
It usually doesn't matter. I opened this issues because we're inconsistent. `IActionResult` is an interface so it's more flexible. See https://forums.asp.net/t/2071936.aspx

**Comment by Rutix** [comment]
I do think the `ActionResult<T>` used in the documentation is more readable than IActionResult since you can see the return type in a first glance though. It makes the sample code easier to read. This is mostly my opinion though.

**Comment by bennyseems** [comment]
My understanding is that it's usually preferable to return an interface if possible, especially when developing, say, an API that will be used by others. One reason for this is that it allows for the developer to change the implementation of the interface without impacting callers of the method (assuming the interface itself doesn't change).

In the example above, the Create method, for example, can return the IActionResult interface, but some other methods (like GetById) need to return a class (ActionResult<TValue>), because they are passing a (generic) type argument, and there is no IActionResult<TValue>.

**Comment by bennyseems** [comment]
My comment above had carats stripped out. They should be in the last paragraph to denote the type being passed.

**Comment by scottaddie** [comment]
@bennyseems I fixed the comment for you. For future reference, surround code like that in backticks.

**Comment by Rick-Anderson** [comment]
@Rutix @bennyseems  good point, I updated the goal of this issue to consistently use `ActionResult`

**Comment by sebwills** [comment]
@Rick-Anderson The text at the start of the Return Values section may need a tweak - it currently says that the `GetAll` method returns a collection, but "in contrast, the `GetById` method returns the `ActionResult<T>` type". In fact they both have an `ActionResult<T>` return type (although `GetAll` relies on the implicit cast to `ActionResult<T>`).

**Comment by jeremybowden73** [comment]
@sebwills  @Rick-Anderson >   In fact they both have an `ActionResult<T>` return type (although `GetAll` relies on the implicit cast to `ActionResult<T>`).

Could you please explain why `GetAll` doesn't return a collection of `TodoItem`s ? It seems logical to say that it does.

**Comment by Rutix** [comment]
@sebwills Isn't `GetById` technically also an implicit cast? Since `NotFound()` is of type `ActionResult` and so is implicited casted to `ActionResult<T>`.
