### ISSUE TITLE
User not in Sample

### ISSUE THREAD

**Issue by Coscotex** [aspnet/Docs#8285]
This is more of an EMPHASIS on the other open feedback by @Alienroid .

Can we please have a working sample where you actually used "connection.User?.FindFirst(ClaimTypes.Email)?.Value;"

Since ClaimTypes.Email is more unique than just the User's Name, it would be really helpful to see a working example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d77892-d376-2f23-2634-f5d34d962a1e
* Version Independent ID: 92ed6330-b49f-1620-6beb-8556a78ac7da
* Content: [Manage users and groups in SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/groups?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/groups.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/groups.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Coscotex - Thanks for the additional comments on this topic!  I copied your request to the other issue and am closing this one.
