### ISSUE TITLE
Typo in Pages/Courses/Index.cshtml

### ISSUE THREAD

**Issue by AlbertoPa** [aspnet/Docs#8286]
In Pages/Courses/Index.cshtml 

&lt;a asp-page="TestCreate"&gt;Create New&lt;/a&gt;

 should be 

&lt;a asp-page="Create"&gt;Create New&lt;/a&gt;

or the "Create new" link in the "Courses" page does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@AlbertoPa thanks. I'll get this fixed.
