### ISSUE TITLE
Composite Primary Key Error

### ISSUE THREAD

**Issue by robinwilson16** [aspnet/Docs#8288]
I get an error when trying to run a migration as the CourseAssignments entity has a composite key:
```
The entity type 'CourseAssignment' requires a primary key to be defined.
```
Then if I add [Key] before the fields I get this:
```
Entity type 'CourseAssignment' has composite primary key defined with data annotations. To set composite primary key, use fluent API.
```

The workaround that worked for me was to do as it said and add it using the fluent API:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<CourseAssignment>()
                .HasKey(c => new { c.InstructorID, c.CourseID});
        }
```

After this I was able to continue.

I did adapt some of the classes and objects so not sure if this was something I did but Googling does seem to suggest that the fluent API must be used.
It would be better if you could just add [Key] before the key fields though or if the system automatically realised it was a composite key from the data model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 634dfb2c-2626-9ec5-35fe-2bd2f27c5e23
* Version Independent ID: 7a77b058-f005-8d68-ae46-e487c597f18e
* Content: [Razor Pages with EF Core in ASP.NET Core - Data Model - 5 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/complex-data-model?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
>  I did adapt some of the classes and objects so not sure if this was something I did

Yes, the code as presented can infer key. Glad you were able to solve it with the suggested fluent API.
