### ISSUE TITLE
Display custom User fields

### ISSUE THREAD

**Issue by hmihail** [aspnet/Docs#8289]
I followed the instructions and added some custom fields to the User class, like `FirstName` and `LastName`. They are saved in the database fine. But how can I display that info in a page, like `Hello, <FirstName>!`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hmihail  you'll probably get a quicker response if you ask that question on a forum.
