### ISSUE TITLE
/fundamentals/configuration.rst Configuration

### ISSUE THREAD

**Issue by aboichev** [aspnet/Docs#829]
https://docs.asp.net/en/latest/fundamentals/configuration.html
- [x] Needs update for API changes
- [x] Per John Russell/DISQUS You are correct that DI is not setup until after ConfigureServices is invoked and the configuration system is not DI aware.
- [x] Show how to read JSON or XML or INI configuration file. See [cust comment](https://docs.asp.net/en/latest/fundamentals/configuration.html#comment-2478366392)
- [x]  move a screenshot showing a result view (see text below)
- [x]  See also #867 "Show how to bind options to a specific config section" 
- [x]  #823
- [x] #1604 
- [x] UE Edit 
- [x] DISQUS
- [x] consider updating the parent options to also have a MySubOptions property, to demonstrate that nested complex options bind recursively. (per HaoK)

I think it would be better to move a screenshot showing a result view displaying the options after the paragraph, which talks about configuring options in ConfigureServices method. Right now it gives a false idea that this step is optional.

Also, it would help a lot to include example of the appsetting.config which looks something like this:

```
{
  "Logging": {
    ...
  },
  "Option1": "value_from_file",
  "Option2 ": 2
}
```

which shows that Options property has to be on the root level of the document, which was not very clear to me. I would also add an example about using 

```
services.Configure<MyOptions>(Configuration.GetSection("MyOptions"));
```

if we want to bring the config settings to this form: 

```
{
  "Logging": {
    ...
  },
  "MyOptions": {
      "Option1": "value_from_file",
      "Option2 ": 2
  }
}
```

.. which seems to be a better choic

**Comment by Rick-Anderson** [comment]
This doc is out of date and has API changes.
See also https://github.com/aspnet/Docs/issues/867 "Show how to bind options to a specific config section" and https://github.com/aspnet/Docs/issues/823

**Comment by danroth27** [comment]
@ardalis Can you incorporate this feedback as part of your RC2 update?

**Comment by ardalis** [comment]
@danroth27 will do

**Comment by colin-young** [comment]
Better examples of what various configuration files would look like should be provided. In particular, an example of an XML configuration file would be helpful. Is it the same as the traditional `app.config`/`web.config` files? I have been unable to find anything addressing that. I understand we're all excited about JSON files, but sometimes your customers have built up a level of comfort or expertise with `.config` files.

**Comment by msaleh6** [comment]
I need to save updated values back to the store (provider/source) from which they were loaded. Can you add that support or is there a way to extend the framework to support saving updated values?

**Comment by Rick-Anderson** [comment]
I don't think their are any plans to write/update the config store. You could fetch your config from a DB  and update that.

**Comment by danroth27** [comment]
Please do provide feedback/suggestions in the [Configuration](https://github.com/aspnet/configuration) repo.
