### ISSUE TITLE
Initialize database - instance the context

### ISSUE THREAD

**Issue by caedunogueira** [aspnet/Docs#8301]
In Initialize method from SeedData class, is there a difference if I instance the context using var context = serviceProvider.GetRequiredService&lt;RazorPagesMoviesContext&gt;(); instead of var context = new RazorPagesMoviesContext(serviceProvider.GetRequiredService&lt;DbContextOptions&lt;RazorPagesMoviesContext&gt;&gt;()) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with SQL Server LocalDB and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Try it and let me know.

**Comment by caedunogueira** [comment]
It's the same behavior. We can also implement using the same context instance, something like this:

Program.cs

        public static void Main(string[] args)
        {
            var host = CreateWebHostBuilder(args).Build();

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;

                try
                {
                    using (var context = services.GetRequiredService<RazorPagesMoviesContext>())
                    {
                        context.Database.Migrate();
                        SeedData.Initialize(context);
                    }
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, "An error occurred seeding the DB.");
                }
            }

            host.Run();
        }

SeedData.cs

        public static void Initialize(RazorPagesMoviesContext context)
        {
            if (context.Movie.Any())
            {
                return;
            }

            context.Movie.AddRange(
                new Movie
                {
                    Title = "When Harry Met Sally",
                    ReleasedDate = DateTime.Parse("1989-2-12"),
                    Genre = "Romantic Comedy",
                    Price = 7.99M
                },
                new Movie
                {
                    Title = "Ghostbusters",
                    ReleasedDate = DateTime.Parse("1984-3-13"),
                    Genre = "Comedy",
                    Price = 8.99M
                },
                new Movie
                {
                    Title = "Ghostbusters 2",
                    ReleasedDate = DateTime.Parse("1986-2-23"),
                    Genre = "Comedy",
                    Price = 9.99M
                },
                new Movie
                {
                    Title = "Rio Bravo",
                    ReleasedDate = DateTime.Parse("1959-4-15"),
                    Genre = "Western",
                    Price = 3.99M
                }
            );
            context.SaveChanges();
        }

It's an alternative way but I don't feel it would be a good one because if, for any reasons, someone would like to use SeedData.Initialize method in another place, it would be use without the using keyword for the context. Just an idea!
