### ISSUE TITLE
DpapiNGXmlEncryptor constructor does not have overloaded constructor with third parameter with type IServiceProvider

### ISSUE THREAD

**Issue by palicpiotr** [aspnet/Docs#8302]
Hello, good article.  (https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/limited-lifetime-payloads?view=aspnetcore-2.1)

But i found slight discrepancy with the documentation in part of IKeyEscrowSink. 
In constructor of class KeyEscrowSink you initialize _escrowEncryptor private field with DpapiNGXmlEncryptor where the third parameter is type of IServiceProvider (services), but actualyy third parameter is type of ILoggerFactory. Is this mistake or in older versions of ASP.NET Core were modified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f34a00d6-1197-1a89-6fb6-9adcc4643850
* Version Independent ID: 46f5eaf3-930a-7442-ad4f-4615c38d03b8
* Content: [Key management extensibility in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/extensibility/key-management?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/data-protection/extensibility/key-management.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/extensibility/key-management.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@palicpiotr  good catch. Thanks for bringing this to our attention.
[DpapiNGXmlEncryptor Constructor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.xmlencryption.dpapingxmlencryptor.-ctor?view=aspnetcore-2.1#Microsoft_AspNetCore_DataProtection_XmlEncryption_DpapiNGXmlEncryptor__ctor_System_String_Microsoft_AspNetCore_DataProtection_XmlEncryption_DpapiNGProtectionDescriptorFlags_Microsoft_Extensions_Logging_ILoggerFactory_) shows you're right.

My guess is this doc was written in an early beta and the API has changed. 

We'll get this fixed. Bonus points if you want to make a PR to fix this.

**Comment by guardrex** [comment]
```csharp
// using Microsoft.Extensions.Logging;

public MyKeyEscrowSink(IServiceProvider services, ILoggerFactory loggerFactory)
{
    // Assuming I'm on a machine that's a member of the CONTOSO
    // domain, I can use the Domain Admins SID to generate an
    // encrypted payload that only they can read. Sample SID from
    // https://technet.microsoft.com/library/cc778824(v=ws.10).aspx.
    _escrowEncryptor = new DpapiNGXmlEncryptor(
        "SID=S-1-5-21-1004336348-1177238915-682003330-512",
        DpapiNGProtectionDescriptorFlags.None,
        loggerFactory);
}
```
