### ISSUE TITLE
Helper support in asp.net core 

### ISSUE THREAD

**Issue by deap82** [aspnet/Docs#8303]
Are there any plans on adding support for the @helper directive in asp.net core? The ability to reuse small html snippets within a file is really useful sometimes. Especially in more sofisticated editor templates. Using the @function to add methods that returns a string works (as long as one don't want to consume a tag helper within that html) but is harder to maintain. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#directives)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
It looks like something similar is being considered. See https://github.com/aspnet/Razor/issues/1898 and https://github.com/aspnet/Razor/issues/281
