### ISSUE TITLE
How does a key become "Revoked"

### ISSUE THREAD

**Issue by kalimist123** [aspnet/Docs#8306]
"Created, active, and expired keys may all be used to unprotect incoming payloads. Revoked keys by default may not be used to unprotect payloads"  Can you explain the difference between "expired" and "revoked" keys?  what can happen to an "expired" key to tranform it's status to "revoked"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275ff6a6-a3f2-fb2b-6fda-4981abf46a7d
* Version Independent ID: e7547577-5c8a-ce9f-d990-b8a4cbaa5a50
* Content: [Key management in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/key-management?view=aspnetcore-2.1#key-expiration-and-rolling)
* Content Source: [aspnetcore/security/data-protection/implementation/key-management.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/implementation/key-management.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @kalimist123 ...

>  Can you explain the difference between "expired" and "revoked" keys?

They're explained at the top of the topic:

* Expired - the key has run its natural lifetime and should no longer be used for new Protect operations.
* Revoked - the key is compromised and must not be used for new Protect operations.

> what can happen to an "expired" key to tranform it's status to "revoked"?

You manually revoke it (AFAIK the framework doesn't revoke keys all by itself), either via [IKeyManager.RevokeAllKeys](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.dataprotection.keymanagement.ikeymanager.revokeallkeys) or [IKeyManager.RevokeKey](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.dataprotection.keymanagement.ikeymanager.revokekey). You would do this if you knew that that the key (or the entire key ring) had become compromised (e.g., a data breach occurs).

**Comment by kalimist123** [comment]
Thank you. I wanted to check if the framework revokes keys by itself as I am considering using keys for long-term data encryption. I know that is not the intended usage.
