### ISSUE TITLE
The Code Cannot be downloaded

### ISSUE THREAD

**Issue by Powerhelmsman** [aspnet/Docs#8307]
This issue was created by @ZhouHelen from https://github.com/MicrosoftDocs/feedback/issues/640
On this web page(https://docs.microsoft.com/zh-cn/aspnet/web-forms/overview/data-access/introduction/creating-a-data-access-layer-cs),

I want to download the code by clicking the link("下载示例应用程序或下载 PDF"),
but it is not successful. What should I do?

**Comment by Rick-Anderson** [comment]
@ZhouHelen I'm sorry, that download is no longer available.
