### ISSUE TITLE
Add section: How to update M.A.All 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8312]
https://github.com/aspnet/Identity/issues/1870 has instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5324eda1-40f2-4e41-08ff-c2610f3853c2
* Version Independent ID: 99d54f78-d56e-8061-e821-90748722c184
* Content: [Microsoft.AspNetCore.All metapackage for ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/metapackage.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/metapackage.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Since M.A.All is going out of service, no need.

**Comment by JunTaoLuo** [comment]
I think you misunderstood. 2.0 is going out of service not M.A.All. Though we recommend users to move to M.A.App in 2.1 and 2.2, we still produce and support M.A.All in these releases.

**Comment by Rick-Anderson** [comment]
Should I re-open #8728 and point to the M.A.App update section on updating M.A.All?

**Comment by JunTaoLuo** [comment]
I would remove the `Update ASP.NET Core 2.0` section. In the `Update ASP.NET Core 2.1` section:

```
We recommend migrating migrating to the `Microsoft.AspNetCore.App` metapackage for 2.1 and later. To keep using the `Microsoft.AspNetCore.All` metapackage and ensure the latest patch version is deployed:
* On development machines and build servers: Install the latest [.NET Core SDK](https://www.microsoft.com/net/download).
* On deployment servers: Install the latest [.NET Core runtime](https://www.microsoft.com/net/download).
 Your app will roll forward to the latest installed version on an application restart.
```
