### ISSUE TITLE
CreateScope() does not exist

### ISSUE THREAD

**Issue by nabokov-ef** [aspnet/Docs#8315]
Copied the code and got this error:
'IServiceProvider' does not contain a definition for 'GetScope' and no accessible extension method 'GetScope' accepting a first argument of type 'IServiceProvider' could be found (are you missing a using directive or an assembly reference?)
Can't figure out where this method is located.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#call-services-from-main)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@nabokov-ef `GetScope` ?? ... Where do you see that? Do you mean `AddScoped`?

Use the sample app for experimenting. It has the correct namespaces and project reference.

https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/dependency-injection/samples/2.x/DependencyInjectionSample

Take a ZIP download of the aspnet/Docs repo and navigate to the sample folder.

**Comment by nabokov-ef** [comment]
@guardrex Excuse me, I was blind. No question.

**Comment by guardrex** [comment]
Ok ... no problem. :+1:
