### ISSUE TITLE
why GetEmailAsync(user) but user.Name ?

### ISSUE THREAD

**Issue by rpokrovskij** [aspnet/Docs#8321]
Could you explain why you mix async get functions with _normal_ getters:

```
public async Task<IActionResult> OnGetAsync()
{
       ...
        var userName = await _userManager.GetUserNameAsync(user);
        var email = await _userManager.GetEmailAsync(user);
        var phoneNumber = await _userManager.GetPhoneNumberAsync(user);
```

with normal:

```
        Input = new InputModel
        {
            Name = user.Name, // !!
            DOB = user.DOB, // !!
            Email = email, // ??
            PhoneNumber = phoneNumber // ??
        };
```

Why not just:

```
        Input = new InputModel
        {
            Name = user.Name, 
            DOB = user.DOB, 
            Email =  user.Email,  
            PhoneNumber =  user.PhoneNumber
        };
```

What is a meaning of mixing async and "straight forward" getters?

**Comment by Rick-Anderson** [comment]
@rpokrovskij  what document are you talking about?

**Comment by Rick-Anderson** [comment]
@rpokrovskij  the async methods hit a data store. That's when you want to use async. The getters are form data.

**Comment by rpokrovskij** [comment]
Thank you for the reply.
I'm talking about this document: https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
