### ISSUE TITLE
Site Extension name is wrong

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#8322]
> 6. Select ASP.NET Core Extensions.

The `ASP.NET Core Extensions` site extension is the one used to enable integration pieces like streaming logs.
To deploy a preview release to Antares, folks need to install the ASP.NET Core Runtime site extension

![siteext](https://user-images.githubusercontent.com/4734691/44811643-f7bc9280-ab89-11e8-9d25-de2f13a96d1e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Host ASP.NET Core on Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1#deploy-aspnet-core-preview-release-to-azure-app-service)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @shirhatti ... I'll patch it.

**Comment by shirhatti** [comment]
cc @vijayrkn

**Comment by vijayrkn** [comment]
Thanks! Also, can we update the screenshot to show x86 runtime selected instead of x64

**Comment by guardrex** [comment]
It does show x86. I must be looking at something else. Where you do you see x64?

**Comment by guardrex** [comment]
I see what you mean about these ... they're new, right?

<img width="218" alt="capture" src="https://user-images.githubusercontent.com/1622880/44812406-c1d4d980-ab9c-11e8-96e3-85863c9725e5.PNG">

Should I squeeze in here somewhere that x86 is supported for framework-dependent deployments; x64 only for standalone. We don't actually say that anywhere here.

**Comment by guardrex** [comment]
@shirhatti The extension states ...

```
ASP.NET Core 2.2 (x86) Runtime 
2.2.0-preview1-35029
```
... but after adding the extension and calling up the console for a `dotnet --info`, it doesn't indicate that that runtime is available.

Is another step required before asking for a `dotnet --info`?

<img width="469" alt="cons" src="https://user-images.githubusercontent.com/1622880/44813609-cf3f9300-ab9f-11e8-9c25-6c9de6f7b8b4.png">

**Comment by shirhatti** [comment]
This needs a bit of explaining, so hold tight.

The 64-bit site extension does not modify the path, so when you run `dotnet --info` you won't see the 64-bit runtimes.
Out-of-proc will only use the 32-bit .NET runtime since it just uses the first dotnet it finds on your path.

However, ANCM in-proc is aware of where the 64-bit runtime is installed and will probe that location.
In-proc uses the .NET bitness that matches that of the worker process (which controlled via the portal).

Given that the default worker process bitness in Antares, everyone will probably need the 32-bit runtime site extension. Only folks running 64-bit in-proc will require the 64-bit site extension.
Perhaps the best option is to recommend installing both site extensions, but only call out the 32-bit one as mandatory.

**Comment by shirhatti** [comment]
Ah sorry. Turns out I misspoke slightly. In the site extension, we do add `dotnet` to the PATH for the site, but we intentionally exclude it from the PATH for Kudu.

**Comment by shirhatti** [comment]
![image](https://user-images.githubusercontent.com/4734691/44816929-9c45d100-ab98-11e8-916b-196e8c89a099.png)

**Comment by guardrex** [comment]
It didn't list that.

```
D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\77.10823.3533\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files\Git\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files (x86)\npm\3.10.8;C:\DWASFiles\Sites\#1troubleshoot\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\funcpack\1.0.0;D:\Program Files (x86)\nodejs\6.9.1;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;D:\Program Files (x86)\dotnet;D:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\PHP\v5.6;D:\Python27;
```

I'm going to update this app and redeploy it first before I draw any conclusions. This app has been sitting here since that topic was first written AFAIK. I'll report back how it goes.

**Comment by shirhatti** [comment]
To answer your original question, `Test-Path D:\home\SiteExtensions\AspNetCoreRuntime.2.2.x86\` or `Test-Path D:\home\SiteExtensions\AspNetCoreRuntime.2.2.x64\` should suffice as a sanity check for whether the site extension installed

**Comment by guardrex** [comment]
ok ... that sounds good.

In the meantime, I ran into another problem. I created a new App ... brought down the pub profile ... shot the app up ... the app runs in the App Service. I go to add the extention ... :boom: ... 

<img width="228" alt="capture" src="https://user-images.githubusercontent.com/1622880/44817954-d4570f00-abac-11e8-9698-8e2cf208216c.PNG">

... and that's a re-test. The first error that popped up the first time I tried to perform the extension install, I think it said something about a bad path.

I'll work with it a bit more and see what's what.

btw- Do we still tell devs to install the ASP.NET Core Extensions extension? For a second there, it looked like it installed that it installed it automatically. I need to double-check it tho ... make sure that I didn't accidentally click on it by mistake.

**Comment by shirhatti** [comment]
Are you running on the free tier on Antares? You probably ran out of disk space

**Comment by guardrex** [comment]
Yes, free. I think so ... ran out of space. However, it didn't say that at first. The first message was about a bad path. I'll re-do all of my steps from scratch with a fresh app deployment and see if it repros.

**Comment by shirhatti** [comment]
> Do we still tell devs to install the ASP.NET Core Extensions extension?

Yes. AFAIK, VS publishes installs it by default. @vijayrkn can confirm?

**Comment by guardrex** [comment]
If it turns out that a small app (as my test app is) can't be installed with the extension (to be able to run with preview) on the free tier ... that seems kind'a bad. It makes me wonder if we have to tell devs in the topic that on the free tier they won't have enough space to install the preview runtime and their app. It's not supported by virtue of the limitation on free tier space.

**Comment by vijayrkn** [comment]
yes, VS installs the ASP.NET Core Extensions by default as part of VS Publish.

**Comment by shirhatti** [comment]
>If it turns out that a small app (as my test app is) can't be installed with the extension (to be able to run with preview) on the free tier ... that seems kind'a bad. It makes me wonder if we have to tell devs in the topic that on the free tier they won't have enough space to install the preview runtime and their app. It's not supported by virtue of the limitation on free tier space.

If I'm not mistaken, that's an issue with publishing a self-contained app as well.

**Comment by guardrex** [comment]
Ah ... I found the other error message. The one about the bad path ...

<img width="236" alt="capture" src="https://user-images.githubusercontent.com/1622880/44818714-98717900-abaf-11e8-99ab-972723d78f7d.PNG">

Anyway ... I think I have enough to get the PR done. I'll see if I can square this away tonight.
