### ISSUE TITLE
Localization sample project has resources in wrong folder

### ISSUE THREAD

**Issue by Eilon** [aspnet/Docs#8323]
Original issue is here: https://github.com/aspnet/Home/issues/3472

> FIrst of all i have to tell that seems like there's an errors in sample localization project: https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/localization/sample/Localization, when trying convention resolving i found that InfoController localization not working until you place resources in Resources/StarterWeb/Controllers/…. Folder where it searching them for.

(Note: I have not verified this issue, I'm just copying it from the original issue.)

cc @Unders0n

**Comment by guardrex** [comment]
The sample is due for an update, but we don't have an ETA for that at this time. I've cross-referenced this issue on the sample update tracking issue (#5495) to make sure that this is addressed when the sample is updated.

**Comment by hishamco** [comment]
@Rick-Anderson this need to be closed

**Comment by Unders0n** [comment]
Sorry, i will post a sample in the coming days

**Comment by guardrex** [comment]
@hishamco, are you saying that the work is either already planned on another issue or that the work is already complete?

**Comment by hishamco** [comment]
@guardrex It's already done in commit https://github.com/aspnet/Docs/commit/29c39626cd2bf929507a4eed1512fe8fff6d888a

**Comment by guardrex** [comment]
Oh ... I see what happened. You wrote ...

> This address #8219 #8323, 

... but GH only auto-closes these issues when the PR says "Fixes" ...

```
Fixes #8219
Fixes #8323
```

**Comment by hishamco** [comment]
Perhaps I didn't mention that in the PR title itself, really i'm not sure how the auto closing is happen :smile:

**Comment by guardrex** [comment]
Do it this way in the PRs comment ...

```
Fixes #8219
Fixes #8323
```

... and the issues will auto-close when the PR merges.

**Comment by guardrex** [comment]
If you want the issue to say open, use "Addresses" instead ...

```
Fixes #8219
Addresses #8323
```

8219 will close ... 8323 will remain open.

**Comment by hishamco** [comment]
I see, thanks for the new information that I know today, I will do it for my next PR today

thanks

**Comment by guardrex** [comment]
I just added to my :cow2: **_Where's the BEEF?!_**:tm: :cow2: issue https://github.com/aspnet/Docs/issues/2617. I'm sort of keeping that up-to-date. We might do something to surface some of it on https://github.com/aspnet/Docs/issues/8814.
