### ISSUE TITLE
Great tutorial

### ISSUE THREAD

**Issue by jkkirkland** [aspnet/Docs#8324]
Learned much doing all eight parts. Most problems I had were self-inflicted gunshot wounds. 

One issue previously mentioned by another user was switch of SchoolContext from ContosoUniversity.Model namespace to ContosoUniversity.Data namespace. I elected to go ahead shift the SchoolContext into the ContosoUniversity.Data namespace and under the Data directory. Then manually did a global file search and replace (not to hard to find what breaks - just follow the build errors).  Doing so only had one small side-effect: namely scaffolding of entities using the "Razor Pages using Entity Framework (CRUD)" broke because I didn't notice that the Data Context used by default still pointed to "ContosoUniversity.Models.ContosoUniversityContext". When I attempted to erroneously change this to "ContosoUniversity.Models.SchoolsContext" following scaffolding the initial scaffolding instructions I was presented with VS error: 

"There was an error running the selected code generator: 
'There was an error creating a DbContext, the file c:\...\SchoolContext.cs already exists'"

 After rerunning the "Add Razor Pages using Entity Framework (CRUD) dialogue and changing the Data Context class for the scaffolding to the correct context "ContosoUniversity.Data.SchoolsContext" everything worked as it should. 

Thanks again for putting this together. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16a5d321-117b-c37c-6ac9-b56009e7ead7
* Version Independent ID: e337d2e1-7447-634a-d11a-511247e0f897
* Content: [Razor Pages with EF Core in ASP.NET Core - Concurrency - 8 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/concurrency.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/concurrency.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @jkkirkland. You're correct the namespace issues. There's an open issue to address that: https://github.com/aspnet/Docs/issues/7745.
