### ISSUE TITLE
ReadAsAsync is missing in net core 2.1

### ISSUE THREAD

**Issue by antonioortizpola** [aspnet/Docs#8326]
I can not seem to find the 'ReadAsAsync', from this blog (https://nodogmablog.bryanhogan.net/2017/10/httpcontent-readasasync-with-net-core-2/) i worry that is not included??

There is a
- ReadAsStreamAsync
- ReadAsStringAsync
- ReadAsByteArrayAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Initiate HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by antonioortizpola** [comment]
Ok, my fault, there is Microsoft.AspNet.WebApi.Client with this call, however it should be added as prerequisite

**Comment by Rick-Anderson** [comment]
@antonioortizpola `Microsoft.AspNet.WebApi.Client` in included in [Microsoft.AspNetCore.App](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.1)

**Comment by scottaddie** [comment]
@antonioortizpola Are you targeting .NET Framework or .NET Core?

**Comment by antonioortizpola** [comment]
Oh god, sorry, my mistake, i got confused because the project had
`Microsoft.NETCore.App`, but i was missing `Microsoft.AspNetCore.App`

**Comment by antonioortizpola** [comment]
@scottaddie we are targeting NET core

**Comment by scottaddie** [comment]
@antonioortizpola No worries. Microsoft.AspNetCore.App is the NuGet package that gives you all the necessary bits for ASP.NET Core 2.1 or later. As Rick pointed out, referencing that package will give you the Microsoft.AspNet.WebApi.Client package too:

![image](https://user-images.githubusercontent.com/10702007/44928311-28810100-ad1d-11e8-8f4d-f8d0d7b362ea.png)
