### ISSUE TITLE
update Tutorial: Get started with SignalR to 2.2

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8335]
- [ ] update Tutorial: Get started with SignalR to 2.2
- [ ] Use include for prereq's
Fixed by #9760
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Tutorial: Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@Rick-Anderson 

> Use include for prereq's

Does the include to use already exist / what's its name?

**Comment by Rick-Anderson** [comment]
Includes are in #9469
