### ISSUE TITLE
Download not available

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8337]
Since the source can no longer be downloaded, (See #8307) I don't know why there is there still a link here to DOWNLOAD? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [ASP.NET Core MVC with Entity Framework Core - Tutorial 1 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
#8307 is a different tutoiral. This download is fine.

**Comment by lm28** [comment]
Thanks Rick - I eventually found the correct link. 
The 'Download or view completed applicatgion' link on this (current) page takes me to https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-mvc/intro/samples/cu-final . . . . but this target does NOT contain a download link.
If I scroll to the bottom of that page, and look in the 'Download it' paragraph, then the link under 'completed project' simply returns me to the same page.
However, the 'ASP Docs/Repository' link took me to a similar looking page, but it did contain download page.
