### ISSUE TITLE
Logging.Console

### ISSUE THREAD

**Issue by rswetnam** [aspnet/Docs#8338]
I've spent quite a bit of time fiddling around trying to see how to get things to show in Microsoft.Extensions.Logging.Console.  Finally figured out that it was a Nuget package that I had to download.  - But still cannot find where to show this console and its output that you refer to in the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @rswetnam ... Console output should show up in a console window in a CLI scenario. In VSC and VS, you can configure for an internal or external console. How are you running the app?

**Comment by rswetnam** [comment]
Hi Luke... Thanks for the quick response.  I set up the TodoSampleApi Project as part of test solution I have in Visual Studio and  pressed F5 and was able to see the Log messages and play around with the different levels.  Probably most of your readers are much more sophisticated than me but I didn't know why I would run the output in a Console, how I would do it, or that you could run it in a internal or external mode.  I still don't know how I would access the external console window once I figured out that it was a Nuget package that I needed to download and how I would configure it .  Some explanation or links answering some of these questions would be helpful for me.

**Comment by guardrex** [comment]
btw --- To make logging dead-on simple and useful, we still recommend a 3rd party provider. Something like Serilog makes it super-easy and useful. You can have sinks for any kind of output, such as dB, log files, Azure Table Storage, etc. The engineers have spoken in year's past about producing an in-the-box Microsoft logging provider, but I haven't heard anything about that this year.
