### ISSUE TITLE
Add ViewComponentResult  guidance

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#834]
From: Ryan Nowak 
We should add this guidance to the docs rather than referring to an old functional test. 

From: Kiran Challa I suppose the documentation is referring to RC1 milestone, the following link works:

https://github.com/aspnet/Mvc/blob/6.0.0-rc1/test/WebSites/ViewComponentWebSite/ViewComponentResultController.cs
Dan Roth recommended a customer look at https://github.com/aspnet/Mvc/blob/dev/test/WebSites/ViewComponentWebSite/ViewComponentResultController.cs

**Comment by danroth27** [comment]
Should be covered by https://github.com/aspnet/Docs/issues/868
