### ISSUE TITLE
Remove/rephrase paragraph stating that bundleconfig is part of a content coming with templates

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Docs#8359]
## General

https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x#configure-bundling-and-minification

> The MVC and Razor Pages project templates provide a bundleconfig.json configuration file which defines the options for each bundle.

The paragraph statement is not correct with current templates and should be remove or rephrased.

## Issues with Existing Topics

The docs section is not correct. I've been answering a question (and a complain) from a fellow dev today about the state of content bundling and minification. The docs statement is incorrect as the `bundleconfig.json` no longer ships. 

This was discussed as part of #7090:
https://github.com/aspnet/Docs/issues/7090

x-ref: https://github.com/aspnet/Templating/issues/326

Thanks!

**Comment by scottaddie** [comment]
Thank you for reporting this, @peterblazejewicz. I hope to get to this within the next week.

**Comment by peterblazejewicz** [comment]
Hi Scott, I know that's hard topic atm to handle nicely, no hurry!

**Comment by scottaddie** [comment]
Fixed in https://github.com/aspnet/Docs/pull/9655
