### ISSUE TITLE
Is it possible to use the "Add new scaffolded" action?

### ISSUE THREAD

**Issue by gabrielRibeiroCamargoFerreira** [aspnet/Docs#8361]
I tried to add the package  "Microsoft. VisualStudio. Web. cogenerators. MVC " But the item does not appear in the menu to select.
My intention is to make the scaffolding of the Identity to reuse in my projects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
>I tried to add the package "Microsoft. VisualStudio. Web. cogenerators. MVC "

Where does it say to do that?

**Comment by gabrielRibeiroCamargoFerreira** [comment]
In csproj.
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.1" PrivateAssets="All" />

**Comment by Rick-Anderson** [comment]
Where in the doc?

**Comment by gabrielRibeiroCamargoFerreira** [comment]
There is nothing in the documentation on how to enable the scaffolding button or if it is possible.
Is it possible to generate?

**Comment by gabrielRibeiroCamargoFerreira** [comment]
I am using SDK 2.1.401 with Visual Studio in version 15.8.2
In my Web Application MVC project the menu appears "Add> New Scaffolded Item", and in that same solution in the Razor Class Library project does not appear

**Comment by Rick-Anderson** [comment]
It won't show in RCL project. RCL is the wrong project for scaffolding.

**Comment by gabrielRibeiroCamargoFerreira** [comment]
And will it never be possible or is it a limitation now?

**Comment by Rick-Anderson** [comment]
RCL's are for UI, not data access.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by gabrielRibeiroCamargoFerreira** [comment]
Yes. Based on this response I changed my architecture to use RCL the correct way
