### ISSUE TITLE
need to mention "listen on http"

### ISSUE THREAD

**Issue by cppcraze** [aspnet/Docs#8362]
Hi there, the instruction in this document is not fully clear. When people just use kestrel in their asp.net core web app, if they only listen on https port, http to https redirect doesn't fully work. It's better mention kestrel needs to listen on both http and https port so that redirect will work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@cppcraze  thanks. We'll get this fixed in the next sprint.

**Comment by guardrex** [comment]
Cross-ref: **Expand scope of the Enforce HTTPS article** #6538
