### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8363]
It seems that the NEXT/Previous links in this tutorial are all pointing to ASP.Net Core 2.1 (Which has not been developed yet)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [ASP.NET Core MVC with EF Core - Inheritance - 9 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-2.0#summary)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
The links work here. Can you grab a couple of them and paste them in here?

**Comment by Rick-Anderson** [comment]
@guardrex I think his complaint is he has version 2.1 selected and these are not updated to 2.1

**Comment by antonioortizpola** [comment]
I think the link from the comment is fine, is pointing to 
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-2.0#summary
and prev and next still pointing to 2.0, and they change fine changing the url to
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-2.1#summary
Or i have not understand the problem yet :s

**Comment by lm28** [comment]
I initially wanted to follow the content for 2.1, but that has not been developed yet, so I reverted to 2.0.
However, I found that each time I clicked the NEXT link at the end of each tutorial, it would take me back to the 2.1 page.
It seems that you have solved the issue. Thanks
