### ISSUE TITLE
NullReferenceException in Index file.

### ISSUE THREAD

**Issue by llgjermeni** [aspnet/Docs#8372]
Hi, I have a NullReferenceException in Pages.Departments.Pages_Departments_Index.ExecuteAsync() in Index.cshtml `<td>@item.RowVersion[7]</td>`. I checked the code and is the same as the tutorial code.
I have used InMemoryDatabase without migration. That's the only difference.

**Comment by scottaddie** [comment]
@llgjermeni Which document are you referring to?

**Comment by llgjermeni** [comment]
Handle concurrency conflicts 
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/concurrency?view=aspnetcore-2.1&tabs=visual-studio

**Comment by llgjermeni** [comment]
@scottaddie this NullReferenceException has to do with InMemoryDatabase or I am missing something else.

**Comment by Rick-Anderson** [comment]
@llgjermeni  you'll probably get a quicker response posting this to a support forum.

**Comment by llgjermeni** [comment]
I just wanted to know if the concurrency can be done with InMemoryDatabase. Anyway thanks for the answer.
