### ISSUE TITLE
Confusing statement in final paragraph

### ISSUE THREAD

**Issue by ronnyek** [aspnet/Docs#8373]
I have reasons why I know injecting IHttpContextAccessor is probably a bad idea... but I've got non-endpoint places I want to access information in claims principal... and trying to understand what would be the proper way to adhere to core principals... (preferring injected dependencies to static). 

Is the right way to stick stick to core principles, just take the mvc endpoints, extract info from claims principal, and pass via arguments to other services/repositories etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b42a61c-cf3a-3bdb-0145-dc6295c5ba23
* Version Independent ID: 5b8d2082-1e70-eb9a-1bbe-7b93f74bdd3a
* Content: [Migrate from ClaimsPrincipal.Current](https://docs.microsoft.com/en-us/aspnet/core/migration/claimsprincipal-current?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/claimsprincipal-current.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/claimsprincipal-current.md)
* Product: **aspnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@ronnyek  you'll probably get a lot faster response posting this to a support forum.
