### ISSUE TITLE
Bower Deprecated

### ISSUE THREAD

**Issue by carsonms** [aspnet/Docs#8375]
This documentation needs updating as it appears that Bower has been deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a90c973b-dd21-5dc6-4c70-7ddfba51271e
* Version Independent ID: b20b9d8e-e29a-44a4-18d0-e78f4e8dc51f
* Content: [Build beautiful, responsive sites with Bootstrap and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bootstrap?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/bootstrap.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bootstrap.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@carsonms You're correct. An easy-to-use replacement for Bower is LibMan. Read more here: https://docs.microsoft.com/aspnet/core/client-side/libman/.

**Comment by keyurpd** [comment]
I can help 'copy-paste' the 'important' note regarding 'bower deprecated' from [here](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-2.1).

**Comment by scottaddie** [comment]
@keyurpd This doc will receive significant updates, as the ASP.NET Core 2.2 project templates have adopted Bootstrap 4. The doc also will be updated to use LibMan.

**Comment by daveabrock** [comment]
Hey, @scottaddie: can I help with these updates?

**Comment by scottaddie** [comment]
@daveabrock We appreciate the offer; however, the decision has been made to retire this doc. It's not our product, and the Bootstrap team already provides good documentation.

**Comment by daveabrock** [comment]
Makes sense. Thanks for the reply.
