### ISSUE TITLE
To download the small sample takes roughly 600 MB currently

### ISSUE THREAD

**Issue by cveld** [aspnet/Docs#8379]
Currently one is required to download or clone the complete docs repo which takes roughly 600 MB as a payload in order to work with the sample code. Ideally github and/or the docs platform should provide a more lean way to only download the sample code specifically. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Tutorial: Get started with SignalR on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @cveld  ... The documentation engineers are working on a fix for this so that individual samples can be downloaded. No ETA yet, but we hope it will be resolved soon. https://github.com/aspnet/Docs/issues/6991#issuecomment-398104010
