### ISSUE TITLE
nvarchar 900

### ISSUE THREAD

**Issue by wanton7** [aspnet/Docs#8383]
Isn't there 900 byte limit for indexes? nvarchar will take 2 bytes for every character so 900 will be 1800 bytes. That Id column should probably be nvarchar(450) or varchar(900).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Work with a distributed cache in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I think we'll need to cross-open this for tooling, since `sql-cache create` creates the table.

**Comment by guardrex** [comment]
Opened at https://github.com/aspnet/DotNetTools/issues/480
