### ISSUE TITLE
Broken URL in Configuration page

### ISSUE THREAD

**Issue by gmanvel** [aspnet/Docs#8386]
In the section [The Configure method](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#the-configure-method) at the end of first paragraph, URL linking to [source code](https://github.com/aspnet/Hosting/blob/release/2.0.0/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L179-L192) in github is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793395fe-c738-22ce-d0e9-29a850c0fa88
* Version Independent ID: 0546ce3a-3258-9817-0f3f-13281c2f55da
* Content: [Application startup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/startup.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/startup.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks @gmanvel ... I'll square that away right now.
