### ISSUE TITLE
Extensibility section / RabbitMQ

### ISSUE THREAD

**Issue by JamesDriscoll** [aspnet/Docs#8393]
In https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1#extensibility you say "The following example shows how an extension method extends an IHostBuilder implementation with RabbitMQ. The extension method (elsewhere in the app) registers a RabbitMQ IHostedService"

I cannot find this "elsewhere in the app". Could you please supply details of this?

Thanks,

James

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1#extensibility)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by JamesDriscoll** [comment]
HI!

Thanks for the quick reply!

I think you should update the docs then to state that there is no concrete implementation of this, and that it would be for the developer to write such extension methods.

For me, the current wording implies that there is sample code available that demonstrates how to set up connections to Rabbit and then handle incoming messages!

Kind regards,

James

**Comment by Tratcher** [comment]
Running RabbitMQ as a hosted service is fine. That's what we used as a prototype when developing hosted services.

I'm not sure what the point of `UseRabbitMq<T>` is since it doesn't provide any functionality beyond `AddHostedService<T>`.

**Comment by guardrex** [comment]
Yes, and that's a problem with my idea of linking this example to the timed hosted service, except that it would link to a full example implementation over in the background tasks topic.

```csharp
var host = new HostBuilder()
    .ConfigureServices((hostContext, services) =>
    {
        services.AddHostedService<TimedHostedService>();
```
... to ...
```csharp
var host = new HostBuilder()
    .UseHostedService<TimedHostedService>()
```

wow

Following David's lead, it was just supposed to be 'extensibility via extension methods on `HostBuilder`'. 

* Do you want to cut the *Extensibility* section out of the topic?
* Substitute the example with something else (possibly the silly `TimedHostedService` example)?
* Just put the extension method for the RabbitMQ example in there to clarify the example a bit more?
* Do nothing?

**Comment by Tratcher** [comment]
TimedHostedService might work.

**Comment by guardrex** [comment]
Ok ... I'll put that up later today for a look. :eyes:

**Comment by JamesDriscoll** [comment]
Just my thoughts, but I would say no to doing nothing.

The current wording implies that the sample app has an extension method of UseRabbitMq when it doesn't. This is misleading and can lead to plenty of unsuccessful searching trying to find it. 

Bear in mind people looking at this post and thinking, I want to write a hosted service that listens to Rabbit - and think "great, there's a sample out there that I can already borrow from (aka cut and paste!!)"
