### ISSUE TITLE
Mismatch between default template by Visual Studio and the template used in the Identity doc page

### ISSUE THREAD

**Issue by mshwf** [aspnet/Docs#8395]
I'm quite confused between the referenced template, in this [section](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.0&tabs=visual-studio#configure-identity-services):
> Services are added in ConfigureServices.

and the template created by VS (15.7.4). I'm using .NET Core 2.1, and this is the template in a clean new project (ASP.NET Core Web Application, MVC, .NET core 2.1):
 

```
// This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });


            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }
```
Also there are a punch of highlighted lines which means that we add them manually, Am I right? because nothing mentioned about these highlighted lines (why do we need to add them, )
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See #8395

**Comment by Rick-Anderson** [comment]
@mshwf  you're looking at view=aspnetcore-2.0 which is the wrong version.

**Comment by mshwf** [comment]
Yes, The highlighted code is in view=aspnetcore-2.0 , but there still a mismatch with the 2.1 (with no code highlighting) .
