### ISSUE TITLE
ASP.NET Core SignalR JavaScript Client Error For Vue-cli

### ISSUE THREAD

**Issue by JianXinZuo** [aspnet/Docs#8397]
Hello, I have a problem with @aspnet/signalr in Vue.
I hope to provide a demo that uses @aspnet/signalr in Vue-cli.
It is best to provide the next demo for both TypeScript and JavaScript.
Thank you

**Comment by davidfowl** [comment]
What’s the problem?

**Comment by BrennanConroy** [comment]
@Rick-Anderson Probably close this as there isn't anything we can act on here.
