### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by olaowolawi** [aspnet/Docs#8398]
There is a problem with navigation here.
The next button is not changing the pages. 

Please help resolve the issue.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [ASP.NET Core MVC with Entity Framework Core - Tutorial 1 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by adolfo1981** [comment]
Same for me. It's showing the same content for all pages in Edge and Chrome.

**Comment by Rick-Anderson** [comment]
@adolfo1981 it's showing mostly the same content, but it's a new page. Check the title and follow the instructions.

**Comment by wpqs** [comment]
Just noticed a comment at the top of the blurb saying v2.1 isn't supported. I suggest you remove the option to select 2.1 from the drop-down until it is.
