### ISSUE TITLE
External Login Authentication

### ISSUE THREAD

**Issue by Urgen-Dorjee** [aspnet/Docs#8399]
Asp.Net core application, I have integrated third parties login authentication, "Twitter,Facebook" etc, however the problem is: "My User Identity context has First and Last Name", which is required but when i try to authenticate through external providers, it wont have an options to add these fields. How can I add these fields with external login providers, so my database will have first and last name along with its external providers credential details.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb577d84-a06b-4d3e-a1c4-92c8a97a85aa
* Version Independent ID: 528fcbb8-5b0f-8340-743f-df612319a229
* Content: [Twitter external login setup with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/twitter-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/twitter-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/twitter-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Urgen-Dorjee ... We have a brand new topic that might help. It explains how to establish additional claims based on user data provided by the external login providers. See if this helps ...

https://docs.microsoft.com/aspnet/core/security/authentication/social/additional-claims

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio might help.

**Comment by Urgen-Dorjee** [comment]
Thanks for your reference docs, let me check how i can make thing up!
