### ISSUE TITLE
The NETCore website failed to start process with commandline '"xxx.exe" ', ErrorCode = '0x800700d8'.

### ISSUE THREAD

**Issue by sdluhaibing** [aspnet/Docs#8400]
The NETCore website failed to start process with commandline '"xxx.exe" ', ErrorCode = '0x800700d8'.

stdout log is empty. 
OS: Windows 7 enterprise, 32 bit
.NET Core 1.0.0 runtime 

The website works fine in windows server 2008R2. 
Already checked the known issue in https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1
but no lucky. BTW, the windows update was done by company LAN tool. Any suggestion/idea would be appreciated.

See below for web config:
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\xxx.exe" arguments="" forwardWindowsAuthToken="false" stdoutLogEnabled="true"  stdoutLogFile=".\logs\stdout" />
    <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Headers" value="Content-Type" />
        <add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
</configuration>

**Comment by sdluhaibing** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath=".\xxx.exe" arguments="" forwardWindowsAuthToken="false" stdoutLogEnabled="true"  stdoutLogFile=".\logs\stdout" />
    <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Headers" value="Content-Type" />
        <add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
      </customHeaders>
    </httpProtocol>
  </system.webServer>
</configuration>

**Comment by guardrex** [comment]
Hello @sdluhaibing ...

That error code might be: `ERROR_EXE_MACHINE_TYPE_MISMATCH`. It's not a common error code and doesn't appear in the IIS Integration repo issues. It might be a platform architecture error [x64 (64-bit) vs. x86 (32-bit)]. If this is a self-contained app, try specifying a 32-bit runtime (for example, `win7-x86`) and see if that will run on your Win7 machine.

If that doesn't work out (or it's a framework-dependent app), I recommend you open this over on the aspnet/Home issues for the engineers to see:

https://github.com/aspnet/Home/issues

Give them as much info about your setup as you can. If you put up a repro project on GitHub for them to see the app (or a small test app that breaks the same way), that can be helpful for them.

Either ping me on the issue "cc @guardrex" ... or please come back and let me know what the cause of the problem was. That's not a typical error code for an ASP.NET Core app, and we might need to add an entry to the [Common errors topic](https://docs.microsoft.com/aspnet/core/host-and-deploy/azure-iis-errors-reference) to cover it.

**Comment by sdluhaibing** [comment]
hello, already tried specify runtime win7-x86 for my app. but found that I can build with any runtime name like "testruntime" and also can publish with this runtime. Seems like dotnet did not verify the runtime when building. I am not sure if it is due to this.

**Comment by guardrex** [comment]
This is a self-contained app? How are you publishing ... are you specifying the RID in the project file and in the publish command?

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.1</TargetFramework>
  <RuntimeIdentifiers>win7-x86;win7-x64</RuntimeIdentifiers>
</PropertyGroup>
```

For your Win7 machine (x86) ...

```console
dotnet publish --configuration Release --runtime win7-x86
```

Published output at: `\bin\Release\netcoreapp2.1\win7-x86\`.

For your WS2008R2 (if x64) ...

```console
dotnet publish --configuration Release --runtime win7-x64
```

Published output at: `\bin\Release\netcoreapp2.1\win7-x64\`.

**Comment by sdluhaibing** [comment]
hello @guardrex, 

No, because we need to install DotNetCore on server side. We build with command "dotnet build --configuration Release -r win7-x86" and then publish with "win7-x86" to local file folder in visual studio. At last copy to the server and finish the deployment. 

See the below for the project.json:
`  "dependencies": {
    "Domain.ViewModel": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Mvc.WebApiCompatShim": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },

  "frameworks": {
    "net451": {
      "dependencies": {
        "Domain.JIT": {
          "target": "project"
        }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": "appsettings.json"
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "runtimes": {
    "win7-x64": {},
    "win7-x86": {}
  }`

**Comment by guardrex** [comment]
Oh ... I see.

*project.json*/*xproj*-based .NET Core is no longer supported. You'll need to upgrade the project and use the latest SDK. See the migration topics over on the .NET Core repo: https://docs.microsoft.com/dotnet/core/migration/

**Comment by sdluhaibing** [comment]
hello @guardrex,

Thanks so much for your information. Checked the latest SDK and link you mentioned. Latest NetCore  2.1 can only work with visual studio 2017. Currently, we are still on visual studio 2015 and can not free to update to 2017 due to the license.  Any problem about the project opened in visual studio 2015 if we only upgrate NetCore to 2.1 and migrate project.json to .csproj?

**Comment by guardrex** [comment]
The minimum VS version supported for the migration to MSBuild/csproj is 2017.

You might be able to get away with using VS2015 purely as an editor. Use the command-line tools to restore/build/publish/etc. However, I'm fairly certain that Intellisense won't work. It may also throw a bunch of warnings and errors. It really isn't supported, and I don't know how 2015 will behave. Even if can work purely as a file editor, it might be painful to use.

Under the circumstances if you can't use 2017 Community Edition, then I recommend Visual Studio Code.

https://code.visualstudio.com/
