### ISSUE TITLE
.css files missing

### ISSUE THREAD

**Issue by DennisCG** [aspnet/Docs#8401]
When I follow the instructions and debug the project there are no stylesheets and other files are missing as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What files exactly are missing?

**Comment by Rick-Anderson** [comment]
If you can reproduce the error, you might want to open an issue with Visual Studio. Can you repo this when creating a new project? Do you have the latest VS and .NET Core SDK? Can you repo this with `dotnet new Razor` ?
