### ISSUE TITLE
Production apps should call UseHsts - why?

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8402]
Do we need to state `UseHsts` does not guarantee traffic will be redirected to HTTPS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ddfb2f-5dea-5e31-2a27-02a4dc16104c
* Version Independent ID: 12ca0b9a-2638-a4ce-c45f-d4579c83dafb
* Content: [Enforce HTTPS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/enforcing-ssl.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/enforcing-ssl.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Tratcher please advise.

**Comment by Tratcher** [comment]
Is there a context for this question? 

But yes, HSTS is not guaranteed, it may not be supported by your client. It also requires at least one successful HTTPS request to establish the HSTS policy. You still need a check on every request to handle HTTP requests (redirect, reject, etc). HSTS is a client side performance optimization to avoid an extra request to the server.

**Comment by Rick-Anderson** [comment]
The doc is **Enforce HTTPS in ASP.NET Core** - so I think we should list the limitations.

Should I add the following to the PR on the doc?

HSTS is a client side performance optimization to avoid an extra request to the server. HSTS limitations:

* HSTS is not guaranteed to limit traffic to HTTPS only.
* HSTS requires at least one successful HTTPS request to establish the HSTS policy.
* Application must check every HTTP request and redirect, reject, etc.

`UseHttpsRedirection` limitations:

* Does not guarantee HTTP requests are redirected to HTTPS.
* Is less robust than HSTS, but more convenient in development.

**Comment by Tratcher** [comment]
Comparing them to each other is a bit odd, an app should have both. UseHttpsRedirection does redirect to https *if properly configured*. The risk is that the client may have sent sensitive data on that initial request. HSTS will prevent such leaks in the future, but cannot protect the first request.

 You missed the part about the client needing to support HSTS.
