### ISSUE TITLE
Custom Scaffolding?

### ISSUE THREAD

**Issue by StevenTCramer** [aspnet/Docs#8405]
I would love to create some custom scaffolding.  Is there any documentation on how to get started?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@seancpeters  do we have anything to get started?

**Comment by Rick-Anderson** [comment]
@seancpeters do we have anything to get started?

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/938
