### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by jocoding** [aspnet/Docs#8411]
Hi, I am receiving an error when trying to this tutorial in the following line of code  var host = WebHostBuilder(args); I am not sure what is wrong.
thanks 
J.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad06677-5842-c1aa-153f-7993a9660dfa
* Version Independent ID: 8daf79df-eac4-358b-e6f0-6def45bd54da
* Content: [ASP.NET Core MVC with Entity Framework Core - Tutorial 1 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/intro?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-mvc/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by jocoding** [comment]
![capture](https://user-images.githubusercontent.com/23239401/45085610-fa266b80-b0f8-11e8-84cc-e69b2af4e3b6.PNG)

**Comment by t-wheatley** [comment]
For anyone having this issue replace the provided "CreateWebHostBuilder":
`public static IWebHostBuilder CreateWebHostBuilder(string[] args) => WebHost.CreateDefaultBuilder(args).UseStartup<Startup>();`


With this "BuildWebHost":

`public static IWebHost BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build();`

**Comment by Lauralius** [comment]
To launch, I had to make that line be

public static IWebHost BuildWebHost(string[] args) => WebHost.CreateDefaultBuilder(args).UseStartup<ContosoUniversity.Startup>().Build();

It might have something to do with the set of NuGets I have. I made sure I had the ones explicitly listed, but there might be something else missing.
