### ISSUE TITLE
Disable Typescript

### ISSUE THREAD

**Issue by martypowell** [aspnet/Docs#8412]
Is there a way to easily generate the project without Typescript? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by SteveSandersonMS** [comment]
Yes, the latest React template in ASP.NET Core 2.1 gives you a plain js/jsx project.

For more info about this change, please search for related issues in this repo.

**Comment by martypowell** [comment]
Awesome, thanks for the quick response, it might be worth adding a quick note about this in this document.

**Comment by martypowell** [comment]
Hopefully this may help someone, but my version of .net core was outdated and therefore I was getting a previous version which used typescript. See this [issue ](https://github.com/aspnet/Templating/issues/572)for more information.

**Comment by OlekRia** [comment]
In ,net core I have to predict you will have React built on Visual Basic Script!
