### ISSUE TITLE
I think a typo exists at Custom configuration section's example code

### ISSUE THREAD

**Issue by devtedlee** [aspnet/Docs#8413]
about 'EFConfigurationProvider/EFConfigurationExtensions.cs:'

title is 'EFConfigurationProvider/EFConfigurationExtensions.cs:'

but code class name is 'public static class EntityFrameworkExtensions'

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration#custom-configuration-provider)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @devtedlee ... I'll take a look as soon as I get back to the office.

**Comment by guardrex** [comment]
Ok ... took a look. Yes, I think let's make the file name match. This class should hold *any* EF extensions ... not just this one. I'll take care of it this afternoon. Thanks for letting us know.
