### ISSUE TITLE
Ubuntu required?

### ISSUE THREAD

**Issue by mrlife** [aspnet/Docs#8421]
Is Ubuntu required for aspnet core on Linux with Nginx, or do the docs just focus on one distribution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti

**Comment by shirhatti** [comment]
Ubuntu is not required and just provided as an example.
ASP.NET Core is supported as documented in our supported OS policy- https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md

The nginx guidance is provided on a best-effort basis.

**Comment by guardrex** [comment]
The topic could explain that (I think). The link would be a nice additional resource, too. I'll float a PR with some language that we can look at.
