### ISSUE TITLE
There is a bug in the sample code

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [aspnet/Docs#8427]
Apparently, if we call services.AddDefaultIdentity&lt;TUser&gt;(), then the changes we make in services.ConfigureApplicationCookie(options =&gt; {}) won't take effect.

We should call services.AddIdentity&lt;TUser, TRole&gt;() instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  see [Configure Identity services](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio#configure-identity-services)

`services.Configure<IdentityOptions>(options =>` works after calling `    services.AddDefaultIdentity<IdentityUser>()`
Does `services.ConfigureApplicationCookie(options =>` work?

**Comment by HaoK** [comment]
Underneath the covers all of these are just adding services to the container, so order matters.

**Comment by HaoK** [comment]
Typically you want to call all of your Adds and then all of your configures
