### ISSUE TITLE
Views cannot discovered automatically from an external assembly in net core 2.x

### ISSUE THREAD

**Issue by hamed-shirbandi** [aspnet/Docs#8429]
I have an RazorUIClassLib project with 1 view and 1 controller.
When i refrence project's dlls to another mvc core 2.1 project, the controller and view can not discovered automatically.

By adding this lines to startup, Controller discovered 

   services.AddMvc()
            .AddApplicationPart(typeof(MyController).GetTypeInfo().Assembly)
            .AddControllersAsServices();

But view still not found.

If i make nuget package from RazorUIClassLib project and install it on target project then controller and view discovered automatically but i need to use direct reference to target projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@pranavkm please comment

**Comment by pranavkm** [comment]
Views are in a separate assembly, and they need to be registered as an application part. Here's the equivalent code:

https://github.com/pranavkm/PluginApp/blob/master/MainApp/Startup.cs#L81-L89

That said, if you have project reference to the class library project or reference it as a package, you shouldn't have to do any of this.

**Comment by mcm-ham** [comment]
@hamed-shirbandi This could be similar to the issue #13951 I experienced. You need to use `dotnet pack` instead of `nuget pack`.
