### ISSUE TITLE
Add the following MovieContext.cs class to the Models folder Missing Reference

### ISSUE THREAD

**Issue by koshercoder** [aspnet/Docs#8430]
I had to add a reference to the Models otherwise the public DbSet&lt;Movie&gt; Movie { get; set; } was  erring out. 

using System;
using Microsoft.EntityFrameworkCore;
using RazorPageMovie.Models;

namespace RazorPagesMovie.Models
{
    public class MovieContext : DbContext
    {
        public MovieContext(DbContextOptions&lt;MovieContext&gt; options)
                : base(options)
        {
        }

        public DbSet&lt;Movie&gt; Movie { get; set; }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa70bd9-d52a-8b71-4f56-abf4b53c5ca1
* Version Independent ID: 99c9a3fe-747c-160e-0a57-421426202506
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@koshercoder  yes, that's required.

**Comment by Rick-Anderson** [comment]
Fixed in unified tutorials.
