### ISSUE TITLE
HasPreviousPage / HasNexPage

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8441]
I have gone over this section of the tutorial several times and these two variable are still not recognised by Index.cshtml.
Im getting Error no CS1061 : "IEnumerable&lt;Student&gt; does not contain a definition of 'HasNextPage' and no extension method...blah blah".
Must 'PaginatedLists.cs' be registered somewhere before the values can be returned to my page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [ASP.NET Core MVC with EF Core - Sort, Filter, Paging - 3 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.0)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@lm28  I'm not sure what you have done wrong but I strongly suggest you follow the RP 2.1 version of this tutorial
https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1

**Comment by lm28** [comment]
Thanks Rick. I had worked my way through the Razor pages content and have been now trying the MVC sample so that I could evaluate which 'design structure' (if I may call it that?) to learn. After a little more investigation, I think that I will probably use Razor for the bulk of my app, and only revert to MVC if/when it might be required.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
