### ISSUE TITLE
systemctl commands need superuser access [ minor correction ]

### ISSUE THREAD

**Issue by Praveen-Rai** [aspnet/Docs#8442]
The code in [Create the service file](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x#create-the-service-file) needs a minor fix.

`systemctl enable kestrel-hellomvc.service`

must be updated to : 

`sudo systemctl enable kestrel-hellomvc.service`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti

**Comment by guardrex** [comment]
@Praveen-Rai Were you also required to `sudo` ...

```console
systemctl start kestrel-hellomvc.service
systemctl status kestrel-hellomvc.service
```

**Comment by Praveen-Rai** [comment]
@guardrex Yes, all systemctl commands require sudo access.

**Comment by Praveen-Rai** [comment]
@guardrex Sure , Meanwhile i am struggling to get the app hosted using SSL and will put up the info as soon as i get clarity. That portion is badly missed in the hosting topics. So, please expect another issue from my end ;-)

**Comment by guardrex** [comment]
Sure thing ... yes, it's best in a new issue. That might take longer to resolve than these few simple things here and on #7641. I hope I can knock these two little items out today.

**Comment by shirhatti** [comment]
Yeah. Looks like all these calls to `systemctl` require sudo
