### ISSUE TITLE
Create full identity UI source - .NET Core CLI

### ISSUE THREAD

**Issue by Phrohdoh** [aspnet/Docs#8443]
&gt; To maintain full control of the Identity UI, run the Identity scaffolder and select Override all files.

There is no such option mentioned in the help for the identity generator so I assume this is a UI option in Visual Studio.

Can this be done with the `dotnet` CLI, and if so how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Phrohdoh** [comment]
We can glue this functionality together manually my using `--listFIles` to get a list of *all* files then using `--files` to scaffold those files.

<details>

```
$ dotnet aspnet-codegenerator identity --listFiles
[.. snip ..]
Account.AccessDenied
Account.ConfirmEmail
Account.ExternalLogin
Account.ForgotPassword
Account.ForgotPasswordConfirmation
Account.Lockout
Account.Login
Account.LoginWith2fa
Account.LoginWithRecoveryCode
Account.Logout
Account.Manage._Layout
Account.Manage._ManageNav
Account.Manage._StatusMessage
Account.Manage.ChangePassword
Account.Manage.DeletePersonalData
Account.Manage.Disable2fa
Account.Manage.DownloadPersonalData
Account.Manage.EnableAuthenticator
Account.Manage.ExternalLogins
Account.Manage.GenerateRecoveryCodes
Account.Manage.Index
Account.Manage.PersonalData
Account.Manage.ResetAuthenticator
Account.Manage.SetPassword
Account.Manage.TwoFactorAuthentication
Account.Register
Account.ResetPassword
Account.ResetPasswordConfirmation
```

Take that file list and combine them with semi-colons but don't forget to surround with quotes or your shell will try to execute them as commands (because `;` is the command terminator)!

```shell
$ dotnet aspnet-codegenerator identity --files="Account.AccessDenied;Account.ConfirmEmail;Account.ExternalLogin;Account.ForgotPassword;Account.ForgotPasswordConfirmation;Account.Lockout;Account.Login;Account.LoginWith2fa;Account.LoginWithRecoveryCode;Account.Logout;Account.Manage._Layout;Account.Manage._ManageNav;Account.Manage._StatusMessage;Account.Manage.ChangePassword;Account.Manage.DeletePersonalData;Account.Manage.Disable2fa;Account.Manage.DownloadPersonalData;Account.Manage.EnableAuthenticator;Account.Manage.ExternalLogins;Account.Manage.GenerateRecoveryCodes;Account.Manage.Index;Account.Manage.PersonalData;Account.Manage.ResetAuthenticator;Account.Manage.SetPassword;Account.Manage.TwoFactorAuthentication;Account.Register;Account.ResetPassword;Account.ResetPasswordConfirmation"
```

</details>

It certainly isn't pretty or ideal but it works.

**Comment by Rick-Anderson** [comment]
@Phrohdoh  perfect timing. I'm working on this today.

**Comment by Rick-Anderson** [comment]
@Phrohdoh do you want to PR this fix?

**Comment by Phrohdoh** [comment]
@Rick-Anderson Unfortunately I've become very busy so won't have time to PR a fix within the near future.
