### ISSUE TITLE
Maybe the guide is a bit out of date?

### ISSUE THREAD

**Issue by dlaptin** [aspnet/Docs#8444]
I have followed the steps in this guide. I don't have the spa.UseAngularCliServer invocation in my Startup class however.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by dlaptin** [comment]
There is no link to download the complete project too.

**Comment by SteveSandersonMS** [comment]
@dlaptin What version of ASP.NET Core are you using? The `UseAngularCliServer` call has been present in the template since ASP.NET Core 2.1.

> There is no link to download the complete project too.

Yes, we'd rather people use the template to generate an up-to-date version and then go through the steps to understand what choices are being made. Also we don't want to maintain another copy of the project.

**Comment by dlaptin** [comment]
@SteveSandersonMS You are right, ASP.NET Core version was 2.0, while dotnet version was 2.1. This is what confused me.
Also, the command "dotnet new angular -o my-new-app" completed successfully, so I was thinking everything is fine and continue to follow the guide.

Thank you for your help.

**Comment by SteveSandersonMS** [comment]
No problem - glad we managed to explain it :)

**Comment by torontom** [comment]
it's a confuse document that does not work!!
