### ISSUE TITLE
Redirect or make the note at the top a warning

### ISSUE THREAD

**Issue by jongalloway** [aspnet/Docs#8445]
The top Google search docs result for "ASP.NET Core 2FA" points to the "Two-factor authentication with SMS" doc. Since SMS based 2FA is now not the recommended solution as SMS based 2FA is easily impersonated. Is it possible to redirect, or at least make the disclaimer at the top of the page recommending TOTP a warning? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7af94e25-52f5-9f7e-33e2-67f223c7472c
* Version Independent ID: 344f2974-548c-9449-c892-5622063892fe
* Content: [Two-factor authentication with SMS in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/2fa?view=aspnetcore-1.1)
* Content Source: [aspnetcore/security/authentication/2fa.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/2fa.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jongalloway we can't redirect this page. It starts out as:

Two factor authentication (2FA) authenticator apps, using a Time-based One-time Password Algorithm (TOTP), are the industry recommended approach for 2FA. 2FA using TOTP is preferred to SMS 2FA. For more information, see [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](xref:security/authentication/identity-enable-qrcodes) for ASP.NET Core 2.0 and later.

I could make that a warning box, but that probably won't change search results.
