### ISSUE TITLE
Error after Update-Database command

### ISSUE THREAD

**Issue by williab3** [aspnet/Docs#8446]
After I enter the Update-Database command in the PMC I get the following error:
CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\mrwilMvcMovieContext-5dda2acf-f45e-4b88-bcfc-3fcd49610910.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
I'm stuck here. Where did I go wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1#add-ef-tooling-and-perform-initial-migration)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@williab3  see https://github.com/aspnet/EntityFramework6/issues/384
Do you have the latest released VS and .NET Core SDK?

cc @ErikEJ

**Comment by williab3** [comment]
I have all of the updates. How do I verify that I have the latest versions?

**Comment by Rick-Anderson** [comment]
For VS  **Help > Check for Updates**

For the SDK
`dotnet --version`
and compare to the latest version

**Comment by spasmsagain** [comment]
Suggest you look at SQL Server update
https://support.microsoft.com/en-us/help/4342123/cumulative-update-10-for-sql-server-2017 
Works for all SQL Server versions (including Express)

I had same problem and the cumulative upgrade (CU 10) fixed the issue and code ran fine.
