### ISSUE TITLE
Possible punctuation typo

### ISSUE THREAD

**Issue by jwatkin** [aspnet/Docs#8451]
Stylistically, shouldn't this page title not end with a "period"?
[Sorry for the relative insignificance of this question. Thank you for all of the great docs.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jwatkin From the MS style manual ...

> Skip end punctuation on titles, headings, subheads, UI titles, and items in a list that are three or fewer words. Save the periods for paragraphs and body copy.

Some punctuation is allowed, mostly under limited conditions.

**Comment by scottaddie** [comment]
@guardrex Markdownlint flags the period as problematic. I'll take care of it.

**Comment by guardrex** [comment]
The first level heading had a period. To make the title match, it was copied-and-pasted to the title of the topic. I don't think it was done on purpose.

**Comment by scottaddie** [comment]
Thank you for reporting this, @jwatkin!
