### ISSUE TITLE
serviceProvider.GetService<IRelationalDatabaseCreator>() returns null exception

### ISSUE THREAD

**Issue by huytnd** [aspnet/Docs#846]
I follow this tutorial (http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html) and get the null exception.
![null_exception](https://cloud.githubusercontent.com/assets/2102905/12063064/dbc548ea-afda-11e5-8d53-2b47d8a2f4b1.jpg)
I use EF 7 RC1 final, dnx46

**Comment by ShaneYu** [comment]
I get this very same issue, but I am using EF 7 RC1 final with DNX451.

**Comment by ShaneYu** [comment]
For now I have replaced the if statement highlighted in @huytnd screenshot with the following; note this may not be the correct way to do it, but it works.

`if (context.Database.EnsureCreated())`

**Comment by shirhatti** [comment]
This tutorial is out of date and we plan to remove it.
You should refer to https://docs.asp.net/projects/mvc/en/latest/getting-started/first-mvc-app/index.html

**Comment by huytnd** [comment]
Update the correct link: https://docs.asp.net/projects/mvc/en/latest/getting-started/first-mvc-app/

**Comment by huytnd** [comment]
I've just found out that the content on these link is the same:
https://docs.asp.net/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html
http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html

**Comment by danroth27** [comment]
#591
