### ISSUE TITLE
Describe new client code generation features (planned for 2.2 Preview 3)

### ISSUE THREAD

**Issue by dougbu** [aspnet/Docs#8460]
## General
https://docs.microsoft.com/en-ca/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.1 covers the current state of client code generation in ASP.NET Core web sites. However, we're working to give customers simple ways to annotate their project files for automated code generation during every build (as source API descriptions change) and that should also be documented.

Note tooling for the new experience isn't going to happen immediately. The initial documentation should focus on manual edits to .csproj files.

## Issues with Existing Topics
Does not cover work described in aspnet/Mvc#4947 and its sub-issues.

### CC
@glennc

**Comment by Rick-Anderson** [comment]
Copied to #8462
