### ISSUE TITLE
Method not found: 'Void Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations..ctor(Microsoft.EntityFrameworkCo re.Design.Internal.IOperationReporter, System.Reflection.Assembly, System.Reflection.Assembly)'

### ISSUE THREAD

**Issue by Jreye039** [aspnet/Docs#8463]
I've added several package references in order to get the project to scaffold however I am still getting errors. I've spent hours trying to get this to work so I'd really appreciate any help you can offer. I'll post a reply to this with screenshots of my added package references as well as the error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3acf0cee-ea0e-b1ca-d239-a8f2bb465f5b
* Version Independent ID: 20f61d94-ae6a-af54-e089-dc6be40182a0
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/adding-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Jreye039** [comment]
kj

**Comment by Rick-Anderson** [comment]
@Jreye039  sorry, this tutorial is out of date. It looks like #8304 solved the problem for you. I hope to get this updated in the next month.
