### ISSUE TITLE
Update tutorials/razor-pages for 2.1

### ISSUE THREAD

**Issue by tiagodenoronha** [aspnet/Docs#8466]
The current document link says this guide is for 2.1, yet details the procedure for ASP.NET Core 2.0 (such as "Add tool reference for Microsoft.EntityFrameworkCore.Tools.DotNet to the second &lt;ItemGroup&gt;". ASP.NET Core 2.1 has this.)
I will open my first PR if you want to update this document, and would be more than glad to receive your feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c4871-adc3-0d13-6f20-6f6ac1f65e91
* Version Independent ID: ea1742b3-808b-d449-3308-6847a9f339f9
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@TNoronha  thanks. This doc is scheduled to be updated in the next month and we'll take care of that.
