### ISSUE TITLE
How to prevent XSS in ASP.NET Core 2.1?

### ISSUE THREAD

**Issue by shapeh** [aspnet/Docs#8467]
In ASP.NET Core we do something like this:

&lt;form...&gt;
&lt;label asp-for="Name"&gt;&lt;/label&gt; * &lt;span asp-validation-for="Name"&gt;&lt;/span&gt;
&lt;input asp-for="Name" autocomplete="on" /&gt;
&lt;input type="submit" value="Sign up and save to database" /&gt;
&lt;/form&gt;

If user enters something like &lt;script&gt;alert('Greetings from Evil Hacker');&lt;/script&gt; in the input box, ASP.NET Core does nothing to prevent this. NET 4.x automatically detects stuff like this and prevents the submission.

Is there a directive for web.config, startup.cs or similar file to prevent submission - or do we have to manually remove &lt; and &gt; from all inputs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c64844-bd39-46c9-8b52-192834fa625a
* Version Independent ID: 94f92690-9791-a4eb-9256-30a497afccd1
* Content: [Prevent Cross-Site Scripting (XSS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/cross-site-scripting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cross-site-scripting.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@shapeh  per the article:

Never put untrusted data into your HTML input, unless you follow the rest of the steps below. 

>NET 4.x automatically detects stuff like this and prevents the submission.

.NET 4.x is not as secure as following the rules in this article.
