### ISSUE TITLE
Sample is missing .sln file and doesn't build

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8468]
https://github.com/aspnet/Docs/tree/master/aspnetcore/signalr/dotnet-client/sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1#error-handling-and-logging)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@anurse  can you get this sample working? cc @tdykstra

**Comment by anurse** [comment]
I don't have the bandwidth to look at it right now

**Comment by Rick-Anderson** [comment]
@BrennanConroy @mikaelm12 do you know who can get the sample download working? It's not urgent but we'd like to have a working sample.

**Comment by Rick-Anderson** [comment]
5 K PV last month. Customer comment
>it dos not test yet because url address wrong and its deffrent in dot net core 2.1

**Comment by scottaddie** [comment]
@Rick-Anderson I see the problem. Working on it right now.
