### ISSUE TITLE
Update "Migrating Configuration From ASP.NET MVC 5 to MVC 6" for RC1

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Docs#847]
This doc still references Beta 8. I'll be submitting a PR within the next day to reflect the changes made in RC1.

**Comment by Rick-Anderson** [comment]
Are you looking at the version I just published for RC1?

**Comment by scottaddie** [comment]
@Rick-Anderson I used [this doc](https://docs.asp.net/projects/mvc/en/latest/migration/migratingfrommvc5.html) (which has been updated for RC1) as a starting point for the sample app I added for [this doc](https://docs.asp.net/projects/mvc/en/latest/migration/migratingconfig.html) (which was referencing Beta 8).

**Comment by Rick-Anderson** [comment]
Looks good. Closing this issue and I'll just work with PR https://github.com/aspnet/Docs/pull/848
