### ISSUE TITLE
Adding component to React Redux ASP.NET Core React template

### ISSUE THREAD

**Issue by KevinBurton** [aspnet/Docs#8471]
I am trying to add components to my simple test project and I am getting an error (squiggly red line) that indicates:

[ts]
Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes&lt;TitleDescription&gt; & Readonly&lt;{ children?: ReactNod...'.
  Type '{}' is not assignable to type 'Readonly&lt;TitleDescriptionProps&gt;'.
    Property 'itemId' is missing in type '{}'.

I am having a hard time tracing where the type {} is defined.

Thank you.

Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7264db1b-55ec-e419-d2c4-bd4fe64922a2
* Version Independent ID: 720995d2-006a-3573-4868-d253c8a2acc7
* Content: [Use the React-with-Redux project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react-with-redux?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa/react-with-redux.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react-with-redux.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Moved to https://github.com/aspnet/Templating/issues/750.
