### ISSUE TITLE
Possible scaffolding problem?

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8473]
I realize that this is slightly outside the context of this demo, however, I have come across the following.
I would like to implement a 'soft delete' on a field (ie: hide it if 'true'). 
In the MODEL, the field is scripted as 
public bool Obsolete { get; set; }

Now when I try to create a new CRUD page using either the Razor or MVC page, (using the scaffold tool) then the both the resulting EDIT and CREATE views are generated as
            &lt;div class="form-group"&gt;
                &lt;div class="checkbox"&gt;
                    &lt;label&gt;
                        &lt;input asp-for="AdmbuildingType.Obsolete" /&gt; @Html.DisplayNameFor(model =&gt; model.Obsolete)
                    &lt;/label&gt;
                &lt;/div&gt;
            &lt;/div&gt;
But this produces a CS1061 error when I try to build the solution.
I am thinking that you might want to update the scaffolding engine to fix the problem.
In the meantime though, how do I fix this myself?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1#common-errors)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by lm28** [comment]
While you contemplate this problem....is there a reason why the scaffolding engine cant also generate the chtml.cs scripts so the user does not need to edit them as suggested by this article.  I have 150+ admin (lookup/refence) tables in my solution. Having the scaffold engine generate a more appropriate code would be a real time save.

**Comment by Rick-Anderson** [comment]
@lm28 can you write the simplest possible sample that reproduces the problem. Put the sample on a public gitHub. 

@seancpeters once @lm28  has the repo, should he open the issue at https://github.com/aspnet/Scaffolding/issues ?

> so the user does not need to edit them as suggested by this article. 
Where does it say that?

**Comment by seancpeters** [comment]
@Rick-Anderson @lm28 - Yes, please open an issue in aspnet/scaffolding. Or we could move this issue there. Thanks!

**Comment by lm28** [comment]
I have submitted it to Scaffolding Issues as requested by @seanpeters : issue No 876
