### ISSUE TITLE
System.Runtime.Caching?

### ISSUE THREAD

**Issue by StingyJack** [aspnet/Docs#8478]
Why use this asp.net specific caching mechanism over System.Runtime.Caching?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Cache in-memory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
.NET Framework only. I wildly guess that it couldn't be made xplat for Core apps, but you'd need to ask one of the engineers (open the question on [aspnet/Home issues](https://github.com/aspnet/Home/issues), where they'll see it). You could target netfx in a Core app and use it that way.

**Comment by StingyJack** [comment]
I'm asking because I tasked someone with converting a library that used the netfx system.runtime.caching to netstandard, and they pointed out pages like this that use an asp.net specific caching. The library would be used by non-asp.net core callers, so this one didn't seem correct. 

It should be available now for both framework sets https://github.com/dotnet/corefx/issues/14529

**Comment by guardrex** [comment]
*I see!* :eyes: I only looked at the API browser ... not the package. https://www.nuget.org/packages/System.Runtime.Caching/

@danmosemsft can you comment? We don't currently doc `System.Runtime.Caching` for Core. I imagine our main thrust will remain `Microsoft.Extensions.Caching.Memory`/`IMemoryCache`, but what about coverage for `System.Runtime.Caching`? Are you expecting coverage? If so, what type of coverage?

**Comment by KKhurin** [comment]
> Why use this asp.net specific caching mechanism over System.Runtime.Caching?

The motivation for porting System.Runtime.Caching to Core was mainly to maintain as much API compatibility with the full .NET framework as possible. Plus (unlike core aspnet/caching) S.R.Caching has a notion of physical memory pressure allowing one to automatically trim the cache size in the face of limited memory resources (which currently only works on Windows only - please vote for #https://github.com/dotnet/corefx/issues/26532 if you need this on Linux/iOS). It is also capable of tracking the size of the cache (please vote for #https://github.com/dotnet/corefx/issues/26538 if you need this functionality in Core - all the wiring is already in place both in GC and the cache but the sized ref GC handle itself isn't exposed in Core).

If you don't need either of 3 features (compatibility, memory pressure, and in the future cache size) then aspnet caching might be a better option as it is more lightweight. Although as far as I am aware nobody ever compared their performance characteristics (both in terms of speed and allocation patterns).


> Are you expecting coverage? If so, what type of coverage?

Most of the API documentation should be exactly the same as in the desktop framework. The only difference is a few missing features (which are currently "documented" via bugs).

**Comment by guardrex** [comment]
Thanks @KKhurin 

@danroth27, would you like `System.Runtime.Caching` covered in aspnet/Docs? If so, how would u like it covered (section of an existing topic or new topic)?

**Comment by guardrex** [comment]
Cross-ref to our existing aspnet/dotnet docs on the subject:

* https://docs.microsoft.com/aspnet/whitepapers/aspnet4/overview#object-caching-and-object-caching-extensibility
* https://docs.microsoft.com/dotnet/framework/performance/caching-in-net-framework-applications

The API doesn't show for .NET Core 2.1, which is what I hit when I first looked ...

https://docs.microsoft.com/dotnet/api/system.runtime.caching?view=netcore-2.1
https://github.com/dotnet/dotnet-api-docs/tree/master/xml/System.Runtime.Caching

**Comment by danroth27** [comment]
@davidfowl Thoughts on usage of System.Runtime.Caching with ASP.NET Core?

**Comment by guardrex** [comment]
I've added a section in the caching topic on #8550.

Note that `System.Runtime.Caching` isn't currently marked for .NET Standard 2.0 ...

https://docs.microsoft.com/dotnet/api/system.runtime.caching?view=netcore-2.1
