### ISSUE TITLE
JQuery and XSS

### ISSUE THREAD

**Issue by jamesjardine** [aspnet/Docs#8482]
I know the focus is on the API, but when I put this together and added the JQuery front end, I noticed that the todo name is not being encoded and is vulnerable to cross-site scripting. This has to do with the technique of just building up the table's rows using concatenation and appending it as HTML. While not as smooth, something like this may work to build that table and encode the name.

var tr = $('&lt;tr&gt;');
$('&lt;td&gt;&lt;input disabled="true" type="checkbox" ' + checked + '&gt;&lt;/td&gt;').appendTo(tr);
var td = $('&lt;td&gt;');
td.text(item.name);
td.appendTo(tr);
$('&lt;td&gt;&lt;button onclick="editItem(' + item.id + ')"&gt;Edit&lt;/button&gt;&lt;/td&gt;' + 
'&lt;td&gt;&lt;button onclick="deleteItem(' + item.id + ')"&gt;Delete&lt;/button&gt;&lt;/td&gt;').appendTo(tr);
tr.appendTo($('#todos'));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@jamesjardine  thanks.

**Comment by Rick-Anderson** [comment]
@scottaddie 	please review. Should I bump this up to `@blowdart` ?

**Comment by scottaddie** [comment]
@Rick-Anderson Let's have Barry weigh in on this.

**Comment by Rick-Anderson** [comment]
@blowdart 	customer discovered  vulnerable to cross-site scripting.  Please comment and set priority.

**Comment by blowdart** [comment]
Oh dear. Yes, you could probably optimise a bit more;

```
        var $tr = $('<tr>').append(
            $('<td>').text(...),
            $('<td>').text(item.name),
            $('<td>').text(...)
```

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan can you fix this JavaScript?

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson sure! @blowdart already provided the solution. I'll fix the `getdata()` method by tomorrow.

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson @blowdart  @jamesjardine please check  https://github.com/aspnet/Docs/pull/9415

**Comment by scottaddie** [comment]
Fixed in https://github.com/aspnet/Docs/pull/9415.
