### ISSUE TITLE
AddJsonHubProtocol should be AddJsonProtocol

### ISSUE THREAD

**Issue by wanton7** [aspnet/Docs#8490]
Examples currently use method AddJsonHubProtocol that doesn't exist. Should be AddJsonProtocol instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8cdc99-48bb-3266-05bb-eda98f59f2e2
* Version Independent ID: 66d252c3-6300-7e28-9aa0-ef2ff66e7a76
* Content: [ASP.NET Core SignalR configuration](https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by lsiddiquee** [comment]
I have been pulling my hair for a while now with this. Finally went to the github repo to see that it is renamed. Please fix this ASAP.

**Comment by tdykstra** [comment]
@wanton7  @lsiddiquee  Thanks for reporting that!  I've fixed it.
