### ISSUE TITLE
Issues setting up Localization in ASP.NET Core razor App - NO MVC!

### ISSUE THREAD

**Issue by JNickVA1** [aspnet/Docs#8491]
I have been trying, without success, to create an ASP.NET Core 2.1 Razor web app that uses localization and I keep running into problems trying to follow the steps listed on this page because I am writing a Web App in Razor pages, NOT a MVC app. The examples all use the _SelectLanguagePartial cshtml which depends on a Home Controller. (I'm referring to the Localization example in the docs and to the Entropy sample code.) I have tried several different ways to accomplish the Localzation, including adding a Home Controller to my project that is only used for the POST of the form from the _SelectLanguagePartial cshtml. Nothing works. Please! Where can I find out how to Localize a non-MVC Razor app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg  please review.

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
Have a look to my [LanguageSwitcherTagHelper](https://github.com/hishamco/LanguageSwitcherTagHelper), but still everything should work as expected, surprisingly I'm working on a PR in [SimplCommerce](https://github.com/simplcommerce/SimplCommerce) that include a modified version of the `_SelectLanguagePartial`  https://github.com/simplcommerce/SimplCommerce/pull/554

If you still have the issue create a minimal repository and share it with us

**Comment by JNickVA1** [comment]
I will upload a simple app soon, but the one main issue I raised has not been mentioned yet by anyone, and that is the fact that the sample code uses a Controller which does not exist in a non-MVC web app.

**Comment by JNickVA1** [comment]
Added a test repo at: https://github.com/JNickVA1/TestCoreRazorLocalization

**Comment by hishamco** [comment]
@JNickVA1 I just have a look into your code, what's confuse my is why you are using `Controller`?!! you can use `PageModel` instead because you are in RazorPages not MVC

One more thing I knew you will ask for is **In which PageModel should I put the set culture code?** simply you can move the language switcher into a partial or taghelper, create a `PageModelBase` that all the page model(s) will inherit from, finally put your code on a post handler

**Comment by JNickVA1** [comment]
OK, I understand what you're saying - I think. I created a PageModel base class that all of my PageModels inherit from and put the code for the SetLanguage into a Post method in the PageModelBase class. My problem now is that I get a compile error in the partial because the SetLanguage method is not defined because there is no @model defined in the partial. and, therefore, I cannot access the method by name.

**Comment by hishamco** [comment]
> I get a compile error in the partial because the SetLanguage method is not defined 

The `Setlanguage` should be used as an action for the form

> because the Context is undefined

The Context should be there, please again refer to https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.WebHost/Views/Shared/_SelectLanguagePartial.cshtml

> If this is the preferred may to write web apps now, then why are the examples written for MVC???

Razor Pages is not the preferred way, each one is suitable for certain cases, if you have a page centeric application, Razor Pages will be a better choice

**Comment by JNickVA1** [comment]
I have incorporated many of the great ideas from the SimplCommerce code as well as from comments here and on StackOverflow and I am still having an issue with localized string in my _Layout.cshtml file. This is the one remaining roadblock. Again, it looks like this would not be an issue at all IF my app was written using ASP.NET Core MVC, but it is written in ASP.NET Core Razor. Any help on this last problem would be greatly appreciated!

**Comment by hishamco** [comment]
Is the above repo reproduce the issue? Coz still I'm surprised what is not working with you

**Comment by JNickVA1** [comment]
Like I said, everything is working now for my individual pages and the SetLanguage, which is in a base PaageModel class. The only thing I can't seem to get working is the localization in the _Layout.cshtml file. The repo has been updated to the current code.

**Comment by hishamco** [comment]
Let me have a look to your repo

**Comment by hishamco** [comment]
https://github.com/JNickVA1/TestCoreRazorLocalization page is not found 😞

**Comment by JNickVA1** [comment]
Oops! Sorry, it was renamed. https://github.com/JNickVA1/CoreMasterTemplate

**Comment by hishamco** [comment]
I Checked the sample, with dropping some unrelated dependencies, seems everything is work fine in layout page, I tried with French culture, regarding `_Layout.zh.resx` be sure you rename it to `_Layout.zh-CN.resx` or use the fallback option

**Comment by JNickVA1** [comment]
I appreciate all of your help. I finally got the localization working. The main culprit was that I did not have the following code correct:
			services.AddMvc()
				// Add support for finding localized views, based on file name suffix, e.g. Index.fr.cshtml
				.AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
				// Add support for localizing strings in data annotations (e.g. validation messages) via the
				// IStringLocalizer abstractions.
				.AddDataAnnotationsLocalization();

**Comment by hishamco** [comment]
FYI I didn't touch any location setup, except naming the resources properly, anyhow I'm glad that your issue is fixed

Please close the issue if no further action needed

**Comment by JNickVA1** [comment]
I do have one other issue that I just found when I tested the app in Chrome - The Language/Culture change made via the dropdown language selector doesn't work. It only appears to work in Edge and IE. Am I missing something that is browser-specific that you can think of?

**Comment by hishamco** [comment]
Use a hot refresh before testing, perhaps it's a caching issue

**Comment by JNickVA1** [comment]
Not a caching issue, it appears. And I was wrong about it working correctly in IE. It only works in Edge. In Chrome and IR the page refreshes when I select one of the supported languages (fr and zh-CN) but the dropdown reverts to English and the verbiage on the page never switches to the selected language. 

The Localization sample app works correctly in all 3 browsers, so I'm thinking it must be due to something in my _SelectLanguagePartial form code:
<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-page-handler="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
	    <label asp-for="@requestCulture.RequestCulture.UICulture.Name">@Localizer["Language:"]</label> 
	    <select name="culture" onchange="this.form.submit();"
          asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
        </select>
    </form>
</div>
 Where the base PageModel method for Set:anguage is:
	public class PageModelBase : PageModel
	{
		[HttpPost]
		public IActionResult OnPostSetLanguageAsync(string culture, string returnUrl)
		{
			Response.Cookies.Append(
				CookieRequestCultureProvider.DefaultCookieName,
				CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
				new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
			);

			return LocalRedirect(returnUrl);
		}
	}

**Comment by JNickVA1** [comment]
The original issue has been resolved.

**Comment by wstaelens** [comment]
I only got it working by this:
https://stackoverflow.com/a/66411764/187650 

I had to change SameSiteMode.None to Unspecified.
```
services.Configure<CookiePolicyOptions>(options =>
        {
            // This lambda determines whether user consent for non-essential 
            // cookies is needed for a given request.
            options.CheckConsentNeeded = context => true;
            // requires using Microsoft.AspNetCore.Http;
            //options.MinimumSameSitePolicy = SameSiteMode.None;
            options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
        });
```
