### ISSUE TITLE
componentWillMounis depricated

### ISSUE THREAD

**Issue by Carlcro** [aspnet/Docs#8503]
This template use a lot of componentWillMount which is depricated and should not be used. Instead use the constructor for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7264db1b-55ec-e419-d2c4-bd4fe64922a2
* Version Independent ID: 720995d2-006a-3573-4868-d253c8a2acc7
* Content: [Use the React-with-Redux project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react-with-redux?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa/react-with-redux.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react-with-redux.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
Thank you for reporting this, @Carlcro. I've moved the issue to https://github.com/aspnet/Templating/issues/739, since it's an engineering concern.
