### ISSUE TITLE
Two missing links

### ISSUE THREAD

**Issue by user135711** [aspnet/Docs#8506]
The two "(more info)" links [here ](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-2.1)are unlinked: 

> For instance, this package contains a simple "instantiate the system pointing at a specific key storage directory with no dependency injection setup" API (more info). It also contains extension methods for limiting the lifetime of protected payloads (more info).

**Comment by guardrex** [comment]
Wow ... yeah. That goes way, way back. That goes back to the Read the Docs import of the content. I'll take of that this evening. Thanks for flagging it.
