### ISSUE TITLE
Cryptography Errors

### ISSUE THREAD

**Issue by molund** [aspnet/Docs#8509]
Using ApplicationPoolIdentity, I was getting these cryptography errors in my logs

"System.Security.Cryptography.CryptographicException: The key {0a0a0a0a-0000-0000-aaaa-bbbbccccdddd} was not found in the key ring."

"Error unprotecting the session cookie."

I discovered that this folder did not exist 
 C:\Users\[App Pool Name].IIS APPPOOL\AppData\Local\ASP.NET\DataProtection-Keys

I had to set "Load User Profile" to "True" in the App Pool settings for the folder to appear.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
That approach is covered at: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis#data-protection

... the second option offered is to enable `Load User Profile`.

Did you see that section?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
