### ISSUE TITLE
Use DateTime.UtcNow in distributed caching topic sample

### ISSUE THREAD

**Issue by lundmikkel** [aspnet/Docs#8514]
In the server start time example, you are using `DateTime.Now` to log the server's time at start up. This should at least be `DateTime.UtcNow`, unless you want the time zone of the server to affect the number (spoiler alert: you don't).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Work with a distributed cache in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @lundmikkel. I guess that given this is just a demonstration app that a local time was used to make at-a-glance eyeball comparisons to the dev's local machine's time. Sure, we can go UTC with it.
