### ISSUE TITLE
Configuration article needs to be updated for RC1

### ISSUE THREAD

**Issue by balachir** [aspnet/Docs#852]
Docs > Fundamentals > Configuration

- [x] Update link to sample code
- [x] Update sample code and doc for API changes (eg: MemoryConfigurationSource is now MemoryConfigurationProvider)

**Comment by balachir** [comment]
I can pick this one up actually, I'm working on the changes

**Comment by Rick-Anderson** [comment]
@balachir great. Looking forward to your PR.
