### ISSUE TITLE
YouTube version

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8527]
[YouTube version](https://www.youtube.com/watch?v=F0SP7Ry4flQ&feature=youtu.be)
by @krchome 
see #8522

If you find this video helpful, leave a comment or 👍 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by daveabrock** [comment]
I might be able to help with these - what is your intention? To link to it? Add content to the Docs based on what is in the videos?

**Comment by Rick-Anderson** [comment]
@daveabrock 	 this discussion issue is just to surface the video. No work needed. I should probably make the more clear.

**Comment by ManavDev** [comment]
Hello Rick, 

I created the project (File > New > Core and selected core 2.2) but the project structure looks different than yours. It created Controllers, Models, and Views but yours has just Page folder. Please help.

**Comment by xXmemestarXx** [comment]
Mine is diffrent to. 

Its probaly because it has been updated since

**Comment by Rick-Anderson** [comment]
> It created Controllers, Models, and Views but yours has just Page folder. Please help.

You selected the wrong template.
