### ISSUE TITLE
What is wrong with these pages?

### ISSUE THREAD

**Issue by serhioV** [aspnet/Docs#8528]
the links like https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-2.1 are not displayed with the content, the "previous" and "next" links always displays the same content to go to RazorPages, but what if I don't want to read the razor pages? Where is the article content?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 912ebaa6-721f-c8b3-7b3a-7f16d4c24360
* Version Independent ID: b6135ff6-897f-c5fa-c61d-d9fad4ee9acd
* Content: [ASP.NET Core MVC with EF Core - Data Model - 5 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/complex-data-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/complex-data-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/complex-data-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
dup of #8529
