### ISSUE TITLE
We don't see the content of the article!!!

### ISSUE THREAD

**Issue by serhioV** [aspnet/Docs#8529]
Please, I am in Chrome, I don't see anything there but the "We recommend the Razor Pages tutorial over the MVC version." where is the content? The article content is not visible to readers !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e2038b-fa1b-897c-32ee-7173c7d1d909
* Version Independent ID: 000c5a97-c1b2-9a48-289d-83ec4f0c0c98
* Content: [ASP.NET Core MVC with EF Core - Sort, Filter, Paging - 3 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/sort-filter-page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
Per the article
This tutorial has not been upgraded to ASP.NET Core 2.1. The ASP.NET Core 2.0 version of this tutorial is available by selecting ASP.NET Core 2.0 above the table of contents or at the top of the page:

**Comment by serhioV** [comment]
> Per the article
> This tutorial has not been upgraded to ASP.NET Core 2.1. The ASP.NET Core 2.0 version of this tutorial is available by selecting ASP.NET Core 2.0 above the table of contents or at the top of the page:

why then there is an "ASP.NET Core 2.1" available in the combo box for that article to confuse people?
