### ISSUE TITLE
Documentation to 'custom user data to Identity in an ASP.NET Core project' is missing steps.

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [aspnet/Docs#8530]
I'm using Visual Studio 15.8.2 - 
dotnet --version = 2.1.401

1) Highlight the four 'WebApp1User' changes in IndexModel 

        private readonly UserManager<WebApp1User> _userManager;
        private readonly SignInManager<WebApp1User> _signInManager;

            UserManager<WebApp1User> userManager,
            SignInManager<WebApp1User> signInManager,

2) Highlight the class name 'WebApp1User' in Register.cshtml.cs

	 var user = new WebApp1User {

3) Add the four 'WebApp1User' changes in RegisterModel that aren't mentioned

        private readonly UserManager<WebApp1User> _userManager;
        private readonly SignInManager<WebApp1User> _signInManager;

            UserManager<WebApp1User> userManager,
            SignInManager<WebApp1User> signInManager,

Registering works, but now when I go to /Identity/Account/Manage

Next, you state 'Add a migration for the custom user data'.  That does nothing yet, you'll generate an empty migration.

You will need to first change ApplicationDbContext.cs by adding the name of the new class after IdentityDbContext

    public class ApplicationDbContext : IdentityDbContext<WebApp1User>

Then the migration will produce the correct results.

But that only gets me to the next error

InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.UserManager`1[WebApplication15.Areas.Identity.Data.WebApp1User]' while attempting to activate 'WebApplication15.Areas.Identity.Pages.Account.RegisterModel'.

So I'm thinking I need to change startup.cs.  And use 'WebAppUser1' as the default identity

            services.AddDefaultIdentity<WebApp1User>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.

At this point, there's a LOT more to do to the framework before this will work...  

Can you please test your walkthru and fix the documentation for us?  It's no longer working for v2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@ZombiesWithCoffee  thanks for reporting this. I'll try to get this tested/fixed ASAP.

**Comment by Rick-Anderson** [comment]
@ZombiesWithCoffee  did you follow VS or CLI instructions.

From comment hub:
App files and code are not appearing as described here. In particular scaffolding does not generate this" "Update the IdentityUser derived class with custom properties. If you named your project WebApp1, the file is named Areas/Identity/Data/WebApp1User.cs."

**Comment by Rick-Anderson** [comment]
@ZombiesWithCoffee  the download works fine. I did remove the version from M.A.App in the project file.

**Comment by ZombiesWithCoffee** [comment]
I'm going to chalk this up to overthinking the issue.  Your documentation is 100% correct.  I was trying to add user fields to a pre-existing project and the step that I was missing was changing the _LoginPartial.cshtml

Interesting though, your sequence to create a project is superior to using the 'Authentication' feature.  Your sequence adds the setup to the IdentityHostingStartup, where the base project creation adds it all to Startup.cs .  I'm going to move those lines to my IdentityHostingStartup.cs 

Sorry for the confusion.  I had a very busy week and wasn't thinking clearly.

**Comment by Linshiqi** [comment]
@ZombiesWithCoffee  I'm suffering this problem too,  I will be grateful if  you would  write a more specific document for how to add user fields to a pre-existing project?

**Comment by javkhalidskipton** [comment]
further to this,
i did the following steps to get it working
IdentityHostingStartup.cs 
change Identity user to WebApp1User as shown below
services.AddDefaultIdentity<WebApp1User>()
                    .AddEntityFrameworkStores<DataContextContext>();

and in login partial
@inject SignInManager<WebApp1User> SignInManager
@inject UserManager<WebApp1User> UserManager
then the project works perfectly. no errors.

**Comment by Squad7** [comment]
@javhalidskipton can you link your code in more detail? It's a little confusing to follow
