### ISSUE TITLE
Why await?

### ISSUE THREAD

**Issue by mattfrear** [aspnet/Docs#8531]
Does the example RequestCultureMiddleware's InvokeAsync method need to `await` the result? Could it be simplified by dropping the async and await keywords, or is it important that it awaits?

```csharp
        public Task InvokeAsync(HttpContext context)
        {
           <snip>
            // Call the next delegate/middleware in the pipeline
            return _next(context);
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I suspect it will block, thus not be a preferable middleware architecture. All of the middleware examples we've received/seen from engineering are async.

**Comment by mattfrear** [comment]
Ok, thanks.
