### ISSUE TITLE
Create Backend services for native mobile apps update

### ISSUE THREAD

**Issue by smartprogrammer93** [aspnet/Docs#8533]
This page contains code that uses old conventions

needs to be updated to the latest asp.net core web api conventions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdbdf1ed-c52a-3be8-1f41-aecbdab0883b
* Version Independent ID: d06996cc-14aa-96e2-fd62-9d5bbc059107
* Content: [Create backend services for native mobile apps with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mobile/native-mobile-backend.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mobile/native-mobile-backend.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @smartprogrammer93 ... Thanks for commenting. We have it on the sample update tracking issue #5495. We'll get to it as soon as we can.
