### ISSUE TITLE
Cannot explicitly instantiate a SignalR hub

### ISSUE THREAD

**Issue by gaazkam** [aspnet/Docs#8537]
From this article:

"Services can be resolved by two mechanisms:

*    IServiceProvider

*    ActivatorUtilities – Permits object creation without service registration in the dependency injection container. ActivatorUtilities is used with user-facing abstractions, such as Tag Helpers, MVC controllers, SignalR Hubs, and model binders."

The way I understood this was that, if it was necessary, I could explicitely instantiate a SignalR hub via Activator utilities.

So I tried:

    using (var scope = scopeFactory.CreateScope())
    {
        var hub = ActivatorUtilities.CreateInstance<ChatHub>(scope.ServiceProvider);
        // do stuff with hub
    }

Unfortunately, it seems that this yields the hub in an unusable state; hub.clients and other important properties are null, so I can't for example call

    hub.Clients.All.SendAsync("something", args)

Trial and error showed me that:

    using (var scope = scopeFactory.CreateScope())
    {
        var hub = scope.ServiceProvider.GetRequiredService<IHubActivator<ChatHub>>().Create();
        // do stuff with hub
    }

This again leads to creating an unusable hub for the same reasons as above;

    using (var scope = scopeFactory.CreateScope())
    {
        var hubContext = scope.ServiceProvider.GetRequiredService<IHubContext<ChatHub>>();
        // do stuff with hubContext
    }

Now this is usable - I can call hubContext.Clients.All.SendAsync("something", args) and similar stuff and this works - BUT this is not a full hub so I have no access to private methods I have defined in ChatHub and I also don't have access to services injected in ChatHub's constructor - which is inconvenient but can be worked around;

    using (var scope = scopeFactory.CreateScope())
    {
        var hub = ActivatorUtilities.CreateInstance<ChatHub>(scope.ServiceProvider);
        var hubContext = scope.ServiceProvider.GetRequiredService<IHubContext<ChatHub>>();
        hub.Context = hubContext;
        // do stuff with hub
    }

This fails to compile, but the compilation message hints about an explicit conversion, so I try it:

    using (var scope = scopeFactory.CreateScope())
    {
        var hub = ActivatorUtilities.CreateInstance<ChatHub>(scope.ServiceProvider);
        var hubContext = scope.ServiceProvider.GetRequiredService<IHubContext<ChatHub>>();
        hub.Context = (HubCallerContext)hubContext;
        // do stuff with hub
    }

This throws in the line when the conversion is done.

The way I'm getting the quoted paragraph from this article is that I should be able to explicitely instantiate a SignalR hub with ActivatorUtilities.CreateInstance. Is this the case? If so, how exactly? If I might suggest, should the documentation be more precise with regard to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#call-services-from-main)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by BrennanConroy** [comment]
Hubs can't be instantiated by users. Should probably remove that part from this section.

**Comment by davidfowl** [comment]
@gaazkam What are you trying to do? You're not supposed to activate the hub from user code. It's something that the framework activates in as a result of invoking a client method.

**Comment by guardrex** [comment]
> Should probably remove that part from this section.

Thus far, I'll remove "SignalR Hubs" from the passage. Let me know if it requires more than that.

**Comment by gaazkam** [comment]
> 
> 
> @gaazkam What are you trying to do? You're not supposed to activate the hub from user code. It's something that the framework activates in as a result of invoking a client method.

Ouch. That's bad news for me.

There are two use cases where I think this is required for my app.

My app is a multiplayer turn-based game, developed as a hobby project. My problem is that I have to notify playerA when playerB makes their move. Thus I have a GameHub, making a move means that the game clients calls a method on this GameHub which then broadcasts the move for both players and any observers of the game.

But now I have the issue of timers. Whenever playerB fails to make a move within the time alloted for their turn, I must conclude the game and declare playerB the looser. To achieve this, I use System.Timers.Timer.

But once the timer fires off, I must somehow broadcast the message that playerB has run out of time and thus lost the game to all connected clients (players & observers)! Even though no user code could call any method on my hub. Running out of time is a server event, not a client event.

The second use case is similar. I have a chatbox in this game. Now mods can mute unruly users either for 2 hours or indefinitely. Again, if they mute a user for 2 hours, a System.Timers.Timer starts and when it ends, I have to remove the mute and send the user the information that their mute has expired.

In both cases the server has to initiate sending some information to the clients.

In case of mutes, I tried reusing the same hub instance the mod invoked the "Mute" method on. But unfortunately, by the time the timer fires off, this hub instance is unusable - its Context, Clients etc have already been disposed.

In case of mutes, I'm currently using this IHubContext instantiation I mentioned:

    var hubContext = scope.ServiceProvider.GetRequiredService<IHubContext<ChatHub>>();

And it seems to be working. 

In case of game timers, I currently have... a Singleton service that depends on IHubContext<GameHub>. I'm afraid this may not be completely correct (is IHubContext thread safe? Can it be promoted to a singleton?) - but it seems to be working for home testing. I thought I'd repleace this with an actual instantiation of GameHub each time I need to announce that playerB has run out of time and lost the game.

In all those cases I do not know how to implement the required functionality if I'm not supposed to call hub methods from server-side code.

... I feel there still is one more use case. It is a theoretical one, not one I'm currently tackling. But I have feeling in this use case calling hub methods from server side code seems to be even more required.

A game similar to Tribal Wars. In such a game playerA may send armies to attack playerB's villages. But these armies do not attack immediatelly - instead, these armies arrive after a time dependant on the distance between both players' villages. So once the army arrives, again, the server must inform playerB that enemy's army has arrived.

...I understand that it is perfecly well possible that my solution to the problem of handling delayed events (and, once these events happen, announcing this to users) is all wrong. However, I could not find any proper solution until now. If I cannot call SignalR hubs from System.Timers.Timer.Elapsed event handler, then I'm stuck.

Final remark: Some people were suggesting me to use a background task. But then we have the same problem: I'll have to call a SignalR hub method from this background task!

**Comment by gaazkam** [comment]
> 
> 
> Just put the logic elsewhere, outside of the hub then call it from the hub and anywhere else in your application.

Yes of course, but the core problem persists: Once the timer fires off, I must somehow call the hub from the timer's handler because I must inform the players that the time has run out with such and such consequences.

Of course I put game logic outside of hub. So once playerA makes a move and sends their move to the hub, then the hub calls game logic, which returns game updates to the hub, which then broadcasts these updates to all players & observers... But the game logic also starts a timer for playerB's turn and if playerB doesn't make their move promptly and the timer fires off then suddenly I have to call the hub from game logic. How else am I supposed to broadcast the "GameOver, playerB lost" update to players & observers?

**Comment by davidfowl** [comment]
> How else am I supposed to broadcast the "GameOver, time's up, playerB lost" update to players & observers?

By using the `IHubContext<GameHub>` from the game logic. I'm not understanding the difficulty. Some sample code would help.

**Comment by gaazkam** [comment]
> By using the `IHubContext<GameHub>` from the game logic. 

Just one question then - am I allowed to explicitely instantiate `IHubContext<GameHub>` within a timer handler and use it to send messages to all connected clients?

The way I was understanding your previous post was that I was not supposed to do this.

> Some sample code would help.

Okay, here are excerpts from my current code.

1) Game timers:

From BattleHub:

    public class BattleHub : Hub
    {
        private readonly IBattleManager _battleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public BattleHub(IBattleManager battleManager, UserManager<ApplicationUser> userManager)
        {
            _userManager  = userManager;
            _battleManager = battleManager;
        }

        // Player makes a move
        public async Task SendCommand(ulong battleId, int teamNo, string moveTypeName, object[] args)
        {
            Move move = Move.GetMove(moveTypeName, args);
            if(move == null) return; // invalid data from client

            var userInfo = await UserInfo.GetUserInfoAsync(Context, _userManager); // simply stores user's nick, ID & roles
            var res = _battleManager.SendCommand(battleId, userInfo, teamNo, move);
            if(res != null)
                await Clients.Group(Convert.ToString(battleId)).SendAsync("BattleUpdate", battleId, res);
        }

From BattleManager (which is registered as a singleton service):

    public class BattleManager: IBattleManager
    {
        private readonly IServiceScopeFactory _scopeFactory;
        public BattleManager(IServiceScopeFactory scopeFactory)
        {
            _scopeFactory = scopeFactory;
        }
        private var battles = new ConcurrentDictionary<ulong, BattleState>();

        public BattleTurnInfo SendCommand(ulong battleId, UserInfo player, int teamNo, Move command)
        {
            BattleState battleState;
            try
            {
                battleState = battles[battleId];
                return battleState.Update(player, teamNo, command);
            }
            catch (KeyNotFoundException)
            {
                return null;
            }
        }

And finally from BatteState:

    public class BattleState
    {
        private readonly IServiceScopeFactory _scopeFactory; // The same as BattleManager's; passed to BattleState by BattleManager on creation of a new battle
        private System.Timers.Timer _timer;
        private UserInfo[] players; // 2 is the only valid size
        // + other vars such as game boards etc

        public BattleState(IServiceScopeFactory scopeFactory, UserInfo[] players)
        {
            _scopeFactory = scopeFactory;
           this.players = players;
           _timer = new System.Timers.Timer() { Interval = 2 * 60 * 1000, AutoReset = false };
           _timer.Elapsed += async (sender, e) => await TimerRunOutAsync(sender, e);

        public BattleTurnInfo Update(UserInfo player, int teamNo, Move move)
        {
            lock (this)
            {
                if (players[teamNo].Equals(player) && needsInputFromPlayer(teamNo))
                {
                    if(acceptInput(teamNo, move))
                    {
                        _timer.Stop();
                        var ret = advanceTurn();
                        if(!isConcluded())
                            _timer.Start(); // Time for the other player's move starts
                        else
                            removeBattle(); // from ConcurrentDictionary
                    }
                }
            }
        }

        public async Task TimerRunOut(object sender, ElapsedEventArgs e)
        {
            BattleTurnInfo updateToSend;
            lock(this)
            {
                if (isConcluded()) return;
                int inactivePlayer = getTeamNoThatNeedsUserInput();

                teams[inactivePlayer].forceLost = true; // from now on isConcluded will return true
                updateToSend = getInactivePlayerUpdate(inactivePlayer);

                removeBattle();
            }

            using (var scope = _scopeFactory.CreateScope())
            {
                var hubContext = scope.ServiceProvider.GetRequiredService<IHubContext<BattleHub>>();
                await hubContext.Clients.Group(Convert.ToString(battleId)).SendAsync("BattleUpdate", battleId, updateToSend);
            }
            await removeBattleAsync();
        }
    }

Am I allowed to do this? Especially with regard to `using (var scope = _scopeFactory.CreateScope())`?

I'm thinking about removing this ConcurrentDictionary and instead serializing the battle state to the db after each turn and deserializing it back on each request. This is because I was adviced to do so by more experienced programmers.

Now the second sample is much simpler. 2 hour mutes from ChatHub

    public class ChatHub : Hub
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IServiceScopeFactory scopeFactory;
        public ChatHub(ApplicationDbContext db, UserManager<ApplicationUser> userManager, IServiceScopeFactory scopeFactory)
        {
            this.userManager = userManager;
            this.scopeFactory = scopeFactory;
        }

        [Authorize]
        public async Task Mute(string usernameToMute)
        {
            var userInfo = await UserInfo.GetUserInfoAsync(Context, userManager);
            if (!userInfo.Roles.Contains("Mod")) return;

            var mutedUser = await userManager.FindByNameAsync(usernameToMute);
            if(mutedUser != null && (await userManager.AddToRoleAsync(mutedUser, "Muted")).Succeeded)
            {
                var message = $"{usernameToMute} has been muted by {userInfo.Name}.";
                await Clients.All.SendAsync("ReceiveChatMessage", message);
             
                var timer = new System.Timers.Timer () { Interval = 120* 60 * 1000, AutoReset = false };
                timer.Elapsed += async(sender, e) =>
                {
                    using (var scope = scopeFactory.CreateScope())
                    {
                        var hubContext = scope.ServiceProvider.GetRequiredService<IHubContext<ChatHub>>();
                        var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
                        var unmutedUser = await userManager.FindByNameAsync(usernameToMute);
                        if(unmutedUser != null && (await userManager.RemoveFromRoleAsync(unmutedUser, "Muted")).Succeeded)
                        {
                            var unmutedMessage = $"Mute of {usernameToMute} (placed by {userInfo.Name}) has expired.";
                            await hubContext.Clients.All.SendAsync("ReceiveChatMessage", message);
                        }
                    }
                };
                timer.Start();
