### ISSUE TITLE
Additional directories where files are written require Read/Write permissions

### ISSUE THREAD

**Issue by Number5isAlive** [aspnet/Docs#8546]
What does this statement mean?  Application specific directories?  If there are directories that are part of the base set that need Read/Write please list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566f8ed0-217e-5125-b0f7-6d93c3a145c1
* Version Independent ID: 9fa94395-eff8-3b12-c2d5-c1c6d4142378
* Content: [ASP.NET Core directory structure](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/directory-structure?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/directory-structure.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/directory-structure.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It just means any additional directories that *you* need to write to. For example, a network share may require write permission; therefore, *you* will need to make sure the app pool identity has write access to that location.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
