### ISSUE TITLE
What about no Async Work?

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#8553]
What if I don't have any async work to perform?  How should I write my `InvokeAsync` method?

>Warning	CS1998	This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread

```csharp
namespace ViewComponentSample.ViewComponents
{
    public class PriorityListViewComponent : ViewComponent
    {
        public async Task&lt;IViewComponentResult&gt; InvokeAsync(
        int maxPriority, bool isDone)
        {
            var items = new List<Item>{ ... };
            return View(items);
        }
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2902f4-b6fd-ba1c-6762-d7c26f5eb4b9
* Version Independent ID: b5715d72-5f10-bb93-1051-7f06dfa9cde8
* Content: [View components in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-2.0#avoiding-magic-strings)
* Content Source: [aspnetcore/mvc/views/view-components.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/view-components.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Possibly like this ...

```csharp
public async Task<IViewComponentResult> InvokeAsync(int maxPriority, bool isDone)
{
    var items = new List<Item>{ ... };
    return await Task.Run(() => View(items));
}
```

... but that might :boom: or get my picture up in the *Async Programmer's Hall of Shame!* :smile: I haven't had to do that in a real app.

**Comment by scottaddie** [comment]
@spottedmahn Why not make a synchronous method instead? Something like this:

```csharp
namespace ViewComponentSample.ViewComponents
{
    public class PriorityListViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(
            int maxPriority, bool isDone)
        {
            var items = new List<Item>{ ... };
            return View(items);
        }
    }
}
```

**Comment by davidfowl** [comment]
@guardrex nope, don't do that 😄

**Comment by guardrex** [comment]
@scottaddie `IViewComponentHelper` method sig demands a `Task<T>` and a `InvokeAsync` name.

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.iviewcomponenthelper

**Comment by scottaddie** [comment]
@guardrex Thanks for the link. Once we figure this out, let's get it added to the doc. Others are likely wondering the same thing.

**Comment by pranavkm** [comment]
> How can a synchronous ViewComponent be called without IViewComponentHelper or resorting to Task.Run with an async ViewComponent?

`Task.FromResult(someResult)`

**Comment by guardrex** [comment]
Thanks @pranavkm ... I'll place the example using that into the topic.

Thanks @spottedmahn.

**Comment by guardrex** [comment]
One small additional update ... add `Result` to the call to get the output that way ...

```cshtml
@Component.InvokeAsync(nameof(PriorityList), new { maxPriority = 4, isDone = true }).Result
```

**Comment by pranavkm** [comment]
In general, making a blocking call may result in thread starvation and deadlock your server. I wouldn't recommend using it.

**Comment by guardrex** [comment]
@pranavkm Plz clarify which approach you're addressing. I thought that at least with `Task.Run` it wouldn't be blocking but use an additional thread. Still might starve, but it wouldn't block. Are you saying that what you just suggested will block? ... or are you saying that both what I show and what you show will block?

**Comment by guardrex** [comment]
@spottedmahn Looks like we'll have to leave this in the realm of *workaround*; therefore, not documented. However, this issue is attached to the topic, so readers who scroll to the bottom will see it.

**Comment by pranavkm** [comment]
Sorry, I hadn't paid attention to the original issue: you can write a `ViewComponent` with a synchronous `Invoke` method:

```C#
 public class PriorityListViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(int maxPriority, bool isDone)
    {
        var items = new List<Item>{ ... };
        return View(items);
    }
}
```

should work

**Comment by guardrex** [comment]
@pranavkm How is it called in Razor with `@Component` (`IViewComponentHelper`)? It seems to want a `Task<T>` and a method named `InvokeAsync`.

https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.mvc.iviewcomponenthelper

**Comment by pranavkm** [comment]
MVC handles invoking a synchronous `ViewComponent.Invoke` method. The same way you can have sync and async actions or page handlers, and not have to worry about how it gets invoked.

**Comment by guardrex** [comment]
It seems a bit strange to call the dev's method (with a synchronous method signature) using the `@await Component.InvokeAsync( ... );` syntax, but it :tada: **_Just Works_**:tm: 🎈 .

I'll get this documented within a few days. Thanks everyone!

Cross-ref the discussion for the invocation changes: https://github.com/aspnet/Mvc/issues/3973

**Comment by spottedmahn** [comment]
>It seems a bit strange to call the dev's method (with a synchronous method signature) using the @await Component.InvokeAsync( ... );

👍

---

Based upon the comments I above I've got this working:

```csharp
public Task<IViewComponentResult> InvokeAsync()
{
	var model = new MyModel
	{
		Name = "Hello world"
	};
	var result = (IViewComponentResult)View(model);
	return Task.FromResult(result);
}

//doesn't work
//InvalidOperationException: Method 'InvokeAsync' of view component 
//'ViewComponentSyncTest.Views.Shared.Components.MyViewComponent.PocViewComponent'
//should be declared to return Task<T>
//public IViewComponentResult InvokeAsync()
//{
//    var model = new MyModel
//    {
//        Name = "Hello world"
//    };
//    return View(model);
//}
```

[Full source: PocViewComponent.cs](https://dev.azure.com/spottedmahn/_git/Experiments?path=%2FViewComponent%20Sync%20Test%2FViewComponent%20Sync%20Test%2FViews%2FShared%2FComponents%2FPoc%2FPocViewComponent.cs&version=GBmaster)

```razor
@await Component.InvokeAsync(nameof(PocViewComponent).Replace("ViewComponent", ""))
```

[Full source: Index.cshtml](https://dev.azure.com/spottedmahn/_git/Experiments?path=%2FViewComponent%20Sync%20Test%2FViewComponent%20Sync%20Test%2FViews%2FHome%2FIndex.cshtml&version=GBmaster)

Demo site: https://viewcomponentsync.azurewebsites.net/

Thanks to everyone!  ASP.NET Core team rocks 👏👏 🏆

**Comment by spottedmahn** [comment]
cleaner version with `Task.FromResult<T>(T result)`...

```csharp
public Task<IViewComponentResult> InvokeAsync()
{
    var model = new MyModel
    {
        Name = "Hello world"
    };
    var result = View(model);
    return Task.FromResult<IViewComponentResult>(result);
}
```

**Comment by spottedmahn** [comment]
Based upon the [PR](https://github.com/aspnet/Docs/pull/8686), I see I can do the following:

```html
@await Component.InvokeAsync(nameof(PocSyncViewComponent).Replace("ViewComponent", ""))
```

```csharp
public class PocSyncViewComponent : ViewComponent
{
	public IViewComponentResult Invoke()
	{
		var model = new MyModel
		{
			Name = "hello world sync"
		};
		return View(model);
	}
}
```

[Full source](https://dev.azure.com/spottedmahn/_git/Experiments?path=%2FViewComponent%20Sync%20Test&version=GBmaster), [Demo app](https://viewcomponentsync.azurewebsites.net/)

---

Feels like magic 🧝‍♂️ in that I'm telling it to call `InvokeAsync()` but the runtime calls `Invoke()`... not sure I'm a fan of that...

---
Thanks again 🙏

**Comment by scottaddie** [comment]
@pranavkm See the comment from @spottedmahn above. This seems like an area that could use some polishing. Is there already an open issue on this in the aspnet/Mvc repo or elsewhere?

**Comment by guardrex** [comment]
This will be auto-closed by the PR.
