### ISSUE TITLE
When ASP.NET Core App (2.1.x or 2.2) fails with: HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by JashanChittesh** [aspnet/Docs#8555]
The [App startup errors](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#app-startup-errors) troubleshooting guide does have some useful information but given that Visual Studio updates can break compatibility with the ASP.NET Core version installed on your server (giving you _HTTP Error 502.5 - Process Failure_, with no useful information in the Application Event Log (**Application '...' with physical root '...' failed to start process with commandline '...', ErrorCode =  '0x80004005 : 80008096.**), it would be helpful to know where to get the most current version of ASP.NET Core:

I guess after each Visual Studio update, you should probably check this URL and upgrade your server, if a new version is available: [.NET Core 2.1 downloads](https://www.microsoft.com/net/download/dotnet-core/2.1)

Eventually, you'll move to .NET Core 2.2 and that's simply "2.2" at the end of the URL: [https://www.microsoft.com/net/download/dotnet-core/2.2](https://www.microsoft.com/net/download/dotnet-core/2.2)

PS: Ah, even better is this URL:

[.NET download archives](https://www.microsoft.com/net/download/archives) ([https://www.microsoft.com/net/download/archives](https://www.microsoft.com/net/download/archives))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4f16c68-708b-003e-8c63-1df60c6344d0
* Version Independent ID: 25fa0508-4450-9051-cdd7-0d3260c60b4f
* Content: [Troubleshoot ASP.NET Core on IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/troubleshoot?view=aspnetcore-2.1#app-startup-errors)
* Content Source: [aspnetcore/host-and-deploy/iis/troubleshoot.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/troubleshoot.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @JashanChittesh Thanks for commenting. That particular problem is covered in the *Common Errors* topic: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-iis-errors-reference?view=aspnetcore-2.1#missing-net-framework-version

The *Common Errors* topic is due for an update asap. Let's leave this issue open, and I'll see what kind of cross-linking/new info can be added when that topic is worked.

**Comment by Rick-Anderson** [comment]
@guardrex 	please double check closed issues when you update this topic.

Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by guardrex** [comment]
@Rick-Anderson That's probably not feasible given the large number of them. I'll cut-'n-paste this over to the issue that I'm working. That work started during the holidays, and I'll be returning to it soon.

**Comment by keyvan1361** [comment]
you can watch my video on how to solve 502 errors on youtube:
 [https://www.youtube.com/watch?v=clCR3k6kkD8](https://www.youtube.com/watch?v=clCR3k6kkD8 )
