### ISSUE TITLE
Code blocks broken

### ISSUE THREAD

**Issue by imba-tjd** [aspnet/Docs#8556]
![default](https://user-images.githubusercontent.com/24759802/45596151-eed11b00-b9e9-11e8-9609-1a7f3a066be0.png)

And the fourth point should be out of `Linux`

![default](https://user-images.githubusercontent.com/24759802/45596153-08726280-b9ea-11e8-8f9c-ea8d81e5514b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-1.1&tabs=linux)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@imba-tjd  thanks for bringing this to our attention. I'll get this fixed ASAP.

@scottaddie @guardrex @tdykstra This was rendering correctly when updated for 2.1
A OPS build change broke it.

**Comment by rxcontributorone** [comment]
llllllll
