### ISSUE TITLE
Namespace error when code pasted in

### ISSUE THREAD

**Issue by Dutchie109** [aspnet/Docs#8558]
Hi - I get an error from the Razor code pasted in to the _Layout.cshtml file: 'ApplicationInsights' does not exist in the namespace 'Microsoft'. Presumably this is because I don't have ApplicationInsights installed. I also get an error from the Razor code further on: @Html.Raw(JavaScriptSnippet.FullScript).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Dutchie109  thanks for reporting this. Until I get this fixed, don't copy/paste, just make the highlighted changes.

**Comment by SeanKilleen** [comment]
I think I've got the fix for this. PR coming shortly.

**Comment by grouchobear** [comment]
I'm a little late to the game here but I'm seeing an issue with InteliSense showing 
**ViewData does not exist in the current context** 
when I create the Welcome view.  The application runs as expected, it's just a little offsetting to see the code appearing to be in err.  
This is occurring in VS2017 v15.9.12
