### ISSUE TITLE
Add Brotli compression to the sample app

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#8559]
Update the sample for recent in-text updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9795b92f-db24-8f1f-88c0-c36666d3526f
* Version Independent ID: 2d56d9b6-3d7b-0204-6c08-8e584fccecc2
* Content: [Response Compression Middleware for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/performance/response-compression.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/response-compression.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@danroth27 	would you like this done before RTM? Can we do Brotli before RTM?

**Comment by guardrex** [comment]
I can do it. I didn't think it was a priority over other 2.2 issues (e.g., Health Checks) because the topic covers Brotli pretty well on its own.

**Comment by Rick-Anderson** [comment]
DR27 asked me to boost priority.

**Comment by guardrex** [comment]
Do you want to send me an order list for my 2.2 assignments? I'll work 'um right down the line.
