### ISSUE TITLE
Backtics ``` are showing

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8563]
&#96;&#96;&#96;console
dotnet dev-certs https --trust
&#96;&#96;&#96;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by rxcontributorone** [comment]
HELLO

**Comment by rxcontributorone** [comment]
Hello

**Comment by rxcontributorone** [comment]
Good

**Comment by rxcontributorone** [comment]
hujbhi

**Comment by rxwebteam** [comment]
Test

**Comment by rxwebteam** [comment]
Test
