### ISSUE TITLE
Browser Link has been removed from ASP.NET Core 2.1

### ISSUE THREAD

**Issue by fsjunges** [aspnet/Docs#8565]
As per https://github.com/aspnet/Docs/pull/6532 the Microsoft.AspNetCore.App metapackage does not contain Browser Link.
You still have to install the Microsoft.VisualStudio.Web.BrowserLink NuGet package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fcc1fa9-004b-0be3-6148-e8c075e5b2bc
* Version Independent ID: 78a1947e-dea7-65b4-2376-05c7795e4bf9
* Content: [Browser Link in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-browserlink?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/using-browserlink.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-browserlink.md)
* Product: **aspnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @fsjunges ... I'll patch that up.

**Comment by guardrex** [comment]
We're good ... I just checked. The topic contains the correct versioning to explain adding the package ref when using the `App` package.
