### ISSUE TITLE
Separate DB context needed to add custom user data?

### ISSUE THREAD

**Issue by AlbertoPa** [aspnet/Docs#8566]
Why is a separate database context is required to have a custom user model when scaffolding identity? This seems to lead to conflicts that need to be manually resolved if one creates a WebApp with identity enabled since the start and then decides to customize, or am I missing something and it is possible to re-use the same DB context and add a custom user model?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by AlbertoPa** [comment]
My apologies: I found this blog post https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/ which answers my question.

**Comment by Rick-Anderson** [comment]
@AlbertoPa  as you found out, it's not required. The article doesn't say it's required.
