### ISSUE TITLE
EF Core Inheritance is not covered on EF Core 2.1 Razor Pages tutorial

### ISSUE THREAD

**Issue by buchajmal** [aspnet/Docs#8568]
EF Core 2.1 Razor Pages tutorial does not cover Inheritance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55345ff6-3c81-969e-3c92-29c24d78d2ca
* Version Independent ID: aa826512-74a5-752a-0ad0-0f8133f6c39e
* Content: [ASP.NET Core MVC with EF Core - Inheritance - 9 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/inheritance.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/inheritance.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@buchajmal  that's correct.
