### ISSUE TITLE
Add detail around the importance of 'AddCookie' authentication scheme

### ISSUE THREAD

**Issue by Randy808** [aspnet/Docs#8569]
# Issue description

In the [documentation](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x) about using the ASP.NET Core 2.1 cookie authentication without ASP.NET Core Identity, it is not specified that the 'AddCookie' extension method on the 'AuthenticationBuilder' requires an authentication scheme to be set. It will not implicitly assume the authentication scheme of the 'AuthenticationBuilder' and will raise the following error: 'No authenticationScheme was specified, and there was no DefaultChallengeScheme found.'

**Comment by HaoK** [comment]
The default scheme is not connected to the default cookie scheme in any way.  If you omit the scheme to AddCookie, it uses CookieAuthenticationDefaults.AuthenticationScheme.  There is no default for the default scheme.  The only way a cookie becomes the default scheme is you pass in the name of the cookie scheme.

**Comment by guardrex** [comment]
> `AuthenticationScheme` passed to `AddAuthentication` sets the default authentication scheme for the app. `AuthenticationScheme` is useful when there are multiple instances of cookie authentication and you want to authorize with a specific scheme. Setting the `AuthenticationScheme` to `CookieAuthenticationDefaults.AuthenticationScheme` provides a value of "Cookies" for the scheme. You can supply any string value that distinguishes the scheme.

Overloaded terms could be a problem, or it could just be that the current text isn't specific enough (or wrong). I'll take a closer look at this later today. I'm buried in response compression concepts at the moment on another issue. 🏃 I'll get back to u in a bit.

**Comment by guardrex** [comment]
Ok ...

>  If you omit the scheme to AddCookie, it uses CookieAuthenticationDefaults.AuthenticationScheme. There is no default for the default scheme. The only way a cookie becomes the default scheme is you pass in the name of the cookie scheme.

This should be added to the topic directly under the `AddAuthentication` content.

I'll check the other topics, too, to see if/where `AddCookie` is mentioned. Where mentioned, I'll see what else can be done.

Thanks @Randy808 for commenting on this.
