### ISSUE TITLE
i Got No executable found matching command "dotnet-aspnet-codegenerator" this error i have tried more please help to get out here!

### ISSUE THREAD

**Issue by touhidulfahim** [aspnet/Docs#8570]
i Got No executable found matching command "dotnet-aspnet-codegenerator" this error i have tried more please help to get out here!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.0)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Install the latest version of the [.NET Core SDK](https://www.microsoft.com/net/download/archives) But not the preview version.
It's no longer a `<DotNetCliToolReference/>` element.
It's a global tool.  Or you ran the command from outside the project directory.

**Comment by byroniac** [comment]
Same problem here on Ubuntu 18.10. Everything worked fine up until the call to the "dotnet aspnet-codegenerator ..." line using SDK 2.2. I have the "dotnet ef ..." subset but no "aspnet-codegenerator" at all. And I'm in the project directory folder. If I'm missing something, then I have no idea what.

**Comment by Joniator** [comment]
This can be an error in your path, you need to restart the terminal after you installed dotnet, at least for me that fixed the problem.
If not, check if the executable exists in ~\.dotnet\tools and can be used directly.
