### ISSUE TITLE
Custom Validation -> Decorate Member?

### ISSUE THREAD

**Issue by spottedmahn** [aspnet/Docs#8574]
Reference: [Custom Validation](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#custom-validation)

It seems like, this attribute would be put on the class, not the member, right?  BTW, I think that would be good include the usage in the docs, thoughts? 💭

```csharp
[ClassicMovie]
public class Movie {
    
    ...

    [WhyCant_I_PutA_CustomAttributeHere?]
    public int Year { get; set; }
}
```

Assuming I put the custom attribute on the class, it seems inconsistent.  I can decorate members with `[Required]`.  Why can't I decorate a member?  (not a doc issue 😊, I know)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1#custom-validation)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Validation goes on the property, not on the class. We should probably mention that.

**Comment by spottedmahn** [comment]
I see, thanks!

I'm happy to take a stab at that if you would like?

**Comment by Rick-Anderson** [comment]
@spottedmahn  that would be great.

**Comment by daveabrock** [comment]
Sorry @spottedmahn - I'm working on the doc and thought I would just take care of this one.

**Comment by spottedmahn** [comment]
nice, thanks @daveabrock!
