### ISSUE TITLE
fundamentals/app-state.rst "Managing Application State"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#858]
- [x] address mikes concerns (on this page)
- [x]  #1840 how to load Session asynchronously
- [x]  #1345 
- [x] Needs UE edit
- [x]  Update for RTM [Fixed via #1517 ]
- [x] Exception should include exception text for search reasons. Don't need the entire call stack on image or text version.

per @MikeWasson on Managing Application State

I think the doc needs better description of what the Session really does:
- It's a dictionary that persists across the browser session
- The dictionary is stored on the server side NOT the client. It's backed by a cache.
- A session ID is stored on the client in a cookie, that's used to fetch the right session dictionary on the server side  

"However, there are extension methods..."
- Specify these are defined in Microsoft.AspNet.Http namespace

In this code:
               services.AddCaching();
               services.AddSession();

Clarify that 
- AddCaching adds the in memory cache, which implements IDistributedCache. 
- AddSession adds the session - which will use any IDistributedCache via DI
  So to use other caches, you would replace "AddCaching" but keep "AddSession"  <<<< this was the confusing part

Not clear if/when the session clears the backing cache? (Seems to be based on the expiration time.) - That is, after you close the browser and the session cookie is deleted, what happens to the stuff in the cache?

"You can’t necessarily assume that a session is restricted to a single user, so be careful what kind of information you store in Session." 
- This is vague, are there security implications or specific security recommendations? What if you store values that are keyed by the user ID? 

"coherent session": I didn't understand this note. I _think_ it's saying that updating one value writes the entire dictionary to the cache?

Is there a way to set the cookie expiration? 
Clarify that the default is a session cookie (ie doesn't persist after the browser session)  << I think

**Comment by danroth27** [comment]
@ardalis do you want to incorporate this feedback?

**Comment by danroth27** [comment]
@ardalis Can you include this feedback in your RC2 update for this article?

**Comment by ardalis** [comment]
Will do

**Comment by Rick-Anderson** [comment]
In PR #1999
