### ISSUE TITLE
Using MicrosoftAccount provider; email confirmation

### ISSUE THREAD

**Issue by jasonshave** [aspnet/Docs#8580]
It would be great to have an example of someone using both built-in authentication and an external provider when it comes to email address confirmation. The behavior I've configured requires email addresses to be confirmed (a high value scenario).

Given the configuration of an external authentication provider, how would one set the email address confirmation for both types of login scenarios?

When I register my MSA with my application it signs me in but the email is unverified. This means if I log out, I can't get back in. It wants me to associate my MSA account again and fails on a duplicate entry check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio

**Comment by jasonshave** [comment]
Thanks @Rick-Anderson . I have email confirmation working for new built-in user registration however I'm not sure where to implement this for the MSA.

**Comment by jasonshave** [comment]
I realized I could modify the user object before it runs `var result = await_userManager.CreateAsync(user);` to include the EmailConfirmed = true value as such in "ExternalLogin.cshtml.cs":

````var user = new UserRegistrationExtension { UserName = Input.Email, Email = Input.Email, EmailConfirmed = true};````

Doesn't make sense to me to require email confirmation on external identity providers as they do their own checking for validity.

**Comment by jasonshave** [comment]
@Rick-Anderson do you know if a closed issue here will result in the

**Comment by blowdart** [comment]
That would be a decision for the customer, and outside of scope for the basic templates. We assume that external providers do the validation.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
