### ISSUE TITLE
2FA with login provider

### ISSUE THREAD

**Issue by jasonshave** [aspnet/Docs#8583]
Just some feedback around 2FA and these providers.

I wasn't able to get the mult-factor page to display if I used an external provider login. I had to add:

`if (result.RequiresTwoFactor)
            {
                return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl });
            }`

...and also change this:

````var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor : true);```` 

to this:

````var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor : false);````

In the `ExternalLogin.cxhtml.cs` file.

Not sure if this should reside in the 2FA configuration guidance (along with a link from this page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1612f19-f267-493a-c230-2ca18e4eb50b
* Version Independent ID: d312db0f-6cf1-87ca-09b0-604a66e18a07
* Content: [Facebook, Google, and external provider authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/index?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/social/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK  where should this information go?
@jasonshave  thanks for the feedback.

**Comment by HaoK** [comment]
Is this an issue with the current templates?  Or only with the docs?

**Comment by Rick-Anderson** [comment]
No. This is how it should be. External logins are protected by whatever the external login provider provides. We don't then layer anything else on top. Consider, for example, Google, my Google login demands a hardware key. I should not then be subjected to a second 2fa prompt by whatever web site I'm logging into wants. The current behaviour is fine. It's by design.
