### ISSUE TITLE
HttpClient should be recommended for dispose.

### ISSUE THREAD

**Issue by oleksandr-bilyk** [aspnet/Docs#8584]
In this article we have text "The HttpClient instances can generally be treated as .NET objects not requiring disposal."
I think that it is amazing that IHttpClientFactory handles underlying socket connection lifetime. However there is big .Net Framework Design Guidelines rule that IDisposable things should be disposed. There is no guarantee that resource lifetime management will not be changed tomorrow. We may say that dispose is not required because in current implementation is handled automatically but is recommended at least according to .NET canonical forms.
I will tell you one story from my experience. In ADO.NET there is IDbConnection, DbConnection, IDbCommend, DbCommand types. SqlConnection and SqlCommand types were disposing resources manually and that's why it never was causing problems even if people were disposing SqlConnection and didn't dispose SqlCommand. LinqToSql developers also did it in such way (were disposing SqlConnection but ignored disposing SqlCommand. But happened on LinqToSql to SQL Compact 3.0 database because it didn't have such internal management.  
There are many beginner or not experienced .NET developers that may interpret your text as recommendation to stop disposing HttpClient generally. But that will be even recommendation because maybe some any function that instantiates and HttpClient should have no coupling on internal optimizations. I will recommend to remove sentence "The HttpClient instances can generally be treated as .NET objects not requiring disposal." and add that in current implementation HttpClient resources are managed by IHttpClientFactory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 881cef77-11ef-ac11-06d0-0996a1ccfa1b
* Version Independent ID: 3d356334-e672-7e8b-1fef-7944ebee99eb
* Content: [Initiate HTTP requests](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/http-requests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-requests.md)
* Product: **aspnet-core**
* GitHub Login: @stevejgordon
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@dougbu  do you recommend we replace "The `HttpClient` instances can generally be treated as .NET objects not requiring disposal." 

with something like:
The `HttpClient` resources are managed by `IHttpClientFactory`.

**Comment by dougbu** [comment]
@rynowak your thoughts?

**Comment by rynowak** [comment]
If you're using `IHttpClientFactory` then it does not matter if you dispose or not. I

 think the best guidance for a **web application** is to use the factory and don't mess with dispose. ASP.NET Core uses DI, and that will be our guidance for anything that shares scope with a request (like a `DbContext`), let the container dispose it for you.

If you're building a reusable library there isn't really one-size-fits-all guidance.

**Comment by oleksandr-bilyk** [comment]
@rynovak Then why do you agree with one-size-fits-all guidance sentence The HttpClient instances can generally be treated as .NET objects not requiring disposal." One do you full people with "generally" words. It is because you are super-mega-experienced developers that know when and how to violate rules? Dependency Injection is just static dependency on IHttpClientFactory interface. That is cool feature that should not be general guide. You should change this statement "The HttpClient instances can generally be treated as .NET objects not requiring disposal."

**Comment by Legends** [comment]
@rynowak  What is the lifetime of a `HttpClient` when created through `IHttpClientFactory`? Scoped?
