### ISSUE TITLE
Question About Server Side

### ISSUE THREAD

**Issue by GitHubNameMsterk** [aspnet/Docs#8587]
Do I need to setup something on every server I want to interrogate? or just on my client side?   (For the sake of context - my goal is to use websockets as a sort of PING/Status Health check)   Maybe this isnt the best solution for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
What about SignalR?

**Comment by Rick-Anderson** [comment]
Yes, you'd still need something on the server. The client can't interrogate a server without the server set up to respond.

**Comment by GitHubNameMsterk** [comment]
Thanks for your time Rick.
