### ISSUE TITLE
Links to websites other than non-profit ones are inappropriate for open source projects.

### ISSUE THREAD

**Issue by drumsta** [aspnet/Docs#8592]
There are scattered links across the documentation to the profit-seeking websites what in my opinion is inappropriate for open source projects. Open source projects should link to the non-profit websites only. Otherwise, those links create ethic issues, like promotion of one websites over others, etc... Why deviq.com? Then why not Stackoverflow or Quora.com or AnyOtherCoolWebsite.com? 

Several examples:
"Static cling" links to https://deviq.com/static-cling/
"Single Responsibility Principle (SRP)" links to https://deviq.com/single-responsibility-principle/
"separate concerns" links to https://deviq.com/separation-of-concerns/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @drumsta ... Thanks for commenting.

In the case of deviq.com, that org is related to Steve Smith (@ardalis). The links you're referring to here were placed by Steve when he wrote this topic. He's the original author of it and still first author today.

I know that during topic updates that some of the Deviq.com links have been changed here and elsewhere to Microsoft documents that cover the same concepts. For example, this one on architectural principles has been used in a few spots ... https://docs.microsoft.com/dotnet/standard/modern-web-apps-azure-architecture/architectural-principles (which was also written by Steve I think).

I'll go over this topic and see which ones can have a MS doc link. I think the other ones probably can stay. Note that they were approved by both engineering and the doc team (at the time).

RE: 3rd party links in general

If we have MS coverage, we try to use the MS coverage. If you spot something where you think we have coverage but linked a 3rd party, please do open an issue (or go ahead and shoot us a PR). We'll take a look at anything you think isn't a good link. You asked about why certain destinations are chosen. There's no magic there ... the author of the topic can recommend links when the doc is written or updated. If the engineers and doc team permit the link, it goes into the docs. To a large degree, the author makes the initial recommendation. The reviewers either approve or decline those choices.

**Comment by ardalis** [comment]
Agree with Luke's assessment. At the time these were the resources that had the best information on the subjects at hand, and in some cases I was able to quickly add the reference material I need on DevIQ topics. At the time they were written DevIQ didn't even have any ads on it or any way to make any money. Since then, it does sell a few video courses (from a separate URL from the reference content) but otherwise all the content linked to is free. I could make it non-profit if I felt like doing the paperwork. It certainly isn't making any profit...

**Comment by guardrex** [comment]
Thanks @ardalis ... I don't think we should change the links unless MS has a doc. I'm 🏃😅 at the moment, but I'll take a look in a few weeks unless you or someone from the community works the issue.
