### ISSUE TITLE
ASP.NET 5 related topics on azure.com to consider adding to ASP.NET 5 doc set

### ISSUE THREAD

**Issue by Erikre** [aspnet/Docs#860]

**Comment by Erikre** [comment]
Here's a list of ASP.NET 5 related topics on azure.com that we should consider adding to docs.asp.net:

Title: Application Insights for ASP.NET 5
URL: http://azure.microsoft.com/documentation/articles/app-insights-asp-net-five/ 
Action: Add as additional resource link to the following topic: Application Insights

Title: Application Insights now supports ASP.NET 5 applications 
URL: http://azure.microsoft.com/blog/application-insights-now-supports-asp-net-v5-applications-2/    
Action: None.

Title: Create an ASP.NET 5 web app in Visual Studio Code 
URL: http://azure.microsoft.com/documentation/articles/web-sites-create-web-app-using-vscode/ 
Action: Add to Tutorials section.

Title: Integrating Azure AD into an ASP.NET 5 web app 
URL: http://azure.microsoft.com/documentation/samples/active-directory-dotnet-webapp-openidconnect-aspnet5  
Action: Consider adding to a new Samples section.

Title: Calling a ASP.NET 5 Web API from a WPF application using Azure AD 
URL: http://azure.microsoft.com/documentation/samples/active-directory-dotnet-native-aspnet5 
Action: Consider adding to a new Samples section.

Title: Calling a web API in an ASP.NET 5 web application using Azure AD 
URL: http://azure.microsoft.com/documentation/samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnet5 
Action: Consider adding to a new Samples section.

Title: Deploy an ASP.NET MVC 5 mobile web app in Azure App Service 
URL: http://azure.microsoft.com/documentation/articles/web-sites-dotnet-deploy-aspnet-mvc-mobile-app/ 
Action: Add to Mobile section.

Title: Get started with Azure Blob storage and Visual Studio connected services (ASP.NET 5) 
URL: http://azure.microsoft.com/documentation/articles/vs-storage-aspnet5-getting-started-blobs/ 
Action: It seem like this could be added to the Working with Data section.

Title: What happened to my ASP.NET 5 project (Visual Studio Azure Storage connected services)? 
URL: http://azure.microsoft.com/documentation/articles/vs-storage-aspnet5-what-happened/ 
Action: None.

Title: Get started with queue storage and Visual Studio connected services (ASP.NET 5) 
URL: http://azure.microsoft.com/documentation/articles/vs-storage-aspnet5-getting-started-queues/  
Action: It seem like this could be added to the Working with Data section.

Title: Build a web service front-end for your application 
URL: http://azure.microsoft.com/documentation/articles/service-fabric-add-a-web-frontend/ 
Action: Consider adding to Tutorials section.

Title: How to get started with Azure Table storage and Visual Studio connected services 
URL: http://azure.microsoft.com/documentation/articles/vs-storage-aspnet5-getting-started-tables/  
Action: Add to Working with Data section.

Title: Adding Azure storage by using Visual Studio Connected Services 
URL: http://azure.microsoft.com/documentation/articles/vs-azure-tools-connected-services-storage/  
Action: Add to Working with Data section.

Title: Hosting Web Apps in Docker 
URL: http://azure.microsoft.com/documentation/articles/vs-azure-tools-docker-hosting-web-apps-in-docker/ 
Action: Add to Publishing and Deployment section.

**Comment by GuardRex** [comment]
and as @moozzyk pointed out earlier https://github.com/aspnet/Hosting/issues/539#issuecomment-168789381 ... hosting .NET 5 app in a Docker container OS scenario (non-Azure Docker host, e.g., Azure VM ... e.g., Nano Server :wink:)
