### ISSUE TITLE
Enabling HTTPS enforcement 

### ISSUE THREAD

**Issue by branstraub** [aspnet/Docs#8601]
# Microsoft Account Authentication issue

I have an dotnet core asp net app running 2.1.3 runtime.
The app has currently https enforcement enabled.
Its running on an Azure web app.

´´´
 app.UseHsts();
 app.UseHttpsRedirection();
´´´

The challenge its somehow been made over http and not https, and i got the following error:

https://login.live.com/err.srf?lc=3082#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=CfDJ8LevvHasNBZCixSGgrkUyfu4rUrE83bi1bvDZpbDQ0sJtu9FSFMR60-KITRAs9oN4dac_D7RaFbuKJMpvTt0Mlp-tgIIr3D3-395-7OCB6cuB7wGgutsgUmgCPXFn3L5w9nxR8vqjya79KnI2RUtypT9tD4Tb84bJH2-oWSGIdfuBbNvnx-UhryRLhtZEZii47Laio6FP1a7SKWFHmniHaM9oP99iLWzM6yttXOqrmGWBoDhsH_YqzzzwWPrppFGjpWuYtIhIdjzFRiBiYCMTM8

Which means the url doest not match with the one enabled on the Microsoft App for Authentication.
I'm facing this issue with both Facebook, Google and MS.

The login with HTTPS enabled page its published at: https://app.myeasybot.com/manage

Any ideas?

Thanks!

**Comment by guardrex** [comment]
Closing in favor of #8600.
