### ISSUE TITLE
Installing nuget package "Microsoft.Extensions.Hosting" is necessary when building in docker

### ISSUE THREAD

**Issue by Julian-Chu** [aspnet/Docs#8609]
I make an app by following this example.  It builds successfully in VS 2017, but fails in docker. The error message is in the follwing:
error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?).
error CS0246: The type or namespace name 'IHostedService' could not be found (are you missing a using directive or an assembly reference?)

After installing nuget package, the issue is solved.  Just for reference if anyone would like to build this in docker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Julian-Chu ... Thanks for commenting.

Can you share your package references from your project file? I'm curious to see what packages you ending up referencing.

**Comment by Julian-Chu** [comment]
Hi @guardrex ,

Here is my packages:
![image](https://user-images.githubusercontent.com/7224544/45759639-9a67ae80-bc28-11e8-8e31-d0c2c7b0883a.png)

Microsoft.Extensions.Hosting package is installed for docker, my VS 2017 can build without this.
docker image tag: microsoft/dotnet

**Comment by guardrex** [comment]
Right-click the project and select **Edit \<PROJECT_NAME>.csproj**. Grab the `<PackageReference>` elements and paste them in here.

Our Web Host sample goes with `Microsoft.AspNetCore.App`, which includes `Microsoft.Extensions.Hosting`. The Generic Host sample directly references the `Microsoft.Extensions.Hosting` package. You can see those two samples here ...

https://github.com/aspnet/Docs/tree/master/aspnetcore/fundamentals/host/hosted-services/samples

The Docker sample app goes with the `App` package. Here's the project file of that sample ...

https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetapp/aspnetapp.csproj

**Comment by Julian-Chu** [comment]
Hi @guardrex ,

I think Microsoft.AspNetCore.App or Microsoft.Extensions.Hosting must be referenced in project correctly like docs and samples, so I suspect it is due to my windows environment, but I have no idea how to identify it. It's not big issue, just to add package manually, and docs/samples are great and correct, so you can close this as well.

Here are 2  .csproj files.  I implemented hosted service in individual project and inject to web project.
Timestealer.HostedService.csproj (service is implemented)
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.1.3" />

    // without this,  build can be successful in VS2017 and dotnet CLI
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="2.1.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Timestealer.DataAccessLayer.EFcore\Timestealer.DataAccessLayer.EFcore.csproj" />
    <ProjectReference Include="..\Timestealer.DataAcessLayer\Timestealer.DataAccessLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.hosting.abstractions\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```
Timestealer.Web.csproj (service is injected)
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDoucmentationFile>true</GenerateDoucmentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Timestealer.DataAccessLayer.EFcore\Timestealer.DataAccessLayer.EFcore.csproj" />
    <ProjectReference Include="..\Timestealer.DataAcessLayer\Timestealer.DataAccessLayer.csproj" />
    <ProjectReference Include="..\Timestealer.HostedService\Timestealer.HostedService.csproj" />
  </ItemGroup>
</Project>
```

**Comment by guardrex** [comment]
The topic doesn't call out the `Microsoft.Extensions.Hosting` package near where it describes the `IHostedService` interface. I'll add language to the topic that specifies the package. Thanks for opening this issue.

RE: Running VS/CLI but not Docker

My guess is that it's transitively referenced by another package. However it comes in, you're right, let's not leave this up to chance or guessing. It's best if the topic is explicit about referencing the package.
