### ISSUE TITLE
typo in appsettings IncludeScopes parameter 

### ISSUE THREAD

**Issue by niboj** [aspnet/Docs#8612]
In the configuration section, in the appsetting example
"IncludeScopes": "true"  
should be without quotes
"IncludeScopes": true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@niboj Thank you for reporting this problem. The fix will go live later today.
