### ISSUE TITLE
IISCertificateMappingAuthenticationModule

### ISSUE THREAD

**Issue by carathorys** [aspnet/Docs#8613]
Hi!

I try to use **IISClientCertificateMappingAuthentication** without any success.
The IIS identifies my client certificate, but I'm not able to obtain the `User` object from my AspNetCore Web API application. When I try to use `User` or `HttpContext.User` objects, they are null, and I can only reach the Client Certificate through `HttpContext.Connection.ClientCertificate` object, but my goal would be that I should get the User object populated like when I use Windows authentication.
Can you provide me some example how to use that module? Or I'm only able to get the client certificate?
I'm trying to use it in AspNetCore Web API 2.1

Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a93d569-16b9-a822-f9f1-ed7c3d31779f
* Version Independent ID: 4b475c3c-b698-234f-e085-a670c7e31aac
* Content: [IIS modules with ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/host-and-deploy/iis/modules?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/modules.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/modules.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Your app follows all the guidance in the Windows Auth topic? https://docs.microsoft.com/aspnet/core/security/authentication/windowsauth

**Comment by carathorys** [comment]
Hi,

I've created an (example)[https://github.com/carathorys/aspnetcore_iisclientcertauth/tree/master] repo how I tried to use it. 
The actual Windows Authentication is disabled, as I don't wanted to authenticate the users with kerberos, rather I wanted to authenticate an AD user by a client certificate. 

We used this method in .NET Framework, and it worked, but currently we wanted to migrate those solutions into .NET Core apps.

**Comment by guardrex** [comment]
@Tratcher Would you like this opened on aspnet/Home?

**Comment by Tratcher** [comment]
@pakrym to confirm this isn't going to work for out-of-proc ANCM, but it may work with the new 2.2 in-proc ANCM.

**Comment by pakrym** [comment]
Filed https://github.com/aspnet/IISIntegration/issues/1432

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
