### ISSUE TITLE
Invalid globbing pattern example: System.ArgumentException: Illegal characters in path.

### ISSUE THREAD

**Issue by aureole82** [aspnet/Docs#8614]
I would say

    "inputFiles": ["wwwroot/**/*(*.css|!(*.min.css)"]

doesn't work.

Could you fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@aureole82 	 thanks for the report. What version of the .NET Core SDK are you using?

**Comment by aureole82** [comment]
`Microsoft .NET Core SDK 2.1.402 (x64)` But why?

In my opinion the globbing pattern just misses a enclosing bracket.

**Comment by Rick-Anderson** [comment]
You mean the closing `)`. Does it work when you add the closing parenthesis?

**Comment by PixelEditor** [comment]
Same here in Microsoft .NET Core SDK 2.1.402 (x64)

Globbing looks to be broken here. If you use just the example you get the "Illegal characters in path" error. If you add a valid normal path with the second path as the gobbing path then the bundler says it can find any files,
