### ISSUE TITLE
Get Started with ASP.NET, your first application in 5 minutes.

### ISSUE THREAD

**Issue by TAlec006** [aspnet/Docs#8616]
5 minutes have passed and I can't even build! It's stuck in the first page of the tutorial that tells me to hit F5 to build and debug it doesn't even do that! it's a big claim to build your first app in 5 minutes when the first page of the tutorial leads to a setback.
[Link to the tutorial page here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.1&tabs=aspnetcore2x#feedback)

**Comment by Rick-Anderson** [comment]
Try the [Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1) version. It's much easier to follow.

**Comment by Rick-Anderson** [comment]
> it's a big claim to build your first app in 5 minutes 

I'd like to get that fixed. That's a big claim.
