### ISSUE TITLE
download sample material

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8617]
Sorry fellas. I need to bug you again....Im still trying to get me head around this, so I am now resorting to download your sample pages, but I'm not having much success there either.
When I get to the GitHub page (Docs/aspnetcore/data/ef-rp/intro/samples) do I 
1. Follow the 'cu' or 'cu21' path
2. If I want to use your code, should I be removing the hashes that are in front of the If/end if statements? (I have tried https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro/samples/cu21/Pages/Students/Index.cshtml.cs)
3. Where can I go to download a complete solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Use the cu21' path

The code is used to host snippets for the article. The download state is the finished tutorial. You'll have to adjust the `#` to get earlier versions working.
