### ISSUE TITLE
The article headings are "iis / iis express" and imply that full iis is needed for WS on express

### ISSUE THREAD

**Issue by oising** [aspnet/Docs#8618]
https://twitter.com/oising/status/1041815933344460801

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b0cac1-adc7-434c-d867-6e28e39bdae7
* Version Independent ID: 762efeed-010e-f422-03d0-22d6681b2851
* Content: [WebSockets support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/websockets.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/websockets.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by oising** [comment]
I am having problems getting WS working on IIS Express 10 (w10/1803) with signalr core 2.1. It always falls back to SSE. At first I assumed WS support wasn't enabled for iis express but I'm told it should be on by default. So it _seems_ my iis express install is just busted, but I can't be sure. This article doesn't help. If WS support is enabled by default on IIS Express, then the article needs to expressly state this, and list which platforms support it OOTB.

**Comment by Rick-Anderson** [comment]
@anurse or @BrennanConroy  please respond.

**Comment by anurse** [comment]
https://github.com/aspnet/Docs/pull/8621
