### ISSUE TITLE
fundamentals/dependency-injection.html "Dependency Injection"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#862]
- [ ]  Needs an edit pass. 
- [x]  Initially, the `IServiceCollection` provided to `ConfigureServices` has just a handful of services defined. - What services are defined? 
- [x] Constructor injection behavior #2068
- [x] compare with @exceptionnotfound [DI blog](https://www.exceptionnotfound.net/getting-started-with-dependency-injection-in-asp-net-core/) 
- [ ] Joe Audette  on DISQUS: might be good to add some guidance also for library authors on how best to implement their own IServiceCollection extensions. I figured out what I think is the right pattern but had some doubts and asked about it here [SO](http://stackoverflow.com/questions/37101455/best-practices-for-servicecollection-extension-methods) 
- [ ] cust asks:  I have a service with the following constructor:
   ```
   public MyServcice( String param).
   ```
  How do I make add my service in the IServicecollection since I need to be able to pass the parameter ?
- [x]  cust reports (and I verified) download link 404's.  Fix download link

Use this issue for all problems with the DI article.

edit example: Remove "Of course, in addition to configuring the application to take advantage of various framework features, you can also use ConfigureServices to configure your own application services." 

The very next section is "Registering Your Own Services"

**Comment by danroth27** [comment]
See https://docs.asp.net/en/latest/fundamentals/startup.html#services-available-in-startup for services available in startup. The DI article should link to that section

**Comment by Rick-Anderson** [comment]
@exceptionnotfound would love a PR from you on this or I could copy some of your blog and add you to the authors list.

**Comment by ardalis** [comment]
For the list of services, there's this, too, that I could merge in if you'd like:
http://ardalis.com/how-to-list-all-services-available-to-an-asp-net-core-app

IIRC I had a list way back in the beta8 days when this article was first published, but it was removed after review feedback.

**Comment by exceptionnotfound** [comment]
@Rick-Anderson I'm not 100% sure on how to do a PR on GitHub (we're not using it yet) so if you want to add pieces of that blog post to the docs and add me to the authors list, that'd be fine by me.

**Comment by ardalis** [comment]
#2481 addresses 2nd bullet.
