### ISSUE TITLE
Document how logging categories work in ASP.NET Core

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#8620]
We show in the Logging doc how to configure log levels for different logging categories, but we don't really describe what categories are available. We only show Microsoft and System. Since the categories are generally tied to the namespaces of the types that do the logging it might not be reasonable to document them all, but we could provide a table of commonly used categories. To generate this list I would suggest that we turn up logging to the Debug level and then pick the categories that look interesting and useful.

**Comment by guardrex** [comment]
@tdykstra

**Comment by danroth27** [comment]
Thanks @tdykstra! I think the categories table could be simplified a bit by collapsing rows under a common prefix and then summarize the various events under that category. I don't think you need to go any more than four levels deep into a category and you can probably drop the log level column. Something like this:

| Category | Description |
| ---------- | ------------ |
| Microsoft.AspNetCore | |
| Microsoft.AspNetCore.DataProtection | Which keys were considered, found, and used |
| Microsoft.AspNetCore.Hosting | How long HTTP requests took to complete and what time they started. Which hosting startup assemblies were loaded. |
| Microsoft.AspNetCore.Mvc | MVC and Razor diagnostics. Model binding, filter execution, view compilation, action selection. |
Microsoft.AspNetCore.Routing | Route matching information |
Microsoft.AspNetCore.Server.Kestrel | Connection start, stop, and keep alive responses. HTTPS certificate information. |
| Microsoft.AspNetCore.StaticFiles | Files served |
Microsoft.EntityFrameworkCore | Database activity and configuration, change detection, migrations. |

Daniel Roth
