### ISSUE TITLE
Invoke authentication before serving Angular app #8623

### ISSUE THREAD

**Issue by ejcastillo** [aspnet/Docs#8624]
Hi, my Angular app is part of network of privileged apps with SSO. Before serving the Angular app, I would like to check if the user is authenticated and if not redirect the user to the IdP. In the old templates you could protect the Home controller which would cause a redirect. In the current template, the only controller is the API controller which is hit after the Angular application has already been served. How can I invoke authentication before it is served? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@SteveSandersonMS please respond.

**Comment by SteveSandersonMS** [comment]
You can put ASP.NET Core middleware into your pipeline, above the `UseSpa` call, so that it redirects people elsewhere if they are not authenticated.

**Comment by ejcastillo** [comment]
@SteveSandersonMS is there a way to protect the SPA static files to ensure only authenticated users can see them? I am aware that static files are public by default (ex: wwwroot). My use case is a privileged Angular app that should only be served to authenticated users (ie the request for static files should be intercepted for authentication before it is served). What is the recommended way of achieving this using the Angular template? I implemented a policy of RequireAuthenticatedUser() which works great for all HTTP requests, but my fear is that the SPA static files are still accessible by directly entering their address. Your answer is much appreciated.
