### ISSUE TITLE
Guidance around changing environment variables in confusing

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#8635]
&gt; [!IMPORTANT]
&gt; When hosting an app in IIS and adding or changing the `ASPNETCORE_ENVIRONMENT` environment variable, use any one of the following approaches to have the new value picked up by apps:
&gt;
&gt; * Restart an app's app pool.
&gt; * Execute `net stop was /y` followed by `net start w3svc` from a command prompt.
&gt; * Restart the server.

Restarting an AppPool will only suffice if you set the environment variable on the AppPool. If you set a system-wide environment variable, that will not suffice. It's impossible to figure out from the docs are currently phrased.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceffa6a2-770c-1cd9-5145-dcd423f9dd22
* Version Independent ID: 1cb5eb30-dd84-e5e1-5826-d74243fabf04
* Content: [Use multiple environments in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1#windows)
* Content Source: [aspnetcore/fundamentals/environments.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/environments.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by shirhatti** [comment]
See https://github.com/aspnet/IISIntegration/issues/1401#issuecomment-422907167

**Comment by spottedmahn** [comment]
>Additionally, neither will restarting IIS via right click->stop->start in IIS manager

**Comment by guardrex** [comment]
@shirhatti I was going to move it to last and flesh it out. For example, I was drafting up something like ...

> * Restart an app's app pool. This approach only works if the environment variable is set on the app pool. This approach doesn't work for a system-wide environment variable.

... but I'm actually leaning toward just striking that option. Isn't it best if we just say to use the `net stop/net start` or restart the server for a general audience?
