### ISSUE TITLE
2.1 code

### ISSUE THREAD

**Issue by chaos520** [aspnet/Docs#8649]
Hi, I am having some errors by following this tutorial and I am using 2.1 as my development environment. I think something wrong somewhere by using 2.0 code in 2.1 therefore may I know when could we get the latest code base for this tutorial? The error that I got so far is during Instructor session. When I tried to test related function in Instructors section, edit does not get the previous values for date field and unable to update the latest values as well. For the create function while input all related fields and save, the null pointer error came out. I hope that your site could provide the latest code base instead of using 2.0 code base.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1#update-the-instructor-pages)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
See the top of that page where it states:

This tutorial demonstrates updating related data. If you run into problems you can't solve, download the completed app for this stage.

**Comment by chaos520** [comment]
I had downloaded the completed code but the code base is 2.0, I just worried that the code base is having huge difference between 2.1 and 2.0

**Comment by chaos520** [comment]
> I had downloaded the completed code but the code base is 2.0, I just worried that the code base is having huge difference between 2.1 and 2.0

I had changed the csproj version to 2.1 seems like it is working.

I will try to study the code instead. Thanks for reply.

**Comment by Rick-Anderson** [comment]
No, look in the 21 directory.
Use the 2.1 code

**Comment by Rick-Anderson** [comment]
Sorry, look at https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/cu21

I'll fix that link. Thanks for pointing this out.

**Comment by chaos520** [comment]
Hmm, I have viewed the section as well, Could we have the latest code base for part 6 to part 8.

**Comment by Rick-Anderson** [comment]
That link is the completed project for all parts in 2.1
We usually don't do snapshots as it's too much work to keep them out of date.

**Comment by chaos520** [comment]
Oh ok, I will review the code again. Thanks for blazing fast support.

**Comment by chaos520** [comment]
As I reviewed https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/cu21/Pages

The code is only available until part 5, hmm...

**Comment by Rick-Anderson** [comment]
I think that's because it didn't change after that. That explains why the links weren't updated.
