### ISSUE TITLE
prevDisabled : NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8651]
I have been stuck on this issue for days. (See #8316)

How/Where does HasPreviousPage get initialised as it is only set in the PaginatedList method, but when is Paginated list called? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 877f0457-37d9-9a34-e2ce-beb41d717086
* Version Independent ID: e9b0d4d1-e98c-fb96-415f-0ff4e37d3658
* Content: [Razor Pages with EF Core in ASP.NET Core - Sort, Filter, Paging - 3 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1#add-paging-functionality-to-the-index-method)
* Content Source: [aspnetcore/data/ef-rp/sort-filter-page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/sort-filter-page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Step through it with the debugger.

**Comment by Rick-Anderson** [comment]
Please don't create new issues for the same problem. You'll probably get a quicker response on a support forum like StackOverflow.
