### ISSUE TITLE
Azure AKS nginx ingress documentation

### ISSUE THREAD

**Issue by spacecat** [aspnet/Docs#8652]
It would be nice to see some docs describing how to configure an nginx-ingress in AKS when you for instance have two applications (both are ASP.NET Core apps), one host, two routes/paths (one for each app). And also how to configure the ASP.NET Core apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@shirhatti

**Comment by spacecat** [comment]
You're right. It's not ASP.NET Core specific but the example applications in the docs are very simple and don't reflect real world.
Also , since AKS is a Microsoft Kubernetes service one would expect some kind of guidance for Microsoft specific technologies. A lot of microsofts customers use their technologies and services exclusively and this is what they would expect.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
