### ISSUE TITLE
Deploy "dotnet new react" app on AWS

### ISSUE THREAD

**Issue by lasharela** [aspnet/Docs#8653]
I'm trying standard template to AWS elastic bean. I have no visual studio. Only visual studio code, so my only friend is dotnet CLI.

dotnet publish that's how I'm trying to publish my application. (I've also tried "dotnet publish -c Release -r win10-x64") but anyway - build requires npm installed on the server. Also, I checked ClientApp in publish directory and map.js file are included.

What's the point. Why I'm getting this error:

InvalidOperationException: The NPM script 'start' exited without indicating that the create-react-app server was listening for requests. The error output was:
Microsoft.AspNetCore.SpaServices.ReactDevelopmentServer.ReactDevelopmentServerMiddleware.StartCreateReactAppServerAsync(string sourcePath, string npmScriptName, ILogger logger)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by SteveSandersonMS** [comment]
> The NPM script 'start' exited without indicating that the create-react-app server was listening for requests.

This implies the problem is that you're still running in dev mode, not prod mode.

Once your app is published, it should not be trying to run the Create-React-App dev server. That won't be available in production.

To fix this, be sure your application runs in the Production environment: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1#development-staging-production
