### ISSUE TITLE
Upgrade to dotnet 2.1 broke the existing formatter

### ISSUE THREAD

**Issue by rahulswarnkar** [aspnet/Docs#8654]
If the action method returns a `Task<T>` asynchronously, context.ObjectType used to be `T` with netcoreapp2.0. Now it's `Task<T>` with netcoreapp2.1.
I had to change to:

```
public override bool CanWriteResult(OutputFormatterCanWriteContext context)
{
    return (typeof(T).IsAssignableFrom(context.ObjectType) || typeof(Task<T>).IsAssignableFrom(context.ObjectType)) && base.CanWriteResult(context);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by davidfowl** [comment]
cc @rynowak

**Comment by rynowak** [comment]
Are you using 2.1.3? We had an issue related to this that I'm pretty sure we patched.

**Comment by rahulswarnkar** [comment]
No, it's 2.1.0

**Comment by rahulswarnkar** [comment]
Thanks. I don't see the problem with 2.1.3.
