### ISSUE TITLE
Asp.Net Core 2.1.0-preview1-final: @Html.ActionLink() is not working for string.Format()

### ISSUE THREAD

**Issue by Raghumu** [aspnet/Docs#8655]
```
<div data-collapse class="left-justify" id="requirements>
  @Html.Raw(string.Format(@_stringLocalizer["RegisterNoticeMessage"], 
      @Html.ActionLink(@_stringLocalizer["RegisterLinkDisplayName"], "Register")))
</div>
```

In this piece of code, @Html.ActionLink() is returning Microsoft.AspNetCore.Mvc.Rendering.TagBuilder instead of returning anchor element containing URL path to the specified action. 
What's wrong in this code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
Why are you using preview for 2.1?

Can you repro this with one line of markup and the current released product?
