### ISSUE TITLE
ControllerBase instead of Controller

### ISSUE THREAD

**Issue by goodies4uall** [aspnet/Docs#8657]
I think the documentation needs to be updated to ControllerBase which is what comes from an empty web API project in .net core 2.1. Seems Controller would have a view and ControllerBase would not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f83a3b4-28f6-5f0f-a8bf-aef76f05fe42
* Version Independent ID: 0d0bc32b-5909-580f-1030-edbf1d3d9a68
* Content: [Migrate from ASP.NET Web API to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/webapi?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/webapi.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
You're correct. `Controller` will still work, but `ControllerBase` is the better option in this particular case. I'll get this updated next week.
