### ISSUE TITLE
Enhance attribute table in the ANCM config reference

### ISSUE THREAD

**Issue by pkzOR** [aspnet/Docs#8659]
Is there a way to set the startupTimeLimit to unlimited using 0, -1, or do we just set it to some large int?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module configuration reference](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.1#attributes-of-the-aspnetcore-element)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Do you really want it to hang forever? I'd set it to the largest int you can stand.

**Comment by guardrex** [comment]
3600 (1 hour) is the max value ...

https://github.com/aspnet/IISIntegration/blob/e1f1705d11d97560c574dbe68a0b560441470f58/src/AspNetCoreModuleV2/AspNetCore/aspnetcore_schema_v2.xml#L17

It looks like a value of 0 (zero) is not infinite timeout ...

https://github.com/aspnet/IISIntegration/blob/26964b268740150ee4aa77e6b3ddf695cbb4aaaa/src/AspNetCoreModuleV2/OutOfProcessRequestHandler/serverprocess.cpp#L561

@pakrym can confirm.

**Comment by guardrex** [comment]
@Rick-Anderson I'd like to increase the priority of this but leave it on the backlog for a closer look later. For example, our table doesn't have mix/max values or define if/when zero is zero or zero is infinite.

**Comment by guardrex** [comment]
@pkzOR Thanks for opening this issue. I'm going to change the title to broaden this issue out a bit.

**Comment by pkzOR** [comment]
It appears to me that if you set it higher than 3600, it defaults back to 120. Is that true?

**Comment by guardrex** [comment]
Yes. You can see that in action by manually changing the value in *web.config* (put some super-high value in there ... I put in 5000 for this example) and look at the configuration in the IIS Manager Config Editor ...

<img width="307" alt="capture" src="https://user-images.githubusercontent.com/1622880/45963449-d1531100-bfe8-11e8-8380-3191edfeec2f.PNG">

If you change it to a value within the range 0-3600 and refresh the config values (navigate away and back from the `aspNetCore` element in the UI), you'll see it pick up and display the valid value you set. I'll set it to `startupTimeLimit="300"` and refresh. It now shows ...

<img width="271" alt="capture2" src="https://user-images.githubusercontent.com/1622880/45963765-8980b980-bfe9-11e8-9511-feef580d8c13.PNG">

**Comment by pkzOR** [comment]
thanks... seems like if it's set too large, then it would default to the largest allowed.  Either way, thanks for looking at it.

**Comment by guardrex** [comment]
I guess in some meeting back in the ancient times of IIS development that they decided not to write the validation logic that way. I can wildly speculate that their reasoning may have gone along the following lines: If the admin/dev had a typo in the value (way too high or too small), it's safer not to assume the limit (the lowest or highest allowed value) and just go with the default (usually a modest value). From the 'typo error' perspective, I can see why they would have set it up the way that they did.

If you think it should be the logic for validation, you could open it as a suggestion at https://windowsserver.uservoice.com/forums/310252-iis-and-web-server-role ... the engineers and managers **_DO_** read and respond to those.
