### ISSUE TITLE
New doc: how publishing works

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Docs#866]
@danroth27 asked me to work on a doc which describes how VS Web Publishing works for ASP.NET 5 projects, as well as how to customize the script.

I'm working on a draft that I'll send out for review to @Rick-Anderson @Erikre and @rachelappel. Once that's completed we will submit the content here.

**Comment by sayedihashimi** [comment]
Thanks, FYI I emailed the current draft to those listed above.

**Comment by sayedihashimi** [comment]
I have the reviewed draft ready at https://www.dropbox.com/s/a96j67sqlgixi3v/web-publish-overview.docx?dl=0.

Can someone help convert to RST and submit a PR?

cc @robbert229

**Comment by robbert229** [comment]
I will convert it to rst.

**Comment by robbert229** [comment]
@sayedihashimi: Finished and made pr #881

**Comment by sayedihashimi** [comment]
@danroth27 can we merge?

**Comment by sayedihashimi** [comment]
Thanks a bunch @robbert229!

**Comment by Rick-Anderson** [comment]
@sayedihashimi we generally like to get a review of the PR and shipit before merging.

**Comment by Rick-Anderson** [comment]
@vijayrkn please review

**Comment by sayedihashimi** [comment]
Vijay already reviewed it.
