### ISSUE TITLE
What for JQuery?

### ISSUE THREAD

**Issue by harveytriana** [aspnet/Docs#8665]
The project loads JQuery in layout, the Site has JQuery in all pages - Why not use it in the examples? With JQuery things are greatly simplified. - Maybe I do not pose a question, but a suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22325a88-5e1d-7b54-87b7-ea331a6c73b6
* Version Independent ID: b92a4bf5-f7c9-50b9-d7d7-46ebcf7387b0
* Content: [ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
The sample does not use jQuery in any way. I think jQuery is just included in the template and wasn't removed when pushing the sample.

I assume you're talking about https://github.com/aspnet/Docs/tree/master/aspnetcore/tutorials/signalr/sample

**Comment by harveytriana** [comment]
It is right. JQuery is essential, since Bootstrap requires it. So, it is natural to write the client-side code using JQuery. Infinitely simpler and more intuitive. It's just an opinion. Thanks for your answer.

**Comment by scottaddie** [comment]
Nothing prevents you from using jQuery. It's all a matter of preference. We prefer plain old JavaScript in the SignalR samples, since the jQuery dependency was removed from the JavaScript client. See https://docs.microsoft.com/aspnet/core/signalr/version-differences?view=aspnetcore-2.1#jquery.
