### ISSUE TITLE
Global vs Local Angular CLI

### ISSUE THREAD

**Issue by EdSF** [aspnet/Docs#8666]
Disclaimer: New to VS 2017 Angular templates.

Message when running ng commands:
Your global Angular CLI version (6.2.3) is greater than your local
version (1.7.0). The local Angular CLI version is used.

While I haven't experienced issues (so far), perhaps detail on this can be added to this doc(?) Searching the interwebs, I sort of get it, but whether or not I *need* to do anything because of this discrepancy needs clarification, particularly because this is in the context of a Visual Studio ASP.Net Core app + Angular (vs. a "pure"Angular project via command line) . Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?tabs=visual-studio&view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by SteveSandersonMS** [comment]
It's not an issue. It genuinely just means you have a different version of the tool installed globally, but that's not going to affect your project because it will use the local installation. No problems will occur.
