### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by liricy** [aspnet/Docs#8667]
# Issue description
Getting CORs issue when calling APIs:

![inkedupload a submission 403 error_li](https://user-images.githubusercontent.com/6519992/45924744-4248da80-bebc-11e8-894d-ce7ec3b549a2.jpg)

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core 2.1.402
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by guardrex** [comment]
Hello @licypal ... How did you set the origin? The most basic set up is ...

```csharp
app.UseCors(builder =>
       builder.WithOrigins("https://XXXXXX.sharepoint.com"));
```

If it looks like you set it up properly according to the topic, then open an issue on the [aspnet/Home issues](https://github.com/aspnet/Home/issues) so that the engineers can take a look.

When you find out what the problem is, please post back here. We might need to improve the topic a bit to head off the problem in the future.

**Comment by guardrex** [comment]
I wonder if that wildcard subdomain is supported with the middleware. @pranavkm

**Comment by guardrex** [comment]
Can u try ...

```csharp
allowedOrigins.Add("https://sharepoint.com");
```

**Comment by licypal** [comment]
Sure. Will try that. How does it differ from https://*.sharepoint.com?

**Comment by licypal** [comment]
I still see the same issue.

**Comment by guardrex** [comment]
Ok ... go ahead and open on aspnet/Home issues for the engineers to take a look. cc: @guardrex ... I'll follow along.

**Comment by guardrex** [comment]
https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.cors.infrastructure.corspolicybuilder.setisoriginallowedtoallowwildcardsubdomains

> configured wildcarded domain when evaluating if the origin is allowed.

"configured wildcarded domain" ... I probably guessed wrong. Either way, the doc is missing coverage, and we'll get it updated when we find out what the story is.

**Comment by guardrex** [comment]
Add a *Troubleshooting* section and call out verbose logging.

https://github.com/aspnet/Home/issues/3549#issuecomment-424741299

**Comment by licypal** [comment]
How do I check that?

**Comment by guardrex** [comment]
@licypal Logging guidance :point_right: https://docs.microsoft.com/aspnet/core/fundamentals/logging

**Comment by guardrex** [comment]
When they said "verbose," it's really `LogLevel.Trace` ... 

https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.loglevel

You can set it in your *appsettings.json* file for the `Default` key. Then, just check your console log as the app runs. If you don't want to monitor apps with console logs, implement a 3rd party provider.

https://docs.microsoft.com/aspnet/core/fundamentals/logging#third-party-logging-providers
