### ISSUE TITLE
Show how to bind options to a specific config section

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#867]
We should add some text to http://docs.asp.net/en/latest/fundamentals/configuration.html#options-example that shows how to bind options to a specific config section instead of to the root configuration. Something like this:

``` c#
    // Configure MyOptions using config
    services.Configure<MyOptions>(
        Configuration.GetSection("MyOptions"));
```

This pattern allows you to group option settings into specific sections.

**Comment by Rick-Anderson** [comment]
fixed via #2346
