### ISSUE TITLE
What is "app's executable" in this document?

### ISSUE THREAD

**Issue by melmi** [aspnet/Docs#8674]
Hi,

This question might be so dumb, but what is the meaning of "app's executable" in this document?

**Comment by guardrex** [comment]
Hi @melmi ... Which document are you referring to. Note that there is a "Content Feedback" button at the bottom of each topic. When an issue is created that way, it tags the issue with the info.

> app's executable

It just means the `.exe` executable file for the app.

**Comment by melmi** [comment]
Ok. I continue using document feedback.
[This](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x) was the document I was referred to.
