### ISSUE TITLE
There is no completed app sample for Core 2.1?

### ISSUE THREAD

**Issue by kosmickanga** [aspnet/Docs#8675]
The link to "download or view the completed app" goes to https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples, where there does not appear to be a completed version of the app. Within this folder,  cu21 only has Students pages so is missing Instructors etc, whereas 21StageSnapShots only goes up to stage-5.  All the other folders appear to contain projects targeting netcoreapp2.0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@kosmickanga That's because the code hasn't changed for 2.1.
You can use the 2.0 code and update the project to 2.1.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
