### ISSUE TITLE
It;s nice to know it just crashes on it's own...

### ISSUE THREAD

**Issue by k3ldar** [aspnet/Docs#8677]
"automatically start after reboots and crashes without requiring human intervention"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @k3ldar ... Do you have a problem that you would like to report? If you have a failing WS, set it up to run as a console app: See the [sample app](https://github.com/aspnet/Docs/tree/master/aspnetcore/host-and-deploy/windows-service/samples) and follow the guidance in the [Provide a way to run outside of a service](https://docs.microsoft.com/aspnet/core/host-and-deploy/windows-service#provide-a-way-to-run-outside-of-a-service) section. Run it as a .NET Core app; not as a service. Usually (with logging), this will show how the app is failing.

**Comment by Sebazzz** [comment]
@guardrex It is just that the wording is a bit odd:

> When hosted as a Windows Service, the app can automatically start after reboots and crashes without requiring human intervention.

"Well... nice" would be my first response. 

I'd drop the "without requiring human intervention" completely. This is already what *automatically* implies.

**Comment by guardrex** [comment]
I both *agree* and *disagree*. :smile: The phrase is just *conversational* in nature. We have guidance from management to speak conversationally with readers in these topics, so this language is permitted per the guidelines. It's grammatically correct and technically accurate given the role of the Service Control Manager. However, we also have guidance to be *concise*; and as you suggest, this could be shortened.

🤔 ... I think given that Tom or Sourabh wrote the sentence this way, I'd like to keep it.

**Comment by scottaddie** [comment]
@guardrex I think the text does need a little work. As it's written, we're implying that crashing is a feature of the product. 😄 At least, that's how it reads to me. @tdykstra Thoughts on new wording for this sentence?

**Comment by Sebazzz** [comment]
What about:

> When hosted as a Windows Service, the app can automatically start after reboots and recovers from  crashes without requiring human intervention.

Or:

> When hosted as a Windows Service, requiring human intervention, the app can automatically (re)starts after reboots and crashes.

**Comment by guardrex** [comment]
First one is ok, but since Tom likes ...

> When hosted as a Windows Service, the app can automatically start after reboots.

I'd recommend taking Tom's advice. *In Tom We Trust!* ... I think it's a logger message somewhere in the framework. :smile:

**Comment by k3ldar** [comment]
The first one hits the mark, for me :-)

**Comment by guardrex** [comment]
Ok, but submit the PR with "and recover" ... "app" is singular.

> When hosted as a Windows Service, the app can automatically start after reboots and recover from crashes without requiring human intervention.

**Comment by guardrex** [comment]
mmmmmm 🤔 ... changed my mind. lol ...... I recommend following Tom's advice.
