### ISSUE TITLE
dbo.Movie not in Databases folder - MvcMovie web app MVC

### ISSUE THREAD

**Issue by jeremybowden73** [aspnet/Docs#8678]
Hi,
I'm following the ASP.NET Core 2.1 we app with MVC tutorial. It's going great until I open SQL Server Object Explorer (SSOX).
In the Databases folder there is no MvcMovieContext db. All I see are four dbs - master, model, msdb and tempdb.
The Movie db must be somewhere because I can seed it, re-build, and the app opens in the localhost browser with the seeded data.
I've searched the whole of the C:\Users\xxx\ folder for *dbo* and *movie* but without any luck.
Any help with where the db is please?
Thanks.

**Comment by jeremybowden73** [comment]
Hi.
It's working now, thanks.
But I don't know why. Reloading the view in SSOX didn't update anything, I had to close the solution and re-open it.

But thanks :)

**Comment by guardrex** [comment]
Yes, that does seem strange. I haven't seen this behavior, but I don't work with enough SQL Server dBs in our doc samples to have noticed. Most of our sample apps run on the EF Core in-memory provider.

I'll close this since it seems somewhat resolved. We can re-open and discuss further if this is an on-going problem and repros more widely.

**Comment by swinnersmusic** [comment]
Hi 
I have exactly the same problem as Jeremy: I cannot find the database in the SSOX view just the four dbs - master, model, msdb and tempdb.
My pic shows the connection string and it places the database where you can see in in the Solution Explorer as shown in my pic.
Please help
I need to learn how to make a new field inside the MVCMovie.db 
I can find this file in windows explorer but cannot explore inside the database from there. 
The tutorial I am following talks about the Database having a .mdf file extension. No such file exists.
Please help its driving me crazy 
Alan Swinburne
![git problem](https://user-images.githubusercontent.com/3308568/78514124-aa61c780-77a7-11ea-9dec-0e2789b0d45c.PNG)
![git problem](https://user-images.githubusercontent.com/3308568/78514144-c36a7880-77a7-11ea-958e-b7c726c1b9dc.PNG)
