### ISSUE TITLE
Setting up nginx reverse-proxy when using ADAL auth

### ISSUE THREAD

**Issue by yohanb** [aspnet/Docs#8679]
Hey,
I think it would be a good idea to the necessary configuration to the nginx reverse proxy for it to work with ADAL authentication since it's a pretty common use case.
By default, nginx will not accept the signin-oidc response since the header is too big.  Please see the following post for the necessary config:
https://medium.com/@mshanak/solve-nginx-error-signin-oidc-502-bad-gateway-dotnet-core-and-identity-serve-bc27920b42d5
Cheers!
Yohan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @yohanb

@shirhatti Should we schedule this?

**Comment by shirhatti** [comment]
I've been burned by this myself in the past, but I believe it was security review that forced us to be far more conservative with suggestions of buffer sizes.

That being said, you shouldn't require changing `fastcgi_*` settings, only `proxy_*`

**Comment by yohanb** [comment]
> I've been burned by this myself in the past, but I believe it was security review that forced us to be far more conservative with suggestions of buffer sizes.
> 
> That being said, you shouldn't require changing `fastcgi_*` settings, only `proxy_*`

Well that's great advice which you should probably include in the doc so people don't wind up with potential security risks following other people's blog posts.

Another option is to setup `CookieAuthenticationOptions.SessionStore` in the auth middleware so the cookie doesn't bloat the header size.

**Comment by Julian89757** [comment]
> However, Nginx isn't set up to manage the Kestrel process. systemd can be used to create a service file to start and monitor the underlying web app. 

nginx does not manage the kestrel, systemd can used to managed kestrel .
so  systemd do not set up  relationship with nginx ???

The [Monitor the app ] section  hav nothing to do with nginx???
