### ISSUE TITLE
Dropdown/Selectlist missing

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8694]
Hi Rick. Could you please include a section on how to use a dropdown list that gets its data from a related table. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f32b67-7418-7f82-c813-c11650bb39a7
* Version Independent ID: 3e28328b-9c7a-359b-2f57-319b0bc7eea3
* Content: [Create a Razor Pages web app with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by NatanRibeiro** [comment]
Hello Guys, I have been trying to do a overload on my page, but it looks like it's not possible. 
To do that I'm using nullable variables on my method.
What's the best way to do that?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
