### ISSUE TITLE
MS needs to SERIOUSLY look at renaming the product.

### ISSUE THREAD

**Issue by lm28** [aspnet/Docs#8695]
The number of times that I search for help related to 'ASP.Net Core2'+'Razor' only to get results or redirection to MVC is INSANE! Its almost impossible to find RAZOR only help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f32b67-7418-7f82-c813-c11650bb39a7
* Version Independent ID: 3e28328b-9c7a-359b-2f57-319b0bc7eea3
* Content: [Create a Razor Pages web app with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tdykstra 	please review

**Comment by Rick-Anderson** [comment]
Google on 
asp.net core 2.0 razor
works pretty good.

**Comment by tdykstra** [comment]
Confirmed -- first search results page is all Razor resources, both for the search phrase you cite and for  'ASP.Net Core2'+'Razor' .  Might be helpful if we could get the actual search keywords and search engine used that results in links to MVC resources; also, redirections were mentioned - it would be good to know the source and target URLs of the redirections.
