### ISSUE TITLE
Securing your secrets

### ISSUE THREAD

**Issue by rhires** [aspnet/Docs#8696]
The link for "more secure and robust location" only shows how to save secrets in development, and makes sure to say that this isn't secure. I would expect "more secure and robust location" to say what "more secure and robust location" is, where it is, and what needs to be done. For example, what about encrypting the data in a file that the application can decrypt at runtime? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9248d17-88df-6a27-9950-fa1d9ade6e5d
* Version Independent ID: 37d8648e-9b65-ae25-24af-d70e5c9473fd
* Content: [Migrate configuration to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/configuration.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
