### ISSUE TITLE
Error when building SessionSample - HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by mayatstafford** [aspnet/Docs#8698]
I"m running VS Pro 2018 15.8.   I downloaded the sample from here: 
Docs/aspnetcore/fundamentals/app-state/samples/2.x/SessionSample/

When I build I get this error: 
HTTP Error 502.5 - Process Failure 

Please advise, thank you.

**Comment by guardrex** [comment]
Hello @mayatstafford ... It was updated and running as of June. I'll run it here now and get back to you shortly.

**Comment by guardrex** [comment]
Seems to be running fine here. I checked in both VSC and VS.

Follow the advice in the troubleshooting topic to see if you can determine why it isn't running there.

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/troubleshoot

That assumes that you're troubleshooting an IIS scenario. You didn't say how you were hosting.

**Comment by mayatstafford** [comment]
I'm running locally on VS, after I installed .NET Core SDK this worked.   Thank you.
