### ISSUE TITLE
Claims-Based Authorization

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#87]
ASP.NET 5 -> Security -> Authorization -> Claims-Based Authorization

**Comment by shaunluttin** [comment]
I have been considering contributing an article on the **Resource Owner Password Flow**. You can see the emerging sample project [here](https://github.com/bigfont/AspNet.Security.OpenIdConnect.Server/tree/bigfont/samples/ResourceOwnerPasswordFlow).  I've been dialoging with @PinpointTownes about it. It looks like @danroth27 may already be working on something like this. What do you all think about having another HowTo or Walkthru on the topic, particularly focusing on using OpenID Connect with the Resource Owner Password Flow?

**Comment by danroth27** [comment]
I think that would be great. I don't have anything in progress at this point so these topics are fair game. Do want to create an issue for the new topic and propose an outline?

**Comment by shaunluttin** [comment]
Sure. I can create an issue and propose an outline. Thanks for getting back to me so quickly. I appreciate that.
