### ISSUE TITLE
Distributed cache topic UE pass

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#8702]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d01025d-86b2-bb2d-86c1-ef0695bc98e3
* Version Independent ID: 5b9a6572-3671-0d54-b2ef-83d04f8b3e96
* Content: [Work with a distributed cache in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1)
* Content Source: [aspnetcore/performance/caching/distributed.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/performance/caching/distributed.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@Tratcher Can u give me a tip here ...

The current topic+sample goes with a `ConfigureDevelopmentServices`, `ConfigureStagingServices`, and `ConfigureProductionServices`. I get it, but showing devs too many ways of doing things ... not being opinionated enough ... is making this (and other topics) too complicated imo for devs coming to Core for the first time. If the environment is set on a property in `ConfigureAppConfiguration` or injected into `Startup` for a local var, we could use `ConfigureServices` with a conditional for these environmental caching configurations.

Should I retain the barely explained/rarely seen `Configure{Environment}Services` approach, or go with an environment local var or property and conditional? If the latter, can we look down the road to the Generic Host for guidance on what to show? Shouldn't we show the following approach ... the **_Nutjob Pattern_**:tm: :smile: [and given that `CreateDefaultBuilder` isn't a thing (yet) for the Generic Host ... you said something like it might be built later; let's make my example here for Web Host] ...

```csharp
public static IHostingEnvironment Environment { get; set; }

public static IWebHostBuilder BuildWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureAppConfiguration((hostingContext, config) =>
        {
            Environment = hostingContext.HostingEnvironment;
        })
        .ConfigureServices(services =>
        {
            if (Environment.IsDevelopment())
            {
                // Development
                services.AddDistributedMemoryCache();
            }
            else
            {
                // Staging/Production/Whatever
                services.AddDistributedSqlServerCache(options =>
                {
                    options.ConnectionString = 
                        @"Data Source=(localdb)\v11.0;Initial Catalog=DistCache;" +
                        @"Integrated Security=True;";
                    options.SchemaName = "dbo";
                    options.TableName = "TestCache";
                });
            }
        }
        ...
```

Whatever we do with examples for environmental service registrations, I think we should do it **one way** (the most common way/the recommended way/the simplest way) across the docs.

**Comment by Tratcher** [comment]
Call the overload of ConfigureServices that gives you the HostingContext.

**Comment by guardrex** [comment]
```csharp
public static IWebHostBuilder BuildWebHostBuilder(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .ConfigureServices((hostContext, services) =>
        {
            if (hostContext.HostingEnvironment.IsDevelopment())
            {
                // Development
                services.AddDistributedMemoryCache();
            }
            else
            {
                // Staging/Production/Whatever
                services.AddDistributedSqlServerCache(options =>
                {
                    options.ConnectionString = 
                        @"Data Source=(localdb)\v11.0;Initial Catalog=DistCache;" +
                        @"Integrated Security=True;";
                    options.SchemaName = "dbo";
                    options.TableName = "TestCache";
                });
            }
        }
        ...
```

**Comment by Tratcher** [comment]
Lovely. :shipit:

**Comment by guardrex** [comment]
@Tratcher One more ❓ ...

The current orders (AFAIK) from management (DE?, DR?) is that we are to use a `Startup` class for all samples (except for the Generic Host sample). I even created a few repo samples in *ancient times* (a year or two ago :smile:) using the extension methods approach before I was ordered to go with a `Startup` class everywhere.

You remarked briefly on one of the issues (I think a Generic Host discussion) that moving to the extension methods everywhere might be a good alternative ... or under consideration as a recommendation ... or something along those lines.

Has there been a ruling yet to go away from `Startup` classes and start using the extension methods everywhere in samples? ... or is that under discussion?

I ask because if management has said *'make it happen,'* then I'd like to go ahead here with the extension methods (:heart:) for this Distributed Cache sample and other samples that I'll be working on in the coming weeks.

**Comment by Tratcher** [comment]
Hold off, we're revisiting this in 3.0 as part of moving WebHost onto GenericHost.

**Comment by guardrex** [comment]
Ok, thanks.
