### ISSUE TITLE
Confirm middleware order notes appear in individual topics

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#8706]
From a discussion on Slack: Check middleware scenario topics and confirm that the order notes from ...

https://docs.microsoft.com/aspnet/core/fundamentals/middleware#built-in-middleware

... are present in the individual topics.

**Comment by Rick-Anderson** [comment]
@guardrex 	should we close this or promote to P1 + P2

**Comment by guardrex** [comment]
Let's close. I have a ton of higher priority work to do. This was a 'good idea if we have time' thing to check. I don't have time in the foreseeable future to address this.
