### ISSUE TITLE
Generated applicationUrl in launchSettings.json causes a System.InvalidOperationException

### ISSUE THREAD

**Issue by eddyvdaker** [aspnet/Docs#8709]
When creating the project (at least on Arch Linux) it creates the application settings for TodoApi which includes a https applicationUrl.
```   
"TodoApi": {
	"commandName": "Project",
	"launchBrowser": true,
	"launchUrl": "api/values",
	"applicationUrl": "https://localhost:5001;http://localhost:5000",
	"environmentVariables": {
		"ASPNETCORE_ENVIRONMENT": "Development"
	}
}
```
Which throws a System.InvalidOperationException. Removing the https url from the applicationUrl fixed this. This is not mentioned in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@scottaddie 	 how are we doing on the Linux cert topic?

**Comment by Rick-Anderson** [comment]
@eddyvdaker 	we don't want to encourage using HTTP in-lieu of HTTPS.
This is tracked in #6199
