### ISSUE TITLE
What is "app's executable" in this document?

### ISSUE THREAD

**Issue by melmi** [aspnet/Docs#8710]
Hi,

This question might be so dumb, but what is the meaning of "app's executable" in this document? I am asking this because in my case, developing a web API, the output of the project is a single DLL. Should I use `dotnet &lt;app_assembly&gt;.dll` instead of `./&lt;app_executable&gt;`? If yes, I think it is better to mention it explicitly in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Excellent point @melmi ... you're correct. Use the `dotnet` command with the DLL. I'll fix the topic when I get back from vacation. 🏖

**Comment by BlueMarmalade** [comment]
this goes for normal applications too. So run "dotnet yourappname.dll" in bash to start it. But this might only work if you have the sdk installed on the server(i'm not sure if it works if you only have the runtime)?

**Comment by BlueMarmalade** [comment]
I can't get it to start by typing ./myappname.dll in bash. I can by typing: dotnet myappname.dll  But when I write the systemd service, it won't start probably for this same reason. So in the service file the ExecStart path to the dll is not working for me.  i get error: (code=exited, status=203/EXEC)

**Comment by guardrex** [comment]
Thanks for the notes @BlueMarmalade.

@shirhatti Do you want me to change the path from `/var/aspnetcore/hellomvc` to `/var/www/hellomvc` on this update?

Either way, we should remove/swap "mvc" given the focus on RP now. How about just `helloapp` and `kestrel-helloapp.service`?

**Comment by BlueMarmalade** [comment]
yes, because having two different locations for the app on a server is confusing. usually i only have a publish folder for my apps, which is in /var/www/appname.

**Comment by guardrex** [comment]
@BlueMarmalade This topic was written by @shirhatti, so I want to make sure he's cool with the change.

According to web sources, tthe default web root is actually `/var/www/html`, so we might want to make it `/var/www/html/helloapp`.

Source: https://help.ubuntu.com/lts/serverguide/httpd.html

> The `DocumentRoot` directive specifies where Apache2 should look for the files that make up the site. The default value is `/var/www/html`, as specified in `/etc/apache2/sites-available/000-default.conf`.

**Comment by BlueMarmalade** [comment]
Maybe. But I don't think it makes sense to put your app into the html directive. Many of the docs for Apache has bad practices, like putting sites into the /sites-available and /sites-enabled directives. These folders can be affected by upgrades to nginx. Putting the app into the html directive is also a bit strange to me, because for me html is a specific markup format. So reading on the docs at Linode.com for nginx they recommend putting it into the /var/www/ directive and create a directive for your app with the name of it's url. So it would be something like this: /var/www/yourapp.com  
[https://www.linode.com/docs/web-servers/nginx/nginx-installation-and-basic-setup/](url)

**Comment by shirhatti** [comment]
> Do you want me to change the path from `/var/aspnetcore/hellomvc` to `/var/www/hellomvc` on this update?

No preferences

**Comment by guardrex** [comment]
Ok ... so my action items for the update are:

1. Fix the `./<app_executable>` bit.
1. Drop "mvc" from naming and go with "app."
1. Let's go with `/var/www/helloapp`.
1. Apply similar updates to the Apache topic.

I'll be back from vacation shortly and push this forward. Thanks all! 🎸
