### ISSUE TITLE
Hosting ASP.NET Core on Full .NET Framework with IIS

### ISSUE THREAD

**Issue by fowl2** [aspnet/Docs#8711]
This article seems to be talking exclusively about .NET Core. eg. states `The bundle installs the .NET Core Runtime, ` .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @fowl2 ... That's correct. This topic pertains to hosting ASP.NET Core apps on IIS. ASP.NET Core is a different implementation of .NET than .NET Framework. See: [Comparison with .NET Framework](https://docs.microsoft.com/dotnet/core/about#comparison-with-net-framework)

**Comment by fowl2** [comment]
Thanks for the confirmation!

So I guess I have two asks then: 

1. This article should make clear which runtime it is targeting.
2. Information on how to run [ASP.NET Core targeting .NET Framework](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.1#aspnet-core-targeting-net-framework) be added (or split into a new page)
