### ISSUE TITLE
How to change configuration in integration tests

### ISSUE THREAD

**Issue by mattfrear** [aspnet/Docs#8712]
We are using a custom WebApplicationFactory&lt;&gt; for running integration tests. 
I wish to change the configuration of my system under test (my api), i.e. override a value in appsettings.json from within my WebApplicationFactory. I can't see anywhere here where changing the configuration of the system under test is described on this page, or have I missed it?

A footnote, or how I solved my problem:
I came across builder.UseSetting() which looks like it should do what I want, but doesn't seem to work.

I eventually got it to work by calling builder.ConfigureAppConfiguration and adding an in-memory collection, like so:
```csharp
        public void OverrideConfiguration(IWebHostBuilder builder, IEnumerable<KeyValuePair<string, string>> configurationValues)
        {
            builder.ConfigureAppConfiguration((_, configurationBuilder) =>
                configurationBuilder.AddInMemoryCollection(configurationValues));
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Updates for config by environment were rejected on https://github.com/aspnet/Docs/issues/8917 and https://github.com/aspnet/Docs/pull/9060.
