### ISSUE TITLE
Up-to-date?

### ISSUE THREAD

**Issue by pvanroos** [aspnet/Docs#8718]
Are these instructions up-to-date?  Should i use it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdbdf1ed-c52a-3be8-1f41-aecbdab0883b
* Version Independent ID: d06996cc-14aa-96e2-fd62-9d5bbc059107
* Content: [Create backend services for native mobile apps with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mobile/native-mobile-backend?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mobile/native-mobile-backend.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mobile/native-mobile-backend.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
The sample app is old (1.x) but tracked for update by https://github.com/aspnet/Docs/issues/5495.

You would need to follow the migration topics to upgrade the sample app. https://docs.microsoft.com/aspnet/core/migration/

**Comment by pvanroos** [comment]
Thx.  I'm looking for guidance on Authentication of Xamarin built native app.  My hope is to build to build a service that handles auth for all of my apps and host on Azure.

**Comment by guardrex** [comment]
... actually ... that looks **_so good_** that I think it should be linked. I'll shoot it in from *the beach* 🏖. (I'm on vacation! lol)
