### ISSUE TITLE
No need for IBackgroundTaskQueue interface

### ISSUE THREAD

**Issue by mcintyre321** [aspnet/Docs#8732]
Please don't encourage the creation of single-implementation interfaces. They are the scourge of c# codebases

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3460b0d-9c60-3a06-ac63-18cf990e53c3
* Version Independent ID: b2dece1f-15b8-03af-6d52-7cc070432b4b
* Content: [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/hosted-services.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/hosted-services.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by mcintyre321** [comment]
You can mock the BackgroundTaskQueue perfectly well, all the properties are virtual.

**Comment by mcintyre321** [comment]
Sorry, I've was a bit snarky above, and to cap it all, incorrect. How gauche! Sorry.

I do think that it's definitely debatable if interface-per-class-to-enable-testing is a good or bad practice, and code from MS is often considered best practice, so I'd prefer to see the samples not to have these interfaces. On the other hand, it's your code, and you're doing a great job providing samples and docs, and none of my business, so I'll, with respect, close my issue.

**Comment by vanthoainguyen** [comment]
Changing a method from none virtual to virtual just to mock/test is also a scourge in the code base. I think having that queue interface allows whoever want to switch to a real broker rather than in-memory queue :)
