### ISSUE TITLE
I am trying to implement OAuth Selfhost google authentication in C# console application but redirects me to http://localhost:8090/signin-google...

### ISSUE THREAD

**Issue by BDChaudhari90** [aspnet/Docs#8735]
I am trying to implement oauth google authentication for c# console web api. I have implemented all the settings into https://console.developers.google.com but I think there is something missing into this

Application starts using below code
```
 using (var app = WebApp.Start<Startup>("http://localhost:8090"))
            {
                Process.Start("http://localhost:8090/api");
                Console.WriteLine("Close this window to stop this server");
                Console.ReadLine();
            }
```
It then check for authentication if not then redirect to google sign in page and once successfully signed into google it redirects request to 
http://localhost:8090/signin-google?state=AQAAANCMnd8BFdERjHoAwE_Cl-sBAAAAx08Y4xymBk-qsr7vNJ4HnwAAAAACAAAAAAAQZgAAAAEAACAAAACu7I4kK7kF0t9TXtDtNnPh6CsuliPuUTVP3b-dlO6XrQAAAAAOgAAAAAIAACAAAAB76rDr-qWpY843RobXDShiaIhIPG_Mil2pkpGDmfb6G3AAAAC60YSEORiYkV5cjHas6GfQO4uNVkcrmn35Oi5b5Tm5EQIP-P1xf2BVRt_8Uz0I6pc5fJdH5g8uaNQfO8tmPmjjx5oyp3mqHeieiQcQZtRIdxbUZ--UvfBi_inHllnVdjeKqeLrj9YmOKPAS7gSA56LQAAAAITwoFOB-PzNhbExKd8BRT-8PjZDDXErODe9yP7AEqIOprxBFcozMD4EPxz_fr3Ka0NSO0Y2D8ONJUInWgm0NRc&code=4/ZwD8jenv3uK5NIj_BdLuwyXbdBCn6Keip3WdNBU_AwKWb4Rl9UPBiA99nS58pdP_5_GXPxS0E1zEaLuLp_emwKM&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile+https://www.googleapis.com/auth/plus.me&authuser=0&session_state=84c6a4254fa0603e07d986f31d9e5a3a32e84f2b..93c1&prompt=none

With error as "localhost is currently unable to handle this request."

Please help me to solve this out.

Did I missed any settings into google or at code level ??

**Comment by Rick-Anderson** [comment]
What's a console web api?

Cam will be working on this topic soon. See #4556
