### ISSUE TITLE
Need separate File Uploads topic for Core WebAPI2.1

### ISSUE THREAD

**Issue by zhenweied09** [aspnet/Docs#8742]
[As a beginner of Core2.1 WebAPI, I want to know how to download/ upload multiple images. 

Unfortunately I can not find out the desired topic related in either the WebAPI section or any other sections, except the “File Uploads” in MVC.

The recommended approach for multiple files Uploads is using IEnumerable<IFormFile> or List<IFormFile> is not working in Core WebAPI 2.1 somehow instead of keeping responding 400 errors. 

After days of investigation on the API reference document I solved the problem by using IFormFileCollection instead. 

So there should be a separate topic of. File Uploads in the WebAPI sections instead of just in MVC, or some more explanation of the difference between IEnumerable<IFormFile> or IFormFileCollection. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by zhenweied09** [comment]
[HttpPost("Photos")]
    public async Task<IActionResult> UploadPhotosAsync(List<IFormFile> files)
    {
        long size = files.Sum(f => f.Length);
        var fileFolder = Path.Combine(_env.WebRootPath, "Photos");

        if (!Directory.Exists(fileFolder))
              Directory.CreateDirectory(fileFolder);

        foreach (var formFile in files)
        {
            if (formFile.Length > 0)
            {
                var fileName = DateTime.Now.ToString("yyyyMMddHHmmss")+
                               Path.GetExtension(file.FileName);
                var filePath = Path.Combine(fileFolder, fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await formFile.CopyToAsync(stream);
                }
            }
        }
        return Ok(new { count = files.Count, size});
    }
}

---------------------
Error:

Microsoft.AspNetCore.MVC.Infrastructure.ObjectResultExecutor[1]
Executing ObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.SerializableError'.

**Comment by guardrex** [comment]
Hello @zhenweied09 ... Thanks for commenting. There's an open issue to address the file uploads topic at: #5331. Let's leave this open, and I'll add it to the list there. I don't think the subject of Web API would call for a separate topic, but the doc author can make that determination when it comes time to work that issue.

**Comment by Rick-Anderson** [comment]
For file uploads, you'd normally want an UI - so Web API wouldn't be the right place. Closing issue.
