### ISSUE TITLE
Reconstitute content on hosting bundle runtime-only-install flag

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#8748]
Cross-ref: **Is there a standalone installer for ANCM; i.e., without .NET Core runtime?** https://github.com/aspnet/IISIntegration/issues/1455

@shirhatti @joeloff Are we adding any other flags in addition to the no-runtime flag?

```
OPT_NO_RUNTIME=1
```

Cross-references:

* https://github.com/aspnet/Docs/issues/5454
* https://github.com/aspnet/Docs/pull/5546

cc: @jkotalik 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by joeloff** [comment]
No separate ANCM installer. In 2.2, the hosting bundle supports

OPT_NO_ANCM=1 (Skip ANCM install)
OPT_NO_RUNTIME=1 (Skip .NET Core runtime install)
OPT_NO_SHAREDFX=1 (Skip ASP.NET Shared framework, aka ASP.NET runtime install)
OPT_NO_X86=1 (Skip install x86 runtimes, ancm on 64-bit OS)
