### ISSUE TITLE
Inaccurate statement on bundleconfig.json

### ISSUE THREAD

**Issue by EdSF** [aspnet/Docs#8758]
RE: "The MVC and Razor Pages project templates provide a bundleconfig.json configuration file "

VS Studio 2017 v15.8.5: Creating a new .Net Core MVC app from scratch using MVC template does *not* have that file (the only json file is `appsettings`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by EdSF** [comment]
Whoops, this actually has prior long story: #7090 
I get it, so perhaps just change the document that has the quoted statement (or just say, _add it manually_).

**Comment by KSib** [comment]
So I assume it just should be added to the root of the project?

**Comment by frankodoom** [comment]
Best way to go about this is to consume it from Gulp. Install the bundle minify tool convert your buildconfig.json to a gulpfile open the task runner and run the build.config tasks

**Comment by Magiel1975** [comment]
Thanks for the help. Small correction. The file name is bundleconfig.json in stead of buildconfig.json
