### ISSUE TITLE
Information about `scripts` element of `project.json`

### ISSUE THREAD

**Issue by johnnyreilly** [aspnet/Docs#876]
Hi,

Unless I've missed it there doesn't seem to be a good resource about the `scripts` element of `project.json`.  There's [this](https://github.com/aspnet/Home/wiki/Project.json-file#scripts) which says:

> Events that you can hook to run scripts for kpm actions:
> ```
{
  "scripts": {
    "prebuild": "echo before building",
    "postbuild": "echo after building",
    "prepack": "echo before packing",
    "postpack": "echo after packing",
    "prerestore": "echo before restoring packages",
    "postrestore": "echo after restoring packages"
  }
}
```
> There are variables available:

> ```
%project:Directory% - The project directory
%project:Name% - The project name
%project:Version% - The project version
```

However this doesn't tell you *when* each event fires and give example usages of each.  It would be really helpful to know this.  I'm currently porting an ASP.Net Web API project with Angular / gulp usage across to ASP.Net 5 and trying to figure the best ways to plug gulp / bower / npm build events into my pipeline.  Information around this area would be very helpful!

**Comment by danroth27** [comment]
Thanks! Going forward we will be moving off of DNX and onto the new [.NET CLI](https://github.com/dotnet/cli), so the project.json docs will be moving to be part of http://dotnet.github.io.

For your specific scenario we hook up gulp using the prepublish event in our [templates](https://github.com/aspnet/templates].

**Comment by johnnyreilly** [comment]
Hi @danroth27,

Thanks for responding!  I'm afraid I was a little puzzled by your comment:

> Going forward we will be moving off of DNX and onto the new .NET CLI

I haven't been watching the ASP.Net standups for a little while and so I think I may have missed something.  There's DNU (dot net utilities) DNVM (dot net virtual machine?) DNX (dot net execution) and now .NET CLI as well?  Is there a document somewhere that outlines the relationship between all these please?  Sorry for being a bit obtuse but it wasn't clear to me how they all tie together from reading  http://dotnet.github.io.

**Comment by danroth27** [comment]
DNU (.NET Development Utility) is really part of [DNX](https://github.com/aspnet/dnx) (.NET Execution Environment), which includes a cross platform native CLR host. DNVM (.NET Version Manager) is used to acquire and manage different DNX versions. DNX is getting replaced by a new cross platform CLR host and tool chain which is being developed in the [.NET CLI](https://gitHub.com/dotnet/cli) repo. The .NET CLI supports building native console applications instead of the specialized application model used by DNX.

**Comment by johnnyreilly** [comment]
Thanks for that @danroth27 - much appreciated
