### ISSUE TITLE
Enhance cross-links for built-in Tag Helper topics

### ISSUE THREAD

**Issue by Katydude** [aspnet/Docs#8771]
Very poorly written. What file are these settings even stored in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d92493-4f8a-5d1e-6be2-d22be29bf21d
* Version Independent ID: db7a9eab-6e8c-9332-b13f-f972dee8e15d
* Content: [Environment Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/environment-tag-helper?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/environment-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/environment-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Katydude ... Any Razor (*.cshtml*) file. See: https://docs.microsoft.com/aspnet/core/mvc/views/tag-helpers/intro

**Comment by Katydude** [comment]
OK, I see what you're / they're getting at now. I guess I just find this format of documentation a bit disjointed, especially when the examples are contrived. But I'm catching on to it. Thanks.

**Comment by guardrex** [comment]
Curious ... Did you arrive directly to this? ... It seems like that's what happened. The environments topic is linked in *Additional resources*, but perhaps it would have helped if it were linked at the top of the topic in the opening paragraph. Otherwise, the topic doesn't link back out to the main Tag Helpers topic. I'll do some cross-linking on this ....... when I get back. 🏖😄

**Comment by Katydude** [comment]
Yes, I came here from https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio%2Caspnetcore2x . This is where I started trying to find out where to plop in the <environment> tag. 

For some context, I'm converting an MVC 5 app to ASP.NET Core 2.x. I ran into the issue of the @Scripts.Render directive not being immediately (ever?) supported on a Core 2.x page. I did get the minified / bundled version of my scripts to render but needed to see how to toggle that to the full versions for debugging...and on and on.

So, I think what threw me is that <environment> is presented as an html tag I could use to switch the page output but I could not find the chain of tasks needed to make that happen.

**Comment by guardrex** [comment]
Ok, thanks. I *think* cross-linking would have helped expose the underlying concepts for the Tag Helper here.

You're right about the lack of some bridging of concepts for migration. We have migration topics for netfx to Core, but they'll be quite challenged to cover every scenario.

https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x

If you find a migration concept that you feel definitely should have been covered, please open a new issue. If management approves, you can send a PR if you want. If that's not an option, we'll get to it asap.

**Comment by guardrex** [comment]
No worries ... :smile: We've all been there for sure.

Idk if the built-in TH topics have had their first major review/update pass. If not, the team will get to that eventually.
