### ISSUE TITLE
Why is project.js file in "Creating a Cross-Platform Console App with DNX" so complicate?

### ISSUE THREAD

**Issue by simonech** [aspnet/Docs#878]
I've seen that project.json file used in the [Creating a Cross-Platform Console App with DNX](https://docs.asp.net/en/latest/dnx/console.html) is very complicate:

The app doesn't use Linq, Threading, Collection.
Also I don't understand what's the point of
```
  "commands": {
    "ConsoleApp1": "ConsoleApp1"
  }
```
since then the app is run with `dnx run`

Why not just leaving it to bare minimum needed to run the sample?
```
{
    "version": "1.0.0-*",
    "dependencies": {
    },
    "frameworks" : {
        "dnx451" : { },
        "dnxcore50" : {
            "dependencies": {
                "System.Console": "4.0.0-beta-*"
            }
        }
    }
}
```

**Comment by danroth27** [comment]
This is all going to change now that we are moving to the new [.NET CLI](https://github.com/dotnet/cli). Please watch for updated docs on http://dotnet.github.io.
