### ISSUE TITLE
Authentication for Single Page Applications

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8789]
Per https://github.com/aspnet/Announcements/issues/307

**Authorization Server**
One of the largest gaps we’ve had has been around authorization for applications beyond a simple forms based login. We plan to fill that gap with a simple to use OpenID Connect based authorization server, which will allow your ASP.NET application to act as an authentication point for your projects, be they web site to API, SPA to API, native application to an API or, for distributed applications API to API. As we are concentrating on first party applications we can make the code you need to plumb in trivial, getting as close to zero configuration as you can, we’re not aiming to replace the excellent third-party solutions out there which enable richer scenarios like third-party applications or which provide a flexibility in configuration and authentication flow.

**Comment by Rick-Anderson** [comment]
@Tratcher 	who can provide us with some working samples and a doc outline?

**Comment by Tratcher** [comment]
@blowdart @javiercn

**Comment by blowdart** [comment]
Weeks away

**Comment by Rick-Anderson** [comment]
@javiercn do you have an ETA on this?

**Comment by javiercn** [comment]
@Rick-Anderson Not sure what you expect from me here.

**Comment by Rick-Anderson** [comment]
@javiercn 	this issue has the **PU** label meaning the **P**roduct **U**nit is responsible for the doc. We'll only supply copy/edit support.

Also
> mkArtakMSFT (Artak) assigned javiercn 5 days ago

**Comment by javiercn** [comment]
@Rick-Anderson We haven't even released an alpha of this.

**Comment by brunoalreis** [comment]
Hi,

Any news on this?

**Comment by jculverwell** [comment]
Is there anyway we can get a update on this?  Not sure if I am looking in the wrong place.
