### ISSUE TITLE
@aspnet/signalr js client version - please make it avialable as js file

### ISSUE THREAD

**Issue by NGancevich** [aspnet/Docs#8792]
Hi, I have an trouble with installing signalr js client using command
npm install @aspnet/signalr 

I have asp.net core 2.1 installed. 

After running in vs 2017 (15.8.5) nothing happens and I can't find any js added to project. Please make available link for js file or advise how to get it. It's real headache .

**Comment by scottaddie** [comment]
@NGancevich Are you running the `npm install` command in Visual Studio's Package Manager Console window or from the command shell? If running it in VS, some additional configuration is needed for npm. See the steps here: https://docs.microsoft.com/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio#create-the-aspnet-core-web-app.

As an alternative to npm, you can install the JS client with LibMan. See the steps here: https://docs.microsoft.com/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio#add-the-signalr-client-library.

**Comment by NGancevich** [comment]
@scottaddie , it helped me.

**Comment by scottaddie** [comment]
Thank you for reporting back, @NGancevich! Glad to hear this helped you.
