### ISSUE TITLE
The specified framework 'Microsoft.AspNetCore.App', version '2.1.5' was not found.

### ISSUE THREAD

**Issue by CribAd** [aspnet/Docs#8794]
Updated Microsoft.AspNetCore.App from 2.1.2 to 2.1.5 via NuGet package, then run a command and get the next error:

_

> It was not possible to find any compatible framework version
> The specified framework 'Microsoft.AspNetCore.App', version '2.1.5' was not found.
>   - Check application dependencies and target a framework version installed at:
>       C:\Program Files\dotnet\
>   - Installing .NET Core prerequisites might help resolve this problem:
>       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
>   - The .NET Core framework and SDK can be installed from:
>       https://aka.ms/dotnet-download
>   - The following versions are installed:
>       2.1.2 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>       2.1.4 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

_

**Comment by guardrex** [comment]
You'll install the latest SDK, but give it like 24 hours. The package is up on NuGet, but the SDK isn't out yet ... https://www.microsoft.com/net/download/dotnet-core/2.1

**Comment by scottaddie** [comment]
@CribAd The .NET Core 2.1.403 SDK is available for download now. I've confirmed that it fixes the error. Use the link provided above by @guardrex.
