### ISSUE TITLE
How to test Web API with Jwt Bearer Authentication

### ISSUE THREAD

**Issue by buchajmal** [aspnet/Docs#8796]
Can you please include samples to test a Web API request with Jwt Bearer token which uses AspNetCore Identity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#inject-mock-services)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @buchajmal ... Yes, you've opened a sister issue to other asks for enhancements to the topic+sample along these lines:

* https://github.com/aspnet/Docs/issues/6882
* https://github.com/aspnet/Docs/issues/7526

It will take a little while before one of us can get to this with the 2.2 release coming out soon. We'll schedule this for work as soon as possible.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

We'll take a look at this issue when we refresh the doc.

**Comment by jabbera** [comment]
For those interested I build a package that makes this simple: https://github.com/jabbera/aspnetcore-testing-role-handler

Feedback welcomed.
