### ISSUE TITLE
services.AddTransient >> services.AddSingleton

### ISSUE THREAD

**Issue by reponemec** [aspnet/Docs#8798]
Have a look at: https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.1.

I think the line of code:
`services.AddTransient<IAuthorizationPolicyProvider, MinimumAgePolicyProvider>();`

should be replaced with 
`services.AddSingleton<IAuthorizationPolicyProvider, MinimumAgePolicyProvider>();`

**Comment by guardrex** [comment]
ping @mjrousos 

The auth sample uses `AddSingleton`: https://github.com/aspnet/AuthSamples/blob/master/samples/CustomPolicyProvider/Startup.cs#L16

**Comment by guardrex** [comment]
I'll just go ahead and quickly knock this out.
