### ISSUE TITLE
Endpoint Routing in 2.2

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8815]
* [Glen's blog](https://blogs.msdn.microsoft.com/webdev/2018/08/27/asp-net-core-2-2-0-preview1-endpoint-routing/)
* [@stevejgordon blog](https://github.com/stevejgordon?tab=overview&from=2018-08-01&to=2018-08-31)
* #8763

**Comment by Rick-Anderson** [comment]
@scottaddie 	@guardrex 	isn't this a dup of #8763 
Can I close this?

**Comment by guardrex** [comment]
I think so ... maybe just add the Glen blog link over there to :eye: it at the end to make sure those aspects were covered.

https://blogs.msdn.microsoft.com/webdev/2018/08/27/asp-net-core-2-2-0-preview1-endpoint-routing/
