### ISSUE TITLE
master issue:Update to angular 6

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8816]
List all doc issues here.

- [ ] This issue #8816
- [ ] 
- [ ] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by Misiu** [comment]
Maybe version 6 can be skipped?
Angular 7 is already out - https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c

**Comment by danroth27** [comment]
@Misiu We haven't updated our templates to Angular 7 yet, but we're tracking the update here: https://github.com/aspnet/Templating/issues/694
