### ISSUE TITLE
How should I pass objects using MessagePack as protocol?

### ISSUE THREAD

**Issue by harveytriana** [aspnet/Docs#8818]
Your instructions are clear. Executing the samples of "../SignalR/samples/SignalRSamples/ ", all run perfect. However, I try to pass an object using the MessagePack protocol,  no error is generated, but the object always comes null to the Server. - When I change the protocol to JSON, everything works as expected.

Question: Is it necessary to use serialization and deserialization when you use objects? 

I will appreciate an example using the MessagePack Hub protocol using an object as argument.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
You shouldn't have to do anything different when using Json or MessagePack.

Could you share what object you're trying to send?

**Comment by harveytriana** [comment]
Thank you.

Resume. I use the example, I made some small changes. Upload this to: http://www.visionary-saas.com/docs/SignalRSamples_2.1_Tests.zip (You can search all the "/ *" so you can see what my changes were).

The object is very simple, - it happens with anyone.
public class WeatherReport
    {
        public string ConnectionId { get; set; }
        public double Temperature { get; set; }
    }
You can notice the following (button [Send Random Temperature]): 
Testing with JSON Protocol:
Connected successfully
jpfBaTYMQMMDAk24v2Shhg joined
jpfBaTYMQMMDAk24v2Shhg Temperature: 61.31428571428572°
jpfBaTYMQMMDAk24v2Shhg Temperature: 61.4°
jpfBaTYMQMMDAk24v2Shhg Temperature: 61.254285714285714°
Disconnected

Testing with MessagePack protocol:
Connected successfully
DIN77SnOMa7_jhBmSXYZOQ joined
undefined Temperature: undefined°
undefined Temperature: undefined°
Disconnected

- Maybe I'm doing something wrong.

**Comment by BrennanConroy** [comment]
Ah, so you need to use the same casing for property names when sending the javascript object so "ConnectionId" and "Temperature" this is a current limitation of the library we're using.

**Comment by harveytriana** [comment]
Hi. Sorry. The behavior was the same.
Basically the only change was the casing in client code:

click('weather-report', function (event) {
    var data = {
        ConnectionId: '',
        Temperature: getTemperature()
    };
    invoke(connection, 'SendWeatherReport', data);
});

Results with JSON as protocol:
- Connected successfully
- BGe2rru1P4Ei_ubfiR5xkg joined
- BGe2rru1P4Ei_ubfiR5xkg Temperature: 61.25°
- BGe2rru1P4Ei_ubfiR5xkg Temperature: 60.71°
- ...
- Disconnected

Results with MessagePack as protocol:
- Connected successfully
- MTvfSNm8zDH1_OKK5E-UWA joined
- undefined Temperature: undefined° ?
- undefined Temperature: undefined° ?
- ...
- Disconnected

For a quick look, I published a much more simplified example here:
https://github.com/harveytriana/MessagePackTest

Do I have something wrong?
Regards.

**Comment by BrennanConroy** [comment]
Capitalize the property names
```
connection.on('SendWeatherReport', function (wr) {
            addLine('message-list', wr.ConnectionId + ' Temperature: ' + wr.Temperature + '°');
        });
```

**Comment by harveytriana** [comment]
It is right.

Thank you very much.
