### ISSUE TITLE
Needs setup code in Startup.cs

### ISSUE THREAD

**Issue by sbsw** [aspnet/Docs#8819]
The documentation needs to mention that Roles require some code in Startup.cs:
```
    services.AddDefaultIdentity<PortalUser>()
        .AddRoles<IdentityRole>()  // <- Must add this line to the code provided by the template
        .AddEntityFrameworkStores<ApplicationDbContext>();
```

Ref: https://stackoverflow.com/a/52524078/1637105

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3668fea-5d71-a4fc-96d1-74b53906bf25
* Version Independent ID: 980a23e7-56e4-da94-a139-cab85135c5f7
* Content: [Role-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/roles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/roles.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@sbsw 	thanks for the comment. We'll get this updated in the next sweep.

**Comment by Rick-Anderson** [comment]
@sbsw 	thanks for reporting this. I will be live in day or two.
