### ISSUE TITLE
Multiple hub protocols

### ISSUE THREAD

**Issue by cecilphillip** [aspnet/Docs#8821]
Can it be outlined if/how multiple hub protocols can be supported on both the client and the server? I've been asked about this a few times. I know it's possible from the server, but I'm not sure about the clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@anurse Please see Cecil's question.

**Comment by anurse** [comment]
It's not possible from the client. The server can support multiple hub protocols but each client must select a single protocol to use for the connection.

**Comment by cecilphillip** [comment]
Right. So can we outline that in this document
