### ISSUE TITLE
Migration process from Asp.net core 1.x to 2.1 applications targeting .Net framework

### ISSUE THREAD

**Issue by srini1978** [aspnet/Docs#8822]
Can we consider the following as steps to migrate a Asp.net core application from 1.x to 2.1 for applications that target full framework .

1. Update target framework monikor to target framework &gt; 462
2. Update .net core sdk version to 2.1.4 in global.json. 
3. In packagereference attribute  for all .csproj, for all references that connect to microsoft.aspnetcore.* change the  version number to 2.1 
E.g   &lt;PackageReference Include=""Microsoft.AspNetCore.Authentication.Cookies" Version="2.1" /&gt;

4. Update the main method of program.cs as per https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1#update-main-method-in-program.cs 
5. Startup.cs code changes for adding and removing configuration providers as per https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1#add-configuration-providers 
6. Database initialization code changes as required - https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1#move-database-initialization-code 
7. Remove references to &lt;DotNetCliToolReference&gt; elements for the following packages. These tools are bundled by default in the .NET Core CLI and don't need to be installed separately. 
Microsoft.DotNet.Watcher.Tools (dotnet watch)
Microsoft.EntityFrameworkCore.Tools.DotNet (dotnet ef)
Microsoft.Extensions.Caching.SqlConfig.Tools (dotnet sql-cache)
Microsoft.Extensions.SecretManager.Tools (dotnet user-secrets)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srini1978** [comment]
If the above steps are good, then can we create a new documentation article for applications targeting full framework that want to migrate from .net core 1.x to 2.1

**Comment by Rick-Anderson** [comment]
@scottaddie 	where would this information go? In [Migrate from ASP.NET Core 1.x to 2.0](https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/?view=aspnetcore-2.1)

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
