### ISSUE TITLE
Example of Strongly Typed HubContext

### ISSUE THREAD

**Issue by nimeshdhruve** [aspnet/Docs#8824]
It would be great if you can please also add example of strongly typed hubcontext. 
Something like:
```
public class IndexModel : PageModel
{
        private readonly IHubContext<ChatHub, IChatClient> _hubContext;

        public IndexModel(IHubContext<ChatHub,IChatClient> hubContext)
        {
            _hubContext = hubContext;
        }
        public void OnGet()
        {
            _hubContext.Clients.All.ReceiveMessage("Anonymous", "Welcome");
        }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf6fefc-557e-114a-a37c-90939e06b083
* Version Independent ID: 92da23e0-6dc5-170e-b489-2ad8bbd46dff
* Content: [SignalR HubContext](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/hubcontext.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubcontext.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@anurse 	please respond.

**Comment by anurse** [comment]
Sounds like a good plan
