### ISSUE TITLE
multiple requirement and multiple handlers in ASP Net policy based authorization

### ISSUE THREAD

**Issue by smukherjee-rythmos** [aspnet/Docs#8825]
Was going through the Policy Based Authorization document https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1.

Have a requirement where in I will have multiple requirement and associated handlers. Something like

    ReadpermissionReq : IAuthorizationRequirement    
    WritePermissionReq : IAuthorizationRequirement

Their associated handlers like

    Readhandler : AuthorizationHandler<ReadpermissionReq>
    WriteHandler : AuthorizationHandler<WritePermissionReq>

Would register them accordingly in `Startup.cs`.

Have few attributes defined for each such requirement like `ReadAttribute: AuthorizeAttribute` and using those attributes in my Api endpoint like

    [Read]
    [HttpGet]
    public Foo GetFoo(int id) {}

Question: Which authorization handler will be invoked in this case. I know for a single requirement and handler it's no issue. But in this case, confused as to which handler will be responsible for processing the authorization logic?

Or do I need to something extra to make sure this specific handlers gets invoked in case of specific attribute?

Most of the document referred talks about single requirement/handler only.

**Comment by smukherjee-rythmos** [comment]
Okey ... have a slight idea about this, just confirm whether am correct or not. As said in question every attribute inherits `AuthorizationAttribute` which accepts a policy in constructor and the same policy is registered in Startup.cs with a specific requirement. As well that requirement has a tight glue with a specific handler.

Thus can I assume that core Authorization pipeline could invoke the specific handler following the chain as mentioned above. @scottaddie or @HaoK

**Comment by HaoK** [comment]
At the lowest level every `IAuthenticationHandler` is given a chance to look at every requirement (the default implementation of `AuthenthenticationHandler<TReq>` is what's doing the filtering underneath the covers to only surface TReq).

The glue as you put it is only in some of the implementations to make it easier for the normal case where there's a 1:1 Handler/Req coupling.

There's nothing preventing you from writing one massive Handler that handles all requirements in a big switch statement if you like.

**Comment by HaoK** [comment]
Regarding the `[Authorize]` that just allows you to specify a policy name, which basically boils down to an Authorize call with the requirements in the policy which all registered  `IAuthorizationHandlers` in DI have a chance to handle.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
