### ISSUE TITLE
Add resource filter example to Filters topic sample

### ISSUE THREAD

**Issue by deivyd321** [aspnet/Docs#8826]
No resourse filter example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a70a955f-dd5a-c46b-dfe8-21521e619320
* Version Independent ID: ebb299e0-6c1c-7077-689d-ac711352e418
* Content: [Filters in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#resource-filters)
* Content Source: [aspnetcore/mvc/controllers/filters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/filters.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @deivyd321 ... I just added this to the sample update tracking issue. #5495 We'll see about getting this in there when the sample is updated. Thanks for opening this issue.

**Comment by poke** [comment]
@Rick-Anderson Sure, I could do that, however, the docs say this:

> The short circuiting resource filter shown earlier is one example of a resource filter.

And that is actually a valid example there. Do you want something else there? Or do we just want to re-include the same code in the resource filter section?

**Comment by Rick-Anderson** [comment]
@poke 	thanks. I think that's good enough.
