### ISSUE TITLE
Update Gulp details describing how to bundle and minify with version 4

### ISSUE THREAD

**Issue by IEvangelist** [aspnet/Docs#8827]
Gulp 4 introduced [breaking changes](https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md#400), as such the existing documentation is only valid for versions of Gulp prior to version 4. With that said, I'd like to add the documentation for Gulp 4 support into the [Bundling and Minification](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md) document. I intend of having this PR count towards my Hacktoberfest contributions 🤘.

/cc @scottaddie

**Comment by scottaddie** [comment]
@IEvangelist Thanks for volunteering to do this. Ping me when the PR is ready for review.
