### ISSUE TITLE
Unable to set shortcut F7 key.

### ISSUE THREAD

**Issue by spymaster49637** [aspnet/Docs#8832]
Following the directions shown above I am unable to set the shortcut key.  After following directions listed above it will not work.  Please advise as to what I might be doing wrong.  One thing I notice in the tutorial is that the ProjectandSolution... is selected but the verbage is - Select EditorContextMenus.CodeWindow.ToggleRazorView.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Kuugen** [comment]
@spymaster49637, I believe EditorContextMenus.CodeWindow.ToggleRazorView is where you need to set F7 and the tutorial is just displaying what it would look like.

**Comment by spymaster49637** [comment]
Thank You!

**Comment by teskemj** [comment]
I attempted to "type" F 7, rather than pressing the F7 key.
