### ISSUE TITLE
Break point for Razor C# class generated for a view

### ISSUE THREAD

**Issue by caedunogueira** [aspnet/Docs#8839]
I wrote CustomTemplateEngine as suggested in this article and added it in Startup's ConfigureServices method but when I run the project and it redirects me to Pages/Index.cshtml, it doesn't stop at break point setted up for "return csharpDocument" line.

The only difference I detected between the article and my example is in ConfigureServices method for the AddMvc method. In my case, it uses the SetCompatibilityVersion method.

Do you have any idea for the break point has not been triggered when Pages/Index.cshtml was redirected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#viewing-the-razor-c-class-generated-for-a-view)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@NTaylorMullen Seems like something is missing from [the instructions](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1#viewing-the-razor-c-class-generated-for-a-view) in the doc. Any ideas?

**Comment by NTaylorMullen** [comment]
My bet is that views are being compiled on build and therefore GenerateCode is never called. If you want to see the output of your Razor files when `RazorCompileOnBuild` is `true` (this is the default) you can look in your obj folder for `cshtml.cs` files for the output of your various Razor files. Otherwise, you can set `RazorCompileOnBuild` to `false` an the old method works

**Comment by caedunogueira** [comment]
@NTaylorMullen I saw the generated code in obj folder, thanks for the clue. I tried also the old method you mentioned and setted up RazorCompileOnBuild to false. The files in obj folder has not been created but that line with break point at CustomTemplateEngine class has not been triggered. Regardless, now I know how to see when it's the default option for RazorCompileOnBuild.

**Comment by scottaddie** [comment]
Thank you, @NTaylorMullen! I'll get this detail added to the doc.
