### ISSUE TITLE
Localization Extensibility

### ISSUE THREAD

**Issue by hishamco** [aspnet/Docs#8867]
Explain the extensibility points in localization APIs, including:
    - Create a custom `RequestCultureProvider`.
     - Create a custom `StringLocalizer`.

/cc @Rick-Anderson @ryanbrandenburg

**Comment by Rick-Anderson** [comment]
@hishamco 	did you want this in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization ?

Can you provide code samples for those?

**Comment by hishamco** [comment]
Yep they should go there, by adding a new section after PO Localization section

> Can you provide code samples for those?

I already have many sample such as [My.Extensions.Localization.Json](https://github.com/hishamco/My.Extensions.Localization.Json), [My.AspNetCore.Localization.Json](https://github.com/hishamco/My.AspNetCore.Localization.Json), [My.AspNetCore.Localization.Session](https://github.com/hishamco/My.AspNetCore.Localization.Session)

**Comment by Rick-Anderson** [comment]
Moved to #8244 for visibility.
