### ISSUE TITLE
Migration for custom user data

### ISSUE THREAD

**Issue by GrahamBonzoWright** [aspnet/Docs#8877]
You need to ensure your DbContext references the derived identity class.
So if ApplicationUser is the derived IndentityUser class the DbContext needs to be
 public class ApplicationDbContext : IdentityDbContext&lt;ApplicationUser&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 431df4fc-4168-cc8f-d053-9b264d2971c1
* Version Independent ID: cd157d04-d596-83fa-6edb-24d52193eb34
* Content: [Add, download, and delete custom user data to Identity in an ASP.NET Core project](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/add-user-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/add-user-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/add-user-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@GrahamBonzoWright 	is your complaint that if you're following this tutorial to migrate custom user data you might not know that `DbContext` must reference the derived identity class?

**Comment by GrahamBonzoWright** [comment]
Specifically yes but in general implementing what must be a common scenario of a user with custom data and roles based authorization requires piecing together information from various places in the documentation.
This is not helped by the current downloadable example (ASP.Net Samples\aspnet\Samples\WebApi\BasicAuthentication) not compiling, giving the error “ ‘IdentityUserRole' does not contain a definition for 'Role' “


-          Graham

**Comment by Rick-Anderson** [comment]
*ASP.Net Samples\aspnet\Samples\WebApi\BasicAuthentication* that looks like it's not an ASP.NET Core sample.
