### ISSUE TITLE
Build successful, but I'm having reference issues

### ISSUE THREAD

**Issue by khozanai** [aspnet/Docs#8880]
I keep getting these errors

An error occurred during the compilation of a resource required to process this request. Please review the following specific error details and modify your source code appropriately.
Generated Code
One or more compilation references are missing. Ensure that your project is referencing 'Microsoft.NET.Sdk.Web' and the 'PreserveCompilationContext' property is not set to false.

The type or namespace name 'Hosting' does not exist in the namespace 'Microsoft.AspNetCore.Razor' (are you missing an assembly reference?)
+
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(RazorPagesMovie.Pages.Index_Page), @"mvc.1.0.razor-page", @"/Pages/Index.cshtml")]
The type or namespace name 'Hosting' does not exist in the namespace 'Microsoft.AspNetCore.Razor' (are you missing an assembly reference?)
+
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"472eba6082c4cfd9087bb1b0a55099908614d006", @"/Pages/Index.cshtml")]
The type or namespace name 'Hosting' does not exist in the namespace 'Microsoft.AspNetCore.Razor' (are you missing an assembly reference?)
+
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"5bffd98f02597e6a09295a2131188dc64093be78", @"/Pages/_ViewImports.cshtml")]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa70bd9-d52a-8b71-4f56-abf4b53c5ca1
* Version Independent ID: 99c9a3fe-747c-160e-0a57-421426202506
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@khozanai What's the output when you execute ...

```
dotnet --version
```

... at a command prompt?

**Comment by khozanai** [comment]
> @khozanai What's the output when you execute ...
> 
> ```
> dotnet --version
> ```
> ... at a command prompt?
> 
> You may need to get the latest SDK 👉 https://www.microsoft.com/net/download (**Download .NET Core SDK** under the macOS tab)

when I run dotnet --version, I get this version: 2.1.4

**Comment by guardrex** [comment]
You might want to go ahead and get 2.1.403 on there and see if that resolves the errors.

Unfortunately, I'm buried in a topic right now or else I'd get on my Mac and see what's what.

If you haven't figured out the problem by later this afternoon, I'll get on the Mac and see if I can repro your errors here.

**Comment by khozanai** [comment]
I just ran the app again after the updated SDK, and got the same errors, twice. Here is a screenshot of the errors.

<img width="1440" alt="screen shot 2018-10-07 at 17 41 01" src="https://user-images.githubusercontent.com/21240267/46583481-6ed22a00-ca58-11e8-91d0-04d06743dde5.png">

**Comment by guardrex** [comment]
I'll try to repro that here in a few hours when I'm free. It's a slightly older 2.0-era app; so if I get the same result you're getting, the first thing I'll try to do is update the app to 2.1. I'll get back to you later today or this evening. Otherwise, @Rick-Anderson might recognize what's going wrong and let us know. He sees dev feedback on this set of topics and may have encountered this happening earlier.

**Comment by khozanai** [comment]
Thank you for all your efforts in assisting to resolve this

**Comment by guardrex** [comment]
For a quick check to see if upgrading the app will help, try using the following project file (*RazorPagesMovie.csproj*) and see what happens. It might still :boom: for other reasons, but it also might improve the situation ...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
  </ItemGroup>

</Project>
```

**Comment by khozanai** [comment]
Yup changing to 2.1, that made the app run, and its working fine now.

Thanks for the help

`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

  </PropertyGroup>
  <ItemGroup>
       

        <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
    
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>
    <ItemGroup>
   <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.1.0-preview1-final" /> 

        
</ItemGroup>
</Project>`

**Comment by guardrex** [comment]
I think this sample is slated for update on the sample update tracking issue #5495. We'll get to it as soon as we can.
