### ISSUE TITLE
Select/Remove multiple entries in Redis ?

### ISSUE THREAD

**Issue by derth** [aspnet/Docs#8889]
I want to invalidate all different caches of an entity, the entity itself, all pagination, etc.
I think to be able to select/remove multiple caches at once based on a string pattern is important.
Is there any way to do this?

**Comment by Rick-Anderson** [comment]
Thanks for the question. We're a doc team - so you'll probably get a much quicker response from a support forum like StackOverlow.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
