### ISSUE TITLE
Warnings don't scare me

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#889]
The background colors for a warning ...
![capture](https://cloud.githubusercontent.com/assets/1622880/12302536/7f63a894-b9da-11e5-8eb9-ca9d9467fe7e.PNG)
... don't scare me enough :skull:. Maybe it's just because a stock Read the Docs theme was accepted without modification, but I was just wondering was something more traditional (red/yellow) ruled out? It would definitely be more of an attention getter ... e.g. ...
![capture2](https://cloud.githubusercontent.com/assets/1622880/12302540/81ddb1e6-b9da-11e5-85f0-a4936dbd7d76.png)

**Comment by danroth27** [comment]
We are doing an update to our styles soon to align with the http://asp.net site, but I don't think we want the colors of the warnings to be quite that dramatic :wink:
