### ISSUE TITLE
ILogger<TodoController>

### ISSUE THREAD

**Issue by paulomorgado** [aspnet/Docs#8891]
This `ILogger&lt;TodoController&gt;` pops up in the example but there's no instructions on where it came from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
I agree that it could use just a hair more explanation. If you flip over to the API browser for `ILogger`, you'll see the second sentence of the description fleshes it out a bit more. I'll surface something along those lines in the topic. Thanks for mentioning this.

https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger-1

**Comment by guardrex** [comment]
Yes, it's ✨ _magical_ ✨. :smile:

It's sort of covered in the topic here ... https://docs.microsoft.com/aspnet/core/fundamentals/logging/#nuget-packages ... where it says ...

> The `ILogger` and `ILoggerFactory` interfaces are in `Microsoft.Extensions.Logging.Abstractions`, **_and default implementations for them_** are in `Microsoft.Extensions.Logging`. (emphasis added)

When I get to this, I'll see if I can move something like that up to the top where `ILogger` is first mentioned. There's probably even more work to be done than just what's in the tracking issue at https://github.com/aspnet/Docs/issues/5161 because this topic has rolling along for quite a while without one of our major overhauls. I'll add this issue to that tracking issue, too.

**Comment by guardrex** [comment]
@tdykstra You're actively working on that ... would you like to take this? Better to keep it all under one roof.

**Comment by tdykstra** [comment]
Yes, thanks.

**Comment by paulomorgado** [comment]
Again @guardrex, I know all about the types. I use them every day, although I'm not writing ASP.NET Core applications.

Nothing on that page tells me where that type was registered. As it is, it simple throws an `InvalidOperationException`.

**Comment by guardrex** [comment]
@StephenCleary's deep dive has some info about getting an `ILogger<T>` when not using ASP.NET Core. See if his section on **_Getting ILogger<T> Instances from ILoggerFactory_** helps.

https://blog.stephencleary.com/2018/06/microsoft-extensions-logging-part-2-types.html

**Comment by guardrex** [comment]
@Tratcher Question: Where/how is an `ILogger<T>` created for a ctor? `AddLogging` registers an `ILoggerFactory`. Does the factory create the `ILogger<T>` using `ILoggerFactory.GetLogger<T>()`?

**Comment by Tratcher** [comment]
It's created through the magic of [open generics](https://github.com/aspnet/Logging/blob/d9b34d1c36fde204bd736d09b89b86451bd82e95/src/Microsoft.Extensions.Logging/LoggingServiceCollectionExtensions.cs#L42), which indeed uses the [factory](https://github.com/aspnet/Logging/blob/d9b34d1c36fde204bd736d09b89b86451bd82e95/src/Microsoft.Extensions.Logging.Abstractions/LoggerOfT.cs#L29).

@paulomorgado This is all enabled by default, are you sure DI isn't failing on another constructor parameter?

**Comment by paulomorgado** [comment]
Got it, @Tratcher!

Entirely my fault. When I used Visual Studio to create missing constructors to add the logger as parameter it created a protected constructor. Having read my code with as much attention as I read the exception details, I thought something was missing on the example.

Even https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection doesn't mention anything about open generics. Shouldn't an example be added to that page?

**Comment by tdykstra** [comment]
@paulomorgado Yes, it would be good to add this info to the DI article. I'll close this issue and open one one on the DI article that links back to this one. If there's more you want to follow up on here, feel free to reopen this one.

**Comment by paulomorgado** [comment]
Thank's @tdykstra! That's all.

Just let me know when the other issue is open.

**Comment by guardrex** [comment]
It's at #8933.
