### ISSUE TITLE
Entity Framework

### ISSUE THREAD

**Issue by paulomorgado** [aspnet/Docs#8892]
[Logging EF Core](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging#aspnet-core-applications) links to this page but there are no instructions on how to configure EF Core logging here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
I read that just to mean that logging is configured normally in an ASP.NET Core app for EF Core (same interfaces and whatnot) ... and then they describe their special considerations in their following paragraphs.

You opened it in the right spot when you opened this at https://github.com/aspnet/EntityFramework.Docs/issues/1039. We don't control their content, so they'll be able to assist on that repo.

**Comment by guardrex** [comment]
@paulomorgado 

> How can I configure EF Core logging to use the logging configured in ASP.NET Core?
>
> I've opened issues but got nothing out of it:
>
> https://github.com/aspnet/Docs/issues/8892
> https://github.com/aspnet/EntityFramework.Docs/issues/1039

There's no special configuration on the ASP.NET Core side. Follow the instructions in the topic: Add Logging services to the app (call `CreateDefaultBuilder` or build an `IHost` or `IWebHost`) and perhaps set up additional providers (e.g., Serilog) if you want more than console logging.

As for a specific example for EF Core, there's nothing to provide given that they fully integrate with the Logging API bits.

You just need to configure logging for the app normally with whatever providers you want to use and it should ✨ **_Just Work_**:tm: ✨
