### ISSUE TITLE
Using Razor Pages with vscode

### ISSUE THREAD

**Issue by bshlok** [aspnet/Docs#8894]
It may be worth including link to instructions for using with vscode:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/razor-pages-start?view=aspnetcore-2.1 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@bshlok thanks. This is do for an upgrade and we hope to fix it soon.

**Comment by daveabrock** [comment]
@Rick-Anderson It appears the link is there. This can probably be closed.

![image](https://user-images.githubusercontent.com/275862/47747345-258b8980-dc56-11e8-93a7-21102b24ded8.png)
