### ISSUE TITLE
incorrect link to core 1 version of 

### ISSUE THREAD

**Issue by saadis01** [aspnet/Docs#8898]
In this note the link to Core 1.x version is incorrect, it point to the 2.1 version

"The ManifestEmbeddedFileProvider is available in ASP.NET Core 2.1 or later. To access files embedded in assemblies in ASP.NET Core 2.0 or earlier, see the ASP.NET Core 1.x version of this topic."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8787c1-1a02-ae68-aa59-7c0e2e823dde
* Version Independent ID: 3e799e5d-a89c-cd03-999f-92ae431f4657
* Content: [File Providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/file-providers.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/file-providers.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for reporting this @saadis01.

The link is correct in the topic ...

> \[ASP.NET Core 1.x version of this topic](xref:fundamentals/file-providers?view=aspnetcore-1.1).

... but renders as ...

> \<a class="xref" href="https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers?view=aspnetcore-2.1" data-linktype="relative-path">ASP.NET Core 1.x version of this topic</a>

@Rick-Anderson @scottaddie Thoughts?

**Comment by Rick-Anderson** [comment]
We have an internal bug (1270316) tracking this. query string versions will be supported eventually, but not now. You'd need to use the full URL for versions.

**Comment by guardrex** [comment]
> full URL for versions.

Relative is ok?
