### ISSUE TITLE
Anti-Request Forgery

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#89]
ASP.NET 5 -> Security -> Anti-Request Forgery

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms/Sending_and_retrieving_form_data

**Comment by danroth27** [comment]
Should reference https://github.com/aspnet/Docs/issues/134

**Comment by vanderaj** [comment]
Hi there,

Will the URL at https://docs.asp.net/en/latest/security/anti-request-forgery.html stay stable once the docs drop? 

As the project lead of OWASP Top 10 2007, OWASP Developer Guide 2.0, and OWASP Application Security Verification Standard 3.0, would love to give as much of the security documentation you've got ready a review before it goes final. I'm easily reachable by the usual means, but best through my owasp address.

I've been developing some unit tests around high functioning CSRF implementations, happy to share code if you don't have a lot of tests for the CSRF functionality in ASP.NET core at the moment.

**Comment by Rick-Anderson** [comment]
@rynowak @blowdart @Tratcher see offer  of tests for the CSRF functionality in ASP.NET core 
@danroth27  please respond to URL stability.

**Comment by danroth27** [comment]
@vanderaj There may still be some URL churn before we go final.

**Comment by Tratcher** [comment]
@vanderaj Feel free to submit a PR to https://github.com/aspnet/antiforgery with additional tests.

**Comment by Rick-Anderson** [comment]
@blowdart @rynowak  please review this **request antiforgery** doc plan:

- Combine [Web API ](http://www.asp.net/web-api/overview/security/preventing-cross-site-request-forgery-csrf-attacks) and [MVC ](http://www.asp.net/mvc/overview/security/xsrfcsrf-prevention-in-aspnet-mvc-and-web-pages) XSRF/CSRF Prevention into one asp.net core article
- introduce https://github.com/aspnet/Antiforgery middleware for Web API
- show snippets from [Angular JS with Antiforgery middleware ](http://www.fiyazhasan.me/angularjs-anti-forgery-with-asp-net-core/) using https://github.com/aspnet/Antiforgery

**Comment by danroth27** [comment]
We should include in this article documenting the new automatic anti-request forgery support in MVC

**Comment by Rick-Anderson** [comment]
@spboyer take a look

**Comment by Rick-Anderson** [comment]
@blowdart @rynowak please review this request antiforgery doc plan:

**Comment by blowdart** [comment]
Yes, that's a doc plan :D

I'd like to see getting the form token part in javascript, rather than having to write a form

**Comment by spboyer** [comment]
Document Plan

- [ ] Combine [Web API ](http://www.asp.net/web-api/overview/security/preventing-cross-site-request-forgery-csrf-attacks) and [MVC ](http://www.asp.net/mvc/overview/security/xsrfcsrf-prevention-in-aspnet-mvc-and-web-pages) XSRF/CSRF Prevention into one asp.net core article
- [ ] Show snippets from [Angular JS with Antiforgery middleware ](http://www.fiyazhasan.me/angularjs-anti-forgery-with-asp-net-core/) using https://github.com/aspnet/Antiforgery
- [ ] Show Tag helper generated token & use

**Comment by spboyer** [comment]
Document outline update after discussion with @rynowak 

- Introduction: What is Antiforgery.
- IAntiforgery
     - Options : setting header, cookie name.
- Fundamentals
     - UserTokens 
     - Cookies 
- Filters
     - ValidateAntiforgeryToken
     - New Features
          - AutoValidateAntiforgeryToken
          - IgnoreAntiforgeryToken
- MVC 
- Samples
     - MVC: TagHelpers, HTMLHelpers
     - SPA: sample using Angular and Web API
- JavaScript (Ajax)

**Comment by Rick-Anderson** [comment]
@danroth27 @spboyer  I might work on this with @fiyazbinhasan  - see his [reventing XSRF in AngularJS Apps with ASP.NET CORE Anti-Forgery Middleware](http://www.fiyazhasan.me/angularjs-anti-forgery-with-asp-net-core/)

**Comment by fiyazbinhasan** [comment]
@Rick-Anderson ok got it.

**Comment by Rick-Anderson** [comment]
@danroth27 @spboyer  -  @fiyazbinhasan  is going to start working on this.  The outline after meeting with @rynowak  doesn't mention 
- - Combine [Web API ](http://www.asp.net/web-api/overview/security/preventing-cross-site-request-forgery-csrf-attacks) and [MVC ](http://www.asp.net/mvc/overview/security/xsrfcsrf-prevention-in-aspnet-mvc-and-web-pages) XSRF/CSRF Prevention into one asp.net core article

But we'll want to combine these two articles - but at the same time follow the outline. @rynowak  is that OK with you?

**Comment by Simply-Awesome** [comment]
> @danroth27 @spboyer - @fiyazbinhasan is going to start working on this. The outline after meeting with @rynowak doesn't mention 
•- Combine Web API  and MVC  XSRF/CSRF Prevention into one asp.net core article

@Rick-Anderson 
It would be totally fantastic, if you could include some information on how to customise when the Anti Forgery token expires - instead of just at the end of the browser session.

**Comment by blowdart** [comment]
CSRF tokens shouldn't expire, unless the underlying identity changes.

**Comment by Rick-Anderson** [comment]
You can see the start of this at https://www.dropbox.com/sh/jfmncpp0z79m9mt/AAAAB98zC4J7f9g_l6egU8nta?dl=0

**Comment by Simply-Awesome** [comment]
@Rick-Anderson 
If you can spare the time, please include:
- enabling only HTTPs anti-forgery tokens
- how HttpOnly flag set to "true" would work with SPAs like Angular
- about XST

I also really like this article:
http://resources.infosecinstitute.com/securing-cookies-httponly-secure-flags/

**Comment by ardalis** [comment]
For reference: #1945

**Comment by ardalis** [comment]
This sample is easily found: https://github.com/aspnet/Antiforgery/tree/dev/samples/AntiforgerySample
But we should update to the Entropy sample: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.AjaxAntiforgeryAuth.Web

The Angular way of passing the token is very angular-specific. A more generic approach would be more widely applicable.

**Comment by Rick-Anderson** [comment]
@fiyazbinhasan  can you write a more generic sample? @danroth27  do we want both an angular and a generic sample? I was thinking angular is very popular and would justify a specific example.

**Comment by ardalis** [comment]
Yes we just discussed and we want both an Angular and a generic example (or more than one: web vs. native clients for instance)

**Comment by fiyazbinhasan** [comment]
@ardalis you can find a ajax(javascript) example on the bottom of this doc @Rick-Anderson provided earlier. I used Jquery for making the task of cookie parsing easier. I can write a raw one if you want :) https://www.dropbox.com/sh/jfmncpp0z79m9mt/AACejY50rKGjSPpAnd5m2q_8a/Preventing%20XSRF%20in%20ASP.NET%20CORE.docx?dl=0

**Comment by danroth27** [comment]
aspnet/antiforgery#119

**Comment by ardalis** [comment]
@fiyazbinhasan thanks for the assistance; please review #1945
