### ISSUE TITLE
Send bulk message in websocket

### ISSUE THREAD

**Issue by JocelyneElKhoury** [aspnet/Docs#8900]
Is there a way to send the same message to several clients without having a loop for in websocket .net core ? i have the below server:

this is how i send currently the message

     public async Task SendMessageAsync(WebSocketConnection connection, string message)
      {
        if (connection.WebSocket.State != WebSocketState.Open) return;
        var arr = Encoding.UTF8.GetBytes(message);

        var buffer = new ArraySegment<byte>(
                array: arr,
                offset: 0,
                count: arr.Length);

        await connection.WebSocket.SendAsync(
            buffer: buffer,
            messageType: WebSocketMessageType.Text,
            endOfMessage: true,
            cancellationToken: CancellationToken.None
            );
        }

this is the websocketconnection:

       public abstract class WebSocketConnection
      {
         public WebSocketHandler Handler { get; }

         public WebSocket WebSocket { get; set; }

         public WebSocketConnection(WebSocketHandler handler)
        {
            Handler = handler;
         }
       }

**Comment by davidfowl** [comment]
> Is there a way to send the same message to several clients without having a loop for in websocket .net core ? i have the below server:

Nope, you have to store all of the clients in a list and do a loop that sends to each of them.
