### ISSUE TITLE
Error when run "Add-Migration Rating" 

### ISSUE THREAD

**Issue by Srusti-Thakkar** [aspnet/Docs#8904]
Hello, I had implemented your code step by step but when I am runnin "Add-Migration Rating" this command it gives me error like :

An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Object reference not set to an instance of an object.
Unable to create an object of type 'DemoAppContext'. Add an implementation of 'IDesignTimeDbContextFactory' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

What is mistake done by me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01013ef6-c55c-ff58-571c-ddc4435993af
* Version Independent ID: 24699fe5-9744-1796-0798-f7b211ec0f2f
* Content: [Add a new field to a Razor Page in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/new-field?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/new-field.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/new-field.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> What is mistake done by me?

Impossible to say, could be many things. `DemoAppContext` is not in the tutorial. Start over and compare to the completed download.
