### ISSUE TITLE
HelloWorldController is non-functional without required attributes.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [aspnet/Docs#8906]
It seems to me the HelloWorldController on this page https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.1 is non-functional. Having just built the example in VS2017 using ASP Dotnet Core 2.1 the claim that any public method on a controller class `is callable as an HTTP endpoint` does not appear to be the case, either with the comment form demonstrated or not.

I found the only way to make the controller endpoints callable was by putting a Controller attribute on the controller and a HttpGet attribute on the method.

**Comment by GaProgMan** [comment]
Using the instructions provided on the linked page (and translating them for the CLI, as I'm currently running Ubuntu), I was **unable** to recreate your issue.

The full CLI steps I took were:

``` bash
ja:~/Code/testingSomething$ dotnet new mvc --name helloworldcontroller
The template "ASP.NET Core Web App (Model-View-Controller)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore-template-3pn-210 for details.

Processing post-creation actions...
Running 'dotnet restore' on helloworldcontroller/helloworldcontroller.csproj...
  Restoring packages for ~/Code/testingSomething/helloworldcontroller/helloworldcontroller.csproj...
  Generating MSBuild file ~/Code/testingSomething/helloworldcontroller/obj/helloworldcontroller.csproj.nuget.g.props.
  Generating MSBuild file ~/Code/testingSomething/helloworldcontroller/obj/helloworldcontroller.csproj.nuget.g.targets.
  Restore completed in 535.58 ms for ~/Code/testingSomething/helloworldcontroller/helloworldcontroller.csproj.

Restore succeeded.

ja:~/Code/testingSomething$ cd helloworldcontroller/
ja:~/Code/testingSomething/helloworldcontroller$ code .
```

I then added the following code to the top of the `HomeController.cs` file:

``` csharp
namespace helloworldcontroller.Controllers
{
    public class HelloWorldController : Controller
    {
        // 
        // GET: /HelloWorld/

        public string Index()
        {
            return "This is my default action...";
        }

        // 
        // GET: /HelloWorld/Welcome/ 

        public string Welcome()
        {
            return "This is the Welcome action method...";
        }
    }

    public class HomeController : Controller
    // HomeController class here
```
Then ran the following command to run the app:

``` bash
ja:~/Code/testingSomething/helloworldcontroller$ dotnet run
```
Then browsed to `https://localhost:5001/helloworld` and received

> This is my default action...

And when I browsed to `https://localhost:5001/helloworld/welcome`, I received

> This is the Welcome action method...

in the browser.

**Comment by Neutrino-Sunset** [comment]
Retested. Problem was between keyboard and chair.

I'd started with the Razor tutorial so had

```
         app.UseMvc();
```
in Startup.Configure instead of 
```
         app.UseMvc(routes =>
         {
            routes.MapRoute(
               name: "default",
               template: "{controller=Home}/{action=Index}/{id?}");
         });
```
