### ISSUE TITLE
Add lazy loading example to RP related data tutorial

### ISSUE THREAD

**Issue by akousmata** [aspnet/Docs#8910]
Unless I'm misunderstanding the libraries being used or referenced.  Lazy loading is now supported which is in contradiction with what this article states:

[quote]Lazy loading. EF Core doesn't currently support lazy loading.[/quote]

https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio#eager-explicit-and-lazy-loading-of-related-data)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tdykstra 	please investigate.

**Comment by tdykstra** [comment]
Lazy loading was added in 2.1.  I made a PR to correct the remark about lazy loading not being supported.  We should add how-to instructions in the tutorial, I'm updating the title to make that clear. 

Thanks @akousmata  for bringing that to our attention!

**Comment by Rick-Anderson** [comment]
The link to the EF docs is all we need.
