### ISSUE TITLE
Can I send messages to clients from outside of SignalR hub?

### ISSUE THREAD

**Issue by gaazkam** [aspnet/Docs#8915]
Terribly sorry for persisting on this issue... But I do believe that the docs would benefit from mentioning this in a more explicit way.

I have come to a solution which seems to be working, but Im not sure if it is the correct one.

I need my hub to send a message to the clients... not immediatelly though, but - lets say - 2 mins after the appropriate method on the hub is invoked. This is my solution:

    public class ChatHub : Hub
    {
        private readonly IServiceScopeFactory scopeFactory;
        public ChatHub(IServiceScopeFactory scopeFactory)
        {
            this.scopeFactory = scopeFactory;
        }

        public async Task DelayedResponse(string message)
        {
            var timer = new Timer () { Interval = 2 * 60 * 1000, AutoReset = false };
            timer.Elapsed += async (sender, e) =&gt;
            {
                using (var scope = scopeFactory.CreateScope())
                {
                    var Clients = scope.ServiceProvider.GetRequiredService&lt;IHubContext&lt;ChatHub&gt;&gt;().Clients;
                    await Clients.All.SendAsync("ReceiveChatMessage", message);
                }
            }
        }
    }

This seems to work however, I'm not sure if this is the correct solution, or if this only works by coincidence. My doubts are based on the fact that:

1. I'm using `IServiceScopeFactory` in this manner only because I read on StackOverflow that this is a Singleton ( https://stackoverflow.com/a/39126718/4385532 ) However, I could not find such an info in the documentation ( https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iservicescopefactory?view=aspnetcore-2.1 ) which is why I'm unsure if this usage is correct. All I know is that it doesnt seem to be Disposed by the time the timer's handler fires off so it seems to be working.
2. Am I supposed to instantiate a HubContext? I suppose yes, but again I cant find this explicitely mentioned in the documentation.

Again - while I did come to a solution that seems to be working, I do believe that the doc pages could benefit from explicit answers to these questions.

These considerations are needed because the straightforward approach fails to work. The below code throws because Clients are disposed:

    public class ChatHub : Hub
    {
        public async Task DelayedResponse(string message)
        {
            var timer = new Timer () { Interval = 2 * 60 * 1000, AutoReset = false };
            timer.Elapsed += async (sender, e) =&gt;
            {
                    await Clients.All.SendAsync("ReceiveChatMessage", message);
            }
        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1#call-services-from-main)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@anurse 	please respond

**Comment by davidfowl** [comment]
@gaazkam Did you see this https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1?

Are you trying to call a method on the hub to kick off an operation? Do you just want to run some code on an interval? See https://github.com/aspnet/Docs/issues/8476. 

That logic you ended up with works but it's an easy way to cause memory leaks because you're starting a long running methods from a transient instance (the Hub itself). The hub is created per invocation, it's not long lived, it is created and disposed per call (this is why you get an object disposed exception when you try to extend the lifetime of the Clients property by capturing it in the timer callback).

Don't use the Hub itself for anything long running, you want to use an [IHostedService](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1). The link I sent has a code sample of one that uses the IHubContext\<THub\>.

**Comment by Rick-Anderson** [comment]
@tdykstra 	is this information worth adding to the article? It can be found in the closed issue so that my be good enough.

**Comment by gaazkam** [comment]
> @gaazkam Did you see this https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1?

Oops. I overlooked this. My bad. I'm sorry and thank you.

> Are you trying to call a method on the hub to kick off an operation? Do you just want to run some code on an interval?

As I said a few weeks ago, I wish to (a) implement timers in a turn-based game (that is, give a player eg 2mins for thinking for their turn and make them loose the game if they exceed this time however slightly - ok accuracy of 1sec is fine but not of say 20sec), and (b) implement tempmuting, that is eg mute a person in chat for 2hours and unmute them automatically when these 2h pass.

> See #8476.

OK thank you!

> That logic you ended up with works but it's an easy way to cause memory leaks because you're starting a long running methods from a transient instance (the Hub itself). The hub is created per invocation, it's not long lived, it is created and disposed per call (this is why you get an object disposed exception when you try to extend the lifetime of the Clients property by capturing it in the timer callback).

Thank you for your explanations!
 
> Don't use the Hub itself for anything long running, you want to use an [IHostedService](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1). The link I sent has a code sample of one that uses the IHubContext<THub>.

And thank you again!

**Comment by BrennanConroy** [comment]
I believe this can be closed. We have the [hubcontext doc](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubcontext?view=aspnetcore-2.1) and https://github.com/aspnet/Docs/issues/6888 for hub lifetime explanation.
