### ISSUE TITLE
404?  Not found :D

### ISSUE THREAD

**Issue by digitalohm** [aspnet/Docs#8916]
During this section:

A request to the page with the "{id:int}" route template that does not include the integer will return an HTTP 404 (not found) error. For example, http://localhost:5000/Movies/Details will return a 404 error. To make the ID optional, append ? to the route constraint:

I"m not able to get a 404 error page, just a blank page.  When I update the page directive to {id:int?} the url Movies/Details still goes to a blank page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 089d4e5a-b09a-936c-a6c9-fe6febf15f0a
* Version Independent ID: 60b67f12-a9c6-27b4-31f5-1e5baeff051b
* Content: [Update the generated pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/da1?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/da1.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/da1.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
MacOS is hiding the 404 error

**Comment by Rick-Anderson** [comment]
Try chrome
