### ISSUE TITLE
Document style observations, queries, and suggestions

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Docs#892]
@Rick-Anderson @danroth27 @ardalis I'd like to inquire on a few issues working with RST and the style guidelines for the first time.

#### CoreCLR or Core CLR
CoreCLR or Core CLR ... The engineering team seems to favor the latter (with a space), so I'm using that form. Ok?

#### Menu Selections
According to the style manual, menu sections are supposed to use the `menuselection` declaration, for example ...
```
:menuselection:`File --> New Remote PowerShell Tab...`
```
However, most authors have chosen (and peer review has allowed) either ...
```
**File -> New Remote PowerShell Tab...**
```
... and/or (sometimes mixing them in the same doc) ...
```
**File > New Remote PowerShell Tab...**
```
I'm going to use the last one, since it separates the list best from surrounding text, has the cleanest inter-menu item separator, and matches the rule on bold type for UI elements. Ok?

#### Format of instructions to the reader
I started with ellipses prior to showing commands, but that wasn't a good choice. What I do find necessary (grammatically) is that sentences are properly punctuated and all instructions to the reader are provided in complete sentences. Ok? [As the former editor of a college newspaper, it's in my genes to write this way.]

#### End sections not shown in TOC
> These should not be included in the bulleted list of topics, however.

... but that doesn't seem to be allowed if you want sections like "Additional Resources" to have the standard heading format and you use ...
```
.. contents:: In this article:
  :local:
  :depth: 1
```
... for the article TOC. Besides, why not provide them in the TOC? As a reader, I'd love to be able to quickly get to "Additional Resources" when I remember that there is a handy link there that I need.

#### Bullets vs. numbers markers for steps
At least one doc mixes bullets for steps with bullets for lists. I think that approach is somewhat disorganized, even if the markers for lists are indented.

One could argue that since a tutorial implies ordering top-to-bottom that the steps don't require a number or marker at all. However, numbering steps within sections provides several significant benefits ...

1. The reader will probably find it easier to keep track of their location in the doc.
2. Numbers make for a better logical separation of chronological steps.
3. Numbers permit un-marked sub-steps (i.e., paragraphs/sentences) and bulleted lists to exist cleanly within the major steps without conflict or confusion.
4. Image indentation will be consistent throughout the doc (detailed further below).
5. Numbers make it easier for anyone to refer to a specific step of a specific section. I could say to someone, "Refer to Azure Network Security Group (for our Nano Server VM) Step 2" [or by using the link and saying, "Refer to Step 2 of `<hyperlink_to_section_of_doc>`"] without ambiguity.

#### Lone headings in bulleted lists ... yuck
There must be an ancient outlining rule on this, because I've been instructed since elementary school back in the 1800's (I'm old) that headings must appear in at least pairs (i.e., no lone headings). That's always made sense to me, and it even looks hokey IMO not to outline that way.

Illustrated ...
```
I. 1st Level Heading
  A. 2nd Level Heading
    1. 3rd Level Heading <-- INCORRECT: Fold into I.A.
  B. 2nd Level Heading
    1. 3rd Level Heading
    2. 3rd Level Heading
II. 1st Level Heading
```
The heading at I.A.1. should be rolled into I.A., because there is no additional indication of multiple items under I.A. If you don't follow this rule, you end up with nutty looking outline formats like this, which actually appears in the docs in at least one spot ...
```
I. 1st Level Heading
  A. 2nd Level Heading <-- INCORRECT: Fold into I.
II. 1st Level Heading
  A. 2nd Level Heading <-- INCORRECT: Fold into II.
```

#### Inconsistent image indentation
Some images (at least in one doc) have been rolled into unordered lists when rendered. This has the effect of indenting the images from the left margin, which doesn't match the rendering of other images (outside of unordered lists) elsewhere in the doc. [This goes back to my earlier point about just numbering the steps. If the steps are numbered, this problem will go away, too.] I get that steps wouldn't be auto-numbered for you, but humans are going to have to maintain some of the doc's infrastructure. That's what we're being paid for, right?! :smile:

#### The Nano doc
If there is a general question/concern on how attention to these items would play out in a doc, my PR for Nano is almost done. I'll have it submitted in a few hours, and you'll see what I mean by example.

**Comment by Rick-Anderson** [comment]
@GuardRex 
Go with "Core CLR"
Menu's - yes - that's what we're doing now 
 "Additional Resources"  should be in the TOC

On numbers v. bullets.
If this were HTML and we could use automatic numbering, we'd using numbering. But given this is RST and #. breaks when you add code, images, etc, then you're forced to hard code numbers (bad).

If I can use #. for auto-numbering, that's what I use. Given that's rare, I usually use bullets. Sometimes I'm forced to hard code numbers (when numbers work better)

Yes on no lone headings

We'd like to have images indented correctly.

On the nano-doc - we'd like to see the first part a quick start with-out a management VM. We want to have the lowest friction approach. The next part would use the management VM.

**Comment by GuardRex** [comment]
@Rick-Anderson

> you're forced to hard code numbers (bad)

Agree with "bad" ... but it helps the doc quite a lot ... especially this monster! I'm glad you stated "I'm forced to hard code numbers (when numbers work better)" ... that's the case with this one.

> On the nano-doc - we'd like to see the first part a quick start with-out a management VM. We want to have the lowest friction approach. The next part would use the management VM.

It would be fairly easy to strip out all of the security bits for a small footprint quick start version. It would be just like my first draft Word version. However, I've been prepping the full security version first. That's what I'll have here in the next hour or two.

If it's ok, let me put this one up to you cats somehow (it's in RST now getting final touches). Then, I can either (a) strip out all of the security bits for a quick start version (the only version), (b) leave it as is (the only version), or (c) strip out the security bits and somehow fold the quick start into the head of the current document ... that might be what you implied, since you were saying "next part."

Just my 2 cents: Given the headless nature of Nano, the virtual necessity to have logs available and Event Viewer for .NET 5 app trobleshooting, and the nature of hacking today (off the charts wild west), I still think the full pro-security version is the best way to go. A quick start is very likely going to get people into security trouble fast, and I can see less-security conscious dev-ops folks creating sets of web servers that present a vast attack surface due to open management ports all over the place. Just my 2 cents and I'll shut up about it now. :smile:

What's the best way for me to get the current RST version to you? ... I mean if you want to see it outside of a PR ... or do you want me to submit it as a PR?

**Comment by Rick-Anderson** [comment]
submit a PR when it's ready to review.

**Comment by GuardRex** [comment]
cool ... maybe an hour to go! ... then ... :beers:
