### ISSUE TITLE
Issue With Add Scaffolding

### ISSUE THREAD

**Issue by yasirnz** [aspnet/Docs#8926]
I am trying to add "MVC Controller with views, using Entity Framework " but in my dialog box, the option is not available. Means I don't have the option to create MVC controller with Entity Framework but I have all others options. Even though I updated my visual studio and everything. Please let me know what I am missing? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d975a83-1550-b284-d0d8-7fe2ea206ff5
* Version Independent ID: 48e81b42-7c2b-afbf-71e6-d4f442a4bd1f
* Content: [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-model?view=aspnetcore-2.1#scaffolding-a-controller)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
What version of Visual Studio do  you have? What version of .NET Core (run `dotnet --version`). Post a screen shot.

**Comment by yasirnz** [comment]
I am using visual studio 2017 updated one
