### ISSUE TITLE
The name 'Initial' is used by an existing migration.

### ISSUE THREAD

**Issue by unforgettableAshwin** [aspnet/Docs#8929]
When I run "Add-Migration Initial", I get "The name 'Initial' is used by an existing migration."

Is this an error or just informational?
Can I ignore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1#pmc)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by unforgettableAshwin** [comment]
It appears to just be informational.  

I ran the following command (Update-Database) and successfully tested the links.

**Comment by Rick-Anderson** [comment]
No it's not informational.

`Add-Migration Initial` first time works
`Add-Migration Initial` 2nd time your error
`Update-Database` works

**Comment by MikePerholtz** [comment]
To expand on [Rick Anderson's answer](https://github.com/aspnet/AspNetCore.Docs/issues/8929#issuecomment-428308657), the bash shell command I used from a VSCode for Mac Terminal was:

`dotnet ef database update`

**Comment by oolivarez-cealsa** [comment]
for this problem i used Remove-Migraction, this command remove previus migration and after you can write the commands Add-Migration Inital.. and Update-Database
