### ISSUE TITLE
Question around CompatibilityVersion

### ISSUE THREAD

**Issue by daveabrock** [aspnet/Docs#8932]
In the HEAD section, this document says to "Opt in to this behavior with the SetCompatibilityVersion method in Startup.Configure for ASP.NET Core 2.1 to 2.x," then outlines the `services.AddMvc()   .SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Version_2_1)` method. However, when creating a new project, this method is there by default. Should the language be changed to reflect that? If so, I can do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes. Add wording that the current templates add that. Also need something like version 2.1 and later. The 2.2 templates add
`services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);`

**Comment by daveabrock** [comment]
Sounds good, @Rick-Anderson. I'll phrase it where the parameter will be reflective of the version they are on.
