### ISSUE TITLE
Explain use of open generics

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#8933]
See https://github.com/aspnet/Docs/issues/8891

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d78f540-81fd-1ba9-cb90-591e4ec27d9b
* Version Independent ID: 2251f557-dd3a-ec35-2558-6243337db009
* Content: [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/dependency-injection.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/dependency-injection.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@BillWagner 	I can't find any docs on open generics.

**Comment by BillWagner** [comment]
It is covered in the  [C# language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#open-and-closed-types)

I don't think we have any conceptual or scenario based docs covering the concept.

**Comment by Rick-Anderson** [comment]
@BillWagner 	but searching on "open  generic" fails. Can we fix searching for "open generic"?

**Comment by Rick-Anderson** [comment]
[c# open generic](https://www.google.com/search?q=c%23+open+generic&rlz=1C1CHBF_enUS801US801&oq=c%23+open&aqs=chrome.0.69i59j69i58j69i57j69i60l2j0.3215j0j7&sourceid=chrome&ie=UTF-8) has lots of hits, but nothing from docs.ms.com

**Comment by Rick-Anderson** [comment]
Created https://github.com/dotnet/csharplang/pull/2131 to help.
