### ISSUE TITLE
PasswordOptions table is broken

### ISSUE THREAD

**Issue by geoperez** [aspnet/Docs#8938]
The markdown table is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3ac09f0-74ca-1a5d-4fec-695b84c1ac95
* Version Independent ID: cd2c1f5e-e4f0-d2c3-4737-8ff4f0c176c2
* Content: [Configure ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/identity-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @AdrienTorris
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @geoperez ... I'll patch that up right now.
