### ISSUE TITLE
Menus no longer match pictures.

### ISSUE THREAD

**Issue by RileyMathews** [aspnet/Docs#8947]
When going through this guide I was getting strange errors until I realized I created the wrong type of solution while following the pictures here. The picture here says to use the ASP.NET Core Web App solution template. When in fact the current menu option for that is for a different template. The template this guide needs appears to now be labeled as 'ASP.NET Core Web App (MVC)'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f1722c-b4e6-920f-4a0e-0124de35719e
* Version Independent ID: 7853becb-e6df-4820-cb22-76f51e3c4442
* Content: [Get started with ASP.NET Core MVC and Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/start-mvc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-mac/start-mvc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-mac/start-mvc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RileyMathews 	 thanks. We'll get this fixed in the next doc sweep.

**Comment by danroth27** [comment]
Should be fixed now. Thanks!
