### ISSUE TITLE
request OAuth tutorials for Web API

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#895]
see https://docs.asp.net/en/latest/security/authentication/introduction-to-aspnet-identity.html#comment-2457875287
@rustd can you comment on this request?

**Comment by rustd** [comment]
@danroth27 ?

**Comment by Rick-Anderson** [comment]
@MikeWasson  can you comment on cust request to have OAuth WebAPI tutorials.

**Comment by jon49** [comment]
There's this https://identityserver.github.io/Documentation/docs/overview/simplestOAuth.html tutorial but it's a little dated. So, I'm not sure how to get passed setting up with:

```csharp
    // configure web api
    var config = new HttpConfiguration();
    config.MapHttpAttributeRoutes();

    // require authentication for all controllers
    config.Filters.Add(new AuthorizeAttribute());
```

So, it would be nice to have a tutorial for authenticating username/password and the token it creates. In my use case I have an internal server that isn't public facing that I will be using to pass the username/password and token too which return the user information. So, if anyone knows where there might be a tutorial on how to do that would be great! I'm still pretty new to ASP.NET in general so this has been a bit of a bear.

**Comment by danroth27** [comment]
See http://leastprivilege.com/2016/01/11/announcing-identityserver-for-asp-net-5-and-net-core/. We plan to start producing content on using Identity Server 4 with ASP.NET 5 in late Feb/early March.
