### ISSUE TITLE
Add ApiController info to model validation doc

### ISSUE THREAD

**Issue by ostan** [aspnet/Docs#8951]
Would be nice to add a few notes about how to suppress or customize this built in behavior (e.g. using SuppressModelStateInvalidFilter on StartUp)
Found it here: https://stackoverflow.com/questions/51125569/net-core-2-1-override-automatic-model-validation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0156ffc3-47ac-d5da-fbc2-9ff5018b071b
* Version Independent ID: 615db388-a244-41f7-21b5-a4085d9ed479
* Content: [Model validation in ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/validation.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tdykstra** [comment]
@ostan Thanks for the suggestion.  We'll add an API controller to the sample app and a new section about it to the article.

**Comment by scottaddie** [comment]
The association between `ApiControllerAttribute` and model validation was added in https://github.com/aspnet/Docs/commit/01cbe3293ee5e3c8ee94eb6b983f1b490f4d0f54#diff-32ecea2bb2ea2e9e3fa915ff43125fcf. The doc points to the **Automatic HTTP 400 responses** section of the attribute's doc, which shows how to suppress the behavior.
