### ISSUE TITLE
Link to the article on sharing data between the controller and view needs to be brought into the official documentation.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [aspnet/Docs#8955]
The bit where it says "See ViewModel vs ViewData vs ViewBag vs TempData vs Session in MVC for more information" links to some old third party blog with poor grammar and broken sample code. This is a critical part of the infrastructure being decribed here and so it needs to be rewritten into the official documentation properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788d46c9-a91a-2788-8db7-b53c37b512f2
* Version Independent ID: 00c2c01d-d235-2d2d-5c96-1f33a9314382
* Content: [Add a view to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-view.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-view.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
View models is the gold standard. However, with Razor Pages, View model is built in. Have you considered Razor Pages?

**Comment by Neutrino-Sunset** [comment]
I'm a bit confused as to what that has to do with the point I made, but to answer your question I'm maintaining an existing application and rearchitecting that part of its implementation is not in scope.

More generally Razor looks cool and all, but despite the documentation I've read I haven't yet seen anything that describes what problem it is intended to solve. These days we are reusing so much code from various sources that there is a lot of learning involved and anything that adds to that needs to justify its usage by solving a clear and pressing problem. It's just not clear to me that Razor does.
