### ISSUE TITLE
IP Address range

### ISSUE THREAD

**Issue by dustinmoris** [aspnet/Docs#8956]
Hi, I needed to safelist a range of IPv4 and IPv6 addresses by Cloudflare but unfortunately this article didn't help me as it only shows how to safelist individual IP addresses rather then ranges of IP addresses. I've implemented a small NuGet package which can help to overcome this problem. Maybe it's worth mentioning it here: https://github.com/dustinmoris/Firewall

Edit by @Rick-Anderson 	
1.7 K PV/month

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517dfd6c-0771-77d8-66e1-d07724134c6c
* Version Independent ID: 51de9bc4-775c-36b6-79d4-71ff635b53a6
* Content: [Client IP safelist for ASP.NET Core](https://docs.microsoft.com/en-US/aspnet/core/security/ip-safelist?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/security/ip-safelist.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/ip-safelist.md)
* Product: **aspnet-core**
* GitHub Login: @damienbod
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@Tratcher Can Host Filtering Middleware (Kestrel edge) or Forwarded Headers Middleware (reverse proxy) work in the same capacity for this scenario?

**Comment by Tratcher** [comment]
I didn't even know we had that doc. Who reviewed it? It needs a little work (it's really inefficient).

We don't have middleware that filter the client IP directly, but the Forwarded Headers Middleware does filter reverse proxy IPs this way. You could take the [IPNetwork](https://github.com/aspnet/BasicMiddleware/blob/6339351ddc1a6815e2cb8fe32da6fa341e877173/src/Microsoft.AspNetCore.HttpOverrides/IPNetwork.cs) class from HttpOverrides and use it to filter based on subnet ranges.

**Comment by SOLiNARY** [comment]
@dustinmoris
You can use IPAddressRange for this:
[code]
                var whitelistIpRange = IPAddressRange.Parse("13.108.0.0/14");
                if (whitelistIpRange.Contains(remoteIp))
                {
                    // do something
                }
[/code]

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by skwebies** [comment]
This implementation is throwing an exception on Asp.net core 2.2, please check this: System.InvalidOperationException: 'A suitable constructor for type 'AdminSafeListMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.'

**Comment by Tratcher** [comment]
Comments on closed issues are not tracked, please open a new issue with the details for your scenario.

@skwebies please show your usage, that's the error you get when you don't pass in enough parameters.
