### ISSUE TITLE
version attribute is not specified

### ISSUE THREAD

**Issue by theangellmethod** [aspnet/Docs#8963]
In the "Add support for Entity Framework Core" section, it says to add the version attribute.  However, in the doc and in the code, this attribute is not there.  I can't tell if this means that the version attribute should be added into the doc and code or if the reference to adding the version attribute should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9847872-0958-fec8-12f9-dc81b1dea67b
* Version Independent ID: 76dd2c7f-aa3f-ec2a-301d-3e288dc4938d
* Content: [Create a Web API with ASP.NET Core and Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/web-api-vsc?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/web-api-vsc.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/web-api-vsc.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@theangellmethod 	thanks for pointing this out. #8963 fixes it. You don't add a version.
