### ISSUE TITLE
How can I download just the project I need ?

### ISSUE THREAD

**Issue by TXX-JSR** [aspnet/Docs#8967]

**Comment by TXX-JSR** [comment]
It takes too long to download 800MB - how can I download just the project I need ?

**Comment by Rick-Anderson** [comment]
@TXX-JSR 	sorry, that's how GitHub works.

**Comment by TXX-JSR** [comment]
There is CHROME a plugin to do this:  https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn  

I believe it exists for Firefox as well

**Comment by Rick-Anderson** [comment]
@dend @mairaw 	@BillWagner 	@danroth27 	@tdykstra 	@scottaddie 	@guardrex 	
Downloading the entire repo for one sample is a frequent customer complaint.

**Comment by Rick-Anderson** [comment]
cc @SyntaxC4

**Comment by mairaw** [comment]
I agree. This should probably be moved to https://github.com/microsoftdocs/feedback, no?

**Comment by Rick-Anderson** [comment]
moved to https://github.com/MicrosoftDocs/feedback/issues/982
