### ISSUE TITLE
Requesting ResetPasswordAsync

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#8974]
From @mskovacic  in #7146
Any updates regarding ResetPasswordAsync() coming soon?

It doesn't have to be an async version, but I suppose it will be because most of the UserManager methods are async. I'd just like to see how to verify the password reset token? I found the ConfirmEmail implementation https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity
but for ResetPassword it is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe1bea60-d173-f6d2-3559-b147699e295a
* Version Independent ID: 98e7aacb-2a01-d581-9b03-bfef2893163e
* Content: [Account confirmation and password recovery in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio#enable-account-confirmation-and-password-recovery)
* Content Source: [aspnetcore/security/authentication/accconfirm.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/accconfirm.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK 	please comment.

**Comment by kienlamb** [comment]
Is this generated token using the time based token provider so it would have to be renew in about 3 minutes?

**Comment by HaoK** [comment]
I'm not sure what the question is, there is a ResetPasswordAsync method:

https://github.com/aspnet/Identity/blob/master/src/Core/UserManager.cs#L908

```C#
        /// <summary>
        /// Resets the <paramref name="user"/>'s password to the specified <paramref name="newPassword"/> after
        /// validating the given password reset <paramref name="token"/>.
        /// </summary>
        /// <param name="user">The user whose password should be reset.</param>
        /// <param name="token">The password reset token to verify.</param>
        /// <param name="newPassword">The new password to set if reset token verification succeeds.</param>
        /// <returns>
        /// The <see cref="Task"/> that represents the asynchronous operation, containing the <see cref="IdentityResult"/>
        /// of the operation.
        /// </returns>
        public virtual async Task<IdentityResult> ResetPasswordAsync(TUser user, string token, string newPassword)
```

**Comment by HaoK** [comment]
The default reset password token is using the email based one which ha 24 hour expiration @kienlamb but its configurable which token provider is used

**Comment by kienlamb** [comment]
I have the setting below and ran into the approximately 3 minutes issue when resetting password. 
 options.Tokens.PasswordResetTokenProvider = TokenOptions.DefaultEmailProvider;

We are running our services inside docker containers and don't have a shared encryption key so switching to time based does work solve our password reset problem but limited to this ~3 minutes constraint.  I think the right solution is to create the encryption provider using a shared certificate.  We haven't had a chance to try that out yet though.  If you don't think will work, please let me know.  Thanks!

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
