### ISSUE TITLE
Async-await and Task confusion

### ISSUE THREAD

**Issue by msaadsaif5** [aspnet/Docs#8978]
Considering the first two methods of ChatHub, first one uses aync-await, while the second one simply returns the task. Is this for demonstration purpose only or there is some logic behind it? what is recommended approach and why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
See https://github.com/aspnet/Docs/issues/7876

**Comment by tdykstra** [comment]
Closing this as the topic is covered by #7876.  Feel free to reopen if there are additional questions not covered by the other issue.
