### ISSUE TITLE
antiforgery-options says to use deprecated parameters. 

### ISSUE THREAD

**Issue by LindaLawton** [aspnet/Docs#8979]
Documentation [antiforgery-options](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1#antiforgery-options)  appears to be out of date.  It says to use   

```
services.AddAntiforgery(options => 
{
    options.CookieDomain = "contoso.com";
    options.CookieName = "X-CSRF-TOKEN-COOKIENAME";
    options.CookiePath = "Path";
    options.FormFieldName = "AntiforgeryFieldname";
    options.HeaderName = "X-CSRF-TOKEN-HEADERNAME";
    options.RequireSsl = false;
    options.SuppressXFrameOptionsHeader = false;
});
```

I am getting deprecated warnings from ` CookieDomain, CookieName, CookiePath and requireSsl.`  If these values are deprecated maybe the documentation should be edited to show what should be used instead.

Looks like it should be something like this. 
```
services.AddAntiforgery(options =>
            {
                options.Cookie.Domain =  "contoso.com";
                options.Cookie.Name = "X-CSRF-TOKEN-COOKIENAME";
                options.Cookie.Path = "Path";
                options.FormFieldName = "AntiforgeryFieldname";
                options.HeaderName = "X-CSRF-TOKEN-HEADERNAME";
                options.Cookie.SecurePolicy = CookieSecurePolicy.SameAsRequest;
                options.SuppressXFrameOptionsHeader = false;
            });
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Yes, thanks for catching this @LindaLawton ... should have been versioned with the new content at 2.0 but got under the radar. I'll square it away asap.

**Comment by LindaLawton** [comment]
I wold offer to submit a pull request but as i am actually using it to figure out what i'm doing wrong i am probably not the best person :)
