### ISSUE TITLE
TagHelper article - Revise Websiteinfo example

### ISSUE THREAD

**Issue by philipp985** [aspnet/Docs#898]
Great articles very helpful for starting to write customized Tag Helpers.
I found one mistake in your example concerning the websiteinfo Tag Helper.
In:
WebsiteInformationTagHelper.cs
Line 14 Should be changed from:
 output.Content.SetContent(
To:
output.Content.SetHtmlContent(
otherwise the example is not working at least on my machine.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/commit/5a4e5e9bb9efd50cec5effb409bbf5cb8dba6486
