### ISSUE TITLE
Provide Guidance for SignalR Java Client Logging

### ISSUE THREAD

**Issue by mikaelm12** [aspnet/Docs#8991]
The SignalR Java client uses slf4j as it's logging abstraction. Because users don't actually need to provide a logging implementation, the library defaults to use a NOP logger. While that is fine, it prints these things to System.err which is less than desirable. 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Filing this issue to track adding guidance in the SignalR Java client docs to help users deal with this.

**Comment by anurse** [comment]
Note this is for **preview 3** and later specifically.

**Comment by mikaelm12** [comment]
Guidance provided here: https://github.com/aspnet/Docs/pull/9112
