### ISSUE TITLE
Spelling mistake - develope

### ISSUE THREAD

**Issue by cdrmuir** [aspnet/Docs#8997]
Section: Why use ASP.NET core?
Bullet point 4, spelling mistake, "develope" instead of "develop"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [Introduction to ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hi @cdrmuir ... It was just fixed on https://github.com/aspnet/Docs/pull/8968. It will go live shortly.
