### ISSUE TITLE
Create a Razor Pages web app is a very good tutorial

### ISSUE THREAD

**Issue by SusheelVig** [aspnet/Docs#9007]
Every thing is explained line by line in a very clear manner and it is working without any problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @SusheelVig!
