### ISSUE TITLE
Framework Tie ins?

### ISSUE THREAD

**Issue by MrAntix** [aspnet/Docs#9011]
May we have a generic template whereby we can choose our own frontend framework?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c220c416-4250-15cd-b421-bf20e265f9db
* Version Independent ID: 855f56d8-3533-cb1e-c0ed-3ce0ba945df4
* Content: [Use the Single Page Application templates with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/index?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/spa/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/index.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @MrAntix ... Your request should go to the product team. We only handle documentation issues here on the docs repo. Open your request over in the [aspnet/Templating issues](https://github.com/aspnet/templating/issues), where the engineers will see it.

You probably already know this, but I'll just mention in passing in case anyone else finds this later that a generic backend template would be of the "webapi" variety described over in the [dotnet new](https://docs.microsoft.com/dotnet/core/tools/dotnet-new#template-options) command template options. There are probably a few over here as well :point_right: https://dotnetnew.azurewebsites.net/.
