### ISSUE TITLE
Is the Facebook package really necessary?

### ISSUE THREAD

**Issue by derth** [aspnet/Docs#9014]
I can register/login with Facebook just fine, without it. Is it only used for some advanced api functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c6faa2-8c65-073b-4988-672c1aa9690c
* Version Independent ID: d22d616f-907e-ae62-1f43-88ad176a87d4
* Content: [Facebook external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/facebook-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/facebook-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by olcay** [comment]
It is not really necessary, you can use Facebook Authentication without the package.
The package makes it easy to integrate and maintain by providing default API functionality of Facebook.
Like the method `AddFacebook()` as in the example.

You can find the details [here](https://github.com/aspnet/Security/tree/master/src/Microsoft.AspNetCore.Authentication.Facebook).

**Comment by Rick-Anderson** [comment]
> Facebook authentication requires the Microsoft.AspNetCore.Authentication.Facebook NuGet package. 

So that should be removed - or added later in the doc to say it provides advanced APIs but is not required for auth?

cc @01binary

**Comment by derth** [comment]
Yes, i think so.

**Comment by 01binary** [comment]
I had a chance to look at this again - explicitly adding the Facebook package is no longer necessary as @derth said.
