### ISSUE TITLE
Add version selector image

### ISSUE THREAD

**Issue by diberry** [aspnet/Docs#9015]
The asp.net core mvc with EF core tutorials have no actual tutorial steps -- just information about why shouldn't I pick razor. I'm an angular deveoper and only use EF on the back end of asp.net core. Based on the tutorial not including any steps and the implication that I should be using razon, I think I'm in the wrong section of the docs. I still need to know how to use asp.net core with EF -- where would that tutorial be? 

All the pages in this series of tutorials have the exact same content. Is that on purpose? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d420a47c-b0c7-b242-3116-3d6382467ffb
* Version Independent ID: 06d9d8e6-7069-fd79-561c-363cc4487821
* Content: [ASP.NET Core MVC with EF Core - CRUD - 2 of 10](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/crud?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-mvc/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-mvc/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by Rick-Anderson** [comment]
@diberry 	yes, please read it. I'll add a screen shot to clarify for folks who don't read it.

**Comment by Rick-Anderson** [comment]
> . I still need to know how to use asp.net core with EF -- where would that tutorial be?

For 2.2, the RP. For 2.1, the MVC version will work.

**Comment by H35am** [comment]
Please bring back the pages!

**Comment by Rick-Anderson** [comment]
The pages are there, use the version selector to access them.
