### ISSUE TITLE
Include other normal razor page(with *.cshtml.cs file) as a "Partial"

### ISSUE THREAD

**Issue by eq7755** [aspnet/Docs#9017]
May I ask if it is possible to add another razor page(with *.cshtml.cs file) as a "Partial". 
For example in index.cshtml file using:
&lt;partial name="About"/&gt;

However, when I do like this, I met an error as following:
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'WebApplication6.Pages.IndexModel', but this ViewDataDictionary instance requires a model item of type 'WebApplication6.Pages.AboutModel'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @eq7755 ... I don't think that's a supported scenario. In this scenario, take a look at the [View Component](https://docs.microsoft.com/aspnet/core/mvc/views/view-components).

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
