### ISSUE TITLE
HTTP Error 400 on Create

### ISSUE THREAD

**Issue by Shampit** [aspnet/Docs#9018]
Whenever i try to create an new movie for the table i get HTTP Error 400

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Shampit start debugging. Compare the `@page` directive to the details/edit.

**Comment by westerandr** [comment]
I have the same issue even in debug mode, the details edit and create all seem to be fine

**Comment by capitao014** [comment]
@Shampit did you manage to solve the problem?
I face the same problem and I'm not able to solve it, can you help me?
