### ISSUE TITLE
I like that you can download the PDF of these

### ISSUE THREAD

**Issue by ajw1970** [aspnet/Docs#9019]
Nice for taking to an e-reader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Test controller logic in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
We appreciate the feedback. Glad to hear that feature is helpful to you.
