### ISSUE TITLE
List IISIntegration overrides

### ISSUE THREAD

**Issue by ArveSystad** [aspnet/Docs#9024]
UseIISIntegration =&gt; It says it overrides settings "Such as...". Would be nice with a list over the exact methods it overrides. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ArveSystad ... Thanks for commenting. I'll get back to you on this shortly.

**Comment by guardrex** [comment]
@Tratcher Is there anything else outside of URL configuration (`UseUrls`, `Listen` options)? The passage is ...

> The ASP.NET Core Module generates a dynamic port to assign to the back-end process. `CreateDefaultBuilder` calls the `UseIISIntegration` method, which picks up the dynamic port and configures Kestrel to listen on `http://localhost:{dynamicPort}/`. This overrides other URL configurations, such as calls to `UseUrls` or Kestrel's `Listen` API. Therefore, calls to `UseUrls` or Kestrel's `Listen` API aren't required when using the module. If `UseUrls` or `Listen` is called, Kestrel listens on the port specified when running the app without IIS.

Either way, I plan to revise the "such as" language.

**Comment by Tratcher** [comment]
"Kestrel _only_ listens on"

Also include the config or command line Urls option.

In 2.1 we changed UseIISIntegration from [registering](https://github.com/aspnet/IISIntegration/pull/470) `http://localhost:{dynamicPort}/` to `http://127.0.0.1:{dynamicPort}/`.
