### ISSUE TITLE
SignalR Security Docs - Clarify cookie vs querystring token

### ISSUE THREAD

**Issue by SeanKilleen** [aspnet/Docs#9026]
Hi all, I'm willing to submit a PR for this to update the docs if I can get a clarified understanding.

# Issue description

I'm in the process of working with our client's security team on mitgiating some findings of their automated security tool, which reported a finding because of a "session token reported in URL".

The [Introduction to SignalR Security doc](https://github.com/aspnet/Docs/blob/master/aspnet/signalr/overview/security/introduction-to-security.md) states:

> SignalR passes the connection token as a query string value, instead of as a cookie. Storing the connection token in a cookie is unsafe because the browser can inadvertently forward the connection token when malicious code is encountered. Also, passing the connection token in the query string prevents the connection token from persisting beyond the current connection. Therefore, a malicious user cannot make a request under another user's authentication credentials.

The security team responded with this point, which I think is a fair one:

> If malicious code is encountered it would be trivial (and much easier) to simply extract the token out of the URL. Further - with the token in the URL it will show up in logs and in referer headers (as described in the report).  There are protections you can employ on cookies to prevent malicious access and from it being sent where it shouldn't be (httponly and path flags). 

This point seems reasonable, so I wonder if there's something that I'm missing here conceptually. Is it that the token isn't truly a session token? How does SignalR protect against someone impersonating a user account and re-using a token? Is the user verification more robust than I understand? 

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Framework 4.x (seems independent of minor version number)

**Comment by SeanKilleen** [comment]
Pinging contributors to the doc as they may have quick clarification that I can use to submit a PR. Apologies if this ping is unwelcome; it seemed the most efficient way to rope the right folks in for a conversation.

@pfletcher, @tfitzmac, @Rick-Anderson, @scottaddie, @v-anpasi, @tdykstra, @neusamir, @gewarren, @guardrex.

**Comment by tdykstra** [comment]
cc @anurse

**Comment by anurse** [comment]
I don't have enough background on this token to comment right now. I can try to get more information. cc @davidfowl

**Comment by SeanKilleen** [comment]
@anurse this is hugely helpful and makes a lot of sense; thanks! Assuming this satisfies the security folks (as I imagine it will), I'll summarize this and add a PR for it. 

I appreciate the quick & thorough response!

**Comment by anurse** [comment]
No problem! Please feel free to reach out with any other questions!

**Comment by Rick-Anderson** [comment]
@SeanKilleen 	a PR with that information would be very appreciated.

**Comment by bethelce** [comment]
hi, @anurse , thank you for your input. I am trying to figure out if the connectionid is the session token here.

**Comment by bethelce** [comment]
in addition, is showing the connectionid on response a vulnerability?

**Comment by guardrex** [comment]
Hello @bethelce ... please open a new issue using the **Content feedback** button at the bottom of the topic. We don't work closed issues.
