### ISSUE TITLE
Missing code snippet in "Configure localization" and "Localization middleware"

### ISSUE THREAD

**Issue by TrieBr** [aspnet/Docs#9029]
The documentation shows code snippets under these two sections, but the code snippets are blank. Empty in both Chrome and Edge, I've also checked various version (ASP Core 2.2 Preview 2, ASP Core 2.1, 2.0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.0#configure-localization)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
**_Ooooooops!_** 🙈 Thanks for reporting this @TrieBr. It probably happened on a recent doc update. I'll get a patch in there shortly to bring them back.
