### ISSUE TITLE
Links in Request Features points to beta-5

### ISSUE THREAD

**Issue by ankitbko** [aspnet/Docs#903]
Most of the links in [request-features.rst](https://github.com/aspnet/Docs/blob/dev/aspnet/fundamentals/request-features.rst) points to beta-5 branch. Shouldn't this be updated to point to master branch?

**Comment by danroth27** [comment]
For now, yes. Eventually all links to types should point to the API reference docs, but we are still waiting on a fix to the .NET Sphinx Domain to make that happen.
