### ISSUE TITLE
Typescript based React Spa Template Disappeared

### ISSUE THREAD

**Issue by simpert** [aspnet/Docs#9032]
On my work PC I recently used the template and it provided a familiar and sought after Typescript base. However, upon activating the template on my Surface in Visual Studio 17 update 3 I can no longer find the typescript based template. I would like to use the typescript template not the new vanilla js template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261c9875-3db6-4d30-f9d6-922a9334ecb2
* Version Independent ID: b8f8f7c4-9c90-869d-9fd7-a887bc28f262
* Content: [Use the React project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-2.1&tabs=visual-studio&viewFallbackFrom=aspnetcore-1.1)
* Content Source: [aspnetcore/client-side/spa/react.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react.md)
* Product: **aspnet-core**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
See https://github.com/aspnet/Templating/issues/242 for an explanation of the change.

**Comment by simpert** [comment]
@scottaddie can you please give us 2 template options one with ts and the new massive create react app one. funny fact I just realized that were talking about react which is massively notorious for shipping breaking changes. This template thing has introduced many issues for me Today as I expected I could get the TS template I was working on at work last week. The ts template seemed great to me and I would expect most aspnet users prefer typescript as vanilla js offers an inferior developing experience.

**Comment by scottaddie** [comment]
@simpert Can you please include this request/feedback in the aspnet/Templating repo? You can use the issue I linked to above. The product team would love to hear this type of feedback, and that's the best place for them to find it.

**Comment by simpert** [comment]
ok thanks for replying so quickly @scottaddie
