### ISSUE TITLE
Taks Runner Manager / Gulpfile with latest version of node.js and VS 15.8.5 did not work. 

### ISSUE THREAD

**Issue by Moomite** [aspnet/Docs#9040]
I got it working after adding tasks.json and replacing current version of node.js loading older version of node following the advice found at: 
https://developercommunity.visualstudio.com/content/problem/312584/update-158-broke-task-runner-gulpfile.html

It wasn't an easy find.

Do you have a plan to fix this? It seems pointless to suggest to use gulp if Task Runner does not work with latest version of VS. At least advise how to get around it and share what is your pathway forward for this or whatever your alternative development path will be.

Anyway I am hardly and expert on all this just sharing as it was quite frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfb34beb-733d-ad1e-37a7-cbe045ee9f15
* Version Independent ID: 02319a95-6eb9-59cd-f5fc-747c61e90123
* Content: [Use Gulp in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp?view=aspnetcore-2.1)
* Content Source: [aspnetcore/client-side/using-gulp.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/using-gulp.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Moomite 	thanks for bringing this to our attention. cc/ @scottaddie

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
