### ISSUE TITLE
Migrating Existing HTTP Modules to ASP.NET

### ISSUE THREAD

**Issue by mperdeck** [aspnet/Docs#905]
I saw that these chapters are still to be done. I would like to offer to write all or some of them:

Migrating HTTP Modules to Middleware
http://docs.asp.net/en/latest/migration/http-modules.html

Create a New NuGet Package with DNX
https://docs.asp.net/en/latest/dnx/create-package.html

Migrating an Existing NuGet Package Project
https://docs.asp.net/en/latest/dnx/migrate-package.html

My experience in these areas comes from converting my open source NuGet package JSNLog (jsnlog.com; 30,000 downloads) to ASP.NET 5, supporting DNX451 and DNXCORE50.

JSNLog is a JavaScript logging package that lets you log client side exceptions and other events automatically in your server side logs. The jsnlog.js client side library sends all log data to the JSNLog server side component, which hands the data to the user's server side logging package, such as NLog or Serilog.

This started life as an ASP.NET 4.x HTTP Handler. After I converted it, the one JSNLog package can now be used as an ASP.NET 4.x HTTP Handler and OWIN Middleware, and as an ASP.NET 5 Middleware with DNX451 and DNXCORE50.

Please let me know if you want me to write those chapters.

Matt Perdeck

**Comment by danroth27** [comment]
Sounds great! I recommend focusing on the Migrating HTTP Modules to Middleware article, as the other two articles will not be relevant once we move off of DNX and onto the [.NET CLI](https://github.com/dotnet/cli).

Do you want to put together an initial outline and send it to us to take a look at?

**Comment by mperdeck** [comment]
Hi Daniel,

Here is my initial outline for the Migrating HTTP Modules to Middleware
article:

* Firstly refer readers to the Middleware article in the ASP.NET 5
Documentation to get some understanding of what an ASP.NET 5 Middleware
looks like

* Difference in nature between an HTTP Handler and an ASP.NET 5 Middleware
(bit of text and picture, saying that essentially, HTTP Handlers only see
requests sent to some configured url wildcard, while a ASP.NET 5 Middleware
sits in a pipeline and sees everything)

* Comparing code structure of an HTTP Modules and that of a Middleware
(some overlap here with the Middleware article in the ASP.NET 5
Documentation, but helps people get a handle on what needs to be done)

* Creating a simple Middleware in VS 2015 that supports dnxcore
(other chapters also have these detailed walk throughs)

* Comparing configuration of an HTTP Module (in web.config) with that of an
ASP.NET5 Middleware

* How the new ASP.NET 5 HttpContext and HttpResponse (as used in the
Middleware) maps onto the ASP.NET 4 HttpContext and HttpResponse (as used
in the HTTP Module)
(fairly high level, focusing on what's relevant to HTTP Handlers /
Middleware, with links to pages with more details)

* Testing an ASP.NET 5 Middleware
(short recap and short example code illustrating dependency injection,
writing xUnit tests, etc., plus links to the relevant chapter)

If this sounds good to you, I would like to start writing the article this
coming weekend.

Thanks,

Matt

**Comment by danroth27** [comment]
Thanks @mperdeck! I think this looks reasonable, but I'd also like to get some folks on the engineering team to review before you spend a bunch of time writing the content. 

@Tratcher @DamianEdwards @davidfowl Could you please take a look? Are there other specific details that should be covered?

**Comment by Tratcher** [comment]
Sounds like a good place to start.

**Comment by davidfowl** [comment]
great article suggestion and outline. I would add modules and handler and I would compare them both to middleware.

**Comment by danroth27** [comment]
@mperdeck Looking forward to a PR!

**Comment by mperdeck** [comment]
Excellent! Starting work now.
