### ISSUE TITLE
Add details for SSL certificate and Kestrel Configuration

### ISSUE THREAD

**Issue by Praveen-Rai** [aspnet/Docs#9052]
This has been missing link in our Hosting section. 

Few references :
https://github.com/aspnet/KestrelHttpServer/issues/2902
https://stackoverflow.com/questions/52227372/asp-net-core-application-service-only-listening-to-port-5000-on-ubuntu
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcdd2c35-bf2b-2673-d150-303a8aaa54d2
* Version Independent ID: 815fe034-c9fc-aee3-a8b5-f2e860b30302
* Content: [Host ASP.NET Core on Linux with Nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/host-and-deploy/linux-nginx.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-nginx.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks ... I'm working on the links part of the HTTPS master issue this morning, so your timing is great. I'm moving this over to the HTTPS issue: https://github.com/aspnet/Docs/issues/6538
