### ISSUE TITLE
Undesirable two IUserStore implementations

### ISSUE THREAD

**Issue by reponemec** [aspnet/Docs#9072]
Have a look at the code under [Reconfigure app to use a new storage provider](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-2.1#reconfigure-app-to-use-a-new-storage-provider) and see operation `ConfigureServices` bottom the document:

```
public void ConfigureServices(IServiceCollection services)
{
    // Add identity types
    services.AddIdentity<ApplicationUser, ApplicationRole>()
        .AddDefaultTokenProviders();

    // Identity Services
    services.AddTransient<IUserStore<ApplicationUser>, CustomUserStore>();
    services.AddTransient<IRoleStore<ApplicationRole>, CustomRoleStore>();
    string connectionString = Configuration.GetConnectionString("DefaultConnection");
    services.AddTransient<SqlConnection>(e => new SqlConnection(connectionString));
    services.AddTransient<DapperUsersTable>();

    // additional configuration
}
```

I think call to `services.AddIdentity` and `services.AddTransient<IUserStore<ApplicationUser>`, `CustomUserStore>()` will result to register two `IUserStore` implementations (default and `CustomUserStore`).
I think rather then call to `services.AddTransient` is to use `IdentityBuilder.AddUserStore` extension method.

@Rick-Anderson 	 edit: 6.4 K PV, 25% CSAT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-1.1#the-data-access-layer)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK 	please review
This doc needs to be updated for 2.1 or later template generated code.

**Comment by Rick-Anderson** [comment]
@HaoK please review

**Comment by HaoK** [comment]
Yep need to register the same instance for both stores or its out of sync

**Comment by HaoK** [comment]
Oh actually I misread, so I don't think there's anything wrong with registering it directly instead of using AddIdentity.  Transient might not be appropriate for a lifetime always.  I was actually referring to the case when the same store is used for both user and role stores, I don't think there's an actual issue with directly registering `IUserStore<TUser>` generally (assuming the developer understands the lifetime implications of their choices).  The AddStore methods registers using scoped

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
