### ISSUE TITLE
Clarification of role of leading underscore

### ISSUE THREAD

**Issue by mikebrind** [aspnet/Docs#9073]
In the content above, it says this:
> When the file name starts with an underscore, Razor Pages doesn't process the markup file as a Razor Pages page, even when the file's markup includes the @page directive.

Can you clarify what "doesn't process the markup file as a Razor Pages page" actually means? Only if I add a file with a leading underscore in the name and add an `@page` directive and handler methods in a `functions` block, a route is built for the "page".  I can navigate to it and the handler methods execute as if the file is a Razor Page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d670c64c-4030-312c-4355-ee518a23a56a
* Version Independent ID: c20d4db8-d403-9218-c39d-47e56c34e767
* Content: [Partial views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/partial.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/partial.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@NTaylorMullen

**Comment by NTaylorMullen** [comment]
@mikebrind thanks for the report. Looks like what you're running into is an actual bug! I've filed an issue [here](https://github.com/aspnet/Mvc/issues/8617). If you are to do `<RazorCompileOnBuild>false</RazorCompileOnBuild>` everything works as expected.
