### ISSUE TITLE
RequireClaim method signature is a little confusing

### ISSUE THREAD

**Issue by benmccallum** [aspnet/Docs#9075]
public AuthorizationPolicyBuilder RequireClaim(string claimType, params string[] requiredValues);
public AuthorizationPolicyBuilder RequireClaim(string claimType, IEnumerable&lt;string&gt; requiredValues);

"requiredValues" is a confusing name as the method only checks for the presence of one of these values, not all. The parameter description is perfect, but I'm not sure if that's enough. I certainly got confused until I confirmed it in the docs here. Maybe something more generic like "values" would suffice? Or super explicit like "anyOfTheseValues" :P.

Not sure if this is the right place to log this. Can put it in the correct repo if that's better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25051544-0e4d-1715-95b7-3a8616475127
* Version Independent ID: 50736569-fc04-ec6d-7b33-a3e0c860b1ed
* Content: [Claims-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/claims?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/claims.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/claims.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @benmccallum ... Yes, this is the docs repo. We just work docs issues out of this repo. Try the aspnet/Security issues for this: https://github.com/aspnet/Security/issues

**Comment by benmccallum** [comment]
No worries. Closing.
