### ISSUE TITLE
update "Logging"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#908]
http://docs.asp.net/en/latest/fundamentals/logging.html

- [ ]  Needs an edit pass. 
- [ ]  API has changed, need to update code.
- [ ]  Good DISQUS questions unanswered.

For example:
You may see more than one log statement per web request you make in your browser, since most browsers will make multiple requests (i.e. for the favicon file) when attempting to load a page
--- Should be written as:
You may see more than one log statement per request; browsers can make multiple requests for a URI.
or
You may see more than one log statement per request; user-agents can make multiple requests for a URI.

**Comment by danroth27** [comment]
the logging APIs also went through some churn in RC2

**Comment by Rick-Anderson** [comment]
@kichalla Given that logging is a service and not a middleware, why is logging configured in ``Configure`` and not in ``ConfigureServices``?
http://docs.asp.net/en/latest/fundamentals/logging.html doesn't say what logging is, just how to use/config/etc.

**Comment by kichalla** [comment]
Good question. I think you should be able to do it in `ConfigureServices` itself (From what I see the hosting layer registers the `ILoggerFactory` service in DI before calling `ConfigureServices`)

cc @Tratcher @Eilon

**Comment by Eilon** [comment]
@davidfowl 

My guess? Just a matter of preference. Configure it wherever you want.

**Comment by davidfowl** [comment]
There's some discussion here about that https://github.com/aspnet/Logging/issues/346
