### ISSUE TITLE
Wrong Namespace Reference in Several PageModels

### ISSUE THREAD

**Issue by RyanLilla** [aspnet/Docs#9089]
Noticed that in some of the scaffolded PageModels in the example code the wrong namespace reference is given. 

For example, in the `Pages/Instructors/Index.cshtml.cs` [code snippet](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-instructor-model), the `_context` field is of type `ContosoUniversity.Data.SchoolContext`, but the namespace that actually contains the SchoolContext type is ContosoUniversity.Models (as specified when first scaffolding the Student model [here](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#scaffold-the-student-model)).

I was going to create a PR myself, but realized it would be better to first discuss what the most appropriate fix would be because there are a few:

1. Change all the lines of code from `private readonly ContosoUniversity.`**Data**`.SchoolContext _context;` to `private readonly ContosoUniversity.`**Models**`.SchoolContext _context;`

2. Keep the PageModels as-is, but change the steps in the tutorial to create the data context type in the ContosoUniversity.Data namespace instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RyanLilla 	I think the problem stems from parts 1-5 were rewritten for ASP.NET Core 2.1 with the 2.1 SDK, but 6-8 were not updated. We're going to update this to 2.2 when it RTMs - at that time we'll get all the code updated.

**Comment by Rick-Anderson** [comment]
Fixed in 2.2 update
