### ISSUE TITLE
What are ports 59518 & 44364 or are they just examples?

### ISSUE THREAD

**Issue by quole** [aspnet/Docs#9113]
```
EXPOSE 59518
EXPOSE 44364
```

Are these ports required for assembly or are they just given as an illustration? The example dockerfile should perhaps be commented with their purpose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d772b44a-b5f3-5a10-4ea3-4463bdcf90bb
* Version Independent ID: 5847cdf8-1823-7740-6e43-030902b26ad8
* Content: [Visual Studio Tools for Docker with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/docker/visual-studio-tools-for-docker.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **scaddie**

**Comment by spboyer** [comment]
@quole - ok to close this issue?

**Comment by quole** [comment]
All good, thank you!
