### ISSUE TITLE
Is the ~ necessary before static files in wwwroot like /images/banner1.svg?

### ISSUE THREAD

**Issue by theangellmethod** [aspnet/Docs#9119]
Using the ~ in my project as shown in ['Serve files inside of web root'](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.1&tabs=aspnetcore2x#serve-files-inside-of-web-root) was causing a 404 to display- when I removed it and only had the equivalent of /images/banner1.svg, the code worked fine.  Is the ~ necessary in ASP.NET Core 2.1?  I saw on the samples there is only a sample for 1.x with no index.hmtl and I also saw in the 'Get Started - Create a Web API' that the "site.js" file is not referenced with a ~ for the index.html file so it seems like it is not needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d47f38e2-bc36-cfb8-b0cc-17a534689f8b
* Version Independent ID: 3fec6e08-fc99-7a5c-796f-3f2347cad891
* Content: [Static files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/fundamentals/static-files.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/static-files.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by theangellmethod** [comment]
It seems like if you have something like:
wwwroot
--css
--images
--js
--index.html

that within the index.html you do not need to use the ~ to reference other items in the wwwroot.  This would match what I am seeing and the tutorial.  Is that true?

**Comment by Rick-Anderson** [comment]
You do. For example, in the layout file
`<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />`

**Comment by theangellmethod** [comment]
In this sample, https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api/samples/2.1/TodoApi/wwwroot/index.html, it shows 

`<script src="site.js"></script>` 

- what is the difference between that and the bootstrap example above?

**Comment by Rick-Anderson** [comment]
That should be fixed.
