### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by shirhatti** [aspnet/Docs#912]
This is the current 404 page on the Docs website.
<img width="1639" alt="screen shot 2016-01-21 at 12 45 36 pm" src="https://cloud.githubusercontent.com/assets/4734691/12494031/f10d2bba-c03c-11e5-8420-9ed4c00f7f09.png">

Can we implement a custom 404 page ?

**Comment by Rick-Anderson** [comment]
When we retire a URL, we should redirect rather than 404
For example, we retired http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html - so everyone pointing to that get's a 404. We have a replacement tutorial.

the asp.net site redirects when they retire.

**Comment by Rick-Anderson** [comment]
this is handled by DocFX team.
