### ISSUE TITLE
Can this be used with Razor Pages?

### ISSUE THREAD

**Issue by Coscotex** [aspnet/Docs#9126]
I see mentions of controllers and action methods in this article, but I would like to confirm if this can be used with razor pages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1#uploading-large-files-with-streaming)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Coscotex** [comment]
To clarify - I'm asking about the streaming large files technique

**Comment by guardrex** [comment]
Hello @Coscotex ... The topic has received a number of issues and will be addressed at some point in the future. We don't have an ETA for that work yet. You can browse the attached issues on the tracking issue for the work to see what other developers have said: #5331

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
