### ISSUE TITLE
Instructor cannot be updated

### ISSUE THREAD

**Issue by mariashahid** [aspnet/Docs#9138]
Hi,

While trying this tutorial, I am having problems when trying to update  Instructor entity via the Edit page. It always gives me validation error for Instructor.OfficeLocation.InstructorID column, saying that it can't be null. 
Please guide how the issue can be resolved

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by mariashahid** [comment]
I have tried downloading the samples available on GitHub. But unfortunately the projects for asp.net core update  2.0 won't  compile due to having references to asp.net core update 2.1 and the projects for core update 2.1 do not have instructor pages implementation. 

Please help resolve this issue.

**Comment by Rick-Anderson** [comment]
Update the project file to the following
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Utils" Version="2.1.5" />
  </ItemGroup>
</Project>
```

**Comment by Rick-Anderson** [comment]
I checked in the project update. The download code works on instructor edit.
