### ISSUE TITLE
AddTransient userstore and table?

### ISSUE THREAD

**Issue by gbjbaanb** [aspnet/Docs#9139]
Why AddTransient and not AddScoped? Does this mean that every call to the Dapper sample is created, a new connection made, and then destroyed, multiple times within each call to a controller?

Is there a reason why Transient was used here, or is it just being safe with implementations that might not be as re-entrant as they could be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b3ef64-9e17-3aab-0b75-57726d906cb6
* Version Independent ID: 8152896e-6969-d992-4877-6d6bbf4772a3
* Content: [Custom storage providers for ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-2.1#reconfigure-app-to-use-a-new-storage-provider)
* Content Source: [aspnetcore/security/authentication/identity-custom-storage-providers.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@blowdart

**Comment by blowdart** [comment]
Safety, because we don't know what database tech you're going to be using.

**Comment by gbjbaanb** [comment]
Fair enough, but it that something that could be mentioned - along with "If you want increased performance and  are using SQL Server replace with AddScoped" or similar wording

**Comment by Rick-Anderson** [comment]
[services.AddTransient](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-custom-storage-providers?view=aspnetcore-2.1#reconfigure-app-to-use-a-new-storage-provider)


If the database is SQL Server, `AddTransient` can be replaced with `AddScoped` for increased performance.

**Comment by Rick-Anderson** [comment]
Closed per #10192
