### ISSUE TITLE
ANCM: Detect client disconnects and logging

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9141]
https://blogs.msdn.microsoft.com/webdev/2018/10/17/asp-net-core-2-2-0-preview3-now-available/#aspnetcoremodule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module configuration reference](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@jkotalik Can you confirm that the location (`CONSOLE`, `FILE`, and `EVENTLOG`) is a flag set with the level (`ERROR`, `WARNING`, `INFO`, or `TRACE`) in the `debugLevel` handler setting?

For example ...

```xml
<handlerSetting name="debugLevel" value="FILE,TRACE" />
```

If so, we can get any processing rules for the flags squared away on the PR. I'll have it in shortly.

**Comment by guardrex** [comment]
>  The value is only a single value.

That's the part that's a little confusing. For example, I saw this note ...

```csharp
// If file or console is enabled but level is not set, enable levels up to info
```

https://github.com/aspnet/IISIntegration/blob/release/2.2/src/AspNetCoreModuleV2/CommonLib/debugutil.cpp#L113

I'll ping u on the PR and then we can see what's right/wrong with the draft.

**Comment by jkotalik** [comment]
Whoops meant to delete that part.
