### ISSUE TITLE
Field names are lost in web client when object use MessagePack annotations

### ISSUE THREAD

**Issue by harveytriana** [aspnet/Docs#9142]
When decores the class with MessagePack annotations, i.e., [MessagePackObject] and [Key(n)], the response in Web Client arrives without field names.

_Why do I have to use the annotations on the object? Because I need to transfer data to a Web Api, to then deliver the data by SignalR (I´m using WebAPIContrib.Core)_

e.g. 
```
public class Book
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public DateTime Date { get; set; }
    public double Price { get; set; }
}
```
After use annotations: [MessagePackObject] and [Key(n)] the object arrives from SignalR in another structure and without field names.
```
[MessagePackObject]
public class Book
{
    [Key(0)] public int Id { get; set; }
    [Key(1)] public string Title { get; set; }
    [Key(2)] public string Author { get; set; }
    [Key(3)] public DateTime Date { get; set; }
    [Key(4)] public double Price { get; set; }
}    
// the web client receives:
[
  469,
  "In His Own Write",
  "John Lennon",
  "2018-10-20T07:23:02.124Z",
  223.54
]
```
The complete sample here:
https://github.com/harveytriana/MessgePackServerData

Any suggestions to not have to rewrite how to handle response from the client side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e807e138-f84c-e63e-ab37-eec0d554d3bb
* Version Independent ID: 3ac41883-3bc2-30ba-a47f-462196850c12
* Content: [Use MessagePack Hub Protocol in SignalR for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/signalr/messagepackhubprotocol?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/messagepackhubprotocol.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/messagepackhubprotocol.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BrennanConroy** [comment]
https://github.com/neuecc/MessagePack-CSharp#object-serialization The messagepack library docs show examples of how to preserve property names. `Key(#)` just does position, whereas `Key("string")` will preserve the name.

**Comment by harveytriana** [comment]
The solution in one line, -elegant.
```
[MessagePackObject(keyAsPropertyName: true)]
public class Book
{
    public int Id { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public DateTime Date { get; set; }
    public double Price { get; set; }
}
```
Thanks a lot Brennan.
