### ISSUE TITLE
Relationship between Windows Auth And AspNetCore Identity

### ISSUE THREAD

**Issue by wadebee** [aspnet/Docs#9143]
Could you please discuss the relationship between the two? Is Identity an abstraction that lays over Windows Auth? When building Intranet apps that could eventually end up outside the intranet what Identity interfaces might be helpful to incorporate? Looking for best practice/architecture style guidance. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@blowdart

**Comment by blowdart** [comment]
There is no relationship. If you are using Windows Auth then AD is the source of truth. Identity doesn't enter into it. We don't recommend mixing the two if you're going for extranet scenarios, instead look at federation via Azure B2C, ADFS or Identity Server.

**Comment by code2expert** [comment]
I'm converting an asp.net core application with anonymous authentication to use windows authentication. It works fine but a bit crude because the login comes up uncontrolled and I cannot seem to be able to logout systematically. I want to be able to use the old forms and in that sense it's very much untidy at the moment. How do I go about this?
