### ISSUE TITLE
Alternative configuration frameworks

### ISSUE THREAD

**Issue by ceddlyburge** [aspnet/Docs#9146]
The Options pattern described here has some benefits and trade-offs, just like everything, and may not be the best fit for all cases.

Here are some other solutions for comparison
- [Config.net](https://github.com/aloneguid/config): lightweight, very simple and easy to use
- [RES.Configuration](https://hackernoon.com/taming-configuration-in-c-a2706b2d4741): medium weight, slightly more setup but more power (disclaimer - written by me)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ceddlyburge ... The engineers called upon us to focus this topic on the Options pattern that the framework provides. In the future, management or the engineers may decide to expand the coverage.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
