### ISSUE TITLE
Non-asp.net core support

### ISSUE THREAD

**Issue by TheDanishDynamo** [aspnet/Docs#9148]
Does this work with .net (classic/non-core)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 765e611b-a170-db1a-fa50-2771d79b2732
* Version Independent ID: ef34ebdf-977a-b797-e263-cb32c1643272
* Content: [Cloud authentication with Azure Active Directory B2C in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/azure-ad-b2c?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/azure-ad-b2c.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/azure-ad-b2c.md)
* Product: **aspnet-core**
* GitHub Login: @CamSoper

**Comment by guardrex** [comment]
Hello @TheDanishDynamo ... Some of the screens on the Azure portal side and some of the set up and underlying behaviors will be the same, but you'd be better off with a topic that pertains directly to a .NET Framework approach when it comes to the coding side of things. Did you see this one :point_right: https://docs.microsoft.com/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-dotnet-susi ... and the sample for that one is over here :point_right: https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi

**Comment by guardrex** [comment]
@CamSoper Is that a good one? ... and would u like me to cross-link that (or a different one) into the topic? We have some boilerplate lying around the repo that I can use (i.e., 'for a .NET Framework approach, see ...').

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
