### ISSUE TITLE
Just someone wanting a tiny part of the Docs.

### ISSUE THREAD

**Issue by 1944GPW** [aspnet/Docs#9157]
Would you be able to indicate the approximate sizes of downloads next to the links please.
I came here for the ASP.Net Core samples only to find Docs-master.zip is a half-gigabyte download.
Some of us are in places with more costly bandwidth than others. Docs-master.zip was corrupted after it came down so 
do I really want to waste another half gig on it again? All I want is the examples, as the referring page shows me. Surely that can't be much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c461e1d-5771-20f9-c9b3-ac4ee7661ee0
* Version Independent ID: e06d8e48-cee4-0c0c-39aa-97abe228c370
* Content: [ASP.NET Core tutorials](https://docs.microsoft.com/en-us/aspnet/core/tutorials/index?view=aspnetcore-2.1#how-to-download-a-sample)
* Content Source: [aspnetcore/tutorials/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for the feedback. We're working on this.

**Comment by Rick-Anderson** [comment]
@tdykstra 	@scottaddie 	how can we track github sample size complaints? Do we need a label?
