### ISSUE TITLE
Why does only Course.cs have [DatabaseGenerated(DatabaseGeneratedOption.None)]?

### ISSUE THREAD

**Issue by Zaknokimi** [aspnet/Docs#9166]
Why does Student.cs and Enrollment.cs not have this data annotation? I think the point for having this can either be clarified better or explained since Enrollment.cs has a primary key for EnrollmentID but it doesn't require this annotation.

**Comment by Rick-Anderson** [comment]
The article explains that in this case we want to select the PK, not the DB.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
