### ISSUE TITLE
Link for Data Protection API setup script is broken

### ISSUE THREAD

**Issue by kevbry** [aspnet/Docs#9172]
Under "Data Protection" -&gt; "Create Data Protection Registry Keys", there is a link to a powershell script. 
1. The link is currently broken. The aspnet/dataprotection repo is also deprecated.
2. Should probably link to the 2.1 script since this is the 2.1 doc, even if nothing has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1#data-protection)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for reporting this @kevbry ... I'll get right on it. 🏃
