### ISSUE TITLE
"Name" is always null, "IsComplete" is always false.

### ISSUE THREAD

**Issue by TRegan3** [aspnet/Docs#9176]
I followed this tutorial step-by-step up the test of the "Create" method.  When post the described json from Postman to the Create method the "Name" property of the TodoItem is always null, and "IsComplete" is always false.  Obviously I'm doing something wrong.  The sole difference with my setup is that I'm using https.  Is another step needed to use https?  I did turn off  SSL Cert Verification as you instructed in the Tip.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by TRegan3** [comment]
I found if I prepend the [FromBody] attribute to the Create method argument it works:

public IActionResult Create([FromBody]ToDoItem item)

Why do I need to add the [FromBody] attribute?

**Comment by scottaddie** [comment]
@TRegan3 Are you targeting .NET Core 2.1? `[FromBody]` is implied when targeting 2.1, which is why it's not shown in the tutorial's code snippet. If you're targeting .NET Core 2.1, please set the 2.1 compatibility flag in `Startup.ConfigureServices`:

```csharp
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

**Comment by TRegan3** [comment]
That's odd.  Yes, I'm targeting 2.1 and yes, I have that line in my Startup.ConfigureServices (I'm following the tutorial very strictly).  Yet and still I must use the [FromBody] Attribute for this to work.  Is there anything else I could be doing wrong?  I'm using Visual Studio 2017 version 15.8.7 and the latest version of Postman.  I'm running this on my local host, which launches a Chrome browser in IIS Express.

**Comment by TRegan3** [comment]
Sorry, I see now, I was missing the [ApiController] attribute on the Controller class.

**Comment by TRegan3** [comment]
Yes, and I should point out it was part of the tutorial that I copied and pasted, I must have inadvertently deleted that attribute when I was making changes.
