### ISSUE TITLE
Update sqlservercache command names

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Docs#919]
Former DNX commands, soon-to-be dotnet CLI tools:

`user-secret` -> `user-secrets`
`sqlservercache` -> `sql-cache`

After https://github.com/aspnet/UserSecrets/pull/58 and https://github.com/aspnet/Caching/pull/145 are merged.

**Comment by cesarbs** [comment]
cc @victorhurdugaci @Eilon @muratg

**Comment by muratg** [comment]
@danroth27

**Comment by danroth27** [comment]
The DNX Commands doc will go away with the move to the .NET CLI, but we should cleanup our other docs that mention these commands.

**Comment by danroth27** [comment]
Some docs that still need this fixed:
- https://docs.asp.net/en/latest/security/authentication/accconfirm.html
- https://docs.asp.net/en/latest/security/authentication/2fa.html

**Comment by danroth27** [comment]
Looks like we don't have docs for the sql-cache tool yet. Added #1412 to track.

**Comment by cesarbs** [comment]
@Rick-Anderson This was related to #1412, closing it too.
