### ISSUE TITLE
Https error.

### ISSUE THREAD

**Issue by sirgallifrey** [aspnet/Docs#9195]
When I try the first set o commands:

dotnet new webapp -o RazorPagesMovie
cd RazorPagesMovie
dotnet run

I get and error about https:

Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/home/adilson/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at RazorPagesMovie.Program.Main(String[] args) in /home/adilson/projects/RazorPagesMovie/Program.cs:line 17

I tried to run 'dotnet tool install --global dotnet-dev-certs' and then 'dotnet dev-certs https' with no success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cafe31d3-11f1-d679-1937-915690ac7360
* Version Independent ID: e6b12009-be25-33e0-c5a8-8a1bd686b387
* Content: [Get started with ASP.NET Core Razor Pages in Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/razor-pages-start?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sirgallifrey ... Did you try re-installing the SDK? You should get the dev cert via the SDK installer.

**Comment by sirgallifrey** [comment]
I had tried 
```
dotnet tool install --global dotnet-dev-certs
dotnet dev-certs https
```
Unfortunately I didn't saw that `dev-certs https` had produced an error asking me for libhostfxr.so:


> A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/adilson/.dotnet/tools/.store/dotnet-dev-certs/2.1.1/dotnet-dev-certs/2.1.1/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.

My problem was that DOTNET_ROOT was not set... after setting it with `export DOTNET_ROOT=/opt/dotnet/` I could generate the cert and run the project.

I'm ready to close this issue since my problem is solved, but I think the tutorial could mention the cert generation, or have a side note about it.

Thanks for the help! :)

**Comment by guardrex** [comment]
@shirhatti Can you help us triage this?

**Comment by shirhatti** [comment]
@sirgallifrey What OS are you on? How did you acquire the shared runtime?

**Comment by sirgallifrey** [comment]
@shirhatti I use Archlinux and I installed the runtime from the official Arch package repository.

Dotnet packages installed: `dotnet-host` `dotnet-runtime` `dotnet-sdk`

https://www.archlinux.org/packages/?sort=&q=dotnet&maintainer=&flagged=

**Comment by sirgallifrey** [comment]
I'll see to file a bug report on the Arch package asking them if it's possible to move the installation to the default location.

**Comment by shirhatti** [comment]
@leecow Who owns the arch package?

**Comment by sirgallifrey** [comment]
They have **Maxime Gauduin** listed as maintainer

**Comment by shirhatti** [comment]
As far as I can tell, Arch is not officially supported by the .NET team and wholly community maintained.

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x#supported-linux-versions

**Comment by Wayne-King** [comment]
On Windows, the cert gets installed by the SDK but it still needs to be explicitly trusted.  The "Get started" article at [https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows#enable-local-https](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows#enable-local-https)
has a section named "Enable local HTTPS" that includes the necessary command line for both Windows and macOS.

That section probably needs to be copied into the tutorial/article associated with this bug.

The necessary command line is:
`dotnet dev-certs https --trust`

**Comment by Rick-Anderson** [comment]
@Wayne-King 	 does that work on Arch? If so, the error message could be better

`To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.`

**Comment by sirgallifrey** [comment]
The DOTNET_ROOT issue was fixed in Arch  and is already available: https://bugs.archlinux.org/task/59263

@Wayne-King that section is great, it could have more info on linux but I can open another issue for that and probably make the PR.

As for the article of this issue I don't think we need to copy the "Enable local HTTPS" section, a link in the Prerequisites would suffice for me. ( https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/razor-pages-start?view=aspnetcore-2.1#prerequisites )

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
