### ISSUE TITLE
"Enable QR Code generation for TOTP authenticator apps in ASP.NET Core" page blank.

### ISSUE THREAD

**Issue by JohnnyWestlake** [aspnet/Docs#9197]
As it says, there's nothing here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-1.1)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by sadjadbp** [comment]
@JohnnyWestlake still see nothing in the page

**Comment by sadjadbp** [comment]
#12436
