### ISSUE TITLE
Preventing Open Redirect Attacks

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#92]
ASP.NET Core -> Security -> Preventing Open Redirect Attacks

- What is an Open Redirect Attack?
  - Describe the problem
  - Show an example attack
- Protecting Against Open Redirect Attacks
  - Using Url.IsLocalUrl to protect redirection done by the server

Current default templates use this helper in `AccountController`:
```
        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        }
```

[Edit Tom Dykstra] [commit with deleted article stub](https://github.com/aspnet/Docs/commit/e4940fb39e40b4af7973e0709c004c6a6cc62f21)

**Comment by danroth27** [comment]
@blowdart I don't think there is really anything specific to ASP.NET Core to document for open redirect attacks. Let me know if you disagree.

**Comment by blowdart** [comment]
No, but it should be mentioned anyway. After all CSRF isn't specific to ASP.NET, but we still cover that, and we have some pieces to help mitigate with IsLocal on the URI class.

**Comment by ardalis** [comment]
@blowdart are you the best person for me to have a quick conversation with about what this should cover? Does this look like a good starting point? https://weblogs.asp.net/jongalloway/preventing-open-redirection-attacks-in-asp-net-mvc

**Comment by blowdart** [comment]
It's very different now, so I'd leave it till I get back from vacation.

**Comment by ardalis** [comment]
I'm out myself 10-17 March. Maybe we can aim for week of 20th.

**Comment by danroth27** [comment]
@ardalis I chatted with @blowdart about this and the only difference is that we now have a built-in framework API  ([`UrlHelper.IsLocalUri()`](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.routing.urlhelper#Microsoft_AspNetCore_Mvc_Routing_UrlHelper_IsLocalUrl_System_String_)) for checking that the redirect URI is local. In earlier incarnations of MVC the code for checking for local URIs was in the templates, and this code has been removed. Other than that the basic ideas are the same: if you accept a redirect URI as a parameter from the request that you expect to go to somewhere in your app then you need to check that it is a local first. That's basically it. This article should be short and sweet.
