### ISSUE TITLE
MVC6 does not load controllers/routes from external assembly/dll referred.

### ISSUE THREAD

**Issue by jalalions** [aspnet/Docs#920]
I am developing mvc6 application, some of my controllers are defined in separate ClassLibary/DLL project. When i refer that dll into my MVC6 project none of the controller/routes gets resisted to routes collection. As per documentation it suppose to scan all DLLs in appdomain to get attribute routes.

**Comment by danroth27** [comment]
> As per documentation it suppose to scan all DLLs in appdomain to get attribute routes.

Could you please point us to the exact location you are seeing this in the docs?

**Comment by danroth27** [comment]
Closing for now. Please reopen with the additional details requested.
