### ISSUE TITLE
Old Docs link is wrong

### ISSUE THREAD

**Issue by JranZu** [aspnet/Docs#9200]
The old documentation here: https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr
links to the wrong page (it goes to getting started, instead of this page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26c63dd-9fdc-7d8d-aec4-4343807ee312
* Version Independent ID: 1986d76e-63e7-8a2d-c8a4-9c132d2b0ee1
* Content: [Introduction to ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/introduction.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/introduction.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks @JranZu ... I'll re-point that link.
