### ISSUE TITLE
Windows Authentication on Nano Server

### ISSUE THREAD

**Issue by biiiipy** [aspnet/Docs#9212]
It should be mentioned in the docs that Windows Authentication won't work on Nano Server, only Server Core (which is a quite sad). Link - https://github.com/aspnet/aspnet-docker/issues/398

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401ad9a0-9e51-80a2-5846-82e9790d7257
* Version Independent ID: fbc36c26-9992-1f4c-66d3-02f898ee7ec4
* Content: [Configure Windows Authentication in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-2.1#)
* Content Source: [aspnetcore/security/authentication/windowsauth.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/windowsauth.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for the heads-up @biiiipy.
