### ISSUE TITLE
Doc  2.1 API ConfigureOptions 

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9232]
demonstrate a new in 2.1 API ConfigureOptions here as well maybe:

`services.ConfigureOptions<UseSomethingFromDI>` instead of `services.AddTransient<IConfigureOptions<YourOptions>, UseSomethingFromDI>();`, this uses reflection to basically do the same thing and also lets UseSomethingFromDI configure multiple option types if desired.

See #5922

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@HaoK 	can you point to sample code for `services.ConfigureOptions<UseSomethingFromDI>`

**Comment by HaoK** [comment]
Yeah its in the tests for options builder:

https://github.com/aspnet/Options/blob/master/test/Microsoft.Extensions.Options.Test/OptionsBuilderTest.cs

```C#
        [Fact]
        public void ConfigureOptionsWithSingletonDepWillUpdate()
        {
            var someService = new SomeService("Something");
            var services = new ServiceCollection().AddOptions().AddSingleton(someService);
            services.AddOptions<FakeOptions>().Configure<SomeService>((o, s) => o.Message = s.Stuff);
            services.AddOptions<FakeOptions>("named").Configure<SomeService>((o, s) => o.Message = "named " + s.Stuff);

            var sp = services.BuildServiceProvider();
            var factory = sp.GetRequiredService<IOptionsFactory<FakeOptions>>();

            Assert.Equal("named Something", factory.Create("named").Message);
            Assert.Equal("Something", factory.Create(Options.DefaultName).Message);

            someService.Stuff = "Else";

            Assert.Equal("named Else", factory.Create("named").Message);
            Assert.Equal("Else", factory.Create(Options.DefaultName).Message);
        }
```
