### ISSUE TITLE
Doc IOptionsBuilder  for 2.1

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9233]
Doc new `IOptionsBuilder` and related overloads, see https://github.com/aspnet/Security/issues/1718#issuecomment-380204790 its related to this general idea of being able to more easily configure options with things from DI

See #5922

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed39cb0e-aa85-8bba-ffb4-859b56a60723
* Version Independent ID: dc7e3449-650b-d117-5eac-69e5ccb250cb
* Content: [Options pattern in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/configuration/options.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/options.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Dup of https://github.com/aspnet/Docs/issues/5924.
