### ISSUE TITLE
@addTagHelper works with assembly name, not the namespace

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9236]
@addTagHelper works with assembly name, not the namespace
customer comment:
Hi, thanks a lot for detailed tutorial! May I just ask you to highlight somehow that @addTagHelper works with assembly name, not the namespace? It is really easy to miss. Just spent a few hours trying to understand why my helper is not working until found the answer on SO. |#6049
Moved from 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Silic0nS0ldier** [comment]
Hit this exact issue almost a year ago. Couldn't figure out the cause at the time. Adding a prominent note about the restriction towards the beginning would be a great addition.
