### ISSUE TITLE
The commands in the docs does not work

### ISSUE THREAD

**Issue by CeciAc** [aspnet/Docs#9251]
@JinGangRed commented on [Wed Oct 17 2018](https://github.com/aspnet/Docs.zh-cn/issues/78)

When I use the command

>  dotnet new webapp -o aspcoreapp

I get the error: `There is no template matching input template name: webapp`.

I changed the command following the suggest template like this:

>  dotnet new web -o aspcore app

It works.

And the other command:

> dotnet dev-certs https --trust

I get the error:` No executable file matching the command "dotnet-dev-certs" was found`.

And the version of the dotnet like this:
![image](https://user-images.githubusercontent.com/26211024/47073714-78634b00-d22b-11e8-92b3-4e7c8019ce6d.png)

---

@imba-tjd commented on [Wed Oct 17 2018](https://github.com/aspnet/Docs.zh-cn/issues/78#issuecomment-430548757)

给个链接啊，你这要别人怎么找

---

@LisandroSu commented on [Wed Oct 17 2018](https://github.com/aspnet/Docs.zh-cn/issues/78#issuecomment-430730401)

Hello, @JinGangRed 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

---

@CeciAc commented on [Mon Oct 22 2018](https://github.com/aspnet/Docs.zh-cn/issues/78#issuecomment-431917913)

Hello, @JinGangRed,
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

---

@JinGangRed commented on [Wed Oct 24 2018](https://github.com/aspnet/Docs.zh-cn/issues/78#issuecomment-432671402)

The link is: https://docs.microsoft.com/zh-cn/aspnet/core/getting-started/?view=aspnetcore-2.1&tabs=windows

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this one here because the user is reporting issues with the given example.

**Comment by scottaddie** [comment]
@JinGangRed You'll need to use at least version 2.1.300 of the .NET Core SDK. That SDK can be downloaded [here](https://www.microsoft.com/net/download). The version you're using is from the .NET Core 2.0 release. In the 2.0 release, the ASP.NET Core Razor Pages project template you're trying to use has the alias `razor`.
