### ISSUE TITLE
RouteDataRequestCultureProvider sample: localization and routing

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9252]
Search [ASP.NET Core Localization Deep Dive](https://joonasw.net/view/aspnet-core-localization-deep-dive) for `RouteDataRequestCultureProvider`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
We already have a good unit tests that shows a use case for localization & routing [here](https://github.com/aspnet/Localization/blob/master/test/Microsoft.AspNetCore.Localization.Routing.Tests/RouteDataRequestCultureProviderTest.cs)

FYI @Rick-Anderson,  @andrewlock and I wrote a blog post about the same topic:
[Url culture provider using middleware as filters in ASP.NET Core 1.1.0](https://andrewlock.net/url-culture-provider-using-middleware-as-mvc-filter-in-asp-net-core-1-1-0/)

[Localization & Routing in ASP.NET Core 1.0](http://www.hishambinateya.com/localization-and-routing-in-asp.net-core-1.0)
