### ISSUE TITLE
Problem with Instructor scaffolding

### ISSUE THREAD

**Issue by LouBH** [aspnet/Docs#9258]
I scaffolded Instructor and tried to run the app, now am getting error message "Instructor" is a namespace but is used like a type.  I am upgrading my skills from VS 2008, so am overwhelmed with new learning.  No idea how to proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by LouBH** [comment]
Re-read the instructions.  I had created a folder called "Instructor" under Pages when it should have been "Instructors".  I wish I understood what I am doing.  Ha ha  I have written SQL for years and can make it jump through hoops.  Linq is leaving me in the dust, trampled and bleeding.

**Comment by LouBH** [comment]
My last post was unclear.  My problem was solved by deleting the "Instructor" pages and scaffolding "Instructors"

**Comment by Rick-Anderson** [comment]
Glad you fixed it. Thanks for reporting back.
