### ISSUE TITLE
Provide outline of how to configure Kestrel for remote connections.

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#926]
We need to add this to our docs - preferably https://docs.asp.net/en/latest/fundamentals/servers.html#kestrel

Customer asks https://docs.asp.net/en/latest/tutorials/your-first-mac-aspnet.html#comment-2475570406

I have this running on a Raspberry Pi (nice) without any major problems: good tutorial! Now if I want to browse from another computer to the Pi (http://ip-address-of-pi:5000) I get a "Connection Refused". How can I make Kestrel allow for remote connections?

@halter73 - can you outline the steps?

**Comment by halter73** [comment]
@Rick-Anderson I responded to the customer comment. Basically, every reference to "localhost" in configuration should be changed to "*" to accept external requests.

I think this has always been the case for WebListener (@Tratcher would know for sure), but it was a somewhat recent change for Kestrel which used to always accept external requests no matter how it was configured.

**Comment by Tratcher** [comment]
localhost can also be replaced by specific IPs, but * is easier and more portable.

**Comment by danroth27** [comment]
We should add this to the Kestrel docs.

**Comment by Tratcher** [comment]
Can we import this doc for WebListener?
http://katanaproject.codeplex.com/wikipage?title=Selfhosting&referringTitle=Documentation

**Comment by danroth27** [comment]
Yeah, we can take a look.

**Comment by spboyer** [comment]
@danroth27 @Rick-Anderson 
we have the following note in the article
>builder.UseUrls("http://localhost") configures Kestrel and WebListener to only listen to local requests. Replace “localhost” with “*” to also listen to external requests.

This issue is covered, we should close this.

**Comment by ColbyBurke** [comment]
What if we tried both localhost and '*' but both were refused?

**Comment by StevenTCramer** [comment]
0.0.0.0 didn't work either... I had to use explicit.
