### ISSUE TITLE
Placement?

### ISSUE THREAD

**Issue by daveabrock** [aspnet/Docs#9267]
So, this content is awesome! But, does it belong in the VS Code tutorial? This is core RP concept material and wondering if it should be linked outside of this tutorial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640a5140-6a41-85ec-6099-0d2fd3dbd61c
* Version Independent ID: 1b989b3f-4f6f-824c-1c37-ef949d7f35a6
* Content: [Scaffolded Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-vsc/page?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-vsc/page.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-vsc/page.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's just a stage in the series. I'm going to unify the 3 version (VS, VSC, macOS).
