### ISSUE TITLE
Best practices multiple handler who process different models

### ISSUE THREAD

**Issue by FerronN** [aspnet/Docs#9271]
I have a Page with multiple forms. Each form has it own Page handler and model. I can't find the best practices for this kind of scenario within the current documentation. 

I ask this question, because when you call Modelstate.Validate() in this scenario it always fails because of the multiple models.
I've to use  ModelState.Clear(); and then TryValidateModel(InputProfile) to validate the model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=visual-studio#multiple-handlers-per-page)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@FerronN ... good point ... we don't have coverage for this scenario (*yet*).

We don't have `TryValidateModel(Object, String)` that takes the prefix, either.

Possibly, the section on manual validation at https://docs.microsoft.com/aspnet/core/mvc/models/validation#manual-validation could be expanded, including this scenario.

I seen some devs around the Net performing manual validation (checking each property manually and not calling `ModelState.Valid`) in each handler for this scenario.

@rynowak 

1. What approach should we describe?
1. Does using the prefix-version of `TryValidateModel` help in this scenario?
1. When is clearing the `ModelState` each time required (either way; using the prefix version of `TryValidateModel` or not)?

**Comment by robertburgh** [comment]
Is it possible to use the asp tag helpers (asp-page-handler for example) and also call a javascript function?
Possible uses would be to use functions to modify classes or use toastr.

**Comment by robertburgh** [comment]
unintended location of previous comment

**Comment by Rick-Anderson** [comment]
@rynowak please respond.

**Comment by Rick-Anderson** [comment]
@dougbu 	please respond.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by jeremysalwen** [comment]
Can I just ask a clarifying question?  For the example: 

```
public class MyPageModel : PageModel
{
    public IActionResult OnPost1Async([Required] SubModel1 model) {}
    public IActionResult OnPost2Async([Required] SubModel2 model) {}
}
```

How are we supposed to do model validation?  `asp-validation-for` spans no longer work.  Is seems like either way you are forced to do completely custom validation?  

This stackoverflow answer seems relevant and suggests hacks are necessary? https://stackoverflow.com/a/59924044/94102
