### ISSUE TITLE
Link to sample code broken

### ISSUE THREAD

**Issue by bobrundle** [aspnet/Docs#9275]
Link to sample code given in 

https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1

is

https://github.com/aspnet/Docs/tree/master/aspnetcore/performance/caching/distributed/sample

Should be 

https://github.com/aspnet/Docs/tree/master/aspnetcore/performance/caching/distributed/samples/2.x/DistCacheSample

**Comment by daveabrock** [comment]
Thanks, @bobrundle! I was able to fix the link in an upcoming PR, so the changes should go live in the next day or two.
