### ISSUE TITLE
@addTagHelper supports wildcard directed at specific namespace

### ISSUE THREAD

**Issue by Silic0nS0ldier** [aspnet/Docs#9279]
The wildcard can be extended like `@addTagHelper AuthoringTagHelpers.TagHelpers.*, AuthoringTagHelpers` however this is about as complex as things get. Something like `AuthoringTagHelpers.TagHelpers.*TagHelper` won't resolve anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ecfbee-8b84-9ef2-65b6-8c2542f6370f
* Version Independent ID: 9a0cbaa2-65c9-1618-1003-5fd2e7f6192f
* Content: [Author Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/authoring?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/tag-helpers/authoring.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/authoring.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
That's correct.

**Comment by curelom** [comment]
After much trouble getting custom taghelpers to work, I found that they cannot be in the same assembly as the web project itself.  Once I created a library and put them in that, everything worked great.

**Comment by Rick-Anderson** [comment]
@curelom 	wrote:
> I found that they cannot be in the same assembly as the web project itself. 

That's not true. The sample has them in the same project.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
