### ISSUE TITLE
HttpContext always null in view from class library

### ISSUE THREAD

**Issue by k3davis** [aspnet/Docs#9294]
I'm able to follow these instructions to embed a simple razor view in a class library and consume it from another app, but when I attempt to do any logic in the underlying class of the page (IndexModel : PageModel), HttpContext is available but null. I can inject HttpContext using IHttpContextAccessor (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.1) and that works, but it doesn't sound from this documentation that this should be necessary. Does it sound like I'm doing something wrong or am I misunderstanding the docs on this point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@k3davis 	what implies `HttpContext` would be initialized?

**Comment by k3davis** [comment]
@Rick-Anderson Fair question; perhaps I'm conflating this doc with the one linked to in my post.

```
public class AboutModel : PageModel
{
    public string Message { get; set; }

    public void OnGet()
    {
        Message = HttpContext.Request.PathBase;
    }
}
```

This certainly looks like code that presumably works in a Razor page but apparently not in a Razor UI class library without using injected `IHttpContextAccessor` in that case, though they both inherit from the same parent class and seem to interchange functionality in other ways.
