### ISSUE TITLE
Content Feedback link results in 404 error

### ISSUE THREAD

**Issue by ackava** [aspnet/Docs#9299]
Reproduce steps,

1. Goto 
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-2.1
2. Click on Content Feedback, click on down arrow and click on "directly on github", results 404 error https://docs.microsoft.com/en-us/aspnet/core/security/authorization/%7B0%7D

**Comment by guardrex** [comment]
It works here ...

<img width="401" alt="capture" src="https://user-images.githubusercontent.com/1622880/47686070-5496f200-dba7-11e8-9d85-3207d9b918d0.PNG">
