### ISSUE TITLE
dotnet dev-certs not found on linux

### ISSUE THREAD

**Issue by heapifyman** [aspnet/Docs#9326]
# Issue description

```
$ dotnet --version
2.1.403

$ dotnet dev-certs
Cannot find command 'dotnet dev-certs', please run the following command to install

dotnet tool install --global dotnet-dev-certs

$ dotnet tool install --global dotnet-dev-certs
Tool 'dotnet-dev-certs' is already installed.

$ dotnet dev-certs
Cannot find command 'dotnet dev-certs', please run the following command to install

dotnet tool install --global dotnet-dev-certs
```

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core 2.1.403
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     antergos
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.403 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.5 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download</strong></summary>

```console
<replace>
```
</details>

**Comment by heapifyman** [comment]
Sorry, pebkac

**Comment by mic3ael** [comment]
I have the same issue, how did you fix that? thanks

**Comment by mic3ael** [comment]
I have just fixed it, uninstall dotnet-dev-certs and install it again fixed the issue.

**Comment by esbgo97** [comment]
Hi, sorry for my English, I found this solution that works for me:

1. uninstall dotnet-dev-certs
   $: dotnet tool uninstall --global dotnet-dev-certs
2. reinstall
    $: dotnet tool install --global dotnet-dev-certs
3. add path, replace [user] for your user:
    $: export PATH="$PATH:/home/[user]/.dotnet/tools"
4. execute again:
    $: dotnet dev-certs https --trust

if want to keep this after reboot need add path on ~/.bash_profile
