### ISSUE TITLE
What libraries are you using?

### ISSUE THREAD

**Issue by lexugax** [aspnet/Docs#9327]
It would be great to see what "usings" you are using together with your code. When copy/pasting some of your code, and after adding the "usings" offered by intellisense, I get errors about methods not being passed the correct parameters, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @lexugax ... This topic is due for an overhaul on #5331. I'll add this issue to the list there.

**Comment by Rick-Anderson** [comment]
For advanced tutorials, we typically don't list all `using` statements. Intellisense does a really good job of helping you. Worst case, check the source.
