### ISSUE TITLE
[SignalR] [Java] Document minimum Android API levels

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#9335]
We should add the following notes to our Java Client documentation regarding compatibility: 

* The SignalR Java Client will run on Android **API Level 16 and above**.
* Connecting through the Azure SignalR Service will require Android **API Level 21 and above** because the Azure SignalR Service requires **TLS 1.2** and does not support **SHA-1**-based cipher suites. [Android added support for SHA-256 (and above) cipher suites in API Level 20](https://developer.android.com/reference/javax/net/ssl/SSLSocket).

**Comment by bradygaster** [comment]
created pr: https://github.com/aspnet/Docs/pull/9342

**Comment by Rick-Anderson** [comment]
@bradygaster 	no need to explicitly call out PR in the issue, it's added automagically when you refer in the PR.

**Comment by bradygaster** [comment]
Closing this issue as we have a PR open for it now in the Java client doc.

**Comment by deepaksharma1992** [comment]
Hi, we were thinking of using SignalR with our android client application. But requirement is to use TLS1.2. Will it be possible to use it on android devices below API 20. Thanks.

**Comment by anurse** [comment]
It's my understanding that no, if you require TLS1.2 you must use Android API Level 20 or above. That's a general Android restriction, not specific to SignalR.

**Comment by deepaksharma1992** [comment]
Hi, yes but we have to enable it on devices below 20, but i am not sure if it is available for the android sigalR  library

**Comment by anurse** [comment]
We don't test TLS 1.2 on Android applications below level 20. It may be possible to enable it, but we don't officially support it at this time.

**Comment by deepaksharma1992** [comment]
Thanks, for your response.

**Comment by deepaksharma1992** [comment]
I am not sure, about I was looking into the code and it is internally using OkHttp. If we could enable the TLSSocketFactory in the client builder. Maybe it will start supporting TLS1.2 on devices below API 20. Will update you as soon as found something.
