### ISSUE TITLE
Consistency for Mac users

### ISSUE THREAD

**Issue by edorsett** [aspnet/Docs#9343]
The 'Adding a new field' link as the next step from Add Search step of the RP w VS Mac tutorial actually jumps to the RP w VS tutorial. There, ef execution is using powershell vs dotnet CLI which is inconsistent. It would have been useful to have that new field step of the tutorial written for dotnet CLI using SQLite on Mac. When replacing the powershell commands on that page with corresponding dotnet ef cli commands, ef migrations are failing with SQLite. Error: SQLite does not support this migration operation ('AlterColumnOperation'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a6e95b3-068c-c582-27a4-7e94fb561929
* Version Independent ID: 72d5fa86-8c64-5d49-cee3-cd683e8bb0d0
* Content: [Add search to an ASP.NET Core Razor Pages app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Fixed in unification version
