### ISSUE TITLE
how to use two cookies in 2.1

### ISSUE THREAD

**Issue by benzhi2011** [aspnet/Docs#9352]
https://stackoverflow.com/questions/53067129/net-core-2-1-claim-based-authentication
I have posted my question on Stackoverflow, can anyone please take a look?
I have dotnet core 1.1 version code works for authentication. I have two cookies, one for user and one for admin so admin can impersonate as the user to login in the system. I need to convert it to 2.1 and I check User.Claims, in 1.1 User.Claims will show 2 signined claims, but 2.1 only shows one. It seems the one comes afterwards override the previous (services.AddAuthentication) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The SO thread says you found your answer. Is that correct?

**Comment by benzhi2011** [comment]
By using the middleware, I can achieve the same as I did for dotnet core 1.1. But I would like to find alternatives, because the middleware is called on every request. Is it necessary? I have tried to updated the user claims in the HttpContext after the SignInAsync. But it doesn't work.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
