### ISSUE TITLE
Policy handler

### ISSUE THREAD

**Issue by mjharper84** [aspnet/Docs#9356]
Helpful, thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @mjharper84!
