### ISSUE TITLE
Please add info about adding a second version

### ISSUE THREAD

**Issue by vankampenp** [aspnet/Docs#9360]
Thanks for this documentation. I would like to have  document for V1 and another for V2. I do get that by duplicating the lines where you specify V1, but then I get two documents, one titled V1, the other V2, but the contents is the same. 
So can you add some word around that as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by vankampenp** [comment]
I would like to use route based versioning, so /api/v2/dothis and /api/v1/dothis

**Comment by Rick-Anderson** [comment]
@vankampenp 	thanks for the suggestion. We'll consider this in the next doc update.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
