### ISSUE TITLE
 Add websocket origin feature to docs

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Docs#9363]
See the change here: https://github.com/aspnet/AspNetCore/commit/768d2a023e32c8530a4cda6a5a3c41fc5136b9a4

example usage:
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddWebSockets(options =>
    {
        options.AllowedOrigins.Add("http://myapp.com");
    });
}
```

This is a first class feature for [websocket origin restriction](https://docs.microsoft.com/aspnet/core/signalr/security?view=aspnetcore-2.1#websocket-origin-restriction) that we added in 2.2.

**Comment by Rick-Anderson** [comment]
BTW we have a https://github.com/aspnet/Docs/tree/release/2.2.0 branch
cc @anurse

**Comment by anurse** [comment]
Note: This should be added to the [WebSockets doc](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.1) **and** linked to from the [SignalR security](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1) doc (replacing the "WebSocket Origin Restriction" section in 2.2 and later)
