### ISSUE TITLE
id vs ID?

### ISSUE THREAD

**Issue by Peter554** [aspnet/Docs#9371]
Can you please clarify why the route parameter id matches with the controller action parameter ID? Is this case insensitive in general? Otherwise a great tutorial so far :+1:

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Add a controller to an ASP.NET Core MVC app](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Yes, it's case insensitive.
