### ISSUE TITLE
Need for the scaffold process is not explained.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [aspnet/Docs#9372]
The 'Scaffold Register, Login, and LogOut' section is as very confusing. It says to follow the instructions in 'Scaffold identity into a Razor project with authorization' and that then 'When a user clicks the Register link, the RegisterModel.OnPostAsync action is invoked'.

But the 'Register', Login and Log Out buttons are already wired up and functional even _before_  following the scaffold process. Which begs two obvious but unanswered questions.
1) What is providing the implementation of the existing /Identity/Account/Register endpoint that the Register button loads.
2) What is the nature of that existing implementation and why do we need to scaffold a replacement implementation. Is the existing implementation broken or deficient in some way, in which case why provide it in the first place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You only need to scaffold them to view the code.

**Comment by Rick-Anderson** [comment]
Per the first sentence

ASP.NET Core 2.1 and later provides ASP.NET Core Identity as a Razor Class Library. Applications that include Identity can apply the scaffolder to selectively add the source code contained in the Identity Razor Class Library (RCL).
