### ISSUE TITLE
ASP.NET Core API Migration 2.0 to 2.1

### ISSUE THREAD

**Issue by dfoulk** [aspnet/Docs#9376]
**Help us make content visible**

- I found [Migrate from ASP.NET Core 2.0 to 2.1
](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1) via Google
- That documentation walks users through migrating from 2.0 to 2.1, but some of the content appears to be irrelevant to API applications (and some content may be missing for API applications). For example: [Changes to Startup](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-startup) shows the addition of `app.UseCookiePolicy()`, which is not present in a fresh 2.1 API template in Visual Studio.

**Describe the new topic**

- It seems like there is enough similarity between the two application types to justify including the ASP.NET Core API migration instructions on the same page as the web app's guide. Maybe some "Notes" or alternative instructions would be best for providing API-specific instructions for the sections in the existing guide.
- Docs > ASP.NET Core 2.1 > Migration > 2.0 to 2.1 (> API)
- If created as a new topic: this topic would serve as a migration guide (ASP.NET Core 2.0 to 2.1) for API applications. It would read similarly to the existing [Migrate from ASP.NET Core 2.0 to 2.1
](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1) migration guide, but would be written for API applications specifically- avoiding confusion when the user reads a section of the guide such as [this one](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1#changes-to-authentication-code) (which does not appear to be relevant to API apps).
- The outline would be similar to that of the previously mentioned (existing) migration guide, just omitting and adding topics specific to API applications (sorry guys, I don't know how to properly migrate an API application short of what I learned from the existing migration guide).

My reasoning for this suggestion is that even though I used the migration guide provided, I ultimately ended up having to create a new ASP.NET Core 2.1 API application and compare its contents to the API that I was migrating. This was (I believe) because there were no "notes" explaining different actions that may (or may not) have been necessary for an API application.

Thanks for your time,
-Derek

**Comment by Rick-Anderson** [comment]
Moved to #9519
