### ISSUE TITLE
It is unclear what's the 3rd option is

### ISSUE THREAD

**Issue by vytasg** [aspnet/Docs#9379]
Quote from the top:
ASP.NET Core ships three server implementations:
    1. Kestrel is the default, cross-platform HTTP server for ASP.NET Core.
    2. HTTP.sys is a Windows-only HTTP server based on the HTTP.sys kernel driver and HTTP Server API. (HTTP.sys is called WebListener in ASP.NET Core 1.x.)
3. ?!?!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f53b58-a048-69ca-2e89-3625bb4cc839
* Version Independent ID: 32a343a1-ba87-7274-e861-2ac194d5aa3d
* Content: [Web server implementations in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/servers/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
@vytasg There aren't 3 options until ASP.NET Core 2.2, in which case IISHttpServer is the third.

@guardrex Please change the introductory text into something more generic, such as "ASP.NET Core ships with the following server implementations:".

**Comment by guardrex** [comment]
Yes, thanks @vytasg. The 3rd line is for `IISHttpServer` ... and that only shows up on the 2.2 versioned content. I'll patch this by moving the lead-in line inside the versioning tags.

**Comment by guardrex** [comment]
Sure ... that makes sense. I'll do that.
