### ISSUE TITLE
Fix node name for Swashbuckle article in TOC

### ISSUE THREAD

**Issue by Akelitz** [aspnet/Docs#9381]
This page should be "Swagger / OpenAPI &gt; Get started with Swashbuckle" in the menu on the left while it is "Swagger / OpenAPI &gt; Overview"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml#feedback)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by tdykstra** [comment]
@Akelitz Thanks for reporting that - I'm fixing it.
