### ISSUE TITLE
Steps for creatin are incomplete

### ISSUE THREAD

**Issue by RowlandShaw** [aspnet/Docs#9384]
The Individual User Accounts options requires a domain name, application id and sign up/in policy, but there's no guidance as to what to put for these

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@RowlandShaw 	where do you see that?

**Comment by RowlandShaw** [comment]
About here:
![image](https://user-images.githubusercontent.com/1315229/47957219-bee5d300-dfa9-11e8-854f-31df64293b96.png)

**Comment by Rick-Anderson** [comment]
@RowlandShaw 	the instructions are for the default user accounts in-app

![image](https://user-images.githubusercontent.com/3605364/47959794-0dd33e80-df91-11e8-91a7-d9dc8a381428.png)

**Comment by Rick-Anderson** [comment]
Somethings wrong with your Visual Studio. Try help/check for updates. If that doesn't fix it, try reinstall/repair the install.

**Comment by Rick-Anderson** [comment]
@RowlandShaw 	I've never seen that behavior and we have multiple thousands of customers reporting success.

**Comment by RowlandShaw** [comment]
Either way, the documentation should say what to put in there, as it is the destination for the "Learn more" link

**Comment by Rick-Anderson** [comment]
@CamSoper 	can you suggest the correct link for Cloud and WOrk + School?

**Comment by boppbo** [comment]
@RowlandShaw Make sure you don't target Web Application and not API in the dialog

**Comment by Rick-Anderson** [comment]
@boppbo Thanks for pointing that out. I can see that was the problem.
