### ISSUE TITLE
VcardInputFormatter.cs code sample is not displayed on docs page (reopens #6849)

### ISSUE THREAD

**Issue by dotnetchris** [aspnet/Docs#9394]
#6849 was not addressed. In other GitHub issues i was informed closed issues are not tracked.

The code file is in https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters/sample/Formatters/VcardInputFormatter.cs

Take a look at the raw docs markdown https://raw.githubusercontent.com/aspnet/Docs/master/aspnetcore/web-api/advanced/custom-formatters.md

You'll find 4 usages of VcardOutputFormatter.cs in the markdown, there are zero instances of VcardInputFormatter.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2207f37-0cf3-3ab9-add8-c50c36409b53
* Version Independent ID: df89a2fd-501e-c917-2962-e4d8d124e852
* Content: [Custom formatters in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/custom-formatters?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/advanced/custom-formatters.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/custom-formatters.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by dotnetchris** [comment]
@Rick-Anderson i located the confusion regarding #6849, the VcardInputFormatter.cs  is not used in the docs markdown to actually be displayed to users.

**Comment by tdykstra** [comment]
@dotnetchris Thanks for explaining the issue,  The omission of input formatter code is by design since in each case the input and output formatter code is similar. I've added a note about the availability of an input example in the sample app at each point where an output example is shown.  Please review PR #9403
