### ISSUE TITLE
Link for "When to use ViewBag, ViewData, or TempData" at the end of page isn't working

### ISSUE THREAD

**Issue by a-yerra** [aspnet/Docs#9399]
The link points to _http://www.rachelappel.com/when-to-use-viewbag-viewdata-or-tempdata-in-asp-net-mvc-3-applications/_ which is no more running. Please restart the webapp or provide an alternative resource.

Thanks!

**Comment by a-yerra** [comment]
This is part of the ASP CORE 2.1 MVC Tutorial at https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/adding-view?view=aspnetcore-2.1

**Comment by ajaybhargavb** [comment]
I just tested this and it seems to be working. Please re-open if you see any flakiness with the link in the future.

**Comment by a-yerra** [comment]
Thanks. Acknowledged, link is working. Probably the host server was down when I last checked.
