### ISSUE TITLE
Link to Getting Started With ASP.NET 5 and Entity Framework 7 fails

### ISSUE THREAD

**Issue by 9034725985** [aspnet/Docs#940]
This link on https://docs.asp.net/en/latest/data/index.html to http://docs.efproject.net/en/latest/getting-started/aspnet5/index.html is 404. Is this intentional? Also following the pattern of ef6, https://docs.asp.net/en/latest/data/entity-framework-7.html is 404 as well.

**Comment by danroth27** [comment]
Looks like the EF folks jumped the gun on the rename: http://docs.efproject.net/en/latest/platforms/aspnetcore/getting-started.html
