### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by athomas-wtv** [aspnet/Docs#9400]
How do I redirect back to the login screen if someone isn't authorized?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3930e5-8a4f-8bdf-7167-9aed8afc4253
* Version Independent ID: cea5942d-fb01-f5bf-3b63-25873d5b79cf
* Content: [Simple authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/simple?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authorization/simple.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/simple.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You don't need to, the framework does that for you.

**Comment by Rick-Anderson** [comment]
@athomas-wtv 	look at the template generated code to see how it's done.

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio
