### ISSUE TITLE
Console app without an entry point

### ISSUE THREAD

**Issue by toryb** [aspnet/Docs#9402]
In the section referenced in the title, the first two steps indicate that the IHostingStartup implementation is in a library that is referenced by the console app. But everything after that indicates that the console app contains the IHostingStartup implementation.

For example, the project XML makes no reference to another library. The sample *.deps.json shows the target and the runtime with the name of the application that is referenced as having the IHostingStartup implementation.

Additionally, the StartupDiagnostics sample application does not reference either the HostingStartupLibrary or the HostingStartupPackage

Is the StartupEnhancement example an example of a console app with no entry point that references a library that contains an IHostingStartup implementation or should the first two steps be changed to indicate that the IHostingStartup implementation is in the console app itself?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613ad64e-bc62-edf7-2e86-42210de718f4
* Version Independent ID: aabbbc32-3237-5ef9-c422-892dc6884a22
* Content: [Enhance an app from an external assembly in ASP.NET Core with IHostingStartup](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/platform-specific-configuration?view=aspnetcore-2.1&tabs=windows)
* Content Source: [aspnetcore/fundamentals/host/platform-specific-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/platform-specific-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks @toryb ... I think you'll end up being correct. The phrase "is referenced" is likely going to turn out to be a poor choice of words. Let me take a closer look at this this afternoon and get back to you. I think we'll end up making a wording change here.
