### ISSUE TITLE
How to work with number?

### ISSUE THREAD

**Issue by TLIOCHON** [aspnet/Docs#9414]
Could you tell how to solve the issue with the decimal number separator (dot or comma)? There is a confilct beetwen jquery validation and .Net model parsing.
Here is the way to reproduce this issue in the demo code with the registration process :
. add number proeprty to RegisterViewModel.cs : public double Height { get; set; }
. add input form group for Heigth to Register.cshtml
. try a registration with french language : with comma the jquery validation fail (The field Height must be a number.), with dot it is model parsing that fail (The value '1.85' is not valid for Height.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#feedback)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review

**Comment by hishamco** [comment]
@Rick-Anderson if you remember, this was already address [here](https://github.com/aspnet/Docs/issues/4076)

**Comment by Rick-Anderson** [comment]
@hishamco 	thanks. I'll get that note added to this doc.

**Comment by hishamco** [comment]
So while this is a duplicate, so we need to close it
