### ISSUE TITLE
Should Fundamentals > Servers be streamlined?

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9416]
This was perhaps discussed and rejected ages ago when the current **Fundamentals &gt; Servers** node and topics were created: Why is so much server configuration in a "fundamentals"-type of topic?

I think the entire node could be collapsed to a single **Servers** overview topic. The deep and extensive details on config for all servers (including an HTTP.sys config topic) could be moved back to **Host and deploy**. That's the way we largely handle IIS/ANCM here.

Any interest in seeing a PR like this to get an :eye:-dear on how it would compose?

cc: @Rick-Anderson @scottaddie @tdykstra @danroth27 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Sounds good to me.

**Comment by Rick-Anderson** [comment]
@tdykstra 	owns TOC so if he says it's OK, it's OK.

**Comment by guardrex** [comment]
Cool ... it won't take long to take a shot at this. It's just a reshuffling of existing content.

I'll wait until after the current round of hosting/server doc updates is merged before I work this issue.

**Comment by danroth27** [comment]
@shirhatti

**Comment by shirhatti** [comment]
My naive answer is yes, but I'd hold off it for the time being. I wanted to do concerted SEO push (post 2.2 updates) and I assume this will just be an artifact of that.

**Comment by guardrex** [comment]
@shirhatti "this will just be an artifact of that" ... Do you want to take this issue, or do u want me to take the issue and wait until you signal me [your PR(s) are merged] before I work it?

**Comment by shirhatti** [comment]
Wait till I signal you 😄

**Comment by guardrex** [comment]
As part of this, we might want to take another look at how we're describing IIS HTTP Server. It's currently defined in the docs as ...

> ASP.NET Core ships with the following server implementations: ...

... and `IISHttpServer` is in the list.

> When hosting in-process, the module has its own server implementation, `IISHttpServer`.

Given https://github.com/aspnet/Docs/issues/9485#issuecomment-439707270 and thinking of it more as a layer of IIS, I wonder if:

* IIS should appear in the list instead of IIS HTTP Server. If IIS is the main server tech, there's no reverse proxy, and IIS HTTP Server is a layer within, that's a potential avenue to simplify how the docs explain the server options available.
* Instead of "has its own server implementation," it might state something along the lines of "has its own layer for processing native requests into managed requests."

**Comment by guardrex** [comment]
@shirhatti Am I still on hold here, or can I proceed with the updates?

**Comment by shirhatti** [comment]
@guardrex You can proceed
