### ISSUE TITLE
Confusing instructions in section "Use F7 to toggle between a Razor Page and the PageModel".

### ISSUE THREAD

**Issue by Bengelinski** [aspnet/Docs#9422]
Confusing instructions in section "Use F7 to toggle between a Razor Page and the PageModel". The textual instruction says to select "Select EditorContextMenus.CodeWindow.ToggleRazorView" - however the picture is showing that the option beneath is selected ("Project and Solution Content....")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.1#use-f7-to-toggle-between-a-razor-page-and-the-pagemodel)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Bengelinski this is fixed in the current version of VS and you no longer need to set it up.

**Comment by ArthurEzenwanne** [comment]
This has actually been fixed, I just installed VS2017. Guess we could close this issue.
