### ISSUE TITLE
Access token logging

### ISSUE THREAD

**Issue by xenalite** [aspnet/Docs#9424]
`"A best practice is to set the web server's logging settings to prevent logging access tokens."`
Would be useful to clarify how to configure logging to log requests except for the ones containing tokens. They appear in `Info` log level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8af11946-ea05-3be2-6fa1-c4c01aa76d8c
* Version Independent ID: 58e87eb0-240b-ab00-c5f4-32a0ab2e0028
* Content: [Security considerations in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/security?view=aspnetcore-2.1#access-token-logging)
* Content Source: [aspnetcore/signalr/security.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/security.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **anurse**

**Comment by Tratcher** [comment]
What field are they being logged from? This is why we don't log request headers or body by default. Is it in the query?

**Comment by xenalite** [comment]
@Tratcher Yes, the token is present in the query string.

**Comment by Tratcher** [comment]
@anurse this is problematic advice as we don't actually provide a way to do it in our stack.

**Comment by anurse** [comment]
This would likely have to be done with a post-processor then. Or we need to provide the functionality. SignalR's access tokens are in the query string, and users should know that, hence why the comment is there.

**Comment by Tratcher** [comment]
@blowdart

**Comment by anurse** [comment]
Filed https://github.com/aspnet/Docs/pull/9440 to add some clarity.

**Comment by Rick-Anderson** [comment]
@anurse what's left to be done in this issue?

**Comment by anurse** [comment]
I don't think there is anything still to be done.
