### ISSUE TITLE
How can we use SASS or LESS in our Angular+Core 2.1 Template Projects?

### ISSUE THREAD

**Issue by FunkMonkey33** [aspnet/Docs#9426]
**Help us make content visible**

- Visual Studio ASP.NET Core 2.1 Angular SASS
- https://docs.microsoft.com/en-us/aspnet/core/client-side/less-sass-fa?view=aspnetcore-2.1

**Describe the new topic**

I would like to be able to use SASS instead of raw CSS in my Angular components.  the styleUrls property does allow you to specify .sass files instead of .css, but they don't get pre-processed.  Google searches for how to do this reference editing webpack.config.cs, which is not present in the Core 2.1 + Angular template.  Other searches reference calling ng eject, which is not supported in the included version of Angular.

Please let us know how to do this.  It makes style management so much better.

Thanks!

Aaron

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by amritrjakacabu015** [comment]
I might be too late on this but, I believe if you change the value of "schematics" under "projects" in your project's angular.json file to: 
`{
        "@schematics/angular:component": {
          "style": "less"
        }` and change all your css files to less (make sure to cover everything i.e. filenames, styleUrls, and angular.json file's "styles" keys). It should work just fine.
