### ISSUE TITLE
there is no web.config in asp.net core 2.0 +

### ISSUE THREAD

**Issue by neno978** [aspnet/Docs#9430]
How to increase default upload size since there is no web config in asp.net core 2.0 project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5cfa38-0e6c-4346-dafc-84ea5c513fcf
* Version Independent ID: c6787f0f-3e9a-6efb-0e6e-5ccb957d3f4a
* Content: [File uploads in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/models/file-uploads.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/models/file-uploads.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
... and note that `UseKestrel` becomes `ConfigureKestrel` in 2.2.

https://docs.microsoft.com/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#maximum-request-body-size

**Comment by ardalis** [comment]
Is that (ConfigureKestrel) a breaking change or will UseKestrel continue to be supported?

**Comment by guardrex** [comment]
@ardalis Not breaking now; possibly not breaking in the future either (3.0).

It was discussed here :point_right: https://github.com/aspnet/KestrelHttpServer/issues/2760#issuecomment-408547274

**Comment by guardrex** [comment]
Also, I should mention in passing @neno978 that this topic is on the schedule for an update at some point. We even have reports that the sample 💥 at times perhaps under certain conditions. See: #5331

**Comment by FunnyNjK** [comment]
When you publish your project, it does create a web.config.  If you publish to a folder profile, you will see it there, or if you publish to IIS/Azure you will also see the file using File Explorer or Azure Console.

..\bin\Release\netcoreapp2.1\publish\web.config

Also if you are hosting under IIS the only 2 items you need are;

From devbrsa - in your Startup Class in the ConfigureSerices method add this at the end.

services.Configure<FormOptions>(x =>
{
    x.MultipartBodyLengthLimit = 1048576000;  //1 GB
});

and in the web.config

  <security>
    <requestFiltering>
      <requestLimits maxAllowedContentLength="1048576000" />
    </requestFiltering>
  </security>

**Comment by neno978** [comment]
@FunnyNjK, ok but what when it is hosted in Linux docker? Then there is no IIS and no web.config? Should the settings be edited through  nginx?
