### ISSUE TITLE
Should the connection between IIS and Kestrel be over HTTPS?

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/Docs#9431]
The docs say no: "Only the reverse proxy server requires an SSL certificate, and that server can communicate with your app servers on the internal network using plain HTTP."

But Scott Hanselman [says yes](https://www.youtube.com/watch?v=h9hlN0DOKRM&feature=youtu.be&t=1494): "You want that secure traffic to be secure all the way. You don't want it terminate at IIS and then have the last hop be eeh. You really want it to be secure all the way, and HTTPS everywhere is becoming an important thing that we don't want to forget."

Is Scott Hanselman's statement incorrect?  Otherwise, should it be incorporated into the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22dcddb-0c25-be1a-9a02-9e71dce86bdb
* Version Independent ID: 3e0e12c2-e544-5655-e001-d2ec180b11a8
* Content: [Kestrel web server implementation in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/servers/kestrel.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/servers/kestrel.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @HappyNomad ... thanks for asking. It's possibly new engineering guidance that hasn't made its way down to us.

@Tratcher @shirhatti ... can you advise?

**Comment by Tratcher** [comment]
I don't quite follow that example, it wasn't even using IIS, it was showing local kestrel config. @danroth27 can you clarify?

ANCM does not support forwarding requests as HTTPS. However it has several other protections in place.

**Comment by shirhatti** [comment]
As Chris said, ANCM doesn't support proxying over HTTPS. It's important to note that just because we don't use HTTPS in the last leg, it doesn't mean we aren't secure. We do create an unique token that we use when proxying over from IIS to your backend process which make it secure.

See https://github.com/aspnet/AspNetCore/blob/master/src/IISIntegration/src/Microsoft.AspNetCore.Server.IISIntegration/IISMiddleware.cs#L89-L93

**Comment by guardrex** [comment]
The pairing token is covered here :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module#proxy-configuration-uses-http-protocol-and-a-pairing-token

**Comment by guardrex** [comment]
I'll close this because the ANCM topics already address this scenario (i.e., not supported; pairing token).

We can re-open to discuss further if required. Thanks @HappyNomad for commenting.
