### ISSUE TITLE
No such thing as HttpRequestMessage as referenced in document page.

### ISSUE THREAD

**Issue by BrianMinister** [aspnet/Docs#9432]
# Issue description

https://docs.microsoft.com/en-us/aspnet/web-api/overview/error-handling/exception-handling references a class called `HttpResponseMessage` which is not found in the API reference.
https://docs.microsoft.com/en-us/dotnet/api/?view=aspnetcore-2.1&term=HttpResponseMessage

# Software versions

- [x] .NET Core 2.1, 2.0

# Details

>This seems to be a pretty critical documentation failure.
>
>Funny part is that this is found under System.Net.Http, and the other lib needed is under System.Net. The page is just incomplete on key information, and the search tool is missing references to the key information.

**Comment by guardrex** [comment]
Hello @BrianMinister ... Try this one ...

https://docs.microsoft.com/dotnet/api/system.net.http.httprequestmessage?view=netframework-4.7.2
