### ISSUE TITLE
AddClaimAsync failed  with SqlException: Cannot insert the value NULL into column 'Id', table 'dbo.AspNetUserClaims'; column does not allow nulls

### ISSUE THREAD

**Issue by niltor** [aspnet/Docs#9433]
# Issue description

AddClaimAsync failed  with SqlException: Cannot insert the value NULL into column 'Id', table 'dbo.AspNetUserClaims'; column does not allow nulls

# Software versions
dotnet 2.1.403
NETCore.App 2.1
AspNetCore.App 2.1.5

<details>

According to the instructions in the official document。

[Persist additional claims and tokens from external providers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/additional-claims?view=aspnetcore-2.1)

when i use code like 
```csharp
await _userManager.AddClaimAsync(user, Principal.FindFirst(ClaimTypes.Gender));
```
i get the error like 
```log
SqlException: Cannot insert the value NULL into column 'Id', table 'guandian.dbo.AspNetUserClaims'; column does not allow nulls. INSERT fails.

DbUpdateException: An error occurred while updating the entries. See the inner exception for details.

```

</details>

**Comment by Rick-Anderson** [comment]
@niltor 	moving to #9518 so it's attached to the doc. You can create issues at the bottom of each page.
