### ISSUE TITLE
sync javascript/typescript examples

### ISSUE THREAD

**Issue by f2calv** [aspnet/Docs#9434]
It would make sense to sync as much of the code in the javascript & typescript examples, i.e.

Typescript example;
public async Task NewMessage(string username, string message)

Javascript example;
public async Task SendMessage(string user, string message)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@f2calv On reviewing the two tutorials more closely, I see a number of differences between them, and both tutorials work well as-is, so there would be limited benefit from resolving the differences, Thanks for the suggestion, but given other priorities for work on our backlog, I don't expect we'll get to this one.
