### ISSUE TITLE
app docs-master is not running

### ISSUE THREAD

**Issue by leder11011** [aspnet/Docs#9436]
steps to reproduce:
leder@leder-VirtualBox:~$ dotnet --version
2.1.403

$killall dotnet

leder@leder-VirtualBox:~/Projekt/Doc-master/aspnetcoreapp$ dotnet publish --configuration Release
Microsoft (R)-Build-Engine, Version 15.8.169+g1ccb72aefa für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Wiederherstellung in "80,82 ms" für "/home/leder/Projekt/Doc-master/aspnetcoreapp/aspnetcoreapp.csproj" abgeschlossen.
/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.aspnetcore.razor.design/2.1.2/build/netstandard2.0/Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(121,5): error : rzc generate exited with code 2. [/home/leder/Projekt/Doc-master/aspnetcoreapp/aspnetcoreapp.csproj]

How come?

**Comment by Rick-Anderson** [comment]
Thanks for the comment. This doesn't appear to be a document issue.
