### ISSUE TITLE
Get stacktrace when a test crashes

### ISSUE THREAD

**Issue by stilren** [aspnet/Docs#9437]
Hi! Thanks for a great tutorial.

One thing that always seems needlessly complicated is getting  a stacktrace whenever a integration test fails. How would one go about that in the most non hacky way in this project?

As a demo, throw an exception in the OnGetAsync method on GithubProfileModel which will cause GithubProfileModel-test to fail with an empty stacktrace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @stilren ... I like your suggestion here for the topic. Let me look into it and get back to you shortly.

**Comment by guardrex** [comment]
@javiercn TL;DR Any way to get the stack trace of the app's exception *in the test* (i.e., some special case where one wouldn't just log it from the app)?

@stilren Why try to recover the stack trace in the test itself? I feel you must have a special reason not to just log it from the app.

Anyway ... as for the test itself ... I'm sure you saw that the test throws its own exception and has its own stack trace. As far as I can tell, the framework doesn't forward the stack trace of the app's exception (or the exception itself for that matter) to the test.

**Comment by javiercn** [comment]
I believe the best option here is to use logging. The host will convert exceptions into 500 responses (Which is what it should do) so the best way to capture the stacktrace is to wait until the exception bubbles up and gets logged.

If you are debugging the best way to see the exception is to enable first chance exceptions and wait for the debugger to break.

**Comment by stilren** [comment]
Wow thats a quick reply! 

As for the use case its partly for test reports, when something breaks in the build pipe you would like to have more information about it without having to reproduce locally (if that is even an option). Its also partly because its much more convenient to have it in the test runner when developing and not having to go digging for logs.

As for throwing a 500, its ofcourse a preferred options but often times the test will break in the middleware before an endpoint is reached (say you forgot to inject a dependency). Also I am not sure you would want to include a stacktrace in your httpresponse even if you could.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

The information is now visible to the doc via the close issue tab.
