### ISSUE TITLE
ANCM In-Process documentation

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Docs#9441]
Overall, ANCM In-Process documentation still needs a lot of work. Topics missing include
- Documentation on new module (AspNetCoreModuleV2) and associated changes
- Getting started with ANCM Inproc
- New ways of gathering information (Logs and debug logs, environment variable activation, etc.)
- Diagnostics (new startup pages) => #9452 resolves this
- Managed server configuration options
- IServerVariableFeature

**Comment by guardrex** [comment]
@jkotalik Are you looking at the 2.2 version of the ANCM ref doc?

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2

**Comment by jkotalik** [comment]
Yep. 

> Documentation on new module (AspNetCoreModuleV2) and associated changes

This refers to how ANCM is now split into two different dlls and architectural changes associated.

> Getting started with ANCM Inproc

@shirhatti will be taking care of this.

> New ways of gathering information (Logs and debug logs, environment variable activation, etc.)

I think this is covered here: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#enhanced-diagnostic-logs, but want to do another pass through.

> Diagnostics (new startup pages)

We added a few new startup pages in 2.2-preview3. @shirhatti we need to make sure the hyperlinks on the startup pages redirect to something 😄

**Comment by guardrex** [comment]
> This refers to how ANCM is now split into two different dlls and architectural changes associated.

> Getting started with ANCM Inproc

Just want to mention in passing that we doc the current approach for the current version. We try not to use 'new in 2.2 you can'- and 'you used to do it this way'-types of remarks in reference docs. Of course, the blog posts make such remarks. Just want to make sure we're on the same page ... it's 💰 **_costly_** 💰 to make changes then go back in later and refactor the changes.

> new startup pages in 2.2-preview3

:+1: Very good ... it's the first I'm hearing about it.

**Comment by guardrex** [comment]
@shirhatti Note that we want to defer configuration details to the ANCM reference topic as much as possible.

We're lightly discussing it on https://github.com/aspnet/Docs/issues/9416 ... e.g., imo there's far (**_FAR_** :smile: lol) too much config now for Kestrel to be in a "fundamentals"-type of topic. The best thing imo for fundamentals is to refer back to the ref topic in *Host and deploy* for the juicy details.

I believe the same thing will turn out to be the case for ANCM/IIS. We may ... guessing at this point ... spit-ball'in here ... just have a single *Servers* topic in fundamentals that is truly just an overview of the key issues ... choices ... pros & cons ... everything config-wise would go back to *Host and deploy*. That's how I feel about it anyway ... but **_I'm only in charge of one thing here_** ... which brand of :beer: I'll be having next Friday. :smile: lol

**Comment by jkotalik** [comment]
Closing for now as we added a good amount of documentation already and it's a catch all.
