### ISSUE TITLE
Separate _ViewImports.cshtml required in each area

### ISSUE THREAD

**Issue by ygoe** [aspnet/Docs#9448]
Is there a reason why a _ViewImports.cshtml file is required in each area's Views folder? Without it, the @model type isn't found in my area's views. After copying the file from /Views into /Areas/MyArea/Views, the error was resolved.

If this is intentional, I guess it should be mentioned here. The assistant in Visual Studio that did other things to create my new (and first) area, hasn't done that either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by ygoe** [comment]
[This question](https://stackoverflow.com/q/13277126/143684) about repeating the _ViewStart.cshtml file in each area might be related. I also needed this to seamlessly integrate my new area into the application. It still applies to ASP.NET Core.

**Comment by Rick-Anderson** [comment]
@dougbu "Is there a reason why a _ViewImports.cshtml file is required in each area's Views folder? "

**Comment by dougbu** [comment]
The `_ViewImports.cshtml` file is found strictly using the folder hierarchy within a project. I couldn't find a description of how different views are found in a quick search. But, this should be documented somewhere.

(I haven't tested the following.) A `_ViewImports.cshtml` file in the `/Areas` folder should apply to every page in all areas. Such a file in the project root should also work fine.

**Comment by rwatjen** [comment]
I have just tested this. If you move both `_ViewImports.cshtml` and `_ViewStart.cshtml` they apply to the entire site. 

It is described in https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-2.1, but it would be nice to have a mention of it here on the Areas page also.

**Comment by Rick-Anderson** [comment]
At least with ASP.NET Core 2.2, all you need is the default *Views\_ViewImports.cshtml* - no need to copy to the areas folder or move to root. 

*_ViewStart.cshtml* can moved moved to the root folder so the entire app uses the same layout (including areas). 

I have a repo demonstrating this at https://github.com/Rick-Anderson/Areas

**Comment by phillip-haydon** [comment]
Why does the imports need to be included in Area's folder? Why doesn't it inherit from the root Views unless its in Areas, similar to way view lookup is handled.
