### ISSUE TITLE
Using Kerberos/Negotiate/UseDefaultCredentials with WebApplicationFactory

### ISSUE THREAD

**Issue by lambdakris** [aspnet/Docs#9451]
Is there a way to set UseDefaultCredentials = true or otherwise use Kerberos/Negotiate for intranet style apps with the WebApplicationFactory?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1#additional-resources)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I can't say ... I haven't attempted it or looked deeply into the subject yet. We have a few issues to improve coverage for testing with an authenticated user under various scenarios. I'm not sure when we'll get to these. Right now, we're all 🏃🏃🏃🏃😅 to get the 2.2 doc updates ready for 2.2 RTM. Let's link these issues together here and leave this open. We may end up working these issues together.

* How to create authenticated request? #6882
* How to actually perform post requests? #7526
* How to test Web API with Jwt Bearer Authentication #8796

**Comment by lambdakris** [comment]
Ok, found [this issue](https://github.com/aspnet/Hosting/issues/924) after some additional digging. In my case, it sounds like WindowsAuth/Kerberos/NTLM/etc are essentially a no go when using the TestServer (though some hacks are possible or manually spawning my own test server with kestrel). However, I am not entirely sure if those other issues you referenced are similarly impacted by the design of TestServer? I would think the Jwt Auth at least should work since that can be added to the request header and does not involve how the HttpClient generated by the TestServer is constructed.

**Comment by guardrex** [comment]
> impacted by the design of TestServer?

Yes, TestServer is still under-the-covers. If a testing scenario directly relates to TestServer operation, it's likely that the behavior remains today. However, there's churn in the framework, so the TestServer today is probably better than in versions past.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
