### ISSUE TITLE
DistributedRedisCache will write  something extra into the cache

### ISSUE THREAD

**Issue by CwjXFH** [aspnet/Docs#9471]
# Document url
[Distributed Redis Cache](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.1#distributed-redis-cache)

# Issue description
Add service in container:
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDistributedRedisCache(opt => { opt.Configuration = "localhost:6379"; });
}
```

Set cache:
```c#
var info = new {Name = "xfh"};
var options = new DistributedCacheEntryOptions()
    .SetSlidingExpiration(TimeSpan.FromSeconds(20));
_cache.SetString(cacheKey, info.ToString(), options);
```

But,wirte into redis three keys and data type is hash instead of string

|key|value|
|---|---|
|absexp|-1|
|sldexp|200000000|
|data|{Name=xfh}|

In addition,`IDistributedCache` cannot use `set`,`list`,etc data struct of redis.

So,I don't think the `IDistributedCache` is suit for redis.,and I don't understand why design this interface.

Maybe I'm wrong,Thanks!

# Software versions

- .NET Core 2.0
- Microsoft.Extensions.Caching.Redis 2.1.2

**Comment by guardrex** [comment]
Hello @CwjXFH ... This is the docs repo, and we just work on documentation issues here. I recommend you open your feedback on the ASP.NET Core issues repo :point_right: https://github.com/aspnet/AspNetCore/issues

**Comment by CwjXFH** [comment]
I'm sorry,thank you!
