### ISSUE TITLE
Please update description for AddMvcCore / FormatFilter usage.

### ISSUE THREAD

**Issue by Igor-Pchelko** [aspnet/Docs#9475]
If endpoint or controller uses FormatFilter attribute then the corresponding service should be registered:

```
services.AddMvcCore()
  ...
  .AddFormatterMappings
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebcd752-af71-c483-eebb-0745bd04fb30
* Version Independent ID: 1f678d5d-230b-0ad0-c925-15b13081f553
* Content: [Format response data in ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.1)
* Content Source: [aspnetcore/web-api/advanced/formatting.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/web-api/advanced/formatting.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Igor-Pchelko 	I don't understand your request.

**Comment by Igor-Pchelko** [comment]
In case if Mvc stack is bootstrapped with AddMvcCore to use FormatFilter attribute we need to call AddFormatterMappings to register corresponding service.

Here are is an example of issue:

**Comment by Rick-Anderson** [comment]
@dougbu 	should this be added to the doc?

**Comment by dougbu** [comment]
@Igor-Pchelko we would not recommend using `AddMvcCore(...)` in most cases.

@Rick-Anderson I wouldn't document this particular aspect of using `AddMvcCore(...)` at all. However, it's worth adding a fairly prominent note wherever `AddMvcCore(...)` is mentioned. That note should state the API is intended only for very advanced uses, that many choices when using it can break applications, and that we do not document those nuances.

**Comment by dougbu** [comment]
FYI @rynowak
