### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#948]
Add a topic to the MVC docs on how to handle file uploads. Link to it from the model binding doc.
Outline:
How to Upload Simple Files (show simple form)
Bind to an Action with IFormFile (or IEnumerable)
  Show how to handle this
  These files are buffered
If you want to stream the file because of size, validation, etc.
  Show streaming support
  Show saving to Azure blog storage

Anti-forgery is different for fileuploads - need to be passed in headers.

Notes:
Uploading files:
1. Multi-Part Form Post
2. Put the data in the Body of a request
3. Streaming/multipart files - prefer for large files or if it's being done frequently
   Two reasons: 1. Sheer size of the data; 2. You want to look at headers before the data is sent, and cancel early (saving bandwidth).

To stream a multi-part post, you need to iterate through each section and decide what to do with it. There are usually two kinds of data: key-value data and opaque file data. The key-value data is just like typical POSTed data. This can be kept in a KeyValueAccumulator for later access. If it's a file section, you determine where to store it and send it there (e.g. with CopyToAsync).

The fileSection.FileName is client-submitted data and should be considered untrustworthy.

Note to author: ignore the model binding on lines 100+ in FileController.cs

File Upload Sample
https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.FileUpload 
FileController - Upload()
DisableFormValueModelBinding - because model binding loads all in memory
RequestFormLimitsController

See also
https://github.com/aspnet/Mvc/tree/dev/test/WebSites/FilesWebSite 
UploadFilesController
IFormFile interface - will be read eagerly, not streamed/chunked
Model binding works against IFormFile or IEnumerable<IFormFile> - see that doc.

You cannot get an IFormFile that's directly connected to the network/HTTP - it's always dealing with buffered data. See also IFormFileCollection

To upload from a mobile app... you would follow same multi-part form post pattern.

For doc sample, consider a user with an avatar image.

FormOptions (Http.Features.FormOptions)
Used to set limits on memory buffers.

MemoryBufferThreshold - how many bytes are buffered in memory - reference when discussing buffering to memory/disk behavior
MultipartBodyLengthLimit - Most likely to be hit. Limit on each part length. Applies to IFormFile uploads. In streaming case, this is unlimited by default.

MultipartReader also has properties that can be set, such as BodyLengthLimit.

If you want to be able to handle file uploads without MVC (e.g. from middleware), you can use HttpContext.Request.Form and ReadFormAsync.

**Comment by Charmatzis** [comment]
if I can help please show me the way... I am quiet new to GitHub.
I have worked with a MVC project and I will write here an example.

**Comment by Charmatzis** [comment]
The model class will be 


```
public class RegisterModel
    {
        [Required]
        [Display(Name = "Username")]
        public string Username { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Photo")]
        [FileExtensions(Extensions = "jpg,jpeg,png")]
        public IFormFile ImageUpload { get; set; }

    }
```


Here is the controller code...


```
 public class RegisterController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        public RegisterController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterModel registerModel)
        {
            if(ModelState.IsValid)
            {
                var file = registerModel.ImageUpload;
                //Get the path of the folder Images in the wwwroot file
                var uploads = Path.Combine(_hostingEnvironment.WebRootPath, "Images");
                var filePathName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                var fileExtention = Path.GetExtension(filePathName);
                var fileName = Guid.NewGuid().ToString("N").Substring(0, 6) + fileExtention;
                var path = Path.Combine(uploads, fileName);
                //the image will be saved with a unique filename
                await file.SaveAsAsync(path);


                //Here is the code for the other properties of the model


                return View();
            }
            else
            {
                return View("Error");
            }
            
        }
}
```

Finally this is the View code


```

@model RegisterModel
@{
    ViewData["Title"] = "Register";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Register" asp-action="Register" method="post" class="form-horizontal col-md-6" role="form" enctype="multipart/form-data">
    <h4>Create a new account</h4>
    <hr />

    <div class="form-group ">
        <label asp-for="Username" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Username" class="form-control" placeholder="username" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="ImageUpload" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ImageUpload" class="form-control" />
            <span asp-validation-for="ImageUpload" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Register</button>
        </div>
    </div>

    <hr />
    <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
</form>
```
