### ISSUE TITLE
Drop 'reverse proxy' language

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9485]
https://github.com/aspnet/Docs/pull/9463#issuecomment-436420203

We'll be dropping 'reverse proxy' language where possible per the engineering guidance. Replacement text will go along the lines of ...

> the ANCM allows an app to run behind IIS

**Comment by Rick-Anderson** [comment]
@Tratcher 'reverse proxy' is widely used. If we want to use a more precise term, we should keep reverse proxy. For example:

the ANCM allows an app to run behind IIS (commonly called a reverse proxy)

that way customers searching on [ASP.NET Core reverse proxy](https://www.google.com/search?q=asp.net+core+reverse+proxy&rlz=1C1CHBF_enUS801US801&oq=ASP.NET+Core+reverse+proxy&aqs=chrome.0.0l6.1489j0j7&sourceid=chrome&ie=UTF-8) can find what they're looking for.

cc @tdykstra @scottaddie @jkotalik

**Comment by guardrex** [comment]
> widely used

... 88 references across 16 markdown files. IIRC, it was ~97 refs, but we removed a few on the doc-a-thon PR.

**Comment by Tratcher** [comment]
@jkotalik what's wrong with the reverse proxy language? That's what ANCM out-of-proc is. Any specific examples where you think it's misleading? Or is this more about cutting the verbosity?

**Comment by guardrex** [comment]
@Tratcher - @jkotalik will need to say ... I'm just following orders.

WRT in-process, can you explain a bit more? Definitions of "reverse proxy" seem to pertain to the number and arrangement of servers for request processing, not how the servers' code is executed on the host (i.e., what process they're running in). Is Kestrel no longer a "server" when hosting in-proc?

**Comment by Tratcher** [comment]
When ANCM hosts ASP.NET Core in-proc it doesn't uses Kestrel, it passes requests directly to the app. In this case it's no longer acting as a proxy, but the direct server (i.e. there's only one server here).

**Comment by guardrex** [comment]
Oh, yes, of course ... `IISHttpServer` ... thanks for reminding me.

However, does the question remain?

There's IIS and IIS HTTP Server&dagger; (`IISHttpServer`) in-proc ... that's *not* considered two servers?

[&dagger;"IIS HTTP Server" &ndash; I guess that's how we'll write it into content.]

**Comment by Tratcher** [comment]
It's no more two servers than HttpSysServer is two servers. They are certainly two layers, but not two independent servers.

**Comment by jkotalik** [comment]
>  Any specific examples where you think it's misleading? 

@Tratcher there isn't anything wrong with the reverse proxy language, per say. The issue is more that if we want to push ANCM InProc as the way to hosting behind IIS from 2.2 and beyond, we should check any place that contains the language "Reverse Proxy" and fix modify it accordingly (whether it be with monikers or changing the language in general).

**Comment by Tratcher** [comment]
Ah, generalizing to account for in-proc where appropriate makes sense.

**Comment by guardrex** [comment]
I believe I'm in good shape now to perform the update.

I'll work this issue after the current batch of IIS-related PRs are merged.

**Comment by guardrex** [comment]
@tdykstra I think we did a good job for the 2.2 updates; so in those spots, I think we're ok. Those references are tied into the hosting model description and seem clear to me. For example ...

* https://docs.microsoft.com/aspnet/core/fundamentals/servers/aspnet-core-module?view=aspnetcore-2.2#aspnet-core-module-description
* https://docs.microsoft.com/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2#hosting-model

... but I'll look again just to make sure.

Idk on the other **_~70+ references_**. I'll check all of them.

**Comment by guardrex** [comment]
@shirhatti I'm going to work the "reverse proxy" language (this issue) now. I'm holding off on the Servers TOC node work for your signal to proceed. Let me know if your schedule changes that affects that work prior to 12/31 ... I'd like to get that one done while I'm still on-the-clock here.
