### ISSUE TITLE
.net core 2.2

### ISSUE THREAD

**Issue by FiodorTretyakov** [aspnet/Docs#9494]
&lt;PropertyGroup&gt;
   &lt;TargetFramework&gt;netcoreapp2.2&lt;/TargetFramework&gt;
   &lt;RuntimeIdentifier&gt;win7-x64&lt;/RuntimeIdentifier&gt;
&lt;/PropertyGroup&gt;

2.2 still in preview. Please, fix to 2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @FiodorTretyakov ... That's by design. We're moving some of the samples to 2.2 in advance of the release. All you need to do is downgrade it to `netcoreapp2.1`.
