### ISSUE TITLE
Cannot create new tables of complex data model

### ISSUE THREAD

**Issue by KruthikaB** [aspnet/Docs#9495]
I am following Razor Pages with EF Core in ASP.NET Core and in step 6 of creating complex data model. I am trying to apply migration using 'Apply the migration to the existing database.' but  the steps dont clearly explain how to apply migration. I am not able to create those tables. Can someone please help me with this or point me to right place if I have missed anything.

Thanks,
Kruthika

**Comment by Rick-Anderson** [comment]
Can you add the link and text to the page you're having problems with?
