### ISSUE TITLE
Detect intended/unintended client disconnect

### ISSUE THREAD

**Issue by pardahlman** [aspnet/Docs#9497]
It is not clear from the documentation if there is any way to distinguish if a client was disconnected from a hub due to technical problems (connectivity issues, application exception, ...) or if it was intended (client closed window, ...).

Looking at the signature, `OnDisconnectedAsync(Exception exception)` I am lead to believe that `exception` will be null when all is fine, and always set to something if the disconnect was unintentional. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1#handle-events-for-a-connection)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @anurse

**Comment by anurse** [comment]
That's correct. I'm doing some updates to the Hubs API doc, so I'll look at including this.
