### ISSUE TITLE
Kudu APIs to publish to Azure from any platform

### ISSUE THREAD

**Issue by Placid7** [aspnet/Docs#9499]
This "Kudu APIs to publish to Azure from any platform" section needs to either be removed or at least sectioned off. It is not required and it's difficult where these steps should start and end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684d1f55-3d8b-9ba6-ee65-e8f84c2b4244
* Version Independent ID: 2db330b4-e830-715f-0a15-e406f85e1d3b
* Content: [Visual Studio publish profiles for ASP.NET Core app deployment](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/visual-studio-publish-profiles.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/visual-studio-publish-profiles.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Placid7 	I don't see

> This `Kudu APIs to publish to Azure from any platform` section

There is a section [The Kudu service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/visual-studio-publish-profiles?view=aspnetcore-2.1#the-kudu-service)

Kudu is super useful.

**Comment by Placid7** [comment]
That's because it's embedded in the "Publish profiles" section. Just search for the string "Kudu" or "Kudu APIs to publish to Azure from any platform" and actually above that is "dotnet publish can use folder, MSDeploy, and Kudu publish profiles:" It completely breaks the flow of the document.

**Comment by Rick-Anderson** [comment]
Closing. Kudu links are very useful.
