### ISSUE TITLE
Logging on Azure

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#950]

**Comment by marchy** [comment]
Any progress on this now that RTM is out?

**Comment by GuardRex** [comment]
@marchy The `publish-iis` tooling will create the correct log path in your `web.config` for Azure App's `LogFiles` folder.

https://github.com/aspnet/IISIntegration/blob/dev/src/Microsoft.AspNetCore.Server.IISIntegration.Tools/WebConfigTransform.cs#L88

https://docs.asp.net/en/latest/publishing/iis.html#publish-iis-tool

**Comment by Rick-Anderson** [comment]
dup of #1673
