### ISSUE TITLE
Add notes about StackExchangeRedis client in ASP.NET SignalR docs

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#9502]
(This is for ASP.NET SignalR, **not** ASP.NET Core SignalR)

We should mention the new StackExchangeRedis package in https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis

cc @BrennanConroy @bradygaster

**Comment by tdykstra** [comment]
Closing as dup of #9589
