### ISSUE TITLE
Documentation: Definition of ApplicationUser and ApplicationDbContext

### ISSUE THREAD

**Issue by nightblade9** [aspnet/Docs#9504]
For anyone creating a brand new ASP.NET MVC Core application, you will notice that `ApplicationDbContext` and `ApplicationUser` are not defined. After a fair amount of searching, I found the definitions in [an earlier tutorial in this series](https://docs.microsoft.com/en-us/aspnet/core/migration/identity?view=aspnetcore-2.1).

For posterity, their definitions are below; both should go into a `Models` namespace.

```
// ApplicationUser.cs
public class ApplicationUser : IdentityUser
    {
    }
```

```
// ApplicationDbContext.cs
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Core Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Core Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d19b295-f935-3755-4ca4-9d0717b21e75
* Version Independent ID: 747a179e-90b7-de07-e270-82414963048a
* Content: [Google external login setup in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authentication/social/google-logins.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/social/google-logins.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@nightblade9 	thanks for this information. We hope to get this updated in the next doc sweep.

**Comment by Rick-Anderson** [comment]
Right click (in VS), go to definition takes you to *Data/ApplicationDbContext.cs*
