### ISSUE TITLE
AngularJS code example in documentation is lacking example of creating the cookie

### ISSUE THREAD

**Issue by ahsteele** [aspnet/Docs#9509]
I realize that the linked code example shows how to provide a token cookie called `XSRF-TOKEN` and have the antiforgery service check for `X-XSRF-TOKEN` header. For a developer not fully paying attention the lack of inline code example of creating the cookie could create a security misconfiguration. Please add a few lines to the AngularJS example showing how to add the cookie in addition to the existing header check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47b14f57-82ac-a2e2-cbc7-22a81a60f4ac
* Version Independent ID: bffca13c-223f-c61f-9cb2-9da8811eecfa
* Content: [Prevent Cross-Site Request Forgery (XSRF/CSRF) attacks in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/anti-request-forgery.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/anti-request-forgery.md)
* Product: **aspnet-core**
* GitHub Login: @steve-smith
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by ahsteele** [comment]
What I take from your response is that Microsoft doesn’t have the resources
to keep its documentation up to date. Even when that documentation is
glaringly incomplete leading to security significant misconfigurations. I
understand that everything must be prioritized but closing an issue because
you can’t work on it right now seems a bit odd.

The necessary work is copying and pasting from the already linked code
example. On the surface it doesn’t seem like a huge time investment is
required. (I understand that often times things that seem simple from the
outside are very difficult on the inside).

What is the required number of 👍 responses to get this issue adequate
resource allocation?

**Comment by Rick-Anderson** [comment]
@scottaddie 	please review.

**Comment by Rick-Anderson** [comment]
@ahsteele 	any chance you could edit PR this?
cc @scottaddie

**Comment by ahsteele** [comment]
Sure I can take a stab at it. I’m back in work mode on Monday so will do so
sometime next week.

**Comment by ahsteele** [comment]
Rick,

Sorry for my delayed reply. I hit the ground running these past few weeks
and haven’t had a chance to get back to this. The documentation for what
needs to be done is in the Angular JS project on GitHub. I will try and
pull the details out by the end of the week. Thank you for hitting me up on
this.

Andrew

**Comment by ahsteele** [comment]
@Rick-Anderson I have made two versions which would address my concerns.

[Option 1](https://github.com/aspnet/Docs/commit/a71743374a4632b70abe0618c114d5972a3dc7cb?diff=split) is to link to an earlier section in the article detailing the IAntiforgery configuration and calling out that the code block below doesn't show how to do this. I also tried to make it more clear no cookie header / configuration is required in the client.

[Option 2](https://github.com/aspnet/Docs/commit/905e478acb8c9533e1ba826c81a9d48fe469ee96?diff=split) is to restate the cookie configuration in the AngularJS example code block.

Not being familiar the project's documentation standards which of the two do you prefer? Let me know and I'll create a PR for that one.

Thank you for being patient with me while I got back to this. Ramping up after the holiday has taken longer than I thought it would.

**Comment by Rick-Anderson** [comment]
**[Option 2](https://github.com/aspnet/Docs/commit/905e478acb8c9533e1ba826c81a9d48fe469ee96?diff=split)** is to restate the cookie configuration in the AngularJS example code block.

That looks best to me but I'll defer to @scottaddie 

@HaoK 	who's the right contact to review XSRF/CSRF with AngularJS?

**Comment by HaoK** [comment]
@blowdart ?
