### ISSUE TITLE
why the = ?

### ISSUE THREAD

**Issue by jagerschmidt** [aspnet/Docs#9512]
thanks for this demo; it helped.  now i'm wondering why every hash & salt i generate ends with one or two equals (=) characters?  this is predictable, which is bad, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc1052d7-e93f-fcb8-6d87-d86cededad23
* Version Independent ID: 61e65ca8-4008-ed27-7254-93385a9ed6d7
* Content: [Hash passwords in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/data-protection/consumer-apis/password-hashing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/data-protection/consumer-apis/password-hashing.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's padding for base64 encoding IIRC. If you search the Net, you'll find references that explain in detail.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by jagerschmidt** [comment]
thanks.  i hadn't b64 encoded anything for 3 years and forgot that extra bits are padded.  also realized, if you don't want any padding, can use bytes in factors of 3.  iow: byte array count that's a factor of 3 = clean (no padding) b64 hash.
