### ISSUE TITLE
How to run a release build?

### ISSUE THREAD

**Issue by Neutrino-Sunset** [aspnet/Docs#9531]
Following this approach IIS references the project root directory containing web.config which launches the process "bin\IISSupport\VSIISExeLauncher.exe". But when you switch to a Release build IISExeLauncherArgs.txt still contains a path to the debug build.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5477f20-bdbf-ae0b-63b4-8bf6789f7a48
* Version Independent ID: fa9dc362-76a4-5d11-f457-b3d8550f9997
* Content: [Development-time IIS support in Visual Studio for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/development-time-iis-support?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/iis/development-time-iis-support.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/development-time-iis-support.md)
* Product: **aspnet-core**
* GitHub Login: @shirhatti
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Neutrino-Sunset ...

> when you switch to a Release build

Could you say a little more about what you're trying to accomplish? I get the impression that you're trying to use the VS IIS dev-time support with a Release build, but that's not a supported scenario AFAIK.

**Comment by Neutrino-Sunset** [comment]
You got it. I'm trying to use VS IIS integration to run a Release build. The project I'm working on the Debug build is really slow, I need to debug occasionally to locate issues but most of the time I need to run the Release build for the performance. Using VS IIS integration I see no way to switch between Debug and Release which means I have to manually reconfig IIS to switch, which for a micro services architecture with many web service is really painful.

This page is the official documentation for VS IIS integration, and there's nothing here which says it's not supported for a Release build, so if that is indeed the case then maybe the docs should be updated to make that clear.

**Comment by guardrex** [comment]
> manually reconfig IIS to switch

What I do is set up a site in IIS (a separate site) and point it to the *publish* folder of the Release configuration. To publish/run the site:

1. Use PowerShell to bring down the site's app pool.
1. Perform a folder publish (VS) or `dotnet publish -c Release` (VSC/CLI)
1. Fire the site's app pool back up.

Some devs still have file locking issues when using *app_offline.htm* (including myself a few times a year or two back), so I prefer to use PS. Let me know if you'd like to see the scripts. They were pulled recently from the docs.

WRT the topic ... Thanks for pointing this out. I agree. I'll add a comment on this to the *Run the project* section of the topic.

**Comment by shirhatti** [comment]
cc @BillHiebert

**Comment by BillHiebert** [comment]
@Neutrino-Sunset - I can't reproduce your original issue: "But when you switch to a Release build IISExeLauncherArgs.txt still contains a path to the debug build."

Can you provide repro steps for this?  
Thanks.
