### ISSUE TITLE
Concern about ID Naming Convention

### ISSUE THREAD

**Issue by hatemalhassani** [aspnet/Docs#9538]
To differentiate words in an identifier, capitalize the first letter of each word in the identifier, generally in naming properties in c# the naming convention is pascal, but i notice in some examples like the movie class the ID property written capital letters. Is that break the Name convention which recommended by Microsoft documents https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/built-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b6d0f3-9bc7-d091-0d45-9fc1e2e7aac8
* Version Independent ID: 20e7eb53-215b-09ab-205d-d20177221278
* Content: [Add validation to an ASP.NET Core Razor Page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/validation?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
No because ID is an abbreviate. 

>Is that break the Name convention which recommended by Microsoft documents docs.microsoft.com/en-us/ef/ef6/modeling/code-first/conventions/built-in

It uses ID as in `DepartmentID`, `CourseID`
