### ISSUE TITLE
Highlight that the default KnownProxies and KnownNetworks value won't work when the proxy is on a different machine

### ISSUE THREAD

**Issue by cviktor** [aspnet/Docs#9540]
I think the docs should highlight that in scenraios where the proxy is not on the same machine as the webserver (for example in container orchestration solutions or cloud solutions) the default value of the KnownProxies and KnownNetworks will cause that the middleware is essentially not working. I think that in a lot of production scenraios the proxy server is different from the actual webserver so the developer have to specify the KnownProxies and KnownNetworks otherwise it won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e548cd16-b06c-5802-a1a7-c627167857ae
* Version Independent ID: c48abb08-bea3-dcff-c067-2edf5dc9b3a6
* Content: [Configure ASP.NET Core to work with proxy servers and load balancers](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/proxy-load-balancer.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/proxy-load-balancer.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @cviktor ... Thanks for your feedback, but I think that it's covered by the topic's text.

The description of `KnownProxies` is ...

> Addresses of known proxies to accept forwarded headers from. Use KnownProxies to specify exact IP address matches.

... and ...

> The default is an `IList<IPAddress>` containing a single entry for `IPAddress.IPv6Loopback`.

... so it's clear that the dev will need to provide the addresses of their known proxies given that the default is only the loopback address. `KnownNetworks` uses similar language.

We can re-open to discuss further if you wish, but I think the topic covers this. We'll keep an eye out for additional feedback. Thanks again for commenting.
