### ISSUE TITLE
.NET Core 2.1 little different

### ISSUE THREAD

**Issue by rogatec** [aspnet/Docs#9550]
the *.csproj file looks a little different when using the newest Visual Studio for Mac, because of the .NET core 2.1 version.

If you want to use the latest .NET core version, just edit the version attributes of the NuGet packages to 2.1.
To prevent any warnings you need the *.CodeGeneration.Tools PackageReference with the current latest version `2.1.0-preview1-final`.
Additionally the *.CodeGeneration.Design PackageRefrence needs `Version="2.1.0"` to prevent errors while `dotnet restore`.

Additionally I needed to add `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1" />` otherwise in the _Startup.cs_ file the DbContext could not resolve `options.UseSqlite()`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8f1ddf-9c5f-dc16-c1f1-666b47ce75cf
* Version Independent ID: 14a55423-04fa-4dc7-bb0b-c09d1350aa6b
* Content: [Add a model to an ASP.NET Core MVC app with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/adding-model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-mac/adding-model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-mac/adding-model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks. I'll be updating this for 2.2 and 2.1 soon.

**Comment by andersbirkmose** [comment]
Hi.
I have followed the guide, and I have added the new nuget version numbers and I have added the sqlite package ref. 

I get no errors in the dot net restore, and I can build the solution. 

But the scaffolding does not create the controller MovieController.cs file nor the Movies folder in views.

**Comment by andersbirkmose** [comment]
this made it work! :-)

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" version="2.1.4" Version="2.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1" />
  </ItemGroup>
  
    <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.1.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\HelloWorld\" />
  </ItemGroup>
</Project>

**Comment by emd5** [comment]
To scaffold the MovieController. In the MvcMovis.csproj should look like this:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="NuGet.Core" Version="2.14.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0" />


  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.1.0-preview1-final" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\HelloWorld.cshtml" />
    <Content Remove="Views\Movies\Movies\Create.cshtml" />
    <Content Remove="Views\Movies\Movies\Delete.cshtml" />
    <Content Remove="Views\Movies\Movies\Details.cshtml" />
    <Content Remove="Views\Movies\Create.cshtml" />
    <Content Remove="Views\Movies\Delete.cshtml" />
    <Content Remove="Views\Movies\Details.cshtml" />
    <Content Remove="Views\Movies\Edit.cshtml" />
    <Content Remove="Views\Movies\Index.cshtml" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Views\HelloWorld\" />
    <Folder Include="Views\Movies\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Views\HelloWorld\EmptyHTMLFile.html" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Views\Movies\Create.cshtml" />
    <None Include="Views\Movies\Delete.cshtml" />
    <None Include="Views\Movies\Details.cshtml" />
    <None Include="Views\Movies\Edit.cshtml" />
    <None Include="Views\Movies\Index.cshtml" />
  </ItemGroup>
</Project>
```

**Comment by Rick-Anderson** [comment]
Fixed

**Comment by LeonhardPrintz** [comment]
For version 2.2.0 this MvcMovies.csproj did the trick for me.

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.0"/>
  </ItemGroup>
    
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.2.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\HelloWorld\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Views\HelloWorld\EmptyHTMLFile.html" />
  </ItemGroup>
</Project>

**Comment by LeonhardPrintz** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.0"/>
  </ItemGroup>
    
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.2.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\HelloWorld\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Views\HelloWorld\EmptyHTMLFile.html" />
  </ItemGroup>
</Project>

**Comment by LeonhardPrintz** [comment]
Huh, how do I post code?

**Comment by LeonhardPrintz** [comment]
[code]<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.2.0"/>
  </ItemGroup>
    
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.2.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\HelloWorld\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Views\HelloWorld\EmptyHTMLFile.html" />
  </ItemGroup>
</Project>
[/code]

**Comment by LeonhardPrintz** [comment]
It keeps taking the code I post and turn it into "netcoreapp2.2 Inprocess"
