### ISSUE TITLE
Unclear what routes variable means

### ISSUE THREAD

**Issue by yuriry** [aspnet/Docs#9570]
There are many examples that use routes.MapRoute without mentioning what the routes variable mean.  One can only guess from the Use Routing Middleware sample in the middle of the article that it is probably a RouteBuilder instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32374077-e02e-d6a6-1cea-05e58447b7cd
* Version Independent ID: 86aeab13-1c25-9fc1-4e56-0390cb40c242
* Content: [Routing in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/routing.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/routing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @yuriry ... We're working on this topic right now on #9527. I'll see what I can do to clarify it. That's correct, it's an [IRouteBuiler](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.routing.iroutebuilder).

**Comment by guardrex** [comment]
I checked ... either via the updates on the PR or the existing content, we have it covered ... 

> Most apps create routes by calling \<xref:Microsoft.AspNetCore.Builder.MapRouteRouteBuilderExtensions.MapRoute\*> or one of the similar extension methods defined on \<xref:Microsoft.AspNetCore.Routing.IRouteBuilder>. Any of the \`IRouteBuilder\` extension methods create an instance of \<xref:Microsoft.AspNetCore.Routing.Route> and add it to the route collection.

Leave this issue open. It will auto-close when the PR merges. Thanks again @yuriry! :rocket:
