### ISSUE TITLE
Update doc to replace @await Html.PartialAsync with Partial Tag Helper

### ISSUE THREAD

**Issue by chpong** [aspnet/Docs#9579]
The doc shows HTML helper but the code shows tag helper. Is there a preference between tag helper "&lt;partial name=..." and HTML helper "@await Html.PartialAsync ..."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117c950a-0bcb-d936-31cf-5859b4280abb
* Version Independent ID: 270bedc7-a636-5bd0-9e2f-e42235deec8c
* Content: [Enable QR Code generation for TOTP authenticator apps in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-enable-qrcodes?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/identity-enable-qrcodes.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-enable-qrcodes.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@chpong It's a matter of personal preference. Both approaches are fully supported. If you do use an HTML Helper, avoid the synchronous forms of it. Those forms are known to cause deadlocks. The `<partial />` Tag Helper renders asynchronously, as does `@Html.PartialAsync`.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Templating/issues/338 seems to indicate TH are preferred.

If you scaffold Identity, it uses both in the same file. Intellisense warns you not to use the HTML Helper

![image](https://user-images.githubusercontent.com/3605364/48452346-bf712d00-e752-11e8-841d-37cc9155acd8.png)

**Comment by Rick-Anderson** [comment]
The ASP.NET Core 2.2 template only use the partial TH, they don't use the partial HTML Helper.

**Comment by chpong** [comment]
@Rick-Anderson, thanks for reopened this as a doc fix which conveys the same preference as the ASP.NET Core 2.2 code!
