### ISSUE TITLE
How do we generate docs like you guys?

### ISSUE THREAD

**Issue by simonmurdock** [aspnet/Docs#958]
Is there a document somewhere explaining how to generate the API section of your docs.asp.net documents?

I see some stuff in this repo but it seems to be undocumented. I'm struggling to find a solution to generate my own docs that look good.

**Comment by danroth27** [comment]
@agjohnson @ericholscher We are using the [autoapi](https://github.com/rtfd/sphinx-autoapi) Sphinx extension to generate our API refs. The process is bit bumpy right now and requires several manual workarounds, but you can see what we currently do by looking at the https://github.com/aspnet/apidocs repo. We are working on a number of fixes with the Read the Docs folks which should improve things.
