### ISSUE TITLE
SameAuthorRequirement extension

### ISSUE THREAD

**Issue by Ponant** [aspnet/Docs#9584]
The class SameAuthorRequirement appears to be a placeholder. What would you typically put in this class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5234edfa-92bb-a0a4-c523-ad2d7823e865
* Version Independent ID: 89c82c33-8e4f-93dc-af2f-492350557a4b
* Content: [Resource-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-2.1&tabs=aspnetcore2x)
* Content Source: [aspnetcore/security/authorization/resourcebased.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/resourcebased.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by HaoK** [comment]
Nope, they are basically marker classes mostly

**Comment by HaoK** [comment]
But you can think of SameAuthor representing as a special case of a more generic SpecificAuthor requirement where the name of the author in the requirement is set to the current user

**Comment by scottaddie** [comment]
I'll try to make this clearer in the doc.
