### ISSUE TITLE
IsAuthenticated=false when using WsFed with identity

### ISSUE THREAD

**Issue by vikz747** [aspnet/Docs#9585]
# Issue description
IsAuthenticated=false when using WsFed with identity

# Software versions
- [ ] .NET Core 2.0

<details>
When using the flow mentioned here - https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-2.1#add-ws-federation-as-an-external-login-provider-for-aspnet-core-identity

and adding WsFed as an external login provider for Identity. The Request's "HttpContext.User.Identity.IsAuthenticated" is showing false even though the user has been successfully authenticated using Azure AD.

The same thing works fine though when using the "WS-fed without identity" example shown in the same article and also in the sample here - https://github.com/aspnet/Security/blob/master/samples/WsFedSample/Startup.cs

The only difference between both of them that I see is that cookie options have been set explicitly.But I couldn't get the "ws-fed WITH identity"case to work even with that.

Is this expected? Is there more info on this anywhere? When using Ws-Fed as an external login provider to identity do we expect the same "username" to be having a backing record in the db tables associated with identity? 

</details>

**Comment by guardrex** [comment]
@HaoK Should this be moved to aspnet/Home for triage?
