### ISSUE TITLE
[ASP.NET SignalR] Add docs on StackExchangeRedis package

### ISSUE THREAD

**Issue by anurse** [aspnet/Docs#9589]
We should update https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-with-redis to reference the new Microsoft.AspNet.SignalR.StackExchangeRedis package added in 2.4.0. It's mostly just a find-replace

cc @BrennanConroy

**Comment by Rick-Anderson** [comment]
@tdykstra 	is this something you could do?
