### ISSUE TITLE
Wildcard subdomain example not working

### ISSUE THREAD

**Issue by SvenLauterbach** [aspnet/Docs#9595]
The example:

```
options.AddPolicy("AllowSubdomain",
    builder =>
    {
        builder.SetIsOriginAllowedToAllowWildcardSubdomains("https://*.example.com");
    });
```
seems to be wrong. The link above the example (https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.cors.infrastructure.corspolicybuilder.setisoriginallowedtoallowwildcardsubdomains?view=aspnetcore-2.1) shows a method which does not accept a string parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bca5db-1196-2a8b-a0d8-4e89b2382288
* Version Independent ID: d3f332c4-4c60-039e-0e1e-bc6b11831f87
* Content: [Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-2.0#cors-policy-options)
* Content Source: [aspnetcore/security/cors.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/cors.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by kamiyn** [comment]
I also have the same problem.
It should be
    builder.WithOrigins("https://*.example.com")
                            .SetIsOriginAllowedToAllowWildcardSubdomains()

**Comment by savbace** [comment]
PR #9685 updates document with 
```csharp
builder.SetIsOriginAllowedToAllowWildcardSubdomains();
``` 
but I think that this code will not work as expected because method uses configured `policy.Origins` to match subdomains ([source](https://github.com/aspnet/AspNetCore/blob/5c6e1aa1d95bb79809c99736acb3b8abd36d08d4/src/Middleware/CORS/src/Infrastructure/CorsPolicyExtensions.cs#L22)).
I suppose that docs should contain example @kamiyn provided:
```csharp
builder.WithOrigins("https://*.example.com")
    .SetIsOriginAllowedToAllowWildcardSubdomains();
```
