### ISSUE TITLE
Behavior of WebHost.CreateDefaultBuilder() with regard to AddEnvironmentVariables and default prefix

### ISSUE THREAD

**Issue by penenkel** [aspnet/Docs#9597]
This article states that:

> AddEnvironmentVariables for environment variables prefixed with ASPNETCORE_ has already been called by CreateDefaultBuilder.

As far as I can tell `CreateDefaultBuilder` only ever calls `AddEnvironmentVariables` without any prefix. 
And looking at https://github.com/aspnet/MetaPackages/blame/2.1.2/src/Microsoft.AspNetCore/WebHost.cs it never has done so before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1#prefixes)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Great catch @penenkel! ... It should just say for the initialization of the `WebHostBuilder` at that spot in the text. I'll put quick patch in to fix it up.

https://github.com/aspnet/Hosting/blob/release/2.1/src/Microsoft.AspNetCore.Hosting/WebHostBuilder.cs#L46

**Comment by guardrex** [comment]
btw -- As I assess the language and get an update in ... this doesn't quite fall into the "bug" 🐞 category because calling `CreateDefaultBuilder` creates the `WebHostBuilder`. This is more of an enhancement to attempt greater specificity. I *think* I have some improved language. I'll ping u on the PR @penenkel in a second.
