### ISSUE TITLE
Only support android 8.0 or above?

### ISSUE THREAD

**Issue by cnkker** [aspnet/Docs#9604]
Only support android 8.0 or above?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e954a77-daa3-980c-0a0b-c4e7dabc8ed0
* Version Independent ID: 09e7b88b-8373-89d4-7360-d71370c095da
* Content: [ASP.NET Core SignalR Java client](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/java-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/java-client.md)
* Product: **aspnet-core**
* GitHub Login: @mikaelm12
* Microsoft Alias: **mimengis**

**Comment by BrennanConroy** [comment]
In the preview3 release we do, however we've got some updates once we RTM, you can see them [here](https://github.com/aspnet/Docs/blob/release/2.2.0/aspnetcore/signalr/java-client.md#android-development-notes).

**Comment by scottaddie** [comment]
This update has gone live.
