### ISSUE TITLE
Working problem

### ISSUE THREAD

**Issue by FaridGN** [aspnet/Docs#9613]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Get started with ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by FaridGN** [comment]
I followed the steps you provided, but it didn't work on my browsers when clicking on "Send Message". What would be the cause? did you forget to add extra configuration in tutorial?

**Comment by BrennanConroy** [comment]
We'll need some more info on what isn't working. We're adding a tip to help out in the tutorial, see https://github.com/aspnet/Docs/pull/9614/files

**Comment by FaridGN** [comment]
Hi again, sorry for late feedback.
Console doesn't show any error in my browser, and I tested all my browsers. And my signalR folder is in lib folder (wwwroot/lib/signalr).  But when installed package.json not via libman, it is working. I don't know why. Here is the code generated in package.json when worked:
{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "devDependencies": {
    "@aspnet/signalr": "1.0.3"
  }
}
and package-lock.json: 
{
  "name": "asp.net",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "@aspnet/signalr": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/@aspnet/signalr/-/signalr-1.0.3.tgz",
      "integrity": "sha512-8nPSarp4k+oP2M6P7tw2FZMXOMR86wH9GPb/4wiqA18c4Ds88SUmE0pSpnNQPDOoWGMj6y9F2Xz5JyoynCPXWQ==",
      "dev": true
    }
  }
}
But this way is little bit long method, the one you showed seems better, but not working.

**Comment by Rick-Anderson** [comment]
@FaridGN 	we've got alot of customers reporting success on this tutorial. I got it working myself. Can you try again and do some debugging?
