### ISSUE TITLE
Document support for Razor templates

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9618]
Copy from #9583 by @danroth27 	

Update the Razor Syntax doc to document Razor template syntax. For details see https://github.com/aspnet/Blazor/pull/1360#issue-210880744.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87067b2-347c-072d-26c8-5a8c7c9c860b
* Version Independent ID: a0b3b70a-3b39-1b5f-a4ce-c41bd2d6b044
* Content: [Razor syntax reference for ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/views/razor.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/razor.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@danroth27 It's a 2.2 scenario?

**Comment by danroth27** [comment]
I think the support for Razor template syntax (i.e. `Action<object> template = @<p>The value is @item.ToString()</p>;`) has been there forever. We just never documented it.

**Comment by guardrex** [comment]
@danroth27 Hacking around isn't producing good results, and I don't see much on the Net. Can you provide a more complete example? Something simple that I thought might work is fighting me ...

```cshtml
@{
    Action<Pet> petTemplate = (pet) => @<p>You have a pet named @pet.Name.</p>;
    
    var pets = new List<Pet>
    {
        new Pet { Name = "Rin Tin Tin" },
        new Pet { Name = "Mr. Bigglesworth" },
        new Pet { Name = "K-9" }
    };
}

@pets.ForEach(petTemplate);
```
