### ISSUE TITLE
Magical Data Binding

### ISSUE THREAD

**Issue by Mimisss** [aspnet/Docs#9627]
Hello. I've followed this part of the tutorial a couple of times very carefully. Also, I've read other's questions about the filtering not working. I'm not sure if and how much this document has changed over time but at the time of this writing, the following fixes have to be made in order to have searching both by title and genre work:

1. Remove the following redundant line:
`SearchString = searchString;`
I don't know why the above code is still in the document's example. As far as I can tell, ASP.NET will **automatically** bind the `searchString` parameter to the `SearchString` property of the model. In fact, the same *magical* binding happens with the `movieGenre` parameter and the `MovieGenre` property, which is then properly bound to the `select` element of the web page. Also, the paragraph about this line of code being necessary in order to have the search value retained in the search box after the search is executed should be deleted. 

2. Based on the above comment, the following HTML line:
`<input type="text" name="SearchString">`
should be replaced by:
`<input type="text" asp-for="SearchString"/>`

By applying the these two changes, both searching by title and by genre work as expected and the controls retain their values after search is executed.

I'm not sure what the source of this confusion is and why it takes so damn long to fix the documentation. Maybe the Core implementation changes all the time. Maybe the Core documentation is in some sort of beta. But having people confused over such a basic matter is far from ideal. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Mimisss 	 great suggestions. I'll be updating this doc next week and I'll add these changes. Thanks for the feedback.
