### ISSUE TITLE
Localization.StarterWeb example in 'Set The Culture Programmatically' missing a step

### ISSUE THREAD

**Issue by Issafalcon** [aspnet/Docs#9628]
It took me a while to figure out why, but when following the example code for setting the culture programmatically, it never picks up the IRequestCultureFeature from the Context.Features.Get&lt;IRequestCultureFeature&gt;(). The sample code is missing app.UseRequestLocalization(); to enable this to work. Would be worth adding to avoid some of the confusion I faced coming to this topic for the first time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1833676-ff1b-c587-cc9c-81afffa8ef68
* Version Independent ID: ad989395-3f49-4d55-521e-cf6fe56281ee
* Content: [Globalization and localization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-2.1#resource-files)
* Content Source: [aspnetcore/fundamentals/localization.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/localization.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@hishamco please review.

**Comment by hishamco** [comment]
@Issafalcon if you mean Localization.StarterWeb that is available in the [entropy repo](https://github.com/aspnet/Entropy) the `app.UseRequestLocalization()` is already there at this line  https://github.com/aspnet/Entropy/blob/master/samples/Localization.StarterWeb/Startup.cs#L109?!! furthermore you can have a look to my [LanguageSwitcherTagHelper](https://github.com/hishamco/LanguageSwitcherTagHelper) which showing the same use case for switching & setting the languages

**Comment by Issafalcon** [comment]
@hishamco - I do apologise. You're right, the entropy repo shows the code. And indeed, the doc shows the UseRequestLocalization further up the page. Thank you for taking the time to respond. Next time I'll spend more time looking at the rest of the docs / sample code rather than focusing in on just one part of them!

**Comment by hishamco** [comment]
You're welcome, any be free to ask anytime

**Comment by hishamco** [comment]
@Rick-Anderson I think we need to close this, because there's no further action needed here
