### ISSUE TITLE
Changes in NSwag v12

### ISSUE THREAD

**Issue by MadKonst** [aspnet/Docs#9631]
Hi, There are some breaking changes in NSwag v12.
Many methods were marked as obsolete.
https://github.com/RSuter/NSwag/releases

Basic setup to make it work now looks like that:

// in ConfigureServices()

services.AddSwaggerDocument(
    configure =>
    {
        configure.PostProcess = (document) =>
        {
            document.Info.Version = "v1";
            document.Info.Title = "My API";
            document.Info.Description = "ASP.NET Core Web API";
        };
    });

// in Configure()

app.UseSwagger();
app.UseSwaggerUi3();

UPDATE Code above is updated as per suggestion from @RSuter 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2483813a-3c16-7ddd-3160-43e6843b55d4
* Version Independent ID: 25f7fb5b-92b0-a45b-57ab-fdceab571884
* Content: [Get started with NSwag and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)
* Content Source: [aspnetcore/tutorials/getting-started-with-NSwag.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-NSwag.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by sebainones** [comment]
The same for me. It works like charm. 
Thanks a lot for sharing that as I couldn't figure out where or how to use "AddSwaggerDocument();" as  the inline documentation stated because it didn't explain that it was from "Services".
Many thanks.

**Comment by RSuter** [comment]
Hi everyone, I'm the develop or NSwag. I know that this tutorial needs to be updated. 

Please check out this wiki page: https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware

The PostProcess in UseSwagger should be only used to transform the document based on the request, nothing other because this post process is not called via CLI, please always use PostProcess in AddSwaggerDocument() if possible: 

```
// in ConfigureServices()

services.AddSwaggerDocument(
configure =>
{
configure.PostProcess = (document) =>
{
document.Info.Version = "v1";
document.Info.Title = "My API";
document.Info.Description = "ASP.NET Core Web API";
};
})

// in Configure()

app.UseSwagger();
app.UseSwaggerUi3();
```

/cc @MadKonst Can you please try this and update your OP?

**Comment by Rick-Anderson** [comment]
@scottaddie 	can you fix?

**Comment by LiangLNZ** [comment]
Hi @RSuter 

The example of Enable OAuth2 authorization in the following link, doesn't work.
https://github.com/RSuter/NSwag/wiki/AspNetCore-Middleware

document.OAuth2Client - doesn't have this property. I am using V12.0.4

app.AddOpenApiDocument(document =>
{
    **document.OAuth2Client** = new OAuth2ClientSettings
    {
        
    };
}

How to enable OAuth2 authorization in the latest version?

Thanks
Lei

**Comment by RSuter** [comment]
@LiangLNZ this config is in UseSwaggerUi3 - I've updated the wiki (it was wrong). 

But we might have a problem with auth in Swagger UI 3, please report if this is also a problem for you: https://github.com/RSuter/NSwag/issues/1304

**Comment by daveabrock** [comment]
Hey, @scottaddie, want me to take this?

**Comment by scottaddie** [comment]
@daveabrock Yes, please.

**Comment by RSuter** [comment]
“NSwag.CodeGeneration.CSharp” is the nuget package which contains the SwaggerToCsharpClientGenerator class

**Comment by daveabrock** [comment]
I am wondering why I am unable to find `AddSwaggerDocument` in 2.2. Shouldn't including `NSwag.AspNetCore` be enough?

**Comment by RSuter** [comment]
Works for me: 

![image](https://user-images.githubusercontent.com/2603405/50489709-6101c480-0a09-11e9-924f-4835512f8477.png)

**Comment by daveabrock** [comment]
When I added the package from the Package Manager Console, it looks like it installed `11.0.9`. I did a manual update to 12, and of course it works.

And @RSuter, thanks for the warnings about deprecated functions. I'll use those to clean up more code examples.
