### ISSUE TITLE
Perf benefits defination

### ISSUE THREAD

**Issue by paul000** [aspnet/Docs#9633]
Advantages of:
FindAsync
In much of the scaffolded code, FindAsync can be used in place of FirstOrDefaultAsync.

One of the advantages is -
Can have perf benefits in some situations, but that rarely happens for typical web apps.

What are perf benefits?

Paul

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Razor Pages with EF Core in ASP.NET Core - CRUD - 2 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-2.1)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Just better performance, but that rarely happens for typical web apps.
