### ISSUE TITLE
Documentation overview doesn't match navigation on the left side

### ISSUE THREAD

**Issue by boppbo** [aspnet/Docs#9637]
see title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d39ecf-0465-afd3-2384-aaafe9e8ea79
* Version Independent ID: e9a58581-b565-25eb-49b3-4c93714f0940
* Content: [Overview of ASP.NET Core Security](https://docs.microsoft.com/en-us/aspnet/core/security/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@boppbo Thanks for pointing that out.  We reorganized the Table of Contents not long ago and intended to eliminate all of these instances of duplicate lists of links (in the doc vs. in the left nav), and we missed this one.  I'll remove the links from the doc.
