### ISSUE TITLE
Redirection to the log-in page after successful log-in

### ISSUE THREAD

**Issue by sheikh-nouman** [aspnet/Docs#9638]
I am using this sample as is but it fails to redirect to the contact page after authentication.

Downloaded the sample, ran and opened Contact info page.
It directs me to the log-in page and as I enter the credentials and press enter it opens the log-in page again. 

I debugged and verified if it logged-in or not. It did, it authenticated user principal with it's claims but is redirected again to the log-in page.
I am using:
VS 2017
Asp.net core 2.1
Razor pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2229fc6-f8c8-952e-e567-b1d5a463055a
* Version Independent ID: b18a015b-914d-f014-f711-120d208904d9
* Content: [Use cookie authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1)
* Content Source: [aspnetcore/security/authentication/cookie.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/cookie.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @sheikh-nouman ... The last time I worked on this topic, the sample worked. I'll take a look now and get back to you. Sometimes the framework changes and a sample will flake out. Stand-by ... I'll get back to you shortly.

**Comment by guardrex** [comment]
@sheikh-nouman I'm not able to repro that here ... I went to the Contact page, was redirected to the login, logged in, and was redirected to the Contact page. It seems ok here ...

<img width="182" alt="capture" src="https://user-images.githubusercontent.com/1622880/49115240-e30e9a00-f25f-11e8-97b4-ca63c56243f7.PNG">

Seems ok. Did you use the login username of `maria.rodriguez@contoso.com` with any password?

**Comment by umair-me** [comment]
Hello, I am also having the same issue, downloaded the project, run it entered correct email but the page redirects to login back again as if the user. Can this be checked please?

**Comment by guardrex** [comment]
Hello @umair-me ... please open a new issue for this topic using the **Content feedback** button at the bottom of the topic. You can reference this issue by mentioning `#9638` in the opening comment.
