### ISSUE TITLE
Split the areas in different projects

### ISSUE THREAD

**Issue by AdrienTorris** [aspnet/Docs#9646]
Is it possible to configure your project to split the different areas into different projects?

The objective is to do something like this:
   - Cms.Web (ASP.NET Core web app, contains no views and no controllers)
   - Cms.Security (.NET Standard project, considered like the "Security" area of the Cms.Web web app)
   - Cms.Admin (.NET Standard project, considered like the "Administration" area of the Cms.Web web app)
and so on...

Is it possible to configure ASP.NET Core to do this?

I tried different things like overriding the rules of RazorViewEngine or implement a custom RazorViewEngine but nothing worked. I can call the controllers of the deported areas, the actions are executed but the views are still searched in the web app project, into areas subfolders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50249794-b4be-a6aa-d7b3-b3918eb282bf
* Version Independent ID: 39d98269-a7dc-017f-55cd-bd33df097368
* Content: [Areas in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1)
* Content Source: [aspnetcore/mvc/controllers/areas.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/controllers/areas.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@AdrienTorris Have you tried using Razor Class Libraries? Read more here: https://docs.microsoft.com/aspnet/core/razor-pages/ui-class

**Comment by AdrienTorris** [comment]
@scottaddie No I didn't try. I tried a lot of things today, like abstract myself the ASP.NET Core router, the razor view engine and other stuff but my code is very complicated now for a very few features, and still not working like I want. I'll check the Razor Class Libraries, thank's.

**Comment by treefishuk** [comment]
I’m working on a project at the moment to do just that :  https://github.com/treefishuk/nomoni it’s very early days but it may give you some inspiration. It’s based off extcore which may also suit your needs.

**Comment by AdrienTorris** [comment]
@scottaddie I couldn't wait I had to check the Razor Class Libraries. It still not working with the views but it works with the pages, it's a way more efficient than the result of my last two days of code, thank's you! I'll keep digging, starting with the documentation, to see if the Razor Class Libraries could work with the controller/views.
![razor-class-library-sample-screenshot](https://user-images.githubusercontent.com/1014357/48856164-fdef9300-edb5-11e8-9786-32974d3aec47.png)

**Comment by AdrienTorris** [comment]
@treefishuk I'll check, thank you.

**Comment by AdrienTorris** [comment]
@scottaddie For now the Razor Class Libraries are matching my needs, thank you very much.

**Comment by scottaddie** [comment]
@AdrienTorris That's great to hear. Thank you for following up.
