### ISSUE TITLE
strongly typed Hub

### ISSUE THREAD

**Issue by f2calv** [aspnet/Docs#9647]
Is this comment still valid?
"Using a strongly typed Hub&lt;T&gt; disables the ability to use SendAsync."
As I'm using async throughout without any issue...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1387f556-b4b7-70f9-5bd0-f0bccc597689
* Version Independent ID: fb016cdc-d281-6b5b-7466-2c718e7274b4
* Content: [Use hubs in ASP.NET Core SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.1)
* Content Source: [aspnetcore/signalr/hubs.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/hubs.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by scottaddie** [comment]
I can confirm that I'm unable to use `SendAsync` with a strongly typed Hub. @anurse Is there something I'm unaware of?

**Comment by f2calv** [comment]
OK understood, so yes I'm using a strongly-typed hub and then calling those methods asynchronously - which I figured was effectively calling SendAsync under the hood.

Maybe...

"Using a strongly typed Hub<T> disables the ability to directly use SendAsync, however any interface-defined methods will be async-capable." ?

**Comment by anurse** [comment]
That seems like a reasonable change :). Interested in making a Pull Request?

**Comment by scottaddie** [comment]
I'll take care of this one, since I'm already in the doc.
