### ISSUE TITLE
.net core WS-Federation Claims always empty

### ISSUE THREAD

**Issue by MSAppsDev** [aspnet/Docs#9649]
My .net core api is calling on-Prem ADFS (WS-Federation sign-in protocol) for authentication but context.User is always null after successful login. Below is my Startup.cs
ConfigureServices()
{
services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
            })
            .AddWsFederation(options =>
            {
                options.Wtrealm = Configuration["wsfed:realm"];
                options.MetadataAddress = Configuration["wsfed:metadata"];
                options.SkipUnrecognizedRequests = true;
                options.RequireHttpsMetadata = false;
            })
            .AddCookie();
}

Configure()
{
app.UseStaticFiles();
            app.UseSpaStaticFiles();
            app.UseAuthentication();

            app.Use(async (context, next) =>
            {
                var user = context.User;
                if (user == null || !user.Identities.Any(identity => identity.IsAuthenticated))
                {
                    await context.ChallengeAsync(WsFederationDefaults.AuthenticationScheme);
                    return;
                }
                else
                {
                    await next();
                }
            });
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Index}/{id?}");
            });
}

I see that IDP is redirecting to my api and returning wresult with the token value but when i try to access context.User, it is null.

Any pointers on whats wrong here?

**Comment by guardrex** [comment]
Hello @MSAppsDev ... We can't troubleshoot implementation/framework issues here on the documentation repo ... only doc issues. Could you move this over to [aspnet/Home issues](https://github.com/aspnet/AspNetCore/issues)? If there's an underlying doc issue, then we would like to hear about that here. We can re-open this issue if there's a doc issue to address.

btw- There's a **Content feedback** button at the bottom of each topic that will tag the issue with the document details. It's easier for us to track the work that way. The content for this issue would be for the https://docs.microsoft.com/aspnet/core/security/authentication/ws-federation topic.
