### ISSUE TITLE
[razor-page overview] can't have Query String in HTTP POST request method

### ISSUE THREAD

**Issue by JulioJu** [aspnet/Docs#9650]
### Feedback

Under https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=netcore-cli#multiple-handlers-per-page, maybe the following sentence is false:

*"Using the preceding code, the URL path that submits to OnPostJoinListAsync is http://localhost:5000/Customers/CreateFATH?handler=JoinList. The URL path that submits to OnPostJoinListUCAsync is http://localhost:5000/Customers/CreateFATH?handler=JoinListUC."*

In fact, as this sentence says, it's a HTTP POST request method and not a HTTP GET request method. Therefore, data are not sent by the query strings `?handler=JoinList` or `?handler=JoinListUC`, but in POST. And as https://en.wikipedia.org/wiki/POST_(HTTP) says, query strings are for HTTP GET request method and not for HTTP POST request method. We can't meld HTTP POST and HTTP GET request methods. 

Furthermore, I've tested the example, and we can't see this URL with this query string in the URL bar.

Probably, there is something that I don't understand, sorry.

Tanks in advance for your answer :-). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 164d7efe-01bf-0b26-7a23-f10704f338f5
* Version Independent ID: b3e2bc87-1582-2d34-c7c2-7c8e901ac771
* Content: [Introduction to Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/?view=aspnetcore-2.1&tabs=netcore-cli)
* Content Source: [aspnetcore/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JulioJu the doc is correct. It's the handler sent in the query string, not data.

**Comment by Rick-Anderson** [comment]
@JulioJu 	keep reading. To move the handler from a query string to a route segment:

You can change the query string `?handler=JoinList` in the URL to a route segment `/JoinList` by specifying the route template `@page "{handler?}"`.

If you don't like the query string `?handler=JoinList` in the URL, you can change the route to put the handler name in the path portion of the URL. You can customize the route by adding a route template enclosed in double quotes after the `@page` directive.
