### ISSUE TITLE
Emphasize IOptionsMonitor as the recommended choice

### ISSUE THREAD

**Issue by HaoK** [aspnet/Docs#9662]
@DamianEdwards brought up a good point recently that our options docs don't make it clear enough that `IOptionsMonitor` is the recommended choice going forward, since its effectively everything IOptions is but more...

@guardrex can you help me add this guidance?

I think maybe we just add a section that says something like this:

## Which options interface to use?

`IOptionsMonitor` is generally recommended as the interface to use because it supports everything `IOptions` does, in addition to supporting named options, reloadable configuration, change notifications, as well as the ability to selectively invalidate instances via the `IOptionsMonitorCache`.  (Note: these should be links to appropriate doc sections)

`IOptionsSnapshot` is a good alternative for scenarios where options should be recomputed on every request.

`IOptions` is really the only choice when using existing frameworks/libraries that are already using `IOptions`

**Comment by guardrex** [comment]
@HaoK `IOptions` is the featured interface in the text and sample app for:

* Simple options access
* Set simple options with a delegate
* Suboptions

```csharp
IOptions<MyOptions> optionsAccessor, 
IOptions<MyOptionsWithDelegateConfig> optionsAccessorWithDelegateConfig, 
IOptions<MySubOptions> subOptionsAccessor, 
```

Should I refactor these scenarios to use `IOptionsMonitor` and move `IOptionsMonitor` coverage to the top of the topic along with the section you suggest?

**Comment by HaoK** [comment]
Yeah I guess so, it doesn't really matter which interface is used for those examples
