### ISSUE TITLE
"Publish with CLI tools" redirects to tutorial on how to use Visual Studio for publishing

### ISSUE THREAD

**Issue by henrikrxn** [aspnet/Docs#9668]
The "Publish with CLI tools" sub-section redirects to https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet?view=aspnetcore-2.1 which is all about using Visual Studio and there is not  even a single use of the CLI

Please provide an explanation of how to use CLI together with the publishing profile XML files generated by Visual Studio. If this is a no-go then explain how to map the .pubxml file to CLI arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2eab542-a420-d6c5-d314-a420837cf602
* Version Independent ID: 48c12168-54f3-0b83-f136-565f483a03e9
* Content: [Deploy ASP.NET Core apps to Azure App Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/azure-apps/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/azure-apps/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
I believe what happened is that the target changed and the link wasn't updated. The target **_used to have_** those instructions.

This is probably what ur looking for ...

https://docs.microsoft.com/aspnet/core/host-and-deploy/visual-studio-publish-profiles#publish-profiles

For example from the topic ...

```console
dotnet publish WebApplication.csproj /p:PublishProfile=<FolderProfileName>
```

I'll get this squared away ASAP ... thanks for reporting it.

**Comment by henrikrxn** [comment]
@guardrex Thank you for a very quick and very, very helpful reply

**Comment by guardrex** [comment]
Sure thing ... sorry that link was busted. I'll have it patched up in a few minutes.
