### ISSUE TITLE
Section 3, Sorting and paging issue with HasPreviousPage, HasNextPage and PageIndex

### ISSUE THREAD

**Issue by stephenmorton** [aspnet/Docs#9674]
Hi guys,

Having an issue here section 3, paging.
When I add the paging code to index.cshtml, I get errors around HasPReviousPage, HasNextPage and PageIndex, app crashed on Student page.
One of the 8 errors I am getting in relation to these functions are:
"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IList<Student>' does not contain a definition for 'HasPreviousPage' and no accessible extension method 'HasPreviousPage' accepting a first argument of type 'IList<Student>' could be found (are you missing a using directive or an assembly reference?)	ContosoUniversity	C:\Users\sgm25\Documents\Development\ASPNET\ContosoUniversity\ContosoUniversity\Pages\Students\Index.cshtml	69	Active"
I can see these functions in the PagenatedList.cs file, but not working here. I have tried updating from the github code, but still have this issue. Any ideas? Thanks in advance.

**Comment by FloorVermaat** [comment]
Have you defined the model as an PaginatedList? Like this: `@model PaginatedList<Product>;` Look at this tutorial: [](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1)

**Comment by stephenmorton** [comment]
Hi Floor,

Thanks so much, I see now. Totally missed that bit in the doc. Updated and all good now. Thanks so much.

Regards,

Stephen G Morton
Total Telco Group Pty Ltd
P 1300 484 511 | D 02 8488 3151 | M 0418 111 068
