### ISSUE TITLE
Update different as scaffolded controller

### ISSUE THREAD

**Issue by boppbo** [aspnet/Docs#9675]
Scaffolded entity framework api controller generates another put body as described her in update. Which solution is better? In the non-error case the scaffolded code should only cause one db query.(I inlined TodoItemExists for clarity)

```
{
	if (id != item.Id)
	{
		return BadRequest();
	}

	_context.Entry(item).State = EntityState.Modified;

	try
	{
		await _context.SaveChangesAsync();
	}
	catch (DbUpdateConcurrencyException)
	{
		if (!_context.TodoItems.Any(e => e.Id == id))
		{
			return NotFound();
		}
		else
		{
			throw;
		}
	}

	return NoContent();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Create a Web API with ASP.NET Core and Visual Studio](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification&view=aspnetcore-2.1#lf-content=177016560:743571877&reply_editor=true)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The scaffolded code looks better than the code in the tutorial, which is:

```
[HttpPut("{id}")]
public IActionResult Update(long id, TodoItem item)
{
    var todo = _context.TodoItems.Find(id);
    if (todo == null)
    {
        return NotFound();
    }

    todo.IsComplete = item.IsComplete;
    todo.Name = item.Name;

    _context.TodoItems.Update(todo);
    _context.SaveChanges();
    return NoContent();
}
```
