### ISSUE TITLE
RP-EF Core tutorial sequence conflict

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9680]
From @stephenmorton ... *Moved from https://github.com/aspnet/Docs/issues/9672#issuecomment-441140541*

&gt; Towards the bottom in the section Testing the app
&gt;
&gt; Run the app and accept the cookie policy. This app doesn't keep personal information. You can read about the cookie policy at EU General Data Protection Regulation (GDPR) support.
&gt;
&gt; Select the Students link and then Create New.
&gt; Test the Edit, Details, and Delete links.
&gt;
&gt; On closer inspection, it doesn't actually say to add a student, but does suggest testing the add/del/details links, prior to initialising, so only way to test would be to try adding a student (In my view, it inferrs adding a student).
&gt; Then lates down, prior to initializing the DB with the test data, it says to remove any students you created. 

https://docs.microsoft.com/aspnet/core/data/ef-rp/intro#test-the-app

This samp is also a candidate for the new seeding approach: https://github.com/aspnet/Docs/issues/9205

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#test-the-app)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Won't fix.
Create new is close enough.
