### ISSUE TITLE
update "Sharing cookies between applications"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#969]
https://docs.asp.net/en/latest/security/data-protection/compatibility/cookie-sharing.html

Needs update.

**Comment by jonaslundgren** [comment]
I just had problems were I realized that the ticket format in the referenced sample code (https://github.com/GrabYourPitchforks/aspnet5-samples/tree/dev/CookieSharing) was out of date compared to RC1. There is a compatble package at https://www.nuget.org/packages/Microsoft.Owin.Security.Cookies.Interop/ . The doc should obviously mention this.
