### ISSUE TITLE
Correct Workflow for EnsureCreated() method 

### ISSUE THREAD

**Issue by krchome** [aspnet/Docs#9692]
Hi,
I found that there is one point missing in the documentation regarding EnsureCreated() method allowing the following workflow and the correct sequence observed is:

EnsureCreated is called on app start, which allows the following work flow:

Delete the DB.
Change the DB schema (for example, add an EmailAddress field).
Delete the scaffolded files for Create, Delete, Edit etc.  and Re-scaffold them in the Students folder (This step must be executed to regenerate the DB schema correctly)
Run the app.
EnsureCreated creates a DB with the EmailAddress column.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
> and Re-scaffold them in the Students folder (This step must be executed to regenerate the DB schema correctly)

Scaffolding doesn't generate the DB Schema. Ensure created does.  cc @tdykstra

**Comment by Rick-Anderson** [comment]
DB create by EF has nothing to do with scaffolding.
