### ISSUE TITLE
Unit Test Logging behavior

### ISSUE THREAD

**Issue by mdarefull** [aspnet/Docs#9697]
Let's assume I have an action method to retrieve a product by id. If the requested product does not exist on my repository my action method return 404 but I also want it to log a warning message.
During testing, I'd like to assert that, if the repository returns null, the action method not only returns 404, but also logs a warning message.
Because Log* methods are extension methods, I cannot replace them for testing nor I cannot assert they are being invoked at the expected moment with the appropriate parameters.
Can you include, as part of the documentation, the recommended strategy to unit test logging behaviors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
@JunTaoLuo @javiercn

**Comment by javiercn** [comment]
@mdarefull Thanks for contacting us.

> Because Log* methods are extension methods, I cannot replace them for testing nor I cannot assert they are being invoked at the expected moment with the appropriate parameters.

There is not a good way to do this, the only thing you can do is register your own test login provider to capture the log messages and then check that in your tests. So a possible test could be to produce the log messages for a given request/response and compare them against a known baseline.

I would say though, that all these tests would be very brittle IMO.

**Comment by mdarefull** [comment]
@javiercn Thank you for your feedback. That's why I'm asking to add a 'recommended way' as part of the documentations just as with other topics.
This is an issue that every developer will come through and having a 'recommended solution' centralized here will be really helpful, IMO.

The workaround we've found, which is not invasive and very simple, IMO, is to create an extension method to `Mock<ILogger>` (we are using Moq) that basically receives the expected message and the log level:
![image](https://user-images.githubusercontent.com/22510674/49109959-1cdca200-f25a-11e8-9a4f-03fe90cbae73.png)
**Usage:**
![image](https://user-images.githubusercontent.com/22510674/49109980-30880880-f25a-11e8-8379-b5243b78e68e.png)

**Comment by javiercn** [comment]
I would not use Moq in this scenario.
I would simply implement a TestLogger, collect the messages on a list and compare against a list of messages you expect after calling a method on your app. It requires a bit more work upfront but your tests will be way more straightforward and easier to write and read.

In general though, I would be careful about writing tests verifying logging, as they are expensive to write and maintain compared to the value that they add. I would only do so for cases where It's a business requirement to log the information.
