### ISSUE TITLE
 mvc/views/mobile.rst Building Mobile Specific Views Building Mobile Specific Views

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#97]
ASP.NET MVC -> Mobile -> Building Mobile Specific Views

**Comment by NBelham** [comment]
Would welcome any drafts on this topic as we have a need to develop a few mobile device specific site pages... http://docs.asp.net/en/latest/mvc/views/mobile.html

**Comment by wangkanai** [comment]
Any progress on building mobile specifics views documentation?

**Comment by wangkanai** [comment]
Does the feature exist in 1.0.0 yet? or just the document have not finished? Thanks

**Comment by danroth27** [comment]
There currently isn't any support in ASP.NET Core for detecting mobile browsers. We should probably remove this topic stub from the ASP.NET Core 1.0 docs since this feature really isn't available in 1.0.

See also  aspnet/Razor#751 for further discussions.

**Comment by danroth27** [comment]
https://github.com/aspnet/Docs/issues/1815
