### ISSUE TITLE
Enhance Windows EventLog provider coverage

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9701]
Testing now for updates with Windows Services projects on https://github.com/aspnet/Docs/pull/9667, and I don't feel that we have good coverage for logging with the Event Log provider. For example, wiring up the provider shoots logging messages into the Application log, but any scenario that uses this provider would be much more beneficial if a dedicated log were created for the app to isolate the logging messages and make them easy to consume/sort/filter. The topic may only require some existing-topic crosslinks, but enhancements that explain out implementing a custom Event Log are also on the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#built-in-logging-providers)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Is this different from #7384?

**Comment by guardrex** [comment]
Yep!
