### ISSUE TITLE
YouTube version of this part

### ISSUE THREAD

**Issue by krchome** [aspnet/Docs#9702]
Available with common creative license :
https://www.youtube.com/watch?v=P7iTtQnkrNs&feature=youtu.be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a54c97f-ddd4-b041-5e5f-a2df009ace50
* Version Independent ID: fa488196-1f98-08ea-adcc-17d9dac86727
* Content: [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial 1 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio#view-the-db)
* Content Source: [aspnetcore/data/ef-rp/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@krchome can you look at [this list of youtube issues](https://github.com/aspnet/Docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc++youtube+in%3Atitle) 

* Make sure each issue you create has the following text "If you find this video helpful, leave a comment or 👍". For example, see #9608
* Find the issues I created pointing to your video's. You need to create an issue for those so I can close my issue. You need to be the author of issues pointing to your videos.
* I think customers love your videos. I'd like to get some feedback/metrics on that. For example, see #9766
