### ISSUE TITLE
"Appending the warning codes to $(NoWarn); applies the C# default values too."

### ISSUE THREAD

**Issue by connorads** [aspnet/Docs#9708]
> Appending the warning codes to `$(NoWarn);` applies the C# default values too.

I found this quite interesting, nice nugget of information.
It seems like a reasonable thing to add into my projects.
But I cannot seem to find any information elsewhere about
1. The use of `$(NoWarn)`
2. What the "default C# NoWarn values" are

Can anyone clarify, perhaps add some links to the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fce65f-1337-58cb-2193-8d8e0e62792d
* Version Independent ID: 59222460-a971-e76e-4fe9-23d4d7d768ee
* Content: [Get started with Swashbuckle and ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/getting-started-with-swashbuckle.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/getting-started-with-swashbuckle.md)
* Product: **aspnet-core**
* GitHub Login: @zuckerthoben
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
@rpetrusha can you suggest a link?

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by connorads** [comment]
Hi @Rick-Anderson
I can't seem to reopen the issue so I'll add a comment here.

Thanks for the link @rpetrusha but I don't think that page has any information about
1. The use of `$(NoWarn)`
2. What the "default C# NoWarn values" are

These are the two specific things I would like some more information about.

Perhaps I should have included a bit more information from the page to explain exactly what I mean.

If you take a look at the [Swashbuckle docs page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio#xml-comments) (that I created this issue from) it has an example about adding `$(NoWarn)` to the `<NoWarn>` options in the csproj and states:

> To suppress warnings project-wide, define a semicolon-delimited list of warning codes to ignore in the project file. Appending the warning codes to $(NoWarn); applies the C# default values too.

```
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <NoWarn>$(NoWarn);1591</NoWarn>
</PropertyGroup>
```

Any ideas?

**Comment by Rick-Anderson** [comment]
cc @scottaddie

**Comment by marcominas** [comment]
Hi @connorads, I think that you may like to see this link that contains a list of c# compile errors:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0006

Hope this helps you.

**Comment by connorads** [comment]
Hi @marcominas, thanks for the suggestion but there doesn't seem to be anything on [that link](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0006), or in the [C# Compiler Errors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) section of the docs, about the two specific things I mentioned _(1. & 2.)_ .... unless I have really got my wires crossed and/or something fairly obvious or apparent is evading me!

If you take a look at the [Swashbuckle docs page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio#xml-comments) (that I created this issue from) it has an example about adding `$(NoWarn)` to the `<NoWarn>` options in the csproj and states:

> To suppress warnings project-wide, define a semicolon-delimited list of warning codes to ignore in the project file. Appending the warning codes to $(NoWarn); applies the C# default values too.

```
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <NoWarn>$(NoWarn);1591</NoWarn>
</PropertyGroup>
```

**The key bits of information are:**
```
<NoWarn>$(NoWarn);1591</NoWarn>
```
> Appending the warning codes to $(NoWarn); applies the C# default values too.

For me this raises further questions that don't seem to be explained in the [Swashbuckle docs page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio#xml-comments), elsewhere in the Microsoft docs, or on the interwebs.

1. How/why/where/when to use `$(NoWarn)`? I'm not talking about the general use of _NoWarn_, _No Warn_, `-nowarn`, `/nowarn` etc. I mean specifically this `$(NoWarn)` with the the dollar sign and the brackets ([property element?](https://docs.microsoft.com/en-gb/visualstudio/msbuild/property-element-msbuild?view=vs-2017))
2. What are the aforementioned "default C# NoWarn values"? Which according to the [Swashbuckle docs page](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio#xml-comments) are being applied when you add `$(NoWarn)` to the `<NoWarn>` section of the `.csproj`.

**Comment by scottaddie** [comment]
The default values are here: https://github.com/dotnet/sdk/blob/2eb6c546931b5bcb92cd3128b93932a980553ea1/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L16

I'll get this added to the doc.

**Comment by scottaddie** [comment]
@BillWagner Anything you want to add to the C# docs regarding NoWarn?

**Comment by BillWagner** [comment]
@scottaddie Over time, what I want to add is to provide links from each C# option (like `-nowarn`) to the corresponding MS Build docs. Not all the options are documented, which is much of the underlying concern.

**Comment by connorads** [comment]
Thanks @scottaddie and everyone for your help 👌

**Comment by stephen-stasa-drivecentric** [comment]
> What happens when you add $(NoWarn) to the <NoWarn> options in the csproj?

Took me a while to realize this so I'll share here: `$(NoWarn)` is just an [MSBuild Property](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022) and this is doing string interpolation (`<NoWarn>$(NoWarn);NU1507</NoWarn>` -> `NoWarn = NoWarn + ";NU1507"`). By prepending `$(NoWarn)` to this definition, you're appending to the exiting list. If you didn't include `$(NoWarn)`, you would override the existing list. 

I think it's also worth noting that this can contain more than just he default values too.  For example, Directory.Build.props can add values to `NoWarn` in every project in a directory. Project files can then contain additional NoWarn codes. If the project's `<NoWarn>` did not have `$(NoWarn)`, then the warnings listed in Directory.Build.props would also be lost. 

You can use pre and post build events to see the values 
![image](https://github.com/dotnet/AspNetCore.Docs/assets/126491700/ca1f4079-0eeb-48bf-b713-431f700d2fbd)
Outputs:
```
NoWarn PreBuild: ;NU1507;NU1506;NU1507;NU1507
...
NoWarn PostBuild: ;NU1507;NU1506;NU1507;NU1507;1701;1702;2008
```
