### ISSUE TITLE
Not enough detail.

### ISSUE THREAD

**Issue by kellyelton** [aspnet/Docs#9709]
What is the lifetime of `HttpContextAccessor`? In the example above UserRepository is `Transient`. What if I create a class that's a `Singleton`, will this still correctly resolve the `HttpContext` for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fc35621-ae53-cfb5-5eb1-07aefdc5342f
* Version Independent ID: 79cb05f8-9ac0-26a8-8434-15de071160c3
* Content: [Access HttpContext in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/http-context.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/http-context.md)
* Product: **aspnet-core**
* GitHub Login: @coderandhiker
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@dougbu 	we should add some comments on lifetime. Can you supply them?

**Comment by dougbu** [comment]
Perhaps @Tratcher or @davidfowl knows off-hand. I would have to research things in repositories I'm not that familiar with.

**Comment by Tratcher** [comment]
The lifetime doesn't matter since it uses a static AsyncLocal to flow the actual state.
https://github.com/aspnet/AspNetCore/blob/5116838807783a5beaf76a8a12e5faedb15a4f2d/src/Http/Http/src/HttpContextAccessor.cs#L10

**Comment by Tratcher** [comment]
Note AddHttpContextAccessor registers it as a singleton.
