### ISSUE TITLE
Adding a Controller Doesn't Appear to Work UNLESS You Stop and Restart Your Project

### ISSUE THREAD

**Issue by DougAtPeddle** [aspnet/Docs#9710]
Following this tutorial, step-by-step on macOS High Sierra (10.13.6) and Visual Studio for Mac Community (7.6.11), when I choose "ASP.NET Core Web App (MVC)" in the previous step ("Get started") in order to differentiate from "ASP.NET Core Web App" (with Razor Pages content), the resulting app runs fine.  However, the new "HelloWorldController" is not recognized after it is added and results in "This localhost page can’t be found No webpage was found for the web address: https://localhost:5001/HelloWorld HTTP ERROR 404" UNLESS/UNTIL the solution is stopped and restarted.  Trying to figure out why I'm not seeing my changes has cost me almost a day.  Please update your documentation.  This may seem obvious, but in other development environments, restarting after every change isn't necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c006d2b-2524-9693-3b4d-adb056e10079
* Version Independent ID: 5ac28d08-55eb-0d48-641a-841573333f92
* Content: [Add a controller to an ASP.NET Core MVC app with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-mac/adding-controller?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-mac/adding-controller.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-mac/adding-controller.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Did you try stepping into the  new controller in the debugger?

**Comment by DougAtPeddle** [comment]
Thanks, Rick.  The issue doesn't seem to be affected by the debugger in any
way.  If you stop and restart the project (with or without debugging), the
new controller works like a charm.  If you simply add the new controller to
the running project without stopping and restarting it, the controller
isn't recognized at all.  It's like it doesn't exist.

I'm not saying that this is wrong or needs to be changed, but I think it's
important that the documentation point out the need to stop and restart
before your changes will be visible.

**Comment by Rick-Anderson** [comment]
Running without debugger to debugger or vice-versa stops/starts the process. Folks generally run without debugger.  The tutorial states:

In Visual Studio, select Run > Start Without Debugging to launch the app.

When you have a problem, you fire up the debugger.

**Comment by tollycoast** [comment]
I have a problem understanding the solution. From the tutorial, I can see you have "Controllers and Views" folders but I don't have it on my own. I have Pages, Properties and wwwroot. I am a newbie to programming
