### ISSUE TITLE
Port not listening when using ServiceUser

### ISSUE THREAD

**Issue by jrswenson** [aspnet/Docs#9717]
When I run the service as ServiceUser, the ports aren't open/listening.  If I run the service as my logon that is an admin, everything works as expected.  I've verified that the icacls grant has set the permissions on the directory and files.  Seems like ServiceUser is missing permissions to open a port for listening.

Anyone else see this behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.1)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@Tratcher

**Comment by Tratcher** [comment]
Have you collected logs from the service to confirm the actual error? It may be a config issue.

Are you using Kestrel or HttpSys?

What port?

**Comment by jrswenson** [comment]
Thanks for the quick response.  I narrowed it down to just the HTTPS.  I removed app.UseHttpsRedirection(); from the Configure() and HTTP works as expected.  Since I'm using the localhost cert, I'm not going to worry about getting the service user working until I have an actual cert.

Thanks again.  Other than this hiccup, I was able to follow this tutorial very easily.

**Comment by Tratcher** [comment]
Yeah, the dev cert doesn't work for services, it's in your local user store.

**Comment by guardrex** [comment]
We have a quick line in the topic on it ...

> Use of the ASP.NET Core HTTPS development certificate to secure a service endpoint isn't supported.

... and I removed the secure bits on the PR that we just set up ...

https://github.com/aspnet/Docs/pull/9667/files#diff-cdbd5855aec082c316fdb8bdb8cfe342

We should be ok going forward. 🤞 I'll close now. Thanks @jrswenson for contacting us.
