### ISSUE TITLE
sqlite library?

### ISSUE THREAD

**Issue by ghkamfung** [aspnet/Docs#9724]
What sqlite library is required for this code to run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb01c6a-6aa4-23b8-c9d9-a37ef752cba8
* Version Independent ID: beb22f38-bebd-5e85-2517-a8ba8455360d
* Content: [Work with SQLite in an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/working-with-sql?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/working-with-sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/working-with-sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by hishamco** [comment]
Simply what you need is add reference to this package `Microsoft.EntityFrameworkCore.Sqlite`
