### ISSUE TITLE
[Question] [Razor Class Library] Is it possible to copy the RCL dlls in a web app's bin folder to have access to them?

### ISSUE THREAD

**Issue by AdrienTorris** [aspnet/Docs#9725]
I made a sample with two Razor Class Libraries modules with pages accessible by the urls '/module1' and '/Module2'. Then I created a new project with only a Web Application, then I copied the RCL dlls from my first sample web app's bin folder to the second one and I expected to can access to my RCLs by the same urls than the first sample, '/module1' and '/Module2', but it's not working.

Did I miss something? Or is it a security lock to prevent attacks like 'I copy my RCL's dll into a not-owned website's bin folder and it's 'magically' add some functionalities to this website without the owner consent'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fd019c7-ceb7-6ef3-26ba-6b44341b6fc5
* Version Independent ID: fd116d00-0dc7-efaf-c714-34d77b345a05
* Content: [Reusable Razor UI in class libraries with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/razor-pages/ui-class.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/ui-class.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@AdrienTorris 	can you get it working with one RCL?

**Comment by Rick-Anderson** [comment]
You can have multiple RCLs. Identity is delivered in an RCL. See [Referencing Razor Class Library content](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-2.1&tabs=visual-studio#referencing-razor-class-library-content)
