### ISSUE TITLE
Can't fork this project from your GitHub

### ISSUE THREAD

**Issue by JeffgLiu** [aspnet/Docs#9738]
Hi Rick. In your GitHub page 
https://github.com/aspnet/Docs/tree/master/aspnetcore/razor-pages/filter/sample/PageFilter
I clicked fork. This project I forked doesn't have "Docs / aspnetcore / razor-pages". It only has "Docs / aspnetcore ". Can you please look into this? Thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0646a3d-a5d1-d4b0-5494-fe38219d16c9
* Version Independent ID: 8b659e63-93b8-a496-bc9b-dce0d9fa8f3c
* Content: [Filter methods for Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-ca/aspnet/core/razor-pages/filter?view=aspnetcore-2.1)
* Content Source: [aspnetcore/razor-pages/filter.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/razor-pages/filter.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@JeffgLiu The TOC moved things around quite a bit over time. Your local fork must be behind some of those TOC changes. You're probably a bunch of commits behind the master branch. You can update your fork or you can just delete your fork and then re-fork the repo. That should get you the sample at that location. I'm going to close but we can re-open if we need to discuss further.
