### ISSUE TITLE
update "Migrating Authentication and Identity"

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#974]
[Migrating Authentication and Identity](https://docs.asp.net/en/latest/migration/identity.html)

- [ ] Update namespace from NewMvc6Project
- [ ]  Provide guidance - it would be helpful if you provided guidance for migrating the data to the new ASP.NET Core Identity SQL schema.  Similar guidance was provided for the migration from ASP.NET Membership to ASP.NET Identity: (create a new issue after fixing 1)

**Comment by Rick-Anderson** [comment]
#1476
:shipit:

**Comment by isaac2004** [comment]
@Rick-Anderson is this still up-for-grabs

**Comment by Rick-Anderson** [comment]
@scottaddie is this issue still open? If so, it's up for grabs.

**Comment by scottaddie** [comment]
This is still up for grabs. We should probably use something like "NewCoreMvcProject" for the namespace.

**Comment by isaac2004** [comment]
@scottaddie @Rick-Anderson since it seems like the whole migration section needs a reconfigure, maybe we add another doc to list provided by @danroth27 in #4237 and close this issue. New Doc would be regarding moving from ASP.NET Identity to new Context Providers. Thoughts?

**Comment by danroth27** [comment]
Looks like my list in #4237 was missing a migration topic for migrating from ASP.NET Identity to ASP.NET Core Identity. I've now added that. @isaac2004 does that cover the topic you wanted added, or were you thinking of something else? I'm not sure what you meant by the "new Context Providers".

**Comment by isaac2004** [comment]
@danroth27 no idea why I said context provider. Someone asked for some guidance on migration to new Core identity Schema and that isn't really documented. A section in the identity doc would suffice. I was curious about consolidating issues.

**Comment by isaac2004** [comment]
@danroth27 I think the issue people are having is on the data side. For instance they have some app using Membership and they want to migrate to Core Identity. There is that doc to go from Membership to ASP.NET Identity and I wonder if another migration doc from ASP.NET to ASP.NET would suffice, or a straight Membership to ASP.NET Core would be more beneficial. This doesn't even take into account 1.x vs 2.x on the Core side. Regardless I can put it together, just want to make sure the right things are being targeted

**Comment by isaac2004** [comment]
@danroth27 please advise

**Comment by danroth27** [comment]
@blowdart should probably weigh in on what he'd like to see here, but I think having a doc for migrating directly from Membership to ASP.NET Core is probably what we want.

**Comment by isaac2004** [comment]
pinging @blowdart for guidance

**Comment by blowdart** [comment]
Agreeing with @danroth27. Damn, that hurts.

**Comment by isaac2004** [comment]
@blowdart @danroth27  So in agreement that a migration doc from ASP.NET Membership to ASP.NET Core 2.0 Identity is needed for this. This doc would show the code changes needed, the changes needed to the DB schema, and some SQL script to migrate the data from the Membership Schema to Core Identity Schema. Would that suffice?

**Comment by blowdart** [comment]
Membership isn't MVC5 and 6, that's just older identity stuff. @HaoK shouldn't that be done with migrations?

**Comment by isaac2004** [comment]
Correct me if I am wrong, but isn't that the ask, getting from the really old Membership DB to Core Identity? Apologies if I misunderstood something

**Comment by blowdart** [comment]
Oh? In that case, yea, that'll be painful, but fun. And no-ones password will work any more :)

**Comment by isaac2004** [comment]
Oh that is an interesting point, is the Hashing mechanism for PW between ASP.NET Identity and Core Identity different? There is a [Membership to ASP.NET Identity](https://docs.microsoft.com/en-us/aspnet/identity/overview/migrations/migrating-an-existing-website-from-sql-membership-to-aspnet-identity) doc out there, so I assumed that the Membership to Core Identity process would be somewhat similar

**Comment by isaac2004** [comment]
Well you are probably going to have to review the doc, so I might as well make your life easier. :) Is there a recommended approach to force the user to reset password (or will they force since it is blank in DB)?

**Comment by blowdart** [comment]
I don't believe you can force it unfortunately. Set it to a random value and then document "All your users need to be emailed to say they must reset their password as part of the migration to improve security. Please don't use Hunter2" :)

**Comment by isaac2004** [comment]
Thanks Barry I will start putting together the skeleton for this based on the Membership to Identity Doc, same format mostly, different steps

**Comment by blowdart** [comment]
Enjoy, I appreciate you doing this, it's a horrible task.

**Comment by isaac2004** [comment]
Hey @blowdart odd question for you. I am going through building this doc and ran across something that may need to be looked at.

Using the default Identity template, the login screen is requesting the email address. This works fine for situations where the username and email are the same, but if they are different, it fails login. The reason for this is that SignInManager doesn't actually check the email, it checks UserName. So in the following scenario

UserName: Isaac
Email: isaac@foo.com

I will never be able to log into the app, since the service will never find a user with the username as the email address. The MVC template forces you to use email in this case, but it should really be username. Again in normal cases, this is fine since by default they are the same. But if they aren't the user may get confused.

**Comment by blowdart** [comment]
Oh god please document that. We have an outstanding bug to fix it, but it won't be in 2.1 in all probability. 

https://github.com/aspnet/Identity/issues/1721
https://github.com/aspnet/Identity/issues/1688
https://github.com/aspnet/Identity/issues/1675

**Comment by isaac2004** [comment]
@blowdart i added it to that doc on membership migration but probably should be put somewhere in the Identity docs no?
