### ISSUE TITLE
No error to debug tag helper rendering

### ISSUE THREAD

**Issue by LucaGabi** [aspnet/Docs#9753]
Hi,

After creating a viewcomponent I used the tag helper notation to render in view: 
&lt;vc:bread-crumb&gt;&lt;/bread-crumb&gt; and it dose not work. If I use the @await Component.InvokeAsync("BreadCrumb") it dose work. How to debug the problem ?

I added @addTagHelper *, &lt;assemblyName&gt; in _ViewImports.cshtml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62cdbf88-1fff-6999-f75a-26fbe730b911
* Version Independent ID: bc48b5cb-d500-f75d-8e48-be4d069a9198
* Content: [Tag Helpers in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.1#managing-tag-helper-scope)
* Content Source: [aspnetcore/mvc/views/tag-helpers/intro.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/intro.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by scottaddie** [comment]
@LucaGabi Do you have a simple project I can see that reproduces the problem?

**Comment by KSib** [comment]
<vc:bread-crumb></bread-crumb> wouldn't work for anyone. It should be <vc:bread-crumb></vc:bread-crumb>

**Comment by scottaddie** [comment]
@KSib You are correct. See the following doc for more info: https://docs.microsoft.com/aspnet/core/mvc/views/view-components#invoking-a-view-component-as-a-tag-helper.
