### ISSUE TITLE
Errors occurs while executes the command "npm run release"

### ISSUE THREAD

**Issue by imeya** [aspnet/Docs#9754]
When executes the command "npm run release", the following error occurs:

```
> PM&gt; npm run release
> npm : npm ERR! path C:\Users\leiyang\source\repos\SignalRChat\package.json
> At line:1 char:1
> + npm run release
> + ~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (npm ERR! path C...at\package.json:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> npm ERR!
>  
> code
>  ENOENT
> 
> npm
>  ERR! errno -4058
> 
> npm
>  
> ERR!
>  
> syscall
>  open
> 
> npm
>  ERR! 
> enoent
>  ENOENT: no such file or directory, open 'C:\Users\leiyang\source\repos\SignalRChat\package.json'
> 
> npm
>  ERR! enoent This is related to npm not being able to find a file.
> npm ERR! 
> enoent
> npm
>  
> ERR!
>  A complete log of this run can be found in:
> npm ERR!
>      C:\Users\leiyang\AppData\Roaming\npm-cache\_logs\2018-11-30T07_53_48_451Z-debug.log
> 
> PM&gt; 
> 

```
---

Screenshot as below:

![error-signal](https://user-images.githubusercontent.com/25738099/49276602-ec933e80-f4b9-11e8-99ab-f276adb043d7.JPG)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-2.1&tabs=visual-studio#create-the-aspnet-core-web-app)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* GitHub Login: @ssougnez
* Microsoft Alias: **scaddie**

**Comment by tdykstra** [comment]
The error seems to indicate package.json is missing.  That's a file you create and edit earlier in the tutorial.  My suggestion is to restart the tutorial, and make sure you do the steps in the **Configure Webpack and TypeScript** section, which has you create the file and edit it twice. Then make sure it still exists for the npm run release command.

**Comment by daveabrock** [comment]
In this case, I believe this is happening because the package manager is being initialized in the root of the solution, not the project. If you `cd` into the project, you should be able to run it. I will have a PR that will resolve this.
