### ISSUE TITLE
Sounds great 

### ISSUE THREAD

**Issue by zanate4019** [aspnet/Docs#9757]
Are there a new verisons of the Visual Studio and CLI project templates coming that take advantage of it?  My team is pretty new to .Net Core and it would be great to have consistency between the ASP.NET and other templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5f1eeee-d500-82bf-0d0a-b4e0d5d5c175
* Version Independent ID: 2373a3df-6ea3-50c7-d63d-61c51d572511
* Content: [.NET Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1)
* Content Source: [aspnetcore/fundamentals/host/generic-host.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/host/generic-host.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@zanate4019 Thanks for commenting.

The deciding factor right now (and as far as we know from engineering guidance for 2.2) is to use the Web Host for web-based workloads. Use either Web Host or Generic Host for non-web-based workloads. Therefore, the answer is 'no' right now for the templates. You should see the templates shift to the Generic Host at 3.0 next year.

At 3.0, the doc guidance should shift as well to *use Generic Host for everything*. Web Host will still be around (supported) at 3.0, but there will be a shift in guidance.

That's the plan based on the latest info we have from engineering. Plans are subject to change of course, but this is what we know today.

**Comment by guardrex** [comment]
@scottaddie btw - This was opened (apparently) from the topic, but the `Source - Docs.ms` label wasn't automatically added to the issue.

**Comment by zanate4019** [comment]
Fair enough.  I look forward to seeing it.

**Comment by guardrex** [comment]
Me, too. The Generic Host 🎸 *ROCKS!* 🎷

I'll close now. We can re-open if further discussion is required.
