### ISSUE TITLE
Add repo with just source code of tutorial.

### ISSUE THREAD

**Issue by dto81** [aspnet/Docs#9763]
It's easier to follow tutorials with larger scope if you can open whole project in one window and follow tutorial in second.
It's very inconvenient to jump back and forth to look up code from previous page or two pages back because current page deals with something I read before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673ec314-1f96-4448-27ba-3f6da655da26
* Version Independent ID: d15a8516-89e7-fd22-4ecb-b4eda61cb6ff
* Content: [Create an ASP.NET Core MVC app with Visual Studio Code](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app-xplat/?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/first-mvc-app-xplat/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app-xplat/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
You can download the code, although currently you need to download everything.

This is being reviewed at a much higher level.

**Comment by Rick-Anderson** [comment]
@SyntaxC4-MSFT do we have a issue tracking this request?

**Comment by Rick-Anderson** [comment]
@SyntaxC4-MSFT @dend  do we have a issue tracking this request?
This is a frequent complaint - you need to download the entire repo to get a sample.

**Comment by Rick-Anderson** [comment]
Closing because this is not a https://github.com/aspnet/Docs issue.
