### ISSUE TITLE
secure user data

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#977]
Start with old version on ACOM https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-deploy-aspnet-mvc-app-membership-oauth-sql-database/
tie data to user,  a user can Create/Update/Delete their data, anyone can Read data

**Comment by danroth27** [comment]
Sounds good.

**Comment by Rick-Anderson** [comment]
https://github.com/Rick-Anderson/secureMvc is the MVC5 version of what I'll be doing.

**Comment by Rick-Anderson** [comment]
@danroth27 I'm starting on this while I wait for PR feedback. It will be pretty much  ACOM https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-deploy-aspnet-mvc-app-membership-oauth-sql-database/ - but then in the next step I make it so users can only Create/Edit/Delete their own data. 

You've already approved this but I just want to double check because it's a old school tutorial, not the new ref type. I think we need to do it as a tutorial. It was the most popular tutorial on ACOM. The ACOM version is missing the critical step of  user data changes checked by authentication/authorization.

**Comment by Rick-Anderson** [comment]
I've got all the code written for this and 1/3rd of the doc. I'll finish this right after RTM.

**Comment by Rick-Anderson** [comment]
https://github.com/aspnet/Docs/pull/1780 fixes this
