### ISSUE TITLE
[SignalR] Add Java streaming support

### ISSUE THREAD

**Issue by hugo-boser** [aspnet/Docs#9771]
hey

any idea of when streaming support will be available?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e954a77-daa3-980c-0a0b-c4e7dabc8ed0
* Version Independent ID: 09e7b88b-8373-89d4-7360-d71370c095da
* Content: [ASP.NET Core SignalR Java client](https://docs.microsoft.com/en-us/aspnet/core/signalr/java-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/java-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/java-client.md)
* Product: **aspnet-core**
* GitHub Login: @mikaelm12
* Microsoft Alias: **mimengis**

**Comment by Rick-Anderson** [comment]
@bradygaster 	 	please respond

**Comment by bradygaster** [comment]
Created issue in product repo [here](https://github.com/aspnet/SignalR/issues/3343). Will leave this open add docs when the feature is ready.

**Comment by gunnerparag** [comment]
Need a hubProxy for the library can some one please help me out here

**Comment by bradygaster** [comment]
correction on the above link. Java server-to-client streaming is here: https://github.com/aspnet/SignalR/issues/2927

client-to-server streaming, which we're trying to ship in our 3.0 release, is here: 
https://github.com/aspnet/AspNetCore/issues/7151
