### ISSUE TITLE
Update base dir approach in Windows Service topic

### ISSUE THREAD

**Issue by Sigvaard** [aspnet/Docs#9774]
> The current working directory returned by calling GetCurrentDirectory for a Windows Service is the C:\WINDOWS\system32 folder. The system32 folder isn't a suitable location to store a service's files (for example, settings files).

A working directory is C:\WINDOWS\system32 for services. Wouldn't simpler fix be to use `Directory.SetCurrentDirectory`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Host ASP.NET Core in a Windows Service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @Sigvaard ... Thanks for commenting.

@Tratcher Stick with what we have ...

```csharp
var pathToExe = Process.GetCurrentProcess().MainModule.FileName;
var pathToContentRoot = Path.GetDirectoryName(pathToExe);
builder.UseContentRoot(pathToContentRoot);
```

... or go with something akin to https://github.com/aspnet/Hosting/issues/771#issuecomment-288502073?

**Comment by Tratcher** [comment]
Hmm, we've been debating something similar over at https://github.com/aspnet/AspNetCore/issues/4206. @shirhatti @jkotalik 
So far I see `Path.GetDirectoryName(pathToExe);`, `Directory.GetCurrentDirectory()` `AppDomain.CurrentDomain.BaseDirectory`...

Do we have anything that would get you the right answer in all of our scenarios?

**Comment by jkotalik** [comment]
@pakrym is investigating this right now.

**Comment by guardrex** [comment]
Tracking [Backport the current directory fix to 2.2.x (aspnet/AspNetCore 4599)](https://github.com/aspnet/AspNetCore/issues/4599) for the 2.2.x fix. Unless I hear otherwise from engineering, the doc will retain the current approach for 2.1. Let's use this issue to track the update.

**Comment by guardrex** [comment]
@pakrym I just looked at the code again that will report the correct base dir for ANCM-hosted apps ... it's not a fix for the scenario here. What would you like to do, if anything, here? To my :eye:, this does look neater (at least) :point_right: https://github.com/aspnet/Hosting/issues/771#issuecomment-288502073.

**Comment by pakrym** [comment]
I wasn't really investigating current directory in Windows Services, just ANCM. We didn't come up with a full solution for services yet.
