### ISSUE TITLE
Update article with bundle on build information

### ISSUE THREAD

**Issue by Joerdwa** [aspnet/Docs#9775]
Might be worth mentioning the 'enable bundle on build' option (available through the mentioned vsix) to integrate bundling as part as the dotnet build task as shown in the latter half of section 'BUILD TIME MINIFICATION' in the following link:
https://www.hanselman.com/blog/OptionsForCSSAndJSBundlingAndMinificationWithASPNETCore.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f55e9a-cd3f-83a0-f142-969dc10d3ceb
* Version Independent ID: f6845f70-1ac6-2036-f213-a3b665b3d8bf
* Content: [Bundle and minify static assets in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/bundling-and-minification.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/bundling-and-minification.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
That blog is about 2 years old.

**Comment by Joerdwa** [comment]
I’ll admit it is an old article. However, the enable bundle on build could still be useful if considering CI support. 

The read me of the actual extension might a bit more up to date: 

https://github.com/madskristensen/BundlerMinifier/blob/master/README.md

**Comment by scottaddie** [comment]
@Joerdwa That **Enable bundle on build** menu item simply does what's described at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification#build-time-execution-of-bundling-and-minification.

**Comment by Joerdwa** [comment]
@scottaddie So it does, my mistake. Feel free to close the issue as the ‘Enable Bundle On Build’ menu item doesn’t add anything here. Thanks for the clarification.
