### ISSUE TITLE
Multiple IMyScopedService 

### ISSUE THREAD

**Issue by bdaniel7** [aspnet/Docs#9779]
What happens when there are multiple IMyScopedService? Is the the system able to differentiate bewteen two implementations of one interface?
UsersController -&gt; UsersService : IService
ProfileController -&gt; ProfileService : IService

public async Task Invoke(HttpContext context, IService theService)
{
  theService ---&gt; always the same service.
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9898482c-fa54-7ce2-1716-d14fbe03990d
* Version Independent ID: 3926c686-0ccc-f9fe-ca52-0134612a1623
* Content: [ASP.NET Core Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-2.1#write-middleware)
* Content Source: [aspnetcore/fundamentals/middleware/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/middleware/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Do you mean multiple implementations of `IMyScopedService`? If so, you'd need to disambiguate them.

**Comment by bdaniel7** [comment]
Well, my understanding was that the middleware can receive an IService, injected at runtime.
When I post to UsersController, the UserService is instantiated, then sent to the middleware, as IService.
When I post to ProfileControlle, the ProfileService is instantiated, then sent to the middleware, as IService.
The middleware is executed at each request, receiving the correct IService.
I can use IEnumerable<IService> services as parameter of the Invoke method, and set the information to all services, but I think it's an ugly workaround.
By the time the software reaches production, there will be around 30 services, that will be iterated on each request.

So the problem is not that I need to disambiguate them, the problem is that only one IService implementation is injected into the middleware.

**Comment by Rick-Anderson** [comment]
@dougbu 	please review.

**Comment by Rick-Anderson** [comment]
@dougbu please review.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
