### ISSUE TITLE
Missing Prerequisite in Docs/mvc/getting-started/first-mvc-app/adding-model.rst

### ISSUE THREAD

**Issue by dylenbrandon** [aspnet/Docs#978]
Please include instructions or a prerequisite for SQL database. As a newcomer, I had a hard time using "dnx ef database update" because the tutorial didn't mention that I needed to install database software.  I understand that the context may have implied the fact that a database is required but it can be troublesome for newcomers if it isn't explicitly specified.

**Comment by danroth27** [comment]
Did you not have VS installed? The Web tools come with LocalDB, so you shouldn't need to install anything else.

**Comment by blogcraft** [comment]
Could the VS installation be a custom one and therefore Web Tools where not installed?

**Comment by danroth27** [comment]
But then the rest of the tutorial wouldn't work as it makes heavy use of VS Web tooling features.

**Comment by dylenbrandon** [comment]
I installed VS 2015 as per the instructions on the tutorial. I was able to finish everything up until "Use data migrations to create the database". SQL was not installed (I wasn't instructed to install it) so the "dnx ef database update" command failed. I was able to figure it out but this was a rather annoying experience for a first time ASP.NET developer.

**Comment by danroth27** [comment]
@dylenbrandon Do you remember the error you saw? 

I don't think you should need to install anything beyond what the VS Web tools give you to complete this tutorial. Adding @rowanmiller to confirm.

**Comment by rowanmiller** [comment]
Correct, you should get LocalDb as part of installing VS2015

**Comment by dylenbrandon** [comment]
@danroth27 It was a SQL connection error. @rowanmiller, I was also under the impression that LocalDB would install with VS2015. Strange issue.

**Comment by danroth27** [comment]
@dylenbrandon if you can reproduce the problem and send us the error we can take a look, but you shouldn't need to install anything beyond Visual Studio to run through this tutorial. I'm going to go ahead and close this issue as there really isn't anything concrete to change in the doc at this point. Let us know though if you get more details and we will investigate.
