### ISSUE TITLE
Update RP tutorial to meet content model guidelines

### ISSUE THREAD

**Issue by tdykstra** [aspnet/Docs#9780]
Update this initially to new advanced tutorial standards, then decide if it or the web API tutorial is the better candidate for an A/B test.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f32b67-7418-7f82-c813-c11650bb39a7
* Version Independent ID: 3e28328b-9c7a-359b-2f57-319b0bc7eea3
* Content: [Create a Razor Pages web app with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/index?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The first two parts of RP are much shorter/easier to go through. I think the reason we're getting low completion on the TOC is that's too hard. This will be much easier.

**Comment by tdykstra** [comment]
We chose a different tutorial for the A/B test.
