### ISSUE TITLE
How do Add "public void ConfigureServices(IServiceCollection services)"

### ISSUE THREAD

**Issue by tollycoast** [aspnet/Docs#9782]
I am following the material, immediately after the json file for connection, there is pane below with the following code 

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        // This lambda determines whether user consent for non-essential cookies is needed for a given request.
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

    services.AddDbContext<MovieContext>(options =>
        options.UseSqlite(Configuration.GetConnectionString("MovieContext")));
    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

With no explanation where to add it or what name to call it and under which folder will it reside? Please help out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa70bd9-d52a-8b71-4f56-abf4b53c5ca1
* Version Independent ID: 99c9a3fe-747c-160e-0a57-421426202506
* Content: [Add a model to an ASP.NET Core Razor Pages app with Visual Studio for Mac](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages-mac/model?view=aspnetcore-2.1)
* Content Source: [aspnetcore/tutorials/razor-pages-mac/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages-mac/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@tollycoast if you can hold on another day I've totally rewritten this tutorial. It will be published tomorrow.

**Comment by tollycoast** [comment]
Ok thanks about that

**Comment by tollycoast** [comment]
I am able to locate the file in Startup.cs but when I right click on the "MovieContext" -> Quick Fix I got different options with none resembling "using RazorPagesMovie.Models". I am sorry, I am bothering, I just want to learn
