### ISSUE TITLE
Have Error: <CopyRefAssembliesToPublishDirectory> beneath element <Project> is unrecognized

### ISSUE THREAD

**Issue by avsanin8** [aspnet/Docs#9792]
Have Error: &lt;CopyRefAssembliesToPublishDirectory&gt; beneath element &lt;Project&gt; is unrecognized
and my project is gone

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0f562-bdf0-eeea-f076-0c3e05222f75
* Version Independent ID: 8269d917-3b32-1607-71da-c756d4d7ad32
* Content: [Migrate from ASP.NET Core 2.0 to 2.1](https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1)
* Content Source: [aspnetcore/migration/20_21.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/20_21.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @avsanin8 ... Put that property inside of a `<PropertyGroup>` in the project file. I'll update the instruction to make that clear. Thanks for mentioning it.

Regarding "my project is gone," I don't understand.

**Comment by avsanin8** [comment]
Yes, thanks, I was wrong, I deleted this line - a project has appeared, you can close the topic

**Comment by guardrex** [comment]
We can leave this open. The issue will automatically close when the PR merges.

**Comment by avsanin8** [comment]
Ok, Could you tell me what to do if there was such an error: "
Severity Code Description Project File Line Suppression State
Error NU1202 Package WebApi.OData 0.5.0 is not compatible with netcoreapp2.1 (.NETCoreApp, Version = v2.1). Package WebApi.OData 0.5.0 supports: 40full (40-Full, Version = v0.0) MvcStore I: \ _ GitHub \ WebStoreAbstract \ CoreMVCStore \ MvcStore \ MvcStore \ MvcStore.csproj 1

**Comment by guardrex** [comment]
I don't recognize that package, but would this one be better for a Core app :point_right: https://www.nuget.org/packages/Microsoft.AspNetCore.OData/
