### ISSUE TITLE
Migrating Existing HTTP Modules to ASP.NET 

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#98]
ASP.NET 5 -> Migration -> Migrating Existing HTTP Modules to ASP.NET

**Comment by danroth27** [comment]
Let's do this as a blog post + sample

**Comment by joelmartinez** [comment]
Just curious if this ever got published, as the `done` label was added on aug 28th last year :)

**Comment by danroth27** [comment]
Not done - sorry about that. But a community contributor is working on an article for this. See #905.

**Comment by joelmartinez** [comment]
@danroth27 totally cool, I understand, good docs take time and resources :) I was just commenting cause I caught the link to this issue from the aspnet docs site.
