### ISSUE TITLE
dotnet tool install -g Microsoft.Web.LibraryManager.Cli gives an error: The tool package could not be restored.

### ISSUE THREAD

**Issue by semuserable** [aspnet/Docs#9810]
# Issue description

Running `dotnet tool install -g Microsoft.Web.LibraryManager.Cli` gives the following error

<details>
<summary>Error message</summary>
The tool package could not be restored.
Tool 'microsoft.web.librarymanager.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
</details>
</br>
but if I run it with a version specified (taken from nuget.org), it's got installed with no problems

`dotnet tool install -g Microsoft.Web.LibraryManager.Cli --version 1.0.163`
</br>

Should this info be updated on https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr?view=aspnetcore-2.2&tabs=visual-studio-code page?

# Software versions

<details>
<summary><strong>dotnet --info output</strong></summary>

```console
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

**Comment by scottaddie** [comment]
I've confirmed that this command does work properly without specifying the version. Closing this issue, but feel free to reopen if you experience this issue again.

**Comment by semuserable** [comment]
I just deleted it ant tried to install without version specified, but I still get the same error. Maybe you need some additional info from my side?
