### ISSUE TITLE
page specific JavaScript and CSS

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Docs#9814]
See #2002

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29734d0-2d2b-3b82-0456-785cc7f361fd
* Version Independent ID: ab07129c-a4dd-44de-45f9-4b49eff0b54c
* Content: [Layout in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/layout?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/views/layout.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/layout.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@daveabrock 	should I close this?

**Comment by daveabrock** [comment]
@Rick-Anderson Yes, I would. Sorry for the delay in responding to this.

**Comment by Rick-Anderson** [comment]
NP - thanks for all your help.
