### ISSUE TITLE
Migration paths for deprecated ILoggerFactory extension methods

### ISSUE THREAD

**Issue by jansokoly** [aspnet/Docs#9829]
Creating a project targeting ASP.NET Core 1.0 (and possibly others) used to add the following to `Configure()` method in `Startup.cs`:
```
loggerFactory.AddConsole(Configuration.GetSection("Logging"));
loggerFactory.AddDebug();
```
Those 2 methods are marked as deprecated in ASP.NET Core 2.2. How to properly migrate this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@jansokoly You can safely remove these 2 lines of code. As of ASP.NET Core 2.0, this code runs when calling `CreateDefaultBuilder` from `Program.Main`. See https://github.com/aspnet/MetaPackages/blob/586d641934e997045ed98b1978684a7b0c607b39/src/Microsoft.AspNetCore/WebHost.cs#L182-L184.
