### ISSUE TITLE
asp-area

### ISSUE THREAD

**Issue by BrettBock** [aspnet/Docs#9834]
Provide an example using asp-area

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc429b-11d9-c0f6-678d-dfb22e23c273
* Version Independent ID: 61eb6984-18c3-2bb1-db35-62735a0b24a4
* Content: [Anchor Tag Helper in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-2.2#asp-page)
* Content Source: [aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/views/tag-helpers/built-in/anchor-tag-helper.md)
* Product: **aspnet-core**
* GitHub Login: @pkellner
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@BrettBock I'm trying to better understand what you're looking for here. Did you already look at the doc's sample app's *Views/Home/Index.cshtml* file?

**Comment by BrettBock** [comment]
Looking for an anchor example that can be used to reference a razor page that is in an area.  I was able to just use an href, e.g. "/area/controller/action", but was not able to get this working with any of the asp anchor tags.  asp-page indicates that it is mutually exclusive to several tags, but asp-area is not include.
