### ISSUE TITLE
No mention of hosting model

### ISSUE THREAD

**Issue by BennieCopeland** [aspnet/Docs#9835]
This does not mention adding "AspNetCoreHostingModel" to the csproj. Does it default to the prior "out of process" hosting if not set? The documentation is also not clear on whether the new "in process" module made it in the 2.2 ANCM, and if there is still the "one application per application pool" limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Thanks @BennieCopeland ... It just hasn't gone live yet. It should appear sometime today.

https://github.com/aspnet/Docs/pull/9809

> still the "one application per application pool" limitation.

Yes, same guidance as before ... one app per app pool.
