### ISSUE TITLE
Should also explain CompatibilityVersion.Latest

### ISSUE THREAD

**Issue by MathiasRonnblom** [aspnet/Docs#9836]
I'm missing an explanation of the enum value CompatibilityVersion.Latest, and its risks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bcb541d-c695-99f6-dde7-f01d0d9307d5
* Version Independent ID: 9585545a-9047-85ff-6117-ddd07ef6ee46
* Content: [Compatibility version for ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/compatibility-version.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/mvc/compatibility-version.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@MathiasRonnblom 	thanks. I hope it's obvious.  Now that we're at 2.2 and their won't be a later 2.x version, lastest can't go higher than 2.2.

This should be documented by the first 3.0 preview.
