### ISSUE TITLE
incomplete/incorrect example code

### ISSUE THREAD

**Issue by f2calv** [aspnet/Docs#9838]
the code snippet under "Connect to a hub" is incomplete/wrong, it ends with;
"async function start() {"
??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf283c9-5cd2-a9ff-b8c8-372d8a04356d
* Version Independent ID: 729fddcf-24e4-b563-4952-a8045b231868
* Content: [ASP.NET Core SignalR JavaScript client](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-2.2#connect-to-a-hub)
* Content Source: [aspnetcore/signalr/javascript-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/javascript-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@f2calv Thanks for reporting that - I'll fix it.

**Comment by bradygaster** [comment]
Got this fixed today. Thanks for letting us know.

**Comment by guardrex** [comment]
Fixed by https://github.com/aspnet/Docs/pull/9870.
