### ISSUE TITLE
Namespaces Are Missing

### ISSUE THREAD

**Issue by Grauenwolf** [aspnet/Docs#9843]
Most of the examples require importing namespaces which are not listed in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#create-logs)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Thanks @Grauenwolf ... I'll take care of it.

**Comment by Rick-Anderson** [comment]
@Grauenwolf 	you can download the sample code to get help with the namespace.
