### ISSUE TITLE
Update for current release

### ISSUE THREAD

**Issue by Grauenwolf** [aspnet/Docs#9844]
None of the configuration examples matches the code found in the current ASP.NET Core template used by Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7184a308-a254-9350-a5cd-5bced1f369ae
* Version Independent ID: 726e3bf1-f367-d733-8933-bccc04da0e16
* Content: [Logging in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#create-logs)
* Content Source: [aspnetcore/fundamentals/logging/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/logging/index.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
@Grauenwolf ... It's somewhat common across the repo for a few reasons. For one thing, the sample apps trail the framework releases. Another is that samples concentrate on the concepts that the topics cover, which often don't strictly require the app to follow the template conventions. In this case (logging), the common thread is just hanging the `ConfigureLogging` method calls off of the host builder ... that's the same pattern regardless of the 2.x flavor.

I'll mark this issue on the sample update tracking issue. The doc author who takes on the 2.2 updates for this sample will see this at that time. Thanks for commenting on the topic.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
