### ISSUE TITLE
Why is RequestHeader in its own virtual host?

### ISSUE THREAD

**Issue by DedicatedManagers** [aspnet/Docs#9851]
Why is the RequestHeader set in its own Virtual Host?   
Also, that separate virtual host seems to apply to all interfaces and ports, so does this affect other non-proxy domains (ie. regular websites served via apache) on the server?

&lt;VirtualHost *:*&gt;
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
&lt;/VirtualHost&gt;

&lt;VirtualHost *:80&gt;
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:5000/
    ProxyPassReverse / http://127.0.0.1:5000/
    ServerName www.example.com
    ServerAlias *.example.com
    ErrorLog ${APACHE_LOG_DIR}helloapp-error.log
    CustomLog ${APACHE_LOG_DIR}helloapp-access.log common
&lt;/VirtualHost&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **spboyer**

**Comment by guardrex** [comment]
@shirhatti

**Comment by shirhatti** [comment]
This version of the doc sets up virtual hosts that bind to all host names. You wouldn't do that on a server where you have other non-proxy sites hosted and won't be able to use our provided config in the docs verbatim

**Comment by guardrex** [comment]
@shirhatti No action to take here, correct?

**Comment by DedicatedManagers** [comment]
@shirhatti  Thanks for your response.  

Your config has the "ServerName" directive, so it does not bind to all host names. In your example, its only binding to "www.example.com"

It also desn't seem to make sense that you'd bind the "RequestHeader" to 443 as the virtual host for the proxy isn't listening on that port.

From what I'm hearing it sounds like I can put the "RequestHeader" in with the other directives in one single VirtualHost.

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.

**Comment by guardrex** [comment]
Hello @TimPurdum ... This issue is closed. Please open your request from the bottom of the Linux on Apache topic using the **Content feedback** button. https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-apache#feedback
