### ISSUE TITLE
Tutorial Mentions Startup.cs as important

### ISSUE THREAD

**Issue by richard-lee-morris** [aspnet/Docs#9852]
" At this point in the tutorial, the Startup.cs file is the most important to understand." But the tutorial left me hanging. There was no elaboration or link to more info. Wazzup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the doc

Startup.cs | Configures services and the request pipeline. See Startup.
-- | --
