### ISSUE TITLE
How to leverage Managed Service Identity in ASP.NET Core configuration provider for Azure Key Vault?

### ISSUE THREAD

**Issue by EdBlankenship** [aspnet/Docs#9854]
If we have an Azure App Service that has a managed service identity with permissions to the Key Vault instance, how do we configure the ASP.NET Core app to leverage that managed service identity instead of needing the three values of "Vault", "ClientId", and "ClientSecret"?

This article doesn't touch on that scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cc0b77a-df21-7007-5cec-4399d98c6dc6
* Version Independent ID: efe5ae5e-ff64-f1c7-6920-4512fc8f36d1
* Content: [Azure Key Vault configuration provider in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2)
* Content Source: [aspnetcore/security/key-vault-configuration.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/key-vault-configuration.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @EdBlankenship ... this is a dup of https://github.com/aspnet/Docs/issues/7380. We've been 🏃🏃🏃🏃🏃😅 for the 2.2 release lately. Now that we'll be getting past this batch of 2.2 issues in the next few days/few weeks, I think we'll get to this fairly soon.

@scottaddie If you're loaded and would like to hand off #7380, assign it to me. I have a cycle or two prior to the end of the contract that I might be able to use to knock it out.

@EdBlankenship I'm going close as a dup. If you have further remarks, please post them on #7380.
