### ISSUE TITLE
Guidance For Adding Identity To WebApi

### ISSUE THREAD

**Issue by danacon01** [aspnet/Docs#9862]
I cannot find in the docs anywhere that talks about adding authentication to a web api, it is all focused on web apps/mvc.

What is the best practice recommendation for adding auth to a web api? Should I use identity for this?
I have seen lots of articles talking about using JWT, but I don't know if that is a generic approach or only appropriate for certain situations.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Scaffold Identity in ASP.NET Core projects](https://docs.microsoft.com/en-gb/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Dup of #4556
