### ISSUE TITLE
Provide workaround for base dir when hosting in-process

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9865]
> `Directory.GetCurrentDirectory()` returns the worker directory of the process started by IIS rather than the application directory (for example, C:\Windows\System32\inetsrv for w3wp.exe).

@Tratcher The base dir question was just asked on the 2.2 RTM blog Q&A. Can I add a note to the end of this to surface `AppDomain.CurrentDomain.BaseDirectory` as a suitable way to go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe69b3a9-896f-e189-0c2c-f87ff735df9c
* Version Independent ID: 97c8549b-66ad-0a23-1971-784fb923042a
* Content: [ASP.NET Core Module configuration reference](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/aspnet-core-module.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/aspnet-core-module.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by Tratcher** [comment]
@shirhatti @pakrym @jkotalik

**Comment by pakrym** [comment]
`AppDomain.CurrentDomain.BaseDirectory` doesn't work when debugging project in VS because it point to the `bin` directory instead of project directory.

**Comment by pakrym** [comment]
This is what I came up with:

``` C#
    internal class CurrentDirectoryHelpers
    {
        internal const string AspNetCoreModuleDll = "aspnetcorev2_inprocess.dll";

        [System.Runtime.InteropServices.DllImport("kernel32.dll")]
        private static extern IntPtr GetModuleHandle(string lpModuleName);

        [System.Runtime.InteropServices.DllImport(AspNetCoreModuleDll)]
        private static extern int http_get_application_properties(ref IISConfigurationData iiConfigData);

        [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
        private struct IISConfigurationData
        {
            public IntPtr pNativeApplication;
            [System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.BStr)]
            public string pwzFullApplicationPath;
            [System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.BStr)]
            public string pwzVirtualApplicationPath;
            public bool fWindowsAuthEnabled;
            public bool fBasicAuthEnabled;
            public bool fAnonymousAuthEnable;
        }

        public static void SetCurrentDirectory()
        {
            try
            {
                // Check if physical path was provided by ANCM
                var sitePhysicalPath = Environment.GetEnvironmentVariable("ASPNETCORE_IIS_PHYSICAL_PATH");
                if (string.IsNullOrEmpty(sitePhysicalPath))
                {
                    // Skip if not running ANCM InProcess
                    if (GetModuleHandle(AspNetCoreModuleDll) == IntPtr.Zero)
                    {
                        return;
                    }

                    IISConfigurationData configurationData = default(IISConfigurationData);
                    if (http_get_application_properties(ref configurationData) != 0)
                    {
                        return;
                    }

                    sitePhysicalPath = configurationData.pwzFullApplicationPath;
                }

                Environment.CurrentDirectory = sitePhysicalPath;
            }
            catch
            {
                // ignore
            }
        }
    }
```

**Comment by guardrex** [comment]
I can place the code in the topic's asset folder and only link to it (i.e., not display it in the topic). Is that ok?

... I'll stand-by on the other one for guidance :point_right: https://github.com/aspnet/Docs/issues/9774

**Comment by pakrym** [comment]
@guardrex I'm fine having just a link but I'd like to clear it with @shirhatti first.

**Comment by guardrex** [comment]
I'll wait for your signal to proceed.

**Comment by shirhatti** [comment]
LGTM

**Comment by alexandrejobin** [comment]
Will this workaround be integrated in the Aspnet Core 2.2.x or we will have to use it internally in our apps?

**Comment by pakrym** [comment]
We are going to port the actual fix to 2.2.x

**Comment by alexandrejobin** [comment]
Great, thank you very much!

**Comment by guardrex** [comment]
Is there an engineering issue yet that I can track on for the doc update?

**Comment by pakrym** [comment]
https://github.com/aspnet/AspNetCore/issues/4599
