### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by AngelusB** [aspnet/Docs#9868]
I'm quit new to Asp.Net ( 2 days)
This tutorial  is great.  Unfortunately no success in getting correct decimal input at field Price. (country NL) . Nor dot nor comma is working . I changed to en-Us with  "var defaultCulture = new CultureInfo("en-US"); etc. Now I can work with decimal dot.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Add search to ASP.NET Core Razor Pages](https://docs.microsoft.com/nl-nl/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per the tutorial - see https://github.com/aspnet/Docs/issues/4076
