### ISSUE TITLE
KeyPerFile Configuration Provider delimiter content

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9875]
> I was trying to integrate the KeyPerFileConfigurationProvider into our code and could not figure out what the syntax/structure that the files needed to be based on the documentation. It seems like the delimiter required is the same as for environment variables, two underscores, so can this be added to the documentation and possibly with an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Configuration in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@HaoK Headcheck: Colons can't be used in file names, so double underscores in the file name for the Key-per-file provider end up becoming colons in the key when the provider runs. Is that correct?

... and if so ... is that what the OP is asking about? :point_up: Hard to grok the "syntax/structure that the files needed to be" part. Not sure how to interpret that.

**Comment by HaoK** [comment]
Yeah I'm guessing its related to that, the filename is used as the key, so its limited to file name characters, and I guess this issue is just asking that we describe the key normalization (__ -> :)

https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.KeyPerFile/src/KeyPerFileConfigurationProvider.cs#L22
