### ISSUE TITLE
Missing sample code snippet - Webpack Dev Middleware

### ISSUE THREAD

**Issue by dliabenow** [aspnet/Docs#9889]
# Issue description

Missing sample code snippet from Webpack Dev Middleware - **Configuration** section.

[https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2#webpack-dev-middleware](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa-services.md#configuration-1)

Also missing the code sample in the Routing  **Configuration** section.

[https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2#routing-helpers](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa-services?view=aspnetcore-2.2#routing-helpers)

**Comment by guardrex** [comment]
Hello @dliabenow ... Take a look at the live topic. Code samples don't render on the GH previews of the docs.

https://docs.microsoft.com/aspnet/core/client-side/spa-services

**Comment by guardrex** [comment]
My bad ..... I see it. I'll fix it up. Thanks for letting us know @dliabenow.
