### ISSUE TITLE
Add Information on the bahavior of chaining methods in the policy builder

### ISSUE THREAD

**Issue by TrieBr** [aspnet/Docs#9892]
For example:
```
services.AddAuthorization(options =>
    {
        options.AddPolicy("AtLeast21", policy =>
            policy.AddRequirements(new MinimumAgeRequirement(21)).RequireRole("admin");
    });
```

Is this an AND operation, or an OR operation (eg the user must be 21 AND an admin, or must be 21 Or an admin)? Is there anyway to explicitly define an AND or an OR operation for multiple requirements?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1141d92-adeb-6841-229f-914c808f9a2b
* Version Independent ID: 7089b376-949f-c1c6-c37a-5d8cc7ecf104
* Content: [Policy-based authorization in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2#requirements)
* Content Source: [aspnetcore/security/authorization/policies.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authorization/policies.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @TrieBr ... It's of the "and" variety. The [RequireRole](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authorization.authorizationpolicybuilder.requirerole) adds a requirement to the AuthorizationPolicyBuilder.

> define an AND or an OR operation for multiple requirements

Did you see the section that pertains to "or"-type policies :point_right: https://docs.microsoft.com/aspnet/core/security/authorization/policies#why-would-i-want-multiple-handlers-for-a-requirement

**Comment by guardrex** [comment]
I'm closing as answered, but we can re-open if you would like to discuss further.
