### ISSUE TITLE
Create an ASP.NET Core app with user data protected by authorization

### ISSUE THREAD

**Issue by scatman255** [aspnet/Docs#9894]
The Button never Shows

```
@if (Model.Contact.Status != ContactStatus.Approved)
{
    @if ((await AuthorizationService.AuthorizeAsync(
     User, Model.Contact, ContactOperations.Approve)).Succeeded)
    {
        <form style="display:inline;" method="post">
            <input type="hidden" name="id" value="@Model.Contact.ContactId" />
            <input type="hidden" name="status" value="@ContactStatus.Approved" />
            <button type="submit" class="btn btn-xs btn-success">Approve</button>
        </form>
    }
}
```
# Issue description

In the Detail Page the Approve or Rejected Button never comes up
The is Authorized always false

Software
VS2019
.Net Core 2.1

Tested first with the own Code an then with your final source files 2.1

Best 

Olli

**Comment by guardrex** [comment]
Hello @scatman255 ... We recommend opening a docs issue from the bottom of the topic. Use the **Content feedback** button so that we know which topic+sample goes with the issue.

I think you're looking at the following, correct?

https://docs.microsoft.com/aspnet/core/security/authorization/secure-data

**Comment by guardrex** [comment]
Looks like it's missing an instruction. In order for the seeding to work, a password must be supplied via the Secret Manager Tool **_before_** starting the steps at ...

https://docs.microsoft.com/aspnet/core/security/authorization/secure-data#test-the-completed-app

1. Delete any users you've created out of the app.

1. From the project's folder, execute the following command with a password following normal password guidelines ... for example ...

   ```console
   dotnet user-secrets set SeedUserPW Password1!
   ```

1. Run the app.

1. Login with `admin@contoso.com` and that password. Now, you should be able to see those buttons when you go to edit a user that you've added.

I'll make some quick updates to that section. Thanks for commenting @scatman255.
