### ISSUE TITLE
getting - Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list using IIS

### ISSUE THREAD

**Issue by msinghm** [aspnet/Docs#9897]
I am trying to write a 'web API with ASP.NET Core' app, but after deploying it on IIS getting 
below error

**HTTP Error 500.21 - Internal Server Error
Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list**

**Comment by guardrex** [comment]
Hello @msinghm ... looks like you don't have the hosting bundle installed on the server.

See :point_right: https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#install-the-net-core-hosting-bundle

I'll close as answered. I think you'll find everything you need in the docs to proceed. Let us know if you run into any trouble with any of the hosting and deployment topics.

**Comment by msinghm** [comment]
Thanks so much Luke Latham, I am able to fix the issue using your reply.

**Comment by pantonis** [comment]
@guardrex I installed [.net core hosting bundle](https://www.microsoft.com/net/permalink/dotnetcore-current-windows-runtime-bundle-installer), restarted pc but I am still getting the same error. 

Thanks

**Comment by guardrex** [comment]
@pantonis Navigate to ...

```
%ProgramFiles%\IIS Express\Asp.Net Core Module\V2\
```

Do you see the ancm v2 there? ...

<img width="391" alt="capture" src="https://user-images.githubusercontent.com/1622880/51129554-5fe5db00-17f0-11e9-820e-c127adb5fc02.PNG">

**Comment by pantonis** [comment]
It was resolved after I updated VS2017 to latest version

**Comment by shadinamrouti** [comment]
Just for info: 
Installing [the hosting bundle 2.2.1](https://download.visualstudio.microsoft.com/download/pr/5ee633f2-bf6d-49bd-8fb6-80c861c36d54/caa93641707e1fd5b8273ada22009246/dotnet-hosting-2.2.1-win.exe) solved the problem. 
The SDK is not enough although it contains the runtime, however, I think it's not registering the module V2 correctly on the server's OS.

**Comment by yoqueuris** [comment]
I was trying to host my **.Net Core 2.2** app in IIS (Local) and got same message.

Even though I had .Net Core SDK 2.2 I got that error message.

Installing **.NET Core 2.2 Runtime & Hosting Bundle** solved my issue. I only had Hosting Bundle 2.1 version installed.

**Comment by stevenlupo** [comment]
I get this exact message, yet I'm publishing it with the --self-contained option using the CLI. If installing the hosting bundle solves the problem, doesn't this mean by definition that it's **_not_** self contained?

I did not install the hosting bundle yet because I'm looking for a self-contained application.

**Comment by guardrex** [comment]
The app is self-contained but still requires the ASP.NET Core Module for IIS. You can run the hosting bundle  installer with switches that will prevent the runtime install. See the IIS Overview topic for details.

**Comment by AKlaus** [comment]
> The app is self-contained but still requires the ASP.NET Core Module for IIS. 
@guardrex, doesn't it contradict to the definition of being self-contained?..

**Comment by guardrex** [comment]
@AKlaus "Self-contained" in the context of a .NET Core app just means that the app contains the .NET Core libs and runtime. It doesn't extend more broadly than that. The alternative, framework-dependent, requires a shared framework on the host. And note that self-contained doesn't include native dependencies on the host, so it really often requires even more than just the ANCM to run properly.

See the .NET Core app deployment doc for details :point_right: https://docs.microsoft.com/dotnet/core/deploying/.

**Comment by roboriaan** [comment]
Is there a solution when publishing to a hosting provider that doesn't allow installing anything. I have to change AspNetCoreModuleV2 to AspNetCoreModule after every publish. I've tried to prevent the web.config from changing without success.

**Comment by guardrex** [comment]
@roboriaan See the `<IsTransformWebConfigDisabled>` property ....

https://docs.microsoft.com/aspnet/core/host-and-deploy/iis/#webconfig-file

... and include your own custom *web.config* file in the project's content root (alongside the project file). On publish, it should move the file into your published output for deployment. It won't change your custom *web.config* file settings when it moves the file.
