### ISSUE TITLE
Migrating from ASP.NET Identity 2.x to 3.x

### ISSUE THREAD

**Issue by danroth27** [aspnet/Docs#99]
ASP.NET 5 -> Migration -> Migrating from ASP.NET Identity 2.x to 3.x

**Comment by danroth27** [comment]
@rustd @HaoK Can you guys provide an outline of what you want documented here?

**Comment by rustd** [comment]
https://github.com/aspnet/Identity/issues/682

**Comment by isaac2004** [comment]
@danroth27 Is this something that is still needed?

**Comment by danroth27** [comment]
@blowdart should make the call on this one.

**Comment by blowdart** [comment]
By 3 you mean Core 2 right?

See https://github.com/aspnet/Docs/pull/5889

**Comment by isaac2004** [comment]
@blowdart No this is an issue about upgrading versions of ASP.NET Framework Identity versions.

**Comment by blowdart** [comment]
Oh if it's old framework to old framework no, but from old framework to new framework, if intermediate steps are needed then yes.

**Comment by isaac2004** [comment]
@danroth27 close?

**Comment by danroth27** [comment]
This issue dates back to the ASP.NET 5 days, when ASP.NET Core Identity was still ASP.NET Identity 3. So this issue is about documenting how to migrate form ASP.NET Identity to ASP.NET Core Identity. Do we already have that covered?

**Comment by isaac2004** [comment]
@danroth27 that PR that @blowdart linked has that. I repurposed the whole migration node.
