### ISSUE TITLE
This doesn't work until binding redirect is added to app.config.

### ISSUE THREAD

**Issue by orloffm** [aspnet/Docs#9906]
&lt;dependentAssembly&gt;
        &lt;assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" /&gt;
        &lt;bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" /&gt;
      &lt;/dependentAssembly&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bc1072-be2c-94f6-49bf-daa9e97dff2d
* Version Independent ID: 36052173-7061-6d01-8aed-915685cd7cf6
* Content: [ASP.NET Core SignalR .NET Client](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.2)
* Content Source: [aspnetcore/signalr/dotnet-client.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/dotnet-client.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
@orloffm That binding redirect is in the sample app, but when I remove it the app works fine.  Do you have the same experience with the sample app?  If so, how does your project differ from the sample app?

**Comment by orloffm** [comment]
I assume it was some glitch in my VS, I don't have other explanation. It was reliably affecting the outcome a week ago, but now everything just works whatever I do with app.config. Probably some package was updated in meantime? So I'm closing this. Thanks.
