### ISSUE TITLE
SingleOrDefaultAsynch should be FindAsync

### ISSUE THREAD

**Issue by LeonhardPrintz** [aspnet/Docs#9907]
This documentation makes a small mistake. The method used to look up a movie in the Edit method isn't SingleOrDefaultAsync but simply FindAsync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 582aeaf8-770f-6861-ab47-bb6a4f2206e4
* Version Independent ID: 51894773-82dc-3c71-f675-8af42cfa925f
* Content: [Controller methods and views in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/controller-methods-views.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/controller-methods-views.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @LeonhardPrintz ... This is a dup of https://github.com/aspnet/Docs/issues/4737 ... and see the linked issue at https://github.com/aspnet/Scaffolding/issues/649.

**Comment by guardrex** [comment]
Re-opening ... the text (paragraph) above doesn't match the code sample (below). It also doesn't match the convo result from the linked issues; therefore, I assume a shift in the scaffolder logic occurred.

> The `HttpGet Edit` method takes the movie `ID` parameter, looks up the movie using the Entity Framework `SingleOrDefaultAsync` method

```csharp
// GET: Movies/Edit/5
public async Task<IActionResult> Edit(int? id)
{
    if (id == null)
    {
        return NotFound();
    }

    var movie = await _context.Movie.FindAsync(id);
    if (movie == null)
    {
        return NotFound();
    }
    return View(movie);
}
```
