### ISSUE TITLE
Client-Side Validation does not work.

### ISSUE THREAD

**Issue by LeonhardPrintz** [aspnet/Docs#9912]
Following this tutorial, it seems client-side validation is not working as of 2018-12-9. Opening the source of the generated Movies/Edit page, I can see that no jquery-validation is loaded at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443a7c53-cc16-7ed5-5950-46a6f195f19c
* Version Independent ID: 12fe9329-2cef-4056-4986-18ed7ae5c397
* Content: [Add validation to an ASP.NET Core MVC app](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/validation?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/first-mvc-app/validation.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mvc-app/validation.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by LeonhardPrintz** [comment]
I found out that this has to be added to the bottom of each view that requires validation.

```
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}
```

**Comment by guardrex** [comment]
Hello @LeonhardPrintz ... Did you walk *all* all of the steps of the tutorial, including the [Controller methods and views](https://docs.microsoft.com/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.2) topic earlier in the tutorial? If so, it should've been handled by the scaffolding system for the Edit view for the Movie class (scroll down about halfway in that topic where it shows the view, and you'll see it shown there). If you did walk those steps and scaffolding didn't generate a view with the script ref, then this might be a 2.2 scaffolding bug 🐞. If that's the case, I'll try to repro it here and then we can take filing a bug report with the engineers from there.

**Comment by LeonhardPrintz** [comment]
Its hard to say if I caused a bug by setting something improper. I have been following the tutorial step by step.

```
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
```

This also works. Whatever the reason this partial just wasn't included in the Create.cshtml Razor page generated by the scaffolding.

**Comment by guardrex** [comment]
I checked. Following the instructions in [Add a model to an ASP.NET Core MVC app](https://docs.microsoft.com/aspnet/core/tutorials/first-mvc-app/adding-model), scaffolding produces the view for the Movie class with the correct `Scripts` section ...

```cshtml
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
```

I'll close, since the tutorial seems ok. We can re-open if you wish to discuss further.
