### ISSUE TITLE
Inconsistency between instructions and sample code.

### ISSUE THREAD

**Issue by sjetha** [aspnet/Docs#9915]
In the "Configure Routing" section, the instructions say that we should add attributes to the controller and the controller's method, but the same code only shows attributes on the controller.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f83a3b4-28f6-5f0f-a8bf-aef76f05fe42
* Version Independent ID: 0d0bc32b-5909-580f-1030-edbf1d3d9a68
* Content: [Migrate from ASP.NET Web API to ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/migration/webapi?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/webapi.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/webapi.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
Hello @sjetha ... Yes, it was a prior-to-2.1 (or 2.0) scenario. Given that there's no sample for versions earlier than 2.1, I think the whole topic can go 2.1+ with those lines removed.

@scottaddie I have a branch set up with updates to cover this but won't submit a PR unless u say to.
