### ISSUE TITLE
Scaffolding tool creates a second DB Context and causes error in migrations

### ISSUE THREAD

**Issue by Jazzwall** [aspnet/Docs#9916]
``dotnet aspnet-codegenerator razorpage -m Movie -dc MovieContext -udl -outDir Pages/Movies --referenceScriptLibraries``

The "-dc" option creates a new context class.  And then the instructions for migrations hits an error as it doesn't know which context class to use.  Please revise the text here to reflect this reality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Jazzwall 	I think I see the problem. The instructions should have you create `RazorPagesMovieContext`
You can see that in the VS Mac tab.

Thanks for pointing that out. 
cc @tdykstra
