### ISSUE TITLE
cannot find 

### ISSUE THREAD

**Issue by RFrancis10** [aspnet/Docs#9917]
cannot find ASP.NET Core Web Application in the new project tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @RFrancis10 ... are you on a recent version of VS? It should look like ...

<img width="459" alt="capture" src="https://user-images.githubusercontent.com/1622880/49703868-2bb74300-fbd0-11e8-9c07-6e6e25762c30.PNG">

**Comment by RFrancis10** [comment]
I think so
I have just downloaded it

**Comment by guardrex** [comment]
... did you install the **ASP.NET and web development workload**? .... and you have the 2.2 SDK from https://dotnet.microsoft.com/download?

**Comment by guardrex** [comment]
That workload should give you 2.2 (one would think! lol) ...

<img width="389" alt="capture" src="https://user-images.githubusercontent.com/1622880/49703934-36260c80-fbd1-11e8-9f52-e6b753605ba2.PNG">

**Comment by RFrancis10** [comment]
downloading these but what is the web development workload ?

**Comment by RFrancis10** [comment]
Yes, now they are all downloaded but still no difference

**Comment by guardrex** [comment]
Use the taskbar search and search for "Visual Studio Installer" ... run it ... then click the "Modify" button. You'll get the workloads. Under **Web & Cloud**, you should see the **ASP.NET and web development** workload. Check that off and the installer should install the bits.
