### ISSUE TITLE
Why Microsoft.AspNetCore.SignalR.StackExchangeRedis?

### ISSUE THREAD

**Issue by wullemsb** [aspnet/Docs#9919]
In  this documentation you are referring to Microsoft.AspNetCore.SignalR.StackExchangeRedis where in fact there also exists another (official?) package Microsoft.AspNetCore.SignalR.Redis. Maybe at least mention the other package as an alternative?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c548355c-d88f-b941-0622-56732973123b
* Version Independent ID: bddd7575-422d-4342-af48-f6b0979fb69a
* Content: [Redis backplane for ASP.NET Core SignalR scale-out](https://docs.microsoft.com/en-us/aspnet/core/signalr/redis-backplane?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/signalr/redis-backplane.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/signalr/redis-backplane.md)
* Product: **aspnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment]
Thanks for pointing out that as something needing clarification.  I'm updating the article to explain that StackExchangeRedis is for 2.2 and later, and the other one is for 2.1.
