### ISSUE TITLE
db First

### ISSUE THREAD

**Issue by Griffin2** [aspnet/Docs#9925]
is there a way to do it db first? I find the code first messy, I dont enjoy seeding

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03221075-5dfa-d1b6-0552-3fe88abe1d03
* Version Independent ID: b8c7d824-35ca-68fb-e3be-839ae886657c
* Content: [Work with a database and ASP.NET Core](https://docs.microsoft.com/en-gb/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/sql.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/sql.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/49759815-ceba9c00-fc66-11e8-9faf-5a09748be32f.png)
