### ISSUE TITLE
IIS Deployment Guidance - 32-bit vs 64-bit

### ISSUE THREAD

**Issue by jhigh2000** [aspnet/Docs#9931]
Would it be possible to incorporate the latest guidance on using 32-bit vs 64-bit application pools in IIS for in-process hosting of asp.net core 2.2 applications? Current best-practice recommendations and a discussion around application requirements, performance, and efficiency/hosting density would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec484002-18c1-6a0d-00de-820d56f038d3
* Version Independent ID: 7903ce53-2cbb-f083-7479-c8abc30211a0
* Content: [Host ASP.NET Core on Windows with IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/iis/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/iis/index.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Thanks for commenting @jhigh2000.

@Tratcher @jkotalik We could add a *Platform* section to the topic. If so, I'd need to know what guidance you'd like to provide ... I can work from an outline or notes.

**Comment by Tratcher** [comment]
@shirhatti @pakrym

**Comment by shirhatti** [comment]
The guidance is ALWAYS use 32-bit unless
- You need larger virtual memory address space
- Need the larger IIS stack size
- Have 64-bit native dependencies
