### ISSUE TITLE
In Process and Auto Build on Browser Request Behavior

### ISSUE THREAD

**Issue by jhigh2000** [aspnet/Docs#9932]
Migrating the hosting model to In-Process changes the "auto build on browser request" behavior when saving .cs files.  With in-proc hosting, the project needs be built manually when the controller is modified, for example.  Since this is a change to the "Save and press F5 to reload" workflow, a mention of that would probably be helpful.

Note: I'm guessing the changed behavior this is not a bug and a consequence of using in-proc hosting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by guardrex** [comment]
@jhigh2000 See :point_right: [Browser Link in ASP.NET Core](https://docs.microsoft.com/aspnet/core/client-side/using-browserlink?view=aspnetcore-2.2)

Since this is more of a migration scenario to Core, it might be best for [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2).

**Comment by guardrex** [comment]
Note that Browser Link is covered in the topic that I linked ... a brief remark about it with a link. The link doesn't go to our topic tho. I'll add a link to our topic there.

**Comment by jhigh2000** [comment]
This is a change in behavior from 2.1 to 2.2 in-proc. 2.2 out of process has the same behavior.

**Comment by guardrex** [comment]
I didn't think Browser Link was ever a default scenario for the save-and-reload experience (or only briefly so in a prior version). The `Microsoft.VisualStudio.Web.BrowserLink` package isn't even in the `App` package. Browser Link is required either way, and it has to wired up manually via package reference and middleware add. There's no behavioral change between 2.1 and 2.2 that I'm aware of.&dagger;

&dagger;:smile: Let's ask @tdykstra ... he may encourage me not to operate my PC after taking so much **_cough syrup_**. lol ... I have a cold today. 🤧

**Comment by guardrex** [comment]
<img width="389" alt="capture" src="https://user-images.githubusercontent.com/1622880/49760153-47caeb00-fc89-11e8-91c5-3c1de41a8c27.PNG">

This is what happens when you spend **_TOO much time in VSC!_**

Hold on a sec while I see if there's a reported issue on it. brb

**Comment by guardrex** [comment]
@barrytang TL;DR ... Does the change to 2.2 IIS in-proc hosting possibly break the VS *auto build on browser request* scenario?

If it should be business-as-usual, then would you like @jhigh2000 to file a bug via *Report a problem*?

If we need to cover something in the migration topic for in-proc and this scenario, what do we need to cover?

**Comment by jhigh2000** [comment]
@DamianEdwards confirmed that this is by [design.](https://twitter.com/DamianEdwards/status/1072243504212897793)

Definitely think this deserves mention in the 2.1 to 2.2 migration docs and maybe even in some of the tutorials, since in-proc hosting is the default behavior with 2.2.

Thanks!

**Comment by guardrex** [comment]
Cool ... perfect ... I'll get that into the topic by EOD. Thanks for your issue and tracking down the info.
