### ISSUE TITLE
Update ASP.NET to ASP.NET Core topic

### ISSUE THREAD

**Issue by guardrex** [aspnet/Docs#9934]
It's about that time ⏰.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by isaac2004** [comment]
lol @guardrex… does just need to get updated to be 2.1? @scottaddie

**Comment by guardrex** [comment]
2.2

... and I'm inquiring with the team now on priority. Do you want to handle the updates?

**Comment by guardrex** [comment]
btw --- I just made a tiny change to repoint the Browser Link link to our topic. That's when I saw that it was getting a bit stale here and there.

**Comment by Rick-Anderson** [comment]
We don't update that topic. We update these

![image](https://user-images.githubusercontent.com/3605364/49758201-7a152200-fc62-11e8-824d-c319398f06bc.png)

cc @scottaddie 	@tdykstra

**Comment by guardrex** [comment]
I just thought that someone coming in for the first time to Core would get a head full of knowledge on **_what not to do_** if this isn't updated to latest.

**Comment by guardrex** [comment]
Maybe the answer is just to change the title to *ASP.NET to ASP.NET Core 2.0* ... that would make it really clear to the reader what they're getting.

**Comment by Rick-Anderson** [comment]
cc @scottaddie 	@tdykstra 	
I agree.

**Comment by scottaddie** [comment]
@guardrex *ASP.NET to ASP.NET Core 2.x* would be a more accurate title.

**Comment by guardrex** [comment]
It's not written for *any* flavor is it ... e.g. `All` package.

**Comment by scottaddie** [comment]
@guardrex All of the docs within this node were intended to target the latest stable release. We haven't had time to update them all. Consequently, there's a mix of 2.0, 2.1, and 2.2 content in there.

**Comment by guardrex** [comment]
I see what you mean ... it's a node name vs. topic name thing. However, the "Overview" topic link loads this topic with the name *Migrate from ASP.NET to ASP.NET Core*. It could still get "2.0" tacked on to it ... the topic is 2.0, and maybe a little misleading either left alone or with "2.x" on it. The node name can stay the same.

**Comment by scottaddie** [comment]
@isaac2004 If you're interested in helping out, this doc needs to be updated for 2.2.
