### ISSUE TITLE
Document web app extension functionalities

### ISSUE THREAD

**Issue by ggirard07** [aspnet/Docs#9935]
I can't find any information about the purpose of this site extension. I noticed it today in our webapps running ASP.Net Core WebAPI.

I found [this post](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-2.1) explaining that a new extension is required in order to install the preview of .Net Core 2.1 on an Azure Web App. But this does not allow me to understand why `ASP.NET Core Extensions` is installed on my web app.
My first idea was that .Net Core wasn't installed at all on an Azure Web App, but after creating a fresh one I was able to run the following comment without any extension:
```
              _    _____   _ ___ ___ 
             /_\  |_  / | | | _ \ __| 
       _ ___/ _ \__/ /| |_| |   / _|___ _ _ 
     (___  /_/ \_\/___|\___/|_|_\___| _____) 
        (_______ _ _)         _ ______ _)_ _ 
               (______________ _ )   (___ _ _) 

Manage your web app environment by running common commands ('mkdir', 'cd' to change directories, etc.) This is a sandbox environment, so any commands that require elevated privileges won't work.

D:\home\site\wwwroot
> dotnet --info
D:\home\site\wwwroot
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\2.1.101\


Microsoft .NET Core Shared Framework Host



  Version  : 2.0.6

  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

> 
```
I am pretty sure this extensions do way more than ensuring a specific version of .Net Core is installed...
Is it possible to add a bit of description to the repo `README.md`?
Or have it properly documented on Microsoft Docs?

I think this issue is also related https://github.com/aspnet/AzureIntegration/issues/161

**Comment by shirhatti** [comment]
> thanks for your link but this one only describe how to integrate ASP.Net Core logs to Application Insights. It does not explain what is the purpose of the extension neither why nor how to use it...

@ggirard07 	That's why the issue is still open- to track the remaining documentation work 😄

**Comment by guardrex** [comment]
@pakrym Making a doc update on the **ASP.NET Core Logging Extension**.

[Create a build configuraition to build OOB logging site extension package (aspnet/AspNetCore
 \#3643)](https://github.com/aspnet/AspNetCore/pull/3643)

It's named "ASP.NET Core Logging Extensions" but only a single service extension, so it seems a little strange when I write in the topic ...

> ... by the **ASP.NET Core Logging Extensions**. This extension enables ...

plural :point_right: singular mismatch

Second thing is the description:

> This extension enables additional functionality for ASP.NET Core on Azure WebSites, such as enabling Azure logging.

I might be wrong, but didn't "Azure WebSites" (naming) fall out-of-favor with marketing? Should it be "Azure Apps" or "Azure App Service"? I can make the doc state the description that way. If I should go that way, let me know if I should open an engineering issue for it (perhaps for the extension name, too :point_up:).

Last thing while I'm here ..... description is "such as" ... is there anything else you would like the Azure Apps topic to say about what this extension does besides supplying logging scenarios.

**Comment by pakrym** [comment]
@guardrex thank you, filed https://github.com/aspnet/AspNetCore/issues/4570 to fix all mentioned issues.

**Comment by guardrex** [comment]
@pakrym I'll doc it as it exists today and open a 3.0 docs issue attached to the engineering issue.

Should the description in the topic restate the description of the extension (for now)? If so, the updates to cover this are over on #9942.

**Comment by pakrym** [comment]
#9942 looks good but I think we should just say logging without such as. In the beginning we thought we might add more features to it that's why description was so vague but logging is the only thing it does.
