### ISSUE TITLE
Update to 2.2

### ISSUE THREAD

**Issue by ssardar22** [aspnet/Docs#9948]
Hi, I have followed the tutorial and have been able to get the web app to work however, the carousel slides and the rest of the content on the page doesn't show up. I can only see the homepage consisting of the welcome and learn more about... message. Selecting home takes me to the same screen and privacy takes me to the detail page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6139d4-022c-395a-0abf-539660550df1
* Version Independent ID: 3dd23f8a-300e-3f78-1dc5-8b759aabdccc
* Content: [Get started with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/getting-started/?view=aspnetcore-2.2&tabs=windows)
* Content Source: [aspnetcore/getting-started/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/getting-started/index.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @ssardar22 ... Are you using the latest (just released) 2.2 SDK? If so, they changed the template app quite a bit between releases. It doesn't look like the one shown in the image in the topic.

@Rick-Anderson If you'd like me to replace that image (and see if anything else needs attention), assign me, and I'll square it away on Tuesday.

**Comment by ssardar22** [comment]
I do have the latest version of the SDK (on windows) and I would appreciate it if you could update the necessary instructions, thanks.

**Comment by Rick-Anderson** [comment]
> the carousel slides and the rest of the content on the page doesn't show up.

There are no  carousel slides in the 2.2 templates. We need to update this page.

**Comment by Rick-Anderson** [comment]
@tdykstra 	do you have time to update this?

**Comment by Rick-Anderson** [comment]
@ssardar22 	I suggest you follow https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio

**Comment by tdykstra** [comment]
@Rick-Anderson I should be able to do that today.
