### ISSUE TITLE
2 mistakes in code

### ISSUE THREAD

**Issue by eyal7773** [aspnet/Docs#9954]
Hello,
Please fix these issues : 
1. in the Controller Delete method, 
the line that invoke service method need to use  the object "book" and not the id string.
like this : 
_bookService.Remove(book.Id);

2. In the controller post method create, if you want the "CreatedAtRoute" to work , so the function name of Action "GetBook" must also be "GetBook"
like this :
[HttpGet("{id:length(24)}",Name ="GetBook")]
        public ActionResult&lt;Book&gt; GetBook(string id)

if not - it will fail with error 500 "No route matches ....."

Thanks 
Eyal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5240866d-d0a1-f0dd-7b2c-203e1d69bc4b
* Version Independent ID: 83a5cb3b-23bc-4f0c-cd1c-1d1ffeb1131a
* Content: [Build web APIs with ASP.NET Core and MongoDB](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-2.2&tabs=visual-studio#add-a-crud-operations-class)
* Content Source: [aspnetcore/tutorials/first-mongo-app.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/first-mongo-app.md)
* Product: **aspnet-core**
* GitHub Login: @prkhandelwal
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
> in the Controller Delete method,
the line that invoke service method need to use the object "book" and not the id string.
like this :
_bookService.Remove(book.Id);

What problem are you encountering? I tested again with Postman, and it's working for me.

> In the controller post method create, if you want the "CreatedAtRoute" to work , so the function name of Action "GetBook" must also be "GetBook"
> like this :
> [HttpGet("{id:length(24)}",Name ="GetBook")]
> public ActionResult<Book> GetBook(string id)
> 
> if not - it will fail with error 500 "No route matches ....."

I tested this with Postman, and it's working for me. The Location header and 201 response are received:

![image](https://user-images.githubusercontent.com/10702007/49955094-9bc31300-fec7-11e8-8822-43e40bd6a49e.png)

**Comment by eyal7773** [comment]
you are right, I didn't saw that the Remove function in the service have 2 versions. Sorry, my mistake.
