### ISSUE TITLE
License files being published on docs

### ISSUE THREAD

**Issue by mairaw** [aspnet/Docs#9955]
These license files are being published on docs and being flagged on the metadata health report.
This should be addressed.

Pages include:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/rpmovepart3/wwwroot/lib/jquery-validation/license
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/rpmovienewfield/wwwroot/lib/jquery-validation/license
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/rpmovienewfield/wwwroot/lib/jquery-validation/license
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/rpmoviesearch/wwwroot/lib/jquery-validation/license

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe596dd-4ef1-142a-a61d-6dd4813b0e3e
* Version Independent ID: 9aa9a90f-f91d-87f1-fd0f-ee665b4106ab
* Content: [The MIT License (MIT)](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/rpmovepart3/wwwroot/lib/jquery-validation/license?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovePart3/wwwroot/lib/jquery-validation/LICENSE.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start/2.2-stage-samples/RPmovePart3/wwwroot/lib/jquery-validation/LICENSE.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson

**Comment by Rick-Anderson** [comment]
@mairaw 	do you know if they're being published because they don't have `/sample/` or `/samples/` in the path. 

The same jQuery license is not being published in all the other folders that have  `/sample/` or `/samples/` in the path. 

cc @tdykstra 	@scottaddie

**Comment by mairaw** [comment]
Missed your question earlier @Rick-Anderson. Yes, docfx.json excludes the samples and samples path. I did a small change. Let's see if that will fix the issue.
