### ISSUE TITLE
Shortcut key to toggle between a Razor Page and the PageModel

### ISSUE THREAD

**Issue by saeed-serpooshan** [aspnet/Docs#9959]
I have installed the latest VS2017 15.9.3, and the shortcut for ToggleRazorView is not F7, but it is Shift+F7. Either the document must be updated or the shortcut (I think F7 is simpler/better shortcut and i set it so, although i'm not sure if it is not conflicting by other features)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a25bf940-8977-fec4-461b-542a9f550fc8
* Version Independent ID: 5492c641-af15-64b8-beaa-ddf511be73e6
* Content: [Get started with Razor Pages in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/razor-pages-start?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/razor-pages/razor-pages-start.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/tutorials/razor-pages/razor-pages-start.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Somehow your settings got changed. It's F7
