### ISSUE TITLE
Sync .NET Core and ASP.NET Core Performance Recommendations

### ISSUE THREAD

**Issue by wadepickett** [aspnet/Docs#9969]
Doc performance recommendation updates for .NET Core are currently underway.  Verify the ASP.NET Core Performance content is in sync with those updates.
See .NET Core performance tracking issue:
https://github.com/dotnet/docs/issues/9532 

Target Version:  ASP.NET Core 2.2

**Comment by Rick-Anderson** [comment]
@wadepickett 	we did that from V 1.0
See [Introduction to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-2.2)

The PU just added a [perf node](https://docs.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-2.2)
