### ISSUE TITLE
Something has changed.

### ISSUE THREAD

**Issue by allen-brad** [aspnet/Docs#9975]
From Scaffold on down, something is different. Following these instructions:  https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2#scaffold-identity-into-a-razor-project-with-authorization

Does not result in the creation of Register, Login, and LogOut files. Authorization is working, but I can't even figure out where the content for those pages is coming from. Please clarify the instructions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* Content: [Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @allen-brad ... The *Scaffold Identity* topic might be linked somewhere in there ... not sure. It's at :point_right: https://docs.microsoft.com/aspnet/core/security/authentication/scaffold-identity ... that may answer your question about where the content is coming from.

**Comment by Rick-Anderson** [comment]
@allen-brad 	You need to scaffold Identity to see those files. See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization which explains that.

**Comment by allen-brad** [comment]
@Rick-Anderson , @guardrex 
Thanks for your reply. However, I'm not confident you really read what I wrote. I posted a URL to the scaffolding instructions. I followed the instructions to the letter and those pages were not generated. You guys both responded by giving me the same URL as I had originally posted. I've tested this in more than one project and I do think something is not working as intended.

**Comment by guardrex** [comment]
Yes ... sorry ... I *didn't* read carefully what you wrote. I scanned past the link assuming that it was just to a bookmarked section of the Identity topic.

@Rick-Anderson I can walk those steps here first thing Friday morning to see if I can repro what @allen-brad ran into. Would you like me to do that?

**Comment by Rick-Anderson** [comment]
@allen-brad 	I read what you wrote. What instructions are you following? What errors are produced? I recently went through it and it was working fine. We have over 21,000 PV in the last month and you're the only one reporting it not working. Are you looking in the right folder?

**Comment by Rick-Anderson** [comment]
@allen-brad 	if there's a problem with  docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization
open an issue on that page and tell us what's wrong.

**Comment by LouBH** [comment]
I created the project in Core 2.1 and had the same problem--Register, LogIn and LogOut files were not created.

**Comment by Rick-Anderson** [comment]
@LouBH  that's how it works. Read my responses to generate them.
