### ISSUE TITLE
Update launch.json

### ISSUE THREAD

**Issue by dcb99** [aspnet/Docs#9978]
It's probably worth mentioning that if the `program` key of configurations in launch.json references `netcoreapp2.1`, it should be changed to `netcoreapp2.2`. I missed that while upgrading, and it's not mentioned in release notes, and ran into some problems until I tracked that down. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46a10a5c-bacc-1bcf-a7ae-499715e1bfdd
* Version Independent ID: 1585163b-b1d7-eeb8-ebc6-adfc2730f393
* Content: [Migrate from ASP.NET Core 2.1 to 2.2](https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-2.2&tabs=visual-studio)
* Content Source: [aspnetcore/migration/21-to-22.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/21-to-22.md)
* Product: **aspnet-core**
* GitHub Login: @scottaddie
* Microsoft Alias: **scaddie**

**Comment by scottaddie** [comment]
@dcb99 You're correct that this needs to be updated. Thank you for pointing it out. I'll get it added to the doc today.

**Comment by dcb99** [comment]
Thanks @scottaddie. A coworker just pointed out that docs are also in source control. Next time I run across something like this I'll try and fix it myself.

**Comment by scottaddie** [comment]
They are indeed. We're happy to help if you have any questions about the contribution process.
