### ISSUE TITLE
Adding new courses to Department

### ISSUE THREAD

**Issue by paul000** [aspnet/Docs#9981]
There are a couple of lines of text in the add course assignments to the instructor ….
that say:
If the number of courses were much greater:
You'd probably use a different user interface to display the courses.
The method of manipulating a join entity to create or delete relationships wouldn't change.

I don't need a different user interface since a university may have thousands of courses, I would like to add courses by typing them in directly from the Department page (either from the department detail page or department edit page). The link would say "Add New Course" and when the add course form pops up the DepartmentID is automatically populated (or carried forward). What is the best way to do this? Should I do it with routing? 

Since I'm not populating a list or selecting a check box I'm not sure of the best method.

Paul Lynn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140ce637-4d58-995f-c69e-b1de51f1dbb5
* Version Independent ID: 9bc46ffa-60db-bdee-0984-fab183c8f503
* Content: [Razor Pages with EF Core in ASP.NET Core - Update Related Data - 7 of 8](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/update-related-data?view=aspnetcore-2.2#add-course-assignments-to-the-instructor-edit-page)
* Content Source: [aspnetcore/data/ef-rp/update-related-data.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/data/ef-rp/update-related-data.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Thanks for contacting us.
We don’t have the resources to invest in this area, so we are closing the issue. Should your request generate enough  👍 responses, we’ll reconsider.
