### ISSUE TITLE
Native dependency injection is not clear

### ISSUE THREAD

**Issue by haiduc32** [aspnet/Docs#9996]
Hi, I'm trying to figure out how to migrate the dependency injection and the section on "Native dependency injection" refers to HttpConfiguration which I can't find in a brand new Aps.Net Core 2.0 project. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1133d6d1-7801-654c-2b7c-dad2bb342501
* Version Independent ID: a7ccce22-f905-06f4-8847-b9eeaf534e1f
* Content: [Migrate from ASP.NET to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-2.2)
* Content Source: [aspnetcore/migration/proper-to-2x/index.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/migration/proper-to-2x/index.md)
* Product: **aspnet-core**
* GitHub Login: @isaac2004
* Microsoft Alias: **scaddie**

**Comment by Rick-Anderson** [comment]
See https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-2.2

**Comment by Rick-Anderson** [comment]
Also, the link in the article
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2
