### ISSUE TITLE
Apache2 Reverse Proxy with OpenID Connect result in a bad Request

### ISSUE THREAD

**Issue by mdemuynck** [aspnet/Docs#9997]
I used the setup as described above in combination with .net core. This works for most scenarios except when using in combination with OpenID connect. After the authentication, the result is:
Bad Request
Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
Apache/2.4.29 (Ubuntu) Server 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd9a1f0-c1b6-4443-0700-4c5beafeed03
* Version Independent ID: c22ca7a0-d1d4-200d-fc36-a9798d350c6e
* Content: [Host ASP.NET Core on Linux with Apache](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/linux-apache.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/host-and-deploy/linux-apache.md)
* Product: **aspnet-core**
* GitHub Login: @spboyer
* Microsoft Alias: **spboyer**

**Comment by guardrex** [comment]
I read online that Apache has a default of 8K (should be able to confirm with command: `getconf PAGESIZE`) and that it can be configured via `LimitRequestLine` and `LimitRequestFieldSize`. You should be able to set those for the virtual host. However, I'm merely looking at online resources and there are very likely security/perf issues, sooooo ........... drum roll plz 🥁 ........... ping @shirhatti

**Comment by mdemuynck** [comment]
Thank you guardrex. Adding LimitRequestFieldSize was the solution. The result from signin-oidc is 9.2 KB, so I guess adding this to the documentation would be nice.

**Comment by guardrex** [comment]
Cool.

We'll hear back from Sourabh soon.

If we're covering this scenario, he'll tell  me what the topic should say.

**Comment by shirhatti** [comment]
It's hard to give prescriptive guidance especially since the size of the header depends on the number of claims. I'd rather just mention you may need to increase the header size.

See https://github.com/aspnet/Docs/issues/8679 which is in similar vein where certain workloads requires change in configuration of your proxy and we have to be cognizant that we aren't going to cover all scenarios.
